import type { CorporationFormationOffice } from './types'
import type { G20SovereignMemberIsoCode } from './g20MemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per G20 sovereign member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const G20_CORPORATION_FORMATION_OFFICES: Record<G20SovereignMemberIsoCode, CorporationFormationOffice> = {
  AR:   office(
    'Public Registry of Commerce (IGJ Argentina)',
    '+54 11 4334 0450',
    'Av. Julio A. Roca 651, Buenos Aires, Argentina',
    'https://www.argentina.gob.ar/justicia/registro-nacional-sociedades',
    '',
    '',
    '',
    '',
    'https://www.argentina.gob.ar/justicia/registro-nacional-sociedades/tramites',
    'https://www.argentina.gob.ar/produccion/registrar-una-empresa',
    'CUIT (Clave Unica de Identificacion Tributaria)',
  ),
  AU:   office(
    'Australian Securities and Investments Commission (ASIC)',
    '+61 1300 300 630',
    'Level 5, 100 Market Street, Sydney NSW 2000, Australia',
    'https://asic.gov.au',
    '',
    'https://twitter.com/asicmedia',
    '',
    'https://www.linkedin.com/company/australian-securities-and-investments-commission/',
    'https://asic.gov.au/for-business/registering-a-company/',
    'https://business.gov.au/planning/new-businesses/register-a-company',
    'Australian Company Number (ACN)',
  ),
  BR:   office(
    'REDESIM / Junta Comercial (Brazil Business Registration)',
    '+55 61 2021 5000',
    'SAIN, Bloco I, Brasilia, Brazil',
    'https://www.gov.br/empresas-e-negocios',
    '',
    '',
    '',
    '',
    'https://www.gov.br/empresas-e-negocios/pt-br/empreendedor',
    'https://www.gov.br/empresas-e-negocios/pt-br/empreendedor/quero-empreender',
    'CNPJ (Cadastro Nacional da Pessoa Juridica)',
  ),
  CA:   office(
    'Corporations Canada (Innovation, Science and Economic Development)',
    '+1 866 333 5556',
    '235 Queen Street, Ottawa, ON K1A 0H5, Canada',
    'https://ised-isde.canada.ca/site/corporations-canada/en',
    '',
    '',
    '',
    '',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/incorporate-business-corporation',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/steps-incorporating',
    'Corporation Number',
  ),
  CN:   office(
    'State Administration for Market Regulation (Enterprise Registration)',
    '+86 10 8865 0000',
    'No. 8 Sanlihe East Road, Xicheng District, Beijing, China',
    'https://www.samr.gov.cn',
    '',
    '',
    '',
    '',
    'https://zwfw.samr.gov.cn',
    'https://www.gov.cn/fuwu/2015-12/09/content_5022390.htm',
    'Unified Social Credit Code',
  ),
  FR:   office(
    'Infogreffe / Guichet Unique France',
    '+33 892 680 271',
    'Paris, France',
    'https://www.infogreffe.fr',
    'contact@infogreffe.fr',
    '',
    '',
    '',
    'https://www.guichet-entreprises.fr',
    'https://www.guichet-entreprises.fr/creer-son-entreprise',
    'SIREN / SIRET Number',
  ),
  DE:   office(
    'Unternehmensregister (German Commercial Register)',
    '+49 30 187810',
    'Berlin, Germany',
    'https://www.unternehmensregister.de',
    'info@handelsregister.de',
    '',
    '',
    '',
    'https://www.unternehmensregister.de',
    'https://www.gruenderplattform.de',
    'Handelsregisternummer',
  ),
  IN:   office(
    'Ministry of Corporate Affairs India (MCA21)',
    '+91 11 2306 3386',
    '5th Floor, A Wing, Shastri Bhawan, New Delhi, India',
    'https://www.mca.gov.in',
    'helpdesk@mca.gov.in',
    '',
    '',
    '',
    'https://www.mca.gov.in/content/mca/global/en/mca/e-filing-services.html',
    'https://www.mca.gov.in/content/mca/global/en/acts-rules/ebooks/company-incorporation.html',
    'Corporate Identification Number (CIN)',
  ),
  ID:   office(
    'OSS Indonesia (Ministry of Investment/BKPM)',
    '+62 21 1500 123',
    'Jl. Jenderal Gatot Subroto No. 44, Jakarta, Indonesia',
    'https://oss.go.id',
    '',
    '',
    '',
    '',
    'https://oss.go.id',
    'https://www.bkpm.go.id/en/public-service',
    'Nomor Induk Berusaha (NIB)',
  ),
  IT:   office(
    'Registro Imprese (Chamber of Commerce Italy)',
    '+39 06 47041',
    'Via Carlo Alberto 16, Rome, Italy',
    'https://www.registroimprese.it',
    'info@registroimprese.it',
    '',
    '',
    '',
    'https://www.registroimprese.it',
    'https://www.infocamere.it/starting-a-business',
    'Codice Fiscale / REA Number',
  ),
  JP:   office(
    'Legal Affairs Bureau (Ministry of Justice Commercial Registration)',
    '+81 3 3580 4111',
    '1-1-1 Kasumigaseki, Chiyoda-ku, Tokyo, Japan',
    'https://www.moj.go.jp',
    '',
    '',
    '',
    '',
    'https://www.moj.go.jp/MINJI/minji06.html',
    'https://www.jetro.go.jp/en/invest/setting_up/section1/page3.html',
    'Corporate Number (Houjin Bango)',
  ),
  MX:   office(
    'Secretaria de Economia - Tu Empresa',
    '+52 55 5729 9100',
    'Av. Insurgentes Sur 1940, Mexico City, Mexico',
    'https://www.gob.mx/se',
    '',
    '',
    '',
    '',
    'https://www.gob.mx/tuempresa',
    'https://www.gob.mx/tramites/ficha/constitucion-de-sociedades/SRE2566',
    'Registro Federal de Contribuyentes (RFC)',
  ),
  RU:   office(
    'Federal Tax Service of Russia (State Registration)',
    '+7 495 913 0009',
    'Neglinnaya St., 23, Moscow, Russia',
    'https://www.nalog.gov.ru',
    '',
    '',
    '',
    '',
    'https://service.nalog.ru/gosreg',
    'https://www.nalog.gov.ru/rn77/yul/interest/reg_ur/',
    'OGRN',
  ),
  SA:   office(
    'Ministry of Commerce Saudi Arabia (Business Platform)',
    '+966 1900',
    'Riyadh, Saudi Arabia',
    'https://mc.gov.sa',
    '',
    '',
    '',
    '',
    'https://business.sa',
    'https://mc.gov.sa/ar/eservices/Pages/default.aspx',
    'Commercial Registration (CR) Number',
  ),
  ZA:   office(
    'Companies and Intellectual Property Commission (CIPC South Africa)',
    '+27 86 100 2472',
    'the dti Campus, 77 Meintjies Street, Sunnyside, Pretoria, South Africa',
    'https://www.cipc.co.za',
    'info@cipc.co.za',
    'https://x.com/theCIPC',
    '',
    'https://www.linkedin.com/company/cipc/',
    'https://www.cipc.co.za/?page_id=3781',
    'https://www.cipc.co.za/?page_id=3791',
    'Enterprise Number',
  ),
  KR:   office(
    'Supreme Court Internet Registry Office',
    '+82 2 3480 1715',
    'Seocho-daero, Seocho-gu, Seoul, Republic of Korea',
    'https://www.iros.go.kr',
    '',
    '',
    '',
    '',
    'https://www.iros.go.kr',
    'https://www.k-startup.go.kr/common/post/detail.do?postSn=95',
    'Business Registration Number',
  ),
  TR:   office(
    'Central Registry System Turkey (MERSIS)',
    '+90 312 417 7777',
    'Ankara, Turkey',
    'https://www.ticaret.gov.tr',
    'bilgi@ticaret.gov.tr',
    '',
    '',
    '',
    'https://mersis.ticaret.gov.tr',
    'https://www.ticaret.gov.tr/sirket-kurulus-islemleri',
    'MERSIS Number',
  ),
  GB:   office(
    'Companies House United Kingdom',
    '+44 303 1234 500',
    'Crown Way, Cardiff CF14 3UZ, United Kingdom',
    'https://www.gov.uk/government/organisations/companies-house',
    'enquiries@companieshouse.gov.uk',
    'https://twitter.com/CompaniesHouse',
    '',
    'https://www.linkedin.com/company/companies-house/',
    'https://www.gov.uk/limited-company-formation',
    'https://www.gov.uk/set-up-limited-company',
    'Company Registration Number (CRN)',
  ),
  US:   office(
    'U.S. State Secretary of State Business Filing Offices (Representative: Delaware Division of Corporations)',
    '+1 302 739 3073',
    '401 Federal Street, Dover, DE 19901, United States',
    'https://corp.delaware.gov',
    '',
    '',
    '',
    '',
    'https://corp.delaware.gov/paytaxes/',
    'https://www.sba.gov/business-guide/launch-your-business/register-your-business',
    'Employer Identification Number (EIN)',
  ),
}
