import type { G20SovereignMemberIsoCode } from './g20MemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per G20 sovereign member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const G20_DOMESTIC_POST_SERVICES: Record<G20SovereignMemberIsoCode, DomesticPostService> = {
  AR: post(
    'Correo Argentino',
    'https://www.correoargentino.com.ar/',
    'atencion@correoargentino.com.ar',
    'https://x.com/CorreoArgentino',
    'https://www.instagram.com/correoargentino/',
    'https://www.linkedin.com/company/correo-argentino/',
    '',
    'ANNNNAAA',
    '^[A-Z]\\d{4}[A-Z]{3}$',
    'C1425CLA',
    'Eight-character CPA (letter + four digits + three letters)',
  ),
  AU: post(
    'Australia Post',
    'https://auspost.com.au/',
    'feedback@auspost.com.au',
    'https://x.com/AusPost',
    'https://www.instagram.com/auspost/',
    'https://www.linkedin.com/company/australia-post/',
    'https://developers.auspost.com.au/',
    'NNNN',
    '^\\d{4}$',
    '2000',
    'Four-digit postcode',
  ),
  BR: post(
    'Correios (Empresa Brasileira de Correios e Telégrafos)',
    'https://www.correios.com.br/',
    'atendimento@correios.com.br',
    'https://x.com/Correios',
    'https://www.instagram.com/correios/',
    'https://www.linkedin.com/company/correios/',
    'https://www.correios.com.br/atendimento/developers',
    'NNNNN-NNN',
    '^\\d{5}-\\d{3}$',
    '70040-902',
    'CEP: five digits + hyphen + three digits',
  ),
  CA: post(
    'Canada Post',
    'https://www.canadapost-postescanada.ca/',
    'customercare@canadapost-postescanada.ca',
    'https://x.com/canadapostcorp',
    'https://www.instagram.com/canadapost/',
    'https://www.linkedin.com/company/canada-post/',
    'https://www.canadapost-postescanada.ca/cpc/en/tools/find-a-postal-code.page',
    'ANA NAN',
    '^[A-Z]\\d[A-Z] \\d[A-Z]\\d$',
    'K1A 0B1',
    'Canadian postal code (letter-digit-letter space digit-letter-digit)',
  ),
  CN: post(
    'China Post',
    'https://www.ems.com.cn/',
    'service@ems.com.cn',
    'https://x.com/chinapost',
    'https://www.instagram.com/chinapost/',
    'https://www.linkedin.com/company/china-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
  FR: post(
    'La Poste',
    'https://www.laposte.fr/',
    'contact@laposte.fr',
    'https://x.com/laposte',
    'https://www.instagram.com/laposte/',
    'https://www.linkedin.com/company/la-poste/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '75001',
    'Five-digit code postal',
  ),
  DE: post(
    'Deutsche Post',
    'https://www.deutschepost.de/',
    'info@deutschepost.de',
    'https://x.com/DeutschePost',
    'https://www.instagram.com/deutschepost/',
    'https://www.linkedin.com/company/deutsche-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10115',
    'Five-digit Postleitzahl',
  ),
  IN: post(
    'India Post',
    'https://www.indiapost.gov.in/',
    'helpdesk@indiapost.gov.in',
    'https://x.com/IndiaPostOffice',
    'https://www.instagram.com/indiapostoffice/',
    'https://www.linkedin.com/company/india-post/',
    'https://www.indiapost.gov.in/',
    'NNNNNN',
    '^\\d{6}$',
    '110001',
    'Six-digit PIN code',
  ),
  ID: post(
    'Pos Indonesia',
    'https://www.posindonesia.co.id/',
    'pusatbantuan@posindonesia.co.id',
    'https://x.com/PosIndonesia',
    'https://www.instagram.com/posindonesia/',
    'https://www.linkedin.com/company/pos-indonesia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10110',
    'Five-digit postcode',
  ),
  IT: post(
    'Poste Italiane',
    'https://www.poste.it/',
    'assistenza.clienti@poste.it',
    'https://x.com/PosteItaliane',
    'https://www.instagram.com/posteitaliane/',
    'https://www.linkedin.com/company/poste-italiane/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00118',
    'Five-digit CAP',
  ),
  JP: post(
    'Japan Post',
    'https://www.post.japanpost.jp/',
    'info@jp-network.japanpost.jp',
    'https://x.com/japanpost_off',
    'https://www.instagram.com/japanpost_off/',
    'https://www.linkedin.com/company/japan-post-holdings/',
    '',
    'NNN-NNNN',
    '^\\d{3}-\\d{4}$',
    '100-0001',
    'Three-digit + four-digit postcode (hyphenated)',
  ),
  MX: post(
    'Correos de México',
    'https://www.correosdemexico.gob.mx/',
    'atencionaclientes@correosdemexico.gob.mx',
    'https://x.com/CorreosdeMexico',
    'https://www.instagram.com/correosdemexico/',
    'https://www.linkedin.com/company/correos-de-mexico/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '06000',
    'Five-digit código postal',
  ),
  RU: post(
    'Russian Post (Pochta Rossii)',
    'https://www.pochta.ru/',
    'info@russianpost.ru',
    'https://x.com/russianpost',
    'https://www.instagram.com/russianpost/',
    'https://www.linkedin.com/company/russian-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '101000',
    'Six-digit postcode',
  ),
  SA: post(
    'Saudi Post (SPL)',
    'https://splonline.com.sa/',
    'customercare@splonline.com.sa',
    'https://x.com/SPLCare',
    'https://www.instagram.com/splcare/',
    'https://www.linkedin.com/company/saudi-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11564',
    'Five-digit postcode (national addressing system)',
  ),
  ZA: post(
    'South African Post Office',
    'http://www.postoffice.co.za/',
    'custserv@postoffice.co.za',
    'https://x.com/PostofficeSa',
    'https://www.instagram.com/sapostoffice/',
    'https://www.linkedin.com/company/south-african-post-office/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '2000',
    'Four-digit postcode (street delivery and P.O. Box)',
  ),
  KR: post(
    'Korea Post',
    'https://www.koreapost.go.kr/',
    'help@koreapost.go.kr',
    'https://x.com/koreapost',
    'https://www.instagram.com/koreapost/',
    'https://www.linkedin.com/company/korea-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '04524',
    'Five-digit postcode (reformed 2015)',
  ),
  TR: post(
    'PTT (Türkiye Post)',
    'https://www.ptt.gov.tr/',
    'info@ptt.gov.tr',
    'https://x.com/PTT',
    'https://www.instagram.com/ptt/',
    'https://www.linkedin.com/company/ptt/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '06100',
    'Five-digit postcode',
  ),
  GB: post(
    'Royal Mail',
    'https://www.royalmail.com/',
    'customerservice@royalmail.com',
    'https://x.com/RoyalMail',
    'https://www.instagram.com/royalmailofficial/',
    'https://www.linkedin.com/company/royal-mail/',
    'https://developer.royalmail.net/',
    'AAN NAA',
    '^[A-Z]{1,2}\\d[A-Z\\d]? \\d[A-Z]{2}$',
    'SW1A 1AA',
    'UK postcode (outward + inward codes)',
  ),
  US: post(
    'United States Postal Service (USPS)',
    'https://www.usps.com/',
    'uspscustomerservice@usps.gov',
    'https://x.com/USPS',
    'https://www.instagram.com/usps/',
    'https://www.linkedin.com/company/usps/',
    'https://developer.usps.com/',
    'NNNNN',
    '^\\d{5}$',
    '20500',
    'Five-digit ZIP; ZIP+4 optional (NNNNN-NNNN)',
  ),
}
