import type { G20SovereignMemberIsoCode } from './g20MemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for Group of Twenty (G20)
 * sovereign members in this module (informational; verify URLs, handles, forms portals, and API
 * bases before production use). Self-contained — no imports from other alliance modules.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const G20_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  G20SovereignMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AR: roster(
    ip(
      'copyright',
      'National Institute of Industrial Property (INPI Argentina) — copyright',
      'https://www.argentina.gob.ar/inpi',
      'inpi@inpi.gob.ar',
      '',
      '',
      'https://www.argentina.gob.ar/inpi',
    ),
    ip(
      'trademarks',
      'National Institute of Industrial Property (INPI Argentina)',
      'https://www.argentina.gob.ar/inpi',
      'inpi@inpi.gob.ar',
      '',
      '',
      'https://www.argentina.gob.ar/inpi',
    ),
    ip(
      'patents',
      'National Institute of Industrial Property (INPI Argentina)',
      'https://www.argentina.gob.ar/inpi',
      'inpi@inpi.gob.ar',
      '',
      '',
      'https://www.argentina.gob.ar/inpi',
    ),
  ),
  AU: roster(
    ip(
      'copyright',
      'Australian Government — Attorney-General\'s Department (Copyright)',
      'https://www.ag.gov.au/rights-and-protections/copyright',
      '',
      '',
      '',
      'https://www.ag.gov.au/rights-and-protections/copyright',
    ),
    ip(
      'trademarks',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
    ip(
      'patents',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
  ),
  BR: roster(
    ip(
      'copyright',
      'Ministry of Culture — copyright (Brazil)',
      'https://www.gov.br/cultura',
      '',
      '',
      '',
      'https://www.gov.br/cultura',
    ),
    ip(
      'trademarks',
      'National Institute of Industrial Property (INPI Brazil)',
      'https://www.gov.br/inpi',
      'inpi@inpi.gov.br',
      'https://x.com/inpi_brasil',
      'https://www.linkedin.com/company/inpi-brasil/',
      'https://www.gov.br/inpi/pt-br/servicos',
    ),
    ip(
      'patents',
      'National Institute of Industrial Property (INPI Brazil)',
      'https://www.gov.br/inpi',
      'inpi@inpi.gov.br',
      'https://x.com/inpi_brasil',
      'https://www.linkedin.com/company/inpi-brasil/',
      'https://www.gov.br/inpi/pt-br/servicos',
    ),
  ),
  CA: roster(
    ip(
      'copyright',
      'Canadian Intellectual Property Office (CIPO) — copyright',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'trademarks',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'patents',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
  ),
  CN: roster(
    ip(
      'copyright',
      'National Copyright Administration of the People\'s Republic of China (NCAC)',
      'https://www.ncac.gov.cn',
      '',
      '',
      '',
      'https://www.ncac.gov.cn',
    ),
    ip(
      'trademarks',
      'China National Intellectual Property Administration (CNIPA)',
      'https://www.cnipa.gov.cn',
      '',
      '',
      '',
      'https://cponline.cnipa.gov.cn',
    ),
    ip(
      'patents',
      'China National Intellectual Property Administration (CNIPA)',
      'https://www.cnipa.gov.cn',
      '',
      '',
      '',
      'https://cponline.cnipa.gov.cn',
    ),
  ),
  FR: roster(
    ip(
      'copyright',
      'Ministry of Culture (France) — copyright',
      'https://www.culture.gouv.fr',
      '',
      '',
      '',
      'https://www.culture.gouv.fr',
    ),
    ip(
      'trademarks',
      'National Institute of Industrial Property (INPI France)',
      'https://www.inpi.fr',
      'contact@inpi.fr',
      'https://x.com/INPIfr',
      'https://www.linkedin.com/company/inpi/',
      'https://www.inpi.fr/fr/services-et-prestations',
    ),
    ip(
      'patents',
      'National Institute of Industrial Property (INPI France)',
      'https://www.inpi.fr',
      'contact@inpi.fr',
      'https://x.com/INPIfr',
      'https://www.linkedin.com/company/inpi/',
      'https://www.inpi.fr/fr/services-et-prestations',
    ),
  ),
  DE: roster(
    ip(
      'copyright',
      'German Patent and Trade Mark Office (DPMA) — copyright liaison',
      'https://www.dpma.de',
      '',
      '',
      '',
      'https://www.dpma.de',
    ),
    ip(
      'trademarks',
      'German Patent and Trade Mark Office (DPMA)',
      'https://www.dpma.de',
      'poststelle@dpma.de',
      '',
      'https://www.linkedin.com/company/dpma/',
      'https://www.dpma.de/english/services/index.html',
    ),
    ip(
      'patents',
      'German Patent and Trade Mark Office (DPMA)',
      'https://www.dpma.de',
      'poststelle@dpma.de',
      '',
      'https://www.linkedin.com/company/dpma/',
      'https://www.dpma.de/english/services/index.html',
    ),
  ),
  IN: roster(
    ip(
      'copyright',
      'Copyright Office of India',
      'https://copyright.gov.in',
      '',
      '',
      '',
      'https://copyright.gov.in',
    ),
    ip(
      'trademarks',
      'Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)',
      'https://ipindia.gov.in',
      'cgoffice@nic.in',
      '',
      'https://www.linkedin.com/company/office-of-the-controller-general-of-patents-designs-and-trade-marks/',
      'https://ipindiaonline.gov.in',
    ),
    ip(
      'patents',
      'Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)',
      'https://ipindia.gov.in',
      'cgoffice@nic.in',
      '',
      'https://www.linkedin.com/company/office-of-the-controller-general-of-patents-designs-and-trade-marks/',
      'https://ipindiaonline.gov.in',
    ),
  ),
  ID: roster(
    ip(
      'copyright',
      'Directorate General of Intellectual Property (DGIP) — copyright',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'trademarks',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'patents',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
  ),
  IT: roster(
    ip(
      'copyright',
      'Ministry of Culture — copyright (Italy)',
      'https://www.beniculturali.it',
      '',
      '',
      '',
      'https://www.uibm.gov.it',
    ),
    ip(
      'trademarks',
      'Italian Patent and Trademark Office (UIBM)',
      'https://www.uibm.gov.it',
      '',
      '',
      '',
      'https://www.uibm.gov.it',
    ),
    ip(
      'patents',
      'Italian Patent and Trademark Office (UIBM)',
      'https://www.uibm.gov.it',
      '',
      '',
      '',
      'https://www.uibm.gov.it',
    ),
  ),
  JP: roster(
    ip(
      'copyright',
      'Agency for Cultural Affairs (Government of Japan — Copyright)',
      'https://www.bunka.go.jp/english/',
      '',
      '',
      '',
      'https://www.bunka.go.jp/english/copyright/index.html',
    ),
    ip(
      'trademarks',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
    ip(
      'patents',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
  ),
  MX: roster(
    ip(
      'copyright',
      'Instituto Nacional del Derecho de Autor (INDAUTOR)',
      'https://www.indautor.gob.mx',
      'indautor@indautor.gob.mx',
      'https://x.com/INDAUTORMX',
      '',
      'https://www.indautor.gob.mx/servicios/',
    ),
    ip(
      'trademarks',
      'Mexican Institute of Industrial Property (IMPI)',
      'https://www.gob.mx/impi',
      'impi@impi.gob.mx',
      'https://x.com/IMPI_MX',
      'https://www.linkedin.com/company/impi/',
      'https://www.gob.mx/impi/acciones-y-programas/servicios-en-linea',
    ),
    ip(
      'patents',
      'Mexican Institute of Industrial Property (IMPI)',
      'https://www.gob.mx/impi',
      'impi@impi.gob.mx',
      'https://x.com/IMPI_MX',
      'https://www.linkedin.com/company/impi/',
      'https://www.gob.mx/impi/acciones-y-programas/servicios-en-linea',
    ),
  ),
  RU: roster(
    ip(
      'copyright',
      'Ministry of Culture of the Russian Federation — copyright',
      'https://culture.gov.ru',
      '',
      '',
      '',
      'https://culture.gov.ru',
    ),
    ip(
      'trademarks',
      'Federal Service for Intellectual Property (Rospatent)',
      'https://rospatent.gov.ru',
      'fips@rupto.ru',
      '',
      '',
      'https://rospatent.gov.ru/ru/services',
    ),
    ip(
      'patents',
      'Federal Service for Intellectual Property (Rospatent)',
      'https://rospatent.gov.ru',
      'fips@rupto.ru',
      '',
      '',
      'https://rospatent.gov.ru/ru/services',
    ),
  ),
  SA: roster(
    ip(
      'copyright',
      'Saudi Authority for Intellectual Property (SAIP)',
      'https://www.saip.gov.sa',
      'info@saip.gov.sa',
      '',
      'https://www.linkedin.com/company/saudi-authority-for-intellectual-property/',
      'https://www.saip.gov.sa',
    ),
    ip(
      'trademarks',
      'Saudi Authority for Intellectual Property (SAIP)',
      'https://www.saip.gov.sa',
      'info@saip.gov.sa',
      '',
      'https://www.linkedin.com/company/saudi-authority-for-intellectual-property/',
      'https://www.saip.gov.sa',
    ),
    ip(
      'patents',
      'Saudi Authority for Intellectual Property (SAIP)',
      'https://www.saip.gov.sa',
      'info@saip.gov.sa',
      '',
      'https://www.linkedin.com/company/saudi-authority-for-intellectual-property/',
      'https://www.saip.gov.sa',
    ),
  ),
  ZA: roster(
    ip(
      'copyright',
      'Companies and Intellectual Property Commission (CIPC) — Copyright Tribunal liaison',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
  ),
  KR: roster(
    ip(
      'copyright',
      'Korea Copyright Commission (KCC)',
      'https://www.copyright.or.kr',
      'help@copyright.or.kr',
      '',
      '',
      'https://www.copyright.or.kr',
    ),
    ip(
      'trademarks',
      'Korean Intellectual Property Office (KIPO)',
      'https://www.kipo.go.kr',
      '',
      '',
      '',
      'https://www.patent.go.kr',
    ),
    ip(
      'patents',
      'Korean Intellectual Property Office (KIPO)',
      'https://www.kipo.go.kr',
      '',
      '',
      '',
      'https://www.patent.go.kr',
    ),
  ),
  TR: roster(
    ip(
      'copyright',
      'Turkish Patent and Trademark Office (TürkPatent) — copyright',
      'https://www.turkpatent.gov.tr',
      '',
      '',
      '',
      'https://www.turkpatent.gov.tr',
    ),
    ip(
      'trademarks',
      'Turkish Patent and Trademark Office (TürkPatent)',
      'https://www.turkpatent.gov.tr',
      '',
      '',
      '',
      'https://www.turkpatent.gov.tr',
    ),
    ip(
      'patents',
      'Turkish Patent and Trademark Office (TürkPatent)',
      'https://www.turkpatent.gov.tr',
      '',
      '',
      '',
      'https://www.turkpatent.gov.tr',
    ),
  ),
  GB: roster(
    ip(
      'copyright',
      'Intellectual Property Office (UK) — copyright guidance',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'patents',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
  ),
  US: roster(
    ip(
      'copyright',
      'U.S. Copyright Office',
      'https://www.copyright.gov',
      '',
      'https://x.com/CopyrightOffice',
      'https://www.linkedin.com/company/us-copyright-office/',
      'https://www.copyright.gov/registration/',
    ),
    ip(
      'trademarks',
      'United States Patent and Trademark Office (USPTO)',
      'https://www.uspto.gov',
      '',
      'https://x.com/uspto',
      'https://www.linkedin.com/company/uspto/',
      'https://www.uspto.gov/apply',
      'https://developer.uspto.gov/',
    ),
    ip(
      'patents',
      'United States Patent and Trademark Office (USPTO)',
      'https://www.uspto.gov',
      '',
      'https://x.com/uspto',
      'https://www.linkedin.com/company/uspto/',
      'https://www.uspto.gov/apply',
      'https://developer.uspto.gov/',
    ),
  ),
}
