import type { G20SovereignMemberIsoCode } from './g20MemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per G20 sovereign member (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const G20_MAIN_INTERNATIONAL_SEAPORTS: Record<G20SovereignMemberIsoCode, MainInternationalSeaport> = {
  AR: seaport(
    'Port of Buenos Aires',
    'https://www.argentina.gob.ar/puertos',
    'puertos@argentina.gob.ar',
    'https://x.com/PuertosArgentina',
    'https://www.instagram.com/puertosargentina/',
    'https://www.linkedin.com/company/puertos-argentina/',
    'aduana@afip.gob.ar',
    'https://www.afip.gob.ar',
    'AFIP Aduana — Puerto Buenos Aires, Buenos Aires, Argentina',
  ),
  AU: seaport(
    'Port of Melbourne',
    'https://www.portofmelbourne.com/',
    'info@portofmelbourne.com',
    'https://x.com/PortOfMelbourne',
    'https://www.instagram.com/portofmelbourne/',
    'https://www.linkedin.com/company/port-of-melbourne/',
    'customs@abf.gov.au',
    'https://www.abf.gov.au',
    'Australian Border Force — Port of Melbourne, Melbourne, Australia',
  ),
  BR: seaport(
    'Port of Santos',
    'https://www.portodesantos.com.br/',
    'atendimento@portodesantos.com.br',
    'https://x.com/PortoSantos',
    'https://www.instagram.com/portodesantos/',
    'https://www.linkedin.com/company/porto-de-santos/',
    'atendimento@receita.fazenda.gov.br',
    'https://www.gov.br/receitafederal',
    'Receita Federal — Porto de Santos, Santos, Brazil',
  ),
  CA: seaport(
    'Port of Vancouver',
    'https://www.portvancouver.com/',
    'info@portvancouver.com',
    'https://x.com/portvancouver',
    'https://www.instagram.com/portvancouver/',
    'https://www.linkedin.com/company/port-of-vancouver/',
    'cbcsa-client-services@cbsa-asfc.gc.ca',
    'https://www.cbsa-asfc.gc.ca',
    'Canada Border Services Agency — Port of Vancouver, Vancouver, Canada',
  ),
  CN: seaport(
    'Port of Shanghai',
    'https://www.portshanghai.com.cn/',
    'info@portshanghai.com.cn',
    'https://x.com/PortShanghai',
    'https://www.instagram.com/portshanghai/',
    'https://www.linkedin.com/company/shanghai-international-port-group/',
    'customs@customs.gov.cn',
    'https://www.customs.gov.cn',
    'General Administration of Customs — Port of Shanghai, Shanghai, China',
  ),
  FR: seaport(
    'Port of Le Havre',
    'https://www.havre-port.fr/',
    'info@havre-port.fr',
    'https://x.com/HavrePort',
    'https://www.instagram.com/havreport/',
    'https://www.linkedin.com/company/grand-port-maritime-du-havre/',
    'douane@douane.gouv.fr',
    'https://www.douane.gouv.fr',
    'French Customs — Port of Le Havre, Le Havre, France',
  ),
  DE: seaport(
    'Port of Hamburg',
    'https://www.hafen-hamburg.de/',
    'info@hafen-hamburg.de',
    'https://x.com/hafenhamburg',
    'https://www.instagram.com/hafenhamburg/',
    'https://www.linkedin.com/company/hamburg-port-authority/',
    'info@zoll.de',
    'https://www.zoll.de',
    'German Customs — Port of Hamburg, Hamburg, Germany',
  ),
  IN: seaport(
    'Jawaharlal Nehru Port (Nhava Sheva)',
    'https://www.jnport.gov.in/',
    'info@jnport.gov.in',
    'https://x.com/JNPort',
    'https://www.instagram.com/jnport/',
    'https://www.linkedin.com/company/jawaharlal-nehru-port-trust/',
    'customs@cbic.gov.in',
    'https://www.cbic.gov.in',
    'Indian Customs — Jawaharlal Nehru Port, Navi Mumbai, India',
  ),
  ID: seaport(
    'Port of Tanjung Priok (Jakarta)',
    'https://www.pelindo.co.id/',
    'info@pelindo.co.id',
    'https://x.com/Pelindo',
    'https://www.instagram.com/pelindo/',
    'https://www.linkedin.com/company/pelindo/',
    'contact.center@beacukai.go.id',
    'https://www.beacukai.go.id',
    'Direktorat Jenderal Bea dan Cukai — Pelabuhan Tanjung Priok, Jakarta, Indonesia',
  ),
  IT: seaport(
    'Port of Genoa',
    'https://www.portsofgenoa.com/',
    'info@portsofgenoa.com',
    'https://x.com/PortofGenoa',
    'https://www.instagram.com/portofgenoa/',
    'https://www.linkedin.com/company/western-ligurian-sea-port-authority/',
    'dogane@dogane.gov.it',
    'https://www.adm.gov.it',
    'Agenzia delle Dogane — Porto di Genova, Genoa, Italy',
  ),
  JP: seaport(
    'Port of Yokohama',
    'https://www.portof_yokohama.jp/',
    'info@portof_yokohama.jp',
    'https://x.com/PortOfYokohama',
    'https://www.instagram.com/portofyokohama/',
    'https://www.linkedin.com/company/port-and-harbor-bureau-city-of-yokohama/',
    'zeimu@customs.go.jp',
    'https://www.customs.go.jp',
    'Yokohama Customs — Port of Yokohama, Yokohama, Japan',
  ),
  MX: seaport(
    'Port of Manzanillo',
    'https://www.puertomanzanillo.com.mx/',
    'contacto@puertomanzanillo.com.mx',
    'https://x.com/PuertoManzanillo',
    'https://www.instagram.com/puertomanzanillo/',
    'https://www.linkedin.com/company/puerto-manzanillo/',
    'atencion@sat.gob.mx',
    'https://www.sat.gob.mx',
    'SAT Aduanas — Puerto de Manzanillo, Manzanillo, Mexico',
  ),
  RU: seaport(
    'Port of Vladivostok',
    'https://www.vmtp.ru/',
    'info@vmtp.ru',
    'https://x.com/VladivostokPort',
    'https://www.instagram.com/vladivostokport/',
    'https://www.linkedin.com/company/vladivostok-sea-port/',
    'customs@fts.customs.ru',
    'https://www.customs.ru',
    'Far Eastern Customs — Port of Vladivostok, Vladivostok, Russia',
  ),
  SA: seaport(
    'King Abdullah Port',
    'https://www.ka-port.com.sa/',
    'info@ka-port.com.sa',
    'https://x.com/KingAbdullahPort',
    'https://www.instagram.com/kingabdullahport/',
    'https://www.linkedin.com/company/king-abdullah-port/',
    'customs@zatca.gov.sa',
    'https://www.zatca.gov.sa',
    'ZATCA Customs — King Abdullah Port, Rabigh, Saudi Arabia',
  ),
  ZA: seaport(
    'Port of Durban',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'customs@sars.gov.za',
    'https://www.sars.gov.za',
    'South African Revenue Service — Customs, Port of Durban, Durban, South Africa',
  ),
  KR: seaport(
    'Port of Busan',
    'https://www.busanpa.com/',
    'info@busanpa.com',
    'https://x.com/BusanPort',
    'https://www.instagram.com/busanport/',
    'https://www.linkedin.com/company/busan-port-authority/',
    'customs@customs.go.kr',
    'https://www.customs.go.kr',
    'Korea Customs Service — Port of Busan, Busan, South Korea',
  ),
  TR: seaport(
    'Port of Mersin',
    'https://www.mersinport.com.tr/',
    'info@mersinport.com.tr',
    'https://x.com/MersinPort',
    'https://www.instagram.com/mersinport/',
    'https://www.linkedin.com/company/mersin-international-port/',
    'gumruk@gumruk.gov.tr',
    'https://www.gumruk.gov.tr',
    'Turkish Customs — Port of Mersin, Mersin, Turkey',
  ),
  GB: seaport(
    'Port of Felixstowe',
    'https://www.portoffelixstowe.co.uk/',
    'info@portoffelixstowe.co.uk',
    'https://x.com/PortofFelixstowe',
    'https://www.instagram.com/portoffelixstowe/',
    'https://www.linkedin.com/company/port-of-felixstowe/',
    'national.advice@hmrc.gov.uk',
    'https://www.gov.uk/government/organisations/hm-revenue-customs',
    'HMRC Border Force — Port of Felixstowe, Felixstowe, United Kingdom',
  ),
  US: seaport(
    'Port of Los Angeles',
    'https://www.portoflosangeles.org/',
    'info@portoflosangeles.org',
    'https://x.com/portofla',
    'https://www.instagram.com/portofla/',
    'https://www.linkedin.com/company/port-of-los-angeles/',
    'losangeles.cbp@cbp.dhs.gov',
    'https://www.cbp.gov',
    'U.S. Customs and Border Protection — Port of Los Angeles, San Pedro, United States',
  ),
}
