import type { G20SovereignMemberIsoCode } from './g20MemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const G20_MAIN_INTERNATIONAL_AIRPORTS: Record<G20SovereignMemberIsoCode, MainInternationalAirport> = {
  AR: {
    name: 'Ministro Pistarini International Airport (EZE)',
    website: 'https://www.aa2000.com.ar/',
    email: 'info@aa2000.com.ar',
    twitter: 'https://x.com/AA2000',
    instagram: 'https://www.instagram.com/aa2000/',
    linkedin: 'https://www.linkedin.com/company/aeropuertos-argentina-2000/',
    apiEndpoint: '',
  },
  AU: {
    name: 'Sydney Kingsford Smith Airport (SYD)',
    website: 'https://www.sydneyairport.com.au/',
    email: 'info@sydneyairport.com.au',
    twitter: 'https://x.com/SydneyAirport',
    instagram: 'https://www.instagram.com/sydneyairport/',
    linkedin: 'https://www.linkedin.com/company/sydney-airport/',
    apiEndpoint: '',
  },
  BR: {
    name: 'Guarulhos International Airport (GRU)',
    website: 'https://www.gru.com.br/',
    email: 'info@gru.com.br',
    twitter: 'https://x.com/AeroportoGRU',
    instagram: 'https://www.instagram.com/aeroportogru/',
    linkedin: 'https://www.linkedin.com/company/gru-airport/',
    apiEndpoint: '',
  },
  CA: {
    name: 'Toronto Pearson International Airport (YYZ)',
    website: 'https://www.torontopearson.com/',
    email: 'info@torontopearson.com',
    twitter: 'https://x.com/TorontoPearson',
    instagram: 'https://www.instagram.com/torontopearson/',
    linkedin: 'https://www.linkedin.com/company/toronto-pearson-international-airport/',
    apiEndpoint: '',
  },
  CN: {
    name: 'Beijing Capital International Airport (PEK)',
    website: 'https://www.bcia.com.cn/',
    email: 'service@bcia.com.cn',
    twitter: 'https://x.com/BeijingAirport',
    instagram: 'https://www.instagram.com/beijingairport/',
    linkedin: 'https://www.linkedin.com/company/beijing-capital-international-airport/',
    apiEndpoint: '',
  },
  FR: {
    name: 'Paris Charles de Gaulle Airport (CDG)',
    website: 'https://www.parisaeroport.fr/',
    email: 'contact@adp.fr',
    twitter: 'https://x.com/ParisAeroport',
    instagram: 'https://www.instagram.com/parisaeroport/',
    linkedin: 'https://www.linkedin.com/company/groupe-adp/',
    apiEndpoint: '',
  },
  DE: {
    name: 'Frankfurt Airport (FRA)',
    website: 'https://www.frankfurt-airport.com/',
    email: 'info@fraport.de',
    twitter: 'https://x.com/Airport_FRA',
    instagram: 'https://www.instagram.com/airport_fra/',
    linkedin: 'https://www.linkedin.com/company/frankfurt-airport/',
    apiEndpoint: '',
  },
  IN: {
    name: 'Indira Gandhi International Airport (DEL)',
    website: 'https://www.newdelhiairport.in/',
    email: 'feedback@delhiairport.com',
    twitter: 'https://x.com/DelhiAirport',
    instagram: 'https://www.instagram.com/delhiairport/',
    linkedin: 'https://www.linkedin.com/company/delhi-international-airport-limited/',
    apiEndpoint: '',
  },
  ID: {
    name: 'Soekarno-Hatta International Airport (CGK)',
    website: 'https://soekarnohatta-airport.co.id/',
    email: 'info@soekarnohatta-airport.co.id',
    twitter: 'https://x.com/SoettaAirport',
    instagram: 'https://www.instagram.com/soettaairport/',
    linkedin: 'https://www.linkedin.com/company/soekarno-hatta-international-airport/',
    apiEndpoint: '',
  },
  IT: {
    name: 'Leonardo da Vinci–Fiumicino Airport (FCO)',
    website: 'https://www.adr.it/',
    email: 'info@adr.it',
    twitter: 'https://x.com/ADRAirports',
    instagram: 'https://www.instagram.com/adr_airports/',
    linkedin: 'https://www.linkedin.com/company/adr-aeroporti-di-roma/',
    apiEndpoint: '',
  },
  JP: {
    name: 'Tokyo Haneda Airport (HND)',
    website: 'https://www.haneda-airport.jp/',
    email: 'info@haneda-airport.jp',
    twitter: 'https://x.com/TokyoHaneda',
    instagram: 'https://www.instagram.com/tokyohaneda/',
    linkedin: 'https://www.linkedin.com/company/tokyo-international-airport/',
    apiEndpoint: '',
  },
  MX: {
    name: 'Mexico City International Airport (MEX)',
    website: 'https://www.aicm.com.mx/',
    email: 'contacto@aicm.com.mx',
    twitter: 'https://x.com/AICM_mx',
    instagram: 'https://www.instagram.com/aicm_mx/',
    linkedin: 'https://www.linkedin.com/company/aeropuerto-internacional-de-la-ciudad-de-mexico/',
    apiEndpoint: '',
  },
  RU: {
    name: 'Sheremetyevo International Airport (SVO)',
    website: 'https://www.svo.aero/',
    email: 'info@svo.aero',
    twitter: 'https://x.com/SVO_airport',
    instagram: 'https://www.instagram.com/svo_airport/',
    linkedin: 'https://www.linkedin.com/company/sheremetyevo-international-airport/',
    apiEndpoint: '',
  },
  SA: {
    name: 'King Khalid International Airport (RUH)',
    website: 'https://www.riyadhairports.com/',
    email: 'info@riyadhairports.com',
    twitter: 'https://x.com/RUH_Airport',
    instagram: 'https://www.instagram.com/ruh_airport/',
    linkedin: 'https://www.linkedin.com/company/riyadh-airports-company/',
    apiEndpoint: '',
  },
  ZA: {
    name: 'O.R. Tambo International Airport (JNB)',
    website: 'https://www.airports.co.za/',
    email: 'info@airports.co.za',
    twitter: 'https://x.com/Airports_ZA',
    instagram: 'https://www.instagram.com/airports_co_za/',
    linkedin: 'https://www.linkedin.com/company/airports-company-south-africa/',
    apiEndpoint: '',
  },
  KR: {
    name: 'Incheon International Airport (ICN)',
    website: 'https://www.airport.kr/',
    email: 'help@airport.kr',
    twitter: 'https://x.com/IncheonAirport',
    instagram: 'https://www.instagram.com/incheonairport/',
    linkedin: 'https://www.linkedin.com/company/incheon-international-airport-corporation/',
    apiEndpoint: '',
  },
  TR: {
    name: 'Istanbul Airport (IST)',
    website: 'https://www.istairport.com/',
    email: 'info@istairport.com',
    twitter: 'https://x.com/istanbulairport',
    instagram: 'https://www.instagram.com/istanbulairport/',
    linkedin: 'https://www.linkedin.com/company/istanbul-airport/',
    apiEndpoint: '',
  },
  GB: {
    name: 'Heathrow Airport (LHR)',
    website: 'https://www.heathrow.com/',
    email: 'customer.service@heathrow.com',
    twitter: 'https://x.com/HeathrowAirport',
    instagram: 'https://www.instagram.com/heathrowairport/',
    linkedin: 'https://www.linkedin.com/company/heathrow-airport/',
    apiEndpoint: '',
  },
  US: {
    name: 'Los Angeles International Airport (LAX)',
    website: 'https://www.flylax.com/',
    email: 'info@lawa.org',
    twitter: 'https://x.com/flyLAXairport',
    instagram: 'https://www.instagram.com/flylax/',
    linkedin: 'https://www.linkedin.com/company/los-angeles-world-airports/',
    apiEndpoint: '',
  },
}
