import type { G20SovereignMemberIsoCode } from './g20MemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const G20_MAIN_EXPORT_COMMODITIES: Record<
  G20SovereignMemberIsoCode,
  MainExportCommodities
> = {
  AR: m(
    'Soybeans',
    'Corn',
    'Wheat',
    'Beef',
    'Gold',
    'Petroleum products',
    'Automobiles',
  ),
  AU: m(
    'Iron ore',
    'Coal',
    'Natural gas',
    'Gold',
    'Beef',
    'Wheat',
    'Aluminium',
  ),
  BR: m(
    'Soybeans',
    'Crude petroleum',
    'Iron ore',
    'Sugar',
    'Poultry meat',
    'Corn',
    'Coffee',
  ),
  CA: m(
    'Crude petroleum',
    'Automobiles',
    'Gold',
    'Wheat',
    'Lumber',
    'Aluminium',
    'Natural gas',
  ),
  CN: m(
    'Electrical machinery',
    'Computers',
    'Telecommunications equipment',
    'Furniture',
    'Plastics',
    'Apparel',
    'Steel',
  ),
  FR: m(
    'Aircraft',
    'Packaged medicaments',
    'Wine',
    'Refined petroleum',
    'Automobiles',
    'Wheat',
    'Pharmaceuticals',
  ),
  DE: m(
    'Automobiles',
    'Packaged medicaments',
    'Machinery',
    'Refined petroleum',
    'Electrical machinery',
    'Plastics',
    'Iron and steel',
  ),
  IN: m(
    'Refined petroleum',
    'Diamonds',
    'Pharmaceuticals',
    'Rice',
    'Machinery',
    'Iron and steel',
    'Cotton yarn',
  ),
  ID: m(
    'Coal',
    'Palm oil',
    'Nickel',
    'Refined petroleum',
    'Rubber',
    'Copper',
    'Gold',
  ),
  IT: m(
    'Machinery',
    'Packaged medicaments',
    'Automobiles',
    'Refined petroleum',
    'Wine',
    'Clothing',
    'Furniture',
  ),
  JP: m(
    'Automobiles',
    'Semiconductor machinery',
    'Integrated circuits',
    'Iron and steel products',
    'Ships',
    'Pharmaceuticals',
    'Optical instruments',
  ),
  MX: m(
    'Automobiles',
    'Computers',
    'Crude petroleum',
    'Telecommunications equipment',
    'Trucks',
    'Auto parts',
    'Gold',
  ),
  RU: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Wheat',
    'Coal',
    'Gold',
    'Iron and steel',
  ),
  SA: m(
    'Crude petroleum',
    'Refined petroleum',
    'Petrochemicals',
    'Plastics',
    'Ammonia',
    'Aluminium',
    'Gold',
  ),
  ZA: m(
    'Platinum',
    'Gold',
    'Coal',
    'Iron ore',
    'Manganese ore',
    'Automobiles',
    'Citrus fruit',
  ),
  KR: m(
    'Semiconductors',
    'Automobiles',
    'Petroleum products',
    'Ships',
    'Petroleum',
    'Iron and steel',
    'Plastics',
  ),
  TR: m(
    'Automobiles',
    'Refined petroleum',
    'Iron and steel',
    'Textiles',
    'Machinery',
    'Gold',
    'Jewellery',
  ),
  GB: m(
    'Gold',
    'Cars',
    'Packaged medicaments',
    'Crude petroleum',
    'Gas turbines',
    'Scotch whisky',
    'Aircraft parts',
  ),
  US: m(
    'Refined petroleum',
    'Aircraft',
    'Natural gas',
    'Semiconductors',
    'Gold',
    'Soybeans',
    'Corn',
  ),
}
