import type { IgadMemberIsoCode } from './igadMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per IGAD member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const IGAD_DOMESTIC_POST_SERVICES: Record<IgadMemberIsoCode, DomesticPostService> = {
  DJ: post(
    'La Poste de Djibouti',
    'https://www.laposte.dj/',
    'poste.contact@yahoo.fr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing in Djibouti City',
  ),
  ET: post(
    'Ethiopian Postal Service (EPSE)',
    'https://www.ethiopostal.com/',
    'info@ethiopostal.com',
    '',
    '',
    'https://www.linkedin.com/company/ethiopian-postal-service/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Addis Ababa and regional centres)',
  ),
  SO: post(
    'Somali Postal Service',
    'https://www.upu.int/en/Somalia',
    'minister@mpt.gov.so',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district and landmark addressing',
  ),
  SS: post(
    'South Sudan Post',
    'http://ssscc.org/',
    'sssccngo@gmail.com',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system; Juba district addressing',
  ),
  SD: post(
    'Sudan Post (Sudapost)',
    'https://sudapost.sd/',
    'info@sudapost.sd',
    '',
    '',
    'https://www.linkedin.com/company/sudan-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11111',
    'Five-digit postcode (verify operational coverage)',
  ),
  KE: post(
    'Postal Corporation of Kenya',
    'http://posta.co.ke/',
    'customercare@posta.co.ke',
    'https://x.com/postakenya',
    'https://www.instagram.com/postakenya/',
    'https://www.linkedin.com/company/postal-corporation-of-kenya/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00100',
    'Five-digit postcode; P.O. Box culture remains common',
  ),
  UG: post(
    'Uganda Post Limited',
    'https://www.eposta.ug/',
    'info@posta.co.ug',
    'https://x.com/ugposts',
    'https://www.instagram.com/ugposts/',
    'https://www.linkedin.com/company/uganda-post-limited/',
    '',
    'none',
    '',
    '',
    'P.O. Box dominant; no universal street postcode',
  ),
}
