import type { NationalBankingInstitution } from './types'
import type { IgadMemberIsoCode } from './igadMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per IGAD member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const IGAD_NATIONAL_BANKING_INSTITUTIONS: Record<
  IgadMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  DJ: [
    bank(
      'CAC International Bank',
      '+253 21 32 22 22',
      'Place Menelik, Djibouti City, Djibouti',
      '',
      '',
      'https://www.cacbankdj.com/',
      'contact@cacbankdj.com',
      '',
      '',
      'https://www.linkedin.com/company/cac-international-bank/',
      '',
      'CACBDJDJ',
      '',
    ),
    bank(
      'Salaam African Bank',
      '+253 21 35 55 55',
      'Avenue Hassan Gouled, Djibouti City, Djibouti',
      '',
      '',
      'https://www.salaam-bank.com/',
      'info@salaam-bank.com',
      '',
      '',
      'https://www.linkedin.com/company/salaam-african-bank/',
      '',
      '',
      '',
    ),
    bank(
      'BCIMR',
      '+253 21 35 30 30',
      'Place Lagarde, Djibouti City, Djibouti',
      '',
      '',
      'https://www.bcimr.dj/',
      'contact@bcimr.dj',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  ET: [
    bank(
      'Commercial Bank of Ethiopia',
      '+251 11 551 9500',
      'Ras Desta Damtew St, Addis Ababa, Ethiopia',
      '',
      '',
      'https://www.combanketh.et/',
      'info@cbe.com.et',
      '',
      '',
      'https://www.linkedin.com/company/commercial-bank-of-ethiopia/',
      '',
      'CBETETAA',
      '',
    ),
    bank(
      'Awash Bank',
      '+251 11 558 2727',
      'Ras Abebe Aregay St, Addis Ababa, Ethiopia',
      '',
      '',
      'https://www.awashbank.com/',
      'info@awashbank.com',
      '',
      '',
      'https://www.linkedin.com/company/awash-bank/',
      '',
      'AWINETAA',
      '',
    ),
    bank(
      'Dashen Bank',
      '+251 11 518 0300',
      'Ras Abebe Aregay St, Addis Ababa, Ethiopia',
      '',
      '',
      'https://dashenbanksc.com/',
      'info@dashenbanksc.com',
      '',
      '',
      'https://www.linkedin.com/company/dashen-bank/',
      '',
      'DASHEETA',
      '',
    ),
  ],
  SO: [
    bank(
      'Salaam Somali Bank',
      '+252 61 700 0000',
      'KM4, Mogadishu, Somalia',
      '',
      '',
      'https://www.salaambank.so/',
      'info@salaambank.so',
      '',
      '',
      'https://www.linkedin.com/company/salaam-somali-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Premier Bank Somalia',
      '+252 61 222 1111',
      'Airport Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.premierbank.so/',
      'info@premierbank.so',
      '',
      '',
      'https://www.linkedin.com/company/premier-bank-somalia/',
      '',
      '',
      '',
    ),
    bank(
      'Dahabshiil Bank International',
      '+252 63 333 3000',
      'Maka Al Mukarama Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.dahabshiilbank.com/',
      'info@dahabshiilbank.com',
      '',
      '',
      'https://www.linkedin.com/company/dahabshiil-bank-international/',
      '',
      '',
      '',
    ),
  ],
  SS: [
    bank(
      'Ivory Bank',
      '+211 92 210 0000',
      'Airport Road, Juba, South Sudan',
      '',
      '',
      'https://www.ivorybankss.com/',
      'info@ivorybankss.com',
      '',
      '',
      'https://www.linkedin.com/company/ivory-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Equity Bank South Sudan',
      '+211 92 535 5555',
      'Customs Market, Juba, South Sudan',
      '',
      '',
      'https://equitygroupholdings.com/ss/',
      'info@equitybankss.com',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-limited/',
      '',
      '',
      '',
    ),
    bank(
      'Cooperative Bank of South Sudan',
      '+211 92 911 1111',
      'Nimule Street, Juba, South Sudan',
      '',
      '',
      'https://www.co-opbankss.com/',
      'info@co-opbankss.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  SD: [
    bank(
      'Bank of Khartoum',
      '+249 183 782 000',
      'Mek Nimir Ave, Khartoum, Sudan',
      '',
      '',
      'https://bankofkhartoum.com/',
      'contactus@bok.sd',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-khartoum/',
      '',
      'BOKHSDKH',
      '',
    ),
    bank(
      'Omdurman National Bank',
      '+249 183 783 200',
      'Baladia Street, Khartoum, Sudan',
      '',
      '',
      'https://www.onb-sd.com/',
      'info@onb-sd.com',
      '',
      '',
      '',
      '',
      'ONBKSDKH',
      '',
    ),
    bank(
      'Faisal Islamic Bank Sudan',
      '+249 183 774 000',
      'Al Gamhouria Street, Khartoum, Sudan',
      '',
      '',
      'https://www.fibsudan.com/',
      'info@fibsudan.com',
      '',
      '',
      'https://www.linkedin.com/company/faisal-islamic-bank-sudan/',
      '',
      'FIBSSDKH',
      '',
    ),
  ],
  KE: [
    bank(
      'KCB Bank Kenya',
      '+254 20 3270000',
      'Kencom House, Moi Avenue, Nairobi, Kenya',
      '',
      '',
      'https://ke.kcbgroup.com/',
      'contactcentre@kcbgroup.com',
      '',
      '',
      'https://www.linkedin.com/company/kcb-bank-kenya-limited/',
      '',
      'KCBLKENX',
      '',
    ),
    bank(
      'Equity Bank Kenya',
      '+254 763 000 000',
      'Equity Centre, Hospital Road, Nairobi, Kenya',
      '',
      '',
      'https://equitygroupholdings.com/ke/',
      'info@equitybank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-limited/',
      '',
      'EQBLKENA',
      '',
    ),
    bank(
      'Co-operative Bank of Kenya',
      '+254 20 2776000',
      'Co-op House, Haile Selassie Avenue, Nairobi, Kenya',
      '',
      '',
      'https://www.co-opbank.co.ke/',
      'customerservice@co-opbank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/co-operative-bank-of-kenya/',
      '',
      'KCOOKENA',
      '',
    ),
  ],
  UG: [
    bank(
      'Stanbic Bank Uganda',
      '+256 312 224 600',
      'Plot 17 Hannington Road, Kampala, Uganda',
      '',
      '',
      'https://www.stanbicbank.co.ug/',
      'customercare@stanbic.com',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-uganda/',
      '',
      'SBICUGKX',
      '',
    ),
    bank(
      'Centenary Bank',
      '+256 417 126 000',
      'Mapeera House, Kampala Road, Kampala, Uganda',
      '',
      '',
      'https://www.centenarybank.co.ug/',
      'customerservice@centenarybank.co.ug',
      '',
      '',
      'https://www.linkedin.com/company/centenary-bank-uganda/',
      '',
      'CERBUGKA',
      '',
    ),
    bank(
      'dfcu Bank',
      '+256 312 300 000',
      'Plot 26 Kyadondo Road, Kampala, Uganda',
      '',
      '',
      'https://www.dfcugroup.com/',
      'customercare@dfcugroup.com',
      '',
      '',
      'https://www.linkedin.com/company/dfcu-bank/',
      '',
      'DFCUUGKA',
      '',
    ),
  ],
}
