import type { NationalBankingInstitution } from './types'
import type { MiktaMemberIsoCode } from './miktaMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per MIKTA member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const MIKTA_NATIONAL_BANKING_INSTITUTIONS: Record<
  MiktaMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  MX: [
    bank(
      'BBVA Mexico',
      '+52 55 5621 3434',
      'Paseo de la Reforma 510, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/bbva-mexico/id375408965',
      'https://play.google.com/store/apps/details?id=com.bancomer.mbanking',
      'https://www.bbva.mx',
      'une.mx@bbva.com',
      'https://twitter.com/BBVA_Mex',
      'https://www.instagram.com/bbva_mex/',
      'https://www.linkedin.com/company/bbva-mexico/',
      '',
      'BCMRMXMM',
      '',
    ),
    bank(
      'Banorte',
      '+52 81 8156 9600',
      'Av. Revolucion 3000 Sur, Monterrey, Mexico',
      'https://apps.apple.com/mx/app/banorte-movil/id445541658',
      'https://play.google.com/store/apps/details?id=com.banorte.movil',
      'https://www.banorte.com',
      'une@banorte.com',
      'https://twitter.com/Banorte_mx',
      'https://www.instagram.com/banorte_mx/',
      'https://www.linkedin.com/company/grupo-financiero-banorte/',
      '',
      'MENOMXMT',
      '',
    ),
    bank(
      'Citibanamex',
      '+52 55 1226 2639',
      'Isabel la Catolica 44, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/citibanamex-movil/id394943449',
      'https://play.google.com/store/apps/details?id=com.citibanamex.banamexmobile',
      'https://www.banamex.com',
      'atencionaclientes@citibanamex.com',
      'https://twitter.com/Citibanamex',
      'https://www.instagram.com/citibanamex/',
      'https://www.linkedin.com/company/citibanamex/',
      '',
      'BNMXMXMM',
      '',
    ),
  ],
  ID: [
    bank(
      'Bank Mandiri',
      '+62 21 5299 7777',
      'Plaza Mandiri, Jl. Jend. Gatot Subroto, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/livin-by-mandiri/id1555417419',
      'https://play.google.com/store/apps/details?id=id.bmri.livin',
      'https://www.bankmandiri.co.id',
      'mandiricare@bankmandiri.co.id',
      'https://twitter.com/bankmandiri',
      'https://www.instagram.com/bankmandiri/',
      'https://www.linkedin.com/company/bankmandiri/',
      '',
      'BMRIIDJA',
      '',
    ),
    bank(
      'Bank Central Asia',
      '+62 21 2358 8000',
      'Menara BCA, Grand Indonesia, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/mybca/id1465918716',
      'https://play.google.com/store/apps/details?id=com.bca.mybca.omni.android',
      'https://www.bca.co.id',
      'halobca@bca.co.id',
      'https://twitter.com/BankBCA',
      'https://www.instagram.com/goodlifebca/',
      'https://www.linkedin.com/company/pt-bank-central-asia-tbk/',
      '',
      'CENAIDJA',
      '',
    ),
    bank(
      'Bank Negara Indonesia',
      '+62 21 5728387',
      'Jl. Jend. Sudirman Kav. 1, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/wondr-by-bni/id6474669196',
      'https://play.google.com/store/apps/details?id=id.co.bni.newagenbni46',
      'https://www.bni.co.id',
      'bnicall@bni.co.id',
      'https://twitter.com/BNI',
      'https://www.instagram.com/bni46/',
      'https://www.linkedin.com/company/pt-bank-negara-indonesia-persero-tbk/',
      '',
      'BNINIDJA',
      '',
    ),
  ],
  KR: [
    bank(
      'KB Kookmin Bank',
      '+82 2 2073 7114',
      '26 Gukjegeumyung-ro 8-gil, Yeongdeungpo-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/kb-star-banking/id373742138',
      'https://play.google.com/store/apps/details?id=com.kbstar.kbbank',
      'https://www.kbstar.com',
      'kbkookminbank@kbfg.com',
      'https://twitter.com/KBFinancialGroup',
      '',
      'https://www.linkedin.com/company/kb-financial-group/',
      '',
      'CZNBKRSE',
      '',
    ),
    bank(
      'Shinhan Bank',
      '+82 2 756 0505',
      '20 Sejong-daero 9-gil, Jung-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/shinhan-sol-global/id1363654579',
      'https://play.google.com/store/apps/details?id=com.shinhan.globalbank',
      'https://www.shinhan.com',
      'global@shinhan.com',
      'https://twitter.com/ShinhanBank',
      '',
      'https://www.linkedin.com/company/shinhan-bank/',
      '',
      'SHBKKRSE',
      '',
    ),
    bank(
      'Woori Bank',
      '+82 2 2002 3000',
      '51 Sogong-ro, Jung-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/woori-won-banking/id1430145879',
      'https://play.google.com/store/apps/details?id=com.wooribank.smart.npib',
      'https://www.wooribank.com',
      'wbmaster@wooribank.com',
      'https://twitter.com/WooriBank',
      '',
      'https://www.linkedin.com/company/woori-bank/',
      '',
      'HVBKKRSE',
      '',
    ),
  ],
  TR: [
    bank(
      'Turkiye Is Bankasi',
      '+90 212 316 0000',
      'Is Kuleleri, Levent, Istanbul, Turkiye',
      '',
      '',
      'https://www.isbank.com.tr',
      'musteriiliskileri@isbank.com.tr',
      '',
      '',
      '',
      '',
      'ISBKTRIS',
      '',
    ),
    bank(
      'Ziraat Bankasi',
      '+90 312 584 2000',
      'Doganbey Mah. Ataturk Bulvari, Ankara, Turkiye',
      '',
      '',
      'https://www.ziraatbank.com.tr',
      'iletisim@ziraatbank.com.tr',
      '',
      '',
      '',
      '',
      'TCZBTR2A',
      '',
    ),
    bank(
      'Garanti BBVA',
      '+90 212 318 1818',
      'Levent Nispetiye Mah., Istanbul, Turkiye',
      '',
      '',
      'https://www.garantibbva.com.tr',
      'iletisim@garantibbva.com.tr',
      '',
      '',
      '',
      '',
      'TGBATRIS',
      '',
    ),
  ],
  AU: [
    bank(
      'Commonwealth Bank of Australia',
      '+61 13 2221',
      'Ground Floor, Tower 1, 201 Sussex Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/commbank/id310251020',
      'https://play.google.com/store/apps/details?id=com.commbank.netbank',
      'https://www.commbank.com.au',
      'customercare@cba.com.au',
      'https://twitter.com/CommBank',
      'https://www.instagram.com/commbank/',
      'https://www.linkedin.com/company/commonwealth-bank/',
      '',
      'CTBAAU2S',
      'https://api.commbank.com.au',
    ),
    bank(
      'Westpac Banking Corporation',
      '+61 13 2032',
      '275 Kent Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/westpac-mobile-banking/id284826145',
      'https://play.google.com/store/apps/details?id=org.westpac.bank',
      'https://www.westpac.com.au',
      'customercare@westpac.com.au',
      'https://twitter.com/Westpac',
      'https://www.instagram.com/westpac/',
      'https://www.linkedin.com/company/westpac/',
      '',
      'WPACAU2S',
      'https://developer.westpac.com.au',
    ),
    bank(
      'Australia and New Zealand Banking Group',
      '+61 13 13 14',
      '833 Collins Street, Docklands, VIC, Australia',
      'https://apps.apple.com/au/app/anz-australia/id385348415',
      'https://play.google.com/store/apps/details?id=com.anz.android',
      'https://www.anz.com.au',
      'contactus@anz.com',
      'https://twitter.com/ANZ_AU',
      'https://www.instagram.com/anz_au/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBAU3M',
      'https://developer.anz.com',
    ),
  ],
}
