import type { CorporationFormationOffice } from './types'
import type { OpecMemberIsoCode } from './opecMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per OPEC member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const OPEC_CORPORATION_FORMATION_OFFICES: Record<OpecMemberIsoCode, CorporationFormationOffice> = {
  DZ:   office(
    'Centre National du Registre du Commerce (CNRC)',
    '+213 23 50 34 34',
    'Route nationale no 24, Lido, Mohammadia, Algiers, Algeria',
    'https://sidjilcom.cnrc.dz',
    'contact@cnrc.dz',
    '',
    '',
    'https://www.linkedin.com/company/cnrc-algerie/',
    'https://sidjilcom.cnrc.dz/inscription',
    'https://sidjilcom.cnrc.dz/faq',
    'Numero du Registre du Commerce (NRC)',
  ),
  CG:   office(
    'Centre de Formalites Administratives des Entreprises (CFE Congo)',
    '+242 06 665 77 77',
    'Avenue Amilcar Cabral, Brazzaville, Republic of the Congo',
    'https://cfe.cg',
    'contact@cfe.cg',
    '',
    '',
    '',
    'https://cfe.cg/creer-entreprise',
    'https://cfe.cg/guide-des-formalites',
    'Numero RCCM',
  ),
  GQ:   office(
    'Ventanilla Unica Empresarial - Ministerio de Comercio (Equatorial Guinea)',
    '+240 333 09 50 00',
    'Avenida de la Independencia, Malabo, Equatorial Guinea',
    'https://www.guineaecuatorialpress.com',
    'comercio@guineaecuatorial-gob.com',
    '',
    '',
    '',
    'https://www.guineaecuatorialpress.com/noticias/ventanilla_unica_empresarial',
    '',
    'Numero de Registro Mercantil',
  ),
  GA:   office(
    'Agence Nationale de Promotion des Investissements du Gabon (ANPI-Gabon)',
    '+241 01 79 20 00',
    'Immeuble Arambo, Libreville, Gabon',
    'https://www.investingabon.ga',
    'contact@investingabon.ga',
    '',
    '',
    'https://www.linkedin.com/company/anpi-gabon/',
    'https://www.investingabon.ga/creer-mon-entreprise',
    'https://www.investingabon.ga/guide-createur',
    'Numero RCCM',
  ),
  IR:   office(
    'Companies Registration Office Iran',
    '+98 21 8888 0000',
    'Tehran, Iran',
    'https://www.irimc.org',
    '',
    '',
    '',
    '',
    'https://www.irimc.org',
    'https://www.irimc.org/en/company-registration',
    'National ID (Shenase Melli)',
  ),
  IQ:   office(
    'Companies Registration Directorate (Ministry of Trade)',
    '+964 790 019 0274',
    'Bab Al-Muadham, Baghdad, Iraq',
    'https://mot.gov.iq',
    '',
    '',
    '',
    '',
    'https://mot.gov.iq',
    'https://mot.gov.iq/ar/services',
    'Company Registration Number',
  ),
  KW:   office(
    'Kuwait Business Center (Ministry of Commerce and Industry)',
    '+965 2248 0000',
    'Kuwait City, Kuwait',
    'https://www.moci.gov.kw',
    '',
    '',
    '',
    '',
    'https://e.gov.kw/sites/kgoenglish/Pages/eServices/MOCI/CommercialLicensing.aspx',
    'https://e.gov.kw/sites/kgoenglish/Pages/Services/MOCI/CommercialLicense.aspx',
    'Commercial License Number',
  ),
  LY:   office(
    'Ministry of Economy and Trade Libya - Commercial Registry Department',
    '+218 21 335 0380',
    'Al-Sikka Road, Tripoli, Libya',
    'https://www.economy.gov.ly',
    'info@economy.gov.ly',
    '',
    '',
    '',
    'https://www.economy.gov.ly/services/commercial-register',
    '',
    'Commercial Registration Number',
  ),
  NG:   office(
    'Corporate Affairs Commission (CAC Nigeria)',
    '+234 700 022 2255',
    'Plot 420, Tigris Crescent, Maitama, Abuja, Nigeria',
    'https://www.cac.gov.ng',
    'enquiries@cac.gov.ng',
    'https://x.com/cacnigeria1',
    'https://www.instagram.com/cacnigeria/',
    'https://www.linkedin.com/company/corporate-affairs-commission-nigeria/',
    'https://pre.cac.gov.ng/register',
    'https://www.cac.gov.ng/resources',
    'Registration Number (RC Number)',
  ),
  SA:   office(
    'Ministry of Commerce Saudi Arabia (Business Platform)',
    '+966 1900',
    'Riyadh, Saudi Arabia',
    'https://mc.gov.sa',
    '',
    '',
    '',
    '',
    'https://business.sa',
    'https://mc.gov.sa/ar/eservices/Pages/default.aspx',
    'Commercial Registration (CR) Number',
  ),
  AE:   office(
    'UAE National Economic Register (Ministry of Economy)',
    '+971 8001222',
    'Ministry of Economy, Abu Dhabi, United Arab Emirates',
    'https://ner.economy.ae',
    'info@economy.ae',
    '',
    '',
    'https://www.linkedin.com/company/ministry-of-economy-uae/',
    'https://ner.economy.ae',
    'https://u.ae/en/information-and-services/business/starting-a-business',
    'Trade License Number',
  ),
  VE:   office(
    'National Superintendency of Foreign Trade Venezuela (SUNACRIP / registro mercantil)',
    '+58 212 408 4000',
    'Caracas, Venezuela',
    'https://www.mppef.gob.ve',
    '',
    '',
    '',
    '',
    'https://www.mppef.gob.ve',
    'https://www.mppef.gob.ve/registro-mercantil',
    'RIF (Registro de Informacion Fiscal)',
  ),
}
