import type { OpecMemberIsoCode } from './opecMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per OPEC member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const OPEC_DOMESTIC_POST_SERVICES: Record<OpecMemberIsoCode, DomesticPostService> = {
  DZ: post(
    'Algérie Poste',
    'https://www.poste.dz/',
    'contact@poste.dz',
    'https://x.com/AlgPoste',
    'https://www.instagram.com/postealgerie/',
    'https://www.linkedin.com/company/algerie-poste/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '16000',
    'Five-digit postcode (wilaya + delivery area)',
  ),
  CG: post(
    'La Poste du Congo EMS',
    'http://laposte.cg/',
    'contact@lacongolaise.cg',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-congo/',
    '',
    'none',
    '',
    '',
    'No national postcode; Brazzaville/Pointe-Noire district addressing',
  ),
  GQ: post(
    'Correos de Guinea Ecuatorial',
    'https://www.correosgq.com/',
    'info@correosgq.com',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; Malabo/Bata addressing',
  ),
  GA: post(
    'Gabon Poste EMS',
    'https://www.gabonpost.ga/',
    'infos@gpost.ga',
    '',
    '',
    'https://www.linkedin.com/company/gabon-poste/',
    '',
    'none',
    '',
    '',
    'No national postcode; Libreville/Port-Gentil district addressing',
  ),
  IR: post(
    'Iran Post (Pishtaz)',
    'https://www.post.ir/',
    'info@post.ir',
    'https://x.com/IranPost',
    '',
    'https://www.linkedin.com/company/iran-post/',
    '',
    'NNNNN-NNNNN',
    '^\\d{5}-\\d{5}$',
    '13147-13146',
    'Ten-digit postcode (five + hyphen + five)',
  ),
  IQ: post(
    'Iraqi Post (Iraq Post Company)',
    'https://www.iraqpost.net/',
    'info@iraqpost.net',
    '',
    '',
    'https://www.linkedin.com/company/iraq-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10001',
    'Five-digit postcode',
  ),
  KW: post(
    'Kuwait Post',
    'https://www.kuwaitpost.com/',
    'info@kuwaitpost.com',
    'https://x.com/KuwaitPost',
    'https://www.instagram.com/kuwaitpost/',
    'https://www.linkedin.com/company/kuwait-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '13001',
    'Five-digit postcode',
  ),
  LY: post(
    'Libyan Post Company',
    'http://nlpc.ly/',
    'info@nlpc.ly',
    '',
    '',
    'https://www.linkedin.com/company/libyan-post/',
    '',
    'none',
    '',
    '',
    'No consistent national postcode published; verify locally',
  ),
  NG: post(
    'Nigeria Postal Service (NIPOST)',
    'http://nipost.gov.ng/',
    'info@nipost.gov.ng',
    'https://x.com/e_nipost',
    'https://www.instagram.com/e_nipost/',
    'https://www.linkedin.com/company/nipost/',
    '',
    'NNNNNN',
    '^\\\\d{6}$',
    '100001',
    'Six-digit postcode (state + LGA + delivery)',
  ),
  SA: post(
    'Saudi Post (SPL)',
    'https://splonline.com.sa/',
    'customercare@splonline.com.sa',
    'https://x.com/SPLCare',
    'https://www.instagram.com/splcare/',
    'https://www.linkedin.com/company/saudi-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11564',
    'Five-digit postcode (national addressing system)',
  ),
  AE: post(
    'Emirates Post Group',
    'https://www.epg.ae/',
    'info@epg.ae',
    'https://x.com/EmiratesPost',
    'https://www.instagram.com/emiratespost/',
    'https://www.linkedin.com/company/emirates-post-group/',
    '',
    'none',
    '',
    '',
    'No national postcode; Makani / building addressing in UAE',
  ),
  VE: post(
    'IPOSTEL (Correo de Venezuela)',
    'https://www.ipostel.gob.ve/',
    'info@ipostel.gob.ve',
    '',
    '',
    '',
    '',
    'NNNN',
    '^\\d{4}$',
    '1010',
    'Four-digit código postal (Caracas)',
  ),
}
