import type { OpecMemberIsoCode } from './opecMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const OPEC_MAIN_INTERNATIONAL_AIRPORTS: Record<OpecMemberIsoCode, MainInternationalAirport> = {
  DZ: {
    name: 'Houari Boumediene Airport (ALG)',
    website: 'https://www.aeroportalger.dz/',
    email: 'contact@aeroportalger.dz',
    twitter: 'https://x.com/AeroportALG',
    instagram: 'https://www.instagram.com/aeroportalger/',
    linkedin: 'https://www.linkedin.com/company/egsa-alger/',
    apiEndpoint: '',
  },
  CG: {
    name: 'Maya-Maya International Airport (BZV)',
    website: 'https://www.aeroport-brazzaville.cg/',
    email: 'contact@aeroport-brazzaville.cg',
    twitter: 'https://x.com/AeroportBZV',
    instagram: 'https://www.instagram.com/aeroportbrazzaville/',
    linkedin: 'https://www.linkedin.com/company/aeroport-maya-maya/',
    apiEndpoint: '',
  },
  GQ: {
    name: 'Malabo International Airport (SSG)',
    website: 'https://www.aeropuerto-malabo.gq/',
    email: 'info@aeropuerto-malabo.gq',
    twitter: 'https://x.com/AeropuertoSSG',
    instagram: 'https://www.instagram.com/aeropuertomalabo/',
    linkedin: 'https://www.linkedin.com/company/aeropuerto-internacional-malabo/',
    apiEndpoint: '',
  },
  GA: {
    name: 'Libreville Leon M\'ba International Airport (LBV)',
    website: 'https://www.aeroport-libreville.ga/',
    email: 'contact@aeroport-libreville.ga',
    twitter: 'https://x.com/AeroportLBV',
    instagram: 'https://www.instagram.com/aeroportlibreville/',
    linkedin: 'https://www.linkedin.com/company/aeroport-leon-mba/',
    apiEndpoint: '',
  },
  IR: {
    name: 'Imam Khomeini International Airport (IKA)',
    website: 'https://www.ikac.ir/',
    email: 'info@ikac.ir',
    twitter: 'https://x.com/IKA_Airport',
    instagram: 'https://www.instagram.com/ika_airport/',
    linkedin: 'https://www.linkedin.com/company/imam-khomeini-international-airport/',
    apiEndpoint: '',
  },
  IQ: {
    name: 'Baghdad International Airport (BGW)',
    website: 'https://www.bgw.aero/',
    email: 'info@bgw.aero',
    twitter: 'https://x.com/BaghdadAirport',
    instagram: 'https://www.instagram.com/baghdadairport/',
    linkedin: 'https://www.linkedin.com/company/baghdad-international-airport/',
    apiEndpoint: '',
  },
  KW: {
    name: 'Kuwait International Airport (KWI)',
    website: 'https://www.kuwait-airport.com.kw/',
    email: 'info@kuwait-airport.com.kw',
    twitter: 'https://x.com/KuwaitAirport',
    instagram: 'https://www.instagram.com/kuwaitairport/',
    linkedin: 'https://www.linkedin.com/company/kuwait-airports/',
    apiEndpoint: '',
  },
  LY: {
    name: 'Mitiga International Airport (MJI)',
    website: 'https://www.lycaa.gov.ly/',
    email: 'info@lycaa.gov.ly',
    twitter: 'https://x.com/LYCAA_Libya',
    instagram: 'https://www.instagram.com/lycaa_libya/',
    linkedin: 'https://www.linkedin.com/company/libyan-civil-aviation-authority/',
    apiEndpoint: '',
  },
  NG: {
    name: 'Murtala Muhammed International Airport (LOS)',
    website: 'https://www.faan.gov.ng/',
    email: 'info@faan.gov.ng',
    twitter: 'https://x.com/FAAN_Official',
    instagram: 'https://www.instagram.com/faan_official/',
    linkedin: 'https://www.linkedin.com/company/federal-airports-authority-of-nigeria/',
    apiEndpoint: '',
  },
  SA: {
    name: 'King Khalid International Airport (RUH)',
    website: 'https://www.riyadhairports.com/',
    email: 'info@riyadhairports.com',
    twitter: 'https://x.com/RUH_Airport',
    instagram: 'https://www.instagram.com/ruh_airport/',
    linkedin: 'https://www.linkedin.com/company/riyadh-airports-company/',
    apiEndpoint: '',
  },
  AE: {
    name: 'Zayed International Airport (AUH)',
    website: 'https://www.zayedinternationalairport.ae/',
    email: 'info@adairports.ae',
    twitter: 'https://x.com/ZayedAirport',
    instagram: 'https://www.instagram.com/zayedairport/',
    linkedin: 'https://www.linkedin.com/company/abu-dhabi-airports/',
    apiEndpoint: '',
  },
  VE: {
    name: 'Simón Bolívar International Airport (CCS)',
    website: 'https://www.aeropuerto-maiquetia.com.ve/',
    email: 'info@aeropuerto-maiquetia.com.ve',
    twitter: 'https://x.com/CCSAirport',
    instagram: 'https://www.instagram.com/ccsairport/',
    linkedin: 'https://www.linkedin.com/company/simon-bolivar-international-airport/',
    apiEndpoint: '',
  },
}
