import type { OpecMemberIsoCode } from './opecMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per OPEC member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const OPEC_MAIN_INTERNATIONAL_SEAPORTS: Record<OpecMemberIsoCode, MainInternationalSeaport> = {
  DZ: seaport(
    'Port of Algiers',
    'https://www.epal.dz/',
    'contact@epal.dz',
    'https://x.com/EPA_Alger',
    'https://www.instagram.com/epa_alger/',
    'https://www.linkedin.com/company/entreprise-portuaire-d-alger/',
    'douane@douane.gov.dz',
    'https://www.douane.gov.dz',
    'Direction Générale des Douanes — Port d\'Alger, Alger, Algeria',
  ),
  CG: seaport(
    'Port of Pointe-Noire',
    'https://www.otal.com/congo/port-of-pointe-noire',
    'contact@port-noire.cg',
    'https://x.com/PortPointeNoire',
    'https://www.instagram.com/portpointenoire/',
    'https://www.linkedin.com/company/port-autonome-de-pointe-noire/',
    'douanes@finances.cg',
    'https://www.douanes.cg',
    'Direction Générale des Douanes — Port de Pointe-Noire, Pointe-Noire, Republic of the Congo',
  ),
  GQ: seaport(
    'Port of Bata',
    'https://www.otal.com/equatorial-guinea/port-of-bata',
    'contact@portbata.gq',
    'https://x.com/PortBata',
    'https://www.instagram.com/portbata/',
    'https://www.linkedin.com/company/port-of-bata/',
    'aduana@guineaecuatorial.gq',
    'https://www.aduana.gq',
    'Aduana de Guinea Ecuatorial — Puerto de Bata, Bata, Equatorial Guinea',
  ),
  GA: seaport(
    'Port of Owendo',
    'https://www.otal.com/gabon/port-of-owendo',
    'contact@port-gentil.ga',
    'https://x.com/PortOwendo',
    'https://www.instagram.com/portowendo/',
    'https://www.linkedin.com/company/port-d-owendo/',
    'douanes@finances.ga',
    'https://www.douanes.ga',
    'Direction Générale des Douanes — Port d\'Owendo, Owendo, Gabon',
  ),
  IR: seaport(
    'Port of Bandar Abbas (Shahid Rajaee)',
    'https://www.pmo.ir/',
    'info@pmo.ir',
    'https://x.com/PortsMaritimeIR',
    'https://www.instagram.com/pmo_ir/',
    'https://www.linkedin.com/company/ports-and-maritime-organization/',
    'customs@irica.gov.ir',
    'https://www.irica.gov.ir',
    'Iran Customs — Shahid Rajaee Port, Bandar Abbas, Iran',
  ),
  IQ: seaport(
    'Umm Qasr Port',
    'https://www.scop.gov.iq/',
    'info@scop.gov.iq',
    'https://x.com/IraqPorts',
    'https://www.instagram.com/iraqports/',
    'https://www.linkedin.com/company/state-company-of-ports-iraq/',
    'customs@customs.gov.iq',
    'https://www.customs.gov.iq',
    'Iraqi Customs — Umm Qasr Port, Basra Governorate, Iraq',
  ),
  KW: seaport(
    'Shuwaikh Port',
    'https://www.pak.gov.kw/',
    'info@pak.gov.kw',
    'https://x.com/KuwaitPorts',
    'https://www.instagram.com/kuwaitports/',
    'https://www.linkedin.com/company/ports-authority-kuwait/',
    'customs@customs.gov.kw',
    'https://www.customs.gov.kw',
    'Kuwait General Administration of Customs — Shuwaikh Port, Kuwait City, Kuwait',
  ),
  LY: seaport(
    'Port of Tripoli',
    'https://www.lpc.ly/',
    'info@lpc.ly',
    'https://x.com/LibyanPorts',
    'https://www.instagram.com/libyanports/',
    'https://www.linkedin.com/company/libyan-ports-corporation/',
    'customs@customs.gov.ly',
    'https://www.customs.gov.ly',
    'Libyan Customs Authority — Port of Tripoli, Tripoli, Libya',
  ),
  NG: seaport(
    'Port of Lagos (Apapa)',
    'https://www.npa.gov.ng/',
    'info@npa.gov.ng',
    'https://x.com/NPA_Nigeria',
    'https://www.instagram.com/npa_nigeria/',
    'https://www.linkedin.com/company/nigerian-ports-authority/',
    'customs@customs.gov.ng',
    'https://www.customs.gov.ng',
    'Nigeria Customs Service — Apapa Port, Lagos, Nigeria',
  ),
  SA: seaport(
    'King Abdullah Port',
    'https://www.ka-port.com.sa/',
    'info@ka-port.com.sa',
    'https://x.com/KingAbdullahPort',
    'https://www.instagram.com/kingabdullahport/',
    'https://www.linkedin.com/company/king-abdullah-port/',
    'customs@zatca.gov.sa',
    'https://www.zatca.gov.sa',
    'ZATCA Customs — King Abdullah Port, Rabigh, Saudi Arabia',
  ),
  AE: seaport(
    'Jebel Ali Port (Dubai)',
    'https://www.dpworld.com/uae',
    'info@dpworld.com',
    'https://x.com/DP_World',
    'https://www.instagram.com/dpworld/',
    'https://www.linkedin.com/company/dp-world/',
    'customs@customs.ae',
    'https://www.customs.ae',
    'Federal Customs Authority — Jebel Ali Port, Dubai, United Arab Emirates',
  ),
  VE: seaport(
    'Port of La Guaira',
    'https://www.bolipuertos.gob.ve/',
    'info@bolipuertos.gob.ve',
    'https://x.com/Bolipuertos',
    'https://www.instagram.com/bolipuertos/',
    'https://www.linkedin.com/company/bolipuertos/',
    'aduana@sencamer.gob.ve',
    'https://www.seniat.gob.ve',
    'SENIAT Aduanas — Puerto de La Guaira, La Guaira, Venezuela',
  ),
}
