import type { NationalBankingInstitution } from './types'
import type { OpecMemberIsoCode } from './opecMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per OPEC member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const OPEC_NATIONAL_BANKING_INSTITUTIONS: Record<
  OpecMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  DZ: [
    bank(
      'Banque Exterieure d Algerie (BEA)',
      '+213 21 98 02 98',
      '11 Rue Colonel Amirouche, Algiers, Algeria',
      '',
      '',
      'https://www.bea.dz/',
      'contact@bea.dz',
      '',
      '',
      'https://www.linkedin.com/company/bea-algerie/',
      '',
      '',
      '',
    ),
    bank(
      'Banque Nationale d Algerie (BNA)',
      '+213 21 63 56 56',
      '8 Boulevard Ernesto Che Guevara, Algiers, Algeria',
      '',
      '',
      'https://www.bna.dz/',
      'contact@bna.dz',
      '',
      '',
      'https://www.linkedin.com/company/banque-nationale-d-alg%C3%A9rie/',
      '',
      '',
      '',
    ),
    bank(
      'Credit Populaire d Algerie (CPA)',
      '+213 21 63 55 55',
      '2 Boulevard Colonel Amirouche, Algiers, Algeria',
      '',
      '',
      'https://www.cpa-bank.dz/',
      'contact@cpa-bank.dz',
      '',
      '',
      'https://www.linkedin.com/company/credit-populaire-d-algerie/',
      '',
      '',
      '',
    ),
  ],
  CG: [
    bank(
      'Ecobank Congo',
      '+242 06 508 0000',
      'Avenue Amilcar Cabral, Brazzaville, Republic of the Congo',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/cg',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCCGCG',
      '',
    ),
    bank(
      'BGFI Bank Congo',
      '+242 06 695 01 01',
      'Avenue Poincare, Brazzaville, Republic of the Congo',
      '',
      '',
      'https://www.bgfibank.com/',
      'contact@bgfibank.com',
      '',
      '',
      'https://www.linkedin.com/company/bgfi-holding-corporation/',
      '',
      'BGFICGCG',
      '',
    ),
    bank(
      'Banque Postale du Congo',
      '+242 05 559 9922',
      'Avenue de la Paix, Brazzaville, Republic of the Congo',
      '',
      '',
      'https://www.bpc.cg/',
      'contact@bpc.cg',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  GQ: [
    bank(
      'BANGE',
      '+240 333 09 46 00',
      'Avenida de la Independencia, Malabo, Equatorial Guinea',
      '',
      '',
      'https://www.bange.es/',
      'atencion.cliente@bange.es',
      '',
      '',
      'https://www.linkedin.com/company/banco-nacional-de-guinea-ecuatorial/',
      '',
      'BANGGQGQ',
      '',
    ),
    bank(
      'CCEI Bank Guinea Ecuatorial',
      '+240 333 09 21 00',
      'Carretera del Aeropuerto, Malabo, Equatorial Guinea',
      '',
      '',
      'https://www.cceibankge.com/',
      'contact@cceibankge.com',
      '',
      '',
      '',
      '',
      'CCEIGQGQ',
      '',
    ),
    bank(
      'BGFI Bank Guinea Ecuatorial',
      '+240 333 09 66 00',
      'Avenida Hassan II, Malabo, Equatorial Guinea',
      '',
      '',
      'https://www.bgfibank.com/',
      'contact@bgfibank.com',
      '',
      '',
      'https://www.linkedin.com/company/bgfi-holding-corporation/',
      '',
      'BGFIGQGQ',
      '',
    ),
  ],
  GA: [
    bank(
      'BGFI Bank Gabon',
      '+241 11 79 54 00',
      'Avenue Savorgnan de Brazza, Libreville, Gabon',
      '',
      '',
      'https://www.bgfibank.com/',
      'contact@bgfibank.com',
      '',
      '',
      'https://www.linkedin.com/company/bgfi-holding-corporation/',
      '',
      'BGFIGALI',
      '',
    ),
    bank(
      'UBA Gabon',
      '+241 11 44 11 11',
      'Boulevard de l Independance, Libreville, Gabon',
      '',
      '',
      'https://www.ubagroup.com/',
      'cfc@ubagroup.com',
      '',
      '',
      'https://www.linkedin.com/company/united-bank-for-africa/',
      '',
      'UNAFGALI',
      '',
    ),
    bank(
      'Ecobank Gabon',
      '+241 01 44 12 12',
      'Avenue du Colonel Parant, Libreville, Gabon',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/ga',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCGALI',
      '',
    ),
  ],
  IR: [
    bank(
      'Bank Melli Iran',
      '+98 21 64140',
      'Ferdowsi Ave, Tehran, Iran',
      '',
      '',
      'https://www.bmi.ir',
      'info@bmi.ir',
      '',
      '',
      '',
      '',
      'MELIIRTH',
      '',
    ),
    bank(
      'Bank Mellat',
      '+98 21 82980',
      'Valiasr Ave, Tehran, Iran',
      '',
      '',
      'https://www.bankmellat.ir',
      'info@bankmellat.ir',
      '',
      '',
      '',
      '',
      'BKMTIRTH',
      '',
    ),
    bank(
      'Bank Tejarat',
      '+98 21 8880 4500',
      'Taleghani Ave, Tehran, Iran',
      '',
      '',
      'https://www.tejaratbank.ir',
      'info@tejaratbank.ir',
      '',
      '',
      '',
      '',
      'BTEJIRTH',
      '',
    ),
  ],
  IQ: [
    bank(
      'Rafidain Bank',
      '+964 1 8177600',
      'Al-Rasheed Street, Baghdad, Iraq',
      '',
      '',
      'https://rafidain-bank.gov.iq',
      'info@rafidain-bank.gov.iq',
      '',
      '',
      '',
      '',
      'RAFDIQBA',
      '',
    ),
    bank(
      'Trade Bank of Iraq',
      '+964 1 7739444',
      'Al-Karrada, Baghdad, Iraq',
      '',
      '',
      'https://www.tbiraq.com',
      'info@tbiraq.com',
      '',
      '',
      'https://www.linkedin.com/company/trade-bank-of-iraq/',
      '',
      'TRIQIQBA',
      '',
    ),
    bank(
      'National Bank of Iraq',
      '+964 1 7198066',
      'Arasat Al-Hindiyah, Baghdad, Iraq',
      '',
      '',
      'https://nbi.iq',
      'info@nbi.iq',
      'https://twitter.com/nbi_iraq',
      'https://www.instagram.com/nbi_iraq/',
      'https://www.linkedin.com/company/national-bank-of-iraq/',
      '',
      'NBIQIQBA',
      '',
    ),
  ],
  KW: [
    bank(
      'National Bank of Kuwait',
      '+965 1801801',
      'Abdullah Al-Ahmad Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/nbk-mobile-banking/id380982741',
      'https://play.google.com/store/apps/details?id=com.nbk',
      'https://www.nbk.com',
      'customer.relations@nbk.com',
      'https://twitter.com/NBKPage',
      'https://www.instagram.com/nbkpage/',
      'https://www.linkedin.com/company/national-bank-of-kuwait/',
      '',
      'NBOKKWKW',
      '',
    ),
    bank(
      'Kuwait Finance House',
      '+965 1803333',
      'KFH Tower, Abdullah Al-Mubarak Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/kfhonline/id570920246',
      'https://play.google.com/store/apps/details?id=com.kfh',
      'https://www.kfh.com',
      'contactus@kfh.com',
      'https://twitter.com/KFHGroup',
      'https://www.instagram.com/kfhgroup/',
      'https://www.linkedin.com/company/kuwait-finance-house/',
      '',
      'KFHOKWKW',
      '',
    ),
    bank(
      'Burgan Bank',
      '+965 1804080',
      'Al-Shuhada Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/burgan-bank/id596108948',
      'https://play.google.com/store/apps/details?id=com.burganbank.mobile',
      'https://www.burgan.com',
      'contactus@burgan.com',
      'https://twitter.com/BurganBank',
      'https://www.instagram.com/burganbank/',
      'https://www.linkedin.com/company/burgan-bank/',
      '',
      'BRGNKWKW',
      '',
    ),
  ],
  LY: [
    bank(
      'Wahda Bank',
      '+218 21 333 5511',
      'Omar Mukhtar Street, Tripoli, Libya',
      '',
      '',
      'https://wahdabank.ly/',
      'info@wahdabank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Jumhouria Bank',
      '+218 21 360 2000',
      'Al Fatah Street, Tripoli, Libya',
      '',
      '',
      'https://www.jbank.ly/',
      'info@jbank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'National Commercial Bank Libya',
      '+218 21 444 9200',
      'September 1st Street, Tripoli, Libya',
      '',
      '',
      'https://www.ncb.ly/',
      'info@ncb.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  NG: [
    bank(
      'Access Bank Nigeria',
      '+234 1 271 2005',
      '14/15 Prince Alaba Oniru St, Victoria Island, Lagos, Nigeria',
      '',
      '',
      'https://www.accessbankplc.com/',
      'contactcenter@accessbankplc.com',
      '',
      '',
      'https://www.linkedin.com/company/access-bank-plc/',
      '',
      'ABNGNGLA',
      '',
    ),
    bank(
      'First Bank of Nigeria',
      '+234 1 905 2326',
      'Samuel Asabia House, 35 Marina, Lagos, Nigeria',
      '',
      '',
      'https://www.firstbanknigeria.com/',
      'firstcontact@firstbanknigeria.com',
      '',
      '',
      'https://www.linkedin.com/company/first-bank-of-nigeria-limited/',
      '',
      'FBNINGLA',
      '',
    ),
    bank(
      'Zenith Bank Nigeria',
      '+234 1 278 7000',
      'Plot 84 Ajose Adeogun St, Victoria Island, Lagos, Nigeria',
      '',
      '',
      'https://www.zenithbank.com/',
      'zenithdirect@zenithbank.com',
      '',
      '',
      'https://www.linkedin.com/company/zenith-bank-plc/',
      '',
      'ZEIBNGLA',
      '',
    ),
  ],
  SA: [
    bank(
      'Saudi National Bank',
      '+966 920001000',
      'King Saud Road, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/alahlimobile/id470322247',
      'https://play.google.com/store/apps/details?id=com.alahli.mobile',
      'https://www.alahli.com',
      'care@alahli.com',
      'https://twitter.com/SNBAlAhli',
      'https://www.instagram.com/snbalahli/',
      'https://www.linkedin.com/company/snbaik/',
      '',
      'NCBKSAJE',
      '',
    ),
    bank(
      'Al Rajhi Bank',
      '+966 920003344',
      'Olaya Street, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/al-rajhi-bank/id563339275',
      'https://play.google.com/store/apps/details?id=com.alrajhibank.mobile',
      'https://www.alrajhibank.com.sa',
      'care@alrajhibank.com.sa',
      'https://twitter.com/AlRajhiBank',
      'https://www.instagram.com/alrajhibank/',
      'https://www.linkedin.com/company/alrajhibank/',
      '',
      'RJHISARI',
      '',
    ),
    bank(
      'Riyad Bank',
      '+966 920002470',
      'King Fahd Road, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/riyad-mobile/id593620831',
      'https://play.google.com/store/apps/details?id=com.riyadbank.mobile',
      'https://www.riyadbank.com',
      'customercare@riyadbank.com',
      'https://twitter.com/RiyadBank',
      'https://www.instagram.com/riyadbank/',
      'https://www.linkedin.com/company/riyad-bank/',
      '',
      'RIBLSARI',
      '',
    ),
  ],
  AE: [
    bank(
      'First Abu Dhabi Bank',
      '+971 2 4996100',
      'Khalifa Business Park, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/fab-mobile/id1023351966',
      'https://play.google.com/store/apps/details?id=com.fab.personal',
      'https://www.bankfab.com',
      'customerservice@bankfab.com',
      'https://twitter.com/FABConnects',
      'https://www.instagram.com/fabconnects/',
      'https://www.linkedin.com/company/first-abu-dhabi-bank-fab/',
      '',
      'NBADAEAA',
      '',
    ),
    bank(
      'Emirates NBD',
      '+971 600540000',
      'Baniyas Road, Deira, Dubai, UAE',
      'https://apps.apple.com/ae/app/emirates-nbd/id455204322',
      'https://play.google.com/store/apps/details?id=com.emberg.mobilebanking',
      'https://www.emiratesnbd.com',
      'customercare@emiratesnbd.com',
      'https://twitter.com/EmiratesNBD_AE',
      'https://www.instagram.com/emiratesnbd/',
      'https://www.linkedin.com/company/emiratesnbd/',
      '',
      'EBILAEAD',
      '',
    ),
    bank(
      'Abu Dhabi Commercial Bank',
      '+971 2 6210090',
      'Sheikh Zayed Street, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/adcb-mobile-banking-app/id453927124',
      'https://play.google.com/store/apps/details?id=com.adcb.mobile.android',
      'https://www.adcb.com',
      'customer.care@adcb.com',
      'https://twitter.com/ADCB',
      'https://www.instagram.com/adcb/',
      'https://www.linkedin.com/company/adcb/',
      '',
      'ADCBAEAA',
      '',
    ),
  ],
  VE: [
    bank(
      'Banco de Venezuela',
      '+58 212 409 5811',
      'Esquina de Sociedad, Caracas, Venezuela',
      '',
      '',
      'https://www.bancodevenezuela.com',
      'atencion_al_cliente@banvenez.com',
      '',
      '',
      '',
      '',
      'BVENVECA',
      '',
    ),
    bank(
      'Banesco Banco Universal',
      '+58 212 501 1111',
      'Av. Principal de Bello Monte, Caracas, Venezuela',
      '',
      '',
      'https://www.banesco.com',
      'atencionclientebanesco@banesco.com',
      '',
      '',
      '',
      '',
      'BEVEVECA',
      '',
    ),
    bank(
      'Banco Mercantil Venezuela',
      '+58 212 503 1111',
      'Av. Andres Bello, Caracas, Venezuela',
      '',
      '',
      'https://www.mercantilbanco.com',
      'mercantil_responde@bancomercantil.com',
      '',
      '',
      '',
      '',
      'MERCVECA',
      '',
    ),
  ],
}
