import type { NationalBankingInstitution } from './types'
import type { FiveEyesMemberIsoCode } from './fiveEyesMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per Five Eyes member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const FIVE_EYES_NATIONAL_BANKING_INSTITUTIONS: Record<
  FiveEyesMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AU: [
    bank(
      'Commonwealth Bank of Australia',
      '+61 13 2221',
      'Ground Floor, Tower 1, 201 Sussex Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/commbank/id310251020',
      'https://play.google.com/store/apps/details?id=com.commbank.netbank',
      'https://www.commbank.com.au',
      'customercare@cba.com.au',
      'https://twitter.com/CommBank',
      'https://www.instagram.com/commbank/',
      'https://www.linkedin.com/company/commonwealth-bank/',
      '',
      'CTBAAU2S',
      'https://api.commbank.com.au',
    ),
    bank(
      'Westpac Banking Corporation',
      '+61 13 2032',
      '275 Kent Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/westpac-mobile-banking/id284826145',
      'https://play.google.com/store/apps/details?id=org.westpac.bank',
      'https://www.westpac.com.au',
      'customercare@westpac.com.au',
      'https://twitter.com/Westpac',
      'https://www.instagram.com/westpac/',
      'https://www.linkedin.com/company/westpac/',
      '',
      'WPACAU2S',
      'https://developer.westpac.com.au',
    ),
    bank(
      'Australia and New Zealand Banking Group',
      '+61 13 13 14',
      '833 Collins Street, Docklands, VIC, Australia',
      'https://apps.apple.com/au/app/anz-australia/id385348415',
      'https://play.google.com/store/apps/details?id=com.anz.android',
      'https://www.anz.com.au',
      'contactus@anz.com',
      'https://twitter.com/ANZ_AU',
      'https://www.instagram.com/anz_au/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBAU3M',
      'https://developer.anz.com',
    ),
  ],
  CA: [
    bank(
      'Royal Bank of Canada',
      '+1 416 974 5151',
      '200 Bay Street, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/rbc-mobile/id407597290',
      'https://play.google.com/store/apps/details?id=com.rbc.mobile.android',
      'https://www.rbc.com',
      'info@rbc.com',
      'https://twitter.com/RBC',
      'https://www.instagram.com/rbc/',
      'https://www.linkedin.com/company/rbc/',
      '',
      'ROYCCAT2',
      '',
    ),
    bank(
      'Toronto-Dominion Bank',
      '+1 416 308 9030',
      '66 Wellington Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/td-canada/id358071948',
      'https://play.google.com/store/apps/details?id=com.td',
      'https://www.td.com',
      'customer.service@td.com',
      'https://twitter.com/TD_Canada',
      'https://www.instagram.com/td_canada/',
      'https://www.linkedin.com/company/td/',
      '',
      'TDOMCATTTOR',
      '',
    ),
    bank(
      'Scotiabank',
      '+1 416 933 8000',
      '44 King Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/scotiabank/id341351824',
      'https://play.google.com/store/apps/details?id=ca.scotiabank.banking',
      'https://www.scotiabank.com',
      'customer.service@scotiabank.com',
      'https://twitter.com/Scotiabank',
      'https://www.instagram.com/scotiabank/',
      'https://www.linkedin.com/company/scotiabank/',
      '',
      'NOSCCATT',
      '',
    ),
  ],
  NZ: [
    bank(
      'ANZ New Zealand',
      '+64 9 252 6777',
      '23 Albert Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/anz-go-money-nz/id486726860',
      'https://play.google.com/store/apps/details?id=nz.co.anz.android.mobilebanking',
      'https://www.anz.co.nz',
      'info@anz.co.nz',
      'https://twitter.com/ANZ_NZ',
      'https://www.instagram.com/anz_nz/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBNZ22',
      '',
    ),
    bank(
      'ASB Bank',
      '+64 9 306 3000',
      '12 Jellicoe Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/asb-mobile-banking/id384056323',
      'https://play.google.com/store/apps/details?id=nz.co.asb.asbmobile',
      'https://www.asb.co.nz',
      'info@asb.co.nz',
      'https://twitter.com/ASBBank',
      'https://www.instagram.com/asbbank/',
      'https://www.linkedin.com/company/asb-bank/',
      '',
      'ASBBNZ2A',
      '',
    ),
    bank(
      'Bank of New Zealand',
      '+64 9 924 9000',
      '80 Queen Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/bnz-mobile/id413489435',
      'https://play.google.com/store/apps/details?id=nz.co.bnz.droidbanking',
      'https://www.bnz.co.nz',
      'bnz_reception@bnz.co.nz',
      'https://twitter.com/bnz',
      'https://www.instagram.com/bankofnz/',
      'https://www.linkedin.com/company/bank-of-new-zealand/',
      '',
      'BKNZNZ22',
      '',
    ),
  ],
  GB: [
    bank(
      'HSBC UK Bank',
      '+44 345 740 4404',
      '8 Canada Square, London, United Kingdom',
      '',
      '',
      'https://www.hsbc.co.uk',
      'ukcustomer.services@hsbc.com',
      '',
      '',
      '',
      '',
      'HBUKGB4B',
      '',
    ),
    bank(
      'Barclays Bank UK',
      '+44 20 7116 1000',
      '1 Churchill Place, London, United Kingdom',
      '',
      '',
      'https://www.barclays.co.uk',
      'customer.services@barclays.co.uk',
      '',
      '',
      '',
      '',
      'BARCGB22',
      '',
    ),
    bank(
      'Lloyds Bank',
      '+44 20 7626 1500',
      '25 Gresham Street, London, United Kingdom',
      '',
      '',
      'https://www.lloydsbank.com',
      'onlinecomplaints@lloydsbank.co.uk',
      '',
      '',
      '',
      '',
      'LOYDGB2L',
      '',
    ),
  ],
  US: [
    bank(
      'JPMorgan Chase Bank',
      '+1 212 270 6000',
      '270 Park Avenue, New York, NY, United States',
      'https://apps.apple.com/us/app/chase-mobile/id298867247',
      'https://play.google.com/store/apps/details?id=com.chase.sig.android',
      'https://www.chase.com',
      'support@chase.com',
      'https://twitter.com/Chase',
      'https://www.instagram.com/chase/',
      'https://www.linkedin.com/company/jpmorganchase/',
      '021000021',
      'CHASUS33',
      'https://api.chase.com',
    ),
    bank(
      'Bank of America',
      '+1 704 386 5681',
      '100 North Tryon Street, Charlotte, NC, United States',
      'https://apps.apple.com/us/app/bank-of-america-mobile-banking/id284847138',
      'https://play.google.com/store/apps/details?id=com.infonow.bofa',
      'https://www.bankofamerica.com',
      'abuse@bankofamerica.com',
      'https://twitter.com/BankofAmerica',
      'https://www.instagram.com/bankofamerica/',
      'https://www.linkedin.com/company/bank-of-america/',
      '026009593',
      'BOFAUS3N',
      '',
    ),
    bank(
      'Wells Fargo Bank',
      '+1 415 396 1300',
      '420 Montgomery Street, San Francisco, CA, United States',
      'https://apps.apple.com/us/app/wells-fargo-mobile/id311548709',
      'https://play.google.com/store/apps/details?id=com.wf.wellsfargomobile',
      'https://www.wellsfargo.com',
      'customer.service@wellsfargo.com',
      'https://twitter.com/WellsFargo',
      'https://www.instagram.com/wellsfargo/',
      'https://www.linkedin.com/company/wellsfargo/',
      '121000248',
      'WFBIUS6S',
      '',
    ),
  ],
}
