/**
 * NY Exchange Offerings - Gemini Index - Cryptocurrencies available on Gemini NY Exchange
 * 
 * This list contains cryptocurrencies that are available for trading on Gemini's
 * New York State cryptocurrency exchange. These offerings represent a curated selection
 * of digital assets that have been approved for trading in New York State through
 * Gemini's platform under BitLicense and Limited Purpose Trust Company charter.
 * 
 * This index excludes assets that are specifically restricted for NY residents,
 * such as USDT (Tether), BOME (Book of Meme), and certain Solana SPL tokens.
 * 
 * This index is used for NY exchange-specific displays, Gemini integration features,
 * and regulatory-compliant currency selection interfaces.
 * 
 * Last Updated: December 2025
 * Source: Gemini Support Documentation, NYDFS Greenlist, and Gemini regulatory filings
 * Regulatory Body: New York State Department of Financial Services (NYDFS)
 */

export type CurrencyType = 'coin' | 'token';
export type ConsensusType = 'proof-of-stake' | 'proof-of-work' | 'proof-of-authority' | 'delegated-proof-of-stake' | 'nominated-proof-of-stake' | 'liquid-proof-of-stake' | 'byzantine-fault-tolerance' | 'proof-of-transfer' | 'proof-of-coverage' | 'token' | 'hybrid' | 'optimistic-rollup';
export type CurrencyClass = 'layer-1' | 'layer-2' | 'defi' | 'dex' | 'nft' | 'gaming' | 'metaverse' | 'oracle' | 'privacy' | 'meme' | 'staking' | 'governance' | 'lending' | 'data' | 'infrastructure' | 'smart-contract-platform' | 'exchange-token' | 'ai' | 'storage' | 'payment' | 'social' | 'interoperability' | 'sports' | 'iot';

export interface NYExchangeOfferingsGeminiItem {
  id: string;
  symbol: string;
  name: string;
  description: string;
  ucid: number;
  type: CurrencyType;
  consensusType: ConsensusType;
  class: CurrencyClass[];
  website: string | null;
  github: string | null;
  npm: string | null;
}

export const NY_EXCHANGE_OFFERINGS_GEMINI: NYExchangeOfferingsGeminiItem[] = [
  { 
    id: 'aave', 
    symbol: 'AAVE', 
    name: 'Aave',
    description: 'A decentralized lending protocol that allows users to lend and borrow cryptocurrencies without intermediaries.',
    ucid: 7278,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://aave.com',
    github: 'https://github.com/aave',
    npm: 'https://www.npmjs.com/package/@aave/protocol-js'
  },
  { 
    id: 'alethea-artificial-liquid-intelligence', 
    symbol: 'ALI', 
    name: 'Alethea Artificial Liquid Intelligence',
    description: 'A protocol enabling the creation and interaction with intelligent NFTs powered by AI.',
    ucid: 9704,
    type: 'token',
    consensusType: 'token',
    class: ['ai', 'nft'],
    website: 'https://alethea.ai',
    github: 'https://github.com/alethea-ai',
    npm: null
  },
  { 
    id: 'amp', 
    symbol: 'AMP', 
    name: 'Amp',
    description: 'A digital collateral token designed to facilitate instant, verifiable assurances for value transfer.',
    ucid: 6945,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'payment'],
    website: 'https://amptoken.org',
    github: 'https://github.com/amptoken',
    npm: null
  },
  { 
    id: 'ankr', 
    symbol: 'ANKR', 
    name: 'Ankr',
    description: 'A decentralized Web3 infrastructure provider offering node hosting, staking, and API services.',
    ucid: 3783,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'staking'],
    website: 'https://www.ankr.com',
    github: 'https://github.com/Ankr-network',
    npm: 'https://www.npmjs.com/package/@ankr.com/ankr.js'
  },
  { 
    id: 'apecoin', 
    symbol: 'APE', 
    name: 'ApeCoin',
    description: 'The governance and utility token for the APE ecosystem, supporting NFT projects like Bored Ape Yacht Club.',
    ucid: 18876,
    type: 'token',
    consensusType: 'token',
    class: ['governance', 'nft', 'metaverse'],
    website: 'https://apecoin.com',
    github: 'https://github.com/ApeCoinDAO',
    npm: null
  },
  { 
    id: 'api3', 
    symbol: 'API3', 
    name: 'API3',
    description: 'A decentralized API oracle solution providing data feeds to smart contracts directly from API providers.',
    ucid: 7737,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure'],
    website: 'https://api3.org',
    github: 'https://github.com/api3dao',
    npm: 'https://www.npmjs.com/package/@api3/airnode-node'
  },
  { 
    id: 'arbitrum', 
    symbol: 'ARB', 
    name: 'Arbitrum',
    description: 'A layer-2 scaling solution for Ethereum using optimistic rollups to increase throughput and reduce costs.',
    ucid: 11841,
    type: 'token',
    consensusType: 'optimistic-rollup',
    class: ['layer-2', 'infrastructure'],
    website: 'https://arbitrum.io',
    github: 'https://github.com/OffchainLabs',
    npm: 'https://www.npmjs.com/package/@arbitrum/sdk'
  },
  { 
    id: 'atom', 
    symbol: 'ATOM', 
    name: 'Cosmos',
    description: 'An ecosystem of interconnected blockchains designed to solve scalability and interoperability issues.',
    ucid: 3794,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'interoperability'],
    website: 'https://cosmos.network',
    github: 'https://github.com/cosmos',
    npm: 'https://www.npmjs.com/package/@cosmjs/stargate'
  },
  { 
    id: 'avalanche-2', 
    symbol: 'AVAX', 
    name: 'Avalanche',
    description: 'A high-performance blockchain platform for decentralized applications and custom blockchain networks.',
    ucid: 5805,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://www.avax.network',
    github: 'https://github.com/ava-labs',
    npm: 'https://www.npmjs.com/package/avalanche'
  },
  { 
    id: 'basic-attention-token', 
    symbol: 'BAT', 
    name: 'Basic Attention Token',
    description: 'A utility token used within the Brave browser ecosystem to reward users for viewing ads and content creators.',
    ucid: 1697,
    type: 'token',
    consensusType: 'token',
    class: ['payment', 'social'],
    website: 'https://basicattentiontoken.org',
    github: 'https://github.com/brave-intl',
    npm: null
  },
  { 
    id: 'bitcoin-cash', 
    symbol: 'BCH', 
    name: 'Bitcoin Cash',
    description: 'A peer-to-peer electronic cash system forked from Bitcoin with larger block sizes for faster transactions.',
    ucid: 1831,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoincash.org',
    github: 'https://github.com/bitcoin-cash-node',
    npm: null
  },
  { 
    id: 'bonk', 
    symbol: 'BONK', 
    name: 'Bonk',
    description: 'A community-driven meme cryptocurrency on Solana featuring a Shiba Inu dog mascot.',
    ucid: 23095,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://bonkcoin.com',
    github: null,
    npm: null
  },
  { 
    id: 'bitcoin', 
    symbol: 'BTC', 
    name: 'Bitcoin',
    description: 'The first decentralized cryptocurrency, serving as digital gold and a peer-to-peer electronic cash system.',
    ucid: 1,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoin.org',
    github: 'https://github.com/bitcoin',
    npm: 'https://www.npmjs.com/package/bitcoinjs-lib'
  },
  { 
    id: 'chiliz', 
    symbol: 'CHZ', 
    name: 'Chiliz',
    description: 'A sports and entertainment blockchain platform enabling fan engagement through fan tokens.',
    ucid: 4066,
    type: 'token',
    consensusType: 'proof-of-authority',
    class: ['sports', 'social', 'nft'],
    website: 'https://chiliz.com',
    github: 'https://github.com/chiliz-chain',
    npm: null
  },
  { 
    id: 'compound-governance-token', 
    symbol: 'COMP', 
    name: 'Compound',
    description: 'A governance token for the Compound protocol, an algorithmic money market on Ethereum.',
    ucid: 5692,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://compound.finance',
    github: 'https://github.com/compound-finance',
    npm: 'https://www.npmjs.com/package/@compound-finance/compound-js'
  },
  { 
    id: 'curve-dao-token', 
    symbol: 'CRV', 
    name: 'Curve DAO Token',
    description: 'The governance token for Curve Finance, a decentralized exchange optimized for stablecoin trading.',
    ucid: 6538,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://curve.fi',
    github: 'https://github.com/curvefi',
    npm: null
  },
  { 
    id: 'somnium-space-cube', 
    symbol: 'CUBE', 
    name: 'Somnium Space',
    description: 'The native currency of Somnium Space, an open VR world built on blockchain technology.',
    ucid: 5239,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'nft'],
    website: 'https://somniumspace.com',
    github: 'https://github.com/somniumspace',
    npm: null
  },
  { 
    id: 'cryptex-finance', 
    symbol: 'CTX', 
    name: 'Cryptex Finance',
    description: 'A decentralized derivatives protocol for creating tokenized indexes and synthetic assets.',
    ucid: 9207,
    type: 'token',
    consensusType: 'token',
    class: ['defi'],
    website: 'https://cryptex.finance',
    github: 'https://github.com/cryptexfinance',
    npm: null
  },
  { 
    id: 'dai', 
    symbol: 'DAI', 
    name: 'Dai',
    description: 'A decentralized stablecoin soft-pegged to the US dollar and backed by crypto collateral on MakerDAO.',
    ucid: 2308,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://makerdao.com',
    github: 'https://github.com/makerdao',
    npm: 'https://www.npmjs.com/package/@makerdao/dai'
  },
  { 
    id: 'dogecoin', 
    symbol: 'DOGE', 
    name: 'Dogecoin',
    description: 'A peer-to-peer cryptocurrency created as a fun, community-driven alternative to Bitcoin.',
    ucid: 74,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment', 'meme'],
    website: 'https://dogecoin.com',
    github: 'https://github.com/dogecoin',
    npm: null
  },
  { 
    id: 'dot', 
    symbol: 'DOT', 
    name: 'Polkadot',
    description: 'A multi-chain protocol enabling diverse blockchains to transfer messages and value in a trust-free fashion.',
    ucid: 6636,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['layer-1', 'interoperability'],
    website: 'https://polkadot.network',
    github: 'https://github.com/paritytech/polkadot',
    npm: 'https://www.npmjs.com/package/@polkadot/api'
  },
  { 
    id: 'drift', 
    symbol: 'DRIFT', 
    name: 'Drift',
    description: 'A decentralized perpetual futures exchange built on Solana with cross-margin trading.',
    ucid: 28932,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex'],
    website: 'https://www.drift.trade',
    github: 'https://github.com/drift-labs',
    npm: 'https://www.npmjs.com/package/@drift-labs/sdk'
  },
  { 
    id: 'dogelon-mars', 
    symbol: 'ELON', 
    name: 'Dogelon Mars',
    description: 'A meme cryptocurrency named after Elon Musk and inspired by Dogecoin.',
    ucid: 9436,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://dogelon.io',
    github: null,
    npm: null
  },
  { 
    id: 'ethereum-name-service', 
    symbol: 'ENS', 
    name: 'Ethereum Name Service',
    description: 'A decentralized naming protocol for blockchain addresses and websites using .eth domains.',
    ucid: 13855,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://ens.domains',
    github: 'https://github.com/ensdomains',
    npm: 'https://www.npmjs.com/package/@ensdomains/ensjs'
  },
  { 
    id: 'ethereum', 
    symbol: 'ETH', 
    name: 'Ethereum',
    description: 'A decentralized platform enabling smart contracts and distributed applications with its native currency Ether.',
    ucid: 1027,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ethereum.org',
    github: 'https://github.com/ethereum',
    npm: 'https://www.npmjs.com/package/ethers'
  },
  { 
    id: 'fetch-ai', 
    symbol: 'FET', 
    name: 'Fetch AI',
    description: 'An AI-powered blockchain platform enabling autonomous agents to perform complex tasks.',
    ucid: 3773,
    type: 'token',
    consensusType: 'delegated-proof-of-stake',
    class: ['ai', 'infrastructure'],
    website: 'https://fetch.ai',
    github: 'https://github.com/fetchai',
    npm: 'https://www.npmjs.com/package/@fetchai/wallet-react'
  },
  { 
    id: 'filecoin', 
    symbol: 'FIL', 
    name: 'Filecoin',
    description: 'A decentralized storage network turning cloud storage into an algorithmic market.',
    ucid: 2280,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'layer-1'],
    website: 'https://filecoin.io',
    github: 'https://github.com/filecoin-project',
    npm: 'https://www.npmjs.com/package/@glif/filecoin-rpc-client'
  },
  { 
    id: 'fantom', 
    symbol: 'FTM', 
    name: 'Fantom',
    description: 'A fast, scalable, and secure smart contract platform using directed acyclic graph (DAG) technology.',
    ucid: 3513,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://fantom.foundation',
    github: 'https://github.com/Fantom-Foundation',
    npm: null
  },
  { 
    id: 'gala', 
    symbol: 'GALA', 
    name: 'Gala',
    description: 'A blockchain gaming platform empowering players with true ownership of in-game assets.',
    ucid: 7080,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'nft'],
    website: 'https://gala.com',
    github: 'https://github.com/gala-games',
    npm: null
  },
  { 
    id: 'gmt', 
    symbol: 'GMT', 
    name: 'STEPN',
    description: 'A Web3 lifestyle app with game-fi and social-fi elements for move-to-earn rewards.',
    ucid: 18069,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'social'],
    website: 'https://stepn.com',
    github: 'https://github.com/stepnofficial',
    npm: null
  },
  { 
    id: 'the-graph', 
    symbol: 'GRT', 
    name: 'The Graph',
    description: 'A decentralized protocol for indexing and querying blockchain data, making it easily accessible.',
    ucid: 6719,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'infrastructure'],
    website: 'https://thegraph.com',
    github: 'https://github.com/graphprotocol',
    npm: 'https://www.npmjs.com/package/@graphprotocol/graph-cli'
  },
  { 
    id: 'gemini-dollar', 
    symbol: 'GUSD', 
    name: 'Gemini Dollar',
    description: 'A regulated stablecoin issued by Gemini, fully backed by US dollars and subject to monthly audits.',
    ucid: 3306,
    type: 'token',
    consensusType: 'token',
    class: ['defi'],
    website: 'https://www.gemini.com/dollar',
    github: null,
    npm: null
  },
  { 
    id: 'helium', 
    symbol: 'HNT', 
    name: 'Helium',
    description: 'A decentralized wireless network for IoT devices powered by a blockchain-based incentive model.',
    ucid: 5665,
    type: 'coin',
    consensusType: 'proof-of-coverage',
    class: ['infrastructure', 'iot'],
    website: 'https://www.helium.com',
    github: 'https://github.com/helium',
    npm: 'https://www.npmjs.com/package/@helium/http'
  },
  { 
    id: 'immutable-x', 
    symbol: 'IMX', 
    name: 'Immutable X',
    description: 'A layer-2 scaling solution for NFTs on Ethereum with zero gas fees and instant trades.',
    ucid: 10603,
    type: 'token',
    consensusType: 'token',
    class: ['layer-2', 'nft'],
    website: 'https://www.immutable.com',
    github: 'https://github.com/immutable',
    npm: 'https://www.npmjs.com/package/@imtbl/core-sdk'
  },
  { 
    id: 'injective', 
    symbol: 'INJ', 
    name: 'Injective',
    description: 'A decentralized exchange protocol enabling cross-chain derivatives trading with zero gas fees.',
    ucid: 7226,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'dex', 'layer-1'],
    website: 'https://injective.com',
    github: 'https://github.com/InjectiveLabs',
    npm: 'https://www.npmjs.com/package/@injectivelabs/sdk-ts'
  },
  { 
    id: 'iotex', 
    symbol: 'IOTX', 
    name: 'IoTeX',
    description: 'A decentralized platform for the Internet of Things combining blockchain and IoT devices.',
    ucid: 2777,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://iotex.io',
    github: 'https://github.com/iotexproject',
    npm: 'https://www.npmjs.com/package/iotex-antenna'
  },
  { 
    id: 'jito-staked-sol', 
    symbol: 'JITOSOL', 
    name: 'Jito Staked SOL',
    description: 'A liquid staking token representing staked SOL on the Jito protocol.',
    ucid: 26302,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking'],
    website: 'https://www.jito.network',
    github: 'https://github.com/jito-foundation',
    npm: null
  },
  { 
    id: 'jito', 
    symbol: 'JTO', 
    name: 'Jito',
    description: 'A liquid staking protocol and MEV infrastructure for Solana.',
    ucid: 28541,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking', 'infrastructure'],
    website: 'https://www.jito.network',
    github: 'https://github.com/jito-foundation',
    npm: 'https://www.npmjs.com/package/@jito-foundation/jito-js'
  },
  { 
    id: 'jupiter', 
    symbol: 'JUP', 
    name: 'Jupiter',
    description: 'A leading DEX aggregator on Solana providing the best swap prices across multiple liquidity sources.',
    ucid: 29210,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex'],
    website: 'https://jup.ag',
    github: 'https://github.com/jup-ag',
    npm: null
  },
  { 
    id: 'kamino', 
    symbol: 'KMNO', 
    name: 'Kamino',
    description: 'An automated liquidity solution and yield optimization protocol on Solana.',
    ucid: 28978,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://kamino.finance',
    github: 'https://github.com/Kamino-Finance',
    npm: null
  },
  { 
    id: 'lido-dao', 
    symbol: 'LDO', 
    name: 'Lido DAO',
    description: 'The governance token for Lido, a liquid staking solution for Ethereum and other networks.',
    ucid: 8000,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking', 'governance'],
    website: 'https://lido.fi',
    github: 'https://github.com/lidofinance',
    npm: 'https://www.npmjs.com/package/@lido-sdk/contracts'
  },
  { 
    id: 'chainlink', 
    symbol: 'LINK', 
    name: 'Chainlink',
    description: 'A decentralized oracle network providing real-world data to smart contracts on any blockchain.',
    ucid: 1975,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure'],
    website: 'https://chain.link',
    github: 'https://github.com/smartcontractkit',
    npm: 'https://www.npmjs.com/package/@chainlink/contracts'
  },
  { 
    id: 'livepeer', 
    symbol: 'LPT', 
    name: 'Livepeer',
    description: 'A decentralized video streaming protocol built on Ethereum for live and on-demand video.',
    ucid: 3640,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://livepeer.org',
    github: 'https://github.com/livepeer',
    npm: 'https://www.npmjs.com/package/livepeer'
  },
  { 
    id: 'loopring', 
    symbol: 'LRC', 
    name: 'Loopring',
    description: 'A zkRollup layer-2 scaling solution for Ethereum with high-throughput decentralized exchanges.',
    ucid: 1934,
    type: 'token',
    consensusType: 'token',
    class: ['layer-2', 'dex'],
    website: 'https://loopring.org',
    github: 'https://github.com/Loopring',
    npm: 'https://www.npmjs.com/package/@loopring-web/loopring-sdk'
  },
  { 
    id: 'litecoin', 
    symbol: 'LTC', 
    name: 'Litecoin',
    description: 'A peer-to-peer cryptocurrency created as the "silver to Bitcoin\'s gold" with faster block times.',
    ucid: 2,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://litecoin.org',
    github: 'https://github.com/litecoin-project',
    npm: null
  },
  { 
    id: 'decentraland', 
    symbol: 'MANA', 
    name: 'Decentraland',
    description: 'A virtual reality platform powered by Ethereum where users can create, experience, and monetize content.',
    ucid: 1966,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'nft', 'gaming'],
    website: 'https://decentraland.org',
    github: 'https://github.com/decentraland',
    npm: 'https://www.npmjs.com/package/decentraland'
  },
  { 
    id: 'mask-network', 
    symbol: 'MASK', 
    name: 'Mask Network',
    description: 'A protocol allowing users to send encrypted messages and interact with DApps on social media platforms.',
    ucid: 8536,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'privacy'],
    website: 'https://mask.io',
    github: 'https://github.com/DimensionDev',
    npm: null
  },
  { 
    id: 'optimism', 
    symbol: 'OP', 
    name: 'Optimism',
    description: 'An Ethereum layer-2 scaling solution using optimistic rollups to reduce costs and increase throughput.',
    ucid: 11840,
    type: 'token',
    consensusType: 'optimistic-rollup',
    class: ['layer-2', 'infrastructure'],
    website: 'https://optimism.io',
    github: 'https://github.com/ethereum-optimism',
    npm: 'https://www.npmjs.com/package/@eth-optimism/sdk'
  },
  { 
    id: 'pax-gold', 
    symbol: 'PAXG', 
    name: 'Pax Gold',
    description: 'A gold-backed cryptocurrency where each token represents one troy ounce of physical gold.',
    ucid: 4705,
    type: 'token',
    consensusType: 'token',
    class: ['defi'],
    website: 'https://paxos.com/paxgold',
    github: null,
    npm: null
  },
  { 
    id: 'pepe', 
    symbol: 'PEPE', 
    name: 'Pepe',
    description: 'A meme cryptocurrency inspired by the Pepe the Frog internet meme.',
    ucid: 24478,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://www.pepe.vip',
    github: null,
    npm: null
  },
  { 
    id: 'polygon', 
    symbol: 'POL', 
    name: 'Polygon',
    description: 'The upgraded native token of the Polygon network, successor to MATIC.',
    ucid: 11419,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['layer-2', 'infrastructure'],
    website: 'https://polygon.technology',
    github: 'https://github.com/maticnetwork',
    npm: 'https://www.npmjs.com/package/@polygon/sdk'
  },
  { 
    id: 'pyth-network', 
    symbol: 'PYTH', 
    name: 'Pyth Network',
    description: 'A decentralized oracle network providing high-fidelity financial market data to smart contracts.',
    ucid: 28177,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'data'],
    website: 'https://pyth.network',
    github: 'https://github.com/pyth-network',
    npm: 'https://www.npmjs.com/package/@pythnetwork/client'
  },
  { 
    id: 'quant', 
    symbol: 'QNT', 
    name: 'Quant',
    description: 'A blockchain operating system enabling interoperability between different blockchains.',
    ucid: 3155,
    type: 'token',
    consensusType: 'token',
    class: ['interoperability', 'infrastructure'],
    website: 'https://quant.network',
    github: null,
    npm: null
  },
  { 
    id: 'ripple-usd', 
    symbol: 'RLUSD', 
    name: 'Ripple USD',
    description: 'A US dollar-backed stablecoin issued by Ripple, designed for enterprise payments and settlements.',
    ucid: 33880,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'payment'],
    website: 'https://ripple.com/solutions/cryptocurrency',
    github: null,
    npm: null
  },
  { 
    id: 'render-token', 
    symbol: 'RNDR', 
    name: 'Render Token',
    description: 'A decentralized GPU rendering network connecting artists with GPU compute power.',
    ucid: 5690,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'ai'],
    website: 'https://rendernetwork.com',
    github: 'https://github.com/rndr-network',
    npm: null
  },
  { 
    id: 'samoyedcoin', 
    symbol: 'SAMO', 
    name: 'Samoyedcoin',
    description: 'A community-driven meme cryptocurrency on Solana featuring a Samoyed dog mascot.',
    ucid: 8677,
    type: 'token',
    consensusType: 'token',
    class: ['meme', 'social'],
    website: 'https://samoyedcoin.com',
    github: 'https://github.com/samoyedcoin',
    npm: null
  },
  { 
    id: 'the-sandbox', 
    symbol: 'SAND', 
    name: 'The Sandbox',
    description: 'A virtual metaverse where players can build, own, and monetize gaming experiences.',
    ucid: 6210,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'gaming', 'nft'],
    website: 'https://www.sandbox.game',
    github: 'https://github.com/thesandboxgame',
    npm: null
  },
  { 
    id: 'shiba-inu', 
    symbol: 'SHIB', 
    name: 'Shiba Inu',
    description: 'A meme cryptocurrency and decentralized ecosystem with DEX, NFTs, and metaverse components.',
    ucid: 5994,
    type: 'token',
    consensusType: 'token',
    class: ['meme', 'defi'],
    website: 'https://shibatoken.com',
    github: 'https://github.com/shytoshikusama',
    npm: null
  },
  { 
    id: 'skale', 
    symbol: 'SKL', 
    name: 'SKALE',
    description: 'An Ethereum-compatible elastic blockchain network for fast, secure dApps.',
    ucid: 5691,
    type: 'token',
    consensusType: 'token',
    class: ['layer-2', 'infrastructure'],
    website: 'https://skale.space',
    github: 'https://github.com/skalenetwork',
    npm: 'https://www.npmjs.com/package/@skalenetwork/skale.js'
  },
  { 
    id: 'sky', 
    symbol: 'SKY', 
    name: 'Sky',
    description: 'The rebranded governance token for the Sky (formerly MakerDAO) ecosystem.',
    ucid: 1518,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    website: 'https://sky.money',
    github: 'https://github.com/makerdao',
    npm: null
  },
  { 
    id: 'solana', 
    symbol: 'SOL', 
    name: 'Solana',
    description: 'A high-performance blockchain supporting fast transactions and low fees through proof-of-history.',
    ucid: 5426,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://solana.com',
    github: 'https://github.com/solana-labs',
    npm: 'https://www.npmjs.com/package/@solana/web3.js'
  },
  { 
    id: 'storj', 
    symbol: 'STORJ', 
    name: 'Storj',
    description: 'A decentralized cloud storage platform that encrypts and distributes files across a global network.',
    ucid: 1772,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    website: 'https://storj.io',
    github: 'https://github.com/storj',
    npm: 'https://www.npmjs.com/package/storj'
  },
  { 
    id: 'sushiswap', 
    symbol: 'SUSHI', 
    name: 'SushiSwap',
    description: 'A decentralized exchange and automated market maker built on multiple blockchains.',
    ucid: 6758,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://sushi.com',
    github: 'https://github.com/sushiswap',
    npm: 'https://www.npmjs.com/package/@sushiswap/sdk'
  },
  { 
    id: 'uma', 
    symbol: 'UMA', 
    name: 'UMA',
    description: 'A decentralized protocol for creating synthetic assets and financial contracts on Ethereum.',
    ucid: 5617,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'oracle'],
    website: 'https://umaproject.org',
    github: 'https://github.com/UMAprotocol',
    npm: 'https://www.npmjs.com/package/@uma/sdk'
  },
  { 
    id: 'uniswap', 
    symbol: 'UNI', 
    name: 'Uniswap',
    description: 'A leading decentralized exchange protocol built on Ethereum using automated market making.',
    ucid: 7083,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://uniswap.org',
    github: 'https://github.com/Uniswap',
    npm: 'https://www.npmjs.com/package/@uniswap/sdk'
  },
  { 
    id: 'usd-coin', 
    symbol: 'USDC', 
    name: 'USD Coin',
    description: 'A fully-backed USD stablecoin issued by Circle and regulated for transparency and trust.',
    ucid: 3408,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'payment'],
    website: 'https://www.circle.com/usdc',
    github: 'https://github.com/circlefin',
    npm: null
  },
  { 
    id: 'dogwifhat', 
    symbol: 'WIF', 
    name: 'DogWifHat',
    description: 'A Solana-based meme cryptocurrency featuring a dog wearing a hat.',
    ucid: 28752,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://dogwifcoin.org',
    github: null,
    npm: null
  },
  { 
    id: 'ripple', 
    symbol: 'XRP', 
    name: 'XRP',
    description: 'A digital payment protocol and cryptocurrency designed for fast, low-cost international money transfers.',
    ucid: 52,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    website: 'https://ripple.com',
    github: 'https://github.com/ripple',
    npm: 'https://www.npmjs.com/package/xrpl'
  },
  { 
    id: 'tezos', 
    symbol: 'XTZ', 
    name: 'Tezos',
    description: 'A self-amending blockchain with on-chain governance and formal verification for smart contracts.',
    ucid: 2011,
    type: 'coin',
    consensusType: 'liquid-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://tezos.com',
    github: 'https://github.com/tezos',
    npm: 'https://www.npmjs.com/package/@taquito/taquito'
  },
  { 
    id: 'yearn-finance', 
    symbol: 'YFI', 
    name: 'yearn.finance',
    description: 'A DeFi yield aggregator that automatically moves funds between lending protocols for optimal returns.',
    ucid: 5864,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    website: 'https://yearn.finance',
    github: 'https://github.com/yearn',
    npm: 'https://www.npmjs.com/package/@yfi/sdk'
  },
  { 
    id: 'zcash', 
    symbol: 'ZEC', 
    name: 'Zcash',
    description: 'A privacy-focused cryptocurrency using zero-knowledge proofs to enable shielded transactions.',
    ucid: 1437,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://z.cash',
    github: 'https://github.com/zcash',
    npm: null
  }
];

export default NY_EXCHANGE_OFFERINGS_GEMINI;
