import type { CorporationFormationOffice } from './types'
import type { G7MemberIsoCode } from './g7MemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per G7 member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const G7_CORPORATION_FORMATION_OFFICES: Record<G7MemberIsoCode, CorporationFormationOffice> = {
  CA:   office(
    'Corporations Canada (Innovation, Science and Economic Development)',
    '+1 866 333 5556',
    '235 Queen Street, Ottawa, ON K1A 0H5, Canada',
    'https://ised-isde.canada.ca/site/corporations-canada/en',
    '',
    '',
    '',
    '',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/incorporate-business-corporation',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/steps-incorporating',
    'Corporation Number',
  ),
  FR:   office(
    'Infogreffe / Guichet Unique France',
    '+33 892 680 271',
    'Paris, France',
    'https://www.infogreffe.fr',
    'contact@infogreffe.fr',
    '',
    '',
    '',
    'https://www.guichet-entreprises.fr',
    'https://www.guichet-entreprises.fr/creer-son-entreprise',
    'SIREN / SIRET Number',
  ),
  DE:   office(
    'Unternehmensregister (German Commercial Register)',
    '+49 30 187810',
    'Berlin, Germany',
    'https://www.unternehmensregister.de',
    'info@handelsregister.de',
    '',
    '',
    '',
    'https://www.unternehmensregister.de',
    'https://www.gruenderplattform.de',
    'Handelsregisternummer',
  ),
  IT:   office(
    'Registro Imprese (Chamber of Commerce Italy)',
    '+39 06 47041',
    'Via Carlo Alberto 16, Rome, Italy',
    'https://www.registroimprese.it',
    'info@registroimprese.it',
    '',
    '',
    '',
    'https://www.registroimprese.it',
    'https://www.infocamere.it/starting-a-business',
    'Codice Fiscale / REA Number',
  ),
  JP:   office(
    'Legal Affairs Bureau (Ministry of Justice Commercial Registration)',
    '+81 3 3580 4111',
    '1-1-1 Kasumigaseki, Chiyoda-ku, Tokyo, Japan',
    'https://www.moj.go.jp',
    '',
    '',
    '',
    '',
    'https://www.moj.go.jp/MINJI/minji06.html',
    'https://www.jetro.go.jp/en/invest/setting_up/section1/page3.html',
    'Corporate Number (Houjin Bango)',
  ),
  GB:   office(
    'Companies House United Kingdom',
    '+44 303 1234 500',
    'Crown Way, Cardiff CF14 3UZ, United Kingdom',
    'https://www.gov.uk/government/organisations/companies-house',
    'enquiries@companieshouse.gov.uk',
    'https://twitter.com/CompaniesHouse',
    '',
    'https://www.linkedin.com/company/companies-house/',
    'https://www.gov.uk/limited-company-formation',
    'https://www.gov.uk/set-up-limited-company',
    'Company Registration Number (CRN)',
  ),
  US:   office(
    'U.S. State Secretary of State Business Filing Offices (Representative: Delaware Division of Corporations)',
    '+1 302 739 3073',
    '401 Federal Street, Dover, DE 19901, United States',
    'https://corp.delaware.gov',
    '',
    '',
    '',
    '',
    'https://corp.delaware.gov/paytaxes/',
    'https://www.sba.gov/business-guide/launch-your-business/register-your-business',
    'Employer Identification Number (EIN)',
  ),
}
