import type { G7MemberIsoCode } from './g7MemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per G7 member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const G7_DOMESTIC_POST_SERVICES: Record<G7MemberIsoCode, DomesticPostService> = {
  CA: post(
    'Canada Post',
    'https://www.canadapost-postescanada.ca/',
    'customercare@canadapost-postescanada.ca',
    'https://x.com/canadapostcorp',
    'https://www.instagram.com/canadapost/',
    'https://www.linkedin.com/company/canada-post/',
    'https://www.canadapost-postescanada.ca/cpc/en/tools/find-a-postal-code.page',
    'ANA NAN',
    '^[A-Z]\\d[A-Z] \\d[A-Z]\\d$',
    'K1A 0B1',
    'Canadian postal code (letter-digit-letter space digit-letter-digit)',
  ),
  FR: post(
    'La Poste',
    'https://www.laposte.fr/',
    'contact@laposte.fr',
    'https://x.com/laposte',
    'https://www.instagram.com/laposte/',
    'https://www.linkedin.com/company/la-poste/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '75001',
    'Five-digit code postal',
  ),
  DE: post(
    'Deutsche Post',
    'https://www.deutschepost.de/',
    'info@deutschepost.de',
    'https://x.com/DeutschePost',
    'https://www.instagram.com/deutschepost/',
    'https://www.linkedin.com/company/deutsche-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10115',
    'Five-digit Postleitzahl',
  ),
  IT: post(
    'Poste Italiane',
    'https://www.poste.it/',
    'assistenza.clienti@poste.it',
    'https://x.com/PosteItaliane',
    'https://www.instagram.com/posteitaliane/',
    'https://www.linkedin.com/company/poste-italiane/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00118',
    'Five-digit CAP',
  ),
  JP: post(
    'Japan Post',
    'https://www.post.japanpost.jp/',
    'info@jp-network.japanpost.jp',
    'https://x.com/japanpost_off',
    'https://www.instagram.com/japanpost_off/',
    'https://www.linkedin.com/company/japan-post-holdings/',
    '',
    'NNN-NNNN',
    '^\\d{3}-\\d{4}$',
    '100-0001',
    'Three-digit + four-digit postcode (hyphenated)',
  ),
  GB: post(
    'Royal Mail',
    'https://www.royalmail.com/',
    'customerservice@royalmail.com',
    'https://x.com/RoyalMail',
    'https://www.instagram.com/royalmailofficial/',
    'https://www.linkedin.com/company/royal-mail/',
    'https://developer.royalmail.net/',
    'AAN NAA',
    '^[A-Z]{1,2}\\d[A-Z\\d]? \\d[A-Z]{2}$',
    'SW1A 1AA',
    'UK postcode (outward + inward codes)',
  ),
  US: post(
    'United States Postal Service (USPS)',
    'https://www.usps.com/',
    'uspscustomerservice@usps.gov',
    'https://x.com/USPS',
    'https://www.instagram.com/usps/',
    'https://www.linkedin.com/company/usps/',
    'https://developer.usps.com/',
    'NNNNN',
    '^\\d{5}$',
    '20500',
    'Five-digit ZIP; ZIP+4 optional (NNNNN-NNNN)',
  ),
}
