import type { NationalBankingInstitution } from './types'
import type { G7MemberIsoCode } from './g7MemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per G7 member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const G7_NATIONAL_BANKING_INSTITUTIONS: Record<
  G7MemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  CA: [
    bank(
      'Royal Bank of Canada',
      '+1 416 974 5151',
      '200 Bay Street, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/rbc-mobile/id407597290',
      'https://play.google.com/store/apps/details?id=com.rbc.mobile.android',
      'https://www.rbc.com',
      'info@rbc.com',
      'https://twitter.com/RBC',
      'https://www.instagram.com/rbc/',
      'https://www.linkedin.com/company/rbc/',
      '',
      'ROYCCAT2',
      '',
    ),
    bank(
      'Toronto-Dominion Bank',
      '+1 416 308 9030',
      '66 Wellington Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/td-canada/id358071948',
      'https://play.google.com/store/apps/details?id=com.td',
      'https://www.td.com',
      'customer.service@td.com',
      'https://twitter.com/TD_Canada',
      'https://www.instagram.com/td_canada/',
      'https://www.linkedin.com/company/td/',
      '',
      'TDOMCATTTOR',
      '',
    ),
    bank(
      'Scotiabank',
      '+1 416 933 8000',
      '44 King Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/scotiabank/id341351824',
      'https://play.google.com/store/apps/details?id=ca.scotiabank.banking',
      'https://www.scotiabank.com',
      'customer.service@scotiabank.com',
      'https://twitter.com/Scotiabank',
      'https://www.instagram.com/scotiabank/',
      'https://www.linkedin.com/company/scotiabank/',
      '',
      'NOSCCATT',
      '',
    ),
  ],
  FR: [
    bank(
      'BNP Paribas',
      '+33 1 42 98 12 34',
      '16 Boulevard des Italiens, 75009 Paris, France',
      'https://apps.apple.com/fr/app/mes-comptes-bnp-paribas/id393156562',
      'https://play.google.com/store/apps/details?id=net.bnpparibas.mescomptes',
      'https://mabanque.bnpparibas',
      'contact@bnpparibas.com',
      'https://twitter.com/bnpparibas',
      'https://www.instagram.com/bnpparibas/',
      'https://www.linkedin.com/company/bnp-paribas/',
      '',
      'BNPAFRPP',
      'https://developers.bnpparibas',
    ),
    bank(
      'Societe Generale',
      '+33 1 42 14 20 00',
      '29 Boulevard Haussmann, 75009 Paris, France',
      'https://apps.apple.com/fr/app/societe-generale/id393156562',
      'https://play.google.com/store/apps/details?id=mobi.societegenerale.mobile.lappli',
      'https://www.societegenerale.fr',
      'contact@societegenerale.com',
      'https://twitter.com/societegenerale',
      'https://www.instagram.com/societegenerale/',
      'https://www.linkedin.com/company/societe-generale/',
      '',
      'SOGEFRPP',
      'https://developer.societegenerale.com',
    ),
    bank(
      'Credit Agricole',
      '+33 1 43 23 52 02',
      '12 Place des Etats-Unis, 92127 Montrouge, France',
      'https://apps.apple.com/fr/app-ma-credit-agricole/id393156562',
      'https://play.google.com/store/apps/details?id=fr.creditagricole.androidapp',
      'https://www.credit-agricole.fr',
      'contact@credit-agricole.com',
      'https://twitter.com/CreditAgricole',
      'https://www.instagram.com/creditagricole/',
      'https://www.linkedin.com/company/credit-agricole/',
      '',
      'AGRIFRPP',
      '',
    ),
  ],
  DE: [
    bank(
      'Deutsche Bank',
      '+49 69 910 10000',
      'Taunusanlage 12, 60325 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/deutsche-bank-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=com.db.pwcc.dbmobile',
      'https://www.deutsche-bank.de',
      'kundenservice@db.com',
      'https://twitter.com/DeutscheBank',
      'https://www.instagram.com/deutschebank/',
      'https://www.linkedin.com/company/deutsche-bank/',
      '',
      'DEUTDEFF',
      'https://developer.db.com',
    ),
    bank(
      'Commerzbank',
      '+49 69 136 20',
      'Kaiserplatz, 60261 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/commerzbank-banking/id393156562',
      'https://play.google.com/store/apps/details?id=de.commerzbanking.mobil',
      'https://www.commerzbank.de',
      'kundenservice@commerzbank.de',
      'https://twitter.com/Commerzbank',
      'https://www.instagram.com/commerzbank/',
      'https://www.linkedin.com/company/commerzbank/',
      '',
      'COBADEFF',
      '',
    ),
    bank(
      'DZ Bank',
      '+49 69 7447 0',
      'Platz der Republik, 60265 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/dz-bank/id393156562',
      '',
      'https://www.dzbank.de',
      'info@dzbank.de',
      'https://twitter.com/DZ_BANK',
      'https://www.instagram.com/dzbank/',
      'https://www.linkedin.com/company/dz-bank/',
      '',
      'GENODEFF',
      '',
    ),
  ],
  IT: [
    bank(
      'Intesa Sanpaolo',
      '+39 800 303 303',
      'Piazza San Carlo 156, Turin, Italy',
      '',
      '',
      'https://www.intesasanpaolo.com',
      'assistenza@intesasanpaolo.com',
      '',
      '',
      '',
      '',
      'BCITITMM',
      '',
    ),
    bank(
      'UniCredit',
      '+39 800 57 57 57',
      'Piazza Gae Aulenti 3, Milan, Italy',
      '',
      '',
      'https://www.unicredit.it',
      'info@unicredit.eu',
      '',
      '',
      '',
      '',
      'UNCRITMM',
      '',
    ),
    bank(
      'Banco BPM',
      '+39 800 024 024',
      'Piazza Meda 4, Milan, Italy',
      '',
      '',
      'https://www.bancobpm.it',
      'contattaci@bancobpm.it',
      '',
      '',
      '',
      '',
      'BAPPIT22',
      '',
    ),
  ],
  JP: [
    bank(
      'MUFG Bank',
      '+81 3 3240 1111',
      '2-7-1 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mufg/id1249041409',
      'https://play.google.com/store/apps/details?id=jp.co.bk.mufg.bkapp',
      'https://www.bk.mufg.jp',
      'info@bk.mufg.jp',
      'https://twitter.com/MUFG',
      '',
      'https://www.linkedin.com/company/mufg/',
      '',
      'BOTKJPJT',
      '',
    ),
    bank(
      'Sumitomo Mitsui Banking Corporation',
      '+81 3 3282 8111',
      '1-1-2 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/smbc/id398950681',
      'https://play.google.com/store/apps/details?id=jp.co.smbc.banking',
      'https://www.smbc.co.jp',
      'koho@smbc.co.jp',
      'https://twitter.com/SMBCGroup',
      '',
      'https://www.linkedin.com/company/smbc-group/',
      '',
      'SMBCJPJT',
      '',
    ),
    bank(
      'Mizuho Bank',
      '+81 3 3214 1111',
      '1-5-5 Otemachi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mizuho-direct/id1535103293',
      'https://play.google.com/store/apps/details?id=jp.co.mizuhobank.direct',
      'https://www.mizuhobank.co.jp',
      'info@mizuho-fg.co.jp',
      'https://twitter.com/MizuhoGroup',
      '',
      'https://www.linkedin.com/company/mizuho/',
      '',
      'MHCBJPJT',
      '',
    ),
  ],
  GB: [
    bank(
      'HSBC UK Bank',
      '+44 345 740 4404',
      '8 Canada Square, London, United Kingdom',
      '',
      '',
      'https://www.hsbc.co.uk',
      'ukcustomer.services@hsbc.com',
      '',
      '',
      '',
      '',
      'HBUKGB4B',
      '',
    ),
    bank(
      'Barclays Bank UK',
      '+44 20 7116 1000',
      '1 Churchill Place, London, United Kingdom',
      '',
      '',
      'https://www.barclays.co.uk',
      'customer.services@barclays.co.uk',
      '',
      '',
      '',
      '',
      'BARCGB22',
      '',
    ),
    bank(
      'Lloyds Bank',
      '+44 20 7626 1500',
      '25 Gresham Street, London, United Kingdom',
      '',
      '',
      'https://www.lloydsbank.com',
      'onlinecomplaints@lloydsbank.co.uk',
      '',
      '',
      '',
      '',
      'LOYDGB2L',
      '',
    ),
  ],
  US: [
    bank(
      'JPMorgan Chase Bank',
      '+1 212 270 6000',
      '270 Park Avenue, New York, NY, United States',
      'https://apps.apple.com/us/app/chase-mobile/id298867247',
      'https://play.google.com/store/apps/details?id=com.chase.sig.android',
      'https://www.chase.com',
      'support@chase.com',
      'https://twitter.com/Chase',
      'https://www.instagram.com/chase/',
      'https://www.linkedin.com/company/jpmorganchase/',
      '021000021',
      'CHASUS33',
      'https://api.chase.com',
    ),
    bank(
      'Bank of America',
      '+1 704 386 5681',
      '100 North Tryon Street, Charlotte, NC, United States',
      'https://apps.apple.com/us/app/bank-of-america-mobile-banking/id284847138',
      'https://play.google.com/store/apps/details?id=com.infonow.bofa',
      'https://www.bankofamerica.com',
      'abuse@bankofamerica.com',
      'https://twitter.com/BankofAmerica',
      'https://www.instagram.com/bankofamerica/',
      'https://www.linkedin.com/company/bank-of-america/',
      '026009593',
      'BOFAUS3N',
      '',
    ),
    bank(
      'Wells Fargo Bank',
      '+1 415 396 1300',
      '420 Montgomery Street, San Francisco, CA, United States',
      'https://apps.apple.com/us/app/wells-fargo-mobile/id311548709',
      'https://play.google.com/store/apps/details?id=com.wf.wellsfargomobile',
      'https://www.wellsfargo.com',
      'customer.service@wellsfargo.com',
      'https://twitter.com/WellsFargo',
      'https://www.instagram.com/wellsfargo/',
      'https://www.linkedin.com/company/wellsfargo/',
      '121000248',
      'WFBIUS6S',
      '',
    ),
  ],
}
