import type { OecdMemberIsoCode } from './oecdMemberIsoCodes'
import type { BondMarketVenue } from './types'

function b(
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  apiEndpoint: string,
): BondMarketVenue {
  return { name, website, email, twitter, linkedin, apiEndpoint }
}

/** Bond market venues for OECD member economies in this module (informational; verify periodically). */
export const OECD_BOND_MARKETS: Record<OecdMemberIsoCode, readonly BondMarketVenue[]> = {
  AU: [
    b(
      'Australian Securities Exchange (ASX) — Fixed Interest Market',
      'https://www.asx.com.au',
      'info@asx.com.au',
      'https://x.com/ASX',
      'https://www.linkedin.com/company/asx-limited/',
      '',
    ),
    b(
      'Australian Office of Financial Management (AOFM — sovereign primary)',
      'https://www.aofm.gov.au',
      'info@aofm.gov.au',
      'https://x.com/AOFM',
      'https://www.linkedin.com/company/australian-office-of-financial-management/',
      '',
    ),
  ],
  AT: [
    b(
      'Wiener Börse AG (Vienna Stock Exchange)',
      'https://www.wienerborse.at',
      'info@wienerborse.at',
      'https://x.com/wienerborse',
      'https://www.linkedin.com/company/wiener-boerse-ag/',
      '',
    ),
    b(
      'Oesterreichische Kontrollbank (OeKB — sovereign primary)',
      'https://www.oekb.at',
      'info@oekb.at',
      '',
      '',
      '',
    ),
  ],
  BE: [
    b(
      'Euronext Brussels — Fixed Income',
      'https://www.euronext.com',
      'info@euronext.com',
      'https://x.com/Euronext',
      'https://www.linkedin.com/company/euronext/',
      '',
    ),
    b(
      'Belgian Debt Agency (Agence de la Dette — sovereign primary)',
      'https://www.debtagency.be',
      'info@debtagency.be',
      '',
      '',
      '',
    ),
  ],
  CA: [
    b(
      'TMX Group — Toronto Stock Exchange / TSX Venture (listed bonds)',
      'https://www.tmx.com',
      'info@tmx.com',
      'https://x.com/TMXGroup',
      'https://www.linkedin.com/company/tmx-group/',
      '',
    ),
    b(
      'Bank of Canada (Government of Canada bond auctions)',
      'https://www.bankofcanada.ca',
      'info@bankofcanada.ca',
      'https://x.com/BankofCanada',
      'https://www.linkedin.com/company/bank-of-canada/',
      '',
    ),
  ],
  CL: [
    b(
      'Bolsa de Comercio de Santiago (BCS)',
      'https://www.bolsadesantiago.com',
      'info@bcs.cl',
      'https://x.com/bcs_cl',
      'https://www.linkedin.com/company/bolsa-de-comercio-de-santiago/',
      '',
    ),
    b(
      'Ministerio de Hacienda — Tesorería General de la República (sovereign primary)',
      'https://www.hacienda.cl',
      'contacto@hacienda.cl',
      '',
      '',
      '',
    ),
  ],
  CO: [
    b(
      'Bolsa de Valores de Colombia (BVC)',
      'https://www.bvc.com.co',
      'atencion@bvc.com.co',
      'https://x.com/bvc_colombia',
      'https://www.linkedin.com/company/bolsa-de-valores-de-colombia/',
      '',
    ),
    b(
      'Ministerio de Hacienda y Crédito Público (sovereign primary)',
      'https://www.minhacienda.gov.co',
      'contactenos@minhacienda.gov.co',
      '',
      '',
      '',
    ),
  ],
  CR: [
    b(
      'Bolsa Nacional de Valores (BNV)',
      'https://www.bnv.co.cr',
      'info@bnv.co.cr',
      '',
      '',
      '',
    ),
    b(
      'Ministerio de Hacienda — Dirección General de Deuda Pública (sovereign primary)',
      'https://www.hacienda.go.cr',
      'info@hacienda.go.cr',
      '',
      '',
      '',
    ),
  ],
  CZ: [
    b(
      'Prague Stock Exchange (PSE)',
      'https://www.pse.cz',
      'info@pse.cz',
      '',
      'https://www.linkedin.com/company/prague-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Central Government Debt (sovereign primary)',
      'https://www.mfcr.cz',
      'info@mfcr.cz',
      '',
      '',
      '',
    ),
  ],
  DK: [
    b(
      'Nasdaq Copenhagen — Fixed Income',
      'https://www.nasdaq.com/solutions/nasdaq-copenhagen',
      'info@nasdaq.com',
      'https://x.com/Nasdaq',
      'https://www.linkedin.com/company/nasdaq/',
      '',
    ),
    b(
      'Danmarks Nationalbank — Government Debt (sovereign primary)',
      'https://www.nationalbanken.dk',
      'info@nationalbanken.dk',
      'https://x.com/DanmarksNB',
      'https://www.linkedin.com/company/danmarks-nationalbank/',
      '',
    ),
  ],
  EE: [
    b(
      'Nasdaq Baltic — Tallinn (fixed income listings)',
      'https://www.nasdaqbaltic.com',
      'info@nasdaqbaltic.com',
      '',
      'https://www.linkedin.com/company/nasdaq-baltic/',
      '',
    ),
    b(
      'State Treasury — Ministry of Finance (sovereign primary)',
      'https://www.rahandusministeerium.ee',
      'info@fin.ee',
      '',
      '',
      '',
    ),
  ],
  FI: [
    b(
      'Nasdaq Helsinki — Fixed Income',
      'https://www.nasdaq.com/solutions/nasdaq-helsinki',
      'info@nasdaq.com',
      'https://x.com/Nasdaq',
      'https://www.linkedin.com/company/nasdaq/',
      '',
    ),
    b(
      'State Treasury — Ministry of Finance (sovereign primary)',
      'https://www.treasuryfinland.fi',
      'info@treasuryfinland.fi',
      '',
      '',
      '',
    ),
  ],
  FR: [
    b(
      'Euronext Paris — Fixed Income',
      'https://www.euronext.com',
      'info@euronext.com',
      'https://x.com/Euronext',
      'https://www.linkedin.com/company/euronext/',
      '',
    ),
    b(
      'Agence France Trésor (AFT — sovereign primary)',
      'https://www.aft.gouv.fr',
      'info@aft.gouv.fr',
      'https://x.com/AgenceFranceTresor',
      'https://www.linkedin.com/company/agence-france-tresor/',
      '',
    ),
  ],
  DE: [
    b(
      'Frankfurt Stock Exchange (Deutsche Börse) — Xetra Bonds',
      'https://www.deutsche-boerse.com',
      'info@deutsche-boerse.com',
      'https://x.com/deutscheboerse',
      'https://www.linkedin.com/company/deutsche-boerse/',
      '',
    ),
    b(
      'Bundesrepublik Deutschland — Finanzagentur (sovereign primary)',
      'https://www.deutsche-finanzagentur.de',
      'info@finanzagentur.de',
      'https://x.com/Finanzagentur',
      'https://www.linkedin.com/company/deutsche-finanzagentur/',
      '',
    ),
  ],
  GR: [
    b(
      'Athens Exchange (ATHEX) — Fixed Income Market',
      'https://www.athexgroup.gr',
      'info@athexgroup.gr',
      'https://x.com/athexgroup',
      'https://www.linkedin.com/company/athex/',
      '',
    ),
    b(
      'Public Debt Management Agency (PDMA — sovereign primary)',
      'https://www.pdma.gr',
      'info@pdma.gr',
      '',
      '',
      '',
    ),
  ],
  HU: [
    b(
      'Budapest Stock Exchange (BSE)',
      'https://www.bse.hu',
      'info@bse.hu',
      'https://x.com/BudapestSE',
      'https://www.linkedin.com/company/budapest-stock-exchange/',
      '',
    ),
    b(
      'Government Debt Management Agency (ÁKK — sovereign primary)',
      'https://www.allamadossag.hu',
      'info@akk.hu',
      '',
      '',
      '',
    ),
  ],
  IS: [
    b(
      'Nasdaq Iceland — Fixed Income',
      'https://www.nasdaq.com/solutions/nasdaq-iceland',
      'info@nasdaq.com',
      'https://x.com/Nasdaq',
      'https://www.linkedin.com/company/nasdaq/',
      '',
    ),
    b(
      'Government Debt Management — Ministry of Finance and Economic Affairs (sovereign primary)',
      'https://www.government.is',
      'info@mfa.is',
      '',
      '',
      '',
    ),
  ],
  IE: [
    b(
      'Euronext Dublin — Fixed Income (Irish Stock Exchange)',
      'https://www.euronext.com',
      'info@euronext.com',
      'https://x.com/Euronext',
      'https://www.linkedin.com/company/euronext/',
      '',
    ),
    b(
      'National Treasury Management Agency (NTMA — sovereign primary)',
      'https://www.ntma.ie',
      'info@ntma.ie',
      'https://x.com/NTMAireland',
      'https://www.linkedin.com/company/ntma/',
      '',
    ),
  ],
  IT: [
    b(
      'Euronext Milan (Borsa Italiana) — MOT / EuroTLX bond segment',
      'https://www.borsaitaliana.it',
      'info@borsaitaliana.it',
      'https://x.com/borsaitaliana',
      'https://www.linkedin.com/company/borsa-italiana/',
      '',
    ),
    b(
      'Ministero dell\'Economia e delle Finanze — Dipartimento del Tesoro (sovereign primary)',
      'https://www.mef.gov.it',
      'info@dt.mef.gov.it',
      '',
      '',
      '',
    ),
  ],
  JP: [
    b(
      'Japan Exchange Group (JPX) — Tokyo Stock Exchange (listed corporate bonds)',
      'https://www.jpx.co.jp',
      'info@jpx.co.jp',
      'https://x.com/JPX_official',
      'https://www.linkedin.com/company/japan-exchange-group/',
      '',
    ),
    b(
      'Ministry of Finance Japan — Government Bond Management (JGB auctions)',
      'https://www.mof.go.jp',
      'zeimu-siryou@mof.go.jp',
      '',
      '',
      '',
    ),
  ],
  LV: [
    b(
      'Nasdaq Riga (fixed income listings)',
      'https://www.nasdaqbaltic.com',
      'info@nasdaqbaltic.com',
      '',
      'https://www.linkedin.com/company/nasdaq-baltic/',
      '',
    ),
    b(
      'State Treasury — Ministry of Finance (sovereign primary)',
      'https://www.fm.gov.lv',
      'info@fm.gov.lv',
      '',
      '',
      '',
    ),
  ],
  LT: [
    b(
      'Nasdaq Vilnius (fixed income listings)',
      'https://www.nasdaqbaltic.com',
      'info@nasdaqbaltic.com',
      '',
      'https://www.linkedin.com/company/nasdaq-baltic/',
      '',
    ),
    b(
      'State Debt Management — Ministry of Finance (sovereign primary)',
      'https://www.finmin.lt',
      'info@finmin.lt',
      '',
      '',
      '',
    ),
  ],
  LU: [
    b(
      'Luxembourg Stock Exchange (LuxSE)',
      'https://www.luxse.com',
      'info@luxse.com',
      'https://x.com/LuxembourgSE',
      'https://www.linkedin.com/company/luxembourg-stock-exchange/',
      '',
    ),
    b(
      'Agence de l\'État — Administration de la Dette (sovereign primary)',
      'https://www.aetat.lu',
      'info@aetat.lu',
      '',
      '',
      '',
    ),
  ],
  MX: [
    b(
      'Bolsa Mexicana de Valores (BMV) — Mercado de Deuda',
      'https://www.bmv.com.mx',
      'atencionainversionistas@bmv.com.mx',
      'https://x.com/BMV_Group',
      'https://www.linkedin.com/company/bolsa-mexicana-de-valores/',
      '',
    ),
    b(
      'Secretaría de Hacienda y Crédito Público (SHCP — sovereign primary)',
      'https://www.gob.mx/shcp',
      'atencion@hacienda.gob.mx',
      '',
      '',
      '',
    ),
  ],
  NL: [
    b(
      'Euronext Amsterdam — Fixed Income',
      'https://www.euronext.com',
      'info@euronext.com',
      'https://x.com/Euronext',
      'https://www.linkedin.com/company/euronext/',
      '',
    ),
    b(
      'Dutch State Treasury Agency (DSTA — sovereign primary)',
      'https://www.dsta.nl',
      'info@dsta.nl',
      'https://x.com/DSTA_NL',
      'https://www.linkedin.com/company/dutch-state-treasury-agency/',
      '',
    ),
  ],
  NZ: [
    b(
      'NZX Limited — Debt Market',
      'https://www.nzx.com',
      'info@nzx.com',
      'https://x.com/NZXGroup',
      'https://www.linkedin.com/company/nzx-limited/',
      '',
    ),
    b(
      'New Zealand Debt Management Office (NZDMO — sovereign primary)',
      'https://debtmanagement.treasury.govt.nz',
      'info@treasury.govt.nz',
      '',
      '',
      '',
    ),
  ],
  NO: [
    b(
      'Oslo Børs — Euronext Oslo (listed bonds)',
      'https://www.euronext.com',
      'info@euronext.com',
      'https://x.com/Euronext',
      'https://www.linkedin.com/company/euronext/',
      '',
    ),
    b(
      'Norges Bank — Government Debt Management (sovereign primary)',
      'https://www.norges-bank.no',
      'postmottak@norges-bank.no',
      'https://x.com/NorgesBank',
      'https://www.linkedin.com/company/norges-bank/',
      '',
    ),
  ],
  PL: [
    b(
      'Warsaw Stock Exchange (GPW) — Catalyst bond market',
      'https://www.gpw.pl',
      'info@gpw.pl',
      'https://x.com/Warsaw_Stock',
      'https://www.linkedin.com/company/warsaw-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt (sovereign primary)',
      'https://www.gov.pl/web/finance',
      'info@mf.gov.pl',
      '',
      '',
      '',
    ),
  ],
  PT: [
    b(
      'Euronext Lisbon — Fixed Income Market',
      'https://www.euronext.com',
      'info@euronext.com',
      'https://x.com/Euronext',
      'https://www.linkedin.com/company/euronext/',
      '',
    ),
    b(
      'IGCP — Agência de Gestão da Tesouraria e da Dívida Pública (sovereign primary)',
      'https://www.igcp.pt',
      'info@igcp.pt',
      '',
      '',
      '',
    ),
  ],
  SK: [
    b(
      'Bratislava Stock Exchange (BSSE)',
      'https://www.bsse.sk',
      'info@bsse.sk',
      '',
      '',
      '',
    ),
    b(
      'Agentúra pre riadenie dlhu a likvidity (ARDAL — sovereign primary)',
      'https://www.ardal.sk',
      'info@ardal.sk',
      '',
      '',
      '',
    ),
  ],
  SI: [
    b(
      'Ljubljana Stock Exchange (LJSE)',
      'https://www.ljse.si',
      'info@ljse.si',
      '',
      'https://www.linkedin.com/company/ljubljana-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt (sovereign primary)',
      'https://www.gov.si',
      'info@mf.gov.si',
      '',
      '',
      '',
    ),
  ],
  ES: [
    b(
      'BME — Bolsa y Mercados Españoles (Fixed Income)',
      'https://www.bme.es',
      'info@bme.es',
      'https://x.com/BME_Markets',
      'https://www.linkedin.com/company/bme/',
      '',
    ),
    b(
      'Agencia de Administración de la Deuda Pública (AADP — sovereign primary)',
      'https://www.aadp.es',
      'info@aadp.es',
      '',
      '',
      '',
    ),
  ],
  SE: [
    b(
      'Nasdaq Stockholm — Fixed Income',
      'https://www.nasdaq.com/solutions/nasdaq-nordic',
      'info@nasdaq.com',
      'https://x.com/Nasdaq',
      'https://www.linkedin.com/company/nasdaq/',
      '',
    ),
    b(
      'Swedish National Debt Office (Riksgälden — sovereign primary)',
      'https://www.riksgalden.se',
      'info@riksgalden.se',
      'https://x.com/Riksgalden',
      'https://www.linkedin.com/company/riksgalden/',
      '',
    ),
  ],
  CH: [
    b(
      'SIX Swiss Exchange — Bonds',
      'https://www.six-group.com',
      'info@six-group.com',
      'https://x.com/sixgroup',
      'https://www.linkedin.com/company/six-group/',
      '',
    ),
    b(
      'Swiss Confederation — Federal Finance Administration (FFA — sovereign primary)',
      'https://www.efv.admin.ch',
      'info@efv.admin.ch',
      '',
      '',
      '',
    ),
  ],
  TR: [
    b(
      'Borsa Istanbul — Debt Securities Market',
      'https://www.borsaistanbul.com',
      'info@borsaistanbul.com',
      'https://x.com/BorsaIstanbul',
      'https://www.linkedin.com/company/borsa-istanbul/',
      '',
    ),
    b(
      'Undersecretariat of Treasury — Republic of Türkiye (sovereign primary)',
      'https://www.hmb.gov.tr',
      'bilgi@hmb.gov.tr',
      '',
      '',
      '',
    ),
  ],
  GB: [
    b(
      'London Stock Exchange (LSE) — Main Market / ORB (Order book for Retail Bonds)',
      'https://www.londonstockexchange.com',
      'info@londonstockexchange.com',
      'https://x.com/LSEplc',
      'https://www.linkedin.com/company/london-stock-exchange/',
      '',
    ),
    b(
      'UK Debt Management Office (DMO — sovereign primary)',
      'https://www.dmo.gov.uk',
      'enquiries@dmo.gov.uk',
      'https://x.com/UKDMO',
      'https://www.linkedin.com/company/debt-management-office/',
      '',
    ),
  ],
  US: [
    b(
      'TreasuryDirect — U.S. Department of the Treasury (sovereign primary / retail)',
      'https://www.treasurydirect.gov',
      'treasurydirect@fiscal.treasury.gov',
      'https://x.com/USTreasury',
      'https://www.linkedin.com/company/us-treasury/',
      'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/',
    ),
    b(
      'FINRA — TRACE (corporate bond transaction reporting)',
      'https://www.finra.org/finra-data/fixed-income/trace',
      'info@finra.org',
      'https://x.com/FINRA',
      'https://www.linkedin.com/company/finra/',
      '',
    ),
  ],
}
