import type { OecdMemberIsoCode } from './oecdMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per OECD member economy.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const OECD_DOMESTIC_POST_SERVICES: Record<OecdMemberIsoCode, DomesticPostService> = {
  AU: post(
    'Australia Post',
    'https://auspost.com.au/',
    'feedback@auspost.com.au',
    'https://x.com/AusPost',
    'https://www.instagram.com/auspost/',
    'https://www.linkedin.com/company/australia-post/',
    'https://developers.auspost.com.au/',
    'NNNN',
    '^\\d{4}$',
    '2000',
    'Four-digit postcode',
  ),
  AT: post(
    'Österreichische Post',
    'https://www.post.at/',
    'kundenservice@post.at',
    'https://x.com/post_at',
    'https://www.instagram.com/post_at/',
    'https://www.linkedin.com/company/osterreichische-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1010',
    'Four-digit postcode',
  ),
  BE: post(
    'bpost',
    'https://www.bpost.be/',
    'info@bpost.be',
    'https://x.com/bpost_be',
    'https://www.instagram.com/bpost_be/',
    'https://www.linkedin.com/company/bpost/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  CA: post(
    'Canada Post',
    'https://www.canadapost-postescanada.ca/',
    'customercare@canadapost-postescanada.ca',
    'https://x.com/canadapostcorp',
    'https://www.instagram.com/canadapost/',
    'https://www.linkedin.com/company/canada-post/',
    'https://www.canadapost-postescanada.ca/cpc/en/tools/find-a-postal-code.page',
    'ANA NAN',
    '^[A-Z]\\d[A-Z] \\d[A-Z]\\d$',
    'K1A 0B1',
    'Canadian postal code (letter-digit-letter space digit-letter-digit)',
  ),
  CL: post(
    'Correos de Chile',
    'https://www.correos.cl/',
    'contacto@correos.cl',
    'https://x.com/CorreosChile',
    'https://www.instagram.com/correoschile/',
    'https://www.linkedin.com/company/correos-de-chile/',
    '',
    'NNNNNNN',
    '^\\d{7}$',
    '8320000',
    'Seven-digit postcode',
  ),
  CO: post(
    '4-72 (Correos de Colombia)',
    'https://www.4-72.com.co/',
    'contactenos@4-72.com.co',
    'https://x.com/472Colombia',
    'https://www.instagram.com/472colombia/',
    'https://www.linkedin.com/company/4-72/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '110111',
    'Six-digit código postal',
  ),
  CR: post(
    'Correos de Costa Rica',
    'https://www.correos.go.cr/',
    'atencioncliente@correos.go.cr',
    'https://x.com/CorreosCR',
    '',
    'https://www.linkedin.com/company/correos-de-costa-rica/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10101',
    'Five-digit código postal',
  ),
  CZ: post(
    'Česká pošta',
    'https://www.ceskaposta.cz/',
    'info@ceskaposta.cz',
    'https://x.com/CeskaPosta',
    'https://www.instagram.com/ceskaposta/',
    'https://www.linkedin.com/company/ceska-posta/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '110 00',
    'Five-digit postcode (space after third digit)',
  ),
  DK: post(
    'PostNord Danmark',
    'https://www.postnord.dk/',
    'kundeservice@postnord.dk',
    'https://x.com/PostNordDK',
    'https://www.instagram.com/postnorddk/',
    'https://www.linkedin.com/company/postnord/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1050',
    'Four-digit postcode',
  ),
  EE: post(
    'Omniva (Eesti Post)',
    'https://www.omniva.ee/',
    'info@omniva.ee',
    'https://x.com/OmnivaEE',
    'https://www.instagram.com/omniva/',
    'https://www.linkedin.com/company/omniva/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10111',
    'Five-digit postcode',
  ),
  FI: post(
    'Posti',
    'https://www.posti.fi/',
    'asiakaspalvelu@posti.fi',
    'https://x.com/PostiGroup',
    'https://www.instagram.com/postigroup/',
    'https://www.linkedin.com/company/posti/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00100',
    'Five-digit postcode',
  ),
  FR: post(
    'La Poste',
    'https://www.laposte.fr/',
    'contact@laposte.fr',
    'https://x.com/laposte',
    'https://www.instagram.com/laposte/',
    'https://www.linkedin.com/company/la-poste/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '75001',
    'Five-digit code postal',
  ),
  DE: post(
    'Deutsche Post',
    'https://www.deutschepost.de/',
    'info@deutschepost.de',
    'https://x.com/DeutschePost',
    'https://www.instagram.com/deutschepost/',
    'https://www.linkedin.com/company/deutsche-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10115',
    'Five-digit Postleitzahl',
  ),
  GR: post(
    'ELTA Hellenic Post',
    'https://www.elta.gr/',
    'info@elta.gr',
    'https://x.com/elta_gr',
    'https://www.instagram.com/elta_gr/',
    'https://www.linkedin.com/company/elta-hellenic-post/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '104 31',
    'Five-digit postcode (space after third digit)',
  ),
  HU: post(
    'Magyar Posta',
    'https://www.posta.hu/',
    'ugyfelszolgalat@posta.hu',
    'https://x.com/MagyarPosta',
    'https://www.instagram.com/magyarposta/',
    'https://www.linkedin.com/company/magyar-posta/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1051',
    'Four-digit postcode',
  ),
  IS: post(
    'Pósturinn (Iceland Post)',
    'https://www.postur.is/',
    'postur@postur.is',
    'https://x.com/Posturinn',
    'https://www.instagram.com/posturinn/',
    'https://www.linkedin.com/company/posturinn/',
    '',
    'NNN',
    '^\\d{3}$',
    '101',
    'Three-digit postcode',
  ),
  IE: post(
    'An Post',
    'https://www.anpost.com/',
    'customerservice@anpost.ie',
    'https://x.com/anpost',
    'https://www.instagram.com/anpost/',
    'https://www.linkedin.com/company/an-post/',
    '',
    'A65 F4E2',
    '^[A-Z]\\d{2} [A-Z0-9]{4}$',
    'D02 AF30',
    'Eircode: routing key + unique identifier',
  ),
  IT: post(
    'Poste Italiane',
    'https://www.poste.it/',
    'assistenza.clienti@poste.it',
    'https://x.com/PosteItaliane',
    'https://www.instagram.com/posteitaliane/',
    'https://www.linkedin.com/company/poste-italiane/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00118',
    'Five-digit CAP',
  ),
  JP: post(
    'Japan Post',
    'https://www.post.japanpost.jp/',
    'info@jp-network.japanpost.jp',
    'https://x.com/japanpost_off',
    'https://www.instagram.com/japanpost_off/',
    'https://www.linkedin.com/company/japan-post-holdings/',
    '',
    'NNN-NNNN',
    '^\\d{3}-\\d{4}$',
    '100-0001',
    'Three-digit + four-digit postcode (hyphenated)',
  ),
  LV: post(
    'Latvijas Pasts',
    'https://www.pasts.lv/',
    'info@pasts.lv',
    'https://x.com/LatvijasPasts',
    '',
    'https://www.linkedin.com/company/latvijas-pasts/',
    '',
    'LV-NNNN',
    '^LV-\\d{4}$',
    'LV-1050',
    'LV- prefix + four digits',
  ),
  LT: post(
    'Lietuvos paštas',
    'https://www.post.lt/',
    'info@post.lt',
    'https://x.com/LietuvosPastas',
    '',
    'https://www.linkedin.com/company/lietuvos-pastas/',
    '',
    'LT-NNNNN',
    '^LT-\\d{5}$',
    'LT-01100',
    'LT- prefix + five digits',
  ),
  LU: post(
    'POST Luxembourg',
    'https://www.post.lu/',
    'info@post.lu',
    'https://x.com/POSTLuxembourg',
    'https://www.instagram.com/postluxembourg/',
    'https://www.linkedin.com/company/post-luxembourg/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1019',
    'Four-digit postcode',
  ),
  MX: post(
    'Correos de México',
    'https://www.correosdemexico.gob.mx/',
    'atencionaclientes@correosdemexico.gob.mx',
    'https://x.com/CorreosdeMexico',
    'https://www.instagram.com/correosdemexico/',
    'https://www.linkedin.com/company/correos-de-mexico/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '06000',
    'Five-digit código postal',
  ),
  NL: post(
    'PostNL',
    'https://www.postnl.nl/',
    'klantenservice@postnl.nl',
    'https://x.com/PostNL',
    'https://www.instagram.com/postnl/',
    'https://www.linkedin.com/company/postnl/',
    '',
    'NNNN AA',
    '^\\d{4} [A-Z]{2}$',
    '1012 AB',
    'Four digits + space + two letters',
  ),
  NZ: post(
    'NZ Post',
    'https://www.nzpost.co.nz/',
    'customercare@nzpost.co.nz',
    'https://x.com/NZPost',
    'https://www.instagram.com/nzpost/',
    'https://www.linkedin.com/company/nz-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '6011',
    'Four-digit postcode',
  ),
  NO: post(
    'Posten Norge (PostNord Norge)',
    'https://www.posten.no/',
    'kundeservice@posten.no',
    'https://x.com/PostenNorge',
    'https://www.instagram.com/postennorge/',
    'https://www.linkedin.com/company/posten-norge/',
    '',
    'NNNN',
    '^\\d{4}$',
    '0150',
    'Four-digit postcode',
  ),
  PL: post(
    'Poczta Polska',
    'https://www.poczta-polska.pl/',
    'kontakt@poczta-polska.pl',
    'https://x.com/PocztaPolska',
    'https://www.instagram.com/pocztapolska/',
    'https://www.linkedin.com/company/poczta-polska/',
    '',
    'NN-NNN',
    '^\\d{2}-\\d{3}$',
    '00-950',
    'Five-digit postcode (hyphen after second digit)',
  ),
  PT: post(
    'CTT Correios de Portugal',
    'https://www.ctt.pt/',
    'info@ctt.pt',
    'https://x.com/CTT',
    'https://www.instagram.com/ctt/',
    'https://www.linkedin.com/company/ctt/',
    '',
    'NNNN-NNN',
    '^\\d{4}-\\d{3}$',
    '1000-001',
    'Seven-digit código postal (four + hyphen + three)',
  ),
  SK: post(
    'Slovenská pošta',
    'https://www.posta.sk/',
    'info@posta.sk',
    'https://x.com/SlovenskaPosta',
    '',
    'https://www.linkedin.com/company/slovenska-posta/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '811 01',
    'Five-digit postcode (space after third digit)',
  ),
  SI: post(
    'Pošta Slovenije',
    'https://www.posta.si/',
    'info@posta.si',
    'https://x.com/PostaSlovenije',
    '',
    'https://www.linkedin.com/company/posta-slovenije/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode (SI- prefix optional)',
  ),
  ES: post(
    'Correos',
    'https://www.correos.es/',
    'atencioncliente@correos.es',
    'https://x.com/Correos',
    'https://www.instagram.com/correos/',
    'https://www.linkedin.com/company/correos/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '28001',
    'Five-digit código postal',
  ),
  SE: post(
    'PostNord Sverige',
    'https://www.postnord.se/',
    'kundservice@postnord.se',
    'https://x.com/PostNordSE',
    'https://www.instagram.com/postnordse/',
    'https://www.linkedin.com/company/postnord/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '111 22',
    'Five-digit postcode (space after third digit)',
  ),
  CH: post(
    'Swiss Post (Die Post / La Poste)',
    'https://www.post.ch/',
    'info@post.ch',
    'https://x.com/post_ch',
    'https://www.instagram.com/post_ch/',
    'https://www.linkedin.com/company/swiss-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '3000',
    'Four-digit postcode (Switzerland)',
  ),
  TR: post(
    'PTT (Türkiye Post)',
    'https://www.ptt.gov.tr/',
    'info@ptt.gov.tr',
    'https://x.com/PTT',
    'https://www.instagram.com/ptt/',
    'https://www.linkedin.com/company/ptt/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '06100',
    'Five-digit postcode',
  ),
  GB: post(
    'Royal Mail',
    'https://www.royalmail.com/',
    'customerservice@royalmail.com',
    'https://x.com/RoyalMail',
    'https://www.instagram.com/royalmailofficial/',
    'https://www.linkedin.com/company/royal-mail/',
    'https://developer.royalmail.net/',
    'AAN NAA',
    '^[A-Z]{1,2}\\d[A-Z\\d]? \\d[A-Z]{2}$',
    'SW1A 1AA',
    'UK postcode (outward + inward codes)',
  ),
  US: post(
    'United States Postal Service (USPS)',
    'https://www.usps.com/',
    'uspscustomerservice@usps.gov',
    'https://x.com/USPS',
    'https://www.instagram.com/usps/',
    'https://www.linkedin.com/company/usps/',
    'https://developer.usps.com/',
    'NNNNN',
    '^\\d{5}$',
    '20500',
    'Five-digit ZIP; ZIP+4 optional (NNNNN-NNNN)',
  ),
}
