import type { OecdMemberIsoCode } from './oecdMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const OECD_MAIN_EXPORT_COMMODITIES: Record<OecdMemberIsoCode, MainExportCommodities> = {
  AU: m(
    'Iron ore',
    'Coal',
    'Natural gas',
    'Gold',
    'Wheat',
    'Beef',
    'Education services',
  ),
  AT: m(
    'Machinery',
    'Vehicles',
    'Iron and steel',
    'Packaged medicaments',
    'Paper',
    'Plastics',
    'Electrical machinery',
  ),
  BE: m(
    'Pharmaceuticals',
    'Packaged medicaments',
    'Refined petroleum',
    'Cars',
    'Diamonds',
    'Chemicals',
    'Plastics',
  ),
  CA: m(
    'Crude petroleum',
    'Automobiles',
    'Gold',
    'Wheat',
    'Lumber',
    'Aluminium',
    'Natural gas',
  ),
  CL: m(
    'Copper ore',
    'Refined copper',
    'Lithium carbonate',
    'Fish',
    'Wine',
    'Wood pulp',
    'Fruit',
  ),
  CO: m(
    'Crude petroleum',
    'Coal',
    'Coffee',
    'Refined petroleum',
    'Gold',
    'Cut flowers',
    'Bananas',
  ),
  CR: m(
    'Bananas',
    'Pineapples',
    'Medical instruments',
    'Coffee',
    'Pharmaceuticals',
    'Sugar',
    'Tropical fruit',
  ),
  CZ: m(
    'Automobiles',
    'Machinery',
    'Electricity',
    'Packaged medicaments',
    'Computers',
    'Iron and steel',
    'Plastics',
  ),
  DK: m(
    'Packaged medicaments',
    'Fish',
    'Pork',
    'Machinery',
    'Refined petroleum',
    'Electricity',
    'Cheese',
  ),
  EE: m(
    'Telecommunications equipment',
    'Wood products',
    'Electrical machinery',
    'Refined petroleum',
    'Fish',
    'Computers',
    'Grain',
  ),
  FI: m(
    'Refined petroleum',
    'Paper pulp',
    'Packaged medicaments',
    'Machinery',
    'Fish',
    'Electrical machinery',
    'Copper',
  ),
  FR: m(
    'Aircraft',
    'Packaged medicaments',
    'Wine',
    'Refined petroleum',
    'Automobiles',
    'Wheat',
    'Pharmaceuticals',
  ),
  DE: m(
    'Automobiles',
    'Packaged medicaments',
    'Machinery',
    'Refined petroleum',
    'Electrical machinery',
    'Plastics',
    'Iron and steel',
  ),
  GR: m(
    'Refined petroleum',
    'Packaged medicaments',
    'Fish',
    'Aluminium',
    'Olive oil',
    'Vegetables',
    'Tourism services',
  ),
  HU: m(
    'Automobiles',
    'Packaged medicaments',
    'Electricity',
    'Machinery',
    'Computers',
    'Pharmaceuticals',
    'Plastics',
  ),
  IS: m(
    'Aluminium',
    'Fish',
    'Marine products',
    'Ferrosilicon',
    'Pharmaceuticals',
    'Wool',
    'Tourism services',
  ),
  IE: m(
    'Packaged medicaments',
    'Organic chemicals',
    'Computers',
    'Aircraft',
    'Medical instruments',
    'Dairy',
    'Whiskey',
  ),
  IT: m(
    'Machinery',
    'Packaged medicaments',
    'Automobiles',
    'Refined petroleum',
    'Wine',
    'Clothing',
    'Furniture',
  ),
  JP: m(
    'Automobiles',
    'Machinery',
    'Electrical machinery',
    'Iron and steel',
    'Plastics',
    'Optical instruments',
    'Ships',
  ),
  LV: m(
    'Refined petroleum',
    'Wheat',
    'Timber',
    'Packaged medicaments',
    'Fish',
    'Electricity',
    'Machinery',
  ),
  LT: m(
    'Refined petroleum',
    'Furniture',
    'Wheat',
    'Packaged medicaments',
    'Machinery',
    'Plastics',
    'Electricity',
  ),
  LU: m(
    'Iron and steel',
    'Packaged medicaments',
    'Rubber tires',
    'Glass',
    'Machinery',
    'Plastics',
    'Aluminium',
  ),
  MX: m(
    'Automobiles',
    'Crude petroleum',
    'Trucks',
    'Computers',
    'Avocados',
    'Beer',
    'Medical instruments',
  ),
  NL: m(
    'Refined petroleum',
    'Packaged medicaments',
    'Machinery',
    'Electrical machinery',
    'Natural gas',
    'Flowers',
    'Tomatoes',
  ),
  NZ: m(
    'Dairy products',
    'Meat',
    'Wood',
    'Fruit',
    'Wine',
    'Aluminium',
    'Fish',
  ),
  NO: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Fish',
    'Aluminium',
    'Machinery',
    'Ships',
  ),
  PL: m(
    'Automobiles',
    'Packaged medicaments',
    'Furniture',
    'Electricity',
    'Computers',
    'Meat',
    'Iron and steel',
  ),
  PT: m(
    'Automobiles',
    'Refined petroleum',
    'Packaged medicaments',
    'Wine',
    'Olive oil',
    'Footwear',
    'Paper pulp',
  ),
  SK: m(
    'Automobiles',
    'Packaged medicaments',
    'Televisions',
    'Machinery',
    'Iron and steel',
    'Refined petroleum',
    'Plastics',
  ),
  SI: m(
    'Packaged medicaments',
    'Automobiles',
    'Refined petroleum',
    'Electricity',
    'Machinery',
    'Aluminium',
    'Wood products',
  ),
  ES: m(
    'Cars',
    'Refined petroleum',
    'Packaged medicaments',
    'Pork',
    'Wine',
    'Fruit and vegetables',
    'Tourism services',
  ),
  SE: m(
    'Packaged medicaments',
    'Refined petroleum',
    'Machinery',
    'Cars',
    'Iron ore',
    'Telecommunications equipment',
    'Paper pulp',
  ),
  CH: m(
    'Pharmaceuticals',
    'Watches',
    'Gold',
    'Machinery',
    'Chemicals',
    'Medical instruments',
    'Precision instruments',
  ),
  TR: m(
    'Automobiles',
    'Refined petroleum',
    'Iron and steel',
    'Textiles',
    'Machinery',
    'Gold',
    'Jewellery',
  ),
  GB: m(
    'Gold',
    'Cars',
    'Packaged medicaments',
    'Crude petroleum',
    'Gas turbines',
    'Scotch whisky',
    'Aircraft parts',
  ),
  US: m(
    'Refined petroleum',
    'Aircraft',
    'Natural gas',
    'Semiconductors',
    'Gold',
    'Soybeans',
    'Corn',
  ),
}
