import type { OecdMemberIsoCode } from './oecdMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const OECD_MAIN_INTERNATIONAL_AIRPORTS: Record<OecdMemberIsoCode, MainInternationalAirport> = {
  AU: {
    name: 'Sydney Kingsford Smith Airport (SYD)',
    website: 'https://www.sydneyairport.com.au/',
    email: 'info@sydneyairport.com.au',
    twitter: 'https://x.com/SydneyAirport',
    instagram: 'https://www.instagram.com/sydneyairport/',
    linkedin: 'https://www.linkedin.com/company/sydney-airport/',
    apiEndpoint: '',
  },
  AT: {
    name: 'Vienna International Airport (VIE)',
    website: 'https://www.viennaairport.com/',
    email: 'info@viennaairport.com',
    twitter: 'https://x.com/viennaairport',
    instagram: 'https://www.instagram.com/viennaairport/',
    linkedin: 'https://www.linkedin.com/company/flughafen-wien-ag/',
    apiEndpoint: '',
  },
  BE: {
    name: 'Brussels Airport (BRU)',
    website: 'https://www.brusselsairport.be/',
    email: 'info@brusselsairport.be',
    twitter: 'https://x.com/BrusselsAirport',
    instagram: 'https://www.instagram.com/brusselsairport/',
    linkedin: 'https://www.linkedin.com/company/brussels-airport/',
    apiEndpoint: '',
  },
  CA: {
    name: 'Toronto Pearson International Airport (YYZ)',
    website: 'https://www.torontopearson.com/',
    email: 'info@torontopearson.com',
    twitter: 'https://x.com/TorontoPearson',
    instagram: 'https://www.instagram.com/torontopearson/',
    linkedin: 'https://www.linkedin.com/company/toronto-pearson-international-airport/',
    apiEndpoint: '',
  },
  CL: {
    name: 'Arturo Merino Benítez International Airport (SCL)',
    website: 'https://www.nuestroaeropuerto.cl/',
    email: 'contacto@nuestroaeropuerto.cl',
    twitter: 'https://x.com/AeropuertoSCL',
    instagram: 'https://www.instagram.com/aeropuertoscl/',
    linkedin: 'https://www.linkedin.com/company/nuevo-aeropuerto-internacional-arturo-merino-benitez/',
    apiEndpoint: '',
  },
  CO: {
    name: 'El Dorado International Airport (BOG)',
    website: 'https://www.eldorado.aero/',
    email: 'info@eldorado.aero',
    twitter: 'https://x.com/BOG_ELDORADO',
    instagram: 'https://www.instagram.com/bog_eldorado/',
    linkedin: 'https://www.linkedin.com/company/el-dorado-international-airport/',
    apiEndpoint: '',
  },
  CR: {
    name: 'Juan Santamaría International Airport (SJO)',
    website: 'https://www.sjoairport.com/',
    email: 'info@sjoairport.com',
    twitter: 'https://x.com/SJOAirport',
    instagram: 'https://www.instagram.com/sjoairport/',
    linkedin: 'https://www.linkedin.com/company/juan-santamaria-international-airport/',
    apiEndpoint: '',
  },
  CZ: {
    name: 'Václav Havel Airport Prague (PRG)',
    website: 'https://www.prg.aero/',
    email: 'info@prg.aero',
    twitter: 'https://x.com/PragueAirport',
    instagram: 'https://www.instagram.com/pragueairport/',
    linkedin: 'https://www.linkedin.com/company/prague-airport/',
    apiEndpoint: '',
  },
  DK: {
    name: 'Copenhagen Airport (CPH)',
    website: 'https://www.cph.dk/',
    email: 'info@cph.dk',
    twitter: 'https://x.com/CopenhagenAirport',
    instagram: 'https://www.instagram.com/copenhagenairport/',
    linkedin: 'https://www.linkedin.com/company/copenhagen-airports/',
    apiEndpoint: '',
  },
  EE: {
    name: 'Tallinn Airport (TLL)',
    website: 'https://www.tallinn-airport.ee/',
    email: 'info@tallinn-airport.ee',
    twitter: 'https://x.com/TallinnAirport',
    instagram: 'https://www.instagram.com/tallinnairport/',
    linkedin: 'https://www.linkedin.com/company/tallinn-airport/',
    apiEndpoint: '',
  },
  FI: {
    name: 'Helsinki-Vantaa Airport (HEL)',
    website: 'https://www.finavia.fi/en/airports/helsinki-airport',
    email: 'helsinki-airport@finavia.fi',
    twitter: 'https://x.com/HelsinkiAirport',
    instagram: 'https://www.instagram.com/helsinkiairport/',
    linkedin: 'https://www.linkedin.com/company/finavia/',
    apiEndpoint: '',
  },
  FR: {
    name: 'Paris Charles de Gaulle Airport (CDG)',
    website: 'https://www.parisaeroport.fr/',
    email: 'contact@adp.fr',
    twitter: 'https://x.com/ParisAeroport',
    instagram: 'https://www.instagram.com/parisaeroport/',
    linkedin: 'https://www.linkedin.com/company/groupe-adp/',
    apiEndpoint: '',
  },
  DE: {
    name: 'Frankfurt Airport (FRA)',
    website: 'https://www.frankfurt-airport.com/',
    email: 'info@fraport.de',
    twitter: 'https://x.com/Airport_FRA',
    instagram: 'https://www.instagram.com/airport_fra/',
    linkedin: 'https://www.linkedin.com/company/frankfurt-airport/',
    apiEndpoint: '',
  },
  GR: {
    name: 'Athens International Airport (ATH)',
    website: 'https://www.aia.gr/',
    email: 'info@aia.gr',
    twitter: 'https://x.com/ATH_airport',
    instagram: 'https://www.instagram.com/athens_airport/',
    linkedin: 'https://www.linkedin.com/company/athens-international-airport/',
    apiEndpoint: '',
  },
  HU: {
    name: 'Budapest Ferenc Liszt International Airport (BUD)',
    website: 'https://www.bud.hu/',
    email: 'info@bud.hu',
    twitter: 'https://x.com/BudapestAirport',
    instagram: 'https://www.instagram.com/budapestairport/',
    linkedin: 'https://www.linkedin.com/company/budapest-airport/',
    apiEndpoint: '',
  },
  IS: {
    name: 'Keflavík International Airport (KEF)',
    website: 'https://www.isavia.is/',
    email: 'info@isavia.is',
    twitter: 'https://x.com/KEF_Airport',
    instagram: 'https://www.instagram.com/kef_airport/',
    linkedin: 'https://www.linkedin.com/company/isavia/',
    apiEndpoint: '',
  },
  IE: {
    name: 'Dublin Airport (DUB)',
    website: 'https://www.dublinairport.com/',
    email: 'info@dublinairport.com',
    twitter: 'https://x.com/DublinAirport',
    instagram: 'https://www.instagram.com/dublinairport/',
    linkedin: 'https://www.linkedin.com/company/dublin-airport/',
    apiEndpoint: '',
  },
  IT: {
    name: 'Leonardo da Vinci–Fiumicino Airport (FCO)',
    website: 'https://www.adr.it/',
    email: 'info@adr.it',
    twitter: 'https://x.com/ADRAirports',
    instagram: 'https://www.instagram.com/adr_airports/',
    linkedin: 'https://www.linkedin.com/company/adr-aeroporti-di-roma/',
    apiEndpoint: '',
  },
  JP: {
    name: 'Tokyo Haneda Airport (HND)',
    website: 'https://www.haneda-airport.jp/',
    email: 'info@haneda-airport.jp',
    twitter: 'https://x.com/TokyoHaneda',
    instagram: 'https://www.instagram.com/tokyohaneda/',
    linkedin: 'https://www.linkedin.com/company/tokyo-international-airport/',
    apiEndpoint: '',
  },
  LV: {
    name: 'Riga International Airport (RIX)',
    website: 'https://www.riga-airport.com/',
    email: 'info@riga-airport.com',
    twitter: 'https://x.com/RigaAirport',
    instagram: 'https://www.instagram.com/rigaairport/',
    linkedin: 'https://www.linkedin.com/company/riga-international-airport/',
    apiEndpoint: '',
  },
  LT: {
    name: 'Vilnius Airport (VNO)',
    website: 'https://www.vilnius-airport.lt/',
    email: 'info@vilnius-airport.lt',
    twitter: 'https://x.com/VilniusAirport',
    instagram: 'https://www.instagram.com/vilniusairport/',
    linkedin: 'https://www.linkedin.com/company/vilnius-airport/',
    apiEndpoint: '',
  },
  LU: {
    name: 'Luxembourg Airport (LUX)',
    website: 'https://www.lux-airport.lu/',
    email: 'info@lux-airport.lu',
    twitter: 'https://x.com/LuxAirport',
    instagram: 'https://www.instagram.com/luxairport/',
    linkedin: 'https://www.linkedin.com/company/luxembourg-airport/',
    apiEndpoint: '',
  },
  MX: {
    name: 'Mexico City International Airport (MEX)',
    website: 'https://www.aicm.com.mx/',
    email: 'contacto@aicm.com.mx',
    twitter: 'https://x.com/AICM_mx',
    instagram: 'https://www.instagram.com/aicm_mx/',
    linkedin: 'https://www.linkedin.com/company/aeropuerto-internacional-de-la-ciudad-de-mexico/',
    apiEndpoint: '',
  },
  NL: {
    name: 'Amsterdam Airport Schiphol (AMS)',
    website: 'https://www.schiphol.nl/',
    email: 'info@schiphol.nl',
    twitter: 'https://x.com/Schiphol',
    instagram: 'https://www.instagram.com/schiphol/',
    linkedin: 'https://www.linkedin.com/company/amsterdam-airport-schiphol/',
    apiEndpoint: '',
  },
  NZ: {
    name: 'Auckland Airport (AKL)',
    website: 'https://www.aucklandairport.co.nz/',
    email: 'info@aucklandairport.co.nz',
    twitter: 'https://x.com/AucklandAirport',
    instagram: 'https://www.instagram.com/aucklandairport/',
    linkedin: 'https://www.linkedin.com/company/auckland-airport/',
    apiEndpoint: '',
  },
  NO: {
    name: 'Oslo Airport Gardermoen (OSL)',
    website: 'https://www.osl.no/',
    email: 'info@osl.no',
    twitter: 'https://x.com/OslAirport',
    instagram: 'https://www.instagram.com/oslairport/',
    linkedin: 'https://www.linkedin.com/company/oslo-airport/',
    apiEndpoint: '',
  },
  PL: {
    name: 'Warsaw Chopin Airport (WAW)',
    website: 'https://www.lot.com/pl/en/warsaw-chopin-airport',
    email: 'info@chopin-airport.pl',
    twitter: 'https://x.com/ChopinAirport',
    instagram: 'https://www.instagram.com/chopinairport/',
    linkedin: 'https://www.linkedin.com/company/chopin-airport/',
    apiEndpoint: '',
  },
  PT: {
    name: 'Lisbon Humberto Delgado Airport (LIS)',
    website: 'https://www.ana.pt/',
    email: 'info@ana.pt',
    twitter: 'https://x.com/ANA_Aeroportos',
    instagram: 'https://www.instagram.com/ana_aeroportos/',
    linkedin: 'https://www.linkedin.com/company/ana-aeroportos-de-portugal/',
    apiEndpoint: '',
  },
  SK: {
    name: 'M. R. Štefánik Airport (BTS)',
    website: 'https://www.airportbratislava.sk/',
    email: 'info@airportbratislava.sk',
    twitter: 'https://x.com/BTSairport',
    instagram: 'https://www.instagram.com/btsairport/',
    linkedin: 'https://www.linkedin.com/company/bratislava-airport/',
    apiEndpoint: '',
  },
  SI: {
    name: 'Ljubljana Jože Pučnik Airport (LJU)',
    website: 'https://www.lju-airport.si/',
    email: 'info@lju-airport.si',
    twitter: 'https://x.com/LJUairport',
    instagram: 'https://www.instagram.com/ljuairport/',
    linkedin: 'https://www.linkedin.com/company/ljubljana-airport/',
    apiEndpoint: '',
  },
  ES: {
    name: 'Adolfo Suárez Madrid–Barajas Airport (MAD)',
    website: 'https://www.aena.es/',
    email: 'info@aena.es',
    twitter: 'https://x.com/Aena',
    instagram: 'https://www.instagram.com/aena/',
    linkedin: 'https://www.linkedin.com/company/aena/',
    apiEndpoint: '',
  },
  SE: {
    name: 'Stockholm Arlanda Airport (ARN)',
    website: 'https://www.swedavia.com/arlanda/',
    email: 'info@swedavia.se',
    twitter: 'https://x.com/Arlanda',
    instagram: 'https://www.instagram.com/arlanda/',
    linkedin: 'https://www.linkedin.com/company/swedavia/',
    apiEndpoint: '',
  },
  CH: {
    name: 'Zurich Airport (ZRH)',
    website: 'https://www.flughafen-zuerich.ch/',
    email: 'info@flughafen-zuerich.ch',
    twitter: 'https://x.com/ZurichAirport',
    instagram: 'https://www.instagram.com/zurichairport/',
    linkedin: 'https://www.linkedin.com/company/flughafen-zurich/',
    apiEndpoint: '',
  },
  TR: {
    name: 'Istanbul Airport (IST)',
    website: 'https://www.istairport.com/',
    email: 'info@istairport.com',
    twitter: 'https://x.com/istanbulairport',
    instagram: 'https://www.instagram.com/istanbulairport/',
    linkedin: 'https://www.linkedin.com/company/istanbul-airport/',
    apiEndpoint: '',
  },
  GB: {
    name: 'Heathrow Airport (LHR)',
    website: 'https://www.heathrow.com/',
    email: 'customer.service@heathrow.com',
    twitter: 'https://x.com/HeathrowAirport',
    instagram: 'https://www.instagram.com/heathrowairport/',
    linkedin: 'https://www.linkedin.com/company/heathrow-airport/',
    apiEndpoint: '',
  },
  US: {
    name: 'Los Angeles International Airport (LAX)',
    website: 'https://www.flylax.com/',
    email: 'info@lawa.org',
    twitter: 'https://x.com/flyLAXairport',
    instagram: 'https://www.instagram.com/flylax/',
    linkedin: 'https://www.linkedin.com/company/los-angeles-world-airports/',
    apiEndpoint: '',
  },
}
