import type { OecdMemberIsoCode } from './oecdMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2 for the
 * 36 OECD economies represented in this module (informational; verify against USGS Mineral
 * Commodity Summaries, BGS World Mineral Production, BGR DERA, and UN Comtrade periodically).
 * OECD spans large primary producers (AU, CA, CL, US, MX, NO, SE, FI), refining and re-export
 * hubs (DE, NL, BE, JP, IT, FR, GB, CH), and small specialised exporters (IS Al / Si, IE small
 * Zn-Pb, LU steel finishing). Hydrocarbon-derived elemental references (Carbon (C), Hydrogen
 * (H)) appear for major crude / gas / coal exporters (AU, CA, NO, US, GB, CO coal).
 */
export const OECD_MAIN_EXPORTED_ELEMENTS: Record<OecdMemberIsoCode, MainExportedElements> = {
  AU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Lithium (Li)',
    'Gold (Au)',
    'Copper (Cu)',
    'Uranium (U)',
  ),
  AT: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Tungsten (W)',
    'Magnesium (Mg)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Copper (Cu)',
  ),
  BE: e(
    'Copper (Cu)',
    'Zinc (Zn)',
    'Cobalt (Co)',
    'Germanium (Ge)',
    'Indium (In)',
    'Silver (Ag)',
    'Iron (Fe)',
  ),
  CA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Potassium (K)',
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Gold (Au)',
    'Uranium (U)',
  ),
  CL: e(
    'Copper (Cu)',
    'Lithium (Li)',
    'Molybdenum (Mo)',
    'Iodine (I)',
    'Silver (Ag)',
    'Gold (Au)',
    'Iron (Fe)',
  ),
  CO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Nickel (Ni)',
    'Gold (Au)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Sulfur (S)',
  ),
  CR: e(
    'Calcium (Ca)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Gold (Au)',
    'Sodium (Na)',
  ),
  CZ: e(
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Lithium (Li)',
  ),
  DK: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Nitrogen (N)',
  ),
  EE: e(
    'Carbon (C)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Phosphorus (P)',
    'Hydrogen (H)',
  ),
  FI: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Chromium (Cr)',
    'Iron (Fe)',
    'Gold (Au)',
  ),
  FR: e(
    'Uranium (U)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Titanium (Ti)',
    'Gold (Au)',
  ),
  DE: e(
    'Carbon (C)',
    'Copper (Cu)',
    'Potassium (K)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Gallium (Ga)',
  ),
  GR: e(
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Iron (Fe)',
    'Magnesium (Mg)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Zinc (Zn)',
  ),
  HU: e(
    'Aluminum (Al)',
    'Manganese (Mn)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  IS: e(
    'Aluminum (Al)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Chlorine (Cl)',
    'Hydrogen (H)',
  ),
  IE: e(
    'Zinc (Zn)',
    'Lead (Pb)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Copper (Cu)',
  ),
  IT: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Lead (Pb)',
    'Zinc (Zn)',
  ),
  JP: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Indium (In)',
    'Silicon (Si)',
    'Iodine (I)',
  ),
  LV: e(
    'Calcium (Ca)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Sodium (Na)',
    'Magnesium (Mg)',
  ),
  LT: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Nitrogen (N)',
  ),
  LU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  MX: e(
    'Silver (Ag)',
    'Copper (Cu)',
    'Gold (Au)',
    'Zinc (Zn)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Carbon (C)',
  ),
  NL: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Nitrogen (N)',
    'Sulfur (S)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Iron (Fe)',
  ),
  NZ: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Carbon (C)',
    'Gold (Au)',
    'Sodium (Na)',
  ),
  NO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Iron (Fe)',
  ),
  PL: e(
    'Copper (Cu)',
    'Silver (Ag)',
    'Carbon (C)',
    'Sulfur (S)',
    'Zinc (Zn)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  PT: e(
    'Copper (Cu)',
    'Tungsten (W)',
    'Tin (Sn)',
    'Lithium (Li)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  SK: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Magnesium (Mg)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  SI: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  ES: e(
    'Copper (Cu)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Tungsten (W)',
    'Calcium (Ca)',
  ),
  SE: e(
    'Iron (Fe)',
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Aluminum (Al)',
  ),
  CH: e(
    'Gold (Au)',
    'Silver (Ag)',
    'Platinum (Pt)',
    'Palladium (Pd)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
  ),
  TR: e(
    'Iron (Fe)',
    'Chromium (Cr)',
    'Copper (Cu)',
    'Boron (B)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Zinc (Zn)',
  ),
  GB: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Lithium (Li)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Tin (Sn)',
  ),
  US: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Helium (He)',
    'Copper (Cu)',
    'Gold (Au)',
    'Molybdenum (Mo)',
    'Silicon (Si)',
  ),
}
