import type { OecdMemberIsoCode } from './oecdMemberIsoCodes'
import type { SecuritiesExchangeCommission } from './types'

function sec(
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): SecuritiesExchangeCommission {
  return { name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

/**
 * Securities and exchange / capital-markets commission by ISO 3166-1 alpha-2 for OECD
 * member economies in this module (informational; verify URLs, handles, forms portals,
 * and API bases before production use). Self-contained — no imports from other alliance
 * modules. `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.iosco.org/about/membership/
 */
export const OECD_SECURITIES_EXCHANGE_COMMISSIONS: Record<
  OecdMemberIsoCode,
  SecuritiesExchangeCommission
> = {
  AU: sec(
    'Australian Securities and Investments Commission (ASIC)',
    'https://asic.gov.au',
    'enquiries@asic.gov.au',
    'https://x.com/ASICConnect',
    'https://www.linkedin.com/company/asic/',
    'https://asic.gov.au/online-services/',
  ),
  AT: sec(
    'Financial Market Authority Austria (FMA)',
    'https://www.fma.gv.at',
    'fma@fma.gv.at',
    'https://x.com/FMA_Austria',
    'https://www.linkedin.com/company/fma-österreich/',
    'https://www.fma.gv.at',
  ),
  BE: sec(
    'Financial Services and Markets Authority Belgium (FSMA)',
    'https://www.fsma.be',
    'info@fsma.be',
    'https://x.com/FSMAbelgique',
    'https://www.linkedin.com/company/fsma/',
    'https://www.fsma.be',
  ),
  CA: sec(
    'Canadian Securities Administrators (CSA)',
    'https://www.securities-administrators.ca',
    'info@csa-acvm.ca',
    'https://x.com/CSA_News',
    'https://www.linkedin.com/company/canadian-securities-administrators/',
    'https://www.securities-administrators.ca',
  ),
  CL: sec(
    'Comisión para el Mercado Financiero (CMF Chile)',
    'https://www.cmfchile.cl',
    'cmf@cmfchile.cl',
    'https://x.com/cmfchile',
    'https://www.linkedin.com/company/comisión-para-el-mercado-financiero/',
    'https://www.cmfchile.cl',
  ),
  CO: sec(
    'Superintendencia Financiera de Colombia (SFC)',
    'https://www.superfinanciera.gov.co',
    'sfc@superfinanciera.gov.co',
    'https://x.com/SuperFinanciera',
    'https://www.linkedin.com/company/superintendencia-financiera-de-colombia/',
    'https://www.superfinanciera.gov.co',
  ),
  CR: sec(
    'Superintendencia General de Valores Costa Rica (SUGEVAL)',
    'https://www.sugeval.fi.cr',
    'sugeval@sugeval.fi.cr',
    '',
    'https://www.linkedin.com/company/sugeval/',
    'https://www.sugeval.fi.cr',
  ),
  CZ: sec(
    'Czech National Bank (CNB) — capital-markets supervision',
    'https://www.cnb.cz',
    'info@cnb.cz',
    '',
    'https://www.linkedin.com/company/czech-national-bank/',
    'https://www.cnb.cz',
  ),
  DK: sec(
    'Danish Financial Supervisory Authority (Finanstilsynet)',
    'https://www.finanstilsynet.dk',
    'finanstilsynet@finanstilsynet.dk',
    'https://x.com/Finanstilsynet',
    'https://www.linkedin.com/company/finanstilsynet/',
    'https://www.finanstilsynet.dk',
  ),
  EE: sec(
    'Estonian Financial Supervision and Resolution Authority (Finantsinspektsioon)',
    'https://www.fi.ee',
    'info@fi.ee',
    '',
    'https://www.linkedin.com/company/finantsinspektsioon/',
    'https://www.fi.ee',
  ),
  FI: sec(
    'Finnish Financial Supervisory Authority (Finanssivalvonta / FIN-FSA)',
    'https://www.finanssivalvonta.fi',
    'kirjaamo@finanssivalvonta.fi',
    'https://x.com/Finanssivalvonta',
    'https://www.linkedin.com/company/finanssivalvonta/',
    'https://www.finanssivalvonta.fi',
  ),
  FR: sec(
    'Autorité des marchés financiers (AMF France)',
    'https://www.amf-france.org',
    'relationsemet@amf-france.org',
    'https://x.com/AMF_actu',
    'https://www.linkedin.com/company/autorité-des-marchés-financiers-amf/',
    'https://www.amf-france.org',
  ),
  DE: sec(
    'Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin)',
    'https://www.bafin.de',
    'poststelle@bafin.de',
    'https://x.com/BaFin_de',
    'https://www.linkedin.com/company/bafin/',
    'https://www.bafin.de',
  ),
  GR: sec(
    'Hellenic Capital Market Commission (HCMC)',
    'https://www.hcmc.gr',
    'info@hcmc.gr',
    '',
    'https://www.linkedin.com/company/hellenic-capital-market-commission/',
    'https://www.hcmc.gr',
  ),
  HU: sec(
    'Magyar Nemzeti Bank (MNB) — financial markets supervision',
    'https://www.mnb.hu',
    'info@mnb.hu',
    'https://x.com/mnbhu',
    'https://www.linkedin.com/company/mnb-magyar-nemzeti-bank/',
    'https://www.mnb.hu',
  ),
  IS: sec(
    'Financial Supervisory Authority Iceland (Fjármálaeftirlitið / FME)',
    'https://www.fme.is',
    'fme@fme.is',
    '',
    'https://www.linkedin.com/company/fjármálaeftirlitið/',
    'https://www.fme.is',
  ),
  IE: sec(
    'Central Bank of Ireland — securities supervision',
    'https://www.centralbank.ie',
    'enquiries@centralbank.ie',
    'https://x.com/centralbankie',
    'https://www.linkedin.com/company/central-bank-of-ireland/',
    'https://www.centralbank.ie',
  ),
  IT: sec(
    'Commissione Nazionale per le Società e la Borsa (CONSOB)',
    'https://www.consob.it',
    'consob@consob.it',
    'https://x.com/consob_it',
    'https://www.linkedin.com/company/consob/',
    'https://www.consob.it',
  ),
  JP: sec(
    'Financial Services Agency Japan (FSA)',
    'https://www.fsa.go.jp',
    'info@fsa.go.jp',
    'https://x.com/FSA_JAPAN',
    'https://www.linkedin.com/company/financial-services-agency-japan/',
    'https://www.fsa.go.jp',
  ),
  LV: sec(
    'Financial and Capital Market Commission Latvia (FKTK)',
    'https://www.fktk.lv',
    'fktk@fktk.lv',
    '',
    'https://www.linkedin.com/company/financial-and-capital-market-commission-fktk/',
    'https://www.fktk.lv',
  ),
  LT: sec(
    'Bank of Lithuania — capital-markets supervision',
    'https://www.lb.lt',
    'info@lb.lt',
    'https://x.com/BankofLithuania',
    'https://www.linkedin.com/company/bank-of-lithuania/',
    'https://www.lb.lt',
  ),
  LU: sec(
    'Commission de Surveillance du Secteur Financier (CSSF Luxembourg)',
    'https://www.cssf.lu',
    'info@cssf.lu',
    'https://x.com/CSSF_Luxembourg',
    'https://www.linkedin.com/company/cssf/',
    'https://www.cssf.lu',
  ),
  MX: sec(
    'Comisión Nacional Bancaria y de Valores (CNBV Mexico)',
    'https://www.gob.mx/cnbv',
    'contacto@cnbv.gob.mx',
    'https://x.com/CNBV_mx',
    'https://www.linkedin.com/company/cnbv/',
    'https://www.gob.mx/cnbv',
  ),
  NL: sec(
    'Autoriteit Financiële Markten (AFM Netherlands)',
    'https://www.afm.nl',
    'info@afm.nl',
    'https://x.com/AFM_NL',
    'https://www.linkedin.com/company/autoriteit-financiële-markten/',
    'https://www.afm.nl',
  ),
  NZ: sec(
    'Financial Markets Authority (FMA New Zealand)',
    'https://www.fma.govt.nz',
    'info@fma.govt.nz',
    'https://x.com/FMANZgov',
    'https://www.linkedin.com/company/financial-markets-authority/',
    'https://www.fma.govt.nz',
  ),
  NO: sec(
    'Financial Supervisory Authority of Norway (Finanstilsynet)',
    'https://www.finanstilsynet.no',
    'post@finanstilsynet.no',
    'https://x.com/Finanstilsynet',
    'https://www.linkedin.com/company/finanstilsynet/',
    'https://www.finanstilsynet.no',
  ),
  PL: sec(
    'Polish Financial Supervision Authority (KNF)',
    'https://www.knf.gov.pl',
    'knf@knf.gov.pl',
    'https://x.com/KNFpl',
    'https://www.linkedin.com/company/urząd-komisji-nadzoru-finansowego/',
    'https://www.knf.gov.pl',
  ),
  PT: sec(
    'Comissão do Mercado de Valores Mobiliários (CMVM Portugal)',
    'https://www.cmvm.pt',
    'cmvm@cmvm.pt',
    'https://x.com/CMVM_pt',
    'https://www.linkedin.com/company/cmvm/',
    'https://www.cmvm.pt',
  ),
  SK: sec(
    'National Bank of Slovakia (NBS) — capital-markets supervision',
    'https://www.nbs.sk',
    'info@nbs.sk',
    '',
    'https://www.linkedin.com/company/national-bank-of-slovakia/',
    'https://www.nbs.sk',
  ),
  SI: sec(
    'Securities Market Agency Slovenia (ATVP)',
    'https://www.atvp.si',
    'atvp@atvp.si',
    '',
    '',
    'https://www.atvp.si',
  ),
  ES: sec(
    'Comisión Nacional del Mercado de Valores (CNMV Spain)',
    'https://www.cnmv.es',
    'cnmv@cnmv.es',
    'https://x.com/cnmv_es',
    'https://www.linkedin.com/company/cnmv/',
    'https://www.cnmv.es',
  ),
  SE: sec(
    'Finansinspektionen (FI Sweden)',
    'https://www.fi.se',
    'finansinspektionen@fi.se',
    'https://x.com/FI_nyheter',
    'https://www.linkedin.com/company/finansinspektionen/',
    'https://www.fi.se',
  ),
  CH: sec(
    'Swiss Financial Market Supervisory Authority (FINMA)',
    'https://www.finma.ch',
    'info@finma.ch',
    'https://x.com/FINMA_media',
    'https://www.linkedin.com/company/finma/',
    'https://www.finma.ch',
  ),
  TR: sec(
    'Capital Markets Board of Turkey (SPK)',
    'https://www.spk.gov.tr',
    'spk@spk.gov.tr',
    'https://x.com/SPK_Kurumu',
    'https://www.linkedin.com/company/sermaye-piyasası-kurulu/',
    'https://www.spk.gov.tr',
  ),
  GB: sec(
    'Financial Conduct Authority (FCA United Kingdom)',
    'https://www.fca.org.uk',
    'consumer.queries@fca.org.uk',
    'https://x.com/TheFCA',
    'https://www.linkedin.com/company/financial-conduct-authority/',
    'https://www.fca.org.uk',
  ),
  US: sec(
    'U.S. Securities and Exchange Commission (SEC)',
    'https://www.sec.gov',
    'help@sec.gov',
    'https://x.com/SECGov',
    'https://www.linkedin.com/company/us-securities-and-exchange-commission/',
    'https://www.sec.gov/forms',
  ),
}
