import type { CorporationFormationOffice } from './types'
import type { EcowasMemberIsoCode } from './ecowasMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per ECOWAS member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const ECOWAS_CORPORATION_FORMATION_OFFICES: Record<EcowasMemberIsoCode, CorporationFormationOffice> = {
  BJ:   office(
    'APIEx Benin - Guichet Unique de Formalisation des Entreprises',
    '+229 21 31 00 65',
    'Boulevard de la Marina, Cotonou, Benin',
    'https://apiex.bj',
    'info@apiex.bj',
    'https://x.com/APIEX_BENIN',
    '',
    'https://www.linkedin.com/company/apiex-benin/',
    'https://monentreprise.bj',
    'https://apiex.bj/guide-du-createur',
    'Numero IFU (Identifiant Fiscal Unique)',
  ),
  CV:   office(
    'Casa do Cidadao - Empresa no Dia (Cabo Verde)',
    '+238 260 38 30',
    'Achada Santo Antonio, Praia, Cabo Verde',
    'https://casadocidadao.cv',
    'contacto@casadocidadao.cv',
    '',
    '',
    '',
    'https://casadocidadao.cv/index.php/empresa-no-dia',
    'https://casadocidadao.cv/index.php/empresa-no-dia/requisitos',
    'Numero de Matricula Comercial (NMC)',
  ),
  GM:   office(
    'Ministry of Justice The Gambia - Registrar of Companies',
    '+220 422 5308',
    'Marina Parade, Banjul, The Gambia',
    'https://www.moj.gov.gm',
    'info@moj.gov.gm',
    '',
    '',
    '',
    'https://www.moj.gov.gm/registrar-general',
    '',
    'Company Registration Number',
  ),
  GH:   office(
    'Registrar-General\'s Department (RGD Ghana)',
    '+233 30 266 1081',
    'Ministries, Accra, Ghana',
    'https://rgd.gov.gh',
    'info@rgd.gov.gh',
    'https://x.com/ORC_ghana',
    '',
    'https://www.linkedin.com/company/office-of-the-registrar-of-companies-ghana/',
    'https://egovonline.gegov.gov.gh/RGDPortalWeb/portal/RGDHome',
    'https://rgd.gov.gh/services/business-registration/',
    'Company Registration Number',
  ),
  GN:   office(
    'Agence de Promotion des Investissements Prives (APIP Guinea) - Guichet Unique',
    '+224 622 98 25 00',
    'Coleah, Commune de Matam, Conakry, Guinea',
    'https://apip.gov.gn',
    'contact@apip.gov.gn',
    '',
    '',
    'https://www.linkedin.com/company/apip-guinee/',
    'https://apip.gov.gn/creation-dentreprise',
    'https://apip.gov.gn/guide-du-createur',
    'Numero RCCM',
  ),
  GW:   office(
    'Centro de Formalizacao de Empresas (CFE Guinea-Bissau)',
    '+245 955 800 800',
    'Avenida Amilcar Cabral, Bissau, Guinea-Bissau',
    'https://www.cfe.gw',
    'info@cfe.gw',
    '',
    '',
    '',
    'https://www.cfe.gw/empresa-no-dia',
    'https://www.cfe.gw/requisitos',
    'Numero de Matricula Comercial',
  ),
  CI:   office(
    'CEPICI - Guichet Unique de Creation d\'Entreprise',
    '+225 27 20 31 14 00',
    'Abidjan Plateau, Avenue Marchand, Cote d\'Ivoire',
    'https://www.cepici.ci',
    'infos@cepici.ci',
    'https://x.com/cepici',
    'https://www.instagram.com/cepici.ci/',
    'https://www.linkedin.com/company/cepici/',
    'https://www.225invest.ci/creation-entreprise',
    'https://www.cepici.ci/guide-du-createur',
    'Numero RCCM',
  ),
  LR:   office(
    'Liberia Business Registry (LBR)',
    '+231 77 700 2000',
    'One Stop Shop, 12th Street Sinkor, Monrovia, Liberia',
    'https://lbr.gov.lr',
    'info@lbr.gov.lr',
    'https://x.com/LBRLiberia',
    '',
    'https://www.linkedin.com/company/liberia-business-registry/',
    'https://lbr.gov.lr/register-business',
    'https://lbr.gov.lr/requirements',
    'Business Registration Number (BRN)',
  ),
  NG:   office(
    'Corporate Affairs Commission (CAC Nigeria)',
    '+234 700 022 2255',
    'Plot 420, Tigris Crescent, Maitama, Abuja, Nigeria',
    'https://www.cac.gov.ng',
    'enquiries@cac.gov.ng',
    'https://x.com/cacnigeria1',
    'https://www.instagram.com/cacnigeria/',
    'https://www.linkedin.com/company/corporate-affairs-commission-nigeria/',
    'https://pre.cac.gov.ng/register',
    'https://www.cac.gov.ng/resources',
    'Registration Number (RC Number)',
  ),
  SN:   office(
    'Bureau d\'Appui a la Creation d\'Entreprise (BCE SENEGAL)',
    '+221 33 839 88 76',
    'Rue Vincens x Rue Saint-Michel, Dakar, Senegal',
    'https://creationdentreprise.sn',
    'contact@creationdentreprise.sn',
    '',
    '',
    '',
    'https://creationdentreprise.sn/formalites',
    'https://creationdentreprise.sn/guide',
    'Numero NINEA / RCCM',
  ),
  SL:   office(
    'Office of the Administrator and Registrar General (OARG Sierra Leone)',
    '+232 79 990 739',
    'Roxy Building, Walpole Street, Freetown, Sierra Leone',
    'https://oarg.gov.sl',
    'info@oarg.gov.sl',
    'https://x.com/OargSierraLeone',
    '',
    'https://www.linkedin.com/company/oarg-sl/',
    'https://oarg.gov.sl/business-registration',
    'https://oarg.gov.sl/requirements',
    'Company Registration Number',
  ),
  TG:   office(
    'Centre de Formalites des Entreprises (CFE Togo)',
    '+228 22 53 47 47',
    'Chaine du Port, Lome, Togo',
    'https://cfe.tg',
    'info@cfe.tg',
    '',
    '',
    'https://www.linkedin.com/company/cfetogo/',
    'https://cfe.tg/creation-dentreprise',
    'https://cfe.tg/pieces-a-fournir',
    'Numero RCCM',
  ),
}
