import type { EcowasMemberIsoCode } from './ecowasMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per ECOWAS member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const ECOWAS_DOMESTIC_POST_SERVICES: Record<EcowasMemberIsoCode, DomesticPostService> = {
  BJ: post(
    'La Poste du Bénin',
    'https://www.poste.bj/',
    'contact@poste.bj',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-benin/',
    '',
    'none',
    '',
    '',
    'No national postcode; arrondissement and P.O. Box',
  ),
  CV: post(
    'Correios de Cabo Verde',
    'https://correios.cv/',
    'cac@cvcorreios.cv',
    'https://x.com/correioscv',
    'https://www.instagram.com/correioscv/',
    'https://www.linkedin.com/company/correios-de-cabo-verde/',
    '',
    'NNNN-NNNN',
    '^\\\\d{4}-\\\\d{4}$',
    '7600-001',
    'Four-digit island prefix + four-digit delivery zone',
  ),
  GM: post(
    'GamPost',
    'https://gampost.gm/',
    'info@gampost.gm',
    '',
    '',
    'https://www.linkedin.com/company/gampost/',
    '',
    'none',
    '',
    '',
    'No national postcode; settlement and P.O. Box',
  ),
  GH: post(
    'Ghana Post',
    'http://ghanapost.com.gh/',
    'info@ghanapost.com.gh',
    'https://x.com/ghanapostgh',
    'https://www.instagram.com/ghanapostgh/',
    'https://www.linkedin.com/company/ghana-post/',
    '',
    'none',
    '',
    '',
    'GhanaPostGPS digital address parallel to legacy P.O. Box; no legacy numeric postcode',
  ),
  GN: post(
    'La Poste Guinée',
    'https://www.gui.post/',
    'direction@gui.post',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-guinee/',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  GW: post(
    'Correios da Guiné-Bissau',
    'https://www.correios.gw/',
    'geral@cgb.gw',
    '',
    '',
    '',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Bissau and regional)',
  ),
  CI: post(
    'La Poste de Côte d\'Ivoire',
    'https://www.la-poste.ci/',
    'info@laposte.ci',
    'https://x.com/LaPosteCI',
    'https://www.instagram.com/laposteci/',
    'https://www.linkedin.com/company/la-poste-de-cote-divoire/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune and P.O. Box dominant',
  ),
  LR: post(
    'LIBPOST',
    'https://libpost.com.lr/',
    'info@libpost.com.lr',
    '',
    '',
    'https://www.linkedin.com/company/libpost/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Monrovia and counties)',
  ),
  NG: post(
    'Nigeria Postal Service (NIPOST)',
    'http://nipost.gov.ng/',
    'info@nipost.gov.ng',
    'https://x.com/e_nipost',
    'https://www.instagram.com/e_nipost/',
    'https://www.linkedin.com/company/nipost/',
    '',
    'NNNNNN',
    '^\\\\d{6}$',
    '100001',
    'Six-digit postcode (state + LGA + delivery)',
  ),
  SN: post(
    'La Poste Sénégal',
    'https://www.laposte.sn/',
    'dircom@laposte.sn',
    'https://x.com/LaPosteSenegal',
    'https://www.instagram.com/lapostesenegal/',
    'https://www.linkedin.com/company/la-poste-senegal/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '12500',
    'Five-digit postcode',
  ),
  SL: post(
    'Salone Post EMS',
    'https://www.slpost.gov.sl/',
    'info@slipa.gov.sl',
    '',
    '',
    'https://www.linkedin.com/company/sierra-leone-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; Freetown district addressing',
  ),
  TG: post(
    'La Poste du Togo',
    'https://www.laposte.tg/',
    'contact@laposte.tg',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-togo/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune addressing',
  ),
}
