import type { EcowasMemberIsoCode } from './ecowasMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const ECOWAS_MAIN_INTERNATIONAL_AIRPORTS: Record<EcowasMemberIsoCode, MainInternationalAirport> = {
  BJ: {
    name: 'Cadjehoun International Airport (COO)',
    website: 'https://www.aeroport-cotonou.bj/',
    email: 'contact@aeroport-cotonou.bj',
    twitter: 'https://x.com/AeroportCotonou',
    instagram: 'https://www.instagram.com/aeroportcotonou/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-cadjehoun/',
    apiEndpoint: '',
  },
  CV: {
    name: 'Nelson Mandela International Airport (SID)',
    website: 'https://www.aeroporto-amilcar-cabral.cv/',
    email: 'info@aeroporto-amilcar-cabral.cv',
    twitter: 'https://x.com/AeroportoSID',
    instagram: 'https://www.instagram.com/aeroporto_sid/',
    linkedin: 'https://www.linkedin.com/company/aeroporto-internacional-nelson-mandela/',
    apiEndpoint: '',
  },
  GM: {
    name: 'Banjul International Airport (BJL)',
    website: 'https://www.gcaa.gm/',
    email: 'info@gcaa.gm',
    twitter: 'https://x.com/GCAA_Gambia',
    instagram: 'https://www.instagram.com/gcaa_gambia/',
    linkedin: 'https://www.linkedin.com/company/gambia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GH: {
    name: 'Kotoka International Airport (ACC)',
    website: 'https://www.gcaa.com.gh/',
    email: 'info@gcaa.com.gh',
    twitter: 'https://x.com/GCAA_Ghana',
    instagram: 'https://www.instagram.com/gcaa_ghana/',
    linkedin: 'https://www.linkedin.com/company/ghana-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GN: {
    name: 'Ahmed Sékou Touré International Airport (CKY)',
    website: 'https://www.aeroport-conakry.gn/',
    email: 'contact@aeroport-conakry.gn',
    twitter: 'https://x.com/AeroportCKY',
    instagram: 'https://www.instagram.com/aeroportconakry/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-conakry/',
    apiEndpoint: '',
  },
  GW: {
    name: 'Osvaldo Vieira International Airport (OXB)',
    website: 'https://www.aeroporto-bissau.gw/',
    email: 'contact@aeroporto-bissau.gw',
    twitter: 'https://x.com/AeroportoOXB',
    instagram: 'https://www.instagram.com/aeroportobissau/',
    linkedin: 'https://www.linkedin.com/company/aeroporto-osvaldo-vieira/',
    apiEndpoint: '',
  },
  CI: {
    name: 'Félix-Houphouët-Boigny International Airport (ABJ)',
    website: 'https://www.aeroport-abidjan.com/',
    email: 'contact@aeroport-abidjan.com',
    twitter: 'https://x.com/AeroportABJ',
    instagram: 'https://www.instagram.com/aeroportabidjan/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-felix-houphouet-boigny/',
    apiEndpoint: '',
  },
  LR: {
    name: 'Roberts International Airport (ROB)',
    website: 'https://www.lcaa.gov.lr/',
    email: 'info@lcaa.gov.lr',
    twitter: 'https://x.com/LCAA_Liberia',
    instagram: 'https://www.instagram.com/lcaa_liberia/',
    linkedin: 'https://www.linkedin.com/company/liberia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  NG: {
    name: 'Murtala Muhammed International Airport (LOS)',
    website: 'https://www.faan.gov.ng/',
    email: 'info@faan.gov.ng',
    twitter: 'https://x.com/FAAN_Official',
    instagram: 'https://www.instagram.com/faan_official/',
    linkedin: 'https://www.linkedin.com/company/federal-airports-authority-of-nigeria/',
    apiEndpoint: '',
  },
  SN: {
    name: 'Blaise Diagne International Airport (DSS)',
    website: 'https://www.aibd.sn/',
    email: 'contact@aibd.sn',
    twitter: 'https://x.com/AIBD_Airport',
    instagram: 'https://www.instagram.com/aibd_airport/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-blaise-diagne/',
    apiEndpoint: '',
  },
  SL: {
    name: 'Freetown Lungi International Airport (FNA)',
    website: 'https://www.slac.gov.sl/',
    email: 'info@slac.gov.sl',
    twitter: 'https://x.com/SLAC_SierraLeone',
    instagram: 'https://www.instagram.com/slac_sierraleone/',
    linkedin: 'https://www.linkedin.com/company/sierra-leone-airports-authority/',
    apiEndpoint: '',
  },
  TG: {
    name: 'Lomé-Tokoin International Airport (LFW)',
    website: 'https://www.aeroport-lome.tg/',
    email: 'contact@aeroport-lome.tg',
    twitter: 'https://x.com/AeroportLFW',
    instagram: 'https://www.instagram.com/aeroportlfw/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-lome/',
    apiEndpoint: '',
  },
}
