import type { EcowasMemberIsoCode } from './ecowasMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per ECOWAS member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const ECOWAS_MAIN_INTERNATIONAL_SEAPORTS: Record<EcowasMemberIsoCode, MainInternationalSeaport> = {
  BJ: seaport(
    'Port of Cotonou',
    'https://www.portdecotonou.com/',
    'contact@portdecotonou.com',
    'https://x.com/PortCotonou',
    'https://www.instagram.com/portcotonou/',
    'https://www.linkedin.com/company/port-autonome-de-cotonou/',
    'douanes@finances.bj',
    'https://www.douanes.bj',
    'Direction Générale des Douanes — Port de Cotonou, Cotonou, Benin',
  ),
  CV: seaport(
    'Port of Praia',
    'https://www.enapor.cv/',
    'info@enapor.cv',
    'https://x.com/ENAPOR_CV',
    'https://www.instagram.com/enapor_cv/',
    'https://www.linkedin.com/company/enapor/',
    'aduaneira@mf.gov.cv',
    'https://www.douanascv.gov.cv',
    'Serviço de Alfândegas — Porto da Praia, Praia, Cabo Verde',
  ),
  GM: seaport(
    'Port of Banjul',
    'https://www.gambiaports.gm/',
    'info@gambiaports.gm',
    'https://x.com/GambiaPorts',
    'https://www.instagram.com/gambiaports/',
    'https://www.linkedin.com/company/gambia-ports-authority/',
    'info@gra.gm',
    'https://www.gra.gm',
    'Gambia Revenue Authority — Customs, Port of Banjul, Banjul, The Gambia',
  ),
  GH: seaport(
    'Port of Tema',
    'https://www.ghanaports.gov.gh/',
    'info@ghanaports.gov.gh',
    'https://x.com/GhanaPorts',
    'https://www.instagram.com/ghanaports/',
    'https://www.linkedin.com/company/ghana-ports-and-harbours-authority/',
    'info@gra.gov.gh',
    'https://www.gra.gov.gh',
    'Ghana Revenue Authority — Customs Division, Port of Tema, Tema, Ghana',
  ),
  GN: seaport(
    'Port of Conakry',
    'https://www.otal.com/guinea/port-of-conakry',
    'contact@portconakry.gn',
    'https://x.com/PortConakry',
    'https://www.instagram.com/portconakry/',
    'https://www.linkedin.com/company/port-autonome-de-conakry/',
    'douanes@finances.gov.gn',
    'https://www.douanes.gov.gn',
    'Direction Générale des Douanes — Port de Conakry, Conakry, Guinea',
  ),
  GW: seaport(
    'Port of Bissau',
    'https://www.portobissau.gw/',
    'info@portobissau.gw',
    'https://x.com/PortBissau',
    'https://www.instagram.com/portbissau/',
    'https://www.linkedin.com/company/porto-de-bissau/',
    'aduaneira@mf.gov.gw',
    'https://www.aduaneira.gov.gw',
    'Alfândega Nacional — Porto de Bissau, Bissau, Guinea-Bissau',
  ),
  CI: seaport(
    'Port of Abidjan',
    'https://www.portabidjan.com/',
    'contact@portabidjan.com',
    'https://x.com/PortAbidjan',
    'https://www.instagram.com/portabidjan/',
    'https://www.linkedin.com/company/port-autonome-d-abidjan/',
    'douanes@dgi.gouv.ci',
    'https://www.douanes.ci',
    'Direction Générale des Douanes — Port d\'Abidjan, Abidjan, Côte d\'Ivoire',
  ),
  LR: seaport(
    'Freeport of Monrovia',
    'https://www.npaliberia.com/',
    'info@npaliberia.com',
    'https://x.com/NPA_Liberia',
    'https://www.instagram.com/npa_liberia/',
    'https://www.linkedin.com/company/national-port-authority-liberia/',
    'customs@lra.gov.lr',
    'https://www.lra.gov.lr',
    'Liberia Revenue Authority — Customs, Freeport of Monrovia, Monrovia, Liberia',
  ),
  NG: seaport(
    'Port of Lagos (Apapa)',
    'https://www.npa.gov.ng/',
    'info@npa.gov.ng',
    'https://x.com/NPA_Nigeria',
    'https://www.instagram.com/npa_nigeria/',
    'https://www.linkedin.com/company/nigerian-ports-authority/',
    'customs@customs.gov.ng',
    'https://www.customs.gov.ng',
    'Nigeria Customs Service — Apapa Port, Lagos, Nigeria',
  ),
  SN: seaport(
    'Port of Dakar',
    'https://www.portdedakar.sn/',
    'contact@portdedakar.sn',
    'https://x.com/PortDakar',
    'https://www.instagram.com/portdedakar/',
    'https://www.linkedin.com/company/port-autonome-de-dakar/',
    'douanes@finances.sn',
    'https://www.douanes.sn',
    'Direction Générale des Douanes — Port de Dakar, Dakar, Senegal',
  ),
  SL: seaport(
    'Port of Freetown',
    'https://www.slpa.sl/',
    'info@slpa.sl',
    'https://x.com/SLPA_Freetown',
    'https://www.instagram.com/slpa_freetown/',
    'https://www.linkedin.com/company/sierra-leone-ports-authority/',
    'customs@nra.gov.sl',
    'https://www.nra.gov.sl',
    'National Revenue Authority — Customs, Port of Freetown, Freetown, Sierra Leone',
  ),
  TG: seaport(
    'Port of Lomé',
    'https://www.portdelome.tg/',
    'contact@portdelome.tg',
    'https://x.com/PortLome',
    'https://www.instagram.com/portdelome/',
    'https://www.linkedin.com/company/port-autonome-de-lome/',
    'douanes@finances.tg',
    'https://www.douanes.tg',
    'Direction Générale des Douanes — Port de Lomé, Lomé, Togo',
  ),
}
