/**
 * Random List Via Media Press Kit Index - Curated list of cryptocurrencies from media press kit
 * 
 * This list contains cryptocurrencies organized from a media press kit source.
 * These currencies are commonly featured in press releases, media kits, and
 * marketing materials for cryptocurrency projects.
 * 
 * This index is used for media-related displays, press kit integrations, and
 * marketing-focused currency selection interfaces.
 * 
 * Last Updated: December 2025
 */

export type CurrencyType = 'coin' | 'token';
export type ConsensusType = 'proof-of-stake' | 'proof-of-work' | 'proof-of-authority' | 'delegated-proof-of-stake' | 'nominated-proof-of-stake' | 'liquid-proof-of-stake' | 'byzantine-fault-tolerance' | 'proof-of-transfer' | 'proof-of-coverage' | 'proof-of-space-and-time' | 'token' | 'hybrid' | 'optimistic-rollup' | 'zk-rollup';
export type CurrencyClass = 'layer-1' | 'layer-2' | 'defi' | 'dex' | 'nft' | 'gaming' | 'metaverse' | 'oracle' | 'privacy' | 'meme' | 'staking' | 'governance' | 'lending' | 'data' | 'infrastructure' | 'smart-contract-platform' | 'exchange-token' | 'ai' | 'storage' | 'payment' | 'social' | 'interoperability' | 'sports' | 'iot';

export interface RandomListViaMediaPressKitItem {
  id: string;
  symbol: string;
  name: string;
  description: string;
  ucid: number;
  type: CurrencyType;
  consensusType: ConsensusType;
  class: CurrencyClass[];
  website: string | null;
  github: string | null;
  npm: string | null;
}

export const RANDOM_LIST_VIA_MEDIA_PRESS_KIT: RandomListViaMediaPressKitItem[] = [
  { 
    id: 'aave', 
    symbol: 'AAVE', 
    name: 'AAVE',
    description: 'A decentralized lending protocol that allows users to lend and borrow cryptocurrencies without intermediaries.',
    ucid: 7278,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://aave.com',
    github: 'https://github.com/aave',
    npm: 'https://www.npmjs.com/package/@aave/protocol-js'
  },
  { 
    id: 'cardano', 
    symbol: 'ADA', 
    name: 'Cardano',
    description: 'A proof-of-stake blockchain platform focused on sustainability, scalability, and transparent governance for decentralized applications.',
    ucid: 2010,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://cardano.org',
    github: 'https://github.com/input-output-hk/cardano-node',
    npm: 'https://www.npmjs.com/package/cardano-serialization-lib'
  },
  { 
    id: 'aioz-network', 
    symbol: 'AIOZ', 
    name: 'AIOZ Network',
    description: 'A decentralized content delivery network powered by blockchain for streaming and storage.',
    ucid: 14658,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['infrastructure', 'storage', 'data'],
    website: 'https://aioz.network',
    github: 'https://github.com/AIOZNetwork',
    npm: null
  },
  { 
    id: 'akash-network', 
    symbol: 'AKT', 
    name: 'Akash',
    description: 'A decentralized cloud computing marketplace enabling users to buy and sell computing resources.',
    ucid: 7431,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['infrastructure', 'ai'],
    website: 'https://akash.network',
    github: 'https://github.com/akash-network',
    npm: null
  },
  { 
    id: 'algorand', 
    symbol: 'ALGO', 
    name: 'Algorand',
    description: 'A pure proof-of-stake blockchain platform designed for speed, security, and decentralization with instant finality.',
    ucid: 4030,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://algorand.com',
    github: 'https://github.com/algorand',
    npm: 'https://www.npmjs.com/package/algosdk'
  },
  { 
    id: 'aragon', 
    symbol: 'ANT', 
    name: 'Aragon',
    description: 'A platform for creating and managing decentralized autonomous organizations (DAOs).',
    ucid: 1680,
    type: 'token',
    consensusType: 'token',
    class: ['governance', 'infrastructure'],
    website: 'https://aragon.org',
    github: 'https://github.com/aragon',
    npm: 'https://www.npmjs.com/package/@aragon/sdk-client'
  },
  { 
    id: 'apecoin', 
    symbol: 'APE', 
    name: 'APECoin',
    description: 'A governance and utility token for the APE ecosystem, associated with Bored Ape Yacht Club.',
    ucid: 18876,
    type: 'token',
    consensusType: 'token',
    class: ['governance', 'nft', 'metaverse'],
    website: 'https://apecoin.com',
    github: 'https://github.com/ApeCoinFoundation',
    npm: null
  },
  { 
    id: 'arweave', 
    symbol: 'AR', 
    name: 'Arweave',
    description: 'A decentralized storage network offering permanent data storage with a one-time fee payment model.',
    ucid: 5632,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    website: 'https://arweave.org',
    github: 'https://github.com/ArweaveTeam',
    npm: 'https://www.npmjs.com/package/arweave'
  },
  { 
    id: 'cosmos', 
    symbol: 'ATOM', 
    name: 'Cosmos',
    description: 'An ecosystem of interconnected blockchains designed to solve scalability and interoperability issues.',
    ucid: 3794,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'interoperability'],
    website: 'https://cosmos.network',
    github: 'https://github.com/cosmos',
    npm: 'https://www.npmjs.com/package/@cosmjs/stargate'
  },
  { 
    id: 'audius', 
    symbol: 'AUDIO', 
    name: 'Audius',
    description: 'A decentralized music streaming protocol empowering artists and curators.',
    ucid: 7455,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'nft'],
    website: 'https://audius.co',
    github: 'https://github.com/AudiusProject',
    npm: 'https://www.npmjs.com/package/@audius/sdk'
  },
  { 
    id: 'avalanche-2', 
    symbol: 'AVAX', 
    name: 'Avalanche',
    description: 'A high-performance blockchain platform for decentralized applications and custom blockchain networks.',
    ucid: 5805,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://www.avax.network',
    github: 'https://github.com/ava-labs',
    npm: 'https://www.npmjs.com/package/avalanche'
  },
  { 
    id: 'axelar', 
    symbol: 'AXL', 
    name: 'Axelar',
    description: 'A cross-chain communication network connecting blockchains and enabling secure asset transfers.',
    ucid: 21846,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['interoperability', 'infrastructure'],
    website: 'https://axelar.network',
    github: 'https://github.com/axelarnetwork',
    npm: 'https://www.npmjs.com/package/@axelar-network/axelarjs-sdk'
  },
  { 
    id: 'balancer', 
    symbol: 'BAL', 
    name: 'Balancer',
    description: 'A decentralized automated market maker (AMM) protocol for programmable liquidity.',
    ucid: 5728,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://balancer.fi',
    github: 'https://github.com/balancer',
    npm: 'https://www.npmjs.com/package/@balancer-labs/sdk'
  },
  { 
    id: 'band-protocol', 
    symbol: 'BAND', 
    name: 'Band Protocol',
    description: 'A cross-chain data oracle platform aggregating and connecting real-world data to smart contracts.',
    ucid: 4679,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure'],
    website: 'https://bandprotocol.com',
    github: 'https://github.com/bandprotocol',
    npm: null
  },
  { 
    id: 'biconomy', 
    symbol: 'BICO', 
    name: 'Biconomy',
    description: 'A multichain relayer infrastructure network simplifying web3 user experiences.',
    ucid: 13396,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'layer-2'],
    website: 'https://biconomy.io',
    github: 'https://github.com/bcnmy',
    npm: 'https://www.npmjs.com/package/@biconomy/mexa'
  },
  { 
    id: 'pancakeswap-token', 
    symbol: 'CAKE', 
    name: 'Pancakeswap',
    description: 'The native governance token of PancakeSwap, a leading decentralized exchange on BNB Chain.',
    ucid: 7186,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://pancakeswap.finance',
    github: 'https://github.com/pancakeswap',
    npm: 'https://www.npmjs.com/package/@pancakeswap/sdk'
  },
  { 
    id: 'celo', 
    symbol: 'CELO', 
    name: 'Celo',
    description: 'A mobile-first blockchain platform focused on financial inclusion with stablecoin support.',
    ucid: 5567,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'payment', 'defi'],
    website: 'https://celo.org',
    github: 'https://github.com/celo-org',
    npm: 'https://www.npmjs.com/package/@celo/contractkit'
  },
  { 
    id: 'centrifuge', 
    symbol: 'CFG', 
    name: 'Centrifuge',
    description: 'A decentralized asset financing protocol connecting real-world assets to DeFi.',
    ucid: 6748,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'infrastructure'],
    website: 'https://centrifuge.io',
    github: 'https://github.com/centrifuge',
    npm: null
  },
  { 
    id: 'cream-2', 
    symbol: 'CREAM', 
    name: 'Cream Finance',
    description: 'A decentralized lending protocol offering diverse asset support across multiple blockchains.',
    ucid: 6193,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://cream.finance',
    github: 'https://github.com/CreamFi',
    npm: null
  },
  { 
    id: 'casper-network', 
    symbol: 'CSPR', 
    name: 'Casper',
    description: 'An enterprise-ready blockchain built for real-world applications with upgradeable smart contracts.',
    ucid: 7950,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://casper.network',
    github: 'https://github.com/casper-network',
    npm: 'https://www.npmjs.com/package/casper-js-sdk'
  },
  { id: 'cream-2', symbol: 'CREAM', name: 'Cream Finance' },
  { 
    id: 'dash', 
    symbol: 'DASH', 
    name: 'Dash',
    description: 'A privacy-focused cryptocurrency featuring instant transactions and a two-tier masternode network.',
    ucid: 131,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'payment', 'privacy'],
    website: 'https://www.dash.org',
    github: 'https://github.com/dashpay',
    npm: null
  },
  { 
    id: 'decred', 
    symbol: 'DCR', 
    name: 'Decred',
    description: 'A cryptocurrency with hybrid proof-of-work/proof-of-stake consensus and on-chain governance.',
    ucid: 1168,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'governance'],
    website: 'https://decred.org',
    github: 'https://github.com/decred',
    npm: null
  },
  { 
    id: 'polkadot', 
    symbol: 'DOT', 
    name: 'Polkadot',
    description: 'A multi-chain protocol enabling diverse blockchains to transfer messages and value in a trust-free fashion.',
    ucid: 6636,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['layer-1', 'interoperability'],
    website: 'https://polkadot.network',
    github: 'https://github.com/paritytech/polkadot',
    npm: 'https://www.npmjs.com/package/@polkadot/api'
  },
  { 
    id: 'enjincoin', 
    symbol: 'ENJ', 
    name: 'Enjin',
    description: 'A blockchain platform for creating, managing, and integrating NFTs across games and applications.',
    ucid: 2130,
    type: 'token',
    consensusType: 'token',
    class: ['nft', 'gaming'],
    website: 'https://enjin.io',
    github: 'https://github.com/enjin',
    npm: 'https://www.npmjs.com/package/@enjin/sdk'
  },
  { 
    id: 'eos', 
    symbol: 'EOS', 
    name: 'EOS',
    description: 'A blockchain platform for building decentralized applications with high transaction throughput.',
    ucid: 1765,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://eosnetwork.com',
    github: 'https://github.com/EOSIO',
    npm: 'https://www.npmjs.com/package/eosjs'
  },
  { 
    id: 'ethereum', 
    symbol: 'ETH', 
    name: 'Ethereum',
    description: 'A decentralized platform enabling smart contracts and distributed applications with its native currency Ether.',
    ucid: 1027,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ethereum.org',
    github: 'https://github.com/ethereum',
    npm: 'https://www.npmjs.com/package/ethers'
  },
  { 
    id: 'flare-networks', 
    symbol: 'FLR', 
    name: 'Flare',
    description: 'A blockchain platform bringing smart contracts to assets that don\'t naturally support them like XRP and Dogecoin.',
    ucid: 7950,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform', 'interoperability'],
    website: 'https://flare.network',
    github: 'https://github.com/flare-foundation',
    npm: null
  },
  { 
    id: 'flow', 
    symbol: 'FLOW', 
    name: 'Flow',
    description: 'A blockchain built for NFTs, gaming, and digital entertainment with fast and low-cost transactions.',
    ucid: 4558,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'nft', 'gaming'],
    website: 'https://flow.com',
    github: 'https://github.com/onflow',
    npm: 'https://www.npmjs.com/package/@onflow/fcl'
  },
  { 
    id: 'fantom', 
    symbol: 'FTM', 
    name: 'Fantom',
    description: 'A fast, scalable, and secure smart contract platform using directed acyclic graph (DAG) technology.',
    ucid: 3513,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://fantom.foundation',
    github: 'https://github.com/Fantom-Foundation',
    npm: null
  },
  { 
    id: 'golem', 
    symbol: 'GLM', 
    name: 'Golem',
    description: 'A decentralized marketplace for computing power, enabling users to rent out or purchase computational resources.',
    ucid: 1455,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'ai'],
    website: 'https://golem.network',
    github: 'https://github.com/golemfactory',
    npm: null
  },
  { 
    id: 'the-graph', 
    symbol: 'GRT', 
    name: 'Graph, The',
    description: 'A decentralized protocol for indexing and querying blockchain data, powering many DeFi and Web3 applications.',
    ucid: 6719,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure', 'data'],
    website: 'https://thegraph.com',
    github: 'https://github.com/graphprotocol',
    npm: 'https://www.npmjs.com/package/@graphprotocol/graph-cli'
  },
  { 
    id: 'hedera-hashgraph', 
    symbol: 'HBAR', 
    name: 'Hedera Hashgraph',
    description: 'A distributed ledger technology using hashgraph consensus for fast, fair, and secure transactions.',
    ucid: 4642,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://hedera.com',
    github: 'https://github.com/hashgraph',
    npm: 'https://www.npmjs.com/package/@hashgraph/sdk'
  },
  { 
    id: 'holo', 
    symbol: 'HOT', 
    name: 'Holochain',
    description: 'A framework for building distributed peer-to-peer applications without blockchain.',
    ucid: 2682,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure'],
    website: 'https://holochain.org',
    github: 'https://github.com/holochain',
    npm: null
  },
  { 
    id: 'internet-computer', 
    symbol: 'ICP', 
    name: 'Internet Computer',
    description: 'A blockchain network designed to extend the internet with decentralized computing capabilities.',
    ucid: 8916,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://internetcomputer.org',
    github: 'https://github.com/dfinity',
    npm: 'https://www.npmjs.com/package/@dfinity/agent'
  },
  { 
    id: 'illuvium', 
    symbol: 'ILV', 
    name: 'Illuvium',
    description: 'An open-world RPG game and auto-battler built on Ethereum with NFT creatures.',
    ucid: 8719,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'nft', 'metaverse'],
    website: 'https://illuvium.io',
    github: 'https://github.com/IlluviumGame',
    npm: null
  },
  { 
    id: 'injective-protocol', 
    symbol: 'INJ', 
    name: 'Injective',
    description: 'A decentralized exchange protocol enabling cross-chain derivatives trading with zero gas fees.',
    ucid: 7226,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'dex', 'layer-1'],
    website: 'https://injective.com',
    github: 'https://github.com/InjectiveLabs',
    npm: 'https://www.npmjs.com/package/@injectivelabs/sdk-ts'
  },
  { 
    id: 'iota', 
    symbol: 'IOTA', 
    name: 'Iota',
    description: 'A distributed ledger for IoT devices using a directed acyclic graph (Tangle) instead of blockchain.',
    ucid: 1720,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'iot', 'infrastructure'],
    website: 'https://www.iota.org',
    github: 'https://github.com/iotaledger',
    npm: 'https://www.npmjs.com/package/@iota/sdk'
  },
  { 
    id: 'jito-governance-token', 
    symbol: 'JTO', 
    name: 'Jito',
    description: 'A Solana liquid staking protocol and MEV infrastructure provider.',
    ucid: 28541,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking', 'infrastructure'],
    website: 'https://jito.network',
    github: 'https://github.com/jito-foundation',
    npm: null
  },
  { 
    id: 'kaspa', 
    symbol: 'KAS', 
    name: 'Kaspa',
    description: 'A proof-of-work cryptocurrency using blockDAG architecture for high transaction throughput.',
    ucid: 20396,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://kaspa.org',
    github: 'https://github.com/kaspanet',
    npm: null
  },
  { 
    id: 'kava', 
    symbol: 'KAVA', 
    name: 'Kava',
    description: 'A DeFi platform built on Cosmos enabling lending, staking, and stablecoins.',
    ucid: 4846,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['defi', 'lending', 'layer-1'],
    website: 'https://kava.io',
    github: 'https://github.com/Kava-Labs',
    npm: null
  },
  { id: 'jito-governance-token', symbol: 'JTO', name: 'Jito' },
  { id: 'kaspa', symbol: 'KAS', name: 'Kaspa' },
  { id: 'kava', symbol: 'KAVA', name: 'Kava' },
  { 
    id: 'kusama', 
    symbol: 'KSM', 
    name: 'Kusama',
    description: 'A scalable network of specialized blockchains built using Substrate, serving as Polkadot\'s canary network.',
    ucid: 5034,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['layer-1', 'interoperability'],
    website: 'https://kusama.network',
    github: 'https://github.com/paritytech/polkadot',
    npm: 'https://www.npmjs.com/package/@polkadot/api'
  },
  { 
    id: 'lido-dao', 
    symbol: 'LDO', 
    name: 'Lido DAO',
    description: 'A liquid staking protocol enabling users to stake ETH and other assets without locking funds.',
    ucid: 8000,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking', 'governance'],
    website: 'https://lido.fi',
    github: 'https://github.com/lidofinance',
    npm: 'https://www.npmjs.com/package/@lido-sdk/contracts'
  },
  { 
    id: 'chainlink', 
    symbol: 'LINK', 
    name: 'Chainlink',
    description: 'A decentralized oracle network connecting smart contracts with real-world data and external APIs.',
    ucid: 1975,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure'],
    website: 'https://chain.link',
    github: 'https://github.com/smartcontractkit',
    npm: 'https://www.npmjs.com/package/@chainlink/contracts'
  },
  { 
    id: 'livepeer', 
    symbol: 'LPT', 
    name: 'Livepeer',
    description: 'A decentralized video streaming network built on Ethereum.',
    ucid: 3640,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'social'],
    website: 'https://livepeer.org',
    github: 'https://github.com/livepeer',
    npm: 'https://www.npmjs.com/package/@livepeer/sdk'
  },
  { 
    id: 'lisk', 
    symbol: 'LSK', 
    name: 'Lisk',
    description: 'A blockchain platform enabling developers to build applications in JavaScript using sidechains.',
    ucid: 1214,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://lisk.com',
    github: 'https://github.com/LiskHQ',
    npm: 'https://www.npmjs.com/package/lisk-sdk'
  },
  { 
    id: 'terra-luna', 
    symbol: 'LUNA', 
    name: 'Terra',
    description: 'The native token of Terra 2.0 blockchain, rebuilt after the Terra Classic collapse.',
    ucid: 20314,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://terra.money',
    github: 'https://github.com/terra-money',
    npm: 'https://www.npmjs.com/package/@terra-money/terra.js'
  },
  { 
    id: 'decentraland', 
    symbol: 'MANA', 
    name: 'Decentraland',
    description: 'A virtual reality platform powered by Ethereum where users can create, experience, and monetize content and applications.',
    ucid: 1966,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'nft', 'gaming'],
    website: 'https://decentraland.org',
    github: 'https://github.com/decentraland',
    npm: 'https://www.npmjs.com/package/decentraland'
  },
  { 
    id: 'mask-network', 
    symbol: 'MASK', 
    name: 'Mask',
    description: 'A portal connecting the internet to Web3, enabling users to send crypto, interact with DApps on social media.',
    ucid: 8536,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'infrastructure'],
    website: 'https://mask.io',
    github: 'https://github.com/DimensionDev',
    npm: null
  },
  { 
    id: 'matic-network', 
    symbol: 'MATIC', 
    name: 'Polygon',
    description: 'A layer-2 scaling solution for Ethereum providing faster and cheaper transactions.',
    ucid: 3890,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['layer-2', 'infrastructure'],
    website: 'https://polygon.technology',
    github: 'https://github.com/maticnetwork',
    npm: 'https://www.npmjs.com/package/@maticnetwork/maticjs'
  },
  { 
    id: 'maker', 
    symbol: 'MKR', 
    name: 'Maker',
    description: 'The governance token of MakerDAO, managing the DAI stablecoin protocol.',
    ucid: 1518,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance', 'lending'],
    website: 'https://makerdao.com',
    github: 'https://github.com/makerdao',
    npm: null
  },
  { 
    id: 'mantle', 
    symbol: 'MNT', 
    name: 'Mantle',
    description: 'An Ethereum layer-2 scaling solution using optimistic rollups for high performance.',
    ucid: 27075,
    type: 'token',
    consensusType: 'optimistic-rollup',
    class: ['layer-2', 'infrastructure'],
    website: 'https://mantle.xyz',
    github: 'https://github.com/mantlenetworkio',
    npm: null
  },
  { 
    id: 'meson-network', 
    symbol: 'MSN', 
    name: 'Meson Network',
    description: 'A decentralized bandwidth marketplace for Web3 infrastructure.',
    ucid: 17552,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'storage'],
    website: 'https://meson.network',
    github: 'https://github.com/daqnext',
    npm: null
  },
  { 
    id: 'near', 
    symbol: 'NEAR', 
    name: 'Near',
    description: 'A sharded proof-of-stake blockchain designed for usability and scalability with simple onboarding.',
    ucid: 6535,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://near.org',
    github: 'https://github.com/near',
    npm: 'https://www.npmjs.com/package/near-api-js'
  },
  { 
    id: 'neo', 
    symbol: 'NEO', 
    name: 'NEO',
    description: 'A blockchain platform for building decentralized applications with digital assets and smart contracts.',
    ucid: 1376,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://neo.org',
    github: 'https://github.com/neo-project',
    npm: 'https://www.npmjs.com/package/@cityofzion/neon-js'
  },
  { 
    id: 'ocean-protocol', 
    symbol: 'OCEAN', 
    name: 'Ocean Protocol',
    description: 'A decentralized data exchange protocol enabling secure sharing and monetization of data.',
    ucid: 3911,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'ai', 'infrastructure'],
    website: 'https://oceanprotocol.com',
    github: 'https://github.com/oceanprotocol',
    npm: 'https://www.npmjs.com/package/@oceanprotocol/lib'
  },
  { 
    id: 'octopus-network', 
    symbol: 'OCT', 
    name: 'Octopus Network',
    description: 'A multichain interoperable crypto network providing shared security for application-specific blockchains.',
    ucid: 11857,
    type: 'token',
    consensusType: 'token',
    class: ['interoperability', 'infrastructure'],
    website: 'https://oct.network',
    github: 'https://github.com/octopus-network',
    npm: null
  },
  { 
    id: 'harmony', 
    symbol: 'ONE', 
    name: 'Harmony',
    description: 'A fast and secure blockchain using sharding for scalability.',
    ucid: 3945,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://harmony.one',
    github: 'https://github.com/harmony-one',
    npm: 'https://www.npmjs.com/package/@harmony-js/core'
  },
  { 
    id: 'ontology', 
    symbol: 'ONT', 
    name: 'Ontology',
    description: 'A high-performance blockchain focused on digital identity and data solutions.',
    ucid: 2566,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'infrastructure'],
    website: 'https://ont.io',
    github: 'https://github.com/ontio',
    npm: 'https://www.npmjs.com/package/ontology-ts-sdk'
  },
  { 
    id: 'optimism', 
    symbol: 'OP', 
    name: 'Optimism',
    description: 'An Ethereum layer-2 scaling solution using optimistic rollups to reduce costs and increase speed.',
    ucid: 11840,
    type: 'token',
    consensusType: 'optimistic-rollup',
    class: ['layer-2', 'infrastructure'],
    website: 'https://optimism.io',
    github: 'https://github.com/ethereum-optimism',
    npm: 'https://www.npmjs.com/package/@eth-optimism/sdk'
  },
  { 
    id: 'quant-network', 
    symbol: 'QNT', 
    name: 'Quant',
    description: 'A blockchain operating system enabling interoperability between different networks through Overledger technology.',
    ucid: 3155,
    type: 'token',
    consensusType: 'token',
    class: ['interoperability', 'infrastructure'],
    website: 'https://quant.network',
    github: null,
    npm: null
  },
  { 
    id: 'quantum-resistant-ledger', 
    symbol: 'QRL', 
    name: 'Quantum Resistance Ledger',
    description: 'A blockchain designed to be secure against quantum computing attacks using XMSS signatures.',
    ucid: 1430,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://theqrl.org',
    github: 'https://github.com/theQRL',
    npm: 'https://www.npmjs.com/package/@theqrl/wallet-helpers'
  },
  { 
    id: 'qtum', 
    symbol: 'QTUM', 
    name: 'Qtum',
    description: 'A blockchain platform combining Bitcoin\'s security with Ethereum\'s smart contract functionality.',
    ucid: 1684,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://qtum.org',
    github: 'https://github.com/qtumproject',
    npm: null
  },
  { 
    id: 'radworks', 
    symbol: 'RAD', 
    name: 'Radworks',
    description: 'A decentralized network for software collaboration and development funding.',
    ucid: 7916,
    type: 'token',
    consensusType: 'token',
    class: ['governance', 'infrastructure'],
    website: 'https://radworks.org',
    github: 'https://github.com/radicle-dev',
    npm: null
  },
  { 
    id: 'ribbon-finance', 
    symbol: 'RBN', 
    name: 'Ribbon Finance',
    description: 'A DeFi protocol offering structured products for earning yield through options strategies.',
    ucid: 9132,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    website: 'https://ribbon.finance',
    github: 'https://github.com/ribbon-finance',
    npm: null
  },
  { 
    id: 'reddcoin', 
    symbol: 'RDD', 
    name: 'Reddcoin',
    description: 'A social cryptocurrency for tipping and microtransactions on social media platforms.',
    ucid: 118,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['social', 'payment'],
    website: 'https://reddcoin.com',
    github: 'https://github.com/reddcoin-project',
    npm: null
  },
  { 
    id: 'request-network', 
    symbol: 'REQ', 
    name: 'Request',
    description: 'A decentralized payment request protocol enabling invoicing and accounting on blockchain.',
    ucid: 2071,
    type: 'token',
    consensusType: 'token',
    class: ['payment', 'defi'],
    website: 'https://request.network',
    github: 'https://github.com/RequestNetwork',
    npm: 'https://www.npmjs.com/package/@requestnetwork/request-client.js'
  },
  { 
    id: 'revain', 
    symbol: 'REV', 
    name: 'Revain',
    description: 'A blockchain-based review platform providing authentic user reviews.',
    ucid: 2135,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'data'],
    website: 'https://revain.org',
    github: null,
    npm: null
  },
  { 
    id: 'ronin', 
    symbol: 'RON', 
    name: 'Ronin',
    description: 'An Ethereum sidechain built for gaming, specifically designed for Axie Infinity.',
    ucid: 14101,
    type: 'coin',
    consensusType: 'proof-of-authority',
    class: ['layer-2', 'gaming', 'nft'],
    website: 'https://roninchain.com',
    github: 'https://github.com/axieinfinity',
    npm: null
  },
  { 
    id: 'oasis-network', 
    symbol: 'ROSE', 
    name: 'Oasis',
    description: 'A privacy-enabled blockchain platform designed for DeFi and scalable data tokenization.',
    ucid: 7653,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'privacy', 'defi'],
    website: 'https://oasisprotocol.org',
    github: 'https://github.com/oasisprotocol',
    npm: null
  },
  { 
    id: 'reserve-rights-token', 
    symbol: 'RSR', 
    name: 'Reserve Rights',
    description: 'A stablecoin platform aiming to create a universal store of value, especially in regions with unstable currencies.',
    ucid: 3964,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'payment'],
    website: 'https://reserve.org',
    github: 'https://github.com/reserve-protocol',
    npm: null
  },
  { 
    id: 'salt', 
    symbol: 'SALT', 
    name: 'Salt Lending',
    description: 'A blockchain-based lending platform allowing users to use crypto assets as collateral for loans.',
    ucid: 1996,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://saltlending.com',
    github: null,
    npm: null
  },
  { 
    id: 'the-sandbox', 
    symbol: 'SAND', 
    name: 'Sandbox, The',
    description: 'A virtual world and gaming metaverse where users can create, own, and monetize gaming experiences.',
    ucid: 6210,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'gaming', 'nft'],
    website: 'https://sandbox.game',
    github: 'https://github.com/thesandboxgame',
    npm: null
  },
  { 
    id: 'siacoin', 
    symbol: 'SC', 
    name: 'Siacoin',
    description: 'A decentralized cloud storage platform where users can rent out unused storage space.',
    ucid: 1042,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    website: 'https://sia.tech',
    github: 'https://github.com/SiaFoundation',
    npm: null
  },
  { 
    id: 'secret', 
    symbol: 'SCRT', 
    name: 'Secret',
    description: 'A privacy-focused blockchain enabling encrypted smart contracts with encrypted inputs, outputs, and state.',
    ucid: 5604,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'privacy', 'smart-contract-platform'],
    website: 'https://scrt.network',
    github: 'https://github.com/scrtlabs',
    npm: 'https://www.npmjs.com/package/secretjs'
  },
  { 
    id: 'sei-network', 
    symbol: 'SEI', 
    name: 'Sei',
    description: 'A layer-1 blockchain optimized for trading and DeFi applications with high throughput.',
    ucid: 23149,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'defi', 'dex'],
    website: 'https://sei.io',
    github: 'https://github.com/sei-protocol',
    npm: null
  },
  { 
    id: 'solana', 
    symbol: 'SOL', 
    name: 'Solana',
    description: 'A high-performance blockchain supporting fast transactions and low fees through proof-of-history.',
    ucid: 5426,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://solana.com',
    github: 'https://github.com/solana-labs',
    npm: 'https://www.npmjs.com/package/@solana/web3.js'
  },
  { 
    id: 'starknet', 
    symbol: 'STRK', 
    name: 'Starknet',
    description: 'An Ethereum layer-2 scaling solution using zk-STARKs for validity proofs.',
    ucid: 22691,
    type: 'token',
    consensusType: 'zk-rollup',
    class: ['layer-2', 'infrastructure'],
    website: 'https://starknet.io',
    github: 'https://github.com/starkware-libs',
    npm: 'https://www.npmjs.com/package/starknet'
  },
  { 
    id: 'sui', 
    symbol: 'SUI', 
    name: 'Sui',
    description: 'A layer-1 blockchain built with the Move programming language for fast, scalable applications.',
    ucid: 20947,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://sui.io',
    github: 'https://github.com/MystenLabs',
    npm: 'https://www.npmjs.com/package/@mysten/sui.js'
  },
  { 
    id: 'the-open-network', 
    symbol: 'TON', 
    name: 'TON',
    description: 'A decentralized layer-1 blockchain originally developed by Telegram, designed for mass adoption.',
    ucid: 11419,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'payment'],
    website: 'https://ton.org',
    github: 'https://github.com/ton-blockchain',
    npm: 'https://www.npmjs.com/package/ton'
  },
  { 
    id: 'trust-wallet-token', 
    symbol: 'TWT', 
    name: 'Trust Token',
    description: 'The utility token of Trust Wallet, providing benefits within the wallet ecosystem.',
    ucid: 5964,
    type: 'token',
    consensusType: 'token',
    class: ['exchange-token', 'governance'],
    website: 'https://trustwallet.com',
    github: 'https://github.com/trustwallet',
    npm: null
  },
  { id: 'the-open-network', symbol: 'TON', name: 'TON' },
  { id: 'trust-wallet-token', symbol: 'TWT', name: 'Trust Token' },
  { 
    id: 'usd-coin', 
    symbol: 'USDC', 
    name: 'USDC',
    description: 'A fully reserved stablecoin pegged 1:1 to the US dollar, issued by Circle.',
    ucid: 3408,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'payment'],
    website: 'https://circle.com/usdc',
    github: 'https://github.com/centrehq',
    npm: null
  },
  { 
    id: 'vechain', 
    symbol: 'VET', 
    name: 'VeChain',
    description: 'An enterprise-grade blockchain platform focused on supply chain management and business processes.',
    ucid: 3077,
    type: 'coin',
    consensusType: 'proof-of-authority',
    class: ['layer-1', 'infrastructure'],
    website: 'https://vechain.org',
    github: 'https://github.com/vechain',
    npm: 'https://www.npmjs.com/package/@vechain/connex'
  },
  { 
    id: 'velas', 
    symbol: 'VLX', 
    name: 'Velas',
    description: 'A high-performance blockchain using AI-powered AIDPOS consensus for scalability.',
    ucid: 4747,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'ai'],
    website: 'https://velas.com',
    github: 'https://github.com/velas',
    npm: null
  },
  { 
    id: 'wormhole', 
    symbol: 'W', 
    name: 'Wormhole',
    description: 'A cross-chain messaging protocol enabling token and NFT transfers across multiple blockchains.',
    ucid: 28285,
    type: 'token',
    consensusType: 'token',
    class: ['interoperability', 'infrastructure'],
    website: 'https://wormhole.com',
    github: 'https://github.com/wormhole-foundation',
    npm: 'https://www.npmjs.com/package/@certusone/wormhole-sdk'
  },
  { 
    id: 'wing-finance', 
    symbol: 'WING', 
    name: 'Wing Finance',
    description: 'A DeFi lending platform based on credit evaluation for diverse digital assets.',
    ucid: 7048,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://wing.finance',
    github: 'https://github.com/wing-finance',
    npm: null
  },
  { 
    id: 'woo-network', 
    symbol: 'WOO', 
    name: 'Woo',
    description: 'A deep liquidity network connecting traders, DeFi platforms, and institutions.',
    ucid: 7501,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex'],
    website: 'https://woo.org',
    github: 'https://github.com/woonetwork',
    npm: null
  },
  { 
    id: 'chia', 
    symbol: 'XCH', 
    name: 'Chia',
    description: 'A blockchain using proof-of-space-and-time consensus, leveraging hard drive storage for farming.',
    ucid: 9258,
    type: 'coin',
    consensusType: 'proof-of-space-and-time',
    class: ['layer-1', 'storage'],
    website: 'https://chia.net',
    github: 'https://github.com/Chia-Network',
    npm: null
  },
  { 
    id: 'xdce-crowd-sale', 
    symbol: 'XDC', 
    name: 'XDC Network',
    description: 'An enterprise-ready hybrid blockchain for global trade and finance with instant block finality.',
    ucid: 2634,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://xdc.org',
    github: 'https://github.com/XinFinOrg',
    npm: 'https://www.npmjs.com/package/xdc3'
  },
  { 
    id: 'ecash', 
    symbol: 'XEC', 
    name: 'eCash',
    description: 'A cryptocurrency derived from Bitcoin Cash focusing on usability as electronic cash.',
    ucid: 10791,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://e.cash',
    github: 'https://github.com/Bitcoin-ABC',
    npm: null
  },
  { 
    id: 'stellar', 
    symbol: 'XLM', 
    name: 'Stellar',
    description: 'An open network for storing and moving money, designed for fast, low-cost cross-border payments.',
    ucid: 512,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    website: 'https://stellar.org',
    github: 'https://github.com/stellar',
    npm: 'https://www.npmjs.com/package/@stellar/stellar-sdk'
  },
  { 
    id: 'monero', 
    symbol: 'XMR', 
    name: 'Monero',
    description: 'A privacy-focused cryptocurrency using ring signatures, stealth addresses, and confidential transactions.',
    ucid: 328,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://getmonero.org',
    github: 'https://github.com/monero-project',
    npm: null
  },
  { 
    id: 'ripple', 
    symbol: 'XRP', 
    name: 'XRP',
    description: 'A digital payment protocol and cryptocurrency designed for fast, low-cost international money transfers.',
    ucid: 52,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    website: 'https://ripple.com',
    github: 'https://github.com/ripple',
    npm: 'https://www.npmjs.com/package/xrpl'
  },
  { 
    id: 'radix', 
    symbol: 'XRD', 
    name: 'Radix',
    description: 'A layer-1 blockchain platform designed specifically for DeFi with linear scalability.',
    ucid: 11948,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'defi', 'smart-contract-platform'],
    website: 'https://radixdlt.com',
    github: 'https://github.com/radixdlt',
    npm: null
  },
  { 
    id: 'tezos', 
    symbol: 'XTZ', 
    name: 'Tezos',
    description: 'A self-amending blockchain with on-chain governance and formal verification for smart contracts.',
    ucid: 2011,
    type: 'coin',
    consensusType: 'liquid-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://tezos.com',
    github: 'https://github.com/tezos',
    npm: 'https://www.npmjs.com/package/@taquito/taquito'
  },
  { 
    id: 'verge', 
    symbol: 'XVG', 
    name: 'Verge',
    description: 'A privacy-focused cryptocurrency using multiple anonymity-centric networks.',
    ucid: 693,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://vergecurrency.com',
    github: 'https://github.com/vergecurrency',
    npm: null
  },
  { 
    id: 'xyo-network', 
    symbol: 'XYO', 
    name: 'XYO',
    description: 'A decentralized network for location data verification using blockchain.',
    ucid: 2765,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'oracle', 'iot'],
    website: 'https://xyo.network',
    github: 'https://github.com/XYOracleNetwork',
    npm: 'https://www.npmjs.com/package/@xyo-network/sdk-xyo-js'
  },
  { 
    id: 'yearn-finance', 
    symbol: 'YFI', 
    name: 'Yearn Finance',
    description: 'A DeFi yield aggregator that automatically moves funds to maximize returns across protocols.',
    ucid: 5864,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance', 'lending'],
    website: 'https://yearn.finance',
    github: 'https://github.com/yearn',
    npm: null
  },
  { 
    id: 'zcash', 
    symbol: 'ZEC', 
    name: 'ZCash',
    description: 'A privacy-focused cryptocurrency using zero-knowledge proofs (zk-SNARKs) for shielded transactions.',
    ucid: 1437,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://z.cash',
    github: 'https://github.com/zcash',
    npm: null
  },
  { 
    id: 'zencash', 
    symbol: 'ZEN', 
    name: 'Horizen',
    description: 'A privacy-focused blockchain platform with sidechain capabilities and a large node network.',
    ucid: 1698,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'infrastructure'],
    website: 'https://horizen.io',
    github: 'https://github.com/HorizenOfficial',
    npm: null
  },
  { 
    id: 'zilliqa', 
    symbol: 'ZIL', 
    name: 'Zilliqa',
    description: 'A high-throughput blockchain using sharding technology for scalability.',
    ucid: 2469,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://zilliqa.com',
    github: 'https://github.com/Zilliqa',
    npm: 'https://www.npmjs.com/package/@zilliqa-js/zilliqa'
  }
];

export default RANDOM_LIST_VIA_MEDIA_PRESS_KIT;

