import type { AseanMemberIsoCode } from './aseanMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per ASEAN member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const ASEAN_DOMESTIC_POST_SERVICES: Record<AseanMemberIsoCode, DomesticPostService> = {
  BN: post(
    'Postal Services Department (Brunei)',
    'https://www.post.gov.bn/',
    'postmaster@post.gov.bn',
    '',
    '',
    'https://www.linkedin.com/company/postal-services-department-brunei/',
    '',
    'AANNNN',
    '^[A-Z]{2}\\d{4}$',
    'BA2110',
    'Two-letter area + four digits (Brunei Darussalam)',
  ),
  KH: post(
    'Cambodia Post',
    'https://www.cambodiapost.com.kh/',
    'info@cambodiapost.com.kh',
    '',
    '',
    'https://www.linkedin.com/company/cambodia-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '12000',
    'Five-digit postcode',
  ),
  ID: post(
    'Pos Indonesia',
    'https://www.posindonesia.co.id/',
    'pusatbantuan@posindonesia.co.id',
    'https://x.com/PosIndonesia',
    'https://www.instagram.com/posindonesia/',
    'https://www.linkedin.com/company/pos-indonesia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10110',
    'Five-digit postcode',
  ),
  LA: post(
    'Lao Post',
    'https://www.laopost.com.la/',
    'info@laopost.la',
    '',
    '',
    'https://www.linkedin.com/company/lao-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '01000',
    'Five-digit postcode',
  ),
  MY: post(
    'Pos Malaysia',
    'https://www.pos.com.my/',
    'customercare@pos.com.my',
    'https://x.com/posmalaysia',
    'https://www.instagram.com/posmalaysia/',
    'https://www.linkedin.com/company/pos-malaysia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '50000',
    'Five-digit postcode',
  ),
  MM: post(
    'Myanmar Post',
    'https://www.myanmarpost.com.mm/',
    'info@myanmarpost.com.mm',
    '',
    '',
    'https://www.linkedin.com/company/myanmar-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11181',
    'Five-digit postcode (Yangon)',
  ),
  PH: post(
    'Philippine Postal Corporation (PHLPost)',
    'https://www.phlpost.gov.ph/',
    'info@phlpost.gov.ph',
    'https://x.com/PHLPost',
    'https://www.instagram.com/phlpost/',
    'https://www.linkedin.com/company/philippine-postal-corporation/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  SG: post(
    'Singapore Post',
    'https://www.singpost.com/',
    'feedback@singpost.com',
    'https://x.com/SingPost',
    'https://www.instagram.com/singpost/',
    'https://www.linkedin.com/company/singapore-post-limited/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '018956',
    'Six-digit postcode',
  ),
  TH: post(
    'Thailand Post',
    'https://www.thailandpost.co.th/',
    'contact@thailandpost.co.th',
    'https://x.com/ThailandPost',
    'https://www.instagram.com/thailandpost/',
    'https://www.linkedin.com/company/thailand-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10100',
    'Five-digit postcode',
  ),
  TL: post(
    'Correios de Timor-Leste',
    'https://www.correios.tl/',
    'info@correios.tl',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system; district addressing',
  ),
  VN: post(
    'Vietnam Post (VNPost)',
    'https://www.vnpost.vn/',
    'contact@vnpost.vn',
    'https://x.com/VNPost',
    'https://www.instagram.com/vnpost/',
    'https://www.linkedin.com/company/vietnam-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
}
