import type { DomesticCourierService } from './types'
import type { AseanMemberIsoCode } from './aseanMemberIsoCodes'

function c(
  name: string,
  website: string,
  email: string,
  instagram: string,
  twitter: string,
  apiEndpoint: string,
): DomesticCourierService {
  return { name, website, email, instagram, twitter, apiEndpoint }
}

/**
 * Domestic courier reference rows by ISO 3166-1 alpha-2 for ASEAN members.
 * Verify URLs, emails, social handles, and `apiEndpoint` bases locally before production use.
 */
export const ASEAN_DOMESTIC_COURIERS = {
  BN: [
    c(
      'Postal Services Department (Brunei)',
      'https://postal.gov.bn/',
      'info.postal@mpt.gov.bn',
      '',
      '',
      '',
    ),
    c(
      'DHL Express Brunei Darussalam',
      'https://www.dhl.com/bn-en/home.html',
      'customerservicebn@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Brunei',
      'https://www.fedex.com/en-bn/',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'Aramex Brunei',
      'https://www.aramex.com/',
      'customerservicebn@aramex.com',
      'https://www.instagram.com/aramex/',
      'https://x.com/aramex',
      'https://ws.aramex.net/',
    ),
  ],
  KH: [
    c(
      'Cambodia Post (national postal operator)',
      'https://www.post.com.kh/',
      'info@post.com.kh',
      '',
      '',
      '',
    ),
    c(
      'DHL Express Cambodia',
      'https://www.dhl.com/kh-en/home.html',
      'kh.customerservice@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Cambodia',
      'https://www.fedex.com/en-kh',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'UPS Cambodia',
      'https://www.ups.com/kh/en',
      'help@ups.com',
      'https://www.instagram.com/ups/',
      'https://x.com/UPS',
      'https://onlinetools.ups.com/api/',
    ),
  ],
  ID: [
    c(
      'PT Pos Indonesia (Pos Indonesia)',
      'https://www.posindonesia.co.id/',
      'pps@mail.posindonesia.co.id',
      'https://www.instagram.com/posindonesia.id/',
      'https://x.com/Posindonesia',
      '',
    ),
    c(
      'JNE Express',
      'https://www.jne.co.id/',
      'customercare@jne.co.id',
      'https://www.instagram.com/jne_id/',
      'https://x.com/jne_id',
      '',
    ),
    c(
      'J&T Express Indonesia',
      'https://jtexpress.id/',
      'care@jit.id',
      'https://www.instagram.com/idjnt/',
      '',
      '',
    ),
    c(
      'SiCepat Ekspres',
      'https://www.sicepat.com/',
      'care@sicepat.com',
      'https://www.instagram.com/sicepatekspres/',
      'https://x.com/sicepatekspress',
      '',
    ),
  ],
  LA: [
    c(
      'Enterprise of Posts Lao (Lao Post)',
      'http://www.laopost.com.la/',
      'info@laopost.com.la',
      '',
      '',
      '',
    ),
    c(
      'DHL Express Laos',
      'https://www.dhl.com/la-en/home.html',
      'la.customerservice@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Laos',
      'https://www.fedex.com/',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'Aramex Laos corridor',
      'https://www.aramex.com/',
      'support@aramex.com',
      'https://www.instagram.com/aramex/',
      'https://x.com/aramex',
      'https://ws.aramex.net/',
    ),
  ],
  MY: [
    c(
      'Pos Malaysia (Pos Laju)',
      'https://www.posmalaysia.com.my/',
      'webmastercsu@pos.com.my',
      'https://www.instagram.com/posmalaysiaofficial/',
      'https://x.com/Pos4u',
      '',
    ),
    c(
      'GD Express (GDEX)',
      'https://www.gdexpress.com/',
      'customerservice@gdex.com.my',
      'https://www.instagram.com/gdexpressmalaysia/',
      'https://x.com/myGdex',
      '',
    ),
    c(
      'J&T Express Malaysia',
      'https://jtexpress.my/',
      'my.market@jet.co.id',
      'https://www.instagram.com/jntexpressmy/',
      '',
      '',
    ),
    c(
      'Ninja Van Malaysia',
      'https://www.ninjavan.co/en-my',
      'help.my@ninjavan.com',
      'https://www.instagram.com/ninjavanmalaysia/',
      '',
      'https://api.ninjavan.co/',
    ),
  ],
  MM: [
    c(
      'Myanmar Post (MPT postal service)',
      'https://www.mpt.gov.mm/',
      'customercare@mpt.gov.mm',
      '',
      '',
      '',
    ),
    c(
      'DHL Express Myanmar',
      'https://www.dhl.com/mm-en/home.html',
      'mm.customerservice@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Myanmar',
      'https://www.fedex.com/',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'UPS Myanmar',
      'https://www.ups.com/',
      'help@ups.com',
      'https://www.instagram.com/ups/',
      'https://x.com/UPS',
      'https://onlinetools.ups.com/api/',
    ),
  ],
  PH: [
    c(
      'LBC Express',
      'https://www.lbcexpress.com/',
      'customercare@lbcexpress.com',
      'https://www.instagram.com/lbcexpress/',
      'https://x.com/LBCexpress',
      '',
    ),
    c(
      'JRS Express',
      'https://www.jrs-express.com/',
      'help@jrs-express.com',
      'https://www.instagram.com/jrsexpress/',
      'https://x.com/jrsexpress',
      '',
    ),
    c(
      'J&T Express Philippines',
      'https://www.jtexpress.ph/',
      'customer@jtexpress.ph',
      'https://www.instagram.com/jntexpressph/',
      '',
      '',
    ),
    c(
      '2GO Express',
      'https://supplychain.2go.com.ph/',
      'customercare@2go.com.ph',
      'https://www.instagram.com/2goexpressofficial/',
      'https://x.com/2GOExpress',
      '',
    ),
  ],
  SG: [
    c(
      'SingPost (Speedpost)',
      'https://www.singpost.com/',
      'askspp@singpost.com',
      'https://www.instagram.com/singpost/',
      'https://x.com/SingPost',
      '',
    ),
    c(
      'Ninja Van Singapore',
      'https://www.ninjavan.co/en-sg',
      'help.sg@ninjavan.com',
      'https://www.instagram.com/ninjavansg/',
      'https://x.com/ninjavan',
      'https://api.ninjavan.co/',
    ),
    c(
      'J&T Express Singapore',
      'https://www.jtexpress.sg/',
      'sg.customerservice@jet.co.id',
      'https://www.instagram.com/jntexpresssg/',
      '',
      '',
    ),
    c(
      'Qxpress',
      'https://www.qxpress.net/',
      'help@qxpress.net',
      'https://www.instagram.com/qxpress/',
      '',
      '',
    ),
  ],
  TH: [
    c(
      'Thailand Post EMS',
      'https://www.thailandpost.com/',
      '1232@thailandpost.com',
      'https://www.instagram.com/thailandpost.official/',
      'https://x.com/ThailandPostPLC',
      '',
    ),
    c(
      'Kerry Express Thailand',
      'https://th.kerryexpress.com/',
      'kes.support@kerrylogistics.com',
      'https://www.instagram.com/kerryexpress.th/',
      '',
      '',
    ),
    c(
      'Flash Express Thailand',
      'https://www.flashexpress.co.th/',
      'cs@flashexpress.com',
      'https://www.instagram.com/flashexpress.th/',
      'https://x.com/FlashExpressTH',
      '',
    ),
    c(
      'Ninja Van Thailand',
      'https://www.ninjavan.co/th-th',
      'help.th@ninjavan.com',
      'https://www.instagram.com/ninjavan_th/',
      'https://x.com/ninjavan',
      'https://api.ninjavan.co/',
    ),
  ],
  TL: [
    c(
      'Correios de Timor-Leste (CTTL)',
      'https://www.cttle.tl/',
      'info@cttle.tl',
      '',
      '',
      '',
    ),
    c(
      'DHL Express Timor-Leste',
      'https://www.dhl.com/tl-en/home.html',
      'tl.customerservice@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Timor-Leste',
      'https://www.fedex.com/',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'UPS Timor-Leste',
      'https://www.ups.com/',
      'help@ups.com',
      'https://www.instagram.com/ups/',
      'https://x.com/UPS',
      'https://onlinetools.ups.com/api/',
    ),
  ],
  VN: [
    c(
      'Vietnam Post (VNPost EMS)',
      'https://vnpost.vn/',
      'dichvu@vnpost.vn',
      'https://www.instagram.com/buu_chinh_viet_nam/',
      '',
      '',
    ),
    c(
      'Viettel Post',
      'https://viettelpost.com.vn/',
      'tracuuvandon@viettel.com.vn',
      'https://www.instagram.com/viettelpost_official/',
      '',
      '',
    ),
    c(
      'Giao Hang Tiet Kiem (GHTK)',
      'https://giaohangtietkiem.vn/',
      'cskh@giaohangtietkiem.vn',
      'https://www.instagram.com/ghtk.official/',
      'https://x.com/giaohangtietkie',
      '',
    ),
    c(
      'GHN (Giao Hàng Nhanh)',
      'https://ghn.vn/',
      'cskh@ghn.vn',
      'https://www.instagram.com/ghn.official/',
      'https://x.com/GHN_VN',
      '',
    ),
  ],
} satisfies Record<AseanMemberIsoCode, DomesticCourierService[]>
