import type { AseanMemberIsoCode } from './aseanMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per ASEAN member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const ASEAN_MAIN_INTERNATIONAL_SEAPORTS: Record<AseanMemberIsoCode, MainInternationalSeaport> = {
  BN: seaport(
    'Muara Port',
    'https://www.mtc.com.bn/',
    'info@mtc.com.bn',
    'https://x.com/MuaraPort',
    'https://www.instagram.com/muaraport/',
    'https://www.linkedin.com/company/muara-port/',
    'customs@rcs.gov.bn',
    'https://www.rcs.gov.bn',
    'Royal Customs and Excise Department — Muara Port, Muara, Brunei',
  ),
  KH: seaport(
    'Sihanoukville Autonomous Port',
    'https://www.pas.gov.kh/',
    'info@pas.gov.kh',
    'https://x.com/SihanoukvillePort',
    'https://www.instagram.com/sihanoukvilleport/',
    'https://www.linkedin.com/company/sihanoukville-autonomous-port/',
    'info@customs.gov.kh',
    'https://www.customs.gov.kh',
    'General Department of Customs and Excise — Sihanoukville Port, Sihanoukville, Cambodia',
  ),
  ID: seaport(
    'Port of Tanjung Priok (Jakarta)',
    'https://www.pelindo.co.id/',
    'info@pelindo.co.id',
    'https://x.com/Pelindo',
    'https://www.instagram.com/pelindo/',
    'https://www.linkedin.com/company/pelindo/',
    'contact.center@beacukai.go.id',
    'https://www.beacukai.go.id',
    'Direktorat Jenderal Bea dan Cukai — Pelabuhan Tanjung Priok, Jakarta, Indonesia',
  ),
  LA: seaport(
    'Port of Laem Chabang (primary maritime gateway; landlocked)',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'customs@customs.gov.la',
    'https://www.customs.gov.la',
    'Department of Customs — Vientiane, Laos',
  ),
  MY: seaport(
    'Port Klang',
    'https://www.pka.gov.my/',
    'info@pka.gov.my',
    'https://x.com/PortKlang',
    'https://www.instagram.com/portklang/',
    'https://www.linkedin.com/company/port-klang-authority/',
    'customs@customs.gov.my',
    'https://www.customs.gov.my',
    'Royal Malaysian Customs — Port Klang, Selangor, Malaysia',
  ),
  MM: seaport(
    'Thilawa Port (Yangon)',
    'https://www.mip.com.mm/',
    'info@mip.com.mm',
    'https://x.com/ThilawaPort',
    'https://www.instagram.com/thilawaport/',
    'https://www.linkedin.com/company/thilawa-port/',
    'info@customs.gov.mm',
    'https://www.customs.gov.mm',
    'Myanmar Customs Department — Thilawa Port, Yangon, Myanmar',
  ),
  PH: seaport(
    'Port of Manila (South Harbor)',
    'https://www.ppa.com.ph/',
    'info@ppa.com.ph',
    'https://x.com/PPA_Official',
    'https://www.instagram.com/ppa_official/',
    'https://www.linkedin.com/company/philippine-ports-authority/',
    'customs@customs.gov.ph',
    'https://www.customs.gov.ph',
    'Bureau of Customs — Port of Manila, Manila, Philippines',
  ),
  SG: seaport(
    'Port of Singapore',
    'https://www.mpa.gov.sg/',
    'MPA_Enquiry@mpa.gov.sg',
    'https://x.com/Mpa_Singapore',
    'https://www.instagram.com/mpa_singapore/',
    'https://www.linkedin.com/company/maritime-and-port-authority-of-singapore/',
    'customs_support@customs.gov.sg',
    'https://www.customs.gov.sg',
    'Singapore Customs — PSA Singapore Terminals, Singapore',
  ),
  TH: seaport(
    'Port of Laem Chabang',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'info@customs.go.th',
    'https://www.customs.go.th',
    'Thai Customs — Laem Chabang Port, Chonburi, Thailand',
  ),
  TL: seaport(
    'Port of Dili',
    'https://www.port-timorleste.tl/',
    'info@port-timorleste.tl',
    'https://x.com/PortDili',
    'https://www.instagram.com/portdili/',
    'https://www.linkedin.com/company/port-of-dili/',
    'customs@customs.gov.tl',
    'https://www.customs.gov.tl',
    'Timor-Leste Customs Service — Port of Dili, Dili, Timor-Leste',
  ),
  VN: seaport(
    'Port of Ho Chi Minh City (Cát Lái)',
    'https://www.saigonnewport.com.vn/',
    'info@saigonnewport.com.vn',
    'https://x.com/SaigonNewport',
    'https://www.instagram.com/saigonnewport/',
    'https://www.linkedin.com/company/saigon-newport-corporation/',
    'contact@customs.gov.vn',
    'https://www.customs.gov.vn',
    'General Department of Vietnam Customs — Cát Lái Port, Ho Chi Minh City, Vietnam',
  ),
}
