import type { NationalBankingInstitution } from './types'
import type { AseanMemberIsoCode } from './aseanMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per ASEAN member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const ASEAN_NATIONAL_BANKING_INSTITUTIONS: Record<
  AseanMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  BN: [
    bank(
      'Baiduri Bank',
      '+673 2449666',
      'Baiduri Community Space, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/baiduri-b-token/id1414199588',
      'https://play.google.com/store/apps/details?id=com.baiduri.mobilebanking',
      'https://www.baiduri.com.bn',
      'info@baiduri.com.bn',
      'https://twitter.com/baiduribank',
      'https://www.instagram.com/baiduribank/',
      'https://www.linkedin.com/company/baiduri-bank/',
      '',
      'BAIDBNDX',
      '',
    ),
    bank(
      'Bank Islam Brunei Darussalam',
      '+673 2238181',
      'Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/bibd-nexgen-wallet/id1541812683',
      'https://play.google.com/store/apps/details?id=com.bibd.nexgen',
      'https://www.bibd.com.bn',
      'enquiry@bibd.com.bn',
      'https://twitter.com/BIBDBrunei',
      'https://www.instagram.com/bibdbrunei/',
      'https://www.linkedin.com/company/bibd/',
      '',
      'BIBDBNBB',
      '',
    ),
    bank(
      'Standard Chartered Brunei',
      '+673 2658000',
      'Jalan Sultan, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/sg/app/sc-mobile-singapore/id445120671',
      'https://play.google.com/store/apps/details?id=com.sc.breezenxt.bn',
      'https://www.sc.com/bn',
      'clientcare.bnd@sc.com',
      'https://twitter.com/StanChart',
      'https://www.instagram.com/stanchart/',
      'https://www.linkedin.com/company/standard-chartered-bank/',
      '',
      'SCBLBNDX',
      '',
    ),
  ],
  KH: [
    bank(
      'ACLEDA Bank',
      '+855 23 994 444',
      '61 Preah Monivong Blvd, Phnom Penh, Cambodia',
      'https://apps.apple.com/kh/app/acleda-unity/id1506321092',
      'https://play.google.com/store/apps/details?id=com.acledabank.unity',
      'https://www.acledabank.com.kh',
      'acledabank@acledabank.com.kh',
      'https://twitter.com/acledabank',
      'https://www.instagram.com/acledabankplc/',
      'https://www.linkedin.com/company/acleda-bank/',
      '',
      'ACLBKHPP',
      '',
    ),
    bank(
      'Canadia Bank',
      '+855 23 868 222',
      '315 Ang Duong Street, Phnom Penh, Cambodia',
      'https://apps.apple.com/kh/app/canadia-bank-app/id1484956757',
      'https://play.google.com/store/apps/details?id=com.canadia.mobilebanking',
      'https://www.canadiabank.com.kh',
      'info@canadiabank.com.kh',
      'https://twitter.com/CanadiaBank',
      'https://www.instagram.com/canadiabank/',
      'https://www.linkedin.com/company/canadia-bank-plc/',
      '',
      'CADIKHPP',
      '',
    ),
    bank(
      'ABA Bank Cambodia',
      '+855 23 225 333',
      '141 Preah Sihanouk Blvd, Phnom Penh, Cambodia',
      'https://apps.apple.com/kh/app/aba-mobile/id968860129',
      'https://play.google.com/store/apps/details?id=com.paygo24.ibank',
      'https://www.ababank.com',
      'info@ababank.com',
      'https://twitter.com/ABA_Bank',
      'https://www.instagram.com/aba_bank/',
      'https://www.linkedin.com/company/aba-bank/',
      '',
      'ABAAKHPP',
      '',
    ),
  ],
  ID: [
    bank(
      'Bank Mandiri',
      '+62 21 5299 7777',
      'Plaza Mandiri, Jl. Jend. Gatot Subroto, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/livin-by-mandiri/id1555417419',
      'https://play.google.com/store/apps/details?id=id.bmri.livin',
      'https://www.bankmandiri.co.id',
      'mandiricare@bankmandiri.co.id',
      'https://twitter.com/bankmandiri',
      'https://www.instagram.com/bankmandiri/',
      'https://www.linkedin.com/company/bankmandiri/',
      '',
      'BMRIIDJA',
      '',
    ),
    bank(
      'Bank Central Asia',
      '+62 21 2358 8000',
      'Menara BCA, Grand Indonesia, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/mybca/id1465918716',
      'https://play.google.com/store/apps/details?id=com.bca.mybca.omni.android',
      'https://www.bca.co.id',
      'halobca@bca.co.id',
      'https://twitter.com/BankBCA',
      'https://www.instagram.com/goodlifebca/',
      'https://www.linkedin.com/company/pt-bank-central-asia-tbk/',
      '',
      'CENAIDJA',
      '',
    ),
    bank(
      'Bank Negara Indonesia',
      '+62 21 5728387',
      'Jl. Jend. Sudirman Kav. 1, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/wondr-by-bni/id6474669196',
      'https://play.google.com/store/apps/details?id=id.co.bni.newagenbni46',
      'https://www.bni.co.id',
      'bnicall@bni.co.id',
      'https://twitter.com/BNI',
      'https://www.instagram.com/bni46/',
      'https://www.linkedin.com/company/pt-bank-negara-indonesia-persero-tbk/',
      '',
      'BNINIDJA',
      '',
    ),
  ],
  LA: [
    bank(
      'Banque Pour Le Commerce Exterieur Lao',
      '+856 21 213200',
      'Pangkham Road, Vientiane, Laos',
      'https://apps.apple.com/la/app/bcel-one/id1224683707',
      'https://play.google.com/store/apps/details?id=com.bcel.one',
      'https://www.bcel.com.la',
      'callcenter@bcel.com.la',
      '',
      '',
      'https://www.linkedin.com/company/bcel/',
      '',
      'BCELLALA',
      '',
    ),
    bank(
      'Lao-Viet Bank',
      '+856 21 254444',
      'Lane Xang Avenue, Vientiane, Laos',
      '',
      '',
      'https://www.laovietbank.com.la',
      'info@laovietbank.com.la',
      '',
      '',
      '',
      '',
      'LVBKLALA',
      '',
    ),
    bank(
      'Banque Franco-Lao',
      '+856 21 260980',
      'Setthathirath Road, Vientiane, Laos',
      '',
      '',
      'https://www.bfl-banque.com',
      'info@bfl-banque.com',
      '',
      '',
      'https://www.linkedin.com/company/banque-franco-lao/',
      '',
      'BFLLLALA',
      '',
    ),
  ],
  MY: [
    bank(
      'Maybank',
      '+60 3 2070 8833',
      'Menara Maybank, 100 Jalan Tun Perak, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/mae-by-maybank2u/id1455827893',
      'https://play.google.com/store/apps/details?id=com.maybank2u.life',
      'https://www.maybank2u.com.my',
      'mgcc@maybank.com.my',
      'https://twitter.com/MyMaybank',
      'https://www.instagram.com/maybank/',
      'https://www.linkedin.com/company/maybank/',
      '',
      'MBBEMYKL',
      '',
    ),
    bank(
      'CIMB Bank',
      '+60 3 6204 7788',
      'Menara CIMB, Jalan Stesen Sentral 2, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/cimb-octo-my/id1533904065',
      'https://play.google.com/store/apps/details?id=com.cimbmalaysia',
      'https://www.cimb.com.my',
      'contactus@cimb.com',
      'https://twitter.com/CIMBMalaysia',
      'https://www.instagram.com/cimbmalaysia/',
      'https://www.linkedin.com/company/cimb/',
      '',
      'CIBBMYKL',
      '',
    ),
    bank(
      'Public Bank',
      '+60 3 2176 8000',
      'Menara Public Bank, Jalan Raja Chulan, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/pbe/id1181169389',
      'https://play.google.com/store/apps/details?id=com.publicbank.pbeng',
      'https://www.pbebank.com',
      'customersupport@publicbank.com.my',
      'https://twitter.com/PublicBankGroup',
      '',
      'https://www.linkedin.com/company/public-bank-berhad/',
      '',
      'PBBEMYKL',
      '',
    ),
  ],
  MM: [
    bank(
      'KBZ Bank',
      '+95 1 9510185',
      'Shwe Gon Daing Road, Yangon, Myanmar',
      'https://apps.apple.com/mm/app/kbzpay/id1343731363',
      'https://play.google.com/store/apps/details?id=com.kbzbank.kpaycustomer',
      'https://www.kbzbank.com',
      'customer.service@kbzbank.com',
      'https://twitter.com/KBZBank',
      'https://www.instagram.com/kbzbank/',
      'https://www.linkedin.com/company/kbz-bank/',
      '',
      'KBZBMMMY',
      '',
    ),
    bank(
      'CB Bank',
      '+95 1 2317770',
      'Corner of Maha Bandoola Road and 22nd Street, Yangon, Myanmar',
      'https://apps.apple.com/mm/app/cb-pay/id1456728501',
      'https://play.google.com/store/apps/details?id=com.cbbank.mobilebanking',
      'https://www.cbbank.com.mm',
      'contact@cbbank.com.mm',
      'https://twitter.com/cbbankmm',
      'https://www.instagram.com/cbbankmm/',
      'https://www.linkedin.com/company/cb-bank-pcl/',
      '',
      'CBRBMMMY',
      '',
    ),
    bank(
      'AYA Bank',
      '+95 1 2317777',
      'No. 416, Mahabandoola Road, Kyauktada Township, Yangon, Myanmar',
      'https://apps.apple.com/mm/app/aya-mobile-banking-2-0/id1439798691',
      'https://play.google.com/store/apps/details?id=com.ayabank.mbanking',
      'https://www.ayabank.com',
      'info@ayabank.com',
      'https://twitter.com/ayabank',
      'https://www.instagram.com/ayabank/',
      'https://www.linkedin.com/company/aya-bank/',
      '',
      'AYABMMMY',
      '',
    ),
  ],
  PH: [
    bank(
      'BDO Unibank',
      '+63 2 8631 8000',
      'BDO Corporate Center, Makati Avenue, Makati, Philippines',
      'https://apps.apple.com/ph/app/bdo-online/id1558548418',
      'https://play.google.com/store/apps/details?id=com.bdo.online',
      'https://www.bdo.com.ph',
      'customercare@bdo.com.ph',
      'https://twitter.com/BDOUnibank',
      'https://www.instagram.com/bdounibank/',
      'https://www.linkedin.com/company/bdo-unibank/',
      '',
      'BNORPHMM',
      '',
    ),
    bank(
      'Bank of the Philippine Islands',
      '+63 2 8891 0000',
      'Ayala North Exchange Tower, Makati, Philippines',
      'https://apps.apple.com/ph/app/bpi-mobile/id1131500055',
      'https://play.google.com/store/apps/details?id=ph.com.bpi.mobile',
      'https://www.bpi.com.ph',
      'help@bpi.com.ph',
      'https://twitter.com/TalktoBPI',
      'https://www.instagram.com/bpi/',
      'https://www.linkedin.com/company/bank-of-the-philippine-islands/',
      '',
      'BOPIPHMM',
      '',
    ),
    bank(
      'Metrobank',
      '+63 2 8870 0700',
      'Metrobank Plaza, Makati Avenue, Makati, Philippines',
      'https://apps.apple.com/ph/app/metrobank-online/id407362868',
      'https://play.google.com/store/apps/details?id=ph.com.metrobank.mcc',
      'https://www.metrobank.com.ph',
      'customercare@metrobank.com.ph',
      'https://twitter.com/Metrobank',
      'https://www.instagram.com/metrobank/',
      'https://www.linkedin.com/company/metrobank/',
      '',
      'MBTCPHMM',
      '',
    ),
  ],
  SG: [
    bank(
      'DBS Bank',
      '+65 6878 8888',
      '12 Marina Boulevard, Marina Bay Financial Centre, Singapore',
      'https://apps.apple.com/sg/app/dbs-digibank/id1068403820',
      'https://play.google.com/store/apps/details?id=com.dbs.sg.dbsmbanking',
      'https://www.dbs.com.sg',
      'contactus@dbs.com',
      'https://twitter.com/dbsbank',
      'https://www.instagram.com/dbsbank/',
      'https://www.linkedin.com/company/dbs-bank/',
      '',
      'DBSSSGSG',
      '',
    ),
    bank(
      'OCBC Bank',
      '+65 6363 3333',
      '65 Chulia Street, OCBC Centre, Singapore',
      'https://apps.apple.com/sg/app/ocbc-digital/id292506828',
      'https://play.google.com/store/apps/details?id=com.ocbc.mobile',
      'https://www.ocbc.com',
      'contactus@ocbc.com',
      'https://twitter.com/OCBCBank',
      'https://www.instagram.com/ocbc/',
      'https://www.linkedin.com/company/ocbc-bank/',
      '',
      'OCBCSGSG',
      '',
    ),
    bank(
      'UOB',
      '+65 6222 2121',
      '80 Raffles Place, UOB Plaza, Singapore',
      'https://apps.apple.com/sg/app/uob-tmrw/id1314626819',
      'https://play.google.com/store/apps/details?id=com.uob.might',
      'https://www.uob.com.sg',
      'uobcustomerservice@uobgroup.com',
      'https://twitter.com/UOBGroup',
      'https://www.instagram.com/uobgroup/',
      'https://www.linkedin.com/company/uob/',
      '',
      'UOVBSGSG',
      '',
    ),
  ],
  TH: [
    bank(
      'Bangkok Bank',
      '+66 2 230 1323',
      '333 Silom Road, Bang Rak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/bualuang-mbanking/id660355106',
      'https://play.google.com/store/apps/details?id=com.bbl.mobilebanking',
      'https://www.bangkokbank.com',
      'customercare@bangkokbank.com',
      'https://twitter.com/bangkokbank',
      'https://www.instagram.com/bangkokbank/',
      'https://www.linkedin.com/company/bangkok-bank/',
      '',
      'BKKBTHBK',
      '',
    ),
    bank(
      'Kasikornbank',
      '+66 2 888 8888',
      '1 Soi Rat Burana 27/1, Rat Burana, Bangkok, Thailand',
      'https://apps.apple.com/th/app/k-plus/id361170631',
      'https://play.google.com/store/apps/details?id=com.kasikorn.retail.mbanking.wap',
      'https://www.kasikornbank.com',
      'kcontactcenter@kasikornbank.com',
      'https://twitter.com/KBank_Live',
      'https://www.instagram.com/kbanklive/',
      'https://www.linkedin.com/company/kasikornbank/',
      '',
      'KASITHBK',
      '',
    ),
    bank(
      'Siam Commercial Bank',
      '+66 2 777 7777',
      '9 Ratchadaphisek Road, Chatuchak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/scb-easy/id568388474',
      'https://play.google.com/store/apps/details?id=com.scb.phone',
      'https://www.scb.co.th',
      'customercare@scb.co.th',
      'https://twitter.com/scb_thailand',
      'https://www.instagram.com/scb_thailand/',
      'https://www.linkedin.com/company/the-siam-commercial-bank-public-company-limited/',
      '',
      'SICOTHBK',
      '',
    ),
  ],
  TL: [
    bank(
      'Banco Nacional de Comercio de Timor-Leste',
      '+670 3310 055',
      'Avenida Bispo de Medeiros, Dili, Timor-Leste',
      '',
      '',
      'https://www.bnctl.tl',
      'info@bnctl.tl',
      '',
      '',
      '',
      '',
      'BNCTTLSX',
      '',
    ),
    bank(
      'Banco Nacional Ultramarino Timor-Leste',
      '+670 3311 133',
      'Avenida Presidente Nicolau Lobato, Dili, Timor-Leste',
      '',
      '',
      'https://www.bnu.tl',
      'info@bnu.tl',
      '',
      '',
      '',
      '',
      'BNULTLSX',
      '',
    ),
    bank(
      'Bank Mandiri Timor-Leste',
      '+670 3310 066',
      'Rua Avenida de Portugal, Dili, Timor-Leste',
      'https://apps.apple.com/id/app/livin-by-mandiri/id1555417419',
      'https://play.google.com/store/apps/details?id=id.bmri.livin',
      'https://www.bankmandiri.co.id',
      'mandiricare@bankmandiri.co.id',
      '',
      '',
      '',
      '',
      'BMRIIDJA',
      '',
    ),
  ],
  VN: [
    bank(
      'Vietcombank',
      '+84 24 3934 3137',
      '198 Tran Quang Khai, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vcb-digibank/id561433131',
      'https://play.google.com/store/apps/details?id=com.vietcombank.vcbmobile',
      'https://www.vietcombank.com.vn',
      'vcb@vietcombank.com.vn',
      'https://twitter.com/Vietcombank',
      'https://www.instagram.com/vietcombank/',
      'https://www.linkedin.com/company/vietcombank/',
      '',
      'BFTVVNVX',
      '',
    ),
    bank(
      'BIDV',
      '+84 24 2220 5544',
      '35 Hang Voi, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/bidv-smartbanking/id1283524786',
      'https://play.google.com/store/apps/details?id=com.vnpay.bidv',
      'https://www.bidv.com.vn',
      'bidv247@bidv.com.vn',
      'https://twitter.com/BIDV',
      '',
      'https://www.linkedin.com/company/bidv/',
      '',
      'BIDVVNVX',
      '',
    ),
    bank(
      'VietinBank',
      '+84 24 3941 8868',
      '108 Tran Hung Dao, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vietinbank-ipay-mobile/id542298015',
      'https://play.google.com/store/apps/details?id=com.vietinbank.ipay',
      'https://www.vietinbank.vn',
      'contact@vietinbank.vn',
      'https://twitter.com/VietinBank',
      '',
      'https://www.linkedin.com/company/vietinbank/',
      '',
      'ICBVVNVX',
      '',
    ),
  ],
}
