import type { NotableUniversity } from './types'
import type { AseanMemberIsoCode } from './aseanMemberIsoCodes'

function u(
  name: string,
  website: string,
  email: string,
  instagram: string,
  twitter: string,
  linkedin: string,
): NotableUniversity {
  return { name, website, email, instagram, twitter, linkedin }
}

/** Three notable ASEAN-member universities — economics / accounting / CS / EE-style faculties (informational; verify). */
export const ASEAN_NOTABLE_UNIVERSITIES = {
  BN: [
    u(
      'Universiti Brunei Darussalam',
      'https://www.ubd.edu.bn/',
      'info.helpdesk@ubd.edu.bn',
      'https://www.instagram.com/ubdwellbeing/',
      'https://x.com/UBDBusinessschl',
      'https://www.linkedin.com/school/universiti-brunei-darussalam/',
    ),
    u(
      'Universiti Teknologi Brunei',
      'https://www.utb.edu.bn/',
      'info.admission@utb.edu.bn',
      '',
      '',
      'https://www.linkedin.com/school/universiti-teknologi-brunei/',
    ),
    u(
      'Politeknik Brunei Darussalam',
      'https://www.pb.edu.bn/',
      'marketing@pb.edu.bn',
      '',
      '',
      '',
    ),
  ],
  KH: [
    u(
      'Royal University of Phnom Penh',
      'https://www.rupp.edu.kh/',
      'infosrupp@gmail.com',
      '',
      '',
      'https://www.linkedin.com/school/royal-university-of-phnom-penh/',
    ),
    u(
      'Institute of Technology of Cambodia',
      'http://itc.edu.kh/',
      'student_affaire@itc.edu.kh',
      '',
      '',
      '',
    ),
    u(
      'Norton University — business computing faculties',
      'https://norton-u.com/',
      'registration@nu.edu.kh',
      '',
      '',
      '',
    ),
  ],
  ID: [
    u(
      'Universitas Indonesia',
      'https://www.ui.ac.id/',
      'humas@ui.ac.id',
      'https://www.instagram.com/univ_indonesia/',
      'https://x.com/univ_indonesia',
      'https://www.linkedin.com/school/universitasindonesia/',
    ),
    u(
      'Bandung Institute of Technology',
      'https://www.itb.ac.id/',
      'humas.itb@gmail.com',
      'https://www.instagram.com/itbandung/',
      'https://x.com/itbandung_reply',
      'https://www.linkedin.com/school/institutteknologibandung/',
    ),
    u(
      'Universitas Gadjah Mada',
      'https://www.ugm.ac.id/',
      'humas@ugm.ac.id',
      'https://www.instagram.com/gadjahmadau/',
      'https://x.com/UGMOfficial',
      'https://www.linkedin.com/school/universitas-gadjah-mada/',
    ),
  ],
  LA: [
    u(
      'National University of Laos',
      'https://nuol.edu.la/',
      'info@nuol.edu.la',
      '',
      '',
      '',
    ),
    u(
      'Souphanouvong University',
      'https://www.su.edu.la/',
      'info@su.edu.la',
      '',
      '',
      '',
    ),
    u(
      'Champasack University',
      'https://www.cpu.edu.la/',
      'info@cpu.edu.la',
      '',
      '',
      '',
    ),
  ],
  MY: [
    u(
      'Universiti Malaya',
      'https://www.um.edu.my/',
      'yweb@um.edu.my',
      'https://www.instagram.com/unimalaya/',
      'https://x.com/unimalayaofficial',
      'https://www.linkedin.com/school/university-of-malaya-official/',
    ),
    u(
      'Universiti Kebangsaan Malaysia',
      'https://www.ukm.my/',
      'tncpi@ukm.edu.my',
      'https://www.instagram.com/ukm_my/',
      'https://x.com/UniversitiBangsa',
      'https://www.linkedin.com/school/universiti-kebangsaan-malaysia/',
    ),
    u(
      'Universiti Sains Malaysia',
      'https://www.usm.my/',
      'pro@sains.usm.my',
      'https://www.instagram.com/usmofficial/',
      'https://x.com/USMNusantara',
      'https://www.linkedin.com/school/universitisainsmalaysia/',
    ),
  ],
  MM: [
    u(
      'University of Yangon',
      'https://www.uy.edu.mm/',
      'Registrar@Uy.edu.mm',
      '',
      '',
      '',
    ),
    u(
      'Yangon Technological University',
      'http://ytu.edu.mm/',
      'ytu.info@mail.com',
      '',
      '',
      '',
    ),
    u(
      'University of Mandalay',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  PH: [
    u(
      'University of the Philippines Diliman',
      'https://www.upd.edu.ph/',
      'ovcsa.upd@up.edu.ph',
      'https://www.instagram.com/officialupdiliman/',
      'https://x.com/upsystem',
      'https://www.linkedin.com/school/university-of-the-philippines-diliman/',
    ),
    u(
      'Ateneo de Manila University',
      'https://www.ateneo.edu/',
      'centralregistrar.information@ateneo.edu',
      'https://www.instagram.com/ateneodemanilauniv/',
      'https://x.com/ateneodemanilauniv',
      'https://www.linkedin.com/school/ateneo/',
    ),
    u(
      'De La Salle University Manila',
      'https://www.dlsu.edu.ph/',
      'registrar@dlsu.edu.ph',
      'https://www.instagram.com/dlsumanila/',
      'https://x.com/dlsumanila',
      'https://www.linkedin.com/school/dlsumanila/',
    ),
  ],
  SG: [
    u(
      'National University of Singapore',
      'https://nus.edu.sg/',
      'enquiry@u.nus.edu',
      'https://www.instagram.com/nusingapore/',
      'https://x.com/NUSingapore',
      'https://www.linkedin.com/school/national-university-of-singapore/',
    ),
    u(
      'Nanyang Technological University',
      'https://www.ntu.edu.sg/',
      'contact@ntu.edu.sg',
      'https://www.instagram.com/ntusg/',
      'https://x.com/NTUsg',
      'https://www.linkedin.com/school/ntusg/',
    ),
    u(
      'Singapore Management University',
      'https://www.smu.edu.sg/',
      'enquiry@smu.edu.sg',
      'https://www.instagram.com/smu_sg/',
      'https://x.com/SingaporeMgtU',
      'https://www.linkedin.com/school/singapore-management-university/',
    ),
  ],
  TH: [
    u(
      'Chulalongkorn University',
      'https://www.chula.ac.th/en/',
      'reg@chula.ac.th',
      'https://www.instagram.com/chulaofficial/',
      'https://x.com/ChulaOfficial',
      'https://www.linkedin.com/school/chulalongkorn-university/',
    ),
    u(
      'Thammasat University',
      'https://www.tu.ac.th/',
      'reg@tu.ac.th',
      'https://www.instagram.com/thammasat.university/',
      'https://x.com/Thammasat1955',
      'https://www.linkedin.com/school/thammasat-university/',
    ),
    u(
      'Kasetsart University',
      'https://www.ku.ac.th/',
      'reg@ku.ac.th',
      'https://www.instagram.com/kasetsart_university/',
      'https://x.com/KasetsartUniv',
      'https://www.linkedin.com/school/kasetsart-university/',
    ),
  ],
  TL: [
    u(
      'Universidade Nacional Timor Lorosa’e',
      'https://www.untl.edu.tl/',
      'reitoria@untl.edu.tl',
      '',
      '',
      '',
    ),
    u(
      'Dili Institute of Technology',
      '',
      '',
      '',
      '',
      '',
    ),
    u(
      'Instituto Católico para Formação de Professores',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  VN: [
    u(
      'Vietnam National University Hanoi (VNU-Hanoi)',
      'https://vnu.edu.vn/',
      'info@vnu.edu.vn',
      'https://www.instagram.com/dhqghn.official/',
      '',
      'https://www.linkedin.com/school/vnu-hanoi/',
    ),
    u(
      'Hanoi University of Science and Technology',
      'https://hust.edu.vn/',
      'daotao.hust@gmail.com',
      'https://www.instagram.com/dhbkhanoi/',
      'https://x.com/DHBKHanoiOfficial',
      'https://www.linkedin.com/school/hanoi-university-of-science-and-technology/',
    ),
    u(
      'Ho Chi Minh City University of Technology — VNU HCMUT',
      'https://hcmut.edu.vn/',
      'p.daotao@hcmut.edu.vn',
      'https://www.instagram.com/dhbkhcmc/',
      'https://x.com/DHBKTPHCM',
      'https://www.linkedin.com/school/hochiminhcity-university-of-technology/',
    ),
  ],
} as const satisfies Record<AseanMemberIsoCode, readonly [NotableUniversity, NotableUniversity, NotableUniversity]>
