import type { CorporationFormationOffice } from './types'
import type { EuMemberIsoCode } from './euMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per EU member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const EU_CORPORATION_FORMATION_OFFICES: Record<EuMemberIsoCode, CorporationFormationOffice> = {
  AT:   office(
    'Firmenbuch (Commercial Register Austria)',
    '+43 1 52152 0',
    'Schottenring 30, 1010 Vienna, Austria',
    'https://www.justiz.gv.at',
    '',
    '',
    '',
    '',
    'https://www.justiz.gv.at/service/firmenbuch.html',
    'https://www.wko.at/service/unternehmensgruendung',
    'Firmenbuchnummer',
  ),
  BE:   office(
    'Banque-Carrefour des Entreprises (BCE/KBO Belgium)',
    '+32 2 277 30 11',
    'Rue du Progres 50, 1210 Brussels, Belgium',
    'https://economie.fgov.be',
    'bce@economie.fgov.be',
    '',
    '',
    '',
    'https://kbopub.economie.fgov.be',
    'https://economie.fgov.be/en/themes/enterprises/starting-business',
    'Numero d\'entreprise / Ondernemingsnummer',
  ),
  BG:   office(
    'Registry Agency Bulgaria (Commercial Register)',
    '+359 2 948 9000',
    '52 Knyaz Dondukov Blvd, Sofia, Bulgaria',
    'https://www.registryagency.bg',
    'info@registryagency.bg',
    '',
    '',
    '',
    'https://portal.registryagency.bg',
    'https://www.registryagency.bg/en/services',
    'UIC (Unified Identification Code)',
  ),
  HR:   office(
    'Court Register (Fina Croatia)',
    '+385 1 480 9000',
    'Ulica grada Vukovara 78, Zagreb, Croatia',
    'https://www.fina.hr',
    'info@fina.hr',
    '',
    '',
    '',
    'https://sudreg.pravosudje.hr',
    'https://www.hok.hr/poslovni-registar',
    'OIB (Personal Identification Number)',
  ),
  CY:   office(
    'Department of Registrar of Companies and Intellectual Property Cyprus',
    '+357 22 403 150',
    'Makarios III Avenue, Nicosia, Cyprus',
    'https://www.companies.gov.cy',
    'companies@companies.gov.cy',
    '',
    '',
    '',
    'https://www.companies.gov.cy',
    'https://www.companies.gov.cy/en/company-registration',
    'Registration Number (HE)',
  ),
  CZ:   office(
    'Business Register (Ministry of Justice Czechia)',
    '+420 296 366 366',
    'Ovocny trh 8, Prague, Czechia',
    'https://www.justice.cz',
    '',
    '',
    '',
    '',
    'https://or.justice.cz',
    'https://www.businessinfo.cz/en/articles/how-to-start-a-business-in-the-czech-republic',
    'ICO (Identification Number of Organization)',
  ),
  DK:   office(
    'Danish Business Authority (Erhvervsstyrelsen)',
    '+45 35 29 10 00',
    'Langelinie Alle 17, 2100 Copenhagen, Denmark',
    'https://erhvervsstyrelsen.dk',
    'es@erhvervsstyrelsen.dk',
    '',
    '',
    '',
    'https://virk.dk',
    'https://erhvervsstyrelsen.dk/start-virksomhed',
    'CVR Number',
  ),
  EE:   office(
    'Centre of Registers and Information Systems (RIK Estonia)',
    '+372 680 3160',
    'Lai 28, Tallinn, Estonia',
    'https://www.rik.ee',
    'info@rik.ee',
    '',
    '',
    '',
    'https://ariregister.rik.ee',
    'https://www.e-resident.gov.ee/start-a-company',
    'Registry Code',
  ),
  FI:   office(
    'Finnish Patent and Registration Office (PRH)',
    '+358 29 509 5000',
    'Sornaisten rantatie 13 C, Helsinki, Finland',
    'https://www.prh.fi',
    'prh@prh.fi',
    '',
    '',
    '',
    'https://www.ytj.fi',
    'https://www.prh.fi/en/kaupparekisteri',
    'Business ID (Y-tunnus)',
  ),
  FR:   office(
    'Infogreffe / Guichet Unique France',
    '+33 892 680 271',
    'Paris, France',
    'https://www.infogreffe.fr',
    'contact@infogreffe.fr',
    '',
    '',
    '',
    'https://www.guichet-entreprises.fr',
    'https://www.guichet-entreprises.fr/creer-son-entreprise',
    'SIREN / SIRET Number',
  ),
  DE:   office(
    'Unternehmensregister (German Commercial Register)',
    '+49 30 187810',
    'Berlin, Germany',
    'https://www.unternehmensregister.de',
    'info@handelsregister.de',
    '',
    '',
    '',
    'https://www.unternehmensregister.de',
    'https://www.gruenderplattform.de',
    'Handelsregisternummer',
  ),
  GR:   office(
    'General Commercial Registry (GEMI Greece)',
    '+30 210 328 6000',
    'Karaoli & Dimitriou 7, Athens, Greece',
    'https://www.businessportal.gr',
    'info@businessportal.gr',
    '',
    '',
    '',
    'https://www.businessportal.gr',
    'https://www.businessportal.gr/en/starting-a-business',
    'GEMI Number',
  ),
  HU:   office(
    'Court of Registration Hungary',
    '+36 1 488 2100',
    'Szalay u. 4, Budapest, Hungary',
    'https://www.e-cegjegyzek.hu',
    '',
    '',
    '',
    '',
    'https://www.e-cegjegyzek.hu',
    'https://www.magyarorszag.hu/en/business',
    'Company Registration Number',
  ),
  IE:   office(
    'Companies Registration Office Ireland (CRO)',
    '+353 1 804 5200',
    'Bloom House, Gloucester Place Lower, Dublin 1, Ireland',
    'https://www.cro.ie',
    'info@cro.ie',
    '',
    '',
    '',
    'https://core.cro.ie',
    'https://www.cro.ie/Registration/Company',
    'Company Registration Number (CRN)',
  ),
  IT:   office(
    'Registro Imprese (Chamber of Commerce Italy)',
    '+39 06 47041',
    'Via Carlo Alberto 16, Rome, Italy',
    'https://www.registroimprese.it',
    'info@registroimprese.it',
    '',
    '',
    '',
    'https://www.registroimprese.it',
    'https://www.infocamere.it/starting-a-business',
    'Codice Fiscale / REA Number',
  ),
  LV:   office(
    'Enterprise Register Latvia',
    '+371 670 31600',
    'Pils laukums 1, Riga, Latvia',
    'https://www.ur.gov.lv',
    'info@ur.gov.lv',
    '',
    '',
    '',
    'https://www.ur.gov.lv',
    'https://www.ur.gov.lv/en/registration-of-undertakings',
    'Registration Number',
  ),
  LT:   office(
    'Centre of Registers Lithuania',
    '+370 5 268 8262',
    'Zygimantu 3, Vilnius, Lithuania',
    'https://www.registrucentras.lt',
    'info@registrucentras.lt',
    '',
    '',
    '',
    'https://www.registrucentras.lt',
    'https://www.registrucentras.lt/en/registration-of-legal-entities',
    'Company Code',
  ),
  LU:   office(
    'Registre de Commerce et des Societes Luxembourg',
    '+352 2478 2478',
    '14 rue Erasme, Luxembourg',
    'https://www.lbr.lu',
    'info@lbr.lu',
    '',
    '',
    '',
    'https://www.lbr.lu',
    'https://guichet.public.lu/en/entreprises/creation-developpement',
    'RCS Number',
  ),
  MT:   office(
    'Malta Business Registry',
    '+356 2342 0000',
    'Notabile Road, Attard, Malta',
    'https://mbr.mt',
    'mbr@mbr.mt',
    '',
    '',
    '',
    'https://mbr.mt',
    'https://mbr.mt/registration-of-companies',
    'Company Registration Number',
  ),
  NL:   office(
    'Netherlands Chamber of Commerce (KVK)',
    '+31 88 585 1585',
    'St.-Jacobsstraat 300, 3511 BT Utrecht, Netherlands',
    'https://www.kvk.nl',
    'info@kvk.nl',
    '',
    '',
    'https://www.linkedin.com/company/kamer-van-koophandel/',
    'https://www.kvk.nl/inschrijven-en-wijzigen/',
    'https://www.kvk.nl/ondernemersplein/',
    'KVK Number',
  ),
  PL:   office(
    'National Court Register (KRS Poland)',
    '+48 22 530 00 00',
    'ul. Czerniakowska 100, Warsaw, Poland',
    'https://www.gov.pl/web/krs',
    '',
    '',
    '',
    '',
    'https://ekrs.ms.gov.pl',
    'https://www.biznes.gov.pl/pl/portal',
    'KRS Number',
  ),
  PT:   office(
    'Instituto dos Registos e Notariado Portugal',
    '+351 217 988 000',
    'Av. D. Joao II, Lisbon, Portugal',
    'https://www.irn.mj.pt',
    'geral@irn.mj.pt',
    '',
    '',
    '',
    'https://eportugal.gov.pt',
    'https://www.portaldaempresa.pt',
    'NIPC (Numero de Identificacao de Pessoa Coletiva)',
  ),
  RO:   office(
    'National Trade Register Office Romania (ONRC)',
    '+40 21 310 2111',
    'B-dul Unirii 78, Bucharest, Romania',
    'https://www.onrc.ro',
    'info@onrc.ro',
    '',
    '',
    '',
    'https://portal.onrc.ro',
    'https://www.onrc.ro/index.php/en/registration-procedures',
    'CUI (Cod Unic de Inregistrare)',
  ),
  SK:   office(
    'ORSR (Register of Legal Entities Slovakia)',
    '+421 2 5971 1111',
    'Bratislava, Slovakia',
    'https://www.orsr.sk',
    '',
    '',
    '',
    '',
    'https://www.orsr.sk',
    'https://www.slovensko.sk/en/life-situation/life-situation/_zivnost',
    'ICO (Identification Number)',
  ),
  SI:   office(
    'AJPES Business Register Slovenia',
    '+386 1 588 16 00',
    'Trzaska 16, Ljubljana, Slovenia',
    'https://www.ajpes.si',
    'info@ajpes.si',
    '',
    '',
    '',
    'https://www.ajpes.si',
    'https://www.ajpes.si/eng/company_registration',
    'Registration Number',
  ),
  ES:   office(
    'Registro Mercantil Central / CIRCE Spain',
    '+34 902 102 102',
    'Madrid, Spain',
    'https://www.rmc.es',
    'rmc@rmc.es',
    '',
    '',
    '',
    'https://www.circe.es',
    'https://www.rmc.es/crear-empresa',
    'NIF (Numero de Identificacion Fiscal)',
  ),
  SE:   office(
    'Swedish Companies Registration Office (Bolagsverket)',
    '+46 771 670 670',
    '851 81 Sundsvall, Sweden',
    'https://www.bolagsverket.se',
    'info@bolagsverket.se',
    '',
    '',
    '',
    'https://foretagsverket.se',
    'https://www.bolagsverket.se/foretag/aktiebolag/starta-aktiebolag',
    'Organisationsnummer',
  ),
}
