import type { EuMemberIsoCode } from './euMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per EU member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const EU_MAIN_INTERNATIONAL_SEAPORTS: Record<EuMemberIsoCode, MainInternationalSeaport> = {
  AT: seaport(
    'Port of Koper (primary maritime gateway; landlocked)',
    'https://www.luka-kp.si/',
    'info@luka-kp.si',
    'https://x.com/PortKoper',
    'https://www.instagram.com/portkoper/',
    'https://www.linkedin.com/company/luka-koper/',
    'zoll@bmf.gv.at',
    'https://www.bmf.gv.at',
    'Bundesministerium Finanzen Zoll — Vienna, Austria',
  ),
  BE: seaport(
    'Port of Antwerp-Bruges',
    'https://www.portofantwerpbruges.com/',
    'info@portofantwerpbruges.com',
    'https://x.com/PortofAntwerp',
    'https://www.instagram.com/portofantwerpbruges/',
    'https://www.linkedin.com/company/port-of-antwerp-bruges/',
    'douanes@minfin.fed.be',
    'https://finances.belgium.be/fr/douanes_accises',
    'Belgian Customs — Port of Antwerp, Antwerp, Belgium',
  ),
  BG: seaport(
    'Port of Varna',
    'https://www.port-varna.com/',
    'info@port-varna.com',
    'https://x.com/PortVarna',
    'https://www.instagram.com/portvarna/',
    'https://www.linkedin.com/company/port-of-varna/',
    'customs@customs.bg',
    'https://www.customs.bg',
    'Bulgarian Customs — Port of Varna, Varna, Bulgaria',
  ),
  HR: seaport(
    'Port of Rijeka',
    'https://www.lukarijeka.hr/',
    'info@lukarijeka.hr',
    'https://x.com/PortRijeka',
    'https://www.instagram.com/portrijeka/',
    'https://www.linkedin.com/company/port-of-rijeka-authority/',
    'carina@carina.hr',
    'https://www.carina.hr',
    'Croatian Customs — Port of Rijeka, Rijeka, Croatia',
  ),
  CY: seaport(
    'Port of Limassol',
    'https://www.cyprusports.gov.cy/',
    'info@cyprusports.gov.cy',
    'https://x.com/CyprusPorts',
    'https://www.instagram.com/cyprusports/',
    'https://www.linkedin.com/company/cyprus-ports-authority/',
    'customs@mof.gov.cy',
    'https://www.mof.gov.cy/customs',
    'Cyprus Customs — Port of Limassol, Limassol, Cyprus',
  ),
  CZ: seaport(
    'Port of Hamburg (primary maritime gateway; landlocked)',
    'https://www.hafen-hamburg.de/',
    'info@hafen-hamburg.de',
    'https://x.com/hafenhamburg',
    'https://www.instagram.com/hafenhamburg/',
    'https://www.linkedin.com/company/hamburg-port-authority/',
    'celni@cs.mfcr.cz',
    'https://www.celnisprava.cz',
    'Czech Customs Administration — Prague, Czech Republic',
  ),
  DK: seaport(
    'Port of Aarhus',
    'https://www.aarhushavn.dk/',
    'info@aarhushavn.dk',
    'https://x.com/AarhusHavn',
    'https://www.instagram.com/aarhushavn/',
    'https://www.linkedin.com/company/port-of-aarhus/',
    'told@skat.dk',
    'https://www.skat.dk',
    'Danish Customs — Port of Aarhus, Aarhus, Denmark',
  ),
  EE: seaport(
    'Port of Muuga (Tallinn)',
    'https://www.portoftallinn.com/',
    'info@portoftallinn.com',
    'https://x.com/PortofTallinn',
    'https://www.instagram.com/portoftallinn/',
    'https://www.linkedin.com/company/port-of-tallinn/',
    'info@toll.ee',
    'https://www.emta.ee',
    'Estonian Tax and Customs Board — Port of Muuga, Tallinn, Estonia',
  ),
  FI: seaport(
    'Port of HaminaKotka',
    'https://www.portofhamina.fi/',
    'info@portofhamina.fi',
    'https://x.com/PortOfHamina',
    'https://www.instagram.com/portofhamina/',
    'https://www.linkedin.com/company/port-of-hamina-kotka/',
    'tulli@tulli.fi',
    'https://www.tulli.fi',
    'Finnish Customs — Port of HaminaKotka, Hamina, Finland',
  ),
  FR: seaport(
    'Port of Le Havre',
    'https://www.havre-port.fr/',
    'info@havre-port.fr',
    'https://x.com/HavrePort',
    'https://www.instagram.com/havreport/',
    'https://www.linkedin.com/company/grand-port-maritime-du-havre/',
    'douane@douane.gouv.fr',
    'https://www.douane.gouv.fr',
    'French Customs — Port of Le Havre, Le Havre, France',
  ),
  DE: seaport(
    'Port of Hamburg',
    'https://www.hafen-hamburg.de/',
    'info@hafen-hamburg.de',
    'https://x.com/hafenhamburg',
    'https://www.instagram.com/hafenhamburg/',
    'https://www.linkedin.com/company/hamburg-port-authority/',
    'info@zoll.de',
    'https://www.zoll.de',
    'German Customs — Port of Hamburg, Hamburg, Germany',
  ),
  GR: seaport(
    'Port of Piraeus',
    'https://www.olp.gr/',
    'info@olp.gr',
    'https://x.com/PiraeusPort',
    'https://www.instagram.com/piraeusport/',
    'https://www.linkedin.com/company/piraeus-port-authority/',
    'info@aade.gr',
    'https://www.aade.gr',
    'Independent Authority for Public Revenue — Port of Piraeus, Piraeus, Greece',
  ),
  HU: seaport(
    'Port of Rijeka (primary maritime gateway; landlocked)',
    'https://www.lukarijeka.hr/',
    'info@lukarijeka.hr',
    'https://x.com/PortRijeka',
    'https://www.instagram.com/portrijeka/',
    'https://www.linkedin.com/company/port-of-rijeka-authority/',
    'vaminfo@nav.gov.hu',
    'https://nav.gov.hu',
    'National Tax and Customs Administration — Budapest, Hungary',
  ),
  IE: seaport(
    'Port of Dublin',
    'https://www.dublinport.ie/',
    'info@dublinport.ie',
    'https://x.com/DublinPort',
    'https://www.instagram.com/dublinport/',
    'https://www.linkedin.com/company/dublin-port-company/',
    'revenue@revenue.ie',
    'https://www.revenue.ie',
    'Revenue Commissioners Customs — Port of Dublin, Dublin, Ireland',
  ),
  IT: seaport(
    'Port of Genoa',
    'https://www.portsofgenoa.com/',
    'info@portsofgenoa.com',
    'https://x.com/PortofGenoa',
    'https://www.instagram.com/portofgenoa/',
    'https://www.linkedin.com/company/western-ligurian-sea-port-authority/',
    'dogane@dogane.gov.it',
    'https://www.adm.gov.it',
    'Agenzia delle Dogane — Porto di Genova, Genoa, Italy',
  ),
  LV: seaport(
    'Port of Riga',
    'https://www.rop.lv/',
    'info@rop.lv',
    'https://x.com/FreeportRiga',
    'https://www.instagram.com/freeportriga/',
    'https://www.linkedin.com/company/freeport-of-riga/',
    'info@vid.gov.lv',
    'https://www.vid.gov.lv',
    'State Revenue Service — Port of Riga, Riga, Latvia',
  ),
  LT: seaport(
    'Port of Klaipėda',
    'https://www.portofklaipeda.lt/',
    'info@portofklaipeda.lt',
    'https://x.com/PortKlaipeda',
    'https://www.instagram.com/portklaipeda/',
    'https://www.linkedin.com/company/klaipeda-state-seaport-authority/',
    'muitine@muitine.lt',
    'https://www.lrmuitine.lt',
    'Lithuanian Customs — Port of Klaipėda, Klaipėda, Lithuania',
  ),
  LU: seaport(
    'Port of Antwerp-Bruges (primary maritime gateway; landlocked)',
    'https://www.portofantwerpbruges.com/',
    'info@portofantwerpbruges.com',
    'https://x.com/PortofAntwerp',
    'https://www.instagram.com/portofantwerpbruges/',
    'https://www.linkedin.com/company/port-of-antwerp-bruges/',
    'douanes@do.etat.lu',
    'https://www.do.etat.lu',
    'Administration des Douanes — Luxembourg City, Luxembourg',
  ),
  MT: seaport(
    'Port of Marsaxlokk (Malta Freeport)',
    'https://www.maltafreeport.com/',
    'info@maltafreeport.com',
    'https://x.com/MaltaFreeport',
    'https://www.instagram.com/maltafreeport/',
    'https://www.linkedin.com/company/malta-freeport/',
    'customs@gov.mt',
    'https://cfr.gov.mt',
    'Malta Customs — Malta Freeport, Marsaxlokk, Malta',
  ),
  NL: seaport(
    'Port of Rotterdam',
    'https://www.portofrotterdam.com/',
    'info@portofrotterdam.com',
    'https://x.com/PortOfRotterdam',
    'https://www.instagram.com/portofrotterdam/',
    'https://www.linkedin.com/company/port-of-rotterdam/',
    'douane@belastingdienst.nl',
    'https://www.belastingdienst.nl',
    'Dutch Customs — Port of Rotterdam, Rotterdam, Netherlands',
  ),
  PL: seaport(
    'Port of Gdańsk',
    'https://www.portgdansk.pl/',
    'info@portgdansk.pl',
    'https://x.com/PortGdansk',
    'https://www.instagram.com/portgdansk/',
    'https://www.linkedin.com/company/port-of-gdansk/',
    'info@mf.gov.pl',
    'https://www.gov.pl/web/kas',
    'National Revenue Administration — Port of Gdańsk, Gdańsk, Poland',
  ),
  PT: seaport(
    'Port of Sines',
    'https://www.portodesines.pt/',
    'info@portodesines.pt',
    'https://x.com/PortodeSines',
    'https://www.instagram.com/portodesines/',
    'https://www.linkedin.com/company/porto-de-sines/',
    'aduaneira@at.gov.pt',
    'https://www.portaldasfinancas.gov.pt',
    'Autoridade Tributária — Port of Sines, Sines, Portugal',
  ),
  RO: seaport(
    'Port of Constanța',
    'https://www.portofconstantza.com/',
    'info@portofconstantza.com',
    'https://x.com/PortConstanta',
    'https://www.instagram.com/portofconstantza/',
    'https://www.linkedin.com/company/maritime-ports-administration-constantza/',
    'customs@customs.ro',
    'https://www.customs.ro',
    'Romanian Customs — Port of Constanța, Constanța, Romania',
  ),
  SK: seaport(
    'Port of Bratislava (Danube)',
    'https://www.spap.sk/',
    'info@spap.sk',
    'https://x.com/SPAP_Bratislava',
    'https://www.instagram.com/spap_bratislava/',
    'https://www.linkedin.com/company/slovak-shipping-and-ports/',
    'celny@financnasprava.sk',
    'https://www.financnasprava.sk',
    'Financial Administration — Port of Bratislava, Bratislava, Slovakia',
  ),
  SI: seaport(
    'Port of Koper',
    'https://www.luka-kp.si/',
    'info@luka-kp.si',
    'https://x.com/PortKoper',
    'https://www.instagram.com/portkoper/',
    'https://www.linkedin.com/company/luka-koper/',
    'carina@carina.gov.si',
    'https://www.carina.gov.si',
    'Financial Administration — Port of Koper, Koper, Slovenia',
  ),
  ES: seaport(
    'Port of Algeciras',
    'https://www.puertoalgeciras.com/',
    'info@puertoalgeciras.com',
    'https://x.com/PuertoAlgeciras',
    'https://www.instagram.com/puertoalgeciras/',
    'https://www.linkedin.com/company/autoridad-portuaria-bahia-de-algeciras/',
    'aduana@aeat.es',
    'https://www.agenciatributaria.es',
    'Spanish Customs — Port of Algeciras, Algeciras, Spain',
  ),
  SE: seaport(
    'Port of Gothenburg',
    'https://www.goteborgshamn.se/',
    'info@goteborgshamn.se',
    'https://x.com/Goteborgshamn',
    'https://www.instagram.com/goteborgshamn/',
    'https://www.linkedin.com/company/port-of-gothenburg/',
    'tullverket@tullverket.se',
    'https://www.tullverket.se',
    'Swedish Customs — Port of Gothenburg, Gothenburg, Sweden',
  ),
}
