import type { EuMemberIsoCode } from './euMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const EU_MAIN_INTERNATIONAL_AIRPORTS: Record<EuMemberIsoCode, MainInternationalAirport> = {
  AT: {
    name: 'Vienna International Airport (VIE)',
    website: 'https://www.viennaairport.com/',
    email: 'info@viennaairport.com',
    twitter: 'https://x.com/viennaairport',
    instagram: 'https://www.instagram.com/viennaairport/',
    linkedin: 'https://www.linkedin.com/company/flughafen-wien-ag/',
    apiEndpoint: '',
  },
  BE: {
    name: 'Brussels Airport (BRU)',
    website: 'https://www.brusselsairport.be/',
    email: 'info@brusselsairport.be',
    twitter: 'https://x.com/BrusselsAirport',
    instagram: 'https://www.instagram.com/brusselsairport/',
    linkedin: 'https://www.linkedin.com/company/brussels-airport/',
    apiEndpoint: '',
  },
  BG: {
    name: 'Sofia Airport (SOF)',
    website: 'https://www.sofia-airport.eu/',
    email: 'info@sofia-airport.eu',
    twitter: 'https://x.com/SofiaAirport',
    instagram: 'https://www.instagram.com/sofiaairport/',
    linkedin: 'https://www.linkedin.com/company/sofia-airport/',
    apiEndpoint: '',
  },
  HR: {
    name: 'Zagreb Airport (ZAG)',
    website: 'https://www.zagreb-airport.hr/',
    email: 'info@zagreb-airport.hr',
    twitter: 'https://x.com/ZagrebAirport',
    instagram: 'https://www.instagram.com/zagrebairport/',
    linkedin: 'https://www.linkedin.com/company/zagreb-airport/',
    apiEndpoint: '',
  },
  CY: {
    name: 'Larnaca International Airport (LCA)',
    website: 'https://www.hermesairports.com/',
    email: 'info@hermesairports.com',
    twitter: 'https://x.com/HermesAirports',
    instagram: 'https://www.instagram.com/hermesairports/',
    linkedin: 'https://www.linkedin.com/company/hermes-airports/',
    apiEndpoint: '',
  },
  CZ: {
    name: 'Václav Havel Airport Prague (PRG)',
    website: 'https://www.prg.aero/',
    email: 'info@prg.aero',
    twitter: 'https://x.com/PragueAirport',
    instagram: 'https://www.instagram.com/pragueairport/',
    linkedin: 'https://www.linkedin.com/company/prague-airport/',
    apiEndpoint: '',
  },
  DK: {
    name: 'Copenhagen Airport (CPH)',
    website: 'https://www.cph.dk/',
    email: 'info@cph.dk',
    twitter: 'https://x.com/CopenhagenAirport',
    instagram: 'https://www.instagram.com/copenhagenairport/',
    linkedin: 'https://www.linkedin.com/company/copenhagen-airports/',
    apiEndpoint: '',
  },
  EE: {
    name: 'Tallinn Airport (TLL)',
    website: 'https://www.tallinn-airport.ee/',
    email: 'info@tallinn-airport.ee',
    twitter: 'https://x.com/TallinnAirport',
    instagram: 'https://www.instagram.com/tallinnairport/',
    linkedin: 'https://www.linkedin.com/company/tallinn-airport/',
    apiEndpoint: '',
  },
  FI: {
    name: 'Helsinki-Vantaa Airport (HEL)',
    website: 'https://www.finavia.fi/en/airports/helsinki-airport',
    email: 'helsinki-airport@finavia.fi',
    twitter: 'https://x.com/HelsinkiAirport',
    instagram: 'https://www.instagram.com/helsinkiairport/',
    linkedin: 'https://www.linkedin.com/company/finavia/',
    apiEndpoint: '',
  },
  FR: {
    name: 'Paris Charles de Gaulle Airport (CDG)',
    website: 'https://www.parisaeroport.fr/',
    email: 'contact@adp.fr',
    twitter: 'https://x.com/ParisAeroport',
    instagram: 'https://www.instagram.com/parisaeroport/',
    linkedin: 'https://www.linkedin.com/company/groupe-adp/',
    apiEndpoint: '',
  },
  DE: {
    name: 'Frankfurt Airport (FRA)',
    website: 'https://www.frankfurt-airport.com/',
    email: 'info@fraport.de',
    twitter: 'https://x.com/Airport_FRA',
    instagram: 'https://www.instagram.com/airport_fra/',
    linkedin: 'https://www.linkedin.com/company/frankfurt-airport/',
    apiEndpoint: '',
  },
  GR: {
    name: 'Athens International Airport (ATH)',
    website: 'https://www.aia.gr/',
    email: 'info@aia.gr',
    twitter: 'https://x.com/ATH_airport',
    instagram: 'https://www.instagram.com/athens_airport/',
    linkedin: 'https://www.linkedin.com/company/athens-international-airport/',
    apiEndpoint: '',
  },
  HU: {
    name: 'Budapest Ferenc Liszt International Airport (BUD)',
    website: 'https://www.bud.hu/',
    email: 'info@bud.hu',
    twitter: 'https://x.com/BudapestAirport',
    instagram: 'https://www.instagram.com/budapestairport/',
    linkedin: 'https://www.linkedin.com/company/budapest-airport/',
    apiEndpoint: '',
  },
  IE: {
    name: 'Dublin Airport (DUB)',
    website: 'https://www.dublinairport.com/',
    email: 'info@dublinairport.com',
    twitter: 'https://x.com/DublinAirport',
    instagram: 'https://www.instagram.com/dublinairport/',
    linkedin: 'https://www.linkedin.com/company/dublin-airport/',
    apiEndpoint: '',
  },
  IT: {
    name: 'Leonardo da Vinci–Fiumicino Airport (FCO)',
    website: 'https://www.adr.it/',
    email: 'info@adr.it',
    twitter: 'https://x.com/ADRAirports',
    instagram: 'https://www.instagram.com/adr_airports/',
    linkedin: 'https://www.linkedin.com/company/adr-aeroporti-di-roma/',
    apiEndpoint: '',
  },
  LV: {
    name: 'Riga International Airport (RIX)',
    website: 'https://www.riga-airport.com/',
    email: 'info@riga-airport.com',
    twitter: 'https://x.com/RigaAirport',
    instagram: 'https://www.instagram.com/rigaairport/',
    linkedin: 'https://www.linkedin.com/company/riga-international-airport/',
    apiEndpoint: '',
  },
  LT: {
    name: 'Vilnius Airport (VNO)',
    website: 'https://www.vilnius-airport.lt/',
    email: 'info@vilnius-airport.lt',
    twitter: 'https://x.com/VilniusAirport',
    instagram: 'https://www.instagram.com/vilniusairport/',
    linkedin: 'https://www.linkedin.com/company/vilnius-airport/',
    apiEndpoint: '',
  },
  LU: {
    name: 'Luxembourg Airport (LUX)',
    website: 'https://www.lux-airport.lu/',
    email: 'info@lux-airport.lu',
    twitter: 'https://x.com/LuxAirport',
    instagram: 'https://www.instagram.com/luxairport/',
    linkedin: 'https://www.linkedin.com/company/luxembourg-airport/',
    apiEndpoint: '',
  },
  MT: {
    name: 'Malta International Airport (MLA)',
    website: 'https://www.maltairport.com/',
    email: 'info@maltairport.com',
    twitter: 'https://x.com/MaltaAirport',
    instagram: 'https://www.instagram.com/maltairport/',
    linkedin: 'https://www.linkedin.com/company/malta-international-airport/',
    apiEndpoint: '',
  },
  NL: {
    name: 'Amsterdam Airport Schiphol (AMS)',
    website: 'https://www.schiphol.nl/',
    email: 'info@schiphol.nl',
    twitter: 'https://x.com/Schiphol',
    instagram: 'https://www.instagram.com/schiphol/',
    linkedin: 'https://www.linkedin.com/company/amsterdam-airport-schiphol/',
    apiEndpoint: '',
  },
  PL: {
    name: 'Warsaw Chopin Airport (WAW)',
    website: 'https://www.lot.com/pl/en/warsaw-chopin-airport',
    email: 'info@chopin-airport.pl',
    twitter: 'https://x.com/ChopinAirport',
    instagram: 'https://www.instagram.com/chopinairport/',
    linkedin: 'https://www.linkedin.com/company/chopin-airport/',
    apiEndpoint: '',
  },
  PT: {
    name: 'Lisbon Humberto Delgado Airport (LIS)',
    website: 'https://www.ana.pt/',
    email: 'info@ana.pt',
    twitter: 'https://x.com/ANA_Aeroportos',
    instagram: 'https://www.instagram.com/ana_aeroportos/',
    linkedin: 'https://www.linkedin.com/company/ana-aeroportos-de-portugal/',
    apiEndpoint: '',
  },
  RO: {
    name: 'Henri Coandă International Airport (OTP)',
    website: 'https://www.bucharestairports.ro/',
    email: 'info@bucharestairports.ro',
    twitter: 'https://x.com/BucharestAirport',
    instagram: 'https://www.instagram.com/bucharestairport/',
    linkedin: 'https://www.linkedin.com/company/bucharest-airports/',
    apiEndpoint: '',
  },
  SK: {
    name: 'M. R. Štefánik Airport (BTS)',
    website: 'https://www.airportbratislava.sk/',
    email: 'info@airportbratislava.sk',
    twitter: 'https://x.com/BTSairport',
    instagram: 'https://www.instagram.com/btsairport/',
    linkedin: 'https://www.linkedin.com/company/bratislava-airport/',
    apiEndpoint: '',
  },
  SI: {
    name: 'Ljubljana Jože Pučnik Airport (LJU)',
    website: 'https://www.lju-airport.si/',
    email: 'info@lju-airport.si',
    twitter: 'https://x.com/LJUairport',
    instagram: 'https://www.instagram.com/ljuairport/',
    linkedin: 'https://www.linkedin.com/company/ljubljana-airport/',
    apiEndpoint: '',
  },
  ES: {
    name: 'Adolfo Suárez Madrid–Barajas Airport (MAD)',
    website: 'https://www.aena.es/',
    email: 'info@aena.es',
    twitter: 'https://x.com/Aena',
    instagram: 'https://www.instagram.com/aena/',
    linkedin: 'https://www.linkedin.com/company/aena/',
    apiEndpoint: '',
  },
  SE: {
    name: 'Stockholm Arlanda Airport (ARN)',
    website: 'https://www.swedavia.com/arlanda/',
    email: 'info@swedavia.se',
    twitter: 'https://x.com/Arlanda',
    instagram: 'https://www.instagram.com/arlanda/',
    linkedin: 'https://www.linkedin.com/company/swedavia/',
    apiEndpoint: '',
  },
}
