import type { EuMemberIsoCode } from './euMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2 for
 * EU member states (informational; verify against USGS Mineral Commodity Summaries, BGS
 * World Mineral Production, EuroMINES, and UN Comtrade periodically). EU is dominated by
 * downstream refining / smelting rather than primary mining; only a handful of members
 * (FI, SE, PL, BG, ES, IE, PT) operate large-scale primary metal mines.
 */
export const EU_MAIN_EXPORTED_ELEMENTS: Record<EuMemberIsoCode, MainExportedElements> = {
  AT: e(
    'Iron (Fe)',
    'Magnesium (Mg)',
    'Tungsten (W)',
    'Copper (Cu)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Zinc (Zn)',
  ),
  BE: e(
    'Cobalt (Co)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Carbon (C)',
    'Silicon (Si)',
    'Germanium (Ge)',
    'Indium (In)',
  ),
  BG: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  HR: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Magnesium (Mg)',
  ),
  CY: e(
    'Copper (Cu)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Sodium (Na)',
  ),
  CZ: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Carbon (C)',
    'Copper (Cu)',
    'Uranium (U)',
    'Magnesium (Mg)',
  ),
  DK: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
  ),
  EE: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  FI: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Copper (Cu)',
    'Chromium (Cr)',
    'Zinc (Zn)',
    'Gold (Au)',
    'Iron (Fe)',
  ),
  FR: e(
    'Uranium (U)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Titanium (Ti)',
    'Gold (Au)',
  ),
  DE: e(
    'Carbon (C)',
    'Copper (Cu)',
    'Potassium (K)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Gallium (Ga)',
  ),
  GR: e(
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Magnesium (Mg)',
    'Silver (Ag)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Iron (Fe)',
  ),
  HU: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Manganese (Mn)',
    'Magnesium (Mg)',
    'Carbon (C)',
  ),
  IE: e(
    'Zinc (Zn)',
    'Lead (Pb)',
    'Carbon (C)',
    'Silver (Ag)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
  ),
  IT: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Lead (Pb)',
    'Zinc (Zn)',
  ),
  LV: e(
    'Carbon (C)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  LT: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Nitrogen (N)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
  ),
  LU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Carbon (C)',
    'Magnesium (Mg)',
    'Zinc (Zn)',
  ),
  MT: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  NL: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  PL: e(
    'Copper (Cu)',
    'Silver (Ag)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Sulfur (S)',
  ),
  PT: e(
    'Copper (Cu)',
    'Tungsten (W)',
    'Tin (Sn)',
    'Lithium (Li)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Lead (Pb)',
  ),
  RO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Gold (Au)',
    'Sulfur (S)',
  ),
  SK: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Carbon (C)',
    'Magnesium (Mg)',
    'Gold (Au)',
  ),
  SI: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Mercury (Hg)',
  ),
  ES: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Tungsten (W)',
    'Mercury (Hg)',
  ),
  SE: e(
    'Iron (Fe)',
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Carbon (C)',
  ),
}
