import type { NationalBankingInstitution } from './types'
import type { EuMemberIsoCode } from './euMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per EU member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const EU_NATIONAL_BANKING_INSTITUTIONS: Record<
  EuMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AT: [
    bank(
      'Erste Bank Oesterreich',
      '+43 5 0100 20100',
      'Am Belvedere 1, Vienna, Austria',
      '',
      '',
      'https://www.sparkasse.at',
      'service@sparkasse.at',
      '',
      '',
      '',
      '',
      'GIBAATWW',
      '',
    ),
    bank(
      'Raiffeisen Bank International',
      '+43 1 71707 0',
      'Am Stadtpark 9, Vienna, Austria',
      '',
      '',
      'https://www.rbinternational.com',
      'office@rbinternational.com',
      '',
      '',
      '',
      '',
      'RZBAATWW',
      '',
    ),
    bank(
      'UniCredit Bank Austria',
      '+43 5 05 05',
      'Rothschildplatz 1, Vienna, Austria',
      '',
      '',
      'https://www.bankaustria.at',
      'service@unicreditgroup.at',
      '',
      '',
      '',
      '',
      'BKAUATWW',
      '',
    ),
  ],
  BE: [
    bank(
      'KBC Bank',
      '+32 2 429 2121',
      'Havenlaan 2, 1080 Brussels, Belgium',
      'https://apps.apple.com/be/app/kbc-mobile/id428811587',
      'https://play.google.com/store/apps/details?id=com.kbc.mobile.android.phone.kbc',
      'https://www.kbc.be',
      'info@kbc.be',
      'https://twitter.com/kbc_be',
      'https://www.instagram.com/kbc_be/',
      'https://www.linkedin.com/company/kbc-bank/',
      '',
      'KREDBEBB',
      'https://developer.kbc.be',
    ),
    bank(
      'BNP Paribas Fortis',
      '+32 2 228 1111',
      'Montagne du Parc 3, 1000 Brussels, Belgium',
      'https://apps.apple.com/be/app/bnp-paribas-fortis-mobile/id428811587',
      'https://play.google.com/store/apps/details?id=be.fortis.mobile',
      'https://www.bnpparibasfortis.be',
      'contact@bnpparibasfortis.be',
      'https://twitter.com/BNPParibasFortis',
      'https://www.instagram.com/bnpparibasfortis/',
      'https://www.linkedin.com/company/bnp-paribas-fortis/',
      '',
      'GEBABEBB',
      '',
    ),
    bank(
      'ING Belgium',
      '+32 2 464 60 04',
      'Avenue Marnix 24, 1000 Brussels, Belgium',
      'https://apps.apple.com/be/app/ing-banking/id474807486',
      'https://play.google.com/store/apps/details?id=com.ing.mobile',
      'https://www.ing.be',
      'contact@ing.be',
      'https://twitter.com/INGBelgium',
      'https://www.instagram.com/ingbelgium/',
      'https://www.linkedin.com/company/ing-belgium/',
      '',
      'BBRUBEBB',
      'https://developer.ing.com',
    ),
  ],
  BG: [
    bank(
      'UniCredit Bulbank',
      '+359 2 9337 000',
      '7 Sveta Nedelya Sq, Sofia, Bulgaria',
      '',
      '',
      'https://www.unicreditbulbank.bg',
      'contact@unicreditgroup.bg',
      '',
      '',
      '',
      '',
      'UNCRBGSF',
      '',
    ),
    bank(
      'DSK Bank',
      '+359 2 0700 10 375',
      '19 Moskovska St, Sofia, Bulgaria',
      '',
      '',
      'https://dskbank.bg',
      'contactcenter@dskbank.bg',
      '',
      '',
      '',
      '',
      'STSABGSF',
      '',
    ),
    bank(
      'United Bulgarian Bank',
      '+359 2 483 1717',
      '89B Vitosha Blvd, Sofia, Bulgaria',
      '',
      '',
      'https://www.ubb.bg',
      'contact.center@ubb.bg',
      '',
      '',
      '',
      '',
      'UBBSBGSF',
      '',
    ),
  ],
  HR: [
    bank(
      'Zagrebacka banka',
      '+385 1 3789 000',
      'Trg bana Josipa Jelacica 10, Zagreb, Croatia',
      '',
      '',
      'https://www.zaba.hr',
      'zaba@unicreditgroup.zaba.hr',
      '',
      '',
      '',
      '',
      'ZABAHR2X',
      '',
    ),
    bank(
      'Privredna banka Zagreb',
      '+385 1 6363 636',
      'Radnicka cesta 50, Zagreb, Croatia',
      '',
      '',
      'https://www.pbz.hr',
      'pbz365@pbz.hr',
      '',
      '',
      '',
      '',
      'PBZGHR2X',
      '',
    ),
    bank(
      'Erste & Steiermarkische Bank',
      '+385 72 37 1000',
      'Ivana Lucica 2, Zagreb, Croatia',
      '',
      '',
      'https://www.erstebank.hr',
      'erstebank@erstebank.hr',
      '',
      '',
      '',
      '',
      'ESBCHR22',
      '',
    ),
  ],
  CY: [
    bank(
      'Bank of Cyprus',
      '+357 22 128000',
      '51 Stasinou St, Nicosia, Cyprus',
      '',
      '',
      'https://www.bankofcyprus.com',
      'info@bankofcyprus.com',
      '',
      '',
      '',
      '',
      'BCYPCY2N',
      '',
    ),
    bank(
      'Hellenic Bank',
      '+357 22 500500',
      '200 Athalassas Ave, Strovolos, Cyprus',
      '',
      '',
      'https://www.hellenicbank.com',
      'contact@hellenicbank.com',
      '',
      '',
      '',
      '',
      'HEBACY2N',
      '',
    ),
    bank(
      'Eurobank Cyprus',
      '+357 25 880000',
      '41 Arch. Makariou III Ave, Limassol, Cyprus',
      '',
      '',
      'https://www.eurobank.com.cy',
      'info@eurobank.com.cy',
      '',
      '',
      '',
      '',
      'EGCYCY2N',
      '',
    ),
  ],
  CZ: [
    bank(
      'Ceska sporitelna',
      '+420 800 207 207',
      'Olbrachtova 1929/62, Prague, Czech Republic',
      '',
      '',
      'https://www.csas.cz',
      'info@csas.cz',
      '',
      '',
      '',
      '',
      'GIBACZPX',
      '',
    ),
    bank(
      'CSOB',
      '+420 800 300 300',
      'Radlicka 333/150, Prague, Czech Republic',
      '',
      '',
      'https://www.csob.cz',
      'info@csob.cz',
      '',
      '',
      '',
      '',
      'CEKOCZPP',
      '',
    ),
    bank(
      'Komerci banka',
      '+420 955 551 552',
      'Na Prikope 33, Prague, Czech Republic',
      '',
      '',
      'https://www.kb.cz',
      'info@kb.cz',
      '',
      '',
      '',
      '',
      'KOMBCZPP',
      '',
    ),
  ],
  DK: [
    bank(
      'Danske Bank',
      '+45 70 123 456',
      'Holmens Kanal 2-12, 1092 Copenhagen, Denmark',
      'https://apps.apple.com/dk/app/danske-mobilbank/id429047995',
      'https://play.google.com/store/apps/details?id=com.danskebank.mobilebank3.dk',
      'https://danskebank.dk',
      'info@danskebank.dk',
      'https://twitter.com/DanskeBank',
      'https://www.instagram.com/danskebank/',
      'https://www.linkedin.com/company/danske-bank/',
      '',
      'DABADKKK',
      'https://developers.danskebank.com',
    ),
    bank(
      'Nordea Denmark',
      '+45 70 33 33 33',
      'Grønjordsvej 10, 2300 Copenhagen, Denmark',
      'https://apps.apple.com/dk/app/nordea-mobile/id429047995',
      'https://play.google.com/store/apps/details?id=com.nordea.mobilebank',
      'https://www.nordea.dk',
      'kundeservice@nordea.dk',
      'https://twitter.com/Nordea',
      'https://www.instagram.com/nordea/',
      'https://www.linkedin.com/company/nordea/',
      '',
      'NDEADKKK',
      'https://developer.nordea.com',
    ),
    bank(
      'Jyske Bank',
      '+45 89 89 89 89',
      'Vestergade 8, 8600 Silkeborg, Denmark',
      'https://apps.apple.com/dk/app/jyske-mobilbank/id429047995',
      'https://play.google.com/store/apps/details?id=dk.jyskebank.drb',
      'https://www.jyskebank.dk',
      'info@jyskebank.dk',
      'https://twitter.com/JyskeBank',
      'https://www.instagram.com/jyskebank/',
      'https://www.linkedin.com/company/jyske-bank/',
      '',
      'JYBADKKK',
      '',
    ),
  ],
  EE: [
    bank(
      'Swedbank Estonia',
      '+372 613 1606',
      'Liivalaia 8, Tallinn, Estonia',
      '',
      '',
      'https://www.swedbank.ee',
      'info@swedbank.ee',
      '',
      '',
      '',
      '',
      'HABAEE2X',
      '',
    ),
    bank(
      'SEB Estonia',
      '+372 665 5100',
      'Tornimae 2, Tallinn, Estonia',
      '',
      '',
      'https://www.seb.ee',
      'info@seb.ee',
      '',
      '',
      '',
      '',
      'EEUHEE2X',
      '',
    ),
    bank(
      'LHV Bank',
      '+372 680 0400',
      'Tartu mnt 2, Tallinn, Estonia',
      '',
      '',
      'https://www.lhv.ee',
      'info@lhv.ee',
      '',
      '',
      '',
      '',
      'LHVBEE22',
      '',
    ),
  ],
  FI: [
    bank(
      'Nordea Finland',
      '+358 200 70 000',
      'Satamaradankatu 5, 00020 Nordea, Helsinki, Finland',
      'https://apps.apple.com/fi/app/nordea-mobile/id429047995',
      'https://play.google.com/store/apps/details?id=com.nordea.mobilebank',
      'https://www.nordea.fi',
      'asiakaspalvelu@nordea.fi',
      'https://twitter.com/Nordea',
      'https://www.instagram.com/nordea/',
      'https://www.linkedin.com/company/nordea/',
      '',
      'NDEAFIHH',
      'https://developer.nordea.com',
    ),
    bank(
      'OP Financial Group',
      '+358 10 252 000',
      'Gebhardinaukio 1, 00510 Helsinki, Finland',
      'https://apps.apple.com/fi/app/op-mobiili/id429047995',
      'https://play.google.com/store/apps/details?id=fi.op.android.opmobiili',
      'https://www.op.fi',
      'asiakaspalvelu@op.fi',
      'https://twitter.com/OPFinancialGrp',
      'https://www.instagram.com/opfinancialgroup/',
      'https://www.linkedin.com/company/op-financial-group/',
      '',
      'OKOYFIHH',
      'https://developer.op.fi',
    ),
    bank(
      'Aktia Bank',
      '+358 10 247 000',
      'Arkadiankatu 4-6, 00100 Helsinki, Finland',
      'https://apps.apple.com/fi/app/aktia-mobiili/id429047995',
      'https://play.google.com/store/apps/details?id=fi.aktia.mobilebank',
      'https://www.aktia.fi',
      'asiakaspalvelu@aktia.fi',
      'https://twitter.com/AktiaPankki',
      'https://www.instagram.com/aktiapankki/',
      'https://www.linkedin.com/company/aktia-bank/',
      '',
      'HELSFIHH',
      '',
    ),
  ],
  FR: [
    bank(
      'BNP Paribas',
      '+33 1 42 98 12 34',
      '16 Boulevard des Italiens, 75009 Paris, France',
      'https://apps.apple.com/fr/app/mes-comptes-bnp-paribas/id393156562',
      'https://play.google.com/store/apps/details?id=net.bnpparibas.mescomptes',
      'https://mabanque.bnpparibas',
      'contact@bnpparibas.com',
      'https://twitter.com/bnpparibas',
      'https://www.instagram.com/bnpparibas/',
      'https://www.linkedin.com/company/bnp-paribas/',
      '',
      'BNPAFRPP',
      'https://developers.bnpparibas',
    ),
    bank(
      'Societe Generale',
      '+33 1 42 14 20 00',
      '29 Boulevard Haussmann, 75009 Paris, France',
      'https://apps.apple.com/fr/app/societe-generale/id393156562',
      'https://play.google.com/store/apps/details?id=mobi.societegenerale.mobile.lappli',
      'https://www.societegenerale.fr',
      'contact@societegenerale.com',
      'https://twitter.com/societegenerale',
      'https://www.instagram.com/societegenerale/',
      'https://www.linkedin.com/company/societe-generale/',
      '',
      'SOGEFRPP',
      'https://developer.societegenerale.com',
    ),
    bank(
      'Credit Agricole',
      '+33 1 43 23 52 02',
      '12 Place des Etats-Unis, 92127 Montrouge, France',
      'https://apps.apple.com/fr/app-ma-credit-agricole/id393156562',
      'https://play.google.com/store/apps/details?id=fr.creditagricole.androidapp',
      'https://www.credit-agricole.fr',
      'contact@credit-agricole.com',
      'https://twitter.com/CreditAgricole',
      'https://www.instagram.com/creditagricole/',
      'https://www.linkedin.com/company/credit-agricole/',
      '',
      'AGRIFRPP',
      '',
    ),
  ],
  DE: [
    bank(
      'Deutsche Bank',
      '+49 69 910 10000',
      'Taunusanlage 12, 60325 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/deutsche-bank-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=com.db.pwcc.dbmobile',
      'https://www.deutsche-bank.de',
      'kundenservice@db.com',
      'https://twitter.com/DeutscheBank',
      'https://www.instagram.com/deutschebank/',
      'https://www.linkedin.com/company/deutsche-bank/',
      '',
      'DEUTDEFF',
      'https://developer.db.com',
    ),
    bank(
      'Commerzbank',
      '+49 69 136 20',
      'Kaiserplatz, 60261 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/commerzbank-banking/id393156562',
      'https://play.google.com/store/apps/details?id=de.commerzbanking.mobil',
      'https://www.commerzbank.de',
      'kundenservice@commerzbank.de',
      'https://twitter.com/Commerzbank',
      'https://www.instagram.com/commerzbank/',
      'https://www.linkedin.com/company/commerzbank/',
      '',
      'COBADEFF',
      '',
    ),
    bank(
      'DZ Bank',
      '+49 69 7447 0',
      'Platz der Republik, 60265 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/dz-bank/id393156562',
      '',
      'https://www.dzbank.de',
      'info@dzbank.de',
      'https://twitter.com/DZ_BANK',
      'https://www.instagram.com/dzbank/',
      'https://www.linkedin.com/company/dz-bank/',
      '',
      'GENODEFF',
      '',
    ),
  ],
  GR: [
    bank(
      'National Bank of Greece',
      '+30 210 334 1000',
      '86 Aiolou Street, Athens, Greece',
      '',
      '',
      'https://www.nbg.gr',
      'info@nbg.gr',
      '',
      '',
      '',
      '',
      'ETHNGRAA',
      '',
    ),
    bank(
      'Piraeus Bank',
      '+30 210 328 8000',
      '4 Amerikis St, Athens, Greece',
      '',
      '',
      'https://www.piraeusbank.gr',
      'customerservice@piraeusbank.gr',
      '',
      '',
      '',
      '',
      'PIRBGRAA',
      '',
    ),
    bank(
      'Eurobank Greece',
      '+30 210 955 5000',
      '8 Othonos St, Athens, Greece',
      '',
      '',
      'https://www.eurobank.gr',
      'info@eurobank.gr',
      '',
      '',
      '',
      '',
      'ERBKGRAA',
      '',
    ),
  ],
  HU: [
    bank(
      'OTP Bank',
      '+36 1 366 6666',
      'Nador utca 16, Budapest, Hungary',
      '',
      '',
      'https://www.otpbank.hu',
      'info@otpbank.hu',
      '',
      '',
      '',
      '',
      'OTPVHUHB',
      '',
    ),
    bank(
      'K&H Bank',
      '+36 1 328 9000',
      'Lechner Odon fasor 9, Budapest, Hungary',
      '',
      '',
      'https://www.kh.hu',
      'bank@kh.hu',
      '',
      '',
      '',
      '',
      'OKHBHUHB',
      '',
    ),
    bank(
      'Erste Bank Hungary',
      '+36 1 298 0222',
      'Nefelejcs utca 24, Budapest, Hungary',
      '',
      '',
      'https://www.erstebank.hu',
      'erste@erstebank.hu',
      '',
      '',
      '',
      '',
      'GIBAHUHB',
      '',
    ),
  ],
  IE: [
    bank(
      'Bank of Ireland',
      '+353 1 611 3333',
      '40 Mespil Road, Dublin 4, Ireland',
      'https://apps.apple.com/ie/app/bank-of-ireland-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=com.bankofireland.mobilebanking',
      'https://www.bankofireland.com',
      'customerservice@bankofireland.com',
      'https://twitter.com/bankofireland',
      'https://www.instagram.com/bankofireland/',
      'https://www.linkedin.com/company/bank-of-ireland/',
      '',
      'BOFIIE2D',
      'https://developer.bankofireland.com',
    ),
    bank(
      'Allied Irish Banks',
      '+353 1 660 0311',
      '10 Molesworth Street, Dublin 2, Ireland',
      'https://apps.apple.com/ie/app/aib-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=com.aib.mobilebanking',
      'https://www.aib.ie',
      'customerservice@aib.ie',
      'https://twitter.com/AskAIB',
      'https://www.instagram.com/aibireland/',
      'https://www.linkedin.com/company/aib/',
      '',
      'AIBKIE2D',
      'https://developer.aib.ie',
    ),
    bank(
      'Permanent TSB',
      '+353 1 212 4100',
      '56-59 St Stephens Green, Dublin 2, Ireland',
      'https://apps.apple.com/ie/app/open24-mobile-banking/id393156562',
      'https://play.google.com/store/apps/details?id=ie.ptsb.mobilebanking',
      'https://www.ptsb.ie',
      'customerservice@ptsb.ie',
      'https://twitter.com/AskPTSB',
      'https://www.instagram.com/permanenttsb/',
      'https://www.linkedin.com/company/permanent-tsb/',
      '',
      'IPBSIE2D',
      '',
    ),
  ],
  IT: [
    bank(
      'Intesa Sanpaolo',
      '+39 800 303 303',
      'Piazza San Carlo 156, Turin, Italy',
      '',
      '',
      'https://www.intesasanpaolo.com',
      'assistenza@intesasanpaolo.com',
      '',
      '',
      '',
      '',
      'BCITITMM',
      '',
    ),
    bank(
      'UniCredit',
      '+39 800 57 57 57',
      'Piazza Gae Aulenti 3, Milan, Italy',
      '',
      '',
      'https://www.unicredit.it',
      'info@unicredit.eu',
      '',
      '',
      '',
      '',
      'UNCRITMM',
      '',
    ),
    bank(
      'Banco BPM',
      '+39 800 024 024',
      'Piazza Meda 4, Milan, Italy',
      '',
      '',
      'https://www.bancobpm.it',
      'contattaci@bancobpm.it',
      '',
      '',
      '',
      '',
      'BAPPIT22',
      '',
    ),
  ],
  LV: [
    bank(
      'Swedbank Latvia',
      '+371 6744 4444',
      'Balasta dambis 15, Riga, Latvia',
      '',
      '',
      'https://www.swedbank.lv',
      'info@swedbank.lv',
      '',
      '',
      '',
      '',
      'HABALV22',
      '',
    ),
    bank(
      'SEB Latvia',
      '+371 2666 8777',
      'Meistaru iela 1, Valdlauci, Latvia',
      '',
      '',
      'https://www.seb.lv',
      'seb@seb.lv',
      '',
      '',
      '',
      '',
      'UNLALV2X',
      '',
    ),
    bank(
      'Citadele Banka',
      '+371 6701 0000',
      'Republikas laukums 2A, Riga, Latvia',
      '',
      '',
      'https://www.citadele.lv',
      'info@citadele.lv',
      '',
      '',
      '',
      '',
      'PARXLV22',
      '',
    ),
  ],
  LT: [
    bank(
      'Swedbank Lithuania',
      '+370 5 268 4444',
      'Konstitucijos pr. 20A, Vilnius, Lithuania',
      '',
      '',
      'https://www.swedbank.lt',
      'info@swedbank.lt',
      '',
      '',
      '',
      '',
      'HABALT22',
      '',
    ),
    bank(
      'SEB Lithuania',
      '+370 5 268 2800',
      'Konstitucijos pr. 24, Vilnius, Lithuania',
      '',
      '',
      'https://www.seb.lt',
      'info@seb.lt',
      '',
      '',
      '',
      '',
      'CBVILT2X',
      '',
    ),
    bank(
      'Siauliu Bankas',
      '+370 5 203 2233',
      'Tilzes g. 149, Siauliai, Lithuania',
      '',
      '',
      'https://www.sb.lt',
      'info@sb.lt',
      '',
      '',
      '',
      '',
      'CBSBLT26',
      '',
    ),
  ],
  LU: [
    bank(
      'Spuerkeess',
      '+352 4015 1',
      '1 Place de Metz, Luxembourg City, Luxembourg',
      '',
      '',
      'https://www.spuerkeess.lu',
      'spuerkeess@spuerkeess.lu',
      '',
      '',
      '',
      '',
      'BCEELULL',
      '',
    ),
    bank(
      'BGL BNP Paribas',
      '+352 4242 2000',
      '50 Avenue J F Kennedy, Luxembourg City, Luxembourg',
      '',
      '',
      'https://www.bgl.lu',
      'contact@bgl.lu',
      '',
      '',
      '',
      '',
      'BGLLLULL',
      '',
    ),
    bank(
      'Banque Internationale a Luxembourg',
      '+352 4590 1',
      '69 Route d\'Esch, Luxembourg City, Luxembourg',
      '',
      '',
      'https://www.bil.com',
      'info@bil.com',
      '',
      '',
      '',
      '',
      'BILLLULL',
      '',
    ),
  ],
  MT: [
    bank(
      'Bank of Valletta',
      '+356 2275 1732',
      '58 Zachary Street, Valletta, Malta',
      '',
      '',
      'https://www.bov.com',
      'customercare@bov.com',
      '',
      '',
      '',
      '',
      'VALLMTMT',
      '',
    ),
    bank(
      'HSBC Bank Malta',
      '+356 2380 2380',
      '116 Archbishop Street, Valletta, Malta',
      '',
      '',
      'https://www.hsbc.com.mt',
      'customerservice@hsbc.com.mt',
      '',
      '',
      '',
      '',
      'MMEBMTMT',
      '',
    ),
    bank(
      'APS Bank',
      '+356 2122 6644',
      'APS Centre, Tower Street, Birkirkara, Malta',
      '',
      '',
      'https://www.apsbank.com.mt',
      'info@apsbank.com.mt',
      '',
      '',
      '',
      '',
      'APSBMTMT',
      '',
    ),
  ],
  NL: [
    bank(
      'ING Bank Netherlands',
      '+31 20 563 9111',
      'Bijlmerdreef 106, 1102 CT Amsterdam, Netherlands',
      'https://apps.apple.com/nl/app/ing-bankieren/id474807486',
      'https://play.google.com/store/apps/details?id=com.ing.mobile',
      'https://www.ing.nl',
      'klantenservice@ing.nl',
      'https://twitter.com/INGnl',
      'https://www.instagram.com/ingnl/',
      'https://www.linkedin.com/company/ing/',
      '',
      'INGBNL2A',
      'https://developer.ing.com',
    ),
    bank(
      'Rabobank',
      '+31 30 216 0000',
      'Croeselaan 18, 3521 CB Utrecht, Netherlands',
      'https://apps.apple.com/nl/app/rabobank-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=nl.rabobank.rabomobile',
      'https://www.rabobank.nl',
      'info@rabobank.nl',
      'https://twitter.com/Rabobank',
      'https://www.instagram.com/rabobank/',
      'https://www.linkedin.com/company/rabobank/',
      '',
      'RABONL2U',
      'https://developer.rabobank.nl',
    ),
    bank(
      'ABN AMRO',
      '+31 20 628 9900',
      'Gustav Mahlerlaan 10, 1082 PP Amsterdam, Netherlands',
      'https://apps.apple.com/nl/app/abn-amro-mobile-banking/id393156562',
      'https://play.google.com/store/apps/details?id=com.abnamro.nl.mobile.payments',
      'https://www.abnamro.nl',
      'klantenservice@abnamro.nl',
      'https://twitter.com/abnamro',
      'https://www.instagram.com/abnamro/',
      'https://www.linkedin.com/company/abn-amro/',
      '',
      'ABNANL2A',
      'https://developer.abnamro.com',
    ),
  ],
  PL: [
    bank(
      'PKO Bank Polski',
      '+48 22 521 1900',
      'ul. Pulawska 15, Warsaw, Poland',
      '',
      '',
      'https://www.pkobp.pl',
      'kontakt@pkobp.pl',
      '',
      '',
      '',
      '',
      'BPKOPLPW',
      '',
    ),
    bank(
      'Bank Pekao',
      '+48 22 591 2323',
      'ul. Zurawia 32/34, Warsaw, Poland',
      '',
      '',
      'https://www.pekao.com.pl',
      'info@pekao.com.pl',
      '',
      '',
      '',
      '',
      'PKOPPLPW',
      '',
    ),
    bank(
      'Santander Bank Polska',
      '+48 61 81 1 9999',
      'Aleja Jana Pawla II 17, Warsaw, Poland',
      '',
      '',
      'https://www.santander.pl',
      'kontakt@santander.pl',
      '',
      '',
      '',
      '',
      'WBKPPLPP',
      '',
    ),
  ],
  PT: [
    bank(
      'Caixa Geral de Depositos',
      '+351 217 900 790',
      'Av. Joao XXI 63, Lisbon, Portugal',
      '',
      '',
      'https://www.cgd.pt',
      'caixadirecta@cgd.pt',
      '',
      '',
      '',
      '',
      'CGDIPTPL',
      '',
    ),
    bank(
      'Millennium bcp',
      '+351 210 040 424',
      'Praca D. Joao I 28, Porto, Portugal',
      '',
      '',
      'https://ind.millenniumbcp.pt',
      'indicador@millenniumbcp.pt',
      '',
      '',
      '',
      '',
      'BCOMPTPL',
      '',
    ),
    bank(
      'Novo Banco',
      '+351 213 501 000',
      'Av. da Liberdade 195, Lisbon, Portugal',
      '',
      '',
      'https://www.novobanco.pt',
      'cliente@novobanco.pt',
      '',
      '',
      '',
      '',
      'BESCPTPL',
      '',
    ),
  ],
  RO: [
    bank(
      'Banca Transilvania',
      '+40 264 308 028',
      'Calea Dorobantilor 30-36, Cluj-Napoca, Romania',
      '',
      '',
      'https://www.bancatransilvania.ro',
      'contact@btrl.ro',
      '',
      '',
      '',
      '',
      'BTRLRO22',
      '',
    ),
    bank(
      'Banca Comerciala Romana',
      '+40 21 407 4200',
      'Bd. Regina Elisabeta 5, Bucharest, Romania',
      '',
      '',
      'https://www.bcr.ro',
      'contact.center@bcr.ro',
      '',
      '',
      '',
      '',
      'RNCBROBU',
      '',
    ),
    bank(
      'BRD Groupe Societe Generale',
      '+40 21 302 6161',
      'Bd. Ion Mihalache 1-7, Bucharest, Romania',
      '',
      '',
      'https://www.brd.ro',
      'mybrdcontact@brd.ro',
      '',
      '',
      '',
      '',
      'BRDEROBU',
      '',
    ),
  ],
  SK: [
    bank(
      'Slovenska sporitelna',
      '+421 2 4862 1111',
      'Tomasikova 48, Bratislava, Slovakia',
      '',
      '',
      'https://www.slsp.sk',
      'info@slsp.sk',
      '',
      '',
      '',
      '',
      'GIBASKBX',
      '',
    ),
    bank(
      'VUB Banka',
      '+421 2 4855 5970',
      'Mlynske nivy 1, Bratislava, Slovakia',
      '',
      '',
      'https://www.vub.sk',
      'kontakt@vub.sk',
      '',
      '',
      '',
      '',
      'SUBASKBX',
      '',
    ),
    bank(
      'Tatra banka',
      '+421 2 5919 1000',
      'Hodzovo namestie 3, Bratislava, Slovakia',
      '',
      '',
      'https://www.tatrabanka.sk',
      'kontakt@tatrabanka.sk',
      '',
      '',
      '',
      '',
      'TATRSKBX',
      '',
    ),
  ],
  SI: [
    bank(
      'NLB d.d.',
      '+386 1 477 2000',
      'Trg republike 2, Ljubljana, Slovenia',
      '',
      '',
      'https://www.nlb.si',
      'info@nlb.si',
      '',
      '',
      '',
      '',
      'LJBASI2X',
      '',
    ),
    bank(
      'NKBM',
      '+386 2 229 2290',
      'Ulica Vita Kraigherja 4, Maribor, Slovenia',
      '',
      '',
      'https://www.nkbm.si',
      'info@nkbm.si',
      '',
      '',
      '',
      '',
      'KBMASI2X',
      '',
    ),
    bank(
      'SKB Banka',
      '+386 1 471 5555',
      'Ajdovscina 4, Ljubljana, Slovenia',
      '',
      '',
      'https://www.skb.si',
      'kontakt@skb.si',
      '',
      '',
      '',
      '',
      'SKBASI2X',
      '',
    ),
  ],
  ES: [
    bank(
      'Banco Santander',
      '+34 91 276 0000',
      'Paseo de Pereda 9-12, 39004 Santander, Spain',
      'https://apps.apple.com/es/app/santander/id393156562',
      'https://play.google.com/store/apps/details?id=es.bancosantander.apps',
      'https://www.bancosantander.es',
      'atencioncliente@santander.com',
      'https://twitter.com/bancosantander',
      'https://www.instagram.com/bancosantander/',
      'https://www.linkedin.com/company/banco-santander/',
      '',
      'BSCHESMM',
      'https://developer.santander.com',
    ),
    bank(
      'BBVA',
      '+34 91 537 6000',
      'Plaza de San Nicolas 4, 48005 Bilbao, Spain',
      'https://apps.apple.com/es/app/bbva-espana/id393156562',
      'https://play.google.com/store/apps/details?id=com.bbva.bbvacontigo',
      'https://www.bbva.es',
      'atencion.cliente@bbva.com',
      'https://twitter.com/bbva',
      'https://www.instagram.com/bbva/',
      'https://www.linkedin.com/company/bbva/',
      '',
      'BBVAESMM',
      'https://developers.bbva.com',
    ),
    bank(
      'CaixaBank',
      '+34 93 404 6000',
      'Avenida Diagonal 621-639, 08028 Barcelona, Spain',
      'https://apps.apple.com/es/app/caixabank/id393156562',
      'https://play.google.com/store/apps/details?id=es.lacaixa.mobile.android.newwapicon',
      'https://www.caixabank.es',
      'info@caixabank.com',
      'https://twitter.com/CaixaBank',
      'https://www.instagram.com/caixabank/',
      'https://www.linkedin.com/company/caixabank/',
      '',
      'CAIXESBB',
      '',
    ),
  ],
  SE: [
    bank(
      'Swedbank',
      '+46 771 22 11 22',
      'Landsvägen 40, 172 63 Sundbyberg, Sweden',
      'https://apps.apple.com/se/app/swedbank/id393156562',
      'https://play.google.com/store/apps/details?id=se.swedbank.mobil',
      'https://www.swedbank.se',
      'kundcenter@swedbank.se',
      'https://twitter.com/Swedbank',
      'https://www.instagram.com/swedbank/',
      'https://www.linkedin.com/company/swedbank/',
      '',
      'SWEDSESS',
      'https://developer.swedbank.com',
    ),
    bank(
      'SEB',
      '+46 771 365 365',
      '106 40 Stockholm, Sweden',
      'https://apps.apple.com/se/app/seb/id393156562',
      'https://play.google.com/store/apps/details?id=se.seb.privatkonto',
      'https://www.seb.se',
      'kundservice@seb.se',
      'https://twitter.com/SEB',
      'https://www.instagram.com/seb/',
      'https://www.linkedin.com/company/seb/',
      '',
      'ESSESESS',
      'https://developer.sebgroup.com',
    ),
    bank(
      'Handelsbanken',
      '+46 8 701 10 00',
      'Kungstradgardsgatan 2, 106 70 Stockholm, Sweden',
      'https://apps.apple.com/se/app/handelsbanken/id393156562',
      'https://play.google.com/store/apps/details?id=se.handelsbanken.mobilebank',
      'https://www.handelsbanken.se',
      'kundservice@handelsbanken.se',
      'https://twitter.com/Handelsbanken',
      'https://www.instagram.com/handelsbanken/',
      'https://www.linkedin.com/company/handelsbanken/',
      '',
      'HANDSESS',
      '',
    ),
  ],
}
