import type { EuMemberIsoCode } from './euMemberIsoCodes'
import type { SecuritiesExchangeCommission } from './types'

function sec(
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): SecuritiesExchangeCommission {
  return { name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

/**
 * Securities and exchange / capital-markets commission by ISO 3166-1 alpha-2 for European Union
 * member states in this module (informational; verify URLs, handles, forms portals, and API
 * bases before production use). Self-contained — no imports from other alliance modules.
 * All EU national competent authorities operate under the European Securities and Markets
 * Authority (ESMA) framework. `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.esma.europa.eu/about-esma/organisation/ncas
 */
export const EU_SECURITIES_EXCHANGE_COMMISSIONS: Record<
  EuMemberIsoCode,
  SecuritiesExchangeCommission
> = {
  AT: sec(
    'Financial Market Authority Austria (FMA)',
    'https://www.fma.gv.at',
    'fma@fma.gv.at',
    'https://x.com/FMA_Austria',
    'https://www.linkedin.com/company/fma-österreich/',
    'https://www.fma.gv.at',
  ),
  BE: sec(
    'Financial Services and Markets Authority Belgium (FSMA)',
    'https://www.fsma.be',
    'info@fsma.be',
    'https://x.com/FSMAbelgique',
    'https://www.linkedin.com/company/fsma/',
    'https://www.fsma.be',
  ),
  BG: sec(
    'Financial Supervision Commission Bulgaria (FSC Bulgaria)',
    'https://www.fsc.bg',
    'fsc@fsc.bg',
    '',
    'https://www.linkedin.com/company/financial-supervision-commission-bulgaria/',
    'https://www.fsc.bg',
  ),
  HR: sec(
    'Croatian Financial Services Supervisory Agency (HANFA)',
    'https://www.hanfa.hr',
    'hanfa@hanfa.hr',
    '',
    'https://www.linkedin.com/company/hanfa/',
    'https://www.hanfa.hr',
  ),
  CY: sec(
    'Cyprus Securities and Exchange Commission (CySEC)',
    'https://www.cysec.gov.cy',
    'cysec@cysec.gov.cy',
    'https://x.com/CySEC_official',
    'https://www.linkedin.com/company/cysec/',
    'https://www.cysec.gov.cy',
  ),
  CZ: sec(
    'Czech National Bank (CNB) — capital-markets supervision',
    'https://www.cnb.cz',
    'info@cnb.cz',
    '',
    'https://www.linkedin.com/company/czech-national-bank/',
    'https://www.cnb.cz',
  ),
  DK: sec(
    'Danish Financial Supervisory Authority (Finanstilsynet)',
    'https://www.finanstilsynet.dk',
    'finanstilsynet@finanstilsynet.dk',
    'https://x.com/Finanstilsynet',
    'https://www.linkedin.com/company/finanstilsynet/',
    'https://www.finanstilsynet.dk',
  ),
  EE: sec(
    'Estonian Financial Supervision and Resolution Authority (Finantsinspektsioon)',
    'https://www.fi.ee',
    'info@fi.ee',
    '',
    'https://www.linkedin.com/company/finantsinspektsioon/',
    'https://www.fi.ee',
  ),
  FI: sec(
    'Finnish Financial Supervisory Authority (Finanssivalvonta / FIN-FSA)',
    'https://www.finanssivalvonta.fi',
    'kirjaamo@finanssivalvonta.fi',
    'https://x.com/Finanssivalvonta',
    'https://www.linkedin.com/company/finanssivalvonta/',
    'https://www.finanssivalvonta.fi',
  ),
  FR: sec(
    'Autorité des marchés financiers (AMF France)',
    'https://www.amf-france.org',
    'relationsemet@amf-france.org',
    'https://x.com/AMF_actu',
    'https://www.linkedin.com/company/autorité-des-marchés-financiers-amf/',
    'https://www.amf-france.org',
  ),
  DE: sec(
    'Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin)',
    'https://www.bafin.de',
    'poststelle@bafin.de',
    'https://x.com/BaFin_de',
    'https://www.linkedin.com/company/bafin/',
    'https://www.bafin.de',
  ),
  GR: sec(
    'Hellenic Capital Market Commission (HCMC)',
    'https://www.hcmc.gr',
    'info@hcmc.gr',
    '',
    'https://www.linkedin.com/company/hellenic-capital-market-commission/',
    'https://www.hcmc.gr',
  ),
  HU: sec(
    'Magyar Nemzeti Bank (MNB) — financial markets supervision',
    'https://www.mnb.hu',
    'info@mnb.hu',
    'https://x.com/mnbhu',
    'https://www.linkedin.com/company/mnb-magyar-nemzeti-bank/',
    'https://www.mnb.hu',
  ),
  IE: sec(
    'Central Bank of Ireland — securities supervision',
    'https://www.centralbank.ie',
    'enquiries@centralbank.ie',
    'https://x.com/centralbankie',
    'https://www.linkedin.com/company/central-bank-of-ireland/',
    'https://www.centralbank.ie',
  ),
  IT: sec(
    'Commissione Nazionale per le Società e la Borsa (CONSOB)',
    'https://www.consob.it',
    'consob@consob.it',
    'https://x.com/consob_it',
    'https://www.linkedin.com/company/consob/',
    'https://www.consob.it',
  ),
  LV: sec(
    'Financial and Capital Market Commission Latvia (FKTK)',
    'https://www.fktk.lv',
    'fktk@fktk.lv',
    '',
    'https://www.linkedin.com/company/financial-and-capital-market-commission-fktk/',
    'https://www.fktk.lv',
  ),
  LT: sec(
    'Bank of Lithuania — capital-markets supervision',
    'https://www.lb.lt',
    'info@lb.lt',
    'https://x.com/BankofLithuania',
    'https://www.linkedin.com/company/bank-of-lithuania/',
    'https://www.lb.lt',
  ),
  LU: sec(
    'Commission de Surveillance du Secteur Financier (CSSF Luxembourg)',
    'https://www.cssf.lu',
    'info@cssf.lu',
    'https://x.com/CSSF_Luxembourg',
    'https://www.linkedin.com/company/cssf/',
    'https://www.cssf.lu',
  ),
  MT: sec(
    'Malta Financial Services Authority (MFSA)',
    'https://www.mfsa.mt',
    'communications@mfsa.mt',
    'https://x.com/MFSAMalta',
    'https://www.linkedin.com/company/malta-financial-services-authority/',
    'https://www.mfsa.mt',
  ),
  NL: sec(
    'Autoriteit Financiële Markten (AFM Netherlands)',
    'https://www.afm.nl',
    'info@afm.nl',
    'https://x.com/AFM_NL',
    'https://www.linkedin.com/company/autoriteit-financiële-markten/',
    'https://www.afm.nl',
  ),
  PL: sec(
    'Polish Financial Supervision Authority (KNF)',
    'https://www.knf.gov.pl',
    'knf@knf.gov.pl',
    'https://x.com/KNFpl',
    'https://www.linkedin.com/company/urząd-komisji-nadzoru-finansowego/',
    'https://www.knf.gov.pl',
  ),
  PT: sec(
    'Comissão do Mercado de Valores Mobiliários (CMVM Portugal)',
    'https://www.cmvm.pt',
    'cmvm@cmvm.pt',
    'https://x.com/CMVM_pt',
    'https://www.linkedin.com/company/cmvm/',
    'https://www.cmvm.pt',
  ),
  RO: sec(
    'Financial Supervisory Authority Romania (ASF)',
    'https://www.asfromania.ro',
    'office@asfromania.ro',
    'https://x.com/ASF_Romania',
    'https://www.linkedin.com/company/asf-romania/',
    'https://www.asfromania.ro',
  ),
  SK: sec(
    'National Bank of Slovakia (NBS) — capital-markets supervision',
    'https://www.nbs.sk',
    'info@nbs.sk',
    '',
    'https://www.linkedin.com/company/national-bank-of-slovakia/',
    'https://www.nbs.sk',
  ),
  SI: sec(
    'Securities Market Agency Slovenia (ATVP)',
    'https://www.atvp.si',
    'atvp@atvp.si',
    '',
    '',
    'https://www.atvp.si',
  ),
  ES: sec(
    'Comisión Nacional del Mercado de Valores (CNMV Spain)',
    'https://www.cnmv.es',
    'cnmv@cnmv.es',
    'https://x.com/cnmv_es',
    'https://www.linkedin.com/company/cnmv/',
    'https://www.cnmv.es',
  ),
  SE: sec(
    'Finansinspektionen (FI Sweden)',
    'https://www.fi.se',
    'finansinspektionen@fi.se',
    'https://x.com/FI_nyheter',
    'https://www.linkedin.com/company/finansinspektionen/',
    'https://www.fi.se',
  ),
}
