import type { NationalBankingInstitution } from './types'
import type { AmuMemberIsoCode } from './amuMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per AMU founding member.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const AMU_NATIONAL_BANKING_INSTITUTIONS: Record<
  AmuMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  DZ: [
    bank(
      'Banque Exterieure d Algerie (BEA)',
      '+213 21 98 02 98',
      '11 Rue Colonel Amirouche, Algiers, Algeria',
      '',
      '',
      'https://www.bea.dz/',
      'contact@bea.dz',
      '',
      '',
      'https://www.linkedin.com/company/bea-algerie/',
      '',
      '',
      '',
    ),
    bank(
      'Banque Nationale d Algerie (BNA)',
      '+213 21 63 56 56',
      '8 Boulevard Ernesto Che Guevara, Algiers, Algeria',
      '',
      '',
      'https://www.bna.dz/',
      'contact@bna.dz',
      '',
      '',
      'https://www.linkedin.com/company/banque-nationale-d-alg%C3%A9rie/',
      '',
      '',
      '',
    ),
    bank(
      'Credit Populaire d Algerie (CPA)',
      '+213 21 63 55 55',
      '2 Boulevard Colonel Amirouche, Algiers, Algeria',
      '',
      '',
      'https://www.cpa-bank.dz/',
      'contact@cpa-bank.dz',
      '',
      '',
      'https://www.linkedin.com/company/credit-populaire-d-algerie/',
      '',
      '',
      '',
    ),
  ],
  LY: [
    bank(
      'Wahda Bank',
      '+218 21 333 5511',
      'Omar Mukhtar Street, Tripoli, Libya',
      '',
      '',
      'https://wahdabank.ly/',
      'info@wahdabank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Jumhouria Bank',
      '+218 21 360 2000',
      'Al Fatah Street, Tripoli, Libya',
      '',
      '',
      'https://www.jbank.ly/',
      'info@jbank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'National Commercial Bank Libya',
      '+218 21 444 9200',
      'September 1st Street, Tripoli, Libya',
      '',
      '',
      'https://www.ncb.ly/',
      'info@ncb.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  MR: [
    bank(
      'Banque Mauritanienne pour le Commerce International (BMCI)',
      '+222 45 29 11 22',
      'Avenue Gamal Abdel Nasser, Nouakchott, Mauritania',
      '',
      '',
      'https://www.bmci.mr/',
      'contact@bmci.mr',
      '',
      '',
      '',
      '',
      'BMCIMRMR',
      '',
    ),
    bank(
      'Banque El Amana',
      '+222 45 25 55 55',
      'Tevragh Zeina, Nouakchott, Mauritania',
      '',
      '',
      'https://www.elamana-bank.mr/',
      'info@elamana-bank.mr',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Societe Generale Mauritanie',
      '+222 45 29 33 33',
      'Ilot K, Nouakchott, Mauritania',
      '',
      '',
      'https://www.societegenerale.mr/',
      'contact@societegenerale.mr',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  MA: [
    bank(
      'Attijariwafa bank',
      '+212 5 22 58 88 88',
      '2 Boulevard Moulay Youssef, Casablanca, Morocco',
      '',
      '',
      'https://www.attijariwafabank.com/',
      'contact@attijariwafa.com',
      '',
      '',
      'https://www.linkedin.com/company/attijariwafa-bank/',
      '',
      'BCMAMAMC',
      '',
    ),
    bank(
      'Banque Populaire du Maroc',
      '+212 5 22 20 25 25',
      '101 Boulevard Mohamed Zerktouni, Casablanca, Morocco',
      '',
      '',
      'https://www.gbp.ma/',
      'relationclient@gbp.ma',
      '',
      '',
      'https://www.linkedin.com/company/banque-populaire-maroc/',
      '',
      'BCPOMAMC',
      '',
    ),
    bank(
      'Bank of Africa Maroc',
      '+212 5 22 46 90 00',
      '140 Avenue Hassan II, Casablanca, Morocco',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.bankofafrica.ma/',
      'relationclient@bankofafrica.ma',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      'BMCEMAMC',
      '',
    ),
  ],
  TN: [
    bank(
      'Banque Internationale Arabe de Tunisie (BIAT)',
      '+216 71 155 000',
      '70-72 Avenue Habib Bourguiba, Tunis, Tunisia',
      '',
      '',
      'https://www.biat.com.tn/',
      'contact@biat.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/biat/',
      '',
      'BIATTNTT',
      '',
    ),
    bank(
      'Amen Bank',
      '+216 71 148 000',
      'Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.amenbank.com.tn/',
      'relationclientele@amenbank.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/amen-bank/',
      '',
      'CFCTTNTT',
      '',
    ),
    bank(
      'BH Bank',
      '+216 71 126 000',
      '18 Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.bhbank.tn/',
      'contact@bhbank.tn',
      '',
      '',
      'https://www.linkedin.com/company/bh-bank/',
      '',
      'BHBKTNTT',
      '',
    ),
  ],
}
