import type { CorporationFormationOffice } from './types'
import type { GccMemberIsoCode } from './gccMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per GCC member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const GCC_CORPORATION_FORMATION_OFFICES: Record<GccMemberIsoCode, CorporationFormationOffice> = {
  BH:   office(
    'Sijilat (Ministry of Industry and Commerce Bahrain)',
    '+973 1757 7777',
    'Bahrain Financial Harbour, Manama, Bahrain',
    'https://www.sijilat.bh',
    'info@moic.gov.bh',
    '',
    '',
    '',
    'https://www.sijilat.bh',
    'https://www.bahrain.bh/wps/portal/en/BNP/HomeNationalPortal/ContentDetailsPage/!ut/p/z1',
    'Commercial Registration (CR) Number',
  ),
  KW:   office(
    'Kuwait Business Center (Ministry of Commerce and Industry)',
    '+965 2248 0000',
    'Kuwait City, Kuwait',
    'https://www.moci.gov.kw',
    '',
    '',
    '',
    '',
    'https://e.gov.kw/sites/kgoenglish/Pages/eServices/MOCI/CommercialLicensing.aspx',
    'https://e.gov.kw/sites/kgoenglish/Pages/Services/MOCI/CommercialLicense.aspx',
    'Commercial License Number',
  ),
  OM:   office(
    'Invest Easy (Ministry of Commerce, Industry and Investment Promotion)',
    '+968 800 77770',
    'Muscat, Oman',
    'https://www.business.gov.om',
    '',
    '',
    '',
    '',
    'https://www.business.gov.om',
    'https://www.business.gov.om/portal/en/home',
    'Commercial Registration Number',
  ),
  QA:   office(
    'Single Window (Ministry of Commerce and Industry Qatar)',
    '+974 16001',
    'Doha, Qatar',
    'https://www.moci.gov.qa',
    '',
    '',
    '',
    '',
    'https://www.sw.gov.qa',
    'https://www.moci.gov.qa/en/our-services/business-services/',
    'Commercial Registration (CR) Number',
  ),
  SA:   office(
    'Ministry of Commerce Saudi Arabia (Business Platform)',
    '+966 1900',
    'Riyadh, Saudi Arabia',
    'https://mc.gov.sa',
    '',
    '',
    '',
    '',
    'https://business.sa',
    'https://mc.gov.sa/ar/eservices/Pages/default.aspx',
    'Commercial Registration (CR) Number',
  ),
  AE:   office(
    'UAE National Economic Register (Ministry of Economy)',
    '+971 8001222',
    'Ministry of Economy, Abu Dhabi, United Arab Emirates',
    'https://ner.economy.ae',
    'info@economy.ae',
    '',
    '',
    'https://www.linkedin.com/company/ministry-of-economy-uae/',
    'https://ner.economy.ae',
    'https://u.ae/en/information-and-services/business/starting-a-business',
    'Trade License Number',
  ),
}
