import type { NationalBankingInstitution } from './types'
import type { GccMemberIsoCode } from './gccMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per GCC member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const GCC_NATIONAL_BANKING_INSTITUTIONS: Record<
  GccMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  BH: [
    bank(
      'National Bank of Bahrain',
      '+973 1720 7777',
      'Government Avenue, Manama, Bahrain',
      'https://apps.apple.com/bh/app/nbb-digital-banking/id1536380198',
      'https://play.google.com/store/apps/details?id=com.nbb.digital',
      'https://www.nbbonline.com',
      'info@nbbonline.com',
      'https://twitter.com/NBBOnline',
      'https://www.instagram.com/nbbonline/',
      'https://www.linkedin.com/company/national-bank-of-bahrain/',
      '',
      'NBOBBHBM',
      '',
    ),
    bank(
      'Bank of Bahrain and Kuwait',
      '+973 1720 4444',
      '43 Government Avenue, Manama, Bahrain',
      'https://apps.apple.com/bh/app/bbk-mobile-banking/id620200228',
      'https://play.google.com/store/apps/details?id=com.path.bbkmobilebanking',
      'https://www.bbkonline.com',
      'info@bbkonline.com',
      'https://twitter.com/bbkbank',
      'https://www.instagram.com/bbkbank/',
      'https://www.linkedin.com/company/bbkbank/',
      '',
      'BBKUBHBM',
      '',
    ),
    bank(
      'Ahli United Bank Bahrain',
      '+973 1758 5858',
      'Manama Center, Manama, Bahrain',
      'https://apps.apple.com/bh/app/ahli-united-bank-bh/id1470266993',
      'https://play.google.com/store/apps/details?id=com.aub.mobile.bh',
      'https://www.ahliunited.com/bh',
      'customerservice@ahliunited.com',
      'https://twitter.com/AUB_Bahrain',
      'https://www.instagram.com/aub_bahrain/',
      'https://www.linkedin.com/company/ahli-united-bank/',
      '',
      'AUBBBHBM',
      '',
    ),
  ],
  KW: [
    bank(
      'National Bank of Kuwait',
      '+965 1801801',
      'Abdullah Al-Ahmad Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/nbk-mobile-banking/id380982741',
      'https://play.google.com/store/apps/details?id=com.nbk',
      'https://www.nbk.com',
      'customer.relations@nbk.com',
      'https://twitter.com/NBKPage',
      'https://www.instagram.com/nbkpage/',
      'https://www.linkedin.com/company/national-bank-of-kuwait/',
      '',
      'NBOKKWKW',
      '',
    ),
    bank(
      'Kuwait Finance House',
      '+965 1803333',
      'KFH Tower, Abdullah Al-Mubarak Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/kfhonline/id570920246',
      'https://play.google.com/store/apps/details?id=com.kfh',
      'https://www.kfh.com',
      'contactus@kfh.com',
      'https://twitter.com/KFHGroup',
      'https://www.instagram.com/kfhgroup/',
      'https://www.linkedin.com/company/kuwait-finance-house/',
      '',
      'KFHOKWKW',
      '',
    ),
    bank(
      'Burgan Bank',
      '+965 1804080',
      'Al-Shuhada Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/burgan-bank/id596108948',
      'https://play.google.com/store/apps/details?id=com.burganbank.mobile',
      'https://www.burgan.com',
      'contactus@burgan.com',
      'https://twitter.com/BurganBank',
      'https://www.instagram.com/burganbank/',
      'https://www.linkedin.com/company/burgan-bank/',
      '',
      'BRGNKWKW',
      '',
    ),
  ],
  OM: [
    bank(
      'Bank Muscat',
      '+968 24795555',
      'Airport Heights, Muscat, Oman',
      'https://apps.apple.com/om/app/bank-muscat-mobile-banking/id563857469',
      'https://play.google.com/store/apps/details?id=com.bankmuscat.mbanking',
      'https://www.bankmuscat.com',
      'customercare@bankmuscat.com',
      'https://twitter.com/bankmuscat',
      'https://www.instagram.com/bankmuscat/',
      'https://www.linkedin.com/company/bank-muscat/',
      '',
      'BMUSOMRX',
      '',
    ),
    bank(
      'National Bank of Oman',
      '+968 24770000',
      'Azaiba, Muscat, Oman',
      'https://apps.apple.com/om/app/nbo-mobile-banking/id534479122',
      'https://play.google.com/store/apps/details?id=com.nbo.om',
      'https://www.nbo.om',
      'customercare@nbo.om',
      'https://twitter.com/NBO_Oman',
      'https://www.instagram.com/nbo_oman/',
      'https://www.linkedin.com/company/national-bank-of-oman/',
      '',
      'NBOMOMRX',
      '',
    ),
    bank(
      'Sohar International',
      '+968 24730000',
      'Madinat Al Sultan Qaboos, Muscat, Oman',
      'https://apps.apple.com/om/app/sohar-international/id1455523628',
      'https://play.google.com/store/apps/details?id=com.sohar.mobilebanking',
      'https://www.soharinternational.com',
      'care@soharinternational.com',
      'https://twitter.com/Sohar_Intl',
      'https://www.instagram.com/sohar_intl/',
      'https://www.linkedin.com/company/sohar-international/',
      '',
      'BSHOOMRX',
      '',
    ),
  ],
  QA: [
    bank(
      'Qatar National Bank',
      '+974 44407777',
      'Grand Hamad Street, Doha, Qatar',
      'https://apps.apple.com/qa/app/qnb-mobile/id727432019',
      'https://play.google.com/store/apps/details?id=com.qnb.mobile',
      'https://www.qnb.com',
      'customerservice@qnb.com',
      'https://twitter.com/QNBGroup',
      'https://www.instagram.com/qnbgroup/',
      'https://www.linkedin.com/company/qnbgroup/',
      '',
      'QNBAQAQA',
      '',
    ),
    bank(
      'Commercial Bank of Qatar',
      '+974 44490000',
      'West Bay, Doha, Qatar',
      'https://apps.apple.com/qa/app/commercial-bank-mobile/id576885219',
      'https://play.google.com/store/apps/details?id=com.cbq.mobile',
      'https://www.cbq.qa',
      'customerservice@cbq.qa',
      'https://twitter.com/CBQatar',
      'https://www.instagram.com/cbqatar/',
      'https://www.linkedin.com/company/commercial-bank/',
      '',
      'CBQAQAQA',
      '',
    ),
    bank(
      'Doha Bank',
      '+974 44456000',
      'Doha Bank Tower, West Bay, Doha, Qatar',
      'https://apps.apple.com/qa/app/doha-bank-qatar/id1148136142',
      'https://play.google.com/store/apps/details?id=com.dohabank.mobilebanking',
      'https://www.dohabank.com',
      'customerservice@dohabank.com.qa',
      'https://twitter.com/DohaBank',
      'https://www.instagram.com/dohabank/',
      'https://www.linkedin.com/company/doha-bank/',
      '',
      'DOHBQAQA',
      '',
    ),
  ],
  SA: [
    bank(
      'Saudi National Bank',
      '+966 920001000',
      'King Saud Road, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/alahlimobile/id470322247',
      'https://play.google.com/store/apps/details?id=com.alahli.mobile',
      'https://www.alahli.com',
      'care@alahli.com',
      'https://twitter.com/SNBAlAhli',
      'https://www.instagram.com/snbalahli/',
      'https://www.linkedin.com/company/snbaik/',
      '',
      'NCBKSAJE',
      '',
    ),
    bank(
      'Al Rajhi Bank',
      '+966 920003344',
      'Olaya Street, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/al-rajhi-bank/id563339275',
      'https://play.google.com/store/apps/details?id=com.alrajhibank.mobile',
      'https://www.alrajhibank.com.sa',
      'care@alrajhibank.com.sa',
      'https://twitter.com/AlRajhiBank',
      'https://www.instagram.com/alrajhibank/',
      'https://www.linkedin.com/company/alrajhibank/',
      '',
      'RJHISARI',
      '',
    ),
    bank(
      'Riyad Bank',
      '+966 920002470',
      'King Fahd Road, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/riyad-mobile/id593620831',
      'https://play.google.com/store/apps/details?id=com.riyadbank.mobile',
      'https://www.riyadbank.com',
      'customercare@riyadbank.com',
      'https://twitter.com/RiyadBank',
      'https://www.instagram.com/riyadbank/',
      'https://www.linkedin.com/company/riyad-bank/',
      '',
      'RIBLSARI',
      '',
    ),
  ],
  AE: [
    bank(
      'First Abu Dhabi Bank',
      '+971 2 4996100',
      'Khalifa Business Park, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/fab-mobile/id1023351966',
      'https://play.google.com/store/apps/details?id=com.fab.personal',
      'https://www.bankfab.com',
      'customerservice@bankfab.com',
      'https://twitter.com/FABConnects',
      'https://www.instagram.com/fabconnects/',
      'https://www.linkedin.com/company/first-abu-dhabi-bank-fab/',
      '',
      'NBADAEAA',
      '',
    ),
    bank(
      'Emirates NBD',
      '+971 600540000',
      'Baniyas Road, Deira, Dubai, UAE',
      'https://apps.apple.com/ae/app/emirates-nbd/id455204322',
      'https://play.google.com/store/apps/details?id=com.emberg.mobilebanking',
      'https://www.emiratesnbd.com',
      'customercare@emiratesnbd.com',
      'https://twitter.com/EmiratesNBD_AE',
      'https://www.instagram.com/emiratesnbd/',
      'https://www.linkedin.com/company/emiratesnbd/',
      '',
      'EBILAEAD',
      '',
    ),
    bank(
      'Abu Dhabi Commercial Bank',
      '+971 2 6210090',
      'Sheikh Zayed Street, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/adcb-mobile-banking-app/id453927124',
      'https://play.google.com/store/apps/details?id=com.adcb.mobile.android',
      'https://www.adcb.com',
      'customer.care@adcb.com',
      'https://twitter.com/ADCB',
      'https://www.instagram.com/adcb/',
      'https://www.linkedin.com/company/adcb/',
      '',
      'ADCBAEAA',
      '',
    ),
  ],
}
