import type { CorporationFormationOffice } from './types'
import type { ComesaMemberIsoCode } from './comesaMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per COMESA member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const COMESA_CORPORATION_FORMATION_OFFICES: Record<ComesaMemberIsoCode, CorporationFormationOffice> = {
  DJ:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Djibouti)',
    '+253 21 35 20 00',
    'Plateau du Serpent, BP 2194, Djibouti City, Djibouti',
    'https://www.investindjibouti.dj',
    'contact@investindjibouti.dj',
    '',
    '',
    '',
    'https://www.investindjibouti.dj/creation-dentreprise',
    'https://www.investindjibouti.dj/guide-creation',
    'Numero RCCM',
  ),
  EG:   office(
    'General Authority for Investment and Free Zones (GAFI) - One Stop Shop',
    '+20 2 3537 3333',
    'Salah Salem Road, Nasr City, Cairo, Egypt',
    'https://www.gafi.gov.eg',
    'info@gafi.gov.eg',
    'https://x.com/gafieg',
    '',
    'https://www.linkedin.com/company/gafi-egypt/',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/default.aspx',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/Procedures.aspx',
    'Commercial Register Number (CR Number)',
  ),
  ER:   office(
    'Ministry of Trade and Industry Eritrea - Business Licensing Office',
    '+291 1 120 055',
    'Harnet Avenue, Asmara, Eritrea',
    'https://www.shabait.com/ministry-of-trade-and-industry',
    'moti@e.gov.er',
    '',
    '',
    '',
    'https://www.shabait.com/ministry-of-trade-and-industry',
    '',
    'Business Registration Number',
  ),
  ET:   office(
    'Ministry of Trade and Regional Integration Ethiopia - Business Registration Directorate',
    '+251 11 551 8020',
    'Kirkos Sub City, Addis Ababa, Ethiopia',
    'https://trade.gov.et',
    'info@trade.gov.et',
    '',
    '',
    '',
    'https://etrade.gov.et',
    'https://trade.gov.et/services/business-registration',
    'Trade Registration Number (TRN)',
  ),
  LY:   office(
    'Ministry of Economy and Trade Libya - Commercial Registry Department',
    '+218 21 335 0380',
    'Al-Sikka Road, Tripoli, Libya',
    'https://www.economy.gov.ly',
    'info@economy.gov.ly',
    '',
    '',
    '',
    'https://www.economy.gov.ly/services/commercial-register',
    '',
    'Commercial Registration Number',
  ),
  SD:   office(
    'Commercial Registrar General (Sudan Ministry of Justice)',
    '+249 183 770 920',
    'Ministry of Justice Complex, Khartoum, Sudan',
    'https://moj.gov.sd',
    'registry@moj.gov.sd',
    '',
    '',
    '',
    'https://moj.gov.sd/services/commercial-registration',
    '',
    'Commercial Registration Number',
  ),
  TN:   office(
    'APII Tunisia - Guichet Unique de l\'Industrie',
    '+216 71 792 144',
    '63 Rue de Syrie, 1002 Tunis, Tunisia',
    'https://www.tunisieindustrie.nat.tn',
    'apii@apii.tn',
    '',
    '',
    'https://www.linkedin.com/company/agence-de-promotion-de-l-industrie-et-de-l-innovation/',
    'https://www.tunisieindustrie.nat.tn/fr/home.asp',
    'https://www.tunisieindustrie.nat.tn/fr/doc.asp',
    'Identifiant Unique de l\'Entreprise (RNE)',
  ),
  KM:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Comores)',
    '+269 773 08 08',
    'Avenue de l\'OUA, Moroni, Comoros',
    'https://www.anpi-comores.km',
    'contact@anpi-comores.km',
    '',
    '',
    '',
    'https://www.anpi-comores.km/guichet-unique',
    'https://www.anpi-comores.km/guide-createur',
    'Numero RCCM',
  ),
  MG:   office(
    'Economic Development Board of Madagascar (EDBM) - One Stop Shop',
    '+261 20 22 670 40',
    'Immeuble EDBM, Antaninarenina, Antananarivo, Madagascar',
    'https://edbm.mg',
    'contact@edbm.mg',
    '',
    '',
    'https://www.linkedin.com/company/edbm/',
    'https://edbm.mg/creation-dentreprise',
    'https://edbm.mg/guide-pratique',
    'Numero RCCM',
  ),
  MU:   office(
    'Corporate and Business Registration Department (CBRD Mauritius)',
    '+230 202 0600',
    '7th Floor, SICOM Tower, Wall Street, Ebene, Mauritius',
    'https://companies.govmu.org',
    'companies.registry@govmu.org',
    '',
    '',
    '',
    'https://companies.govmu.org/Pages/Corporate%20and%20Business/Company-Registration.aspx',
    'https://companies.govmu.org/Pages/Guidelines.aspx',
    'Business Registration Number (BRN)',
  ),
  SC:   office(
    'Seychelles Revenue Commission - Registrar General Division',
    '+248 4 282 800',
    'Maison Collet, Francis Rachel Street, Victoria, Seychelles',
    'https://www.src.gov.sc',
    'registrargeneral@src.gov.sc',
    '',
    '',
    '',
    'https://www.src.gov.sc/services/business-registration',
    'https://www.src.gov.sc/checklists-and-forms',
    'Company Registration Number',
  ),
  BI:   office(
    'Agence de Developpement du Burundi (ADB) - Guichet Unique',
    '+257 22 27 90 00',
    'Avenue du Large, Immeuble Old East, Bujumbura, Burundi',
    'https://investburundi.bi',
    'info@investburundi.bi',
    '',
    '',
    '',
    'https://investburundi.bi/guichet-unique',
    'https://investburundi.bi/procedures-de-creation',
    'Numero RCCM',
  ),
  KE:   office(
    'Business Registration Service (BRS Kenya)',
    '+254 20 222 7461',
    'Sheria House, Harambee Avenue, Nairobi, Kenya',
    'https://brs.go.ke',
    'info@brs.go.ke',
    'https://x.com/BRS_Kenya',
    '',
    'https://www.linkedin.com/company/business-registration-service-kenya/',
    'https://brs.go.ke/service/company-registration',
    'https://www.ecitizen.go.ke',
    'Certificate of Incorporation Number',
  ),
  MW:   office(
    'Registrar General Department Malawi',
    '+265 1 770 155',
    'Glyn Jones Road, Ginnery Corner, Blantyre, Malawi',
    'https://www.registrargeneral.gov.mw',
    'registrargeneral@justice.gov.mw',
    '',
    '',
    '',
    'https://www.registrargeneral.gov.mw/company-registration',
    'https://www.registrargeneral.gov.mw/forms-and-fees',
    'Certificate of Incorporation Number',
  ),
  RW:   office(
    'Rwanda Development Board (RDB) - Business Registration',
    '+250 252 587 441',
    'KG 9 Avenue, Nyarutarama, Kigali, Rwanda',
    'https://rdb.rw',
    'info@rdb.rw',
    'https://x.com/RDBrwanda',
    'https://www.instagram.com/visitrwanda_now/',
    'https://www.linkedin.com/company/rwanda-development-board/',
    'https://org.rdb.rw',
    'https://rdb.rw/business/business-registration/',
    'Company Registration Number',
  ),
  UG:   office(
    'Uganda Registration Services Bureau (URSB)',
    '+256 414 233 219',
    'Plot 5 George Street, Georgian House, Kampala, Uganda',
    'https://www.ursb.go.ug',
    'registration@ursb.go.ug',
    'https://x.com/URSBHQ',
    '',
    'https://www.linkedin.com/company/uganda-registration-services-bureau/',
    'https://ursb.go.ug/business-registration/',
    'https://ursb.go.ug/forms-and-fees/',
    'Registration Number',
  ),
  SZ:   office(
    'Eswatini Companies Office (Ministry of Commerce, Industry and Trade)',
    '+268 2404 3200',
    'Lilunga House, Somhlolo Road, Mbabane, Eswatini',
    'https://www.gov.sz/index.php/business/companies-office',
    'companiesoffice@gov.sz',
    '',
    '',
    '',
    'https://www.gov.sz/index.php/business/companies-office',
    'https://www.gov.sz/index.php/business/forms',
    'Company Registration Number',
  ),
  ZM:   office(
    'Patents and Companies Registration Agency (PACRA Zambia)',
    '+260 211 255 127',
    'PACRA Building, Haile Selassie Avenue, Lusaka, Zambia',
    'https://www.pacra.org.zm',
    'info@pacra.org.zm',
    'https://x.com/PacraZm',
    '',
    'https://www.linkedin.com/company/pacra-zambia/',
    'https://portal.pacra.org.zm',
    'https://www.pacra.org.zm/checklists',
    'Company Registration Number',
  ),
  ZW:   office(
    'Deeds, Companies and Intellectual Property Office (DCIP Zimbabwe)',
    '+263 242 794 571',
    '4th Floor, Century House, Corner Nelson Mandela Ave and Angwa St, Harare, Zimbabwe',
    'https://dcip.gov.zw',
    'info@dcip.gov.zw',
    '',
    '',
    '',
    'https://dcip.gov.zw/company-registration',
    'https://dcip.gov.zw/requirements',
    'Company Registration Number',
  ),
  CD:   office(
    'Guichet Unique de Creation d\'Entreprise (GUCE DRC)',
    '+243 81 555 7000',
    'Immeuble Fickin, Boulevard du 30 Juin, Gombe, Kinshasa, DR Congo',
    'https://guichetunique.cd',
    'contact@guichetunique.cd',
    '',
    '',
    '',
    'https://guichetunique.cd/creation-dentreprise',
    'https://guichetunique.cd/pieces-a-fournir',
    'Numero RCCM',
  ),
}
