import type { ComesaMemberIsoCode } from './comesaMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per COMESA member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const COMESA_DOMESTIC_POST_SERVICES: Record<ComesaMemberIsoCode, DomesticPostService> = {
  DJ: post(
    'La Poste de Djibouti',
    'https://www.laposte.dj/',
    'poste.contact@yahoo.fr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing in Djibouti City',
  ),
  EG: post(
    'Egypt Post',
    'http://www.egpost.org/',
    'webmaster@egpost.org',
    'https://x.com/Egyptpost',
    'https://www.instagram.com/egypt.post/',
    'https://www.linkedin.com/company/egypt-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11511',
    'Five-digit national postcode',
  ),
  ER: post(
    'Eritrean Postal Service',
    'https://www.shabait.com/category/national-development/telecom-post/',
    'info@ericsson.com.er',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No published national postcode system',
  ),
  ET: post(
    'Ethiopian Postal Service (EPSE)',
    'https://www.ethiopostal.com/',
    'info@ethiopostal.com',
    '',
    '',
    'https://www.linkedin.com/company/ethiopian-postal-service/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Addis Ababa and regional centres)',
  ),
  LY: post(
    'Libyan Post Company',
    'http://nlpc.ly/',
    'info@nlpc.ly',
    '',
    '',
    'https://www.linkedin.com/company/libyan-post/',
    '',
    'none',
    '',
    '',
    'No consistent national postcode published; verify locally',
  ),
  SD: post(
    'Sudan Post (Sudapost)',
    'https://sudapost.sd/',
    'info@sudapost.sd',
    '',
    '',
    'https://www.linkedin.com/company/sudan-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11111',
    'Five-digit postcode (verify operational coverage)',
  ),
  TN: post(
    'Rapid-Poste (La Poste Tunisia)',
    'https://www.pos.tn/',
    'contact@rapidpost.com.tn',
    'https://x.com/RapidposteTN',
    'https://www.instagram.com/rapidpostenetunisienne/',
    'https://www.linkedin.com/company/la-poste-tunisienne/',
    '',
    'NNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  KM: post(
    'Comores Poste',
    'https://poste-comores.com/',
    'contact@poste-comores.km',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and village addressing',
  ),
  MG: post(
    'Paositra Malagasy',
    'http://www.poste.mg/',
    'contact@paositra.mg',
    'https://x.com/Paositra',
    'https://www.instagram.com/paositramalagasy/',
    'https://www.linkedin.com/company/paositra-malagasy/',
    '',
    'NNN',
    '^\\\\d{3}$',
    '101',
    'Three-digit postcode',
  ),
  MU: post(
    'Mauritius Post Ltd',
    'https://www.mauritiuspost.mu/',
    'info@mpl.mu',
    '',
    '',
    'https://www.linkedin.com/company/mauritius-post-ltd/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '42602',
    'Five-digit postcode (optional letter suffix in some datasets)',
  ),
  SC: post(
    'Seychelles Postal Services',
    'https://www.seychelles-post.com/',
    'info@sib.gov.sc',
    '',
    '',
    'https://www.linkedin.com/company/seychelles-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; island and district addressing',
  ),
  BI: post(
    'Régie nationale des Postes du Burundi',
    'http://www.poste.bi/',
    'info@burundipost.bi',
    '',
    '',
    'https://www.linkedin.com/company/poste-burundi/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune-based addressing',
  ),
  KE: post(
    'Postal Corporation of Kenya',
    'http://posta.co.ke/',
    'customercare@posta.co.ke',
    'https://x.com/postakenya',
    'https://www.instagram.com/postakenya/',
    'https://www.linkedin.com/company/postal-corporation-of-kenya/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00100',
    'Five-digit postcode; P.O. Box culture remains common',
  ),
  MW: post(
    'Malawi Posts Corporation',
    'https://malawipost.gov.mw/',
    'info@malawipost.gov.mw',
    '',
    '',
    'https://www.linkedin.com/company/malawi-posts-corporation/',
    '',
    'none',
    '',
    '',
    'No national postcode; district and P.O. Box',
  ),
  RW: post(
    'Rwanda Post (Iposita)',
    'https://i-posita.rw/',
    'info@ipostarltd.rw',
    'https://x.com/ipositaryw',
    'https://www.instagram.com/ipositaryw/',
    'https://www.linkedin.com/company/iposta-rwanda/',
    '',
    'none',
    '',
    '',
    'No legacy numeric postcode; Kigali addressing reforms — verify locally',
  ),
  UG: post(
    'Uganda Post Limited',
    'https://www.eposta.ug/',
    'info@posta.co.ug',
    'https://x.com/ugposts',
    'https://www.instagram.com/ugposts/',
    'https://www.linkedin.com/company/uganda-post-limited/',
    '',
    'none',
    '',
    '',
    'P.O. Box dominant; no universal street postcode',
  ),
  SZ: post(
    'Eswatini Posts & Telecommunications Corporation',
    'https://www.eswatinipost.co.sz/',
    'info@post.co.sz',
    '',
    '',
    'https://www.linkedin.com/company/eswatini-posts-telecommunications/',
    '',
    'ANNN',
    '^[A-Z]\\\\d{3}$',
    'H100',
    'Letter + three digits (H = Hhohho region prefix)',
  ),
  ZM: post(
    'Zambia Postal Services Corporation',
    'http://www.zampost.gov.zm/',
    'info.zampost@gmail.com',
    '',
    '',
    'https://www.linkedin.com/company/zambia-postal-services-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '10101',
    'Five-digit postcode',
  ),
  ZW: post(
    'Zimpost',
    'http://www.zimpost.co.zw/',
    'zimpost@zimpost.co.zw',
    'https://x.com/zimpost_',
    'https://www.instagram.com/zimpost_/',
    'https://www.linkedin.com/company/zimpost/',
    '',
    'none',
    '',
    '',
    'No national postcode; suburb and P.O. Box routing',
  ),
  CD: post(
    'SCPT RDC (Services postaux)',
    'https://scpt.cd/',
    'info@postesrdc.cd',
    '',
    '',
    'https://www.linkedin.com/company/scpt-rdc/',
    '',
    'none',
    '',
    '',
    'No universal national postcode; commune and P.O. Box',
  ),
}
