import type { ComesaMemberIsoCode } from './comesaMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

const OAPI_TRADEMARKS = ip(
  'trademarks',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

const OAPI_PATENTS = ip(
  'patents',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

function oapiMember(copyright: IntellectualPropertyDepartment): IntellectualPropertyDepartmentsRoster {
  return roster(copyright, OAPI_TRADEMARKS, OAPI_PATENTS)
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for Common Market for Eastern and
 * Southern Africa (COMESA) members in this module (informational; verify URLs, handles, forms
 * portals, and API bases before production use). Self-contained — no imports from other alliance
 * modules. `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const COMESA_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  ComesaMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  DJ: roster(
    ip(
      'copyright',
      'Ministry of Culture and Communication — copyright (Djibouti)',
      'https://www.communication.gouv.dj',
      '',
      '',
      '',
      'https://www.communication.gouv.dj',
    ),
    ip(
      'trademarks',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
    ip(
      'patents',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
  ),
  EG: roster(
    ip(
      'copyright',
      'Egyptian Copyright Office (Ministry of Culture)',
      'https://www.culture.gov.eg',
      '',
      '',
      '',
      'https://www.culture.gov.eg',
    ),
    ip(
      'trademarks',
      'Egyptian Patent Office — Trademarks Department',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
    ip(
      'patents',
      'Egyptian Patent Office',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
  ),
  ER: roster(
    ip(
      'copyright',
      'Ministry of Information — copyright (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
    ip(
      'trademarks',
      'Ministry of Trade and Industry — industrial property (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
    ip(
      'patents',
      'Ministry of Trade and Industry — industrial property (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
  ),
  ET: roster(
    ip(
      'copyright',
      'Ethiopian Intellectual Property Authority — copyright',
      'https://www.eipa.gov.et',
      'info@eipa.gov.et',
      '',
      '',
      'https://www.eipa.gov.et',
    ),
    ip(
      'trademarks',
      'Ethiopian Intellectual Property Authority (EIPA)',
      'https://www.eipa.gov.et',
      'info@eipa.gov.et',
      '',
      '',
      'https://www.eipa.gov.et',
    ),
    ip(
      'patents',
      'Ethiopian Intellectual Property Authority (EIPA)',
      'https://www.eipa.gov.et',
      'info@eipa.gov.et',
      '',
      '',
      'https://www.eipa.gov.et',
    ),
  ),
  LY: roster(
    ip(
      'copyright',
      'Libyan National Centre for Culture and Arts — copyright',
      'https://www.culture.gov.ly',
      '',
      '',
      '',
      'https://www.culture.gov.ly',
    ),
    ip(
      'trademarks',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
    ip(
      'patents',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
  ),
  SD: roster(
    ip(
      'copyright',
      'Sudan Copyright Office (Ministry of Culture)',
      'https://www.moc.gov.sd',
      '',
      '',
      '',
      'https://www.moc.gov.sd',
    ),
    ip(
      'trademarks',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
    ip(
      'patents',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
  ),
  TN: roster(
    ip(
      'copyright',
      'Office National du Droit d\'Auteur (ONDA)',
      'https://www.onda.tn',
      'contact@onda.tn',
      '',
      '',
      'https://www.onda.tn',
    ),
    ip(
      'trademarks',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
    ip(
      'patents',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
  ),
  KM: oapiMember(
    ip(
      'copyright',
      'Centre Comorien du Droit d\'Auteur et des Droits Voisins',
      'https://www.beit-salam.km',
      '',
      '',
      '',
      'https://www.beit-salam.km',
    ),
  ),
  MG: roster(
    ip(
      'copyright',
      'Office Malgache des Droits d\'Auteur (OMDA)',
      'https://www.omda.mg',
      '',
      '',
      '',
      'https://www.omda.mg',
    ),
    ip(
      'trademarks',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
    ip(
      'patents',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
  ),
  MU: roster(
    ip(
      'copyright',
      'Mauritius Society of Authors (MASA)',
      'https://www.masa.mu',
      'info@masa.mu',
      '',
      '',
      'https://www.masa.mu',
    ),
    ip(
      'trademarks',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
    ip(
      'patents',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
  ),
  SC: roster(
    ip(
      'copyright',
      'Seychelles Copyright Office (Ministry of Finance, National Planning and Trade)',
      'https://www.finance.gov.sc',
      '',
      '',
      '',
      'https://www.finance.gov.sc',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
    ip(
      'patents',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
  ),
  BI: roster(
    ip(
      'copyright',
      'Office Burundais des Droits d\'Auteur (OBDA)',
      'https://www.obda.bi',
      '',
      '',
      '',
      'https://www.obda.bi',
    ),
    ip(
      'trademarks',
      'Office Burundais de la Propriété Intellectuelle (OBPI)',
      'https://www.obpi.bi',
      '',
      '',
      '',
      'https://www.obpi.bi',
    ),
    ip(
      'patents',
      'Office Burundais de la Propriété Intellectuelle (OBPI)',
      'https://www.obpi.bi',
      '',
      '',
      '',
      'https://www.obpi.bi',
    ),
  ),
  KE: roster(
    ip(
      'copyright',
      'Kenya Copyright Board (KECOBO)',
      'https://www.copyright.go.ke',
      'info@copyright.go.ke',
      'https://x.com/KECOBO',
      'https://www.linkedin.com/company/kenya-copyright-board/',
      'https://www.copyright.go.ke',
    ),
    ip(
      'trademarks',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
    ip(
      'patents',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
  ),
  MW: roster(
    ip(
      'copyright',
      'Copyright Society of Malawi (COSOMA)',
      'https://www.cosoma.mw',
      'info@cosoma.mw',
      '',
      '',
      'https://www.cosoma.mw',
    ),
    ip(
      'trademarks',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
    ip(
      'patents',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
  ),
  RW: roster(
    ip(
      'copyright',
      'Rwanda Society of Authors (RSAU)',
      'https://www.rsau.rw',
      'info@rsau.rw',
      '',
      '',
      'https://www.rsau.rw',
    ),
    ip(
      'trademarks',
      'Rwanda Development Board — Intellectual Property',
      'https://www.rdb.rw',
      'info@rdb.rw',
      'https://x.com/RwandaDevBoard',
      'https://www.linkedin.com/company/rwanda-development-board/',
      'https://www.rdb.rw',
    ),
    ip(
      'patents',
      'Rwanda Development Board — Intellectual Property',
      'https://www.rdb.rw',
      'info@rdb.rw',
      'https://x.com/RwandaDevBoard',
      'https://www.linkedin.com/company/rwanda-development-board/',
      'https://www.rdb.rw',
    ),
  ),
  UG: roster(
    ip(
      'copyright',
      'Uganda Registration Services Bureau — Copyright Registry',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
    ip(
      'trademarks',
      'Uganda Registration Services Bureau (URSB) — Industrial Property',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
    ip(
      'patents',
      'Uganda Registration Services Bureau (URSB) — Industrial Property',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
  ),
  SZ: roster(
    ip(
      'copyright',
      'Copyright Society of Eswatini (COSOES)',
      'https://www.cosoes.org.sz',
      '',
      '',
      '',
      'https://www.cosoes.org.sz',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
  ),
  ZM: roster(
    ip(
      'copyright',
      'Copyright Society of Zambia (COSOZA)',
      'https://www.cosoza.org.zm',
      'info@cosoza.org.zm',
      '',
      '',
      'https://www.cosoza.org.zm',
    ),
    ip(
      'trademarks',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
    ip(
      'patents',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
  ),
  ZW: roster(
    ip(
      'copyright',
      'Zimbabwe Intellectual Property Office (ZIPO) — copyright',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
    ip(
      'trademarks',
      'Zimbabwe Intellectual Property Office (ZIPO)',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
    ip(
      'patents',
      'Zimbabwe Intellectual Property Office (ZIPO)',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
  ),
  CD: roster(
    ip(
      'copyright',
      'Office Congolais des Droits d\'Auteur (OCADA)',
      'https://www.ocada.cd',
      '',
      '',
      '',
      'https://www.ocada.cd',
    ),
    ip(
      'trademarks',
      'Office Congolais de la Propriété Intellectuelle (OCPI)',
      'https://www.ocpi.cd',
      'info@ocpi.cd',
      '',
      '',
      'https://www.ocpi.cd',
    ),
    ip(
      'patents',
      'Office Congolais de la Propriété Intellectuelle (OCPI)',
      'https://www.ocpi.cd',
      'info@ocpi.cd',
      '',
      '',
      'https://www.ocpi.cd',
    ),
  ),
}
