import type { ComesaMemberIsoCode } from './comesaMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2 for
 * COMESA (Common Market for Eastern and Southern Africa) members (informational; verify against
 * USGS Mineral Commodity Summaries, BGS World Mineral Production, and UN Comtrade periodically).
 * Hydrocarbon-led (EG, LY, SD, TN) carry `Carbon (C)` + `Hydrogen (H)`; copper-belt economies
 * (ZM, CD) lead with `Copper (Cu)` + `Cobalt (Co)`; gold-led (SD, ET, KE, UG, ZW) carry
 * `Gold (Au)`.
 */
export const COMESA_MAIN_EXPORTED_ELEMENTS: Record<ComesaMemberIsoCode, MainExportedElements> = {
  DJ: e(
    'Sodium (Na)',
    'Chlorine (Cl)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Sulfur (S)',
  ),
  EG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Titanium (Ti)',
  ),
  ER: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Silver (Ag)',
    'Potassium (K)',
    'Iron (Fe)',
    'Sulfur (S)',
  ),
  ET: e(
    'Gold (Au)',
    'Tantalum (Ta)',
    'Potassium (K)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Platinum (Pt)',
    'Calcium (Ca)',
  ),
  LY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Potassium (K)',
    'Phosphorus (P)',
    'Calcium (Ca)',
  ),
  SD: e(
    'Gold (Au)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Chromium (Cr)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Sulfur (S)',
  ),
  TN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Fluorine (F)',
  ),
  KM: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Magnesium (Mg)',
    'Sulfur (S)',
  ),
  MG: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Titanium (Ti)',
    'Carbon (C)',
    'Chromium (Cr)',
    'Gold (Au)',
    'Zirconium (Zr)',
  ),
  MU: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  SC: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  BI: e(
    'Gold (Au)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Tantalum (Ta)',
    'Niobium (Nb)',
    'Nickel (Ni)',
    'Iron (Fe)',
  ),
  KE: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Sodium (Na)',
    'Fluorine (F)',
    'Gold (Au)',
    'Niobium (Nb)',
    'Calcium (Ca)',
  ),
  MW: e(
    'Uranium (U)',
    'Niobium (Nb)',
    'Tantalum (Ta)',
    'Titanium (Ti)',
    'Iron (Fe)',
    'Gold (Au)',
    'Calcium (Ca)',
  ),
  RW: e(
    'Tantalum (Ta)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Gold (Au)',
    'Niobium (Nb)',
    'Beryllium (Be)',
    'Iron (Fe)',
  ),
  UG: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Cobalt (Co)',
    'Iron (Fe)',
    'Phosphorus (P)',
  ),
  SZ: e(
    'Carbon (C)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Sulfur (S)',
  ),
  ZM: e(
    'Copper (Cu)',
    'Cobalt (Co)',
    'Gold (Au)',
    'Manganese (Mn)',
    'Nickel (Ni)',
    'Beryllium (Be)',
    'Iron (Fe)',
  ),
  ZW: e(
    'Platinum (Pt)',
    'Gold (Au)',
    'Carbon (C)',
    'Chromium (Cr)',
    'Nickel (Ni)',
    'Lithium (Li)',
    'Cobalt (Co)',
  ),
  CD: e(
    'Cobalt (Co)',
    'Copper (Cu)',
    'Carbon (C)',
    'Gold (Au)',
    'Tin (Sn)',
    'Tantalum (Ta)',
    'Germanium (Ge)',
  ),
}
