import type { NationalBankingInstitution } from './types'
import type { ComesaMemberIsoCode } from './comesaMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per COMESA member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const COMESA_NATIONAL_BANKING_INSTITUTIONS: Record<
  ComesaMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  DJ: [
    bank(
      'CAC International Bank',
      '+253 21 32 22 22',
      'Place Menelik, Djibouti City, Djibouti',
      '',
      '',
      'https://www.cacbankdj.com/',
      'contact@cacbankdj.com',
      '',
      '',
      'https://www.linkedin.com/company/cac-international-bank/',
      '',
      'CACBDJDJ',
      '',
    ),
    bank(
      'Salaam African Bank',
      '+253 21 35 55 55',
      'Avenue Hassan Gouled, Djibouti City, Djibouti',
      '',
      '',
      'https://www.salaam-bank.com/',
      'info@salaam-bank.com',
      '',
      '',
      'https://www.linkedin.com/company/salaam-african-bank/',
      '',
      '',
      '',
    ),
    bank(
      'BCIMR',
      '+253 21 35 30 30',
      'Place Lagarde, Djibouti City, Djibouti',
      '',
      '',
      'https://www.bcimr.dj/',
      'contact@bcimr.dj',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  EG: [
    bank(
      'National Bank of Egypt',
      '+20 2 2576 0777',
      '1187 Corniche El Nil, Cairo, Egypt',
      '',
      '',
      'https://www.nbe.com.eg/',
      'customer.service@nbe.com.eg',
      '',
      '',
      'https://www.linkedin.com/company/national-bank-of-egypt/',
      '',
      'NBEGEGCX',
      '',
    ),
    bank(
      'Banque Misr',
      '+20 2 19888',
      '151 Mohamed Farid St, Cairo, Egypt',
      '',
      '',
      'https://www.banquemisr.com/',
      'customercare@banquemisr.com',
      '',
      '',
      'https://www.linkedin.com/company/banque-misr/',
      '',
      'BMISEGCX',
      '',
    ),
    bank(
      'Commercial International Bank (CIB)',
      '+20 2 19666',
      '21/23 Charles de Gaulle St, Giza, Egypt',
      '',
      '',
      'https://www.cibeg.com/',
      'customer.care@cibeg.com',
      '',
      '',
      'https://www.linkedin.com/company/cibegypt/',
      '',
      'CIBEEGCX',
      '',
    ),
  ],
  ER: [
    bank(
      'Commercial Bank of Eritrea',
      '+291 1 182 251',
      'Harnet Avenue, Asmara, Eritrea',
      '',
      '',
      'https://www.combank-er.com/',
      'info@combank-er.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Housing and Commerce Bank Eritrea',
      '+291 1 181 166',
      'Godaif Street, Asmara, Eritrea',
      '',
      '',
      'https://www.hcb-er.com/',
      'info@hcb-er.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Eritrean Investment and Development Bank',
      '+291 1 181 399',
      'Sematat Avenue, Asmara, Eritrea',
      '',
      '',
      'https://www.eidb-er.com/',
      'info@eidb-er.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  ET: [
    bank(
      'Commercial Bank of Ethiopia',
      '+251 11 551 9500',
      'Ras Desta Damtew St, Addis Ababa, Ethiopia',
      '',
      '',
      'https://www.combanketh.et/',
      'info@cbe.com.et',
      '',
      '',
      'https://www.linkedin.com/company/commercial-bank-of-ethiopia/',
      '',
      'CBETETAA',
      '',
    ),
    bank(
      'Awash Bank',
      '+251 11 558 2727',
      'Ras Abebe Aregay St, Addis Ababa, Ethiopia',
      '',
      '',
      'https://www.awashbank.com/',
      'info@awashbank.com',
      '',
      '',
      'https://www.linkedin.com/company/awash-bank/',
      '',
      'AWINETAA',
      '',
    ),
    bank(
      'Dashen Bank',
      '+251 11 518 0300',
      'Ras Abebe Aregay St, Addis Ababa, Ethiopia',
      '',
      '',
      'https://dashenbanksc.com/',
      'info@dashenbanksc.com',
      '',
      '',
      'https://www.linkedin.com/company/dashen-bank/',
      '',
      'DASHEETA',
      '',
    ),
  ],
  LY: [
    bank(
      'Wahda Bank',
      '+218 21 333 5511',
      'Omar Mukhtar Street, Tripoli, Libya',
      '',
      '',
      'https://wahdabank.ly/',
      'info@wahdabank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Jumhouria Bank',
      '+218 21 360 2000',
      'Al Fatah Street, Tripoli, Libya',
      '',
      '',
      'https://www.jbank.ly/',
      'info@jbank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'National Commercial Bank Libya',
      '+218 21 444 9200',
      'September 1st Street, Tripoli, Libya',
      '',
      '',
      'https://www.ncb.ly/',
      'info@ncb.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  SD: [
    bank(
      'Bank of Khartoum',
      '+249 183 782 000',
      'Mek Nimir Ave, Khartoum, Sudan',
      '',
      '',
      'https://bankofkhartoum.com/',
      'contactus@bok.sd',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-khartoum/',
      '',
      'BOKHSDKH',
      '',
    ),
    bank(
      'Omdurman National Bank',
      '+249 183 783 200',
      'Baladia Street, Khartoum, Sudan',
      '',
      '',
      'https://www.onb-sd.com/',
      'info@onb-sd.com',
      '',
      '',
      '',
      '',
      'ONBKSDKH',
      '',
    ),
    bank(
      'Faisal Islamic Bank Sudan',
      '+249 183 774 000',
      'Al Gamhouria Street, Khartoum, Sudan',
      '',
      '',
      'https://www.fibsudan.com/',
      'info@fibsudan.com',
      '',
      '',
      'https://www.linkedin.com/company/faisal-islamic-bank-sudan/',
      '',
      'FIBSSDKH',
      '',
    ),
  ],
  TN: [
    bank(
      'Banque Internationale Arabe de Tunisie (BIAT)',
      '+216 71 155 000',
      '70-72 Avenue Habib Bourguiba, Tunis, Tunisia',
      '',
      '',
      'https://www.biat.com.tn/',
      'contact@biat.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/biat/',
      '',
      'BIATTNTT',
      '',
    ),
    bank(
      'Amen Bank',
      '+216 71 148 000',
      'Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.amenbank.com.tn/',
      'relationclientele@amenbank.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/amen-bank/',
      '',
      'CFCTTNTT',
      '',
    ),
    bank(
      'BH Bank',
      '+216 71 126 000',
      '18 Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.bhbank.tn/',
      'contact@bhbank.tn',
      '',
      '',
      'https://www.linkedin.com/company/bh-bank/',
      '',
      'BHBKTNTT',
      '',
    ),
  ],
  KM: [
    bank(
      'Banque Federale de Commerce (BFC)',
      '+269 773 20 00',
      'Place de France, Moroni, Comoros',
      '',
      '',
      'https://www.bfc-comores.com/',
      'contact@bfc-comores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Exim Bank Comores',
      '+269 773 25 25',
      'Avenue de la Corniche, Moroni, Comoros',
      '',
      '',
      'https://www.eximbankcomores.com/',
      'info@eximbankcomores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'SNPSF',
      '+269 773 18 18',
      'Avenue Ali Soilih, Moroni, Comoros',
      '',
      '',
      'https://www.snpsf.com/',
      'contact@snpsf.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  MG: [
    bank(
      'BNI Madagascar',
      '+261 20 22 217 17',
      '74 Rue du 26 Juin 1960, Antananarivo, Madagascar',
      '',
      '',
      'https://www.bni.mg/',
      'contact@bni.mg',
      '',
      '',
      'https://www.linkedin.com/company/bni-madagascar/',
      '',
      'CLMADMGM',
      '',
    ),
    bank(
      'Bank of Africa Madagascar',
      '+261 20 22 206 06',
      'Immeuble BOA, Analakely, Antananarivo, Madagascar',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boamadagascar.com/',
      'contact@boamadagascar.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      'AFRIMGMG',
      '',
    ),
    bank(
      'BGFI Bank Madagascar',
      '+261 20 22 629 00',
      'Zone Galaxy, Andraharo, Antananarivo, Madagascar',
      '',
      '',
      'https://www.bgfibank.com/',
      'contact@bgfibank.com',
      '',
      '',
      'https://www.linkedin.com/company/bgfi-holding-corporation/',
      '',
      '',
      '',
    ),
  ],
  MU: [
    bank(
      'The Mauritius Commercial Bank',
      '+230 202 5000',
      'Sir William Newton St, Port Louis, Mauritius',
      '',
      '',
      'https://www.mcb.mu/',
      'contact@mcb.mu',
      '',
      '',
      'https://www.linkedin.com/company/the-mauritius-commercial-bank-limited/',
      '',
      'MCBLMUMU',
      '',
    ),
    bank(
      'SBM Bank (Mauritius)',
      '+230 202 1111',
      '1 Queen Elizabeth II Avenue, Port Louis, Mauritius',
      '',
      '',
      'https://www.sbmgroup.mu/',
      'sbm@sbmgroup.mu',
      '',
      '',
      'https://www.linkedin.com/company/sbm-bank-mauritius-ltd/',
      '',
      'STCBMUMU',
      '',
    ),
    bank(
      'Absa Bank Mauritius',
      '+230 402 1000',
      'Absa House, Wall Street, Ebene, Mauritius',
      '',
      '',
      'https://www.absabank.mu/',
      'absamauritius@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCMUMU',
      '',
    ),
  ],
  SC: [
    bank(
      'Nouvobanq',
      '+248 4 280 800',
      'Rue de la Possession, Victoria, Seychelles',
      '',
      '',
      'https://www.nouvobanq.sc/',
      'info@nouvobanq.sc',
      '',
      '',
      'https://www.linkedin.com/company/nouvobanq/',
      '',
      'NOVHSCSC',
      '',
    ),
    bank(
      'Absa Bank Seychelles',
      '+248 4 389 000',
      'Independence House Annex, Victoria, Seychelles',
      '',
      '',
      'https://www.absa.sc/',
      'seychelles@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCSCSC',
      '',
    ),
    bank(
      'Mauritius Commercial Bank Seychelles',
      '+248 4 288 800',
      '9th Floor, Caravelle House, Victoria, Seychelles',
      '',
      '',
      'https://www.mcbseychelles.sc/',
      'contact@mcbseychelles.sc',
      '',
      '',
      'https://www.linkedin.com/company/mcb-seychelles/',
      '',
      'MCBLSCSC',
      '',
    ),
  ],
  BI: [
    bank(
      'Banque de Credit de Bujumbura (BCB)',
      '+257 22 22 10 88',
      'Boulevard de la Liberte, Bujumbura, Burundi',
      '',
      '',
      'https://www.bcb.bi/',
      'contact@bcb.bi',
      '',
      '',
      'https://www.linkedin.com/company/banque-de-cr%C3%A9dit-de-bujumbura/',
      '',
      'BCBIBIBI',
      '',
    ),
    bank(
      'Interbank Burundi',
      '+257 22 22 08 50',
      'Avenue de l Industrie, Bujumbura, Burundi',
      '',
      '',
      'https://www.interbankburundi.com/',
      'info@interbankburundi.com',
      '',
      '',
      'https://www.linkedin.com/company/interbank-burundi/',
      '',
      'INBKBIBI',
      '',
    ),
    bank(
      'BANCOBU',
      '+257 22 20 80 00',
      'Avenue du Large 26, Bujumbura, Burundi',
      '',
      '',
      'https://www.bancobu.bi/',
      'contact@bancobu.bi',
      '',
      '',
      'https://www.linkedin.com/company/bancobu/',
      '',
      'BCBUBIBI',
      '',
    ),
  ],
  KE: [
    bank(
      'KCB Bank Kenya',
      '+254 20 3270000',
      'Kencom House, Moi Avenue, Nairobi, Kenya',
      '',
      '',
      'https://ke.kcbgroup.com/',
      'contactcentre@kcbgroup.com',
      '',
      '',
      'https://www.linkedin.com/company/kcb-bank-kenya-limited/',
      '',
      'KCBLKENX',
      '',
    ),
    bank(
      'Equity Bank Kenya',
      '+254 763 000 000',
      'Equity Centre, Hospital Road, Nairobi, Kenya',
      '',
      '',
      'https://equitygroupholdings.com/ke/',
      'info@equitybank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-limited/',
      '',
      'EQBLKENA',
      '',
    ),
    bank(
      'Co-operative Bank of Kenya',
      '+254 20 2776000',
      'Co-op House, Haile Selassie Avenue, Nairobi, Kenya',
      '',
      '',
      'https://www.co-opbank.co.ke/',
      'customerservice@co-opbank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/co-operative-bank-of-kenya/',
      '',
      'KCOOKENA',
      '',
    ),
  ],
  MW: [
    bank(
      'National Bank of Malawi',
      '+265 1 820 333',
      '7 Henderson Street, Blantyre, Malawi',
      '',
      '',
      'https://www.natbank.co.mw/',
      'customer.service@natbank.co.mw',
      '',
      '',
      'https://www.linkedin.com/company/national-bank-of-malawi/',
      '',
      'NBMAMWMW',
      '',
    ),
    bank(
      'FDH Bank',
      '+265 1 820 222',
      'FDH House, Glyn Jones Road, Blantyre, Malawi',
      '',
      '',
      'https://www.fdh.co.mw/',
      'customerservice@fdh.co.mw',
      '',
      '',
      'https://www.linkedin.com/company/fdh-bank-plc/',
      '',
      'FDHFMWMW',
      '',
    ),
    bank(
      'Standard Bank Malawi',
      '+265 1 820 944',
      'Kaomba Centre, Blantyre, Malawi',
      '',
      '',
      'https://www.standardbank.co.mw/',
      'malawi@standardbank.co.mw',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBICMWMX',
      '',
    ),
  ],
  RW: [
    bank(
      'Bank of Kigali',
      '+250 788 143 000',
      'KN3 Ave, Kigali, Rwanda',
      '',
      '',
      'https://www.bk.rw/',
      'customerservice@bk.rw',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-kigali/',
      '',
      'BKIGRWRW',
      '',
    ),
    bank(
      'I&M Bank Rwanda',
      '+250 252 575 000',
      'KN3 Ave, Kigali, Rwanda',
      '',
      '',
      'https://www.imbankrw.com/',
      'customercare@imbank.co.rw',
      '',
      '',
      'https://www.linkedin.com/company/i-m-bank-rwanda/',
      '',
      'IMRWRWRW',
      '',
    ),
    bank(
      'Ecobank Rwanda',
      '+250 252 550 678',
      'Avenue de la Paix, Kigali, Rwanda',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/rw',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCRWRW',
      '',
    ),
  ],
  UG: [
    bank(
      'Stanbic Bank Uganda',
      '+256 312 224 600',
      'Plot 17 Hannington Road, Kampala, Uganda',
      '',
      '',
      'https://www.stanbicbank.co.ug/',
      'customercare@stanbic.com',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-uganda/',
      '',
      'SBICUGKX',
      '',
    ),
    bank(
      'Centenary Bank',
      '+256 417 126 000',
      'Mapeera House, Kampala Road, Kampala, Uganda',
      '',
      '',
      'https://www.centenarybank.co.ug/',
      'customerservice@centenarybank.co.ug',
      '',
      '',
      'https://www.linkedin.com/company/centenary-bank-uganda/',
      '',
      'CERBUGKA',
      '',
    ),
    bank(
      'dfcu Bank',
      '+256 312 300 000',
      'Plot 26 Kyadondo Road, Kampala, Uganda',
      '',
      '',
      'https://www.dfcugroup.com/',
      'customercare@dfcugroup.com',
      '',
      '',
      'https://www.linkedin.com/company/dfcu-bank/',
      '',
      'DFCUUGKA',
      '',
    ),
  ],
  SZ: [
    bank(
      'Eswatini Bank',
      '+268 2404 1000',
      'Swazi Plaza, Mbabane, Eswatini',
      '',
      '',
      'https://www.eswatinibank.co.sz/',
      'info@eswatinibank.co.sz',
      '',
      '',
      'https://www.linkedin.com/company/eswatini-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Standard Bank Eswatini',
      '+268 2408 3000',
      'Swazi Trade House, Mbabane, Eswatini',
      '',
      '',
      'https://www.standardbank.co.sz/',
      'service@standardbank.co.sz',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBICSZMX',
      '',
    ),
    bank(
      'Nedbank Eswatini',
      '+268 2408 5600',
      'Nedbank Centre, Mbabane, Eswatini',
      '',
      '',
      'https://www.nedbank.co.sz/',
      'contact@nedbank.co.sz',
      '',
      '',
      'https://www.linkedin.com/company/nedbank/',
      '',
      'NEDSSZMX',
      '',
    ),
  ],
  ZM: [
    bank(
      'Zanaco',
      '+260 211 220 314',
      'Cairo Road, Lusaka, Zambia',
      '',
      '',
      'https://www.zanaco.co.zm/',
      'customercare@zanaco.co.zm',
      '',
      '',
      'https://www.linkedin.com/company/zanaco/',
      '',
      'ZNCOZMLU',
      '',
    ),
    bank(
      'Absa Bank Zambia',
      '+260 211 366 800',
      'Stand 4643, Addis Ababa Drive, Lusaka, Zambia',
      '',
      '',
      'https://www.absa.co.zm/',
      'zambia@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCZMLX',
      '',
    ),
    bank(
      'Stanbic Bank Zambia',
      '+260 211 224 700',
      'Corner of Great East Road and Addis Ababa Drive, Lusaka, Zambia',
      '',
      '',
      'https://www.stanbicbank.co.zm/',
      'zambia@stanbic.com',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-zambia/',
      '',
      'SBICZMLX',
      '',
    ),
  ],
  ZW: [
    bank(
      'CBZ Bank',
      '+263 242 748 050',
      'Union House, 60 Kwame Nkrumah Ave, Harare, Zimbabwe',
      '',
      '',
      'https://www.cbz.co.zw/',
      'contactcentre@cbz.co.zw',
      '',
      '',
      'https://www.linkedin.com/company/cbz-bank-limited/',
      '',
      'COBZZWHA',
      '',
    ),
    bank(
      'Steward Bank Zimbabwe',
      '+263 242 795 858',
      '1906 Liberation Legacy Way, Harare, Zimbabwe',
      '',
      '',
      'https://www.stewardbank.co.zw/',
      'contactcentre@stewardbank.co.zw',
      '',
      '',
      'https://www.linkedin.com/company/steward-bank-zimbabwe/',
      '',
      '',
      '',
    ),
    bank(
      'Stanbic Bank Zimbabwe',
      '+263 242 758 311',
      'Stanbic Centre, 59 Samora Machel Ave, Harare, Zimbabwe',
      '',
      '',
      'https://www.stanbicbank.co.zw/',
      'customercare@stanbic.co.zw',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-zimbabwe/',
      '',
      'SBICZWHX',
      '',
    ),
  ],
  CD: [
    bank(
      'Rawbank',
      '+243 99 601 1300',
      '3487 Boulevard du 30 Juin, Kinshasa, DR Congo',
      '',
      '',
      'https://www.rawbank.com/',
      'info@rawbank.com',
      'https://x.com/Rawbank',
      '',
      'https://www.linkedin.com/company/rawbank/',
      '',
      'RAWBCDKI',
      '',
    ),
    bank(
      'Equity BCDC',
      '+243 99 601 1301',
      '5 Avenue des Aviateurs, Kinshasa, DR Congo',
      '',
      '',
      'https://equitygroupholdings.com/cd/',
      'contact@equitygroupholdings.com',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-congo/',
      '',
      'BCDCCDKI',
      '',
    ),
    bank(
      'Ecobank DRC',
      '+243 81 555 7700',
      'Immeuble Ecobank, Gombe, Kinshasa, DR Congo',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/cd',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCCDKI',
      '',
    ),
  ],
}
