import type { CorporationFormationOffice } from './types'
import type { ApecMemberIsoCode } from './apecMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per APEC member economy.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const APEC_CORPORATION_FORMATION_OFFICES: Record<ApecMemberIsoCode, CorporationFormationOffice> = {
  AU:   office(
    'Australian Securities and Investments Commission (ASIC)',
    '+61 1300 300 630',
    'Level 5, 100 Market Street, Sydney NSW 2000, Australia',
    'https://asic.gov.au',
    '',
    'https://twitter.com/asicmedia',
    '',
    'https://www.linkedin.com/company/australian-securities-and-investments-commission/',
    'https://asic.gov.au/for-business/registering-a-company/',
    'https://business.gov.au/planning/new-businesses/register-a-company',
    'Australian Company Number (ACN)',
  ),
  BN:   office(
    'Registry of Companies and Business Names (ROCBN)',
    '+673 2383444',
    'Ministry of Finance and Economy, Bandar Seri Begawan, Brunei Darussalam',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    '',
    '',
    '',
    '',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    'https://business.gov.bn/SitePages/Starting%20a%20Business.aspx',
    'Business Registration Number',
  ),
  CA:   office(
    'Corporations Canada (Innovation, Science and Economic Development)',
    '+1 866 333 5556',
    '235 Queen Street, Ottawa, ON K1A 0H5, Canada',
    'https://ised-isde.canada.ca/site/corporations-canada/en',
    '',
    '',
    '',
    '',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/incorporate-business-corporation',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/steps-incorporating',
    'Corporation Number',
  ),
  CL:   office(
    'Registro de Empresas y Sociedades (Tu Empresa en un Dia)',
    '+56 2 2440 6000',
    'Santiago, Chile',
    'https://www.registrodeempresasysociedades.cl',
    '',
    '',
    '',
    '',
    'https://www.registrodeempresasysociedades.cl',
    'https://www.chileatiende.gob.cl/fichas/31239-constituir-una-sociedad-en-el-registro-de-empresas-y-sociedades-res',
    'Rol Unico Tributario (RUT)',
  ),
  CN:   office(
    'State Administration for Market Regulation (Enterprise Registration)',
    '+86 10 8865 0000',
    'No. 8 Sanlihe East Road, Xicheng District, Beijing, China',
    'https://www.samr.gov.cn',
    '',
    '',
    '',
    '',
    'https://zwfw.samr.gov.cn',
    'https://www.gov.cn/fuwu/2015-12/09/content_5022390.htm',
    'Unified Social Credit Code',
  ),
  HK:   office(
    'Companies Registry (Hong Kong e-Registry)',
    '+852 2867 2587',
    '14th Floor, Queensway Government Offices, 66 Queensway, Hong Kong',
    'https://www.cr.gov.hk',
    'crenq@cr.gov.hk',
    '',
    '',
    '',
    'https://www.eregistry.gov.hk',
    'https://www.cr.gov.hk/en/faq/local-company-incorporation.htm',
    'Business Registration Number (BRN)',
  ),
  ID:   office(
    'OSS Indonesia (Ministry of Investment/BKPM)',
    '+62 21 1500 123',
    'Jl. Jenderal Gatot Subroto No. 44, Jakarta, Indonesia',
    'https://oss.go.id',
    '',
    '',
    '',
    '',
    'https://oss.go.id',
    'https://www.bkpm.go.id/en/public-service',
    'Nomor Induk Berusaha (NIB)',
  ),
  JP:   office(
    'Legal Affairs Bureau (Ministry of Justice Commercial Registration)',
    '+81 3 3580 4111',
    '1-1-1 Kasumigaseki, Chiyoda-ku, Tokyo, Japan',
    'https://www.moj.go.jp',
    '',
    '',
    '',
    '',
    'https://www.moj.go.jp/MINJI/minji06.html',
    'https://www.jetro.go.jp/en/invest/setting_up/section1/page3.html',
    'Corporate Number (Houjin Bango)',
  ),
  MY:   office(
    'Companies Commission of Malaysia (SSM)',
    '+60 3 7721 4000',
    'Menara SSM@Sentral, No. 7 Jalan Stesen Sentral 5, Kuala Lumpur, Malaysia',
    'https://www.ssm.com.my',
    'enquiry@ssm.com.my',
    '',
    '',
    '',
    'https://ezbiz.ssm.com.my',
    'https://www.ssm.com.my/Pages/Legal_Framework/Company/Guidelines.aspx',
    'Company Number',
  ),
  MX:   office(
    'Secretaria de Economia - Tu Empresa',
    '+52 55 5729 9100',
    'Av. Insurgentes Sur 1940, Mexico City, Mexico',
    'https://www.gob.mx/se',
    '',
    '',
    '',
    '',
    'https://www.gob.mx/tuempresa',
    'https://www.gob.mx/tramites/ficha/constitucion-de-sociedades/SRE2566',
    'Registro Federal de Contribuyentes (RFC)',
  ),
  NZ:   office(
    'New Zealand Companies Office',
    '+64 50 872 2669',
    'Wellington, New Zealand',
    'https://companies-register.companiesoffice.govt.nz',
    '',
    '',
    '',
    '',
    'https://companies-register.companiesoffice.govt.nz/help-centre/starting-a-company',
    'https://www.business.govt.nz/getting-started/advice-for-start-ups/10-step-guide-to-starting-a-business/',
    'New Zealand Business Number (NZBN)',
  ),
  PG:   office(
    'Investment Promotion Authority (IPA) Papua New Guinea',
    '+675 321 7311',
    'Malaoro Street, Port Moresby, Papua New Guinea',
    'https://www.ipa.gov.pg',
    '',
    '',
    '',
    '',
    'https://www.ipa.gov.pg/online-services',
    'https://www.ipa.gov.pg/business-registration',
    'Company Number',
  ),
  PE:   office(
    'SUNARP - SID Sunarp',
    '+51 1 208 3100',
    'Av. Primavera 1878, Santiago de Surco, Lima, Peru',
    'https://www.sunarp.gob.pe',
    '',
    '',
    '',
    '',
    'https://sid.sunarp.gob.pe',
    'https://www.gob.pe/709-inscribir-una-empresa-en-el-registro-de-personas-juridicas',
    'Registro Unico de Contribuyentes (RUC)',
  ),
  PH:   office(
    'Securities and Exchange Commission Philippines (eSPARC)',
    '+63 2 8818 0921',
    '7907 Makati Avenue, Salcedo Village, Makati, Philippines',
    'https://www.sec.gov.ph',
    'imessagemo@sec.gov.ph',
    '',
    '',
    '',
    'https://esparc.sec.gov.ph',
    'https://www.sec.gov.ph/wp-content/uploads/2022/02/2022MC_no3.pdf',
    'SEC Registration Number',
  ),
  RU:   office(
    'Federal Tax Service of Russia (State Registration)',
    '+7 495 913 0009',
    'Neglinnaya St., 23, Moscow, Russia',
    'https://www.nalog.gov.ru',
    '',
    '',
    '',
    '',
    'https://service.nalog.ru/gosreg',
    'https://www.nalog.gov.ru/rn77/yul/interest/reg_ur/',
    'OGRN',
  ),
  SG:   office(
    'Accounting and Corporate Regulatory Authority (ACRA)',
    '+65 6248 6028',
    '10 Anson Road, International Plaza, Singapore',
    'https://www.acra.gov.sg',
    '',
    '',
    '',
    'https://www.linkedin.com/company/accounting-and-corporate-regulatory-authority-acra-/',
    'https://www.bizfile.gov.sg',
    'https://www.acra.gov.sg/how-to-guides/before-you-start/incorporation',
    'Unique Entity Number (UEN)',
  ),
  KR:   office(
    'Supreme Court Internet Registry Office',
    '+82 2 3480 1715',
    'Seocho-daero, Seocho-gu, Seoul, Republic of Korea',
    'https://www.iros.go.kr',
    '',
    '',
    '',
    '',
    'https://www.iros.go.kr',
    'https://www.k-startup.go.kr/common/post/detail.do?postSn=95',
    'Business Registration Number',
  ),
  TW:   office(
    'Department of Commerce (MOEA Taiwan)',
    '+886 2 2321 2200',
    'No. 15, Fuzhou St., Zhongzheng District, Taipei, Taiwan',
    'https://gcis.nat.gov.tw',
    '',
    '',
    '',
    '',
    'https://onestop.nat.gov.tw',
    'https://gcis.nat.gov.tw/mainNew/subclassNAction.do?method=getFile&pk=903',
    'Unified Business Number (UBN)',
  ),
  TH:   office(
    'Department of Business Development (DBD)',
    '+66 2 547 5959',
    'Nonthaburi, Thailand',
    'https://www.dbd.go.th',
    '',
    '',
    '',
    '',
    'https://www.dbd.go.th',
    'https://www.dbd.go.th/download/article/article_20200617110202.pdf',
    'Company Registration Number',
  ),
  US:   office(
    'U.S. State Secretary of State Business Filing Offices (Representative: Delaware Division of Corporations)',
    '+1 302 739 3073',
    '401 Federal Street, Dover, DE 19901, United States',
    'https://corp.delaware.gov',
    '',
    '',
    '',
    '',
    'https://corp.delaware.gov/paytaxes/',
    'https://www.sba.gov/business-guide/launch-your-business/register-your-business',
    'Employer Identification Number (EIN)',
  ),
  VN:   office(
    'Business Registration Management Agency (Ministry of Finance)',
    '+84 24 0804 3128',
    'Hanoi, Vietnam',
    'https://dangkykinhdoanh.gov.vn',
    '',
    '',
    '',
    '',
    'https://dangkykinhdoanh.gov.vn',
    'https://dangkykinhdoanh.gov.vn/vn/Pages/Trangchu.aspx',
    'Tax Identification Number (MST)',
  ),
}
