import type { ApecMemberIsoCode } from './apecMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per APEC member economy.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const APEC_DOMESTIC_POST_SERVICES: Record<ApecMemberIsoCode, DomesticPostService> = {
  AU: post(
    'Australia Post',
    'https://auspost.com.au/',
    'feedback@auspost.com.au',
    'https://x.com/AusPost',
    'https://www.instagram.com/auspost/',
    'https://www.linkedin.com/company/australia-post/',
    'https://developers.auspost.com.au/',
    'NNNN',
    '^\\d{4}$',
    '2000',
    'Four-digit postcode',
  ),
  BN: post(
    'Postal Services Department (Brunei)',
    'https://www.post.gov.bn/',
    'postmaster@post.gov.bn',
    '',
    '',
    'https://www.linkedin.com/company/postal-services-department-brunei/',
    '',
    'AANNNN',
    '^[A-Z]{2}\\d{4}$',
    'BA2110',
    'Two-letter area + four digits (Brunei Darussalam)',
  ),
  CA: post(
    'Canada Post',
    'https://www.canadapost-postescanada.ca/',
    'customercare@canadapost-postescanada.ca',
    'https://x.com/canadapostcorp',
    'https://www.instagram.com/canadapost/',
    'https://www.linkedin.com/company/canada-post/',
    'https://www.canadapost-postescanada.ca/cpc/en/tools/find-a-postal-code.page',
    'ANA NAN',
    '^[A-Z]\\d[A-Z] \\d[A-Z]\\d$',
    'K1A 0B1',
    'Canadian postal code (letter-digit-letter space digit-letter-digit)',
  ),
  CL: post(
    'Correos de Chile',
    'https://www.correos.cl/',
    'contacto@correos.cl',
    'https://x.com/CorreosChile',
    'https://www.instagram.com/correoschile/',
    'https://www.linkedin.com/company/correos-de-chile/',
    '',
    'NNNNNNN',
    '^\\d{7}$',
    '8320000',
    'Seven-digit postcode',
  ),
  CN: post(
    'China Post',
    'https://www.ems.com.cn/',
    'service@ems.com.cn',
    'https://x.com/chinapost',
    'https://www.instagram.com/chinapost/',
    'https://www.linkedin.com/company/china-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
  HK: post(
    'Hongkong Post',
    'https://www.hongkongpost.hk/',
    'hkpost@hkpost.gov.hk',
    'https://x.com/hkpost',
    'https://www.instagram.com/hkpost/',
    'https://www.linkedin.com/company/hongkong-post/',
    '',
    'none',
    '',
    '',
    'No postal code; building name and district addressing',
  ),
  ID: post(
    'Pos Indonesia',
    'https://www.posindonesia.co.id/',
    'pusatbantuan@posindonesia.co.id',
    'https://x.com/PosIndonesia',
    'https://www.instagram.com/posindonesia/',
    'https://www.linkedin.com/company/pos-indonesia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10110',
    'Five-digit postcode',
  ),
  JP: post(
    'Japan Post',
    'https://www.post.japanpost.jp/',
    'info@jp-network.japanpost.jp',
    'https://x.com/japanpost_off',
    'https://www.instagram.com/japanpost_off/',
    'https://www.linkedin.com/company/japan-post-holdings/',
    '',
    'NNN-NNNN',
    '^\\d{3}-\\d{4}$',
    '100-0001',
    'Three-digit + four-digit postcode (hyphenated)',
  ),
  MY: post(
    'Pos Malaysia',
    'https://www.pos.com.my/',
    'customercare@pos.com.my',
    'https://x.com/posmalaysia',
    'https://www.instagram.com/posmalaysia/',
    'https://www.linkedin.com/company/pos-malaysia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '50000',
    'Five-digit postcode',
  ),
  MX: post(
    'Correos de México',
    'https://www.correosdemexico.gob.mx/',
    'atencionaclientes@correosdemexico.gob.mx',
    'https://x.com/CorreosdeMexico',
    'https://www.instagram.com/correosdemexico/',
    'https://www.linkedin.com/company/correos-de-mexico/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '06000',
    'Five-digit código postal',
  ),
  NZ: post(
    'NZ Post',
    'https://www.nzpost.co.nz/',
    'customercare@nzpost.co.nz',
    'https://x.com/NZPost',
    'https://www.instagram.com/nzpost/',
    'https://www.linkedin.com/company/nz-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '6011',
    'Four-digit postcode',
  ),
  PG: post(
    'Post PNG',
    'https://www.postpng.com.pg/',
    'info@postpng.com.pg',
    '',
    '',
    'https://www.linkedin.com/company/post-png/',
    '',
    'NNN',
    '^\\d{3}$',
    '111',
    'Three-digit postcode',
  ),
  PE: post(
    'Serpost (Correos del Perú)',
    'https://www.serpost.com.pe/',
    'atencion@serpost.com.pe',
    'https://x.com/SerpostPeru',
    'https://www.instagram.com/serpostperu/',
    'https://www.linkedin.com/company/serpost/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '15001',
    'Five-digit código postal (Lima uses leading 15)',
  ),
  PH: post(
    'Philippine Postal Corporation (PHLPost)',
    'https://www.phlpost.gov.ph/',
    'info@phlpost.gov.ph',
    'https://x.com/PHLPost',
    'https://www.instagram.com/phlpost/',
    'https://www.linkedin.com/company/philippine-postal-corporation/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  RU: post(
    'Russian Post (Pochta Rossii)',
    'https://www.pochta.ru/',
    'info@russianpost.ru',
    'https://x.com/russianpost',
    'https://www.instagram.com/russianpost/',
    'https://www.linkedin.com/company/russian-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '101000',
    'Six-digit postcode',
  ),
  SG: post(
    'Singapore Post',
    'https://www.singpost.com/',
    'feedback@singpost.com',
    'https://x.com/SingPost',
    'https://www.instagram.com/singpost/',
    'https://www.linkedin.com/company/singapore-post-limited/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '018956',
    'Six-digit postcode',
  ),
  KR: post(
    'Korea Post',
    'https://www.koreapost.go.kr/',
    'help@koreapost.go.kr',
    'https://x.com/koreapost',
    'https://www.instagram.com/koreapost/',
    'https://www.linkedin.com/company/korea-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '04524',
    'Five-digit postcode (reformed 2015)',
  ),
  TW: post(
    'Chunghwa Post',
    'https://www.post.gov.tw/',
    'service@post.gov.tw',
    'https://x.com/chunghwapost',
    'https://www.instagram.com/chunghwapost/',
    'https://www.linkedin.com/company/chunghwa-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10058',
    'Five-digit postcode (Taiwan)',
  ),
  TH: post(
    'Thailand Post',
    'https://www.thailandpost.co.th/',
    'contact@thailandpost.co.th',
    'https://x.com/ThailandPost',
    'https://www.instagram.com/thailandpost/',
    'https://www.linkedin.com/company/thailand-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10100',
    'Five-digit postcode',
  ),
  US: post(
    'United States Postal Service (USPS)',
    'https://www.usps.com/',
    'uspscustomerservice@usps.gov',
    'https://x.com/USPS',
    'https://www.instagram.com/usps/',
    'https://www.linkedin.com/company/usps/',
    'https://developer.usps.com/',
    'NNNNN',
    '^\\d{5}$',
    '20500',
    'Five-digit ZIP; ZIP+4 optional (NNNNN-NNNN)',
  ),
  VN: post(
    'Vietnam Post (VNPost)',
    'https://www.vnpost.vn/',
    'contact@vnpost.vn',
    'https://x.com/VNPost',
    'https://www.instagram.com/vnpost/',
    'https://www.linkedin.com/company/vietnam-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
}
