import type { DomesticCourierService } from './types'

function c(
  name: string,
  website: string,
  email: string,
  instagram: string,
  twitter: string,
  apiEndpoint: string,
): DomesticCourierService {
  return { name, website, email, instagram, twitter, apiEndpoint }
}

/**
 * Domestic courier reference rows by ISO 3166-1 alpha-2 for APEC member economies.
 * Verify URLs, emails, social handles, and `apiEndpoint` bases locally before production use.
 */
export const APEC_DOMESTIC_COURIERS = {
  AU: [
    c(
      'Australia Post',
      'https://auspost.com.au/',
      'customerservicecentre@auspost.com.au',
      'https://www.instagram.com/auspost/',
      'https://x.com/auspost',
      'https://digitalapi.auspost.com.au/',
    ),
    c(
      'StarTrack (Australia Post)',
      'https://startrackcourier.com.au/',
      'customerservicecourier.au@startrack.com.au',
      'https://www.instagram.com/auspost/',
      'https://x.com/auspost',
      'https://digitalapi.auspost.com.au/',
    ),
    c(
      'Toll Group (domestic parcels)',
      'https://www.mytoll.com/',
      'au.customersolutions@tollpriority.com.au',
      'https://www.instagram.com/tollgroup/',
      'https://x.com/TOLL_Group',
      '',
    ),
    c(
      'CouriersPlease',
      'https://www.couriersplease.com.au/',
      'info@couriersplease.com.au',
      'https://www.instagram.com/couriersplease/',
      '',
      '',
    ),
  ],
  BN: [
    c(
      'Postal Services Department (Brunei)',
      'https://postal.gov.bn/',
      'info.postal@mpt.gov.bn',
      '',
      '',
      '',
    ),
    c(
      'DHL Express Brunei Darussalam',
      'https://www.dhl.com/bn-en/home.html',
      'customerservicebn@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Brunei',
      'https://www.fedex.com/en-bn/',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'Aramex Brunei',
      'https://www.aramex.com/',
      'customerservicebn@aramex.com',
      'https://www.instagram.com/aramex/',
      'https://x.com/aramex',
      'https://ws.aramex.net/',
    ),
  ],
  CA: [
    c(
      'Canada Post',
      'https://www.canadapost-postescanada.ca/',
      'info@canadapost.ca',
      'https://www.instagram.com/canadapostagram/',
      'https://x.com/canadapostcorp',
      'https://soa-gw.canadapost.ca/',
    ),
    c(
      'Purolator',
      'https://www.purolator.com/',
      'shipments@purolator.com',
      'https://www.instagram.com/purolatorinc/',
      'https://x.com/PurolatorInc',
      'https://webservices.purolator.com/',
    ),
    c(
      'UPS Canada',
      'https://www.ups.com/ca/en/Home.page',
      'help@ups.com',
      'https://www.instagram.com/ups/',
      'https://x.com/UPS',
      'https://onlinetools.ups.com/api/',
    ),
    c(
      'FedEx Canada',
      'https://www.fedex.com/en-ca/home.html',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
  ],
  CL: [
    c(
      'Correos de Chile EMS',
      'https://www.correos.cl/',
      'atencionalclientecorreos@correos.cl',
      'https://www.instagram.com/correoschile/',
      'https://x.com/correoschile',
      '',
    ),
    c(
      'Blue Express Chile',
      'https://www.blueexpress.cl/',
      'atenciones@blueexpress.cl',
      'https://www.instagram.com/bluexpressoficial/',
      'https://x.com/Bluexpress_Cl',
      '',
    ),
    c(
      'Chilexpress',
      'https://www.chilexpress.cl/',
      'ayudaonline@corporativoexpress.cl',
      'https://www.instagram.com/chilexpress_sa/',
      'https://x.com/chileexpress',
      '',
    ),
    c(
      'Starken Chile',
      'https://www.starken.cl/',
      'contactoclientes@starken.cl',
      'https://www.instagram.com/starkenchile/',
      'https://x.com/starkenchile',
      '',
    ),
  ],
  CN: [
    c(
      'SF Express',
      'https://www.sf-express.com/us/en/',
      'intl_cs@sf-express.com',
      'https://www.instagram.com/sfexpress_official/',
      'https://x.com/SF_Express_US',
      '',
    ),
    c(
      'China Postal Express & Logistics (EMS)',
      'http://www.ems.com.cn/english/',
      'info@chinaems.com.cn',
      '',
      'https://x.com/china_mail',
      '',
    ),
    c(
      'JD Logistics (domestic parcels)',
      'https://www.jdl.cn/',
      'service@jd.com',
      '',
      '',
      '',
    ),
    c(
      'YTO Express Group',
      'https://www.ytoexpress.com/',
      'yto@yuantong888.com',
      '',
      '',
      '',
    ),
  ],
  HK: [
    c(
      'Hongkong Post EMS',
      'https://www.hongkongpost.hk/',
      'enquiries@hongkongpost.hk',
      '',
      '',
      '',
    ),
    c(
      'SF Express Hong Kong',
      'https://htm.sf-express.com/hk/sc/',
      'hk.cs@sf-express.com',
      'https://www.instagram.com/sfhk_official/',
      '',
      '',
    ),
    c(
      'Kerry Express Hong Kong',
      'https://www.kerryexpress.com.hk/zh/',
      'cs.hk@kerry-logistics.com',
      'https://www.instagram.com/kerry_express.hk/',
      '',
      '',
    ),
    c(
      'DHL Express Hong Kong SAR',
      'https://www.dhl.com/hk-en/home.html',
      'hk.customermasterbilling@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
  ],
  ID: [
    c(
      'PT Pos Indonesia (Pos Indonesia)',
      'https://www.posindonesia.co.id/',
      'pps@mail.posindonesia.co.id',
      'https://www.instagram.com/posindonesia.id/',
      'https://x.com/Posindonesia',
      '',
    ),
    c(
      'JNE Express',
      'https://www.jne.co.id/',
      'customercare@jne.co.id',
      'https://www.instagram.com/jne_id/',
      'https://x.com/jne_id',
      '',
    ),
    c(
      'J&T Express Indonesia',
      'https://jtexpress.id/',
      'care@jit.id',
      'https://www.instagram.com/idjnt/',
      '',
      '',
    ),
    c(
      'SiCepat Ekspres',
      'https://www.sicepat.com/',
      'care@sicepat.com',
      'https://www.instagram.com/sicepatekspres/',
      'https://x.com/sicepatekspress',
      '',
    ),
  ],
  JP: [
    c(
      'Japan Post (Yu-Pack / EMS)',
      'https://www.post.japanpost.jp/',
      'customer@mail.post.japanpost.jp',
      'https://www.instagram.com/japanpost_official/',
      'https://x.com/JapanPost_EN',
      '',
    ),
    c(
      'Yamato Transport (クロネコ)',
      'https://www.kuronekoyamato.co.jp/',
      'info-support@yamato-group.com',
      'https://www.instagram.com/kuronekoyamatointernational/',
      'https://x.com/YamatoinUS',
      '',
    ),
    c(
      'Sagawa Express',
      'https://www.sagawa-exp.co.jp/',
      'cust-sv@sagawa-exp.co.jp',
      'https://www.instagram.com/sagawa_express/',
      '',
      '',
    ),
    c(
      'Seino Transportation',
      'https://www.seino.co.jp/',
      'webmaster-inquiry-form@sei.co.jp',
      'https://www.instagram.com/seino_sg/',
      '',
      '',
    ),
  ],
  MY: [
    c(
      'Pos Malaysia (Pos Laju)',
      'https://www.posmalaysia.com.my/',
      'webmastercsu@pos.com.my',
      'https://www.instagram.com/posmalaysiaofficial/',
      'https://x.com/Pos4u',
      '',
    ),
    c(
      'GD Express (GDEX)',
      'https://www.gdexpress.com/',
      'customerservice@gdex.com.my',
      'https://www.instagram.com/gdexpressmalaysia/',
      'https://x.com/myGdex',
      '',
    ),
    c(
      'J&T Express Malaysia',
      'https://jtexpress.my/',
      'my.market@jet.co.id',
      'https://www.instagram.com/jntexpressmy/',
      '',
      '',
    ),
    c(
      'Ninja Van Malaysia',
      'https://www.ninjavan.co/en-my',
      'help.my@ninjavan.com',
      'https://www.instagram.com/ninjavanmalaysia/',
      '',
      'https://api.ninjavan.co/',
    ),
  ],
  MX: [
    c(
      'Correos de México (SEPOMEX)',
      'https://www.correosdemexico.gob.mx/',
      'atencionacliente@sepomex.gob.mx',
      'https://www.instagram.com/correosdemexico/',
      'https://x.com/CorreosMexico',
      '',
    ),
    c(
      'Estafeta',
      'https://www.estafeta.com/',
      'atencionaclientes@estafeta.com',
      'https://www.instagram.com/estafetamx/',
      'https://x.com/Estafeta',
      '',
    ),
    c(
      'DHL Express Mexico',
      'https://www.dhl.com/mx-es/home.html',
      'customerservicemx@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Mexico',
      'https://www.fedex.com/es-mx/home.html',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
  ],
  NZ: [
    c(
      'NZ Post / CourierPost',
      'https://www.nzpost.co.nz/',
      'consumerhelp@nzpost.co.nz',
      'https://www.instagram.com/nzpost/',
      'https://x.com/nzpost',
      '',
    ),
    c(
      'Aramex (Fastway Couriers NZ)',
      'https://www.aramex.co.nz/',
      'support@aramex.co.nz',
      'https://www.instagram.com/aramex/',
      'https://x.com/aramex',
      'https://ws.aramex.net/',
    ),
    c(
      'PBT Couriers',
      'https://www.pbt.com/',
      'customer.service@pbt.com',
      'https://www.instagram.com/pbtcouriers/',
      '',
      '',
    ),
    c(
      'Pace Couriers',
      'https://pacecouriers.co.nz/',
      'info@pacecouriers.co.nz',
      '',
      '',
      '',
    ),
  ],
  PG: [
    c(
      'Post PNG Limited',
      'https://www.postpng.com.pg/',
      'customerservice@postpng.com.pg',
      '',
      '',
      '',
    ),
    c(
      'DHL Express Papua New Guinea',
      'https://www.dhl.com/pg-en/home.html',
      'customerservicepg@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
    c(
      'FedEx Papua New Guinea (service partner)',
      'https://www.fedex.com/en-pg/home.html',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'UPS Papua New Guinea',
      'https://www.ups.com/pg/en',
      'help@ups.com',
      'https://www.instagram.com/ups/',
      'https://x.com/UPS',
      'https://onlinetools.ups.com/api/',
    ),
  ],
  PE: [
    c(
      'Serpost (Correos del Perú)',
      'https://www.serpost.com.pe/',
      'consultas_web@serpost.com.pe',
      'https://www.instagram.com/serpost/',
      '',
      '',
    ),
    c(
      'Olva Courier',
      'https://www.olvacourier.com/',
      'consultasolvacourier@olvacourier.com',
      'https://www.instagram.com/olvacourier/',
      'https://x.com/OlvaCourier',
      '',
    ),
    c(
      'Urbano Perú',
      'https://www.urbano.com.pe/',
      'corporativo.servicios@urbanoexpress.com.pe',
      'https://www.instagram.com/urbanoconectaperu/',
      'https://x.com/Urbanoconectaper',
      '',
    ),
    c(
      'Chazki',
      'https://chazki.pe/',
      'ayuda.chazki@chazki.com',
      'https://www.instagram.com/chazki.pe/',
      'https://x.com/chazki_pe',
      '',
    ),
  ],
  PH: [
    c(
      'LBC Express',
      'https://www.lbcexpress.com/',
      'customercare@lbcexpress.com',
      'https://www.instagram.com/lbcexpress/',
      'https://x.com/LBCexpress',
      '',
    ),
    c(
      'JRS Express',
      'https://www.jrs-express.com/',
      'help@jrs-express.com',
      'https://www.instagram.com/jrsexpress/',
      'https://x.com/jrsexpress',
      '',
    ),
    c(
      'J&T Express Philippines',
      'https://www.jtexpress.ph/',
      'customer@jtexpress.ph',
      'https://www.instagram.com/jntexpressph/',
      '',
      '',
    ),
    c(
      '2GO Express',
      'https://supplychain.2go.com.ph/',
      'customercare@2go.com.ph',
      'https://www.instagram.com/2goexpressofficial/',
      'https://x.com/2GOExpress',
      '',
    ),
  ],
  RU: [
    c(
      'Russian Post (Почта России)',
      'https://www.pochta.ru/',
      'callcenter@russianpost.ru',
      'https://www.instagram.com/russianpostofficial/',
      'https://x.com/russianpostoff',
      '',
    ),
    c(
      'CDEK (СДЭК)',
      'https://www.cdek.ru/',
      'info@cdek.ru',
      'https://www.instagram.com/cdek_official/',
      'https://x.com/cdek_official',
      'https://api.cdek.ru/',
    ),
    c(
      'Boxberry',
      'https://boxberry.ru/',
      'info@boxberry.ru',
      'https://www.instagram.com/boxberry_ru/',
      'https://x.com/boxberryru',
      'https://api.boxberry.ru/',
    ),
    c(
      'DHL Express Russia',
      'https://www.dhl.com/ru-ru/home.html',
      'customerserviceru@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
  ],
  SG: [
    c(
      'SingPost (Speedpost)',
      'https://www.singpost.com/',
      'askspp@singpost.com',
      'https://www.instagram.com/singpost/',
      'https://x.com/SingPost',
      '',
    ),
    c(
      'Ninja Van Singapore',
      'https://www.ninjavan.co/en-sg',
      'help.sg@ninjavan.com',
      'https://www.instagram.com/ninjavansg/',
      'https://x.com/ninjavan',
      'https://api.ninjavan.co/',
    ),
    c(
      'J&T Express Singapore',
      'https://www.jtexpress.sg/',
      'sg.customerservice@jet.co.id',
      'https://www.instagram.com/jntexpresssg/',
      '',
      '',
    ),
    c(
      'Qxpress',
      'https://www.qxpress.net/',
      'help@qxpress.net',
      'https://www.instagram.com/qxpress/',
      '',
      '',
    ),
  ],
  KR: [
    c(
      'CJ Logistics (CJ대한통운)',
      'https://www.cjlogistics.com/',
      'customercare@cjlogistics.com',
      'https://www.instagram.com/cjlogistics_global/',
      'https://x.com/CJ_Logistics',
      '',
    ),
    c(
      'Korea Post EMS',
      'https://www.epost.go.kr/',
      'webmaster@epost.go.kr',
      'https://www.instagram.com/koreapost_official/',
      '',
      '',
    ),
    c(
      'Hanjin Transportation',
      'https://www.hanjin.co.kr/',
      'webmaster@hanjin.co.kr',
      'https://www.instagram.com/hanjin_official/',
      '',
      '',
    ),
    c(
      'Lotte Global Logistics',
      'https://www.lotteglogis.com/',
      'webmaster@lotteglogis.com',
      'https://www.instagram.com/lotteglogis/',
      '',
      '',
    ),
  ],
  TW: [
    c(
      'Chunghwa Post',
      'https://www.post.gov.tw/',
      'webmaster@post.gov.tw',
      'https://www.instagram.com/chunghwa_post/',
      '',
      '',
    ),
    c(
      'Black Cat Logistics (T-Cat / Yamato Taiwan)',
      'https://www.t-cat.com.tw/',
      'service@t-cat.com.tw',
      'https://www.instagram.com/tcat.official/',
      '',
      '',
    ),
    c(
      'HCT Logistics',
      'https://www.hct.com.tw/',
      'service@hct.com.tw',
      'https://www.instagram.com/hct_logistics/',
      '',
      '',
    ),
    c(
      'Kerry TJ Logistics',
      'https://www.kerrytj.com/',
      'cservice@kerrytj.com',
      'https://www.instagram.com/kerrytjlogistics/',
      '',
      '',
    ),
  ],
  TH: [
    c(
      'Thailand Post EMS',
      'https://www.thailandpost.com/',
      '1232@thailandpost.com',
      'https://www.instagram.com/thailandpost.official/',
      'https://x.com/ThailandPostPLC',
      '',
    ),
    c(
      'Kerry Express Thailand',
      'https://th.kerryexpress.com/',
      'kes.support@kerrylogistics.com',
      'https://www.instagram.com/kerryexpress.th/',
      '',
      '',
    ),
    c(
      'Flash Express Thailand',
      'https://www.flashexpress.co.th/',
      'cs@flashexpress.com',
      'https://www.instagram.com/flashexpress.th/',
      'https://x.com/FlashExpressTH',
      '',
    ),
    c(
      'Ninja Van Thailand',
      'https://www.ninjavan.co/th-th',
      'help.th@ninjavan.com',
      'https://www.instagram.com/ninjavan_th/',
      'https://x.com/ninjavan',
      'https://api.ninjavan.co/',
    ),
  ],
  US: [
    c(
      'United States Postal Service (USPS)',
      'https://www.usps.com/',
      'USPSContactUs@usps.gov',
      'https://www.instagram.com/uspostalservice/',
      'https://x.com/USPS',
      'https://apis.usps.com/',
    ),
    c(
      'UPS United States',
      'https://www.ups.com/us/en/Home.page',
      'help@ups.com',
      'https://www.instagram.com/ups/',
      'https://x.com/UPS',
      'https://onlinetools.ups.com/api/',
    ),
    c(
      'FedEx Corporation',
      'https://www.fedex.com/en-us/home.html',
      'support@fedex.com',
      'https://www.instagram.com/fedex/',
      'https://x.com/FedEx',
      'https://apis.fedex.com/',
    ),
    c(
      'DHL Express United States',
      'https://www.dhl.com/us-en/home.html',
      'customerservice@dhl.com',
      'https://www.instagram.com/dhlexpress/',
      'https://x.com/DHLexpress',
      'https://api-eu.dhl.com/',
    ),
  ],
  VN: [
    c(
      'Vietnam Post (VNPost EMS)',
      'https://vnpost.vn/',
      'dichvu@vnpost.vn',
      'https://www.instagram.com/buu_chinh_viet_nam/',
      '',
      '',
    ),
    c(
      'Viettel Post',
      'https://viettelpost.com.vn/',
      'tracuuvandon@viettel.com.vn',
      'https://www.instagram.com/viettelpost_official/',
      '',
      '',
    ),
    c(
      'Giao Hang Tiet Kiem (GHTK)',
      'https://giaohangtietkiem.vn/',
      'cskh@giaohangtietkiem.vn',
      'https://www.instagram.com/ghtk.official/',
      'https://x.com/giaohangtietkie',
      '',
    ),
    c(
      'GHN (Giao Hàng Nhanh)',
      'https://ghn.vn/',
      'cskh@ghn.vn',
      'https://www.instagram.com/ghn.official/',
      'https://x.com/GHN_VN',
      '',
    ),
  ],
} satisfies Record<string, DomesticCourierService[]>
