import type { ApecMemberIsoCode } from './apecMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for APEC member economies
 * (informational; verify URLs, handles, forms portals, and API bases before production use).
 * Spans unified national IP offices (AU IP Australia industrial; CA CIPO; CN CNIPA; SG IPOS;
 * MY MyIPO; PH IPOPHL; TH DIP), split copyright / industrial regimes (US Copyright Office +
 * USPTO; JP Agency for Cultural Affairs + JPO; KR KCC + KIPO; MX INDAUTOR + IMPI; VN COV +
 * NOIP), and APEC “economy” members HK and TW. `apiEndpoint` is populated only where a
 * documented public developer API exists (notably USPTO Open Data Portal). Verify periodically
 * against WIPO’s directory of IP offices:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const APEC_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  ApecMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AU: roster(
    ip(
      'copyright',
      'Australian Government — Attorney-General\'s Department (Copyright)',
      'https://www.ag.gov.au/rights-and-protections/copyright',
      '',
      '',
      '',
      'https://www.ag.gov.au/rights-and-protections/copyright',
    ),
    ip(
      'trademarks',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
    ip(
      'patents',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
  ),
  BN: roster(
    ip(
      'copyright',
      'Brunei Darussalam Intellectual Property Office (BruIPO) — copyright',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'trademarks',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'patents',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
  ),
  CA: roster(
    ip(
      'copyright',
      'Canadian Intellectual Property Office (CIPO) — copyright',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'trademarks',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'patents',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
  ),
  CL: roster(
    ip(
      'copyright',
      'Ministerio de las Culturas, las Artes y el Patrimonio — Dirección de Derecho de Autor',
      'https://www.cultura.gob.cl',
      '',
      'https://x.com/mincultura',
      '',
      'https://www.cultura.gob.cl',
    ),
    ip(
      'trademarks',
      'Instituto Nacional de Propiedad Industrial (INAPI Chile)',
      'https://www.inapi.cl',
      'contacto@inapi.cl',
      'https://x.com/INAPIChile',
      'https://www.linkedin.com/company/inapi-chile/',
      'https://tramites.inapi.cl',
    ),
    ip(
      'patents',
      'Instituto Nacional de Propiedad Industrial (INAPI Chile)',
      'https://www.inapi.cl',
      'contacto@inapi.cl',
      'https://x.com/INAPIChile',
      'https://www.linkedin.com/company/inapi-chile/',
      'https://tramites.inapi.cl',
    ),
  ),
  CN: roster(
    ip(
      'copyright',
      'National Copyright Administration of the People\'s Republic of China (NCAC)',
      'https://www.ncac.gov.cn',
      '',
      '',
      '',
      'https://www.ncac.gov.cn',
    ),
    ip(
      'trademarks',
      'China National Intellectual Property Administration (CNIPA)',
      'https://www.cnipa.gov.cn',
      '',
      '',
      '',
      'https://cponline.cnipa.gov.cn',
    ),
    ip(
      'patents',
      'China National Intellectual Property Administration (CNIPA)',
      'https://www.cnipa.gov.cn',
      '',
      '',
      '',
      'https://cponline.cnipa.gov.cn',
    ),
  ),
  HK: roster(
    ip(
      'copyright',
      'Intellectual Property Department (Copyright)',
      'https://www.ipd.gov.hk',
      'ipd@ipd.gov.hk',
      '',
      '',
      'https://www.ipd.gov.hk/en/copyright/index.htm',
    ),
    ip(
      'trademarks',
      'Intellectual Property Department (IPD)',
      'https://www.ipd.gov.hk',
      'ipd@ipd.gov.hk',
      '',
      '',
      'https://www.ipd.gov.hk/en/forms-filing/index.htm',
    ),
    ip(
      'patents',
      'Intellectual Property Department (IPD)',
      'https://www.ipd.gov.hk',
      'ipd@ipd.gov.hk',
      '',
      '',
      'https://www.ipd.gov.hk/en/forms-filing/index.htm',
    ),
  ),
  ID: roster(
    ip(
      'copyright',
      'Directorate General of Intellectual Property (DGIP) — copyright',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'trademarks',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'patents',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
  ),
  JP: roster(
    ip(
      'copyright',
      'Agency for Cultural Affairs (Government of Japan — Copyright)',
      'https://www.bunka.go.jp/english/',
      '',
      '',
      '',
      'https://www.bunka.go.jp/english/copyright/index.html',
    ),
    ip(
      'trademarks',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
    ip(
      'patents',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
  ),
  MY: roster(
    ip(
      'copyright',
      'Intellectual Property Corporation of Malaysia (MyIPO) — copyright',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'trademarks',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'patents',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
  ),
  MX: roster(
    ip(
      'copyright',
      'Instituto Nacional del Derecho de Autor (INDAUTOR)',
      'https://www.indautor.gob.mx',
      'indautor@indautor.gob.mx',
      'https://x.com/INDAUTORMX',
      '',
      'https://www.indautor.gob.mx/servicios/',
    ),
    ip(
      'trademarks',
      'Mexican Institute of Industrial Property (IMPI)',
      'https://www.gob.mx/impi',
      'impi@impi.gob.mx',
      'https://x.com/IMPI_MX',
      'https://www.linkedin.com/company/impi/',
      'https://www.gob.mx/impi/acciones-y-programas/servicios-en-linea',
    ),
    ip(
      'patents',
      'Mexican Institute of Industrial Property (IMPI)',
      'https://www.gob.mx/impi',
      'impi@impi.gob.mx',
      'https://x.com/IMPI_MX',
      'https://www.linkedin.com/company/impi/',
      'https://www.gob.mx/impi/acciones-y-programas/servicios-en-linea',
    ),
  ),
  NZ: roster(
    ip(
      'copyright',
      'Manatū Taonga — Ministry for Culture and Heritage (Copyright)',
      'https://www.mch.govt.nz',
      'info@mch.govt.nz',
      '',
      '',
      'https://www.mch.govt.nz/copyright',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
    ip(
      'patents',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
  ),
  PG: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Papua New Guinea (IPOPNG) — copyright',
      'https://www.ipopng.gov.pg',
      'info@ipopng.gov.pg',
      '',
      '',
      'https://www.ipopng.gov.pg',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Papua New Guinea (IPOPNG)',
      'https://www.ipopng.gov.pg',
      'info@ipopng.gov.pg',
      '',
      '',
      'https://www.ipopng.gov.pg',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Papua New Guinea (IPOPNG)',
      'https://www.ipopng.gov.pg',
      'info@ipopng.gov.pg',
      '',
      '',
      'https://www.ipopng.gov.pg',
    ),
  ),
  PE: roster(
    ip(
      'copyright',
      'National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI) — copyright',
      'https://www.indecopi.gob.pe',
      'consultas@indecopi.gob.pe',
      'https://x.com/INDECOPI',
      'https://www.linkedin.com/company/indecopi/',
      'https://www.indecopi.gob.pe/servicios-en-linea',
    ),
    ip(
      'trademarks',
      'National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI)',
      'https://www.indecopi.gob.pe',
      'consultas@indecopi.gob.pe',
      'https://x.com/INDECOPI',
      'https://www.linkedin.com/company/indecopi/',
      'https://www.indecopi.gob.pe/servicios-en-linea',
    ),
    ip(
      'patents',
      'National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI)',
      'https://www.indecopi.gob.pe',
      'consultas@indecopi.gob.pe',
      'https://x.com/INDECOPI',
      'https://www.linkedin.com/company/indecopi/',
      'https://www.indecopi.gob.pe/servicios-en-linea',
    ),
  ),
  PH: roster(
    ip(
      'copyright',
      'Intellectual Property Office of the Philippines (IPOPHL) — copyright',
      'https://www.ipophil.gov.ph',
      'info@ipophil.gov.ph',
      'https://x.com/IPOPHL',
      'https://www.linkedin.com/company/intellectual-property-office-of-the-philippines/',
      'https://epayment.ipophil.gov.ph/',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of the Philippines (IPOPHL)',
      'https://www.ipophil.gov.ph',
      'info@ipophil.gov.ph',
      'https://x.com/IPOPHL',
      'https://www.linkedin.com/company/intellectual-property-office-of-the-philippines/',
      'https://epayment.ipophil.gov.ph/',
    ),
    ip(
      'patents',
      'Intellectual Property Office of the Philippines (IPOPHL)',
      'https://www.ipophil.gov.ph',
      'info@ipophil.gov.ph',
      'https://x.com/IPOPHL',
      'https://www.linkedin.com/company/intellectual-property-office-of-the-philippines/',
      'https://epayment.ipophil.gov.ph/',
    ),
  ),
  RU: roster(
    ip(
      'copyright',
      'Ministry of Culture of the Russian Federation — copyright',
      'https://culture.gov.ru',
      '',
      '',
      '',
      'https://culture.gov.ru',
    ),
    ip(
      'trademarks',
      'Federal Service for Intellectual Property (Rospatent)',
      'https://rospatent.gov.ru',
      'fips@rupto.ru',
      '',
      '',
      'https://rospatent.gov.ru/ru/services',
    ),
    ip(
      'patents',
      'Federal Service for Intellectual Property (Rospatent)',
      'https://rospatent.gov.ru',
      'fips@rupto.ru',
      '',
      '',
      'https://rospatent.gov.ru/ru/services',
    ),
  ),
  SG: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Singapore (IPOS) — copyright',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
  ),
  KR: roster(
    ip(
      'copyright',
      'Korea Copyright Commission (KCC)',
      'https://www.copyright.or.kr',
      'help@copyright.or.kr',
      '',
      '',
      'https://www.copyright.or.kr',
    ),
    ip(
      'trademarks',
      'Korean Intellectual Property Office (KIPO)',
      'https://www.kipo.go.kr',
      '',
      '',
      '',
      'https://www.patent.go.kr',
    ),
    ip(
      'patents',
      'Korean Intellectual Property Office (KIPO)',
      'https://www.kipo.go.kr',
      '',
      '',
      '',
      'https://www.patent.go.kr',
    ),
  ),
  TW: roster(
    ip(
      'copyright',
      'Bureau of Copyright, Ministry of Culture (Taiwan)',
      'https://www.moc.gov.tw',
      '',
      '',
      '',
      'https://www.moc.gov.tw',
    ),
    ip(
      'trademarks',
      'Taiwan Intellectual Property Office (TIPO)',
      'https://www.tipo.gov.tw',
      'tiponet@tipo.gov.tw',
      '',
      '',
      'https://tiponet.tipo.gov.tw',
    ),
    ip(
      'patents',
      'Taiwan Intellectual Property Office (TIPO)',
      'https://www.tipo.gov.tw',
      'tiponet@tipo.gov.tw',
      '',
      '',
      'https://tiponet.tipo.gov.tw',
    ),
  ),
  TH: roster(
    ip(
      'copyright',
      'Department of Intellectual Property (DIP) — copyright',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
    ip(
      'trademarks',
      'Department of Intellectual Property (DIP)',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
    ip(
      'patents',
      'Department of Intellectual Property (DIP)',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
  ),
  US: roster(
    ip(
      'copyright',
      'U.S. Copyright Office',
      'https://www.copyright.gov',
      '',
      'https://x.com/CopyrightOffice',
      'https://www.linkedin.com/company/us-copyright-office/',
      'https://www.copyright.gov/registration/',
    ),
    ip(
      'trademarks',
      'United States Patent and Trademark Office (USPTO)',
      'https://www.uspto.gov',
      '',
      'https://x.com/uspto',
      'https://www.linkedin.com/company/uspto/',
      'https://www.uspto.gov/apply',
      'https://developer.uspto.gov/',
    ),
    ip(
      'patents',
      'United States Patent and Trademark Office (USPTO)',
      'https://www.uspto.gov',
      '',
      'https://x.com/uspto',
      'https://www.linkedin.com/company/uspto/',
      'https://www.uspto.gov/apply',
      'https://developer.uspto.gov/',
    ),
  ),
  VN: roster(
    ip(
      'copyright',
      'Copyright Office of Vietnam (COV)',
      'https://cov.gov.vn',
      '',
      '',
      '',
      'https://cov.gov.vn',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Vietnam (NOIP)',
      'https://www.noip.gov.vn',
      'noip@noip.gov.vn',
      '',
      '',
      'https://www.noip.gov.vn/en-US/OnlineFiling',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Vietnam (NOIP)',
      'https://www.noip.gov.vn',
      'noip@noip.gov.vn',
      '',
      '',
      'https://www.noip.gov.vn/en-US/OnlineFiling',
    ),
  ),
}
