import type { ApecMemberIsoCode } from './apecMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per APEC economy (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const APEC_MAIN_INTERNATIONAL_AIRPORTS: Record<ApecMemberIsoCode, MainInternationalAirport> = {
  AU: {
    name: 'Sydney Kingsford Smith Airport (SYD)',
    website: 'https://www.sydneyairport.com.au/',
    email: 'info@sydneyairport.com.au',
    twitter: 'https://x.com/SydneyAirport',
    instagram: 'https://www.instagram.com/sydneyairport/',
    linkedin: 'https://www.linkedin.com/company/sydney-airport/',
    apiEndpoint: '',
  },
  BN: {
    name: 'Brunei International Airport (BWN)',
    website: 'https://www.bruneiair.com/',
    email: 'info@bruneiair.com',
    twitter: 'https://x.com/BruneiAirport',
    instagram: 'https://www.instagram.com/bruneiairport/',
    linkedin: 'https://www.linkedin.com/company/brunei-international-airport/',
    apiEndpoint: '',
  },
  CA: {
    name: 'Toronto Pearson International Airport (YYZ)',
    website: 'https://www.torontopearson.com/',
    email: 'info@torontopearson.com',
    twitter: 'https://x.com/TorontoPearson',
    instagram: 'https://www.instagram.com/torontopearson/',
    linkedin: 'https://www.linkedin.com/company/toronto-pearson-international-airport/',
    apiEndpoint: '',
  },
  CL: {
    name: 'Arturo Merino Benítez International Airport (SCL)',
    website: 'https://www.nuestroaeropuerto.cl/',
    email: 'contacto@nuestroaeropuerto.cl',
    twitter: 'https://x.com/AeropuertoSCL',
    instagram: 'https://www.instagram.com/aeropuertoscl/',
    linkedin: 'https://www.linkedin.com/company/nuevo-aeropuerto-internacional-arturo-merino-benitez/',
    apiEndpoint: '',
  },
  CN: {
    name: 'Beijing Capital International Airport (PEK)',
    website: 'https://www.bcia.com.cn/',
    email: 'service@bcia.com.cn',
    twitter: 'https://x.com/BeijingAirport',
    instagram: 'https://www.instagram.com/beijingairport/',
    linkedin: 'https://www.linkedin.com/company/beijing-capital-international-airport/',
    apiEndpoint: '',
  },
  HK: {
    name: 'Hong Kong International Airport (HKG)',
    website: 'https://www.hongkongairport.com/',
    email: 'enquiry@hkia.gov.hk',
    twitter: 'https://x.com/hkairport',
    instagram: 'https://www.instagram.com/hkairport/',
    linkedin: 'https://www.linkedin.com/company/hong-kong-international-airport/',
    apiEndpoint: '',
  },
  ID: {
    name: 'Soekarno-Hatta International Airport (CGK)',
    website: 'https://soekarnohatta-airport.co.id/',
    email: 'info@soekarnohatta-airport.co.id',
    twitter: 'https://x.com/SoettaAirport',
    instagram: 'https://www.instagram.com/soettaairport/',
    linkedin: 'https://www.linkedin.com/company/soekarno-hatta-international-airport/',
    apiEndpoint: '',
  },
  JP: {
    name: 'Tokyo Haneda Airport (HND)',
    website: 'https://www.haneda-airport.jp/',
    email: 'info@haneda-airport.jp',
    twitter: 'https://x.com/TokyoHaneda',
    instagram: 'https://www.instagram.com/tokyohaneda/',
    linkedin: 'https://www.linkedin.com/company/tokyo-international-airport/',
    apiEndpoint: '',
  },
  MY: {
    name: 'Kuala Lumpur International Airport (KUL)',
    website: 'https://www.klia.com.my/',
    email: 'info@klia.com.my',
    twitter: 'https://x.com/KLIA_Malaysia',
    instagram: 'https://www.instagram.com/klia_malaysia/',
    linkedin: 'https://www.linkedin.com/company/malaysia-airports/',
    apiEndpoint: '',
  },
  MX: {
    name: 'Mexico City International Airport (MEX)',
    website: 'https://www.aicm.com.mx/',
    email: 'contacto@aicm.com.mx',
    twitter: 'https://x.com/AICM_mx',
    instagram: 'https://www.instagram.com/aicm_mx/',
    linkedin: 'https://www.linkedin.com/company/aeropuerto-internacional-de-la-ciudad-de-mexico/',
    apiEndpoint: '',
  },
  NZ: {
    name: 'Auckland Airport (AKL)',
    website: 'https://www.aucklandairport.co.nz/',
    email: 'info@aucklandairport.co.nz',
    twitter: 'https://x.com/AucklandAirport',
    instagram: 'https://www.instagram.com/aucklandairport/',
    linkedin: 'https://www.linkedin.com/company/auckland-airport/',
    apiEndpoint: '',
  },
  PG: {
    name: 'Jacksons International Airport (POM)',
    website: 'https://www.nac.com.pg/',
    email: 'info@nac.com.pg',
    twitter: 'https://x.com/NAC_PNG',
    instagram: 'https://www.instagram.com/nac_png/',
    linkedin: 'https://www.linkedin.com/company/national-airports-corporation-png/',
    apiEndpoint: '',
  },
  PE: {
    name: 'Jorge Chávez International Airport (LIM)',
    website: 'https://www.lima-airport.com/',
    email: 'info@lima-airport.com',
    twitter: 'https://x.com/LimaAirport',
    instagram: 'https://www.instagram.com/limaairport/',
    linkedin: 'https://www.linkedin.com/company/lima-airport-partners/',
    apiEndpoint: '',
  },
  PH: {
    name: 'Ninoy Aquino International Airport (MNL)',
    website: 'https://www.miaa.gov.ph/',
    email: 'info@miaa.gov.ph',
    twitter: 'https://x.com/MIAA_Official',
    instagram: 'https://www.instagram.com/miaa_official/',
    linkedin: 'https://www.linkedin.com/company/manila-international-airport-authority/',
    apiEndpoint: '',
  },
  RU: {
    name: 'Sheremetyevo International Airport (SVO)',
    website: 'https://www.svo.aero/',
    email: 'info@svo.aero',
    twitter: 'https://x.com/SVO_airport',
    instagram: 'https://www.instagram.com/svo_airport/',
    linkedin: 'https://www.linkedin.com/company/sheremetyevo-international-airport/',
    apiEndpoint: '',
  },
  SG: {
    name: 'Singapore Changi Airport (SIN)',
    website: 'https://www.changiairport.com/',
    email: 'feedback@changiairport.com',
    twitter: 'https://x.com/ChangiAirport',
    instagram: 'https://www.instagram.com/changiairport/',
    linkedin: 'https://www.linkedin.com/company/changi-airport-group/',
    apiEndpoint: '',
  },
  KR: {
    name: 'Incheon International Airport (ICN)',
    website: 'https://www.airport.kr/',
    email: 'help@airport.kr',
    twitter: 'https://x.com/IncheonAirport',
    instagram: 'https://www.instagram.com/incheonairport/',
    linkedin: 'https://www.linkedin.com/company/incheon-international-airport-corporation/',
    apiEndpoint: '',
  },
  TW: {
    name: 'Taiwan Taoyuan International Airport (TPE)',
    website: 'https://www.taoyuan-airport.com/',
    email: 'service@taoyuan-airport.com',
    twitter: 'https://x.com/TaoyuanAirport',
    instagram: 'https://www.instagram.com/taoyuanairport/',
    linkedin: 'https://www.linkedin.com/company/taoyuan-international-airport-corporation/',
    apiEndpoint: '',
  },
  TH: {
    name: 'Suvarnabhumi Airport (BKK)',
    website: 'https://suvarnabhumi.airportthai.co.th/',
    email: 'info@airportthai.co.th',
    twitter: 'https://x.com/AOT_BKK',
    instagram: 'https://www.instagram.com/suvarnabhumi_airport/',
    linkedin: 'https://www.linkedin.com/company/airports-of-thailand/',
    apiEndpoint: '',
  },
  US: {
    name: 'Los Angeles International Airport (LAX)',
    website: 'https://www.flylax.com/',
    email: 'info@lawa.org',
    twitter: 'https://x.com/flyLAXairport',
    instagram: 'https://www.instagram.com/flylax/',
    linkedin: 'https://www.linkedin.com/company/los-angeles-world-airports/',
    apiEndpoint: '',
  },
  VN: {
    name: 'Noi Bai International Airport (HAN)',
    website: 'https://www.noibaiairport.vn/',
    email: 'info@noibaiairport.vn',
    twitter: 'https://x.com/NoiBaiAirport',
    instagram: 'https://www.instagram.com/noibaiairport/',
    linkedin: 'https://www.linkedin.com/company/noi-bai-international-airport/',
    apiEndpoint: '',
  },
}
