import type { ApecMemberIsoCode } from './apecMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2
 * for APEC member economies (informational; verify against USGS Mineral Commodity Summaries
 * and UN Comtrade periodically). Hydrocarbon exporters carry `Carbon (C)` and `Hydrogen (H)`;
 * semiconductor-led exporters carry `Silicon (Si)`.
 */
export const APEC_MAIN_EXPORTED_ELEMENTS: Record<ApecMemberIsoCode, MainExportedElements> = {
  AU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Copper (Cu)',
    'Lithium (Li)',
    'Nickel (Ni)',
    'Zinc (Zn)',
  ),
  BN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  CA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Nickel (Ni)',
    'Iron (Fe)',
    'Gold (Au)',
    'Uranium (U)',
    'Potassium (K)',
  ),
  CL: e(
    'Copper (Cu)',
    'Lithium (Li)',
    'Molybdenum (Mo)',
    'Silver (Ag)',
    'Gold (Au)',
    'Iron (Fe)',
    'Iodine (I)',
  ),
  CN: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Gold (Au)',
    'Carbon (C)',
  ),
  HK: e(
    'Gold (Au)',
    'Silver (Ag)',
    'Copper (Cu)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Carbon (C)',
  ),
  ID: e(
    'Carbon (C)',
    'Nickel (Ni)',
    'Copper (Cu)',
    'Tin (Sn)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Hydrogen (H)',
  ),
  JP: e(
    'Iron (Fe)',
    'Copper (Cu)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Gold (Au)',
    'Silver (Ag)',
    'Titanium (Ti)',
  ),
  MY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Silicon (Si)',
  ),
  MX: e(
    'Silver (Ag)',
    'Gold (Au)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Iron (Fe)',
    'Carbon (C)',
  ),
  NZ: e(
    'Gold (Au)',
    'Iron (Fe)',
    'Silver (Ag)',
    'Titanium (Ti)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Silicon (Si)',
  ),
  PG: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Silver (Ag)',
    'Carbon (C)',
    'Hydrogen (H)',
  ),
  PE: e(
    'Copper (Cu)',
    'Silver (Ag)',
    'Gold (Au)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Tin (Sn)',
    'Iron (Fe)',
  ),
  PH: e(
    'Nickel (Ni)',
    'Copper (Cu)',
    'Gold (Au)',
    'Iron (Fe)',
    'Chromium (Cr)',
    'Cobalt (Co)',
    'Silver (Ag)',
  ),
  RU: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Palladium (Pd)',
    'Platinum (Pt)',
  ),
  SG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Silicon (Si)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
  ),
  KR: e(
    'Iron (Fe)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Gold (Au)',
    'Titanium (Ti)',
  ),
  TW: e(
    'Silicon (Si)',
    'Copper (Cu)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Gallium (Ga)',
    'Germanium (Ge)',
  ),
  TH: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Gold (Au)',
    'Silicon (Si)',
  ),
  US: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Iron (Fe)',
    'Gold (Au)',
    'Helium (He)',
  ),
  VN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Tin (Sn)',
  ),
}
