import type { ApecMemberIsoCode } from './apecMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per APEC member economy (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const APEC_MAIN_INTERNATIONAL_SEAPORTS: Record<ApecMemberIsoCode, MainInternationalSeaport> = {
  AU: seaport(
    'Port of Melbourne',
    'https://www.portofmelbourne.com/',
    'info@portofmelbourne.com',
    'https://x.com/PortOfMelbourne',
    'https://www.instagram.com/portofmelbourne/',
    'https://www.linkedin.com/company/port-of-melbourne/',
    'customs@abf.gov.au',
    'https://www.abf.gov.au',
    'Australian Border Force — Port of Melbourne, Melbourne, Australia',
  ),
  BN: seaport(
    'Muara Port',
    'https://www.mtc.com.bn/',
    'info@mtc.com.bn',
    'https://x.com/MuaraPort',
    'https://www.instagram.com/muaraport/',
    'https://www.linkedin.com/company/muara-port/',
    'customs@rcs.gov.bn',
    'https://www.rcs.gov.bn',
    'Royal Customs and Excise Department — Muara Port, Muara, Brunei',
  ),
  CA: seaport(
    'Port of Vancouver',
    'https://www.portvancouver.com/',
    'info@portvancouver.com',
    'https://x.com/portvancouver',
    'https://www.instagram.com/portvancouver/',
    'https://www.linkedin.com/company/port-of-vancouver/',
    'cbcsa-client-services@cbsa-asfc.gc.ca',
    'https://www.cbsa-asfc.gc.ca',
    'Canada Border Services Agency — Port of Vancouver, Vancouver, Canada',
  ),
  CL: seaport(
    'Port of San Antonio',
    'https://www.portsanantonio.cl/',
    'contacto@portsanantonio.cl',
    'https://x.com/PortSanAntonioCL',
    'https://www.instagram.com/portsanantonio/',
    'https://www.linkedin.com/company/puerto-san-antonio/',
    'aduana@aduana.cl',
    'https://www.aduana.cl',
    'Servicio Nacional de Aduanas — Puerto San Antonio, San Antonio, Chile',
  ),
  CN: seaport(
    'Port of Shanghai',
    'https://www.portshanghai.com.cn/',
    'info@portshanghai.com.cn',
    'https://x.com/PortShanghai',
    'https://www.instagram.com/portshanghai/',
    'https://www.linkedin.com/company/shanghai-international-port-group/',
    'customs@customs.gov.cn',
    'https://www.customs.gov.cn',
    'General Administration of Customs — Port of Shanghai, Shanghai, China',
  ),
  HK: seaport(
    'Port of Hong Kong (Kwai Tsing)',
    'https://www.pdc.gov.hk/',
    'enquiry@pdc.gov.hk',
    'https://x.com/HKPortDevelopment',
    'https://www.instagram.com/hkportdevelopment/',
    'https://www.linkedin.com/company/port-development-council/',
    'enquiry_customs@customs.gov.hk',
    'https://www.customs.gov.hk',
    'Hong Kong Customs and Excise — Kwai Tsing Container Terminals, Hong Kong',
  ),
  ID: seaport(
    'Port of Tanjung Priok (Jakarta)',
    'https://www.pelindo.co.id/',
    'info@pelindo.co.id',
    'https://x.com/Pelindo',
    'https://www.instagram.com/pelindo/',
    'https://www.linkedin.com/company/pelindo/',
    'contact.center@beacukai.go.id',
    'https://www.beacukai.go.id',
    'Direktorat Jenderal Bea dan Cukai — Pelabuhan Tanjung Priok, Jakarta, Indonesia',
  ),
  JP: seaport(
    'Port of Yokohama',
    'https://www.portof_yokohama.jp/',
    'info@portof_yokohama.jp',
    'https://x.com/PortOfYokohama',
    'https://www.instagram.com/portofyokohama/',
    'https://www.linkedin.com/company/port-and-harbor-bureau-city-of-yokohama/',
    'zeimu@customs.go.jp',
    'https://www.customs.go.jp',
    'Yokohama Customs — Port of Yokohama, Yokohama, Japan',
  ),
  MY: seaport(
    'Port Klang',
    'https://www.pka.gov.my/',
    'info@pka.gov.my',
    'https://x.com/PortKlang',
    'https://www.instagram.com/portklang/',
    'https://www.linkedin.com/company/port-klang-authority/',
    'customs@customs.gov.my',
    'https://www.customs.gov.my',
    'Royal Malaysian Customs — Port Klang, Selangor, Malaysia',
  ),
  MX: seaport(
    'Port of Manzanillo',
    'https://www.puertomanzanillo.com.mx/',
    'contacto@puertomanzanillo.com.mx',
    'https://x.com/PuertoManzanillo',
    'https://www.instagram.com/puertomanzanillo/',
    'https://www.linkedin.com/company/puerto-manzanillo/',
    'atencion@sat.gob.mx',
    'https://www.sat.gob.mx',
    'SAT Aduanas — Puerto de Manzanillo, Manzanillo, Mexico',
  ),
  NZ: seaport(
    'Port of Tauranga',
    'https://www.port-tauranga.co.nz/',
    'info@port-tauranga.co.nz',
    'https://x.com/PortofTauranga',
    'https://www.instagram.com/portoftauranga/',
    'https://www.linkedin.com/company/port-of-tauranga/',
    'customs@customs.govt.nz',
    'https://www.customs.govt.nz',
    'New Zealand Customs Service — Port of Tauranga, Tauranga, New Zealand',
  ),
  PG: seaport(
    'Port of Lae',
    'https://www.pngports.com.pg/',
    'info@pngports.com.pg',
    'https://x.com/PNGPorts',
    'https://www.instagram.com/pngports/',
    'https://www.linkedin.com/company/png-ports-corporation/',
    'customs@irc.gov.pg',
    'https://www.irc.gov.pg',
    'PNG Customs — Port of Lae, Lae, Papua New Guinea',
  ),
  PE: seaport(
    'Port of Callao',
    'https://www.enapu.com.pe/',
    'info@enapu.com.pe',
    'https://x.com/ENAPU_Peru',
    'https://www.instagram.com/enapu_peru/',
    'https://www.linkedin.com/company/enapu/',
    'consultas@sunat.gob.pe',
    'https://www.sunat.gob.pe',
    'SUNAT Aduanas — Puerto del Callao, Callao, Peru',
  ),
  PH: seaport(
    'Port of Manila (South Harbor)',
    'https://www.ppa.com.ph/',
    'info@ppa.com.ph',
    'https://x.com/PPA_Official',
    'https://www.instagram.com/ppa_official/',
    'https://www.linkedin.com/company/philippine-ports-authority/',
    'customs@customs.gov.ph',
    'https://www.customs.gov.ph',
    'Bureau of Customs — Port of Manila, Manila, Philippines',
  ),
  RU: seaport(
    'Port of Vladivostok',
    'https://www.vmtp.ru/',
    'info@vmtp.ru',
    'https://x.com/VladivostokPort',
    'https://www.instagram.com/vladivostokport/',
    'https://www.linkedin.com/company/vladivostok-sea-port/',
    'customs@fts.customs.ru',
    'https://www.customs.ru',
    'Far Eastern Customs — Port of Vladivostok, Vladivostok, Russia',
  ),
  SG: seaport(
    'Port of Singapore',
    'https://www.mpa.gov.sg/',
    'MPA_Enquiry@mpa.gov.sg',
    'https://x.com/Mpa_Singapore',
    'https://www.instagram.com/mpa_singapore/',
    'https://www.linkedin.com/company/maritime-and-port-authority-of-singapore/',
    'customs_support@customs.gov.sg',
    'https://www.customs.gov.sg',
    'Singapore Customs — PSA Singapore Terminals, Singapore',
  ),
  KR: seaport(
    'Port of Busan',
    'https://www.busanpa.com/',
    'info@busanpa.com',
    'https://x.com/BusanPort',
    'https://www.instagram.com/busanport/',
    'https://www.linkedin.com/company/busan-port-authority/',
    'customs@customs.go.kr',
    'https://www.customs.go.kr',
    'Korea Customs Service — Port of Busan, Busan, South Korea',
  ),
  TW: seaport(
    'Port of Kaohsiung',
    'https://www.khb.gov.tw/',
    'service@khb.gov.tw',
    'https://x.com/KaohsiungPort',
    'https://www.instagram.com/kaohsiungport/',
    'https://www.linkedin.com/company/kaohsiung-harbor-bureau/',
    'customs@customs.gov.tw',
    'https://web.customs.gov.tw',
    'Customs Administration — Port of Kaohsiung, Kaohsiung, Chinese Taipei',
  ),
  TH: seaport(
    'Port of Laem Chabang',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'info@customs.go.th',
    'https://www.customs.go.th',
    'Thai Customs — Laem Chabang Port, Chonburi, Thailand',
  ),
  US: seaport(
    'Port of Los Angeles',
    'https://www.portoflosangeles.org/',
    'info@portoflosangeles.org',
    'https://x.com/portofla',
    'https://www.instagram.com/portofla/',
    'https://www.linkedin.com/company/port-of-los-angeles/',
    'losangeles.cbp@cbp.dhs.gov',
    'https://www.cbp.gov',
    'U.S. Customs and Border Protection — Port of Los Angeles, San Pedro, United States',
  ),
  VN: seaport(
    'Port of Ho Chi Minh City (Cát Lái)',
    'https://www.saigonnewport.com.vn/',
    'info@saigonnewport.com.vn',
    'https://x.com/SaigonNewport',
    'https://www.instagram.com/saigonnewport/',
    'https://www.linkedin.com/company/saigon-newport-corporation/',
    'contact@customs.gov.vn',
    'https://www.customs.gov.vn',
    'General Department of Vietnam Customs — Cát Lái Port, Ho Chi Minh City, Vietnam',
  ),
}
