import type { NationalBankingInstitution } from './types'
import type { ApecMemberIsoCode } from './apecMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per APEC member economy.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const APEC_NATIONAL_BANKING_INSTITUTIONS: Record<
  ApecMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AU: [
    bank(
      'Commonwealth Bank of Australia',
      '+61 13 2221',
      'Ground Floor, Tower 1, 201 Sussex Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/commbank/id310251020',
      'https://play.google.com/store/apps/details?id=com.commbank.netbank',
      'https://www.commbank.com.au',
      'customercare@cba.com.au',
      'https://twitter.com/CommBank',
      'https://www.instagram.com/commbank/',
      'https://www.linkedin.com/company/commonwealth-bank/',
      '',
      'CTBAAU2S',
      'https://api.commbank.com.au',
    ),
    bank(
      'Westpac Banking Corporation',
      '+61 13 2032',
      '275 Kent Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/westpac-mobile-banking/id284826145',
      'https://play.google.com/store/apps/details?id=org.westpac.bank',
      'https://www.westpac.com.au',
      'customercare@westpac.com.au',
      'https://twitter.com/Westpac',
      'https://www.instagram.com/westpac/',
      'https://www.linkedin.com/company/westpac/',
      '',
      'WPACAU2S',
      'https://developer.westpac.com.au',
    ),
    bank(
      'Australia and New Zealand Banking Group',
      '+61 13 13 14',
      '833 Collins Street, Docklands, VIC, Australia',
      'https://apps.apple.com/au/app/anz-australia/id385348415',
      'https://play.google.com/store/apps/details?id=com.anz.android',
      'https://www.anz.com.au',
      'contactus@anz.com',
      'https://twitter.com/ANZ_AU',
      'https://www.instagram.com/anz_au/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBAU3M',
      'https://developer.anz.com',
    ),
  ],
  BN: [
    bank(
      'Baiduri Bank',
      '+673 2449666',
      'Baiduri Community Space, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/baiduri-b-token/id1414199588',
      'https://play.google.com/store/apps/details?id=com.baiduri.mobilebanking',
      'https://www.baiduri.com.bn',
      'info@baiduri.com.bn',
      'https://twitter.com/baiduribank',
      'https://www.instagram.com/baiduribank/',
      'https://www.linkedin.com/company/baiduri-bank/',
      '',
      'BAIDBNDX',
      '',
    ),
    bank(
      'Bank Islam Brunei Darussalam',
      '+673 2238181',
      'Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/bibd-nexgen-wallet/id1541812683',
      'https://play.google.com/store/apps/details?id=com.bibd.nexgen',
      'https://www.bibd.com.bn',
      'enquiry@bibd.com.bn',
      'https://twitter.com/BIBDBrunei',
      'https://www.instagram.com/bibdbrunei/',
      'https://www.linkedin.com/company/bibd/',
      '',
      'BIBDBNBB',
      '',
    ),
    bank(
      'Standard Chartered Brunei',
      '+673 2658000',
      'Jalan Sultan, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/sg/app/sc-mobile-singapore/id445120671',
      'https://play.google.com/store/apps/details?id=com.sc.breezenxt.bn',
      'https://www.sc.com/bn',
      'clientcare.bnd@sc.com',
      'https://twitter.com/StanChart',
      'https://www.instagram.com/stanchart/',
      'https://www.linkedin.com/company/standard-chartered-bank/',
      '',
      'SCBLBNDX',
      '',
    ),
  ],
  CA: [
    bank(
      'Royal Bank of Canada',
      '+1 416 974 5151',
      '200 Bay Street, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/rbc-mobile/id407597290',
      'https://play.google.com/store/apps/details?id=com.rbc.mobile.android',
      'https://www.rbc.com',
      'info@rbc.com',
      'https://twitter.com/RBC',
      'https://www.instagram.com/rbc/',
      'https://www.linkedin.com/company/rbc/',
      '',
      'ROYCCAT2',
      '',
    ),
    bank(
      'Toronto-Dominion Bank',
      '+1 416 308 9030',
      '66 Wellington Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/td-canada/id358071948',
      'https://play.google.com/store/apps/details?id=com.td',
      'https://www.td.com',
      'customer.service@td.com',
      'https://twitter.com/TD_Canada',
      'https://www.instagram.com/td_canada/',
      'https://www.linkedin.com/company/td/',
      '',
      'TDOMCATTTOR',
      '',
    ),
    bank(
      'Scotiabank',
      '+1 416 933 8000',
      '44 King Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/scotiabank/id341351824',
      'https://play.google.com/store/apps/details?id=ca.scotiabank.banking',
      'https://www.scotiabank.com',
      'customer.service@scotiabank.com',
      'https://twitter.com/Scotiabank',
      'https://www.instagram.com/scotiabank/',
      'https://www.linkedin.com/company/scotiabank/',
      '',
      'NOSCCATT',
      '',
    ),
  ],
  CL: [
    bank(
      'Banco de Chile',
      '+56 2 2637 1111',
      'Ahumada 251, Santiago, Chile',
      'https://apps.apple.com/cl/app/banco-de-chile/id404124896',
      'https://play.google.com/store/apps/details?id=cl.bancochile.mi_banco',
      'https://www.bancochile.cl',
      'informaciones@bancochile.cl',
      'https://twitter.com/bancodechile',
      'https://www.instagram.com/bancodechile/',
      'https://www.linkedin.com/company/banco-de-chile/',
      '',
      'BCHICLRM',
      '',
    ),
    bank(
      'Banco Santander Chile',
      '+56 2 2320 2000',
      'Bandera 140, Santiago, Chile',
      'https://apps.apple.com/cl/app/banco-santander-chile/id498462567',
      'https://play.google.com/store/apps/details?id=cl.santander.santander',
      'https://www.santander.cl',
      'contacto@santander.cl',
      'https://twitter.com/SantanderChile',
      'https://www.instagram.com/santanderchile/',
      'https://www.linkedin.com/company/banco-santander-chile/',
      '',
      'BSCHCLRM',
      '',
    ),
    bank(
      'BancoEstado',
      '+56 2 2670 7000',
      'Morande 25, Santiago, Chile',
      'https://apps.apple.com/cl/app/bancoestado/id450526199',
      'https://play.google.com/store/apps/details?id=cl.bancoestado.bemovil',
      'https://www.bancoestado.cl',
      'contacto@bancoestado.cl',
      'https://twitter.com/BancoEstado',
      'https://www.instagram.com/bancoestado/',
      'https://www.linkedin.com/company/bancoestado/',
      '',
      'BECHCLRM',
      '',
    ),
  ],
  CN: [
    bank(
      'Industrial and Commercial Bank of China',
      '+86 10 6610 8610',
      '55 Fuxingmennei Avenue, Beijing, China',
      'https://apps.apple.com/cn/app/icbc/id363280271',
      'https://play.google.com/store/apps/details?id=com.icbc',
      'https://www.icbc.com.cn',
      'info@icbc.com.cn',
      '',
      '',
      'https://www.linkedin.com/company/icbc/',
      '',
      'ICBKCNBJ',
      '',
    ),
    bank(
      'Bank of China',
      '+86 10 6659 6688',
      '1 Fuxingmen Nei Dajie, Beijing, China',
      'https://apps.apple.com/cn/app/bank-of-china/id463862286',
      'https://play.google.com/store/apps/details?id=com.boc.bocsoft.mobilebanking',
      'https://www.boc.cn',
      'ir@bankofchina.com',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-china/',
      '',
      'BKCHCNBJ',
      '',
    ),
    bank(
      'China Construction Bank',
      '+86 10 6621 5566',
      '25 Finance Street, Xicheng District, Beijing, China',
      'https://apps.apple.com/cn/app/china-construction-bank/id391710657',
      'https://play.google.com/store/apps/details?id=com.ccb.mobile',
      'https://www.ccb.com',
      'ccbcc.zh@ccb.com',
      '',
      '',
      'https://www.linkedin.com/company/china-construction-bank/',
      '',
      'PCBCCNBJ',
      '',
    ),
  ],
  HK: [
    bank(
      'HSBC Hong Kong',
      '+852 2233 3000',
      '1 Queen\'s Road Central, Hong Kong',
      'https://apps.apple.com/hk/app/hsbc-hk-mobile-banking/id1203937732',
      'https://play.google.com/store/apps/details?id=hk.com.hsbc.hsbchkmobilebanking',
      'https://www.hsbc.com.hk',
      'feedback@hsbc.com.hk',
      'https://twitter.com/HSBC_HK',
      'https://www.instagram.com/hsbc_hk/',
      'https://www.linkedin.com/company/hsbc/',
      '',
      'HSBCHKHH',
      '',
    ),
    bank(
      'Bank of China Hong Kong',
      '+852 3988 2388',
      'Bank of China Tower, 1 Garden Road, Central, Hong Kong',
      'https://apps.apple.com/hk/app/boc-hk-mobile-banking/id406998928',
      'https://play.google.com/store/apps/details?id=com.bochk.bocpay',
      'https://www.bochk.com',
      'enquiry@bochk.com',
      'https://twitter.com/BOCHKNews',
      'https://www.instagram.com/boc_hong_kong/',
      'https://www.linkedin.com/company/bank-of-china-hong-kong/',
      '',
      'BKCHHKHH',
      '',
    ),
    bank(
      'Hang Seng Bank',
      '+852 2198 8000',
      '83 Des Voeux Road Central, Hong Kong',
      'https://apps.apple.com/hk/app/hang-seng-personal-banking/id507756905',
      'https://play.google.com/store/apps/details?id=com.hangseng.rbmobile',
      'https://www.hangseng.com',
      'grc@hangseng.com',
      'https://twitter.com/HangSengBank',
      'https://www.instagram.com/hangsengbank/',
      'https://www.linkedin.com/company/hang-seng-bank/',
      '',
      'HASEHKHH',
      '',
    ),
  ],
  ID: [
    bank(
      'Bank Mandiri',
      '+62 21 5299 7777',
      'Plaza Mandiri, Jl. Jend. Gatot Subroto, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/livin-by-mandiri/id1555417419',
      'https://play.google.com/store/apps/details?id=id.bmri.livin',
      'https://www.bankmandiri.co.id',
      'mandiricare@bankmandiri.co.id',
      'https://twitter.com/bankmandiri',
      'https://www.instagram.com/bankmandiri/',
      'https://www.linkedin.com/company/bankmandiri/',
      '',
      'BMRIIDJA',
      '',
    ),
    bank(
      'Bank Central Asia',
      '+62 21 2358 8000',
      'Menara BCA, Grand Indonesia, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/mybca/id1465918716',
      'https://play.google.com/store/apps/details?id=com.bca.mybca.omni.android',
      'https://www.bca.co.id',
      'halobca@bca.co.id',
      'https://twitter.com/BankBCA',
      'https://www.instagram.com/goodlifebca/',
      'https://www.linkedin.com/company/pt-bank-central-asia-tbk/',
      '',
      'CENAIDJA',
      '',
    ),
    bank(
      'Bank Negara Indonesia',
      '+62 21 5728387',
      'Jl. Jend. Sudirman Kav. 1, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/wondr-by-bni/id6474669196',
      'https://play.google.com/store/apps/details?id=id.co.bni.newagenbni46',
      'https://www.bni.co.id',
      'bnicall@bni.co.id',
      'https://twitter.com/BNI',
      'https://www.instagram.com/bni46/',
      'https://www.linkedin.com/company/pt-bank-negara-indonesia-persero-tbk/',
      '',
      'BNINIDJA',
      '',
    ),
  ],
  JP: [
    bank(
      'MUFG Bank',
      '+81 3 3240 1111',
      '2-7-1 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mufg/id1249041409',
      'https://play.google.com/store/apps/details?id=jp.co.bk.mufg.bkapp',
      'https://www.bk.mufg.jp',
      'info@bk.mufg.jp',
      'https://twitter.com/MUFG',
      '',
      'https://www.linkedin.com/company/mufg/',
      '',
      'BOTKJPJT',
      '',
    ),
    bank(
      'Sumitomo Mitsui Banking Corporation',
      '+81 3 3282 8111',
      '1-1-2 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/smbc/id398950681',
      'https://play.google.com/store/apps/details?id=jp.co.smbc.banking',
      'https://www.smbc.co.jp',
      'koho@smbc.co.jp',
      'https://twitter.com/SMBCGroup',
      '',
      'https://www.linkedin.com/company/smbc-group/',
      '',
      'SMBCJPJT',
      '',
    ),
    bank(
      'Mizuho Bank',
      '+81 3 3214 1111',
      '1-5-5 Otemachi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mizuho-direct/id1535103293',
      'https://play.google.com/store/apps/details?id=jp.co.mizuhobank.direct',
      'https://www.mizuhobank.co.jp',
      'info@mizuho-fg.co.jp',
      'https://twitter.com/MizuhoGroup',
      '',
      'https://www.linkedin.com/company/mizuho/',
      '',
      'MHCBJPJT',
      '',
    ),
  ],
  MY: [
    bank(
      'Maybank',
      '+60 3 2070 8833',
      'Menara Maybank, 100 Jalan Tun Perak, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/mae-by-maybank2u/id1455827893',
      'https://play.google.com/store/apps/details?id=com.maybank2u.life',
      'https://www.maybank2u.com.my',
      'mgcc@maybank.com.my',
      'https://twitter.com/MyMaybank',
      'https://www.instagram.com/maybank/',
      'https://www.linkedin.com/company/maybank/',
      '',
      'MBBEMYKL',
      '',
    ),
    bank(
      'CIMB Bank',
      '+60 3 6204 7788',
      'Menara CIMB, Jalan Stesen Sentral 2, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/cimb-octo-my/id1533904065',
      'https://play.google.com/store/apps/details?id=com.cimbmalaysia',
      'https://www.cimb.com.my',
      'contactus@cimb.com',
      'https://twitter.com/CIMBMalaysia',
      'https://www.instagram.com/cimbmalaysia/',
      'https://www.linkedin.com/company/cimb/',
      '',
      'CIBBMYKL',
      '',
    ),
    bank(
      'Public Bank',
      '+60 3 2176 8000',
      'Menara Public Bank, Jalan Raja Chulan, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/pbe/id1181169389',
      'https://play.google.com/store/apps/details?id=com.publicbank.pbeng',
      'https://www.pbebank.com',
      'customersupport@publicbank.com.my',
      'https://twitter.com/PublicBankGroup',
      '',
      'https://www.linkedin.com/company/public-bank-berhad/',
      '',
      'PBBEMYKL',
      '',
    ),
  ],
  MX: [
    bank(
      'BBVA Mexico',
      '+52 55 5621 3434',
      'Paseo de la Reforma 510, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/bbva-mexico/id375408965',
      'https://play.google.com/store/apps/details?id=com.bancomer.mbanking',
      'https://www.bbva.mx',
      'une.mx@bbva.com',
      'https://twitter.com/BBVA_Mex',
      'https://www.instagram.com/bbva_mex/',
      'https://www.linkedin.com/company/bbva-mexico/',
      '',
      'BCMRMXMM',
      '',
    ),
    bank(
      'Banorte',
      '+52 81 8156 9600',
      'Av. Revolucion 3000 Sur, Monterrey, Mexico',
      'https://apps.apple.com/mx/app/banorte-movil/id445541658',
      'https://play.google.com/store/apps/details?id=com.banorte.movil',
      'https://www.banorte.com',
      'une@banorte.com',
      'https://twitter.com/Banorte_mx',
      'https://www.instagram.com/banorte_mx/',
      'https://www.linkedin.com/company/grupo-financiero-banorte/',
      '',
      'MENOMXMT',
      '',
    ),
    bank(
      'Citibanamex',
      '+52 55 1226 2639',
      'Isabel la Catolica 44, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/citibanamex-movil/id394943449',
      'https://play.google.com/store/apps/details?id=com.citibanamex.banamexmobile',
      'https://www.banamex.com',
      'atencionaclientes@citibanamex.com',
      'https://twitter.com/Citibanamex',
      'https://www.instagram.com/citibanamex/',
      'https://www.linkedin.com/company/citibanamex/',
      '',
      'BNMXMXMM',
      '',
    ),
  ],
  NZ: [
    bank(
      'ANZ New Zealand',
      '+64 9 252 6777',
      '23 Albert Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/anz-go-money-nz/id486726860',
      'https://play.google.com/store/apps/details?id=nz.co.anz.android.mobilebanking',
      'https://www.anz.co.nz',
      'info@anz.co.nz',
      'https://twitter.com/ANZ_NZ',
      'https://www.instagram.com/anz_nz/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBNZ22',
      '',
    ),
    bank(
      'ASB Bank',
      '+64 9 306 3000',
      '12 Jellicoe Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/asb-mobile-banking/id384056323',
      'https://play.google.com/store/apps/details?id=nz.co.asb.asbmobile',
      'https://www.asb.co.nz',
      'info@asb.co.nz',
      'https://twitter.com/ASBBank',
      'https://www.instagram.com/asbbank/',
      'https://www.linkedin.com/company/asb-bank/',
      '',
      'ASBBNZ2A',
      '',
    ),
    bank(
      'Bank of New Zealand',
      '+64 9 924 9000',
      '80 Queen Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/bnz-mobile/id413489435',
      'https://play.google.com/store/apps/details?id=nz.co.bnz.droidbanking',
      'https://www.bnz.co.nz',
      'bnz_reception@bnz.co.nz',
      'https://twitter.com/bnz',
      'https://www.instagram.com/bankofnz/',
      'https://www.linkedin.com/company/bank-of-new-zealand/',
      '',
      'BKNZNZ22',
      '',
    ),
  ],
  PG: [
    bank(
      'Bank South Pacific',
      '+675 320 1212',
      'Douglas Street, Port Moresby, Papua New Guinea',
      'https://apps.apple.com/pg/app/bsp-mobile/id1441758301',
      'https://play.google.com/store/apps/details?id=com.bsp.mobile',
      'https://www.bsp.com.pg',
      'customercare@bsp.com.pg',
      'https://twitter.com/BSPLimited',
      'https://www.instagram.com/bsplimited/',
      'https://www.linkedin.com/company/bank-south-pacific/',
      '',
      'BOSPAPGM',
      '',
    ),
    bank(
      'Kina Bank',
      '+675 308 3888',
      'Kina Centre, Douglas Street, Port Moresby, Papua New Guinea',
      'https://apps.apple.com/pg/app/kina-bank-mobile/id6445904767',
      'https://play.google.com/store/apps/details?id=com.kinabank.mobile',
      'https://www.kinabank.com.pg',
      'info@kinabank.com.pg',
      'https://twitter.com/KinaBankPNG',
      'https://www.instagram.com/kinabankpng/',
      'https://www.linkedin.com/company/kina-bank/',
      '',
      'KINAPGM1',
      '',
    ),
    bank(
      'ANZ Bank Papua New Guinea',
      '+675 321 1077',
      'Cuthbertson House, Douglas Street, Port Moresby, Papua New Guinea',
      'https://apps.apple.com/pg/app/anz-png/id385348415',
      'https://play.google.com/store/apps/details?id=com.anz.android',
      'https://www.anz.com/pg',
      'contactus@anz.com',
      'https://twitter.com/ANZ_AU',
      'https://www.instagram.com/anz_au/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBPAPX',
      '',
    ),
  ],
  PE: [
    bank(
      'Banco de Credito del Peru',
      '+51 1 311 9898',
      'Calle Centenario 156, La Molina, Lima, Peru',
      'https://apps.apple.com/pe/app/bcp/id511971097',
      'https://play.google.com/store/apps/details?id=pe.com.bcp.inbanking',
      'https://www.viabcp.com',
      'contacto@bcp.com.pe',
      'https://twitter.com/BCPComunica',
      'https://www.instagram.com/viabcp/',
      'https://www.linkedin.com/company/bcp/',
      '',
      'BCPLPEPL',
      '',
    ),
    bank(
      'Interbank Peru',
      '+51 1 219 2000',
      'Carlos Villaran 140, La Victoria, Lima, Peru',
      'https://apps.apple.com/pe/app/interbank-app/id455429155',
      'https://play.google.com/store/apps/details?id=pe.interbank.mobilebanking',
      'https://www.interbank.pe',
      'servicioalcliente@intercorp.com.pe',
      'https://twitter.com/Interbank',
      'https://www.instagram.com/interbank/',
      'https://www.linkedin.com/company/interbank/',
      '',
      'BINPPEPL',
      '',
    ),
    bank(
      'BBVA Peru',
      '+51 1 595 0000',
      'Av. Republica de Panama 3055, San Isidro, Lima, Peru',
      'https://apps.apple.com/pe/app/bbva-peru/id375267788',
      'https://play.google.com/store/apps/details?id=com.bbva.netcash.peru',
      'https://www.bbva.pe',
      'contacto.pe@bbva.com',
      'https://twitter.com/BBVA_Peru',
      'https://www.instagram.com/bbva_peru/',
      'https://www.linkedin.com/company/bbva-en-peru/',
      '',
      'BCONPEPL',
      '',
    ),
  ],
  PH: [
    bank(
      'BDO Unibank',
      '+63 2 8631 8000',
      'BDO Corporate Center, Makati Avenue, Makati, Philippines',
      'https://apps.apple.com/ph/app/bdo-online/id1558548418',
      'https://play.google.com/store/apps/details?id=com.bdo.online',
      'https://www.bdo.com.ph',
      'customercare@bdo.com.ph',
      'https://twitter.com/BDOUnibank',
      'https://www.instagram.com/bdounibank/',
      'https://www.linkedin.com/company/bdo-unibank/',
      '',
      'BNORPHMM',
      '',
    ),
    bank(
      'Bank of the Philippine Islands',
      '+63 2 8891 0000',
      'Ayala North Exchange Tower, Makati, Philippines',
      'https://apps.apple.com/ph/app/bpi-mobile/id1131500055',
      'https://play.google.com/store/apps/details?id=ph.com.bpi.mobile',
      'https://www.bpi.com.ph',
      'help@bpi.com.ph',
      'https://twitter.com/TalktoBPI',
      'https://www.instagram.com/bpi/',
      'https://www.linkedin.com/company/bank-of-the-philippine-islands/',
      '',
      'BOPIPHMM',
      '',
    ),
    bank(
      'Metrobank',
      '+63 2 8870 0700',
      'Metrobank Plaza, Makati Avenue, Makati, Philippines',
      'https://apps.apple.com/ph/app/metrobank-online/id407362868',
      'https://play.google.com/store/apps/details?id=ph.com.metrobank.mcc',
      'https://www.metrobank.com.ph',
      'customercare@metrobank.com.ph',
      'https://twitter.com/Metrobank',
      'https://www.instagram.com/metrobank/',
      'https://www.linkedin.com/company/metrobank/',
      '',
      'MBTCPHMM',
      '',
    ),
  ],
  RU: [
    bank(
      'Sberbank',
      '+7 495 500 5550',
      '19 Vavilova Street, Moscow, Russia',
      'https://apps.apple.com/ru/app/sberbank-online/id492224193',
      'https://play.google.com/store/apps/details?id=ru.sberbankmobile',
      'https://www.sberbank.com',
      'media@sberbank.ru',
      'https://twitter.com/sberbank',
      'https://www.instagram.com/sberbank/',
      'https://www.linkedin.com/company/sberbank/',
      '',
      'SABRRUMM',
      '',
    ),
    bank(
      'VTB Bank',
      '+7 495 777 2424',
      '29 Bolshaya Morskaya Street, Saint Petersburg, Russia',
      'https://apps.apple.com/ru/app/vtb-online/id1366975900',
      'https://play.google.com/store/apps/details?id=ru.vtb24.mobilebanking.android',
      'https://www.vtb.ru',
      'info@vtb.ru',
      'https://twitter.com/vtb',
      '',
      'https://www.linkedin.com/company/vtb/',
      '',
      'VTBRRUMM',
      '',
    ),
    bank(
      'Gazprombank',
      '+7 495 913 7474',
      '63 Novocheremushkinskaya Street, Moscow, Russia',
      'https://apps.apple.com/ru/app/gazprombank/id1457312516',
      'https://play.google.com/store/apps/details?id=ru.gazprombank.mobile',
      'https://www.gazprombank.ru',
      'mailbox@gazprombank.ru',
      'https://twitter.com/gazprombank',
      '',
      'https://www.linkedin.com/company/gazprombank/',
      '',
      'GAZPRUMM',
      '',
    ),
  ],
  SG: [
    bank(
      'DBS Bank',
      '+65 6878 8888',
      '12 Marina Boulevard, Marina Bay Financial Centre, Singapore',
      'https://apps.apple.com/sg/app/dbs-digibank/id1068403820',
      'https://play.google.com/store/apps/details?id=com.dbs.sg.dbsmbanking',
      'https://www.dbs.com.sg',
      'contactus@dbs.com',
      'https://twitter.com/dbsbank',
      'https://www.instagram.com/dbsbank/',
      'https://www.linkedin.com/company/dbs-bank/',
      '',
      'DBSSSGSG',
      '',
    ),
    bank(
      'OCBC Bank',
      '+65 6363 3333',
      '65 Chulia Street, OCBC Centre, Singapore',
      'https://apps.apple.com/sg/app/ocbc-digital/id292506828',
      'https://play.google.com/store/apps/details?id=com.ocbc.mobile',
      'https://www.ocbc.com',
      'contactus@ocbc.com',
      'https://twitter.com/OCBCBank',
      'https://www.instagram.com/ocbc/',
      'https://www.linkedin.com/company/ocbc-bank/',
      '',
      'OCBCSGSG',
      '',
    ),
    bank(
      'UOB',
      '+65 6222 2121',
      '80 Raffles Place, UOB Plaza, Singapore',
      'https://apps.apple.com/sg/app/uob-tmrw/id1314626819',
      'https://play.google.com/store/apps/details?id=com.uob.might',
      'https://www.uob.com.sg',
      'uobcustomerservice@uobgroup.com',
      'https://twitter.com/UOBGroup',
      'https://www.instagram.com/uobgroup/',
      'https://www.linkedin.com/company/uob/',
      '',
      'UOVBSGSG',
      '',
    ),
  ],
  KR: [
    bank(
      'KB Kookmin Bank',
      '+82 2 2073 7114',
      '26 Gukjegeumyung-ro 8-gil, Yeongdeungpo-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/kb-star-banking/id373742138',
      'https://play.google.com/store/apps/details?id=com.kbstar.kbbank',
      'https://www.kbstar.com',
      'kbkookminbank@kbfg.com',
      'https://twitter.com/KBFinancialGroup',
      '',
      'https://www.linkedin.com/company/kb-financial-group/',
      '',
      'CZNBKRSE',
      '',
    ),
    bank(
      'Shinhan Bank',
      '+82 2 756 0505',
      '20 Sejong-daero 9-gil, Jung-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/shinhan-sol-global/id1363654579',
      'https://play.google.com/store/apps/details?id=com.shinhan.globalbank',
      'https://www.shinhan.com',
      'global@shinhan.com',
      'https://twitter.com/ShinhanBank',
      '',
      'https://www.linkedin.com/company/shinhan-bank/',
      '',
      'SHBKKRSE',
      '',
    ),
    bank(
      'Woori Bank',
      '+82 2 2002 3000',
      '51 Sogong-ro, Jung-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/woori-won-banking/id1430145879',
      'https://play.google.com/store/apps/details?id=com.wooribank.smart.npib',
      'https://www.wooribank.com',
      'wbmaster@wooribank.com',
      'https://twitter.com/WooriBank',
      '',
      'https://www.linkedin.com/company/woori-bank/',
      '',
      'HVBKKRSE',
      '',
    ),
  ],
  TW: [
    bank(
      'CTBC Bank',
      '+886 2 3327 7777',
      '168 Jingmao 2nd Road, Nangang District, Taipei, Taiwan',
      'https://apps.apple.com/tw/app/ctbc-mobile-banking/id389813800',
      'https://play.google.com/store/apps/details?id=com.chinatrust.mobilebank',
      'https://www.ctbcbank.com',
      'service@ctbcbank.com',
      'https://twitter.com/CTBCBank',
      'https://www.instagram.com/ctbc_official/',
      'https://www.linkedin.com/company/ctbc-bank/',
      '',
      'CTCBTWTP',
      '',
    ),
    bank(
      'Taipei Fubon Bank',
      '+886 2 8751 6665',
      '108 Renai Road, Taipei, Taiwan',
      'https://apps.apple.com/tw/app/taipei-fubon-bank/id514522089',
      'https://play.google.com/store/apps/details?id=com.fubon',
      'https://www.fubon.com/banking',
      'service@fubon.com',
      '',
      '',
      'https://www.linkedin.com/company/fubon-financial/',
      '',
      'TPBKTWTP',
      '',
    ),
    bank(
      'Bank of Taiwan',
      '+886 2 2349 3456',
      '120 Section 1, Chongqing South Road, Taipei, Taiwan',
      'https://apps.apple.com/tw/app/bot-mobile-banking/id1005101522',
      'https://play.google.com/store/apps/details?id=tw.com.bot.mobilebank',
      'https://www.bot.com.tw',
      'service@bot.com.tw',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-taiwan/',
      '',
      'BKTWTWTP',
      '',
    ),
  ],
  TH: [
    bank(
      'Bangkok Bank',
      '+66 2 230 1323',
      '333 Silom Road, Bang Rak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/bualuang-mbanking/id660355106',
      'https://play.google.com/store/apps/details?id=com.bbl.mobilebanking',
      'https://www.bangkokbank.com',
      'customercare@bangkokbank.com',
      'https://twitter.com/bangkokbank',
      'https://www.instagram.com/bangkokbank/',
      'https://www.linkedin.com/company/bangkok-bank/',
      '',
      'BKKBTHBK',
      '',
    ),
    bank(
      'Kasikornbank',
      '+66 2 888 8888',
      '1 Soi Rat Burana 27/1, Rat Burana, Bangkok, Thailand',
      'https://apps.apple.com/th/app/k-plus/id361170631',
      'https://play.google.com/store/apps/details?id=com.kasikorn.retail.mbanking.wap',
      'https://www.kasikornbank.com',
      'kcontactcenter@kasikornbank.com',
      'https://twitter.com/KBank_Live',
      'https://www.instagram.com/kbanklive/',
      'https://www.linkedin.com/company/kasikornbank/',
      '',
      'KASITHBK',
      '',
    ),
    bank(
      'Siam Commercial Bank',
      '+66 2 777 7777',
      '9 Ratchadaphisek Road, Chatuchak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/scb-easy/id568388474',
      'https://play.google.com/store/apps/details?id=com.scb.phone',
      'https://www.scb.co.th',
      'customercare@scb.co.th',
      'https://twitter.com/scb_thailand',
      'https://www.instagram.com/scb_thailand/',
      'https://www.linkedin.com/company/the-siam-commercial-bank-public-company-limited/',
      '',
      'SICOTHBK',
      '',
    ),
  ],
  US: [
    bank(
      'JPMorgan Chase Bank',
      '+1 212 270 6000',
      '270 Park Avenue, New York, NY, United States',
      'https://apps.apple.com/us/app/chase-mobile/id298867247',
      'https://play.google.com/store/apps/details?id=com.chase.sig.android',
      'https://www.chase.com',
      'support@chase.com',
      'https://twitter.com/Chase',
      'https://www.instagram.com/chase/',
      'https://www.linkedin.com/company/jpmorganchase/',
      '021000021',
      'CHASUS33',
      'https://api.chase.com',
    ),
    bank(
      'Bank of America',
      '+1 704 386 5681',
      '100 North Tryon Street, Charlotte, NC, United States',
      'https://apps.apple.com/us/app/bank-of-america-mobile-banking/id284847138',
      'https://play.google.com/store/apps/details?id=com.infonow.bofa',
      'https://www.bankofamerica.com',
      'abuse@bankofamerica.com',
      'https://twitter.com/BankofAmerica',
      'https://www.instagram.com/bankofamerica/',
      'https://www.linkedin.com/company/bank-of-america/',
      '026009593',
      'BOFAUS3N',
      '',
    ),
    bank(
      'Wells Fargo Bank',
      '+1 415 396 1300',
      '420 Montgomery Street, San Francisco, CA, United States',
      'https://apps.apple.com/us/app/wells-fargo-mobile/id311548709',
      'https://play.google.com/store/apps/details?id=com.wf.wellsfargomobile',
      'https://www.wellsfargo.com',
      'customer.service@wellsfargo.com',
      'https://twitter.com/WellsFargo',
      'https://www.instagram.com/wellsfargo/',
      'https://www.linkedin.com/company/wellsfargo/',
      '121000248',
      'WFBIUS6S',
      '',
    ),
  ],
  VN: [
    bank(
      'Vietcombank',
      '+84 24 3934 3137',
      '198 Tran Quang Khai, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vcb-digibank/id561433131',
      'https://play.google.com/store/apps/details?id=com.vietcombank.vcbmobile',
      'https://www.vietcombank.com.vn',
      'vcb@vietcombank.com.vn',
      'https://twitter.com/Vietcombank',
      'https://www.instagram.com/vietcombank/',
      'https://www.linkedin.com/company/vietcombank/',
      '',
      'BFTVVNVX',
      '',
    ),
    bank(
      'BIDV',
      '+84 24 2220 5544',
      '35 Hang Voi, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/bidv-smartbanking/id1283524786',
      'https://play.google.com/store/apps/details?id=com.vnpay.bidv',
      'https://www.bidv.com.vn',
      'bidv247@bidv.com.vn',
      'https://twitter.com/BIDV',
      '',
      'https://www.linkedin.com/company/bidv/',
      '',
      'BIDVVNVX',
      '',
    ),
    bank(
      'VietinBank',
      '+84 24 3941 8868',
      '108 Tran Hung Dao, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vietinbank-ipay-mobile/id542298015',
      'https://play.google.com/store/apps/details?id=com.vietinbank.ipay',
      'https://www.vietinbank.vn',
      'contact@vietinbank.vn',
      'https://twitter.com/VietinBank',
      '',
      'https://www.linkedin.com/company/vietinbank/',
      '',
      'ICBVVNVX',
      '',
    ),
  ],
}
