import type { NotableUniversity } from './types'
import type { ApecMemberIsoCode } from './apecMemberIsoCodes'

function u(
  name: string,
  website: string,
  email: string,
  instagram: string,
  twitter: string,
  linkedin: string,
): NotableUniversity {
  return { name, website, email, instagram, twitter, linkedin }
}

/** Three notable APEC-member universities — economics / accounting / CS / EE-style faculties (informational; verify). */
export const APEC_NOTABLE_UNIVERSITIES = {
  AU: [
    u(
      'Australian National University',
      'https://www.anu.edu.au/',
      'students@anu.edu.au',
      'https://www.instagram.com/anufromaurora/',
      'https://x.com/anupublicaffairs',
      'https://www.linkedin.com/school/australian-national-university/',
    ),
    u(
      'The University of Melbourne',
      'https://www.unimelb.edu.au/',
      'communications-general@unimelb.edu.au',
      'https://www.instagram.com/unimelb/',
      'https://x.com/unimelb',
      'https://www.linkedin.com/school/university-of-melbourne/',
    ),
    u(
      'UNSW Sydney',
      'https://www.unsw.edu.au/',
      'study@unsw.edu.au',
      'https://www.instagram.com/unsw/',
      'https://x.com/unsw',
      'https://www.linkedin.com/school/unsw/',
    ),
  ],
  BN: [
    u(
      'Universiti Brunei Darussalam',
      'https://www.ubd.edu.bn/',
      'info.helpdesk@ubd.edu.bn',
      'https://www.instagram.com/ubdwellbeing/',
      '',
      'https://www.linkedin.com/school/universiti-brunei-darussalam/',
    ),
    u(
      'Universiti Teknologi Brunei',
      'https://www.utb.edu.bn/',
      'info.admission@utb.edu.bn',
      '',
      '',
      'https://www.linkedin.com/school/universiti-teknologi-brunei/',
    ),
    u(
      'Politeknik Brunei Darussalam',
      'https://www.pb.edu.bn/',
      'marketing@pb.edu.bn',
      '',
      '',
      '',
    ),
  ],
  CA: [
    u(
      'University of Toronto',
      'https://www.utoronto.ca/',
      'communications@utoronto.ca',
      'https://www.instagram.com/uoft/',
      'https://x.com/UofT',
      'https://www.linkedin.com/school/university-of-toronto/',
    ),
    u(
      'The University of British Columbia',
      'https://www.ubc.ca/',
      'student.service@ubc.ca',
      'https://www.instagram.com/universityofbc/',
      'https://x.com/UBCNews',
      'https://www.linkedin.com/school/the-university-of-british-columbia/',
    ),
    u(
      'McGill University',
      'https://www.mcgill.ca/',
      'registration@mcgill.ca',
      'https://www.instagram.com/mcgillu/',
      'https://x.com/mcgillnews',
      'https://www.linkedin.com/school/mcgill-university/',
    ),
  ],
  CL: [
    u(
      'Universidad de Chile',
      'https://www.uchile.cl/',
      'preguntas@admision.uchile.cl',
      'https://www.instagram.com/uchile/',
      'https://x.com/udechileofficial',
      'https://www.linkedin.com/school/universidad-de-chile/',
    ),
    u(
      'Pontificia Universidad Católica de Chile',
      'https://www.uc.cl/',
      'admision@uc.cl',
      'https://www.instagram.com/ucatolica/',
      'https://x.com/UCampus_UC',
      'https://www.linkedin.com/school/universidad-catolica-de-chile/',
    ),
    u(
      'Universidad Técnica Federico Santa María',
      'https://www.usm.cl/',
      'admision@adm.usm.cl',
      'https://www.instagram.com/usantamaria_cl/',
      '',
      'https://www.linkedin.com/school/universidad-tecnica-federico-santa-maria/',
    ),
  ],
  CN: [
    u(
      'Tsinghua University',
      'https://www.tsinghua.edu.cn/',
      'info@tsinghua.edu.cn',
      'https://www.instagram.com/tsinghuaofficial/',
      'https://x.com/tsinghua',
      'https://www.linkedin.com/school/tsinghua-university/',
    ),
    u(
      'Peking University',
      'https://english.pku.edu.cn/',
      'xiaoban@pku.edu.cn',
      'https://www.instagram.com/pekinguniversity/',
      '',
      'https://www.linkedin.com/school/peking-university/',
    ),
    u(
      'Shanghai Jiao Tong University',
      'https://www.sjtu.edu.cn/',
      'study@sjtu.edu.cn',
      'https://www.instagram.com/shanghai_jiao_tong/',
      '',
      'https://www.linkedin.com/school/shanghai-jiao-tong-university/',
    ),
  ],
  HK: [
    u(
      'The University of Hong Kong',
      'https://www.hku.hk/',
      'communications@hku.hk',
      'https://www.instagram.com/theuniversityofhongkong/',
      'https://x.com/theHKUofficial',
      'https://www.linkedin.com/school/the-university-of-hong-kong/',
    ),
    u(
      'The Hong Kong University of Science and Technology',
      'https://hkust.edu.hk/',
      'ugo@ust.hk',
      'https://www.instagram.com/thehkust/',
      'https://x.com/hkust',
      'https://www.linkedin.com/school/hkust/',
    ),
    u(
      'The Chinese University of Hong Kong',
      'https://www.cuhk.edu.hk/',
      'ugadmission@cuhk.edu.hk',
      'https://www.instagram.com/cuhkofficial/',
      'https://x.com/cuhkofficial',
      'https://www.linkedin.com/school/the-chinese-university-of-hong-kong/',
    ),
  ],
  ID: [
    u(
      'Universitas Indonesia',
      'https://www.ui.ac.id/',
      'humas@ui.ac.id',
      'https://www.instagram.com/univ_indonesia/',
      'https://x.com/univ_indonesia',
      'https://www.linkedin.com/school/universitasindonesia/',
    ),
    u(
      'Bandung Institute of Technology',
      'https://www.itb.ac.id/',
      'humas.itb@gmail.com',
      'https://www.instagram.com/itbandung/',
      '',
      'https://www.linkedin.com/school/institutteknologibandung/',
    ),
    u(
      'Universitas Gadjah Mada',
      'https://www.ugm.ac.id/',
      'humas@ugm.ac.id',
      'https://www.instagram.com/gadjahmadau/',
      '',
      'https://www.linkedin.com/school/universitas-gadjah-mada/',
    ),
  ],
  JP: [
    u(
      'The University of Tokyo',
      'https://www.u-tokyo.ac.jp/',
      'webmaster@mail.u-tokyo.ac.jp',
      'https://www.instagram.com/the_university_of_tokyo/',
      'https://x.com/UTokyo_News_en',
      'https://www.linkedin.com/school/the-university-of-tokyo/',
    ),
    u(
      'Kyoto University',
      'https://www.kyoto-u.ac.jp/',
      'admissions@mail2.adm.kyoto-u.ac.jp',
      'https://www.instagram.com/kyotouniversity/',
      'https://x.com/KyotoU_News',
      'https://www.linkedin.com/school/kyoto-university/',
    ),
    u(
      'Tokyo Institute of Technology (Institute of Science Tokyo cluster)',
      'https://www.titech.ac.jp/',
      'study@pr.titech.ac.jp',
      'https://www.instagram.com/titech_en/',
      '',
      'https://www.linkedin.com/school/tokyo-institute-of-technology/',
    ),
  ],
  KR: [
    u(
      'Seoul National University',
      'https://www.snu.ac.kr/',
      'admission@snu.ac.kr',
      'https://www.instagram.com/snublue/',
      'https://x.com/snublue',
      'https://www.linkedin.com/school/seoul-national-university/',
    ),
    u(
      'Korea Advanced Institute of Science and Technology',
      'https://www.kaist.ac.kr/',
      'admission@kaist.ac.kr',
      'https://www.instagram.com/withkaist/',
      '',
      'https://www.linkedin.com/school/kaist/',
    ),
    u(
      'Yonsei University',
      'https://www.yonsei.ac.kr/',
      'admission@yonsei.ac.kr',
      'https://www.instagram.com/yonseiuniv.official/',
      '',
      'https://www.linkedin.com/school/yonsei-university/',
    ),
  ],
  MX: [
    u(
      'Universidad Nacional Autónoma de México',
      'https://www.unam.mx/',
      'webmaster@mail.unam.mx',
      'https://www.instagram.com/clubunam/',
      'https://x.com/UNAM_MX',
      'https://www.linkedin.com/school/universidad-nacional-aut-noma-de-m-xico/',
    ),
    u(
      'Instituto Tecnológico de Monterrey',
      'https://tec.mx/',
      'admision@tec.mx',
      'https://www.instagram.com/tecdemonterrey/',
      'https://x.com/TecdeMonterrey',
      'https://www.linkedin.com/school/tecdemonterrey/',
    ),
    u(
      'Instituto Politécnico Nacional',
      'https://www.ipn.mx/',
      'comunicacionsocial@ipn.mx',
      'https://www.instagram.com/ipn.mx/',
      '',
      'https://www.linkedin.com/school/instituto-polit%C3%A9cnico-nacional/',
    ),
  ],
  MY: [
    u(
      'Universiti Malaya',
      'https://www.um.edu.my/',
      'yweb@um.edu.my',
      'https://www.instagram.com/unimalaya/',
      'https://x.com/unimalayaofficial',
      'https://www.linkedin.com/school/university-of-malaya-official/',
    ),
    u(
      'Universiti Kebangsaan Malaysia',
      'https://www.ukm.my/',
      'tncpi@ukm.edu.my',
      'https://www.instagram.com/ukm_my/',
      '',
      'https://www.linkedin.com/school/universiti-kebangsaan-malaysia/',
    ),
    u(
      'Universiti Sains Malaysia',
      'https://www.usm.my/',
      'pro@sains.usm.my',
      'https://www.instagram.com/usmofficial/',
      '',
      'https://www.linkedin.com/school/universitisainsmalaysia/',
    ),
  ],
  NZ: [
    u(
      'University of Auckland',
      'https://www.auckland.ac.nz/',
      'contact@auckland.ac.nz',
      'https://www.instagram.com/universityofauckland/',
      'https://x.com/AucklandUni',
      'https://www.linkedin.com/school/university-of-auckland/',
    ),
    u(
      'University of Otago',
      'https://www.otago.ac.nz/',
      'askotago@otago.ac.nz',
      'https://www.instagram.com/universityofotago/',
      'https://x.com/otago',
      'https://www.linkedin.com/school/university-of-otago/',
    ),
    u(
      'Victoria University of Wellington Te Herenga Waka',
      'https://www.wgtn.ac.nz/',
      'futurestudents@vuw.ac.nz',
      'https://www.instagram.com/victoriauniversitynz/',
      '',
      'https://www.linkedin.com/school/victoria-university-of-wellington/',
    ),
  ],
  PG: [
    u(
      'University of Papua New Guinea',
      'https://www.upng.ac.pg/',
      'registrar@upng.ac.pg',
      '',
      '',
      '',
    ),
    u(
      'Papua New Guinea University of Technology',
      'https://www.unitech.ac.pg/',
      'registrar@unitech.ac.pg',
      '',
      '',
      '',
    ),
    u(
      'Divine Word University',
      'https://www.dwu.ac.pg/',
      'registrar@dwu.ac.pg',
      '',
      '',
      '',
    ),
  ],
  PE: [
    u(
      'Universidad Nacional Mayor de San Marcos',
      'https://www.unmsm.edu.pe/',
      'centrodocumentacion@unmsm.edu.pe',
      'https://www.instagram.com/oficialunmsm/',
      '',
      'https://www.linkedin.com/school/universidad-de-san-marcos/',
    ),
    u(
      'Pontificia Universidad Católica del Perú',
      'https://www.pucp.edu.pe/',
      'admision@pucp.edu.pe',
      'https://www.instagram.com/pucp/',
      'https://x.com/pucp',
      'https://www.linkedin.com/school/pontificia-universidad-catolica-del-peru/',
    ),
    u(
      'Universidad de Ingeniería y Tecnología',
      'https://www.utec.edu.pe/',
      'admision@utec.edu.pe',
      'https://www.instagram.com/utecedu/',
      '',
      'https://www.linkedin.com/school/universidad-de-ingeneria-y-tecnologia/',
    ),
  ],
  PH: [
    u(
      'University of the Philippines Diliman',
      'https://upd.edu.ph/',
      'ovcsa.upd@up.edu.ph',
      'https://www.instagram.com/officialupdiliman/',
      'https://x.com/upsystem',
      'https://www.linkedin.com/school/university-of-the-philippines-diliman/',
    ),
    u(
      'Ateneo de Manila University',
      'https://www.ateneo.edu/',
      'centralregistrar.information@ateneo.edu',
      'https://www.instagram.com/ateneodemanilauniv/',
      'https://x.com/ateneodemanilauniv',
      'https://www.linkedin.com/school/ateneo/',
    ),
    u(
      'De La Salle University Manila',
      'https://www.dlsu.edu.ph/',
      'registrar@dlsu.edu.ph',
      'https://www.instagram.com/dlsumanila/',
      'https://x.com/dlsumanila',
      'https://www.linkedin.com/school/dlsumanila/',
    ),
  ],
  RU: [
    u(
      'Lomonosov Moscow State University',
      'https://www.msu.ru/',
      'welcome@rector.msu.ru',
      'https://www.instagram.com/msu_official/',
      'https://x.com/msuofficial',
      'https://www.linkedin.com/school/moscow-state-university/',
    ),
    u(
      'Bauman Moscow State Technical University',
      'https://bmstu.ru/',
      'rector@bmstu.ru',
      'https://www.instagram.com/bmstu_ru/',
      '',
      'https://www.linkedin.com/school/baumanskymoscowstatetechnicaluniversity/',
    ),
    u(
      'Higher School of Economics National Research University',
      'https://www.hse.ru/',
      'info@hse.ru',
      'https://www.instagram.com/hse.russia/',
      'https://x.com/hseaunews',
      'https://www.linkedin.com/school/national-research-university-higher-school-of-economics/',
    ),
  ],
  SG: [
    u(
      'National University of Singapore',
      'https://nus.edu.sg/',
      'enquiry@u.nus.edu',
      'https://www.instagram.com/nusingapore/',
      'https://x.com/NUSingapore',
      'https://www.linkedin.com/school/national-university-of-singapore/',
    ),
    u(
      'Nanyang Technological University',
      'https://www.ntu.edu.sg/',
      'contact@ntu.edu.sg',
      'https://www.instagram.com/ntusg/',
      'https://x.com/NTUsg',
      'https://www.linkedin.com/school/ntusg/',
    ),
    u(
      'Singapore Management University',
      'https://www.smu.edu.sg/',
      'enquiry@smu.edu.sg',
      'https://www.instagram.com/smu_sg/',
      'https://x.com/SingaporeMgtU',
      'https://www.linkedin.com/school/singapore-management-university/',
    ),
  ],
  TH: [
    u(
      'Chulalongkorn University',
      'https://www.chula.ac.th/en/',
      'reg@chula.ac.th',
      'https://www.instagram.com/chulaofficial/',
      'https://x.com/ChulaOfficial',
      'https://www.linkedin.com/school/chulalongkorn-university/',
    ),
    u(
      'Thammasat University',
      'https://www.tu.ac.th/',
      'reg@tu.ac.th',
      'https://www.instagram.com/thammasat.university/',
      'https://x.com/Thammasat1955',
      'https://www.linkedin.com/school/thammasat-university/',
    ),
    u(
      'King Mongkuts University of Technology Thonburi',
      'https://www.kmutt.ac.th/',
      'admission@kmutt.ac.th',
      'https://www.instagram.com/kmuttofficial/',
      '',
      'https://www.linkedin.com/school/kmutt/',
    ),
  ],
  TW: [
    u(
      'National Taiwan University',
      'https://www.ntu.edu.tw/',
      'ntucrec@ntu.edu.tw',
      'https://www.instagram.com/national_taiwan_university/',
      'https://x.com/NCU_NTU',
      'https://www.linkedin.com/school/national-taiwan-university/',
    ),
    u(
      'National Yang Ming Chiao Tung University',
      'https://www.nycu.edu.tw/',
      'admissions@nycu.edu.tw',
      'https://www.instagram.com/nycudotcom/',
      '',
      'https://www.linkedin.com/school/national-chiao-tung-university/',
    ),
    u(
      'National Tsing Hua University Taiwan',
      'https://nthu.edu.tw/',
      'admissions@my.nthu.edu.tw',
      'https://www.instagram.com/nthu_tw/',
      '',
      'https://www.linkedin.com/school/national-tsing-hua-university/',
    ),
  ],
  US: [
    u(
      'Massachusetts Institute of Technology',
      'https://web.mit.edu/',
      'mitadmissions@mit.edu',
      'https://www.instagram.com/mitadmissions/',
      'https://x.com/MIT',
      'https://www.linkedin.com/school/mit/',
    ),
    u(
      'Stanford University',
      'https://www.stanford.edu/',
      'admissions@stanford.edu',
      'https://www.instagram.com/stanford/',
      'https://x.com/Stanford',
      'https://www.linkedin.com/school/stanford-university/',
    ),
    u(
      'University of California, Berkeley',
      'https://www.berkeley.edu/',
      'admissions@berkeley.edu',
      'https://www.instagram.com/ucberkeleyofficial/',
      'https://x.com/UCBerkeley',
      'https://www.linkedin.com/school/uc-berkeley/',
    ),
  ],
  VN: [
    u(
      'Vietnam National University Hanoi (VNU-Hanoi)',
      'https://vnu.edu.vn/',
      'info@vnu.edu.vn',
      'https://www.instagram.com/dhqghn.official/',
      '',
      'https://www.linkedin.com/school/vnu-hanoi/',
    ),
    u(
      'Hanoi University of Science and Technology',
      'https://hust.edu.vn/',
      'daotao.hust@gmail.com',
      'https://www.instagram.com/dhbkhanoi/',
      'https://x.com/DHBKHanoiOfficial',
      'https://www.linkedin.com/school/hanoi-university-of-science-and-technology/',
    ),
    u(
      'Ho Chi Minh City University of Technology — VNU HCMUT',
      'https://hcmut.edu.vn/',
      'p.daotao@hcmut.edu.vn',
      'https://www.instagram.com/dhbkhcmc/',
      'https://x.com/DHBKTPHCM',
      'https://www.linkedin.com/school/hochiminhcity-university-of-technology/',
    ),
  ],
} as const satisfies Record<ApecMemberIsoCode, readonly [NotableUniversity, NotableUniversity, NotableUniversity]>
