import type { CorporationFormationOffice } from './types'
import type { NatoMemberIsoCode } from './natoMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per NATO Ally state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const NATO_CORPORATION_FORMATION_OFFICES: Record<NatoMemberIsoCode, CorporationFormationOffice> = {
  AL:   office(
    'National Business Center Albania (QKB)',
    '+355 4 222 0000',
    'Rruga e Kavajes, Tirana, Albania',
    'https://www.qkb.gov.al',
    'info@qkb.gov.al',
    '',
    '',
    'https://www.linkedin.com/company/qendra-kombetare-e-biznesit/',
    'https://e-albania.al',
    'https://www.qkb.gov.al/perdoruesit-e-re/te-hapesh-nje-biznes',
    'NIPT (Numri Identifikues i Personit te Tatueshem)',
  ),
  BE:   office(
    'Banque-Carrefour des Entreprises (BCE/KBO Belgium)',
    '+32 2 277 30 11',
    'Rue du Progres 50, 1210 Brussels, Belgium',
    'https://economie.fgov.be',
    'bce@economie.fgov.be',
    '',
    '',
    '',
    'https://kbopub.economie.fgov.be',
    'https://economie.fgov.be/en/themes/enterprises/starting-business',
    'Numero d\'entreprise / Ondernemingsnummer',
  ),
  BG:   office(
    'Registry Agency Bulgaria (Commercial Register)',
    '+359 2 948 9000',
    '52 Knyaz Dondukov Blvd, Sofia, Bulgaria',
    'https://www.registryagency.bg',
    'info@registryagency.bg',
    '',
    '',
    '',
    'https://portal.registryagency.bg',
    'https://www.registryagency.bg/en/services',
    'UIC (Unified Identification Code)',
  ),
  CA:   office(
    'Corporations Canada (Innovation, Science and Economic Development)',
    '+1 866 333 5556',
    '235 Queen Street, Ottawa, ON K1A 0H5, Canada',
    'https://ised-isde.canada.ca/site/corporations-canada/en',
    '',
    '',
    '',
    '',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/incorporate-business-corporation',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/steps-incorporating',
    'Corporation Number',
  ),
  HR:   office(
    'Court Register (Fina Croatia)',
    '+385 1 480 9000',
    'Ulica grada Vukovara 78, Zagreb, Croatia',
    'https://www.fina.hr',
    'info@fina.hr',
    '',
    '',
    '',
    'https://sudreg.pravosudje.hr',
    'https://www.hok.hr/poslovni-registar',
    'OIB (Personal Identification Number)',
  ),
  CZ:   office(
    'Business Register (Ministry of Justice Czechia)',
    '+420 296 366 366',
    'Ovocny trh 8, Prague, Czechia',
    'https://www.justice.cz',
    '',
    '',
    '',
    '',
    'https://or.justice.cz',
    'https://www.businessinfo.cz/en/articles/how-to-start-a-business-in-the-czech-republic',
    'ICO (Identification Number of Organization)',
  ),
  DK:   office(
    'Danish Business Authority (Erhvervsstyrelsen)',
    '+45 35 29 10 00',
    'Langelinie Alle 17, 2100 Copenhagen, Denmark',
    'https://erhvervsstyrelsen.dk',
    'es@erhvervsstyrelsen.dk',
    '',
    '',
    '',
    'https://virk.dk',
    'https://erhvervsstyrelsen.dk/start-virksomhed',
    'CVR Number',
  ),
  EE:   office(
    'Centre of Registers and Information Systems (RIK Estonia)',
    '+372 680 3160',
    'Lai 28, Tallinn, Estonia',
    'https://www.rik.ee',
    'info@rik.ee',
    '',
    '',
    '',
    'https://ariregister.rik.ee',
    'https://www.e-resident.gov.ee/start-a-company',
    'Registry Code',
  ),
  FI:   office(
    'Finnish Patent and Registration Office (PRH)',
    '+358 29 509 5000',
    'Sornaisten rantatie 13 C, Helsinki, Finland',
    'https://www.prh.fi',
    'prh@prh.fi',
    '',
    '',
    '',
    'https://www.ytj.fi',
    'https://www.prh.fi/en/kaupparekisteri',
    'Business ID (Y-tunnus)',
  ),
  FR:   office(
    'Infogreffe / Guichet Unique France',
    '+33 892 680 271',
    'Paris, France',
    'https://www.infogreffe.fr',
    'contact@infogreffe.fr',
    '',
    '',
    '',
    'https://www.guichet-entreprises.fr',
    'https://www.guichet-entreprises.fr/creer-son-entreprise',
    'SIREN / SIRET Number',
  ),
  DE:   office(
    'Unternehmensregister (German Commercial Register)',
    '+49 30 187810',
    'Berlin, Germany',
    'https://www.unternehmensregister.de',
    'info@handelsregister.de',
    '',
    '',
    '',
    'https://www.unternehmensregister.de',
    'https://www.gruenderplattform.de',
    'Handelsregisternummer',
  ),
  GR:   office(
    'General Commercial Registry (GEMI Greece)',
    '+30 210 328 6000',
    'Karaoli & Dimitriou 7, Athens, Greece',
    'https://www.businessportal.gr',
    'info@businessportal.gr',
    '',
    '',
    '',
    'https://www.businessportal.gr',
    'https://www.businessportal.gr/en/starting-a-business',
    'GEMI Number',
  ),
  HU:   office(
    'Court of Registration Hungary',
    '+36 1 488 2100',
    'Szalay u. 4, Budapest, Hungary',
    'https://www.e-cegjegyzek.hu',
    '',
    '',
    '',
    '',
    'https://www.e-cegjegyzek.hu',
    'https://www.magyarorszag.hu/en/business',
    'Company Registration Number',
  ),
  IS:   office(
    'Registers Iceland (Skra Island)',
    '+354 510 1000',
    'Armuli 10-12, Reykjavik, Iceland',
    'https://www.skra.is',
    'skra@skra.is',
    '',
    '',
    '',
    'https://www.skra.is/english/individuals/establish-a-company',
    'https://www.islandsstofa.is/en/start-a-business',
    'Kennitala (National ID / Company ID)',
  ),
  IT:   office(
    'Registro Imprese (Chamber of Commerce Italy)',
    '+39 06 47041',
    'Via Carlo Alberto 16, Rome, Italy',
    'https://www.registroimprese.it',
    'info@registroimprese.it',
    '',
    '',
    '',
    'https://www.registroimprese.it',
    'https://www.infocamere.it/starting-a-business',
    'Codice Fiscale / REA Number',
  ),
  LV:   office(
    'Enterprise Register Latvia',
    '+371 670 31600',
    'Pils laukums 1, Riga, Latvia',
    'https://www.ur.gov.lv',
    'info@ur.gov.lv',
    '',
    '',
    '',
    'https://www.ur.gov.lv',
    'https://www.ur.gov.lv/en/registration-of-undertakings',
    'Registration Number',
  ),
  LT:   office(
    'Centre of Registers Lithuania',
    '+370 5 268 8262',
    'Zygimantu 3, Vilnius, Lithuania',
    'https://www.registrucentras.lt',
    'info@registrucentras.lt',
    '',
    '',
    '',
    'https://www.registrucentras.lt',
    'https://www.registrucentras.lt/en/registration-of-legal-entities',
    'Company Code',
  ),
  LU:   office(
    'Registre de Commerce et des Societes Luxembourg',
    '+352 2478 2478',
    '14 rue Erasme, Luxembourg',
    'https://www.lbr.lu',
    'info@lbr.lu',
    '',
    '',
    '',
    'https://www.lbr.lu',
    'https://guichet.public.lu/en/entreprises/creation-developpement',
    'RCS Number',
  ),
  ME:   office(
    'Central Registry of Business Entities Montenegro',
    '+382 20 230 468',
    'Podgorica, Montenegro',
    'https://www.crps.me',
    'info@crps.me',
    '',
    '',
    '',
    'https://www.crps.me',
    'https://www.investmontenegro.me/starting-a-business',
    'PIB (Tax Identification Number)',
  ),
  NL:   office(
    'Netherlands Chamber of Commerce (KVK)',
    '+31 88 585 1585',
    'St.-Jacobsstraat 300, 3511 BT Utrecht, Netherlands',
    'https://www.kvk.nl',
    'info@kvk.nl',
    '',
    '',
    'https://www.linkedin.com/company/kamer-van-koophandel/',
    'https://www.kvk.nl/inschrijven-en-wijzigen/',
    'https://www.kvk.nl/ondernemersplein/',
    'KVK Number',
  ),
  MK:   office(
    'Central Registry North Macedonia',
    '+389 2 3117 171',
    'Skopje, North Macedonia',
    'https://www.crm.com.mk',
    'info@crm.com.mk',
    '',
    '',
    '',
    'https://www.crm.com.mk',
    'https://www.investinmacedonia.gov.mk/starting-a-business',
    'EMBS (Central Registry Number)',
  ),
  NO:   office(
    'Brønnøysundregistrene (Brreg Norway)',
    '+47 75 00 75 00',
    'Postboks 900, 8910 Brønnøysund, Norway',
    'https://www.brreg.no',
    'postmottak@brreg.no',
    '',
    '',
    '',
    'https://www.altinn.no',
    'https://www.brreg.no/en/start-and-run-business',
    'Organisasjonsnummer',
  ),
  PL:   office(
    'National Court Register (KRS Poland)',
    '+48 22 530 00 00',
    'ul. Czerniakowska 100, Warsaw, Poland',
    'https://www.gov.pl/web/krs',
    '',
    '',
    '',
    '',
    'https://ekrs.ms.gov.pl',
    'https://www.biznes.gov.pl/pl/portal',
    'KRS Number',
  ),
  PT:   office(
    'Instituto dos Registos e Notariado Portugal',
    '+351 217 988 000',
    'Av. D. Joao II, Lisbon, Portugal',
    'https://www.irn.mj.pt',
    'geral@irn.mj.pt',
    '',
    '',
    '',
    'https://eportugal.gov.pt',
    'https://www.portaldaempresa.pt',
    'NIPC (Numero de Identificacao de Pessoa Coletiva)',
  ),
  RO:   office(
    'National Trade Register Office Romania (ONRC)',
    '+40 21 310 2111',
    'B-dul Unirii 78, Bucharest, Romania',
    'https://www.onrc.ro',
    'info@onrc.ro',
    '',
    '',
    '',
    'https://portal.onrc.ro',
    'https://www.onrc.ro/index.php/en/registration-procedures',
    'CUI (Cod Unic de Inregistrare)',
  ),
  SK:   office(
    'ORSR (Register of Legal Entities Slovakia)',
    '+421 2 5971 1111',
    'Bratislava, Slovakia',
    'https://www.orsr.sk',
    '',
    '',
    '',
    '',
    'https://www.orsr.sk',
    'https://www.slovensko.sk/en/life-situation/life-situation/_zivnost',
    'ICO (Identification Number)',
  ),
  SI:   office(
    'AJPES Business Register Slovenia',
    '+386 1 588 16 00',
    'Trzaska 16, Ljubljana, Slovenia',
    'https://www.ajpes.si',
    'info@ajpes.si',
    '',
    '',
    '',
    'https://www.ajpes.si',
    'https://www.ajpes.si/eng/company_registration',
    'Registration Number',
  ),
  ES:   office(
    'Registro Mercantil Central / CIRCE Spain',
    '+34 902 102 102',
    'Madrid, Spain',
    'https://www.rmc.es',
    'rmc@rmc.es',
    '',
    '',
    '',
    'https://www.circe.es',
    'https://www.rmc.es/crear-empresa',
    'NIF (Numero de Identificacion Fiscal)',
  ),
  SE:   office(
    'Swedish Companies Registration Office (Bolagsverket)',
    '+46 771 670 670',
    '851 81 Sundsvall, Sweden',
    'https://www.bolagsverket.se',
    'info@bolagsverket.se',
    '',
    '',
    '',
    'https://foretagsverket.se',
    'https://www.bolagsverket.se/foretag/aktiebolag/starta-aktiebolag',
    'Organisationsnummer',
  ),
  TR:   office(
    'Central Registry System Turkey (MERSIS)',
    '+90 312 417 7777',
    'Ankara, Turkey',
    'https://www.ticaret.gov.tr',
    'bilgi@ticaret.gov.tr',
    '',
    '',
    '',
    'https://mersis.ticaret.gov.tr',
    'https://www.ticaret.gov.tr/sirket-kurulus-islemleri',
    'MERSIS Number',
  ),
  GB:   office(
    'Companies House United Kingdom',
    '+44 303 1234 500',
    'Crown Way, Cardiff CF14 3UZ, United Kingdom',
    'https://www.gov.uk/government/organisations/companies-house',
    'enquiries@companieshouse.gov.uk',
    'https://twitter.com/CompaniesHouse',
    '',
    'https://www.linkedin.com/company/companies-house/',
    'https://www.gov.uk/limited-company-formation',
    'https://www.gov.uk/set-up-limited-company',
    'Company Registration Number (CRN)',
  ),
  US:   office(
    'U.S. State Secretary of State Business Filing Offices (Representative: Delaware Division of Corporations)',
    '+1 302 739 3073',
    '401 Federal Street, Dover, DE 19901, United States',
    'https://corp.delaware.gov',
    '',
    '',
    '',
    '',
    'https://corp.delaware.gov/paytaxes/',
    'https://www.sba.gov/business-guide/launch-your-business/register-your-business',
    'Employer Identification Number (EIN)',
  ),
}
