import type { NatoMemberIsoCode } from './natoMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per NATO Ally.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const NATO_DOMESTIC_POST_SERVICES: Record<NatoMemberIsoCode, DomesticPostService> = {
  AL: post(
    'Posta Shqiptare',
    'https://www.postashqiptare.al/',
    'info@postashqiptare.al',
    'https://x.com/PostaShqiptare',
    '',
    'https://www.linkedin.com/company/posta-shqiptare/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1001',
    'Four-digit postcode',
  ),
  BE: post(
    'bpost',
    'https://www.bpost.be/',
    'info@bpost.be',
    'https://x.com/bpost_be',
    'https://www.instagram.com/bpost_be/',
    'https://www.linkedin.com/company/bpost/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  BG: post(
    'Bulgarian Posts',
    'https://www.bgpost.bg/',
    'info@bgpost.bg',
    'https://x.com/BulgarianPosts',
    '',
    'https://www.linkedin.com/company/bulgarian-posts/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  CA: post(
    'Canada Post',
    'https://www.canadapost-postescanada.ca/',
    'customercare@canadapost-postescanada.ca',
    'https://x.com/canadapostcorp',
    'https://www.instagram.com/canadapost/',
    'https://www.linkedin.com/company/canada-post/',
    'https://www.canadapost-postescanada.ca/cpc/en/tools/find-a-postal-code.page',
    'ANA NAN',
    '^[A-Z]\\d[A-Z] \\d[A-Z]\\d$',
    'K1A 0B1',
    'Canadian postal code (letter-digit-letter space digit-letter-digit)',
  ),
  HR: post(
    'Hrvatska pošta',
    'https://www.posta.hr/',
    'info@posta.hr',
    'https://x.com/HrvatskaPosta',
    'https://www.instagram.com/hrvatskaposta/',
    'https://www.linkedin.com/company/hrvatska-posta/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10000',
    'Five-digit postcode',
  ),
  CZ: post(
    'Česká pošta',
    'https://www.ceskaposta.cz/',
    'info@ceskaposta.cz',
    'https://x.com/CeskaPosta',
    'https://www.instagram.com/ceskaposta/',
    'https://www.linkedin.com/company/ceska-posta/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '110 00',
    'Five-digit postcode (space after third digit)',
  ),
  DK: post(
    'PostNord Danmark',
    'https://www.postnord.dk/',
    'kundeservice@postnord.dk',
    'https://x.com/PostNordDK',
    'https://www.instagram.com/postnorddk/',
    'https://www.linkedin.com/company/postnord/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1050',
    'Four-digit postcode',
  ),
  EE: post(
    'Omniva (Eesti Post)',
    'https://www.omniva.ee/',
    'info@omniva.ee',
    'https://x.com/OmnivaEE',
    'https://www.instagram.com/omniva/',
    'https://www.linkedin.com/company/omniva/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10111',
    'Five-digit postcode',
  ),
  FI: post(
    'Posti',
    'https://www.posti.fi/',
    'asiakaspalvelu@posti.fi',
    'https://x.com/PostiGroup',
    'https://www.instagram.com/postigroup/',
    'https://www.linkedin.com/company/posti/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00100',
    'Five-digit postcode',
  ),
  FR: post(
    'La Poste',
    'https://www.laposte.fr/',
    'contact@laposte.fr',
    'https://x.com/laposte',
    'https://www.instagram.com/laposte/',
    'https://www.linkedin.com/company/la-poste/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '75001',
    'Five-digit code postal',
  ),
  DE: post(
    'Deutsche Post',
    'https://www.deutschepost.de/',
    'info@deutschepost.de',
    'https://x.com/DeutschePost',
    'https://www.instagram.com/deutschepost/',
    'https://www.linkedin.com/company/deutsche-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10115',
    'Five-digit Postleitzahl',
  ),
  GR: post(
    'ELTA Hellenic Post',
    'https://www.elta.gr/',
    'info@elta.gr',
    'https://x.com/elta_gr',
    'https://www.instagram.com/elta_gr/',
    'https://www.linkedin.com/company/elta-hellenic-post/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '104 31',
    'Five-digit postcode (space after third digit)',
  ),
  HU: post(
    'Magyar Posta',
    'https://www.posta.hu/',
    'ugyfelszolgalat@posta.hu',
    'https://x.com/MagyarPosta',
    'https://www.instagram.com/magyarposta/',
    'https://www.linkedin.com/company/magyar-posta/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1051',
    'Four-digit postcode',
  ),
  IS: post(
    'Pósturinn (Iceland Post)',
    'https://www.postur.is/',
    'postur@postur.is',
    'https://x.com/Posturinn',
    'https://www.instagram.com/posturinn/',
    'https://www.linkedin.com/company/posturinn/',
    '',
    'NNN',
    '^\\d{3}$',
    '101',
    'Three-digit postcode',
  ),
  IT: post(
    'Poste Italiane',
    'https://www.poste.it/',
    'assistenza.clienti@poste.it',
    'https://x.com/PosteItaliane',
    'https://www.instagram.com/posteitaliane/',
    'https://www.linkedin.com/company/poste-italiane/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00118',
    'Five-digit CAP',
  ),
  LV: post(
    'Latvijas Pasts',
    'https://www.pasts.lv/',
    'info@pasts.lv',
    'https://x.com/LatvijasPasts',
    '',
    'https://www.linkedin.com/company/latvijas-pasts/',
    '',
    'LV-NNNN',
    '^LV-\\d{4}$',
    'LV-1050',
    'LV- prefix + four digits',
  ),
  LT: post(
    'Lietuvos paštas',
    'https://www.post.lt/',
    'info@post.lt',
    'https://x.com/LietuvosPastas',
    '',
    'https://www.linkedin.com/company/lietuvos-pastas/',
    '',
    'LT-NNNNN',
    '^LT-\\d{5}$',
    'LT-01100',
    'LT- prefix + five digits',
  ),
  LU: post(
    'POST Luxembourg',
    'https://www.post.lu/',
    'info@post.lu',
    'https://x.com/POSTLuxembourg',
    'https://www.instagram.com/postluxembourg/',
    'https://www.linkedin.com/company/post-luxembourg/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1019',
    'Four-digit postcode',
  ),
  ME: post(
    'Pošta Crne Gore',
    'https://www.postacg.me/',
    'info@postacg.me',
    '',
    '',
    'https://www.linkedin.com/company/posta-crne-gore/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '81000',
    'Five-digit postcode',
  ),
  NL: post(
    'PostNL',
    'https://www.postnl.nl/',
    'klantenservice@postnl.nl',
    'https://x.com/PostNL',
    'https://www.instagram.com/postnl/',
    'https://www.linkedin.com/company/postnl/',
    '',
    'NNNN AA',
    '^\\d{4} [A-Z]{2}$',
    '1012 AB',
    'Four digits + space + two letters',
  ),
  MK: post(
    'North Macedonia Post (Пошта на Северна Македонија)',
    'https://www.posta.com.mk/',
    'info@posta.com.mk',
    '',
    '',
    'https://www.linkedin.com/company/north-macedonia-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  NO: post(
    'Posten Norge (PostNord Norge)',
    'https://www.posten.no/',
    'kundeservice@posten.no',
    'https://x.com/PostenNorge',
    'https://www.instagram.com/postennorge/',
    'https://www.linkedin.com/company/posten-norge/',
    '',
    'NNNN',
    '^\\d{4}$',
    '0150',
    'Four-digit postcode',
  ),
  PL: post(
    'Poczta Polska',
    'https://www.poczta-polska.pl/',
    'kontakt@poczta-polska.pl',
    'https://x.com/PocztaPolska',
    'https://www.instagram.com/pocztapolska/',
    'https://www.linkedin.com/company/poczta-polska/',
    '',
    'NN-NNN',
    '^\\d{2}-\\d{3}$',
    '00-950',
    'Five-digit postcode (hyphen after second digit)',
  ),
  PT: post(
    'CTT Correios de Portugal',
    'https://www.ctt.pt/',
    'info@ctt.pt',
    'https://x.com/CTT',
    'https://www.instagram.com/ctt/',
    'https://www.linkedin.com/company/ctt/',
    '',
    'NNNN-NNN',
    '^\\d{4}-\\d{3}$',
    '1000-001',
    'Seven-digit código postal (four + hyphen + three)',
  ),
  RO: post(
    'Poșta Română',
    'https://www.posta-romana.ro/',
    'relatii.clienti@posta-romana.ro',
    'https://x.com/PostaRomana',
    'https://www.instagram.com/postaromana/',
    'https://www.linkedin.com/company/posta-romana/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '010011',
    'Six-digit postcode',
  ),
  SK: post(
    'Slovenská pošta',
    'https://www.posta.sk/',
    'info@posta.sk',
    'https://x.com/SlovenskaPosta',
    '',
    'https://www.linkedin.com/company/slovenska-posta/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '811 01',
    'Five-digit postcode (space after third digit)',
  ),
  SI: post(
    'Pošta Slovenije',
    'https://www.posta.si/',
    'info@posta.si',
    'https://x.com/PostaSlovenije',
    '',
    'https://www.linkedin.com/company/posta-slovenije/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode (SI- prefix optional)',
  ),
  ES: post(
    'Correos',
    'https://www.correos.es/',
    'atencioncliente@correos.es',
    'https://x.com/Correos',
    'https://www.instagram.com/correos/',
    'https://www.linkedin.com/company/correos/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '28001',
    'Five-digit código postal',
  ),
  SE: post(
    'PostNord Sverige',
    'https://www.postnord.se/',
    'kundservice@postnord.se',
    'https://x.com/PostNordSE',
    'https://www.instagram.com/postnordse/',
    'https://www.linkedin.com/company/postnord/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '111 22',
    'Five-digit postcode (space after third digit)',
  ),
  TR: post(
    'PTT (Türkiye Post)',
    'https://www.ptt.gov.tr/',
    'info@ptt.gov.tr',
    'https://x.com/PTT',
    'https://www.instagram.com/ptt/',
    'https://www.linkedin.com/company/ptt/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '06100',
    'Five-digit postcode',
  ),
  GB: post(
    'Royal Mail',
    'https://www.royalmail.com/',
    'customerservice@royalmail.com',
    'https://x.com/RoyalMail',
    'https://www.instagram.com/royalmailofficial/',
    'https://www.linkedin.com/company/royal-mail/',
    'https://developer.royalmail.net/',
    'AAN NAA',
    '^[A-Z]{1,2}\\d[A-Z\\d]? \\d[A-Z]{2}$',
    'SW1A 1AA',
    'UK postcode (outward + inward codes)',
  ),
  US: post(
    'United States Postal Service (USPS)',
    'https://www.usps.com/',
    'uspscustomerservice@usps.gov',
    'https://x.com/USPS',
    'https://www.instagram.com/usps/',
    'https://www.linkedin.com/company/usps/',
    'https://developer.usps.com/',
    'NNNNN',
    '^\\d{5}$',
    '20500',
    'Five-digit ZIP; ZIP+4 optional (NNNNN-NNNN)',
  ),
}
