import type { NatoMemberIsoCode } from './natoMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for NATO Allies in this module
 * (informational; verify URLs, handles, forms portals, and API bases before production use).
 * Self-contained — no imports from other alliance modules. `apiEndpoint` is almost always
 * empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const NATO_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  NatoMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AL: roster(
    ip(
      'copyright',
      'General Directorate of Industrial Property (GDIP Albania) — copyright',
      'https://www.dppi.gov.al',
      'info@dppi.gov.al',
      '',
      '',
      'https://www.dppi.gov.al',
    ),
    ip(
      'trademarks',
      'General Directorate of Industrial Property (GDIP Albania)',
      'https://www.dppi.gov.al',
      'info@dppi.gov.al',
      '',
      '',
      'https://www.dppi.gov.al',
    ),
    ip(
      'patents',
      'General Directorate of Industrial Property (GDIP Albania)',
      'https://www.dppi.gov.al',
      'info@dppi.gov.al',
      '',
      '',
      'https://www.dppi.gov.al',
    ),
  ),
  BE: roster(
    ip(
      'copyright',
      'FPS Economy — Intellectual Property (Belgium) — copyright',
      'https://economie.fgov.be/en/themes/intellectual-property',
      '',
      '',
      '',
      'https://economie.fgov.be/en/themes/intellectual-property',
    ),
    ip(
      'trademarks',
      'FPS Economy — Intellectual Property (Belgium)',
      'https://economie.fgov.be/en/themes/intellectual-property',
      'contact@economie.fgov.be',
      '',
      'https://www.linkedin.com/company/fps-economy/',
      'https://economie.fgov.be/en/themes/intellectual-property',
    ),
    ip(
      'patents',
      'FPS Economy — Intellectual Property (Belgium)',
      'https://economie.fgov.be/en/themes/intellectual-property',
      'contact@economie.fgov.be',
      '',
      'https://www.linkedin.com/company/fps-economy/',
      'https://economie.fgov.be/en/themes/intellectual-property',
    ),
  ),
  BG: roster(
    ip(
      'copyright',
      'Patent Office of the Republic of Bulgaria — copyright',
      'https://www.bpo.bg',
      'info@bpo.bg',
      '',
      '',
      'https://www.bpo.bg',
    ),
    ip(
      'trademarks',
      'Patent Office of the Republic of Bulgaria',
      'https://www.bpo.bg',
      'info@bpo.bg',
      '',
      '',
      'https://www.bpo.bg',
    ),
    ip(
      'patents',
      'Patent Office of the Republic of Bulgaria',
      'https://www.bpo.bg',
      'info@bpo.bg',
      '',
      '',
      'https://www.bpo.bg',
    ),
  ),
  CA: roster(
    ip(
      'copyright',
      'Canadian Intellectual Property Office (CIPO) — copyright',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'trademarks',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'patents',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
  ),
  HR: roster(
    ip(
      'copyright',
      'State Intellectual Property Office (DZIV, Croatia) — copyright',
      'https://www.dziv.hr',
      'ured@dziv.hr',
      '',
      '',
      'https://www.dziv.hr',
    ),
    ip(
      'trademarks',
      'State Intellectual Property Office (DZIV, Croatia)',
      'https://www.dziv.hr',
      'ured@dziv.hr',
      '',
      '',
      'https://www.dziv.hr',
    ),
    ip(
      'patents',
      'State Intellectual Property Office (DZIV, Croatia)',
      'https://www.dziv.hr',
      'ured@dziv.hr',
      '',
      '',
      'https://www.dziv.hr',
    ),
  ),
  CZ: roster(
    ip(
      'copyright',
      'Industrial Property Office of the Czech Republic — copyright',
      'https://upv.gov.cz',
      'podatelna@upv.cz',
      '',
      '',
      'https://upv.gov.cz',
    ),
    ip(
      'trademarks',
      'Industrial Property Office of the Czech Republic',
      'https://upv.gov.cz',
      'podatelna@upv.cz',
      '',
      '',
      'https://upv.gov.cz',
    ),
    ip(
      'patents',
      'Industrial Property Office of the Czech Republic',
      'https://upv.gov.cz',
      'podatelna@upv.cz',
      '',
      '',
      'https://upv.gov.cz',
    ),
  ),
  DK: roster(
    ip(
      'copyright',
      'Ministry of Culture (Denmark) — copyright',
      'https://www.kum.dk',
      '',
      '',
      '',
      'https://www.kum.dk',
    ),
    ip(
      'trademarks',
      'Danish Patent and Trademark Office',
      'https://www.dkpto.dk',
      'dkpto@dkpto.dk',
      '',
      '',
      'https://www.dkpto.dk/english',
    ),
    ip(
      'patents',
      'Danish Patent and Trademark Office',
      'https://www.dkpto.dk',
      'dkpto@dkpto.dk',
      '',
      '',
      'https://www.dkpto.dk/english',
    ),
  ),
  EE: roster(
    ip(
      'copyright',
      'Estonian Patent Office — copyright',
      'https://www.epa.ee',
      'info@epa.ee',
      '',
      '',
      'https://www.epa.ee',
    ),
    ip(
      'trademarks',
      'Estonian Patent Office',
      'https://www.epa.ee',
      'info@epa.ee',
      '',
      '',
      'https://www.epa.ee',
    ),
    ip(
      'patents',
      'Estonian Patent Office',
      'https://www.epa.ee',
      'info@epa.ee',
      '',
      '',
      'https://www.epa.ee',
    ),
  ),
  FI: roster(
    ip(
      'copyright',
      'Finnish Patent and Registration Office (PRH) — copyright',
      'https://www.prh.fi/en',
      '',
      '',
      '',
      'https://www.prh.fi/en',
    ),
    ip(
      'trademarks',
      'Finnish Patent and Registration Office (PRH)',
      'https://www.prh.fi/en',
      'customer.service@prh.fi',
      '',
      '',
      'https://www.prh.fi/en',
    ),
    ip(
      'patents',
      'Finnish Patent and Registration Office (PRH)',
      'https://www.prh.fi/en',
      'customer.service@prh.fi',
      '',
      '',
      'https://www.prh.fi/en',
    ),
  ),
  FR: roster(
    ip(
      'copyright',
      'Ministry of Culture (France) — copyright',
      'https://www.culture.gouv.fr',
      '',
      '',
      '',
      'https://www.culture.gouv.fr',
    ),
    ip(
      'trademarks',
      'National Institute of Industrial Property (INPI France)',
      'https://www.inpi.fr',
      'contact@inpi.fr',
      'https://x.com/INPIfr',
      'https://www.linkedin.com/company/inpi/',
      'https://www.inpi.fr/fr/services-et-prestations',
    ),
    ip(
      'patents',
      'National Institute of Industrial Property (INPI France)',
      'https://www.inpi.fr',
      'contact@inpi.fr',
      'https://x.com/INPIfr',
      'https://www.linkedin.com/company/inpi/',
      'https://www.inpi.fr/fr/services-et-prestations',
    ),
  ),
  DE: roster(
    ip(
      'copyright',
      'German Patent and Trade Mark Office (DPMA) — copyright liaison',
      'https://www.dpma.de',
      '',
      '',
      '',
      'https://www.dpma.de',
    ),
    ip(
      'trademarks',
      'German Patent and Trade Mark Office (DPMA)',
      'https://www.dpma.de',
      'poststelle@dpma.de',
      '',
      'https://www.linkedin.com/company/dpma/',
      'https://www.dpma.de/english/services/index.html',
    ),
    ip(
      'patents',
      'German Patent and Trade Mark Office (DPMA)',
      'https://www.dpma.de',
      'poststelle@dpma.de',
      '',
      'https://www.linkedin.com/company/dpma/',
      'https://www.dpma.de/english/services/index.html',
    ),
  ),
  GR: roster(
    ip(
      'copyright',
      'Hellenic Industrial Property Organisation (OBI) — copyright',
      'https://www.obi.gr',
      'info@obi.gr',
      '',
      '',
      'https://www.obi.gr',
    ),
    ip(
      'trademarks',
      'Hellenic Industrial Property Organisation (OBI)',
      'https://www.obi.gr',
      'info@obi.gr',
      '',
      '',
      'https://www.obi.gr',
    ),
    ip(
      'patents',
      'Hellenic Industrial Property Organisation (OBI)',
      'https://www.obi.gr',
      'info@obi.gr',
      '',
      '',
      'https://www.obi.gr',
    ),
  ),
  HU: roster(
    ip(
      'copyright',
      'Hungarian Intellectual Property Office (HIPO) — copyright',
      'https://www.sztnh.gov.hu',
      'sztnh@sztnh.gov.hu',
      '',
      '',
      'https://www.sztnh.gov.hu',
    ),
    ip(
      'trademarks',
      'Hungarian Intellectual Property Office (HIPO)',
      'https://www.sztnh.gov.hu',
      'sztnh@sztnh.gov.hu',
      '',
      '',
      'https://www.sztnh.gov.hu',
    ),
    ip(
      'patents',
      'Hungarian Intellectual Property Office (HIPO)',
      'https://www.sztnh.gov.hu',
      'sztnh@sztnh.gov.hu',
      '',
      '',
      'https://www.sztnh.gov.hu',
    ),
  ),
  IS: roster(
    ip(
      'copyright',
      'Ministry of Education, Science and Culture (Iceland) — copyright',
      'https://www.government.is/ministries/ministry-of-education-science-and-culture/',
      '',
      '',
      '',
      'https://www.government.is/ministries/ministry-of-education-science-and-culture/',
    ),
    ip(
      'trademarks',
      'Patent Office of Iceland (Einkaleyfastofa)',
      'https://www.einkaleyfastofa.is',
      'einkaleyfastofa@einkaleyfastofa.is',
      '',
      '',
      'https://www.einkaleyfastofa.is/english/trademark',
    ),
    ip(
      'patents',
      'Patent Office of Iceland (Einkaleyfastofa)',
      'https://www.einkaleyfastofa.is',
      'einkaleyfastofa@einkaleyfastofa.is',
      '',
      '',
      'https://www.einkaleyfastofa.is/english/patent',
    ),
  ),
  IT: roster(
    ip(
      'copyright',
      'Ministry of Culture — copyright (Italy)',
      'https://www.beniculturali.it',
      '',
      '',
      '',
      'https://www.uibm.gov.it',
    ),
    ip(
      'trademarks',
      'Italian Patent and Trademark Office (UIBM)',
      'https://www.uibm.gov.it',
      '',
      '',
      '',
      'https://www.uibm.gov.it',
    ),
    ip(
      'patents',
      'Italian Patent and Trademark Office (UIBM)',
      'https://www.uibm.gov.it',
      '',
      '',
      '',
      'https://www.uibm.gov.it',
    ),
  ),
  LV: roster(
    ip(
      'copyright',
      'Latvian Patent Office — copyright',
      'https://www.lrpv.gov.lv',
      'lrpv@lrpv.gov.lv',
      '',
      '',
      'https://www.lrpv.gov.lv',
    ),
    ip(
      'trademarks',
      'Latvian Patent Office',
      'https://www.lrpv.gov.lv',
      'lrpv@lrpv.gov.lv',
      '',
      '',
      'https://www.lrpv.gov.lv',
    ),
    ip(
      'patents',
      'Latvian Patent Office',
      'https://www.lrpv.gov.lv',
      'lrpv@lrpv.gov.lv',
      '',
      '',
      'https://www.lrpv.gov.lv',
    ),
  ),
  LT: roster(
    ip(
      'copyright',
      'State Patent Bureau of the Republic of Lithuania — copyright',
      'https://vpb.lrv.lt',
      '',
      '',
      '',
      'https://vpb.lrv.lt',
    ),
    ip(
      'trademarks',
      'State Patent Bureau of the Republic of Lithuania',
      'https://vpb.lrv.lt',
      '',
      '',
      '',
      'https://vpb.lrv.lt',
    ),
    ip(
      'patents',
      'State Patent Bureau of the Republic of Lithuania',
      'https://vpb.lrv.lt',
      '',
      '',
      '',
      'https://vpb.lrv.lt',
    ),
  ),
  LU: roster(
    ip(
      'copyright',
      'Intellectual Property Office Luxembourg — copyright',
      'https://www.etat.lu/ip',
      '',
      '',
      '',
      'https://www.etat.lu/ip',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office Luxembourg',
      'https://www.etat.lu/ip',
      '',
      '',
      '',
      'https://www.etat.lu/ip',
    ),
    ip(
      'patents',
      'Intellectual Property Office Luxembourg',
      'https://www.etat.lu/ip',
      '',
      '',
      '',
      'https://www.etat.lu/ip',
    ),
  ),
  ME: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Montenegro — copyright',
      'https://www.ipo.gov.me',
      'ipo@ipo.gov.me',
      '',
      '',
      'https://www.ipo.gov.me',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Montenegro',
      'https://www.ipo.gov.me',
      'ipo@ipo.gov.me',
      '',
      '',
      'https://www.ipo.gov.me',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Montenegro',
      'https://www.ipo.gov.me',
      'ipo@ipo.gov.me',
      '',
      '',
      'https://www.ipo.gov.me',
    ),
  ),
  NL: roster(
    ip(
      'copyright',
      'Netherlands Enterprise Agency (RVO) — copyright',
      'https://www.rvo.nl/onderwerpen/intellectueel-eigendom',
      '',
      '',
      '',
      'https://www.rvo.nl/onderwerpen/intellectueel-eigendom',
    ),
    ip(
      'trademarks',
      'Netherlands Enterprise Agency (RVO) — intellectual property',
      'https://www.rvo.nl/onderwerpen/intellectueel-eigendom',
      'info@rvo.nl',
      '',
      '',
      'https://www.rvo.nl/onderwerpen/intellectueel-eigendom',
    ),
    ip(
      'patents',
      'Netherlands Enterprise Agency (RVO) — intellectual property',
      'https://www.rvo.nl/onderwerpen/intellectueel-eigendom',
      'info@rvo.nl',
      '',
      '',
      'https://www.rvo.nl/onderwerpen/intellectueel-eigendom',
    ),
  ),
  MK: roster(
    ip(
      'copyright',
      'State Office of Industrial Property (North Macedonia) — copyright',
      'https://www.ippo.gov.mk',
      'info@ippo.gov.mk',
      '',
      '',
      'https://www.ippo.gov.mk',
    ),
    ip(
      'trademarks',
      'State Office of Industrial Property (North Macedonia)',
      'https://www.ippo.gov.mk',
      'info@ippo.gov.mk',
      '',
      '',
      'https://www.ippo.gov.mk',
    ),
    ip(
      'patents',
      'State Office of Industrial Property (North Macedonia)',
      'https://www.ippo.gov.mk',
      'info@ippo.gov.mk',
      '',
      '',
      'https://www.ippo.gov.mk',
    ),
  ),
  NO: roster(
    ip(
      'copyright',
      'Ministry of Culture and Equality (Norway) — copyright',
      'https://www.regjeringen.no/en/dep/kud/id545/',
      '',
      '',
      '',
      'https://www.regjeringen.no/en/dep/kud/id545/',
    ),
    ip(
      'trademarks',
      'Norwegian Industrial Property Office (Patentstyret)',
      'https://www.patentstyret.no',
      'post@patentstyret.no',
      'https://x.com/patentstyret',
      'https://www.linkedin.com/company/patentstyret/',
      'https://www.patentstyret.no/en/trademarks/',
    ),
    ip(
      'patents',
      'Norwegian Industrial Property Office (Patentstyret)',
      'https://www.patentstyret.no',
      'post@patentstyret.no',
      'https://x.com/patentstyret',
      'https://www.linkedin.com/company/patentstyret/',
      'https://www.patentstyret.no/en/patents/',
    ),
  ),
  PL: roster(
    ip(
      'copyright',
      'Polish Patent Office (UPRP) — copyright',
      'https://www.uprp.gov.pl',
      '',
      '',
      '',
      'https://www.uprp.gov.pl',
    ),
    ip(
      'trademarks',
      'Polish Patent Office (UPRP)',
      'https://www.uprp.gov.pl',
      '',
      '',
      '',
      'https://www.uprp.gov.pl',
    ),
    ip(
      'patents',
      'Polish Patent Office (UPRP)',
      'https://www.uprp.gov.pl',
      '',
      '',
      '',
      'https://www.uprp.gov.pl',
    ),
  ),
  PT: roster(
    ip(
      'copyright',
      'National Institute of Industrial Property (INPI Portugal) — copyright',
      'https://www.inpi.pt',
      'geral@inpi.pt',
      '',
      '',
      'https://www.inpi.pt',
    ),
    ip(
      'trademarks',
      'National Institute of Industrial Property (INPI Portugal)',
      'https://www.inpi.pt',
      'geral@inpi.pt',
      '',
      '',
      'https://www.inpi.pt',
    ),
    ip(
      'patents',
      'National Institute of Industrial Property (INPI Portugal)',
      'https://www.inpi.pt',
      'geral@inpi.pt',
      '',
      '',
      'https://www.inpi.pt',
    ),
  ),
  RO: roster(
    ip(
      'copyright',
      'State Office for Inventions and Trademarks (OSIM Romania) — copyright',
      'https://www.osim.ro',
      'office@osim.ro',
      '',
      '',
      'https://www.osim.ro',
    ),
    ip(
      'trademarks',
      'State Office for Inventions and Trademarks (OSIM Romania)',
      'https://www.osim.ro',
      'office@osim.ro',
      '',
      '',
      'https://www.osim.ro',
    ),
    ip(
      'patents',
      'State Office for Inventions and Trademarks (OSIM Romania)',
      'https://www.osim.ro',
      'office@osim.ro',
      '',
      '',
      'https://www.osim.ro',
    ),
  ),
  SK: roster(
    ip(
      'copyright',
      'Industrial Property Office of the Slovak Republic — copyright',
      'https://www.upvsr.sk',
      '',
      '',
      '',
      'https://www.upvsr.sk',
    ),
    ip(
      'trademarks',
      'Industrial Property Office of the Slovak Republic',
      'https://www.upvsr.sk',
      '',
      '',
      '',
      'https://www.upvsr.sk',
    ),
    ip(
      'patents',
      'Industrial Property Office of the Slovak Republic',
      'https://www.upvsr.sk',
      '',
      '',
      '',
      'https://www.upvsr.sk',
    ),
  ),
  SI: roster(
    ip(
      'copyright',
      'Slovenian Intellectual Property Office — copyright',
      'https://www.uil.si',
      '',
      '',
      '',
      'https://www.uil.si',
    ),
    ip(
      'trademarks',
      'Slovenian Intellectual Property Office',
      'https://www.uil.si',
      '',
      '',
      '',
      'https://www.uil.si',
    ),
    ip(
      'patents',
      'Slovenian Intellectual Property Office',
      'https://www.uil.si',
      '',
      '',
      '',
      'https://www.uil.si',
    ),
  ),
  ES: roster(
    ip(
      'copyright',
      'Spanish Patent and Trademark Office (OEPM) — copyright liaison',
      'https://www.oepm.es',
      '',
      '',
      '',
      'https://www.oepm.es',
    ),
    ip(
      'trademarks',
      'Spanish Patent and Trademark Office (OEPM)',
      'https://www.oepm.es',
      'informacion@oepm.es',
      '',
      '',
      'https://www.oepm.es/es/que_hacemos.html',
    ),
    ip(
      'patents',
      'Spanish Patent and Trademark Office (OEPM)',
      'https://www.oepm.es',
      'informacion@oepm.es',
      '',
      '',
      'https://www.oepm.es/es/que_hacemos.html',
    ),
  ),
  SE: roster(
    ip(
      'copyright',
      'Swedish Patent and Registration Office (PRV) — copyright',
      'https://www.prv.se',
      '',
      '',
      '',
      'https://www.prv.se',
    ),
    ip(
      'trademarks',
      'Swedish Patent and Registration Office (PRV)',
      'https://www.prv.se',
      'prv@prv.se',
      '',
      '',
      'https://www.prv.se/en',
    ),
    ip(
      'patents',
      'Swedish Patent and Registration Office (PRV)',
      'https://www.prv.se',
      'prv@prv.se',
      '',
      '',
      'https://www.prv.se/en',
    ),
  ),
  TR: roster(
    ip(
      'copyright',
      'Turkish Patent and Trademark Office (TürkPatent) — copyright',
      'https://www.turkpatent.gov.tr',
      '',
      '',
      '',
      'https://www.turkpatent.gov.tr',
    ),
    ip(
      'trademarks',
      'Turkish Patent and Trademark Office (TürkPatent)',
      'https://www.turkpatent.gov.tr',
      '',
      '',
      '',
      'https://www.turkpatent.gov.tr',
    ),
    ip(
      'patents',
      'Turkish Patent and Trademark Office (TürkPatent)',
      'https://www.turkpatent.gov.tr',
      '',
      '',
      '',
      'https://www.turkpatent.gov.tr',
    ),
  ),
  GB: roster(
    ip(
      'copyright',
      'Intellectual Property Office (UK) — copyright guidance',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'patents',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
  ),
  US: roster(
    ip(
      'copyright',
      'U.S. Copyright Office',
      'https://www.copyright.gov',
      '',
      'https://x.com/CopyrightOffice',
      'https://www.linkedin.com/company/us-copyright-office/',
      'https://www.copyright.gov/registration/',
    ),
    ip(
      'trademarks',
      'United States Patent and Trademark Office (USPTO)',
      'https://www.uspto.gov',
      '',
      'https://x.com/uspto',
      'https://www.linkedin.com/company/uspto/',
      'https://www.uspto.gov/apply',
      'https://developer.uspto.gov/',
    ),
    ip(
      'patents',
      'United States Patent and Trademark Office (USPTO)',
      'https://www.uspto.gov',
      '',
      'https://x.com/uspto',
      'https://www.linkedin.com/company/uspto/',
      'https://www.uspto.gov/apply',
      'https://developer.uspto.gov/',
    ),
  ),
}
