import type { NatoMemberIsoCode } from './natoMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2 for the
 * 32 NATO Allies (informational; verify against USGS Mineral Commodity Summaries, BGS World
 * Mineral Production, BGR DERA, and UN Comtrade periodically). The Alliance spans large primary
 * producers (CA, US, AU-style? NATO has no AU), refining / re-export hubs (DE, NL, BE, IT, FR,
 * GB), and a major hydrocarbon exporter (NO). Hydrocarbon-derived elemental references
 * (Carbon (C), Hydrogen (H)) appear for major crude / gas exporters (NO, US, CA, GB, RO, NL
 * legacy), and for coal exporters (PL, CZ, TR). Aluminum (Al) and Copper (Cu) appear across
 * smelting hubs (IS Norðurál, NO Hydro / Karmøy, PL KGHM, FI Outokumpu, BE Umicore / Olen, BG
 * Pirdop, RS-region Bor adjacency note — RS is non-NATO).
 */
export const NATO_MAIN_EXPORTED_ELEMENTS: Record<NatoMemberIsoCode, MainExportedElements> = {
  AL: e(
    'Chromium (Cr)',
    'Copper (Cu)',
    'Nickel (Ni)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
  ),
  BE: e(
    'Copper (Cu)',
    'Zinc (Zn)',
    'Cobalt (Co)',
    'Germanium (Ge)',
    'Indium (In)',
    'Silver (Ag)',
    'Iron (Fe)',
  ),
  BG: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Iron (Fe)',
    'Silver (Ag)',
    'Aluminum (Al)',
  ),
  CA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Potassium (K)',
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Gold (Au)',
    'Uranium (U)',
  ),
  HR: e(
    'Calcium (Ca)',
    'Carbon (C)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Magnesium (Mg)',
  ),
  CZ: e(
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Lithium (Li)',
  ),
  DK: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Nitrogen (N)',
  ),
  EE: e(
    'Carbon (C)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Phosphorus (P)',
    'Hydrogen (H)',
  ),
  FI: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Chromium (Cr)',
    'Iron (Fe)',
    'Gold (Au)',
  ),
  FR: e(
    'Uranium (U)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Titanium (Ti)',
    'Gold (Au)',
  ),
  DE: e(
    'Carbon (C)',
    'Copper (Cu)',
    'Potassium (K)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Gallium (Ga)',
  ),
  GR: e(
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Iron (Fe)',
    'Magnesium (Mg)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Zinc (Zn)',
  ),
  HU: e(
    'Aluminum (Al)',
    'Manganese (Mn)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  IS: e(
    'Aluminum (Al)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Chlorine (Cl)',
    'Hydrogen (H)',
  ),
  IT: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Lead (Pb)',
    'Zinc (Zn)',
  ),
  LV: e(
    'Calcium (Ca)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Sodium (Na)',
    'Magnesium (Mg)',
  ),
  LT: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Nitrogen (N)',
  ),
  LU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  ME: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Silicon (Si)',
  ),
  NL: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Nitrogen (N)',
    'Sulfur (S)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Iron (Fe)',
  ),
  MK: e(
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Nickel (Ni)',
    'Calcium (Ca)',
    'Silicon (Si)',
  ),
  NO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Iron (Fe)',
  ),
  PL: e(
    'Copper (Cu)',
    'Silver (Ag)',
    'Carbon (C)',
    'Sulfur (S)',
    'Zinc (Zn)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  PT: e(
    'Copper (Cu)',
    'Tungsten (W)',
    'Tin (Sn)',
    'Lithium (Li)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  RO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Gold (Au)',
    'Silicon (Si)',
  ),
  SK: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Magnesium (Mg)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  SI: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  ES: e(
    'Copper (Cu)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Tungsten (W)',
    'Calcium (Ca)',
  ),
  SE: e(
    'Iron (Fe)',
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Aluminum (Al)',
  ),
  TR: e(
    'Iron (Fe)',
    'Chromium (Cr)',
    'Copper (Cu)',
    'Boron (B)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Zinc (Zn)',
  ),
  GB: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Lithium (Li)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Tin (Sn)',
  ),
  US: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Helium (He)',
    'Copper (Cu)',
    'Gold (Au)',
    'Molybdenum (Mo)',
    'Silicon (Si)',
  ),
}
