import type { NationalBankingInstitution } from './types'
import type { NatoMemberIsoCode } from './natoMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per NATO Ally state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const NATO_NATIONAL_BANKING_INSTITUTIONS: Record<
  NatoMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AL: [
    bank(
      'Banka Kombetare Tregtare',
      '+355 4 227 8156',
      'Rruga e Vilave, Tirana, Albania',
      '',
      '',
      'https://www.bkt.com.al',
      'info@bkt.com.al',
      '',
      '',
      '',
      '',
      'NCBAALTX',
      '',
    ),
    bank(
      'Raiffeisen Bank Albania',
      '+355 4 227 4740',
      'Blvd. Bajram Curri, Tirana, Albania',
      '',
      '',
      'https://www.raiffeisen.al',
      'info@raiffeisen.al',
      '',
      '',
      '',
      '',
      'SGSBALTX',
      '',
    ),
    bank(
      'Credins Bank',
      '+355 4 535 3000',
      'Rruga Ibrahim Rugova, Tirana, Albania',
      '',
      '',
      'https://www.bankacredins.com',
      'info@bankacredins.com',
      '',
      '',
      '',
      '',
      'CDISALTR',
      '',
    ),
  ],
  BE: [
    bank(
      'KBC Bank',
      '+32 2 429 2121',
      'Havenlaan 2, 1080 Brussels, Belgium',
      'https://apps.apple.com/be/app/kbc-mobile/id428811587',
      'https://play.google.com/store/apps/details?id=com.kbc.mobile.android.phone.kbc',
      'https://www.kbc.be',
      'info@kbc.be',
      'https://twitter.com/kbc_be',
      'https://www.instagram.com/kbc_be/',
      'https://www.linkedin.com/company/kbc-bank/',
      '',
      'KREDBEBB',
      'https://developer.kbc.be',
    ),
    bank(
      'BNP Paribas Fortis',
      '+32 2 228 1111',
      'Montagne du Parc 3, 1000 Brussels, Belgium',
      'https://apps.apple.com/be/app/bnp-paribas-fortis-mobile/id428811587',
      'https://play.google.com/store/apps/details?id=be.fortis.mobile',
      'https://www.bnpparibasfortis.be',
      'contact@bnpparibasfortis.be',
      'https://twitter.com/BNPParibasFortis',
      'https://www.instagram.com/bnpparibasfortis/',
      'https://www.linkedin.com/company/bnp-paribas-fortis/',
      '',
      'GEBABEBB',
      '',
    ),
    bank(
      'ING Belgium',
      '+32 2 464 60 04',
      'Avenue Marnix 24, 1000 Brussels, Belgium',
      'https://apps.apple.com/be/app/ing-banking/id474807486',
      'https://play.google.com/store/apps/details?id=com.ing.mobile',
      'https://www.ing.be',
      'contact@ing.be',
      'https://twitter.com/INGBelgium',
      'https://www.instagram.com/ingbelgium/',
      'https://www.linkedin.com/company/ing-belgium/',
      '',
      'BBRUBEBB',
      'https://developer.ing.com',
    ),
  ],
  BG: [
    bank(
      'UniCredit Bulbank',
      '+359 2 9337 000',
      '7 Sveta Nedelya Sq, Sofia, Bulgaria',
      '',
      '',
      'https://www.unicreditbulbank.bg',
      'contact@unicreditgroup.bg',
      '',
      '',
      '',
      '',
      'UNCRBGSF',
      '',
    ),
    bank(
      'DSK Bank',
      '+359 2 0700 10 375',
      '19 Moskovska St, Sofia, Bulgaria',
      '',
      '',
      'https://dskbank.bg',
      'contactcenter@dskbank.bg',
      '',
      '',
      '',
      '',
      'STSABGSF',
      '',
    ),
    bank(
      'United Bulgarian Bank',
      '+359 2 483 1717',
      '89B Vitosha Blvd, Sofia, Bulgaria',
      '',
      '',
      'https://www.ubb.bg',
      'contact.center@ubb.bg',
      '',
      '',
      '',
      '',
      'UBBSBGSF',
      '',
    ),
  ],
  CA: [
    bank(
      'Royal Bank of Canada',
      '+1 416 974 5151',
      '200 Bay Street, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/rbc-mobile/id407597290',
      'https://play.google.com/store/apps/details?id=com.rbc.mobile.android',
      'https://www.rbc.com',
      'info@rbc.com',
      'https://twitter.com/RBC',
      'https://www.instagram.com/rbc/',
      'https://www.linkedin.com/company/rbc/',
      '',
      'ROYCCAT2',
      '',
    ),
    bank(
      'Toronto-Dominion Bank',
      '+1 416 308 9030',
      '66 Wellington Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/td-canada/id358071948',
      'https://play.google.com/store/apps/details?id=com.td',
      'https://www.td.com',
      'customer.service@td.com',
      'https://twitter.com/TD_Canada',
      'https://www.instagram.com/td_canada/',
      'https://www.linkedin.com/company/td/',
      '',
      'TDOMCATTTOR',
      '',
    ),
    bank(
      'Scotiabank',
      '+1 416 933 8000',
      '44 King Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/scotiabank/id341351824',
      'https://play.google.com/store/apps/details?id=ca.scotiabank.banking',
      'https://www.scotiabank.com',
      'customer.service@scotiabank.com',
      'https://twitter.com/Scotiabank',
      'https://www.instagram.com/scotiabank/',
      'https://www.linkedin.com/company/scotiabank/',
      '',
      'NOSCCATT',
      '',
    ),
  ],
  HR: [
    bank(
      'Zagrebacka banka',
      '+385 1 3789 000',
      'Trg bana Josipa Jelacica 10, Zagreb, Croatia',
      '',
      '',
      'https://www.zaba.hr',
      'zaba@unicreditgroup.zaba.hr',
      '',
      '',
      '',
      '',
      'ZABAHR2X',
      '',
    ),
    bank(
      'Privredna banka Zagreb',
      '+385 1 6363 636',
      'Radnicka cesta 50, Zagreb, Croatia',
      '',
      '',
      'https://www.pbz.hr',
      'pbz365@pbz.hr',
      '',
      '',
      '',
      '',
      'PBZGHR2X',
      '',
    ),
    bank(
      'Erste & Steiermarkische Bank',
      '+385 72 37 1000',
      'Ivana Lucica 2, Zagreb, Croatia',
      '',
      '',
      'https://www.erstebank.hr',
      'erstebank@erstebank.hr',
      '',
      '',
      '',
      '',
      'ESBCHR22',
      '',
    ),
  ],
  CZ: [
    bank(
      'Ceska sporitelna',
      '+420 800 207 207',
      'Olbrachtova 1929/62, Prague, Czech Republic',
      '',
      '',
      'https://www.csas.cz',
      'info@csas.cz',
      '',
      '',
      '',
      '',
      'GIBACZPX',
      '',
    ),
    bank(
      'CSOB',
      '+420 800 300 300',
      'Radlicka 333/150, Prague, Czech Republic',
      '',
      '',
      'https://www.csob.cz',
      'info@csob.cz',
      '',
      '',
      '',
      '',
      'CEKOCZPP',
      '',
    ),
    bank(
      'Komerci banka',
      '+420 955 551 552',
      'Na Prikope 33, Prague, Czech Republic',
      '',
      '',
      'https://www.kb.cz',
      'info@kb.cz',
      '',
      '',
      '',
      '',
      'KOMBCZPP',
      '',
    ),
  ],
  DK: [
    bank(
      'Danske Bank',
      '+45 70 123 456',
      'Holmens Kanal 2-12, 1092 Copenhagen, Denmark',
      'https://apps.apple.com/dk/app/danske-mobilbank/id429047995',
      'https://play.google.com/store/apps/details?id=com.danskebank.mobilebank3.dk',
      'https://danskebank.dk',
      'info@danskebank.dk',
      'https://twitter.com/DanskeBank',
      'https://www.instagram.com/danskebank/',
      'https://www.linkedin.com/company/danske-bank/',
      '',
      'DABADKKK',
      'https://developers.danskebank.com',
    ),
    bank(
      'Nordea Denmark',
      '+45 70 33 33 33',
      'Grønjordsvej 10, 2300 Copenhagen, Denmark',
      'https://apps.apple.com/dk/app/nordea-mobile/id429047995',
      'https://play.google.com/store/apps/details?id=com.nordea.mobilebank',
      'https://www.nordea.dk',
      'kundeservice@nordea.dk',
      'https://twitter.com/Nordea',
      'https://www.instagram.com/nordea/',
      'https://www.linkedin.com/company/nordea/',
      '',
      'NDEADKKK',
      'https://developer.nordea.com',
    ),
    bank(
      'Jyske Bank',
      '+45 89 89 89 89',
      'Vestergade 8, 8600 Silkeborg, Denmark',
      'https://apps.apple.com/dk/app/jyske-mobilbank/id429047995',
      'https://play.google.com/store/apps/details?id=dk.jyskebank.drb',
      'https://www.jyskebank.dk',
      'info@jyskebank.dk',
      'https://twitter.com/JyskeBank',
      'https://www.instagram.com/jyskebank/',
      'https://www.linkedin.com/company/jyske-bank/',
      '',
      'JYBADKKK',
      '',
    ),
  ],
  EE: [
    bank(
      'Swedbank Estonia',
      '+372 613 1606',
      'Liivalaia 8, Tallinn, Estonia',
      '',
      '',
      'https://www.swedbank.ee',
      'info@swedbank.ee',
      '',
      '',
      '',
      '',
      'HABAEE2X',
      '',
    ),
    bank(
      'SEB Estonia',
      '+372 665 5100',
      'Tornimae 2, Tallinn, Estonia',
      '',
      '',
      'https://www.seb.ee',
      'info@seb.ee',
      '',
      '',
      '',
      '',
      'EEUHEE2X',
      '',
    ),
    bank(
      'LHV Bank',
      '+372 680 0400',
      'Tartu mnt 2, Tallinn, Estonia',
      '',
      '',
      'https://www.lhv.ee',
      'info@lhv.ee',
      '',
      '',
      '',
      '',
      'LHVBEE22',
      '',
    ),
  ],
  FI: [
    bank(
      'Nordea Finland',
      '+358 200 70 000',
      'Satamaradankatu 5, 00020 Nordea, Helsinki, Finland',
      'https://apps.apple.com/fi/app/nordea-mobile/id429047995',
      'https://play.google.com/store/apps/details?id=com.nordea.mobilebank',
      'https://www.nordea.fi',
      'asiakaspalvelu@nordea.fi',
      'https://twitter.com/Nordea',
      'https://www.instagram.com/nordea/',
      'https://www.linkedin.com/company/nordea/',
      '',
      'NDEAFIHH',
      'https://developer.nordea.com',
    ),
    bank(
      'OP Financial Group',
      '+358 10 252 000',
      'Gebhardinaukio 1, 00510 Helsinki, Finland',
      'https://apps.apple.com/fi/app/op-mobiili/id429047995',
      'https://play.google.com/store/apps/details?id=fi.op.android.opmobiili',
      'https://www.op.fi',
      'asiakaspalvelu@op.fi',
      'https://twitter.com/OPFinancialGrp',
      'https://www.instagram.com/opfinancialgroup/',
      'https://www.linkedin.com/company/op-financial-group/',
      '',
      'OKOYFIHH',
      'https://developer.op.fi',
    ),
    bank(
      'Aktia Bank',
      '+358 10 247 000',
      'Arkadiankatu 4-6, 00100 Helsinki, Finland',
      'https://apps.apple.com/fi/app/aktia-mobiili/id429047995',
      'https://play.google.com/store/apps/details?id=fi.aktia.mobilebank',
      'https://www.aktia.fi',
      'asiakaspalvelu@aktia.fi',
      'https://twitter.com/AktiaPankki',
      'https://www.instagram.com/aktiapankki/',
      'https://www.linkedin.com/company/aktia-bank/',
      '',
      'HELSFIHH',
      '',
    ),
  ],
  FR: [
    bank(
      'BNP Paribas',
      '+33 1 42 98 12 34',
      '16 Boulevard des Italiens, 75009 Paris, France',
      'https://apps.apple.com/fr/app/mes-comptes-bnp-paribas/id393156562',
      'https://play.google.com/store/apps/details?id=net.bnpparibas.mescomptes',
      'https://mabanque.bnpparibas',
      'contact@bnpparibas.com',
      'https://twitter.com/bnpparibas',
      'https://www.instagram.com/bnpparibas/',
      'https://www.linkedin.com/company/bnp-paribas/',
      '',
      'BNPAFRPP',
      'https://developers.bnpparibas',
    ),
    bank(
      'Societe Generale',
      '+33 1 42 14 20 00',
      '29 Boulevard Haussmann, 75009 Paris, France',
      'https://apps.apple.com/fr/app/societe-generale/id393156562',
      'https://play.google.com/store/apps/details?id=mobi.societegenerale.mobile.lappli',
      'https://www.societegenerale.fr',
      'contact@societegenerale.com',
      'https://twitter.com/societegenerale',
      'https://www.instagram.com/societegenerale/',
      'https://www.linkedin.com/company/societe-generale/',
      '',
      'SOGEFRPP',
      'https://developer.societegenerale.com',
    ),
    bank(
      'Credit Agricole',
      '+33 1 43 23 52 02',
      '12 Place des Etats-Unis, 92127 Montrouge, France',
      'https://apps.apple.com/fr/app-ma-credit-agricole/id393156562',
      'https://play.google.com/store/apps/details?id=fr.creditagricole.androidapp',
      'https://www.credit-agricole.fr',
      'contact@credit-agricole.com',
      'https://twitter.com/CreditAgricole',
      'https://www.instagram.com/creditagricole/',
      'https://www.linkedin.com/company/credit-agricole/',
      '',
      'AGRIFRPP',
      '',
    ),
  ],
  DE: [
    bank(
      'Deutsche Bank',
      '+49 69 910 10000',
      'Taunusanlage 12, 60325 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/deutsche-bank-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=com.db.pwcc.dbmobile',
      'https://www.deutsche-bank.de',
      'kundenservice@db.com',
      'https://twitter.com/DeutscheBank',
      'https://www.instagram.com/deutschebank/',
      'https://www.linkedin.com/company/deutsche-bank/',
      '',
      'DEUTDEFF',
      'https://developer.db.com',
    ),
    bank(
      'Commerzbank',
      '+49 69 136 20',
      'Kaiserplatz, 60261 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/commerzbank-banking/id393156562',
      'https://play.google.com/store/apps/details?id=de.commerzbanking.mobil',
      'https://www.commerzbank.de',
      'kundenservice@commerzbank.de',
      'https://twitter.com/Commerzbank',
      'https://www.instagram.com/commerzbank/',
      'https://www.linkedin.com/company/commerzbank/',
      '',
      'COBADEFF',
      '',
    ),
    bank(
      'DZ Bank',
      '+49 69 7447 0',
      'Platz der Republik, 60265 Frankfurt am Main, Germany',
      'https://apps.apple.com/de/app/dz-bank/id393156562',
      '',
      'https://www.dzbank.de',
      'info@dzbank.de',
      'https://twitter.com/DZ_BANK',
      'https://www.instagram.com/dzbank/',
      'https://www.linkedin.com/company/dz-bank/',
      '',
      'GENODEFF',
      '',
    ),
  ],
  GR: [
    bank(
      'National Bank of Greece',
      '+30 210 334 1000',
      '86 Aiolou Street, Athens, Greece',
      '',
      '',
      'https://www.nbg.gr',
      'info@nbg.gr',
      '',
      '',
      '',
      '',
      'ETHNGRAA',
      '',
    ),
    bank(
      'Piraeus Bank',
      '+30 210 328 8000',
      '4 Amerikis St, Athens, Greece',
      '',
      '',
      'https://www.piraeusbank.gr',
      'customerservice@piraeusbank.gr',
      '',
      '',
      '',
      '',
      'PIRBGRAA',
      '',
    ),
    bank(
      'Eurobank Greece',
      '+30 210 955 5000',
      '8 Othonos St, Athens, Greece',
      '',
      '',
      'https://www.eurobank.gr',
      'info@eurobank.gr',
      '',
      '',
      '',
      '',
      'ERBKGRAA',
      '',
    ),
  ],
  HU: [
    bank(
      'OTP Bank',
      '+36 1 366 6666',
      'Nador utca 16, Budapest, Hungary',
      '',
      '',
      'https://www.otpbank.hu',
      'info@otpbank.hu',
      '',
      '',
      '',
      '',
      'OTPVHUHB',
      '',
    ),
    bank(
      'K&H Bank',
      '+36 1 328 9000',
      'Lechner Odon fasor 9, Budapest, Hungary',
      '',
      '',
      'https://www.kh.hu',
      'bank@kh.hu',
      '',
      '',
      '',
      '',
      'OKHBHUHB',
      '',
    ),
    bank(
      'Erste Bank Hungary',
      '+36 1 298 0222',
      'Nefelejcs utca 24, Budapest, Hungary',
      '',
      '',
      'https://www.erstebank.hu',
      'erste@erstebank.hu',
      '',
      '',
      '',
      '',
      'GIBAHUHB',
      '',
    ),
  ],
  IS: [
    bank(
      'Landsbankinn',
      '+354 410 4000',
      'Austurstraeti 11, 155 Reykjavik, Iceland',
      'https://apps.apple.com/is/app/landsbankinn/id393156562',
      'https://play.google.com/store/apps/details?id=is.landsbankinn.mobile',
      'https://www.landsbankinn.is',
      'info@landsbankinn.is',
      'https://twitter.com/landsbankinn',
      'https://www.instagram.com/landsbankinn/',
      'https://www.linkedin.com/company/landsbankinn/',
      '',
      'NBIIISRE',
      '',
    ),
    bank(
      'Arion Bank',
      '+354 444 1000',
      'Borgartun 19, 105 Reykjavik, Iceland',
      'https://apps.apple.com/is/app/arion-banki/id393156562',
      'https://play.google.com/store/apps/details?id=is.arion.app',
      'https://www.arionbanki.is',
      'info@arionbanki.is',
      'https://twitter.com/arionbanki',
      'https://www.instagram.com/arionbanki/',
      'https://www.linkedin.com/company/arion-bank/',
      '',
      'ESJAISRE',
      '',
    ),
    bank(
      'Islandsbanki',
      '+354 440 4000',
      'Hagatorg, 107 Reykjavik, Iceland',
      'https://apps.apple.com/is/app/islandsbanki/id393156562',
      'https://play.google.com/store/apps/details?id=is.islandsbanki.app',
      'https://www.islandsbanki.is',
      'info@islandsbanki.is',
      'https://twitter.com/islandsbanki',
      'https://www.instagram.com/islandsbanki/',
      'https://www.linkedin.com/company/islandsbanki/',
      '',
      'GLITISRE',
      '',
    ),
  ],
  IT: [
    bank(
      'Intesa Sanpaolo',
      '+39 800 303 303',
      'Piazza San Carlo 156, Turin, Italy',
      '',
      '',
      'https://www.intesasanpaolo.com',
      'assistenza@intesasanpaolo.com',
      '',
      '',
      '',
      '',
      'BCITITMM',
      '',
    ),
    bank(
      'UniCredit',
      '+39 800 57 57 57',
      'Piazza Gae Aulenti 3, Milan, Italy',
      '',
      '',
      'https://www.unicredit.it',
      'info@unicredit.eu',
      '',
      '',
      '',
      '',
      'UNCRITMM',
      '',
    ),
    bank(
      'Banco BPM',
      '+39 800 024 024',
      'Piazza Meda 4, Milan, Italy',
      '',
      '',
      'https://www.bancobpm.it',
      'contattaci@bancobpm.it',
      '',
      '',
      '',
      '',
      'BAPPIT22',
      '',
    ),
  ],
  LV: [
    bank(
      'Swedbank Latvia',
      '+371 6744 4444',
      'Balasta dambis 15, Riga, Latvia',
      '',
      '',
      'https://www.swedbank.lv',
      'info@swedbank.lv',
      '',
      '',
      '',
      '',
      'HABALV22',
      '',
    ),
    bank(
      'SEB Latvia',
      '+371 2666 8777',
      'Meistaru iela 1, Valdlauci, Latvia',
      '',
      '',
      'https://www.seb.lv',
      'seb@seb.lv',
      '',
      '',
      '',
      '',
      'UNLALV2X',
      '',
    ),
    bank(
      'Citadele Banka',
      '+371 6701 0000',
      'Republikas laukums 2A, Riga, Latvia',
      '',
      '',
      'https://www.citadele.lv',
      'info@citadele.lv',
      '',
      '',
      '',
      '',
      'PARXLV22',
      '',
    ),
  ],
  LT: [
    bank(
      'Swedbank Lithuania',
      '+370 5 268 4444',
      'Konstitucijos pr. 20A, Vilnius, Lithuania',
      '',
      '',
      'https://www.swedbank.lt',
      'info@swedbank.lt',
      '',
      '',
      '',
      '',
      'HABALT22',
      '',
    ),
    bank(
      'SEB Lithuania',
      '+370 5 268 2800',
      'Konstitucijos pr. 24, Vilnius, Lithuania',
      '',
      '',
      'https://www.seb.lt',
      'info@seb.lt',
      '',
      '',
      '',
      '',
      'CBVILT2X',
      '',
    ),
    bank(
      'Siauliu Bankas',
      '+370 5 203 2233',
      'Tilzes g. 149, Siauliai, Lithuania',
      '',
      '',
      'https://www.sb.lt',
      'info@sb.lt',
      '',
      '',
      '',
      '',
      'CBSBLT26',
      '',
    ),
  ],
  LU: [
    bank(
      'Spuerkeess',
      '+352 4015 1',
      '1 Place de Metz, Luxembourg City, Luxembourg',
      '',
      '',
      'https://www.spuerkeess.lu',
      'spuerkeess@spuerkeess.lu',
      '',
      '',
      '',
      '',
      'BCEELULL',
      '',
    ),
    bank(
      'BGL BNP Paribas',
      '+352 4242 2000',
      '50 Avenue J F Kennedy, Luxembourg City, Luxembourg',
      '',
      '',
      'https://www.bgl.lu',
      'contact@bgl.lu',
      '',
      '',
      '',
      '',
      'BGLLLULL',
      '',
    ),
    bank(
      'Banque Internationale a Luxembourg',
      '+352 4590 1',
      '69 Route d\'Esch, Luxembourg City, Luxembourg',
      '',
      '',
      'https://www.bil.com',
      'info@bil.com',
      '',
      '',
      '',
      '',
      'BILLLULL',
      '',
    ),
  ],
  ME: [
    bank(
      'Crnogorska Komercijalna Banka',
      '+382 20 401 100',
      'Moskovska 3, Podgorica, Montenegro',
      '',
      '',
      'https://www.ckb.me',
      'info@ckb.me',
      '',
      '',
      '',
      '',
      'CKBCMEPG',
      '',
    ),
    bank(
      'NLB Banka Podgorica',
      '+382 20 404 000',
      'Bulevar Stanka Dragojevica 46, Podgorica, Montenegro',
      '',
      '',
      'https://www.nlb.me',
      'info@nlb.me',
      '',
      '',
      '',
      '',
      'MNBAMEPG',
      '',
    ),
    bank(
      'Erste Bank AD Podgorica',
      '+382 20 440 000',
      'Studentska bb, Podgorica, Montenegro',
      '',
      '',
      'https://www.erstebank.me',
      'info@erstebank.me',
      '',
      '',
      '',
      '',
      'OPPOMEPG',
      '',
    ),
  ],
  NL: [
    bank(
      'ING Bank Netherlands',
      '+31 20 563 9111',
      'Bijlmerdreef 106, 1102 CT Amsterdam, Netherlands',
      'https://apps.apple.com/nl/app/ing-bankieren/id474807486',
      'https://play.google.com/store/apps/details?id=com.ing.mobile',
      'https://www.ing.nl',
      'klantenservice@ing.nl',
      'https://twitter.com/INGnl',
      'https://www.instagram.com/ingnl/',
      'https://www.linkedin.com/company/ing/',
      '',
      'INGBNL2A',
      'https://developer.ing.com',
    ),
    bank(
      'Rabobank',
      '+31 30 216 0000',
      'Croeselaan 18, 3521 CB Utrecht, Netherlands',
      'https://apps.apple.com/nl/app/rabobank-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=nl.rabobank.rabomobile',
      'https://www.rabobank.nl',
      'info@rabobank.nl',
      'https://twitter.com/Rabobank',
      'https://www.instagram.com/rabobank/',
      'https://www.linkedin.com/company/rabobank/',
      '',
      'RABONL2U',
      'https://developer.rabobank.nl',
    ),
    bank(
      'ABN AMRO',
      '+31 20 628 9900',
      'Gustav Mahlerlaan 10, 1082 PP Amsterdam, Netherlands',
      'https://apps.apple.com/nl/app/abn-amro-mobile-banking/id393156562',
      'https://play.google.com/store/apps/details?id=com.abnamro.nl.mobile.payments',
      'https://www.abnamro.nl',
      'klantenservice@abnamro.nl',
      'https://twitter.com/abnamro',
      'https://www.instagram.com/abnamro/',
      'https://www.linkedin.com/company/abn-amro/',
      '',
      'ABNANL2A',
      'https://developer.abnamro.com',
    ),
  ],
  MK: [
    bank(
      'Komercijalna Banka AD Skopje',
      '+389 2 3168 168',
      'Orce Nikolov 3, Skopje, North Macedonia',
      '',
      '',
      'https://www.kb.mk',
      'contact@kb.mk',
      '',
      '',
      '',
      '',
      'KOBSMK2X',
      '',
    ),
    bank(
      'Stopanska Banka AD Skopje',
      '+389 2 3295 000',
      '11 Oktomvri 7, Skopje, North Macedonia',
      '',
      '',
      'https://www.stb.com.mk',
      'kontakt@stb.com.mk',
      '',
      '',
      '',
      '',
      'STOBMK2X',
      '',
    ),
    bank(
      'NLB Banka Skopje',
      '+389 2 15600',
      'Majka Tereza 1, Skopje, North Macedonia',
      '',
      '',
      'https://nlb.mk',
      'kontakt@nlb.mk',
      '',
      '',
      '',
      '',
      'TUTNMK22',
      '',
    ),
  ],
  NO: [
    bank(
      'DNB Bank',
      '+47 915 04800',
      'Dronning Eufemias gate 30, 0191 Oslo, Norway',
      'https://apps.apple.com/no/app/dnb-mobilbank/id393156562',
      'https://play.google.com/store/apps/details?id=no.dnb.mobilbank',
      'https://www.dnb.no',
      'postmottak@dnb.no',
      'https://twitter.com/DNB_Bank',
      'https://www.instagram.com/dnb_no/',
      'https://www.linkedin.com/company/dnb/',
      '',
      'DNBANOKK',
      'https://developer.dnb.no',
    ),
    bank(
      'Nordea Norway',
      '+47 915 03030',
      'Essendrops gate 7, 0368 Oslo, Norway',
      'https://apps.apple.com/no/app/nordea-mobile/id393156562',
      'https://play.google.com/store/apps/details?id=com.nordea.mobilebank',
      'https://www.nordea.no',
      'kundeservice@nordea.no',
      'https://twitter.com/Nordea',
      'https://www.instagram.com/nordea/',
      'https://www.linkedin.com/company/nordea/',
      '',
      'NDEANOKK',
      'https://developer.nordea.com',
    ),
    bank(
      'SpareBank 1 SR-Bank',
      '+47 915 03000',
      'Stavanger, Norway',
      'https://apps.apple.com/no/app/sparebank-1/id393156562',
      'https://play.google.com/store/apps/details?id=no.sparebank1.mobilbank',
      'https://www.sparebank1.no',
      'post@srbank.no',
      'https://twitter.com/SpareBank1',
      'https://www.instagram.com/sparebank1/',
      'https://www.linkedin.com/company/sparebank-1/',
      '',
      'SPRONO22',
      '',
    ),
  ],
  PL: [
    bank(
      'PKO Bank Polski',
      '+48 22 521 1900',
      'ul. Pulawska 15, Warsaw, Poland',
      '',
      '',
      'https://www.pkobp.pl',
      'kontakt@pkobp.pl',
      '',
      '',
      '',
      '',
      'BPKOPLPW',
      '',
    ),
    bank(
      'Bank Pekao',
      '+48 22 591 2323',
      'ul. Zurawia 32/34, Warsaw, Poland',
      '',
      '',
      'https://www.pekao.com.pl',
      'info@pekao.com.pl',
      '',
      '',
      '',
      '',
      'PKOPPLPW',
      '',
    ),
    bank(
      'Santander Bank Polska',
      '+48 61 81 1 9999',
      'Aleja Jana Pawla II 17, Warsaw, Poland',
      '',
      '',
      'https://www.santander.pl',
      'kontakt@santander.pl',
      '',
      '',
      '',
      '',
      'WBKPPLPP',
      '',
    ),
  ],
  PT: [
    bank(
      'Caixa Geral de Depositos',
      '+351 217 900 790',
      'Av. Joao XXI 63, Lisbon, Portugal',
      '',
      '',
      'https://www.cgd.pt',
      'caixadirecta@cgd.pt',
      '',
      '',
      '',
      '',
      'CGDIPTPL',
      '',
    ),
    bank(
      'Millennium bcp',
      '+351 210 040 424',
      'Praca D. Joao I 28, Porto, Portugal',
      '',
      '',
      'https://ind.millenniumbcp.pt',
      'indicador@millenniumbcp.pt',
      '',
      '',
      '',
      '',
      'BCOMPTPL',
      '',
    ),
    bank(
      'Novo Banco',
      '+351 213 501 000',
      'Av. da Liberdade 195, Lisbon, Portugal',
      '',
      '',
      'https://www.novobanco.pt',
      'cliente@novobanco.pt',
      '',
      '',
      '',
      '',
      'BESCPTPL',
      '',
    ),
  ],
  RO: [
    bank(
      'Banca Transilvania',
      '+40 264 308 028',
      'Calea Dorobantilor 30-36, Cluj-Napoca, Romania',
      '',
      '',
      'https://www.bancatransilvania.ro',
      'contact@btrl.ro',
      '',
      '',
      '',
      '',
      'BTRLRO22',
      '',
    ),
    bank(
      'Banca Comerciala Romana',
      '+40 21 407 4200',
      'Bd. Regina Elisabeta 5, Bucharest, Romania',
      '',
      '',
      'https://www.bcr.ro',
      'contact.center@bcr.ro',
      '',
      '',
      '',
      '',
      'RNCBROBU',
      '',
    ),
    bank(
      'BRD Groupe Societe Generale',
      '+40 21 302 6161',
      'Bd. Ion Mihalache 1-7, Bucharest, Romania',
      '',
      '',
      'https://www.brd.ro',
      'mybrdcontact@brd.ro',
      '',
      '',
      '',
      '',
      'BRDEROBU',
      '',
    ),
  ],
  SK: [
    bank(
      'Slovenska sporitelna',
      '+421 2 4862 1111',
      'Tomasikova 48, Bratislava, Slovakia',
      '',
      '',
      'https://www.slsp.sk',
      'info@slsp.sk',
      '',
      '',
      '',
      '',
      'GIBASKBX',
      '',
    ),
    bank(
      'VUB Banka',
      '+421 2 4855 5970',
      'Mlynske nivy 1, Bratislava, Slovakia',
      '',
      '',
      'https://www.vub.sk',
      'kontakt@vub.sk',
      '',
      '',
      '',
      '',
      'SUBASKBX',
      '',
    ),
    bank(
      'Tatra banka',
      '+421 2 5919 1000',
      'Hodzovo namestie 3, Bratislava, Slovakia',
      '',
      '',
      'https://www.tatrabanka.sk',
      'kontakt@tatrabanka.sk',
      '',
      '',
      '',
      '',
      'TATRSKBX',
      '',
    ),
  ],
  SI: [
    bank(
      'NLB d.d.',
      '+386 1 477 2000',
      'Trg republike 2, Ljubljana, Slovenia',
      '',
      '',
      'https://www.nlb.si',
      'info@nlb.si',
      '',
      '',
      '',
      '',
      'LJBASI2X',
      '',
    ),
    bank(
      'NKBM',
      '+386 2 229 2290',
      'Ulica Vita Kraigherja 4, Maribor, Slovenia',
      '',
      '',
      'https://www.nkbm.si',
      'info@nkbm.si',
      '',
      '',
      '',
      '',
      'KBMASI2X',
      '',
    ),
    bank(
      'SKB Banka',
      '+386 1 471 5555',
      'Ajdovscina 4, Ljubljana, Slovenia',
      '',
      '',
      'https://www.skb.si',
      'kontakt@skb.si',
      '',
      '',
      '',
      '',
      'SKBASI2X',
      '',
    ),
  ],
  ES: [
    bank(
      'Banco Santander',
      '+34 91 276 0000',
      'Paseo de Pereda 9-12, 39004 Santander, Spain',
      'https://apps.apple.com/es/app/santander/id393156562',
      'https://play.google.com/store/apps/details?id=es.bancosantander.apps',
      'https://www.bancosantander.es',
      'atencioncliente@santander.com',
      'https://twitter.com/bancosantander',
      'https://www.instagram.com/bancosantander/',
      'https://www.linkedin.com/company/banco-santander/',
      '',
      'BSCHESMM',
      'https://developer.santander.com',
    ),
    bank(
      'BBVA',
      '+34 91 537 6000',
      'Plaza de San Nicolas 4, 48005 Bilbao, Spain',
      'https://apps.apple.com/es/app/bbva-espana/id393156562',
      'https://play.google.com/store/apps/details?id=com.bbva.bbvacontigo',
      'https://www.bbva.es',
      'atencion.cliente@bbva.com',
      'https://twitter.com/bbva',
      'https://www.instagram.com/bbva/',
      'https://www.linkedin.com/company/bbva/',
      '',
      'BBVAESMM',
      'https://developers.bbva.com',
    ),
    bank(
      'CaixaBank',
      '+34 93 404 6000',
      'Avenida Diagonal 621-639, 08028 Barcelona, Spain',
      'https://apps.apple.com/es/app/caixabank/id393156562',
      'https://play.google.com/store/apps/details?id=es.lacaixa.mobile.android.newwapicon',
      'https://www.caixabank.es',
      'info@caixabank.com',
      'https://twitter.com/CaixaBank',
      'https://www.instagram.com/caixabank/',
      'https://www.linkedin.com/company/caixabank/',
      '',
      'CAIXESBB',
      '',
    ),
  ],
  SE: [
    bank(
      'Swedbank',
      '+46 771 22 11 22',
      'Landsvägen 40, 172 63 Sundbyberg, Sweden',
      'https://apps.apple.com/se/app/swedbank/id393156562',
      'https://play.google.com/store/apps/details?id=se.swedbank.mobil',
      'https://www.swedbank.se',
      'kundcenter@swedbank.se',
      'https://twitter.com/Swedbank',
      'https://www.instagram.com/swedbank/',
      'https://www.linkedin.com/company/swedbank/',
      '',
      'SWEDSESS',
      'https://developer.swedbank.com',
    ),
    bank(
      'SEB',
      '+46 771 365 365',
      '106 40 Stockholm, Sweden',
      'https://apps.apple.com/se/app/seb/id393156562',
      'https://play.google.com/store/apps/details?id=se.seb.privatkonto',
      'https://www.seb.se',
      'kundservice@seb.se',
      'https://twitter.com/SEB',
      'https://www.instagram.com/seb/',
      'https://www.linkedin.com/company/seb/',
      '',
      'ESSESESS',
      'https://developer.sebgroup.com',
    ),
    bank(
      'Handelsbanken',
      '+46 8 701 10 00',
      'Kungstradgardsgatan 2, 106 70 Stockholm, Sweden',
      'https://apps.apple.com/se/app/handelsbanken/id393156562',
      'https://play.google.com/store/apps/details?id=se.handelsbanken.mobilebank',
      'https://www.handelsbanken.se',
      'kundservice@handelsbanken.se',
      'https://twitter.com/Handelsbanken',
      'https://www.instagram.com/handelsbanken/',
      'https://www.linkedin.com/company/handelsbanken/',
      '',
      'HANDSESS',
      '',
    ),
  ],
  TR: [
    bank(
      'Turkiye Is Bankasi',
      '+90 212 316 0000',
      'Is Kuleleri, Levent, Istanbul, Turkiye',
      '',
      '',
      'https://www.isbank.com.tr',
      'musteriiliskileri@isbank.com.tr',
      '',
      '',
      '',
      '',
      'ISBKTRIS',
      '',
    ),
    bank(
      'Ziraat Bankasi',
      '+90 312 584 2000',
      'Doganbey Mah. Ataturk Bulvari, Ankara, Turkiye',
      '',
      '',
      'https://www.ziraatbank.com.tr',
      'iletisim@ziraatbank.com.tr',
      '',
      '',
      '',
      '',
      'TCZBTR2A',
      '',
    ),
    bank(
      'Garanti BBVA',
      '+90 212 318 1818',
      'Levent Nispetiye Mah., Istanbul, Turkiye',
      '',
      '',
      'https://www.garantibbva.com.tr',
      'iletisim@garantibbva.com.tr',
      '',
      '',
      '',
      '',
      'TGBATRIS',
      '',
    ),
  ],
  GB: [
    bank(
      'HSBC UK Bank',
      '+44 345 740 4404',
      '8 Canada Square, London, United Kingdom',
      '',
      '',
      'https://www.hsbc.co.uk',
      'ukcustomer.services@hsbc.com',
      '',
      '',
      '',
      '',
      'HBUKGB4B',
      '',
    ),
    bank(
      'Barclays Bank UK',
      '+44 20 7116 1000',
      '1 Churchill Place, London, United Kingdom',
      '',
      '',
      'https://www.barclays.co.uk',
      'customer.services@barclays.co.uk',
      '',
      '',
      '',
      '',
      'BARCGB22',
      '',
    ),
    bank(
      'Lloyds Bank',
      '+44 20 7626 1500',
      '25 Gresham Street, London, United Kingdom',
      '',
      '',
      'https://www.lloydsbank.com',
      'onlinecomplaints@lloydsbank.co.uk',
      '',
      '',
      '',
      '',
      'LOYDGB2L',
      '',
    ),
  ],
  US: [
    bank(
      'JPMorgan Chase Bank',
      '+1 212 270 6000',
      '270 Park Avenue, New York, NY, United States',
      'https://apps.apple.com/us/app/chase-mobile/id298867247',
      'https://play.google.com/store/apps/details?id=com.chase.sig.android',
      'https://www.chase.com',
      'support@chase.com',
      'https://twitter.com/Chase',
      'https://www.instagram.com/chase/',
      'https://www.linkedin.com/company/jpmorganchase/',
      '021000021',
      'CHASUS33',
      'https://api.chase.com',
    ),
    bank(
      'Bank of America',
      '+1 704 386 5681',
      '100 North Tryon Street, Charlotte, NC, United States',
      'https://apps.apple.com/us/app/bank-of-america-mobile-banking/id284847138',
      'https://play.google.com/store/apps/details?id=com.infonow.bofa',
      'https://www.bankofamerica.com',
      'abuse@bankofamerica.com',
      'https://twitter.com/BankofAmerica',
      'https://www.instagram.com/bankofamerica/',
      'https://www.linkedin.com/company/bank-of-america/',
      '026009593',
      'BOFAUS3N',
      '',
    ),
    bank(
      'Wells Fargo Bank',
      '+1 415 396 1300',
      '420 Montgomery Street, San Francisco, CA, United States',
      'https://apps.apple.com/us/app/wells-fargo-mobile/id311548709',
      'https://play.google.com/store/apps/details?id=com.wf.wellsfargomobile',
      'https://www.wellsfargo.com',
      'customer.service@wellsfargo.com',
      'https://twitter.com/WellsFargo',
      'https://www.instagram.com/wellsfargo/',
      'https://www.linkedin.com/company/wellsfargo/',
      '121000248',
      'WFBIUS6S',
      '',
    ),
  ],
}
