import type { NatoMemberIsoCode } from './natoMemberIsoCodes'
import type { SecuritiesExchangeCommission } from './types'

function sec(
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): SecuritiesExchangeCommission {
  return { name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

/**
 * Securities and exchange / capital-markets commission by ISO 3166-1 alpha-2 for NATO
 * Allies in this module (informational; verify URLs, handles, forms portals, and API bases
 * before production use). Self-contained — no imports from other alliance modules.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.iosco.org/about/membership/
 */
export const NATO_SECURITIES_EXCHANGE_COMMISSIONS: Record<
  NatoMemberIsoCode,
  SecuritiesExchangeCommission
> = {
  AL: sec(
    'Albanian Financial Supervisory Authority (AFSA)',
    'https://www.afsa.gov.al',
    'afsa@afsa.gov.al',
    '',
    'https://www.linkedin.com/company/albanian-financial-supervisory-authority/',
    'https://www.afsa.gov.al',
  ),
  BE: sec(
    'Financial Services and Markets Authority Belgium (FSMA)',
    'https://www.fsma.be',
    'info@fsma.be',
    'https://x.com/FSMAbelgique',
    'https://www.linkedin.com/company/fsma/',
    'https://www.fsma.be',
  ),
  BG: sec(
    'Financial Supervision Commission Bulgaria (FSC Bulgaria)',
    'https://www.fsc.bg',
    'fsc@fsc.bg',
    '',
    'https://www.linkedin.com/company/financial-supervision-commission-bulgaria/',
    'https://www.fsc.bg',
  ),
  CA: sec(
    'Canadian Securities Administrators (CSA)',
    'https://www.securities-administrators.ca',
    'info@csa-acvm.ca',
    'https://x.com/CSA_News',
    'https://www.linkedin.com/company/canadian-securities-administrators/',
    'https://www.securities-administrators.ca',
  ),
  HR: sec(
    'Croatian Financial Services Supervisory Agency (HANFA)',
    'https://www.hanfa.hr',
    'hanfa@hanfa.hr',
    '',
    'https://www.linkedin.com/company/hanfa/',
    'https://www.hanfa.hr',
  ),
  CZ: sec(
    'Czech National Bank (CNB) — capital-markets supervision',
    'https://www.cnb.cz',
    'info@cnb.cz',
    '',
    'https://www.linkedin.com/company/czech-national-bank/',
    'https://www.cnb.cz',
  ),
  DK: sec(
    'Danish Financial Supervisory Authority (Finanstilsynet)',
    'https://www.finanstilsynet.dk',
    'finanstilsynet@finanstilsynet.dk',
    'https://x.com/Finanstilsynet',
    'https://www.linkedin.com/company/finanstilsynet/',
    'https://www.finanstilsynet.dk',
  ),
  EE: sec(
    'Estonian Financial Supervision and Resolution Authority (Finantsinspektsioon)',
    'https://www.fi.ee',
    'info@fi.ee',
    '',
    'https://www.linkedin.com/company/finantsinspektsioon/',
    'https://www.fi.ee',
  ),
  FI: sec(
    'Finnish Financial Supervisory Authority (Finanssivalvonta / FIN-FSA)',
    'https://www.finanssivalvonta.fi',
    'kirjaamo@finanssivalvonta.fi',
    'https://x.com/Finanssivalvonta',
    'https://www.linkedin.com/company/finanssivalvonta/',
    'https://www.finanssivalvonta.fi',
  ),
  FR: sec(
    'Autorité des marchés financiers (AMF France)',
    'https://www.amf-france.org',
    'relationsemet@amf-france.org',
    'https://x.com/AMF_actu',
    'https://www.linkedin.com/company/autorité-des-marchés-financiers-amf/',
    'https://www.amf-france.org',
  ),
  DE: sec(
    'Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin)',
    'https://www.bafin.de',
    'poststelle@bafin.de',
    'https://x.com/BaFin_de',
    'https://www.linkedin.com/company/bafin/',
    'https://www.bafin.de',
  ),
  GR: sec(
    'Hellenic Capital Market Commission (HCMC)',
    'https://www.hcmc.gr',
    'info@hcmc.gr',
    '',
    'https://www.linkedin.com/company/hellenic-capital-market-commission/',
    'https://www.hcmc.gr',
  ),
  HU: sec(
    'Magyar Nemzeti Bank (MNB) — financial markets supervision',
    'https://www.mnb.hu',
    'info@mnb.hu',
    'https://x.com/mnbhu',
    'https://www.linkedin.com/company/mnb-magyar-nemzeti-bank/',
    'https://www.mnb.hu',
  ),
  IS: sec(
    'Financial Supervisory Authority Iceland (Fjármálaeftirlitið / FME)',
    'https://www.fme.is',
    'fme@fme.is',
    '',
    'https://www.linkedin.com/company/fjármálaeftirlitið/',
    'https://www.fme.is',
  ),
  IT: sec(
    'Commissione Nazionale per le Società e la Borsa (CONSOB)',
    'https://www.consob.it',
    'consob@consob.it',
    'https://x.com/consob_it',
    'https://www.linkedin.com/company/consob/',
    'https://www.consob.it',
  ),
  LV: sec(
    'Financial and Capital Market Commission Latvia (FKTK)',
    'https://www.fktk.lv',
    'fktk@fktk.lv',
    '',
    'https://www.linkedin.com/company/financial-and-capital-market-commission-fktk/',
    'https://www.fktk.lv',
  ),
  LT: sec(
    'Bank of Lithuania — capital-markets supervision',
    'https://www.lb.lt',
    'info@lb.lt',
    'https://x.com/BankofLithuania',
    'https://www.linkedin.com/company/bank-of-lithuania/',
    'https://www.lb.lt',
  ),
  LU: sec(
    'Commission de Surveillance du Secteur Financier (CSSF Luxembourg)',
    'https://www.cssf.lu',
    'info@cssf.lu',
    'https://x.com/CSSF_Luxembourg',
    'https://www.linkedin.com/company/cssf/',
    'https://www.cssf.lu',
  ),
  ME: sec(
    'Capital Market Commission Montenegro (Komisija za tržište kapitala)',
    'https://www.sec.me',
    'komisija@sec.me',
    '',
    '',
    'https://www.sec.me',
  ),
  NL: sec(
    'Autoriteit Financiële Markten (AFM Netherlands)',
    'https://www.afm.nl',
    'info@afm.nl',
    'https://x.com/AFM_NL',
    'https://www.linkedin.com/company/autoriteit-financiële-markten/',
    'https://www.afm.nl',
  ),
  MK: sec(
    'Securities and Exchange Commission North Macedonia (Komisija za hartii od vrednost)',
    'https://www.sec.mk',
    'sec@sec.mk',
    '',
    '',
    'https://www.sec.mk',
  ),
  NO: sec(
    'Financial Supervisory Authority of Norway (Finanstilsynet)',
    'https://www.finanstilsynet.no',
    'post@finanstilsynet.no',
    'https://x.com/Finanstilsynet',
    'https://www.linkedin.com/company/finanstilsynet/',
    'https://www.finanstilsynet.no',
  ),
  PL: sec(
    'Polish Financial Supervision Authority (KNF)',
    'https://www.knf.gov.pl',
    'knf@knf.gov.pl',
    'https://x.com/KNFpl',
    'https://www.linkedin.com/company/urząd-komisji-nadzoru-finansowego/',
    'https://www.knf.gov.pl',
  ),
  PT: sec(
    'Comissão do Mercado de Valores Mobiliários (CMVM Portugal)',
    'https://www.cmvm.pt',
    'cmvm@cmvm.pt',
    'https://x.com/CMVM_pt',
    'https://www.linkedin.com/company/cmvm/',
    'https://www.cmvm.pt',
  ),
  RO: sec(
    'Financial Supervisory Authority Romania (ASF)',
    'https://www.asfromania.ro',
    'office@asfromania.ro',
    'https://x.com/ASF_Romania',
    'https://www.linkedin.com/company/asf-romania/',
    'https://www.asfromania.ro',
  ),
  SK: sec(
    'National Bank of Slovakia (NBS) — capital-markets supervision',
    'https://www.nbs.sk',
    'info@nbs.sk',
    '',
    'https://www.linkedin.com/company/national-bank-of-slovakia/',
    'https://www.nbs.sk',
  ),
  SI: sec(
    'Securities Market Agency Slovenia (ATVP)',
    'https://www.atvp.si',
    'atvp@atvp.si',
    '',
    '',
    'https://www.atvp.si',
  ),
  ES: sec(
    'Comisión Nacional del Mercado de Valores (CNMV Spain)',
    'https://www.cnmv.es',
    'cnmv@cnmv.es',
    'https://x.com/cnmv_es',
    'https://www.linkedin.com/company/cnmv/',
    'https://www.cnmv.es',
  ),
  SE: sec(
    'Finansinspektionen (FI Sweden)',
    'https://www.fi.se',
    'finansinspektionen@fi.se',
    'https://x.com/FI_nyheter',
    'https://www.linkedin.com/company/finansinspektionen/',
    'https://www.fi.se',
  ),
  TR: sec(
    'Capital Markets Board of Turkey (SPK)',
    'https://www.spk.gov.tr',
    'spk@spk.gov.tr',
    'https://x.com/SPK_Kurumu',
    'https://www.linkedin.com/company/sermaye-piyasası-kurulu/',
    'https://www.spk.gov.tr',
  ),
  GB: sec(
    'Financial Conduct Authority (FCA United Kingdom)',
    'https://www.fca.org.uk',
    'consumer.queries@fca.org.uk',
    'https://x.com/TheFCA',
    'https://www.linkedin.com/company/financial-conduct-authority/',
    'https://www.fca.org.uk',
  ),
  US: sec(
    'U.S. Securities and Exchange Commission (SEC)',
    'https://www.sec.gov',
    'help@sec.gov',
    'https://x.com/SECGov',
    'https://www.linkedin.com/company/us-securities-and-exchange-commission/',
    'https://www.sec.gov/forms',
  ),
}
