import type { CorporationFormationOffice } from './types'
import type { ArabLeagueMemberIsoCode } from './arabLeagueMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per Arab League member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const ARAB_LEAGUE_CORPORATION_FORMATION_OFFICES: Record<ArabLeagueMemberIsoCode, CorporationFormationOffice> = {
  DZ:   office(
    'Centre National du Registre du Commerce (CNRC)',
    '+213 23 50 34 34',
    'Route nationale no 24, Lido, Mohammadia, Algiers, Algeria',
    'https://sidjilcom.cnrc.dz',
    'contact@cnrc.dz',
    '',
    '',
    'https://www.linkedin.com/company/cnrc-algerie/',
    'https://sidjilcom.cnrc.dz/inscription',
    'https://sidjilcom.cnrc.dz/faq',
    'Numero du Registre du Commerce (NRC)',
  ),
  BH:   office(
    'Sijilat (Ministry of Industry and Commerce Bahrain)',
    '+973 1757 7777',
    'Bahrain Financial Harbour, Manama, Bahrain',
    'https://www.sijilat.bh',
    'info@moic.gov.bh',
    '',
    '',
    '',
    'https://www.sijilat.bh',
    'https://www.bahrain.bh/wps/portal/en/BNP/HomeNationalPortal/ContentDetailsPage/!ut/p/z1',
    'Commercial Registration (CR) Number',
  ),
  KM:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Comores)',
    '+269 773 08 08',
    'Avenue de l\'OUA, Moroni, Comoros',
    'https://www.anpi-comores.km',
    'contact@anpi-comores.km',
    '',
    '',
    '',
    'https://www.anpi-comores.km/guichet-unique',
    'https://www.anpi-comores.km/guide-createur',
    'Numero RCCM',
  ),
  DJ:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Djibouti)',
    '+253 21 35 20 00',
    'Plateau du Serpent, BP 2194, Djibouti City, Djibouti',
    'https://www.investindjibouti.dj',
    'contact@investindjibouti.dj',
    '',
    '',
    '',
    'https://www.investindjibouti.dj/creation-dentreprise',
    'https://www.investindjibouti.dj/guide-creation',
    'Numero RCCM',
  ),
  EG:   office(
    'General Authority for Investment and Free Zones (GAFI) - One Stop Shop',
    '+20 2 3537 3333',
    'Salah Salem Road, Nasr City, Cairo, Egypt',
    'https://www.gafi.gov.eg',
    'info@gafi.gov.eg',
    'https://x.com/gafieg',
    '',
    'https://www.linkedin.com/company/gafi-egypt/',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/default.aspx',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/Procedures.aspx',
    'Commercial Register Number (CR Number)',
  ),
  IQ:   office(
    'Companies Registration Directorate (Ministry of Trade)',
    '+964 790 019 0274',
    'Bab Al-Muadham, Baghdad, Iraq',
    'https://mot.gov.iq',
    '',
    '',
    '',
    '',
    'https://mot.gov.iq',
    'https://mot.gov.iq/ar/services',
    'Company Registration Number',
  ),
  JO:   office(
    'Companies Control Department (Ministry of Industry, Trade and Supply)',
    '+962 6 5629030',
    'Amman, Jordan',
    'https://www.ccd.gov.jo',
    '',
    '',
    '',
    '',
    'https://www.ccd.gov.jo',
    'https://www.mit.gov.jo/EN/List/Services',
    'Registration Number',
  ),
  KW:   office(
    'Kuwait Business Center (Ministry of Commerce and Industry)',
    '+965 2248 0000',
    'Kuwait City, Kuwait',
    'https://www.moci.gov.kw',
    '',
    '',
    '',
    '',
    'https://e.gov.kw/sites/kgoenglish/Pages/eServices/MOCI/CommercialLicensing.aspx',
    'https://e.gov.kw/sites/kgoenglish/Pages/Services/MOCI/CommercialLicense.aspx',
    'Commercial License Number',
  ),
  LB:   office(
    'Lebanese Commercial Register (Ministry of Justice)',
    '+961 1 425000',
    'Palace of Justice, Beirut, Lebanon',
    'https://www.justice.gov.lb',
    '',
    '',
    '',
    '',
    'https://cr.justice.gov.lb',
    'https://investinlebanon.gov.lb/en/doing_business/starting_a_business',
    'Commercial Register Number',
  ),
  LY:   office(
    'Ministry of Economy and Trade Libya - Commercial Registry Department',
    '+218 21 335 0380',
    'Al-Sikka Road, Tripoli, Libya',
    'https://www.economy.gov.ly',
    'info@economy.gov.ly',
    '',
    '',
    '',
    'https://www.economy.gov.ly/services/commercial-register',
    '',
    'Commercial Registration Number',
  ),
  MR:   office(
    'Agence de Promotion des Investissements en Mauritanie (APIM) - Guichet Unique',
    '+222 45 25 33 77',
    'Ilot C, Tevragh Zeina, Nouakchott, Mauritania',
    'https://apim.gov.mr',
    'contact@apim.gov.mr',
    '',
    '',
    '',
    'https://apim.gov.mr/creation-dentreprise',
    'https://apim.gov.mr/guide-createur',
    'Numero RCCM',
  ),
  MA:   office(
    'OMPIC Morocco - DirectEntreprise',
    '+212 5 22 58 64 00',
    'Route de Nouasseur, Km 9.5, Casablanca, Morocco',
    'https://www.directentreprise.ma',
    'contact@ompic.ma',
    'https://x.com/OMPICMaroc',
    '',
    'https://www.linkedin.com/company/ompic-maroc/',
    'https://www.directentreprise.ma',
    'https://www.ompic.ma/fr/content/guide-de-creation',
    'Numero du Registre de Commerce (RC)',
  ),
  OM:   office(
    'Invest Easy (Ministry of Commerce, Industry and Investment Promotion)',
    '+968 800 77770',
    'Muscat, Oman',
    'https://www.business.gov.om',
    '',
    '',
    '',
    '',
    'https://www.business.gov.om',
    'https://www.business.gov.om/portal/en/home',
    'Commercial Registration Number',
  ),
  PS:   office(
    'Companies Registrar (Ministry of National Economy)',
    '+970 2 298 7990',
    'Ramallah, Palestine',
    'https://www.mne.gov.ps',
    '',
    '',
    '',
    '',
    'https://www.mne.gov.ps',
    'https://www.mne.gov.ps/services',
    'Company Registration Number',
  ),
  QA:   office(
    'Single Window (Ministry of Commerce and Industry Qatar)',
    '+974 16001',
    'Doha, Qatar',
    'https://www.moci.gov.qa',
    '',
    '',
    '',
    '',
    'https://www.sw.gov.qa',
    'https://www.moci.gov.qa/en/our-services/business-services/',
    'Commercial Registration (CR) Number',
  ),
  SA:   office(
    'Ministry of Commerce Saudi Arabia (Business Platform)',
    '+966 1900',
    'Riyadh, Saudi Arabia',
    'https://mc.gov.sa',
    '',
    '',
    '',
    '',
    'https://business.sa',
    'https://mc.gov.sa/ar/eservices/Pages/default.aspx',
    'Commercial Registration (CR) Number',
  ),
  SO:   office(
    'Ministry of Commerce and Industry Somalia - Company Registrar',
    '+252 61 553 3333',
    'Maka Al-Mukarama Road, Mogadishu, Somalia',
    'https://moci.gov.so',
    'info@moci.gov.so',
    '',
    '',
    '',
    'https://moci.gov.so/services/business-registration',
    '',
    'Business Registration Number',
  ),
  SD:   office(
    'Commercial Registrar General (Sudan Ministry of Justice)',
    '+249 183 770 920',
    'Ministry of Justice Complex, Khartoum, Sudan',
    'https://moj.gov.sd',
    'registry@moj.gov.sd',
    '',
    '',
    '',
    'https://moj.gov.sd/services/commercial-registration',
    '',
    'Commercial Registration Number',
  ),
  SY:   office(
    'Directorate of Companies (Ministry of Internal Trade and Consumer Protection)',
    '+963 11 221 0000',
    'Damascus, Syria',
    'http://mci.gov.sy',
    '',
    '',
    '',
    '',
    'http://mci.gov.sy',
    'http://mci.gov.sy/index.php?node=5512',
    'Commercial Register Number',
  ),
  TN:   office(
    'APII Tunisia - Guichet Unique de l\'Industrie',
    '+216 71 792 144',
    '63 Rue de Syrie, 1002 Tunis, Tunisia',
    'https://www.tunisieindustrie.nat.tn',
    'apii@apii.tn',
    '',
    '',
    'https://www.linkedin.com/company/agence-de-promotion-de-l-industrie-et-de-l-innovation/',
    'https://www.tunisieindustrie.nat.tn/fr/home.asp',
    'https://www.tunisieindustrie.nat.tn/fr/doc.asp',
    'Identifiant Unique de l\'Entreprise (RNE)',
  ),
  AE:   office(
    'UAE National Economic Register (Ministry of Economy)',
    '+971 8001222',
    'Ministry of Economy, Abu Dhabi, United Arab Emirates',
    'https://ner.economy.ae',
    'info@economy.ae',
    '',
    '',
    'https://www.linkedin.com/company/ministry-of-economy-uae/',
    'https://ner.economy.ae',
    'https://u.ae/en/information-and-services/business/starting-a-business',
    'Trade License Number',
  ),
  YE:   office(
    'Ministry of Industry and Trade - Companies Registrar',
    '+967 1 250 327',
    'Sanaa, Yemen',
    'https://www.moit.gov.ye',
    '',
    '',
    '',
    '',
    'https://www.moit.gov.ye',
    'https://yemen.gov.ye/portal/service',
    'Commercial Registration Number',
  ),
}
