import type { ArabLeagueMemberIsoCode } from './arabLeagueMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per Arab League member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const ARAB_LEAGUE_DOMESTIC_POST_SERVICES: Record<ArabLeagueMemberIsoCode, DomesticPostService> = {
  DZ: post(
    'Algérie Poste',
    'https://www.poste.dz/',
    'contact@poste.dz',
    'https://x.com/AlgPoste',
    'https://www.instagram.com/postealgerie/',
    'https://www.linkedin.com/company/algerie-poste/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '16000',
    'Five-digit postcode (wilaya + delivery area)',
  ),
  BH: post(
    'Bahrain Post',
    'https://www.bahrainpost.gov.bh/',
    'info@bahrainpost.gov.bh',
    'https://x.com/BahrainPost',
    'https://www.instagram.com/bahrainpost/',
    'https://www.linkedin.com/company/bahrain-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '317',
    'Three- or four-digit postcode',
  ),
  KM: post(
    'Comores Poste',
    'https://poste-comores.com/',
    'contact@poste-comores.km',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and village addressing',
  ),
  DJ: post(
    'La Poste de Djibouti',
    'https://www.laposte.dj/',
    'poste.contact@yahoo.fr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing in Djibouti City',
  ),
  EG: post(
    'Egypt Post',
    'http://www.egpost.org/',
    'webmaster@egpost.org',
    'https://x.com/Egyptpost',
    'https://www.instagram.com/egypt.post/',
    'https://www.linkedin.com/company/egypt-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11511',
    'Five-digit national postcode',
  ),
  IQ: post(
    'Iraqi Post (Iraq Post Company)',
    'https://www.iraqpost.net/',
    'info@iraqpost.net',
    '',
    '',
    'https://www.linkedin.com/company/iraq-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10001',
    'Five-digit postcode',
  ),
  JO: post(
    'Jordan Post',
    'https://www.jordanpost.com.jo/',
    'info@jordanpost.com.jo',
    'https://x.com/JordanPostCo',
    'https://www.instagram.com/jordanpost/',
    'https://www.linkedin.com/company/jordan-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11118',
    'Five-digit postcode',
  ),
  KW: post(
    'Kuwait Post',
    'https://www.kuwaitpost.com/',
    'info@kuwaitpost.com',
    'https://x.com/KuwaitPost',
    'https://www.instagram.com/kuwaitpost/',
    'https://www.linkedin.com/company/kuwait-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '13001',
    'Five-digit postcode',
  ),
  LB: post(
    'Liban Post',
    'https://www.libanpost.com/',
    'info@libanpost.com',
    'https://x.com/LibanPost',
    'https://www.instagram.com/libanpost/',
    'https://www.linkedin.com/company/liban-post/',
    '',
    'NNNN NNNN',
    '^\\d{4} \\d{4}$',
    '1107 2810',
    'Eight-digit postcode (two groups of four)',
  ),
  LY: post(
    'Libyan Post Company',
    'http://nlpc.ly/',
    'info@nlpc.ly',
    '',
    '',
    'https://www.linkedin.com/company/libyan-post/',
    '',
    'none',
    '',
    '',
    'No consistent national postcode published; verify locally',
  ),
  MR: post(
    'Mauripost (Société mauritanienne des postes)',
    'https://www.mauripost.mr/',
    'contact@mauripost.mr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  MA: post(
    'Barid Al-Maghrib',
    'https://www.barid.ma/',
    'webmaster@barid.ma',
    'https://x.com/PosteMaroc',
    'https://www.instagram.com/baridalma_',
    'https://www.linkedin.com/company/barid-al-maghrib/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '20000',
    'Five-digit postcode',
  ),
  OM: post(
    'Oman Post',
    'https://www.omanpost.om/',
    'info@omanpost.om',
    'https://x.com/OmanPost',
    'https://www.instagram.com/omanpost/',
    'https://www.linkedin.com/company/oman-post/',
    '',
    'NNN',
    '^\\d{3}$',
    '100',
    'Three-digit postcode',
  ),
  PS: post(
    'Palestinian Post (Palestine Post)',
    'https://www.palpost.ps/',
    'info@palpost.ps',
    'https://x.com/PalPostPs',
    'https://www.instagram.com/palpost.ps/',
    'https://www.linkedin.com/company/palestine-post/',
    '',
    'none',
    '',
    '',
    'P.O. Box and locality addressing; verify West Bank/Gaza routing',
  ),
  QA: post(
    'Qatar Post (Q-Post)',
    'https://www.qpost.com.qa/',
    'info@qpost.com.qa',
    'https://x.com/QatarPost',
    'https://www.instagram.com/qatarpost/',
    'https://www.linkedin.com/company/qatar-post/',
    '',
    'none',
    '',
    '',
    'No national street postcode; zone and building addressing',
  ),
  SA: post(
    'Saudi Post (SPL)',
    'https://splonline.com.sa/',
    'customercare@splonline.com.sa',
    'https://x.com/SPLCare',
    'https://www.instagram.com/splcare/',
    'https://www.linkedin.com/company/saudi-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11564',
    'Five-digit postcode (national addressing system)',
  ),
  SO: post(
    'Somali Postal Service',
    'https://www.upu.int/en/Somalia',
    'minister@mpt.gov.so',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district and landmark addressing',
  ),
  SD: post(
    'Sudan Post (Sudapost)',
    'https://sudapost.sd/',
    'info@sudapost.sd',
    '',
    '',
    'https://www.linkedin.com/company/sudan-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11111',
    'Five-digit postcode (verify operational coverage)',
  ),
  SY: post(
    'Syrian Post',
    'https://www.syrianpost.gov.sy/',
    'info@syrianpost.gov.sy',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No consistent national postcode published; verify locally',
  ),
  TN: post(
    'Rapid-Poste (La Poste Tunisia)',
    'https://www.pos.tn/',
    'contact@rapidpost.com.tn',
    'https://x.com/RapidposteTN',
    'https://www.instagram.com/rapidpostenetunisienne/',
    'https://www.linkedin.com/company/la-poste-tunisienne/',
    '',
    'NNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  AE: post(
    'Emirates Post Group',
    'https://www.epg.ae/',
    'info@epg.ae',
    'https://x.com/EmiratesPost',
    'https://www.instagram.com/emiratespost/',
    'https://www.linkedin.com/company/emirates-post-group/',
    '',
    'none',
    '',
    '',
    'No national postcode; Makani / building addressing in UAE',
  ),
  YE: post(
    'Yemen Post',
    'https://www.yemenpost.ye/',
    'info@yemenpost.ye',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'Limited national postcode coverage; verify operational status locally',
  ),
}
