import type { ArabLeagueMemberIsoCode } from './arabLeagueMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

/**
 * OAPI — unified trademarks and patents for Comoros and Mauritania (Bangui Agreement members).
 * Copyright remains with each national office per the WIPO directory. No documented public REST
 * API — e-services portal for filings.
 */
const OAPI_TRADEMARKS = ip(
  'trademarks',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

const OAPI_PATENTS = ip(
  'patents',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

function oapiMember(copyright: IntellectualPropertyDepartment): IntellectualPropertyDepartmentsRoster {
  return roster(copyright, OAPI_TRADEMARKS, OAPI_PATENTS)
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for League of Arab States members
 * represented in this module (informational; verify URLs, handles, forms portals, and API bases
 * before production use). Ten African members align with African Union entries for the same ISO
 * codes in `africanUnion/intellectualPropertyDepartmentsByIso.ts`. Gulf and Levant members use
 * national MOCI / economy IP desks and dedicated authorities (e.g. SAIP, UAE MoE IP). Comoros and
 * Mauritania are OAPI / Bangui Agreement states. `apiEndpoint` is almost always empty. Verify
 * periodically against WIPO’s directory of IP offices:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const ARAB_LEAGUE_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  ArabLeagueMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  DZ: roster(
    ip(
      'copyright',
      'Office Algérien du Droit d\'Auteur et des Droits Voisins (OADA)',
      'https://www.oada.dz',
      'contact@oada.dz',
      '',
      '',
      'https://www.oada.dz',
    ),
    ip(
      'trademarks',
      'Institut National de la Propriété Industrielle (INAPI)',
      'https://www.inapi.dz',
      'contact@inapi.dz',
      '',
      '',
      'https://www.inapi.dz',
    ),
    ip(
      'patents',
      'Institut National de la Propriété Industrielle (INAPI)',
      'https://www.inapi.dz',
      'contact@inapi.dz',
      '',
      '',
      'https://www.inapi.dz',
    ),
  ),
  BH: roster(
    ip(
      'copyright',
      'Ministry of Information — copyright (Bahrain)',
      'https://www.mia.gov.bh',
      '',
      '',
      '',
      'https://www.mia.gov.bh',
    ),
    ip(
      'trademarks',
      'National Office for Industrial Property (NOIP) — Ministry of Industry and Commerce (Bahrain)',
      'https://www.moic.gov.bh',
      '',
      '',
      '',
      'https://www.moic.gov.bh',
    ),
    ip(
      'patents',
      'National Office for Industrial Property (NOIP) — Ministry of Industry and Commerce (Bahrain)',
      'https://www.moic.gov.bh',
      '',
      '',
      '',
      'https://www.moic.gov.bh',
    ),
  ),
  KM: oapiMember(
    ip(
      'copyright',
      'Centre Comorien du Droit d\'Auteur et des Droits Voisins',
      'https://www.beit-salam.km',
      '',
      '',
      '',
      'https://www.beit-salam.km',
    ),
  ),
  DJ: roster(
    ip(
      'copyright',
      'Ministry of Culture and Communication — copyright (Djibouti)',
      'https://www.communication.gouv.dj',
      '',
      '',
      '',
      'https://www.communication.gouv.dj',
    ),
    ip(
      'trademarks',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
    ip(
      'patents',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
  ),
  EG: roster(
    ip(
      'copyright',
      'Egyptian Copyright Office (Ministry of Culture)',
      'https://www.culture.gov.eg',
      '',
      '',
      '',
      'https://www.culture.gov.eg',
    ),
    ip(
      'trademarks',
      'Egyptian Patent Office — Trademarks Department',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
    ip(
      'patents',
      'Egyptian Patent Office',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
  ),
  IQ: roster(
    ip(
      'copyright',
      'Ministry of Culture, Tourism and Antiquities — copyright (Iraq) (verify locally)',
      'https://www.mocul.gov.iq',
      '',
      '',
      '',
      'https://www.mocul.gov.iq',
    ),
    ip(
      'trademarks',
      'Central Organization for Standardization and Quality Control — industrial property (Iraq) (verify locally)',
      'https://www.cosqc.gov.iq',
      '',
      '',
      '',
      'https://www.cosqc.gov.iq',
    ),
    ip(
      'patents',
      'Ministry of Industry and Minerals — patents (Iraq) (verify locally)',
      'https://www.industry.gov.iq',
      '',
      '',
      '',
      'https://www.industry.gov.iq',
    ),
  ),
  JO: roster(
    ip(
      'copyright',
      'National Library Department — copyright (Jordan)',
      'https://www.nl.gov.jo',
      '',
      '',
      '',
      'https://www.nl.gov.jo',
    ),
    ip(
      'trademarks',
      'Ministry of Industry, Trade and Supply — industrial property (Jordan)',
      'https://www.mit.gov.jo',
      '',
      '',
      '',
      'https://www.mit.gov.jo',
    ),
    ip(
      'patents',
      'Ministry of Industry, Trade and Supply — patents (Jordan)',
      'https://www.mit.gov.jo',
      '',
      '',
      '',
      'https://www.mit.gov.jo',
    ),
  ),
  KW: roster(
    ip(
      'copyright',
      'National Council for Culture, Arts and Letters — copyright (Kuwait)',
      'https://www.nccal.gov.kw',
      '',
      '',
      '',
      'https://www.nccal.gov.kw',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce and Industry — intellectual property (Kuwait)',
      'https://www.moci.gov.kw',
      '',
      '',
      '',
      'https://www.moci.gov.kw',
    ),
    ip(
      'patents',
      'Ministry of Commerce and Industry — intellectual property (Kuwait)',
      'https://www.moci.gov.kw',
      '',
      '',
      '',
      'https://www.moci.gov.kw',
    ),
  ),
  LB: roster(
    ip(
      'copyright',
      'Ministry of Culture — copyright (Lebanon) (verify locally)',
      'https://www.culture.gov.lb',
      '',
      '',
      '',
      'https://www.culture.gov.lb',
    ),
    ip(
      'trademarks',
      'Ministry of Economy and Trade — intellectual property (Lebanon) (verify locally)',
      'https://www.economy.gov.lb',
      '',
      '',
      '',
      'https://www.economy.gov.lb',
    ),
    ip(
      'patents',
      'Ministry of Economy and Trade — intellectual property (Lebanon) (verify locally)',
      'https://www.economy.gov.lb',
      '',
      '',
      '',
      'https://www.economy.gov.lb',
    ),
  ),
  LY: roster(
    ip(
      'copyright',
      'Libyan National Centre for Culture and Arts — copyright',
      'https://www.culture.gov.ly',
      '',
      '',
      '',
      'https://www.culture.gov.ly',
    ),
    ip(
      'trademarks',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
    ip(
      'patents',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
  ),
  MR: oapiMember(
    ip(
      'copyright',
      'Bureau Mauritanien du Droit d\'Auteur (BUMDA)',
      'https://www.bumda.mr',
      '',
      '',
      '',
      'https://www.bumda.mr',
    ),
  ),
  MA: roster(
    ip(
      'copyright',
      'Bureau Marocain des Droits d\'Auteur (BMDA)',
      'https://www.bmda.org',
      'contact@bmda.org',
      '',
      '',
      'https://www.bmda.org',
    ),
    ip(
      'trademarks',
      'Office Marocain de la Propriété Industrielle et Commerciale (OMPIC)',
      'https://www.ompic.ma',
      'contact@ompic.ma',
      '',
      'https://www.linkedin.com/company/ompic/',
      'https://www.ompic.ma',
    ),
    ip(
      'patents',
      'Office Marocain de la Propriété Industrielle et Commerciale (OMPIC)',
      'https://www.ompic.ma',
      'contact@ompic.ma',
      '',
      'https://www.linkedin.com/company/ompic/',
      'https://www.ompic.ma',
    ),
  ),
  OM: roster(
    ip(
      'copyright',
      'Ministry of Culture, Sports and Youth — copyright (Oman)',
      'https://www.mcsy.gov.om',
      '',
      '',
      '',
      'https://www.mcsy.gov.om',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Investment Promotion — intellectual property (Oman)',
      'https://www.moci.gov.om',
      '',
      '',
      '',
      'https://www.moci.gov.om',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Investment Promotion — intellectual property (Oman)',
      'https://www.moci.gov.om',
      '',
      '',
      '',
      'https://www.moci.gov.om',
    ),
  ),
  PS: roster(
    ip(
      'copyright',
      'Ministry of Culture — copyright (Palestine) (verify locally)',
      'https://www.moc.pna.ps',
      '',
      '',
      '',
      'https://www.moc.pna.ps',
    ),
    ip(
      'trademarks',
      'Ministry of National Economy — industrial property (Palestine) (verify locally)',
      'https://www.mne.gov.ps',
      '',
      '',
      '',
      'https://www.mne.gov.ps',
    ),
    ip(
      'patents',
      'Ministry of National Economy — industrial property (Palestine) (verify locally)',
      'https://www.mne.gov.ps',
      '',
      '',
      '',
      'https://www.mne.gov.ps',
    ),
  ),
  QA: roster(
    ip(
      'copyright',
      'Ministry of Culture — copyright (Qatar)',
      'https://www.moc.gov.qa',
      '',
      '',
      '',
      'https://www.moc.gov.qa',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce and Industry — intellectual property (Qatar)',
      'https://www.moci.gov.qa',
      '',
      '',
      '',
      'https://www.moci.gov.qa',
    ),
    ip(
      'patents',
      'Ministry of Commerce and Industry — intellectual property (Qatar)',
      'https://www.moci.gov.qa',
      '',
      '',
      '',
      'https://www.moci.gov.qa',
    ),
  ),
  SA: roster(
    ip(
      'copyright',
      'Saudi Authority for Intellectual Property (SAIP)',
      'https://www.saip.gov.sa',
      'info@saip.gov.sa',
      '',
      'https://www.linkedin.com/company/saudi-authority-for-intellectual-property/',
      'https://www.saip.gov.sa',
    ),
    ip(
      'trademarks',
      'Saudi Authority for Intellectual Property (SAIP)',
      'https://www.saip.gov.sa',
      'info@saip.gov.sa',
      '',
      'https://www.linkedin.com/company/saudi-authority-for-intellectual-property/',
      'https://www.saip.gov.sa',
    ),
    ip(
      'patents',
      'Saudi Authority for Intellectual Property (SAIP)',
      'https://www.saip.gov.sa',
      'info@saip.gov.sa',
      '',
      'https://www.linkedin.com/company/saudi-authority-for-intellectual-property/',
      'https://www.saip.gov.sa',
    ),
  ),
  SO: roster(
    ip(
      'copyright',
      'Ministry of Information, Culture and Tourism — copyright (Somalia)',
      'https://www.mict.gov.so',
      '',
      '',
      '',
      'https://www.mict.gov.so',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
    ip(
      'patents',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
  ),
  SD: roster(
    ip(
      'copyright',
      'Sudan Copyright Office (Ministry of Culture)',
      'https://www.moc.gov.sd',
      '',
      '',
      '',
      'https://www.moc.gov.sd',
    ),
    ip(
      'trademarks',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
    ip(
      'patents',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
  ),
  SY: roster(
    ip(
      'copyright',
      'Ministry of Culture — copyright (Syria) (verify locally)',
      'https://www.moc.gov.sy',
      '',
      '',
      '',
      'https://www.moc.gov.sy',
    ),
    ip(
      'trademarks',
      'Ministry of Industry — industrial property (Syria) (verify locally)',
      'https://www.industry.gov.sy',
      '',
      '',
      '',
      'https://www.industry.gov.sy',
    ),
    ip(
      'patents',
      'Ministry of Industry — industrial property (Syria) (verify locally)',
      'https://www.industry.gov.sy',
      '',
      '',
      '',
      'https://www.industry.gov.sy',
    ),
  ),
  TN: roster(
    ip(
      'copyright',
      'Office National du Droit d\'Auteur (ONDA)',
      'https://www.onda.tn',
      'contact@onda.tn',
      '',
      '',
      'https://www.onda.tn',
    ),
    ip(
      'trademarks',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
    ip(
      'patents',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
  ),
  AE: roster(
    ip(
      'copyright',
      'Ministry of Economy — Intellectual Property (United Arab Emirates)',
      'https://www.moec.gov.ae/en/ip',
      '',
      '',
      '',
      'https://www.moec.gov.ae/en/ip',
    ),
    ip(
      'trademarks',
      'Ministry of Economy — Intellectual Property (United Arab Emirates)',
      'https://www.moec.gov.ae/en/ip',
      '',
      '',
      '',
      'https://www.moec.gov.ae/en/ip',
    ),
    ip(
      'patents',
      'Ministry of Economy — Intellectual Property (United Arab Emirates)',
      'https://www.moec.gov.ae/en/ip',
      '',
      '',
      '',
      'https://www.moec.gov.ae/en/ip',
    ),
  ),
  YE: roster(
    ip(
      'copyright',
      'Ministry of Information, Culture and Tourism — copyright (Yemen) (verify locally)',
      'https://www.mic.gov.ye',
      '',
      '',
      '',
      'https://www.mic.gov.ye',
    ),
    ip(
      'trademarks',
      'Ministry of Industry and Trade — industrial property (Yemen) (verify locally)',
      'https://www.industry.gov.ye',
      '',
      '',
      '',
      'https://www.industry.gov.ye',
    ),
    ip(
      'patents',
      'Ministry of Industry and Trade — industrial property (Yemen) (verify locally)',
      'https://www.industry.gov.ye',
      '',
      '',
      '',
      'https://www.industry.gov.ye',
    ),
  ),
}
