import type { ArabLeagueMemberIsoCode } from './arabLeagueMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const ARAB_LEAGUE_MAIN_INTERNATIONAL_AIRPORTS: Record<ArabLeagueMemberIsoCode, MainInternationalAirport> = {
  DZ: {
    name: 'Houari Boumediene Airport (ALG)',
    website: 'https://www.aeroportalger.dz/',
    email: 'contact@aeroportalger.dz',
    twitter: 'https://x.com/AeroportALG',
    instagram: 'https://www.instagram.com/aeroportalger/',
    linkedin: 'https://www.linkedin.com/company/egsa-alger/',
    apiEndpoint: '',
  },
  BH: {
    name: 'Bahrain International Airport (BAH)',
    website: 'https://www.bahrainairport.com/',
    email: 'info@bahrainairport.com',
    twitter: 'https://x.com/BahrainAirport',
    instagram: 'https://www.instagram.com/bahrainairport/',
    linkedin: 'https://www.linkedin.com/company/bahrain-airport-company/',
    apiEndpoint: '',
  },
  KM: {
    name: 'Prince Said Ibrahim International Airport (HAH)',
    website: 'https://www.aeroport-comores.km/',
    email: 'info@aeroport-comores.km',
    twitter: 'https://x.com/AeroportHAH',
    instagram: 'https://www.instagram.com/aeroportcomores/',
    linkedin: 'https://www.linkedin.com/company/aeroport-prince-said-ibrahim/',
    apiEndpoint: '',
  },
  DJ: {
    name: 'Djibouti-Ambouli International Airport (JIB)',
    website: 'https://www.aeroport-djibouti.dj/',
    email: 'contact@aeroport-djibouti.dj',
    twitter: 'https://x.com/AeroportJIB',
    instagram: 'https://www.instagram.com/aeroportdjibouti/',
    linkedin: 'https://www.linkedin.com/company/djibouti-ambouli-international-airport/',
    apiEndpoint: '',
  },
  EG: {
    name: 'Cairo International Airport (CAI)',
    website: 'https://www.cairo-airport.com/',
    email: 'info@cairo-airport.com',
    twitter: 'https://x.com/CairoAirport',
    instagram: 'https://www.instagram.com/cairoairport/',
    linkedin: 'https://www.linkedin.com/company/cairo-airport/',
    apiEndpoint: '',
  },
  IQ: {
    name: 'Baghdad International Airport (BGW)',
    website: 'https://www.bgw.aero/',
    email: 'info@bgw.aero',
    twitter: 'https://x.com/BaghdadAirport',
    instagram: 'https://www.instagram.com/baghdadairport/',
    linkedin: 'https://www.linkedin.com/company/baghdad-international-airport/',
    apiEndpoint: '',
  },
  JO: {
    name: 'Queen Alia International Airport (AMM)',
    website: 'https://www.qaiairport.com/',
    email: 'info@qaiairport.com',
    twitter: 'https://x.com/QAIAirport',
    instagram: 'https://www.instagram.com/qaiairport/',
    linkedin: 'https://www.linkedin.com/company/queen-alia-international-airport/',
    apiEndpoint: '',
  },
  KW: {
    name: 'Kuwait International Airport (KWI)',
    website: 'https://www.kuwait-airport.com.kw/',
    email: 'info@kuwait-airport.com.kw',
    twitter: 'https://x.com/KuwaitAirport',
    instagram: 'https://www.instagram.com/kuwaitairport/',
    linkedin: 'https://www.linkedin.com/company/kuwait-airports/',
    apiEndpoint: '',
  },
  LB: {
    name: 'Beirut-Rafic Hariri International Airport (BEY)',
    website: 'https://www.beirutairport.gov.lb/',
    email: 'info@beirutairport.gov.lb',
    twitter: 'https://x.com/BeirutAirport',
    instagram: 'https://www.instagram.com/beirutairport/',
    linkedin: 'https://www.linkedin.com/company/rafic-hariri-international-airport/',
    apiEndpoint: '',
  },
  LY: {
    name: 'Mitiga International Airport (MJI)',
    website: 'https://www.lycaa.gov.ly/',
    email: 'info@lycaa.gov.ly',
    twitter: 'https://x.com/LYCAA_Libya',
    instagram: 'https://www.instagram.com/lycaa_libya/',
    linkedin: 'https://www.linkedin.com/company/libyan-civil-aviation-authority/',
    apiEndpoint: '',
  },
  MR: {
    name: 'Nouakchott-Oumtounsy International Airport (NKC)',
    website: 'https://www.anac.mr/',
    email: 'contact@anac.mr',
    twitter: 'https://x.com/ANAC_Mauritanie',
    instagram: 'https://www.instagram.com/anac_mauritanie/',
    linkedin: 'https://www.linkedin.com/company/anac-mauritanie/',
    apiEndpoint: '',
  },
  MA: {
    name: 'Mohammed V International Airport (CMN)',
    website: 'https://www.onda.ma/en',
    email: 'contact@onda.ma',
    twitter: 'https://x.com/ONDA_MAROC',
    instagram: 'https://www.instagram.com/onda_maroc/',
    linkedin: 'https://www.linkedin.com/company/onda-officiel/',
    apiEndpoint: '',
  },
  OM: {
    name: 'Muscat International Airport (MCT)',
    website: 'https://www.muscatairport.co.om/',
    email: 'info@muscatairport.co.om',
    twitter: 'https://x.com/MuscatAirport',
    instagram: 'https://www.instagram.com/muscatairport/',
    linkedin: 'https://www.linkedin.com/company/oman-airports/',
    apiEndpoint: '',
  },
  PS: {
    name: 'Yasser Arafat International Airport (GZA)',
    website: 'https://www.gia.gov.ps/',
    email: 'info@gia.gov.ps',
    twitter: 'https://x.com/GazaAirport',
    instagram: 'https://www.instagram.com/gazaairport/',
    linkedin: 'https://www.linkedin.com/company/gaza-international-airport/',
    apiEndpoint: '',
  },
  QA: {
    name: 'Hamad International Airport (DOH)',
    website: 'https://www.dohahamadairport.com/',
    email: 'info@dohahamadairport.com',
    twitter: 'https://x.com/HIAQatar',
    instagram: 'https://www.instagram.com/hiaqatar/',
    linkedin: 'https://www.linkedin.com/company/hamad-international-airport/',
    apiEndpoint: '',
  },
  SA: {
    name: 'King Khalid International Airport (RUH)',
    website: 'https://www.riyadhairports.com/',
    email: 'info@riyadhairports.com',
    twitter: 'https://x.com/RUH_Airport',
    instagram: 'https://www.instagram.com/ruh_airport/',
    linkedin: 'https://www.linkedin.com/company/riyadh-airports-company/',
    apiEndpoint: '',
  },
  SO: {
    name: 'Aden Adde International Airport (MGQ)',
    website: 'https://www.scaa.gov.so/',
    email: 'info@scaa.gov.so',
    twitter: 'https://x.com/SCAA_Somalia',
    instagram: 'https://www.instagram.com/scaa_somalia/',
    linkedin: 'https://www.linkedin.com/company/somalia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  SD: {
    name: 'Khartoum International Airport (KRT)',
    website: 'https://www.krtairport.gov.sd/',
    email: 'info@krtairport.gov.sd',
    twitter: 'https://x.com/KRTAirport',
    instagram: 'https://www.instagram.com/krtairport/',
    linkedin: 'https://www.linkedin.com/company/khartoum-international-airport/',
    apiEndpoint: '',
  },
  SY: {
    name: 'Damascus International Airport (DAM)',
    website: 'https://www.damascus-airport.com/',
    email: 'info@damascus-airport.com',
    twitter: 'https://x.com/DamascusAirport',
    instagram: 'https://www.instagram.com/damascusairport/',
    linkedin: 'https://www.linkedin.com/company/damascus-international-airport/',
    apiEndpoint: '',
  },
  TN: {
    name: 'Tunis-Carthage International Airport (TUN)',
    website: 'https://www.oaca.nat.tn/',
    email: 'contact@oaca.nat.tn',
    twitter: 'https://x.com/OACA_Tunisia',
    instagram: 'https://www.instagram.com/oaca_tunisia/',
    linkedin: 'https://www.linkedin.com/company/office-de-l-aviation-civile-et-des-aeroports-oaca/',
    apiEndpoint: '',
  },
  AE: {
    name: 'Zayed International Airport (AUH)',
    website: 'https://www.zayedinternationalairport.ae/',
    email: 'info@adairports.ae',
    twitter: 'https://x.com/ZayedAirport',
    instagram: 'https://www.instagram.com/zayedairport/',
    linkedin: 'https://www.linkedin.com/company/abu-dhabi-airports/',
    apiEndpoint: '',
  },
  YE: {
    name: 'Sana\'a International Airport (SAH)',
    website: 'https://www.yemenia.com/',
    email: 'info@yemenia.com',
    twitter: 'https://x.com/YemeniaAir',
    instagram: 'https://www.instagram.com/yemeniaair/',
    linkedin: 'https://www.linkedin.com/company/yemen-airways/',
    apiEndpoint: '',
  },
}
