import type { ArabLeagueMemberIsoCode } from './arabLeagueMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per Arab League member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const ARAB_LEAGUE_MAIN_INTERNATIONAL_SEAPORTS: Record<ArabLeagueMemberIsoCode, MainInternationalSeaport> = {
  DZ: seaport(
    'Port of Algiers',
    'https://www.epal.dz/',
    'contact@epal.dz',
    'https://x.com/EPA_Alger',
    'https://www.instagram.com/epa_alger/',
    'https://www.linkedin.com/company/entreprise-portuaire-d-alger/',
    'douane@douane.gov.dz',
    'https://www.douane.gov.dz',
    'Direction Générale des Douanes — Port d\'Alger, Alger, Algeria',
  ),
  BH: seaport(
    'Khalifa Bin Salman Port (Mina Salman)',
    'https://www.ports.gov.bh/',
    'info@ports.gov.bh',
    'https://x.com/BahrainPorts',
    'https://www.instagram.com/bahrainports/',
    'https://www.linkedin.com/company/ports-maritime-and-aviation-authority/',
    'customs@nca.gov.bh',
    'https://www.nca.gov.bh',
    'National Customs Authority — Mina Salman, Manama, Bahrain',
  ),
  KM: seaport(
    'Port of Moroni',
    'https://www.portcomores.km/',
    'info@portcomores.km',
    'https://x.com/PortComores',
    'https://www.instagram.com/portcomores/',
    'https://www.linkedin.com/company/port-autonome-des-comores/',
    'douanes@finances.km',
    'https://www.douanes.km',
    'Direction des Douanes — Port de Moroni, Moroni, Comoros',
  ),
  DJ: seaport(
    'Port of Djibouti',
    'https://www.portdedjibouti.com/',
    'contact@portdedjibouti.com',
    'https://x.com/PortDjibouti',
    'https://www.instagram.com/portdedjibouti/',
    'https://www.linkedin.com/company/port-de-djibouti/',
    'douanes@douanes.dj',
    'https://www.douanes.dj',
    'Direction Générale des Douanes — Port de Djibouti, Djibouti City, Djibouti',
  ),
  EG: seaport(
    'Port of Alexandria',
    'https://www.alexandria-port.com/',
    'info@alexandria-port.com',
    'https://x.com/AlexPortEgypt',
    'https://www.instagram.com/alexportegypt/',
    'https://www.linkedin.com/company/alexandria-port-authority/',
    'customs@customs.gov.eg',
    'https://www.customs.gov.eg',
    'Egyptian Customs Authority — Port of Alexandria, Alexandria, Egypt',
  ),
  IQ: seaport(
    'Umm Qasr Port',
    'https://www.scop.gov.iq/',
    'info@scop.gov.iq',
    'https://x.com/IraqPorts',
    'https://www.instagram.com/iraqports/',
    'https://www.linkedin.com/company/state-company-of-ports-iraq/',
    'customs@customs.gov.iq',
    'https://www.customs.gov.iq',
    'Iraqi Customs — Umm Qasr Port, Basra Governorate, Iraq',
  ),
  JO: seaport(
    'Port of Aqaba',
    'https://www.aqabaport.com.jo/',
    'info@aqabaport.com.jo',
    'https://x.com/AqabaPort',
    'https://www.instagram.com/aqabaport/',
    'https://www.linkedin.com/company/aqaba-port-marine-services/',
    'customs@customs.gov.jo',
    'https://www.customs.gov.jo',
    'Jordan Customs — Port of Aqaba, Aqaba, Jordan',
  ),
  KW: seaport(
    'Shuwaikh Port',
    'https://www.pak.gov.kw/',
    'info@pak.gov.kw',
    'https://x.com/KuwaitPorts',
    'https://www.instagram.com/kuwaitports/',
    'https://www.linkedin.com/company/ports-authority-kuwait/',
    'customs@customs.gov.kw',
    'https://www.customs.gov.kw',
    'Kuwait General Administration of Customs — Shuwaikh Port, Kuwait City, Kuwait',
  ),
  LB: seaport(
    'Port of Beirut',
    'https://www.portdebeyrouth.com/',
    'info@portdebeyrouth.com',
    'https://x.com/PortBeirut',
    'https://www.instagram.com/portbeirut/',
    'https://www.linkedin.com/company/port-of-beirut/',
    'customs@customs.gov.lb',
    'https://www.customs.gov.lb',
    'Lebanese Customs — Port of Beirut, Beirut, Lebanon',
  ),
  LY: seaport(
    'Port of Tripoli',
    'https://www.lpc.ly/',
    'info@lpc.ly',
    'https://x.com/LibyanPorts',
    'https://www.instagram.com/libyanports/',
    'https://www.linkedin.com/company/libyan-ports-corporation/',
    'customs@customs.gov.ly',
    'https://www.customs.gov.ly',
    'Libyan Customs Authority — Port of Tripoli, Tripoli, Libya',
  ),
  MR: seaport(
    'Port of Nouadhibou',
    'https://www.otal.com/mauritania/port-of-nouadhibou',
    'contact@portnouadhibou.mr',
    'https://x.com/PortNouadhibou',
    'https://www.instagram.com/portnouadhibou/',
    'https://www.linkedin.com/company/port-de-nouadhibou/',
    'douanes@finances.gov.mr',
    'https://www.douanes.gov.mr',
    'Direction Générale des Douanes — Port de Nouadhibou, Nouadhibou, Mauritania',
  ),
  MA: seaport(
    'Port of Tanger Med',
    'https://www.tangermed.ma/',
    'contact@tangermed.ma',
    'https://x.com/TangerMed',
    'https://www.instagram.com/tangermed/',
    'https://www.linkedin.com/company/tanger-med/',
    'douane@douane.gov.ma',
    'https://www.douane.gov.ma',
    'Administration des Douanes — Tanger Med, Tanger, Morocco',
  ),
  OM: seaport(
    'Port of Salalah',
    'https://www.salalahport.com/',
    'info@salalahport.com',
    'https://x.com/SalalahPort',
    'https://www.instagram.com/salalahport/',
    'https://www.linkedin.com/company/port-of-salalah/',
    'customs@customs.gov.om',
    'https://www.customs.gov.om',
    'Royal Oman Police Customs — Port of Salalah, Salalah, Oman',
  ),
  PS: seaport(
    'Port of Gaza',
    'https://www.portofgaza.ps/',
    'info@portofgaza.ps',
    '',
    '',
    'https://www.linkedin.com/company/port-of-gaza/',
    'customs@customs.pna.ps',
    'https://www.customs.pna.ps',
    'Palestinian Customs — Port of Gaza, Gaza City, Palestine',
  ),
  QA: seaport(
    'Hamad Port',
    'https://www.mwani.com.qa/',
    'info@mwani.com.qa',
    'https://x.com/MwaniQatar',
    'https://www.instagram.com/mwaniqatar/',
    'https://www.linkedin.com/company/mwani-qatar/',
    'customs@gac.gov.qa',
    'https://www.customs.gov.qa',
    'General Authority of Customs — Hamad Port, Doha, Qatar',
  ),
  SA: seaport(
    'King Abdullah Port',
    'https://www.ka-port.com.sa/',
    'info@ka-port.com.sa',
    'https://x.com/KingAbdullahPort',
    'https://www.instagram.com/kingabdullahport/',
    'https://www.linkedin.com/company/king-abdullah-port/',
    'customs@zatca.gov.sa',
    'https://www.zatca.gov.sa',
    'ZATCA Customs — King Abdullah Port, Rabigh, Saudi Arabia',
  ),
  SO: seaport(
    'Port of Mogadishu',
    'https://www.mpa.gov.so/',
    'info@mpa.gov.so',
    'https://x.com/MPA_Somalia',
    'https://www.instagram.com/mpa_somalia/',
    'https://www.linkedin.com/company/mogadishu-port-authority/',
    'customs@finance.gov.so',
    'https://www.customs.gov.so',
    'Somalia Customs — Port of Mogadishu, Mogadishu, Somalia',
  ),
  SD: seaport(
    'Port Sudan',
    'https://www.spc.sd/',
    'info@spc.sd',
    'https://x.com/SPC_Sudan',
    'https://www.instagram.com/spc_sudan/',
    'https://www.linkedin.com/company/sea-ports-corporation-sudan/',
    'customs@customs.gov.sd',
    'https://www.customs.gov.sd',
    'Sudan Customs Authority — Port Sudan, Port Sudan, Sudan',
  ),
  SY: seaport(
    'Port of Latakia',
    'https://www.lattakiaport.gov.sy/',
    'info@lattakiaport.gov.sy',
    '',
    '',
    'https://www.linkedin.com/company/lattakia-port/',
    'customs@customs.gov.sy',
    'https://www.customs.gov.sy',
    'Syrian Customs — Port of Latakia, Latakia, Syria',
  ),
  TN: seaport(
    'Port of Rades',
    'https://www.ommp.nat.tn/',
    'contact@ommp.nat.tn',
    'https://x.com/OMMP_Tunisia',
    'https://www.instagram.com/ommp_tunisia/',
    'https://www.linkedin.com/company/ommp-tunisia/',
    'douane@douane.gov.tn',
    'https://www.douane.gov.tn',
    'Direction Générale des Douanes — Port de Radès, Radès, Tunisia',
  ),
  AE: seaport(
    'Jebel Ali Port (Dubai)',
    'https://www.dpworld.com/uae',
    'info@dpworld.com',
    'https://x.com/DP_World',
    'https://www.instagram.com/dpworld/',
    'https://www.linkedin.com/company/dp-world/',
    'customs@customs.ae',
    'https://www.customs.ae',
    'Federal Customs Authority — Jebel Ali Port, Dubai, United Arab Emirates',
  ),
  YE: seaport(
    'Port of Aden',
    'https://www.adenport.com.ye/',
    'info@adenport.com.ye',
    '',
    '',
    'https://www.linkedin.com/company/aden-port/',
    'customs@customs.gov.ye',
    'https://www.customs.gov.ye',
    'Yemen Customs Authority — Port of Aden, Aden, Yemen',
  ),
}
