import type { NationalBankingInstitution } from './types'
import type { ArabLeagueMemberIsoCode } from './arabLeagueMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per Arab League member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const ARAB_LEAGUE_NATIONAL_BANKING_INSTITUTIONS: Record<
  ArabLeagueMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  DZ: [
    bank(
      'Banque Exterieure d Algerie (BEA)',
      '+213 21 98 02 98',
      '11 Rue Colonel Amirouche, Algiers, Algeria',
      '',
      '',
      'https://www.bea.dz/',
      'contact@bea.dz',
      '',
      '',
      'https://www.linkedin.com/company/bea-algerie/',
      '',
      '',
      '',
    ),
    bank(
      'Banque Nationale d Algerie (BNA)',
      '+213 21 63 56 56',
      '8 Boulevard Ernesto Che Guevara, Algiers, Algeria',
      '',
      '',
      'https://www.bna.dz/',
      'contact@bna.dz',
      '',
      '',
      'https://www.linkedin.com/company/banque-nationale-d-alg%C3%A9rie/',
      '',
      '',
      '',
    ),
    bank(
      'Credit Populaire d Algerie (CPA)',
      '+213 21 63 55 55',
      '2 Boulevard Colonel Amirouche, Algiers, Algeria',
      '',
      '',
      'https://www.cpa-bank.dz/',
      'contact@cpa-bank.dz',
      '',
      '',
      'https://www.linkedin.com/company/credit-populaire-d-algerie/',
      '',
      '',
      '',
    ),
  ],
  BH: [
    bank(
      'National Bank of Bahrain',
      '+973 1720 7777',
      'Government Avenue, Manama, Bahrain',
      'https://apps.apple.com/bh/app/nbb-digital-banking/id1536380198',
      'https://play.google.com/store/apps/details?id=com.nbb.digital',
      'https://www.nbbonline.com',
      'info@nbbonline.com',
      'https://twitter.com/NBBOnline',
      'https://www.instagram.com/nbbonline/',
      'https://www.linkedin.com/company/national-bank-of-bahrain/',
      '',
      'NBOBBHBM',
      '',
    ),
    bank(
      'Bank of Bahrain and Kuwait',
      '+973 1720 4444',
      '43 Government Avenue, Manama, Bahrain',
      'https://apps.apple.com/bh/app/bbk-mobile-banking/id620200228',
      'https://play.google.com/store/apps/details?id=com.path.bbkmobilebanking',
      'https://www.bbkonline.com',
      'info@bbkonline.com',
      'https://twitter.com/bbkbank',
      'https://www.instagram.com/bbkbank/',
      'https://www.linkedin.com/company/bbkbank/',
      '',
      'BBKUBHBM',
      '',
    ),
    bank(
      'Ahli United Bank Bahrain',
      '+973 1758 5858',
      'Manama Center, Manama, Bahrain',
      'https://apps.apple.com/bh/app/ahli-united-bank-bh/id1470266993',
      'https://play.google.com/store/apps/details?id=com.aub.mobile.bh',
      'https://www.ahliunited.com/bh',
      'customerservice@ahliunited.com',
      'https://twitter.com/AUB_Bahrain',
      'https://www.instagram.com/aub_bahrain/',
      'https://www.linkedin.com/company/ahli-united-bank/',
      '',
      'AUBBBHBM',
      '',
    ),
  ],
  KM: [
    bank(
      'Banque Federale de Commerce (BFC)',
      '+269 773 20 00',
      'Place de France, Moroni, Comoros',
      '',
      '',
      'https://www.bfc-comores.com/',
      'contact@bfc-comores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Exim Bank Comores',
      '+269 773 25 25',
      'Avenue de la Corniche, Moroni, Comoros',
      '',
      '',
      'https://www.eximbankcomores.com/',
      'info@eximbankcomores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'SNPSF',
      '+269 773 18 18',
      'Avenue Ali Soilih, Moroni, Comoros',
      '',
      '',
      'https://www.snpsf.com/',
      'contact@snpsf.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  DJ: [
    bank(
      'CAC International Bank',
      '+253 21 32 22 22',
      'Place Menelik, Djibouti City, Djibouti',
      '',
      '',
      'https://www.cacbankdj.com/',
      'contact@cacbankdj.com',
      '',
      '',
      'https://www.linkedin.com/company/cac-international-bank/',
      '',
      'CACBDJDJ',
      '',
    ),
    bank(
      'Salaam African Bank',
      '+253 21 35 55 55',
      'Avenue Hassan Gouled, Djibouti City, Djibouti',
      '',
      '',
      'https://www.salaam-bank.com/',
      'info@salaam-bank.com',
      '',
      '',
      'https://www.linkedin.com/company/salaam-african-bank/',
      '',
      '',
      '',
    ),
    bank(
      'BCIMR',
      '+253 21 35 30 30',
      'Place Lagarde, Djibouti City, Djibouti',
      '',
      '',
      'https://www.bcimr.dj/',
      'contact@bcimr.dj',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  EG: [
    bank(
      'National Bank of Egypt',
      '+20 2 2576 0777',
      '1187 Corniche El Nil, Cairo, Egypt',
      '',
      '',
      'https://www.nbe.com.eg/',
      'customer.service@nbe.com.eg',
      '',
      '',
      'https://www.linkedin.com/company/national-bank-of-egypt/',
      '',
      'NBEGEGCX',
      '',
    ),
    bank(
      'Banque Misr',
      '+20 2 19888',
      '151 Mohamed Farid St, Cairo, Egypt',
      '',
      '',
      'https://www.banquemisr.com/',
      'customercare@banquemisr.com',
      '',
      '',
      'https://www.linkedin.com/company/banque-misr/',
      '',
      'BMISEGCX',
      '',
    ),
    bank(
      'Commercial International Bank (CIB)',
      '+20 2 19666',
      '21/23 Charles de Gaulle St, Giza, Egypt',
      '',
      '',
      'https://www.cibeg.com/',
      'customer.care@cibeg.com',
      '',
      '',
      'https://www.linkedin.com/company/cibegypt/',
      '',
      'CIBEEGCX',
      '',
    ),
  ],
  IQ: [
    bank(
      'Rafidain Bank',
      '+964 1 8177600',
      'Al-Rasheed Street, Baghdad, Iraq',
      '',
      '',
      'https://rafidain-bank.gov.iq',
      'info@rafidain-bank.gov.iq',
      '',
      '',
      '',
      '',
      'RAFDIQBA',
      '',
    ),
    bank(
      'Trade Bank of Iraq',
      '+964 1 7739444',
      'Al-Karrada, Baghdad, Iraq',
      '',
      '',
      'https://www.tbiraq.com',
      'info@tbiraq.com',
      '',
      '',
      'https://www.linkedin.com/company/trade-bank-of-iraq/',
      '',
      'TRIQIQBA',
      '',
    ),
    bank(
      'National Bank of Iraq',
      '+964 1 7198066',
      'Arasat Al-Hindiyah, Baghdad, Iraq',
      '',
      '',
      'https://nbi.iq',
      'info@nbi.iq',
      'https://twitter.com/nbi_iraq',
      'https://www.instagram.com/nbi_iraq/',
      'https://www.linkedin.com/company/national-bank-of-iraq/',
      '',
      'NBIQIQBA',
      '',
    ),
  ],
  JO: [
    bank(
      'Arab Bank',
      '+962 6 4600900',
      'Shmeisani, Amman, Jordan',
      'https://apps.apple.com/jo/app/arab-bank-mobile-banking/id548103117',
      'https://play.google.com/store/apps/details?id=com.arabbank.app',
      'https://www.arabbank.com',
      'customer.care@arabbank.com',
      'https://twitter.com/Arabbankgroup',
      'https://www.instagram.com/arabbankgroup/',
      'https://www.linkedin.com/company/arab-bank/',
      '',
      'ARABJOAX',
      '',
    ),
    bank(
      'Housing Bank for Trade and Finance',
      '+962 6 5200400',
      'Shmeisani, Amman, Jordan',
      'https://apps.apple.com/jo/app/housing-bank-mobile-app/id1484556773',
      'https://play.google.com/store/apps/details?id=com.hbtf.mobile',
      'https://www.hbtf.com',
      'customerservice@hbtf.com',
      'https://twitter.com/HousingBankJo',
      'https://www.instagram.com/housingbankjo/',
      'https://www.linkedin.com/company/housing-bank/',
      '',
      'HBHOJOAM',
      '',
    ),
    bank(
      'Jordan Kuwait Bank',
      '+962 6 5202222',
      'Abdali Boulevard, Amman, Jordan',
      'https://apps.apple.com/jo/app/jkbmobile/id1222397087',
      'https://play.google.com/store/apps/details?id=com.jkb.jkbmobile',
      'https://www.jkb.com',
      'contactus@jkb.com',
      'https://twitter.com/JKBJO',
      'https://www.instagram.com/jkbjo/',
      'https://www.linkedin.com/company/jordan-kuwait-bank/',
      '',
      'JOKWJOAM',
      '',
    ),
  ],
  KW: [
    bank(
      'National Bank of Kuwait',
      '+965 1801801',
      'Abdullah Al-Ahmad Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/nbk-mobile-banking/id380982741',
      'https://play.google.com/store/apps/details?id=com.nbk',
      'https://www.nbk.com',
      'customer.relations@nbk.com',
      'https://twitter.com/NBKPage',
      'https://www.instagram.com/nbkpage/',
      'https://www.linkedin.com/company/national-bank-of-kuwait/',
      '',
      'NBOKKWKW',
      '',
    ),
    bank(
      'Kuwait Finance House',
      '+965 1803333',
      'KFH Tower, Abdullah Al-Mubarak Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/kfhonline/id570920246',
      'https://play.google.com/store/apps/details?id=com.kfh',
      'https://www.kfh.com',
      'contactus@kfh.com',
      'https://twitter.com/KFHGroup',
      'https://www.instagram.com/kfhgroup/',
      'https://www.linkedin.com/company/kuwait-finance-house/',
      '',
      'KFHOKWKW',
      '',
    ),
    bank(
      'Burgan Bank',
      '+965 1804080',
      'Al-Shuhada Street, Kuwait City, Kuwait',
      'https://apps.apple.com/kw/app/burgan-bank/id596108948',
      'https://play.google.com/store/apps/details?id=com.burganbank.mobile',
      'https://www.burgan.com',
      'contactus@burgan.com',
      'https://twitter.com/BurganBank',
      'https://www.instagram.com/burganbank/',
      'https://www.linkedin.com/company/burgan-bank/',
      '',
      'BRGNKWKW',
      '',
    ),
  ],
  LB: [
    bank(
      'Bank Audi',
      '+961 1 994000',
      'Bab Idriss, Beirut Central District, Beirut, Lebanon',
      'https://apps.apple.com/lb/app/bank-audi-mobile/id440803985',
      'https://play.google.com/store/apps/details?id=com.bankaudi.mobilebanking',
      'https://www.bankaudigroup.com',
      'info@bankaudi.com.lb',
      'https://twitter.com/BankAudi',
      'https://www.instagram.com/bankaudi/',
      'https://www.linkedin.com/company/bank-audi/',
      '',
      'AUDBLBBX',
      '',
    ),
    bank(
      'BLOM Bank',
      '+961 1 991000',
      'Verdun Main Street, Beirut, Lebanon',
      'https://apps.apple.com/lb/app/blom-bank-mobile/id689928042',
      'https://play.google.com/store/apps/details?id=com.blombank.mobile',
      'https://www.blombank.com',
      'customerservice@blombank.com',
      'https://twitter.com/BLOMBANK',
      'https://www.instagram.com/blombank/',
      'https://www.linkedin.com/company/blom-bank/',
      '',
      'BLOMLBBX',
      '',
    ),
    bank(
      'Byblos Bank',
      '+961 1 205050',
      'Achrafieh, Beirut, Lebanon',
      'https://apps.apple.com/lb/app/byblos-bank-mobile/id469196143',
      'https://play.google.com/store/apps/details?id=com.byblosbank.mobile',
      'https://www.byblosbank.com',
      'customersupport@byblosbank.com.lb',
      'https://twitter.com/ByblosBank',
      'https://www.instagram.com/byblosbank/',
      'https://www.linkedin.com/company/byblos-bank/',
      '',
      'BYBALBBX',
      '',
    ),
  ],
  LY: [
    bank(
      'Wahda Bank',
      '+218 21 333 5511',
      'Omar Mukhtar Street, Tripoli, Libya',
      '',
      '',
      'https://wahdabank.ly/',
      'info@wahdabank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Jumhouria Bank',
      '+218 21 360 2000',
      'Al Fatah Street, Tripoli, Libya',
      '',
      '',
      'https://www.jbank.ly/',
      'info@jbank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'National Commercial Bank Libya',
      '+218 21 444 9200',
      'September 1st Street, Tripoli, Libya',
      '',
      '',
      'https://www.ncb.ly/',
      'info@ncb.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  MR: [
    bank(
      'Banque Mauritanienne pour le Commerce International (BMCI)',
      '+222 45 29 11 22',
      'Avenue Gamal Abdel Nasser, Nouakchott, Mauritania',
      '',
      '',
      'https://www.bmci.mr/',
      'contact@bmci.mr',
      '',
      '',
      '',
      '',
      'BMCIMRMR',
      '',
    ),
    bank(
      'Banque El Amana',
      '+222 45 25 55 55',
      'Tevragh Zeina, Nouakchott, Mauritania',
      '',
      '',
      'https://www.elamana-bank.mr/',
      'info@elamana-bank.mr',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Societe Generale Mauritanie',
      '+222 45 29 33 33',
      'Ilot K, Nouakchott, Mauritania',
      '',
      '',
      'https://www.societegenerale.mr/',
      'contact@societegenerale.mr',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  MA: [
    bank(
      'Attijariwafa bank',
      '+212 5 22 58 88 88',
      '2 Boulevard Moulay Youssef, Casablanca, Morocco',
      '',
      '',
      'https://www.attijariwafabank.com/',
      'contact@attijariwafa.com',
      '',
      '',
      'https://www.linkedin.com/company/attijariwafa-bank/',
      '',
      'BCMAMAMC',
      '',
    ),
    bank(
      'Banque Populaire du Maroc',
      '+212 5 22 20 25 25',
      '101 Boulevard Mohamed Zerktouni, Casablanca, Morocco',
      '',
      '',
      'https://www.gbp.ma/',
      'relationclient@gbp.ma',
      '',
      '',
      'https://www.linkedin.com/company/banque-populaire-maroc/',
      '',
      'BCPOMAMC',
      '',
    ),
    bank(
      'Bank of Africa Maroc',
      '+212 5 22 46 90 00',
      '140 Avenue Hassan II, Casablanca, Morocco',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.bankofafrica.ma/',
      'relationclient@bankofafrica.ma',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      'BMCEMAMC',
      '',
    ),
  ],
  OM: [
    bank(
      'Bank Muscat',
      '+968 24795555',
      'Airport Heights, Muscat, Oman',
      'https://apps.apple.com/om/app/bank-muscat-mobile-banking/id563857469',
      'https://play.google.com/store/apps/details?id=com.bankmuscat.mbanking',
      'https://www.bankmuscat.com',
      'customercare@bankmuscat.com',
      'https://twitter.com/bankmuscat',
      'https://www.instagram.com/bankmuscat/',
      'https://www.linkedin.com/company/bank-muscat/',
      '',
      'BMUSOMRX',
      '',
    ),
    bank(
      'National Bank of Oman',
      '+968 24770000',
      'Azaiba, Muscat, Oman',
      'https://apps.apple.com/om/app/nbo-mobile-banking/id534479122',
      'https://play.google.com/store/apps/details?id=com.nbo.om',
      'https://www.nbo.om',
      'customercare@nbo.om',
      'https://twitter.com/NBO_Oman',
      'https://www.instagram.com/nbo_oman/',
      'https://www.linkedin.com/company/national-bank-of-oman/',
      '',
      'NBOMOMRX',
      '',
    ),
    bank(
      'Sohar International',
      '+968 24730000',
      'Madinat Al Sultan Qaboos, Muscat, Oman',
      'https://apps.apple.com/om/app/sohar-international/id1455523628',
      'https://play.google.com/store/apps/details?id=com.sohar.mobilebanking',
      'https://www.soharinternational.com',
      'care@soharinternational.com',
      'https://twitter.com/Sohar_Intl',
      'https://www.instagram.com/sohar_intl/',
      'https://www.linkedin.com/company/sohar-international/',
      '',
      'BSHOOMRX',
      '',
    ),
  ],
  PS: [
    bank(
      'Bank of Palestine',
      '+970 2 2974000',
      'Ain Misbah, Ramallah, Palestine',
      'https://apps.apple.com/il/app/bank-of-palestine/id6444734527',
      'https://play.google.com/store/apps/details?id=com.bop.mobile',
      'https://www.bankofpalestine.com',
      'customerservice@bop.ps',
      'https://twitter.com/BankOfPalestine',
      'https://www.instagram.com/bankofpalestine/',
      'https://www.linkedin.com/company/bank-of-palestine/',
      '',
      'PALSPS22',
      '',
    ),
    bank(
      'Quds Bank',
      '+970 2 2943333',
      'Al-Irsal Street, Ramallah, Palestine',
      'https://apps.apple.com/il/app/quds-bank/id1480477702',
      'https://play.google.com/store/apps/details?id=com.qudsbank.mobile',
      'https://www.qudsbank.ps',
      'info@qudsbank.ps',
      'https://twitter.com/QudsBank',
      'https://www.instagram.com/qudsbank/',
      'https://www.linkedin.com/company/quds-bank/',
      '',
      'QUDSPS22',
      '',
    ),
    bank(
      'Palestine Islamic Bank',
      '+970 2 2969888',
      'Al-Masyoun, Ramallah, Palestine',
      'https://apps.apple.com/il/app/pib-mobile-banking/id1435120514',
      'https://play.google.com/store/apps/details?id=com.pib.ps',
      'https://www.islamicbank.ps',
      'info@islamicbank.ps',
      'https://twitter.com/PIB_Palestine',
      'https://www.instagram.com/pib_palestine/',
      'https://www.linkedin.com/company/palestine-islamic-bank/',
      '',
      'PISBPS22',
      '',
    ),
  ],
  QA: [
    bank(
      'Qatar National Bank',
      '+974 44407777',
      'Grand Hamad Street, Doha, Qatar',
      'https://apps.apple.com/qa/app/qnb-mobile/id727432019',
      'https://play.google.com/store/apps/details?id=com.qnb.mobile',
      'https://www.qnb.com',
      'customerservice@qnb.com',
      'https://twitter.com/QNBGroup',
      'https://www.instagram.com/qnbgroup/',
      'https://www.linkedin.com/company/qnbgroup/',
      '',
      'QNBAQAQA',
      '',
    ),
    bank(
      'Commercial Bank of Qatar',
      '+974 44490000',
      'West Bay, Doha, Qatar',
      'https://apps.apple.com/qa/app/commercial-bank-mobile/id576885219',
      'https://play.google.com/store/apps/details?id=com.cbq.mobile',
      'https://www.cbq.qa',
      'customerservice@cbq.qa',
      'https://twitter.com/CBQatar',
      'https://www.instagram.com/cbqatar/',
      'https://www.linkedin.com/company/commercial-bank/',
      '',
      'CBQAQAQA',
      '',
    ),
    bank(
      'Doha Bank',
      '+974 44456000',
      'Doha Bank Tower, West Bay, Doha, Qatar',
      'https://apps.apple.com/qa/app/doha-bank-qatar/id1148136142',
      'https://play.google.com/store/apps/details?id=com.dohabank.mobilebanking',
      'https://www.dohabank.com',
      'customerservice@dohabank.com.qa',
      'https://twitter.com/DohaBank',
      'https://www.instagram.com/dohabank/',
      'https://www.linkedin.com/company/doha-bank/',
      '',
      'DOHBQAQA',
      '',
    ),
  ],
  SA: [
    bank(
      'Saudi National Bank',
      '+966 920001000',
      'King Saud Road, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/alahlimobile/id470322247',
      'https://play.google.com/store/apps/details?id=com.alahli.mobile',
      'https://www.alahli.com',
      'care@alahli.com',
      'https://twitter.com/SNBAlAhli',
      'https://www.instagram.com/snbalahli/',
      'https://www.linkedin.com/company/snbaik/',
      '',
      'NCBKSAJE',
      '',
    ),
    bank(
      'Al Rajhi Bank',
      '+966 920003344',
      'Olaya Street, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/al-rajhi-bank/id563339275',
      'https://play.google.com/store/apps/details?id=com.alrajhibank.mobile',
      'https://www.alrajhibank.com.sa',
      'care@alrajhibank.com.sa',
      'https://twitter.com/AlRajhiBank',
      'https://www.instagram.com/alrajhibank/',
      'https://www.linkedin.com/company/alrajhibank/',
      '',
      'RJHISARI',
      '',
    ),
    bank(
      'Riyad Bank',
      '+966 920002470',
      'King Fahd Road, Riyadh, Saudi Arabia',
      'https://apps.apple.com/sa/app/riyad-mobile/id593620831',
      'https://play.google.com/store/apps/details?id=com.riyadbank.mobile',
      'https://www.riyadbank.com',
      'customercare@riyadbank.com',
      'https://twitter.com/RiyadBank',
      'https://www.instagram.com/riyadbank/',
      'https://www.linkedin.com/company/riyad-bank/',
      '',
      'RIBLSARI',
      '',
    ),
  ],
  SO: [
    bank(
      'Salaam Somali Bank',
      '+252 61 700 0000',
      'KM4, Mogadishu, Somalia',
      '',
      '',
      'https://www.salaambank.so/',
      'info@salaambank.so',
      '',
      '',
      'https://www.linkedin.com/company/salaam-somali-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Premier Bank Somalia',
      '+252 61 222 1111',
      'Airport Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.premierbank.so/',
      'info@premierbank.so',
      '',
      '',
      'https://www.linkedin.com/company/premier-bank-somalia/',
      '',
      '',
      '',
    ),
    bank(
      'Dahabshiil Bank International',
      '+252 63 333 3000',
      'Maka Al Mukarama Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.dahabshiilbank.com/',
      'info@dahabshiilbank.com',
      '',
      '',
      'https://www.linkedin.com/company/dahabshiil-bank-international/',
      '',
      '',
      '',
    ),
  ],
  SD: [
    bank(
      'Bank of Khartoum',
      '+249 183 782 000',
      'Mek Nimir Ave, Khartoum, Sudan',
      '',
      '',
      'https://bankofkhartoum.com/',
      'contactus@bok.sd',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-khartoum/',
      '',
      'BOKHSDKH',
      '',
    ),
    bank(
      'Omdurman National Bank',
      '+249 183 783 200',
      'Baladia Street, Khartoum, Sudan',
      '',
      '',
      'https://www.onb-sd.com/',
      'info@onb-sd.com',
      '',
      '',
      '',
      '',
      'ONBKSDKH',
      '',
    ),
    bank(
      'Faisal Islamic Bank Sudan',
      '+249 183 774 000',
      'Al Gamhouria Street, Khartoum, Sudan',
      '',
      '',
      'https://www.fibsudan.com/',
      'info@fibsudan.com',
      '',
      '',
      'https://www.linkedin.com/company/faisal-islamic-bank-sudan/',
      '',
      'FIBSSDKH',
      '',
    ),
  ],
  SY: [
    bank(
      'Commercial Bank of Syria',
      '+963 11 2210400',
      'Sabaa Bahrat Square, Damascus, Syria',
      '',
      '',
      'https://www.cbs-bank.sy',
      'info@cbs-bank.sy',
      '',
      '',
      '',
      '',
      'CBSYSYDA',
      '',
    ),
    bank(
      'Banque Bemo Saudi Fransi',
      '+963 11 3391000',
      'Al-Malki, Damascus, Syria',
      '',
      '',
      'https://www.bbsfbank.com',
      'info@bbsfbank.com',
      '',
      '',
      '',
      '',
      'BBSFSYDA',
      '',
    ),
    bank(
      'Bank of Syria and Overseas',
      '+963 11 3391666',
      'Youssef Al-Azmeh Square, Damascus, Syria',
      '',
      '',
      'https://www.bso-sy.com',
      'info@bso-sy.com',
      '',
      '',
      '',
      '',
      'BSYOSYDA',
      '',
    ),
  ],
  TN: [
    bank(
      'Banque Internationale Arabe de Tunisie (BIAT)',
      '+216 71 155 000',
      '70-72 Avenue Habib Bourguiba, Tunis, Tunisia',
      '',
      '',
      'https://www.biat.com.tn/',
      'contact@biat.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/biat/',
      '',
      'BIATTNTT',
      '',
    ),
    bank(
      'Amen Bank',
      '+216 71 148 000',
      'Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.amenbank.com.tn/',
      'relationclientele@amenbank.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/amen-bank/',
      '',
      'CFCTTNTT',
      '',
    ),
    bank(
      'BH Bank',
      '+216 71 126 000',
      '18 Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.bhbank.tn/',
      'contact@bhbank.tn',
      '',
      '',
      'https://www.linkedin.com/company/bh-bank/',
      '',
      'BHBKTNTT',
      '',
    ),
  ],
  AE: [
    bank(
      'First Abu Dhabi Bank',
      '+971 2 4996100',
      'Khalifa Business Park, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/fab-mobile/id1023351966',
      'https://play.google.com/store/apps/details?id=com.fab.personal',
      'https://www.bankfab.com',
      'customerservice@bankfab.com',
      'https://twitter.com/FABConnects',
      'https://www.instagram.com/fabconnects/',
      'https://www.linkedin.com/company/first-abu-dhabi-bank-fab/',
      '',
      'NBADAEAA',
      '',
    ),
    bank(
      'Emirates NBD',
      '+971 600540000',
      'Baniyas Road, Deira, Dubai, UAE',
      'https://apps.apple.com/ae/app/emirates-nbd/id455204322',
      'https://play.google.com/store/apps/details?id=com.emberg.mobilebanking',
      'https://www.emiratesnbd.com',
      'customercare@emiratesnbd.com',
      'https://twitter.com/EmiratesNBD_AE',
      'https://www.instagram.com/emiratesnbd/',
      'https://www.linkedin.com/company/emiratesnbd/',
      '',
      'EBILAEAD',
      '',
    ),
    bank(
      'Abu Dhabi Commercial Bank',
      '+971 2 6210090',
      'Sheikh Zayed Street, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/adcb-mobile-banking-app/id453927124',
      'https://play.google.com/store/apps/details?id=com.adcb.mobile.android',
      'https://www.adcb.com',
      'customer.care@adcb.com',
      'https://twitter.com/ADCB',
      'https://www.instagram.com/adcb/',
      'https://www.linkedin.com/company/adcb/',
      '',
      'ADCBAEAA',
      '',
    ),
  ],
  YE: [
    bank(
      'Yemen Kuwait Bank',
      '+967 1 274060',
      'Zubairi Street, Sanaa, Yemen',
      '',
      '',
      'https://www.yk-bank.com',
      'info@yk-bank.com',
      '',
      '',
      '',
      '',
      'YKBIYESA',
      '',
    ),
    bank(
      'Cooperative and Agricultural Credit Bank',
      '+967 1 407000',
      'Zubairi Street, Sanaa, Yemen',
      '',
      '',
      'https://www.cacbank.com.ye',
      'info@cacbank.com.ye',
      '',
      '',
      '',
      '',
      'CACBYESA',
      '',
    ),
    bank(
      'International Bank of Yemen',
      '+967 1 211700',
      'Algeria Street, Sanaa, Yemen',
      '',
      '',
      'https://www.ibyemen.com',
      'info@ibyemen.com',
      '',
      '',
      '',
      '',
      'IBYEMYEA',
      '',
    ),
  ],
}
