import type { NationalBankingInstitution } from './types'
import type { BricsMemberIsoCode } from './bricsMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per BRICS founding member.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const BRICS_NATIONAL_BANKING_INSTITUTIONS: Record<
  BricsMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  BR: [
    bank(
      'Banco do Brasil',
      '+55 61 3493 9010',
      'SAUN Quadra 5, Brasilia, Brazil',
      '',
      '',
      'https://www.bb.com.br',
      'sac@bb.com.br',
      '',
      '',
      '',
      '',
      'BRASBRRJ',
      '',
    ),
    bank(
      'Itau Unibanco',
      '+55 11 3003 3030',
      'Praca Alfredo Egydio de Souza Aranha 100, Sao Paulo, Brazil',
      '',
      '',
      'https://www.itau.com.br',
      'itau@itau-unibanco.com.br',
      '',
      '',
      '',
      '',
      'ITAUBRSP',
      '',
    ),
    bank(
      'Bradesco',
      '+55 11 3684 2525',
      'Cidade de Deus, Osasco, Sao Paulo, Brazil',
      '',
      '',
      'https://banco.bradesco',
      'atendimento@bradesco.com.br',
      '',
      '',
      '',
      '',
      'BBDEBRSPSPO',
      '',
    ),
  ],
  RU: [
    bank(
      'Sberbank',
      '+7 495 500 5550',
      '19 Vavilova Street, Moscow, Russia',
      'https://apps.apple.com/ru/app/sberbank-online/id492224193',
      'https://play.google.com/store/apps/details?id=ru.sberbankmobile',
      'https://www.sberbank.com',
      'media@sberbank.ru',
      'https://twitter.com/sberbank',
      'https://www.instagram.com/sberbank/',
      'https://www.linkedin.com/company/sberbank/',
      '',
      'SABRRUMM',
      '',
    ),
    bank(
      'VTB Bank',
      '+7 495 777 2424',
      '29 Bolshaya Morskaya Street, Saint Petersburg, Russia',
      'https://apps.apple.com/ru/app/vtb-online/id1366975900',
      'https://play.google.com/store/apps/details?id=ru.vtb24.mobilebanking.android',
      'https://www.vtb.ru',
      'info@vtb.ru',
      'https://twitter.com/vtb',
      '',
      'https://www.linkedin.com/company/vtb/',
      '',
      'VTBRRUMM',
      '',
    ),
    bank(
      'Gazprombank',
      '+7 495 913 7474',
      '63 Novocheremushkinskaya Street, Moscow, Russia',
      'https://apps.apple.com/ru/app/gazprombank/id1457312516',
      'https://play.google.com/store/apps/details?id=ru.gazprombank.mobile',
      'https://www.gazprombank.ru',
      'mailbox@gazprombank.ru',
      'https://twitter.com/gazprombank',
      '',
      'https://www.linkedin.com/company/gazprombank/',
      '',
      'GAZPRUMM',
      '',
    ),
  ],
  IN: [
    bank(
      'State Bank of India',
      '+91 22 2274 0841',
      'Madame Cama Road, Nariman Point, Mumbai, India',
      '',
      '',
      'https://sbi.co.in',
      'customercare@sbi.co.in',
      '',
      '',
      '',
      '',
      'SBININBB',
      '',
    ),
    bank(
      'HDFC Bank',
      '+91 22 6160 6161',
      'HDFC Bank House, Senapati Bapat Marg, Mumbai, India',
      '',
      '',
      'https://www.hdfcbank.com',
      'support@hdfcbank.com',
      '',
      '',
      '',
      '',
      'HDFCINBB',
      '',
    ),
    bank(
      'ICICI Bank',
      '+91 22 2653 1414',
      'Bandra Kurla Complex, Mumbai, India',
      '',
      '',
      'https://www.icicibank.com',
      'customer.care@icicibank.com',
      '',
      '',
      '',
      '',
      'ICICINBB',
      '',
    ),
  ],
  CN: [
    bank(
      'Industrial and Commercial Bank of China',
      '+86 10 6610 8610',
      '55 Fuxingmennei Avenue, Beijing, China',
      'https://apps.apple.com/cn/app/icbc/id363280271',
      'https://play.google.com/store/apps/details?id=com.icbc',
      'https://www.icbc.com.cn',
      'info@icbc.com.cn',
      '',
      '',
      'https://www.linkedin.com/company/icbc/',
      '',
      'ICBKCNBJ',
      '',
    ),
    bank(
      'Bank of China',
      '+86 10 6659 6688',
      '1 Fuxingmen Nei Dajie, Beijing, China',
      'https://apps.apple.com/cn/app/bank-of-china/id463862286',
      'https://play.google.com/store/apps/details?id=com.boc.bocsoft.mobilebanking',
      'https://www.boc.cn',
      'ir@bankofchina.com',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-china/',
      '',
      'BKCHCNBJ',
      '',
    ),
    bank(
      'China Construction Bank',
      '+86 10 6621 5566',
      '25 Finance Street, Xicheng District, Beijing, China',
      'https://apps.apple.com/cn/app/china-construction-bank/id391710657',
      'https://play.google.com/store/apps/details?id=com.ccb.mobile',
      'https://www.ccb.com',
      'ccbcc.zh@ccb.com',
      '',
      '',
      'https://www.linkedin.com/company/china-construction-bank/',
      '',
      'PCBCCNBJ',
      '',
    ),
  ],
  ZA: [
    bank(
      'Standard Bank South Africa',
      '+27 11 636 9111',
      '5 Simmonds Street, Johannesburg, South Africa',
      '',
      '',
      'https://www.standardbank.co.za/',
      'information@standardbank.co.za',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBZAZAJJ',
      '',
    ),
    bank(
      'First National Bank South Africa',
      '+27 87 575 9404',
      '1 First Place, Bank City, Johannesburg, South Africa',
      '',
      '',
      'https://www.fnb.co.za/',
      'fnbcustomercare@fnb.co.za',
      '',
      '',
      'https://www.linkedin.com/company/fnb-south-africa/',
      '',
      'FIRNZAJJ',
      '',
    ),
    bank(
      'Absa Bank South Africa',
      '+27 11 350 4000',
      '7th Floor, Absa Towers West, Johannesburg, South Africa',
      '',
      '',
      'https://www.absa.co.za/',
      'absa@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'ABSAZAJJ',
      '',
    ),
  ],
}
