import type { CorporationFormationOffice } from './types'
import type { SadcMemberIsoCode } from './sadcMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per SADC member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const SADC_CORPORATION_FORMATION_OFFICES: Record<SadcMemberIsoCode, CorporationFormationOffice> = {
  AO:   office(
    'Guiche Unico da Empresa (GUE) Angola',
    '+244 222 331 251',
    'Largo da Maianga, Edificio One Metropolis, Luanda, Angola',
    'https://gue.gov.ao',
    'geral@gue.gov.ao',
    '',
    '',
    '',
    'https://gue.gov.ao/ao/servicos/criacao-de-empresas',
    'https://gue.gov.ao/ao/servicos/requisitos',
    'Numero de Identificacao de Pessoa Coletiva (NIF)',
  ),
  BW:   office(
    'Companies and Intellectual Property Authority (CIPA)',
    '+267 367 3700',
    'Plot 50676, Fairgrounds Office Park, Gaborone, Botswana',
    'https://www.cipa.co.bw',
    'info@cipa.co.bw',
    'https://x.com/CIPA_Botswana',
    '',
    'https://www.linkedin.com/company/cipa-botswana/',
    'https://www.cipa.co.bw/register-a-company',
    'https://www.cipa.co.bw/company-registration-checklist',
    'Company Registration Number',
  ),
  KM:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Comores)',
    '+269 773 08 08',
    'Avenue de l\'OUA, Moroni, Comoros',
    'https://www.anpi-comores.km',
    'contact@anpi-comores.km',
    '',
    '',
    '',
    'https://www.anpi-comores.km/guichet-unique',
    'https://www.anpi-comores.km/guide-createur',
    'Numero RCCM',
  ),
  CD:   office(
    'Guichet Unique de Creation d\'Entreprise (GUCE DRC)',
    '+243 81 555 7000',
    'Immeuble Fickin, Boulevard du 30 Juin, Gombe, Kinshasa, DR Congo',
    'https://guichetunique.cd',
    'contact@guichetunique.cd',
    '',
    '',
    '',
    'https://guichetunique.cd/creation-dentreprise',
    'https://guichetunique.cd/pieces-a-fournir',
    'Numero RCCM',
  ),
  SZ:   office(
    'Eswatini Companies Office (Ministry of Commerce, Industry and Trade)',
    '+268 2404 3200',
    'Lilunga House, Somhlolo Road, Mbabane, Eswatini',
    'https://www.gov.sz/index.php/business/companies-office',
    'companiesoffice@gov.sz',
    '',
    '',
    '',
    'https://www.gov.sz/index.php/business/companies-office',
    'https://www.gov.sz/index.php/business/forms',
    'Company Registration Number',
  ),
  LS:   office(
    'One Stop Business Facilitation Centre (OBFC Lesotho)',
    '+266 22 312 100',
    'Bedco House, Kingsway Road, Maseru, Lesotho',
    'https://www.obfc.org.ls',
    'info@obfc.org.ls',
    '',
    '',
    '',
    'https://www.obfc.org.ls/company-registration',
    'https://www.obfc.org.ls/checklists',
    'Company Registration Number',
  ),
  MG:   office(
    'Economic Development Board of Madagascar (EDBM) - One Stop Shop',
    '+261 20 22 670 40',
    'Immeuble EDBM, Antaninarenina, Antananarivo, Madagascar',
    'https://edbm.mg',
    'contact@edbm.mg',
    '',
    '',
    'https://www.linkedin.com/company/edbm/',
    'https://edbm.mg/creation-dentreprise',
    'https://edbm.mg/guide-pratique',
    'Numero RCCM',
  ),
  MW:   office(
    'Registrar General Department Malawi',
    '+265 1 770 155',
    'Glyn Jones Road, Ginnery Corner, Blantyre, Malawi',
    'https://www.registrargeneral.gov.mw',
    'registrargeneral@justice.gov.mw',
    '',
    '',
    '',
    'https://www.registrargeneral.gov.mw/company-registration',
    'https://www.registrargeneral.gov.mw/forms-and-fees',
    'Certificate of Incorporation Number',
  ),
  MU:   office(
    'Corporate and Business Registration Department (CBRD Mauritius)',
    '+230 202 0600',
    '7th Floor, SICOM Tower, Wall Street, Ebene, Mauritius',
    'https://companies.govmu.org',
    'companies.registry@govmu.org',
    '',
    '',
    '',
    'https://companies.govmu.org/Pages/Corporate%20and%20Business/Company-Registration.aspx',
    'https://companies.govmu.org/Pages/Guidelines.aspx',
    'Business Registration Number (BRN)',
  ),
  MZ:   office(
    'Conservatoria do Registo das Entidades Legais (CREL Mozambique)',
    '+258 21 327 800',
    'Av. Vladimir Lenine 265, Maputo, Mozambique',
    'https://www.mjcr.gov.mz',
    'atendimento@mjcr.gov.mz',
    '',
    '',
    '',
    'https://www.mjcr.gov.mz/servicos/registo-comercial',
    'https://www.mjcr.gov.mz/servicos/requisitos',
    'Numero de Registo Comercial (NUEL)',
  ),
  NA:   office(
    'Business and Intellectual Property Authority (BIPA Namibia)',
    '+264 61 299 4400',
    '55 Robert Mugabe Avenue, Windhoek, Namibia',
    'https://www.bipa.na',
    'info@bipa.na',
    'https://x.com/BIPA_NA',
    '',
    'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
    'https://www.bipa.na/company-registration',
    'https://www.bipa.na/checklists-and-forms',
    'Company Registration Number',
  ),
  SC:   office(
    'Seychelles Revenue Commission - Registrar General Division',
    '+248 4 282 800',
    'Maison Collet, Francis Rachel Street, Victoria, Seychelles',
    'https://www.src.gov.sc',
    'registrargeneral@src.gov.sc',
    '',
    '',
    '',
    'https://www.src.gov.sc/services/business-registration',
    'https://www.src.gov.sc/checklists-and-forms',
    'Company Registration Number',
  ),
  ZA:   office(
    'Companies and Intellectual Property Commission (CIPC South Africa)',
    '+27 86 100 2472',
    'the dti Campus, 77 Meintjies Street, Sunnyside, Pretoria, South Africa',
    'https://www.cipc.co.za',
    'info@cipc.co.za',
    'https://x.com/theCIPC',
    '',
    'https://www.linkedin.com/company/cipc/',
    'https://www.cipc.co.za/?page_id=3781',
    'https://www.cipc.co.za/?page_id=3791',
    'Enterprise Number',
  ),
  TZ:   office(
    'Business Registrations and Licensing Agency (BRELA Tanzania)',
    '+255 22 221 0113',
    'BRELA House, Shaaban Robert Street, Dar es Salaam, Tanzania',
    'https://www.brela.go.tz',
    'info@brela.go.tz',
    'https://x.com/BrelaTanzania',
    '',
    'https://www.linkedin.com/company/brela/',
    'https://ors.brela.go.tz',
    'https://www.brela.go.tz/index.php/business-registration',
    'Company Registration Number',
  ),
  ZM:   office(
    'Patents and Companies Registration Agency (PACRA Zambia)',
    '+260 211 255 127',
    'PACRA Building, Haile Selassie Avenue, Lusaka, Zambia',
    'https://www.pacra.org.zm',
    'info@pacra.org.zm',
    'https://x.com/PacraZm',
    '',
    'https://www.linkedin.com/company/pacra-zambia/',
    'https://portal.pacra.org.zm',
    'https://www.pacra.org.zm/checklists',
    'Company Registration Number',
  ),
  ZW:   office(
    'Deeds, Companies and Intellectual Property Office (DCIP Zimbabwe)',
    '+263 242 794 571',
    '4th Floor, Century House, Corner Nelson Mandela Ave and Angwa St, Harare, Zimbabwe',
    'https://dcip.gov.zw',
    'info@dcip.gov.zw',
    '',
    '',
    '',
    'https://dcip.gov.zw/company-registration',
    'https://dcip.gov.zw/requirements',
    'Company Registration Number',
  ),
}
