import type { SadcMemberIsoCode } from './sadcMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per SADC member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const SADC_DOMESTIC_POST_SERVICES: Record<SadcMemberIsoCode, DomesticPostService> = {
  AO: post(
    'CTT Angola (Empresa Nacional de Correios)',
    'https://www.ctt.ao/',
    'geral@ctt.ao',
    'https://x.com/cttangola',
    'https://www.instagram.com/correiosdeangola/',
    'https://www.linkedin.com/company/correios-de-angola/',
    '',
    'none',
    '',
    '',
    'No national structured postcode; descriptive street addressing and P.O. Box common',
  ),
  BW: post(
    'BotswanaPost',
    'https://www.botspost.co.bw/',
    'customercare@botspost.co.bw',
    'https://x.com/BotswanaPost',
    'https://www.instagram.com/botswanapost/',
    'https://www.linkedin.com/company/botswanapost/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00000',
    'Five-digit national postcode (verify district mapping locally)',
  ),
  KM: post(
    'Comores Poste',
    'https://poste-comores.com/',
    'contact@poste-comores.km',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and village addressing',
  ),
  CD: post(
    'SCPT RDC (Services postaux)',
    'https://scpt.cd/',
    'info@postesrdc.cd',
    '',
    '',
    'https://www.linkedin.com/company/scpt-rdc/',
    '',
    'none',
    '',
    '',
    'No universal national postcode; commune and P.O. Box',
  ),
  SZ: post(
    'Eswatini Posts & Telecommunications Corporation',
    'https://www.eswatinipost.co.sz/',
    'info@post.co.sz',
    '',
    '',
    'https://www.linkedin.com/company/eswatini-posts-telecommunications/',
    '',
    'ANNN',
    '^[A-Z]\\\\d{3}$',
    'H100',
    'Letter + three digits (H = Hhohho region prefix)',
  ),
  LS: post(
    'Lesotho Postal Services',
    'https://lesothopost.org.ls/',
    'info@post.org.ls',
    '',
    '',
    'https://www.linkedin.com/company/lesotho-postal-services/',
    '',
    'NNN',
    '^\\\\d{3}$',
    '100',
    'Three-digit postcode',
  ),
  MG: post(
    'Paositra Malagasy',
    'http://www.poste.mg/',
    'contact@paositra.mg',
    'https://x.com/Paositra',
    'https://www.instagram.com/paositramalagasy/',
    'https://www.linkedin.com/company/paositra-malagasy/',
    '',
    'NNN',
    '^\\\\d{3}$',
    '101',
    'Three-digit postcode',
  ),
  MW: post(
    'Malawi Posts Corporation',
    'https://malawipost.gov.mw/',
    'info@malawipost.gov.mw',
    '',
    '',
    'https://www.linkedin.com/company/malawi-posts-corporation/',
    '',
    'none',
    '',
    '',
    'No national postcode; district and P.O. Box',
  ),
  MU: post(
    'Mauritius Post Ltd',
    'https://www.mauritiuspost.mu/',
    'info@mpl.mu',
    '',
    '',
    'https://www.linkedin.com/company/mauritius-post-ltd/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '42602',
    'Five-digit postcode (optional letter suffix in some datasets)',
  ),
  MZ: post(
    'Correios de Moçambique',
    'http://correios.co.mz/',
    'cac@correios.co.mz',
    '',
    '',
    'https://www.linkedin.com/company/correios-de-mocambique/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1100',
    'Four-digit postcode',
  ),
  NA: post(
    'NamPost',
    'https://nampost.na/',
    'customerservice@namibiapost.na',
    '',
    '',
    'https://www.linkedin.com/company/nampost/',
    '',
    'none',
    '',
    '',
    'Private bag / P.O. Box numbering; no universal street postcode',
  ),
  SC: post(
    'Seychelles Postal Services',
    'https://www.seychelles-post.com/',
    'info@sib.gov.sc',
    '',
    '',
    'https://www.linkedin.com/company/seychelles-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; island and district addressing',
  ),
  ZA: post(
    'South African Post Office',
    'http://www.postoffice.co.za/',
    'custserv@postoffice.co.za',
    'https://x.com/PostofficeSa',
    'https://www.instagram.com/sapostoffice/',
    'https://www.linkedin.com/company/south-african-post-office/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '2000',
    'Four-digit postcode (street delivery and P.O. Box)',
  ),
  TZ: post(
    'Tanzania Posts Corporation',
    'https://posta.co.tz/',
    'info@tpoc.co.tz',
    '',
    '',
    'https://www.linkedin.com/company/tanzania-posts-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '11101',
    'Five-digit postcode',
  ),
  ZM: post(
    'Zambia Postal Services Corporation',
    'http://www.zampost.gov.zm/',
    'info.zampost@gmail.com',
    '',
    '',
    'https://www.linkedin.com/company/zambia-postal-services-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '10101',
    'Five-digit postcode',
  ),
  ZW: post(
    'Zimpost',
    'http://www.zimpost.co.zw/',
    'zimpost@zimpost.co.zw',
    'https://x.com/zimpost_',
    'https://www.instagram.com/zimpost_/',
    'https://www.linkedin.com/company/zimpost/',
    '',
    'none',
    '',
    '',
    'No national postcode; suburb and P.O. Box routing',
  ),
}
