import type { SadcMemberIsoCode } from './sadcMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

const OAPI_TRADEMARKS = ip(
  'trademarks',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

const OAPI_PATENTS = ip(
  'patents',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

function oapiMember(copyright: IntellectualPropertyDepartment): IntellectualPropertyDepartmentsRoster {
  return roster(copyright, OAPI_TRADEMARKS, OAPI_PATENTS)
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for Southern African Development
 * Community (SADC) members in this module (informational; verify URLs, handles, forms portals,
 * and API bases before production use). Self-contained — no imports from other alliance modules.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const SADC_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  SadcMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AO: roster(
    ip(
      'copyright',
      'Instituto Angolano da Propriedade Intelectual (IAPI) — copyright',
      'https://www.iapi.gov.ao',
      'geral@iapi.gov.ao',
      '',
      '',
      'https://www.iapi.gov.ao',
    ),
    ip(
      'trademarks',
      'Instituto Angolano da Propriedade Intelectual (IAPI)',
      'https://www.iapi.gov.ao',
      'geral@iapi.gov.ao',
      '',
      '',
      'https://www.iapi.gov.ao',
    ),
    ip(
      'patents',
      'Instituto Angolano da Propriedade Intelectual (IAPI)',
      'https://www.iapi.gov.ao',
      'geral@iapi.gov.ao',
      '',
      '',
      'https://www.iapi.gov.ao',
    ),
  ),
  BW: roster(
    ip(
      'copyright',
      'Copyright Society of Botswana (COSBOTS)',
      'https://www.cosbots.org.bw',
      'info@cosbots.org.bw',
      '',
      'https://www.linkedin.com/company/cosbots/',
      'https://www.cosbots.org.bw',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Authority (CIPA)',
      'https://www.cipa.co.bw',
      'info@cipa.co.bw',
      'https://x.com/CIPABotswana',
      'https://www.linkedin.com/company/cipa-botswana/',
      'https://www.cipa.co.bw',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Authority (CIPA)',
      'https://www.cipa.co.bw',
      'info@cipa.co.bw',
      'https://x.com/CIPABotswana',
      'https://www.linkedin.com/company/cipa-botswana/',
      'https://www.cipa.co.bw',
    ),
  ),
  KM: oapiMember(
    ip(
      'copyright',
      'Centre Comorien du Droit d\'Auteur et des Droits Voisins',
      'https://www.beit-salam.km',
      '',
      '',
      '',
      'https://www.beit-salam.km',
    ),
  ),
  CD: roster(
    ip(
      'copyright',
      'Office Congolais des Droits d\'Auteur (OCADA)',
      'https://www.ocada.cd',
      '',
      '',
      '',
      'https://www.ocada.cd',
    ),
    ip(
      'trademarks',
      'Office Congolais de la Propriété Intellectuelle (OCPI)',
      'https://www.ocpi.cd',
      'info@ocpi.cd',
      '',
      '',
      'https://www.ocpi.cd',
    ),
    ip(
      'patents',
      'Office Congolais de la Propriété Intellectuelle (OCPI)',
      'https://www.ocpi.cd',
      'info@ocpi.cd',
      '',
      '',
      'https://www.ocpi.cd',
    ),
  ),
  SZ: roster(
    ip(
      'copyright',
      'Copyright Society of Eswatini (COSOES)',
      'https://www.cosoes.org.sz',
      '',
      '',
      '',
      'https://www.cosoes.org.sz',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
  ),
  LS: roster(
    ip(
      'copyright',
      'Copyright Society of Lesotho (COSOLE)',
      'https://www.cosole.org.ls',
      '',
      '',
      '',
      'https://www.cosole.org.ls',
    ),
    ip(
      'trademarks',
      'Registrar General — Industrial Property (Lesotho)',
      'https://www.gov.ls',
      '',
      '',
      '',
      'https://www.gov.ls',
    ),
    ip(
      'patents',
      'Registrar General — Industrial Property (Lesotho)',
      'https://www.gov.ls',
      '',
      '',
      '',
      'https://www.gov.ls',
    ),
  ),
  MG: roster(
    ip(
      'copyright',
      'Office Malgache des Droits d\'Auteur (OMDA)',
      'https://www.omda.mg',
      '',
      '',
      '',
      'https://www.omda.mg',
    ),
    ip(
      'trademarks',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
    ip(
      'patents',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
  ),
  MW: roster(
    ip(
      'copyright',
      'Copyright Society of Malawi (COSOMA)',
      'https://www.cosoma.mw',
      'info@cosoma.mw',
      '',
      '',
      'https://www.cosoma.mw',
    ),
    ip(
      'trademarks',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
    ip(
      'patents',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
  ),
  MU: roster(
    ip(
      'copyright',
      'Mauritius Society of Authors (MASA)',
      'https://www.masa.mu',
      'info@masa.mu',
      '',
      '',
      'https://www.masa.mu',
    ),
    ip(
      'trademarks',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
    ip(
      'patents',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
  ),
  MZ: roster(
    ip(
      'copyright',
      'Instituto Nacional da Propriedade Intelectual (IPI) — copyright',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'trademarks',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'patents',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
  ),
  NA: roster(
    ip(
      'copyright',
      'Namibian Society for Composers and Authors of Music (NAMCOS)',
      'https://www.namcos.org.na',
      'info@namcos.org.na',
      '',
      '',
      'https://www.namcos.org.na',
    ),
    ip(
      'trademarks',
      'Business and Intellectual Property Authority (BIPA)',
      'https://www.bipa.na',
      'info@bipa.na',
      '',
      'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
      'https://www.bipa.na',
    ),
    ip(
      'patents',
      'Business and Intellectual Property Authority (BIPA)',
      'https://www.bipa.na',
      'info@bipa.na',
      '',
      'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
      'https://www.bipa.na',
    ),
  ),
  SC: roster(
    ip(
      'copyright',
      'Seychelles Copyright Office (Ministry of Finance, National Planning and Trade)',
      'https://www.finance.gov.sc',
      '',
      '',
      '',
      'https://www.finance.gov.sc',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
    ip(
      'patents',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
  ),
  ZA: roster(
    ip(
      'copyright',
      'Companies and Intellectual Property Commission (CIPC) — Copyright Tribunal liaison',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
  ),
  TZ: roster(
    ip(
      'copyright',
      'Copyright Society of Tanzania (COSOTA)',
      'https://www.cosota.go.tz',
      'info@cosota.go.tz',
      '',
      '',
      'https://www.cosota.go.tz',
    ),
    ip(
      'trademarks',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
    ip(
      'patents',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
  ),
  ZM: roster(
    ip(
      'copyright',
      'Copyright Society of Zambia (COSOZA)',
      'https://www.cosoza.org.zm',
      'info@cosoza.org.zm',
      '',
      '',
      'https://www.cosoza.org.zm',
    ),
    ip(
      'trademarks',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
    ip(
      'patents',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
  ),
  ZW: roster(
    ip(
      'copyright',
      'Zimbabwe Intellectual Property Office (ZIPO) — copyright',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
    ip(
      'trademarks',
      'Zimbabwe Intellectual Property Office (ZIPO)',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
    ip(
      'patents',
      'Zimbabwe Intellectual Property Office (ZIPO)',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
  ),
}
