import type { SadcMemberIsoCode } from './sadcMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const SADC_MAIN_EXPORT_COMMODITIES: Record<SadcMemberIsoCode, MainExportCommodities> = {
  AO: m(
    'Crude petroleum',
    'Diamonds',
    'Refined petroleum',
    'Petroleum gas',
    'Iron ore',
    'Coffee',
    'Fish',
  ),
  BW: m(
    'Diamonds',
    'Copper-nickel',
    'Beef',
    'Soda ash',
    'Textiles',
    'Vehicles',
    'Gold',
  ),
  KM: m(
    'Vanilla',
    'Cloves',
    'Ylang-ylang',
    'Fish',
    'Vegetables',
    'Copra',
    'Tourism services',
  ),
  CD: m(
    'Refined copper',
    'Cobalt',
    'Crude petroleum',
    'Diamonds',
    'Gold',
    'Coltan',
    'Coffee',
  ),
  SZ: m(
    'Sugar',
    'Soft drink concentrates',
    'Wood pulp',
    'Refrigerators',
    'Edible fruits',
    'Cotton yarn',
    'Textiles',
  ),
  LS: m(
    'Garments',
    'Diamonds',
    'Wool',
    'Mohair',
    'Footwear',
    'Vehicles',
    'Electricity',
  ),
  MG: m(
    'Vanilla',
    'Nickel',
    'Cobalt',
    'Cloves',
    'Knitted garments',
    'Titanium ores',
    'Shrimp',
  ),
  MW: m(
    'Tobacco',
    'Tea',
    'Sugar',
    'Coffee',
    'Cotton',
    'Peanuts',
    'Pulses',
  ),
  MU: m(
    'Sugar',
    'Textiles',
    'Garments',
    'Fish',
    'Tuna',
    'Cut flowers',
    'Tourism services',
  ),
  MZ: m(
    'Aluminium',
    'Coal',
    'Natural gas',
    'Electricity',
    'Heavy sands',
    'Tobacco',
    'Prawns',
  ),
  NA: m(
    'Diamonds',
    'Uranium',
    'Gold',
    'Copper',
    'Fish',
    'Zinc',
    'Beef',
  ),
  SC: m(
    'Fish',
    'Canned tuna',
    'Petroleum products',
    'Vanilla',
    'Cinnamon',
    'Copra',
    'Tourism services',
  ),
  ZA: m(
    'Gold',
    'Platinum',
    'Coal',
    'Iron ore',
    'Diamonds',
    'Automobiles',
    'Manganese ore',
  ),
  TZ: m(
    'Gold',
    'Cashew nuts',
    'Tobacco',
    'Cotton',
    'Coffee',
    'Tea',
    'Sisal',
  ),
  ZM: m(
    'Refined copper',
    'Copper ore',
    'Cobalt',
    'Maize',
    'Sugar',
    'Tobacco',
    'Electricity',
  ),
  ZW: m(
    'Gold',
    'Tobacco',
    'Ferroalloys',
    'Nickel',
    'Platinum',
    'Diamonds',
    'Cotton',
  ),
}
