import type { SadcMemberIsoCode } from './sadcMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per SADC member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const SADC_MAIN_INTERNATIONAL_SEAPORTS: Record<SadcMemberIsoCode, MainInternationalSeaport> = {
  AO: seaport(
    'Port of Luanda',
    'https://www.otal.com/angola/port-of-luanda',
    'info@portosdeangola.co.ao',
    'https://x.com/PortosAngola',
    'https://www.instagram.com/portosdeangola/',
    'https://www.linkedin.com/company/portos-de-angola/',
    'aduaneira@minfin.gov.ao',
    'https://www.minfin.gov.ao',
    'Customs Post — Port of Luanda, Luanda, Angola',
  ),
  BW: seaport(
    'Port of Walvis Bay (primary maritime gateway; landlocked)',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'info@botswanacustoms.gov.bw',
    'https://www.botswanacustoms.gov.bw',
    'Botswana Unified Revenue Service — Gaborone, Botswana',
  ),
  KM: seaport(
    'Port of Moroni',
    'https://www.portcomores.km/',
    'info@portcomores.km',
    'https://x.com/PortComores',
    'https://www.instagram.com/portcomores/',
    'https://www.linkedin.com/company/port-autonome-des-comores/',
    'douanes@finances.km',
    'https://www.douanes.km',
    'Direction des Douanes — Port de Moroni, Moroni, Comoros',
  ),
  CD: seaport(
    'Port of Matadi',
    'https://www.opdrdc.cd/',
    'contact@opdrdc.cd',
    'https://x.com/OPDRDC',
    'https://www.instagram.com/opdrdc/',
    'https://www.linkedin.com/company/office-des-ports-et-voies-fluviales-rdc/',
    'douanes@dgda.cd',
    'https://www.douanesrdc.cd',
    'Direction Générale des Douanes et Accises — Port de Matadi, Matadi, DRC',
  ),
  SZ: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@sra.org.sz',
    'https://www.sra.org.sz',
    'Eswatini Revenue Service — Mbabane, Eswatini',
  ),
  LS: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@lra.org.ls',
    'https://www.lra.org.ls',
    'Lesotho Revenue Authority — Customs Division, Maseru, Lesotho',
  ),
  MG: seaport(
    'Port of Toamasina',
    'https://www.otal.com/madagascar/port-of-toamasina',
    'contact@port-toamasina.mg',
    'https://x.com/PortToamasina',
    'https://www.instagram.com/porttoamasina/',
    'https://www.linkedin.com/company/port-de-toamasina/',
    'douanes@douanes.gov.mg',
    'https://www.douanes.gov.mg',
    'Direction Générale des Douanes — Port de Toamasina, Toamasina, Madagascar',
  ),
  MW: seaport(
    'Port of Nacala (primary maritime gateway; landlocked)',
    'https://www.otal.com/mozambique/port-of-nacala',
    'info@cdi.mw',
    'https://x.com/CDI_Malawi',
    'https://www.instagram.com/cdi_malawi/',
    'https://www.linkedin.com/company/corridor-development-initiative/',
    'customs@mra.mw',
    'https://www.mra.mw',
    'Malawi Revenue Authority — Customs Division, Blantyre, Malawi',
  ),
  MU: seaport(
    'Port Louis',
    'https://www.mpa.mu/',
    'info@mpa.mu',
    'https://x.com/MPA_Mauritius',
    'https://www.instagram.com/mpa_mauritius/',
    'https://www.linkedin.com/company/mauritius-ports-authority/',
    'customs@mra.mu',
    'https://www.mra.mu',
    'Mauritius Revenue Authority — Customs, Port Louis, Mauritius',
  ),
  MZ: seaport(
    'Port of Maputo',
    'https://www.portmaputo.com/',
    'info@portmaputo.com',
    'https://x.com/PortMaputo',
    'https://www.instagram.com/portmaputo/',
    'https://www.linkedin.com/company/porto-de-maputo/',
    'aduaneira@at.gov.mz',
    'https://www.at.gov.mz',
    'Autoridade Tributária de Moçambique — Alfândega do Porto de Maputo, Maputo, Mozambique',
  ),
  NA: seaport(
    'Port of Walvis Bay',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'customs@namra.org.na',
    'https://www.namra.org.na',
    'Namibia Revenue Agency — Customs, Port of Walvis Bay, Walvis Bay, Namibia',
  ),
  SC: seaport(
    'Port Victoria',
    'https://www.spa.sc/',
    'info@spa.sc',
    'https://x.com/SPA_Seychelles',
    'https://www.instagram.com/spa_seychelles/',
    'https://www.linkedin.com/company/seychelles-ports-authority/',
    'customs@src.gov.sc',
    'https://www.src.gov.sc',
    'Seychelles Revenue Commission — Customs, Port Victoria, Mahé, Seychelles',
  ),
  ZA: seaport(
    'Port of Durban',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'customs@sars.gov.za',
    'https://www.sars.gov.za',
    'South African Revenue Service — Customs, Port of Durban, Durban, South Africa',
  ),
  TZ: seaport(
    'Port of Dar es Salaam',
    'https://www.tanzaniaports.com/',
    'info@tanzaniaports.com',
    'https://x.com/TanzaniaPorts',
    'https://www.instagram.com/tanzaniaports/',
    'https://www.linkedin.com/company/tanzania-ports-authority/',
    'customs@tra.go.tz',
    'https://www.tra.go.tz',
    'Tanzania Revenue Authority — Customs, Port of Dar es Salaam, Dar es Salaam, Tanzania',
  ),
  ZM: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@zra.org.zm',
    'https://www.zra.org.zm',
    'Zambia Revenue Authority — Customs Division, Lusaka, Zambia',
  ),
  ZW: seaport(
    'Port of Beira (primary maritime gateway; landlocked)',
    'https://www.otal.com/mozambique/port-of-beira',
    'info@cdm.co.mz',
    'https://x.com/CDM_Mozambique',
    'https://www.instagram.com/cdm_mozambique/',
    'https://www.linkedin.com/company/cfm-mozambique/',
    'info@zimra.co.zw',
    'https://www.zimra.co.zw',
    'Zimbabwe Revenue Authority — Customs Division, Harare, Zimbabwe',
  ),
}
