import type { SadcMemberIsoCode } from './sadcMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const SADC_MAIN_INTERNATIONAL_AIRPORTS: Record<SadcMemberIsoCode, MainInternationalAirport> = {
  AO: {
    name: 'Quatro de Fevereiro International Airport (LAD)',
    website: 'https://www.aeroportosdeangola.co.ao/',
    email: 'info@aeroportosdeangola.co.ao',
    twitter: 'https://x.com/AngolaAirports',
    instagram: 'https://www.instagram.com/angolaairports/',
    linkedin: 'https://www.linkedin.com/company/angola-airports/',
    apiEndpoint: '',
  },
  BW: {
    name: 'Sir Seretse Khama International Airport (GBE)',
    website: 'https://www.caab.co.bw/',
    email: 'info@caab.co.bw',
    twitter: 'https://x.com/CAAB_Botswana',
    instagram: 'https://www.instagram.com/caab_botswana/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-botswana/',
    apiEndpoint: '',
  },
  KM: {
    name: 'Prince Said Ibrahim International Airport (HAH)',
    website: 'https://www.aeroport-comores.km/',
    email: 'info@aeroport-comores.km',
    twitter: 'https://x.com/AeroportHAH',
    instagram: 'https://www.instagram.com/aeroportcomores/',
    linkedin: 'https://www.linkedin.com/company/aeroport-prince-said-ibrahim/',
    apiEndpoint: '',
  },
  CD: {
    name: 'N\'djili International Airport (FIH)',
    website: 'https://www.rva-rdc.cd/',
    email: 'contact@rva-rdc.cd',
    twitter: 'https://x.com/RVA_RDC',
    instagram: 'https://www.instagram.com/rva_rdc/',
    linkedin: 'https://www.linkedin.com/company/regie-des-voies-aeriennes-rva/',
    apiEndpoint: '',
  },
  SZ: {
    name: 'King Mswati III International Airport (SHO)',
    website: 'https://www.eswacaa.co.sz/',
    email: 'info@eswacaa.co.sz',
    twitter: 'https://x.com/Eswacaa',
    instagram: 'https://www.instagram.com/eswacaa/',
    linkedin: 'https://www.linkedin.com/company/eswacaa/',
    apiEndpoint: '',
  },
  LS: {
    name: 'Moshoeshoe I International Airport (MSU)',
    website: 'https://www.lac.org.ls/',
    email: 'info@lac.org.ls',
    twitter: 'https://x.com/LAC_Lesotho',
    instagram: 'https://www.instagram.com/lac_lesotho/',
    linkedin: 'https://www.linkedin.com/company/lesotho-airports-authority/',
    apiEndpoint: '',
  },
  MG: {
    name: 'Ivato International Airport (TNR)',
    website: 'https://www.ravinala.mg/',
    email: 'contact@ravinala.mg',
    twitter: 'https://x.com/RavinalaAirports',
    instagram: 'https://www.instagram.com/ravinalaairports/',
    linkedin: 'https://www.linkedin.com/company/ravinala-airports/',
    apiEndpoint: '',
  },
  MW: {
    name: 'Kamuzu International Airport (LLW)',
    website: 'https://www.dca.gov.mw/',
    email: 'info@dca.gov.mw',
    twitter: 'https://x.com/DCA_Malawi',
    instagram: 'https://www.instagram.com/dca_malawi/',
    linkedin: 'https://www.linkedin.com/company/department-of-civil-aviation-malawi/',
    apiEndpoint: '',
  },
  MU: {
    name: 'Sir Seewoosagur Ramgoolam International Airport (MRU)',
    website: 'https://www.airports.mu/',
    email: 'info@airports.mu',
    twitter: 'https://x.com/AirportsMauritius',
    instagram: 'https://www.instagram.com/airportsmauritius/',
    linkedin: 'https://www.linkedin.com/company/airports-of-mauritius-co-ltd/',
    apiEndpoint: '',
  },
  MZ: {
    name: 'Maputo International Airport (MPM)',
    website: 'https://www.aeroportos.co.mz/',
    email: 'info@aeroportos.co.mz',
    twitter: 'https://x.com/AeroportosMZ',
    instagram: 'https://www.instagram.com/aeroportosmz/',
    linkedin: 'https://www.linkedin.com/company/aeroportos-de-mocambique/',
    apiEndpoint: '',
  },
  NA: {
    name: 'Hosea Kutako International Airport (WDH)',
    website: 'https://www.airports.com.na/',
    email: 'info@airports.com.na',
    twitter: 'https://x.com/AirportsNamibia',
    instagram: 'https://www.instagram.com/airportsnamibia/',
    linkedin: 'https://www.linkedin.com/company/namibia-airports-company/',
    apiEndpoint: '',
  },
  SC: {
    name: 'Seychelles International Airport (SEZ)',
    website: 'https://www.scaa.sc/',
    email: 'info@scaa.sc',
    twitter: 'https://x.com/SCAA_Seychelles',
    instagram: 'https://www.instagram.com/scaa_seychelles/',
    linkedin: 'https://www.linkedin.com/company/seychelles-civil-aviation-authority/',
    apiEndpoint: '',
  },
  ZA: {
    name: 'O.R. Tambo International Airport (JNB)',
    website: 'https://www.airports.co.za/',
    email: 'info@airports.co.za',
    twitter: 'https://x.com/Airports_ZA',
    instagram: 'https://www.instagram.com/airports_co_za/',
    linkedin: 'https://www.linkedin.com/company/airports-company-south-africa/',
    apiEndpoint: '',
  },
  TZ: {
    name: 'Julius Nyerere International Airport (DAR)',
    website: 'https://www.taa.go.tz/',
    email: 'info@taa.go.tz',
    twitter: 'https://x.com/TAA_Tanzania',
    instagram: 'https://www.instagram.com/taa_tanzania/',
    linkedin: 'https://www.linkedin.com/company/tanzania-airports-authority/',
    apiEndpoint: '',
  },
  ZM: {
    name: 'Kenneth Kaunda International Airport (LUN)',
    website: 'https://www.zacl.co.zm/',
    email: 'info@zacl.co.zm',
    twitter: 'https://x.com/ZACL_Airports',
    instagram: 'https://www.instagram.com/zacl_airports/',
    linkedin: 'https://www.linkedin.com/company/zambia-airports-corporation-limited/',
    apiEndpoint: '',
  },
  ZW: {
    name: 'Robert Gabriel Mugabe International Airport (HRE)',
    website: 'https://www.caaz.co.zw/',
    email: 'info@caaz.co.zw',
    twitter: 'https://x.com/CAAZ_Zimbabwe',
    instagram: 'https://www.instagram.com/caaz_zimbabwe/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-zimbabwe/',
    apiEndpoint: '',
  },
}
