import type { NationalBankingInstitution } from './types'
import type { SadcMemberIsoCode } from './sadcMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per SADC member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const SADC_NATIONAL_BANKING_INSTITUTIONS: Record<
  SadcMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AO: [
    bank(
      'Banco de Fomento Angola (BFA)',
      '+244 222 641 840',
      'Rua Amilcar Cabral 58, Luanda, Angola',
      '',
      '',
      'https://www.bfa.ao/',
      'cliente@bfa.ao',
      '',
      '',
      'https://www.linkedin.com/company/bfa-angola/',
      '',
      'BFAOAOLU',
      '',
    ),
    bank(
      'Banco BIC Angola',
      '+244 222 670 000',
      'Largo 17 de Setembro 3, Luanda, Angola',
      '',
      '',
      'https://www.bancobic.ao/',
      'apoio.cliente@bancobic.ao',
      '',
      '',
      'https://www.linkedin.com/company/banco-bic-angola/',
      '',
      'BICIAOLU',
      '',
    ),
    bank(
      'Banco Economico',
      '+244 226 420 000',
      'Rua 1. Congresso do MPLA 8, Luanda, Angola',
      '',
      '',
      'https://www.bancoeconomico.ao/',
      'contactcenter@bancoeconomico.ao',
      '',
      '',
      'https://www.linkedin.com/company/banco-econ%C3%B3mico-angola/',
      '',
      'BEBKAOLU',
      '',
    ),
  ],
  BW: [
    bank(
      'First National Bank Botswana',
      '+267 370 6000',
      'Plot 8843 Khama Crescent, Gaborone, Botswana',
      '',
      '',
      'https://www.fnbbotswana.co.bw/',
      'customer.service@fnbbotswana.co.bw',
      '',
      '',
      'https://www.linkedin.com/company/fnb-botswana/',
      '',
      'FIRNBWGX',
      '',
    ),
    bank(
      'Absa Bank Botswana',
      '+267 315 9575',
      'Absa House, Queens Road, Gaborone, Botswana',
      '',
      '',
      'https://www.absa.co.bw/',
      'absa.bw@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCBWGX',
      '',
    ),
    bank(
      'Stanbic Bank Botswana',
      '+267 398 7801',
      'Fairgrounds Office Park, Gaborone, Botswana',
      '',
      '',
      'https://www.stanbicbank.co.bw/',
      'contactcentre@stanbicbank.co.bw',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-botswana/',
      '',
      'SBICBWGX',
      '',
    ),
  ],
  KM: [
    bank(
      'Banque Federale de Commerce (BFC)',
      '+269 773 20 00',
      'Place de France, Moroni, Comoros',
      '',
      '',
      'https://www.bfc-comores.com/',
      'contact@bfc-comores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Exim Bank Comores',
      '+269 773 25 25',
      'Avenue de la Corniche, Moroni, Comoros',
      '',
      '',
      'https://www.eximbankcomores.com/',
      'info@eximbankcomores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'SNPSF',
      '+269 773 18 18',
      'Avenue Ali Soilih, Moroni, Comoros',
      '',
      '',
      'https://www.snpsf.com/',
      'contact@snpsf.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  CD: [
    bank(
      'Rawbank',
      '+243 99 601 1300',
      '3487 Boulevard du 30 Juin, Kinshasa, DR Congo',
      '',
      '',
      'https://www.rawbank.com/',
      'info@rawbank.com',
      'https://x.com/Rawbank',
      '',
      'https://www.linkedin.com/company/rawbank/',
      '',
      'RAWBCDKI',
      '',
    ),
    bank(
      'Equity BCDC',
      '+243 99 601 1301',
      '5 Avenue des Aviateurs, Kinshasa, DR Congo',
      '',
      '',
      'https://equitygroupholdings.com/cd/',
      'contact@equitygroupholdings.com',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-congo/',
      '',
      'BCDCCDKI',
      '',
    ),
    bank(
      'Ecobank DRC',
      '+243 81 555 7700',
      'Immeuble Ecobank, Gombe, Kinshasa, DR Congo',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/cd',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCCDKI',
      '',
    ),
  ],
  SZ: [
    bank(
      'Eswatini Bank',
      '+268 2404 1000',
      'Swazi Plaza, Mbabane, Eswatini',
      '',
      '',
      'https://www.eswatinibank.co.sz/',
      'info@eswatinibank.co.sz',
      '',
      '',
      'https://www.linkedin.com/company/eswatini-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Standard Bank Eswatini',
      '+268 2408 3000',
      'Swazi Trade House, Mbabane, Eswatini',
      '',
      '',
      'https://www.standardbank.co.sz/',
      'service@standardbank.co.sz',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBICSZMX',
      '',
    ),
    bank(
      'Nedbank Eswatini',
      '+268 2408 5600',
      'Nedbank Centre, Mbabane, Eswatini',
      '',
      '',
      'https://www.nedbank.co.sz/',
      'contact@nedbank.co.sz',
      '',
      '',
      'https://www.linkedin.com/company/nedbank/',
      '',
      'NEDSSZMX',
      '',
    ),
  ],
  LS: [
    bank(
      'Standard Lesotho Bank',
      '+266 2223 1234',
      'Kingsway Road, Maseru, Lesotho',
      '',
      '',
      'https://www.standardlesothobank.co.ls/',
      'customer.service@standardlesothobank.co.ls',
      '',
      '',
      'https://www.linkedin.com/company/standard-lesotho-bank/',
      '',
      'SBICLSMX',
      '',
    ),
    bank(
      'Nedbank Lesotho',
      '+266 2221 2555',
      'Kingsway Street, Maseru, Lesotho',
      '',
      '',
      'https://www.nedbank.co.ls/',
      'customerservice@nedbank.co.ls',
      '',
      '',
      'https://www.linkedin.com/company/nedbank/',
      '',
      'NEDSLSMX',
      '',
    ),
    bank(
      'First National Bank Lesotho',
      '+266 2224 1000',
      'Pioneer Mall, Maseru, Lesotho',
      '',
      '',
      'https://www.fnb.co.ls/',
      'fnbcustomercare@fnb.co.ls',
      '',
      '',
      'https://www.linkedin.com/company/fnb-lesotho/',
      '',
      'FIRNLSMX',
      '',
    ),
  ],
  MG: [
    bank(
      'BNI Madagascar',
      '+261 20 22 217 17',
      '74 Rue du 26 Juin 1960, Antananarivo, Madagascar',
      '',
      '',
      'https://www.bni.mg/',
      'contact@bni.mg',
      '',
      '',
      'https://www.linkedin.com/company/bni-madagascar/',
      '',
      'CLMADMGM',
      '',
    ),
    bank(
      'Bank of Africa Madagascar',
      '+261 20 22 206 06',
      'Immeuble BOA, Analakely, Antananarivo, Madagascar',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boamadagascar.com/',
      'contact@boamadagascar.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      'AFRIMGMG',
      '',
    ),
    bank(
      'BGFI Bank Madagascar',
      '+261 20 22 629 00',
      'Zone Galaxy, Andraharo, Antananarivo, Madagascar',
      '',
      '',
      'https://www.bgfibank.com/',
      'contact@bgfibank.com',
      '',
      '',
      'https://www.linkedin.com/company/bgfi-holding-corporation/',
      '',
      '',
      '',
    ),
  ],
  MW: [
    bank(
      'National Bank of Malawi',
      '+265 1 820 333',
      '7 Henderson Street, Blantyre, Malawi',
      '',
      '',
      'https://www.natbank.co.mw/',
      'customer.service@natbank.co.mw',
      '',
      '',
      'https://www.linkedin.com/company/national-bank-of-malawi/',
      '',
      'NBMAMWMW',
      '',
    ),
    bank(
      'FDH Bank',
      '+265 1 820 222',
      'FDH House, Glyn Jones Road, Blantyre, Malawi',
      '',
      '',
      'https://www.fdh.co.mw/',
      'customerservice@fdh.co.mw',
      '',
      '',
      'https://www.linkedin.com/company/fdh-bank-plc/',
      '',
      'FDHFMWMW',
      '',
    ),
    bank(
      'Standard Bank Malawi',
      '+265 1 820 944',
      'Kaomba Centre, Blantyre, Malawi',
      '',
      '',
      'https://www.standardbank.co.mw/',
      'malawi@standardbank.co.mw',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBICMWMX',
      '',
    ),
  ],
  MU: [
    bank(
      'The Mauritius Commercial Bank',
      '+230 202 5000',
      'Sir William Newton St, Port Louis, Mauritius',
      '',
      '',
      'https://www.mcb.mu/',
      'contact@mcb.mu',
      '',
      '',
      'https://www.linkedin.com/company/the-mauritius-commercial-bank-limited/',
      '',
      'MCBLMUMU',
      '',
    ),
    bank(
      'SBM Bank (Mauritius)',
      '+230 202 1111',
      '1 Queen Elizabeth II Avenue, Port Louis, Mauritius',
      '',
      '',
      'https://www.sbmgroup.mu/',
      'sbm@sbmgroup.mu',
      '',
      '',
      'https://www.linkedin.com/company/sbm-bank-mauritius-ltd/',
      '',
      'STCBMUMU',
      '',
    ),
    bank(
      'Absa Bank Mauritius',
      '+230 402 1000',
      'Absa House, Wall Street, Ebene, Mauritius',
      '',
      '',
      'https://www.absabank.mu/',
      'absamauritius@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCMUMU',
      '',
    ),
  ],
  MZ: [
    bank(
      'Banco Comercial e de Investimentos (BCI)',
      '+258 21 352 700',
      'Praca 25 de Junho, Maputo, Mozambique',
      '',
      '',
      'https://www.bci.co.mz/',
      'cliente@bci.co.mz',
      '',
      '',
      'https://www.linkedin.com/company/bci-banco-comercial-e-de-investimentos/',
      '',
      'BCIOMZMA',
      '',
    ),
    bank(
      'Millennium bim',
      '+258 21 350 000',
      'Avenida Julius Nyerere 3435, Maputo, Mozambique',
      '',
      '',
      'https://ind.millenniumbim.co.mz/',
      'cliente@millenniumbim.co.mz',
      '',
      '',
      'https://www.linkedin.com/company/millennium-bim/',
      '',
      'MILLMZMA',
      '',
    ),
    bank(
      'Standard Bank Mozambique',
      '+258 21 327 000',
      'Avenida Julius Nyerere 4, Maputo, Mozambique',
      '',
      '',
      'https://www.standardbank.co.mz/',
      'contactcentre@standardbank.co.mz',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBICMZMX',
      '',
    ),
  ],
  NA: [
    bank(
      'Bank Windhoek',
      '+264 61 299 1200',
      'C/o Independence Ave & Fidel Castro St, Windhoek, Namibia',
      '',
      '',
      'https://www.bankwindhoek.com.na/',
      'info@bankwindhoek.com.na',
      '',
      '',
      'https://www.linkedin.com/company/bank-windhoek/',
      '',
      'BWLINANX',
      '',
    ),
    bank(
      'First National Bank Namibia',
      '+264 61 299 2222',
      '209 Independence Avenue, Windhoek, Namibia',
      '',
      '',
      'https://www.fnbnamibia.com.na/',
      'custhelp@fnbnamibia.com.na',
      '',
      '',
      'https://www.linkedin.com/company/fnb-namibia/',
      '',
      'FIRNNANX',
      '',
    ),
    bank(
      'Nedbank Namibia',
      '+264 61 295 2222',
      'Nedbank Campus, Fidel Castro St, Windhoek, Namibia',
      '',
      '',
      'https://nedbanknamibia.com.na/',
      'info@nedbanknamibia.com.na',
      '',
      '',
      'https://www.linkedin.com/company/nedbank/',
      '',
      'NEDSNANX',
      '',
    ),
  ],
  SC: [
    bank(
      'Nouvobanq',
      '+248 4 280 800',
      'Rue de la Possession, Victoria, Seychelles',
      '',
      '',
      'https://www.nouvobanq.sc/',
      'info@nouvobanq.sc',
      '',
      '',
      'https://www.linkedin.com/company/nouvobanq/',
      '',
      'NOVHSCSC',
      '',
    ),
    bank(
      'Absa Bank Seychelles',
      '+248 4 389 000',
      'Independence House Annex, Victoria, Seychelles',
      '',
      '',
      'https://www.absa.sc/',
      'seychelles@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCSCSC',
      '',
    ),
    bank(
      'Mauritius Commercial Bank Seychelles',
      '+248 4 288 800',
      '9th Floor, Caravelle House, Victoria, Seychelles',
      '',
      '',
      'https://www.mcbseychelles.sc/',
      'contact@mcbseychelles.sc',
      '',
      '',
      'https://www.linkedin.com/company/mcb-seychelles/',
      '',
      'MCBLSCSC',
      '',
    ),
  ],
  ZA: [
    bank(
      'Standard Bank South Africa',
      '+27 11 636 9111',
      '5 Simmonds Street, Johannesburg, South Africa',
      '',
      '',
      'https://www.standardbank.co.za/',
      'information@standardbank.co.za',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBZAZAJJ',
      '',
    ),
    bank(
      'First National Bank South Africa',
      '+27 87 575 9404',
      '1 First Place, Bank City, Johannesburg, South Africa',
      '',
      '',
      'https://www.fnb.co.za/',
      'fnbcustomercare@fnb.co.za',
      '',
      '',
      'https://www.linkedin.com/company/fnb-south-africa/',
      '',
      'FIRNZAJJ',
      '',
    ),
    bank(
      'Absa Bank South Africa',
      '+27 11 350 4000',
      '7th Floor, Absa Towers West, Johannesburg, South Africa',
      '',
      '',
      'https://www.absa.co.za/',
      'absa@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'ABSAZAJJ',
      '',
    ),
  ],
  TZ: [
    bank(
      'NMB Bank Tanzania',
      '+255 22 232 2000',
      'NMB House, Ohio Street, Dar es Salaam, Tanzania',
      '',
      '',
      'https://www.nmbbank.co.tz/',
      'customercare@nmbbank.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/nmb-bank-plc/',
      '',
      'NMIBTZTZ',
      '',
    ),
    bank(
      'CRDB Bank',
      '+255 22 219 7700',
      'Azikiwe Street, Dar es Salaam, Tanzania',
      '',
      '',
      'https://www.crdbbank.co.tz/',
      'servicequality@crdbbank.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/crdb-bank-plc/',
      '',
      'CORUTZTZ',
      '',
    ),
    bank(
      'NBC Bank Tanzania',
      '+255 22 219 7000',
      'Sokoine Drive, Dar es Salaam, Tanzania',
      '',
      '',
      'https://nbc.co.tz/',
      'customercare@nbc.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/nbc-bank-tanzania/',
      '',
      'NICATZTZ',
      '',
    ),
  ],
  ZM: [
    bank(
      'Zanaco',
      '+260 211 220 314',
      'Cairo Road, Lusaka, Zambia',
      '',
      '',
      'https://www.zanaco.co.zm/',
      'customercare@zanaco.co.zm',
      '',
      '',
      'https://www.linkedin.com/company/zanaco/',
      '',
      'ZNCOZMLU',
      '',
    ),
    bank(
      'Absa Bank Zambia',
      '+260 211 366 800',
      'Stand 4643, Addis Ababa Drive, Lusaka, Zambia',
      '',
      '',
      'https://www.absa.co.zm/',
      'zambia@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCZMLX',
      '',
    ),
    bank(
      'Stanbic Bank Zambia',
      '+260 211 224 700',
      'Corner of Great East Road and Addis Ababa Drive, Lusaka, Zambia',
      '',
      '',
      'https://www.stanbicbank.co.zm/',
      'zambia@stanbic.com',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-zambia/',
      '',
      'SBICZMLX',
      '',
    ),
  ],
  ZW: [
    bank(
      'CBZ Bank',
      '+263 242 748 050',
      'Union House, 60 Kwame Nkrumah Ave, Harare, Zimbabwe',
      '',
      '',
      'https://www.cbz.co.zw/',
      'contactcentre@cbz.co.zw',
      '',
      '',
      'https://www.linkedin.com/company/cbz-bank-limited/',
      '',
      'COBZZWHA',
      '',
    ),
    bank(
      'Steward Bank Zimbabwe',
      '+263 242 795 858',
      '1906 Liberation Legacy Way, Harare, Zimbabwe',
      '',
      '',
      'https://www.stewardbank.co.zw/',
      'contactcentre@stewardbank.co.zw',
      '',
      '',
      'https://www.linkedin.com/company/steward-bank-zimbabwe/',
      '',
      '',
      '',
    ),
    bank(
      'Stanbic Bank Zimbabwe',
      '+263 242 758 311',
      'Stanbic Centre, 59 Samora Machel Ave, Harare, Zimbabwe',
      '',
      '',
      'https://www.stanbicbank.co.zw/',
      'customercare@stanbic.co.zw',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-zimbabwe/',
      '',
      'SBICZWHX',
      '',
    ),
  ],
}
