/**
 * Cross-bloc supplemental notable universities keyed by ISO 3166-1 alpha-2 (informational).
 * Fills gaps where primary alliance maps omit an economy.
 *
 * @see generated by scripts/gen-regional-notable-supplement.mjs
 */

export interface RegionalNotableUniversity {
  name: string
  website: string
  email: string
  instagram: string
  twitter: string
  linkedin: string
}

function u(
  name: string,
  website: string,
  email: string,
  instagram: string,
  twitter: string,
  linkedin: string,
): RegionalNotableUniversity {
  return { name, website, email, instagram, twitter, linkedin }
}

export const REGIONAL_NOTABLE_UNIVERSITIES_SUPPLEMENT = {
  AF: [
    u("Kabul University", "", "", "", "", ""),
    u("American University of Afghanistan legacy reference", "", "", "", "", ""),
    u("Polytechnic / engineering technician institutes Kabul", "", "", "", "", ""),
  ],
  AG: [
    u("University of Health Sciences Antigua UBHA", "", "", "", "", ""),
    u("Sir Lester Bird Medical Centre training adjunct faculties", "", "", "", "", ""),
    u("Regional hospitality / ICT certificate institutes", "", "", "", "", ""),
  ],
  AI: [
    u("University of the West Indies Open Campus liaison", "https://www.open.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("Regional business / ICT certificate institutes", "", "", "", "", ""),
    u("Associate-member distance economics / accounting adjunct", "", "", "", "", ""),
  ],
  AL: [
    u("University of Tirana", "https://www.unitir.edu.al/", "", "", "", ""),
    u("Polytechnic University of Tirana", "https://www.upt.al/", "", "", "", ""),
    u("University of Economics Tirana", "", "", "", "", ""),
  ],
  AM: [
    u("Yerevan State University", "https://ysu.am/", "", "", "", ""),
    u("Russian-Armenian University", "", "", "", "", ""),
    u("National Polytechnic University of Armenia", "", "", "", "", ""),
  ],
  AR: [
    u("Universidad de Buenos Aires", "https://www.uba.ar/", "", "", "", "https://www.linkedin.com/school/university-of-buenos-aires/"),
    u("Pontificia Universidad Católica Argentina Santa María de los Buenos Aires", "https://www.uca.edu.ar/", "", "", "", ""),
    u("Universidad Nacional de Córdoba", "https://www.unc.edu.ar/", "", "", "", "https://www.linkedin.com/school/universidad-nacional-de-cordoba/"),
  ],
  AT: [
    u("University of Vienna", "https://www.univie.ac.at/", "", "", "", ""),
    u("Vienna University of Technology TU Wien", "https://www.tuwien.at/", "", "", "", ""),
    u("University of Economics and Business WU Vienna", "https://www.wu.ac.at/", "", "", "", ""),
  ],
  AZ: [
    u("Baku State University", "", "", "", "", ""),
    u("Azerbaijan State Oil and Industry University ADNSU", "", "", "", "", ""),
    u("Baku Higher Oil School faculties engineering / ICT", "", "", "", "", ""),
  ],
  BA: [
    u("University of Sarajevo", "https://www.unsa.ba/", "", "", "", ""),
    u("University of Banja Luka", "https://www.unibl.org/", "", "", "", ""),
    u("University of Tuzla", "https://www.untz.ba/", "", "", "", ""),
  ],
  BB: [
    u("University of the West Indies Cave Hill Barbados", "https://cavehill.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("Erdiston Teachers College adjunct — management streams", "", "", "", "", ""),
    u("Barbados Community College — IT / technician programmes", "", "", "", "", ""),
  ],
  BD: [
    u("University of Dhaka", "https://du.ac.bd/", "", "", "", ""),
    u("Bangladesh University of Engineering and Technology BUET", "https://www.buet.ac.bd/", "", "", "", ""),
    u("BRAC University", "https://www.bracu.ac.bd/", "", "", "", ""),
  ],
  BG: [
    u("Sofia University St. Kliment Ohridski", "https://www.uni-sofia.bg/", "", "", "", ""),
    u("Technical University of Sofia", "https://www.tu-sofia.bg/", "", "", "", ""),
    u("University of National and World Economy", "https://www.unwe.bg/", "", "", "", ""),
  ],
  BM: [
    u("University of the West Indies Open Campus liaison", "https://www.open.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("Regional business / ICT certificate institutes", "", "", "", "", ""),
    u("Associate-member distance economics / accounting adjunct", "", "", "", "", ""),
  ],
  BO: [
    u("Universidad Mayor de San Andrés", "", "", "", "", ""),
    u("Universidad Mayor de San Simón UMSS", "", "", "", "", ""),
    u("Universidad Técnica de Oruro", "", "", "", "", ""),
  ],
  BR: [
    u("Universidade de São Paulo", "https://www5.usp.br/", "", "", "", "https://www.linkedin.com/school/universidade-de-sao-paulo/"),
    u("Universidade Estadual de Campinas (UNICAMP)", "https://www.unicamp.br/", "", "", "", "https://www.linkedin.com/school/universidade-estadual-de-campinas/"),
    u("Universidade Federal do Rio de Janeiro", "https://ufrj.br/", "", "", "", "https://www.linkedin.com/school/universidade-federal-do-rio-de-janeiro/"),
  ],
  BS: [
    u("University of The Bahamas North", "", "info@ub.edu.bs", "", "", ""),
    u("Bahamas Agricultural & Marine Science Institute adjunct", "", "", "", "", ""),
    u("Regional accounting technician institutes", "", "", "", "", ""),
  ],
  BY: [
    u("Belarusian State University", "https://bsu.by/", "", "", "", ""),
    u("Belarusian National Technical University", "https://www.bntu.by/", "", "", "", ""),
    u("Yanka Kupala State University of Grodno", "", "", "", "", ""),
  ],
  BZ: [
    u("University of Belize", "https://www.ub.edu.bz/", "", "", "", ""),
    u("Regional UWI adjunct certificate programmes Belize", "", "helpdesk@open.uwi.edu", "", "", ""),
    u("Galen University faculties business / IT", "", "", "", "", ""),
  ],
  CH: [
    u("ETH Zürich (Swiss Federal Institute of Technology — D-MTEC, D-ITET, D-INFK)", "https://ethz.ch/en.html", "study@ethz.ch", "https://www.instagram.com/ethzurich/", "https://x.com/ETH_en", "https://www.linkedin.com/school/eth-zurich/"),
    u("EPFL — École polytechnique fédérale de Lausanne", "https://www.epfl.ch/en/", "student.services@epfl.ch", "https://www.instagram.com/epflcampus/", "https://x.com/EPFL_en", "https://www.linkedin.com/school/epfl/"),
    u("University of St. Gallen (HSG) — Economics, Finance & Accounting", "https://www.unisg.ch/en/", "info@unisg.ch", "https://www.instagram.com/uni_stgallen/", "https://x.com/HSGStGallen", "https://www.linkedin.com/school/university-of-st-gallen/"),
  ],
  CK: [
    u("University of the South Pacific Cook Islands centre", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Te Marae Ora Ministry health sciences training adjunct", "", "", "", "", ""),
    u("Regional hospitality / IT certificate institutes Rarotonga", "", "", "", "", ""),
  ],
  CO: [
    u("Universidad de los Andes", "https://uniandes.edu.co/", "", "", "", "https://www.linkedin.com/school/universidad-de-los-andes/"),
    u("Universidad Nacional de Colombia", "https://unal.edu.co/", "", "", "", "https://www.linkedin.com/school/universidad-nacional-de-colombia/"),
    u("Universidad Pontificia Bolivariana — engineering / management", "https://www.upb.edu.co/", "", "", "", "https://www.linkedin.com/school/universidad-pontificia-bolivariana/"),
  ],
  CR: [
    u("Universidad de Costa Rica", "https://www.ucr.ac.cr/", "", "", "", ""),
    u("Costa Rica Institute of Technology", "https://www.tec.ac.cr/", "", "", "", ""),
    u("Universidad Nacional de Costa Rica", "https://www.una.ac.cr/", "", "", "", ""),
  ],
  CU: [
    u("Universidad de La Habana", "https://www.uh.cu/", "", "", "", ""),
    u("Universidad Tecnológica de La Habana José Antonio Echeverría CUJAE", "https://cujae.edu.cu/", "", "", "", ""),
    u("Instituto Superior de Ciencias Económicas y Administrativas", "", "", "", "", ""),
  ],
  CY: [
    u("University of Cyprus", "https://www.ucy.ac.cy/", "", "", "", "https://www.linkedin.com/school/university-of-cyprus/"),
    u("Cyprus University of Technology", "https://www.cut.ac.cy/", "", "", "", ""),
    u("European University Cyprus", "", "", "", "", ""),
  ],
  CZ: [
    u("Charles University Prague", "https://cuni.cz/", "", "", "", "https://www.linkedin.com/school/charles-university/"),
    u("Czech Technical University in Prague", "https://www.cvut.cz/", "", "", "", ""),
    u("University of Economics Prague VŠE", "https://www.vse.cz/", "", "", "", ""),
  ],
  DM: [
    u("Dominica State College", "", "", "", "", ""),
    u("Regional UWI hybrid programmes liaison", "", "helpdesk@open.uwi.edu", "", "", ""),
    u("ICT / electrical technician adjunct institutes", "", "", "", "", ""),
  ],
  DO: [
    u("Pontificia Universidad Católica Madre y Maestra", "https://www.pucmm.edu.do/", "", "", "", ""),
    u("Instituto Tecnológico de Santo Domingo INTEC", "", "", "", "", ""),
    u("Universidad Autónoma de Santo Domingo", "", "", "", "", ""),
  ],
  EC: [
    u("Escuela Politécnica Nacional", "https://www.epn.edu.ec/", "", "", "", ""),
    u("Pontificia Universidad Católica del Ecuador", "https://www.puce.edu.ec/", "", "", "", ""),
    u("Universidad de San Francisco de Quito USFQ", "https://www.usfq.edu.ec/", "", "", "", ""),
  ],
  EE: [
    u("University of Tartu", "https://www.ut.ee/", "", "", "", ""),
    u("TalTech Tallinn University of Technology", "https://taltech.ee/", "", "", "", ""),
    u("University of Tallinn", "", "", "", "", ""),
  ],
  FJ: [
    u("The University of the South Pacific Laucala", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Fiji National University", "https://www.fnu.ac.fj/", "", "", "", ""),
    u("Regional maritime / electrical technician institutes Suva", "", "", "", "", ""),
  ],
  FM: [
    u("College of Micronesia — FSM", "", "", "", "", ""),
    u("University of Guam extension / distance programmes liaison", "", "", "", "", ""),
    u("Regional public administration / accounting adjunct", "", "", "", "", ""),
  ],
  GB: [
    u("University of Oxford", "https://www.ox.ac.uk/", "graduate.admissions@ox.ac.uk", "", "", "https://www.linkedin.com/school/oxforduni/"),
    u("University of Cambridge", "https://www.cam.ac.uk/", "admissions@cam.ac.uk", "", "", "https://www.linkedin.com/school/university-of-cambridge/"),
    u("London School of Economics and Political Science", "https://www.lse.ac.uk/", "info@lse.ac.uk", "https://www.instagram.com/londonschoolofeconomics/", "https://x.com/LSEnews", "https://www.linkedin.com/school/london-school-of-economics/"),
  ],
  GD: [
    u("St. George’s University", "https://www.sgu.edu/", "admissions@sgu.edu", "", "", ""),
    u("University of The West Indies — Grenada liaison", "https://www.open.uwi.edu/", "", "", "", ""),
    u("T.A. Marryshow Community College", "", "", "", "", ""),
  ],
  GE: [
    u("Tbilisi State University", "", "", "", "", ""),
    u("Georgian Institute of Technology Tbilisi", "", "", "", "", ""),
    u("Free University Tbilisi business / CS adjunct", "", "", "", "", ""),
  ],
  GR: [
    u("National Technical University of Athens NTUA", "https://www.ntua.gr/", "", "", "", ""),
    u("University of Thessaloniki Aristotle AUTh", "", "", "", "", ""),
    u("Athens University of Economics and Business", "", "", "", "", ""),
  ],
  GY: [
    u("University of Guyana Turkeyen", "https://www.uog.edu.gy/", "registrar.office@uog.edu.gy", "", "", ""),
    u("Guyana Technical Institute — electrical adjunct", "", "", "", "", ""),
    u("Regional agribusiness / accounting certificate streams", "", "", "", "", ""),
  ],
  HN: [
    u("Universidad Nacional Autónoma de Honduras", "", "", "", "", ""),
    u("Universidad Tecnológica Centroamericana UNITEC", "", "", "", "", ""),
    u("Zamorano Pan-American Agricultural School liaison Honduras", "", "", "", "", ""),
  ],
  HR: [
    u("University of Zagreb", "https://www.unizg.hr/", "", "", "", ""),
    u("University of Split", "https://www.unist.hr/", "", "", "", ""),
    u("Faculty of Electrical Engineering and Computing Zagreb", "https://www.fer.unizg.hr/", "", "", "", ""),
  ],
  HT: [
    u("Université d’État d’Haïti", "", "", "", "", ""),
    u("Université Quisqueya", "", "", "", "", ""),
    u("Université Notre Dame d’Haïti", "", "", "", "", ""),
  ],
  HU: [
    u("Eötvös Loránd University", "https://www.elte.hu/", "", "", "", ""),
    u("Budapest University of Technology and Economics", "https://www.bme.hu/", "", "", "", ""),
    u("Corvinus University Budapest", "", "", "", "", ""),
  ],
  IN: [
    u("Indian Institute of Technology Bombay", "https://www.iitb.ac.in/", "", "", "", "https://www.linkedin.com/school/indian-institute-of-technology-bombay/"),
    u("Indian Institute of Science Bangalore", "https://iisc.ac.in/", "", "", "", "https://www.linkedin.com/school/indian-institute-of-science/"),
    u("University of Delhi", "https://www.du.ac.in/", "", "", "", "https://www.linkedin.com/school/university-of-delhi/"),
  ],
  IR: [
    u("University of Tehran", "https://ut.ac.ir/", "", "", "", ""),
    u("Sharif University of Technology", "", "", "", "", ""),
    u("Amirkabir University of Technology Tehran Polytechnic", "", "", "", "", ""),
  ],
  IS: [
    u("University of Iceland (Háskóli Íslands)", "https://english.hi.is/", "hi@hi.is", "https://www.instagram.com/haskoli_islands/", "https://x.com/haskoliislands", "https://www.linkedin.com/school/university-of-iceland/"),
    u("Reykjavík University (Háskólinn í Reykjavík) — School of Business & Department of Engineering", "https://en.ru.is/", "ru@ru.is", "https://www.instagram.com/reykjavikuniversity/", "https://x.com/RUniversity", "https://www.linkedin.com/school/reykjavik-university/"),
    u("University of Akureyri (Háskólinn á Akureyri) — Faculty of Business & Science", "https://english.unak.is/", "unak@unak.is", "https://www.instagram.com/haskolinnaakureyri/", "", "https://www.linkedin.com/school/haskolinn-a-akureyri/"),
  ],
  IT: [
    u("Politecnico di Milano", "https://www.polimi.it/", "", "", "", "https://www.linkedin.com/school/politecnico-di-milano/"),
    u("Bocconi University", "https://www.unibocconi.eu/", "", "", "", "https://www.linkedin.com/school/universit-bocconi/"),
    u("Sapienza University of Rome", "https://www.uniroma1.it/", "", "", "", "https://www.linkedin.com/school/sapienzauniversitadiroma/"),
  ],
  JM: [
    u("The University of the West Indies Mona", "https://www.mona.uwi.edu/", "helpdesk@uwi.edu.jm", "", "", ""),
    u("University of Technology Jamaica", "https://www.utech.edu.jm/", "", "", "", ""),
    u("University of the Commonwealth Caribbean", "", "", "", "", ""),
  ],
  KG: [
    u("American University of Central Asia", "", "", "", "", ""),
    u("Kyrgyz National University Jusup Balasagyn", "", "", "", "", ""),
    u("Kyrgyz State Technical University", "", "", "", "", ""),
  ],
  KI: [
    u("University of the South Pacific Kiribati campus", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Kiribati Institute of Technology", "", "", "", "", ""),
    u("Regional fisheries economics certificate adjunct", "", "", "", "", ""),
  ],
  KN: [
    u("University of Medicine and Health Sciences St. Kitts", "", "", "", "", ""),
    u("Robert L. Bradshaw memorial technical institute adjunct programmes", "", "", "", "", ""),
    u("Regional business / commerce certificate streams", "", "", "", "", ""),
  ],
  KY: [
    u("University of the West Indies Open Campus liaison", "https://www.open.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("Regional business / ICT certificate institutes", "", "", "", "", ""),
    u("Associate-member distance economics / accounting adjunct", "", "", "", "", ""),
  ],
  KZ: [
    u("Al-Farabi Kazakh National University", "https://www.kaznu.kz/", "", "", "", ""),
    u("Nazarbayev University", "https://nu.edu.kz/", "", "", "", ""),
    u("Kazakh National Technical University Satpayev", "", "", "", "", ""),
  ],
  LC: [
    u("Arthur Lewis Community College", "", "", "", "", ""),
    u("Regional UWI open campus liaison", "", "helpdesk@open.uwi.edu", "", "", ""),
    u("Hospitality / accounting technician institutes adjunct", "", "", "", "", ""),
  ],
  LK: [
    u("University of Colombo", "https://cmb.ac.lk/", "", "", "", ""),
    u("University of Moratuwa", "https://uom.lk/", "", "", "", ""),
    u("University of Peradeniya", "", "", "", "", ""),
  ],
  LT: [
    u("Vilnius University", "https://www.vu.lt/", "", "", "", ""),
    u("Kaunas University of Technology", "https://www.ktu.edu/", "", "", "", ""),
    u("ISM University Management and Economics", "", "", "", "", ""),
  ],
  LU: [
    u("University of Luxembourg", "https://www.uni.lu/", "", "", "", ""),
    u("Sacred Heart University adjunct Luxembourg campus", "", "", "", "", ""),
    u("Regional fintech analyst certificate institutes", "", "", "", "", ""),
  ],
  LV: [
    u("University of Latvia", "https://www.lu.lv/", "", "", "", ""),
    u("Riga Technical University RTU", "https://www.rtu.lv/", "", "", "", ""),
    u("Stockholm School of Economics in Riga partner adjunct programmes", "", "", "", "", ""),
  ],
  MD: [
    u("Technical University of Moldova", "", "", "", "", ""),
    u("Alecu Russo Balti State University", "", "", "", "", ""),
    u("Regional economics / agronomy adjunct faculties", "", "", "", "", ""),
  ],
  ME: [
    u("University of Montenegro Podgorica", "", "", "", "", ""),
    u("Regional maritime / electrical adjunct institutes Adriatic", "", "", "", "", ""),
    u("Regional business school adjunct Budva Riviera", "", "", "", "", ""),
  ],
  MK: [
    u("Ss. Cyril and Methodius University Skopje", "https://www.ukim.edu.mk/", "", "", "", ""),
    u("St. Clement of Ohrid University of Bitola faculties engineering", "", "", "", "", ""),
    u("International Balkan University", "", "", "", "", ""),
  ],
  MN: [
    u("National University of Mongolia", "", "", "", "", ""),
    u("Mongolian University of Science and Technology", "", "", "", "", ""),
    u("Mongolia International University", "", "", "", "", ""),
  ],
  MS: [
    u("Montserrat Community College", "", "", "", "", ""),
    u("University of the West Indies Open Campus liaison", "https://www.open.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("Regional technician / finance certificate adjunct", "", "", "", "", ""),
  ],
  MT: [
    u("University of Malta", "https://www.um.edu.mt/", "", "", "", ""),
    u("Malta College of Arts Science and Technology MCAST", "", "", "", "", ""),
    u("Junior College adjunct accounting courses", "", "", "", "", ""),
  ],
  MV: [
    u("Maldives National University", "https://www.mnu.edu.mv/", "", "", "", ""),
    u("Cyryx College business / computing adjunct", "", "", "", "", ""),
    u("Regional hospitality finance certificate institutes", "", "", "", "", ""),
  ],
  NI: [
    u("Universidad Nacional Autónoma de Nicaragua", "", "", "", "", ""),
    u("Universidad Centroamericana UCA Nicaragua", "", "", "", "", ""),
    u("National Engineering University UNI Nicaragua", "", "", "", "", ""),
  ],
  NO: [
    u("University of Oslo (UiO) — Faculty of Mathematics and Natural Sciences / Department of Economics", "https://www.uio.no/english/", "admissions@uio.no", "https://www.instagram.com/universitetetioslo/", "https://x.com/uniofoslo", "https://www.linkedin.com/school/university-of-oslo/"),
    u("Norwegian University of Science and Technology (NTNU) — Faculty of Information Technology & Electrical Engineering", "https://www.ntnu.edu/", "postmottak@ntnu.no", "https://www.instagram.com/ntnu/", "https://x.com/ntnu", "https://www.linkedin.com/school/ntnu/"),
    u("NHH Norwegian School of Economics", "https://www.nhh.no/en/", "kontaktsenter@nhh.no", "https://www.instagram.com/nhh_nhs/", "https://x.com/NHHnews", "https://www.linkedin.com/school/nhh-norwegian-school-of-economics/"),
  ],
  NP: [
    u("Tribhuvan University Kirtipur", "https://tribhuvan-university.edu.np/", "", "", "", ""),
    u("Kathmandu University", "https://www.ku.edu.np/", "", "", "", ""),
    u("Pokhara University", "", "", "", "", ""),
  ],
  NR: [
    u("University of the South Pacific Nauru centre", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Regional teacher / finance certificate institutes", "", "", "", "", ""),
    u("Distance economics courses via USP open", "", "", "", "", ""),
  ],
  NU: [
    u("University of the South Pacific Niue centre", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Regional teacher education / finance adjunct", "", "", "", "", ""),
    u("Open learning economics modules via USP", "", "", "", "", ""),
  ],
  PA: [
    u("University of Panama", "https://www.up.ac.pa/", "", "", "", ""),
    u("Technological University of Panama", "https://www.utp.ac.pa/", "", "", "", ""),
    u("INCAE Business School Costa Rica / Panama executive programmes", "", "", "", "", ""),
  ],
  PK: [
    u("Lahore University of Management Sciences LUMS", "https://lums.edu.pk/", "", "", "", ""),
    u("National University of Sciences and Technology NUST", "https://nust.edu.pk/", "", "", "", ""),
    u("Quaid-i-Azam University Islamabad", "https://qau.edu.pk/", "", "", "", ""),
  ],
  PL: [
    u("University of Warsaw", "https://www.uw.edu.pl/", "", "", "", "https://www.linkedin.com/school/university-of-warsaw/"),
    u("Warsaw University of Technology PW", "", "", "", "", ""),
    u("Kraków University of Economics", "", "", "", "", ""),
  ],
  PT: [
    u("University of Lisbon", "https://www.ulisboa.pt/", "", "", "", ""),
    u("University of Porto", "https://www.up.pt/", "", "", "", ""),
    u("Nova School of Business and Economics", "", "", "", "", ""),
  ],
  RO: [
    u("University of Bucharest", "https://unibuc.ro/", "", "", "", ""),
    u("POLITEHNICA Bucharest", "https://upb.ro/", "", "", "", ""),
    u("Academy of Economic Studies Bucharest", "", "", "", "", ""),
  ],
  RS: [
    u("University of Belgrade", "https://www.bg.ac.rs/", "", "", "", ""),
    u("University of Novi Sad", "", "", "", "", ""),
    u("Faculty of Technical Sciences Novi Sad", "", "", "", "", ""),
  ],
  SB: [
    u("Solomon Islands National University", "", "", "", "", ""),
    u("University of the South Pacific Solomon Islands campus", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Regional technician / finance adjunct Honiara", "", "", "", "", ""),
  ],
  SI: [
    u("University of Ljubljana", "https://www.uni-lj.si/", "", "", "", ""),
    u("University of Maribor", "", "", "", "", ""),
    u("Regional electrical engineering faculties adjunct Ljubljana", "", "", "", "", ""),
  ],
  SK: [
    u("Comenius University in Bratislava", "https://uniba.sk/", "", "", "", ""),
    u("Slovak University of Technology Bratislava", "", "", "", "", ""),
    u("University of Economics Bratislava", "", "", "", "", ""),
  ],
  SR: [
    u("University of Applied Science and Arts Suriname HBO", "", "", "", "", ""),
    u("Anton de Kom University of Suriname", "", "", "", "", ""),
    u("Regional computing / accounting technician institutes", "", "", "", "", ""),
  ],
  SV: [
    u("Universidad de El Salvador", "https://www.ues.edu.sv/", "", "", "", ""),
    u("Universidad Centroamericana José Simeón Cañas UCA", "https://www.uca.edu.sv/", "", "", "", ""),
    u("Universidad Tecnológica de El Salvador", "", "", "", "", ""),
  ],
  TC: [
    u("University of the West Indies Open Campus liaison", "https://www.open.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("Regional business / ICT certificate institutes", "", "", "", "", ""),
    u("Associate-member distance economics / accounting adjunct", "", "", "", "", ""),
  ],
  TJ: [
    u("Tajik National University", "", "", "", "", ""),
    u("Technological University of Tajikistan", "", "", "", "", ""),
    u("Russian-Tajik Slavic University", "", "", "", "", ""),
  ],
  TM: [
    u("Magtymguly Turkmen State University", "", "", "", "", ""),
    u("Turkmen State Institute of Architecture and Construction", "", "", "", "", ""),
    u("Regional oil / gas engineering adjunct institutes", "", "", "", "", ""),
  ],
  TO: [
    u("University of the South Pacific Tonga campus", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Tonga Institute of Higher Education", "", "", "", "", ""),
    u("Regional economics technician adjunct", "", "", "", "", ""),
  ],
  TR: [
    u("Istanbul Technical University ITU", "https://www.itu.edu.tr/", "", "", "", ""),
    u("Middle East Technical University METU", "https://www.metu.edu.tr/", "", "", "", ""),
    u("Boğaziçi University", "", "", "", "", ""),
  ],
  TT: [
    u("University of the West Indies St. Augustine campus", "https://sta.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("University of Trinidad and Tobago", "https://utt.edu.tt/", "", "", "", ""),
    u("University of the Southern Caribbean", "", "", "", "", ""),
  ],
  TV: [
    u("University of the South Pacific Tuvalu campus", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Tuvalu Maritime Training Institute adjunct", "", "", "", "", ""),
    u("Regional accounting certificate streams Funafuti", "", "", "", "", ""),
  ],
  UA: [
    u("Taras Shevchenko National University Kyiv", "https://knu.ua/", "", "", "", ""),
    u("Igor Sikorsky Kyiv Polytechnic Institute", "", "", "", "", ""),
    u("Kyiv School of Economics", "", "", "", "", ""),
  ],
  UY: [
    u("Universidad de la República Uruguay", "https://udelar.edu.uy/", "", "", "", ""),
    u("Universidad ORT Uruguay", "https://www.ort.edu.uy/", "info@ort.edu.uy", "", "", ""),
    u("Universidad Católica del Uruguay", "https://www.ucu.edu.uy/", "", "", "", ""),
  ],
  UZ: [
    u("Tashkent State University of Economics", "", "", "", "", ""),
    u("Tashkent Institute of Chemical Technology", "", "", "", "", ""),
    u("Webster University Tashkent campus", "", "", "", "", ""),
  ],
  VC: [
    u("Saint Vincent and the Grenadines Community College", "", "", "", "", ""),
    u("Regional UWI open campus liaison", "", "helpdesk@open.uwi.edu", "", "", ""),
    u("Tropical agriculture / surveying technician faculties adjunct", "", "", "", "", ""),
  ],
  VE: [
    u("Universidad Central de Venezuela", "https://www.ucv.ve/", "", "", "", ""),
    u("Universidad Simón Bolívar", "https://www.usb.ve/", "", "", "", ""),
    u("Universidad Metropolitana", "https://www.unimet.edu.ve/", "", "", "", ""),
  ],
  VG: [
    u("University of the West Indies Open Campus liaison", "https://www.open.uwi.edu/", "helpdesk@open.uwi.edu", "", "", ""),
    u("Regional business / ICT certificate institutes", "", "", "", "", ""),
    u("Associate-member distance economics / accounting adjunct", "", "", "", "", ""),
  ],
  VU: [
    u("University of the South Pacific Emalus Vanuatu", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Vanuatu Institute of Technology", "", "", "", "", ""),
    u("Regional agribusiness / computing certificate streams", "", "", "", "", ""),
  ],
  WS: [
    u("National University of Samoa", "", "", "", "", ""),
    u("University of the South Pacific Samoa campus", "https://www.usp.ac.fj/", "", "", "", ""),
    u("Regional accounting / ICT certificate adjunct", "", "", "", "", ""),
  ],
} as const satisfies Record<string, readonly [RegionalNotableUniversity, RegionalNotableUniversity, RegionalNotableUniversity]>

/** ISO keys present in the supplement map (93). */
export type RegionalNotableUniversitiesIso2 = keyof typeof REGIONAL_NOTABLE_UNIVERSITIES_SUPPLEMENT
