// Bitcoin Oracle (ALEX/Domo) for Bitcoin (BTC)
// Native Bitcoin L1/L2 Indexing Oracle

export const bitcoinOracle = {
  name: "Bitcoin Oracle (ALEX)",
  blockchain: "Bitcoin (BTC) L1/L2",
  type: "Native Bitcoin Oracle (Federated)",
  description: "Bitcoin Oracle is a decentralized, on-chain indexing solution designed specifically for Bitcoin and its Layer 2 ecosystems (e.g., Stacks, Ordinals, BRC-20). It provides tamper-proof, censorship-resistant price and event data, enabling DeFi and smart contract applications directly on Bitcoin. Uses a federated model of off-chain indexers reaching consensus.",
  url: "https://alexgo.io/",
  docs: "https://medium.com/alexgobtc/bitcoin-oracle-a-roadmap-for-the-future-of-bitcoin-defi-6f0041851b63",
  dashboardUrl: "https://oracle.alexgo.io/",
  api: {
    roadmap: "https://medium.com/alexgobtc/bitcoin-oracle-a-roadmap-for-the-future-of-bitcoin-defi-6f0041851b63",
    indexerDashboard: "https://oracle.alexgo.io/",
    stacksDocs: "https://docs.stacks.co/",
    clarinetSdk: "https://github.com/hirosystems/clarinet-sdk",
    bitcoinjsLib: "https://github.com/bitcoinjs/bitcoinjs-lib",
  },
  features: [
    "Native Bitcoin L1/L2 indexing",
    "BRC-20 token support",
    "Ordinals inscription tracking",
    "Tamper-proof consensus model",
    "Censorship-resistant data",
    "Stacks smart contract integration",
    "Bitcoin UTXO state tracking",
    "Custom feed creation",
    "Federated indexer network",
    "On-chain data publication",
  ],
  useCases: [
    "Bitcoin DeFi protocols on Stacks",
    "BRC-20 token applications",
    "Ordinals-based NFT platforms",
    "Bitcoin L2 smart contracts",
    "UTXO state verification",
    "Cross-layer data synchronization",
    "Inscription indexing",
    "Bitcoin-native lending protocols",
  ],
  integrationMethod: "Stacks Smart Contracts (Clarity) / bitcoinjs-lib / Clarinet SDK",
  dataFrequency: "Real-time indexing with blockchain confirmation",
  pricing: "Free for read access (Alpha/Beta phase)",
  coverage: "Bitcoin state (UTXOs, inscriptions), BRC-20 prices, custom feeds",
  layer2Support: {
    stacks: "Primary integration via Clarity smart contracts",
    ordinals: "Native Ordinals and BRC-20 indexing",
    lightning: "Planned future support",
  },
  status: "Alpha (launched 2023), mainnet 2025",
  federatedModel: {
    description: "Off-chain indexers reach consensus on Bitcoin data",
    consensus: "Federated agreement among trusted indexers",
    dataPublishing: "On-chain publication via Stacks",
    verification: "Cryptographic proof of consensus",
  },
  socialMedia: {
    twitter: "https://twitter.com/ALEXLabBTC",
    telegram: "https://t.me/AlexCommunity",
    discord: "https://discord.gg/alexlab",
    github: "https://github.com/alexgo-io",
    medium: "https://medium.com/alexgobtc",
  },
  integrationNotes: "Use Clarinet SDK for Stacks smart contract development. Queries Bitcoin Oracle via Clarity contracts on Stacks. For Bitcoin L1, use bitcoinjs-lib for transaction and UTXO parsing. Currently in Alpha with mainnet launch planned for 2025.",
  npmPackages: [
    "bitcoinjs-lib",
    "@stacks/transactions",
    "@stacks/network",
  ],
  sampleClarityCall: "contract.call('bitcoin-oracle', 'get-btc-price', [])",
};

