// OpenTimestamps Oracle for Bitcoin (BTC)
// Open-Source Timestamping Protocol

export const openTimestampsOracle = {
  name: "OpenTimestamps",
  blockchain: "Bitcoin (BTC)",
  type: "Timestamping Oracle Protocol",
  description: "OpenTimestamps is an open-source, scalable protocol for timestamping using Bitcoin's blockchain. It creates cryptographic proofs of data existence at specific times, leveraging Bitcoin's security. Unlike Proof of Existence, OpenTimestamps uses a more efficient calendar server architecture and is completely free to use.",
  url: "https://opentimestamps.org/",
  docs: "https://opentimestamps.org/",
  githubUrl: "https://github.com/opentimestamps",
  api: {
    calendarServers: [
      "https://alice.btc.calendar.opentimestamps.org",
      "https://bob.btc.calendar.opentimestamps.org",
      "https://finney.calendar.eternitywall.com",
    ],
    timestamp: "POST /digest (to calendar server)",
    verify: "Local verification using .ots file",
    upgrade: "POST /timestamp/{digest} (upgrade to Bitcoin-confirmed)",
    documentation: "https://github.com/opentimestamps/opentimestamps-server/blob/master/doc/protocol.md",
  },
  features: [
    "Free timestamping service",
    "Scalable calendar server architecture",
    "No registration required",
    "Multiple independent calendar servers",
    "Efficient aggregation (multiple timestamps per transaction)",
    "Open-source protocol and clients",
    "Cross-platform support",
    "Git integration for code timestamping",
    "Local verification (no server needed)",
    "Privacy-preserving (no data upload)",
  ],
  useCases: [
    "Git commit timestamping",
    "Document notarization",
    "Code release verification",
    "Academic publication timestamping",
    "Legal document certification",
    "Data integrity audits",
    "Supply chain verification",
    "Media authenticity",
    "Intellectual property protection",
    "Archive verification",
  ],
  integrationMethod: "Command-line tool / Python library / JavaScript library / Calendar server API",
  dataFrequency: "Immediate pending timestamp, Bitcoin confirmation in ~1 hour (batched)",
  pricing: "Completely free (aggregated Bitcoin transactions)",
  coverage: "Universal - any file or data can be timestamped",
  howItWorks: {
    timestamp: [
      "User computes SHA-256 hash of document",
      "Hash is submitted to calendar server",
      "Server aggregates multiple timestamps into Merkle tree",
      "Merkle root is periodically committed to Bitcoin",
      "User receives .ots file (timestamp proof)",
    ],
    verification: [
      "User provides original file and .ots proof",
      "Hash is recomputed and compared",
      "Merkle proof is verified against Bitcoin transaction",
      "Bitcoin block timestamp provides proof of existence",
      "No server needed for verification",
    ],
    upgrade: [
      "Initial timestamp is 'pending' (in calendar server)",
      "After ~1 hour, timestamp is 'upgraded' to Bitcoin-confirmed",
      "User can request upgrade to get final .ots file",
      "Final .ots file contains Bitcoin transaction reference",
    ],
  },
  technicalDetails: {
    hashAlgorithm: "SHA-256, SHA-1, RIPEMD-160, KECCAK-256",
    aggregation: "Merkle tree for efficient batching",
    storage: "Bitcoin OP_RETURN (Merkle root)",
    calendarServers: "Decentralized public servers",
    verification: "Completely local (no server required)",
  },
  tools: {
    cli: "ots (command-line tool)",
    pythonLibrary: "opentimestamps-python",
    jsLibrary: "javascript-opentimestamps",
    gitIntegration: "git-timestamp",
  },
  socialMedia: {
    github: "https://github.com/opentimestamps",
    twitter: "https://twitter.com/opentimestamps",
  },
  integrationNotes: "Use `ots` CLI tool for simple timestamping: `ots stamp file.txt` creates file.txt.ots. Verify with `ots verify file.txt.ots`. For JavaScript integration, use javascript-opentimestamps library. Completely free with no API key required.",
  npmPackages: [
    "javascript-opentimestamps",
  ],
  cliCommands: [
    "ots stamp <file> # Create timestamp",
    "ots verify <file.ots> # Verify timestamp",
    "ots upgrade <file.ots> # Upgrade pending to confirmed",
    "ots info <file.ots> # Show timestamp details",
  ],
  advantages: [
    "Completely free (no transaction fees)",
    "Efficient aggregation (many timestamps per Bitcoin tx)",
    "Decentralized architecture",
    "No account or registration needed",
    "Open-source and auditable",
    "Local verification (privacy-preserving)",
    "Multiple independent servers",
  ],
  comparison: {
    vsProofOfExistence: "OpenTimestamps is free, more scalable, and uses calendar servers for aggregation. Proof of Existence requires payment for each timestamp.",
  },
};

