// Currency: Binance Coin (BNB)
// Source: Cryptocurrency Data
// Research Data Compiled from Multiple Sources

import type { CurrencyData, DerivedInfo } from './currencyData';
import { toHex } from './utils';
import { Wallet } from 'ethers';

export const binanceCoinData: CurrencyData = {
  basicInfo: {
    name: "Binance Coin",
    symbolTicker: "BNB",
    description: "The native cryptocurrency of the Binance ecosystem, used for trading fee discounts, staking, and governance on the Binance Smart Chain.",
    creator: "Binance",
    debutYear: 2017,
    website: "https://www.bnbchain.org/",
    whitePaper: "https://github.com/bnb-chain/whitepaper/blob/master/WHITEPAPER.md",
    primaryNFTMarketplace: "https://www.binance.com/en/nft/home",
    secondaryNFTMarketplace: "https://element.market/bsc",
  },

  technicalInfo: {
    proofingType: "Proof of Stake",
    class: "Layer 1 Blockchain / Exchange Token",
    totalSupply: "200,000,000 BNB (with burns)",
    libraryHashing: "Keccak-256",
    librarySigning: "ECDSA",
    mnemonicSeedPhraseLengths: "12, 24 words (BIP39)",
    privateKeyFormat: "64-character hexadecimal (32 bytes) with optional 0x prefix",
    privateKeyToPublicKeyCurve: "secp256k1",
    publicKeyToPublicWalletAddressHashing: "Keccak-256 (last 20 bytes)",
    NPMLibraryHashing: "@noble/hashes/sha3",
    NPMLibrarySigning: "ethers",
    keyStoreFormat: "Ethereum-compatible JSON Keystore (Web3 Secret Storage)",
    jsonFormat: "EVM-compatible JSON (BEP-20)",
    smartContractLanguage: "Solidity / Vyper (EVM-compatible)",
    primaryNPMPackage: "ethers",
    secondaryNPMPackage: "@noble/secp256k1",
    tertiaryNPMPackage: "web3",
    web3ConnectMechanism: "WalletConnect / MetaMask / Trust Wallet",
    nativeWallet: "Trust Wallet / Binance Chain Wallet",
    humanReadableAddressingPlatform: "SPACE ID (.bnb domains)",
    humanReadableAddressingNPMPackage: "@siddomains/sidjs",
    SendingMechanism: "EVM transaction broadcasting (BSC)",
    NFTMintingMechanism: "BEP-721 (ERC-721 compatible) / BEP-1155",
    AssetTokenSupportAndMechanism: "BEP-20 (ERC-20 compatible) / BEP-2 (Binance Chain)",
    evmChainID: 56,
    typicalDerivationPath: "m/44'/60'/0'/0/0 (BIP44 Ethereum standard, BSC is EVM-compatible)",
    sendingFunctionality: "ethers.Wallet.sendTransaction() or web3.eth.sendTransaction()",
  },

  dex: [
    {
      name: "PancakeSwap",
      url: "https://pancakeswap.finance/",
      type: "AMM DEX",
      description: "The largest decentralized exchange on BNB Smart Chain with deep liquidity",
    },
    {
      name: "Biswap",
      url: "https://biswap.org/",
      type: "AMM DEX",
      description: "Low-fee DEX with multi-type referral system and lottery",
    },
    {
      name: "ApeSwap",
      url: "https://apeswap.finance/",
      type: "Multi-Chain AMM",
      description: "DeFi hub with AMM, lending, and farming on multiple chains",
    },
    {
      name: "THENA",
      url: "https://www.thena.fi/",
      type: "Next-Gen AMM",
      description: "Liquidity layer with ve(3,3) tokenomics on BNB Chain",
    },
    {
      name: "Uniswap V3 (BSC)",
      url: "https://app.uniswap.org/",
      type: "Concentrated Liquidity AMM",
      description: "Uniswap V3 deployment on BNB Smart Chain",
    },
    {
      name: "BabySwap",
      url: "https://babyswap.finance/",
      type: "AMM DEX",
      description: "Community-driven DEX with NFT marketplace integration",
    },
    {
      name: "DODO",
      url: "https://dodoex.io/",
      type: "PMM DEX",
      description: "Proactive Market Maker DEX with capital-efficient liquidity",
    },
  ],

  stakingProviders: [
    {
      name: "Binance Staking",
      url: "https://www.binance.com/en/staking",
      type: "Exchange Staking",
      description: "Official Binance exchange staking with flexible and locked options",
    },
    {
      name: "Trust Wallet",
      url: "https://trustwallet.com/staking",
      type: "Wallet Staking",
      description: "Native staking through Trust Wallet mobile app",
    },
    {
      name: "BNB Chain Validators",
      url: "https://www.bnbchain.org/en/bnb-smart-chain/validators",
      type: "Native Staking",
      description: "Delegate to any of the 21 active validators on BNB Smart Chain",
    },
    {
      name: "pSTAKE Finance",
      url: "https://pstake.finance/",
      type: "Liquid Staking",
      description: "Liquid staking for BNB with stkBNB tokens",
    },
    {
      name: "Ankr",
      url: "https://www.ankr.com/staking/stake/bnb/",
      type: "Liquid Staking",
      description: "Liquid staking with ankrBNB tokens",
    },
    {
      name: "Kraken",
      url: "https://www.kraken.com/features/staking-coins",
      type: "Exchange Staking",
      description: "Stake BNB through Kraken exchange",
    },
    {
      name: "Stader",
      url: "https://www.staderlabs.com/",
      type: "Liquid Staking",
      description: "Multi-chain liquid staking protocol including BNB",
    },
  ],

  miningPools: "N/A (Proof of Stake Authority - No Mining)",

  marketInfo: {
    allTimeHigh: {
      price: 1330.51,
      currency: "USD",
      date: "2025-10-12",
    },
  },

  socialMedia: {
    discord: "https://discord.gg/binance",
    instagram: "https://www.instagram.com/binance/",
    linkedin: "https://www.linkedin.com/company/binance/",
    reddit: "https://www.reddit.com/r/binance/",
    slack: "N/A",
    telegram: "https://t.me/binance",
    twitterX: "https://twitter.com/binance",
  },

  identifiers: {
    UCID: "1839",
    identifierBraveNewCoin: "BNB",
    identifierCoinAPI: "BNB",
    identifierCoinCap: "binance-coin",
    identifierCoinGecko: "binancecoin",
    identifierCoinPaprika: "bnb-binance-coin",
  },

  blockExplorer: {
    blockExplorerAPI: "https://api.bscscan.com/api",
    blockExplorerLink: "https://bscscan.com/address/",
  },

  rpcEndpoints: [
    {
      name: "Binance - DataSeed 1",
      url: "https://bsc-dataseed1.binance.org",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Binance - DataSeed 2",
      url: "https://bsc-dataseed2.binance.org",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Binance - DataSeed 3",
      url: "https://bsc-dataseed3.binance.org",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Binance - DataSeed 4",
      url: "https://bsc-dataseed4.binance.org",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "DeFiBit - DataSeed 1",
      url: "https://bsc-dataseed1.defibit.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via DeFiBit. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "DeFiBit - DataSeed 2",
      url: "https://bsc-dataseed2.defibit.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via DeFiBit. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "DeFiBit - DataSeed 3",
      url: "https://bsc-dataseed3.defibit.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via DeFiBit. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "DeFiBit - DataSeed 4",
      url: "https://bsc-dataseed4.defibit.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via DeFiBit. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ninicoin - DataSeed 1",
      url: "https://bsc-dataseed1.ninicoin.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via Ninicoin. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ninicoin - DataSeed 2",
      url: "https://bsc-dataseed2.ninicoin.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via Ninicoin. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ninicoin - DataSeed 3",
      url: "https://bsc-dataseed3.ninicoin.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via Ninicoin. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ninicoin - DataSeed 4",
      url: "https://bsc-dataseed4.ninicoin.io",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC RPC endpoint via Ninicoin. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "PublicNode - BSC RPC",
      url: "https://bsc-rpc.publicnode.com",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Public RPC endpoint for BNB Smart Chain via PublicNode. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No API key required.",
      npmPackage: "ethers",
      documentation: "https://publicnode.com/",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ankr - MainNet HTTPS",
      url: "https://rpc.ankr.com/bsc",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public, Optional API Key)",
      description: "Free RPC provider with WebSocket support. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). Free tier with rate limits. Optional API key for premium features.",
      npmPackage: "ethers",
      documentation: "https://www.ankr.com/rpc/bsc",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ankr - MainNet WebSocket",
      url: "wss://rpc.ankr.com/bsc/ws",
      port: 443,
      protocol: "wss",
      type: "EVM RPC WebSocket (Public, Optional API Key)",
      description: "WebSocket endpoint for real-time subscriptions. Provides Ethereum-compatible JSON-RPC over WebSocket for BNB Smart Chain (Chain ID: 56). Free tier with rate limits. Optional API key for premium features.",
      npmPackage: "ethers",
      documentation: "https://www.ankr.com/rpc/bsc",
      network: "mainnet",
      serviceType: "evm-ws",
    },
    {
      name: "1RPC - MainNet",
      url: "https://1rpc.io/bnb",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Privacy-focused free RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain (Chain ID: 56). No tracking, no API key required. Rate limits apply.",
      npmPackage: "ethers",
      documentation: "https://www.1rpc.io/ecosystem/bnb-chain",
      network: "mainnet",
      serviceType: "evm-rpc",
    },
    {
      name: "BscScan API - MainNet",
      url: "https://api.bscscan.com/api",
      port: 443,
      protocol: "https",
      type: "REST API (API Key Required)",
      description: "Official block explorer API. Provides indexed data including transaction history, token transfers, internal transactions, and BEP-20 events. Free tier: ~5 calls/second, ~100,000 calls/day. Requires free API key from https://bscscan.com/myapikey",
      npmPackage: "axios",
      documentation: "https://docs.bscscan.com",
      network: "mainnet",
      serviceType: "rest",
      requiresApiKey: true,
    },
    {
      name: "Binance TestNet - DataSeed 1-S1",
      url: "https://data-seed-prebsc-1-s1.binance.org",
      port: 8545,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC TestNet RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain TestNet (Chain ID: 97). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "testnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Binance TestNet - DataSeed 2-S1",
      url: "https://data-seed-prebsc-2-s1.binance.org",
      port: 8545,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC TestNet RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain TestNet (Chain ID: 97). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "testnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Binance TestNet - DataSeed 1-S3",
      url: "https://data-seed-prebsc-1-s3.binance.org",
      port: 8545,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC TestNet RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain TestNet (Chain ID: 97). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "testnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Binance TestNet - DataSeed 2-S3",
      url: "https://data-seed-prebsc-2-s3.binance.org",
      port: 8545,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Official Binance BSC TestNet RPC endpoint. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain TestNet (Chain ID: 97). No API key required.",
      npmPackage: "ethers",
      documentation: "https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes",
      network: "testnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ankr - TestNet HTTPS",
      url: "https://rpc.ankr.com/bsc_testnet_chapel",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public, Optional API Key)",
      description: "Free RPC provider for BSC TestNet with WebSocket support. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain TestNet (Chain ID: 97). Free tier with rate limits. Optional API key for premium features.",
      npmPackage: "ethers",
      documentation: "https://www.ankr.com/rpc/bsc",
      network: "testnet",
      serviceType: "evm-rpc",
    },
    {
      name: "Ankr - TestNet WebSocket",
      url: "wss://rpc.ankr.com/bsc_testnet_chapel/ws",
      port: 443,
      protocol: "wss",
      type: "EVM RPC WebSocket (Public, Optional API Key)",
      description: "WebSocket endpoint for BSC TestNet real-time subscriptions. Provides Ethereum-compatible JSON-RPC over WebSocket for BNB Smart Chain TestNet (Chain ID: 97). Free tier with rate limits. Optional API key for premium features.",
      npmPackage: "ethers",
      documentation: "https://www.ankr.com/rpc/bsc",
      network: "testnet",
      serviceType: "evm-ws",
    },
    {
      name: "1RPC - TestNet",
      url: "https://1rpc.io/bnb-testnet",
      port: 443,
      protocol: "https",
      type: "EVM RPC Node (Public)",
      description: "Privacy-focused free RPC endpoint for BSC TestNet. Provides Ethereum-compatible JSON-RPC for BNB Smart Chain TestNet (Chain ID: 97). No tracking, no API key required. Rate limits apply.",
      npmPackage: "ethers",
      documentation: "https://www.1rpc.io/ecosystem/bnb-chain",
      network: "testnet",
      serviceType: "evm-rpc",
    },
    {
      name: "BscScan API - TestNet",
      url: "https://api-testnet.bscscan.com/api",
      port: 443,
      protocol: "https",
      type: "REST API (API Key Required)",
      description: "Official block explorer API for BSC TestNet. Provides indexed data including transaction history, token transfers, internal transactions, and BEP-20 events. Free tier: ~5 calls/second, ~100,000 calls/day. Requires free API key from https://bscscan.com/myapikey",
      npmPackage: "axios",
      documentation: "https://docs.bscscan.com",
      network: "testnet",
      serviceType: "rest",
      requiresApiKey: true,
    },
  ],
  
  deriveFromPrivateKey: async (privateKey: string): Promise<DerivedInfo> => {
    // Import dependencies when needed to avoid loading them if not used
    const secp = await import('@noble/secp256k1');
    
    const wallet = new Wallet(privateKey.startsWith("0x") ? privateKey : `0x${privateKey}`);
    // wallet.publicKey is not typed in ethers v6 typings; compute from private key via noble
    const sk = Uint8Array.from((wallet.privateKey.slice(2)).match(/.{1,2}/g)!.map((b) => parseInt(b, 16)));
    const pub = secp.getPublicKey(sk, false);
    const addressString: string = String(wallet.address);
    
    return { publicKey: toHex(pub), address: addressString };
  }
};
