import type { CorporationFormationOffice } from './types'
import type { CensadMemberIsoCode } from './censadMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per CEN-SAD member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const CENSAD_CORPORATION_FORMATION_OFFICES: Record<CensadMemberIsoCode, CorporationFormationOffice> = {
  BJ:   office(
    'APIEx Benin - Guichet Unique de Formalisation des Entreprises',
    '+229 21 31 00 65',
    'Boulevard de la Marina, Cotonou, Benin',
    'https://apiex.bj',
    'info@apiex.bj',
    'https://x.com/APIEX_BENIN',
    '',
    'https://www.linkedin.com/company/apiex-benin/',
    'https://monentreprise.bj',
    'https://apiex.bj/guide-du-createur',
    'Numero IFU (Identifiant Fiscal Unique)',
  ),
  BF:   office(
    'CEFORE Burkina Faso (Maison de l\'Entreprise)',
    '+226 25 39 80 60',
    '17 BP 502 Ouagadougou 17, Avenue de Lyon, Ouagadougou, Burkina Faso',
    'https://www.me.bf',
    'formalites@me.bf',
    '',
    '',
    '',
    'https://www.me.bf/creation-d-entreprise',
    'https://www.me.bf/guide-createur',
    'Numero RCCM (Registre du Commerce et du Credit Mobilier)',
  ),
  CF:   office(
    'Guichet Unique de Formalites des Entreprises (RCA)',
    '+236 75 05 05 05',
    'Avenue de l\'Independance, Bangui, Central African Republic',
    'https://www.apica.cf',
    'contact@apica.cf',
    '',
    '',
    '',
    'https://www.apica.cf/creation-entreprise',
    'https://www.apica.cf/check-list',
    'Numero RCCM',
  ),
  TD:   office(
    'Agence Nationale des Investissements et des Exportations (ANIE Chad) - Guichet Unique',
    '+235 22 52 42 42',
    'Quartier Sabangali, N\'Djamena, Chad',
    'https://www.anie.td',
    'contact@anie.td',
    '',
    '',
    '',
    'https://www.anie.td/guichet-unique',
    'https://www.anie.td/guide-createur',
    'Numero RCCM',
  ),
  KM:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Comores)',
    '+269 773 08 08',
    'Avenue de l\'OUA, Moroni, Comoros',
    'https://www.anpi-comores.km',
    'contact@anpi-comores.km',
    '',
    '',
    '',
    'https://www.anpi-comores.km/guichet-unique',
    'https://www.anpi-comores.km/guide-createur',
    'Numero RCCM',
  ),
  DJ:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Djibouti)',
    '+253 21 35 20 00',
    'Plateau du Serpent, BP 2194, Djibouti City, Djibouti',
    'https://www.investindjibouti.dj',
    'contact@investindjibouti.dj',
    '',
    '',
    '',
    'https://www.investindjibouti.dj/creation-dentreprise',
    'https://www.investindjibouti.dj/guide-creation',
    'Numero RCCM',
  ),
  EG:   office(
    'General Authority for Investment and Free Zones (GAFI) - One Stop Shop',
    '+20 2 3537 3333',
    'Salah Salem Road, Nasr City, Cairo, Egypt',
    'https://www.gafi.gov.eg',
    'info@gafi.gov.eg',
    'https://x.com/gafieg',
    '',
    'https://www.linkedin.com/company/gafi-egypt/',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/default.aspx',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/Procedures.aspx',
    'Commercial Register Number (CR Number)',
  ),
  ER:   office(
    'Ministry of Trade and Industry Eritrea - Business Licensing Office',
    '+291 1 120 055',
    'Harnet Avenue, Asmara, Eritrea',
    'https://www.shabait.com/ministry-of-trade-and-industry',
    'moti@e.gov.er',
    '',
    '',
    '',
    'https://www.shabait.com/ministry-of-trade-and-industry',
    '',
    'Business Registration Number',
  ),
  GM:   office(
    'Ministry of Justice The Gambia - Registrar of Companies',
    '+220 422 5308',
    'Marina Parade, Banjul, The Gambia',
    'https://www.moj.gov.gm',
    'info@moj.gov.gm',
    '',
    '',
    '',
    'https://www.moj.gov.gm/registrar-general',
    '',
    'Company Registration Number',
  ),
  GH:   office(
    'Registrar-General\'s Department (RGD Ghana)',
    '+233 30 266 1081',
    'Ministries, Accra, Ghana',
    'https://rgd.gov.gh',
    'info@rgd.gov.gh',
    'https://x.com/ORC_ghana',
    '',
    'https://www.linkedin.com/company/office-of-the-registrar-of-companies-ghana/',
    'https://egovonline.gegov.gov.gh/RGDPortalWeb/portal/RGDHome',
    'https://rgd.gov.gh/services/business-registration/',
    'Company Registration Number',
  ),
  GN:   office(
    'Agence de Promotion des Investissements Prives (APIP Guinea) - Guichet Unique',
    '+224 622 98 25 00',
    'Coleah, Commune de Matam, Conakry, Guinea',
    'https://apip.gov.gn',
    'contact@apip.gov.gn',
    '',
    '',
    'https://www.linkedin.com/company/apip-guinee/',
    'https://apip.gov.gn/creation-dentreprise',
    'https://apip.gov.gn/guide-du-createur',
    'Numero RCCM',
  ),
  GW:   office(
    'Centro de Formalizacao de Empresas (CFE Guinea-Bissau)',
    '+245 955 800 800',
    'Avenida Amilcar Cabral, Bissau, Guinea-Bissau',
    'https://www.cfe.gw',
    'info@cfe.gw',
    '',
    '',
    '',
    'https://www.cfe.gw/empresa-no-dia',
    'https://www.cfe.gw/requisitos',
    'Numero de Matricula Comercial',
  ),
  CI:   office(
    'CEPICI - Guichet Unique de Creation d\'Entreprise',
    '+225 27 20 31 14 00',
    'Abidjan Plateau, Avenue Marchand, Cote d\'Ivoire',
    'https://www.cepici.ci',
    'infos@cepici.ci',
    'https://x.com/cepici',
    'https://www.instagram.com/cepici.ci/',
    'https://www.linkedin.com/company/cepici/',
    'https://www.225invest.ci/creation-entreprise',
    'https://www.cepici.ci/guide-du-createur',
    'Numero RCCM',
  ),
  LY:   office(
    'Ministry of Economy and Trade Libya - Commercial Registry Department',
    '+218 21 335 0380',
    'Al-Sikka Road, Tripoli, Libya',
    'https://www.economy.gov.ly',
    'info@economy.gov.ly',
    '',
    '',
    '',
    'https://www.economy.gov.ly/services/commercial-register',
    '',
    'Commercial Registration Number',
  ),
  ML:   office(
    'API Mali - Guichet Unique de Creation d\'Entreprise',
    '+223 20 22 18 12',
    'Avenue du Mali, Hamdallaye ACI 2000, Bamako, Mali',
    'https://www.apimali.gov.ml',
    'contact@apimali.gov.ml',
    '',
    '',
    '',
    'https://www.apimali.gov.ml/guichet-unique',
    'https://www.apimali.gov.ml/repertoire-des-formalites',
    'Numero RCCM',
  ),
  MR:   office(
    'Agence de Promotion des Investissements en Mauritanie (APIM) - Guichet Unique',
    '+222 45 25 33 77',
    'Ilot C, Tevragh Zeina, Nouakchott, Mauritania',
    'https://apim.gov.mr',
    'contact@apim.gov.mr',
    '',
    '',
    '',
    'https://apim.gov.mr/creation-dentreprise',
    'https://apim.gov.mr/guide-createur',
    'Numero RCCM',
  ),
  MA:   office(
    'OMPIC Morocco - DirectEntreprise',
    '+212 5 22 58 64 00',
    'Route de Nouasseur, Km 9.5, Casablanca, Morocco',
    'https://www.directentreprise.ma',
    'contact@ompic.ma',
    'https://x.com/OMPICMaroc',
    '',
    'https://www.linkedin.com/company/ompic-maroc/',
    'https://www.directentreprise.ma',
    'https://www.ompic.ma/fr/content/guide-de-creation',
    'Numero du Registre de Commerce (RC)',
  ),
  NE:   office(
    'Maison de l\'Entreprise du Niger - CFE',
    '+227 20 75 23 47',
    'Boulevard Mali Bero, Niamey, Niger',
    'https://www.me.ne',
    'infos@me.ne',
    '',
    '',
    '',
    'https://www.me.ne/creation-dentreprise',
    'https://www.me.ne/guide-des-formalites',
    'Numero RCCM',
  ),
  NG:   office(
    'Corporate Affairs Commission (CAC Nigeria)',
    '+234 700 022 2255',
    'Plot 420, Tigris Crescent, Maitama, Abuja, Nigeria',
    'https://www.cac.gov.ng',
    'enquiries@cac.gov.ng',
    'https://x.com/cacnigeria1',
    'https://www.instagram.com/cacnigeria/',
    'https://www.linkedin.com/company/corporate-affairs-commission-nigeria/',
    'https://pre.cac.gov.ng/register',
    'https://www.cac.gov.ng/resources',
    'Registration Number (RC Number)',
  ),
  SN:   office(
    'Bureau d\'Appui a la Creation d\'Entreprise (BCE SENEGAL)',
    '+221 33 839 88 76',
    'Rue Vincens x Rue Saint-Michel, Dakar, Senegal',
    'https://creationdentreprise.sn',
    'contact@creationdentreprise.sn',
    '',
    '',
    '',
    'https://creationdentreprise.sn/formalites',
    'https://creationdentreprise.sn/guide',
    'Numero NINEA / RCCM',
  ),
  SL:   office(
    'Office of the Administrator and Registrar General (OARG Sierra Leone)',
    '+232 79 990 739',
    'Roxy Building, Walpole Street, Freetown, Sierra Leone',
    'https://oarg.gov.sl',
    'info@oarg.gov.sl',
    'https://x.com/OargSierraLeone',
    '',
    'https://www.linkedin.com/company/oarg-sl/',
    'https://oarg.gov.sl/business-registration',
    'https://oarg.gov.sl/requirements',
    'Company Registration Number',
  ),
  SO:   office(
    'Ministry of Commerce and Industry Somalia - Company Registrar',
    '+252 61 553 3333',
    'Maka Al-Mukarama Road, Mogadishu, Somalia',
    'https://moci.gov.so',
    'info@moci.gov.so',
    '',
    '',
    '',
    'https://moci.gov.so/services/business-registration',
    '',
    'Business Registration Number',
  ),
  SD:   office(
    'Commercial Registrar General (Sudan Ministry of Justice)',
    '+249 183 770 920',
    'Ministry of Justice Complex, Khartoum, Sudan',
    'https://moj.gov.sd',
    'registry@moj.gov.sd',
    '',
    '',
    '',
    'https://moj.gov.sd/services/commercial-registration',
    '',
    'Commercial Registration Number',
  ),
  TG:   office(
    'Centre de Formalites des Entreprises (CFE Togo)',
    '+228 22 53 47 47',
    'Chaine du Port, Lome, Togo',
    'https://cfe.tg',
    'info@cfe.tg',
    '',
    '',
    'https://www.linkedin.com/company/cfetogo/',
    'https://cfe.tg/creation-dentreprise',
    'https://cfe.tg/pieces-a-fournir',
    'Numero RCCM',
  ),
  TN:   office(
    'APII Tunisia - Guichet Unique de l\'Industrie',
    '+216 71 792 144',
    '63 Rue de Syrie, 1002 Tunis, Tunisia',
    'https://www.tunisieindustrie.nat.tn',
    'apii@apii.tn',
    '',
    '',
    'https://www.linkedin.com/company/agence-de-promotion-de-l-industrie-et-de-l-innovation/',
    'https://www.tunisieindustrie.nat.tn/fr/home.asp',
    'https://www.tunisieindustrie.nat.tn/fr/doc.asp',
    'Identifiant Unique de l\'Entreprise (RNE)',
  ),
}
