import type { CensadMemberIsoCode } from './censadMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per CEN-SAD member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const CENSAD_DOMESTIC_POST_SERVICES: Record<CensadMemberIsoCode, DomesticPostService> = {
  BJ: post(
    'La Poste du Bénin',
    'https://www.poste.bj/',
    'contact@poste.bj',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-benin/',
    '',
    'none',
    '',
    '',
    'No national postcode; arrondissement and P.O. Box',
  ),
  BF: post(
    'La Poste Burkina Faso (SONAPOST)',
    'http://www.sonapost.bf/',
    'contact@sonapost.bf',
    '',
    '',
    'https://www.linkedin.com/company/sonapost/',
    '',
    'none',
    '',
    '',
    'No national postcode system; commune and P.O. Box routing',
  ),
  CF: post(
    'Office national des Postes RCA',
    'https://onet-rca.cf/',
    'contact@onet-rca.cf',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  TD: post(
    'La Poste Tchadienne',
    'https://www.laposte.td/',
    'contact@laposte.td',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-tchadienne/',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  KM: post(
    'Comores Poste',
    'https://poste-comores.com/',
    'contact@poste-comores.km',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and village addressing',
  ),
  DJ: post(
    'La Poste de Djibouti',
    'https://www.laposte.dj/',
    'poste.contact@yahoo.fr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing in Djibouti City',
  ),
  EG: post(
    'Egypt Post',
    'http://www.egpost.org/',
    'webmaster@egpost.org',
    'https://x.com/Egyptpost',
    'https://www.instagram.com/egypt.post/',
    'https://www.linkedin.com/company/egypt-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11511',
    'Five-digit national postcode',
  ),
  ER: post(
    'Eritrean Postal Service',
    'https://www.shabait.com/category/national-development/telecom-post/',
    'info@ericsson.com.er',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No published national postcode system',
  ),
  GM: post(
    'GamPost',
    'https://gampost.gm/',
    'info@gampost.gm',
    '',
    '',
    'https://www.linkedin.com/company/gampost/',
    '',
    'none',
    '',
    '',
    'No national postcode; settlement and P.O. Box',
  ),
  GH: post(
    'Ghana Post',
    'http://ghanapost.com.gh/',
    'info@ghanapost.com.gh',
    'https://x.com/ghanapostgh',
    'https://www.instagram.com/ghanapostgh/',
    'https://www.linkedin.com/company/ghana-post/',
    '',
    'none',
    '',
    '',
    'GhanaPostGPS digital address parallel to legacy P.O. Box; no legacy numeric postcode',
  ),
  GN: post(
    'La Poste Guinée',
    'https://www.gui.post/',
    'direction@gui.post',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-guinee/',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  GW: post(
    'Correios da Guiné-Bissau',
    'https://www.correios.gw/',
    'geral@cgb.gw',
    '',
    '',
    '',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Bissau and regional)',
  ),
  CI: post(
    'La Poste de Côte d\'Ivoire',
    'https://www.la-poste.ci/',
    'info@laposte.ci',
    'https://x.com/LaPosteCI',
    'https://www.instagram.com/laposteci/',
    'https://www.linkedin.com/company/la-poste-de-cote-divoire/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune and P.O. Box dominant',
  ),
  LY: post(
    'Libyan Post Company',
    'http://nlpc.ly/',
    'info@nlpc.ly',
    '',
    '',
    'https://www.linkedin.com/company/libyan-post/',
    '',
    'none',
    '',
    '',
    'No consistent national postcode published; verify locally',
  ),
  ML: post(
    'La Poste du Mali EMS',
    'https://www.sap.ml/',
    'contact@post.ml',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-mali/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune addressing',
  ),
  MR: post(
    'Mauripost (Société mauritanienne des postes)',
    'https://www.mauripost.mr/',
    'contact@mauripost.mr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  MA: post(
    'Barid Al-Maghrib',
    'https://www.barid.ma/',
    'webmaster@barid.ma',
    'https://x.com/PosteMaroc',
    'https://www.instagram.com/baridalma_',
    'https://www.linkedin.com/company/barid-al-maghrib/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '20000',
    'Five-digit postcode',
  ),
  NE: post(
    'La Poste du Niger',
    'https://www.nigerpost.ne/',
    'npn@refer.ne',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-niger/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '8001',
    'Four-digit postcode (Niamey and regions)',
  ),
  NG: post(
    'Nigeria Postal Service (NIPOST)',
    'http://nipost.gov.ng/',
    'info@nipost.gov.ng',
    'https://x.com/e_nipost',
    'https://www.instagram.com/e_nipost/',
    'https://www.linkedin.com/company/nipost/',
    '',
    'NNNNNN',
    '^\\\\d{6}$',
    '100001',
    'Six-digit postcode (state + LGA + delivery)',
  ),
  SN: post(
    'La Poste Sénégal',
    'https://www.laposte.sn/',
    'dircom@laposte.sn',
    'https://x.com/LaPosteSenegal',
    'https://www.instagram.com/lapostesenegal/',
    'https://www.linkedin.com/company/la-poste-senegal/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '12500',
    'Five-digit postcode',
  ),
  SL: post(
    'Salone Post EMS',
    'https://www.slpost.gov.sl/',
    'info@slipa.gov.sl',
    '',
    '',
    'https://www.linkedin.com/company/sierra-leone-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; Freetown district addressing',
  ),
  SO: post(
    'Somali Postal Service',
    'https://www.upu.int/en/Somalia',
    'minister@mpt.gov.so',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district and landmark addressing',
  ),
  SD: post(
    'Sudan Post (Sudapost)',
    'https://sudapost.sd/',
    'info@sudapost.sd',
    '',
    '',
    'https://www.linkedin.com/company/sudan-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11111',
    'Five-digit postcode (verify operational coverage)',
  ),
  TG: post(
    'La Poste du Togo',
    'https://www.laposte.tg/',
    'contact@laposte.tg',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-togo/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune addressing',
  ),
  TN: post(
    'Rapid-Poste (La Poste Tunisia)',
    'https://www.pos.tn/',
    'contact@rapidpost.com.tn',
    'https://x.com/RapidposteTN',
    'https://www.instagram.com/rapidpostenetunisienne/',
    'https://www.linkedin.com/company/la-poste-tunisienne/',
    '',
    'NNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
}
