import type { CensadMemberIsoCode } from './censadMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

const OAPI_TRADEMARKS = ip(
  'trademarks',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

const OAPI_PATENTS = ip(
  'patents',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

function oapiMember(copyright: IntellectualPropertyDepartment): IntellectualPropertyDepartmentsRoster {
  return roster(copyright, OAPI_TRADEMARKS, OAPI_PATENTS)
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for Community of Sahel-Saharan
 * States (CEN-SAD) members in this module (informational; verify URLs, handles, forms portals,
 * and API bases before production use). Self-contained — no imports from other alliance modules.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const CENSAD_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  CensadMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  BJ: oapiMember(
    ip(
      'copyright',
      'Bureau Béninois du Droit d\'Auteur et des Droits Voisins (BURIDA)',
      'https://www.burida.bj',
      'contact@burida.bj',
      '',
      '',
      'https://www.burida.bj',
    ),
  ),
  BF: oapiMember(
    ip(
      'copyright',
      'Office Burkinabè des Droits d\'Auteur (OBDA)',
      'https://www.obda.bf',
      'obda@obda.bf',
      '',
      '',
      'https://www.obda.bf',
    ),
  ),
  CF: oapiMember(
    ip(
      'copyright',
      'Office Centrafricain du Droit d\'Auteur (OCADA)',
      'https://www.ocada-rca.cf',
      '',
      '',
      '',
      'https://www.ocada-rca.cf',
    ),
  ),
  TD: oapiMember(
    ip(
      'copyright',
      'Agence Tchadienne du Droit d\'Auteur (ATCHADA)',
      'https://www.atchada.td',
      '',
      '',
      '',
      'https://www.atchada.td',
    ),
  ),
  KM: oapiMember(
    ip(
      'copyright',
      'Centre Comorien du Droit d\'Auteur et des Droits Voisins',
      'https://www.beit-salam.km',
      '',
      '',
      '',
      'https://www.beit-salam.km',
    ),
  ),
  DJ: roster(
    ip(
      'copyright',
      'Ministry of Culture and Communication — copyright (Djibouti)',
      'https://www.communication.gouv.dj',
      '',
      '',
      '',
      'https://www.communication.gouv.dj',
    ),
    ip(
      'trademarks',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
    ip(
      'patents',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
  ),
  EG: roster(
    ip(
      'copyright',
      'Egyptian Copyright Office (Ministry of Culture)',
      'https://www.culture.gov.eg',
      '',
      '',
      '',
      'https://www.culture.gov.eg',
    ),
    ip(
      'trademarks',
      'Egyptian Patent Office — Trademarks Department',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
    ip(
      'patents',
      'Egyptian Patent Office',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
  ),
  ER: roster(
    ip(
      'copyright',
      'Ministry of Information — copyright (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
    ip(
      'trademarks',
      'Ministry of Trade and Industry — industrial property (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
    ip(
      'patents',
      'Ministry of Trade and Industry — industrial property (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
  ),
  GM: roster(
    ip(
      'copyright',
      'National Centre for Arts and Culture (NCAC) — copyright',
      'https://www.ncac.gm',
      'info@ncac.gm',
      '',
      '',
      'https://www.ncac.gm',
    ),
    ip(
      'trademarks',
      'Registrar General\'s Department — Industrial Property (The Gambia)',
      'https://www.moj.gov.gm',
      '',
      '',
      '',
      'https://www.moj.gov.gm',
    ),
    ip(
      'patents',
      'Registrar General\'s Department — Industrial Property (The Gambia)',
      'https://www.moj.gov.gm',
      '',
      '',
      '',
      'https://www.moj.gov.gm',
    ),
  ),
  GH: roster(
    ip(
      'copyright',
      'Copyright Office, Registrar General\'s Department',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      '',
      'https://rgd.gov.gh',
    ),
    ip(
      'trademarks',
      'Registrar General\'s Department — Industrial Property',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      'https://www.linkedin.com/company/registrar-generals-department-ghana/',
      'https://rgd.gov.gh',
    ),
    ip(
      'patents',
      'Registrar General\'s Department — Industrial Property',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      'https://www.linkedin.com/company/registrar-generals-department-ghana/',
      'https://rgd.gov.gh',
    ),
  ),
  GN: oapiMember(
    ip(
      'copyright',
      'Bureau Guinéen du Droit d\'Auteur (BGDA)',
      'https://www.bgda.gn',
      '',
      '',
      '',
      'https://www.bgda.gn',
    ),
  ),
  GW: oapiMember(
    ip(
      'copyright',
      'Instituto Nacional de Direitos de Autor (INDA — Guinea-Bissau)',
      'https://www.inda.gw',
      '',
      '',
      '',
      'https://www.inda.gw',
    ),
  ),
  CI: oapiMember(
    ip(
      'copyright',
      'Bureau Ivoirien du Droit d\'Auteur (BURIDA)',
      'https://www.burida.ci',
      'contact@burida.ci',
      '',
      '',
      'https://www.burida.ci',
    ),
  ),
  LY: roster(
    ip(
      'copyright',
      'Libyan National Centre for Culture and Arts — copyright',
      'https://www.culture.gov.ly',
      '',
      '',
      '',
      'https://www.culture.gov.ly',
    ),
    ip(
      'trademarks',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
    ip(
      'patents',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
  ),
  ML: oapiMember(
    ip(
      'copyright',
      'Bureau Malien du Droit d\'Auteur (BUMADA)',
      'https://www.bumada.ml',
      '',
      '',
      '',
      'https://www.bumada.ml',
    ),
  ),
  MR: oapiMember(
    ip(
      'copyright',
      'Bureau Mauritanien du Droit d\'Auteur (BUMDA)',
      'https://www.bumda.mr',
      '',
      '',
      '',
      'https://www.bumda.mr',
    ),
  ),
  MA: roster(
    ip(
      'copyright',
      'Bureau Marocain des Droits d\'Auteur (BMDA)',
      'https://www.bmda.org',
      'contact@bmda.org',
      '',
      '',
      'https://www.bmda.org',
    ),
    ip(
      'trademarks',
      'Office Marocain de la Propriété Industrielle et Commerciale (OMPIC)',
      'https://www.ompic.ma',
      'contact@ompic.ma',
      '',
      'https://www.linkedin.com/company/ompic/',
      'https://www.ompic.ma',
    ),
    ip(
      'patents',
      'Office Marocain de la Propriété Industrielle et Commerciale (OMPIC)',
      'https://www.ompic.ma',
      'contact@ompic.ma',
      '',
      'https://www.linkedin.com/company/ompic/',
      'https://www.ompic.ma',
    ),
  ),
  NE: oapiMember(
    ip(
      'copyright',
      'Bureau Nigérien du Droit d\'Auteur (BUNDA)',
      'https://www.bunda.ne',
      '',
      '',
      '',
      'https://www.bunda.ne',
    ),
  ),
  NG: roster(
    ip(
      'copyright',
      'Nigerian Copyright Commission (NCC)',
      'https://www.copyright.gov.ng',
      'info@copyright.gov.ng',
      'https://x.com/NCC_NG',
      'https://www.linkedin.com/company/nigerian-copyright-commission/',
      'https://www.copyright.gov.ng',
    ),
    ip(
      'trademarks',
      'Trademarks, Patents and Designs Registry (Federal Ministry of Industry, Trade and Investment)',
      'https://www.fmiti.gov.ng',
      'info@fmiti.gov.ng',
      '',
      '',
      'https://www.fmiti.gov.ng',
    ),
    ip(
      'patents',
      'Trademarks, Patents and Designs Registry (Federal Ministry of Industry, Trade and Investment)',
      'https://www.fmiti.gov.ng',
      'info@fmiti.gov.ng',
      '',
      '',
      'https://www.fmiti.gov.ng',
    ),
  ),
  SN: oapiMember(
    ip(
      'copyright',
      'Bureau Sénégalais du Droit d\'Auteur (BSDA)',
      'https://www.bsda.sn',
      'contact@bsda.sn',
      '',
      '',
      'https://www.bsda.sn',
    ),
  ),
  SL: roster(
    ip(
      'copyright',
      'Sierra Leone Copyright Office',
      'https://www.mic.gov.sl',
      '',
      '',
      '',
      'https://www.mic.gov.sl',
    ),
    ip(
      'trademarks',
      'National Intellectual Property Office of Sierra Leone (NIPOSL)',
      'https://www.niposl.gov.sl',
      'info@niposl.gov.sl',
      '',
      '',
      'https://www.niposl.gov.sl',
    ),
    ip(
      'patents',
      'National Intellectual Property Office of Sierra Leone (NIPOSL)',
      'https://www.niposl.gov.sl',
      'info@niposl.gov.sl',
      '',
      '',
      'https://www.niposl.gov.sl',
    ),
  ),
  SO: roster(
    ip(
      'copyright',
      'Ministry of Information, Culture and Tourism — copyright (Somalia)',
      'https://www.mict.gov.so',
      '',
      '',
      '',
      'https://www.mict.gov.so',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
    ip(
      'patents',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
  ),
  SD: roster(
    ip(
      'copyright',
      'Sudan Copyright Office (Ministry of Culture)',
      'https://www.moc.gov.sd',
      '',
      '',
      '',
      'https://www.moc.gov.sd',
    ),
    ip(
      'trademarks',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
    ip(
      'patents',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
  ),
  TG: oapiMember(
    ip(
      'copyright',
      'Office Togolais des Droits d\'Auteur et des Droits Voisins (OTDAV)',
      'https://www.otdav.tg',
      '',
      '',
      '',
      'https://www.otdav.tg',
    ),
  ),
  TN: roster(
    ip(
      'copyright',
      'Office National du Droit d\'Auteur (ONDA)',
      'https://www.onda.tn',
      'contact@onda.tn',
      '',
      '',
      'https://www.onda.tn',
    ),
    ip(
      'trademarks',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
    ip(
      'patents',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
  ),
}
