import type { CensadMemberIsoCode } from './censadMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const CENSAD_MAIN_INTERNATIONAL_AIRPORTS: Record<CensadMemberIsoCode, MainInternationalAirport> = {
  BJ: {
    name: 'Cadjehoun International Airport (COO)',
    website: 'https://www.aeroport-cotonou.bj/',
    email: 'contact@aeroport-cotonou.bj',
    twitter: 'https://x.com/AeroportCotonou',
    instagram: 'https://www.instagram.com/aeroportcotonou/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-cadjehoun/',
    apiEndpoint: '',
  },
  BF: {
    name: 'Thomas Sankara International Airport Ouagadougou (OUA)',
    website: 'https://www.aeroport-ouagadougou.bf/',
    email: 'contact@aeroport-ouagadougou.bf',
    twitter: 'https://x.com/AIB_OUA',
    instagram: 'https://www.instagram.com/aib_ouagadougou/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-bobo-dioulasso/',
    apiEndpoint: '',
  },
  CF: {
    name: 'Bangui M\'Poko International Airport (BGF)',
    website: 'https://www.aeroport-bangui.cf/',
    email: 'info@aeroport-bangui.cf',
    twitter: 'https://x.com/AeroportBGF',
    instagram: 'https://www.instagram.com/aeroportbangui/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-bangui-mpoko/',
    apiEndpoint: '',
  },
  TD: {
    name: 'N\'Djamena International Airport (NDJ)',
    website: 'https://www.anac.td/',
    email: 'contact@anac.td',
    twitter: 'https://x.com/ANAC_Tchad',
    instagram: 'https://www.instagram.com/anac_tchad/',
    linkedin: 'https://www.linkedin.com/company/anac-tchad/',
    apiEndpoint: '',
  },
  KM: {
    name: 'Prince Said Ibrahim International Airport (HAH)',
    website: 'https://www.aeroport-comores.km/',
    email: 'info@aeroport-comores.km',
    twitter: 'https://x.com/AeroportHAH',
    instagram: 'https://www.instagram.com/aeroportcomores/',
    linkedin: 'https://www.linkedin.com/company/aeroport-prince-said-ibrahim/',
    apiEndpoint: '',
  },
  DJ: {
    name: 'Djibouti-Ambouli International Airport (JIB)',
    website: 'https://www.aeroport-djibouti.dj/',
    email: 'contact@aeroport-djibouti.dj',
    twitter: 'https://x.com/AeroportJIB',
    instagram: 'https://www.instagram.com/aeroportdjibouti/',
    linkedin: 'https://www.linkedin.com/company/djibouti-ambouli-international-airport/',
    apiEndpoint: '',
  },
  EG: {
    name: 'Cairo International Airport (CAI)',
    website: 'https://www.cairo-airport.com/',
    email: 'info@cairo-airport.com',
    twitter: 'https://x.com/CairoAirport',
    instagram: 'https://www.instagram.com/cairoairport/',
    linkedin: 'https://www.linkedin.com/company/cairo-airport/',
    apiEndpoint: '',
  },
  ER: {
    name: 'Asmara International Airport (ASM)',
    website: 'https://www.eritreanairlines.com/',
    email: 'info@eritreanairlines.com',
    twitter: 'https://x.com/EritreaAirlines',
    instagram: 'https://www.instagram.com/eritreanairlines/',
    linkedin: 'https://www.linkedin.com/company/eritrean-airlines/',
    apiEndpoint: '',
  },
  GM: {
    name: 'Banjul International Airport (BJL)',
    website: 'https://www.gcaa.gm/',
    email: 'info@gcaa.gm',
    twitter: 'https://x.com/GCAA_Gambia',
    instagram: 'https://www.instagram.com/gcaa_gambia/',
    linkedin: 'https://www.linkedin.com/company/gambia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GH: {
    name: 'Kotoka International Airport (ACC)',
    website: 'https://www.gcaa.com.gh/',
    email: 'info@gcaa.com.gh',
    twitter: 'https://x.com/GCAA_Ghana',
    instagram: 'https://www.instagram.com/gcaa_ghana/',
    linkedin: 'https://www.linkedin.com/company/ghana-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GN: {
    name: 'Ahmed Sékou Touré International Airport (CKY)',
    website: 'https://www.aeroport-conakry.gn/',
    email: 'contact@aeroport-conakry.gn',
    twitter: 'https://x.com/AeroportCKY',
    instagram: 'https://www.instagram.com/aeroportconakry/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-conakry/',
    apiEndpoint: '',
  },
  GW: {
    name: 'Osvaldo Vieira International Airport (OXB)',
    website: 'https://www.aeroporto-bissau.gw/',
    email: 'contact@aeroporto-bissau.gw',
    twitter: 'https://x.com/AeroportoOXB',
    instagram: 'https://www.instagram.com/aeroportobissau/',
    linkedin: 'https://www.linkedin.com/company/aeroporto-osvaldo-vieira/',
    apiEndpoint: '',
  },
  CI: {
    name: 'Félix-Houphouët-Boigny International Airport (ABJ)',
    website: 'https://www.aeroport-abidjan.com/',
    email: 'contact@aeroport-abidjan.com',
    twitter: 'https://x.com/AeroportABJ',
    instagram: 'https://www.instagram.com/aeroportabidjan/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-felix-houphouet-boigny/',
    apiEndpoint: '',
  },
  LY: {
    name: 'Mitiga International Airport (MJI)',
    website: 'https://www.lycaa.gov.ly/',
    email: 'info@lycaa.gov.ly',
    twitter: 'https://x.com/LYCAA_Libya',
    instagram: 'https://www.instagram.com/lycaa_libya/',
    linkedin: 'https://www.linkedin.com/company/libyan-civil-aviation-authority/',
    apiEndpoint: '',
  },
  ML: {
    name: 'Modibo Keita International Airport (BKO)',
    website: 'https://www.aeroport-bamako.ml/',
    email: 'contact@aeroport-bamako.ml',
    twitter: 'https://x.com/AeroportBKO',
    instagram: 'https://www.instagram.com/aeroportbamako/',
    linkedin: 'https://www.linkedin.com/company/aeroport-modibo-keita/',
    apiEndpoint: '',
  },
  MR: {
    name: 'Nouakchott-Oumtounsy International Airport (NKC)',
    website: 'https://www.anac.mr/',
    email: 'contact@anac.mr',
    twitter: 'https://x.com/ANAC_Mauritanie',
    instagram: 'https://www.instagram.com/anac_mauritanie/',
    linkedin: 'https://www.linkedin.com/company/anac-mauritanie/',
    apiEndpoint: '',
  },
  MA: {
    name: 'Mohammed V International Airport (CMN)',
    website: 'https://www.onda.ma/en',
    email: 'contact@onda.ma',
    twitter: 'https://x.com/ONDA_MAROC',
    instagram: 'https://www.instagram.com/onda_maroc/',
    linkedin: 'https://www.linkedin.com/company/onda-officiel/',
    apiEndpoint: '',
  },
  NE: {
    name: 'Diori Hamani International Airport (NIM)',
    website: 'https://www.anac.ne/',
    email: 'contact@anac.ne',
    twitter: 'https://x.com/ANAC_Niger',
    instagram: 'https://www.instagram.com/anac_niger/',
    linkedin: 'https://www.linkedin.com/company/anac-niger/',
    apiEndpoint: '',
  },
  NG: {
    name: 'Murtala Muhammed International Airport (LOS)',
    website: 'https://www.faan.gov.ng/',
    email: 'info@faan.gov.ng',
    twitter: 'https://x.com/FAAN_Official',
    instagram: 'https://www.instagram.com/faan_official/',
    linkedin: 'https://www.linkedin.com/company/federal-airports-authority-of-nigeria/',
    apiEndpoint: '',
  },
  SN: {
    name: 'Blaise Diagne International Airport (DSS)',
    website: 'https://www.aibd.sn/',
    email: 'contact@aibd.sn',
    twitter: 'https://x.com/AIBD_Airport',
    instagram: 'https://www.instagram.com/aibd_airport/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-blaise-diagne/',
    apiEndpoint: '',
  },
  SL: {
    name: 'Freetown Lungi International Airport (FNA)',
    website: 'https://www.slac.gov.sl/',
    email: 'info@slac.gov.sl',
    twitter: 'https://x.com/SLAC_SierraLeone',
    instagram: 'https://www.instagram.com/slac_sierraleone/',
    linkedin: 'https://www.linkedin.com/company/sierra-leone-airports-authority/',
    apiEndpoint: '',
  },
  SO: {
    name: 'Aden Adde International Airport (MGQ)',
    website: 'https://www.scaa.gov.so/',
    email: 'info@scaa.gov.so',
    twitter: 'https://x.com/SCAA_Somalia',
    instagram: 'https://www.instagram.com/scaa_somalia/',
    linkedin: 'https://www.linkedin.com/company/somalia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  SD: {
    name: 'Khartoum International Airport (KRT)',
    website: 'https://www.krtairport.gov.sd/',
    email: 'info@krtairport.gov.sd',
    twitter: 'https://x.com/KRTAirport',
    instagram: 'https://www.instagram.com/krtairport/',
    linkedin: 'https://www.linkedin.com/company/khartoum-international-airport/',
    apiEndpoint: '',
  },
  TG: {
    name: 'Lomé-Tokoin International Airport (LFW)',
    website: 'https://www.aeroport-lome.tg/',
    email: 'contact@aeroport-lome.tg',
    twitter: 'https://x.com/AeroportLFW',
    instagram: 'https://www.instagram.com/aeroportlfw/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-lome/',
    apiEndpoint: '',
  },
  TN: {
    name: 'Tunis-Carthage International Airport (TUN)',
    website: 'https://www.oaca.nat.tn/',
    email: 'contact@oaca.nat.tn',
    twitter: 'https://x.com/OACA_Tunisia',
    instagram: 'https://www.instagram.com/oaca_tunisia/',
    linkedin: 'https://www.linkedin.com/company/office-de-l-aviation-civile-et-des-aeroports-oaca/',
    apiEndpoint: '',
  },
}
