import type { CensadMemberIsoCode } from './censadMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2 for
 * CEN-SAD (Community of Sahel-Saharan States) members (informational; verify against USGS
 * Mineral Commodity Summaries, BGS World Mineral Production, and UN Comtrade periodically).
 * Hydrocarbon-led economies (DZ-style: LY, NG, EG, TN, TD, SD) carry `Carbon (C)` + `Hydrogen (H)`;
 * gold-led Sahel economies (BF, ML, GH, CI, SD) carry `Gold (Au)`; bauxite-led GN carries
 * `Aluminum (Al)`; phosphate-led MA, SN, TG carry `Phosphorus (P)`.
 */
export const CENSAD_MAIN_EXPORTED_ELEMENTS: Record<CensadMemberIsoCode, MainExportedElements> = {
  BJ: e(
    'Calcium (Ca)',
    'Carbon (C)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Sodium (Na)',
  ),
  BF: e(
    'Gold (Au)',
    'Zinc (Zn)',
    'Manganese (Mn)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Phosphorus (P)',
    'Calcium (Ca)',
  ),
  CF: e(
    'Carbon (C)',
    'Gold (Au)',
    'Iron (Fe)',
    'Uranium (U)',
    'Copper (Cu)',
    'Manganese (Mn)',
    'Cobalt (Co)',
  ),
  TD: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Gold (Au)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  KM: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Magnesium (Mg)',
    'Sulfur (S)',
  ),
  DJ: e(
    'Sodium (Na)',
    'Chlorine (Cl)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Sulfur (S)',
  ),
  EG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Titanium (Ti)',
  ),
  ER: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Silver (Ag)',
    'Potassium (K)',
    'Iron (Fe)',
    'Sulfur (S)',
  ),
  GM: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Calcium (Ca)',
  ),
  GH: e(
    'Gold (Au)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Lithium (Li)',
    'Iron (Fe)',
  ),
  GN: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Carbon (C)',
    'Uranium (U)',
    'Copper (Cu)',
    'Calcium (Ca)',
  ),
  GW: e(
    'Phosphorus (P)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  CI: e(
    'Gold (Au)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Manganese (Mn)',
    'Nickel (Ni)',
    'Aluminum (Al)',
    'Iron (Fe)',
  ),
  LY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Potassium (K)',
    'Phosphorus (P)',
    'Calcium (Ca)',
  ),
  ML: e(
    'Gold (Au)',
    'Lithium (Li)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Phosphorus (P)',
  ),
  MR: e(
    'Iron (Fe)',
    'Gold (Au)',
    'Copper (Cu)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Sodium (Na)',
  ),
  MA: e(
    'Phosphorus (P)',
    'Fluorine (F)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Cobalt (Co)',
  ),
  NE: e(
    'Uranium (U)',
    'Gold (Au)',
    'Carbon (C)',
    'Iron (Fe)',
    'Tin (Sn)',
    'Phosphorus (P)',
    'Molybdenum (Mo)',
  ),
  NG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Tantalum (Ta)',
    'Niobium (Nb)',
    'Lead (Pb)',
    'Gold (Au)',
  ),
  SN: e(
    'Phosphorus (P)',
    'Gold (Au)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
  ),
  SL: e(
    'Iron (Fe)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Carbon (C)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Manganese (Mn)',
  ),
  SO: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Sodium (Na)',
    'Magnesium (Mg)',
  ),
  SD: e(
    'Gold (Au)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Chromium (Cr)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Sulfur (S)',
  ),
  TG: e(
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Carbon (C)',
  ),
  TN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Fluorine (F)',
  ),
}
