import type { CensadMemberIsoCode } from './censadMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per CEN-SAD member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const CENSAD_MAIN_INTERNATIONAL_SEAPORTS: Record<CensadMemberIsoCode, MainInternationalSeaport> = {
  BJ: seaport(
    'Port of Cotonou',
    'https://www.portdecotonou.com/',
    'contact@portdecotonou.com',
    'https://x.com/PortCotonou',
    'https://www.instagram.com/portcotonou/',
    'https://www.linkedin.com/company/port-autonome-de-cotonou/',
    'douanes@finances.bj',
    'https://www.douanes.bj',
    'Direction Générale des Douanes — Port de Cotonou, Cotonou, Benin',
  ),
  BF: seaport(
    'Port of Lomé (primary maritime gateway; landlocked)',
    'https://www.portdelome.tg/',
    'contact@portdelome.tg',
    'https://x.com/PortLome',
    'https://www.instagram.com/portdelome/',
    'https://www.linkedin.com/company/port-autonome-de-lome/',
    'douanes@finances.gov.bf',
    'https://www.douanes.gov.bf',
    'Direction Générale des Douanes, Ouagadougou, Burkina Faso',
  ),
  CF: seaport(
    'Port of Douala (primary maritime gateway; landlocked)',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.cf',
    'https://www.douanes-centrafrique.org',
    'Direction Générale des Douanes — Bangui, Central African Republic',
  ),
  TD: seaport(
    'Port of Douala (primary maritime gateway; landlocked)',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.td',
    'https://www.douanes.td',
    'Direction Générale des Douanes — N\'Djamena, Chad',
  ),
  KM: seaport(
    'Port of Moroni',
    'https://www.portcomores.km/',
    'info@portcomores.km',
    'https://x.com/PortComores',
    'https://www.instagram.com/portcomores/',
    'https://www.linkedin.com/company/port-autonome-des-comores/',
    'douanes@finances.km',
    'https://www.douanes.km',
    'Direction des Douanes — Port de Moroni, Moroni, Comoros',
  ),
  DJ: seaport(
    'Port of Djibouti',
    'https://www.portdedjibouti.com/',
    'contact@portdedjibouti.com',
    'https://x.com/PortDjibouti',
    'https://www.instagram.com/portdedjibouti/',
    'https://www.linkedin.com/company/port-de-djibouti/',
    'douanes@douanes.dj',
    'https://www.douanes.dj',
    'Direction Générale des Douanes — Port de Djibouti, Djibouti City, Djibouti',
  ),
  EG: seaport(
    'Port of Alexandria',
    'https://www.alexandria-port.com/',
    'info@alexandria-port.com',
    'https://x.com/AlexPortEgypt',
    'https://www.instagram.com/alexportegypt/',
    'https://www.linkedin.com/company/alexandria-port-authority/',
    'customs@customs.gov.eg',
    'https://www.customs.gov.eg',
    'Egyptian Customs Authority — Port of Alexandria, Alexandria, Egypt',
  ),
  ER: seaport(
    'Port of Massawa',
    'https://www.shabait.com/',
    'info@shabait.com',
    'https://x.com/shabait',
    'https://www.instagram.com/shabait/',
    'https://www.linkedin.com/company/eritrean-ports/',
    'customs@shabait.com',
    'https://www.shabait.com',
    'Eritrean Customs — Port of Massawa, Massawa, Eritrea',
  ),
  GM: seaport(
    'Port of Banjul',
    'https://www.gambiaports.gm/',
    'info@gambiaports.gm',
    'https://x.com/GambiaPorts',
    'https://www.instagram.com/gambiaports/',
    'https://www.linkedin.com/company/gambia-ports-authority/',
    'info@gra.gm',
    'https://www.gra.gm',
    'Gambia Revenue Authority — Customs, Port of Banjul, Banjul, The Gambia',
  ),
  GH: seaport(
    'Port of Tema',
    'https://www.ghanaports.gov.gh/',
    'info@ghanaports.gov.gh',
    'https://x.com/GhanaPorts',
    'https://www.instagram.com/ghanaports/',
    'https://www.linkedin.com/company/ghana-ports-and-harbours-authority/',
    'info@gra.gov.gh',
    'https://www.gra.gov.gh',
    'Ghana Revenue Authority — Customs Division, Port of Tema, Tema, Ghana',
  ),
  GN: seaport(
    'Port of Conakry',
    'https://www.otal.com/guinea/port-of-conakry',
    'contact@portconakry.gn',
    'https://x.com/PortConakry',
    'https://www.instagram.com/portconakry/',
    'https://www.linkedin.com/company/port-autonome-de-conakry/',
    'douanes@finances.gov.gn',
    'https://www.douanes.gov.gn',
    'Direction Générale des Douanes — Port de Conakry, Conakry, Guinea',
  ),
  GW: seaport(
    'Port of Bissau',
    'https://www.portobissau.gw/',
    'info@portobissau.gw',
    'https://x.com/PortBissau',
    'https://www.instagram.com/portbissau/',
    'https://www.linkedin.com/company/porto-de-bissau/',
    'aduaneira@mf.gov.gw',
    'https://www.aduaneira.gov.gw',
    'Alfândega Nacional — Porto de Bissau, Bissau, Guinea-Bissau',
  ),
  CI: seaport(
    'Port of Abidjan',
    'https://www.portabidjan.com/',
    'contact@portabidjan.com',
    'https://x.com/PortAbidjan',
    'https://www.instagram.com/portabidjan/',
    'https://www.linkedin.com/company/port-autonome-d-abidjan/',
    'douanes@dgi.gouv.ci',
    'https://www.douanes.ci',
    'Direction Générale des Douanes — Port d\'Abidjan, Abidjan, Côte d\'Ivoire',
  ),
  LY: seaport(
    'Port of Tripoli',
    'https://www.lpc.ly/',
    'info@lpc.ly',
    'https://x.com/LibyanPorts',
    'https://www.instagram.com/libyanports/',
    'https://www.linkedin.com/company/libyan-ports-corporation/',
    'customs@customs.gov.ly',
    'https://www.customs.gov.ly',
    'Libyan Customs Authority — Port of Tripoli, Tripoli, Libya',
  ),
  ML: seaport(
    'Port of Dakar (primary maritime gateway; landlocked)',
    'https://www.portdedakar.sn/',
    'contact@portdedakar.sn',
    'https://x.com/PortDakar',
    'https://www.instagram.com/portdedakar/',
    'https://www.linkedin.com/company/port-autonome-de-dakar/',
    'douanes@finances.ml',
    'https://www.douanes.ml',
    'Direction Générale des Douanes — Bamako, Mali',
  ),
  MR: seaport(
    'Port of Nouadhibou',
    'https://www.otal.com/mauritania/port-of-nouadhibou',
    'contact@portnouadhibou.mr',
    'https://x.com/PortNouadhibou',
    'https://www.instagram.com/portnouadhibou/',
    'https://www.linkedin.com/company/port-de-nouadhibou/',
    'douanes@finances.gov.mr',
    'https://www.douanes.gov.mr',
    'Direction Générale des Douanes — Port de Nouadhibou, Nouadhibou, Mauritania',
  ),
  MA: seaport(
    'Port of Tanger Med',
    'https://www.tangermed.ma/',
    'contact@tangermed.ma',
    'https://x.com/TangerMed',
    'https://www.instagram.com/tangermed/',
    'https://www.linkedin.com/company/tanger-med/',
    'douane@douane.gov.ma',
    'https://www.douane.gov.ma',
    'Administration des Douanes — Tanger Med, Tanger, Morocco',
  ),
  NE: seaport(
    'Port of Cotonou (primary maritime gateway; landlocked)',
    'https://www.portdecotonou.com/',
    'contact@portdecotonou.com',
    'https://x.com/PortCotonou',
    'https://www.instagram.com/portcotonou/',
    'https://www.linkedin.com/company/port-autonome-de-cotonou/',
    'douanes@finances.ne',
    'https://www.douanes.ne',
    'Direction Générale des Douanes — Niamey, Niger',
  ),
  NG: seaport(
    'Port of Lagos (Apapa)',
    'https://www.npa.gov.ng/',
    'info@npa.gov.ng',
    'https://x.com/NPA_Nigeria',
    'https://www.instagram.com/npa_nigeria/',
    'https://www.linkedin.com/company/nigerian-ports-authority/',
    'customs@customs.gov.ng',
    'https://www.customs.gov.ng',
    'Nigeria Customs Service — Apapa Port, Lagos, Nigeria',
  ),
  SN: seaport(
    'Port of Dakar',
    'https://www.portdedakar.sn/',
    'contact@portdedakar.sn',
    'https://x.com/PortDakar',
    'https://www.instagram.com/portdedakar/',
    'https://www.linkedin.com/company/port-autonome-de-dakar/',
    'douanes@finances.sn',
    'https://www.douanes.sn',
    'Direction Générale des Douanes — Port de Dakar, Dakar, Senegal',
  ),
  SL: seaport(
    'Port of Freetown',
    'https://www.slpa.sl/',
    'info@slpa.sl',
    'https://x.com/SLPA_Freetown',
    'https://www.instagram.com/slpa_freetown/',
    'https://www.linkedin.com/company/sierra-leone-ports-authority/',
    'customs@nra.gov.sl',
    'https://www.nra.gov.sl',
    'National Revenue Authority — Customs, Port of Freetown, Freetown, Sierra Leone',
  ),
  SO: seaport(
    'Port of Mogadishu',
    'https://www.mpa.gov.so/',
    'info@mpa.gov.so',
    'https://x.com/MPA_Somalia',
    'https://www.instagram.com/mpa_somalia/',
    'https://www.linkedin.com/company/mogadishu-port-authority/',
    'customs@finance.gov.so',
    'https://www.customs.gov.so',
    'Somalia Customs — Port of Mogadishu, Mogadishu, Somalia',
  ),
  SD: seaport(
    'Port Sudan',
    'https://www.spc.sd/',
    'info@spc.sd',
    'https://x.com/SPC_Sudan',
    'https://www.instagram.com/spc_sudan/',
    'https://www.linkedin.com/company/sea-ports-corporation-sudan/',
    'customs@customs.gov.sd',
    'https://www.customs.gov.sd',
    'Sudan Customs Authority — Port Sudan, Port Sudan, Sudan',
  ),
  TG: seaport(
    'Port of Lomé',
    'https://www.portdelome.tg/',
    'contact@portdelome.tg',
    'https://x.com/PortLome',
    'https://www.instagram.com/portdelome/',
    'https://www.linkedin.com/company/port-autonome-de-lome/',
    'douanes@finances.tg',
    'https://www.douanes.tg',
    'Direction Générale des Douanes — Port de Lomé, Lomé, Togo',
  ),
  TN: seaport(
    'Port of Rades',
    'https://www.ommp.nat.tn/',
    'contact@ommp.nat.tn',
    'https://x.com/OMMP_Tunisia',
    'https://www.instagram.com/ommp_tunisia/',
    'https://www.linkedin.com/company/ommp-tunisia/',
    'douane@douane.gov.tn',
    'https://www.douane.gov.tn',
    'Direction Générale des Douanes — Port de Radès, Radès, Tunisia',
  ),
}
