import type { CensadMemberIsoCode } from './censadMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const CENSAD_MAIN_EXPORT_COMMODITIES: Record<CensadMemberIsoCode, MainExportCommodities> = {
  BJ: m(
    'Cotton',
    'Gold',
    'Cashew nuts',
    'Refined petroleum',
    'Palm oil',
    'Soybeans',
    'Maize',
  ),
  BF: m(
    'Gold',
    'Cotton',
    'Oil seeds',
    'Zinc ore',
    'Sesame seeds',
    'Fruits and nuts',
    'Livestock',
  ),
  CF: m(
    'Gold',
    'Diamonds',
    'Timber',
    'Cotton',
    'Hides and skins',
    'Sesame seeds',
    'Coffee',
  ),
  TD: m(
    'Crude petroleum',
    'Cotton',
    'Livestock',
    'Gum arabic',
    'Sesame seeds',
    'Gold',
    'Hides and skins',
  ),
  KM: m(
    'Vanilla',
    'Cloves',
    'Ylang-ylang',
    'Fish',
    'Essential oils',
    'Copra',
    'Pepper',
  ),
  DJ: m(
    'Live animals',
    'Coffee',
    'Hides and skins',
    'Salt',
    'Scrap metal',
    'Re-exported goods',
    'Petroleum re-exports',
  ),
  EG: m(
    'Refined petroleum',
    'Natural gas',
    'Gold',
    'Fertilizers',
    'Textiles and garments',
    'Citrus fruit',
    'Aluminum',
  ),
  ER: m(
    'Copper ore',
    'Gold',
    'Livestock',
    'Textiles',
    'Food products',
    'Salt',
    'Hides and skins',
  ),
  GM: m(
    'Groundnuts',
    'Fish',
    'Cotton',
    'Timber',
    'Palm kernels',
    'Petroleum products',
    'Re-exported goods',
  ),
  GH: m(
    'Gold',
    'Crude petroleum',
    'Cocoa',
    'Cashew nuts',
    'Manganese ore',
    'Oil seeds',
    'Refined petroleum',
  ),
  GN: m(
    'Gold',
    'Bauxite',
    'Aluminum',
    'Diamonds',
    'Palm oil',
    'Coffee',
    'Fruits',
  ),
  GW: m(
    'Cashew nuts',
    'Fish',
    'Gold',
    'Timber',
    'Palm oil',
    'Cotton',
    'Peanuts',
  ),
  CI: m(
    'Cocoa',
    'Gold',
    'Refined petroleum',
    'Rubber',
    'Cashew nuts',
    'Cotton',
    'Palm oil',
  ),
  LY: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Fertilizers',
    'Hydrocarbon derivatives',
    'Dates',
    'Wheat',
  ),
  ML: m(
    'Gold',
    'Cotton',
    'Livestock',
    'Salt',
    'Sesame seeds',
    'Fruits',
    'Shea nuts',
  ),
  MR: m(
    'Iron ore',
    'Gold',
    'Fish',
    'Copper',
    'Gypsum',
    'Crude petroleum',
    'Livestock',
  ),
  MA: m(
    'Automobiles',
    'Fertilizers',
    'Phosphates',
    'Electrical components',
    'Textiles',
    'Citrus fruit',
    'Fish',
  ),
  NE: m(
    'Uranium',
    'Gold',
    'Livestock',
    'Onions',
    'Cowpeas',
    'Sesame seeds',
    'Crude petroleum',
  ),
  NG: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Cocoa',
    'Fertilizers',
    'Sesame seeds',
    'Gold',
  ),
  SN: m(
    'Refined petroleum',
    'Gold',
    'Fish',
    'Phosphates',
    'Groundnuts',
    'Cement',
    'Titanium ore',
  ),
  SL: m(
    'Iron ore',
    'Diamonds',
    'Rutile',
    'Cocoa',
    'Coffee',
    'Fish',
    'Timber',
  ),
  SO: m(
    'Livestock',
    'Charcoal',
    'Fish',
    'Gold',
    'Sesame seeds',
    'Bananas',
    'Hides and skins',
  ),
  SD: m(
    'Gold',
    'Crude petroleum',
    'Livestock',
    'Sesame seeds',
    'Cotton',
    'Gum arabic',
    'Sheep',
  ),
  TG: m(
    'Crude petroleum',
    'Re-exported goods',
    'Cocoa',
    'Phosphates',
    'Cotton',
    'Coffee',
    'Refined petroleum',
  ),
  TN: m(
    'Electrical components',
    'Olive oil',
    'Textiles',
    'Phosphates',
    'Dates',
    'Fish',
    'Hydrocarbons',
  ),
}
