import type { NationalBankingInstitution } from './types'
import type { CensadMemberIsoCode } from './censadMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per CEN-SAD member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const CENSAD_NATIONAL_BANKING_INSTITUTIONS: Record<
  CensadMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  BJ: [
    bank(
      'Ecobank Benin',
      '+229 21 31 31 00',
      'Boulevard Saint-Michel, Cotonou, Benin',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/bj',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCBJBJ',
      '',
    ),
    bank(
      'Bank of Africa Benin (BOA-Benin)',
      '+229 21 31 32 82',
      'Avenue Jean-Paul II, Cotonou, Benin',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boabenin.com/',
      'contact@boabenin.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      'AFRIBJBJ',
      '',
    ),
    bank(
      'Banque Atlantique Benin',
      '+229 21 31 10 18',
      'Boulevard de la Marina, Cotonou, Benin',
      '',
      '',
      'https://www.banqueatlantique.net/',
      'contact@banqueatlantique.net',
      '',
      '',
      'https://www.linkedin.com/company/banque-atlantique/',
      '',
      '',
      '',
    ),
  ],
  BF: [
    bank(
      'Coris Bank International (CBI)',
      '+226 25 37 77 77',
      'Avenue Kwame N\'Krumah, Ouagadougou 01 BP 5487, Burkina Faso',
      '',
      'https://play.google.com/store/apps/details?id=com.coris.mobile',
      'https://www.corisbank.com/',
      'contact@corisbank.com',
      'https://x.com/CorisBank',
      'https://www.instagram.com/corisbank/',
      'https://www.linkedin.com/company/coris-bank-international/',
      '',
      '',
      '',
    ),
    bank(
      'Ecobank Burkina Faso',
      '+226 25 30 62 30',
      'Avenue Kwame N\'Krumah, Ouagadougou 01 BP 4540, Burkina Faso',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/bf',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Bank of Africa Burkina Faso (BOA-BF)',
      '+226 25 31 28 28',
      'Avenue de la Nation, Ouagadougou 01 BP 5139, Burkina Faso',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boa-bf.com/',
      'contact@boa-bf.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      '',
      '',
    ),
  ],
  CF: [
    bank(
      'Ecobank Centrafrique',
      '+236 21 61 45 23',
      'Avenue des Martyrs, Bangui, Central African Republic',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/cf',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Banque Populaire Maroco-Centrafricaine',
      '+236 21 61 62 30',
      'Avenue de l Independance, Bangui, Central African Republic',
      '',
      '',
      'https://www.bpmc-rca.com/',
      'contact@bpmc-rca.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'BGFI Bank Centrafrique',
      '+236 21 61 33 00',
      'Boulevard Charles de Gaulle, Bangui, Central African Republic',
      '',
      '',
      'https://www.bgfibank.com/',
      'contact@bgfibank.com',
      '',
      '',
      'https://www.linkedin.com/company/bgfi-holding-corporation/',
      '',
      'BGFICFCF',
      '',
    ),
  ],
  TD: [
    bank(
      'Ecobank Tchad',
      '+235 22 51 51 10',
      'Avenue Charles de Gaulle, N Djamena, Chad',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/td',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCTDTD',
      '',
    ),
    bank(
      'Orabank Tchad',
      '+235 22 52 52 52',
      'Avenue du General Malloum, N Djamena, Chad',
      '',
      '',
      'https://www.orabank.net/',
      'contact@orabank.net',
      '',
      '',
      'https://www.linkedin.com/company/orabank/',
      '',
      '',
      '',
    ),
    bank(
      'Commercial Bank Tchad',
      '+235 22 53 44 44',
      'Boulevard de Gaulle, N Djamena, Chad',
      '',
      '',
      'https://www.cbtchad.com/',
      'contact@cbtchad.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  KM: [
    bank(
      'Banque Federale de Commerce (BFC)',
      '+269 773 20 00',
      'Place de France, Moroni, Comoros',
      '',
      '',
      'https://www.bfc-comores.com/',
      'contact@bfc-comores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Exim Bank Comores',
      '+269 773 25 25',
      'Avenue de la Corniche, Moroni, Comoros',
      '',
      '',
      'https://www.eximbankcomores.com/',
      'info@eximbankcomores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'SNPSF',
      '+269 773 18 18',
      'Avenue Ali Soilih, Moroni, Comoros',
      '',
      '',
      'https://www.snpsf.com/',
      'contact@snpsf.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  DJ: [
    bank(
      'CAC International Bank',
      '+253 21 32 22 22',
      'Place Menelik, Djibouti City, Djibouti',
      '',
      '',
      'https://www.cacbankdj.com/',
      'contact@cacbankdj.com',
      '',
      '',
      'https://www.linkedin.com/company/cac-international-bank/',
      '',
      'CACBDJDJ',
      '',
    ),
    bank(
      'Salaam African Bank',
      '+253 21 35 55 55',
      'Avenue Hassan Gouled, Djibouti City, Djibouti',
      '',
      '',
      'https://www.salaam-bank.com/',
      'info@salaam-bank.com',
      '',
      '',
      'https://www.linkedin.com/company/salaam-african-bank/',
      '',
      '',
      '',
    ),
    bank(
      'BCIMR',
      '+253 21 35 30 30',
      'Place Lagarde, Djibouti City, Djibouti',
      '',
      '',
      'https://www.bcimr.dj/',
      'contact@bcimr.dj',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  EG: [
    bank(
      'National Bank of Egypt',
      '+20 2 2576 0777',
      '1187 Corniche El Nil, Cairo, Egypt',
      '',
      '',
      'https://www.nbe.com.eg/',
      'customer.service@nbe.com.eg',
      '',
      '',
      'https://www.linkedin.com/company/national-bank-of-egypt/',
      '',
      'NBEGEGCX',
      '',
    ),
    bank(
      'Banque Misr',
      '+20 2 19888',
      '151 Mohamed Farid St, Cairo, Egypt',
      '',
      '',
      'https://www.banquemisr.com/',
      'customercare@banquemisr.com',
      '',
      '',
      'https://www.linkedin.com/company/banque-misr/',
      '',
      'BMISEGCX',
      '',
    ),
    bank(
      'Commercial International Bank (CIB)',
      '+20 2 19666',
      '21/23 Charles de Gaulle St, Giza, Egypt',
      '',
      '',
      'https://www.cibeg.com/',
      'customer.care@cibeg.com',
      '',
      '',
      'https://www.linkedin.com/company/cibegypt/',
      '',
      'CIBEEGCX',
      '',
    ),
  ],
  ER: [
    bank(
      'Commercial Bank of Eritrea',
      '+291 1 182 251',
      'Harnet Avenue, Asmara, Eritrea',
      '',
      '',
      'https://www.combank-er.com/',
      'info@combank-er.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Housing and Commerce Bank Eritrea',
      '+291 1 181 166',
      'Godaif Street, Asmara, Eritrea',
      '',
      '',
      'https://www.hcb-er.com/',
      'info@hcb-er.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Eritrean Investment and Development Bank',
      '+291 1 181 399',
      'Sematat Avenue, Asmara, Eritrea',
      '',
      '',
      'https://www.eidb-er.com/',
      'info@eidb-er.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  GM: [
    bank(
      'Trust Bank Gambia',
      '+220 439 5136',
      '7 Ecowas Avenue, Banjul, The Gambia',
      '',
      '',
      'https://www.trustbankgambia.com/',
      'info@trustbankgambia.com',
      '',
      '',
      'https://www.linkedin.com/company/trust-bank-limited-gambia/',
      '',
      'TBLIGMGM',
      '',
    ),
    bank(
      'Ecobank Gambia',
      '+220 439 9600',
      'Kairaba Avenue, Serrekunda, The Gambia',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/gm',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCGMGM',
      '',
    ),
    bank(
      'AGIB Bank',
      '+220 422 4465',
      'Hagan Street, Banjul, The Gambia',
      '',
      '',
      'https://www.agib.gm/',
      'info@agib.gm',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  GH: [
    bank(
      'GCB Bank',
      '+233 302 664910',
      'Thorpe Road, Accra, Ghana',
      '',
      '',
      'https://www.gcbbank.com.gh/',
      'customerservice@gcbbank.com.gh',
      '',
      '',
      'https://www.linkedin.com/company/gcb-bank-limited/',
      '',
      'GHCBGHAC',
      '',
    ),
    bank(
      'Ecobank Ghana',
      '+233 302 213999',
      '2 Morocco Lane, Accra, Ghana',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/gh',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCGHAC',
      '',
    ),
    bank(
      'Absa Bank Ghana',
      '+233 302 429150',
      'Absa House, High Street, Accra, Ghana',
      '',
      '',
      'https://www.absa.com.gh/',
      'absa.gh@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCGHAC',
      '',
    ),
  ],
  GN: [
    bank(
      'Ecobank Guinea',
      '+224 622 50 08 08',
      'Avenue de la Republique, Conakry, Guinea',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/gn',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCGNGN',
      '',
    ),
    bank(
      'VistaGui Bank',
      '+224 628 68 68 68',
      'Kaloum, Conakry, Guinea',
      '',
      '',
      'https://www.vistabankgroup.com/',
      'contact@vistabankgroup.com',
      '',
      '',
      'https://www.linkedin.com/company/vista-bank-group/',
      '',
      '',
      '',
    ),
    bank(
      'UBA Guinea',
      '+224 622 95 11 11',
      'Avenue de la Republique, Conakry, Guinea',
      '',
      '',
      'https://www.ubagroup.com/',
      'cfc@ubagroup.com',
      '',
      '',
      'https://www.linkedin.com/company/united-bank-for-africa/',
      '',
      '',
      '',
    ),
  ],
  GW: [
    bank(
      'Banco da Africa Ocidental (BAO)',
      '+245 955 111 111',
      'Avenida Amilcar Cabral, Bissau, Guinea-Bissau',
      '',
      '',
      'https://www.bao.gw/',
      'contacto@bao.gw',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Ecobank Guinea-Bissau',
      '+245 955 555 555',
      'Avenida dos Combatentes, Bissau, Guinea-Bissau',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/gw',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Banco da Uniao (BDU)',
      '+245 966 666 666',
      'Praza Che Guevara, Bissau, Guinea-Bissau',
      '',
      '',
      'https://www.bdu-gw.com/',
      'info@bdu-gw.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  CI: [
    bank(
      'Societe Generale Cote d Ivoire (SGCI)',
      '+225 27 20 20 10 10',
      'Immeuble Alpha 2000, Plateau, Abidjan, Cote d Ivoire',
      '',
      '',
      'https://www.sgci.ci/',
      'contacts@sgci.ci',
      '',
      '',
      'https://www.linkedin.com/company/soci%C3%A9t%C3%A9-g%C3%A9n%C3%A9rale-c%C3%B4te-d-ivoire/',
      '',
      'SOGECICI',
      '',
    ),
    bank(
      'BICICI',
      '+225 27 20 20 30 00',
      'Avenue Franchet d Esperey, Plateau, Abidjan, Cote d Ivoire',
      '',
      '',
      'https://www.bicici.com/',
      'contact@bicici.com',
      '',
      '',
      'https://www.linkedin.com/company/bicici/',
      '',
      'BICICICI',
      '',
    ),
    bank(
      'Ecobank Cote d Ivoire',
      '+225 27 20 31 59 00',
      'Avenue Houdaille, Plateau, Abidjan, Cote d Ivoire',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/ci',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCCICI',
      '',
    ),
  ],
  LY: [
    bank(
      'Wahda Bank',
      '+218 21 333 5511',
      'Omar Mukhtar Street, Tripoli, Libya',
      '',
      '',
      'https://wahdabank.ly/',
      'info@wahdabank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Jumhouria Bank',
      '+218 21 360 2000',
      'Al Fatah Street, Tripoli, Libya',
      '',
      '',
      'https://www.jbank.ly/',
      'info@jbank.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'National Commercial Bank Libya',
      '+218 21 444 9200',
      'September 1st Street, Tripoli, Libya',
      '',
      '',
      'https://www.ncb.ly/',
      'info@ncb.ly',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  ML: [
    bank(
      'Bank of Africa Mali (BOA Mali)',
      '+223 20 22 33 44',
      'Avenue du Mali, Bamako BP E 2798, Mali',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boamali.com/',
      'contact@boamali.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      '',
      '',
    ),
    bank(
      'Ecobank Mali',
      '+223 20 22 99 99',
      'Avenue du Mali, Bamako BP 224, Mali',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/ml',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Banque de Developpement du Mali (BDM)',
      '+223 20 22 12 12',
      'Avenue Modibo Keita, Bamako BP 224, Mali',
      '',
      'https://play.google.com/store/apps/details?id=com.bdm.mobile',
      'https://www.bdm.ml/',
      'contact@bdm.ml',
      '',
      '',
      'https://www.linkedin.com/company/banque-de-d%C3%A9veloppement-du-mali/',
      '',
      '',
      '',
    ),
  ],
  MR: [
    bank(
      'Banque Mauritanienne pour le Commerce International (BMCI)',
      '+222 45 29 11 22',
      'Avenue Gamal Abdel Nasser, Nouakchott, Mauritania',
      '',
      '',
      'https://www.bmci.mr/',
      'contact@bmci.mr',
      '',
      '',
      '',
      '',
      'BMCIMRMR',
      '',
    ),
    bank(
      'Banque El Amana',
      '+222 45 25 55 55',
      'Tevragh Zeina, Nouakchott, Mauritania',
      '',
      '',
      'https://www.elamana-bank.mr/',
      'info@elamana-bank.mr',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Societe Generale Mauritanie',
      '+222 45 29 33 33',
      'Ilot K, Nouakchott, Mauritania',
      '',
      '',
      'https://www.societegenerale.mr/',
      'contact@societegenerale.mr',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  MA: [
    bank(
      'Attijariwafa bank',
      '+212 5 22 58 88 88',
      '2 Boulevard Moulay Youssef, Casablanca, Morocco',
      '',
      '',
      'https://www.attijariwafabank.com/',
      'contact@attijariwafa.com',
      '',
      '',
      'https://www.linkedin.com/company/attijariwafa-bank/',
      '',
      'BCMAMAMC',
      '',
    ),
    bank(
      'Banque Populaire du Maroc',
      '+212 5 22 20 25 25',
      '101 Boulevard Mohamed Zerktouni, Casablanca, Morocco',
      '',
      '',
      'https://www.gbp.ma/',
      'relationclient@gbp.ma',
      '',
      '',
      'https://www.linkedin.com/company/banque-populaire-maroc/',
      '',
      'BCPOMAMC',
      '',
    ),
    bank(
      'Bank of Africa Maroc',
      '+212 5 22 46 90 00',
      '140 Avenue Hassan II, Casablanca, Morocco',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.bankofafrica.ma/',
      'relationclient@bankofafrica.ma',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      'BMCEMAMC',
      '',
    ),
  ],
  NE: [
    bank(
      'Ecobank Niger',
      '+227 20 73 20 20',
      'Avenue du General de Gaulle, Niamey BP 11207, Niger',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/ne',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Banque Commerciale du Niger (BCN)',
      '+227 20 73 33 33',
      'Avenue du General de Gaulle, Niamey BP 11207, Niger',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boa-ne.com/',
      'contact@boa-ne.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      '',
      '',
    ),
    bank(
      'BIA-Niger (Banque Internationale pour l Afrique au Niger)',
      '+227 20 73 11 11',
      'Rue du Commerce, Niamey BP 10966, Niger',
      '',
      'https://play.google.com/store/apps/details?id=com.bianiger.mobile',
      'https://www.bianiger.com/',
      'contact@bianiger.com',
      '',
      '',
      'https://www.linkedin.com/company/bia-niger/',
      '',
      '',
      '',
    ),
  ],
  NG: [
    bank(
      'Access Bank Nigeria',
      '+234 1 271 2005',
      '14/15 Prince Alaba Oniru St, Victoria Island, Lagos, Nigeria',
      '',
      '',
      'https://www.accessbankplc.com/',
      'contactcenter@accessbankplc.com',
      '',
      '',
      'https://www.linkedin.com/company/access-bank-plc/',
      '',
      'ABNGNGLA',
      '',
    ),
    bank(
      'First Bank of Nigeria',
      '+234 1 905 2326',
      'Samuel Asabia House, 35 Marina, Lagos, Nigeria',
      '',
      '',
      'https://www.firstbanknigeria.com/',
      'firstcontact@firstbanknigeria.com',
      '',
      '',
      'https://www.linkedin.com/company/first-bank-of-nigeria-limited/',
      '',
      'FBNINGLA',
      '',
    ),
    bank(
      'Zenith Bank Nigeria',
      '+234 1 278 7000',
      'Plot 84 Ajose Adeogun St, Victoria Island, Lagos, Nigeria',
      '',
      '',
      'https://www.zenithbank.com/',
      'zenithdirect@zenithbank.com',
      '',
      '',
      'https://www.linkedin.com/company/zenith-bank-plc/',
      '',
      'ZEIBNGLA',
      '',
    ),
  ],
  SN: [
    bank(
      'CBAO Groupe Attijariwafa Bank',
      '+221 33 889 6800',
      '1 Place de l Independance, Dakar, Senegal',
      '',
      '',
      'https://www.cbao.sn/',
      'contact@cbao.sn',
      '',
      '',
      'https://www.linkedin.com/company/cbao-groupe-attijariwafa-bank/',
      '',
      'CBAOSNDA',
      '',
    ),
    bank(
      'Societe Generale Senegal',
      '+221 33 839 5500',
      '19 Avenue Nelson Mandela, Dakar, Senegal',
      '',
      '',
      'https://www.societegenerale.sn/',
      'relation.client@socgen.com',
      '',
      '',
      'https://www.linkedin.com/company/soci%C3%A9t%C3%A9-g%C3%A9n%C3%A9rale-s%C3%A9n%C3%A9gal/',
      '',
      'SOGESNDA',
      '',
    ),
    bank(
      'Ecobank Senegal',
      '+221 33 889 8300',
      'Boulevard de la Republique, Dakar, Senegal',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/sn',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCSNDA',
      '',
    ),
  ],
  SL: [
    bank(
      'Sierra Leone Commercial Bank',
      '+232 76 600 000',
      '23 Siaka Stevens St, Freetown, Sierra Leone',
      '',
      '',
      'https://www.slcb.sl/',
      'info@slcb.sl',
      '',
      '',
      'https://www.linkedin.com/company/sierra-leone-commercial-bank/',
      '',
      'SLCBSLSL',
      '',
    ),
    bank(
      'Rokel Commercial Bank',
      '+232 76 555 555',
      '1 Wallace Johnson St, Freetown, Sierra Leone',
      '',
      '',
      'https://www.rokelbank.com/',
      'info@rokelbank.com',
      '',
      '',
      'https://www.linkedin.com/company/rokel-commercial-bank/',
      '',
      'ROKLSLSL',
      '',
    ),
    bank(
      'Ecobank Sierra Leone',
      '+232 77 986 986',
      '35 Lightfoot Boston St, Freetown, Sierra Leone',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/sl',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCSLSL',
      '',
    ),
  ],
  SO: [
    bank(
      'Salaam Somali Bank',
      '+252 61 700 0000',
      'KM4, Mogadishu, Somalia',
      '',
      '',
      'https://www.salaambank.so/',
      'info@salaambank.so',
      '',
      '',
      'https://www.linkedin.com/company/salaam-somali-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Premier Bank Somalia',
      '+252 61 222 1111',
      'Airport Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.premierbank.so/',
      'info@premierbank.so',
      '',
      '',
      'https://www.linkedin.com/company/premier-bank-somalia/',
      '',
      '',
      '',
    ),
    bank(
      'Dahabshiil Bank International',
      '+252 63 333 3000',
      'Maka Al Mukarama Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.dahabshiilbank.com/',
      'info@dahabshiilbank.com',
      '',
      '',
      'https://www.linkedin.com/company/dahabshiil-bank-international/',
      '',
      '',
      '',
    ),
  ],
  SD: [
    bank(
      'Bank of Khartoum',
      '+249 183 782 000',
      'Mek Nimir Ave, Khartoum, Sudan',
      '',
      '',
      'https://bankofkhartoum.com/',
      'contactus@bok.sd',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-khartoum/',
      '',
      'BOKHSDKH',
      '',
    ),
    bank(
      'Omdurman National Bank',
      '+249 183 783 200',
      'Baladia Street, Khartoum, Sudan',
      '',
      '',
      'https://www.onb-sd.com/',
      'info@onb-sd.com',
      '',
      '',
      '',
      '',
      'ONBKSDKH',
      '',
    ),
    bank(
      'Faisal Islamic Bank Sudan',
      '+249 183 774 000',
      'Al Gamhouria Street, Khartoum, Sudan',
      '',
      '',
      'https://www.fibsudan.com/',
      'info@fibsudan.com',
      '',
      '',
      'https://www.linkedin.com/company/faisal-islamic-bank-sudan/',
      '',
      'FIBSSDKH',
      '',
    ),
  ],
  TG: [
    bank(
      'Ecobank Togo',
      '+228 22 53 55 00',
      '2 Rue du Commerce, Lome, Togo',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/tg',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCTGTG',
      '',
    ),
    bank(
      'Orabank Togo',
      '+228 22 21 72 72',
      '3613 Boulevard du 13 Janvier, Lome, Togo',
      '',
      '',
      'https://www.orabank.net/',
      'contact@orabank.net',
      '',
      '',
      'https://www.linkedin.com/company/orabank/',
      '',
      'ORBKTGTG',
      '',
    ),
    bank(
      'Banque Togolaise pour le Commerce et l Industrie (BTCI)',
      '+228 22 21 58 58',
      'Rue du Commerce, Lome, Togo',
      '',
      '',
      'https://www.btci.tg/',
      'contact@btci.tg',
      '',
      '',
      '',
      '',
      'BTKITGTG',
      '',
    ),
  ],
  TN: [
    bank(
      'Banque Internationale Arabe de Tunisie (BIAT)',
      '+216 71 155 000',
      '70-72 Avenue Habib Bourguiba, Tunis, Tunisia',
      '',
      '',
      'https://www.biat.com.tn/',
      'contact@biat.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/biat/',
      '',
      'BIATTNTT',
      '',
    ),
    bank(
      'Amen Bank',
      '+216 71 148 000',
      'Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.amenbank.com.tn/',
      'relationclientele@amenbank.com.tn',
      '',
      '',
      'https://www.linkedin.com/company/amen-bank/',
      '',
      'CFCTTNTT',
      '',
    ),
    bank(
      'BH Bank',
      '+216 71 126 000',
      '18 Avenue Mohamed V, Tunis, Tunisia',
      '',
      '',
      'https://www.bhbank.tn/',
      'contact@bhbank.tn',
      '',
      '',
      'https://www.linkedin.com/company/bh-bank/',
      '',
      'BHBKTNTT',
      '',
    ),
  ],
}
