import type { IoraMemberIsoCode } from './ioraMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per IORA member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const IORA_DOMESTIC_POST_SERVICES: Record<IoraMemberIsoCode, DomesticPostService> = {
  AU: post(
    'Australia Post',
    'https://auspost.com.au/',
    'feedback@auspost.com.au',
    'https://x.com/AusPost',
    'https://www.instagram.com/auspost/',
    'https://www.linkedin.com/company/australia-post/',
    'https://developers.auspost.com.au/',
    'NNNN',
    '^\\d{4}$',
    '2000',
    'Four-digit postcode',
  ),
  BD: post(
    'Bangladesh Post Office',
    'https://bdpost.gov.bd/',
    'info@bdpost.gov.bd',
    'https://x.com/BangladeshPost',
    '',
    'https://www.linkedin.com/company/bangladesh-post-office/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  KM: post(
    'Comores Poste',
    'https://poste-comores.com/',
    'contact@poste-comores.km',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and village addressing',
  ),
  FR: post(
    'La Poste',
    'https://www.laposte.fr/',
    'contact@laposte.fr',
    'https://x.com/laposte',
    'https://www.instagram.com/laposte/',
    'https://www.linkedin.com/company/la-poste/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '75001',
    'Five-digit code postal',
  ),
  IN: post(
    'India Post',
    'https://www.indiapost.gov.in/',
    'helpdesk@indiapost.gov.in',
    'https://x.com/IndiaPostOffice',
    'https://www.instagram.com/indiapostoffice/',
    'https://www.linkedin.com/company/india-post/',
    'https://www.indiapost.gov.in/',
    'NNNNNN',
    '^\\d{6}$',
    '110001',
    'Six-digit PIN code',
  ),
  ID: post(
    'Pos Indonesia',
    'https://www.posindonesia.co.id/',
    'pusatbantuan@posindonesia.co.id',
    'https://x.com/PosIndonesia',
    'https://www.instagram.com/posindonesia/',
    'https://www.linkedin.com/company/pos-indonesia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10110',
    'Five-digit postcode',
  ),
  IR: post(
    'Iran Post (Pishtaz)',
    'https://www.post.ir/',
    'info@post.ir',
    'https://x.com/IranPost',
    '',
    'https://www.linkedin.com/company/iran-post/',
    '',
    'NNNNN-NNNNN',
    '^\\d{5}-\\d{5}$',
    '13147-13146',
    'Ten-digit postcode (five + hyphen + five)',
  ),
  KE: post(
    'Postal Corporation of Kenya',
    'http://posta.co.ke/',
    'customercare@posta.co.ke',
    'https://x.com/postakenya',
    'https://www.instagram.com/postakenya/',
    'https://www.linkedin.com/company/postal-corporation-of-kenya/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00100',
    'Five-digit postcode; P.O. Box culture remains common',
  ),
  MG: post(
    'Paositra Malagasy',
    'http://www.poste.mg/',
    'contact@paositra.mg',
    'https://x.com/Paositra',
    'https://www.instagram.com/paositramalagasy/',
    'https://www.linkedin.com/company/paositra-malagasy/',
    '',
    'NNN',
    '^\\\\d{3}$',
    '101',
    'Three-digit postcode',
  ),
  MY: post(
    'Pos Malaysia',
    'https://www.pos.com.my/',
    'customercare@pos.com.my',
    'https://x.com/posmalaysia',
    'https://www.instagram.com/posmalaysia/',
    'https://www.linkedin.com/company/pos-malaysia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '50000',
    'Five-digit postcode',
  ),
  MV: post(
    'Maldives Post',
    'https://www.maldivespost.com/',
    'info@maldivespost.com',
    'https://x.com/MaldivesPost',
    '',
    'https://www.linkedin.com/company/maldives-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '20026',
    'Five-digit postcode',
  ),
  MU: post(
    'Mauritius Post Ltd',
    'https://www.mauritiuspost.mu/',
    'info@mpl.mu',
    '',
    '',
    'https://www.linkedin.com/company/mauritius-post-ltd/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '42602',
    'Five-digit postcode (optional letter suffix in some datasets)',
  ),
  MZ: post(
    'Correios de Moçambique',
    'http://correios.co.mz/',
    'cac@correios.co.mz',
    '',
    '',
    'https://www.linkedin.com/company/correios-de-mocambique/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1100',
    'Four-digit postcode',
  ),
  OM: post(
    'Oman Post',
    'https://www.omanpost.om/',
    'info@omanpost.om',
    'https://x.com/OmanPost',
    'https://www.instagram.com/omanpost/',
    'https://www.linkedin.com/company/oman-post/',
    '',
    'NNN',
    '^\\d{3}$',
    '100',
    'Three-digit postcode',
  ),
  SC: post(
    'Seychelles Postal Services',
    'https://www.seychelles-post.com/',
    'info@sib.gov.sc',
    '',
    '',
    'https://www.linkedin.com/company/seychelles-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; island and district addressing',
  ),
  SG: post(
    'Singapore Post',
    'https://www.singpost.com/',
    'feedback@singpost.com',
    'https://x.com/SingPost',
    'https://www.instagram.com/singpost/',
    'https://www.linkedin.com/company/singapore-post-limited/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '018956',
    'Six-digit postcode',
  ),
  SO: post(
    'Somali Postal Service',
    'https://www.upu.int/en/Somalia',
    'minister@mpt.gov.so',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district and landmark addressing',
  ),
  ZA: post(
    'South African Post Office',
    'http://www.postoffice.co.za/',
    'custserv@postoffice.co.za',
    'https://x.com/PostofficeSa',
    'https://www.instagram.com/sapostoffice/',
    'https://www.linkedin.com/company/south-african-post-office/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '2000',
    'Four-digit postcode (street delivery and P.O. Box)',
  ),
  LK: post(
    'Sri Lanka Post',
    'https://www.slpost.gov.lk/',
    'info@slpost.gov.lk',
    'https://x.com/SLPost',
    '',
    'https://www.linkedin.com/company/sri-lanka-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00100',
    'Five-digit postcode',
  ),
  TZ: post(
    'Tanzania Posts Corporation',
    'https://posta.co.tz/',
    'info@tpoc.co.tz',
    '',
    '',
    'https://www.linkedin.com/company/tanzania-posts-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '11101',
    'Five-digit postcode',
  ),
  TH: post(
    'Thailand Post',
    'https://www.thailandpost.co.th/',
    'contact@thailandpost.co.th',
    'https://x.com/ThailandPost',
    'https://www.instagram.com/thailandpost/',
    'https://www.linkedin.com/company/thailand-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10100',
    'Five-digit postcode',
  ),
  AE: post(
    'Emirates Post Group',
    'https://www.epg.ae/',
    'info@epg.ae',
    'https://x.com/EmiratesPost',
    'https://www.instagram.com/emiratespost/',
    'https://www.linkedin.com/company/emirates-post-group/',
    '',
    'none',
    '',
    '',
    'No national postcode; Makani / building addressing in UAE',
  ),
  YE: post(
    'Yemen Post',
    'https://www.yemenpost.ye/',
    'info@yemenpost.ye',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'Limited national postcode coverage; verify operational status locally',
  ),
}
