import type { IoraMemberIsoCode } from './ioraMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

const OAPI_TRADEMARKS = ip(
  'trademarks',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

const OAPI_PATENTS = ip(
  'patents',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

function oapiMember(copyright: IntellectualPropertyDepartment): IntellectualPropertyDepartmentsRoster {
  return roster(copyright, OAPI_TRADEMARKS, OAPI_PATENTS)
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for Indian Ocean Rim Association
 * (IORA) members in this module (informational; verify URLs, handles, forms portals, and API
 * bases before production use). Self-contained — no imports from other alliance modules.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const IORA_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  IoraMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AU: roster(
    ip(
      'copyright',
      'Australian Government — Attorney-General\'s Department (Copyright)',
      'https://www.ag.gov.au/rights-and-protections/copyright',
      '',
      '',
      '',
      'https://www.ag.gov.au/rights-and-protections/copyright',
    ),
    ip(
      'trademarks',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
    ip(
      'patents',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
  ),
  BD: roster(
    ip(
      'copyright',
      'Department of Patents, Designs and Trademarks (DPDT, Bangladesh) — copyright',
      'https://dpdt.gov.bd',
      'dpdt@dpdt.gov.bd',
      '',
      '',
      'https://dpdt.gov.bd',
    ),
    ip(
      'trademarks',
      'Department of Patents, Designs and Trademarks (DPDT, Bangladesh)',
      'https://dpdt.gov.bd',
      'dpdt@dpdt.gov.bd',
      '',
      '',
      'https://dpdt.gov.bd',
    ),
    ip(
      'patents',
      'Department of Patents, Designs and Trademarks (DPDT, Bangladesh)',
      'https://dpdt.gov.bd',
      'dpdt@dpdt.gov.bd',
      '',
      '',
      'https://dpdt.gov.bd',
    ),
  ),
  KM: oapiMember(
    ip(
      'copyright',
      'Centre Comorien du Droit d\'Auteur et des Droits Voisins',
      'https://www.beit-salam.km',
      '',
      '',
      '',
      'https://www.beit-salam.km',
    ),
  ),
  FR: roster(
    ip(
      'copyright',
      'Ministry of Culture (France) — copyright',
      'https://www.culture.gouv.fr',
      '',
      '',
      '',
      'https://www.culture.gouv.fr',
    ),
    ip(
      'trademarks',
      'National Institute of Industrial Property (INPI France)',
      'https://www.inpi.fr',
      'contact@inpi.fr',
      'https://x.com/INPIfr',
      'https://www.linkedin.com/company/inpi/',
      'https://www.inpi.fr/fr/services-et-prestations',
    ),
    ip(
      'patents',
      'National Institute of Industrial Property (INPI France)',
      'https://www.inpi.fr',
      'contact@inpi.fr',
      'https://x.com/INPIfr',
      'https://www.linkedin.com/company/inpi/',
      'https://www.inpi.fr/fr/services-et-prestations',
    ),
  ),
  IN: roster(
    ip(
      'copyright',
      'Copyright Office of India',
      'https://copyright.gov.in',
      '',
      '',
      '',
      'https://copyright.gov.in',
    ),
    ip(
      'trademarks',
      'Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)',
      'https://ipindia.gov.in',
      'cgoffice@nic.in',
      '',
      'https://www.linkedin.com/company/office-of-the-controller-general-of-patents-designs-and-trade-marks/',
      'https://ipindiaonline.gov.in',
    ),
    ip(
      'patents',
      'Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)',
      'https://ipindia.gov.in',
      'cgoffice@nic.in',
      '',
      'https://www.linkedin.com/company/office-of-the-controller-general-of-patents-designs-and-trade-marks/',
      'https://ipindiaonline.gov.in',
    ),
  ),
  ID: roster(
    ip(
      'copyright',
      'Directorate General of Intellectual Property (DGIP) — copyright',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'trademarks',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'patents',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
  ),
  IR: roster(
    ip(
      'copyright',
      'Iran Intellectual Property Center (IIPC) — copyright',
      'https://iipc.ir',
      '',
      '',
      '',
      'https://iipc.ir',
    ),
    ip(
      'trademarks',
      'Iran Intellectual Property Center (IIPC)',
      'https://iipc.ir',
      '',
      '',
      '',
      'https://iipc.ir',
    ),
    ip(
      'patents',
      'Iran Intellectual Property Center (IIPC)',
      'https://iipc.ir',
      '',
      '',
      '',
      'https://iipc.ir',
    ),
  ),
  KE: roster(
    ip(
      'copyright',
      'Kenya Copyright Board (KECOBO)',
      'https://www.copyright.go.ke',
      'info@copyright.go.ke',
      'https://x.com/KECOBO',
      'https://www.linkedin.com/company/kenya-copyright-board/',
      'https://www.copyright.go.ke',
    ),
    ip(
      'trademarks',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
    ip(
      'patents',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
  ),
  MG: roster(
    ip(
      'copyright',
      'Office Malgache des Droits d\'Auteur (OMDA)',
      'https://www.omda.mg',
      '',
      '',
      '',
      'https://www.omda.mg',
    ),
    ip(
      'trademarks',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
    ip(
      'patents',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
  ),
  MY: roster(
    ip(
      'copyright',
      'Intellectual Property Corporation of Malaysia (MyIPO) — copyright',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'trademarks',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'patents',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
  ),
  MV: roster(
    ip(
      'copyright',
      'Maldives Intellectual Property Office — copyright',
      'https://www.ipmaldives.gov.mv',
      '',
      '',
      '',
      'https://www.ipmaldives.gov.mv',
    ),
    ip(
      'trademarks',
      'Maldives Intellectual Property Office',
      'https://www.ipmaldives.gov.mv',
      '',
      '',
      '',
      'https://www.ipmaldives.gov.mv',
    ),
    ip(
      'patents',
      'Maldives Intellectual Property Office',
      'https://www.ipmaldives.gov.mv',
      '',
      '',
      '',
      'https://www.ipmaldives.gov.mv',
    ),
  ),
  MU: roster(
    ip(
      'copyright',
      'Mauritius Society of Authors (MASA)',
      'https://www.masa.mu',
      'info@masa.mu',
      '',
      '',
      'https://www.masa.mu',
    ),
    ip(
      'trademarks',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
    ip(
      'patents',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
  ),
  MZ: roster(
    ip(
      'copyright',
      'Instituto Nacional da Propriedade Intelectual (IPI) — copyright',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'trademarks',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'patents',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
  ),
  OM: roster(
    ip(
      'copyright',
      'Ministry of Culture, Sports and Youth — copyright (Oman)',
      'https://www.mcsy.gov.om',
      '',
      '',
      '',
      'https://www.mcsy.gov.om',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Investment Promotion — intellectual property (Oman)',
      'https://www.moci.gov.om',
      '',
      '',
      '',
      'https://www.moci.gov.om',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Investment Promotion — intellectual property (Oman)',
      'https://www.moci.gov.om',
      '',
      '',
      '',
      'https://www.moci.gov.om',
    ),
  ),
  SC: roster(
    ip(
      'copyright',
      'Seychelles Copyright Office (Ministry of Finance, National Planning and Trade)',
      'https://www.finance.gov.sc',
      '',
      '',
      '',
      'https://www.finance.gov.sc',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
    ip(
      'patents',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
  ),
  SG: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Singapore (IPOS) — copyright',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
  ),
  SO: roster(
    ip(
      'copyright',
      'Ministry of Information, Culture and Tourism — copyright (Somalia)',
      'https://www.mict.gov.so',
      '',
      '',
      '',
      'https://www.mict.gov.so',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
    ip(
      'patents',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
  ),
  ZA: roster(
    ip(
      'copyright',
      'Companies and Intellectual Property Commission (CIPC) — Copyright Tribunal liaison',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
  ),
  LK: roster(
    ip(
      'copyright',
      'National Intellectual Property Office of Sri Lanka (NIPO) — copyright',
      'https://www.nipo.gov.lk',
      'info@nipo.gov.lk',
      '',
      '',
      'https://www.nipo.gov.lk',
    ),
    ip(
      'trademarks',
      'National Intellectual Property Office of Sri Lanka (NIPO)',
      'https://www.nipo.gov.lk',
      'info@nipo.gov.lk',
      '',
      '',
      'https://www.nipo.gov.lk',
    ),
    ip(
      'patents',
      'National Intellectual Property Office of Sri Lanka (NIPO)',
      'https://www.nipo.gov.lk',
      'info@nipo.gov.lk',
      '',
      '',
      'https://www.nipo.gov.lk',
    ),
  ),
  TZ: roster(
    ip(
      'copyright',
      'Copyright Society of Tanzania (COSOTA)',
      'https://www.cosota.go.tz',
      'info@cosota.go.tz',
      '',
      '',
      'https://www.cosota.go.tz',
    ),
    ip(
      'trademarks',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
    ip(
      'patents',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
  ),
  TH: roster(
    ip(
      'copyright',
      'Department of Intellectual Property (DIP) — copyright',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
    ip(
      'trademarks',
      'Department of Intellectual Property (DIP)',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
    ip(
      'patents',
      'Department of Intellectual Property (DIP)',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
  ),
  AE: roster(
    ip(
      'copyright',
      'Ministry of Economy — Intellectual Property (United Arab Emirates)',
      'https://www.moec.gov.ae/en/ip',
      '',
      '',
      '',
      'https://www.moec.gov.ae/en/ip',
    ),
    ip(
      'trademarks',
      'Ministry of Economy — Intellectual Property (United Arab Emirates)',
      'https://www.moec.gov.ae/en/ip',
      '',
      '',
      '',
      'https://www.moec.gov.ae/en/ip',
    ),
    ip(
      'patents',
      'Ministry of Economy — Intellectual Property (United Arab Emirates)',
      'https://www.moec.gov.ae/en/ip',
      '',
      '',
      '',
      'https://www.moec.gov.ae/en/ip',
    ),
  ),
  YE: roster(
    ip(
      'copyright',
      'Ministry of Information, Culture and Tourism — copyright (Yemen) (verify locally)',
      'https://www.mic.gov.ye',
      '',
      '',
      '',
      'https://www.mic.gov.ye',
    ),
    ip(
      'trademarks',
      'Ministry of Industry and Trade — industrial property (Yemen) (verify locally)',
      'https://www.industry.gov.ye',
      '',
      '',
      '',
      'https://www.industry.gov.ye',
    ),
    ip(
      'patents',
      'Ministry of Industry and Trade — industrial property (Yemen) (verify locally)',
      'https://www.industry.gov.ye',
      '',
      '',
      '',
      'https://www.industry.gov.ye',
    ),
  ),
}
