import type { IoraMemberIsoCode } from './ioraMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const IORA_MAIN_INTERNATIONAL_AIRPORTS: Record<IoraMemberIsoCode, MainInternationalAirport> = {
  AU: {
    name: 'Sydney Kingsford Smith Airport (SYD)',
    website: 'https://www.sydneyairport.com.au/',
    email: 'info@sydneyairport.com.au',
    twitter: 'https://x.com/SydneyAirport',
    instagram: 'https://www.instagram.com/sydneyairport/',
    linkedin: 'https://www.linkedin.com/company/sydney-airport/',
    apiEndpoint: '',
  },
  BD: {
    name: 'Hazrat Shahjalal International Airport (DAC)',
    website: 'https://www.caab.gov.bd/',
    email: 'info@caab.gov.bd',
    twitter: 'https://x.com/CAAB_Official',
    instagram: 'https://www.instagram.com/caab_official/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-bangladesh/',
    apiEndpoint: '',
  },
  KM: {
    name: 'Prince Said Ibrahim International Airport (HAH)',
    website: 'https://www.aeroport-comores.km/',
    email: 'info@aeroport-comores.km',
    twitter: 'https://x.com/AeroportHAH',
    instagram: 'https://www.instagram.com/aeroportcomores/',
    linkedin: 'https://www.linkedin.com/company/aeroport-prince-said-ibrahim/',
    apiEndpoint: '',
  },
  FR: {
    name: 'Paris Charles de Gaulle Airport (CDG)',
    website: 'https://www.parisaeroport.fr/',
    email: 'contact@adp.fr',
    twitter: 'https://x.com/ParisAeroport',
    instagram: 'https://www.instagram.com/parisaeroport/',
    linkedin: 'https://www.linkedin.com/company/groupe-adp/',
    apiEndpoint: '',
  },
  IN: {
    name: 'Indira Gandhi International Airport (DEL)',
    website: 'https://www.newdelhiairport.in/',
    email: 'feedback@delhiairport.com',
    twitter: 'https://x.com/DelhiAirport',
    instagram: 'https://www.instagram.com/delhiairport/',
    linkedin: 'https://www.linkedin.com/company/delhi-international-airport-limited/',
    apiEndpoint: '',
  },
  ID: {
    name: 'Soekarno-Hatta International Airport (CGK)',
    website: 'https://soekarnohatta-airport.co.id/',
    email: 'info@soekarnohatta-airport.co.id',
    twitter: 'https://x.com/SoettaAirport',
    instagram: 'https://www.instagram.com/soettaairport/',
    linkedin: 'https://www.linkedin.com/company/soekarno-hatta-international-airport/',
    apiEndpoint: '',
  },
  IR: {
    name: 'Imam Khomeini International Airport (IKA)',
    website: 'https://www.ikac.ir/',
    email: 'info@ikac.ir',
    twitter: 'https://x.com/IKA_Airport',
    instagram: 'https://www.instagram.com/ika_airport/',
    linkedin: 'https://www.linkedin.com/company/imam-khomeini-international-airport/',
    apiEndpoint: '',
  },
  KE: {
    name: 'Jomo Kenyatta International Airport (NBO)',
    website: 'https://www.kaa.go.ke/',
    email: 'info@kaa.go.ke',
    twitter: 'https://x.com/KenyaAirports',
    instagram: 'https://www.instagram.com/kenyaairports/',
    linkedin: 'https://www.linkedin.com/company/kenya-airports-authority/',
    apiEndpoint: '',
  },
  MG: {
    name: 'Ivato International Airport (TNR)',
    website: 'https://www.ravinala.mg/',
    email: 'contact@ravinala.mg',
    twitter: 'https://x.com/RavinalaAirports',
    instagram: 'https://www.instagram.com/ravinalaairports/',
    linkedin: 'https://www.linkedin.com/company/ravinala-airports/',
    apiEndpoint: '',
  },
  MY: {
    name: 'Kuala Lumpur International Airport (KUL)',
    website: 'https://www.klia.com.my/',
    email: 'info@klia.com.my',
    twitter: 'https://x.com/KLIA_Malaysia',
    instagram: 'https://www.instagram.com/klia_malaysia/',
    linkedin: 'https://www.linkedin.com/company/malaysia-airports/',
    apiEndpoint: '',
  },
  MV: {
    name: 'Velana International Airport (MLE)',
    website: 'https://www.maclonline.com/',
    email: 'info@macl.aero',
    twitter: 'https://x.com/MACL_Official',
    instagram: 'https://www.instagram.com/macl_official/',
    linkedin: 'https://www.linkedin.com/company/maldives-airports-company-limited/',
    apiEndpoint: '',
  },
  MU: {
    name: 'Sir Seewoosagur Ramgoolam International Airport (MRU)',
    website: 'https://www.airports.mu/',
    email: 'info@airports.mu',
    twitter: 'https://x.com/AirportsMauritius',
    instagram: 'https://www.instagram.com/airportsmauritius/',
    linkedin: 'https://www.linkedin.com/company/airports-of-mauritius-co-ltd/',
    apiEndpoint: '',
  },
  MZ: {
    name: 'Maputo International Airport (MPM)',
    website: 'https://www.aeroportos.co.mz/',
    email: 'info@aeroportos.co.mz',
    twitter: 'https://x.com/AeroportosMZ',
    instagram: 'https://www.instagram.com/aeroportosmz/',
    linkedin: 'https://www.linkedin.com/company/aeroportos-de-mocambique/',
    apiEndpoint: '',
  },
  OM: {
    name: 'Muscat International Airport (MCT)',
    website: 'https://www.muscatairport.co.om/',
    email: 'info@muscatairport.co.om',
    twitter: 'https://x.com/MuscatAirport',
    instagram: 'https://www.instagram.com/muscatairport/',
    linkedin: 'https://www.linkedin.com/company/oman-airports/',
    apiEndpoint: '',
  },
  SC: {
    name: 'Seychelles International Airport (SEZ)',
    website: 'https://www.scaa.sc/',
    email: 'info@scaa.sc',
    twitter: 'https://x.com/SCAA_Seychelles',
    instagram: 'https://www.instagram.com/scaa_seychelles/',
    linkedin: 'https://www.linkedin.com/company/seychelles-civil-aviation-authority/',
    apiEndpoint: '',
  },
  SG: {
    name: 'Singapore Changi Airport (SIN)',
    website: 'https://www.changiairport.com/',
    email: 'feedback@changiairport.com',
    twitter: 'https://x.com/ChangiAirport',
    instagram: 'https://www.instagram.com/changiairport/',
    linkedin: 'https://www.linkedin.com/company/changi-airport-group/',
    apiEndpoint: '',
  },
  SO: {
    name: 'Aden Adde International Airport (MGQ)',
    website: 'https://www.scaa.gov.so/',
    email: 'info@scaa.gov.so',
    twitter: 'https://x.com/SCAA_Somalia',
    instagram: 'https://www.instagram.com/scaa_somalia/',
    linkedin: 'https://www.linkedin.com/company/somalia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  ZA: {
    name: 'O.R. Tambo International Airport (JNB)',
    website: 'https://www.airports.co.za/',
    email: 'info@airports.co.za',
    twitter: 'https://x.com/Airports_ZA',
    instagram: 'https://www.instagram.com/airports_co_za/',
    linkedin: 'https://www.linkedin.com/company/airports-company-south-africa/',
    apiEndpoint: '',
  },
  LK: {
    name: 'Bandaranaike International Airport (CMB)',
    website: 'https://www.airport.lk/',
    email: 'info@airport.lk',
    twitter: 'https://x.com/BandaranaikeAP',
    instagram: 'https://www.instagram.com/bandaranaikeap/',
    linkedin: 'https://www.linkedin.com/company/bandaranaike-international-airport/',
    apiEndpoint: '',
  },
  TZ: {
    name: 'Julius Nyerere International Airport (DAR)',
    website: 'https://www.taa.go.tz/',
    email: 'info@taa.go.tz',
    twitter: 'https://x.com/TAA_Tanzania',
    instagram: 'https://www.instagram.com/taa_tanzania/',
    linkedin: 'https://www.linkedin.com/company/tanzania-airports-authority/',
    apiEndpoint: '',
  },
  TH: {
    name: 'Suvarnabhumi Airport (BKK)',
    website: 'https://suvarnabhumi.airportthai.co.th/',
    email: 'info@airportthai.co.th',
    twitter: 'https://x.com/AOT_BKK',
    instagram: 'https://www.instagram.com/suvarnabhumi_airport/',
    linkedin: 'https://www.linkedin.com/company/airports-of-thailand/',
    apiEndpoint: '',
  },
  AE: {
    name: 'Zayed International Airport (AUH)',
    website: 'https://www.zayedinternationalairport.ae/',
    email: 'info@adairports.ae',
    twitter: 'https://x.com/ZayedAirport',
    instagram: 'https://www.instagram.com/zayedairport/',
    linkedin: 'https://www.linkedin.com/company/abu-dhabi-airports/',
    apiEndpoint: '',
  },
  YE: {
    name: 'Sana\'a International Airport (SAH)',
    website: 'https://www.yemenia.com/',
    email: 'info@yemenia.com',
    twitter: 'https://x.com/YemeniaAir',
    instagram: 'https://www.instagram.com/yemeniaair/',
    linkedin: 'https://www.linkedin.com/company/yemen-airways/',
    apiEndpoint: '',
  },
}
