import type { IoraMemberIsoCode } from './ioraMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const IORA_MAIN_EXPORT_COMMODITIES: Record<IoraMemberIsoCode, MainExportCommodities> = {
  AU: m(
    'Iron ore',
    'Coal',
    'Natural gas',
    'Gold',
    'Beef',
    'Wheat',
    'Aluminium',
  ),
  BD: m(
    'Garments',
    'Jute',
    'Leather goods',
    'Fish',
    'Home textiles',
    'Footwear',
    'Rice',
  ),
  KM: m(
    'Vanilla',
    'Cloves',
    'Ylang-ylang',
    'Fish',
    'Essential oils',
    'Copra',
    'Pepper',
  ),
  FR: m(
    'Aircraft',
    'Packaged medicaments',
    'Wine',
    'Refined petroleum',
    'Automobiles',
    'Wheat',
    'Pharmaceuticals',
  ),
  IN: m(
    'Refined petroleum',
    'Diamonds',
    'Pharmaceuticals',
    'Rice',
    'Machinery',
    'Iron and steel',
    'Cotton yarn',
  ),
  ID: m(
    'Coal',
    'Palm oil',
    'Nickel',
    'Refined petroleum',
    'Rubber',
    'Copper',
    'Gold',
  ),
  IR: m(
    'Crude petroleum',
    'Petrochemicals',
    'Natural gas',
    'Dates',
    'Pistachios',
    'Carpets',
    'Steel',
  ),
  KE: m(
    'Tea',
    'Cut flowers',
    'Coffee',
    'Refined petroleum',
    'Titanium ore',
    'Avocados',
    'Vegetables',
  ),
  MG: m(
    'Vanilla',
    'Nickel',
    'Apparel',
    'Cloves',
    'Gold',
    'Shrimp',
    'Graphite',
  ),
  MY: m(
    'Integrated circuits',
    'Palm oil',
    'Refined petroleum',
    'Liquified natural gas',
    'Rubber',
    'Natural gas',
    'Electrical machinery',
  ),
  MV: m(
    'Fish',
    'Tourism services',
    'Garments',
    'Coconut products',
    'Thresher shark meat',
    'Aircraft parts',
    'Re-exports',
  ),
  MU: m(
    'Fish',
    'Textiles',
    'Sugar',
    'Refined petroleum',
    'Jewelry',
    'Cut flowers',
    'Medical devices',
  ),
  MZ: m(
    'Coal',
    'Aluminum',
    'Natural gas',
    'Electrical energy',
    'Cashew nuts',
    'Prawns',
    'Tobacco',
  ),
  OM: m(
    'Crude petroleum',
    'Refined petroleum',
    'Liquified natural gas',
    'Fertilizers',
    'Metals',
    'Fish',
    'Plastics',
  ),
  SC: m(
    'Fish',
    'Processed fish',
    'Petroleum re-exports',
    'Copra',
    'Cinnamon',
    'Canned tuna',
    'Tourism-linked goods',
  ),
  SG: m(
    'Integrated circuits',
    'Refined petroleum',
    'Machinery',
    'Pharmaceuticals',
    'Optical media',
    'Gold',
    'Gas turbines',
  ),
  SO: m(
    'Livestock',
    'Charcoal',
    'Fish',
    'Gold',
    'Sesame seeds',
    'Bananas',
    'Hides and skins',
  ),
  ZA: m(
    'Platinum',
    'Gold',
    'Coal',
    'Iron ore',
    'Manganese ore',
    'Automobiles',
    'Citrus fruit',
  ),
  LK: m(
    'Tea',
    'Apparel',
    'Rubber',
    'Coconut products',
    'Spices',
    'Fish',
    'Gems',
  ),
  TZ: m(
    'Gold',
    'Cashew nuts',
    'Coffee',
    'Refined petroleum',
    'Cotton',
    'Tobacco',
    'Tea',
  ),
  TH: m(
    'Computers',
    'Automobiles',
    'Rubber',
    'Rice',
    'Jewellery',
    'Sugar',
    'Chicken',
  ),
  AE: m(
    'Crude petroleum',
    'Refined petroleum',
    'Gold',
    'Diamonds',
    'Aluminium',
    'Telecommunications equipment',
    'Dates',
  ),
  YE: m(
    'Crude petroleum',
    'Gold',
    'Fish',
    'Coffee',
    'Honey',
    'Vegetables',
    'Scrap metal',
  ),
}
