import type { IoraMemberIsoCode } from './ioraMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2 for IORA
 * members (informational; verify against USGS Mineral Commodity Summaries, BGS World Mineral
 * Production, and UN Comtrade periodically). IORA spans Australia and India (major primary
 * producers across iron, aluminum, manganese, titanium), Iran and Oman / UAE / Yemen (Carbon /
 * Hydrogen / Sulfur from hydrocarbon value chains), Indonesia, Malaysia and Thailand
 * (Sn, Ni, Cu, Sb, Si) and small island economies (mineral sands / salt / fisheries-derived
 * generic Ca / Si / Na entries). FR appears as its IORA seat (La Réunion) reflecting the
 * mainland France Aluminum / Silicon / Uranium-refining profile.
 */
export const IORA_MAIN_EXPORTED_ELEMENTS: Record<IoraMemberIsoCode, MainExportedElements> = {
  AU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Lithium (Li)',
    'Gold (Au)',
    'Copper (Cu)',
    'Uranium (U)',
  ),
  BD: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Sulfur (S)',
  ),
  KM: e(
    'Calcium (Ca)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Carbon (C)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Magnesium (Mg)',
  ),
  FR: e(
    'Uranium (U)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Titanium (Ti)',
    'Gold (Au)',
  ),
  IN: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Manganese (Mn)',
    'Chromium (Cr)',
    'Titanium (Ti)',
    'Zinc (Zn)',
  ),
  ID: e(
    'Carbon (C)',
    'Nickel (Ni)',
    'Tin (Sn)',
    'Copper (Cu)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Hydrogen (H)',
  ),
  IR: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Aluminum (Al)',
  ),
  KE: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Fluorine (F)',
  ),
  MG: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Titanium (Ti)',
    'Chromium (Cr)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  MY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Copper (Cu)',
  ),
  MV: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Sodium (Na)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Magnesium (Mg)',
  ),
  MU: e(
    'Calcium (Ca)',
    'Carbon (C)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Magnesium (Mg)',
  ),
  MZ: e(
    'Aluminum (Al)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Tantalum (Ta)',
    'Iron (Fe)',
  ),
  OM: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Iron (Fe)',
    'Chromium (Cr)',
    'Gold (Au)',
  ),
  SC: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Sodium (Na)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Magnesium (Mg)',
  ),
  SG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Tin (Sn)',
  ),
  SO: e(
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Carbon (C)',
    'Sodium (Na)',
  ),
  ZA: e(
    'Platinum (Pt)',
    'Palladium (Pd)',
    'Gold (Au)',
    'Iron (Fe)',
    'Chromium (Cr)',
    'Manganese (Mn)',
    'Carbon (C)',
  ),
  LK: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Carbon (C)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
  ),
  TZ: e(
    'Gold (Au)',
    'Carbon (C)',
    'Nickel (Ni)',
    'Copper (Cu)',
    'Iron (Fe)',
    'Tin (Sn)',
    'Helium (He)',
  ),
  TH: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Zinc (Zn)',
    'Antimony (Sb)',
  ),
  AE: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Helium (He)',
    'Iron (Fe)',
    'Gold (Au)',
  ),
  YE: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
  ),
}
