import type { IoraMemberIsoCode } from './ioraMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per IORA member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const IORA_MAIN_INTERNATIONAL_SEAPORTS: Record<IoraMemberIsoCode, MainInternationalSeaport> = {
  AU: seaport(
    'Port of Melbourne',
    'https://www.portofmelbourne.com/',
    'info@portofmelbourne.com',
    'https://x.com/PortOfMelbourne',
    'https://www.instagram.com/portofmelbourne/',
    'https://www.linkedin.com/company/port-of-melbourne/',
    'customs@abf.gov.au',
    'https://www.abf.gov.au',
    'Australian Border Force — Port of Melbourne, Melbourne, Australia',
  ),
  BD: seaport(
    'Port of Chittagong (Chattogram)',
    'https://www.cpa.gov.bd/',
    'info@cpa.gov.bd',
    'https://x.com/CPA_Bangladesh',
    'https://www.instagram.com/cpa_bangladesh/',
    'https://www.linkedin.com/company/chittagong-port-authority/',
    'customs@customs.gov.bd',
    'https://www.customs.gov.bd',
    'National Board of Revenue Customs — Chattogram Port, Chattogram, Bangladesh',
  ),
  KM: seaport(
    'Port of Moroni',
    'https://www.portcomores.km/',
    'info@portcomores.km',
    'https://x.com/PortComores',
    'https://www.instagram.com/portcomores/',
    'https://www.linkedin.com/company/port-autonome-des-comores/',
    'douanes@finances.km',
    'https://www.douanes.km',
    'Direction des Douanes — Port de Moroni, Moroni, Comoros',
  ),
  FR: seaport(
    'Port of Le Havre',
    'https://www.havre-port.fr/',
    'info@havre-port.fr',
    'https://x.com/HavrePort',
    'https://www.instagram.com/havreport/',
    'https://www.linkedin.com/company/grand-port-maritime-du-havre/',
    'douane@douane.gouv.fr',
    'https://www.douane.gouv.fr',
    'French Customs — Port of Le Havre, Le Havre, France',
  ),
  IN: seaport(
    'Jawaharlal Nehru Port (Nhava Sheva)',
    'https://www.jnport.gov.in/',
    'info@jnport.gov.in',
    'https://x.com/JNPort',
    'https://www.instagram.com/jnport/',
    'https://www.linkedin.com/company/jawaharlal-nehru-port-trust/',
    'customs@cbic.gov.in',
    'https://www.cbic.gov.in',
    'Indian Customs — Jawaharlal Nehru Port, Navi Mumbai, India',
  ),
  ID: seaport(
    'Port of Tanjung Priok (Jakarta)',
    'https://www.pelindo.co.id/',
    'info@pelindo.co.id',
    'https://x.com/Pelindo',
    'https://www.instagram.com/pelindo/',
    'https://www.linkedin.com/company/pelindo/',
    'contact.center@beacukai.go.id',
    'https://www.beacukai.go.id',
    'Direktorat Jenderal Bea dan Cukai — Pelabuhan Tanjung Priok, Jakarta, Indonesia',
  ),
  IR: seaport(
    'Port of Bandar Abbas (Shahid Rajaee)',
    'https://www.pmo.ir/',
    'info@pmo.ir',
    'https://x.com/PortsMaritimeIR',
    'https://www.instagram.com/pmo_ir/',
    'https://www.linkedin.com/company/ports-and-maritime-organization/',
    'customs@irica.gov.ir',
    'https://www.irica.gov.ir',
    'Iran Customs — Shahid Rajaee Port, Bandar Abbas, Iran',
  ),
  KE: seaport(
    'Port of Mombasa',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@kra.go.ke',
    'https://www.kra.go.ke',
    'Kenya Revenue Authority — Customs Services, Port of Mombasa, Mombasa, Kenya',
  ),
  MG: seaport(
    'Port of Toamasina',
    'https://www.otal.com/madagascar/port-of-toamasina',
    'contact@port-toamasina.mg',
    'https://x.com/PortToamasina',
    'https://www.instagram.com/porttoamasina/',
    'https://www.linkedin.com/company/port-de-toamasina/',
    'douanes@douanes.gov.mg',
    'https://www.douanes.gov.mg',
    'Direction Générale des Douanes — Port de Toamasina, Toamasina, Madagascar',
  ),
  MY: seaport(
    'Port Klang',
    'https://www.pka.gov.my/',
    'info@pka.gov.my',
    'https://x.com/PortKlang',
    'https://www.instagram.com/portklang/',
    'https://www.linkedin.com/company/port-klang-authority/',
    'customs@customs.gov.my',
    'https://www.customs.gov.my',
    'Royal Malaysian Customs — Port Klang, Selangor, Malaysia',
  ),
  MV: seaport(
    'Port of Malé',
    'https://www.mpa.gov.mv/',
    'info@mpa.gov.mv',
    'https://x.com/MPA_Maldives',
    'https://www.instagram.com/mpa_maldives/',
    'https://www.linkedin.com/company/maldives-ports-limited/',
    'customs@customs.gov.mv',
    'https://www.customs.gov.mv',
    'Maldives Customs Service — Port of Malé, Malé, Maldives',
  ),
  MU: seaport(
    'Port Louis',
    'https://www.mpa.mu/',
    'info@mpa.mu',
    'https://x.com/MPA_Mauritius',
    'https://www.instagram.com/mpa_mauritius/',
    'https://www.linkedin.com/company/mauritius-ports-authority/',
    'customs@mra.mu',
    'https://www.mra.mu',
    'Mauritius Revenue Authority — Customs, Port Louis, Mauritius',
  ),
  MZ: seaport(
    'Port of Maputo',
    'https://www.portmaputo.com/',
    'info@portmaputo.com',
    'https://x.com/PortMaputo',
    'https://www.instagram.com/portmaputo/',
    'https://www.linkedin.com/company/porto-de-maputo/',
    'aduaneira@at.gov.mz',
    'https://www.at.gov.mz',
    'Autoridade Tributária de Moçambique — Alfândega do Porto de Maputo, Maputo, Mozambique',
  ),
  OM: seaport(
    'Port of Salalah',
    'https://www.salalahport.com/',
    'info@salalahport.com',
    'https://x.com/SalalahPort',
    'https://www.instagram.com/salalahport/',
    'https://www.linkedin.com/company/port-of-salalah/',
    'customs@customs.gov.om',
    'https://www.customs.gov.om',
    'Royal Oman Police Customs — Port of Salalah, Salalah, Oman',
  ),
  SC: seaport(
    'Port Victoria',
    'https://www.spa.sc/',
    'info@spa.sc',
    'https://x.com/SPA_Seychelles',
    'https://www.instagram.com/spa_seychelles/',
    'https://www.linkedin.com/company/seychelles-ports-authority/',
    'customs@src.gov.sc',
    'https://www.src.gov.sc',
    'Seychelles Revenue Commission — Customs, Port Victoria, Mahé, Seychelles',
  ),
  SG: seaport(
    'Port of Singapore',
    'https://www.mpa.gov.sg/',
    'MPA_Enquiry@mpa.gov.sg',
    'https://x.com/Mpa_Singapore',
    'https://www.instagram.com/mpa_singapore/',
    'https://www.linkedin.com/company/maritime-and-port-authority-of-singapore/',
    'customs_support@customs.gov.sg',
    'https://www.customs.gov.sg',
    'Singapore Customs — PSA Singapore Terminals, Singapore',
  ),
  SO: seaport(
    'Port of Mogadishu',
    'https://www.mpa.gov.so/',
    'info@mpa.gov.so',
    'https://x.com/MPA_Somalia',
    'https://www.instagram.com/mpa_somalia/',
    'https://www.linkedin.com/company/mogadishu-port-authority/',
    'customs@finance.gov.so',
    'https://www.customs.gov.so',
    'Somalia Customs — Port of Mogadishu, Mogadishu, Somalia',
  ),
  ZA: seaport(
    'Port of Durban',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'customs@sars.gov.za',
    'https://www.sars.gov.za',
    'South African Revenue Service — Customs, Port of Durban, Durban, South Africa',
  ),
  LK: seaport(
    'Port of Colombo',
    'https://www.slpa.lk/',
    'info@slpa.lk',
    'https://x.com/SLPA_LK',
    'https://www.instagram.com/slpa_lk/',
    'https://www.linkedin.com/company/sri-lanka-ports-authority/',
    'customs@gov.lk',
    'https://www.customs.gov.lk',
    'Sri Lanka Customs — Port of Colombo, Colombo, Sri Lanka',
  ),
  TZ: seaport(
    'Port of Dar es Salaam',
    'https://www.tanzaniaports.com/',
    'info@tanzaniaports.com',
    'https://x.com/TanzaniaPorts',
    'https://www.instagram.com/tanzaniaports/',
    'https://www.linkedin.com/company/tanzania-ports-authority/',
    'customs@tra.go.tz',
    'https://www.tra.go.tz',
    'Tanzania Revenue Authority — Customs, Port of Dar es Salaam, Dar es Salaam, Tanzania',
  ),
  TH: seaport(
    'Port of Laem Chabang',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'info@customs.go.th',
    'https://www.customs.go.th',
    'Thai Customs — Laem Chabang Port, Chonburi, Thailand',
  ),
  AE: seaport(
    'Jebel Ali Port (Dubai)',
    'https://www.dpworld.com/uae',
    'info@dpworld.com',
    'https://x.com/DP_World',
    'https://www.instagram.com/dpworld/',
    'https://www.linkedin.com/company/dp-world/',
    'customs@customs.ae',
    'https://www.customs.ae',
    'Federal Customs Authority — Jebel Ali Port, Dubai, United Arab Emirates',
  ),
  YE: seaport(
    'Port of Aden',
    'https://www.adenport.com.ye/',
    'info@adenport.com.ye',
    '',
    '',
    'https://www.linkedin.com/company/aden-port/',
    'customs@customs.gov.ye',
    'https://www.customs.gov.ye',
    'Yemen Customs Authority — Port of Aden, Aden, Yemen',
  ),
}
