import type { NationalBankingInstitution } from './types'
import type { IoraMemberIsoCode } from './ioraMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per IORA member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const IORA_NATIONAL_BANKING_INSTITUTIONS: Record<
  IoraMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AU: [
    bank(
      'Commonwealth Bank of Australia',
      '+61 13 2221',
      'Ground Floor, Tower 1, 201 Sussex Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/commbank/id310251020',
      'https://play.google.com/store/apps/details?id=com.commbank.netbank',
      'https://www.commbank.com.au',
      'customercare@cba.com.au',
      'https://twitter.com/CommBank',
      'https://www.instagram.com/commbank/',
      'https://www.linkedin.com/company/commonwealth-bank/',
      '',
      'CTBAAU2S',
      'https://api.commbank.com.au',
    ),
    bank(
      'Westpac Banking Corporation',
      '+61 13 2032',
      '275 Kent Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/westpac-mobile-banking/id284826145',
      'https://play.google.com/store/apps/details?id=org.westpac.bank',
      'https://www.westpac.com.au',
      'customercare@westpac.com.au',
      'https://twitter.com/Westpac',
      'https://www.instagram.com/westpac/',
      'https://www.linkedin.com/company/westpac/',
      '',
      'WPACAU2S',
      'https://developer.westpac.com.au',
    ),
    bank(
      'Australia and New Zealand Banking Group',
      '+61 13 13 14',
      '833 Collins Street, Docklands, VIC, Australia',
      'https://apps.apple.com/au/app/anz-australia/id385348415',
      'https://play.google.com/store/apps/details?id=com.anz.android',
      'https://www.anz.com.au',
      'contactus@anz.com',
      'https://twitter.com/ANZ_AU',
      'https://www.instagram.com/anz_au/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBAU3M',
      'https://developer.anz.com',
    ),
  ],
  BD: [
    bank(
      'Sonali Bank PLC',
      '+880 2 956 0400',
      '45 Motijheel C/A, Dhaka, Bangladesh',
      '',
      '',
      'https://www.sonalibank.com.bd',
      'info@sonalibank.com.bd',
      '',
      '',
      '',
      '',
      'BSONBDDH',
      '',
    ),
    bank(
      'BRAC Bank',
      '+880 2 5566 8000',
      'Anik Tower, Tejgaon, Dhaka, Bangladesh',
      '',
      '',
      'https://www.bracbank.com',
      'enquiry@bracbank.com',
      '',
      '',
      '',
      '',
      'BRAKBDDH',
      '',
    ),
    bank(
      'Dutch-Bangla Bank',
      '+880 2 47116395',
      '47 Motijheel C/A, Dhaka, Bangladesh',
      '',
      '',
      'https://www.dutchbanglabank.com',
      'dbbl@dutchbanglabank.com',
      '',
      '',
      '',
      '',
      'DBBLBDDH',
      '',
    ),
  ],
  KM: [
    bank(
      'Banque Federale de Commerce (BFC)',
      '+269 773 20 00',
      'Place de France, Moroni, Comoros',
      '',
      '',
      'https://www.bfc-comores.com/',
      'contact@bfc-comores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Exim Bank Comores',
      '+269 773 25 25',
      'Avenue de la Corniche, Moroni, Comoros',
      '',
      '',
      'https://www.eximbankcomores.com/',
      'info@eximbankcomores.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'SNPSF',
      '+269 773 18 18',
      'Avenue Ali Soilih, Moroni, Comoros',
      '',
      '',
      'https://www.snpsf.com/',
      'contact@snpsf.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  FR: [
    bank(
      'BNP Paribas',
      '+33 1 42 98 12 34',
      '16 Boulevard des Italiens, 75009 Paris, France',
      'https://apps.apple.com/fr/app/mes-comptes-bnp-paribas/id393156562',
      'https://play.google.com/store/apps/details?id=net.bnpparibas.mescomptes',
      'https://mabanque.bnpparibas',
      'contact@bnpparibas.com',
      'https://twitter.com/bnpparibas',
      'https://www.instagram.com/bnpparibas/',
      'https://www.linkedin.com/company/bnp-paribas/',
      '',
      'BNPAFRPP',
      'https://developers.bnpparibas',
    ),
    bank(
      'Societe Generale',
      '+33 1 42 14 20 00',
      '29 Boulevard Haussmann, 75009 Paris, France',
      'https://apps.apple.com/fr/app/societe-generale/id393156562',
      'https://play.google.com/store/apps/details?id=mobi.societegenerale.mobile.lappli',
      'https://www.societegenerale.fr',
      'contact@societegenerale.com',
      'https://twitter.com/societegenerale',
      'https://www.instagram.com/societegenerale/',
      'https://www.linkedin.com/company/societe-generale/',
      '',
      'SOGEFRPP',
      'https://developer.societegenerale.com',
    ),
    bank(
      'Credit Agricole',
      '+33 1 43 23 52 02',
      '12 Place des Etats-Unis, 92127 Montrouge, France',
      'https://apps.apple.com/fr/app-ma-credit-agricole/id393156562',
      'https://play.google.com/store/apps/details?id=fr.creditagricole.androidapp',
      'https://www.credit-agricole.fr',
      'contact@credit-agricole.com',
      'https://twitter.com/CreditAgricole',
      'https://www.instagram.com/creditagricole/',
      'https://www.linkedin.com/company/credit-agricole/',
      '',
      'AGRIFRPP',
      '',
    ),
  ],
  IN: [
    bank(
      'State Bank of India',
      '+91 22 2274 0841',
      'Madame Cama Road, Nariman Point, Mumbai, India',
      '',
      '',
      'https://sbi.co.in',
      'customercare@sbi.co.in',
      '',
      '',
      '',
      '',
      'SBININBB',
      '',
    ),
    bank(
      'HDFC Bank',
      '+91 22 6160 6161',
      'HDFC Bank House, Senapati Bapat Marg, Mumbai, India',
      '',
      '',
      'https://www.hdfcbank.com',
      'support@hdfcbank.com',
      '',
      '',
      '',
      '',
      'HDFCINBB',
      '',
    ),
    bank(
      'ICICI Bank',
      '+91 22 2653 1414',
      'Bandra Kurla Complex, Mumbai, India',
      '',
      '',
      'https://www.icicibank.com',
      'customer.care@icicibank.com',
      '',
      '',
      '',
      '',
      'ICICINBB',
      '',
    ),
  ],
  ID: [
    bank(
      'Bank Mandiri',
      '+62 21 5299 7777',
      'Plaza Mandiri, Jl. Jend. Gatot Subroto, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/livin-by-mandiri/id1555417419',
      'https://play.google.com/store/apps/details?id=id.bmri.livin',
      'https://www.bankmandiri.co.id',
      'mandiricare@bankmandiri.co.id',
      'https://twitter.com/bankmandiri',
      'https://www.instagram.com/bankmandiri/',
      'https://www.linkedin.com/company/bankmandiri/',
      '',
      'BMRIIDJA',
      '',
    ),
    bank(
      'Bank Central Asia',
      '+62 21 2358 8000',
      'Menara BCA, Grand Indonesia, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/mybca/id1465918716',
      'https://play.google.com/store/apps/details?id=com.bca.mybca.omni.android',
      'https://www.bca.co.id',
      'halobca@bca.co.id',
      'https://twitter.com/BankBCA',
      'https://www.instagram.com/goodlifebca/',
      'https://www.linkedin.com/company/pt-bank-central-asia-tbk/',
      '',
      'CENAIDJA',
      '',
    ),
    bank(
      'Bank Negara Indonesia',
      '+62 21 5728387',
      'Jl. Jend. Sudirman Kav. 1, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/wondr-by-bni/id6474669196',
      'https://play.google.com/store/apps/details?id=id.co.bni.newagenbni46',
      'https://www.bni.co.id',
      'bnicall@bni.co.id',
      'https://twitter.com/BNI',
      'https://www.instagram.com/bni46/',
      'https://www.linkedin.com/company/pt-bank-negara-indonesia-persero-tbk/',
      '',
      'BNINIDJA',
      '',
    ),
  ],
  IR: [
    bank(
      'Bank Melli Iran',
      '+98 21 64140',
      'Ferdowsi Ave, Tehran, Iran',
      '',
      '',
      'https://www.bmi.ir',
      'info@bmi.ir',
      '',
      '',
      '',
      '',
      'MELIIRTH',
      '',
    ),
    bank(
      'Bank Mellat',
      '+98 21 82980',
      'Valiasr Ave, Tehran, Iran',
      '',
      '',
      'https://www.bankmellat.ir',
      'info@bankmellat.ir',
      '',
      '',
      '',
      '',
      'BKMTIRTH',
      '',
    ),
    bank(
      'Bank Tejarat',
      '+98 21 8880 4500',
      'Taleghani Ave, Tehran, Iran',
      '',
      '',
      'https://www.tejaratbank.ir',
      'info@tejaratbank.ir',
      '',
      '',
      '',
      '',
      'BTEJIRTH',
      '',
    ),
  ],
  KE: [
    bank(
      'KCB Bank Kenya',
      '+254 20 3270000',
      'Kencom House, Moi Avenue, Nairobi, Kenya',
      '',
      '',
      'https://ke.kcbgroup.com/',
      'contactcentre@kcbgroup.com',
      '',
      '',
      'https://www.linkedin.com/company/kcb-bank-kenya-limited/',
      '',
      'KCBLKENX',
      '',
    ),
    bank(
      'Equity Bank Kenya',
      '+254 763 000 000',
      'Equity Centre, Hospital Road, Nairobi, Kenya',
      '',
      '',
      'https://equitygroupholdings.com/ke/',
      'info@equitybank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-limited/',
      '',
      'EQBLKENA',
      '',
    ),
    bank(
      'Co-operative Bank of Kenya',
      '+254 20 2776000',
      'Co-op House, Haile Selassie Avenue, Nairobi, Kenya',
      '',
      '',
      'https://www.co-opbank.co.ke/',
      'customerservice@co-opbank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/co-operative-bank-of-kenya/',
      '',
      'KCOOKENA',
      '',
    ),
  ],
  MG: [
    bank(
      'BNI Madagascar',
      '+261 20 22 217 17',
      '74 Rue du 26 Juin 1960, Antananarivo, Madagascar',
      '',
      '',
      'https://www.bni.mg/',
      'contact@bni.mg',
      '',
      '',
      'https://www.linkedin.com/company/bni-madagascar/',
      '',
      'CLMADMGM',
      '',
    ),
    bank(
      'Bank of Africa Madagascar',
      '+261 20 22 206 06',
      'Immeuble BOA, Analakely, Antananarivo, Madagascar',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boamadagascar.com/',
      'contact@boamadagascar.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      'AFRIMGMG',
      '',
    ),
    bank(
      'BGFI Bank Madagascar',
      '+261 20 22 629 00',
      'Zone Galaxy, Andraharo, Antananarivo, Madagascar',
      '',
      '',
      'https://www.bgfibank.com/',
      'contact@bgfibank.com',
      '',
      '',
      'https://www.linkedin.com/company/bgfi-holding-corporation/',
      '',
      '',
      '',
    ),
  ],
  MY: [
    bank(
      'Maybank',
      '+60 3 2070 8833',
      'Menara Maybank, 100 Jalan Tun Perak, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/mae-by-maybank2u/id1455827893',
      'https://play.google.com/store/apps/details?id=com.maybank2u.life',
      'https://www.maybank2u.com.my',
      'mgcc@maybank.com.my',
      'https://twitter.com/MyMaybank',
      'https://www.instagram.com/maybank/',
      'https://www.linkedin.com/company/maybank/',
      '',
      'MBBEMYKL',
      '',
    ),
    bank(
      'CIMB Bank',
      '+60 3 6204 7788',
      'Menara CIMB, Jalan Stesen Sentral 2, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/cimb-octo-my/id1533904065',
      'https://play.google.com/store/apps/details?id=com.cimbmalaysia',
      'https://www.cimb.com.my',
      'contactus@cimb.com',
      'https://twitter.com/CIMBMalaysia',
      'https://www.instagram.com/cimbmalaysia/',
      'https://www.linkedin.com/company/cimb/',
      '',
      'CIBBMYKL',
      '',
    ),
    bank(
      'Public Bank',
      '+60 3 2176 8000',
      'Menara Public Bank, Jalan Raja Chulan, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/pbe/id1181169389',
      'https://play.google.com/store/apps/details?id=com.publicbank.pbeng',
      'https://www.pbebank.com',
      'customersupport@publicbank.com.my',
      'https://twitter.com/PublicBankGroup',
      '',
      'https://www.linkedin.com/company/public-bank-berhad/',
      '',
      'PBBEMYKL',
      '',
    ),
  ],
  MV: [
    bank(
      'Bank of Maldives',
      '+960 332 2944',
      '11 Boduthakurufaanu Magu, Male, Maldives',
      '',
      '',
      'https://www.bankofmaldives.com.mv',
      'info@bankofmaldives.com.mv',
      '',
      '',
      '',
      '',
      'MALBMVMV',
      '',
    ),
    bank(
      'Maldives Islamic Bank',
      '+960 331 8383',
      'Velaanaage, Ameer Ahmed Magu, Male, Maldives',
      '',
      '',
      'https://www.mib.com.mv',
      'info@mib.com.mv',
      '',
      '',
      '',
      '',
      'MIBLMVMV',
      '',
    ),
    bank(
      'State Bank of India Maldives',
      '+960 330 8488',
      'Boduthakurufaanu Magu, Male, Maldives',
      '',
      '',
      'https://sbi.co.in/web/global-link/sbi-maldives',
      'sbi.maldives@sbi.co.in',
      '',
      '',
      '',
      '',
      'SBININBBMLD',
      '',
    ),
  ],
  MU: [
    bank(
      'The Mauritius Commercial Bank',
      '+230 202 5000',
      'Sir William Newton St, Port Louis, Mauritius',
      '',
      '',
      'https://www.mcb.mu/',
      'contact@mcb.mu',
      '',
      '',
      'https://www.linkedin.com/company/the-mauritius-commercial-bank-limited/',
      '',
      'MCBLMUMU',
      '',
    ),
    bank(
      'SBM Bank (Mauritius)',
      '+230 202 1111',
      '1 Queen Elizabeth II Avenue, Port Louis, Mauritius',
      '',
      '',
      'https://www.sbmgroup.mu/',
      'sbm@sbmgroup.mu',
      '',
      '',
      'https://www.linkedin.com/company/sbm-bank-mauritius-ltd/',
      '',
      'STCBMUMU',
      '',
    ),
    bank(
      'Absa Bank Mauritius',
      '+230 402 1000',
      'Absa House, Wall Street, Ebene, Mauritius',
      '',
      '',
      'https://www.absabank.mu/',
      'absamauritius@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCMUMU',
      '',
    ),
  ],
  MZ: [
    bank(
      'Banco Comercial e de Investimentos (BCI)',
      '+258 21 352 700',
      'Praca 25 de Junho, Maputo, Mozambique',
      '',
      '',
      'https://www.bci.co.mz/',
      'cliente@bci.co.mz',
      '',
      '',
      'https://www.linkedin.com/company/bci-banco-comercial-e-de-investimentos/',
      '',
      'BCIOMZMA',
      '',
    ),
    bank(
      'Millennium bim',
      '+258 21 350 000',
      'Avenida Julius Nyerere 3435, Maputo, Mozambique',
      '',
      '',
      'https://ind.millenniumbim.co.mz/',
      'cliente@millenniumbim.co.mz',
      '',
      '',
      'https://www.linkedin.com/company/millennium-bim/',
      '',
      'MILLMZMA',
      '',
    ),
    bank(
      'Standard Bank Mozambique',
      '+258 21 327 000',
      'Avenida Julius Nyerere 4, Maputo, Mozambique',
      '',
      '',
      'https://www.standardbank.co.mz/',
      'contactcentre@standardbank.co.mz',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBICMZMX',
      '',
    ),
  ],
  OM: [
    bank(
      'Bank Muscat',
      '+968 24795555',
      'Airport Heights, Muscat, Oman',
      'https://apps.apple.com/om/app/bank-muscat-mobile-banking/id563857469',
      'https://play.google.com/store/apps/details?id=com.bankmuscat.mbanking',
      'https://www.bankmuscat.com',
      'customercare@bankmuscat.com',
      'https://twitter.com/bankmuscat',
      'https://www.instagram.com/bankmuscat/',
      'https://www.linkedin.com/company/bank-muscat/',
      '',
      'BMUSOMRX',
      '',
    ),
    bank(
      'National Bank of Oman',
      '+968 24770000',
      'Azaiba, Muscat, Oman',
      'https://apps.apple.com/om/app/nbo-mobile-banking/id534479122',
      'https://play.google.com/store/apps/details?id=com.nbo.om',
      'https://www.nbo.om',
      'customercare@nbo.om',
      'https://twitter.com/NBO_Oman',
      'https://www.instagram.com/nbo_oman/',
      'https://www.linkedin.com/company/national-bank-of-oman/',
      '',
      'NBOMOMRX',
      '',
    ),
    bank(
      'Sohar International',
      '+968 24730000',
      'Madinat Al Sultan Qaboos, Muscat, Oman',
      'https://apps.apple.com/om/app/sohar-international/id1455523628',
      'https://play.google.com/store/apps/details?id=com.sohar.mobilebanking',
      'https://www.soharinternational.com',
      'care@soharinternational.com',
      'https://twitter.com/Sohar_Intl',
      'https://www.instagram.com/sohar_intl/',
      'https://www.linkedin.com/company/sohar-international/',
      '',
      'BSHOOMRX',
      '',
    ),
  ],
  SC: [
    bank(
      'Nouvobanq',
      '+248 4 280 800',
      'Rue de la Possession, Victoria, Seychelles',
      '',
      '',
      'https://www.nouvobanq.sc/',
      'info@nouvobanq.sc',
      '',
      '',
      'https://www.linkedin.com/company/nouvobanq/',
      '',
      'NOVHSCSC',
      '',
    ),
    bank(
      'Absa Bank Seychelles',
      '+248 4 389 000',
      'Independence House Annex, Victoria, Seychelles',
      '',
      '',
      'https://www.absa.sc/',
      'seychelles@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'BARCSCSC',
      '',
    ),
    bank(
      'Mauritius Commercial Bank Seychelles',
      '+248 4 288 800',
      '9th Floor, Caravelle House, Victoria, Seychelles',
      '',
      '',
      'https://www.mcbseychelles.sc/',
      'contact@mcbseychelles.sc',
      '',
      '',
      'https://www.linkedin.com/company/mcb-seychelles/',
      '',
      'MCBLSCSC',
      '',
    ),
  ],
  SG: [
    bank(
      'DBS Bank',
      '+65 6878 8888',
      '12 Marina Boulevard, Marina Bay Financial Centre, Singapore',
      'https://apps.apple.com/sg/app/dbs-digibank/id1068403820',
      'https://play.google.com/store/apps/details?id=com.dbs.sg.dbsmbanking',
      'https://www.dbs.com.sg',
      'contactus@dbs.com',
      'https://twitter.com/dbsbank',
      'https://www.instagram.com/dbsbank/',
      'https://www.linkedin.com/company/dbs-bank/',
      '',
      'DBSSSGSG',
      '',
    ),
    bank(
      'OCBC Bank',
      '+65 6363 3333',
      '65 Chulia Street, OCBC Centre, Singapore',
      'https://apps.apple.com/sg/app/ocbc-digital/id292506828',
      'https://play.google.com/store/apps/details?id=com.ocbc.mobile',
      'https://www.ocbc.com',
      'contactus@ocbc.com',
      'https://twitter.com/OCBCBank',
      'https://www.instagram.com/ocbc/',
      'https://www.linkedin.com/company/ocbc-bank/',
      '',
      'OCBCSGSG',
      '',
    ),
    bank(
      'UOB',
      '+65 6222 2121',
      '80 Raffles Place, UOB Plaza, Singapore',
      'https://apps.apple.com/sg/app/uob-tmrw/id1314626819',
      'https://play.google.com/store/apps/details?id=com.uob.might',
      'https://www.uob.com.sg',
      'uobcustomerservice@uobgroup.com',
      'https://twitter.com/UOBGroup',
      'https://www.instagram.com/uobgroup/',
      'https://www.linkedin.com/company/uob/',
      '',
      'UOVBSGSG',
      '',
    ),
  ],
  SO: [
    bank(
      'Salaam Somali Bank',
      '+252 61 700 0000',
      'KM4, Mogadishu, Somalia',
      '',
      '',
      'https://www.salaambank.so/',
      'info@salaambank.so',
      '',
      '',
      'https://www.linkedin.com/company/salaam-somali-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Premier Bank Somalia',
      '+252 61 222 1111',
      'Airport Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.premierbank.so/',
      'info@premierbank.so',
      '',
      '',
      'https://www.linkedin.com/company/premier-bank-somalia/',
      '',
      '',
      '',
    ),
    bank(
      'Dahabshiil Bank International',
      '+252 63 333 3000',
      'Maka Al Mukarama Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.dahabshiilbank.com/',
      'info@dahabshiilbank.com',
      '',
      '',
      'https://www.linkedin.com/company/dahabshiil-bank-international/',
      '',
      '',
      '',
    ),
  ],
  ZA: [
    bank(
      'Standard Bank South Africa',
      '+27 11 636 9111',
      '5 Simmonds Street, Johannesburg, South Africa',
      '',
      '',
      'https://www.standardbank.co.za/',
      'information@standardbank.co.za',
      '',
      '',
      'https://www.linkedin.com/company/standard-bank-group/',
      '',
      'SBZAZAJJ',
      '',
    ),
    bank(
      'First National Bank South Africa',
      '+27 87 575 9404',
      '1 First Place, Bank City, Johannesburg, South Africa',
      '',
      '',
      'https://www.fnb.co.za/',
      'fnbcustomercare@fnb.co.za',
      '',
      '',
      'https://www.linkedin.com/company/fnb-south-africa/',
      '',
      'FIRNZAJJ',
      '',
    ),
    bank(
      'Absa Bank South Africa',
      '+27 11 350 4000',
      '7th Floor, Absa Towers West, Johannesburg, South Africa',
      '',
      '',
      'https://www.absa.co.za/',
      'absa@absa.africa',
      '',
      '',
      'https://www.linkedin.com/company/absa/',
      '',
      'ABSAZAJJ',
      '',
    ),
  ],
  LK: [
    bank(
      'Bank of Ceylon',
      '+94 11 244 6790',
      'No 1 Bank of Ceylon Mawatha, Colombo, Sri Lanka',
      '',
      '',
      'https://www.boc.lk',
      'customercare@boc.lk',
      '',
      '',
      '',
      '',
      'BCEYLKLX',
      '',
    ),
    bank(
      'Commercial Bank of Ceylon',
      '+94 11 235 3353',
      '21 Sir Razik Fareed Mawatha, Colombo, Sri Lanka',
      '',
      '',
      'https://www.combank.lk',
      'service@combank.net',
      '',
      '',
      '',
      '',
      'CCEYLKLX',
      '',
    ),
    bank(
      'People\'s Bank Sri Lanka',
      '+94 11 248 1481',
      'No 75 Sir Chittampalam A Gardiner Mawatha, Colombo, Sri Lanka',
      '',
      '',
      'https://www.peoplesbank.lk',
      'customersupport@peoplesbank.lk',
      '',
      '',
      '',
      '',
      'PSBKLKLX',
      '',
    ),
  ],
  TZ: [
    bank(
      'NMB Bank Tanzania',
      '+255 22 232 2000',
      'NMB House, Ohio Street, Dar es Salaam, Tanzania',
      '',
      '',
      'https://www.nmbbank.co.tz/',
      'customercare@nmbbank.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/nmb-bank-plc/',
      '',
      'NMIBTZTZ',
      '',
    ),
    bank(
      'CRDB Bank',
      '+255 22 219 7700',
      'Azikiwe Street, Dar es Salaam, Tanzania',
      '',
      '',
      'https://www.crdbbank.co.tz/',
      'servicequality@crdbbank.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/crdb-bank-plc/',
      '',
      'CORUTZTZ',
      '',
    ),
    bank(
      'NBC Bank Tanzania',
      '+255 22 219 7000',
      'Sokoine Drive, Dar es Salaam, Tanzania',
      '',
      '',
      'https://nbc.co.tz/',
      'customercare@nbc.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/nbc-bank-tanzania/',
      '',
      'NICATZTZ',
      '',
    ),
  ],
  TH: [
    bank(
      'Bangkok Bank',
      '+66 2 230 1323',
      '333 Silom Road, Bang Rak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/bualuang-mbanking/id660355106',
      'https://play.google.com/store/apps/details?id=com.bbl.mobilebanking',
      'https://www.bangkokbank.com',
      'customercare@bangkokbank.com',
      'https://twitter.com/bangkokbank',
      'https://www.instagram.com/bangkokbank/',
      'https://www.linkedin.com/company/bangkok-bank/',
      '',
      'BKKBTHBK',
      '',
    ),
    bank(
      'Kasikornbank',
      '+66 2 888 8888',
      '1 Soi Rat Burana 27/1, Rat Burana, Bangkok, Thailand',
      'https://apps.apple.com/th/app/k-plus/id361170631',
      'https://play.google.com/store/apps/details?id=com.kasikorn.retail.mbanking.wap',
      'https://www.kasikornbank.com',
      'kcontactcenter@kasikornbank.com',
      'https://twitter.com/KBank_Live',
      'https://www.instagram.com/kbanklive/',
      'https://www.linkedin.com/company/kasikornbank/',
      '',
      'KASITHBK',
      '',
    ),
    bank(
      'Siam Commercial Bank',
      '+66 2 777 7777',
      '9 Ratchadaphisek Road, Chatuchak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/scb-easy/id568388474',
      'https://play.google.com/store/apps/details?id=com.scb.phone',
      'https://www.scb.co.th',
      'customercare@scb.co.th',
      'https://twitter.com/scb_thailand',
      'https://www.instagram.com/scb_thailand/',
      'https://www.linkedin.com/company/the-siam-commercial-bank-public-company-limited/',
      '',
      'SICOTHBK',
      '',
    ),
  ],
  AE: [
    bank(
      'First Abu Dhabi Bank',
      '+971 2 4996100',
      'Khalifa Business Park, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/fab-mobile/id1023351966',
      'https://play.google.com/store/apps/details?id=com.fab.personal',
      'https://www.bankfab.com',
      'customerservice@bankfab.com',
      'https://twitter.com/FABConnects',
      'https://www.instagram.com/fabconnects/',
      'https://www.linkedin.com/company/first-abu-dhabi-bank-fab/',
      '',
      'NBADAEAA',
      '',
    ),
    bank(
      'Emirates NBD',
      '+971 600540000',
      'Baniyas Road, Deira, Dubai, UAE',
      'https://apps.apple.com/ae/app/emirates-nbd/id455204322',
      'https://play.google.com/store/apps/details?id=com.emberg.mobilebanking',
      'https://www.emiratesnbd.com',
      'customercare@emiratesnbd.com',
      'https://twitter.com/EmiratesNBD_AE',
      'https://www.instagram.com/emiratesnbd/',
      'https://www.linkedin.com/company/emiratesnbd/',
      '',
      'EBILAEAD',
      '',
    ),
    bank(
      'Abu Dhabi Commercial Bank',
      '+971 2 6210090',
      'Sheikh Zayed Street, Abu Dhabi, UAE',
      'https://apps.apple.com/ae/app/adcb-mobile-banking-app/id453927124',
      'https://play.google.com/store/apps/details?id=com.adcb.mobile.android',
      'https://www.adcb.com',
      'customer.care@adcb.com',
      'https://twitter.com/ADCB',
      'https://www.instagram.com/adcb/',
      'https://www.linkedin.com/company/adcb/',
      '',
      'ADCBAEAA',
      '',
    ),
  ],
  YE: [
    bank(
      'Yemen Kuwait Bank',
      '+967 1 274060',
      'Zubairi Street, Sanaa, Yemen',
      '',
      '',
      'https://www.yk-bank.com',
      'info@yk-bank.com',
      '',
      '',
      '',
      '',
      'YKBIYESA',
      '',
    ),
    bank(
      'Cooperative and Agricultural Credit Bank',
      '+967 1 407000',
      'Zubairi Street, Sanaa, Yemen',
      '',
      '',
      'https://www.cacbank.com.ye',
      'info@cacbank.com.ye',
      '',
      '',
      '',
      '',
      'CACBYESA',
      '',
    ),
    bank(
      'International Bank of Yemen',
      '+967 1 211700',
      'Algeria Street, Sanaa, Yemen',
      '',
      '',
      'https://www.ibyemen.com',
      'info@ibyemen.com',
      '',
      '',
      '',
      '',
      'IBYEMYEA',
      '',
    ),
  ],
}
