import type { NationalBankingInstitution } from './types'
import type { MintMemberIsoCode } from './mintMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per MINT member state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const MINT_NATIONAL_BANKING_INSTITUTIONS: Record<
  MintMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  MX: [
    bank(
      'BBVA Mexico',
      '+52 55 5621 3434',
      'Paseo de la Reforma 510, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/bbva-mexico/id375408965',
      'https://play.google.com/store/apps/details?id=com.bancomer.mbanking',
      'https://www.bbva.mx',
      'une.mx@bbva.com',
      'https://twitter.com/BBVA_Mex',
      'https://www.instagram.com/bbva_mex/',
      'https://www.linkedin.com/company/bbva-mexico/',
      '',
      'BCMRMXMM',
      '',
    ),
    bank(
      'Banorte',
      '+52 81 8156 9600',
      'Av. Revolucion 3000 Sur, Monterrey, Mexico',
      'https://apps.apple.com/mx/app/banorte-movil/id445541658',
      'https://play.google.com/store/apps/details?id=com.banorte.movil',
      'https://www.banorte.com',
      'une@banorte.com',
      'https://twitter.com/Banorte_mx',
      'https://www.instagram.com/banorte_mx/',
      'https://www.linkedin.com/company/grupo-financiero-banorte/',
      '',
      'MENOMXMT',
      '',
    ),
    bank(
      'Citibanamex',
      '+52 55 1226 2639',
      'Isabel la Catolica 44, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/citibanamex-movil/id394943449',
      'https://play.google.com/store/apps/details?id=com.citibanamex.banamexmobile',
      'https://www.banamex.com',
      'atencionaclientes@citibanamex.com',
      'https://twitter.com/Citibanamex',
      'https://www.instagram.com/citibanamex/',
      'https://www.linkedin.com/company/citibanamex/',
      '',
      'BNMXMXMM',
      '',
    ),
  ],
  ID: [
    bank(
      'Bank Mandiri',
      '+62 21 5299 7777',
      'Plaza Mandiri, Jl. Jend. Gatot Subroto, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/livin-by-mandiri/id1555417419',
      'https://play.google.com/store/apps/details?id=id.bmri.livin',
      'https://www.bankmandiri.co.id',
      'mandiricare@bankmandiri.co.id',
      'https://twitter.com/bankmandiri',
      'https://www.instagram.com/bankmandiri/',
      'https://www.linkedin.com/company/bankmandiri/',
      '',
      'BMRIIDJA',
      '',
    ),
    bank(
      'Bank Central Asia',
      '+62 21 2358 8000',
      'Menara BCA, Grand Indonesia, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/mybca/id1465918716',
      'https://play.google.com/store/apps/details?id=com.bca.mybca.omni.android',
      'https://www.bca.co.id',
      'halobca@bca.co.id',
      'https://twitter.com/BankBCA',
      'https://www.instagram.com/goodlifebca/',
      'https://www.linkedin.com/company/pt-bank-central-asia-tbk/',
      '',
      'CENAIDJA',
      '',
    ),
    bank(
      'Bank Negara Indonesia',
      '+62 21 5728387',
      'Jl. Jend. Sudirman Kav. 1, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/wondr-by-bni/id6474669196',
      'https://play.google.com/store/apps/details?id=id.co.bni.newagenbni46',
      'https://www.bni.co.id',
      'bnicall@bni.co.id',
      'https://twitter.com/BNI',
      'https://www.instagram.com/bni46/',
      'https://www.linkedin.com/company/pt-bank-negara-indonesia-persero-tbk/',
      '',
      'BNINIDJA',
      '',
    ),
  ],
  NG: [
    bank(
      'Access Bank Nigeria',
      '+234 1 271 2005',
      '14/15 Prince Alaba Oniru St, Victoria Island, Lagos, Nigeria',
      '',
      '',
      'https://www.accessbankplc.com/',
      'contactcenter@accessbankplc.com',
      '',
      '',
      'https://www.linkedin.com/company/access-bank-plc/',
      '',
      'ABNGNGLA',
      '',
    ),
    bank(
      'First Bank of Nigeria',
      '+234 1 905 2326',
      'Samuel Asabia House, 35 Marina, Lagos, Nigeria',
      '',
      '',
      'https://www.firstbanknigeria.com/',
      'firstcontact@firstbanknigeria.com',
      '',
      '',
      'https://www.linkedin.com/company/first-bank-of-nigeria-limited/',
      '',
      'FBNINGLA',
      '',
    ),
    bank(
      'Zenith Bank Nigeria',
      '+234 1 278 7000',
      'Plot 84 Ajose Adeogun St, Victoria Island, Lagos, Nigeria',
      '',
      '',
      'https://www.zenithbank.com/',
      'zenithdirect@zenithbank.com',
      '',
      '',
      'https://www.linkedin.com/company/zenith-bank-plc/',
      '',
      'ZEIBNGLA',
      '',
    ),
  ],
  TR: [
    bank(
      'Turkiye Is Bankasi',
      '+90 212 316 0000',
      'Is Kuleleri, Levent, Istanbul, Turkiye',
      '',
      '',
      'https://www.isbank.com.tr',
      'musteriiliskileri@isbank.com.tr',
      '',
      '',
      '',
      '',
      'ISBKTRIS',
      '',
    ),
    bank(
      'Ziraat Bankasi',
      '+90 312 584 2000',
      'Doganbey Mah. Ataturk Bulvari, Ankara, Turkiye',
      '',
      '',
      'https://www.ziraatbank.com.tr',
      'iletisim@ziraatbank.com.tr',
      '',
      '',
      '',
      '',
      'TCZBTR2A',
      '',
    ),
    bank(
      'Garanti BBVA',
      '+90 212 318 1818',
      'Levent Nispetiye Mah., Istanbul, Turkiye',
      '',
      '',
      'https://www.garantibbva.com.tr',
      'iletisim@garantibbva.com.tr',
      '',
      '',
      '',
      '',
      'TGBATRIS',
      '',
    ),
  ],
}
