import type { BriMemberIsoCode } from './participantStatesIsoCodes'
import type { BondMarketVenue } from './types'

function b(
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  apiEndpoint: string,
): BondMarketVenue {
  return { name, website, email, twitter, linkedin, apiEndpoint }
}

// ---- Regional venues shared across multiple BRI members ----

/**
 * Bourse Régionale des Valeurs Mobilières — the single regional listed exchange for the
 * eight UEMOA / West African CFA franc-zone states (BJ, BF, CI, GW, ML, NE, SN, TG).
 * Headquartered in Abidjan with a single trading floor; sovereign and corporate bonds are
 * listed alongside equities. No free public REST API — daily price / yield bulletins are
 * published as PDF / Excel and commercial feeds are distributed via Bloomberg / Refinitiv.
 */
const BRVM = b(
  'BRVM (Bourse Régionale des Valeurs Mobilières)',
  'https://www.brvm.org',
  'info@brvm.org',
  'https://x.com/brvm_officiel',
  'https://www.linkedin.com/company/brvm/',
  '',
)

/**
 * Bourse des Valeurs Mobilières d'Afrique Centrale — the unified CEMAC / Central African
 * CFA franc-zone exchange (post-2019 merger of the former BVMAC Libreville with the
 * Cameroonian Douala Stock Exchange). Covers CM, CF, TD, CG, GQ, GA. Headquartered in
 * Douala. Sovereign and corporate bond listings; no free public REST API — commercial
 * distribution via Bloomberg / Refinitiv.
 */
const BVMAC = b(
  'BVMAC (Bourse des Valeurs Mobilières d\'Afrique Centrale)',
  'https://www.bvm-ac.com',
  'contact@bvm-ac.com',
  'https://x.com/bvmacofficiel',
  'https://www.linkedin.com/company/bvmac/',
  '',
)

/**
 * Bond market venues by ISO 3166-1 alpha-2 for Belt and Road Initiative (BRI) participant
 * economies in this module (informational; verify URLs, handles, and API bases before
 * production use). BRI spans the world's largest sovereign-bond markets (CN, RU, IT, PL),
 * Gulf and Southeast Asian hubs (AE, SA, SG, MY, TH), regional African exchanges (JSE,
 * NSE, NGX, BRVM, BVMAC), and central-bank-only T-bills desks for small island economies.
 * Pattern:
 *   - National listed-bond exchanges appear as the primary entry where they exist.
 *   - Regional listed-bond exchanges — BRVM (UEMOA: BJ, CI, GW, ML, NE, SN, TG) and
 *     BVMAC (CEMAC: CM, CF, TD, CG, GQ, GA) — appear for franc-zone members.
 *   - Major economies list exchange + sovereign DMO / treasury primary desk where
 *     appropriate (CN: CFETS + SSE/SZSE; EG: EGX + MoF; ZA: JSE + National Treasury).
 *   - Countries with no listed bond venue use the central bank's Treasury bill / bond desk.
 *   - Multiple venues are listed where they coexist (NG: FMDQ + NGX + DMO; AE: ADX + DFM).
 * `apiEndpoint` is the empty string for virtually all venues — distribution via paid
 * Bloomberg / Refinitiv / vendor feeds. Verify periodically.
 */
export const BRI_BOND_MARKETS: Record<BriMemberIsoCode, readonly BondMarketVenue[]> = {
  AF: [
    b(
      'Da Afghanistan Bank (T-bills desk; no listed bond venue)',
      'https://dab.gov.af',
      'info@dab.gov.af',
      '',
      '',
      '',
    ),
  ],
  AL: [
    b(
      'Tirana Stock Exchange (TSE)',
      'https://www.tse.al',
      'info@tse.al',
      '',
      'https://www.linkedin.com/company/tirana-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt Management (sovereign primary)',
      'https://www.financa.gov.al',
      'info@financa.gov.al',
      '',
      '',
      '',
    ),
  ],
  DZ: [
    b(
      'Bourse d\'Alger (Société de Gestion de la Bourse des Valeurs — SGBV)',
      'https://www.sgbv.dz',
      'contact@sgbv.dz',
      '',
      '',
      '',
    ),
  ],
  AO: [
    b(
      'BODIVA (Bolsa de Dívida e Valores de Angola)',
      'https://www.bodiva.ao',
      'geral@bodiva.ao',
      'https://x.com/BODIVAangola',
      'https://www.linkedin.com/company/bodiva/',
      '',
    ),
  ],
  AG: [
    b(
      'Eastern Caribbean Securities Exchange (ECSE — Antigua and Barbuda listings)',
      'https://www.ecseonline.com',
      'info@ecseonline.com',
      '',
      '',
      '',
    ),
  ],
  AR: [
    b(
      'BYMA (Bolsas y Mercados Argentinos)',
      'https://www.byma.com.ar',
      'info@byma.com.ar',
      'https://x.com/bymaoficial',
      'https://www.linkedin.com/company/byma/',
      '',
    ),
    b(
      'Secretaría de Finanzas — Subsecretaría de Financiamiento (sovereign primary)',
      'https://www.argentina.gob.ar/economia/finanzas',
      'finanzas@mecon.gov.ar',
      '',
      '',
      '',
    ),
  ],
  AM: [
    b(
      'Armenia Securities Exchange (AMX)',
      'https://amx.am',
      'info@amx.am',
      '',
      '',
      '',
    ),
    b(
      'Central Bank of Armenia (government bond auctions)',
      'https://www.cba.am',
      'info@cba.am',
      '',
      '',
      '',
    ),
  ],
  AT: [
    b(
      'Wiener Börse AG (Vienna Stock Exchange)',
      'https://www.wienerborse.at',
      'info@wienerborse.at',
      'https://x.com/wienerborse',
      'https://www.linkedin.com/company/wiener-boerse-ag/',
      '',
    ),
    b(
      'Oesterreichische Kontrollbank (OeKB — sovereign primary)',
      'https://www.oekb.at',
      'info@oekb.at',
      '',
      'https://www.linkedin.com/company/oesterreichische-kontrollbank/',
      '',
    ),
  ],
  AZ: [
    b(
      'Baku Stock Exchange (BSE)',
      'https://www.bse.az',
      'info@bse.az',
      '',
      '',
      '',
    ),
  ],
  BH: [
    b(
      'Bahrain Bourse',
      'https://www.bahrainbourse.com',
      'info@bahrainbourse.com',
      'https://x.com/BahrainBourse',
      'https://www.linkedin.com/company/bahrain-bourse/',
      '',
    ),
    b(
      'Central Bank of Bahrain (CBB — sovereign Sukuk primary)',
      'https://www.cbb.gov.bh',
      'info@cbb.gov.bh',
      'https://x.com/CentralBankBH',
      'https://www.linkedin.com/company/central-bank-of-bahrain/',
      '',
    ),
  ],
  BD: [
    b(
      'Dhaka Stock Exchange (DSE)',
      'https://www.dsebd.org',
      'info@dsebd.org',
      '',
      'https://www.linkedin.com/company/dhaka-stock-exchange/',
      '',
    ),
    b(
      'Bangladesh Bank (government securities auctions)',
      'https://www.bb.org.bd',
      'info@bb.org.bd',
      '',
      '',
      '',
    ),
  ],
  BB: [
    b(
      'Barbados Stock Exchange (BSE)',
      'https://www.bse.com.bb',
      'info@bse.com.bb',
      '',
      'https://www.linkedin.com/company/barbados-stock-exchange/',
      '',
    ),
    b(
      'Central Bank of Barbados (T-bills desk)',
      'https://www.centralbank.org.bb',
      'info@centralbank.org.bb',
      '',
      '',
      '',
    ),
  ],
  BY: [
    b(
      'Belarusian Currency and Stock Exchange (BCSE)',
      'https://www.bcse.by',
      'info@bcse.by',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance of the Republic of Belarus (sovereign primary)',
      'https://www.minfin.gov.by',
      'info@minfin.gov.by',
      '',
      '',
      '',
    ),
  ],
  BJ: [BRVM],
  BO: [
    b(
      'Bolsa Boliviana de Valores (BBV)',
      'https://www.bbv.com.bo',
      'info@bbv.com.bo',
      '',
      '',
      '',
    ),
    b(
      'Ministerio de Economía y Finanzas Públicas (sovereign primary)',
      'https://www.economiayfinanzas.gob.bo',
      'info@economiayfinanzas.gob.bo',
      '',
      '',
      '',
    ),
  ],
  BA: [
    b(
      'Sarajevo Stock Exchange (SASE)',
      'https://www.sase.ba',
      'info@sase.ba',
      '',
      '',
      '',
    ),
    b(
      'Banja Luka Stock Exchange (BLSE)',
      'https://www.blberza.com',
      'info@blberza.com',
      '',
      '',
      '',
    ),
  ],
  BW: [
    b(
      'Botswana Stock Exchange (BSE) — Bond Market',
      'https://www.bse.co.bw',
      'enquiries@bse.co.bw',
      'https://x.com/BSE_Botswana',
      'https://www.linkedin.com/company/botswana-stock-exchange/',
      '',
    ),
  ],
  BN: [
    b(
      'Autoriti Monetari Brunei Darussalam (AMBD — T-bills / Sukuk desk; no listed bond venue)',
      'https://www.ambd.gov.bn',
      'info@ambd.gov.bn',
      '',
      'https://www.linkedin.com/company/autoriti-monetari-brunei-darussalam/',
      '',
    ),
  ],
  BG: [
    b(
      'Bulgarian Stock Exchange (BSE)',
      'https://www.bse-sofia.bg',
      'info@bse-sofia.bg',
      '',
      'https://www.linkedin.com/company/bulgarian-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt Directorate (sovereign primary)',
      'https://www.minfin.bg',
      'info@minfin.bg',
      '',
      '',
      '',
    ),
  ],
  BI: [
    b(
      'Banque de la République du Burundi (T-bills / T-bonds desk)',
      'https://www.brb.bi',
      'info@brb.bi',
      '',
      '',
      '',
    ),
  ],
  CV: [
    b(
      'Bolsa de Valores de Cabo Verde (BVC)',
      'https://www.bvc.cv',
      'bvc@bvc.cv',
      '',
      '',
      '',
    ),
  ],
  KH: [
    b(
      'Cambodia Securities Exchange (CSX)',
      'https://www.csx.com.kh',
      'info@csx.com.kh',
      '',
      'https://www.linkedin.com/company/cambodia-securities-exchange/',
      '',
    ),
    b(
      'National Bank of Cambodia (government bond auctions)',
      'https://www.nbc.gov.kh',
      'info@nbc.gov.kh',
      '',
      '',
      '',
    ),
  ],
  CM: [BVMAC],
  CF: [BVMAC],
  TD: [BVMAC],
  CL: [
    b(
      'Bolsa de Comercio de Santiago (BCS)',
      'https://www.bolsadesantiago.com',
      'info@bcs.cl',
      'https://x.com/bcs_cl',
      'https://www.linkedin.com/company/bolsa-de-comercio-de-santiago/',
      '',
    ),
    b(
      'Ministerio de Hacienda — Tesorería General de la República (sovereign primary)',
      'https://www.hacienda.cl',
      'contacto@hacienda.cl',
      '',
      '',
      '',
    ),
  ],
  CN: [
    b(
      'China Foreign Exchange Trade System (CFETS) — China Interbank Bond Market (CIBM)',
      'https://www.chinamoney.com.cn',
      'service@cfets.com.cn',
      '',
      '',
      '',
    ),
    b(
      'Shanghai Stock Exchange (SSE) — Exchange Bond Market',
      'https://www.sse.com.cn',
      'service@sse.com.cn',
      '',
      'https://www.linkedin.com/company/shanghai-stock-exchange/',
      '',
    ),
    b(
      'Shenzhen Stock Exchange (SZSE) — Exchange Bond Market',
      'https://www.szse.cn',
      'service@szse.cn',
      '',
      '',
      '',
    ),
  ],
  CO: [
    b(
      'Bolsa de Valores de Colombia (BVC)',
      'https://www.bvc.com.co',
      'info@bvc.com.co',
      'https://x.com/bvc_colombia',
      'https://www.linkedin.com/company/bolsa-de-valores-de-colombia/',
      '',
    ),
    b(
      'Ministerio de Hacienda y Crédito Público (sovereign primary)',
      'https://www.minhacienda.gov.co',
      'contacto@minhacienda.gov.co',
      '',
      '',
      '',
    ),
  ],
  KM: [
    b(
      'Banque Centrale des Comores (T-bills desk; no listed bond venue)',
      'https://www.banque-comores.km',
      'bcc@banque-comores.km',
      '',
      '',
      '',
    ),
  ],
  CK: [
    b(
      'Cook Islands Ministry of Finance and Economic Management (T-bills desk; no listed bond venue)',
      'https://www.mfem.gov.ck',
      'info@mfem.gov.ck',
      '',
      '',
      '',
    ),
  ],
  CR: [
    b(
      'Bolsa Nacional de Valores (BNV)',
      'https://www.bnvalores.com',
      'info@bnvalores.com',
      '',
      '',
      '',
    ),
    b(
      'Ministerio de Hacienda (sovereign primary)',
      'https://www.hacienda.go.cr',
      'info@hacienda.go.cr',
      '',
      '',
      '',
    ),
  ],
  CI: [BRVM],
  HR: [
    b(
      'Zagreb Stock Exchange (ZSE)',
      'https://www.zse.hr',
      'info@zse.hr',
      'https://x.com/ZSEhr',
      'https://www.linkedin.com/company/zagreb-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — State Debt (sovereign primary)',
      'https://mfin.gov.hr',
      'info@mfin.hr',
      '',
      '',
      '',
    ),
  ],
  CU: [
    b(
      'Banco Central de Cuba (T-bills desk; no listed bond venue)',
      'https://www.bc.gob.cu',
      'info@bc.gob.cu',
      '',
      '',
      '',
    ),
  ],
  CY: [
    b(
      'Cyprus Stock Exchange (CSE)',
      'https://www.cse.com.cy',
      'info@cse.com.cy',
      '',
      'https://www.linkedin.com/company/cyprus-stock-exchange/',
      '',
    ),
    b(
      'Public Debt Management Office — Ministry of Finance (sovereign primary)',
      'https://www.mof.gov.cy',
      'info@mof.gov.cy',
      '',
      '',
      '',
    ),
  ],
  CZ: [
    b(
      'Prague Stock Exchange (PSE)',
      'https://www.pse.cz',
      'info@pse.cz',
      '',
      'https://www.linkedin.com/company/prague-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Central Government Debt (sovereign primary)',
      'https://www.mfcr.cz',
      'info@mfcr.cz',
      '',
      '',
      '',
    ),
  ],
  CD: [
    b(
      'Banque Centrale du Congo (T-bills desk; no listed bond venue)',
      'https://www.bcc.cd',
      'info@bcc.cd',
      '',
      'https://www.linkedin.com/company/banque-centrale-du-congo/',
      '',
    ),
  ],
  DJ: [
    b(
      'Banque Centrale de Djibouti (T-bills desk; no listed bond venue)',
      'https://banque-centrale.dj',
      'info@banque-centrale.dj',
      '',
      '',
      '',
    ),
  ],
  DM: [
    b(
      'Eastern Caribbean Securities Exchange (ECSE — Dominica listings)',
      'https://www.ecseonline.com',
      'info@ecseonline.com',
      '',
      '',
      '',
    ),
  ],
  DO: [
    b(
      'Bolsa de Valores de la República Dominicana (BVRD)',
      'https://www.bvrd.com.do',
      'info@bvrd.com.do',
      '',
      'https://www.linkedin.com/company/bvrd/',
      '',
    ),
    b(
      'Ministerio de Hacienda (sovereign primary)',
      'https://www.hacienda.gob.do',
      'info@hacienda.gob.do',
      '',
      '',
      '',
    ),
  ],
  EC: [
    b(
      'Bolsa de Valores de Quito (BVQ)',
      'https://www.bvq.com.ec',
      'info@bvq.com.ec',
      '',
      '',
      '',
    ),
    b(
      'Bolsa de Valores de Guayaquil (BVG)',
      'https://www.bvg.com.ec',
      'info@bvg.com.ec',
      '',
      '',
      '',
    ),
    b(
      'Ministerio de Economía y Finanzas (sovereign primary)',
      'https://www.finanzas.gob.ec',
      'info@finanzas.gob.ec',
      '',
      '',
      '',
    ),
  ],
  EG: [
    b(
      'Egyptian Exchange (EGX)',
      'https://www.egx.com.eg',
      'egxinfo@egx.com.eg',
      'https://x.com/EGX_Egypt',
      'https://www.linkedin.com/company/the-egyptian-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Debt Management Unit (sovereign primary)',
      'https://www.mof.gov.eg',
      'contact@mof.gov.eg',
      '',
      '',
      '',
    ),
  ],
  SV: [
    b(
      'Bolsa de Valores de El Salvador (BVES)',
      'https://www.bves.com.sv',
      'info@bves.com.sv',
      '',
      '',
      '',
    ),
    b(
      'Banco Central de Reserva de El Salvador (sovereign primary)',
      'https://www.bcr.gob.sv',
      'info@bcr.gob.sv',
      '',
      '',
      '',
    ),
  ],
  GQ: [BVMAC],
  ER: [
    b(
      'Bank of Eritrea (T-bills desk; no listed bond venue)',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  EE: [
    b(
      'Nasdaq Baltic — Tallinn (fixed income listings)',
      'https://www.nasdaqbaltic.com',
      'info@nasdaqbaltic.com',
      '',
      'https://www.linkedin.com/company/nasdaq-baltic/',
      '',
    ),
    b(
      'State Treasury — Ministry of Finance (sovereign primary)',
      'https://www.rahandusministeerium.ee',
      'info@fin.ee',
      '',
      '',
      '',
    ),
  ],
  ET: [
    b(
      'Ethiopian Securities Exchange (ESX)',
      'https://esx.et',
      'info@esx.et',
      '',
      'https://www.linkedin.com/company/ethiopian-securities-exchange/',
      '',
    ),
    b(
      'National Bank of Ethiopia (T-bills desk)',
      'https://nbe.gov.et',
      'info@nbe.gov.et',
      '',
      '',
      '',
    ),
  ],
  FJ: [
    b(
      'South Pacific Stock Exchange (SPSE)',
      'https://www.spse.com.fj',
      'info@spse.com.fj',
      '',
      '',
      '',
    ),
    b(
      'Reserve Bank of Fiji (T-bills desk)',
      'https://www.rbf.gov.fj',
      'info@rbf.gov.fj',
      '',
      '',
      '',
    ),
  ],
  GA: [BVMAC],
  GM: [
    b(
      'Central Bank of The Gambia (T-bills / Sukuk Al-Salaam desk)',
      'https://www.cbg.gm',
      'info@cbg.gm',
      'https://x.com/CBGambia',
      'https://www.linkedin.com/company/central-bank-of-the-gambia/',
      '',
    ),
  ],
  GE: [
    b(
      'Georgian Stock Exchange (GSE)',
      'https://www.gse.ge',
      'info@gse.ge',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt (sovereign primary)',
      'https://www.mof.gov.ge',
      'info@mof.gov.ge',
      '',
      '',
      '',
    ),
  ],
  GH: [
    b(
      'Ghana Fixed Income Market (GFIM) — Ghana Stock Exchange',
      'https://gse.com.gh/gfim',
      'info@gse.com.gh',
      'https://x.com/GSEghana',
      'https://www.linkedin.com/company/ghana-stock-exchange/',
      '',
    ),
  ],
  GR: [
    b(
      'Athens Exchange (ATHEX) — Fixed Income Market',
      'https://www.athexgroup.gr',
      'info@athexgroup.gr',
      'https://x.com/athexgroup',
      'https://www.linkedin.com/company/athex/',
      '',
    ),
    b(
      'Public Debt Management Agency (PDMA — sovereign primary)',
      'https://www.pdma.gr',
      'info@pdma.gr',
      '',
      '',
      '',
    ),
  ],
  GD: [
    b(
      'Eastern Caribbean Securities Exchange (ECSE — Grenada listings)',
      'https://www.ecseonline.com',
      'info@ecseonline.com',
      '',
      '',
      '',
    ),
  ],
  GN: [
    b(
      'Banque Centrale de la République de Guinée (T-bills desk)',
      'https://www.bcrg-guinee.org',
      'info@bcrg-guinee.org',
      '',
      '',
      '',
    ),
  ],
  GW: [BRVM],
  GY: [
    b(
      'Guyana Stock Exchange (GSE)',
      'https://www.gyse.com.gy',
      'info@gyse.com.gy',
      '',
      '',
      '',
    ),
    b(
      'Bank of Guyana (T-bills desk)',
      'https://www.bankofguyana.org.gy',
      'info@bankofguyana.org.gy',
      '',
      '',
      '',
    ),
  ],
  HN: [
    b(
      'Bolsa Centroamericana de Valores (BCV — Honduras)',
      'https://www.bcv.hn',
      'info@bcv.hn',
      '',
      '',
      '',
    ),
    b(
      'Secretaría de Finanzas (sovereign primary)',
      'https://www.sefin.gob.hn',
      'info@sefin.gob.hn',
      '',
      '',
      '',
    ),
  ],
  HU: [
    b(
      'Budapest Stock Exchange (BSE)',
      'https://www.bse.hu',
      'info@bse.hu',
      'https://x.com/BudapestSE',
      'https://www.linkedin.com/company/budapest-stock-exchange/',
      '',
    ),
    b(
      'Government Debt Management Agency (ÁKK — sovereign primary)',
      'https://www.allamadossag.hu',
      'info@akk.hu',
      '',
      '',
      '',
    ),
  ],
  ID: [
    b(
      'Indonesia Stock Exchange (IDX) — Corporate Bond Market',
      'https://www.idx.co.id',
      'info@idx.co.id',
      'https://x.com/IDXOfficial',
      'https://www.linkedin.com/company/indonesia-stock-exchange/',
      '',
    ),
    b(
      'Directorate General of Financing and Risk Management — Ministry of Finance (SBN primary)',
      'https://www.djppr.kemenkeu.go.id',
      'djppr@kemenkeu.go.id',
      '',
      '',
      '',
    ),
  ],
  IR: [
    b(
      'Tehran Stock Exchange (TSE)',
      'https://www.tse.ir',
      'info@tse.ir',
      '',
      '',
      '',
    ),
    b(
      'Central Bank of Iran (government bond auctions)',
      'https://www.cbi.ir',
      'info@cbi.ir',
      '',
      '',
      '',
    ),
  ],
  IQ: [
    b(
      'Iraq Stock Exchange (ISX)',
      'https://www.isx-iq.net',
      'info@isx-iq.net',
      '',
      '',
      '',
    ),
    b(
      'Central Bank of Iraq (government bond auctions)',
      'https://cbi.iq',
      'info@cbi.iq',
      '',
      '',
      '',
    ),
  ],
  IT: [
    b(
      'Euronext Milan (Borsa Italiana) — MOT / EuroTLX bond segment',
      'https://www.borsaitaliana.it',
      'info@borsaitaliana.it',
      'https://x.com/borsaitaliana',
      'https://www.linkedin.com/company/borsa-italiana/',
      '',
    ),
    b(
      'Ministero dell\'Economia e delle Finanze — Dipartimento del Tesoro (sovereign primary)',
      'https://www.mef.gov.it',
      'info@dt.mef.gov.it',
      '',
      '',
      '',
    ),
  ],
  JM: [
    b(
      'Jamaica Stock Exchange (JSE)',
      'https://www.jamstockex.com',
      'info@jamstockex.com',
      'https://x.com/JamStockEx',
      'https://www.linkedin.com/company/jamaica-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance and the Public Service (sovereign primary)',
      'https://www.mof.gov.jm',
      'info@mof.gov.jm',
      '',
      '',
      '',
    ),
  ],
  JO: [
    b(
      'Amman Stock Exchange (ASE)',
      'https://www.ase.com.jo',
      'info@ase.com.jo',
      'https://x.com/ASEJO',
      'https://www.linkedin.com/company/amman-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt Department (sovereign primary)',
      'https://www.mof.gov.jo',
      'info@mof.gov.jo',
      '',
      '',
      '',
    ),
  ],
  KZ: [
    b(
      'Kazakhstan Stock Exchange (KASE)',
      'https://kase.kz',
      'info@kase.kz',
      'https://x.com/KASE_official',
      'https://www.linkedin.com/company/kazakhstan-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt (sovereign primary)',
      'https://www.gov.kz',
      'info@mf.gov.kz',
      '',
      '',
      '',
    ),
  ],
  KE: [
    b(
      'Nairobi Securities Exchange (NSE) — Fixed Income Market',
      'https://www.nse.co.ke',
      'info@nse.co.ke',
      'https://x.com/NSE_PLC',
      'https://www.linkedin.com/company/nairobi-securities-exchange/',
      '',
    ),
    b(
      'Central Bank of Kenya — DhowCSD (retail Treasury platform)',
      'https://www.dhowcsd.go.ke',
      'info@centralbank.go.ke',
      'https://x.com/CBKKenya',
      'https://www.linkedin.com/company/central-bank-of-kenya/',
      '',
    ),
  ],
  KI: [
    b(
      'Ministry of Finance and Economic Development — Kiribati (T-bills desk; no listed bond venue)',
      'https://www.mfed.gov.ki',
      'info@mfed.gov.ki',
      '',
      '',
      '',
    ),
  ],
  KW: [
    b(
      'Boursa Kuwait (Kuwait Stock Exchange)',
      'https://www.boursakuwait.com.kw',
      'info@boursakuwait.com.kw',
      'https://x.com/BoursaKuwait',
      'https://www.linkedin.com/company/boursa-kuwait/',
      '',
    ),
    b(
      'Central Bank of Kuwait (CBK — sovereign bond auctions)',
      'https://www.cbk.gov.kw',
      'info@cbk.gov.kw',
      '',
      'https://www.linkedin.com/company/central-bank-of-kuwait/',
      '',
    ),
  ],
  KG: [
    b(
      'Kyrgyz Stock Exchange (KSE)',
      'https://www.kse.kg',
      'info@kse.kg',
      '',
      '',
      '',
    ),
    b(
      'National Bank of the Kyrgyz Republic (government bond auctions)',
      'https://www.nbkr.kg',
      'info@nbkr.kg',
      '',
      '',
      '',
    ),
  ],
  LA: [
    b(
      'Lao Securities Exchange (LSX)',
      'https://www.lsx.com.la',
      'info@lsx.com.la',
      '',
      '',
      '',
    ),
    b(
      'Bank of the Lao PDR (government bond auctions)',
      'https://www.bol.gov.la',
      'info@bol.gov.la',
      '',
      '',
      '',
    ),
  ],
  LV: [
    b(
      'Nasdaq Riga (fixed income listings)',
      'https://www.nasdaqbaltic.com',
      'info@nasdaqbaltic.com',
      '',
      'https://www.linkedin.com/company/nasdaq-baltic/',
      '',
    ),
    b(
      'State Treasury — Ministry of Finance (sovereign primary)',
      'https://www.fm.gov.lv',
      'info@fm.gov.lv',
      '',
      '',
      '',
    ),
  ],
  LB: [
    b(
      'Beirut Stock Exchange (BSE)',
      'https://www.bse.com.lb',
      'info@bse.com.lb',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt Management (sovereign primary)',
      'https://www.finance.gov.lb',
      'info@finance.gov.lb',
      '',
      '',
      '',
    ),
  ],
  LS: [
    b(
      'Maseru Securities Market (MSM) — operated by Central Bank of Lesotho',
      'https://www.centralbank.org.ls',
      'info@centralbank.org.ls',
      '',
      '',
      '',
    ),
  ],
  LR: [
    b(
      'Central Bank of Liberia (T-bills desk; no listed bond venue)',
      'https://www.cbl.org.lr',
      'info@cbl.org.lr',
      '',
      'https://www.linkedin.com/company/central-bank-of-liberia/',
      '',
    ),
  ],
  LY: [
    b(
      'Libyan Stock Market (LSM)',
      'https://www.lsm.ly',
      'info@lsm.ly',
      '',
      '',
      '',
    ),
  ],
  LT: [
    b(
      'Nasdaq Vilnius (fixed income listings)',
      'https://www.nasdaqbaltic.com',
      'info@nasdaqbaltic.com',
      '',
      'https://www.linkedin.com/company/nasdaq-baltic/',
      '',
    ),
    b(
      'State Debt Management — Ministry of Finance (sovereign primary)',
      'https://www.finmin.lt',
      'info@finmin.lt',
      '',
      '',
      '',
    ),
  ],
  LU: [
    b(
      'Luxembourg Stock Exchange (LuxSE)',
      'https://www.luxse.com',
      'info@luxse.com',
      'https://x.com/LuxembourgSE',
      'https://www.linkedin.com/company/luxembourg-stock-exchange/',
      '',
    ),
    b(
      'Agence de l\'État — Administration de la Dette (sovereign primary)',
      'https://www.aetat.lu',
      'info@aetat.lu',
      '',
      '',
      '',
    ),
  ],
  MG: [
    b(
      'Banky Foiben\'i Madagasikara (T-bills auctions; no listed bond venue)',
      'https://www.banky-foiben.mg',
      'bfm@banky-foiben.mg',
      '',
      '',
      '',
    ),
  ],
  MW: [
    b(
      'Malawi Stock Exchange (MSE) — Debt Market',
      'https://www.mse.co.mw',
      'info@mse.co.mw',
      '',
      'https://www.linkedin.com/company/malawi-stock-exchange/',
      '',
    ),
  ],
  MY: [
    b(
      'Bursa Malaysia — Bond Market',
      'https://www.bursamalaysia.com',
      'bursamalaysia@bursamalaysia.com',
      'https://x.com/BursaMalaysia',
      'https://www.linkedin.com/company/bursa-malaysia/',
      '',
    ),
    b(
      'Bank Negara Malaysia — Malaysian Government Securities (MGS primary)',
      'https://www.bnm.gov.my',
      'bnmtelelink@bnm.gov.my',
      'https://x.com/BNM_official',
      'https://www.linkedin.com/company/bank-negara-malaysia/',
      '',
    ),
  ],
  MV: [
    b(
      'Maldives Monetary Authority (T-bills desk; no listed bond venue)',
      'https://www.mma.gov.mv',
      'info@mma.gov.mv',
      '',
      '',
      '',
    ),
  ],
  ML: [BRVM],
  MT: [
    b(
      'Malta Stock Exchange (MSE)',
      'https://www.borzamalta.com.mt',
      'info@borzamalta.com.mt',
      '',
      'https://www.linkedin.com/company/malta-stock-exchange/',
      '',
    ),
    b(
      'Central Bank of Malta (Malta Government Stocks primary)',
      'https://www.centralbankmalta.org',
      'info@centralbankmalta.org',
      '',
      '',
      '',
    ),
  ],
  MR: [
    b(
      'Banque Centrale de Mauritanie (T-bills desk; no listed bond venue)',
      'https://www.bcm.mr',
      'bcm@bcm.mr',
      '',
      '',
      '',
    ),
  ],
  FM: [
    b(
      'Bank of the Federated States of Micronesia (T-bills desk; no listed bond venue)',
      'https://www.fsmfinance.fm',
      'info@fsmfinance.fm',
      '',
      '',
      '',
    ),
  ],
  MD: [
    b(
      'Moldova Stock Exchange (MSE)',
      'https://www.mse.md',
      'info@mse.md',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance (sovereign primary)',
      'https://www.mf.gov.md',
      'info@mf.gov.md',
      '',
      '',
      '',
    ),
  ],
  MN: [
    b(
      'Mongolian Stock Exchange (MSE)',
      'https://www.mse.mn',
      'info@mse.mn',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance (sovereign primary)',
      'https://www.mof.gov.mn',
      'info@mof.gov.mn',
      '',
      '',
      '',
    ),
  ],
  ME: [
    b(
      'Montenegro Stock Exchange (MNSE)',
      'https://www.mnse.me',
      'info@mnse.me',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance (sovereign primary)',
      'https://www.gov.me',
      'info@mf.gov.me',
      '',
      '',
      '',
    ),
  ],
  MA: [
    b(
      'Bourse de Casablanca',
      'https://www.casablanca-bourse.com',
      'contact@casablanca-bourse.com',
      '',
      'https://www.linkedin.com/company/bourse-de-casablanca/',
      '',
    ),
    b(
      'Trésor du Royaume du Maroc — Direction du Trésor (sovereign primary)',
      'https://www.finances.gov.ma',
      'contact@dtfe.gov.ma',
      '',
      '',
      '',
    ),
  ],
  MZ: [
    b(
      'Bolsa de Valores de Moçambique (BVM)',
      'https://www.bvm.co.mz',
      'bvm@bvm.co.mz',
      '',
      '',
      '',
    ),
  ],
  MM: [
    b(
      'Yangon Stock Exchange (YSX — limited corporate listings; no liquid bond market)',
      'https://www.ysx-mm.com',
      'info@ysx-mm.com',
      '',
      '',
      '',
    ),
    b(
      'Central Bank of Myanmar (T-bills desk; no listed bond venue)',
      'https://www.cbm.gov.mm',
      'info@cbm.gov.mm',
      '',
      '',
      '',
    ),
  ],
  NA: [
    b(
      'Namibian Stock Exchange (NSX)',
      'https://www.nsx.com.na',
      'info@nsx.com.na',
      '',
      'https://www.linkedin.com/company/namibian-stock-exchange/',
      '',
    ),
    b(
      'Bank of Namibia (sovereign primary auctions)',
      'https://www.bon.com.na',
      'info@bon.com.na',
      '',
      '',
      '',
    ),
  ],
  NP: [
    b(
      'Nepal Stock Exchange (NEPSE)',
      'https://www.nepse.com.np',
      'info@nepse.com.np',
      '',
      '',
      '',
    ),
    b(
      'Nepal Rastra Bank (government bond auctions)',
      'https://www.nrb.org.np',
      'info@nrb.org.np',
      '',
      '',
      '',
    ),
  ],
  NZ: [
    b(
      'NZX Limited — Debt Market',
      'https://www.nzx.com',
      'info@nzx.com',
      'https://x.com/NZXGroup',
      'https://www.linkedin.com/company/nzx-limited/',
      '',
    ),
    b(
      'New Zealand Debt Management Office (NZDMO — sovereign primary)',
      'https://debtmanagement.treasury.govt.nz',
      'info@treasury.govt.nz',
      '',
      '',
      '',
    ),
  ],
  NI: [
    b(
      'Nicaragua Stock Exchange (BVSN)',
      'https://www.bvsn.com.ni',
      'info@bvsn.com.ni',
      '',
      '',
      '',
    ),
    b(
      'Ministerio de Hacienda y Crédito Público (sovereign primary)',
      'https://www.mhcp.gob.ni',
      'info@mhcp.gob.ni',
      '',
      '',
      '',
    ),
  ],
  NE: [BRVM],
  NG: [
    b(
      'FMDQ Securities Exchange (premier OTC fixed-income & derivatives venue)',
      'https://www.fmdqgroup.com',
      'info@fmdqgroup.com',
      'https://x.com/FMDQGroup',
      'https://www.linkedin.com/company/fmdq/',
      '',
    ),
    b(
      'Nigerian Exchange Group (NGX) — Bond Market',
      'https://ngxgroup.com',
      'contact@ngxgroup.com',
      'https://x.com/NGXGROUP',
      'https://www.linkedin.com/company/nigerian-exchange-group/',
      '',
    ),
    b(
      'Debt Management Office (DMO) Nigeria — sovereign primary',
      'https://www.dmo.gov.ng',
      'enquiries@dmo.gov.ng',
      'https://x.com/DMONigeria',
      'https://www.linkedin.com/company/debt-management-office-nigeria/',
      '',
    ),
  ],
  NU: [
    b(
      'Treasury Department — Niue (T-bills desk; no listed bond venue)',
      'https://www.gov.nu',
      'treasury@gov.nu',
      '',
      '',
      '',
    ),
  ],
  MK: [
    b(
      'Macedonian Stock Exchange (MSE)',
      'https://www.mse.mk',
      'info@mse.mk',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance (sovereign primary)',
      'https://www.finance.gov.mk',
      'info@finance.gov.mk',
      '',
      '',
      '',
    ),
  ],
  OM: [
    b(
      'Muscat Securities Market (MSM)',
      'https://www.msx.om',
      'info@msx.om',
      'https://x.com/MuscatSecMarket',
      'https://www.linkedin.com/company/muscat-securities-market/',
      '',
    ),
    b(
      'Central Bank of Oman (CBO — government development bonds)',
      'https://www.cbo.gov.om',
      'info@cbo.gov.om',
      '',
      '',
      '',
    ),
  ],
  PK: [
    b(
      'Pakistan Stock Exchange (PSX)',
      'https://www.psx.com.pk',
      'info@psx.com.pk',
      'https://x.com/OfficialPSX',
      'https://www.linkedin.com/company/pakistan-stock-exchange-limited/',
      '',
    ),
    b(
      'State Bank of Pakistan (government securities auctions)',
      'https://www.sbp.org.pk',
      'info@sbp.org.pk',
      '',
      '',
      '',
    ),
  ],
  PA: [
    b(
      'Latin American Stock Exchange (Latinex / BVPASA)',
      'https://www.panabolsa.com',
      'info@panabolsa.com',
      '',
      '',
      '',
    ),
    b(
      'Ministerio de Economía y Finanzas (sovereign primary)',
      'https://www.mef.gob.pa',
      'info@mef.gob.pa',
      '',
      '',
      '',
    ),
  ],
  PG: [
    b(
      'Port Moresby Stock Exchange (POMSoX)',
      'https://www.pomsox.com.pg',
      'info@pomsox.com.pg',
      '',
      '',
      '',
    ),
    b(
      'Bank of Papua New Guinea (T-bills desk; no liquid listed bond market)',
      'https://www.bankpng.gov.pg',
      'info@bankpng.gov.pg',
      '',
      '',
      '',
    ),
  ],
  PE: [
    b(
      'Bolsa de Valores de Lima (BVL)',
      'https://www.bvl.com.pe',
      'atencion@bvl.com.pe',
      'https://x.com/BVLperu',
      'https://www.linkedin.com/company/bolsa-de-valores-de-lima/',
      '',
    ),
    b(
      'Ministerio de Economía y Finanzas — Dirección General del Tesoro Público (sovereign primary)',
      'https://www.mef.gob.pe',
      'consultas@mef.gob.pe',
      '',
      '',
      '',
    ),
  ],
  PH: [
    b(
      'Philippine Dealing & Exchange Corp (PDEx) — OTC fixed-income platform',
      'https://www.pde.com.ph',
      'info@pde.com.ph',
      '',
      'https://www.linkedin.com/company/philippine-dealing-exchange-corp/',
      '',
    ),
    b(
      'Bureau of the Treasury (BTr — sovereign primary / retail Treasury bonds)',
      'https://www.treasury.gov.ph',
      'info@treasury.gov.ph',
      'https://x.com/PH_Treasury',
      '',
      '',
    ),
  ],
  PL: [
    b(
      'Warsaw Stock Exchange (GPW) — Catalyst bond market',
      'https://www.gpw.pl',
      'info@gpw.pl',
      'https://x.com/Warsaw_Stock',
      'https://www.linkedin.com/company/warsaw-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt (sovereign primary)',
      'https://www.gov.pl/web/finance',
      'info@mf.gov.pl',
      '',
      '',
      '',
    ),
  ],
  PT: [
    b(
      'Euronext Lisbon — Fixed Income Market',
      'https://www.euronext.com',
      'info@euronext.com',
      'https://x.com/Euronext',
      'https://www.linkedin.com/company/euronext/',
      '',
    ),
    b(
      'IGCP — Agência de Gestão da Tesouraria e da Dívida Pública (sovereign primary)',
      'https://www.igcp.pt',
      'info@igcp.pt',
      '',
      '',
      '',
    ),
  ],
  QA: [
    b(
      'Qatar Stock Exchange (QSE)',
      'https://www.qe.com.qa',
      'info@qe.com.qa',
      'https://x.com/QatarExchange',
      'https://www.linkedin.com/company/qatar-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt Management (sovereign primary)',
      'https://www.mof.gov.qa',
      'info@mof.gov.qa',
      '',
      '',
      '',
    ),
  ],
  CG: [BVMAC],
  RO: [
    b(
      'Bucharest Stock Exchange (BVB)',
      'https://www.bvb.ro',
      'info@bvb.ro',
      'https://x.com/BVB_Ro',
      'https://www.linkedin.com/company/bucharest-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Public Finance — Public Debt (sovereign primary)',
      'https://www.mfinante.gov.ro',
      'info@mfinante.gov.ro',
      '',
      '',
      '',
    ),
  ],
  RU: [
    b(
      'Moscow Exchange (MOEX) — Bond Market',
      'https://www.moex.com',
      'info@moex.com',
      'https://x.com/Moscow_Exchange',
      'https://www.linkedin.com/company/moscow-exchange/',
      '',
    ),
    b(
      'Ministry of Finance of the Russian Federation (OFZ primary auctions)',
      'https://minfin.gov.ru',
      'info@minfin.gov.ru',
      '',
      '',
      '',
    ),
  ],
  RW: [
    b(
      'Rwanda Stock Exchange (RSE)',
      'https://rse.rw',
      'info@rse.rw',
      '',
      'https://www.linkedin.com/company/rwanda-stock-exchange/',
      '',
    ),
  ],
  WS: [
    b(
      'Samoa Stock Exchange (SSX)',
      'https://www.samoastockexchange.ws',
      'info@samoastockexchange.ws',
      '',
      '',
      '',
    ),
    b(
      'Central Bank of Samoa (T-bills desk)',
      'https://www.cbs.gov.ws',
      'info@cbs.gov.ws',
      '',
      '',
      '',
    ),
  ],
  SA: [
    b(
      'Saudi Exchange (Tadawul) — Sukuk & Bonds Market',
      'https://www.saudiexchange.sa',
      'info@saudiexchange.sa',
      'https://x.com/SaudiExchange',
      'https://www.linkedin.com/company/saudi-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Debt Management Office (sovereign primary)',
      'https://www.mof.gov.sa',
      'info@mof.gov.sa',
      '',
      '',
      '',
    ),
  ],
  SN: [BRVM],
  RS: [
    b(
      'Belgrade Stock Exchange (BELEX)',
      'https://www.belex.rs',
      'info@belex.rs',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt Administration (sovereign primary)',
      'https://www.mfin.gov.rs',
      'info@mfin.gov.rs',
      '',
      '',
      '',
    ),
  ],
  SC: [
    b(
      'MERJ Exchange (Mauritius-anchored multi-asset venue listing Seychelles debt)',
      'https://merj.exchange',
      'info@merj.exchange',
      'https://x.com/MERJexchange',
      'https://www.linkedin.com/company/merj-exchange/',
      '',
    ),
  ],
  SL: [
    b(
      'Bank of Sierra Leone (T-bills / T-bonds desk; no listed bond venue)',
      'https://www.bsl.gov.sl',
      'info@bsl.gov.sl',
      '',
      '',
      '',
    ),
  ],
  SG: [
    b(
      'Singapore Exchange (SGX) — Fixed Income',
      'https://www.sgx.com',
      'helpdesk@sgx.com',
      'https://x.com/SGX',
      'https://www.linkedin.com/company/sgx/',
      '',
    ),
    b(
      'Monetary Authority of Singapore (MAS — Singapore Government Securities primary)',
      'https://www.mas.gov.sg',
      'contact@mas.gov.sg',
      'https://x.com/mas_sg',
      'https://www.linkedin.com/company/monetary-authority-of-singapore/',
      '',
    ),
  ],
  SK: [
    b(
      'Bratislava Stock Exchange (BSSE)',
      'https://www.bsse.sk',
      'info@bsse.sk',
      '',
      '',
      '',
    ),
    b(
      'Agentúra pre riadenie dlhu a likvidity (ARDAL — sovereign primary)',
      'https://www.ardal.sk',
      'info@ardal.sk',
      '',
      '',
      '',
    ),
  ],
  SI: [
    b(
      'Ljubljana Stock Exchange (LJSE)',
      'https://www.ljse.si',
      'info@ljse.si',
      '',
      'https://www.linkedin.com/company/ljubljana-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt (sovereign primary)',
      'https://www.gov.si',
      'info@mf.gov.si',
      '',
      '',
      '',
    ),
  ],
  SB: [
    b(
      'Central Bank of Solomon Islands (T-bills desk; no listed bond venue)',
      'https://www.cbsi.com.sb',
      'info@cbsi.com.sb',
      '',
      '',
      '',
    ),
  ],
  SO: [
    b(
      'Central Bank of Somalia (T-bills desk; no listed bond venue)',
      'https://www.centralbank.gov.so',
      'info@centralbank.gov.so',
      '',
      '',
      '',
    ),
  ],
  ZA: [
    b(
      'Johannesburg Stock Exchange (JSE) — Interest Rate Market',
      'https://www.jse.co.za',
      'info@jse.co.za',
      'https://x.com/JSE_Group',
      'https://www.linkedin.com/company/jse-ltd/',
      '',
    ),
    b(
      'National Treasury — Asset and Liability Management (sovereign primary)',
      'https://www.treasury.gov.za',
      'enquiries@treasury.gov.za',
      '',
      '',
      '',
    ),
  ],
  SS: [
    b(
      'Bank of South Sudan (T-bills desk; no listed bond venue)',
      'https://boss.gov.ss',
      'info@boss.gov.ss',
      '',
      '',
      '',
    ),
  ],
  LK: [
    b(
      'Colombo Stock Exchange (CSE)',
      'https://www.cse.lk',
      'info@cse.lk',
      'https://x.com/CSE_Media',
      'https://www.linkedin.com/company/colombo-stock-exchange/',
      '',
    ),
    b(
      'Central Bank of Sri Lanka (government securities auctions)',
      'https://www.cbsl.gov.lk',
      'info@cbsl.gov.lk',
      '',
      '',
      '',
    ),
  ],
  SD: [
    b(
      'Khartoum Stock Exchange (KSE) — Sukuk and bonds',
      'https://www.kse.sd',
      'info@kse.sd',
      '',
      'https://www.linkedin.com/company/khartoum-stock-exchange/',
      '',
    ),
  ],
  SR: [
    b(
      'Suriname Stock Exchange (SSX)',
      'https://www.ssx.sr',
      'info@ssx.sr',
      '',
      '',
      '',
    ),
    b(
      'Central Bank of Suriname (T-bills desk)',
      'https://www.cbvs.sr',
      'info@cbvs.sr',
      '',
      '',
      '',
    ),
  ],
  SY: [
    b(
      'Damascus Securities Exchange (DSE — limited activity; verify status)',
      'http://www.dse.sy',
      'info@dse.sy',
      '',
      '',
      '',
    ),
  ],
  TJ: [
    b(
      'Dushanbe Stock Exchange (DSE)',
      'https://www.dse.tj',
      'info@dse.tj',
      '',
      '',
      '',
    ),
    b(
      'National Bank of Tajikistan (government bond auctions)',
      'https://www.nbt.tj',
      'info@nbt.tj',
      '',
      '',
      '',
    ),
  ],
  TZ: [
    b(
      'Dar es Salaam Stock Exchange (DSE) — Fixed Income Market',
      'https://www.dse.co.tz',
      'info@dse.co.tz',
      'https://x.com/DSEtanzania',
      'https://www.linkedin.com/company/dar-es-salaam-stock-exchange/',
      '',
    ),
    b(
      'Bank of Tanzania (sovereign primary auctions)',
      'https://www.bot.go.tz',
      'info@bot.go.tz',
      '',
      '',
      '',
    ),
  ],
  TH: [
    b(
      'Thai Bond Market Association (ThaiBMA)',
      'https://www.thaibma.or.th',
      'info@thaibma.or.th',
      '',
      'https://www.linkedin.com/company/thai-bond-market-association/',
      '',
    ),
    b(
      'Stock Exchange of Thailand (SET) — Corporate Bonds',
      'https://www.set.or.th',
      'info@set.or.th',
      'https://x.com/SET_Thailand',
      'https://www.linkedin.com/company/the-stock-exchange-of-thailand/',
      '',
    ),
    b(
      'Public Debt Management Office (PDMO — sovereign primary)',
      'https://www.pdmo.go.th',
      'info@pdmo.go.th',
      '',
      '',
      '',
    ),
  ],
  TL: [
    b(
      'Banco Central de Timor-Leste (T-bills desk; no listed bond venue)',
      'https://www.bancocentral.tl',
      'info@bancocentral.tl',
      '',
      '',
      '',
    ),
  ],
  TG: [BRVM],
  TO: [
    b(
      'Ministry of Finance — Tonga (T-bills desk; no listed bond venue)',
      'https://www.finance.gov.to',
      'info@finance.gov.to',
      '',
      '',
      '',
    ),
  ],
  TT: [
    b(
      'Trinidad and Tobago Stock Exchange (TTSE)',
      'https://www.stockex.co.tt',
      'info@stockex.co.tt',
      '',
      'https://www.linkedin.com/company/trinidad-and-tobago-stock-exchange/',
      '',
    ),
    b(
      'Ministry of Finance (sovereign primary)',
      'https://www.finance.gov.tt',
      'info@finance.gov.tt',
      '',
      '',
      '',
    ),
  ],
  TN: [
    b(
      'Bourse de Tunis (BVMT)',
      'https://www.bvmt.com.tn',
      'bvmt@bvmt.com.tn',
      '',
      'https://www.linkedin.com/company/bourse-de-tunis/',
      '',
    ),
  ],
  TR: [
    b(
      'Borsa Istanbul — Debt Securities Market',
      'https://www.borsaistanbul.com',
      'info@borsaistanbul.com',
      'https://x.com/BorsaIstanbul',
      'https://www.linkedin.com/company/borsa-istanbul/',
      '',
    ),
    b(
      'Undersecretariat of Treasury — Republic of Türkiye (sovereign primary)',
      'https://www.hazine.gov.tr',
      'info@hazine.gov.tr',
      '',
      '',
      '',
    ),
  ],
  TM: [
    b(
      'Central Bank of Turkmenistan (T-bills desk; no listed bond venue)',
      'https://www.cbt.tm',
      'info@cbt.tm',
      '',
      '',
      '',
    ),
  ],
  UG: [
    b(
      'Uganda Securities Exchange (USE) — Fixed Income Market',
      'https://www.use.or.ug',
      'info@use.or.ug',
      '',
      'https://www.linkedin.com/company/uganda-securities-exchange/',
      '',
    ),
    b(
      'Bank of Uganda (sovereign primary auctions)',
      'https://www.bou.or.ug',
      'info@bou.or.ug',
      '',
      '',
      '',
    ),
  ],
  UA: [
    b(
      'PFTS Stock Exchange — Fixed Income Market',
      'https://www.pfts.com',
      'info@pfts.com',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance — Public Debt Management (sovereign primary)',
      'https://www.minfin.gov.ua',
      'info@minfin.gov.ua',
      '',
      '',
      '',
    ),
  ],
  AE: [
    b(
      'Abu Dhabi Securities Exchange (ADX)',
      'https://www.adx.ae',
      'info@adx.ae',
      'https://x.com/ADXUAE',
      'https://www.linkedin.com/company/abu-dhabi-securities-exchange/',
      '',
    ),
    b(
      'Dubai Financial Market (DFM)',
      'https://www.dfm.ae',
      'info@dfm.ae',
      'https://x.com/DubaiFinancialMarket',
      'https://www.linkedin.com/company/dubai-financial-market/',
      '',
    ),
    b(
      'Nasdaq Dubai (international bond listing hub)',
      'https://www.nasdaqdubai.com',
      'info@nasdaqdubai.com',
      '',
      'https://www.linkedin.com/company/nasdaq-dubai/',
      '',
    ),
  ],
  UY: [
    b(
      'Bolsa de Valores de Montevideo (BVM)',
      'https://www.bvm.com.uy',
      'info@bvm.com.uy',
      '',
      '',
      '',
    ),
    b(
      'Ministerio de Economía y Finanzas (sovereign primary)',
      'https://www.gub.uy',
      'info@mef.gub.uy',
      '',
      '',
      '',
    ),
  ],
  UZ: [
    b(
      'Tashkent Stock Exchange (UZSE)',
      'https://www.uzse.uz',
      'info@uzse.uz',
      '',
      '',
      '',
    ),
    b(
      'Ministry of Finance (sovereign primary)',
      'https://www.mf.uz',
      'info@mf.uz',
      '',
      '',
      '',
    ),
  ],
  VU: [
    b(
      'Reserve Bank of Vanuatu (T-bills desk; no listed bond venue)',
      'https://www.vrbv.vu',
      'info@vrbv.vu',
      '',
      '',
      '',
    ),
  ],
  VE: [
    b(
      'Bolsa de Valores de Caracas (BVC)',
      'https://www.bvc.com.ve',
      'info@bvc.com.ve',
      '',
      '',
      '',
    ),
    b(
      'Banco Central de Venezuela (sovereign primary)',
      'https://www.bcv.org.ve',
      'info@bcv.org.ve',
      '',
      '',
      '',
    ),
  ],
  VN: [
    b(
      'Hanoi Stock Exchange (HNX) — Government & Corporate Bond Market',
      'https://www.hnx.vn',
      'info@hnx.vn',
      '',
      'https://www.linkedin.com/company/hanoi-stock-exchange/',
      '',
    ),
    b(
      'Ho Chi Minh Stock Exchange (HOSE) — Corporate Bonds',
      'https://www.hsx.vn',
      'info@hsx.vn',
      '',
      '',
      '',
    ),
    b(
      'State Treasury of Vietnam (sovereign primary)',
      'https://www.kbnn.gov.vn',
      'info@kbnn.gov.vn',
      '',
      '',
      '',
    ),
  ],
  YE: [
    b(
      'Central Bank of Yemen (T-bills desk; no listed bond venue)',
      'https://www.centralbank.gov.ye',
      'info@centralbank.gov.ye',
      '',
      '',
      '',
    ),
  ],
  ZM: [
    b(
      'Lusaka Securities Exchange (LuSE) — Government Bond Market',
      'https://luse.co.zm',
      'info@luse.co.zm',
      '',
      'https://www.linkedin.com/company/lusaka-securities-exchange/',
      '',
    ),
  ],
  ZW: [
    b(
      'Zimbabwe Stock Exchange (ZSE)',
      'https://www.zse.co.zw',
      'info@zse.co.zw',
      'https://x.com/ZSE_OFFICIAL',
      'https://www.linkedin.com/company/zimbabwe-stock-exchange/',
      '',
    ),
    b(
      'Victoria Falls Stock Exchange (VFEX) — USD-denominated debt',
      'https://www.vfex.exchange',
      'info@vfex.exchange',
      'https://x.com/VFEX_Exchange',
      'https://www.linkedin.com/company/vfex/',
      '',
    ),
  ],
}
