import type { CorporationFormationOffice } from './types'
import type { BriMemberIsoCode } from './participantStatesIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per Belt and Road participant economy.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const BRI_CORPORATION_FORMATION_OFFICES: Record<BriMemberIsoCode, CorporationFormationOffice> = {
  AF:   office(
    'Afghanistan Central Business Registry (Ministry of Industry and Commerce)',
    '+93 20 210 6666',
    'Kabul, Afghanistan',
    'https://www.acci.org.af',
    'info@acci.org.af',
    '',
    '',
    '',
    'https://www.acci.org.af',
    'https://www.acci.org.af/business-registration',
    'Tax Identification Number (TIN)',
  ),
  AL:   office(
    'National Business Center Albania (QKB)',
    '+355 4 222 0000',
    'Rruga e Kavajes, Tirana, Albania',
    'https://www.qkb.gov.al',
    'info@qkb.gov.al',
    '',
    '',
    'https://www.linkedin.com/company/qendra-kombetare-e-biznesit/',
    'https://e-albania.al',
    'https://www.qkb.gov.al/perdoruesit-e-re/te-hapesh-nje-biznes',
    'NIPT (Numri Identifikues i Personit te Tatueshem)',
  ),
  DZ:   office(
    'Centre National du Registre du Commerce (CNRC)',
    '+213 23 50 34 34',
    'Route nationale no 24, Lido, Mohammadia, Algiers, Algeria',
    'https://sidjilcom.cnrc.dz',
    'contact@cnrc.dz',
    '',
    '',
    'https://www.linkedin.com/company/cnrc-algerie/',
    'https://sidjilcom.cnrc.dz/inscription',
    'https://sidjilcom.cnrc.dz/faq',
    'Numero du Registre du Commerce (NRC)',
  ),
  AO:   office(
    'Guiche Unico da Empresa (GUE) Angola',
    '+244 222 331 251',
    'Largo da Maianga, Edificio One Metropolis, Luanda, Angola',
    'https://gue.gov.ao',
    'geral@gue.gov.ao',
    '',
    '',
    '',
    'https://gue.gov.ao/ao/servicos/criacao-de-empresas',
    'https://gue.gov.ao/ao/servicos/requisitos',
    'Numero de Identificacao de Pessoa Coletiva (NIF)',
  ),
  AG:   office(
    'Intellectual Property and Commerce Office (IPCO) Antigua and Barbuda',
    '+1 268 462 0007',
    'High Street, St John\'s, Antigua and Barbuda',
    'https://www.ipco.gov.ag',
    'ipco@gov.ag',
    '',
    '',
    '',
    'https://www.ipco.gov.ag',
    'https://www.ab.gov.ag/content/registering-business',
    'Company Registration Number',
  ),
  AR:   office(
    'Public Registry of Commerce (IGJ Argentina)',
    '+54 11 4334 0450',
    'Av. Julio A. Roca 651, Buenos Aires, Argentina',
    'https://www.argentina.gob.ar/justicia/registro-nacional-sociedades',
    '',
    '',
    '',
    '',
    'https://www.argentina.gob.ar/justicia/registro-nacional-sociedades/tramites',
    'https://www.argentina.gob.ar/produccion/registrar-una-empresa',
    'CUIT (Clave Unica de Identificacion Tributaria)',
  ),
  AM:   office(
    'State Register of Legal Entities (Ministry of Justice Armenia)',
    '+374 10 523 523',
    '3 Vazgen Sargsyan St, Yerevan, Armenia',
    'https://www.e-register.am',
    'info@moj.am',
    '',
    '',
    '',
    'https://www.e-register.am',
    'https://www.moj.am/en/services',
    'State Registration Number',
  ),
  AT:   office(
    'Firmenbuch (Commercial Register Austria)',
    '+43 1 52152 0',
    'Schottenring 30, 1010 Vienna, Austria',
    'https://www.justiz.gv.at',
    '',
    '',
    '',
    '',
    'https://www.justiz.gv.at/service/firmenbuch.html',
    'https://www.wko.at/service/unternehmensgruendung',
    'Firmenbuchnummer',
  ),
  AZ:   office(
    'State Tax Service of Azerbaijan (Business Registration)',
    '+994 12 195',
    '167 Nizami St, Baku, Azerbaijan',
    'https://www.taxes.gov.az',
    'info@taxes.gov.az',
    '',
    '',
    '',
    'https://www.e-taxes.gov.az',
    'https://www.economy.gov.az/en/pages/view/starting-a-business',
    'VOEN (Taxpayer Identification Number)',
  ),
  BH:   office(
    'Sijilat (Ministry of Industry and Commerce Bahrain)',
    '+973 1757 7777',
    'Bahrain Financial Harbour, Manama, Bahrain',
    'https://www.sijilat.bh',
    'info@moic.gov.bh',
    '',
    '',
    '',
    'https://www.sijilat.bh',
    'https://www.bahrain.bh/wps/portal/en/BNP/HomeNationalPortal/ContentDetailsPage/!ut/p/z1',
    'Commercial Registration (CR) Number',
  ),
  BD:   office(
    'Registrar of Joint Stock Companies and Firms (RJSC)',
    '+880 2 951 2778',
    'E-6/B, Agargaon Administrative Area, Dhaka, Bangladesh',
    'https://www.roc.gov.bd',
    'info@roc.gov.bd',
    '',
    '',
    '',
    'https://www.roc.gov.bd',
    'https://www.bida.gov.bd/invest-in-bangladesh/starting-business',
    'Company Registration Number',
  ),
  BB:   office(
    'Corporate Affairs and Intellectual Property Office (CAIPO) Barbados',
    '+1 246 535 5600',
    'Baobab Tower, Warrens, St Michael, Barbados',
    'https://www.caipo.gov.bb',
    'caipo@gov.bb',
    '',
    '',
    '',
    'https://www.caipo.gov.bb',
    'https://www.investbarbados.org/starting-a-business',
    'Company Registration Number',
  ),
  BY:   office(
    'Unified State Register of Legal Entities (Ministry of Justice Belarus)',
    '+375 17 200 00 46',
    'Kollektsionnaya 10, Minsk, Belarus',
    'https://www.minjust.gov.by',
    'info@minjust.gov.by',
    '',
    '',
    '',
    'https://egr.gov.by',
    'https://www.minjust.gov.by/en/activities/state-registration',
    'UNP (Unified Taxpayer Number)',
  ),
  BJ:   office(
    'APIEx Benin - Guichet Unique de Formalisation des Entreprises',
    '+229 21 31 00 65',
    'Boulevard de la Marina, Cotonou, Benin',
    'https://apiex.bj',
    'info@apiex.bj',
    'https://x.com/APIEX_BENIN',
    '',
    'https://www.linkedin.com/company/apiex-benin/',
    'https://monentreprise.bj',
    'https://apiex.bj/guide-du-createur',
    'Numero IFU (Identifiant Fiscal Unique)',
  ),
  BO:   office(
    'Fundempresa Bolivia (Business Formalization)',
    '+591 2 211 6000',
    'Av. Camacho 1296, La Paz, Bolivia',
    'https://www.fundempresa.org.bo',
    'info@fundempresa.org.bo',
    '',
    '',
    '',
    'https://www.fundempresa.org.bo',
    'https://www.fundempresa.org.bo/tramites',
    'NIT (Numero de Identificacion Tributaria)',
  ),
  BA:   office(
    'Registry of Business Entities (Bosnia and Herzegovina)',
    '+387 33 666 000',
    'Sarajevo, Bosnia and Herzegovina',
    'https://www.fbih.gov.ba',
    '',
    '',
    '',
    '',
    'https://www.rju.gov.ba',
    'https://fipa.gov.ba/invest-in-bih/starting-a-business',
    'ID Number (JIB)',
  ),
  BW:   office(
    'Companies and Intellectual Property Authority (CIPA)',
    '+267 367 3700',
    'Plot 50676, Fairgrounds Office Park, Gaborone, Botswana',
    'https://www.cipa.co.bw',
    'info@cipa.co.bw',
    'https://x.com/CIPA_Botswana',
    '',
    'https://www.linkedin.com/company/cipa-botswana/',
    'https://www.cipa.co.bw/register-a-company',
    'https://www.cipa.co.bw/company-registration-checklist',
    'Company Registration Number',
  ),
  BN:   office(
    'Registry of Companies and Business Names (ROCBN)',
    '+673 2383444',
    'Ministry of Finance and Economy, Bandar Seri Begawan, Brunei Darussalam',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    '',
    '',
    '',
    '',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    'https://business.gov.bn/SitePages/Starting%20a%20Business.aspx',
    'Business Registration Number',
  ),
  BG:   office(
    'Registry Agency Bulgaria (Commercial Register)',
    '+359 2 948 9000',
    '52 Knyaz Dondukov Blvd, Sofia, Bulgaria',
    'https://www.registryagency.bg',
    'info@registryagency.bg',
    '',
    '',
    '',
    'https://portal.registryagency.bg',
    'https://www.registryagency.bg/en/services',
    'UIC (Unified Identification Code)',
  ),
  BI:   office(
    'Agence de Developpement du Burundi (ADB) - Guichet Unique',
    '+257 22 27 90 00',
    'Avenue du Large, Immeuble Old East, Bujumbura, Burundi',
    'https://investburundi.bi',
    'info@investburundi.bi',
    '',
    '',
    '',
    'https://investburundi.bi/guichet-unique',
    'https://investburundi.bi/procedures-de-creation',
    'Numero RCCM',
  ),
  CV:   office(
    'Casa do Cidadao - Empresa no Dia (Cabo Verde)',
    '+238 260 38 30',
    'Achada Santo Antonio, Praia, Cabo Verde',
    'https://casadocidadao.cv',
    'contacto@casadocidadao.cv',
    '',
    '',
    '',
    'https://casadocidadao.cv/index.php/empresa-no-dia',
    'https://casadocidadao.cv/index.php/empresa-no-dia/requisitos',
    'Numero de Matricula Comercial (NMC)',
  ),
  KH:   office(
    'Business Registration (Ministry of Commerce Cambodia)',
    '+855 23 866 050',
    'Lot 19-61, Russian Blvd, Phnom Penh, Cambodia',
    'https://www.businessregistration.moc.gov.kh',
    '',
    '',
    '',
    '',
    'https://www.businessregistration.moc.gov.kh',
    'https://www.moc.gov.kh/en-us/service/business-registration',
    'Enterprise Registration Number',
  ),
  CM:   office(
    'Centre de Formalites de Creation d\'Entreprise (CFCE Cameroun)',
    '+237 233 42 59 59',
    'Immeuble MAGZI, Yaounde, Cameroon',
    'https://www.apme.cm',
    'cfce@apme.cm',
    '',
    '',
    'https://www.linkedin.com/company/apme-cameroun/',
    'https://www.apme.cm/cfce',
    'https://www.apme.cm/cfce/check-list',
    'Numero RCCM',
  ),
  CF:   office(
    'Guichet Unique de Formalites des Entreprises (RCA)',
    '+236 75 05 05 05',
    'Avenue de l\'Independance, Bangui, Central African Republic',
    'https://www.apica.cf',
    'contact@apica.cf',
    '',
    '',
    '',
    'https://www.apica.cf/creation-entreprise',
    'https://www.apica.cf/check-list',
    'Numero RCCM',
  ),
  TD:   office(
    'Agence Nationale des Investissements et des Exportations (ANIE Chad) - Guichet Unique',
    '+235 22 52 42 42',
    'Quartier Sabangali, N\'Djamena, Chad',
    'https://www.anie.td',
    'contact@anie.td',
    '',
    '',
    '',
    'https://www.anie.td/guichet-unique',
    'https://www.anie.td/guide-createur',
    'Numero RCCM',
  ),
  CL:   office(
    'Registro de Empresas y Sociedades (Tu Empresa en un Dia)',
    '+56 2 2440 6000',
    'Santiago, Chile',
    'https://www.registrodeempresasysociedades.cl',
    '',
    '',
    '',
    '',
    'https://www.registrodeempresasysociedades.cl',
    'https://www.chileatiende.gob.cl/fichas/31239-constituir-una-sociedad-en-el-registro-de-empresas-y-sociedades-res',
    'Rol Unico Tributario (RUT)',
  ),
  CN:   office(
    'State Administration for Market Regulation (Enterprise Registration)',
    '+86 10 8865 0000',
    'No. 8 Sanlihe East Road, Xicheng District, Beijing, China',
    'https://www.samr.gov.cn',
    '',
    '',
    '',
    '',
    'https://zwfw.samr.gov.cn',
    'https://www.gov.cn/fuwu/2015-12/09/content_5022390.htm',
    'Unified Social Credit Code',
  ),
  CO:   office(
    'Chamber of Commerce / RUES Colombia',
    '+57 601 594 1000',
    'Calle 26 69-76, Bogota, Colombia',
    'https://www.ccb.org.co',
    'contactenos@ccb.org.co',
    '',
    '',
    '',
    'https://www.rues.org.co',
    'https://www.ccb.org.co/crear-empresa',
    'NIT (Numero de Identificacion Tributaria)',
  ),
  KM:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Comores)',
    '+269 773 08 08',
    'Avenue de l\'OUA, Moroni, Comoros',
    'https://www.anpi-comores.km',
    'contact@anpi-comores.km',
    '',
    '',
    '',
    'https://www.anpi-comores.km/guichet-unique',
    'https://www.anpi-comores.km/guide-createur',
    'Numero RCCM',
  ),
  CK:   office(
    'Ministry of Justice Cook Islands (Companies Registry)',
    '+682 29370',
    'Avarua, Rarotonga, Cook Islands',
    'https://www.mfem.gov.ck',
    'registry@mfem.gov.ck',
    '',
    '',
    '',
    'https://www.mfem.gov.ck',
    'https://www.business.gov.ck',
    'Company Registration Number',
  ),
  CR:   office(
    'National Registry Costa Rica (Personas Juridicas)',
    '+506 2202 0888',
    'Zapote, San Jose, Costa Rica',
    'https://www.rnpdigital.com',
    '',
    '',
    '',
    '',
    'https://www.rnpdigital.com',
    'https://www.hacienda.go.cr/ATV/frmAnexoyAsistente.aspx',
    'Cedula Juridica',
  ),
  CI:   office(
    'CEPICI - Guichet Unique de Creation d\'Entreprise',
    '+225 27 20 31 14 00',
    'Abidjan Plateau, Avenue Marchand, Cote d\'Ivoire',
    'https://www.cepici.ci',
    'infos@cepici.ci',
    'https://x.com/cepici',
    'https://www.instagram.com/cepici.ci/',
    'https://www.linkedin.com/company/cepici/',
    'https://www.225invest.ci/creation-entreprise',
    'https://www.cepici.ci/guide-du-createur',
    'Numero RCCM',
  ),
  HR:   office(
    'Court Register (Fina Croatia)',
    '+385 1 480 9000',
    'Ulica grada Vukovara 78, Zagreb, Croatia',
    'https://www.fina.hr',
    'info@fina.hr',
    '',
    '',
    '',
    'https://sudreg.pravosudje.hr',
    'https://www.hok.hr/poslovni-registar',
    'OIB (Personal Identification Number)',
  ),
  CU:   office(
    'National Office of Statistics and Information (ONBC Cuba)',
    '+53 7 862 8041',
    'Obispo 256, Havana, Cuba',
    'https://www.onbc.cu',
    'info@onbc.cu',
    '',
    '',
    '',
    'https://www.onbc.cu',
    'https://www.onbc.cu/servicios',
    'Codigo REEUP',
  ),
  CY:   office(
    'Department of Registrar of Companies and Intellectual Property Cyprus',
    '+357 22 403 150',
    'Makarios III Avenue, Nicosia, Cyprus',
    'https://www.companies.gov.cy',
    'companies@companies.gov.cy',
    '',
    '',
    '',
    'https://www.companies.gov.cy',
    'https://www.companies.gov.cy/en/company-registration',
    'Registration Number (HE)',
  ),
  CZ:   office(
    'Business Register (Ministry of Justice Czechia)',
    '+420 296 366 366',
    'Ovocny trh 8, Prague, Czechia',
    'https://www.justice.cz',
    '',
    '',
    '',
    '',
    'https://or.justice.cz',
    'https://www.businessinfo.cz/en/articles/how-to-start-a-business-in-the-czech-republic',
    'ICO (Identification Number of Organization)',
  ),
  CD:   office(
    'Guichet Unique de Creation d\'Entreprise (GUCE DRC)',
    '+243 81 555 7000',
    'Immeuble Fickin, Boulevard du 30 Juin, Gombe, Kinshasa, DR Congo',
    'https://guichetunique.cd',
    'contact@guichetunique.cd',
    '',
    '',
    '',
    'https://guichetunique.cd/creation-dentreprise',
    'https://guichetunique.cd/pieces-a-fournir',
    'Numero RCCM',
  ),
  DJ:   office(
    'Agence Nationale pour la Promotion des Investissements (ANPI Djibouti)',
    '+253 21 35 20 00',
    'Plateau du Serpent, BP 2194, Djibouti City, Djibouti',
    'https://www.investindjibouti.dj',
    'contact@investindjibouti.dj',
    '',
    '',
    '',
    'https://www.investindjibouti.dj/creation-dentreprise',
    'https://www.investindjibouti.dj/guide-creation',
    'Numero RCCM',
  ),
  DM:   office(
    'Companies and Intellectual Property Office Dominica',
    '+1 767 266 3201',
    'Kennedy Avenue, Roseau, Dominica',
    'https://www.dominica.gov.dm',
    'cipo@gov.dm',
    '',
    '',
    '',
    'https://www.dominica.gov.dm',
    'https://investdominica.dm/starting-a-business',
    'Company Registration Number',
  ),
  DO:   office(
    'ONAPI Dominican Republic (National Office of Industrial Property)',
    '+1 809 567 4771',
    'Av. Lope de Vega 29, Santo Domingo, Dominican Republic',
    'https://www.onapi.gov.do',
    'info@onapi.gov.do',
    '',
    '',
    '',
    'https://www.onapi.gov.do',
    'https://www.cei-rd.gov.do/crear-empresa',
    'RNC (Registro Nacional de Contribuyentes)',
  ),
  EC:   office(
    'Superintendencia de Companias Ecuador',
    '+593 2 393 0600',
    'Av. Amazonas N37-29, Quito, Ecuador',
    'https://www.supercias.gob.ec',
    'info@supercias.gob.ec',
    '',
    '',
    '',
    'https://iib.supercias.gob.ec',
    'https://www.supercias.gob.ec/portal/constitucion-de-companias',
    'RUC (Registro Unico de Contribuyentes)',
  ),
  EG:   office(
    'General Authority for Investment and Free Zones (GAFI) - One Stop Shop',
    '+20 2 3537 3333',
    'Salah Salem Road, Nasr City, Cairo, Egypt',
    'https://www.gafi.gov.eg',
    'info@gafi.gov.eg',
    'https://x.com/gafieg',
    '',
    'https://www.linkedin.com/company/gafi-egypt/',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/default.aspx',
    'https://www.gafi.gov.eg/English/StartBusiness/Pages/Procedures.aspx',
    'Commercial Register Number (CR Number)',
  ),
  SV:   office(
    'CNRC El Salvador (National Registry Center)',
    '+503 2247 5000',
    'San Salvador, El Salvador',
    'https://www.cnr.gob.sv',
    'info@cnr.gob.sv',
    '',
    '',
    '',
    'https://www.cnr.gob.sv',
    'https://www.cnr.gob.sv/registro-mercantil',
    'NIT (Numero de Identificacion Tributaria)',
  ),
  GQ:   office(
    'Ventanilla Unica Empresarial - Ministerio de Comercio (Equatorial Guinea)',
    '+240 333 09 50 00',
    'Avenida de la Independencia, Malabo, Equatorial Guinea',
    'https://www.guineaecuatorialpress.com',
    'comercio@guineaecuatorial-gob.com',
    '',
    '',
    '',
    'https://www.guineaecuatorialpress.com/noticias/ventanilla_unica_empresarial',
    '',
    'Numero de Registro Mercantil',
  ),
  ER:   office(
    'Ministry of Trade and Industry Eritrea - Business Licensing Office',
    '+291 1 120 055',
    'Harnet Avenue, Asmara, Eritrea',
    'https://www.shabait.com/ministry-of-trade-and-industry',
    'moti@e.gov.er',
    '',
    '',
    '',
    'https://www.shabait.com/ministry-of-trade-and-industry',
    '',
    'Business Registration Number',
  ),
  EE:   office(
    'Centre of Registers and Information Systems (RIK Estonia)',
    '+372 680 3160',
    'Lai 28, Tallinn, Estonia',
    'https://www.rik.ee',
    'info@rik.ee',
    '',
    '',
    '',
    'https://ariregister.rik.ee',
    'https://www.e-resident.gov.ee/start-a-company',
    'Registry Code',
  ),
  ET:   office(
    'Ministry of Trade and Regional Integration Ethiopia - Business Registration Directorate',
    '+251 11 551 8020',
    'Kirkos Sub City, Addis Ababa, Ethiopia',
    'https://trade.gov.et',
    'info@trade.gov.et',
    '',
    '',
    '',
    'https://etrade.gov.et',
    'https://trade.gov.et/services/business-registration',
    'Trade Registration Number (TRN)',
  ),
  FJ:   office(
    'Registrar of Companies Fiji',
    '+679 330 6166',
    'Level 5, FNPF Place, Suva, Fiji',
    'https://www.companies.gov.fj',
    'companies@companies.gov.fj',
    '',
    '',
    '',
    'https://www.companies.gov.fj',
    'https://www.investmentfiji.org.fj/starting-a-business',
    'Company Registration Number',
  ),
  GA:   office(
    'Agence Nationale de Promotion des Investissements du Gabon (ANPI-Gabon)',
    '+241 01 79 20 00',
    'Immeuble Arambo, Libreville, Gabon',
    'https://www.investingabon.ga',
    'contact@investingabon.ga',
    '',
    '',
    'https://www.linkedin.com/company/anpi-gabon/',
    'https://www.investingabon.ga/creer-mon-entreprise',
    'https://www.investingabon.ga/guide-createur',
    'Numero RCCM',
  ),
  GM:   office(
    'Ministry of Justice The Gambia - Registrar of Companies',
    '+220 422 5308',
    'Marina Parade, Banjul, The Gambia',
    'https://www.moj.gov.gm',
    'info@moj.gov.gm',
    '',
    '',
    '',
    'https://www.moj.gov.gm/registrar-general',
    '',
    'Company Registration Number',
  ),
  GE:   office(
    'National Agency of Public Registry Georgia',
    '+995 32 405 050',
    '2 Vazha-Pshavela Ave, Tbilisi, Georgia',
    'https://www.napr.gov.ge',
    'info@napr.gov.ge',
    '',
    '',
    '',
    'https://enreg.reestri.gov.ge',
    'https://www.enterprisegeorgia.gov.ge/en/Start-a-Business',
    'Identification Code',
  ),
  GH:   office(
    'Registrar-General\'s Department (RGD Ghana)',
    '+233 30 266 1081',
    'Ministries, Accra, Ghana',
    'https://rgd.gov.gh',
    'info@rgd.gov.gh',
    'https://x.com/ORC_ghana',
    '',
    'https://www.linkedin.com/company/office-of-the-registrar-of-companies-ghana/',
    'https://egovonline.gegov.gov.gh/RGDPortalWeb/portal/RGDHome',
    'https://rgd.gov.gh/services/business-registration/',
    'Company Registration Number',
  ),
  GR:   office(
    'General Commercial Registry (GEMI Greece)',
    '+30 210 328 6000',
    'Karaoli & Dimitriou 7, Athens, Greece',
    'https://www.businessportal.gr',
    'info@businessportal.gr',
    '',
    '',
    '',
    'https://www.businessportal.gr',
    'https://www.businessportal.gr/en/starting-a-business',
    'GEMI Number',
  ),
  GD:   office(
    'Corporate Affairs and Intellectual Property Office Grenada',
    '+1 473 440 2939',
    'Frederick Street, St George\'s, Grenada',
    'https://www.gov.gd',
    'caipo@gov.gd',
    '',
    '',
    '',
    'https://www.gov.gd',
    'https://grenadagrenadines.com/invest/starting-a-business',
    'Company Registration Number',
  ),
  GN:   office(
    'Agence de Promotion des Investissements Prives (APIP Guinea) - Guichet Unique',
    '+224 622 98 25 00',
    'Coleah, Commune de Matam, Conakry, Guinea',
    'https://apip.gov.gn',
    'contact@apip.gov.gn',
    '',
    '',
    'https://www.linkedin.com/company/apip-guinee/',
    'https://apip.gov.gn/creation-dentreprise',
    'https://apip.gov.gn/guide-du-createur',
    'Numero RCCM',
  ),
  GW:   office(
    'Centro de Formalizacao de Empresas (CFE Guinea-Bissau)',
    '+245 955 800 800',
    'Avenida Amilcar Cabral, Bissau, Guinea-Bissau',
    'https://www.cfe.gw',
    'info@cfe.gw',
    '',
    '',
    '',
    'https://www.cfe.gw/empresa-no-dia',
    'https://www.cfe.gw/requisitos',
    'Numero de Matricula Comercial',
  ),
  GY:   office(
    'Deeds and Commercial Registry Guyana',
    '+592 225 0555',
    'Avenue of the Republic, Georgetown, Guyana',
    'https://www.deeds.gov.gy',
    'deedsregistry@gov.gy',
    '',
    '',
    '',
    'https://www.deeds.gov.gy',
    'https://goinvest.gov.gy/starting-a-business',
    'Company Registration Number',
  ),
  HN:   office(
    'Property Institute Honduras (Registro Mercantil)',
    '+504 2239 3000',
    'Tegucigalpa, Honduras',
    'https://www.ip.gob.hn',
    'info@ip.gob.hn',
    '',
    '',
    '',
    'https://www.ip.gob.hn',
    'https://www.cni.hn/crear-empresa',
    'RTN (Registro Tributario Nacional)',
  ),
  HU:   office(
    'Court of Registration Hungary',
    '+36 1 488 2100',
    'Szalay u. 4, Budapest, Hungary',
    'https://www.e-cegjegyzek.hu',
    '',
    '',
    '',
    '',
    'https://www.e-cegjegyzek.hu',
    'https://www.magyarorszag.hu/en/business',
    'Company Registration Number',
  ),
  ID:   office(
    'OSS Indonesia (Ministry of Investment/BKPM)',
    '+62 21 1500 123',
    'Jl. Jenderal Gatot Subroto No. 44, Jakarta, Indonesia',
    'https://oss.go.id',
    '',
    '',
    '',
    '',
    'https://oss.go.id',
    'https://www.bkpm.go.id/en/public-service',
    'Nomor Induk Berusaha (NIB)',
  ),
  IR:   office(
    'Companies Registration Office Iran',
    '+98 21 8888 0000',
    'Tehran, Iran',
    'https://www.irimc.org',
    '',
    '',
    '',
    '',
    'https://www.irimc.org',
    'https://www.irimc.org/en/company-registration',
    'National ID (Shenase Melli)',
  ),
  IQ:   office(
    'Companies Registration Directorate (Ministry of Trade)',
    '+964 790 019 0274',
    'Bab Al-Muadham, Baghdad, Iraq',
    'https://mot.gov.iq',
    '',
    '',
    '',
    '',
    'https://mot.gov.iq',
    'https://mot.gov.iq/ar/services',
    'Company Registration Number',
  ),
  IT:   office(
    'Registro Imprese (Chamber of Commerce Italy)',
    '+39 06 47041',
    'Via Carlo Alberto 16, Rome, Italy',
    'https://www.registroimprese.it',
    'info@registroimprese.it',
    '',
    '',
    '',
    'https://www.registroimprese.it',
    'https://www.infocamere.it/starting-a-business',
    'Codice Fiscale / REA Number',
  ),
  JM:   office(
    'Companies Office of Jamaica',
    '+1 876 908 4419',
    '1 Grenada Way, Kingston, Jamaica',
    'https://www.orcjamaica.gov.jm',
    'info@orcjamaica.gov.jm',
    '',
    '',
    '',
    'https://www.orcjamaica.gov.jm',
    'https://www.jamaicatradeandinvest.org/starting-a-business',
    'Company Registration Number',
  ),
  JO:   office(
    'Companies Control Department (Ministry of Industry, Trade and Supply)',
    '+962 6 5629030',
    'Amman, Jordan',
    'https://www.ccd.gov.jo',
    '',
    '',
    '',
    '',
    'https://www.ccd.gov.jo',
    'https://www.mit.gov.jo/EN/List/Services',
    'Registration Number',
  ),
  KZ:   office(
    'Ministry of Justice Kazakhstan (eGov Business Registration)',
    '+7 7172 74 90 00',
    'Astana, Kazakhstan',
    'https://www.gov.kz',
    'info@adilet.gov.kz',
    '',
    '',
    '',
    'https://egov.kz',
    'https://www.invest.gov.kz/doing-business',
    'BIN (Business Identification Number)',
  ),
  KE:   office(
    'Business Registration Service (BRS Kenya)',
    '+254 20 222 7461',
    'Sheria House, Harambee Avenue, Nairobi, Kenya',
    'https://brs.go.ke',
    'info@brs.go.ke',
    'https://x.com/BRS_Kenya',
    '',
    'https://www.linkedin.com/company/business-registration-service-kenya/',
    'https://brs.go.ke/service/company-registration',
    'https://www.ecitizen.go.ke',
    'Certificate of Incorporation Number',
  ),
  KI:   office(
    'Ministry of Commerce, Industry and Cooperatives Kiribati',
    '+686 750 26000',
    'Betio, Tarawa, Kiribati',
    'https://www.mfep.gov.ki',
    'commerce@mfep.gov.ki',
    '',
    '',
    '',
    'https://www.mfep.gov.ki',
    'https://www.mfep.gov.ki/commerce',
    'Business License Number',
  ),
  KW:   office(
    'Kuwait Business Center (Ministry of Commerce and Industry)',
    '+965 2248 0000',
    'Kuwait City, Kuwait',
    'https://www.moci.gov.kw',
    '',
    '',
    '',
    '',
    'https://e.gov.kw/sites/kgoenglish/Pages/eServices/MOCI/CommercialLicensing.aspx',
    'https://e.gov.kw/sites/kgoenglish/Pages/Services/MOCI/CommercialLicense.aspx',
    'Commercial License Number',
  ),
  KG:   office(
    'Ministry of Justice Kyrgyzstan (Business Registration)',
    '+996 312 620 000',
    'Bishkek, Kyrgyzstan',
    'https://www.minjust.gov.kg',
    'info@minjust.gov.kg',
    '',
    '',
    '',
    'https://www.minjust.gov.kg',
    'https://www.invest.gov.kg/en/starting-business',
    'INN (Taxpayer Identification Number)',
  ),
  LA:   office(
    'Enterprise Registration Office (Ministry of Industry and Commerce)',
    '+856 21 412 011',
    'Vientiane, Lao PDR',
    'https://erm.gov.la',
    '',
    '',
    '',
    '',
    'https://erm.gov.la',
    'https://www.laotradeportal.gov.la/kcfinder/upload/files/Forms%20for%20business%20registration.pdf',
    'Enterprise Registration Certificate Number',
  ),
  LV:   office(
    'Enterprise Register Latvia',
    '+371 670 31600',
    'Pils laukums 1, Riga, Latvia',
    'https://www.ur.gov.lv',
    'info@ur.gov.lv',
    '',
    '',
    '',
    'https://www.ur.gov.lv',
    'https://www.ur.gov.lv/en/registration-of-undertakings',
    'Registration Number',
  ),
  LB:   office(
    'Lebanese Commercial Register (Ministry of Justice)',
    '+961 1 425000',
    'Palace of Justice, Beirut, Lebanon',
    'https://www.justice.gov.lb',
    '',
    '',
    '',
    '',
    'https://cr.justice.gov.lb',
    'https://investinlebanon.gov.lb/en/doing_business/starting_a_business',
    'Commercial Register Number',
  ),
  LS:   office(
    'One Stop Business Facilitation Centre (OBFC Lesotho)',
    '+266 22 312 100',
    'Bedco House, Kingsway Road, Maseru, Lesotho',
    'https://www.obfc.org.ls',
    'info@obfc.org.ls',
    '',
    '',
    '',
    'https://www.obfc.org.ls/company-registration',
    'https://www.obfc.org.ls/checklists',
    'Company Registration Number',
  ),
  LR:   office(
    'Liberia Business Registry (LBR)',
    '+231 77 700 2000',
    'One Stop Shop, 12th Street Sinkor, Monrovia, Liberia',
    'https://lbr.gov.lr',
    'info@lbr.gov.lr',
    'https://x.com/LBRLiberia',
    '',
    'https://www.linkedin.com/company/liberia-business-registry/',
    'https://lbr.gov.lr/register-business',
    'https://lbr.gov.lr/requirements',
    'Business Registration Number (BRN)',
  ),
  LY:   office(
    'Ministry of Economy and Trade Libya - Commercial Registry Department',
    '+218 21 335 0380',
    'Al-Sikka Road, Tripoli, Libya',
    'https://www.economy.gov.ly',
    'info@economy.gov.ly',
    '',
    '',
    '',
    'https://www.economy.gov.ly/services/commercial-register',
    '',
    'Commercial Registration Number',
  ),
  LT:   office(
    'Centre of Registers Lithuania',
    '+370 5 268 8262',
    'Zygimantu 3, Vilnius, Lithuania',
    'https://www.registrucentras.lt',
    'info@registrucentras.lt',
    '',
    '',
    '',
    'https://www.registrucentras.lt',
    'https://www.registrucentras.lt/en/registration-of-legal-entities',
    'Company Code',
  ),
  LU:   office(
    'Registre de Commerce et des Societes Luxembourg',
    '+352 2478 2478',
    '14 rue Erasme, Luxembourg',
    'https://www.lbr.lu',
    'info@lbr.lu',
    '',
    '',
    '',
    'https://www.lbr.lu',
    'https://guichet.public.lu/en/entreprises/creation-developpement',
    'RCS Number',
  ),
  MG:   office(
    'Economic Development Board of Madagascar (EDBM) - One Stop Shop',
    '+261 20 22 670 40',
    'Immeuble EDBM, Antaninarenina, Antananarivo, Madagascar',
    'https://edbm.mg',
    'contact@edbm.mg',
    '',
    '',
    'https://www.linkedin.com/company/edbm/',
    'https://edbm.mg/creation-dentreprise',
    'https://edbm.mg/guide-pratique',
    'Numero RCCM',
  ),
  MW:   office(
    'Registrar General Department Malawi',
    '+265 1 770 155',
    'Glyn Jones Road, Ginnery Corner, Blantyre, Malawi',
    'https://www.registrargeneral.gov.mw',
    'registrargeneral@justice.gov.mw',
    '',
    '',
    '',
    'https://www.registrargeneral.gov.mw/company-registration',
    'https://www.registrargeneral.gov.mw/forms-and-fees',
    'Certificate of Incorporation Number',
  ),
  MY:   office(
    'Companies Commission of Malaysia (SSM)',
    '+60 3 7721 4000',
    'Menara SSM@Sentral, No. 7 Jalan Stesen Sentral 5, Kuala Lumpur, Malaysia',
    'https://www.ssm.com.my',
    'enquiry@ssm.com.my',
    '',
    '',
    '',
    'https://ezbiz.ssm.com.my',
    'https://www.ssm.com.my/Pages/Legal_Framework/Company/Guidelines.aspx',
    'Company Number',
  ),
  MV:   office(
    'Ministry of Economic Development and Trade Maldives (Business Center)',
    '+960 334 3101',
    'Male, Maldives',
    'https://www.trade.gov.mv',
    'info@trade.gov.mv',
    '',
    '',
    '',
    'https://www.trade.gov.mv',
    'https://www.investmaldives.org/starting-a-business',
    'Business Registration Number',
  ),
  ML:   office(
    'API Mali - Guichet Unique de Creation d\'Entreprise',
    '+223 20 22 18 12',
    'Avenue du Mali, Hamdallaye ACI 2000, Bamako, Mali',
    'https://www.apimali.gov.ml',
    'contact@apimali.gov.ml',
    '',
    '',
    '',
    'https://www.apimali.gov.ml/guichet-unique',
    'https://www.apimali.gov.ml/repertoire-des-formalites',
    'Numero RCCM',
  ),
  MT:   office(
    'Malta Business Registry',
    '+356 2342 0000',
    'Notabile Road, Attard, Malta',
    'https://mbr.mt',
    'mbr@mbr.mt',
    '',
    '',
    '',
    'https://mbr.mt',
    'https://mbr.mt/registration-of-companies',
    'Company Registration Number',
  ),
  MR:   office(
    'Agence de Promotion des Investissements en Mauritanie (APIM) - Guichet Unique',
    '+222 45 25 33 77',
    'Ilot C, Tevragh Zeina, Nouakchott, Mauritania',
    'https://apim.gov.mr',
    'contact@apim.gov.mr',
    '',
    '',
    '',
    'https://apim.gov.mr/creation-dentreprise',
    'https://apim.gov.mr/guide-createur',
    'Numero RCCM',
  ),
  FM:   office(
    'Division of Statistics and Economic Support (FSM)',
    '+691 320 2825',
    'Palikir, Pohnpei, Federated States of Micronesia',
    'https://www.fsmgov.org',
    'info@fsmgov.org',
    '',
    '',
    '',
    'https://www.fsmgov.org',
    'https://www.fsmgov.org/fsm/departments/commerce',
    'Business License Number',
  ),
  MD:   office(
    'Public Services Agency Moldova',
    '+373 22 257 070',
    'Chisinau, Moldova',
    'https://www.asp.gov.md',
    'info@asp.gov.md',
    '',
    '',
    '',
    'https://www.asp.gov.md',
    'https://www.invest.gov.md/en/starting-business',
    'IDNO (Identification Number)',
  ),
  MN:   office(
    'General Authority for State Registration Mongolia',
    '+976 51 262 683',
    'Ulaanbaatar, Mongolia',
    'https://www.burtgel.mn',
    'info@burtgel.mn',
    '',
    '',
    '',
    'https://www.burtgel.mn',
    'https://www.investmongolia.gov.mn/starting-business',
    'State Registration Number',
  ),
  ME:   office(
    'Central Registry of Business Entities Montenegro',
    '+382 20 230 468',
    'Podgorica, Montenegro',
    'https://www.crps.me',
    'info@crps.me',
    '',
    '',
    '',
    'https://www.crps.me',
    'https://www.investmontenegro.me/starting-a-business',
    'PIB (Tax Identification Number)',
  ),
  MA:   office(
    'OMPIC Morocco - DirectEntreprise',
    '+212 5 22 58 64 00',
    'Route de Nouasseur, Km 9.5, Casablanca, Morocco',
    'https://www.directentreprise.ma',
    'contact@ompic.ma',
    'https://x.com/OMPICMaroc',
    '',
    'https://www.linkedin.com/company/ompic-maroc/',
    'https://www.directentreprise.ma',
    'https://www.ompic.ma/fr/content/guide-de-creation',
    'Numero du Registre de Commerce (RC)',
  ),
  MZ:   office(
    'Conservatoria do Registo das Entidades Legais (CREL Mozambique)',
    '+258 21 327 800',
    'Av. Vladimir Lenine 265, Maputo, Mozambique',
    'https://www.mjcr.gov.mz',
    'atendimento@mjcr.gov.mz',
    '',
    '',
    '',
    'https://www.mjcr.gov.mz/servicos/registo-comercial',
    'https://www.mjcr.gov.mz/servicos/requisitos',
    'Numero de Registo Comercial (NUEL)',
  ),
  MM:   office(
    'Directorate of Investment and Company Administration (DICA)',
    '+95 1 658118',
    'Building 1, Nay Pyi Taw, Myanmar',
    'https://www.dica.gov.mm',
    '',
    '',
    '',
    '',
    'https://www.myco.dica.gov.mm',
    'https://www.dica.gov.mm/en/service',
    'Company Registration Number',
  ),
  NA:   office(
    'Business and Intellectual Property Authority (BIPA Namibia)',
    '+264 61 299 4400',
    '55 Robert Mugabe Avenue, Windhoek, Namibia',
    'https://www.bipa.na',
    'info@bipa.na',
    'https://x.com/BIPA_NA',
    '',
    'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
    'https://www.bipa.na/company-registration',
    'https://www.bipa.na/checklists-and-forms',
    'Company Registration Number',
  ),
  NP:   office(
    'Office of Company Registrar Nepal',
    '+977 1 422 0255',
    'Tripureshwor, Kathmandu, Nepal',
    'https://www.ocr.gov.np',
    'info@ocr.gov.np',
    '',
    '',
    '',
    'https://www.ocr.gov.np',
    'https://www.ocr.gov.np/company-registration',
    'Company Registration Number',
  ),
  NZ:   office(
    'New Zealand Companies Office',
    '+64 50 872 2669',
    'Wellington, New Zealand',
    'https://companies-register.companiesoffice.govt.nz',
    '',
    '',
    '',
    '',
    'https://companies-register.companiesoffice.govt.nz/help-centre/starting-a-company',
    'https://www.business.govt.nz/getting-started/advice-for-start-ups/10-step-guide-to-starting-a-business/',
    'New Zealand Business Number (NZBN)',
  ),
  NI:   office(
    'Ministry of Development, Industry and Trade Nicaragua (MIFIC)',
    '+505 2248 9000',
    'Managua, Nicaragua',
    'https://www.mific.gob.ni',
    'info@mific.gob.ni',
    '',
    '',
    '',
    'https://www.mific.gob.ni',
    'https://www.mific.gob.ni/registro-mercantil',
    'RUC (Registro Unico de Contribuyentes)',
  ),
  NE:   office(
    'Maison de l\'Entreprise du Niger - CFE',
    '+227 20 75 23 47',
    'Boulevard Mali Bero, Niamey, Niger',
    'https://www.me.ne',
    'infos@me.ne',
    '',
    '',
    '',
    'https://www.me.ne/creation-dentreprise',
    'https://www.me.ne/guide-des-formalites',
    'Numero RCCM',
  ),
  NG:   office(
    'Corporate Affairs Commission (CAC Nigeria)',
    '+234 700 022 2255',
    'Plot 420, Tigris Crescent, Maitama, Abuja, Nigeria',
    'https://www.cac.gov.ng',
    'enquiries@cac.gov.ng',
    'https://x.com/cacnigeria1',
    'https://www.instagram.com/cacnigeria/',
    'https://www.linkedin.com/company/corporate-affairs-commission-nigeria/',
    'https://pre.cac.gov.ng/register',
    'https://www.cac.gov.ng/resources',
    'Registration Number (RC Number)',
  ),
  NU:   office(
    'Niue Companies Registry',
    '+683 4024',
    'Alofi, Niue',
    'https://www.gov.nu',
    'registry@gov.nu',
    '',
    '',
    '',
    'https://www.gov.nu',
    'https://www.gov.nu/nbi',
    'Company Registration Number',
  ),
  MK:   office(
    'Central Registry North Macedonia',
    '+389 2 3117 171',
    'Skopje, North Macedonia',
    'https://www.crm.com.mk',
    'info@crm.com.mk',
    '',
    '',
    '',
    'https://www.crm.com.mk',
    'https://www.investinmacedonia.gov.mk/starting-a-business',
    'EMBS (Central Registry Number)',
  ),
  OM:   office(
    'Invest Easy (Ministry of Commerce, Industry and Investment Promotion)',
    '+968 800 77770',
    'Muscat, Oman',
    'https://www.business.gov.om',
    '',
    '',
    '',
    '',
    'https://www.business.gov.om',
    'https://www.business.gov.om/portal/en/home',
    'Commercial Registration Number',
  ),
  PK:   office(
    'Securities and Exchange Commission of Pakistan (SECP)',
    '+92 51 920 7091',
    'NIC Building, 63 Jinnah Avenue, Islamabad, Pakistan',
    'https://www.secp.gov.pk',
    'helpdesk@secp.gov.pk',
    '',
    '',
    '',
    'https://eservices.secp.gov.pk',
    'https://www.secp.gov.pk/company-formation',
    'National Tax Number (NTN)',
  ),
  PA:   office(
    'Public Registry of Panama (Registro Publico)',
    '+507 507 5000',
    'Avenida Cuba y Calle D, Panama City, Panama',
    'https://www.registro-publico.gob.pa',
    'info@registro-publico.gob.pa',
    '',
    '',
    '',
    'https://www.registro-publico.gob.pa',
    'https://www.investpanama.gob.pa/starting-a-business',
    'RUC (Registro Unico de Contribuyentes)',
  ),
  PG:   office(
    'Investment Promotion Authority (IPA) Papua New Guinea',
    '+675 321 7311',
    'Malaoro Street, Port Moresby, Papua New Guinea',
    'https://www.ipa.gov.pg',
    '',
    '',
    '',
    '',
    'https://www.ipa.gov.pg/online-services',
    'https://www.ipa.gov.pg/business-registration',
    'Company Number',
  ),
  PE:   office(
    'SUNARP - SID Sunarp',
    '+51 1 208 3100',
    'Av. Primavera 1878, Santiago de Surco, Lima, Peru',
    'https://www.sunarp.gob.pe',
    '',
    '',
    '',
    '',
    'https://sid.sunarp.gob.pe',
    'https://www.gob.pe/709-inscribir-una-empresa-en-el-registro-de-personas-juridicas',
    'Registro Unico de Contribuyentes (RUC)',
  ),
  PH:   office(
    'Securities and Exchange Commission Philippines (eSPARC)',
    '+63 2 8818 0921',
    '7907 Makati Avenue, Salcedo Village, Makati, Philippines',
    'https://www.sec.gov.ph',
    'imessagemo@sec.gov.ph',
    '',
    '',
    '',
    'https://esparc.sec.gov.ph',
    'https://www.sec.gov.ph/wp-content/uploads/2022/02/2022MC_no3.pdf',
    'SEC Registration Number',
  ),
  PL:   office(
    'National Court Register (KRS Poland)',
    '+48 22 530 00 00',
    'ul. Czerniakowska 100, Warsaw, Poland',
    'https://www.gov.pl/web/krs',
    '',
    '',
    '',
    '',
    'https://ekrs.ms.gov.pl',
    'https://www.biznes.gov.pl/pl/portal',
    'KRS Number',
  ),
  PT:   office(
    'Instituto dos Registos e Notariado Portugal',
    '+351 217 988 000',
    'Av. D. Joao II, Lisbon, Portugal',
    'https://www.irn.mj.pt',
    'geral@irn.mj.pt',
    '',
    '',
    '',
    'https://eportugal.gov.pt',
    'https://www.portaldaempresa.pt',
    'NIPC (Numero de Identificacao de Pessoa Coletiva)',
  ),
  QA:   office(
    'Single Window (Ministry of Commerce and Industry Qatar)',
    '+974 16001',
    'Doha, Qatar',
    'https://www.moci.gov.qa',
    '',
    '',
    '',
    '',
    'https://www.sw.gov.qa',
    'https://www.moci.gov.qa/en/our-services/business-services/',
    'Commercial Registration (CR) Number',
  ),
  CG:   office(
    'Centre de Formalites Administratives des Entreprises (CFE Congo)',
    '+242 06 665 77 77',
    'Avenue Amilcar Cabral, Brazzaville, Republic of the Congo',
    'https://cfe.cg',
    'contact@cfe.cg',
    '',
    '',
    '',
    'https://cfe.cg/creer-entreprise',
    'https://cfe.cg/guide-des-formalites',
    'Numero RCCM',
  ),
  RO:   office(
    'National Trade Register Office Romania (ONRC)',
    '+40 21 310 2111',
    'B-dul Unirii 78, Bucharest, Romania',
    'https://www.onrc.ro',
    'info@onrc.ro',
    '',
    '',
    '',
    'https://portal.onrc.ro',
    'https://www.onrc.ro/index.php/en/registration-procedures',
    'CUI (Cod Unic de Inregistrare)',
  ),
  RU:   office(
    'Federal Tax Service of Russia (State Registration)',
    '+7 495 913 0009',
    'Neglinnaya St., 23, Moscow, Russia',
    'https://www.nalog.gov.ru',
    '',
    '',
    '',
    '',
    'https://service.nalog.ru/gosreg',
    'https://www.nalog.gov.ru/rn77/yul/interest/reg_ur/',
    'OGRN',
  ),
  RW:   office(
    'Rwanda Development Board (RDB) - Business Registration',
    '+250 252 587 441',
    'KG 9 Avenue, Nyarutarama, Kigali, Rwanda',
    'https://rdb.rw',
    'info@rdb.rw',
    'https://x.com/RDBrwanda',
    'https://www.instagram.com/visitrwanda_now/',
    'https://www.linkedin.com/company/rwanda-development-board/',
    'https://org.rdb.rw',
    'https://rdb.rw/business/business-registration/',
    'Company Registration Number',
  ),
  WS:   office(
    'Ministry of Commerce, Industry and Labour Samoa',
    '+685 20471',
    'Apia, Samoa',
    'https://www.mcil.gov.ws',
    'registry@mcil.gov.ws',
    '',
    '',
    '',
    'https://www.mcil.gov.ws',
    'https://www.mcil.gov.ws/business-registration',
    'Company Registration Number',
  ),
  SA:   office(
    'Ministry of Commerce Saudi Arabia (Business Platform)',
    '+966 1900',
    'Riyadh, Saudi Arabia',
    'https://mc.gov.sa',
    '',
    '',
    '',
    '',
    'https://business.sa',
    'https://mc.gov.sa/ar/eservices/Pages/default.aspx',
    'Commercial Registration (CR) Number',
  ),
  SN:   office(
    'Bureau d\'Appui a la Creation d\'Entreprise (BCE SENEGAL)',
    '+221 33 839 88 76',
    'Rue Vincens x Rue Saint-Michel, Dakar, Senegal',
    'https://creationdentreprise.sn',
    'contact@creationdentreprise.sn',
    '',
    '',
    '',
    'https://creationdentreprise.sn/formalites',
    'https://creationdentreprise.sn/guide',
    'Numero NINEA / RCCM',
  ),
  RS:   office(
    'Business Registers Agency Serbia (APR)',
    '+381 11 333 0000',
    'Bulevar Mihajla Pupina 6, Belgrade, Serbia',
    'https://www.apr.gov.rs',
    'info@apr.gov.rs',
    '',
    '',
    '',
    'https://www.apr.gov.rs',
    'https://www.apr.gov.rs/en/registration',
    'PIB (Tax Identification Number)',
  ),
  SC:   office(
    'Seychelles Revenue Commission - Registrar General Division',
    '+248 4 282 800',
    'Maison Collet, Francis Rachel Street, Victoria, Seychelles',
    'https://www.src.gov.sc',
    'registrargeneral@src.gov.sc',
    '',
    '',
    '',
    'https://www.src.gov.sc/services/business-registration',
    'https://www.src.gov.sc/checklists-and-forms',
    'Company Registration Number',
  ),
  SL:   office(
    'Office of the Administrator and Registrar General (OARG Sierra Leone)',
    '+232 79 990 739',
    'Roxy Building, Walpole Street, Freetown, Sierra Leone',
    'https://oarg.gov.sl',
    'info@oarg.gov.sl',
    'https://x.com/OargSierraLeone',
    '',
    'https://www.linkedin.com/company/oarg-sl/',
    'https://oarg.gov.sl/business-registration',
    'https://oarg.gov.sl/requirements',
    'Company Registration Number',
  ),
  SG:   office(
    'Accounting and Corporate Regulatory Authority (ACRA)',
    '+65 6248 6028',
    '10 Anson Road, International Plaza, Singapore',
    'https://www.acra.gov.sg',
    '',
    '',
    '',
    'https://www.linkedin.com/company/accounting-and-corporate-regulatory-authority-acra-/',
    'https://www.bizfile.gov.sg',
    'https://www.acra.gov.sg/how-to-guides/before-you-start/incorporation',
    'Unique Entity Number (UEN)',
  ),
  SK:   office(
    'ORSR (Register of Legal Entities Slovakia)',
    '+421 2 5971 1111',
    'Bratislava, Slovakia',
    'https://www.orsr.sk',
    '',
    '',
    '',
    '',
    'https://www.orsr.sk',
    'https://www.slovensko.sk/en/life-situation/life-situation/_zivnost',
    'ICO (Identification Number)',
  ),
  SI:   office(
    'AJPES Business Register Slovenia',
    '+386 1 588 16 00',
    'Trzaska 16, Ljubljana, Slovenia',
    'https://www.ajpes.si',
    'info@ajpes.si',
    '',
    '',
    '',
    'https://www.ajpes.si',
    'https://www.ajpes.si/eng/company_registration',
    'Registration Number',
  ),
  SB:   office(
    'Business Registry Unit Solomon Islands',
    '+677 22556',
    'Honiara, Solomon Islands',
    'https://www.commerce.gov.sb',
    'registry@commerce.gov.sb',
    '',
    '',
    '',
    'https://www.commerce.gov.sb',
    'https://www.commerce.gov.sb/business-registration',
    'Company Registration Number',
  ),
  SO:   office(
    'Ministry of Commerce and Industry Somalia - Company Registrar',
    '+252 61 553 3333',
    'Maka Al-Mukarama Road, Mogadishu, Somalia',
    'https://moci.gov.so',
    'info@moci.gov.so',
    '',
    '',
    '',
    'https://moci.gov.so/services/business-registration',
    '',
    'Business Registration Number',
  ),
  ZA:   office(
    'Companies and Intellectual Property Commission (CIPC South Africa)',
    '+27 86 100 2472',
    'the dti Campus, 77 Meintjies Street, Sunnyside, Pretoria, South Africa',
    'https://www.cipc.co.za',
    'info@cipc.co.za',
    'https://x.com/theCIPC',
    '',
    'https://www.linkedin.com/company/cipc/',
    'https://www.cipc.co.za/?page_id=3781',
    'https://www.cipc.co.za/?page_id=3791',
    'Enterprise Number',
  ),
  SS:   office(
    'Ministry of Justice and Constitutional Affairs South Sudan - Business Registry',
    '+211 92 348 8800',
    'Ministries Road, Juba, South Sudan',
    'https://www.mojca.gov.ss',
    'info@mojca.gov.ss',
    '',
    '',
    '',
    'https://www.mojca.gov.ss/services/business-registration',
    '',
    'Certificate of Incorporation Number',
  ),
  LK:   office(
    'Registrar of Companies Sri Lanka',
    '+94 11 268 9210',
    'Level 12, West Tower, World Trade Center, Colombo, Sri Lanka',
    'https://www.drc.gov.lk',
    'info@drc.gov.lk',
    '',
    '',
    '',
    'https://www.drc.gov.lk',
    'https://www.drc.gov.lk/registration-of-companies',
    'Company Registration Number',
  ),
  SD:   office(
    'Commercial Registrar General (Sudan Ministry of Justice)',
    '+249 183 770 920',
    'Ministry of Justice Complex, Khartoum, Sudan',
    'https://moj.gov.sd',
    'registry@moj.gov.sd',
    '',
    '',
    '',
    'https://moj.gov.sd/services/commercial-registration',
    '',
    'Commercial Registration Number',
  ),
  SR:   office(
    'Chamber of Commerce and Industry Suriname',
    '+597 474 889',
    'Dr. Sophie Redmondstraat 59, Paramaribo, Suriname',
    'https://www.kkf.sr',
    'info@kkf.sr',
    '',
    '',
    '',
    'https://www.kkf.sr',
    'https://www.investsuriname.org/starting-a-business',
    'KvK Number',
  ),
  SY:   office(
    'Directorate of Companies (Ministry of Internal Trade and Consumer Protection)',
    '+963 11 221 0000',
    'Damascus, Syria',
    'http://mci.gov.sy',
    '',
    '',
    '',
    '',
    'http://mci.gov.sy',
    'http://mci.gov.sy/index.php?node=5512',
    'Commercial Register Number',
  ),
  TJ:   office(
    'Tax Committee of Tajikistan (Business Registration)',
    '+992 37 221 0808',
    'Dushanbe, Tajikistan',
    'https://www.andoz.tj',
    'info@andoz.tj',
    '',
    '',
    '',
    'https://www.andoz.tj',
    'https://www.investcom.tj/starting-business',
    'INN (Taxpayer Identification Number)',
  ),
  TZ:   office(
    'Business Registrations and Licensing Agency (BRELA Tanzania)',
    '+255 22 221 0113',
    'BRELA House, Shaaban Robert Street, Dar es Salaam, Tanzania',
    'https://www.brela.go.tz',
    'info@brela.go.tz',
    'https://x.com/BrelaTanzania',
    '',
    'https://www.linkedin.com/company/brela/',
    'https://ors.brela.go.tz',
    'https://www.brela.go.tz/index.php/business-registration',
    'Company Registration Number',
  ),
  TH:   office(
    'Department of Business Development (DBD)',
    '+66 2 547 5959',
    'Nonthaburi, Thailand',
    'https://www.dbd.go.th',
    '',
    '',
    '',
    '',
    'https://www.dbd.go.th',
    'https://www.dbd.go.th/download/article/article_20200617110202.pdf',
    'Company Registration Number',
  ),
  TL:   office(
    'SERVE, I.P. One-Stop Shop (Timor-Leste)',
    '+670 7723 0044',
    'Dili, Timor-Leste',
    'https://www.serve.gov.tl',
    '',
    '',
    '',
    '',
    'https://www.serve.gov.tl',
    'https://www.tradeinvest.tl/business-registration',
    'Business Registration Number',
  ),
  TG:   office(
    'Centre de Formalites des Entreprises (CFE Togo)',
    '+228 22 53 47 47',
    'Chaine du Port, Lome, Togo',
    'https://cfe.tg',
    'info@cfe.tg',
    '',
    '',
    'https://www.linkedin.com/company/cfetogo/',
    'https://cfe.tg/creation-dentreprise',
    'https://cfe.tg/pieces-a-fournir',
    'Numero RCCM',
  ),
  TO:   office(
    'Ministry of Commerce and Consumer Affairs Tonga',
    '+676 23 611',
    'Nuku\'alofa, Tonga',
    'https://www.commerce.gov.to',
    'commerce@commerce.gov.to',
    '',
    '',
    '',
    'https://www.commerce.gov.to',
    'https://www.commerce.gov.to/business-registration',
    'Business Registration Number',
  ),
  TT:   office(
    'Companies Registry Trinidad and Tobago',
    '+1 868 624 1462',
    'Corner of Richmond and Duke Streets, Port of Spain, Trinidad and Tobago',
    'https://www.legalaffairs.gov.tt',
    'registry@legalaffairs.gov.tt',
    '',
    '',
    '',
    'https://www.legalaffairs.gov.tt',
    'https://www.investt.co.tt/starting-a-business',
    'Company Registration Number',
  ),
  TN:   office(
    'APII Tunisia - Guichet Unique de l\'Industrie',
    '+216 71 792 144',
    '63 Rue de Syrie, 1002 Tunis, Tunisia',
    'https://www.tunisieindustrie.nat.tn',
    'apii@apii.tn',
    '',
    '',
    'https://www.linkedin.com/company/agence-de-promotion-de-l-industrie-et-de-l-innovation/',
    'https://www.tunisieindustrie.nat.tn/fr/home.asp',
    'https://www.tunisieindustrie.nat.tn/fr/doc.asp',
    'Identifiant Unique de l\'Entreprise (RNE)',
  ),
  TR:   office(
    'Central Registry System Turkey (MERSIS)',
    '+90 312 417 7777',
    'Ankara, Turkey',
    'https://www.ticaret.gov.tr',
    'bilgi@ticaret.gov.tr',
    '',
    '',
    '',
    'https://mersis.ticaret.gov.tr',
    'https://www.ticaret.gov.tr/sirket-kurulus-islemleri',
    'MERSIS Number',
  ),
  TM:   office(
    'Ministry of Finance and Economy Turkmenistan',
    '+993 12 39 17 00',
    'Ashgabat, Turkmenistan',
    'https://www.turkmenistan.gov.tm',
    '',
    '',
    '',
    '',
    'https://www.turkmenistan.gov.tm',
    'https://www.turkmenistan.gov.tm/en/category/economy',
    'State Registration Number',
  ),
  UG:   office(
    'Uganda Registration Services Bureau (URSB)',
    '+256 414 233 219',
    'Plot 5 George Street, Georgian House, Kampala, Uganda',
    'https://www.ursb.go.ug',
    'registration@ursb.go.ug',
    'https://x.com/URSBHQ',
    '',
    'https://www.linkedin.com/company/uganda-registration-services-bureau/',
    'https://ursb.go.ug/business-registration/',
    'https://ursb.go.ug/forms-and-fees/',
    'Registration Number',
  ),
  UA:   office(
    'Unified State Register of Legal Entities Ukraine',
    '+380 44 279 8755',
    'Kyiv, Ukraine',
    'https://usr.minjust.gov.ua',
    'info@minjust.gov.ua',
    '',
    '',
    '',
    'https://usr.minjust.gov.ua',
    'https://usr.minjust.gov.ua/content/registration',
    'EDRPOU Code',
  ),
  AE:   office(
    'UAE National Economic Register (Ministry of Economy)',
    '+971 8001222',
    'Ministry of Economy, Abu Dhabi, United Arab Emirates',
    'https://ner.economy.ae',
    'info@economy.ae',
    '',
    '',
    'https://www.linkedin.com/company/ministry-of-economy-uae/',
    'https://ner.economy.ae',
    'https://u.ae/en/information-and-services/business/starting-a-business',
    'Trade License Number',
  ),
  UY:   office(
    'National Internal Trade Registry Uruguay (DNRPA / BPS)',
    '+598 2904 0000',
    'Montevideo, Uruguay',
    'https://www.gub.uy',
    'info@agesic.gub.uy',
    '',
    '',
    '',
    'https://www.gub.uy/tramites',
    'https://www.gub.uy/tramites/crear-empresa',
    'RUT (Registro Unico Tributario)',
  ),
  UZ:   office(
    'Ministry of Justice Uzbekistan (Single Window)',
    '+998 71 233 1010',
    'Tashkent, Uzbekistan',
    'https://www.minjust.uz',
    'info@minjust.uz',
    '',
    '',
    '',
    'https://my.gov.uz',
    'https://www.invest.gov.uz/starting-business',
    'STIR (Taxpayer Identification Number)',
  ),
  VU:   office(
    'Vanuatu Financial Services Commission',
    '+678 22666',
    'Port Vila, Vanuatu',
    'https://www.vfsc.vu',
    'info@vfsc.vu',
    '',
    '',
    '',
    'https://www.vfsc.vu',
    'https://www.vfsc.vu/company-registration',
    'Company Registration Number',
  ),
  VE:   office(
    'National Superintendency of Foreign Trade Venezuela (SUNACRIP / registro mercantil)',
    '+58 212 408 4000',
    'Caracas, Venezuela',
    'https://www.mppef.gob.ve',
    '',
    '',
    '',
    '',
    'https://www.mppef.gob.ve',
    'https://www.mppef.gob.ve/registro-mercantil',
    'RIF (Registro de Informacion Fiscal)',
  ),
  VN:   office(
    'Business Registration Management Agency (Ministry of Finance)',
    '+84 24 0804 3128',
    'Hanoi, Vietnam',
    'https://dangkykinhdoanh.gov.vn',
    '',
    '',
    '',
    '',
    'https://dangkykinhdoanh.gov.vn',
    'https://dangkykinhdoanh.gov.vn/vn/Pages/Trangchu.aspx',
    'Tax Identification Number (MST)',
  ),
  YE:   office(
    'Ministry of Industry and Trade - Companies Registrar',
    '+967 1 250 327',
    'Sanaa, Yemen',
    'https://www.moit.gov.ye',
    '',
    '',
    '',
    '',
    'https://www.moit.gov.ye',
    'https://yemen.gov.ye/portal/service',
    'Commercial Registration Number',
  ),
  ZM:   office(
    'Patents and Companies Registration Agency (PACRA Zambia)',
    '+260 211 255 127',
    'PACRA Building, Haile Selassie Avenue, Lusaka, Zambia',
    'https://www.pacra.org.zm',
    'info@pacra.org.zm',
    'https://x.com/PacraZm',
    '',
    'https://www.linkedin.com/company/pacra-zambia/',
    'https://portal.pacra.org.zm',
    'https://www.pacra.org.zm/checklists',
    'Company Registration Number',
  ),
  ZW:   office(
    'Deeds, Companies and Intellectual Property Office (DCIP Zimbabwe)',
    '+263 242 794 571',
    '4th Floor, Century House, Corner Nelson Mandela Ave and Angwa St, Harare, Zimbabwe',
    'https://dcip.gov.zw',
    'info@dcip.gov.zw',
    '',
    '',
    '',
    'https://dcip.gov.zw/company-registration',
    'https://dcip.gov.zw/requirements',
    'Company Registration Number',
  ),
}
