import type { BriMemberIsoCode } from './participantStatesIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per Belt and Road participant economy.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const BRI_DOMESTIC_POST_SERVICES: Record<BriMemberIsoCode, DomesticPostService> = {
  AF: post(
    'Afghan Post',
    'https://afghanpost.gov.af/',
    'info@afghanpost.gov.af',
    '',
    '',
    '',
    '',
    'NNNN',
    '^\\d{4}$',
    '1001',
    'Four-digit postcode (Kabul and major cities)',
  ),
  AL: post(
    'Posta Shqiptare',
    'https://www.postashqiptare.al/',
    'info@postashqiptare.al',
    'https://x.com/PostaShqiptare',
    '',
    'https://www.linkedin.com/company/posta-shqiptare/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1001',
    'Four-digit postcode',
  ),
  DZ: post(
    'Algérie Poste',
    'https://www.poste.dz/',
    'contact@poste.dz',
    'https://x.com/AlgPoste',
    'https://www.instagram.com/postealgerie/',
    'https://www.linkedin.com/company/algerie-poste/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '16000',
    'Five-digit postcode (wilaya + delivery area)',
  ),
  AO: post(
    'CTT Angola (Empresa Nacional de Correios)',
    'https://www.ctt.ao/',
    'geral@ctt.ao',
    'https://x.com/cttangola',
    'https://www.instagram.com/correiosdeangola/',
    'https://www.linkedin.com/company/correios-de-angola/',
    '',
    'none',
    '',
    '',
    'No national structured postcode; descriptive street addressing and P.O. Box common',
  ),
  AG: post(
    'Antigua and Barbuda Postal Service',
    'https://www.abpost.gov.ag/',
    'info@abpost.gov.ag',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and locality addressing',
  ),
  AR: post(
    'Correo Argentino',
    'https://www.correoargentino.com.ar/',
    'atencion@correoargentino.com.ar',
    'https://x.com/CorreoArgentino',
    'https://www.instagram.com/correoargentino/',
    'https://www.linkedin.com/company/correo-argentino/',
    '',
    'ANNNNAAA',
    '^[A-Z]\\d{4}[A-Z]{3}$',
    'C1425CLA',
    'Eight-character CPA (letter + four digits + three letters)',
  ),
  AM: post(
    'HayPost',
    'https://www.haypost.am/',
    'info@haypost.am',
    'https://x.com/HayPostArmenia',
    'https://www.instagram.com/haypost/',
    'https://www.linkedin.com/company/haypost/',
    '',
    'NNNN',
    '^\\d{4}$',
    '0010',
    'Four-digit postcode',
  ),
  AT: post(
    'Österreichische Post',
    'https://www.post.at/',
    'kundenservice@post.at',
    'https://x.com/post_at',
    'https://www.instagram.com/post_at/',
    'https://www.linkedin.com/company/osterreichische-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1010',
    'Four-digit postcode',
  ),
  AZ: post(
    'Azərpoçt',
    'https://www.azermarka.az/',
    'info@azermarka.az',
    'https://x.com/Azerpost',
    '',
    'https://www.linkedin.com/company/azerpost/',
    '',
    'AZ NNNN',
    '^AZ \\d{4}$',
    'AZ 1000',
    'AZ prefix + four digits',
  ),
  BH: post(
    'Bahrain Post',
    'https://www.bahrainpost.gov.bh/',
    'info@bahrainpost.gov.bh',
    'https://x.com/BahrainPost',
    'https://www.instagram.com/bahrainpost/',
    'https://www.linkedin.com/company/bahrain-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '317',
    'Three- or four-digit postcode',
  ),
  BD: post(
    'Bangladesh Post Office',
    'https://bdpost.gov.bd/',
    'info@bdpost.gov.bd',
    'https://x.com/BangladeshPost',
    '',
    'https://www.linkedin.com/company/bangladesh-post-office/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  BB: post(
    'Barbados Postal Service',
    'https://www.bps.gov.bb/',
    'info@bps.gov.bb',
    '',
    '',
    '',
    '',
    'BBNNNNN',
    '^BB\\d{5}$',
    'BB11000',
    'BB + five digits (Barbados)',
  ),
  BY: post(
    'Belpochta',
    'https://www.belpost.by/',
    'info@belpost.by',
    'https://x.com/belpost_by',
    '',
    'https://www.linkedin.com/company/belpochta/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '220050',
    'Six-digit postcode',
  ),
  BJ: post(
    'La Poste du Bénin',
    'https://www.poste.bj/',
    'contact@poste.bj',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-benin/',
    '',
    'none',
    '',
    '',
    'No national postcode; arrondissement and P.O. Box',
  ),
  BO: post(
    'Correos de Bolivia',
    'https://www.correos.gob.bo/',
    'info@correos.gob.bo',
    '',
    '',
    'https://www.linkedin.com/company/correos-de-bolivia/',
    '',
    'none',
    '',
    '',
    'No national postcode system; city and zone addressing',
  ),
  BA: post(
    'BH Pošta / Pošte Srpske',
    'https://www.posta.ba/',
    'info@posta.ba',
    '',
    '',
    'https://www.linkedin.com/company/bh-posta/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '71000',
    'Five-digit postcode (Bosnia and Herzegovina)',
  ),
  BW: post(
    'BotswanaPost',
    'https://www.botspost.co.bw/',
    'customercare@botspost.co.bw',
    'https://x.com/BotswanaPost',
    'https://www.instagram.com/botswanapost/',
    'https://www.linkedin.com/company/botswanapost/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00000',
    'Five-digit national postcode (verify district mapping locally)',
  ),
  BN: post(
    'Postal Services Department (Brunei)',
    'https://www.post.gov.bn/',
    'postmaster@post.gov.bn',
    '',
    '',
    'https://www.linkedin.com/company/postal-services-department-brunei/',
    '',
    'AANNNN',
    '^[A-Z]{2}\\d{4}$',
    'BA2110',
    'Two-letter area + four digits (Brunei Darussalam)',
  ),
  BG: post(
    'Bulgarian Posts',
    'https://www.bgpost.bg/',
    'info@bgpost.bg',
    'https://x.com/BulgarianPosts',
    '',
    'https://www.linkedin.com/company/bulgarian-posts/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  BI: post(
    'Régie nationale des Postes du Burundi',
    'http://www.poste.bi/',
    'info@burundipost.bi',
    '',
    '',
    'https://www.linkedin.com/company/poste-burundi/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune-based addressing',
  ),
  CV: post(
    'Correios de Cabo Verde',
    'https://correios.cv/',
    'cac@cvcorreios.cv',
    'https://x.com/correioscv',
    'https://www.instagram.com/correioscv/',
    'https://www.linkedin.com/company/correios-de-cabo-verde/',
    '',
    'NNNN-NNNN',
    '^\\\\d{4}-\\\\d{4}$',
    '7600-001',
    'Four-digit island prefix + four-digit delivery zone',
  ),
  KH: post(
    'Cambodia Post',
    'https://www.cambodiapost.com.kh/',
    'info@cambodiapost.com.kh',
    '',
    '',
    'https://www.linkedin.com/company/cambodia-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '12000',
    'Five-digit postcode',
  ),
  CM: post(
    'CAMPOST',
    'http://campost.cm/',
    'info@campost.cm',
    '',
    '',
    'https://www.linkedin.com/company/campost/',
    '',
    'none',
    '',
    '',
    'No national postcode; regional and P.O. Box routing',
  ),
  CF: post(
    'Office national des Postes RCA',
    'https://onet-rca.cf/',
    'contact@onet-rca.cf',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  TD: post(
    'La Poste Tchadienne',
    'https://www.laposte.td/',
    'contact@laposte.td',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-tchadienne/',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  CL: post(
    'Correos de Chile',
    'https://www.correos.cl/',
    'contacto@correos.cl',
    'https://x.com/CorreosChile',
    'https://www.instagram.com/correoschile/',
    'https://www.linkedin.com/company/correos-de-chile/',
    '',
    'NNNNNNN',
    '^\\d{7}$',
    '8320000',
    'Seven-digit postcode',
  ),
  CN: post(
    'China Post',
    'https://www.ems.com.cn/',
    'service@ems.com.cn',
    'https://x.com/chinapost',
    'https://www.instagram.com/chinapost/',
    'https://www.linkedin.com/company/china-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
  CO: post(
    '4-72 (Correos de Colombia)',
    'https://www.4-72.com.co/',
    'contactenos@4-72.com.co',
    'https://x.com/472Colombia',
    'https://www.instagram.com/472colombia/',
    'https://www.linkedin.com/company/4-72/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '110111',
    'Six-digit código postal',
  ),
  KM: post(
    'Comores Poste',
    'https://poste-comores.com/',
    'contact@poste-comores.km',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and village addressing',
  ),
  CK: post(
    'Cook Islands Post Office',
    'https://www.cookislands.gov.ck/',
    'postoffice@cookislands.gov.ck',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; Rarotonga and island addressing',
  ),
  CR: post(
    'Correos de Costa Rica',
    'https://www.correos.go.cr/',
    'atencioncliente@correos.go.cr',
    'https://x.com/CorreosCR',
    '',
    'https://www.linkedin.com/company/correos-de-costa-rica/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10101',
    'Five-digit código postal',
  ),
  CI: post(
    'La Poste de Côte d\'Ivoire',
    'https://www.la-poste.ci/',
    'info@laposte.ci',
    'https://x.com/LaPosteCI',
    'https://www.instagram.com/laposteci/',
    'https://www.linkedin.com/company/la-poste-de-cote-divoire/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune and P.O. Box dominant',
  ),
  HR: post(
    'Hrvatska pošta',
    'https://www.posta.hr/',
    'info@posta.hr',
    'https://x.com/HrvatskaPosta',
    'https://www.instagram.com/hrvatskaposta/',
    'https://www.linkedin.com/company/hrvatska-posta/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10000',
    'Five-digit postcode',
  ),
  CU: post(
    'Correos de Cuba',
    'https://www.correos.cu/',
    'info@correos.cu',
    '',
    '',
    '',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10400',
    'Five-digit código postal',
  ),
  CY: post(
    'Cyprus Post',
    'https://www.cypruspost.post/',
    'info@cypruspost.post',
    'https://x.com/CyprusPost',
    '',
    'https://www.linkedin.com/company/cyprus-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1010',
    'Four-digit postcode',
  ),
  CZ: post(
    'Česká pošta',
    'https://www.ceskaposta.cz/',
    'info@ceskaposta.cz',
    'https://x.com/CeskaPosta',
    'https://www.instagram.com/ceskaposta/',
    'https://www.linkedin.com/company/ceska-posta/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '110 00',
    'Five-digit postcode (space after third digit)',
  ),
  CD: post(
    'SCPT RDC (Services postaux)',
    'https://scpt.cd/',
    'info@postesrdc.cd',
    '',
    '',
    'https://www.linkedin.com/company/scpt-rdc/',
    '',
    'none',
    '',
    '',
    'No universal national postcode; commune and P.O. Box',
  ),
  DJ: post(
    'La Poste de Djibouti',
    'https://www.laposte.dj/',
    'poste.contact@yahoo.fr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing in Djibouti City',
  ),
  DM: post(
    'Dominica Postal Service',
    'https://www.dominicapost.dm/',
    'info@dominicapost.dm',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  DO: post(
    'INPOSDOM (Correos Dominicanos)',
    'https://www.inposdom.gob.do/',
    'info@inposdom.gob.do',
    'https://x.com/INPOSDOM',
    '',
    'https://www.linkedin.com/company/inposdom/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10101',
    'Five-digit código postal',
  ),
  EC: post(
    'Correos del Ecuador',
    'https://www.correosdelecuador.gob.ec/',
    'info@correosdelecuador.gob.ec',
    'https://x.com/CorreosEcuador',
    '',
    'https://www.linkedin.com/company/correos-del-ecuador/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '170150',
    'Six-digit código postal',
  ),
  EG: post(
    'Egypt Post',
    'http://www.egpost.org/',
    'webmaster@egpost.org',
    'https://x.com/Egyptpost',
    'https://www.instagram.com/egypt.post/',
    'https://www.linkedin.com/company/egypt-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11511',
    'Five-digit national postcode',
  ),
  SV: post(
    'Correos de El Salvador',
    'https://www.correos.gob.sv/',
    'info@correos.gob.sv',
    '',
    '',
    'https://www.linkedin.com/company/correos-de-el-salvador/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1101',
    'Four-digit código postal',
  ),
  GQ: post(
    'Correos de Guinea Ecuatorial',
    'https://www.correosgq.com/',
    'info@correosgq.com',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; Malabo/Bata addressing',
  ),
  ER: post(
    'Eritrean Postal Service',
    'https://www.shabait.com/category/national-development/telecom-post/',
    'info@ericsson.com.er',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No published national postcode system',
  ),
  EE: post(
    'Omniva (Eesti Post)',
    'https://www.omniva.ee/',
    'info@omniva.ee',
    'https://x.com/OmnivaEE',
    'https://www.instagram.com/omniva/',
    'https://www.linkedin.com/company/omniva/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10111',
    'Five-digit postcode',
  ),
  ET: post(
    'Ethiopian Postal Service (EPSE)',
    'https://www.ethiopostal.com/',
    'info@ethiopostal.com',
    '',
    '',
    'https://www.linkedin.com/company/ethiopian-postal-service/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Addis Ababa and regional centres)',
  ),
  FJ: post(
    'Fiji Post',
    'https://www.fijipost.com.fj/',
    'info@fijipost.com.fj',
    'https://x.com/FijiPost',
    '',
    'https://www.linkedin.com/company/fiji-post/',
    '',
    'none',
    '',
    '',
    'No national postcode; town and island addressing',
  ),
  GA: post(
    'Gabon Poste EMS',
    'https://www.gabonpost.ga/',
    'infos@gpost.ga',
    '',
    '',
    'https://www.linkedin.com/company/gabon-poste/',
    '',
    'none',
    '',
    '',
    'No national postcode; Libreville/Port-Gentil district addressing',
  ),
  GM: post(
    'GamPost',
    'https://gampost.gm/',
    'info@gampost.gm',
    '',
    '',
    'https://www.linkedin.com/company/gampost/',
    '',
    'none',
    '',
    '',
    'No national postcode; settlement and P.O. Box',
  ),
  GE: post(
    'Georgian Post',
    'https://www.gpost.ge/',
    'info@gpost.ge',
    'https://x.com/GeorgianPost',
    '',
    'https://www.linkedin.com/company/georgian-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '0108',
    'Four-digit postcode',
  ),
  GH: post(
    'Ghana Post',
    'http://ghanapost.com.gh/',
    'info@ghanapost.com.gh',
    'https://x.com/ghanapostgh',
    'https://www.instagram.com/ghanapostgh/',
    'https://www.linkedin.com/company/ghana-post/',
    '',
    'none',
    '',
    '',
    'GhanaPostGPS digital address parallel to legacy P.O. Box; no legacy numeric postcode',
  ),
  GR: post(
    'ELTA Hellenic Post',
    'https://www.elta.gr/',
    'info@elta.gr',
    'https://x.com/elta_gr',
    'https://www.instagram.com/elta_gr/',
    'https://www.linkedin.com/company/elta-hellenic-post/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '104 31',
    'Five-digit postcode (space after third digit)',
  ),
  GD: post(
    'Grenada Postal Corporation',
    'https://www.grenadapost.gd/',
    'info@grenadapost.gd',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  GN: post(
    'La Poste Guinée',
    'https://www.gui.post/',
    'direction@gui.post',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-guinee/',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  GW: post(
    'Correios da Guiné-Bissau',
    'https://www.correios.gw/',
    'geral@cgb.gw',
    '',
    '',
    '',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Bissau and regional)',
  ),
  GY: post(
    'Guyana Post Office Corporation',
    'https://www.guyanapost.gy/',
    'info@guyanapost.gy',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; locality addressing',
  ),
  HN: post(
    'Honducor (Correos de Honduras)',
    'https://www.honducor.gob.hn/',
    'info@honducor.gob.hn',
    '',
    '',
    'https://www.linkedin.com/company/honducor/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11101',
    'Five-digit código postal',
  ),
  HU: post(
    'Magyar Posta',
    'https://www.posta.hu/',
    'ugyfelszolgalat@posta.hu',
    'https://x.com/MagyarPosta',
    'https://www.instagram.com/magyarposta/',
    'https://www.linkedin.com/company/magyar-posta/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1051',
    'Four-digit postcode',
  ),
  ID: post(
    'Pos Indonesia',
    'https://www.posindonesia.co.id/',
    'pusatbantuan@posindonesia.co.id',
    'https://x.com/PosIndonesia',
    'https://www.instagram.com/posindonesia/',
    'https://www.linkedin.com/company/pos-indonesia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10110',
    'Five-digit postcode',
  ),
  IR: post(
    'Iran Post (Pishtaz)',
    'https://www.post.ir/',
    'info@post.ir',
    'https://x.com/IranPost',
    '',
    'https://www.linkedin.com/company/iran-post/',
    '',
    'NNNNN-NNNNN',
    '^\\d{5}-\\d{5}$',
    '13147-13146',
    'Ten-digit postcode (five + hyphen + five)',
  ),
  IQ: post(
    'Iraqi Post (Iraq Post Company)',
    'https://www.iraqpost.net/',
    'info@iraqpost.net',
    '',
    '',
    'https://www.linkedin.com/company/iraq-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10001',
    'Five-digit postcode',
  ),
  IT: post(
    'Poste Italiane',
    'https://www.poste.it/',
    'assistenza.clienti@poste.it',
    'https://x.com/PosteItaliane',
    'https://www.instagram.com/posteitaliane/',
    'https://www.linkedin.com/company/poste-italiane/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00118',
    'Five-digit CAP',
  ),
  JM: post(
    'Jamaica Post',
    'https://www.jamaicapost.gov.jm/',
    'info@jamaicapost.gov.jm',
    'https://x.com/JamaicaPost',
    '',
    'https://www.linkedin.com/company/jamaica-post/',
    '',
    'none',
    '',
    '',
    'No national postcode; parish and locality addressing',
  ),
  JO: post(
    'Jordan Post',
    'https://www.jordanpost.com.jo/',
    'info@jordanpost.com.jo',
    'https://x.com/JordanPostCo',
    'https://www.instagram.com/jordanpost/',
    'https://www.linkedin.com/company/jordan-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11118',
    'Five-digit postcode',
  ),
  KZ: post(
    'Kazpost',
    'https://www.kazpost.kz/',
    'info@kazpost.kz',
    'https://x.com/Kazpost',
    '',
    'https://www.linkedin.com/company/kazpost/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '010000',
    'Six-digit postcode',
  ),
  KE: post(
    'Postal Corporation of Kenya',
    'http://posta.co.ke/',
    'customercare@posta.co.ke',
    'https://x.com/postakenya',
    'https://www.instagram.com/postakenya/',
    'https://www.linkedin.com/company/postal-corporation-of-kenya/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00100',
    'Five-digit postcode; P.O. Box culture remains common',
  ),
  KI: post(
    'Kiribati Post',
    'https://www.kiribatipost.ki/',
    'info@kiribatipost.ki',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  KW: post(
    'Kuwait Post',
    'https://www.kuwaitpost.com/',
    'info@kuwaitpost.com',
    'https://x.com/KuwaitPost',
    'https://www.instagram.com/kuwaitpost/',
    'https://www.linkedin.com/company/kuwait-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '13001',
    'Five-digit postcode',
  ),
  KG: post(
    'Kyrgyz Pochtasy',
    'https://www.kyrgyzpost.kg/',
    'info@kyrgyzpost.kg',
    '',
    '',
    'https://www.linkedin.com/company/kyrgyz-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '720000',
    'Six-digit postcode',
  ),
  LA: post(
    'Lao Post',
    'https://www.laopost.com.la/',
    'info@laopost.la',
    '',
    '',
    'https://www.linkedin.com/company/lao-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '01000',
    'Five-digit postcode',
  ),
  LV: post(
    'Latvijas Pasts',
    'https://www.pasts.lv/',
    'info@pasts.lv',
    'https://x.com/LatvijasPasts',
    '',
    'https://www.linkedin.com/company/latvijas-pasts/',
    '',
    'LV-NNNN',
    '^LV-\\d{4}$',
    'LV-1050',
    'LV- prefix + four digits',
  ),
  LB: post(
    'Liban Post',
    'https://www.libanpost.com/',
    'info@libanpost.com',
    'https://x.com/LibanPost',
    'https://www.instagram.com/libanpost/',
    'https://www.linkedin.com/company/liban-post/',
    '',
    'NNNN NNNN',
    '^\\d{4} \\d{4}$',
    '1107 2810',
    'Eight-digit postcode (two groups of four)',
  ),
  LS: post(
    'Lesotho Postal Services',
    'https://lesothopost.org.ls/',
    'info@post.org.ls',
    '',
    '',
    'https://www.linkedin.com/company/lesotho-postal-services/',
    '',
    'NNN',
    '^\\\\d{3}$',
    '100',
    'Three-digit postcode',
  ),
  LR: post(
    'LIBPOST',
    'https://libpost.com.lr/',
    'info@libpost.com.lr',
    '',
    '',
    'https://www.linkedin.com/company/libpost/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1000',
    'Four-digit postcode (Monrovia and counties)',
  ),
  LY: post(
    'Libyan Post Company',
    'http://nlpc.ly/',
    'info@nlpc.ly',
    '',
    '',
    'https://www.linkedin.com/company/libyan-post/',
    '',
    'none',
    '',
    '',
    'No consistent national postcode published; verify locally',
  ),
  LT: post(
    'Lietuvos paštas',
    'https://www.post.lt/',
    'info@post.lt',
    'https://x.com/LietuvosPastas',
    '',
    'https://www.linkedin.com/company/lietuvos-pastas/',
    '',
    'LT-NNNNN',
    '^LT-\\d{5}$',
    'LT-01100',
    'LT- prefix + five digits',
  ),
  LU: post(
    'POST Luxembourg',
    'https://www.post.lu/',
    'info@post.lu',
    'https://x.com/POSTLuxembourg',
    'https://www.instagram.com/postluxembourg/',
    'https://www.linkedin.com/company/post-luxembourg/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1019',
    'Four-digit postcode',
  ),
  MG: post(
    'Paositra Malagasy',
    'http://www.poste.mg/',
    'contact@paositra.mg',
    'https://x.com/Paositra',
    'https://www.instagram.com/paositramalagasy/',
    'https://www.linkedin.com/company/paositra-malagasy/',
    '',
    'NNN',
    '^\\\\d{3}$',
    '101',
    'Three-digit postcode',
  ),
  MW: post(
    'Malawi Posts Corporation',
    'https://malawipost.gov.mw/',
    'info@malawipost.gov.mw',
    '',
    '',
    'https://www.linkedin.com/company/malawi-posts-corporation/',
    '',
    'none',
    '',
    '',
    'No national postcode; district and P.O. Box',
  ),
  MY: post(
    'Pos Malaysia',
    'https://www.pos.com.my/',
    'customercare@pos.com.my',
    'https://x.com/posmalaysia',
    'https://www.instagram.com/posmalaysia/',
    'https://www.linkedin.com/company/pos-malaysia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '50000',
    'Five-digit postcode',
  ),
  MV: post(
    'Maldives Post',
    'https://www.maldivespost.com/',
    'info@maldivespost.com',
    'https://x.com/MaldivesPost',
    '',
    'https://www.linkedin.com/company/maldives-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '20026',
    'Five-digit postcode',
  ),
  ML: post(
    'La Poste du Mali EMS',
    'https://www.sap.ml/',
    'contact@post.ml',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-mali/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune addressing',
  ),
  MT: post(
    'MaltaPost',
    'https://www.maltapost.com/',
    'info@maltapost.com',
    'https://x.com/MaltaPost',
    'https://www.instagram.com/maltapost/',
    'https://www.linkedin.com/company/maltapost/',
    '',
    'AAA NNNN',
    '^[A-Z]{3} \\d{4}$',
    'VLT 1117',
    'Three letters + space + four digits',
  ),
  MR: post(
    'Mauripost (Société mauritanienne des postes)',
    'https://www.mauripost.mr/',
    'contact@mauripost.mr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  FM: post(
    'FSM Postal Service',
    'https://www.fsmpost.fm/',
    'info@fsmpost.fm',
    '',
    '',
    '',
    '',
    'NNNNN',
    '^\\d{5}$',
    '96941',
    'Five-digit postcode (uses US ZIP format)',
  ),
  MD: post(
    'Poșta Moldovei',
    'https://www.posta.md/',
    'info@posta.md',
    'https://x.com/PostaMoldovei',
    '',
    'https://www.linkedin.com/company/posta-moldovei/',
    '',
    'MD-NNNN',
    '^MD-\\d{4}$',
    'MD-2001',
    'MD- prefix + four digits',
  ),
  MN: post(
    'Mongol Post',
    'https://www.mongolpost.mn/',
    'info@mongolpost.mn',
    '',
    '',
    'https://www.linkedin.com/company/mongol-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '14200',
    'Five-digit postcode',
  ),
  ME: post(
    'Pošta Crne Gore',
    'https://www.postacg.me/',
    'info@postacg.me',
    '',
    '',
    'https://www.linkedin.com/company/posta-crne-gore/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '81000',
    'Five-digit postcode',
  ),
  MA: post(
    'Barid Al-Maghrib',
    'https://www.barid.ma/',
    'webmaster@barid.ma',
    'https://x.com/PosteMaroc',
    'https://www.instagram.com/baridalma_',
    'https://www.linkedin.com/company/barid-al-maghrib/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '20000',
    'Five-digit postcode',
  ),
  MZ: post(
    'Correios de Moçambique',
    'http://correios.co.mz/',
    'cac@correios.co.mz',
    '',
    '',
    'https://www.linkedin.com/company/correios-de-mocambique/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1100',
    'Four-digit postcode',
  ),
  MM: post(
    'Myanmar Post',
    'https://www.myanmarpost.com.mm/',
    'info@myanmarpost.com.mm',
    '',
    '',
    'https://www.linkedin.com/company/myanmar-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11181',
    'Five-digit postcode (Yangon)',
  ),
  NA: post(
    'NamPost',
    'https://nampost.na/',
    'customerservice@namibiapost.na',
    '',
    '',
    'https://www.linkedin.com/company/nampost/',
    '',
    'none',
    '',
    '',
    'Private bag / P.O. Box numbering; no universal street postcode',
  ),
  NP: post(
    'Nepal Post',
    'https://www.nepalpost.gov.np/',
    'info@nepalpost.gov.np',
    '',
    '',
    'https://www.linkedin.com/company/nepal-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '44600',
    'Five-digit postcode',
  ),
  NZ: post(
    'NZ Post',
    'https://www.nzpost.co.nz/',
    'customercare@nzpost.co.nz',
    'https://x.com/NZPost',
    'https://www.instagram.com/nzpost/',
    'https://www.linkedin.com/company/nz-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '6011',
    'Four-digit postcode',
  ),
  NI: post(
    'Correos de Nicaragua',
    'https://www.correos.gob.ni/',
    'info@correos.gob.ni',
    '',
    '',
    '',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11001',
    'Five-digit código postal',
  ),
  NE: post(
    'La Poste du Niger',
    'https://www.nigerpost.ne/',
    'npn@refer.ne',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-niger/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '8001',
    'Four-digit postcode (Niamey and regions)',
  ),
  NG: post(
    'Nigeria Postal Service (NIPOST)',
    'http://nipost.gov.ng/',
    'info@nipost.gov.ng',
    'https://x.com/e_nipost',
    'https://www.instagram.com/e_nipost/',
    'https://www.linkedin.com/company/nipost/',
    '',
    'NNNNNN',
    '^\\\\d{6}$',
    '100001',
    'Six-digit postcode (state + LGA + delivery)',
  ),
  NU: post(
    'Niue Post',
    'https://www.niuepost.nu/',
    'info@niuepost.nu',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; village addressing',
  ),
  MK: post(
    'North Macedonia Post (Пошта на Северна Македонија)',
    'https://www.posta.com.mk/',
    'info@posta.com.mk',
    '',
    '',
    'https://www.linkedin.com/company/north-macedonia-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  OM: post(
    'Oman Post',
    'https://www.omanpost.om/',
    'info@omanpost.om',
    'https://x.com/OmanPost',
    'https://www.instagram.com/omanpost/',
    'https://www.linkedin.com/company/oman-post/',
    '',
    'NNN',
    '^\\d{3}$',
    '100',
    'Three-digit postcode',
  ),
  PK: post(
    'Pakistan Post',
    'https://www.pakpost.gov.pk/',
    'info@pakpost.gov.pk',
    'https://x.com/PakistanPost',
    '',
    'https://www.linkedin.com/company/pakistan-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '44000',
    'Five-digit postcode',
  ),
  PA: post(
    'Correos y Telégrafos de Panamá',
    'https://www.correospanama.gob.pa/',
    'info@correospanama.gob.pa',
    '',
    '',
    'https://www.linkedin.com/company/correos-y-telegrafos-de-panama/',
    '',
    'none',
    '',
    '',
    'No national street postcode; zone and building addressing',
  ),
  PG: post(
    'Post PNG',
    'https://www.postpng.com.pg/',
    'info@postpng.com.pg',
    '',
    '',
    'https://www.linkedin.com/company/post-png/',
    '',
    'NNN',
    '^\\d{3}$',
    '111',
    'Three-digit postcode',
  ),
  PE: post(
    'Serpost (Correos del Perú)',
    'https://www.serpost.com.pe/',
    'atencion@serpost.com.pe',
    'https://x.com/SerpostPeru',
    'https://www.instagram.com/serpostperu/',
    'https://www.linkedin.com/company/serpost/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '15001',
    'Five-digit código postal (Lima uses leading 15)',
  ),
  PH: post(
    'Philippine Postal Corporation (PHLPost)',
    'https://www.phlpost.gov.ph/',
    'info@phlpost.gov.ph',
    'https://x.com/PHLPost',
    'https://www.instagram.com/phlpost/',
    'https://www.linkedin.com/company/philippine-postal-corporation/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  PL: post(
    'Poczta Polska',
    'https://www.poczta-polska.pl/',
    'kontakt@poczta-polska.pl',
    'https://x.com/PocztaPolska',
    'https://www.instagram.com/pocztapolska/',
    'https://www.linkedin.com/company/poczta-polska/',
    '',
    'NN-NNN',
    '^\\d{2}-\\d{3}$',
    '00-950',
    'Five-digit postcode (hyphen after second digit)',
  ),
  PT: post(
    'CTT Correios de Portugal',
    'https://www.ctt.pt/',
    'info@ctt.pt',
    'https://x.com/CTT',
    'https://www.instagram.com/ctt/',
    'https://www.linkedin.com/company/ctt/',
    '',
    'NNNN-NNN',
    '^\\d{4}-\\d{3}$',
    '1000-001',
    'Seven-digit código postal (four + hyphen + three)',
  ),
  QA: post(
    'Qatar Post (Q-Post)',
    'https://www.qpost.com.qa/',
    'info@qpost.com.qa',
    'https://x.com/QatarPost',
    'https://www.instagram.com/qatarpost/',
    'https://www.linkedin.com/company/qatar-post/',
    '',
    'none',
    '',
    '',
    'No national street postcode; zone and building addressing',
  ),
  CG: post(
    'La Poste du Congo EMS',
    'http://laposte.cg/',
    'contact@lacongolaise.cg',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-congo/',
    '',
    'none',
    '',
    '',
    'No national postcode; Brazzaville/Pointe-Noire district addressing',
  ),
  RO: post(
    'Poșta Română',
    'https://www.posta-romana.ro/',
    'relatii.clienti@posta-romana.ro',
    'https://x.com/PostaRomana',
    'https://www.instagram.com/postaromana/',
    'https://www.linkedin.com/company/posta-romana/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '010011',
    'Six-digit postcode',
  ),
  RU: post(
    'Russian Post (Pochta Rossii)',
    'https://www.pochta.ru/',
    'info@russianpost.ru',
    'https://x.com/russianpost',
    'https://www.instagram.com/russianpost/',
    'https://www.linkedin.com/company/russian-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '101000',
    'Six-digit postcode',
  ),
  RW: post(
    'Rwanda Post (Iposita)',
    'https://i-posita.rw/',
    'info@ipostarltd.rw',
    'https://x.com/ipositaryw',
    'https://www.instagram.com/ipositaryw/',
    'https://www.linkedin.com/company/iposta-rwanda/',
    '',
    'none',
    '',
    '',
    'No legacy numeric postcode; Kigali addressing reforms — verify locally',
  ),
  WS: post(
    'Samoa Post',
    'https://www.samoapost.ws/',
    'info@samoapost.ws',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; village addressing',
  ),
  SA: post(
    'Saudi Post (SPL)',
    'https://splonline.com.sa/',
    'customercare@splonline.com.sa',
    'https://x.com/SPLCare',
    'https://www.instagram.com/splcare/',
    'https://www.linkedin.com/company/saudi-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11564',
    'Five-digit postcode (national addressing system)',
  ),
  SN: post(
    'La Poste Sénégal',
    'https://www.laposte.sn/',
    'dircom@laposte.sn',
    'https://x.com/LaPosteSenegal',
    'https://www.instagram.com/lapostesenegal/',
    'https://www.linkedin.com/company/la-poste-senegal/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '12500',
    'Five-digit postcode',
  ),
  RS: post(
    'Pošta Srbije',
    'https://www.posta.rs/',
    'info@posta.rs',
    'https://x.com/PostaSrbije',
    '',
    'https://www.linkedin.com/company/posta-srbije/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11000',
    'Five-digit postcode',
  ),
  SC: post(
    'Seychelles Postal Services',
    'https://www.seychelles-post.com/',
    'info@sib.gov.sc',
    '',
    '',
    'https://www.linkedin.com/company/seychelles-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; island and district addressing',
  ),
  SL: post(
    'Salone Post EMS',
    'https://www.slpost.gov.sl/',
    'info@slipa.gov.sl',
    '',
    '',
    'https://www.linkedin.com/company/sierra-leone-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; Freetown district addressing',
  ),
  SG: post(
    'Singapore Post',
    'https://www.singpost.com/',
    'feedback@singpost.com',
    'https://x.com/SingPost',
    'https://www.instagram.com/singpost/',
    'https://www.linkedin.com/company/singapore-post-limited/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '018956',
    'Six-digit postcode',
  ),
  SK: post(
    'Slovenská pošta',
    'https://www.posta.sk/',
    'info@posta.sk',
    'https://x.com/SlovenskaPosta',
    '',
    'https://www.linkedin.com/company/slovenska-posta/',
    '',
    'NNN NN',
    '^\\d{3} \\d{2}$',
    '811 01',
    'Five-digit postcode (space after third digit)',
  ),
  SI: post(
    'Pošta Slovenije',
    'https://www.posta.si/',
    'info@posta.si',
    'https://x.com/PostaSlovenije',
    '',
    'https://www.linkedin.com/company/posta-slovenije/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode (SI- prefix optional)',
  ),
  SB: post(
    'Solomon Post',
    'https://www.solomonpost.com.sb/',
    'info@solomonpost.com.sb',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  SO: post(
    'Somali Postal Service',
    'https://www.upu.int/en/Somalia',
    'minister@mpt.gov.so',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district and landmark addressing',
  ),
  ZA: post(
    'South African Post Office',
    'http://www.postoffice.co.za/',
    'custserv@postoffice.co.za',
    'https://x.com/PostofficeSa',
    'https://www.instagram.com/sapostoffice/',
    'https://www.linkedin.com/company/south-african-post-office/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '2000',
    'Four-digit postcode (street delivery and P.O. Box)',
  ),
  SS: post(
    'South Sudan Post',
    'http://ssscc.org/',
    'sssccngo@gmail.com',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system; Juba district addressing',
  ),
  LK: post(
    'Sri Lanka Post',
    'https://www.slpost.gov.lk/',
    'info@slpost.gov.lk',
    'https://x.com/SLPost',
    '',
    'https://www.linkedin.com/company/sri-lanka-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00100',
    'Five-digit postcode',
  ),
  SD: post(
    'Sudan Post (Sudapost)',
    'https://sudapost.sd/',
    'info@sudapost.sd',
    '',
    '',
    'https://www.linkedin.com/company/sudan-post/',
    '',
    'NNNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{5}$',
    '11111',
    'Five-digit postcode (verify operational coverage)',
  ),
  SR: post(
    'Surpost (Suriname Post)',
    'https://www.surpost.sr/',
    'info@surpost.sr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing',
  ),
  SY: post(
    'Syrian Post',
    'https://www.syrianpost.gov.sy/',
    'info@syrianpost.gov.sy',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No consistent national postcode published; verify locally',
  ),
  TJ: post(
    'Tajik Pocht',
    'https://www.tajikpost.tj/',
    'info@tajikpost.tj',
    '',
    '',
    '',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '734000',
    'Six-digit postcode',
  ),
  TZ: post(
    'Tanzania Posts Corporation',
    'https://posta.co.tz/',
    'info@tpoc.co.tz',
    '',
    '',
    'https://www.linkedin.com/company/tanzania-posts-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '11101',
    'Five-digit postcode',
  ),
  TH: post(
    'Thailand Post',
    'https://www.thailandpost.co.th/',
    'contact@thailandpost.co.th',
    'https://x.com/ThailandPost',
    'https://www.instagram.com/thailandpost/',
    'https://www.linkedin.com/company/thailand-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10100',
    'Five-digit postcode',
  ),
  TL: post(
    'Correios de Timor-Leste',
    'https://www.correios.tl/',
    'info@correios.tl',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system; district addressing',
  ),
  TG: post(
    'La Poste du Togo',
    'https://www.laposte.tg/',
    'contact@laposte.tg',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-togo/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune addressing',
  ),
  TO: post(
    'Tonga Post',
    'https://www.tongapost.to/',
    'info@tongapost.to',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  TT: post(
    'TTPost (Trinidad and Tobago Postal Corporation)',
    'https://www.ttpost.net/',
    'info@ttpost.net',
    'https://x.com/TTPost',
    '',
    'https://www.linkedin.com/company/ttpost/',
    '',
    'none',
    '',
    '',
    'No national postcode; locality addressing',
  ),
  TN: post(
    'Rapid-Poste (La Poste Tunisia)',
    'https://www.pos.tn/',
    'contact@rapidpost.com.tn',
    'https://x.com/RapidposteTN',
    'https://www.instagram.com/rapidpostenetunisienne/',
    'https://www.linkedin.com/company/la-poste-tunisienne/',
    '',
    'NNNN',
    '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  TR: post(
    'PTT (Türkiye Post)',
    'https://www.ptt.gov.tr/',
    'info@ptt.gov.tr',
    'https://x.com/PTT',
    'https://www.instagram.com/ptt/',
    'https://www.linkedin.com/company/ptt/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '06100',
    'Five-digit postcode',
  ),
  TM: post(
    'Turkmen Pochtasy',
    'https://www.turkmenpost.gov.tm/',
    'info@turkmenpost.gov.tm',
    '',
    '',
    '',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '744000',
    'Six-digit postcode',
  ),
  UG: post(
    'Uganda Post Limited',
    'https://www.eposta.ug/',
    'info@posta.co.ug',
    'https://x.com/ugposts',
    'https://www.instagram.com/ugposts/',
    'https://www.linkedin.com/company/uganda-post-limited/',
    '',
    'none',
    '',
    '',
    'P.O. Box dominant; no universal street postcode',
  ),
  UA: post(
    'Ukrposhta',
    'https://www.ukrposhta.ua/',
    'info@ukrposhta.ua',
    'https://x.com/Ukrposhta',
    'https://www.instagram.com/ukrposhta/',
    'https://www.linkedin.com/company/ukrposhta/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '01001',
    'Five-digit postcode',
  ),
  AE: post(
    'Emirates Post Group',
    'https://www.epg.ae/',
    'info@epg.ae',
    'https://x.com/EmiratesPost',
    'https://www.instagram.com/emiratespost/',
    'https://www.linkedin.com/company/emirates-post-group/',
    '',
    'none',
    '',
    '',
    'No national postcode; Makani / building addressing in UAE',
  ),
  UY: post(
    'Correo Uruguayo',
    'https://www.correo.com.uy/',
    'atencion@correo.com.uy',
    'https://x.com/CorreoUruguayo',
    '',
    'https://www.linkedin.com/company/correo-uruguayo/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11000',
    'Five-digit código postal',
  ),
  UZ: post(
    'O\'zbekiston Pochtasi',
    'https://www.pochta.uz/',
    'info@pochta.uz',
    '',
    '',
    'https://www.linkedin.com/company/uzbekistan-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
  VU: post(
    'Vanuatu Post',
    'https://www.vanuatupost.vu/',
    'info@vanuatupost.vu',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  VE: post(
    'IPOSTEL (Correo de Venezuela)',
    'https://www.ipostel.gob.ve/',
    'info@ipostel.gob.ve',
    '',
    '',
    '',
    '',
    'NNNN',
    '^\\d{4}$',
    '1010',
    'Four-digit código postal (Caracas)',
  ),
  VN: post(
    'Vietnam Post (VNPost)',
    'https://www.vnpost.vn/',
    'contact@vnpost.vn',
    'https://x.com/VNPost',
    'https://www.instagram.com/vnpost/',
    'https://www.linkedin.com/company/vietnam-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
  YE: post(
    'Yemen Post',
    'https://www.yemenpost.ye/',
    'info@yemenpost.ye',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'Limited national postcode coverage; verify operational status locally',
  ),
  ZM: post(
    'Zambia Postal Services Corporation',
    'http://www.zampost.gov.zm/',
    'info.zampost@gmail.com',
    '',
    '',
    'https://www.linkedin.com/company/zambia-postal-services-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '10101',
    'Five-digit postcode',
  ),
  ZW: post(
    'Zimpost',
    'http://www.zimpost.co.zw/',
    'zimpost@zimpost.co.zw',
    'https://x.com/zimpost_',
    'https://www.instagram.com/zimpost_/',
    'https://www.linkedin.com/company/zimpost/',
    '',
    'none',
    '',
    '',
    'No national postcode; suburb and P.O. Box routing',
  ),
}
