import type { IntellectualPropertyDepartmentsRoster } from './types'
import { BRI_INTELLECTUAL_PROPERTY_DEPARTMENTS } from './intellectualPropertyDepartmentsByIso'

/**
 * Subset of `BRI_INTELLECTUAL_PROPERTY_DEPARTMENTS` for participant economies not represented
 * in other alliance IP modules in this repository. Re-exported for optional use by other
 * packages; canonical data lives in `intellectualPropertyDepartmentsByIso.ts` in this folder.
 */
const BRI_SUPPLEMENT_ISO_CODES = [
  'AF',
  'AL',
  'AG',
  'AR',
  'AM',
  'AT',
  'AZ',
  'BD',
  'BB',
  'BY',
  'BO',
  'BA',
  'BG',
  'CO',
  'CK',
  'CR',
  'HR',
  'CU',
  'CY',
  'CZ',
  'DM',
  'DO',
  'EC',
  'SV',
  'EE',
  'FJ',
  'GE',
  'GR',
  'GD',
  'GY',
  'HN',
  'HU',
  'IR',
  'IT',
  'JM',
  'KZ',
  'KI',
  'KG',
  'LV',
  'LT',
  'LU',
  'MV',
  'MT',
  'FM',
  'MD',
  'MN',
  'ME',
  'NP',
  'NI',
  'NU',
  'MK',
  'PK',
  'PA',
  'PL',
  'PT',
  'RO',
  'WS',
  'RS',
  'SK',
  'SI',
  'SB',
  'LK',
  'SR',
  'TJ',
  'TO',
  'TT',
  'TR',
  'TM',
  'UA',
  'UY',
  'UZ',
  'VU',
  'VE',
] as const

export const BRI_SUPPLEMENTAL_INTELLECTUAL_PROPERTY_DEPARTMENTS = Object.fromEntries(
  BRI_SUPPLEMENT_ISO_CODES.map((iso) => [
    iso,
    BRI_INTELLECTUAL_PROPERTY_DEPARTMENTS[iso],
  ]),
) as Record<
  (typeof BRI_SUPPLEMENT_ISO_CODES)[number],
  IntellectualPropertyDepartmentsRoster
>
