import type { BriMemberIsoCode } from './participantStatesIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per Belt and Road participant economy (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const BRI_MAIN_INTERNATIONAL_SEAPORTS: Record<BriMemberIsoCode, MainInternationalSeaport> = {
  AF: seaport(
    'Port of Karachi (primary maritime gateway; landlocked)',
    'https://www.kpt.gov.pk/',
    'info@kpt.gov.pk',
    'https://x.com/KarachiPort',
    'https://www.instagram.com/karachiport/',
    'https://www.linkedin.com/company/karachi-port-trust/',
    'customs@customs.gov.af',
    'https://www.customs.gov.af',
    'Afghanistan Customs — Kabul, Afghanistan',
  ),
  AL: seaport(
    'Port of Durrës',
    'https://www.portdurres.com.al/',
    'info@portdurres.com.al',
    'https://x.com/PortDurres',
    'https://www.instagram.com/portdurres/',
    'https://www.linkedin.com/company/port-of-durres/',
    'dogana@dogana.gov.al',
    'https://www.dogana.gov.al',
    'Albanian Customs — Port of Durrës, Durrës, Albania',
  ),
  DZ: seaport(
    'Port of Algiers',
    'https://www.epal.dz/',
    'contact@epal.dz',
    'https://x.com/EPA_Alger',
    'https://www.instagram.com/epa_alger/',
    'https://www.linkedin.com/company/entreprise-portuaire-d-alger/',
    'douane@douane.gov.dz',
    'https://www.douane.gov.dz',
    'Direction Générale des Douanes — Port d\'Alger, Alger, Algeria',
  ),
  AO: seaport(
    'Port of Luanda',
    'https://www.otal.com/angola/port-of-luanda',
    'info@portosdeangola.co.ao',
    'https://x.com/PortosAngola',
    'https://www.instagram.com/portosdeangola/',
    'https://www.linkedin.com/company/portos-de-angola/',
    'aduaneira@minfin.gov.ao',
    'https://www.minfin.gov.ao',
    'Customs Post — Port of Luanda, Luanda, Angola',
  ),
  AG: seaport(
    'Port of St. John\'s',
    'https://www.antiguaport.com/',
    'info@antiguaport.com',
    'https://x.com/AntiguaPort',
    'https://www.instagram.com/antiguaport/',
    'https://www.linkedin.com/company/antigua-port-authority/',
    'customs@antigua.gov.ag',
    'https://www.customs.gov.ag',
    'Antigua and Barbuda Customs — Port of St. John\'s, St. John\'s, Antigua and Barbuda',
  ),
  AR: seaport(
    'Port of Buenos Aires',
    'https://www.argentina.gob.ar/puertos',
    'puertos@argentina.gob.ar',
    'https://x.com/PuertosArgentina',
    'https://www.instagram.com/puertosargentina/',
    'https://www.linkedin.com/company/puertos-argentina/',
    'aduana@afip.gob.ar',
    'https://www.afip.gob.ar',
    'AFIP Aduana — Puerto Buenos Aires, Buenos Aires, Argentina',
  ),
  AM: seaport(
    'Port of Poti (primary maritime gateway; landlocked)',
    'https://www.potiport.com/',
    'info@potiport.com',
    'https://x.com/PotiPort',
    'https://www.instagram.com/potiport/',
    'https://www.linkedin.com/company/poti-port/',
    'customs@customs.am',
    'https://www.customs.am',
    'State Revenue Committee — Yerevan, Armenia',
  ),
  AT: seaport(
    'Port of Koper (primary maritime gateway; landlocked)',
    'https://www.luka-kp.si/',
    'info@luka-kp.si',
    'https://x.com/PortKoper',
    'https://www.instagram.com/portkoper/',
    'https://www.linkedin.com/company/luka-koper/',
    'zoll@bmf.gv.at',
    'https://www.bmf.gv.at',
    'Bundesministerium Finanzen Zoll — Vienna, Austria',
  ),
  AZ: seaport(
    'Port of Baku (Alat)',
    'https://www.portofbaku.com/',
    'info@portofbaku.com',
    'https://x.com/PortofBaku',
    'https://www.instagram.com/portofbaku/',
    'https://www.linkedin.com/company/baku-international-sea-trade-port/',
    'customs@taxes.gov.az',
    'https://www.customs.gov.az',
    'State Customs Committee — Port of Baku, Baku, Azerbaijan',
  ),
  BH: seaport(
    'Khalifa Bin Salman Port (Mina Salman)',
    'https://www.ports.gov.bh/',
    'info@ports.gov.bh',
    'https://x.com/BahrainPorts',
    'https://www.instagram.com/bahrainports/',
    'https://www.linkedin.com/company/ports-maritime-and-aviation-authority/',
    'customs@nca.gov.bh',
    'https://www.nca.gov.bh',
    'National Customs Authority — Mina Salman, Manama, Bahrain',
  ),
  BD: seaport(
    'Port of Chittagong (Chattogram)',
    'https://www.cpa.gov.bd/',
    'info@cpa.gov.bd',
    'https://x.com/CPA_Bangladesh',
    'https://www.instagram.com/cpa_bangladesh/',
    'https://www.linkedin.com/company/chittagong-port-authority/',
    'customs@customs.gov.bd',
    'https://www.customs.gov.bd',
    'National Board of Revenue Customs — Chattogram Port, Chattogram, Bangladesh',
  ),
  BB: seaport(
    'Port of Bridgetown',
    'https://www.barbadosport.com/',
    'info@barbadosport.com',
    'https://x.com/BarbadosPort',
    'https://www.instagram.com/barbadosport/',
    'https://www.linkedin.com/company/barbados-port-inc/',
    'customs@bra.gov.bb',
    'https://www.bra.gov.bb',
    'Barbados Revenue Authority Customs — Port of Bridgetown, Bridgetown, Barbados',
  ),
  BY: seaport(
    'Port of Klaipėda (primary maritime gateway; landlocked)',
    'https://www.portofklaipeda.lt/',
    'info@portofklaipeda.lt',
    'https://x.com/PortKlaipeda',
    'https://www.instagram.com/portklaipeda/',
    'https://www.linkedin.com/company/klaipeda-state-seaport-authority/',
    'customs@gov.by',
    'https://www.customs.gov.by',
    'State Customs Committee — Minsk, Belarus',
  ),
  BJ: seaport(
    'Port of Cotonou',
    'https://www.portdecotonou.com/',
    'contact@portdecotonou.com',
    'https://x.com/PortCotonou',
    'https://www.instagram.com/portcotonou/',
    'https://www.linkedin.com/company/port-autonome-de-cotonou/',
    'douanes@finances.bj',
    'https://www.douanes.bj',
    'Direction Générale des Douanes — Port de Cotonou, Cotonou, Benin',
  ),
  BO: seaport(
    'Port of Arica (primary maritime gateway; landlocked)',
    'https://www.puertoarica.cl/',
    'contacto@puertoarica.cl',
    'https://x.com/PuertoArica',
    'https://www.instagram.com/puertoarica/',
    'https://www.linkedin.com/company/puerto-arica/',
    'aduana@aduana.gob.bo',
    'https://www.aduana.gob.bo',
    'Aduana Nacional — La Paz, Bolivia',
  ),
  BA: seaport(
    'Port of Ploče (primary maritime gateway; landlocked)',
    'https://www.portploce.hr/',
    'info@portploce.hr',
    'https://x.com/PortPloce',
    'https://www.instagram.com/portploce/',
    'https://www.linkedin.com/company/port-of-ploce/',
    'carina@uino.gov.ba',
    'https://www.uino.gov.ba',
    'Indirect Taxation Authority — Sarajevo, Bosnia and Herzegovina',
  ),
  BW: seaport(
    'Port of Walvis Bay (primary maritime gateway; landlocked)',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'info@botswanacustoms.gov.bw',
    'https://www.botswanacustoms.gov.bw',
    'Botswana Unified Revenue Service — Gaborone, Botswana',
  ),
  BN: seaport(
    'Muara Port',
    'https://www.mtc.com.bn/',
    'info@mtc.com.bn',
    'https://x.com/MuaraPort',
    'https://www.instagram.com/muaraport/',
    'https://www.linkedin.com/company/muara-port/',
    'customs@rcs.gov.bn',
    'https://www.rcs.gov.bn',
    'Royal Customs and Excise Department — Muara Port, Muara, Brunei',
  ),
  BG: seaport(
    'Port of Varna',
    'https://www.port-varna.com/',
    'info@port-varna.com',
    'https://x.com/PortVarna',
    'https://www.instagram.com/portvarna/',
    'https://www.linkedin.com/company/port-of-varna/',
    'customs@customs.bg',
    'https://www.customs.bg',
    'Bulgarian Customs — Port of Varna, Varna, Bulgaria',
  ),
  BI: seaport(
    'Port of Bujumbura (Lake Tanganyika)',
    'https://www.obr.bi/',
    'info@obr.bi',
    'https://x.com/OBR_Burundi',
    'https://www.instagram.com/obr_burundi/',
    'https://www.linkedin.com/company/office-burundais-des-recettes/',
    'douanes@obr.bi',
    'https://www.obr.bi',
    'Bureau des Douanes — Port de Bujumbura, Bujumbura, Burundi',
  ),
  CV: seaport(
    'Port of Praia',
    'https://www.enapor.cv/',
    'info@enapor.cv',
    'https://x.com/ENAPOR_CV',
    'https://www.instagram.com/enapor_cv/',
    'https://www.linkedin.com/company/enapor/',
    'aduaneira@mf.gov.cv',
    'https://www.douanascv.gov.cv',
    'Serviço de Alfândegas — Porto da Praia, Praia, Cabo Verde',
  ),
  KH: seaport(
    'Sihanoukville Autonomous Port',
    'https://www.pas.gov.kh/',
    'info@pas.gov.kh',
    'https://x.com/SihanoukvillePort',
    'https://www.instagram.com/sihanoukvilleport/',
    'https://www.linkedin.com/company/sihanoukville-autonomous-port/',
    'info@customs.gov.kh',
    'https://www.customs.gov.kh',
    'General Department of Customs and Excise — Sihanoukville Port, Sihanoukville, Cambodia',
  ),
  CM: seaport(
    'Port of Douala',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.cm',
    'https://www.douanes.cm',
    'Direction Générale des Douanes — Port de Douala, Douala, Cameroon',
  ),
  CF: seaport(
    'Port of Douala (primary maritime gateway; landlocked)',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.cf',
    'https://www.douanes-centrafrique.org',
    'Direction Générale des Douanes — Bangui, Central African Republic',
  ),
  TD: seaport(
    'Port of Douala (primary maritime gateway; landlocked)',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.td',
    'https://www.douanes.td',
    'Direction Générale des Douanes — N\'Djamena, Chad',
  ),
  CL: seaport(
    'Port of San Antonio',
    'https://www.portsanantonio.cl/',
    'contacto@portsanantonio.cl',
    'https://x.com/PortSanAntonioCL',
    'https://www.instagram.com/portsanantonio/',
    'https://www.linkedin.com/company/puerto-san-antonio/',
    'aduana@aduana.cl',
    'https://www.aduana.cl',
    'Servicio Nacional de Aduanas — Puerto San Antonio, San Antonio, Chile',
  ),
  CN: seaport(
    'Port of Shanghai',
    'https://www.portshanghai.com.cn/',
    'info@portshanghai.com.cn',
    'https://x.com/PortShanghai',
    'https://www.instagram.com/portshanghai/',
    'https://www.linkedin.com/company/shanghai-international-port-group/',
    'customs@customs.gov.cn',
    'https://www.customs.gov.cn',
    'General Administration of Customs — Port of Shanghai, Shanghai, China',
  ),
  CO: seaport(
    'Port of Cartagena',
    'https://www.puertocartagena.com/',
    'info@puertocartagena.com',
    'https://x.com/PuertoCartagena',
    'https://www.instagram.com/puertocartagena/',
    'https://www.linkedin.com/company/sociedad-portuaria-regional-de-cartagena/',
    'contacto@dian.gov.co',
    'https://www.dian.gov.co',
    'DIAN Aduanas — Puerto de Cartagena, Cartagena, Colombia',
  ),
  KM: seaport(
    'Port of Moroni',
    'https://www.portcomores.km/',
    'info@portcomores.km',
    'https://x.com/PortComores',
    'https://www.instagram.com/portcomores/',
    'https://www.linkedin.com/company/port-autonome-des-comores/',
    'douanes@finances.km',
    'https://www.douanes.km',
    'Direction des Douanes — Port de Moroni, Moroni, Comoros',
  ),
  CK: seaport(
    'Port of Avatiu (Rarotonga)',
    'https://www.ports.co.ck/',
    'info@ports.co.ck',
    'https://x.com/CookIslandsPorts',
    'https://www.instagram.com/cookislandsports/',
    'https://www.linkedin.com/company/cook-islands-ports-authority/',
    'customs@cookislands.gov.ck',
    'https://www.customs.gov.ck',
    'Cook Islands Customs — Port of Avatiu, Rarotonga, Cook Islands',
  ),
  CR: seaport(
    'Port of Limón (Puerto Limón)',
    'https://www.japdeva.go.cr/',
    'info@japdeva.go.cr',
    'https://x.com/JAPDEVA',
    'https://www.instagram.com/japdeva/',
    'https://www.linkedin.com/company/japdeva/',
    'aduana@hacienda.go.cr',
    'https://www.hacienda.go.cr',
    'Servicio Nacional de Aduanas — Puerto Limón, Limón, Costa Rica',
  ),
  CI: seaport(
    'Port of Abidjan',
    'https://www.portabidjan.com/',
    'contact@portabidjan.com',
    'https://x.com/PortAbidjan',
    'https://www.instagram.com/portabidjan/',
    'https://www.linkedin.com/company/port-autonome-d-abidjan/',
    'douanes@dgi.gouv.ci',
    'https://www.douanes.ci',
    'Direction Générale des Douanes — Port d\'Abidjan, Abidjan, Côte d\'Ivoire',
  ),
  HR: seaport(
    'Port of Rijeka',
    'https://www.lukarijeka.hr/',
    'info@lukarijeka.hr',
    'https://x.com/PortRijeka',
    'https://www.instagram.com/portrijeka/',
    'https://www.linkedin.com/company/port-of-rijeka-authority/',
    'carina@carina.hr',
    'https://www.carina.hr',
    'Croatian Customs — Port of Rijeka, Rijeka, Croatia',
  ),
  CU: seaport(
    'Port of Mariel',
    'https://www.zedmariel.cu/',
    'info@zedmariel.cu',
    'https://x.com/ZonaMariel',
    'https://www.instagram.com/zonamariel/',
    'https://www.linkedin.com/company/zona-especial-mariel/',
    'aduana@aduana.gob.cu',
    'https://www.aduana.gob.cu',
    'Aduana General de la República — Puerto Mariel, Mariel, Cuba',
  ),
  CY: seaport(
    'Port of Limassol',
    'https://www.cyprusports.gov.cy/',
    'info@cyprusports.gov.cy',
    'https://x.com/CyprusPorts',
    'https://www.instagram.com/cyprusports/',
    'https://www.linkedin.com/company/cyprus-ports-authority/',
    'customs@mof.gov.cy',
    'https://www.mof.gov.cy/customs',
    'Cyprus Customs — Port of Limassol, Limassol, Cyprus',
  ),
  CZ: seaport(
    'Port of Hamburg (primary maritime gateway; landlocked)',
    'https://www.hafen-hamburg.de/',
    'info@hafen-hamburg.de',
    'https://x.com/hafenhamburg',
    'https://www.instagram.com/hafenhamburg/',
    'https://www.linkedin.com/company/hamburg-port-authority/',
    'celni@cs.mfcr.cz',
    'https://www.celnisprava.cz',
    'Czech Customs Administration — Prague, Czech Republic',
  ),
  CD: seaport(
    'Port of Matadi',
    'https://www.opdrdc.cd/',
    'contact@opdrdc.cd',
    'https://x.com/OPDRDC',
    'https://www.instagram.com/opdrdc/',
    'https://www.linkedin.com/company/office-des-ports-et-voies-fluviales-rdc/',
    'douanes@dgda.cd',
    'https://www.douanesrdc.cd',
    'Direction Générale des Douanes et Accises — Port de Matadi, Matadi, DRC',
  ),
  DJ: seaport(
    'Port of Djibouti',
    'https://www.portdedjibouti.com/',
    'contact@portdedjibouti.com',
    'https://x.com/PortDjibouti',
    'https://www.instagram.com/portdedjibouti/',
    'https://www.linkedin.com/company/port-de-djibouti/',
    'douanes@douanes.dj',
    'https://www.douanes.dj',
    'Direction Générale des Douanes — Port de Djibouti, Djibouti City, Djibouti',
  ),
  DM: seaport(
    'Port of Roseau',
    'https://www.dominicaports.dm/',
    'info@dominicaports.dm',
    'https://x.com/DominicaPorts',
    'https://www.instagram.com/dominicaport/',
    'https://www.linkedin.com/company/dominica-ports-authority/',
    'customs@customs.gov.dm',
    'https://www.customs.gov.dm',
    'Dominica Customs — Port of Roseau, Roseau, Dominica',
  ),
  DO: seaport(
    'Port of Caucedo',
    'https://www.dpworld.com/dominican-republic',
    'info@dpworld.com',
    'https://x.com/DP_World',
    'https://www.instagram.com/dpworld/',
    'https://www.linkedin.com/company/dp-world/',
    'aduana@dgii.gov.do',
    'https://www.dgii.gov.do',
    'DGA Aduanas — Puerto Caucedo, Santo Domingo, Dominican Republic',
  ),
  EC: seaport(
    'Port of Guayaquil',
    'https://www.puertodeguayaquil.com/',
    'info@puertodeguayaquil.com',
    'https://x.com/PuertoGuayaquil',
    'https://www.instagram.com/puertoguayaquil/',
    'https://www.linkedin.com/company/autoridad-portuaria-de-guayaquil/',
    'aduana@aduana.gob.ec',
    'https://www.aduana.gob.ec',
    'Servicio Nacional de Aduanas — Puerto de Guayaquil, Guayaquil, Ecuador',
  ),
  EG: seaport(
    'Port of Alexandria',
    'https://www.alexandria-port.com/',
    'info@alexandria-port.com',
    'https://x.com/AlexPortEgypt',
    'https://www.instagram.com/alexportegypt/',
    'https://www.linkedin.com/company/alexandria-port-authority/',
    'customs@customs.gov.eg',
    'https://www.customs.gov.eg',
    'Egyptian Customs Authority — Port of Alexandria, Alexandria, Egypt',
  ),
  SV: seaport(
    'Port of Acajutla',
    'https://www.portacajutla.gob.sv/',
    'info@portacajutla.gob.sv',
    'https://x.com/PortAcajutla',
    'https://www.instagram.com/portacajutla/',
    'https://www.linkedin.com/company/autoridad-portuaria-acajutla/',
    'aduana@aduana.gob.sv',
    'https://www.aduana.gob.sv',
    'Dirección General de Aduanas — Puerto Acajutla, Acajutla, El Salvador',
  ),
  GQ: seaport(
    'Port of Bata',
    'https://www.otal.com/equatorial-guinea/port-of-bata',
    'contact@portbata.gq',
    'https://x.com/PortBata',
    'https://www.instagram.com/portbata/',
    'https://www.linkedin.com/company/port-of-bata/',
    'aduana@guineaecuatorial.gq',
    'https://www.aduana.gq',
    'Aduana de Guinea Ecuatorial — Puerto de Bata, Bata, Equatorial Guinea',
  ),
  ER: seaport(
    'Port of Massawa',
    'https://www.shabait.com/',
    'info@shabait.com',
    'https://x.com/shabait',
    'https://www.instagram.com/shabait/',
    'https://www.linkedin.com/company/eritrean-ports/',
    'customs@shabait.com',
    'https://www.shabait.com',
    'Eritrean Customs — Port of Massawa, Massawa, Eritrea',
  ),
  EE: seaport(
    'Port of Muuga (Tallinn)',
    'https://www.portoftallinn.com/',
    'info@portoftallinn.com',
    'https://x.com/PortofTallinn',
    'https://www.instagram.com/portoftallinn/',
    'https://www.linkedin.com/company/port-of-tallinn/',
    'info@toll.ee',
    'https://www.emta.ee',
    'Estonian Tax and Customs Board — Port of Muuga, Tallinn, Estonia',
  ),
  ET: seaport(
    'Port of Djibouti (primary maritime gateway; landlocked)',
    'https://www.portdedjibouti.com/',
    'contact@portdedjibouti.com',
    'https://x.com/PortDjibouti',
    'https://www.instagram.com/portdedjibouti/',
    'https://www.linkedin.com/company/port-de-djibouti/',
    'info@erca.gov.et',
    'https://www.erca.gov.et',
    'Ethiopian Customs Commission — Modjo Dry Port, Modjo, Ethiopia',
  ),
  FJ: seaport(
    'Port of Suva',
    'https://www.fijiports.com.fj/',
    'info@fijiports.com.fj',
    'https://x.com/FijiPorts',
    'https://www.instagram.com/fijiports/',
    'https://www.linkedin.com/company/fiji-ports-corporation/',
    'customs@fiji.gov.fj',
    'https://www.frcs.org.fj',
    'FRCS Customs — Port of Suva, Suva, Fiji',
  ),
  GA: seaport(
    'Port of Owendo',
    'https://www.otal.com/gabon/port-of-owendo',
    'contact@port-gentil.ga',
    'https://x.com/PortOwendo',
    'https://www.instagram.com/portowendo/',
    'https://www.linkedin.com/company/port-d-owendo/',
    'douanes@finances.ga',
    'https://www.douanes.ga',
    'Direction Générale des Douanes — Port d\'Owendo, Owendo, Gabon',
  ),
  GM: seaport(
    'Port of Banjul',
    'https://www.gambiaports.gm/',
    'info@gambiaports.gm',
    'https://x.com/GambiaPorts',
    'https://www.instagram.com/gambiaports/',
    'https://www.linkedin.com/company/gambia-ports-authority/',
    'info@gra.gm',
    'https://www.gra.gm',
    'Gambia Revenue Authority — Customs, Port of Banjul, Banjul, The Gambia',
  ),
  GE: seaport(
    'Port of Poti',
    'https://www.potiport.com/',
    'info@potiport.com',
    'https://x.com/PotiPort',
    'https://www.instagram.com/potiport/',
    'https://www.linkedin.com/company/poti-port/',
    'customs@customs.gov.ge',
    'https://www.customs.gov.ge',
    'Revenue Service of Georgia — Port of Poti, Poti, Georgia',
  ),
  GH: seaport(
    'Port of Tema',
    'https://www.ghanaports.gov.gh/',
    'info@ghanaports.gov.gh',
    'https://x.com/GhanaPorts',
    'https://www.instagram.com/ghanaports/',
    'https://www.linkedin.com/company/ghana-ports-and-harbours-authority/',
    'info@gra.gov.gh',
    'https://www.gra.gov.gh',
    'Ghana Revenue Authority — Customs Division, Port of Tema, Tema, Ghana',
  ),
  GR: seaport(
    'Port of Piraeus',
    'https://www.olp.gr/',
    'info@olp.gr',
    'https://x.com/PiraeusPort',
    'https://www.instagram.com/piraeusport/',
    'https://www.linkedin.com/company/piraeus-port-authority/',
    'info@aade.gr',
    'https://www.aade.gr',
    'Independent Authority for Public Revenue — Port of Piraeus, Piraeus, Greece',
  ),
  GD: seaport(
    'Port of St. George\'s',
    'https://www.grenadaports.com/',
    'info@grenadaports.com',
    'https://x.com/GrenadaPorts',
    'https://www.instagram.com/grenadaports/',
    'https://www.linkedin.com/company/grenada-ports-authority/',
    'customs@customs.gov.gd',
    'https://www.customs.gov.gd',
    'Grenada Customs — Port of St. George\'s, St. George\'s, Grenada',
  ),
  GN: seaport(
    'Port of Conakry',
    'https://www.otal.com/guinea/port-of-conakry',
    'contact@portconakry.gn',
    'https://x.com/PortConakry',
    'https://www.instagram.com/portconakry/',
    'https://www.linkedin.com/company/port-autonome-de-conakry/',
    'douanes@finances.gov.gn',
    'https://www.douanes.gov.gn',
    'Direction Générale des Douanes — Port de Conakry, Conakry, Guinea',
  ),
  GW: seaport(
    'Port of Bissau',
    'https://www.portobissau.gw/',
    'info@portobissau.gw',
    'https://x.com/PortBissau',
    'https://www.instagram.com/portbissau/',
    'https://www.linkedin.com/company/porto-de-bissau/',
    'aduaneira@mf.gov.gw',
    'https://www.aduaneira.gov.gw',
    'Alfândega Nacional — Porto de Bissau, Bissau, Guinea-Bissau',
  ),
  GY: seaport(
    'Port of Georgetown',
    'https://www.guyanaports.com/',
    'info@guyanaports.com',
    'https://x.com/GuyanaPorts',
    'https://www.instagram.com/guyanaports/',
    'https://www.linkedin.com/company/guyana-ports-inc/',
    'customs@gra.gov.gy',
    'https://www.gra.gov.gy',
    'Guyana Revenue Authority Customs — Port of Georgetown, Georgetown, Guyana',
  ),
  HN: seaport(
    'Port of Puerto Cortés',
    'https://www.enp.hn/',
    'info@enp.hn',
    'https://x.com/ENP_Honduras',
    'https://www.instagram.com/enp_honduras/',
    'https://www.linkedin.com/company/empresa-nacional-portuaria/',
    'aduana@aduana.gob.hn',
    'https://www.aduana.gob.hn',
    'Administración Aduanera — Puerto Cortés, Puerto Cortés, Honduras',
  ),
  HU: seaport(
    'Port of Rijeka (primary maritime gateway; landlocked)',
    'https://www.lukarijeka.hr/',
    'info@lukarijeka.hr',
    'https://x.com/PortRijeka',
    'https://www.instagram.com/portrijeka/',
    'https://www.linkedin.com/company/port-of-rijeka-authority/',
    'vaminfo@nav.gov.hu',
    'https://nav.gov.hu',
    'National Tax and Customs Administration — Budapest, Hungary',
  ),
  ID: seaport(
    'Port of Tanjung Priok (Jakarta)',
    'https://www.pelindo.co.id/',
    'info@pelindo.co.id',
    'https://x.com/Pelindo',
    'https://www.instagram.com/pelindo/',
    'https://www.linkedin.com/company/pelindo/',
    'contact.center@beacukai.go.id',
    'https://www.beacukai.go.id',
    'Direktorat Jenderal Bea dan Cukai — Pelabuhan Tanjung Priok, Jakarta, Indonesia',
  ),
  IR: seaport(
    'Port of Bandar Abbas (Shahid Rajaee)',
    'https://www.pmo.ir/',
    'info@pmo.ir',
    'https://x.com/PortsMaritimeIR',
    'https://www.instagram.com/pmo_ir/',
    'https://www.linkedin.com/company/ports-and-maritime-organization/',
    'customs@irica.gov.ir',
    'https://www.irica.gov.ir',
    'Iran Customs — Shahid Rajaee Port, Bandar Abbas, Iran',
  ),
  IQ: seaport(
    'Umm Qasr Port',
    'https://www.scop.gov.iq/',
    'info@scop.gov.iq',
    'https://x.com/IraqPorts',
    'https://www.instagram.com/iraqports/',
    'https://www.linkedin.com/company/state-company-of-ports-iraq/',
    'customs@customs.gov.iq',
    'https://www.customs.gov.iq',
    'Iraqi Customs — Umm Qasr Port, Basra Governorate, Iraq',
  ),
  IT: seaport(
    'Port of Genoa',
    'https://www.portsofgenoa.com/',
    'info@portsofgenoa.com',
    'https://x.com/PortofGenoa',
    'https://www.instagram.com/portofgenoa/',
    'https://www.linkedin.com/company/western-ligurian-sea-port-authority/',
    'dogane@dogane.gov.it',
    'https://www.adm.gov.it',
    'Agenzia delle Dogane — Porto di Genova, Genoa, Italy',
  ),
  JM: seaport(
    'Port of Kingston',
    'https://www.portjam.com/',
    'info@portjam.com',
    'https://x.com/PortAuthorityJM',
    'https://www.instagram.com/portauthorityjm/',
    'https://www.linkedin.com/company/port-authority-of-jamaica/',
    'customs@jacustoms.gov.jm',
    'https://www.jacustoms.gov.jm',
    'Jamaica Customs Agency — Port of Kingston, Kingston, Jamaica',
  ),
  JO: seaport(
    'Port of Aqaba',
    'https://www.aqabaport.com.jo/',
    'info@aqabaport.com.jo',
    'https://x.com/AqabaPort',
    'https://www.instagram.com/aqabaport/',
    'https://www.linkedin.com/company/aqaba-port-marine-services/',
    'customs@customs.gov.jo',
    'https://www.customs.gov.jo',
    'Jordan Customs — Port of Aqaba, Aqaba, Jordan',
  ),
  KZ: seaport(
    'Port of Aktau',
    'https://www.seaportaktau.kz/',
    'info@seaportaktau.kz',
    'https://x.com/AktauPort',
    'https://www.instagram.com/aktauport/',
    'https://www.linkedin.com/company/aktau-seaport/',
    'customs@kgd.gov.kz',
    'https://www.gov.kz/memleket/entities/kgd',
    'Committee of State Revenue — Port of Aktau, Aktau, Kazakhstan',
  ),
  KE: seaport(
    'Port of Mombasa',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@kra.go.ke',
    'https://www.kra.go.ke',
    'Kenya Revenue Authority — Customs Services, Port of Mombasa, Mombasa, Kenya',
  ),
  KI: seaport(
    'Port of Betio (Tarawa)',
    'https://www.mic.gov.ki/',
    'info@mic.gov.ki',
    'https://x.com/KiribatiPorts',
    'https://www.instagram.com/kiribatiports/',
    'https://www.linkedin.com/company/kiribati-ports/',
    'customs@mfed.gov.ki',
    'https://www.mfed.gov.ki',
    'Kiribati Customs — Port of Betio, Tarawa, Kiribati',
  ),
  KW: seaport(
    'Shuwaikh Port',
    'https://www.pak.gov.kw/',
    'info@pak.gov.kw',
    'https://x.com/KuwaitPorts',
    'https://www.instagram.com/kuwaitports/',
    'https://www.linkedin.com/company/ports-authority-kuwait/',
    'customs@customs.gov.kw',
    'https://www.customs.gov.kw',
    'Kuwait General Administration of Customs — Shuwaikh Port, Kuwait City, Kuwait',
  ),
  KG: seaport(
    'Port of Bandar Abbas (primary maritime gateway; landlocked)',
    'https://www.pmo.ir/',
    'info@pmo.ir',
    'https://x.com/PortsMaritimeIR',
    'https://www.instagram.com/pmo_ir/',
    'https://www.linkedin.com/company/ports-and-maritime-organization/',
    'customs@customs.gov.kg',
    'https://www.customs.gov.kg',
    'State Customs Service — Bishkek, Kyrgyzstan',
  ),
  LA: seaport(
    'Port of Laem Chabang (primary maritime gateway; landlocked)',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'customs@customs.gov.la',
    'https://www.customs.gov.la',
    'Department of Customs — Vientiane, Laos',
  ),
  LV: seaport(
    'Port of Riga',
    'https://www.rop.lv/',
    'info@rop.lv',
    'https://x.com/FreeportRiga',
    'https://www.instagram.com/freeportriga/',
    'https://www.linkedin.com/company/freeport-of-riga/',
    'info@vid.gov.lv',
    'https://www.vid.gov.lv',
    'State Revenue Service — Port of Riga, Riga, Latvia',
  ),
  LB: seaport(
    'Port of Beirut',
    'https://www.portdebeyrouth.com/',
    'info@portdebeyrouth.com',
    'https://x.com/PortBeirut',
    'https://www.instagram.com/portbeirut/',
    'https://www.linkedin.com/company/port-of-beirut/',
    'customs@customs.gov.lb',
    'https://www.customs.gov.lb',
    'Lebanese Customs — Port of Beirut, Beirut, Lebanon',
  ),
  LS: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@lra.org.ls',
    'https://www.lra.org.ls',
    'Lesotho Revenue Authority — Customs Division, Maseru, Lesotho',
  ),
  LR: seaport(
    'Freeport of Monrovia',
    'https://www.npaliberia.com/',
    'info@npaliberia.com',
    'https://x.com/NPA_Liberia',
    'https://www.instagram.com/npa_liberia/',
    'https://www.linkedin.com/company/national-port-authority-liberia/',
    'customs@lra.gov.lr',
    'https://www.lra.gov.lr',
    'Liberia Revenue Authority — Customs, Freeport of Monrovia, Monrovia, Liberia',
  ),
  LY: seaport(
    'Port of Tripoli',
    'https://www.lpc.ly/',
    'info@lpc.ly',
    'https://x.com/LibyanPorts',
    'https://www.instagram.com/libyanports/',
    'https://www.linkedin.com/company/libyan-ports-corporation/',
    'customs@customs.gov.ly',
    'https://www.customs.gov.ly',
    'Libyan Customs Authority — Port of Tripoli, Tripoli, Libya',
  ),
  LT: seaport(
    'Port of Klaipėda',
    'https://www.portofklaipeda.lt/',
    'info@portofklaipeda.lt',
    'https://x.com/PortKlaipeda',
    'https://www.instagram.com/portklaipeda/',
    'https://www.linkedin.com/company/klaipeda-state-seaport-authority/',
    'muitine@muitine.lt',
    'https://www.lrmuitine.lt',
    'Lithuanian Customs — Port of Klaipėda, Klaipėda, Lithuania',
  ),
  LU: seaport(
    'Port of Antwerp-Bruges (primary maritime gateway; landlocked)',
    'https://www.portofantwerpbruges.com/',
    'info@portofantwerpbruges.com',
    'https://x.com/PortofAntwerp',
    'https://www.instagram.com/portofantwerpbruges/',
    'https://www.linkedin.com/company/port-of-antwerp-bruges/',
    'douanes@do.etat.lu',
    'https://www.do.etat.lu',
    'Administration des Douanes — Luxembourg City, Luxembourg',
  ),
  MG: seaport(
    'Port of Toamasina',
    'https://www.otal.com/madagascar/port-of-toamasina',
    'contact@port-toamasina.mg',
    'https://x.com/PortToamasina',
    'https://www.instagram.com/porttoamasina/',
    'https://www.linkedin.com/company/port-de-toamasina/',
    'douanes@douanes.gov.mg',
    'https://www.douanes.gov.mg',
    'Direction Générale des Douanes — Port de Toamasina, Toamasina, Madagascar',
  ),
  MW: seaport(
    'Port of Nacala (primary maritime gateway; landlocked)',
    'https://www.otal.com/mozambique/port-of-nacala',
    'info@cdi.mw',
    'https://x.com/CDI_Malawi',
    'https://www.instagram.com/cdi_malawi/',
    'https://www.linkedin.com/company/corridor-development-initiative/',
    'customs@mra.mw',
    'https://www.mra.mw',
    'Malawi Revenue Authority — Customs Division, Blantyre, Malawi',
  ),
  MY: seaport(
    'Port Klang',
    'https://www.pka.gov.my/',
    'info@pka.gov.my',
    'https://x.com/PortKlang',
    'https://www.instagram.com/portklang/',
    'https://www.linkedin.com/company/port-klang-authority/',
    'customs@customs.gov.my',
    'https://www.customs.gov.my',
    'Royal Malaysian Customs — Port Klang, Selangor, Malaysia',
  ),
  MV: seaport(
    'Port of Malé',
    'https://www.mpa.gov.mv/',
    'info@mpa.gov.mv',
    'https://x.com/MPA_Maldives',
    'https://www.instagram.com/mpa_maldives/',
    'https://www.linkedin.com/company/maldives-ports-limited/',
    'customs@customs.gov.mv',
    'https://www.customs.gov.mv',
    'Maldives Customs Service — Port of Malé, Malé, Maldives',
  ),
  ML: seaport(
    'Port of Dakar (primary maritime gateway; landlocked)',
    'https://www.portdedakar.sn/',
    'contact@portdedakar.sn',
    'https://x.com/PortDakar',
    'https://www.instagram.com/portdedakar/',
    'https://www.linkedin.com/company/port-autonome-de-dakar/',
    'douanes@finances.ml',
    'https://www.douanes.ml',
    'Direction Générale des Douanes — Bamako, Mali',
  ),
  MT: seaport(
    'Port of Marsaxlokk (Malta Freeport)',
    'https://www.maltafreeport.com/',
    'info@maltafreeport.com',
    'https://x.com/MaltaFreeport',
    'https://www.instagram.com/maltafreeport/',
    'https://www.linkedin.com/company/malta-freeport/',
    'customs@gov.mt',
    'https://cfr.gov.mt',
    'Malta Customs — Malta Freeport, Marsaxlokk, Malta',
  ),
  MR: seaport(
    'Port of Nouadhibou',
    'https://www.otal.com/mauritania/port-of-nouadhibou',
    'contact@portnouadhibou.mr',
    'https://x.com/PortNouadhibou',
    'https://www.instagram.com/portnouadhibou/',
    'https://www.linkedin.com/company/port-de-nouadhibou/',
    'douanes@finances.gov.mr',
    'https://www.douanes.gov.mr',
    'Direction Générale des Douanes — Port de Nouadhibou, Nouadhibou, Mauritania',
  ),
  FM: seaport(
    'Port of Micronesia (Pohnpei)',
    'https://www.fsmgov.org/',
    'info@fsmgov.org',
    '',
    '',
    'https://www.linkedin.com/company/federated-states-of-micronesia/',
    'customs@fsmgov.org',
    'https://www.fsmgov.org',
    'FSM Customs — Kolonia, Pohnpei, Micronesia',
  ),
  MD: seaport(
    'Port of Giurgiulești',
    'https://www.portgiurgiulesti.md/',
    'info@portgiurgiulesti.md',
    'https://x.com/PortGiurgiulesti',
    'https://www.instagram.com/portgiurgiulesti/',
    'https://www.linkedin.com/company/port-giurgiulesti/',
    'customs@customs.gov.md',
    'https://www.customs.gov.md',
    'Customs Service — Port of Giurgiulești, Giurgiulești, Moldova',
  ),
  MN: seaport(
    'Port of Tianjin (primary maritime gateway; landlocked)',
    'https://www.ptacn.com/',
    'info@ptacn.com',
    'https://x.com/TianjinPort',
    'https://www.instagram.com/tianjinport/',
    'https://www.linkedin.com/company/tianjin-port/',
    'customs@customs.gov.mn',
    'https://www.customs.gov.mn',
    'Mongolian Customs — Ulaanbaatar, Mongolia',
  ),
  ME: seaport(
    'Port of Bar',
    'https://www.portofbar.me/',
    'info@portofbar.me',
    'https://x.com/PortofBar',
    'https://www.instagram.com/portofbar/',
    'https://www.linkedin.com/company/port-of-bar/',
    'carina@uino.gov.me',
    'https://www.gov.me/en/customs',
    'Customs Administration — Port of Bar, Bar, Montenegro',
  ),
  MA: seaport(
    'Port of Tanger Med',
    'https://www.tangermed.ma/',
    'contact@tangermed.ma',
    'https://x.com/TangerMed',
    'https://www.instagram.com/tangermed/',
    'https://www.linkedin.com/company/tanger-med/',
    'douane@douane.gov.ma',
    'https://www.douane.gov.ma',
    'Administration des Douanes — Tanger Med, Tanger, Morocco',
  ),
  MZ: seaport(
    'Port of Maputo',
    'https://www.portmaputo.com/',
    'info@portmaputo.com',
    'https://x.com/PortMaputo',
    'https://www.instagram.com/portmaputo/',
    'https://www.linkedin.com/company/porto-de-maputo/',
    'aduaneira@at.gov.mz',
    'https://www.at.gov.mz',
    'Autoridade Tributária de Moçambique — Alfândega do Porto de Maputo, Maputo, Mozambique',
  ),
  MM: seaport(
    'Thilawa Port (Yangon)',
    'https://www.mip.com.mm/',
    'info@mip.com.mm',
    'https://x.com/ThilawaPort',
    'https://www.instagram.com/thilawaport/',
    'https://www.linkedin.com/company/thilawa-port/',
    'info@customs.gov.mm',
    'https://www.customs.gov.mm',
    'Myanmar Customs Department — Thilawa Port, Yangon, Myanmar',
  ),
  NA: seaport(
    'Port of Walvis Bay',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'customs@namra.org.na',
    'https://www.namra.org.na',
    'Namibia Revenue Agency — Customs, Port of Walvis Bay, Walvis Bay, Namibia',
  ),
  NP: seaport(
    'Port of Kolkata (primary maritime gateway; landlocked)',
    'https://www.kolkataport.gov.in/',
    'info@kolkataport.gov.in',
    'https://x.com/KolkataPort',
    'https://www.instagram.com/kolkata_port/',
    'https://www.linkedin.com/company/kolkata-port-trust/',
    'customs@customs.gov.np',
    'https://www.customs.gov.np',
    'Department of Customs — Kathmandu, Nepal',
  ),
  NZ: seaport(
    'Port of Tauranga',
    'https://www.port-tauranga.co.nz/',
    'info@port-tauranga.co.nz',
    'https://x.com/PortofTauranga',
    'https://www.instagram.com/portoftauranga/',
    'https://www.linkedin.com/company/port-of-tauranga/',
    'customs@customs.govt.nz',
    'https://www.customs.govt.nz',
    'New Zealand Customs Service — Port of Tauranga, Tauranga, New Zealand',
  ),
  NI: seaport(
    'Port of Corinto',
    'https://www.epn.com.ni/',
    'info@epn.com.ni',
    'https://x.com/EPN_Nicaragua',
    'https://www.instagram.com/epn_nicaragua/',
    'https://www.linkedin.com/company/empresa-portuaria-nacional/',
    'aduana@dga.gob.ni',
    'https://www.dga.gob.ni',
    'DGA Aduanas — Puerto Corinto, Corinto, Nicaragua',
  ),
  NE: seaport(
    'Port of Cotonou (primary maritime gateway; landlocked)',
    'https://www.portdecotonou.com/',
    'contact@portdecotonou.com',
    'https://x.com/PortCotonou',
    'https://www.instagram.com/portcotonou/',
    'https://www.linkedin.com/company/port-autonome-de-cotonou/',
    'douanes@finances.ne',
    'https://www.douanes.ne',
    'Direction Générale des Douanes — Niamey, Niger',
  ),
  NG: seaport(
    'Port of Lagos (Apapa)',
    'https://www.npa.gov.ng/',
    'info@npa.gov.ng',
    'https://x.com/NPA_Nigeria',
    'https://www.instagram.com/npa_nigeria/',
    'https://www.linkedin.com/company/nigerian-ports-authority/',
    'customs@customs.gov.ng',
    'https://www.customs.gov.ng',
    'Nigeria Customs Service — Apapa Port, Lagos, Nigeria',
  ),
  NU: seaport(
    'Port of Alofi',
    'https://www.niueports.nu/',
    'info@niueports.nu',
    '',
    '',
    'https://www.linkedin.com/company/niue-ports/',
    'customs@niue.gov.nu',
    'https://www.niue.gov.nu',
    'Niue Customs — Port of Alofi, Alofi, Niue',
  ),
  MK: seaport(
    'Port of Thessaloniki (primary maritime gateway; landlocked)',
    'https://www.thpa.gr/',
    'info@thpa.gr',
    'https://x.com/ThessalonikiPort',
    'https://www.instagram.com/thessalonikiport/',
    'https://www.linkedin.com/company/thessaloniki-port-authority/',
    'customs@customs.gov.mk',
    'https://www.customs.gov.mk',
    'Customs Administration — Skopje, North Macedonia',
  ),
  OM: seaport(
    'Port of Salalah',
    'https://www.salalahport.com/',
    'info@salalahport.com',
    'https://x.com/SalalahPort',
    'https://www.instagram.com/salalahport/',
    'https://www.linkedin.com/company/port-of-salalah/',
    'customs@customs.gov.om',
    'https://www.customs.gov.om',
    'Royal Oman Police Customs — Port of Salalah, Salalah, Oman',
  ),
  PK: seaport(
    'Port of Karachi',
    'https://www.kpt.gov.pk/',
    'info@kpt.gov.pk',
    'https://x.com/KarachiPort',
    'https://www.instagram.com/karachiport/',
    'https://www.linkedin.com/company/karachi-port-trust/',
    'customs@customs.gov.pk',
    'https://www.fbr.gov.pk',
    'Pakistan Customs — Port of Karachi, Karachi, Pakistan',
  ),
  PA: seaport(
    'Port of Balboa (Panama Canal)',
    'https://www.pancanal.com/',
    'info@pancanal.com',
    'https://x.com/thepanamacanal',
    'https://www.instagram.com/panamacanal/',
    'https://www.linkedin.com/company/panama-canal-authority/',
    'aduana@ana.gob.pa',
    'https://www.ana.gob.pa',
    'National Customs Authority — Port of Balboa, Panama City, Panama',
  ),
  PG: seaport(
    'Port of Lae',
    'https://www.pngports.com.pg/',
    'info@pngports.com.pg',
    'https://x.com/PNGPorts',
    'https://www.instagram.com/pngports/',
    'https://www.linkedin.com/company/png-ports-corporation/',
    'customs@irc.gov.pg',
    'https://www.irc.gov.pg',
    'PNG Customs — Port of Lae, Lae, Papua New Guinea',
  ),
  PE: seaport(
    'Port of Callao',
    'https://www.enapu.com.pe/',
    'info@enapu.com.pe',
    'https://x.com/ENAPU_Peru',
    'https://www.instagram.com/enapu_peru/',
    'https://www.linkedin.com/company/enapu/',
    'consultas@sunat.gob.pe',
    'https://www.sunat.gob.pe',
    'SUNAT Aduanas — Puerto del Callao, Callao, Peru',
  ),
  PH: seaport(
    'Port of Manila (South Harbor)',
    'https://www.ppa.com.ph/',
    'info@ppa.com.ph',
    'https://x.com/PPA_Official',
    'https://www.instagram.com/ppa_official/',
    'https://www.linkedin.com/company/philippine-ports-authority/',
    'customs@customs.gov.ph',
    'https://www.customs.gov.ph',
    'Bureau of Customs — Port of Manila, Manila, Philippines',
  ),
  PL: seaport(
    'Port of Gdańsk',
    'https://www.portgdansk.pl/',
    'info@portgdansk.pl',
    'https://x.com/PortGdansk',
    'https://www.instagram.com/portgdansk/',
    'https://www.linkedin.com/company/port-of-gdansk/',
    'info@mf.gov.pl',
    'https://www.gov.pl/web/kas',
    'National Revenue Administration — Port of Gdańsk, Gdańsk, Poland',
  ),
  PT: seaport(
    'Port of Sines',
    'https://www.portodesines.pt/',
    'info@portodesines.pt',
    'https://x.com/PortodeSines',
    'https://www.instagram.com/portodesines/',
    'https://www.linkedin.com/company/porto-de-sines/',
    'aduaneira@at.gov.pt',
    'https://www.portaldasfinancas.gov.pt',
    'Autoridade Tributária — Port of Sines, Sines, Portugal',
  ),
  QA: seaport(
    'Hamad Port',
    'https://www.mwani.com.qa/',
    'info@mwani.com.qa',
    'https://x.com/MwaniQatar',
    'https://www.instagram.com/mwaniqatar/',
    'https://www.linkedin.com/company/mwani-qatar/',
    'customs@gac.gov.qa',
    'https://www.customs.gov.qa',
    'General Authority of Customs — Hamad Port, Doha, Qatar',
  ),
  CG: seaport(
    'Port of Pointe-Noire',
    'https://www.otal.com/congo/port-of-pointe-noire',
    'contact@port-noire.cg',
    'https://x.com/PortPointeNoire',
    'https://www.instagram.com/portpointenoire/',
    'https://www.linkedin.com/company/port-autonome-de-pointe-noire/',
    'douanes@finances.cg',
    'https://www.douanes.cg',
    'Direction Générale des Douanes — Port de Pointe-Noire, Pointe-Noire, Republic of the Congo',
  ),
  RO: seaport(
    'Port of Constanța',
    'https://www.portofconstantza.com/',
    'info@portofconstantza.com',
    'https://x.com/PortConstanta',
    'https://www.instagram.com/portofconstantza/',
    'https://www.linkedin.com/company/maritime-ports-administration-constantza/',
    'customs@customs.ro',
    'https://www.customs.ro',
    'Romanian Customs — Port of Constanța, Constanța, Romania',
  ),
  RU: seaport(
    'Port of Vladivostok',
    'https://www.vmtp.ru/',
    'info@vmtp.ru',
    'https://x.com/VladivostokPort',
    'https://www.instagram.com/vladivostokport/',
    'https://www.linkedin.com/company/vladivostok-sea-port/',
    'customs@fts.customs.ru',
    'https://www.customs.ru',
    'Far Eastern Customs — Port of Vladivostok, Vladivostok, Russia',
  ),
  RW: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@rra.gov.rw',
    'https://www.rra.gov.rw',
    'Rwanda Revenue Authority — Customs Services, Kigali, Rwanda',
  ),
  WS: seaport(
    'Port of Apia',
    'https://www.samoaports.ws/',
    'info@samoaports.ws',
    'https://x.com/SamoaPorts',
    'https://www.instagram.com/samoaports/',
    'https://www.linkedin.com/company/samoa-ports-authority/',
    'customs@revenue.gov.ws',
    'https://www.revenue.gov.ws',
    'Samoa Revenue Authority Customs — Port of Apia, Apia, Samoa',
  ),
  SA: seaport(
    'King Abdullah Port',
    'https://www.ka-port.com.sa/',
    'info@ka-port.com.sa',
    'https://x.com/KingAbdullahPort',
    'https://www.instagram.com/kingabdullahport/',
    'https://www.linkedin.com/company/king-abdullah-port/',
    'customs@zatca.gov.sa',
    'https://www.zatca.gov.sa',
    'ZATCA Customs — King Abdullah Port, Rabigh, Saudi Arabia',
  ),
  SN: seaport(
    'Port of Dakar',
    'https://www.portdedakar.sn/',
    'contact@portdedakar.sn',
    'https://x.com/PortDakar',
    'https://www.instagram.com/portdedakar/',
    'https://www.linkedin.com/company/port-autonome-de-dakar/',
    'douanes@finances.sn',
    'https://www.douanes.sn',
    'Direction Générale des Douanes — Port de Dakar, Dakar, Senegal',
  ),
  RS: seaport(
    'Port of Bar',
    'https://www.portofbar.rs/',
    'info@portofbar.rs',
    'https://x.com/PortofBarRS',
    'https://www.instagram.com/portofbar/',
    'https://www.linkedin.com/company/port-of-bar-serbia/',
    'carina@uino.gov.rs',
    'https://www.carina.rs',
    'Serbian Customs — Port of Bar, Bar, Serbia',
  ),
  SC: seaport(
    'Port Victoria',
    'https://www.spa.sc/',
    'info@spa.sc',
    'https://x.com/SPA_Seychelles',
    'https://www.instagram.com/spa_seychelles/',
    'https://www.linkedin.com/company/seychelles-ports-authority/',
    'customs@src.gov.sc',
    'https://www.src.gov.sc',
    'Seychelles Revenue Commission — Customs, Port Victoria, Mahé, Seychelles',
  ),
  SL: seaport(
    'Port of Freetown',
    'https://www.slpa.sl/',
    'info@slpa.sl',
    'https://x.com/SLPA_Freetown',
    'https://www.instagram.com/slpa_freetown/',
    'https://www.linkedin.com/company/sierra-leone-ports-authority/',
    'customs@nra.gov.sl',
    'https://www.nra.gov.sl',
    'National Revenue Authority — Customs, Port of Freetown, Freetown, Sierra Leone',
  ),
  SG: seaport(
    'Port of Singapore',
    'https://www.mpa.gov.sg/',
    'MPA_Enquiry@mpa.gov.sg',
    'https://x.com/Mpa_Singapore',
    'https://www.instagram.com/mpa_singapore/',
    'https://www.linkedin.com/company/maritime-and-port-authority-of-singapore/',
    'customs_support@customs.gov.sg',
    'https://www.customs.gov.sg',
    'Singapore Customs — PSA Singapore Terminals, Singapore',
  ),
  SK: seaport(
    'Port of Bratislava (Danube)',
    'https://www.spap.sk/',
    'info@spap.sk',
    'https://x.com/SPAP_Bratislava',
    'https://www.instagram.com/spap_bratislava/',
    'https://www.linkedin.com/company/slovak-shipping-and-ports/',
    'celny@financnasprava.sk',
    'https://www.financnasprava.sk',
    'Financial Administration — Port of Bratislava, Bratislava, Slovakia',
  ),
  SI: seaport(
    'Port of Koper',
    'https://www.luka-kp.si/',
    'info@luka-kp.si',
    'https://x.com/PortKoper',
    'https://www.instagram.com/portkoper/',
    'https://www.linkedin.com/company/luka-koper/',
    'carina@carina.gov.si',
    'https://www.carina.gov.si',
    'Financial Administration — Port of Koper, Koper, Slovenia',
  ),
  SB: seaport(
    'Port of Honiara',
    'https://www.sipa.com.sb/',
    'info@sipa.com.sb',
    'https://x.com/SolomonPorts',
    'https://www.instagram.com/solomonports/',
    'https://www.linkedin.com/company/solomon-ports/',
    'customs@customs.gov.sb',
    'https://www.customs.gov.sb',
    'Solomon Islands Customs — Port of Honiara, Honiara, Solomon Islands',
  ),
  SO: seaport(
    'Port of Mogadishu',
    'https://www.mpa.gov.so/',
    'info@mpa.gov.so',
    'https://x.com/MPA_Somalia',
    'https://www.instagram.com/mpa_somalia/',
    'https://www.linkedin.com/company/mogadishu-port-authority/',
    'customs@finance.gov.so',
    'https://www.customs.gov.so',
    'Somalia Customs — Port of Mogadishu, Mogadishu, Somalia',
  ),
  ZA: seaport(
    'Port of Durban',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'customs@sars.gov.za',
    'https://www.sars.gov.za',
    'South African Revenue Service — Customs, Port of Durban, Durban, South Africa',
  ),
  SS: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@nra.gov.ss',
    'https://www.nra.gov.ss',
    'National Revenue Authority — Customs, Juba, South Sudan',
  ),
  LK: seaport(
    'Port of Colombo',
    'https://www.slpa.lk/',
    'info@slpa.lk',
    'https://x.com/SLPA_LK',
    'https://www.instagram.com/slpa_lk/',
    'https://www.linkedin.com/company/sri-lanka-ports-authority/',
    'customs@gov.lk',
    'https://www.customs.gov.lk',
    'Sri Lanka Customs — Port of Colombo, Colombo, Sri Lanka',
  ),
  SD: seaport(
    'Port Sudan',
    'https://www.spc.sd/',
    'info@spc.sd',
    'https://x.com/SPC_Sudan',
    'https://www.instagram.com/spc_sudan/',
    'https://www.linkedin.com/company/sea-ports-corporation-sudan/',
    'customs@customs.gov.sd',
    'https://www.customs.gov.sd',
    'Sudan Customs Authority — Port Sudan, Port Sudan, Sudan',
  ),
  SR: seaport(
    'Port of Paramaribo (Nieuwe Haven)',
    'https://www.havenbeheer.sr/',
    'info@havenbeheer.sr',
    'https://x.com/SurinamePorts',
    'https://www.instagram.com/surinameports/',
    'https://www.linkedin.com/company/suriname-ports/',
    'customs@customs.gov.sr',
    'https://www.customs.gov.sr',
    'Suriname Customs — Nieuwe Haven, Paramaribo, Suriname',
  ),
  SY: seaport(
    'Port of Latakia',
    'https://www.lattakiaport.gov.sy/',
    'info@lattakiaport.gov.sy',
    '',
    '',
    'https://www.linkedin.com/company/lattakia-port/',
    'customs@customs.gov.sy',
    'https://www.customs.gov.sy',
    'Syrian Customs — Port of Latakia, Latakia, Syria',
  ),
  TJ: seaport(
    'Port of Bandar Abbas (primary maritime gateway; landlocked)',
    'https://www.pmo.ir/',
    'info@pmo.ir',
    'https://x.com/PortsMaritimeIR',
    'https://www.instagram.com/pmo_ir/',
    'https://www.linkedin.com/company/ports-and-maritime-organization/',
    'customs@customs.tj',
    'https://www.customs.tj',
    'Customs Service — Dushanbe, Tajikistan',
  ),
  TZ: seaport(
    'Port of Dar es Salaam',
    'https://www.tanzaniaports.com/',
    'info@tanzaniaports.com',
    'https://x.com/TanzaniaPorts',
    'https://www.instagram.com/tanzaniaports/',
    'https://www.linkedin.com/company/tanzania-ports-authority/',
    'customs@tra.go.tz',
    'https://www.tra.go.tz',
    'Tanzania Revenue Authority — Customs, Port of Dar es Salaam, Dar es Salaam, Tanzania',
  ),
  TH: seaport(
    'Port of Laem Chabang',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'info@customs.go.th',
    'https://www.customs.go.th',
    'Thai Customs — Laem Chabang Port, Chonburi, Thailand',
  ),
  TL: seaport(
    'Port of Dili',
    'https://www.port-timorleste.tl/',
    'info@port-timorleste.tl',
    'https://x.com/PortDili',
    'https://www.instagram.com/portdili/',
    'https://www.linkedin.com/company/port-of-dili/',
    'customs@customs.gov.tl',
    'https://www.customs.gov.tl',
    'Timor-Leste Customs Service — Port of Dili, Dili, Timor-Leste',
  ),
  TG: seaport(
    'Port of Lomé',
    'https://www.portdelome.tg/',
    'contact@portdelome.tg',
    'https://x.com/PortLome',
    'https://www.instagram.com/portdelome/',
    'https://www.linkedin.com/company/port-autonome-de-lome/',
    'douanes@finances.tg',
    'https://www.douanes.tg',
    'Direction Générale des Douanes — Port de Lomé, Lomé, Togo',
  ),
  TO: seaport(
    'Port of Nuku\'alofa',
    'https://www.tongaports.to/',
    'info@tongaports.to',
    'https://x.com/TongaPorts',
    'https://www.instagram.com/tongaports/',
    'https://www.linkedin.com/company/tonga-ports-authority/',
    'customs@customs.gov.to',
    'https://www.customs.gov.to',
    'Tonga Customs — Port of Nuku\'alofa, Nuku\'alofa, Tonga',
  ),
  TT: seaport(
    'Port of Port of Spain',
    'https://www.patnt.com/',
    'info@patnt.com',
    'https://x.com/PATNT',
    'https://www.instagram.com/patnt/',
    'https://www.linkedin.com/company/port-authority-of-trinidad-and-tobago/',
    'customs@customs.gov.tt',
    'https://www.customs.gov.tt',
    'Trinidad and Tobago Customs — Port of Spain, Port of Spain, Trinidad and Tobago',
  ),
  TN: seaport(
    'Port of Rades',
    'https://www.ommp.nat.tn/',
    'contact@ommp.nat.tn',
    'https://x.com/OMMP_Tunisia',
    'https://www.instagram.com/ommp_tunisia/',
    'https://www.linkedin.com/company/ommp-tunisia/',
    'douane@douane.gov.tn',
    'https://www.douane.gov.tn',
    'Direction Générale des Douanes — Port de Radès, Radès, Tunisia',
  ),
  TR: seaport(
    'Port of Mersin',
    'https://www.mersinport.com.tr/',
    'info@mersinport.com.tr',
    'https://x.com/MersinPort',
    'https://www.instagram.com/mersinport/',
    'https://www.linkedin.com/company/mersin-international-port/',
    'gumruk@gumruk.gov.tr',
    'https://www.gumruk.gov.tr',
    'Turkish Customs — Port of Mersin, Mersin, Turkey',
  ),
  TM: seaport(
    'Port of Turkmenbashi',
    'https://www.turkmenbashiseaport.gov.tm/',
    'info@turkmenbashiseaport.gov.tm',
    'https://x.com/TurkmenbashiPort',
    'https://www.instagram.com/turkmenbashiport/',
    'https://www.linkedin.com/company/turkmenbashi-international-seaport/',
    'customs@customs.gov.tm',
    'https://www.customs.gov.tm',
    'State Customs Service — Port of Turkmenbashi, Turkmenbashi, Turkmenistan',
  ),
  UG: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@ura.go.ug',
    'https://www.ura.go.ug',
    'Uganda Revenue Authority — Customs, Kampala, Uganda',
  ),
  UA: seaport(
    'Port of Odesa',
    'https://www.uspa.gov.ua/',
    'info@uspa.gov.ua',
    'https://x.com/USPA_Ukraine',
    'https://www.instagram.com/uspa_ukraine/',
    'https://www.linkedin.com/company/ukraine-sea-ports-authority/',
    'customs@customs.gov.ua',
    'https://www.customs.gov.ua',
    'State Customs Service — Port of Odesa, Odesa, Ukraine',
  ),
  AE: seaport(
    'Jebel Ali Port (Dubai)',
    'https://www.dpworld.com/uae',
    'info@dpworld.com',
    'https://x.com/DP_World',
    'https://www.instagram.com/dpworld/',
    'https://www.linkedin.com/company/dp-world/',
    'customs@customs.ae',
    'https://www.customs.ae',
    'Federal Customs Authority — Jebel Ali Port, Dubai, United Arab Emirates',
  ),
  UY: seaport(
    'Port of Montevideo',
    'https://www.anp.com.uy/',
    'info@anp.com.uy',
    'https://x.com/ANP_Uruguay',
    'https://www.instagram.com/anp_uruguay/',
    'https://www.linkedin.com/company/administracion-nacional-de-puertos/',
    'aduana@aduana.gub.uy',
    'https://www.aduana.gub.uy',
    'Dirección Nacional de Aduanas — Puerto de Montevideo, Montevideo, Uruguay',
  ),
  UZ: seaport(
    'Port of Bandar Abbas (primary maritime gateway; landlocked)',
    'https://www.pmo.ir/',
    'info@pmo.ir',
    'https://x.com/PortsMaritimeIR',
    'https://www.instagram.com/pmo_ir/',
    'https://www.linkedin.com/company/ports-and-maritime-organization/',
    'customs@customs.uz',
    'https://www.customs.uz',
    'State Customs Committee — Tashkent, Uzbekistan',
  ),
  VU: seaport(
    'Port Vila',
    'https://www.vanuatuports.vu/',
    'info@vanuatuports.vu',
    'https://x.com/VanuatuPorts',
    'https://www.instagram.com/vanuatuports/',
    'https://www.linkedin.com/company/vanuatu-ports/',
    'customs@customs.gov.vu',
    'https://www.customs.gov.vu',
    'Vanuatu Customs — Port Vila, Port Vila, Vanuatu',
  ),
  VE: seaport(
    'Port of La Guaira',
    'https://www.bolipuertos.gob.ve/',
    'info@bolipuertos.gob.ve',
    'https://x.com/Bolipuertos',
    'https://www.instagram.com/bolipuertos/',
    'https://www.linkedin.com/company/bolipuertos/',
    'aduana@sencamer.gob.ve',
    'https://www.seniat.gob.ve',
    'SENIAT Aduanas — Puerto de La Guaira, La Guaira, Venezuela',
  ),
  VN: seaport(
    'Port of Ho Chi Minh City (Cát Lái)',
    'https://www.saigonnewport.com.vn/',
    'info@saigonnewport.com.vn',
    'https://x.com/SaigonNewport',
    'https://www.instagram.com/saigonnewport/',
    'https://www.linkedin.com/company/saigon-newport-corporation/',
    'contact@customs.gov.vn',
    'https://www.customs.gov.vn',
    'General Department of Vietnam Customs — Cát Lái Port, Ho Chi Minh City, Vietnam',
  ),
  YE: seaport(
    'Port of Aden',
    'https://www.adenport.com.ye/',
    'info@adenport.com.ye',
    '',
    '',
    'https://www.linkedin.com/company/aden-port/',
    'customs@customs.gov.ye',
    'https://www.customs.gov.ye',
    'Yemen Customs Authority — Port of Aden, Aden, Yemen',
  ),
  ZM: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@zra.org.zm',
    'https://www.zra.org.zm',
    'Zambia Revenue Authority — Customs Division, Lusaka, Zambia',
  ),
  ZW: seaport(
    'Port of Beira (primary maritime gateway; landlocked)',
    'https://www.otal.com/mozambique/port-of-beira',
    'info@cdm.co.mz',
    'https://x.com/CDM_Mozambique',
    'https://www.instagram.com/cdm_mozambique/',
    'https://www.linkedin.com/company/cfm-mozambique/',
    'info@zimra.co.zw',
    'https://www.zimra.co.zw',
    'Zimbabwe Revenue Authority — Customs Division, Harare, Zimbabwe',
  ),
}
