import type { BriMemberIsoCode } from './participantStatesIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const BRI_MAIN_INTERNATIONAL_AIRPORTS: Record<BriMemberIsoCode, MainInternationalAirport> = {
  AF: {
    name: 'Kabul International Airport (KBL)',
    website: 'https://www.kabulairport.com/',
    email: 'info@kabulairport.com',
    twitter: 'https://x.com/KabulAirport',
    instagram: 'https://www.instagram.com/kabulairport/',
    linkedin: 'https://www.linkedin.com/company/kabul-international-airport/',
    apiEndpoint: '',
  },
  AL: {
    name: 'Tirana International Airport Nënë Tereza (TIA)',
    website: 'https://www.tirana-airport.com/',
    email: 'info@tirana-airport.com',
    twitter: 'https://x.com/TiranaAirport',
    instagram: 'https://www.instagram.com/tiranaairport/',
    linkedin: 'https://www.linkedin.com/company/tirana-international-airport/',
    apiEndpoint: '',
  },
  DZ: {
    name: 'Houari Boumediene Airport (ALG)',
    website: 'https://www.aeroportalger.dz/',
    email: 'contact@aeroportalger.dz',
    twitter: 'https://x.com/AeroportALG',
    instagram: 'https://www.instagram.com/aeroportalger/',
    linkedin: 'https://www.linkedin.com/company/egsa-alger/',
    apiEndpoint: '',
  },
  AO: {
    name: 'Quatro de Fevereiro International Airport (LAD)',
    website: 'https://www.aeroportosdeangola.co.ao/',
    email: 'info@aeroportosdeangola.co.ao',
    twitter: 'https://x.com/AngolaAirports',
    instagram: 'https://www.instagram.com/angolaairports/',
    linkedin: 'https://www.linkedin.com/company/angola-airports/',
    apiEndpoint: '',
  },
  AG: {
    name: 'V.C. Bird International Airport (ANU)',
    website: 'https://www.antigua-barbuda.com/',
    email: 'info@ab.gov.ag',
    twitter: 'https://x.com/AntiguaAirport',
    instagram: 'https://www.instagram.com/antiguaairport/',
    linkedin: 'https://www.linkedin.com/company/vc-bird-international-airport/',
    apiEndpoint: '',
  },
  AR: {
    name: 'Ministro Pistarini International Airport (EZE)',
    website: 'https://www.aa2000.com.ar/',
    email: 'info@aa2000.com.ar',
    twitter: 'https://x.com/AA2000',
    instagram: 'https://www.instagram.com/aa2000/',
    linkedin: 'https://www.linkedin.com/company/aeropuertos-argentina-2000/',
    apiEndpoint: '',
  },
  AM: {
    name: 'Zvartnots International Airport (EVN)',
    website: 'https://www.zvartnots.aero/',
    email: 'info@zvartnots.aero',
    twitter: 'https://x.com/ZvartnotsAirport',
    instagram: 'https://www.instagram.com/zvartnotsairport/',
    linkedin: 'https://www.linkedin.com/company/zvartnots-international-airport/',
    apiEndpoint: '',
  },
  AT: {
    name: 'Vienna International Airport (VIE)',
    website: 'https://www.viennaairport.com/',
    email: 'info@viennaairport.com',
    twitter: 'https://x.com/viennaairport',
    instagram: 'https://www.instagram.com/viennaairport/',
    linkedin: 'https://www.linkedin.com/company/flughafen-wien-ag/',
    apiEndpoint: '',
  },
  AZ: {
    name: 'Heydar Aliyev International Airport (GYD)',
    website: 'https://www.airport.az/',
    email: 'info@airport.az',
    twitter: 'https://x.com/BakuAirport',
    instagram: 'https://www.instagram.com/bakuairport/',
    linkedin: 'https://www.linkedin.com/company/heydar-aliyev-international-airport/',
    apiEndpoint: '',
  },
  BH: {
    name: 'Bahrain International Airport (BAH)',
    website: 'https://www.bahrainairport.com/',
    email: 'info@bahrainairport.com',
    twitter: 'https://x.com/BahrainAirport',
    instagram: 'https://www.instagram.com/bahrainairport/',
    linkedin: 'https://www.linkedin.com/company/bahrain-airport-company/',
    apiEndpoint: '',
  },
  BD: {
    name: 'Hazrat Shahjalal International Airport (DAC)',
    website: 'https://www.caab.gov.bd/',
    email: 'info@caab.gov.bd',
    twitter: 'https://x.com/CAAB_Official',
    instagram: 'https://www.instagram.com/caab_official/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-bangladesh/',
    apiEndpoint: '',
  },
  BB: {
    name: 'Grantley Adams International Airport (BGI)',
    website: 'https://www.gaabarbados.org/',
    email: 'info@gaabarbados.org',
    twitter: 'https://x.com/GAABarbados',
    instagram: 'https://www.instagram.com/gaabarbados/',
    linkedin: 'https://www.linkedin.com/company/grantley-adams-international-airport/',
    apiEndpoint: '',
  },
  BY: {
    name: 'Minsk National Airport (MSQ)',
    website: 'https://www.airport.by/',
    email: 'info@airport.by',
    twitter: 'https://x.com/MinskAirport',
    instagram: 'https://www.instagram.com/minskairport/',
    linkedin: 'https://www.linkedin.com/company/minsk-national-airport/',
    apiEndpoint: '',
  },
  BJ: {
    name: 'Cadjehoun International Airport (COO)',
    website: 'https://www.aeroport-cotonou.bj/',
    email: 'contact@aeroport-cotonou.bj',
    twitter: 'https://x.com/AeroportCotonou',
    instagram: 'https://www.instagram.com/aeroportcotonou/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-cadjehoun/',
    apiEndpoint: '',
  },
  BO: {
    name: 'El Alto International Airport (LPB)',
    website: 'https://www.sabsa.aero/',
    email: 'info@sabsa.aero',
    twitter: 'https://x.com/SABSA_Bolivia',
    instagram: 'https://www.instagram.com/sabsa_bolivia/',
    linkedin: 'https://www.linkedin.com/company/servicio-de-navegacion-aerea-sabsa/',
    apiEndpoint: '',
  },
  BA: {
    name: 'Sarajevo International Airport (SJJ)',
    website: 'https://www.sarajevo-airport.ba/',
    email: 'info@sarajevo-airport.ba',
    twitter: 'https://x.com/SarajevoAirport',
    instagram: 'https://www.instagram.com/sarajevoairport/',
    linkedin: 'https://www.linkedin.com/company/sarajevo-international-airport/',
    apiEndpoint: '',
  },
  BW: {
    name: 'Sir Seretse Khama International Airport (GBE)',
    website: 'https://www.caab.co.bw/',
    email: 'info@caab.co.bw',
    twitter: 'https://x.com/CAAB_Botswana',
    instagram: 'https://www.instagram.com/caab_botswana/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-botswana/',
    apiEndpoint: '',
  },
  BN: {
    name: 'Brunei International Airport (BWN)',
    website: 'https://www.bruneiair.com/',
    email: 'info@bruneiair.com',
    twitter: 'https://x.com/BruneiAirport',
    instagram: 'https://www.instagram.com/bruneiairport/',
    linkedin: 'https://www.linkedin.com/company/brunei-international-airport/',
    apiEndpoint: '',
  },
  BG: {
    name: 'Sofia Airport (SOF)',
    website: 'https://www.sofia-airport.eu/',
    email: 'info@sofia-airport.eu',
    twitter: 'https://x.com/SofiaAirport',
    instagram: 'https://www.instagram.com/sofiaairport/',
    linkedin: 'https://www.linkedin.com/company/sofia-airport/',
    apiEndpoint: '',
  },
  BI: {
    name: 'Melchior Ndadaye International Airport (BJM)',
    website: 'https://www.aeroport-bujumbura.bi/',
    email: 'info@aeroport-bujumbura.bi',
    twitter: 'https://x.com/AeroportBJM',
    instagram: 'https://www.instagram.com/aeroportbujumbura/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-bujumbura/',
    apiEndpoint: '',
  },
  CV: {
    name: 'Nelson Mandela International Airport (SID)',
    website: 'https://www.aeroporto-amilcar-cabral.cv/',
    email: 'info@aeroporto-amilcar-cabral.cv',
    twitter: 'https://x.com/AeroportoSID',
    instagram: 'https://www.instagram.com/aeroporto_sid/',
    linkedin: 'https://www.linkedin.com/company/aeroporto-internacional-nelson-mandela/',
    apiEndpoint: '',
  },
  KH: {
    name: 'Phnom Penh International Airport (PNH)',
    website: 'https://www.cambodia-airports.aero/',
    email: 'info@cambodia-airports.aero',
    twitter: 'https://x.com/CambodiaAirports',
    instagram: 'https://www.instagram.com/cambodiaairports/',
    linkedin: 'https://www.linkedin.com/company/cambodia-airports/',
    apiEndpoint: '',
  },
  CM: {
    name: 'Yaoundé Nsimalen International Airport (NSI)',
    website: 'https://www.aeroport-yaounde.cm/',
    email: 'info@aeroport-yaounde.cm',
    twitter: 'https://x.com/AeroportNSI',
    instagram: 'https://www.instagram.com/aeroportnsimalen/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-nsimalen/',
    apiEndpoint: '',
  },
  CF: {
    name: 'Bangui M\'Poko International Airport (BGF)',
    website: 'https://www.aeroport-bangui.cf/',
    email: 'info@aeroport-bangui.cf',
    twitter: 'https://x.com/AeroportBGF',
    instagram: 'https://www.instagram.com/aeroportbangui/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-bangui-mpoko/',
    apiEndpoint: '',
  },
  TD: {
    name: 'N\'Djamena International Airport (NDJ)',
    website: 'https://www.anac.td/',
    email: 'contact@anac.td',
    twitter: 'https://x.com/ANAC_Tchad',
    instagram: 'https://www.instagram.com/anac_tchad/',
    linkedin: 'https://www.linkedin.com/company/anac-tchad/',
    apiEndpoint: '',
  },
  CL: {
    name: 'Arturo Merino Benítez International Airport (SCL)',
    website: 'https://www.nuestroaeropuerto.cl/',
    email: 'contacto@nuestroaeropuerto.cl',
    twitter: 'https://x.com/AeropuertoSCL',
    instagram: 'https://www.instagram.com/aeropuertoscl/',
    linkedin: 'https://www.linkedin.com/company/nuevo-aeropuerto-internacional-arturo-merino-benitez/',
    apiEndpoint: '',
  },
  CN: {
    name: 'Beijing Capital International Airport (PEK)',
    website: 'https://www.bcia.com.cn/',
    email: 'service@bcia.com.cn',
    twitter: 'https://x.com/BeijingAirport',
    instagram: 'https://www.instagram.com/beijingairport/',
    linkedin: 'https://www.linkedin.com/company/beijing-capital-international-airport/',
    apiEndpoint: '',
  },
  CO: {
    name: 'El Dorado International Airport (BOG)',
    website: 'https://www.eldorado.aero/',
    email: 'info@eldorado.aero',
    twitter: 'https://x.com/BOG_ELDORADO',
    instagram: 'https://www.instagram.com/bog_eldorado/',
    linkedin: 'https://www.linkedin.com/company/el-dorado-international-airport/',
    apiEndpoint: '',
  },
  KM: {
    name: 'Prince Said Ibrahim International Airport (HAH)',
    website: 'https://www.aeroport-comores.km/',
    email: 'info@aeroport-comores.km',
    twitter: 'https://x.com/AeroportHAH',
    instagram: 'https://www.instagram.com/aeroportcomores/',
    linkedin: 'https://www.linkedin.com/company/aeroport-prince-said-ibrahim/',
    apiEndpoint: '',
  },
  CK: {
    name: 'Rarotonga International Airport (RAR)',
    website: 'https://www.airports.co.ck/',
    email: 'info@airports.co.ck',
    twitter: 'https://x.com/CookIslandsAir',
    instagram: 'https://www.instagram.com/cookislandsair/',
    linkedin: 'https://www.linkedin.com/company/cook-islands-airports/',
    apiEndpoint: '',
  },
  CR: {
    name: 'Juan Santamaría International Airport (SJO)',
    website: 'https://www.sjoairport.com/',
    email: 'info@sjoairport.com',
    twitter: 'https://x.com/SJOAirport',
    instagram: 'https://www.instagram.com/sjoairport/',
    linkedin: 'https://www.linkedin.com/company/juan-santamaria-international-airport/',
    apiEndpoint: '',
  },
  CI: {
    name: 'Félix-Houphouët-Boigny International Airport (ABJ)',
    website: 'https://www.aeroport-abidjan.com/',
    email: 'contact@aeroport-abidjan.com',
    twitter: 'https://x.com/AeroportABJ',
    instagram: 'https://www.instagram.com/aeroportabidjan/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-felix-houphouet-boigny/',
    apiEndpoint: '',
  },
  HR: {
    name: 'Zagreb Airport (ZAG)',
    website: 'https://www.zagreb-airport.hr/',
    email: 'info@zagreb-airport.hr',
    twitter: 'https://x.com/ZagrebAirport',
    instagram: 'https://www.instagram.com/zagrebairport/',
    linkedin: 'https://www.linkedin.com/company/zagreb-airport/',
    apiEndpoint: '',
  },
  CU: {
    name: 'José Martí International Airport (HAV)',
    website: 'https://www.ecasa.co.cu/',
    email: 'info@ecasa.co.cu',
    twitter: 'https://x.com/HavanaAirport',
    instagram: 'https://www.instagram.com/havanaairport/',
    linkedin: 'https://www.linkedin.com/company/jose-marti-international-airport/',
    apiEndpoint: '',
  },
  CY: {
    name: 'Larnaca International Airport (LCA)',
    website: 'https://www.hermesairports.com/',
    email: 'info@hermesairports.com',
    twitter: 'https://x.com/HermesAirports',
    instagram: 'https://www.instagram.com/hermesairports/',
    linkedin: 'https://www.linkedin.com/company/hermes-airports/',
    apiEndpoint: '',
  },
  CZ: {
    name: 'Václav Havel Airport Prague (PRG)',
    website: 'https://www.prg.aero/',
    email: 'info@prg.aero',
    twitter: 'https://x.com/PragueAirport',
    instagram: 'https://www.instagram.com/pragueairport/',
    linkedin: 'https://www.linkedin.com/company/prague-airport/',
    apiEndpoint: '',
  },
  CD: {
    name: 'N\'djili International Airport (FIH)',
    website: 'https://www.rva-rdc.cd/',
    email: 'contact@rva-rdc.cd',
    twitter: 'https://x.com/RVA_RDC',
    instagram: 'https://www.instagram.com/rva_rdc/',
    linkedin: 'https://www.linkedin.com/company/regie-des-voies-aeriennes-rva/',
    apiEndpoint: '',
  },
  DJ: {
    name: 'Djibouti-Ambouli International Airport (JIB)',
    website: 'https://www.aeroport-djibouti.dj/',
    email: 'contact@aeroport-djibouti.dj',
    twitter: 'https://x.com/AeroportJIB',
    instagram: 'https://www.instagram.com/aeroportdjibouti/',
    linkedin: 'https://www.linkedin.com/company/djibouti-ambouli-international-airport/',
    apiEndpoint: '',
  },
  DM: {
    name: 'Douglas-Charles Airport (DOM)',
    website: 'https://www.dominicaairport.com/',
    email: 'info@dominicaairport.com',
    twitter: 'https://x.com/DominicaAirport',
    instagram: 'https://www.instagram.com/dominicaairport/',
    linkedin: 'https://www.linkedin.com/company/douglas-charles-airport/',
    apiEndpoint: '',
  },
  DO: {
    name: 'Las Américas International Airport (SDQ)',
    website: 'https://www.aerodom.com/',
    email: 'info@aerodom.com',
    twitter: 'https://x.com/AerodomSDQ',
    instagram: 'https://www.instagram.com/aerodom/',
    linkedin: 'https://www.linkedin.com/company/aerodom/',
    apiEndpoint: '',
  },
  EC: {
    name: 'Mariscal Sucre International Airport (UIO)',
    website: 'https://www.quitoairport.aero/',
    email: 'info@quitoairport.aero',
    twitter: 'https://x.com/QuitoAirport',
    instagram: 'https://www.instagram.com/quitoairport/',
    linkedin: 'https://www.linkedin.com/company/mariscal-sucre-international-airport/',
    apiEndpoint: '',
  },
  EG: {
    name: 'Cairo International Airport (CAI)',
    website: 'https://www.cairo-airport.com/',
    email: 'info@cairo-airport.com',
    twitter: 'https://x.com/CairoAirport',
    instagram: 'https://www.instagram.com/cairoairport/',
    linkedin: 'https://www.linkedin.com/company/cairo-airport/',
    apiEndpoint: '',
  },
  SV: {
    name: 'Monseñor Óscar Arnulfo Romero International Airport (SAL)',
    website: 'https://www.aeropuertoelsalvador.gob.sv/',
    email: 'info@aeropuertoelsalvador.gob.sv',
    twitter: 'https://x.com/SALAirport',
    instagram: 'https://www.instagram.com/salairport/',
    linkedin: 'https://www.linkedin.com/company/oscar-arnulfo-romero-international-airport/',
    apiEndpoint: '',
  },
  GQ: {
    name: 'Malabo International Airport (SSG)',
    website: 'https://www.aeropuerto-malabo.gq/',
    email: 'info@aeropuerto-malabo.gq',
    twitter: 'https://x.com/AeropuertoSSG',
    instagram: 'https://www.instagram.com/aeropuertomalabo/',
    linkedin: 'https://www.linkedin.com/company/aeropuerto-internacional-malabo/',
    apiEndpoint: '',
  },
  ER: {
    name: 'Asmara International Airport (ASM)',
    website: 'https://www.eritreanairlines.com/',
    email: 'info@eritreanairlines.com',
    twitter: 'https://x.com/EritreaAirlines',
    instagram: 'https://www.instagram.com/eritreanairlines/',
    linkedin: 'https://www.linkedin.com/company/eritrean-airlines/',
    apiEndpoint: '',
  },
  EE: {
    name: 'Tallinn Airport (TLL)',
    website: 'https://www.tallinn-airport.ee/',
    email: 'info@tallinn-airport.ee',
    twitter: 'https://x.com/TallinnAirport',
    instagram: 'https://www.instagram.com/tallinnairport/',
    linkedin: 'https://www.linkedin.com/company/tallinn-airport/',
    apiEndpoint: '',
  },
  ET: {
    name: 'Addis Ababa Bole International Airport (ADD)',
    website: 'https://www.ethiopianairlines.com/add',
    email: 'addinfo@ethiopianairlines.com',
    twitter: 'https://x.com/flyethiopian',
    instagram: 'https://www.instagram.com/flyethiopian/',
    linkedin: 'https://www.linkedin.com/company/ethiopian-airlines/',
    apiEndpoint: '',
  },
  FJ: {
    name: 'Nadi International Airport (NAN)',
    website: 'https://www.nadi-airport.com/',
    email: 'info@nadi-airport.com',
    twitter: 'https://x.com/NadiAirport',
    instagram: 'https://www.instagram.com/nadiairport/',
    linkedin: 'https://www.linkedin.com/company/nadi-international-airport/',
    apiEndpoint: '',
  },
  GA: {
    name: 'Libreville Leon M\'ba International Airport (LBV)',
    website: 'https://www.aeroport-libreville.ga/',
    email: 'contact@aeroport-libreville.ga',
    twitter: 'https://x.com/AeroportLBV',
    instagram: 'https://www.instagram.com/aeroportlibreville/',
    linkedin: 'https://www.linkedin.com/company/aeroport-leon-mba/',
    apiEndpoint: '',
  },
  GM: {
    name: 'Banjul International Airport (BJL)',
    website: 'https://www.gcaa.gm/',
    email: 'info@gcaa.gm',
    twitter: 'https://x.com/GCAA_Gambia',
    instagram: 'https://www.instagram.com/gcaa_gambia/',
    linkedin: 'https://www.linkedin.com/company/gambia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GE: {
    name: 'Tbilisi International Airport (TBS)',
    website: 'https://www.tbilisi-airport.com/',
    email: 'info@tbilisi-airport.com',
    twitter: 'https://x.com/TbilisiAirport',
    instagram: 'https://www.instagram.com/tbilisiairport/',
    linkedin: 'https://www.linkedin.com/company/tbilisi-international-airport/',
    apiEndpoint: '',
  },
  GH: {
    name: 'Kotoka International Airport (ACC)',
    website: 'https://www.gcaa.com.gh/',
    email: 'info@gcaa.com.gh',
    twitter: 'https://x.com/GCAA_Ghana',
    instagram: 'https://www.instagram.com/gcaa_ghana/',
    linkedin: 'https://www.linkedin.com/company/ghana-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GR: {
    name: 'Athens International Airport (ATH)',
    website: 'https://www.aia.gr/',
    email: 'info@aia.gr',
    twitter: 'https://x.com/ATH_airport',
    instagram: 'https://www.instagram.com/athens_airport/',
    linkedin: 'https://www.linkedin.com/company/athens-international-airport/',
    apiEndpoint: '',
  },
  GD: {
    name: 'Maurice Bishop International Airport (GND)',
    website: 'https://www.grenadaairports.com/',
    email: 'info@grenadaairports.com',
    twitter: 'https://x.com/GrenadaAirport',
    instagram: 'https://www.instagram.com/grenadaairport/',
    linkedin: 'https://www.linkedin.com/company/maurice-bishop-international-airport/',
    apiEndpoint: '',
  },
  GN: {
    name: 'Ahmed Sékou Touré International Airport (CKY)',
    website: 'https://www.aeroport-conakry.gn/',
    email: 'contact@aeroport-conakry.gn',
    twitter: 'https://x.com/AeroportCKY',
    instagram: 'https://www.instagram.com/aeroportconakry/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-conakry/',
    apiEndpoint: '',
  },
  GW: {
    name: 'Osvaldo Vieira International Airport (OXB)',
    website: 'https://www.aeroporto-bissau.gw/',
    email: 'contact@aeroporto-bissau.gw',
    twitter: 'https://x.com/AeroportoOXB',
    instagram: 'https://www.instagram.com/aeroportobissau/',
    linkedin: 'https://www.linkedin.com/company/aeroporto-osvaldo-vieira/',
    apiEndpoint: '',
  },
  GY: {
    name: 'Cheddi Jagan International Airport (GEO)',
    website: 'https://www.cjairport-gy.com/',
    email: 'info@cjairport-gy.com',
    twitter: 'https://x.com/GuyanaAirport',
    instagram: 'https://www.instagram.com/guyanaairport/',
    linkedin: 'https://www.linkedin.com/company/cheddi-jagan-international-airport/',
    apiEndpoint: '',
  },
  HN: {
    name: 'Toncontín International Airport (TGU)',
    website: 'https://www.aeropuertosdehonduras.hn/',
    email: 'info@aeropuertosdehonduras.hn',
    twitter: 'https://x.com/HondurasAirport',
    instagram: 'https://www.instagram.com/hondurasairport/',
    linkedin: 'https://www.linkedin.com/company/toncontin-international-airport/',
    apiEndpoint: '',
  },
  HU: {
    name: 'Budapest Ferenc Liszt International Airport (BUD)',
    website: 'https://www.bud.hu/',
    email: 'info@bud.hu',
    twitter: 'https://x.com/BudapestAirport',
    instagram: 'https://www.instagram.com/budapestairport/',
    linkedin: 'https://www.linkedin.com/company/budapest-airport/',
    apiEndpoint: '',
  },
  ID: {
    name: 'Soekarno-Hatta International Airport (CGK)',
    website: 'https://soekarnohatta-airport.co.id/',
    email: 'info@soekarnohatta-airport.co.id',
    twitter: 'https://x.com/SoettaAirport',
    instagram: 'https://www.instagram.com/soettaairport/',
    linkedin: 'https://www.linkedin.com/company/soekarno-hatta-international-airport/',
    apiEndpoint: '',
  },
  IR: {
    name: 'Imam Khomeini International Airport (IKA)',
    website: 'https://www.ikac.ir/',
    email: 'info@ikac.ir',
    twitter: 'https://x.com/IKA_Airport',
    instagram: 'https://www.instagram.com/ika_airport/',
    linkedin: 'https://www.linkedin.com/company/imam-khomeini-international-airport/',
    apiEndpoint: '',
  },
  IQ: {
    name: 'Baghdad International Airport (BGW)',
    website: 'https://www.bgw.aero/',
    email: 'info@bgw.aero',
    twitter: 'https://x.com/BaghdadAirport',
    instagram: 'https://www.instagram.com/baghdadairport/',
    linkedin: 'https://www.linkedin.com/company/baghdad-international-airport/',
    apiEndpoint: '',
  },
  IT: {
    name: 'Leonardo da Vinci–Fiumicino Airport (FCO)',
    website: 'https://www.adr.it/',
    email: 'info@adr.it',
    twitter: 'https://x.com/ADRAirports',
    instagram: 'https://www.instagram.com/adr_airports/',
    linkedin: 'https://www.linkedin.com/company/adr-aeroporti-di-roma/',
    apiEndpoint: '',
  },
  JM: {
    name: 'Norman Manley International Airport (KIN)',
    website: 'https://www.nmia.aero/',
    email: 'info@nmia.aero',
    twitter: 'https://x.com/NMIA_Airport',
    instagram: 'https://www.instagram.com/nmia_airport/',
    linkedin: 'https://www.linkedin.com/company/norman-manley-international-airport/',
    apiEndpoint: '',
  },
  JO: {
    name: 'Queen Alia International Airport (AMM)',
    website: 'https://www.qaiairport.com/',
    email: 'info@qaiairport.com',
    twitter: 'https://x.com/QAIAirport',
    instagram: 'https://www.instagram.com/qaiairport/',
    linkedin: 'https://www.linkedin.com/company/queen-alia-international-airport/',
    apiEndpoint: '',
  },
  KZ: {
    name: 'Almaty International Airport (ALA)',
    website: 'https://www.alaport.com/',
    email: 'info@alaport.com',
    twitter: 'https://x.com/AlmatyAirport',
    instagram: 'https://www.instagram.com/almatyairport/',
    linkedin: 'https://www.linkedin.com/company/almaty-international-airport/',
    apiEndpoint: '',
  },
  KE: {
    name: 'Jomo Kenyatta International Airport (NBO)',
    website: 'https://www.kaa.go.ke/',
    email: 'info@kaa.go.ke',
    twitter: 'https://x.com/KenyaAirports',
    instagram: 'https://www.instagram.com/kenyaairports/',
    linkedin: 'https://www.linkedin.com/company/kenya-airports-authority/',
    apiEndpoint: '',
  },
  KI: {
    name: 'Bonriki International Airport (TRW)',
    website: 'https://www.aviation.gov.ki/',
    email: 'info@aviation.gov.ki',
    twitter: 'https://x.com/KiribatiAir',
    instagram: 'https://www.instagram.com/kiribatiair/',
    linkedin: 'https://www.linkedin.com/company/kiribati-aviation/',
    apiEndpoint: '',
  },
  KW: {
    name: 'Kuwait International Airport (KWI)',
    website: 'https://www.kuwait-airport.com.kw/',
    email: 'info@kuwait-airport.com.kw',
    twitter: 'https://x.com/KuwaitAirport',
    instagram: 'https://www.instagram.com/kuwaitairport/',
    linkedin: 'https://www.linkedin.com/company/kuwait-airports/',
    apiEndpoint: '',
  },
  KG: {
    name: 'Manas International Airport (FRU)',
    website: 'https://www.airport.kg/',
    email: 'info@airport.kg',
    twitter: 'https://x.com/ManasAirport',
    instagram: 'https://www.instagram.com/manasairport/',
    linkedin: 'https://www.linkedin.com/company/manas-international-airport/',
    apiEndpoint: '',
  },
  LA: {
    name: 'Wattay International Airport (VTE)',
    website: 'https://www.vientianeairport.com/',
    email: 'info@vientianeairport.com',
    twitter: 'https://x.com/VTEAirport',
    instagram: 'https://www.instagram.com/vteairport/',
    linkedin: 'https://www.linkedin.com/company/wattay-international-airport/',
    apiEndpoint: '',
  },
  LV: {
    name: 'Riga International Airport (RIX)',
    website: 'https://www.riga-airport.com/',
    email: 'info@riga-airport.com',
    twitter: 'https://x.com/RigaAirport',
    instagram: 'https://www.instagram.com/rigaairport/',
    linkedin: 'https://www.linkedin.com/company/riga-international-airport/',
    apiEndpoint: '',
  },
  LB: {
    name: 'Beirut-Rafic Hariri International Airport (BEY)',
    website: 'https://www.beirutairport.gov.lb/',
    email: 'info@beirutairport.gov.lb',
    twitter: 'https://x.com/BeirutAirport',
    instagram: 'https://www.instagram.com/beirutairport/',
    linkedin: 'https://www.linkedin.com/company/rafic-hariri-international-airport/',
    apiEndpoint: '',
  },
  LS: {
    name: 'Moshoeshoe I International Airport (MSU)',
    website: 'https://www.lac.org.ls/',
    email: 'info@lac.org.ls',
    twitter: 'https://x.com/LAC_Lesotho',
    instagram: 'https://www.instagram.com/lac_lesotho/',
    linkedin: 'https://www.linkedin.com/company/lesotho-airports-authority/',
    apiEndpoint: '',
  },
  LR: {
    name: 'Roberts International Airport (ROB)',
    website: 'https://www.lcaa.gov.lr/',
    email: 'info@lcaa.gov.lr',
    twitter: 'https://x.com/LCAA_Liberia',
    instagram: 'https://www.instagram.com/lcaa_liberia/',
    linkedin: 'https://www.linkedin.com/company/liberia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  LY: {
    name: 'Mitiga International Airport (MJI)',
    website: 'https://www.lycaa.gov.ly/',
    email: 'info@lycaa.gov.ly',
    twitter: 'https://x.com/LYCAA_Libya',
    instagram: 'https://www.instagram.com/lycaa_libya/',
    linkedin: 'https://www.linkedin.com/company/libyan-civil-aviation-authority/',
    apiEndpoint: '',
  },
  LT: {
    name: 'Vilnius Airport (VNO)',
    website: 'https://www.vilnius-airport.lt/',
    email: 'info@vilnius-airport.lt',
    twitter: 'https://x.com/VilniusAirport',
    instagram: 'https://www.instagram.com/vilniusairport/',
    linkedin: 'https://www.linkedin.com/company/vilnius-airport/',
    apiEndpoint: '',
  },
  LU: {
    name: 'Luxembourg Airport (LUX)',
    website: 'https://www.lux-airport.lu/',
    email: 'info@lux-airport.lu',
    twitter: 'https://x.com/LuxAirport',
    instagram: 'https://www.instagram.com/luxairport/',
    linkedin: 'https://www.linkedin.com/company/luxembourg-airport/',
    apiEndpoint: '',
  },
  MG: {
    name: 'Ivato International Airport (TNR)',
    website: 'https://www.ravinala.mg/',
    email: 'contact@ravinala.mg',
    twitter: 'https://x.com/RavinalaAirports',
    instagram: 'https://www.instagram.com/ravinalaairports/',
    linkedin: 'https://www.linkedin.com/company/ravinala-airports/',
    apiEndpoint: '',
  },
  MW: {
    name: 'Kamuzu International Airport (LLW)',
    website: 'https://www.dca.gov.mw/',
    email: 'info@dca.gov.mw',
    twitter: 'https://x.com/DCA_Malawi',
    instagram: 'https://www.instagram.com/dca_malawi/',
    linkedin: 'https://www.linkedin.com/company/department-of-civil-aviation-malawi/',
    apiEndpoint: '',
  },
  MY: {
    name: 'Kuala Lumpur International Airport (KUL)',
    website: 'https://www.klia.com.my/',
    email: 'info@klia.com.my',
    twitter: 'https://x.com/KLIA_Malaysia',
    instagram: 'https://www.instagram.com/klia_malaysia/',
    linkedin: 'https://www.linkedin.com/company/malaysia-airports/',
    apiEndpoint: '',
  },
  MV: {
    name: 'Velana International Airport (MLE)',
    website: 'https://www.maclonline.com/',
    email: 'info@macl.aero',
    twitter: 'https://x.com/MACL_Official',
    instagram: 'https://www.instagram.com/macl_official/',
    linkedin: 'https://www.linkedin.com/company/maldives-airports-company-limited/',
    apiEndpoint: '',
  },
  ML: {
    name: 'Modibo Keita International Airport (BKO)',
    website: 'https://www.aeroport-bamako.ml/',
    email: 'contact@aeroport-bamako.ml',
    twitter: 'https://x.com/AeroportBKO',
    instagram: 'https://www.instagram.com/aeroportbamako/',
    linkedin: 'https://www.linkedin.com/company/aeroport-modibo-keita/',
    apiEndpoint: '',
  },
  MT: {
    name: 'Malta International Airport (MLA)',
    website: 'https://www.maltairport.com/',
    email: 'info@maltairport.com',
    twitter: 'https://x.com/MaltaAirport',
    instagram: 'https://www.instagram.com/maltairport/',
    linkedin: 'https://www.linkedin.com/company/malta-international-airport/',
    apiEndpoint: '',
  },
  MR: {
    name: 'Nouakchott-Oumtounsy International Airport (NKC)',
    website: 'https://www.anac.mr/',
    email: 'contact@anac.mr',
    twitter: 'https://x.com/ANAC_Mauritanie',
    instagram: 'https://www.instagram.com/anac_mauritanie/',
    linkedin: 'https://www.linkedin.com/company/anac-mauritanie/',
    apiEndpoint: '',
  },
  FM: {
    name: 'Pohnpei International Airport (PNI)',
    website: 'https://www.fsmgov.org/',
    email: 'info@fsmgov.org',
    twitter: 'https://x.com/FSMGov',
    instagram: 'https://www.instagram.com/fsmgov/',
    linkedin: 'https://www.linkedin.com/company/federated-states-of-micronesia/',
    apiEndpoint: '',
  },
  MD: {
    name: 'Chișinău International Airport (KIV)',
    website: 'https://www.airport.md/',
    email: 'info@airport.md',
    twitter: 'https://x.com/ChisinauAirport',
    instagram: 'https://www.instagram.com/chisinauairport/',
    linkedin: 'https://www.linkedin.com/company/chisinau-international-airport/',
    apiEndpoint: '',
  },
  MN: {
    name: 'Chinggis Khaan International Airport (UBN)',
    website: 'https://www.ub-airport.mn/',
    email: 'info@ub-airport.mn',
    twitter: 'https://x.com/UBAirport',
    instagram: 'https://www.instagram.com/ubairport/',
    linkedin: 'https://www.linkedin.com/company/chinggis-khaan-international-airport/',
    apiEndpoint: '',
  },
  ME: {
    name: 'Podgorica Airport (TGD)',
    website: 'https://www.montenegroairports.com/',
    email: 'info@montenegroairports.com',
    twitter: 'https://x.com/MontenegroAirport',
    instagram: 'https://www.instagram.com/montenegroairport/',
    linkedin: 'https://www.linkedin.com/company/airports-of-montenegro/',
    apiEndpoint: '',
  },
  MA: {
    name: 'Mohammed V International Airport (CMN)',
    website: 'https://www.onda.ma/en',
    email: 'contact@onda.ma',
    twitter: 'https://x.com/ONDA_MAROC',
    instagram: 'https://www.instagram.com/onda_maroc/',
    linkedin: 'https://www.linkedin.com/company/onda-officiel/',
    apiEndpoint: '',
  },
  MZ: {
    name: 'Maputo International Airport (MPM)',
    website: 'https://www.aeroportos.co.mz/',
    email: 'info@aeroportos.co.mz',
    twitter: 'https://x.com/AeroportosMZ',
    instagram: 'https://www.instagram.com/aeroportosmz/',
    linkedin: 'https://www.linkedin.com/company/aeroportos-de-mocambique/',
    apiEndpoint: '',
  },
  MM: {
    name: 'Yangon International Airport (RGN)',
    website: 'https://www.yangonairport.aero/',
    email: 'info@yangonairport.aero',
    twitter: 'https://x.com/YangonAirport',
    instagram: 'https://www.instagram.com/yangonairport/',
    linkedin: 'https://www.linkedin.com/company/yangon-international-airport/',
    apiEndpoint: '',
  },
  NA: {
    name: 'Hosea Kutako International Airport (WDH)',
    website: 'https://www.airports.com.na/',
    email: 'info@airports.com.na',
    twitter: 'https://x.com/AirportsNamibia',
    instagram: 'https://www.instagram.com/airportsnamibia/',
    linkedin: 'https://www.linkedin.com/company/namibia-airports-company/',
    apiEndpoint: '',
  },
  NP: {
    name: 'Tribhuvan International Airport (KTM)',
    website: 'https://www.tiairport.com.np/',
    email: 'info@tiairport.com.np',
    twitter: 'https://x.com/TIAirport',
    instagram: 'https://www.instagram.com/tiairport/',
    linkedin: 'https://www.linkedin.com/company/tribhuvan-international-airport/',
    apiEndpoint: '',
  },
  NZ: {
    name: 'Auckland Airport (AKL)',
    website: 'https://www.aucklandairport.co.nz/',
    email: 'info@aucklandairport.co.nz',
    twitter: 'https://x.com/AucklandAirport',
    instagram: 'https://www.instagram.com/aucklandairport/',
    linkedin: 'https://www.linkedin.com/company/auckland-airport/',
    apiEndpoint: '',
  },
  NI: {
    name: 'Augusto C. Sandino International Airport (MGA)',
    website: 'https://www.eaai.com.ni/',
    email: 'info@eaai.com.ni',
    twitter: 'https://x.com/MGAAirport',
    instagram: 'https://www.instagram.com/mgaairport/',
    linkedin: 'https://www.linkedin.com/company/augusto-c-sandino-international-airport/',
    apiEndpoint: '',
  },
  NE: {
    name: 'Diori Hamani International Airport (NIM)',
    website: 'https://www.anac.ne/',
    email: 'contact@anac.ne',
    twitter: 'https://x.com/ANAC_Niger',
    instagram: 'https://www.instagram.com/anac_niger/',
    linkedin: 'https://www.linkedin.com/company/anac-niger/',
    apiEndpoint: '',
  },
  NG: {
    name: 'Murtala Muhammed International Airport (LOS)',
    website: 'https://www.faan.gov.ng/',
    email: 'info@faan.gov.ng',
    twitter: 'https://x.com/FAAN_Official',
    instagram: 'https://www.instagram.com/faan_official/',
    linkedin: 'https://www.linkedin.com/company/federal-airports-authority-of-nigeria/',
    apiEndpoint: '',
  },
  NU: {
    name: 'Niue International Airport (IUE)',
    website: 'https://www.niueairport.nu/',
    email: 'info@niueairport.nu',
    twitter: 'https://x.com/NiueAirport',
    instagram: 'https://www.instagram.com/niueairport/',
    linkedin: 'https://www.linkedin.com/company/niue-international-airport/',
    apiEndpoint: '',
  },
  MK: {
    name: 'Skopje International Airport (SKP)',
    website: 'https://www.skopjeairport.mk/',
    email: 'info@skopjeairport.mk',
    twitter: 'https://x.com/SkopjeAirport',
    instagram: 'https://www.instagram.com/skopjeairport/',
    linkedin: 'https://www.linkedin.com/company/skopje-international-airport/',
    apiEndpoint: '',
  },
  OM: {
    name: 'Muscat International Airport (MCT)',
    website: 'https://www.muscatairport.co.om/',
    email: 'info@muscatairport.co.om',
    twitter: 'https://x.com/MuscatAirport',
    instagram: 'https://www.instagram.com/muscatairport/',
    linkedin: 'https://www.linkedin.com/company/oman-airports/',
    apiEndpoint: '',
  },
  PK: {
    name: 'Jinnah International Airport (KHI)',
    website: 'https://www.karachiairport.com.pk/',
    email: 'info@karachiairport.com.pk',
    twitter: 'https://x.com/KarachiAirport',
    instagram: 'https://www.instagram.com/karachi_airport/',
    linkedin: 'https://www.linkedin.com/company/jinnah-international-airport/',
    apiEndpoint: '',
  },
  PA: {
    name: 'Tocumen International Airport (PTY)',
    website: 'https://www.tocumenpanama.aero/',
    email: 'info@tocumenpanama.aero',
    twitter: 'https://x.com/TocumenPTY',
    instagram: 'https://www.instagram.com/tocumenpty/',
    linkedin: 'https://www.linkedin.com/company/tocumen-international-airport/',
    apiEndpoint: '',
  },
  PG: {
    name: 'Jacksons International Airport (POM)',
    website: 'https://www.nac.com.pg/',
    email: 'info@nac.com.pg',
    twitter: 'https://x.com/NAC_PNG',
    instagram: 'https://www.instagram.com/nac_png/',
    linkedin: 'https://www.linkedin.com/company/national-airports-corporation-png/',
    apiEndpoint: '',
  },
  PE: {
    name: 'Jorge Chávez International Airport (LIM)',
    website: 'https://www.lima-airport.com/',
    email: 'info@lima-airport.com',
    twitter: 'https://x.com/LimaAirport',
    instagram: 'https://www.instagram.com/limaairport/',
    linkedin: 'https://www.linkedin.com/company/lima-airport-partners/',
    apiEndpoint: '',
  },
  PH: {
    name: 'Ninoy Aquino International Airport (MNL)',
    website: 'https://www.miaa.gov.ph/',
    email: 'info@miaa.gov.ph',
    twitter: 'https://x.com/MIAA_Official',
    instagram: 'https://www.instagram.com/miaa_official/',
    linkedin: 'https://www.linkedin.com/company/manila-international-airport-authority/',
    apiEndpoint: '',
  },
  PL: {
    name: 'Warsaw Chopin Airport (WAW)',
    website: 'https://www.lot.com/pl/en/warsaw-chopin-airport',
    email: 'info@chopin-airport.pl',
    twitter: 'https://x.com/ChopinAirport',
    instagram: 'https://www.instagram.com/chopinairport/',
    linkedin: 'https://www.linkedin.com/company/chopin-airport/',
    apiEndpoint: '',
  },
  PT: {
    name: 'Lisbon Humberto Delgado Airport (LIS)',
    website: 'https://www.ana.pt/',
    email: 'info@ana.pt',
    twitter: 'https://x.com/ANA_Aeroportos',
    instagram: 'https://www.instagram.com/ana_aeroportos/',
    linkedin: 'https://www.linkedin.com/company/ana-aeroportos-de-portugal/',
    apiEndpoint: '',
  },
  QA: {
    name: 'Hamad International Airport (DOH)',
    website: 'https://www.dohahamadairport.com/',
    email: 'info@dohahamadairport.com',
    twitter: 'https://x.com/HIAQatar',
    instagram: 'https://www.instagram.com/hiaqatar/',
    linkedin: 'https://www.linkedin.com/company/hamad-international-airport/',
    apiEndpoint: '',
  },
  CG: {
    name: 'Maya-Maya International Airport (BZV)',
    website: 'https://www.aeroport-brazzaville.cg/',
    email: 'contact@aeroport-brazzaville.cg',
    twitter: 'https://x.com/AeroportBZV',
    instagram: 'https://www.instagram.com/aeroportbrazzaville/',
    linkedin: 'https://www.linkedin.com/company/aeroport-maya-maya/',
    apiEndpoint: '',
  },
  RO: {
    name: 'Henri Coandă International Airport (OTP)',
    website: 'https://www.bucharestairports.ro/',
    email: 'info@bucharestairports.ro',
    twitter: 'https://x.com/BucharestAirport',
    instagram: 'https://www.instagram.com/bucharestairport/',
    linkedin: 'https://www.linkedin.com/company/bucharest-airports/',
    apiEndpoint: '',
  },
  RU: {
    name: 'Sheremetyevo International Airport (SVO)',
    website: 'https://www.svo.aero/',
    email: 'info@svo.aero',
    twitter: 'https://x.com/SVO_airport',
    instagram: 'https://www.instagram.com/svo_airport/',
    linkedin: 'https://www.linkedin.com/company/sheremetyevo-international-airport/',
    apiEndpoint: '',
  },
  RW: {
    name: 'Kigali International Airport (KGL)',
    website: 'https://www.rcaa.gov.rw/',
    email: 'info@rcaa.gov.rw',
    twitter: 'https://x.com/RCAA_Rwanda',
    instagram: 'https://www.instagram.com/rcaa_rwanda/',
    linkedin: 'https://www.linkedin.com/company/rwanda-civil-aviation-authority/',
    apiEndpoint: '',
  },
  WS: {
    name: 'Faleolo International Airport (APW)',
    website: 'https://www.samoaairports.ws/',
    email: 'info@samoaairports.ws',
    twitter: 'https://x.com/SamoaAirports',
    instagram: 'https://www.instagram.com/samoaairports/',
    linkedin: 'https://www.linkedin.com/company/samoa-airports-authority/',
    apiEndpoint: '',
  },
  SA: {
    name: 'King Khalid International Airport (RUH)',
    website: 'https://www.riyadhairports.com/',
    email: 'info@riyadhairports.com',
    twitter: 'https://x.com/RUH_Airport',
    instagram: 'https://www.instagram.com/ruh_airport/',
    linkedin: 'https://www.linkedin.com/company/riyadh-airports-company/',
    apiEndpoint: '',
  },
  SN: {
    name: 'Blaise Diagne International Airport (DSS)',
    website: 'https://www.aibd.sn/',
    email: 'contact@aibd.sn',
    twitter: 'https://x.com/AIBD_Airport',
    instagram: 'https://www.instagram.com/aibd_airport/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-blaise-diagne/',
    apiEndpoint: '',
  },
  RS: {
    name: 'Belgrade Nikola Tesla Airport (BEG)',
    website: 'https://www.beg.aero/',
    email: 'info@beg.aero',
    twitter: 'https://x.com/BEG_Airport',
    instagram: 'https://www.instagram.com/beg_airport/',
    linkedin: 'https://www.linkedin.com/company/belgrade-nikola-tesla-airport/',
    apiEndpoint: '',
  },
  SC: {
    name: 'Seychelles International Airport (SEZ)',
    website: 'https://www.scaa.sc/',
    email: 'info@scaa.sc',
    twitter: 'https://x.com/SCAA_Seychelles',
    instagram: 'https://www.instagram.com/scaa_seychelles/',
    linkedin: 'https://www.linkedin.com/company/seychelles-civil-aviation-authority/',
    apiEndpoint: '',
  },
  SL: {
    name: 'Freetown Lungi International Airport (FNA)',
    website: 'https://www.slac.gov.sl/',
    email: 'info@slac.gov.sl',
    twitter: 'https://x.com/SLAC_SierraLeone',
    instagram: 'https://www.instagram.com/slac_sierraleone/',
    linkedin: 'https://www.linkedin.com/company/sierra-leone-airports-authority/',
    apiEndpoint: '',
  },
  SG: {
    name: 'Singapore Changi Airport (SIN)',
    website: 'https://www.changiairport.com/',
    email: 'feedback@changiairport.com',
    twitter: 'https://x.com/ChangiAirport',
    instagram: 'https://www.instagram.com/changiairport/',
    linkedin: 'https://www.linkedin.com/company/changi-airport-group/',
    apiEndpoint: '',
  },
  SK: {
    name: 'M. R. Štefánik Airport (BTS)',
    website: 'https://www.airportbratislava.sk/',
    email: 'info@airportbratislava.sk',
    twitter: 'https://x.com/BTSairport',
    instagram: 'https://www.instagram.com/btsairport/',
    linkedin: 'https://www.linkedin.com/company/bratislava-airport/',
    apiEndpoint: '',
  },
  SI: {
    name: 'Ljubljana Jože Pučnik Airport (LJU)',
    website: 'https://www.lju-airport.si/',
    email: 'info@lju-airport.si',
    twitter: 'https://x.com/LJUairport',
    instagram: 'https://www.instagram.com/ljuairport/',
    linkedin: 'https://www.linkedin.com/company/ljubljana-airport/',
    apiEndpoint: '',
  },
  SB: {
    name: 'Honiara International Airport (HIR)',
    website: 'https://www.siac.com.sb/',
    email: 'info@siac.com.sb',
    twitter: 'https://x.com/SIAC_Solomon',
    instagram: 'https://www.instagram.com/siac_solomon/',
    linkedin: 'https://www.linkedin.com/company/solomon-islands-airports-corporation/',
    apiEndpoint: '',
  },
  SO: {
    name: 'Aden Adde International Airport (MGQ)',
    website: 'https://www.scaa.gov.so/',
    email: 'info@scaa.gov.so',
    twitter: 'https://x.com/SCAA_Somalia',
    instagram: 'https://www.instagram.com/scaa_somalia/',
    linkedin: 'https://www.linkedin.com/company/somalia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  ZA: {
    name: 'O.R. Tambo International Airport (JNB)',
    website: 'https://www.airports.co.za/',
    email: 'info@airports.co.za',
    twitter: 'https://x.com/Airports_ZA',
    instagram: 'https://www.instagram.com/airports_co_za/',
    linkedin: 'https://www.linkedin.com/company/airports-company-south-africa/',
    apiEndpoint: '',
  },
  SS: {
    name: 'Juba International Airport (JUB)',
    website: 'https://www.sscaa.gov.ss/',
    email: 'info@sscaa.gov.ss',
    twitter: 'https://x.com/SSCAA_SouthSudan',
    instagram: 'https://www.instagram.com/sscaa_southsudan/',
    linkedin: 'https://www.linkedin.com/company/south-sudan-civil-aviation-authority/',
    apiEndpoint: '',
  },
  LK: {
    name: 'Bandaranaike International Airport (CMB)',
    website: 'https://www.airport.lk/',
    email: 'info@airport.lk',
    twitter: 'https://x.com/BandaranaikeAP',
    instagram: 'https://www.instagram.com/bandaranaikeap/',
    linkedin: 'https://www.linkedin.com/company/bandaranaike-international-airport/',
    apiEndpoint: '',
  },
  SD: {
    name: 'Khartoum International Airport (KRT)',
    website: 'https://www.krtairport.gov.sd/',
    email: 'info@krtairport.gov.sd',
    twitter: 'https://x.com/KRTAirport',
    instagram: 'https://www.instagram.com/krtairport/',
    linkedin: 'https://www.linkedin.com/company/khartoum-international-airport/',
    apiEndpoint: '',
  },
  SR: {
    name: 'Johan Adolf Pengel International Airport (PBM)',
    website: 'https://www.jap-airport.com/',
    email: 'info@jap-airport.com',
    twitter: 'https://x.com/JAPAirport',
    instagram: 'https://www.instagram.com/japairport/',
    linkedin: 'https://www.linkedin.com/company/johan-adolf-pengel-international-airport/',
    apiEndpoint: '',
  },
  SY: {
    name: 'Damascus International Airport (DAM)',
    website: 'https://www.damascus-airport.com/',
    email: 'info@damascus-airport.com',
    twitter: 'https://x.com/DamascusAirport',
    instagram: 'https://www.instagram.com/damascusairport/',
    linkedin: 'https://www.linkedin.com/company/damascus-international-airport/',
    apiEndpoint: '',
  },
  TJ: {
    name: 'Dushanbe International Airport (DYU)',
    website: 'https://www.airport.tj/',
    email: 'info@airport.tj',
    twitter: 'https://x.com/DushanbeAirport',
    instagram: 'https://www.instagram.com/dushanbeairport/',
    linkedin: 'https://www.linkedin.com/company/dushanbe-international-airport/',
    apiEndpoint: '',
  },
  TZ: {
    name: 'Julius Nyerere International Airport (DAR)',
    website: 'https://www.taa.go.tz/',
    email: 'info@taa.go.tz',
    twitter: 'https://x.com/TAA_Tanzania',
    instagram: 'https://www.instagram.com/taa_tanzania/',
    linkedin: 'https://www.linkedin.com/company/tanzania-airports-authority/',
    apiEndpoint: '',
  },
  TH: {
    name: 'Suvarnabhumi Airport (BKK)',
    website: 'https://suvarnabhumi.airportthai.co.th/',
    email: 'info@airportthai.co.th',
    twitter: 'https://x.com/AOT_BKK',
    instagram: 'https://www.instagram.com/suvarnabhumi_airport/',
    linkedin: 'https://www.linkedin.com/company/airports-of-thailand/',
    apiEndpoint: '',
  },
  TL: {
    name: 'Presidente Nicolau Lobato International Airport (DIL)',
    website: 'https://www.aeroportodili.tl/',
    email: 'info@aeroportodili.tl',
    twitter: 'https://x.com/DiliAirport',
    instagram: 'https://www.instagram.com/diliairport/',
    linkedin: 'https://www.linkedin.com/company/dili-international-airport/',
    apiEndpoint: '',
  },
  TG: {
    name: 'Lomé-Tokoin International Airport (LFW)',
    website: 'https://www.aeroport-lome.tg/',
    email: 'contact@aeroport-lome.tg',
    twitter: 'https://x.com/AeroportLFW',
    instagram: 'https://www.instagram.com/aeroportlfw/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-lome/',
    apiEndpoint: '',
  },
  TO: {
    name: 'Fua\'amotu International Airport (TBU)',
    website: 'https://www.tongaairports.com/',
    email: 'info@tongaairports.com',
    twitter: 'https://x.com/TongaAirports',
    instagram: 'https://www.instagram.com/tongaairports/',
    linkedin: 'https://www.linkedin.com/company/tonga-airports-limited/',
    apiEndpoint: '',
  },
  TT: {
    name: 'Piarco International Airport (POS)',
    website: 'https://www.tntairports.com/',
    email: 'info@tntairports.com',
    twitter: 'https://x.com/TNTAirports',
    instagram: 'https://www.instagram.com/tntairports/',
    linkedin: 'https://www.linkedin.com/company/trinidad-and-tobago-airports-authority/',
    apiEndpoint: '',
  },
  TN: {
    name: 'Tunis-Carthage International Airport (TUN)',
    website: 'https://www.oaca.nat.tn/',
    email: 'contact@oaca.nat.tn',
    twitter: 'https://x.com/OACA_Tunisia',
    instagram: 'https://www.instagram.com/oaca_tunisia/',
    linkedin: 'https://www.linkedin.com/company/office-de-l-aviation-civile-et-des-aeroports-oaca/',
    apiEndpoint: '',
  },
  TR: {
    name: 'Istanbul Airport (IST)',
    website: 'https://www.istairport.com/',
    email: 'info@istairport.com',
    twitter: 'https://x.com/istanbulairport',
    instagram: 'https://www.instagram.com/istanbulairport/',
    linkedin: 'https://www.linkedin.com/company/istanbul-airport/',
    apiEndpoint: '',
  },
  TM: {
    name: 'Ashgabat International Airport (ASB)',
    website: 'https://www.airport.gov.tm/',
    email: 'info@airport.gov.tm',
    twitter: 'https://x.com/AshgabatAirport',
    instagram: 'https://www.instagram.com/ashgabatairport/',
    linkedin: 'https://www.linkedin.com/company/ashgabat-international-airport/',
    apiEndpoint: '',
  },
  UG: {
    name: 'Entebbe International Airport (EBB)',
    website: 'https://www.caa.co.ug/',
    email: 'info@caa.co.ug',
    twitter: 'https://x.com/CAA_Uganda',
    instagram: 'https://www.instagram.com/caa_uganda/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-uganda/',
    apiEndpoint: '',
  },
  UA: {
    name: 'Boryspil International Airport (KBP)',
    website: 'https://www.kbp.aero/',
    email: 'info@kbp.aero',
    twitter: 'https://x.com/BoryspilAirport',
    instagram: 'https://www.instagram.com/boryspilairport/',
    linkedin: 'https://www.linkedin.com/company/boryspil-international-airport/',
    apiEndpoint: '',
  },
  AE: {
    name: 'Zayed International Airport (AUH)',
    website: 'https://www.zayedinternationalairport.ae/',
    email: 'info@adairports.ae',
    twitter: 'https://x.com/ZayedAirport',
    instagram: 'https://www.instagram.com/zayedairport/',
    linkedin: 'https://www.linkedin.com/company/abu-dhabi-airports/',
    apiEndpoint: '',
  },
  UY: {
    name: 'Carrasco International Airport (MVD)',
    website: 'https://www.aeropuertodecarrasco.com.uy/',
    email: 'info@aeropuertodecarrasco.com.uy',
    twitter: 'https://x.com/CarrascoAirport',
    instagram: 'https://www.instagram.com/carrascoairport/',
    linkedin: 'https://www.linkedin.com/company/carrasco-international-airport/',
    apiEndpoint: '',
  },
  UZ: {
    name: 'Tashkent International Airport (TAS)',
    website: 'https://www.uzairports.uz/',
    email: 'info@uzairports.uz',
    twitter: 'https://x.com/TashkentAirport',
    instagram: 'https://www.instagram.com/tashkentairport/',
    linkedin: 'https://www.linkedin.com/company/tashkent-international-airport/',
    apiEndpoint: '',
  },
  VU: {
    name: 'Bauerfield International Airport (VLI)',
    website: 'https://www.airports.vu/',
    email: 'info@airports.vu',
    twitter: 'https://x.com/VanuatuAirports',
    instagram: 'https://www.instagram.com/vanuatuairports/',
    linkedin: 'https://www.linkedin.com/company/airports-vanuatu/',
    apiEndpoint: '',
  },
  VE: {
    name: 'Simón Bolívar International Airport (CCS)',
    website: 'https://www.aeropuerto-maiquetia.com.ve/',
    email: 'info@aeropuerto-maiquetia.com.ve',
    twitter: 'https://x.com/CCSAirport',
    instagram: 'https://www.instagram.com/ccsairport/',
    linkedin: 'https://www.linkedin.com/company/simon-bolivar-international-airport/',
    apiEndpoint: '',
  },
  VN: {
    name: 'Noi Bai International Airport (HAN)',
    website: 'https://www.noibaiairport.vn/',
    email: 'info@noibaiairport.vn',
    twitter: 'https://x.com/NoiBaiAirport',
    instagram: 'https://www.instagram.com/noibaiairport/',
    linkedin: 'https://www.linkedin.com/company/noi-bai-international-airport/',
    apiEndpoint: '',
  },
  YE: {
    name: 'Sana\'a International Airport (SAH)',
    website: 'https://www.yemenia.com/',
    email: 'info@yemenia.com',
    twitter: 'https://x.com/YemeniaAir',
    instagram: 'https://www.instagram.com/yemeniaair/',
    linkedin: 'https://www.linkedin.com/company/yemen-airways/',
    apiEndpoint: '',
  },
  ZM: {
    name: 'Kenneth Kaunda International Airport (LUN)',
    website: 'https://www.zacl.co.zm/',
    email: 'info@zacl.co.zm',
    twitter: 'https://x.com/ZACL_Airports',
    instagram: 'https://www.instagram.com/zacl_airports/',
    linkedin: 'https://www.linkedin.com/company/zambia-airports-corporation-limited/',
    apiEndpoint: '',
  },
  ZW: {
    name: 'Robert Gabriel Mugabe International Airport (HRE)',
    website: 'https://www.caaz.co.zw/',
    email: 'info@caaz.co.zw',
    twitter: 'https://x.com/CAAZ_Zimbabwe',
    instagram: 'https://www.instagram.com/caaz_zimbabwe/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-zimbabwe/',
    apiEndpoint: '',
  },
}
