import type { BriMemberIsoCode } from './participantStatesIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2 for BRI
 * partner countries (informational; verify against USGS Mineral Commodity Summaries, BGS World
 * Mineral Production, and UN Comtrade periodically). Hydrocarbon-led economies carry `Carbon (C)`
 * + `Hydrogen (H)`; semiconductor / wafer hubs carry `Silicon (Si)`; smelter economies carry
 * `Aluminum (Al)`. Diamond / coal / graphite producers carry `Carbon (C)`.
 */
export const BRI_MAIN_EXPORTED_ELEMENTS: Record<BriMemberIsoCode, MainExportedElements> = {
  AF: e(
    'Iron (Fe)',
    'Copper (Cu)',
    'Lithium (Li)',
    'Chromium (Cr)',
    'Gold (Au)',
    'Carbon (C)',
    'Beryllium (Be)',
  ),
  AL: e(
    'Chromium (Cr)',
    'Copper (Cu)',
    'Nickel (Ni)',
    'Iron (Fe)',
    'Carbon (C)',
    'Calcium (Ca)',
    'Hydrogen (H)',
  ),
  DZ: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Helium (He)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Mercury (Hg)',
  ),
  AO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Gold (Au)',
    'Copper (Cu)',
    'Phosphorus (P)',
  ),
  AG: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Chlorine (Cl)',
  ),
  AR: e(
    'Lithium (Li)',
    'Gold (Au)',
    'Silver (Ag)',
    'Copper (Cu)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Boron (B)',
  ),
  AM: e(
    'Copper (Cu)',
    'Molybdenum (Mo)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Iron (Fe)',
  ),
  AT: e(
    'Iron (Fe)',
    'Magnesium (Mg)',
    'Tungsten (W)',
    'Copper (Cu)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Zinc (Zn)',
  ),
  AZ: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Copper (Cu)',
  ),
  BH: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  BD: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Aluminum (Al)',
  ),
  BB: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  BY: e(
    'Potassium (K)',
    'Nitrogen (N)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Phosphorus (P)',
  ),
  BJ: e(
    'Calcium (Ca)',
    'Carbon (C)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Sodium (Na)',
  ),
  BO: e(
    'Tin (Sn)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Gold (Au)',
    'Antimony (Sb)',
    'Lithium (Li)',
  ),
  BA: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Carbon (C)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Silicon (Si)',
  ),
  BW: e(
    'Carbon (C)',
    'Copper (Cu)',
    'Nickel (Ni)',
    'Gold (Au)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Sulfur (S)',
  ),
  BN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  BG: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  BI: e(
    'Gold (Au)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Tantalum (Ta)',
    'Niobium (Nb)',
    'Nickel (Ni)',
    'Iron (Fe)',
  ),
  CV: e(
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  KH: e(
    'Iron (Fe)',
    'Manganese (Mn)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  CM: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Cobalt (Co)',
    'Manganese (Mn)',
    'Gold (Au)',
  ),
  CF: e(
    'Carbon (C)',
    'Gold (Au)',
    'Iron (Fe)',
    'Uranium (U)',
    'Copper (Cu)',
    'Manganese (Mn)',
    'Cobalt (Co)',
  ),
  TD: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Gold (Au)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  CL: e(
    'Copper (Cu)',
    'Lithium (Li)',
    'Molybdenum (Mo)',
    'Iron (Fe)',
    'Silver (Ag)',
    'Gold (Au)',
    'Boron (B)',
  ),
  CN: e(
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Tungsten (W)',
    'Antimony (Sb)',
  ),
  CO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Gold (Au)',
    'Nickel (Ni)',
    'Silver (Ag)',
    'Beryllium (Be)',
    'Copper (Cu)',
  ),
  KM: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Magnesium (Mg)',
    'Sulfur (S)',
  ),
  CK: e(
    'Manganese (Mn)',
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
  ),
  CR: e(
    'Silicon (Si)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Carbon (C)',
  ),
  CI: e(
    'Gold (Au)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Manganese (Mn)',
    'Nickel (Ni)',
    'Aluminum (Al)',
    'Iron (Fe)',
  ),
  HR: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Magnesium (Mg)',
  ),
  CU: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Copper (Cu)',
    'Iron (Fe)',
    'Chromium (Cr)',
    'Gold (Au)',
    'Sulfur (S)',
  ),
  CY: e(
    'Copper (Cu)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Sodium (Na)',
  ),
  CZ: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Carbon (C)',
    'Copper (Cu)',
    'Uranium (U)',
    'Magnesium (Mg)',
  ),
  CD: e(
    'Cobalt (Co)',
    'Copper (Cu)',
    'Carbon (C)',
    'Gold (Au)',
    'Tin (Sn)',
    'Tantalum (Ta)',
    'Germanium (Ge)',
  ),
  DJ: e(
    'Sodium (Na)',
    'Chlorine (Cl)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Sulfur (S)',
  ),
  DM: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  DO: e(
    'Gold (Au)',
    'Silver (Ag)',
    'Nickel (Ni)',
    'Copper (Cu)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  EC: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Sulfur (S)',
    'Molybdenum (Mo)',
  ),
  EG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Titanium (Ti)',
  ),
  SV: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
    'Carbon (C)',
  ),
  GQ: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Gold (Au)',
    'Iron (Fe)',
    'Titanium (Ti)',
    'Aluminum (Al)',
  ),
  ER: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Silver (Ag)',
    'Potassium (K)',
    'Iron (Fe)',
    'Sulfur (S)',
  ),
  EE: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  ET: e(
    'Gold (Au)',
    'Tantalum (Ta)',
    'Potassium (K)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Platinum (Pt)',
    'Calcium (Ca)',
  ),
  FJ: e(
    'Gold (Au)',
    'Silver (Ag)',
    'Copper (Cu)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Silicon (Si)',
  ),
  GA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Manganese (Mn)',
    'Gold (Au)',
    'Iron (Fe)',
    'Niobium (Nb)',
    'Uranium (U)',
  ),
  GM: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Calcium (Ca)',
  ),
  GE: e(
    'Manganese (Mn)',
    'Copper (Cu)',
    'Gold (Au)',
    'Iron (Fe)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Aluminum (Al)',
  ),
  GH: e(
    'Gold (Au)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Lithium (Li)',
    'Iron (Fe)',
  ),
  GR: e(
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Magnesium (Mg)',
    'Silver (Ag)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Iron (Fe)',
  ),
  GD: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  GN: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Carbon (C)',
    'Uranium (U)',
    'Copper (Cu)',
    'Calcium (Ca)',
  ),
  GW: e(
    'Phosphorus (P)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  GY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Manganese (Mn)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  HN: e(
    'Silver (Ag)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Gold (Au)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Calcium (Ca)',
  ),
  HU: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Manganese (Mn)',
    'Magnesium (Mg)',
    'Carbon (C)',
  ),
  ID: e(
    'Carbon (C)',
    'Nickel (Ni)',
    'Copper (Cu)',
    'Tin (Sn)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Hydrogen (H)',
  ),
  IR: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Zinc (Zn)',
  ),
  IQ: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  IT: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Lead (Pb)',
    'Zinc (Zn)',
  ),
  JM: e(
    'Aluminum (Al)',
    'Gold (Au)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Magnesium (Mg)',
    'Sulfur (S)',
  ),
  JO: e(
    'Phosphorus (P)',
    'Potassium (K)',
    'Bromine (Br)',
    'Sulfur (S)',
    'Calcium (Ca)',
    'Magnesium (Mg)',
    'Iron (Fe)',
  ),
  KZ: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Uranium (U)',
    'Chromium (Cr)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Iron (Fe)',
  ),
  KE: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Sodium (Na)',
    'Fluorine (F)',
    'Gold (Au)',
    'Niobium (Nb)',
    'Calcium (Ca)',
  ),
  KI: e(
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Aluminum (Al)',
  ),
  KW: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  KG: e(
    'Gold (Au)',
    'Mercury (Hg)',
    'Antimony (Sb)',
    'Silver (Ag)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Uranium (U)',
  ),
  LA: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Tin (Sn)',
    'Iron (Fe)',
    'Potassium (K)',
    'Silver (Ag)',
    'Zinc (Zn)',
  ),
  LV: e(
    'Carbon (C)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  LB: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
    'Carbon (C)',
  ),
  LS: e(
    'Carbon (C)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  LR: e(
    'Iron (Fe)',
    'Gold (Au)',
    'Carbon (C)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Silver (Ag)',
  ),
  LY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Potassium (K)',
    'Phosphorus (P)',
    'Calcium (Ca)',
  ),
  LT: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Nitrogen (N)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
  ),
  LU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Carbon (C)',
    'Magnesium (Mg)',
    'Zinc (Zn)',
  ),
  MG: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Titanium (Ti)',
    'Carbon (C)',
    'Chromium (Cr)',
    'Gold (Au)',
    'Zirconium (Zr)',
  ),
  MW: e(
    'Uranium (U)',
    'Niobium (Nb)',
    'Tantalum (Ta)',
    'Titanium (Ti)',
    'Iron (Fe)',
    'Gold (Au)',
    'Calcium (Ca)',
  ),
  MY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Silicon (Si)',
  ),
  MV: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  ML: e(
    'Gold (Au)',
    'Lithium (Li)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Phosphorus (P)',
  ),
  MT: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  MR: e(
    'Iron (Fe)',
    'Gold (Au)',
    'Copper (Cu)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Sodium (Na)',
  ),
  FM: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  MD: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  MN: e(
    'Copper (Cu)',
    'Carbon (C)',
    'Gold (Au)',
    'Molybdenum (Mo)',
    'Iron (Fe)',
    'Fluorine (F)',
    'Uranium (U)',
  ),
  ME: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Calcium (Ca)',
    'Silicon (Si)',
  ),
  MA: e(
    'Phosphorus (P)',
    'Fluorine (F)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Cobalt (Co)',
  ),
  MZ: e(
    'Aluminum (Al)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Gold (Au)',
    'Iron (Fe)',
  ),
  MM: e(
    'Tin (Sn)',
    'Tungsten (W)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Carbon (C)',
    'Antimony (Sb)',
  ),
  NA: e(
    'Uranium (U)',
    'Carbon (C)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Gold (Au)',
    'Lithium (Li)',
    'Lead (Pb)',
  ),
  NP: e(
    'Magnesium (Mg)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Carbon (C)',
  ),
  NZ: e(
    'Gold (Au)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Carbon (C)',
    'Silver (Ag)',
    'Hydrogen (H)',
    'Titanium (Ti)',
  ),
  NI: e(
    'Gold (Au)',
    'Silver (Ag)',
    'Copper (Cu)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Iron (Fe)',
    'Calcium (Ca)',
  ),
  NE: e(
    'Uranium (U)',
    'Gold (Au)',
    'Carbon (C)',
    'Iron (Fe)',
    'Tin (Sn)',
    'Phosphorus (P)',
    'Molybdenum (Mo)',
  ),
  NG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Tantalum (Ta)',
    'Niobium (Nb)',
    'Lead (Pb)',
    'Gold (Au)',
  ),
  NU: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  MK: e(
    'Copper (Cu)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Gold (Au)',
    'Iron (Fe)',
    'Silver (Ag)',
    'Calcium (Ca)',
  ),
  OM: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Copper (Cu)',
    'Aluminum (Al)',
    'Chromium (Cr)',
    'Iron (Fe)',
  ),
  PK: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Chromium (Cr)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  PA: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Molybdenum (Mo)',
    'Manganese (Mn)',
    'Iron (Fe)',
    'Calcium (Ca)',
  ),
  PG: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Carbon (C)',
    'Hydrogen (H)',
  ),
  PE: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Silver (Ag)',
    'Zinc (Zn)',
    'Lead (Pb)',
    'Tin (Sn)',
    'Molybdenum (Mo)',
  ),
  PH: e(
    'Nickel (Ni)',
    'Copper (Cu)',
    'Gold (Au)',
    'Iron (Fe)',
    'Chromium (Cr)',
    'Cobalt (Co)',
    'Silver (Ag)',
  ),
  PL: e(
    'Copper (Cu)',
    'Silver (Ag)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Sulfur (S)',
  ),
  PT: e(
    'Copper (Cu)',
    'Tungsten (W)',
    'Tin (Sn)',
    'Lithium (Li)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Lead (Pb)',
  ),
  QA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Helium (He)',
    'Sulfur (S)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silicon (Si)',
  ),
  CG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Potassium (K)',
    'Iron (Fe)',
    'Gold (Au)',
    'Copper (Cu)',
    'Phosphorus (P)',
  ),
  RO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Gold (Au)',
    'Sulfur (S)',
  ),
  RU: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Palladium (Pd)',
    'Platinum (Pt)',
    'Nickel (Ni)',
    'Aluminum (Al)',
    'Iron (Fe)',
  ),
  RW: e(
    'Tantalum (Ta)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Gold (Au)',
    'Niobium (Nb)',
    'Beryllium (Be)',
    'Iron (Fe)',
  ),
  WS: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  SA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Helium (He)',
    'Phosphorus (P)',
    'Aluminum (Al)',
    'Gold (Au)',
  ),
  SN: e(
    'Phosphorus (P)',
    'Gold (Au)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
  ),
  RS: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Lithium (Li)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Antimony (Sb)',
    'Iron (Fe)',
  ),
  SC: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  SL: e(
    'Iron (Fe)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Carbon (C)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Manganese (Mn)',
  ),
  SG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Silicon (Si)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
  ),
  SK: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Carbon (C)',
    'Magnesium (Mg)',
    'Gold (Au)',
  ),
  SI: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Mercury (Hg)',
  ),
  SB: e(
    'Gold (Au)',
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  SO: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Sodium (Na)',
    'Magnesium (Mg)',
  ),
  ZA: e(
    'Platinum (Pt)',
    'Palladium (Pd)',
    'Gold (Au)',
    'Chromium (Cr)',
    'Manganese (Mn)',
    'Carbon (C)',
    'Iron (Fe)',
  ),
  SS: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Gold (Au)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  LK: e(
    'Carbon (C)',
    'Aluminum (Al)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Manganese (Mn)',
  ),
  SD: e(
    'Gold (Au)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Chromium (Cr)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Sulfur (S)',
  ),
  SR: e(
    'Gold (Au)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silver (Ag)',
    'Copper (Cu)',
  ),
  SY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Aluminum (Al)',
  ),
  TJ: e(
    'Aluminum (Al)',
    'Antimony (Sb)',
    'Gold (Au)',
    'Silver (Ag)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Uranium (U)',
  ),
  TZ: e(
    'Gold (Au)',
    'Carbon (C)',
    'Nickel (Ni)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Titanium (Ti)',
    'Niobium (Nb)',
  ),
  TH: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Gold (Au)',
    'Silicon (Si)',
  ),
  TL: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
  ),
  TG: e(
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Carbon (C)',
  ),
  TO: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  TT: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Nitrogen (N)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  TN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Fluorine (F)',
  ),
  TR: e(
    'Chromium (Cr)',
    'Boron (B)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Gold (Au)',
    'Calcium (Ca)',
    'Magnesium (Mg)',
  ),
  TM: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Potassium (K)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  UG: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Cobalt (Co)',
    'Iron (Fe)',
    'Phosphorus (P)',
  ),
  UA: e(
    'Iron (Fe)',
    'Manganese (Mn)',
    'Titanium (Ti)',
    'Carbon (C)',
    'Uranium (U)',
    'Zirconium (Zr)',
    'Aluminum (Al)',
  ),
  AE: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Gold (Au)',
  ),
  UY: e(
    'Gold (Au)',
    'Silver (Ag)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Sodium (Na)',
  ),
  UZ: e(
    'Gold (Au)',
    'Uranium (U)',
    'Copper (Cu)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Silver (Ag)',
    'Molybdenum (Mo)',
  ),
  VU: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  VE: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Niobium (Nb)',
  ),
  VN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Copper (Cu)',
    'Tin (Sn)',
  ),
  YE: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Gold (Au)',
    'Silver (Ag)',
    'Calcium (Ca)',
    'Copper (Cu)',
  ),
  ZM: e(
    'Copper (Cu)',
    'Cobalt (Co)',
    'Gold (Au)',
    'Manganese (Mn)',
    'Nickel (Ni)',
    'Beryllium (Be)',
    'Iron (Fe)',
  ),
  ZW: e(
    'Platinum (Pt)',
    'Gold (Au)',
    'Carbon (C)',
    'Chromium (Cr)',
    'Nickel (Ni)',
    'Lithium (Li)',
    'Cobalt (Co)',
  ),
}
