import type { BriMemberIsoCode } from './participantStatesIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const BRI_MAIN_EXPORT_COMMODITIES: Record<BriMemberIsoCode, MainExportCommodities> = {
  AF: m(
    'Dried fruits',
    'Carpets',
    'Precious stones',
    'Copper ore',
    'Hides and skins',
    'Grapes',
    'Herbs',
  ),
  AL: m(
    'Footwear',
    'Garments',
    'Chromium ore',
    'Electricity',
    'Oil seeds',
    'Tobacco',
    'Copper',
  ),
  DZ: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Fertilizers',
    'Hydrocarbon derivatives',
    'Dates',
    'Wheat',
  ),
  AO: m(
    'Crude petroleum',
    'Diamonds',
    'Refined petroleum',
    'Liquified natural gas',
    'Ships',
    'Iron ore',
    'Copper ore',
  ),
  AG: m(
    'Tourism services',
    'Passenger ships',
    'Rum',
    'Fruit',
    'Fish',
    'Bed linen',
    'Electronics',
  ),
  AR: m(
    'Soybeans',
    'Corn',
    'Wheat',
    'Beef',
    'Gold',
    'Petroleum products',
    'Automobiles',
  ),
  AM: m(
    'Copper ore',
    'Gold',
    'Tobacco',
    'Brandy',
    'Textiles',
    'Precious stones',
    'Food products',
  ),
  AT: m(
    'Machinery',
    'Automobiles',
    'Pharmaceuticals',
    'Paper',
    'Iron and steel',
    'Wood products',
    'Electricity',
  ),
  AZ: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Tomatoes',
    'Gold',
    'Cotton',
    'Plastics',
  ),
  BH: m(
    'Refined petroleum',
    'Aluminium',
    'Petrochemicals',
    'Fertilizers',
    'Iron ore',
    'Plastics',
    'Financial services exports',
  ),
  BD: m(
    'Garments',
    'Jute',
    'Leather goods',
    'Fish',
    'Home textiles',
    'Footwear',
    'Rice',
  ),
  BB: m(
    'Rum',
    'Sugar',
    'Tourism services',
    'Chemicals',
    'Electronics',
    'Fish',
    'Manufactured goods',
  ),
  BY: m(
    'Potassium fertilizers',
    'Refined petroleum',
    'Tractors',
    'Dairy products',
    'Machinery',
    'Wood products',
    'Steel',
  ),
  BJ: m(
    'Cotton',
    'Gold',
    'Cashew nuts',
    'Refined petroleum',
    'Palm oil',
    'Soybeans',
    'Maize',
  ),
  BO: m(
    'Natural gas',
    'Gold',
    'Zinc ore',
    'Soybeans',
    'Silver',
    'Tin',
    'Quinoa',
  ),
  BA: m(
    'Electricity',
    'Aluminium',
    'Furniture',
    'Footwear',
    'Wood products',
    'Iron and steel',
    'Textiles',
  ),
  BW: m(
    'Diamonds',
    'Copper ore',
    'Beef',
    'Carbonates',
    'Live cattle',
    'Machinery parts',
    'Salt',
  ),
  BN: m(
    'Crude petroleum',
    'Liquified natural gas',
    'Refined petroleum',
    'Chemicals',
    'Fish',
    'Garments',
    'Plastics',
  ),
  BG: m(
    'Refined copper',
    'Wheat',
    'Sunflower oil',
    'Medicaments',
    'Iron and steel',
    'Electricity',
    'Packaged medicaments',
  ),
  BI: m(
    'Coffee',
    'Gold',
    'Tea',
    'Niobium and tantalum ore',
    'Cobalt',
    'Hides and skins',
    'Wheat flour',
  ),
  CV: m(
    'Fish',
    'Footwear',
    'Garments',
    'Petroleum products',
    'Electronics',
    'Plastic products',
    'Beverages',
  ),
  KH: m(
    'Garments',
    'Footwear',
    'Rice',
    'Rubber',
    'Timber',
    'Fish',
    'Cassava',
  ),
  CM: m(
    'Crude petroleum',
    'Timber',
    'Cocoa',
    'Cotton',
    'Aluminum',
    'Coffee',
    'Bananas',
  ),
  CF: m(
    'Gold',
    'Diamonds',
    'Timber',
    'Cotton',
    'Hides and skins',
    'Sesame seeds',
    'Coffee',
  ),
  TD: m(
    'Crude petroleum',
    'Cotton',
    'Livestock',
    'Gum arabic',
    'Sesame seeds',
    'Gold',
    'Hides and skins',
  ),
  CL: m(
    'Copper',
    'Refined copper',
    'Fruits (cherries)',
    'Salmon',
    'Wine',
    'Wood pulp',
    'Lithium',
  ),
  CN: m(
    'Electrical machinery',
    'Computers',
    'Telecommunications equipment',
    'Furniture',
    'Plastics',
    'Apparel',
    'Steel',
  ),
  CO: m(
    'Crude petroleum',
    'Coal',
    'Coffee',
    'Gold',
    'Bananas',
    'Cut flowers',
    'Refined petroleum',
  ),
  KM: m(
    'Vanilla',
    'Cloves',
    'Ylang-ylang',
    'Fish',
    'Essential oils',
    'Copra',
    'Pepper',
  ),
  CK: m(
    'Fish',
    'Pearls',
    'Fruit',
    'Copra',
    'Tourism services',
    'Black pearls',
    'Clothing',
  ),
  CR: m(
    'Medical instruments',
    'Bananas',
    'Pineapples',
    'Coffee',
    'Melons',
    'Orthopedic appliances',
    'Fruit juice',
  ),
  CI: m(
    'Cocoa',
    'Gold',
    'Refined petroleum',
    'Rubber',
    'Cashew nuts',
    'Cotton',
    'Palm oil',
  ),
  HR: m(
    'Electricity',
    'Packaged medicaments',
    'Refined petroleum',
    'Fish',
    'Wood products',
    'Machinery',
    'Tourism services',
  ),
  CU: m(
    'Raw sugar',
    'Nickel',
    'Tobacco',
    'Zinc',
    'Pharmaceuticals',
    'Rum',
    'Fish',
  ),
  CY: m(
    'Refined petroleum',
    'Cheese',
    'Packaged medicaments',
    'Fish',
    'Halloumi',
    'Potatoes',
    'Tourism services',
  ),
  CZ: m(
    'Automobiles',
    'Machinery',
    'Electricity',
    'Packaged medicaments',
    'Computers',
    'Iron and steel',
    'Plastics',
  ),
  CD: m(
    'Copper',
    'Cobalt',
    'Gold',
    'Crude petroleum',
    'Diamonds',
    'Copper ore',
    'Refined copper',
  ),
  DJ: m(
    'Live animals',
    'Coffee',
    'Hides and skins',
    'Salt',
    'Scrap metal',
    'Re-exported goods',
    'Petroleum re-exports',
  ),
  DM: m(
    'Bananas',
    'Soap',
    'Tourism services',
    'Citrus fruit',
    'Vegetables',
    'Cocoa',
    'Manufactured goods',
  ),
  DO: m(
    'Gold',
    'Medical instruments',
    'Tobacco',
    'Bananas',
    'Textiles',
    'Rum',
    'Cocoa',
  ),
  EC: m(
    'Crude petroleum',
    'Bananas',
    'Shrimp',
    'Cocoa',
    'Fish',
    'Cut flowers',
    'Gold',
  ),
  EG: m(
    'Refined petroleum',
    'Natural gas',
    'Gold',
    'Fertilizers',
    'Textiles and garments',
    'Citrus fruit',
    'Aluminum',
  ),
  SV: m(
    'Textiles',
    'Coffee',
    'Sugar',
    'Gold',
    'Electricity',
    'Paper',
    'Medicaments',
  ),
  GQ: m(
    'Crude petroleum',
    'Liquified natural gas',
    'Timber',
    'Cocoa',
    'Fish',
    'Methanol',
    'Timber products',
  ),
  ER: m(
    'Copper ore',
    'Gold',
    'Livestock',
    'Textiles',
    'Food products',
    'Salt',
    'Hides and skins',
  ),
  EE: m(
    'Telecommunications equipment',
    'Wood products',
    'Electrical machinery',
    'Refined petroleum',
    'Fish',
    'Computers',
    'Grain',
  ),
  ET: m(
    'Coffee',
    'Gold',
    'Oil seeds',
    'Cut flowers',
    'Livestock',
    'Garments',
    'Pulses',
  ),
  FJ: m(
    'Water',
    'Fish',
    'Sugar',
    'Gold',
    'Timber',
    'Garments',
    'Mineral water',
  ),
  GA: m(
    'Crude petroleum',
    'Manganese ore',
    'Timber',
    'Refined petroleum',
    'Uranium',
    'Gold',
    'Palm oil',
  ),
  GM: m(
    'Groundnuts',
    'Fish',
    'Cotton',
    'Timber',
    'Palm kernels',
    'Petroleum products',
    'Re-exported goods',
  ),
  GE: m(
    'Copper ore',
    'Wine',
    'Ferroalloys',
    'Gold',
    'Nuts',
    'Mineral water',
    'Machinery',
  ),
  GH: m(
    'Gold',
    'Crude petroleum',
    'Cocoa',
    'Cashew nuts',
    'Manganese ore',
    'Oil seeds',
    'Refined petroleum',
  ),
  GR: m(
    'Refined petroleum',
    'Packaged medicaments',
    'Fish',
    'Aluminium',
    'Olive oil',
    'Vegetables',
    'Tourism services',
  ),
  GD: m(
    'Nutmeg',
    'Cocoa',
    'Fish',
    'Tourism services',
    'Mace',
    'Bananas',
    'Manufactured goods',
  ),
  GN: m(
    'Gold',
    'Bauxite',
    'Aluminum',
    'Diamonds',
    'Palm oil',
    'Coffee',
    'Fruits',
  ),
  GW: m(
    'Cashew nuts',
    'Fish',
    'Gold',
    'Timber',
    'Palm oil',
    'Cotton',
    'Peanuts',
  ),
  GY: m(
    'Gold',
    'Rice',
    'Bauxite',
    'Sugar',
    'Shrimp',
    'Timber',
    'Aluminium ore',
  ),
  HN: m(
    'Coffee',
    'Bananas',
    'Palm oil',
    'Shrimp',
    'Melons',
    'Apparel',
    'Gold',
  ),
  HU: m(
    'Automobiles',
    'Packaged medicaments',
    'Electricity',
    'Machinery',
    'Computers',
    'Pharmaceuticals',
    'Plastics',
  ),
  ID: m(
    'Coal',
    'Palm oil',
    'Nickel',
    'Refined petroleum',
    'Rubber',
    'Copper',
    'Gold',
  ),
  IR: m(
    'Crude petroleum',
    'Petrochemicals',
    'Natural gas',
    'Dates',
    'Pistachios',
    'Carpets',
    'Steel',
  ),
  IQ: m(
    'Crude petroleum',
    'Refined petroleum',
    'Gold',
    'Dates',
    'Wheat flour',
    'Natural gas',
    'Sulfur',
  ),
  IT: m(
    'Machinery',
    'Packaged medicaments',
    'Automobiles',
    'Refined petroleum',
    'Wine',
    'Clothing',
    'Furniture',
  ),
  JM: m(
    'Alumina',
    'Bauxite',
    'Rum',
    'Coffee',
    'Tourism services',
    'Yam',
    'Mining products',
  ),
  JO: m(
    'Potassium fertilizers',
    'Phosphates',
    'Garments',
    'Vegetables',
    'Olive oil',
    'Medical instruments',
    'Pharmaceuticals',
  ),
  KZ: m(
    'Crude petroleum',
    'Refined copper',
    'Wheat',
    'Uranium',
    'Iron ore',
    'Coal',
    'Natural gas',
  ),
  KE: m(
    'Tea',
    'Cut flowers',
    'Coffee',
    'Refined petroleum',
    'Titanium ore',
    'Avocados',
    'Vegetables',
  ),
  KI: m(
    'Fish',
    'Copra',
    'Seaweed',
    'Coconut oil',
    'Tourism services',
    'Tuna',
    'Handicrafts',
  ),
  KW: m(
    'Crude petroleum',
    'Refined petroleum',
    'Liquified natural gas',
    'Petrochemicals',
    'Fertilizers',
    'Aluminium',
    'Chemicals',
  ),
  KG: m(
    'Gold',
    'Cotton',
    'Precious-metal ore',
    'Electricity',
    'Dried fruits',
    'Apparel',
    'Honey',
  ),
  LA: m(
    'Electricity (hydro)',
    'Copper ore',
    'Coffee',
    'Rubber',
    'Timber',
    'Maize',
    'Gold',
  ),
  LV: m(
    'Refined petroleum',
    'Wheat',
    'Timber',
    'Packaged medicaments',
    'Fish',
    'Electricity',
    'Machinery',
  ),
  LB: m(
    'Gold',
    'Jewellery',
    'Refined petroleum',
    'Scrap copper',
    'Citrus fruit',
    'Wine',
    'Vegetables',
  ),
  LS: m(
    'Diamonds',
    'Garments',
    'Wool',
    'Water',
    'Mohair',
    'Footwear',
    'Textiles',
  ),
  LR: m(
    'Iron ore',
    'Gold',
    'Rubber',
    'Ships',
    'Diamonds',
    'Palm oil',
    'Timber',
  ),
  LY: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Fertilizers',
    'Hydrocarbon derivatives',
    'Dates',
    'Wheat',
  ),
  LT: m(
    'Refined petroleum',
    'Furniture',
    'Wheat',
    'Packaged medicaments',
    'Machinery',
    'Plastics',
    'Electricity',
  ),
  LU: m(
    'Iron and steel',
    'Packaged medicaments',
    'Rubber tires',
    'Glass',
    'Machinery',
    'Plastics',
    'Aluminium',
  ),
  MG: m(
    'Vanilla',
    'Nickel',
    'Apparel',
    'Cloves',
    'Gold',
    'Shrimp',
    'Graphite',
  ),
  MW: m(
    'Tobacco',
    'Tea',
    'Sugar',
    'Legumes',
    'Coffee',
    'Nuts',
    'Cotton',
  ),
  MY: m(
    'Integrated circuits',
    'Palm oil',
    'Refined petroleum',
    'Liquified natural gas',
    'Rubber',
    'Natural gas',
    'Electrical machinery',
  ),
  MV: m(
    'Fish',
    'Tourism services',
    'Garments',
    'Coconut products',
    'Thresher shark meat',
    'Aircraft parts',
    'Re-exports',
  ),
  ML: m(
    'Gold',
    'Cotton',
    'Livestock',
    'Salt',
    'Sesame seeds',
    'Fruits',
    'Shea nuts',
  ),
  MT: m(
    'Refined petroleum',
    'Packaged medicaments',
    'Fish',
    'Integrated circuits',
    'Pharmaceuticals',
    'Electronics',
    'Tourism services',
  ),
  MR: m(
    'Iron ore',
    'Gold',
    'Fish',
    'Copper',
    'Gypsum',
    'Crude petroleum',
    'Livestock',
  ),
  FM: m(
    'Fish',
    'Copra',
    'Tourism services',
    'Black pearls',
    'Kava',
    'Bananas',
    'Handicrafts',
  ),
  MD: m(
    'Wine',
    'Sunflower seeds',
    'Wheat',
    'Apparel',
    'Fruit',
    'Electricity',
    'Vegetables',
  ),
  MN: m(
    'Coal',
    'Copper',
    'Gold',
    'Cashmere',
    'Iron ore',
    'Crude petroleum',
    'Wool',
  ),
  ME: m(
    'Aluminium',
    'Electricity',
    'Wine',
    'Fish',
    'Packaged medicaments',
    'Tourism services',
    'Steel',
  ),
  MA: m(
    'Automobiles',
    'Fertilizers',
    'Phosphates',
    'Electrical components',
    'Textiles',
    'Citrus fruit',
    'Fish',
  ),
  MZ: m(
    'Coal',
    'Aluminum',
    'Natural gas',
    'Electrical energy',
    'Cashew nuts',
    'Prawns',
    'Tobacco',
  ),
  MM: m(
    'Natural gas',
    'Garments',
    'Rice',
    'Copper',
    'Dried peas',
    'Fish',
    'Jade',
  ),
  NA: m(
    'Diamonds',
    'Uranium',
    'Fish',
    'Zinc',
    'Gold',
    'Beef',
    'Salt',
  ),
  NP: m(
    'Palm oil',
    'Carpets',
    'Tea',
    'Cardamom',
    'Clothing',
    'Iron and steel',
    'Vegetables',
  ),
  NZ: m(
    'Milk powder',
    'Meat',
    'Wood products',
    'Wine',
    'Honey',
    'Butter',
    'Fruit',
  ),
  NI: m(
    'Gold',
    'Coffee',
    'Beef',
    'Sugar',
    'Beans',
    'Rum',
    'Textiles',
  ),
  NE: m(
    'Uranium',
    'Gold',
    'Livestock',
    'Onions',
    'Cowpeas',
    'Sesame seeds',
    'Crude petroleum',
  ),
  NG: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Cocoa',
    'Fertilizers',
    'Sesame seeds',
    'Gold',
  ),
  NU: m(
    'Coconut products',
    'Tourism services',
    'Handicrafts',
    'Fish',
    'Honey',
    'Passenger ships',
    'Food products',
  ),
  MK: m(
    'Refined copper',
    'Iron and steel',
    'Automobile parts',
    'Textiles',
    'Wine',
    'Tobacco',
    'Vegetables',
  ),
  OM: m(
    'Crude petroleum',
    'Refined petroleum',
    'Liquified natural gas',
    'Fertilizers',
    'Metals',
    'Fish',
    'Plastics',
  ),
  PK: m(
    'Textiles',
    'Rice',
    'Leather goods',
    'Cotton yarn',
    'Sports goods',
    'Sugar',
    'Cement',
  ),
  PA: m(
    'Bananas',
    'Refined petroleum',
    'Fish',
    'Gold',
    'Medical instruments',
    'Copper ore',
    'Melons',
  ),
  PG: m(
    'Liquified natural gas',
    'Gold',
    'Copper ore',
    'Petroleum',
    'Palm oil',
    'Logs',
    'Coffee',
  ),
  PE: m(
    'Copper',
    'Gold',
    'Zinc',
    'Fishmeal',
    'Grapes',
    'Asparagus',
    'Blueberries',
  ),
  PH: m(
    'Integrated circuits',
    'Semiconductors',
    'Refined copper',
    'Bananas',
    'Coconut oil',
    'Gold',
    'Electronics',
  ),
  PL: m(
    'Automobiles',
    'Packaged medicaments',
    'Furniture',
    'Electricity',
    'Computers',
    'Meat',
    'Iron and steel',
  ),
  PT: m(
    'Automobiles',
    'Refined petroleum',
    'Packaged medicaments',
    'Wine',
    'Olive oil',
    'Footwear',
    'Paper pulp',
  ),
  QA: m(
    'Liquified natural gas',
    'Crude petroleum',
    'Refined petroleum',
    'Aluminium',
    'Fertilizers',
    'Petrochemicals',
    'Steel',
  ),
  CG: m(
    'Crude petroleum',
    'Timber',
    'Diamonds',
    'Refined petroleum',
    'Copper',
    'Gold',
    'Plywood',
  ),
  RO: m(
    'Automobiles',
    'Packaged medicaments',
    'Wheat',
    'Refined petroleum',
    'Electricity',
    'Timber',
    'Machinery',
  ),
  RU: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Wheat',
    'Coal',
    'Gold',
    'Iron and steel',
  ),
  RW: m(
    'Gold',
    'Coffee',
    'Tea',
    'Tin',
    'Tantalum',
    'Tungsten',
    'Niobium',
  ),
  WS: m(
    'Fish',
    'Coconut oil',
    'Automotive parts',
    'Noni juice',
    'Tourism services',
    'Kava',
    'Beer',
  ),
  SA: m(
    'Crude petroleum',
    'Refined petroleum',
    'Petrochemicals',
    'Plastics',
    'Ammonia',
    'Aluminium',
    'Gold',
  ),
  SN: m(
    'Refined petroleum',
    'Gold',
    'Fish',
    'Phosphates',
    'Groundnuts',
    'Cement',
    'Titanium ore',
  ),
  RS: m(
    'Electricity',
    'Packaged medicaments',
    'Fruit',
    'Automobiles',
    'Iron and steel',
    'Copper ore',
    'Raspberries',
  ),
  SC: m(
    'Fish',
    'Processed fish',
    'Petroleum re-exports',
    'Copra',
    'Cinnamon',
    'Canned tuna',
    'Tourism-linked goods',
  ),
  SL: m(
    'Iron ore',
    'Diamonds',
    'Rutile',
    'Cocoa',
    'Coffee',
    'Fish',
    'Timber',
  ),
  SG: m(
    'Integrated circuits',
    'Refined petroleum',
    'Machinery',
    'Pharmaceuticals',
    'Optical media',
    'Gold',
    'Gas turbines',
  ),
  SK: m(
    'Automobiles',
    'Packaged medicaments',
    'Televisions',
    'Machinery',
    'Iron and steel',
    'Refined petroleum',
    'Plastics',
  ),
  SI: m(
    'Packaged medicaments',
    'Automobiles',
    'Refined petroleum',
    'Electricity',
    'Machinery',
    'Aluminium',
    'Wood products',
  ),
  SB: m(
    'Timber',
    'Fish',
    'Palm oil',
    'Copra',
    'Gold',
    'Tourism services',
    'Cocoa',
  ),
  SO: m(
    'Livestock',
    'Charcoal',
    'Fish',
    'Gold',
    'Sesame seeds',
    'Bananas',
    'Hides and skins',
  ),
  ZA: m(
    'Platinum',
    'Gold',
    'Coal',
    'Iron ore',
    'Manganese ore',
    'Automobiles',
    'Citrus fruit',
  ),
  SS: m(
    'Crude petroleum',
    'Gold',
    'Timber',
    'Gum arabic',
    'Sesame seeds',
    'Hides and skins',
    'Honey',
  ),
  LK: m(
    'Tea',
    'Apparel',
    'Rubber',
    'Coconut products',
    'Spices',
    'Fish',
    'Gems',
  ),
  SD: m(
    'Gold',
    'Crude petroleum',
    'Livestock',
    'Sesame seeds',
    'Cotton',
    'Gum arabic',
    'Sheep',
  ),
  SR: m(
    'Gold',
    'Oil',
    'Rice',
    'Aluminium ore',
    'Shrimp',
    'Timber',
    'Bananas',
  ),
  SY: m(
    'Crude petroleum',
    'Phosphates',
    'Cotton',
    'Olive oil',
    'Fruits',
    'Vegetables',
    'Textiles',
  ),
  TJ: m(
    'Aluminium',
    'Electricity',
    'Cotton',
    'Precious-metal ore',
    'Vegetables',
    'Dried fruits',
    'Textiles',
  ),
  TZ: m(
    'Gold',
    'Cashew nuts',
    'Coffee',
    'Refined petroleum',
    'Cotton',
    'Tobacco',
    'Tea',
  ),
  TH: m(
    'Computers',
    'Automobiles',
    'Rubber',
    'Rice',
    'Jewellery',
    'Sugar',
    'Chicken',
  ),
  TL: m(
    'Coffee',
    'Crude petroleum',
    'Natural gas',
    'Sandalwood',
    'Tuna',
    'Marble',
    'Cinnamon',
  ),
  TG: m(
    'Crude petroleum',
    'Re-exported goods',
    'Cocoa',
    'Phosphates',
    'Cotton',
    'Coffee',
    'Refined petroleum',
  ),
  TO: m(
    'Fish',
    'Squash',
    'Vanilla',
    'Coconut products',
    'Tourism services',
    'Root crops',
    'Handicrafts',
  ),
  TT: m(
    'Liquified natural gas',
    'Ammonia',
    'Methanol',
    'Iron and steel',
    'Petroleum products',
    'Chemicals',
    'Cocoa',
  ),
  TN: m(
    'Electrical components',
    'Olive oil',
    'Textiles',
    'Phosphates',
    'Dates',
    'Fish',
    'Hydrocarbons',
  ),
  TR: m(
    'Automobiles',
    'Refined petroleum',
    'Iron and steel',
    'Textiles',
    'Machinery',
    'Gold',
    'Jewellery',
  ),
  TM: m(
    'Natural gas',
    'Crude petroleum',
    'Refined petroleum',
    'Cotton',
    'Wheat',
    'Polypropylene',
    'Electricity',
  ),
  UG: m(
    'Coffee',
    'Gold',
    'Fish',
    'Tea',
    'Cotton',
    'Maize',
    'Cut flowers',
  ),
  UA: m(
    'Corn',
    'Wheat',
    'Sunflower oil',
    'Iron ore',
    'Steel',
    'Rapeseed',
    'Poultry meat',
  ),
  AE: m(
    'Crude petroleum',
    'Refined petroleum',
    'Gold',
    'Diamonds',
    'Aluminium',
    'Telecommunications equipment',
    'Dates',
  ),
  UY: m(
    'Beef',
    'Soybeans',
    'Cellulose pulp',
    'Rice',
    'Wool',
    'Dairy products',
    'Wood',
  ),
  UZ: m(
    'Gold',
    'Natural gas',
    'Cotton',
    'Copper',
    'Textiles',
    'Fruits',
    'Uranium',
  ),
  VU: m(
    'Beef',
    'Copra',
    'Kava',
    'Tourism services',
    'Fish',
    'Cocoa',
    'Timber',
  ),
  VE: m(
    'Crude petroleum',
    'Refined petroleum',
    'Gold',
    'Iron ore',
    'Aluminium',
    'Soybeans',
    'Corn',
  ),
  VN: m(
    'Integrated circuits',
    'Footwear',
    'Electronics',
    'Textiles',
    'Coffee',
    'Rice',
    'Seafood',
  ),
  YE: m(
    'Crude petroleum',
    'Gold',
    'Fish',
    'Coffee',
    'Honey',
    'Vegetables',
    'Scrap metal',
  ),
  ZM: m(
    'Copper',
    'Refined copper',
    'Cobalt',
    'Gold',
    'Tobacco',
    'Sugar',
    'Gemstones',
  ),
  ZW: m(
    'Platinum',
    'Gold',
    'Tobacco',
    'Nickel',
    'Diamonds',
    'Ferroalloys',
    'Cotton',
  ),
}
