import type { BriMemberIsoCode } from './participantStatesIsoCodes'
import type { RareEarths } from './types'

/**
 * Documented rare-earth element exports (lanthanide series plus Sc and Y) by ISO 3166-1 alpha-2
 * for BRI partner countries. Notable entries:
 *  - China (CN): full light + heavy REE separation, oxide / metal / alloy exports.
 *  - Vietnam (VN): Nam Xe / Dong Pao / Yen Phu light-REE concentrate.
 *  - Myanmar (MM): heavy-REE ion-adsorption clay routed via Yunnan border trade.
 *  - Malaysia (MY): Lynas Advanced Materials Plant (LAMP) refines Australian Mt Weld concentrate.
 *  - Thailand (TH): monazite from tin tailings (Phuket / Phang Nga).
 *  - Russia (RU): Lovozero loparite + Solikamsk Magnesium light-REE concentrate.
 *  - Kazakhstan (KZ): byproduct REE recovery from uranium ISL streams (Stepnogorsk).
 *  - South Africa (ZA): Steenkampskraal historical / restart light-REE concentrate.
 *  - Egypt (EG): monazite recovery from Rosetta-coast black-sand operations.
 * Other entries are empty (informational; verify periodically).
 */
export const BRI_RARE_EARTHS: Record<BriMemberIsoCode, RareEarths> = {
  AF: [],
  AL: [],
  DZ: [],
  AO: [],
  AG: [],
  AR: [],
  AM: [],
  AT: [],
  AZ: [],
  BH: [],
  BD: [],
  BB: [],
  BY: [],
  BJ: [],
  BO: [],
  BA: [],
  BW: [],
  BN: [],
  BG: [],
  BI: [],
  CV: [],
  KH: [],
  CM: [],
  CF: [],
  TD: [],
  CL: [],
  CN: [
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Samarium (Sm)',
    'Europium (Eu)',
    'Gadolinium (Gd)',
    'Terbium (Tb)',
    'Dysprosium (Dy)',
    'Holmium (Ho)',
    'Erbium (Er)',
    'Thulium (Tm)',
    'Ytterbium (Yb)',
    'Lutetium (Lu)',
    'Yttrium (Y)',
    'Scandium (Sc)',
  ],
  CO: [],
  KM: [],
  CK: [],
  CR: [],
  CI: [],
  HR: [],
  CU: [],
  CY: [],
  CZ: [],
  CD: [],
  DJ: [],
  DM: [],
  DO: [],
  EC: [],
  EG: [
    'Neodymium (Nd)',
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Yttrium (Y)',
  ],
  SV: [],
  GQ: [],
  ER: [],
  EE: [],
  ET: [],
  FJ: [],
  GA: [],
  GM: [],
  GE: [],
  GH: [],
  GR: [],
  GD: [],
  GN: [],
  GW: [],
  GY: [],
  HN: [],
  HU: [],
  ID: [],
  IR: [],
  IQ: [],
  IT: [],
  JM: [],
  JO: [],
  KZ: [
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Yttrium (Y)',
  ],
  KE: [],
  KI: [],
  KW: [],
  KG: [],
  LA: [],
  LV: [],
  LB: [],
  LS: [],
  LR: [],
  LY: [],
  LT: [],
  LU: [],
  MG: [],
  MW: [],
  MY: [
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Dysprosium (Dy)',
    'Terbium (Tb)',
  ],
  MV: [],
  ML: [],
  MT: [],
  MR: [],
  FM: [],
  MD: [],
  MN: [],
  ME: [],
  MA: [],
  MZ: [],
  MM: [
    'Yttrium (Y)',
    'Dysprosium (Dy)',
    'Terbium (Tb)',
    'Holmium (Ho)',
    'Erbium (Er)',
  ],
  NA: [],
  NP: [],
  NZ: [],
  NI: [],
  NE: [],
  NG: [],
  NU: [],
  MK: [],
  OM: [],
  PK: [],
  PA: [],
  PG: [],
  PE: [],
  PH: [],
  PL: [],
  PT: [],
  QA: [],
  CG: [],
  RO: [],
  RU: [
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Yttrium (Y)',
  ],
  RW: [],
  WS: [],
  SA: [],
  SN: [],
  RS: [],
  SC: [],
  SL: [],
  SG: [],
  SK: [],
  SI: [],
  SB: [],
  SO: [],
  ZA: [
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
  ],
  SS: [],
  LK: [],
  SD: [],
  SR: [],
  SY: [],
  TJ: [],
  TZ: [],
  TH: [
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Neodymium (Nd)',
  ],
  TL: [],
  TG: [],
  TO: [],
  TT: [],
  TN: [],
  TR: [],
  TM: [],
  UG: [],
  UA: [],
  AE: [],
  UY: [],
  UZ: [],
  VU: [],
  VE: [],
  VN: [
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Yttrium (Y)',
  ],
  YE: [],
  ZM: [],
  ZW: [],
}
