import type { CorporationFormationOffice } from './types'
import type { CaricomMemberIsoCode } from './caricomMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per CARICOM member or associate territory.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const CARICOM_CORPORATION_FORMATION_OFFICES: Record<CaricomMemberIsoCode, CorporationFormationOffice> = {
  AG:   office(
    'Intellectual Property and Commerce Office (IPCO) Antigua and Barbuda',
    '+1 268 462 0007',
    'High Street, St John\'s, Antigua and Barbuda',
    'https://www.ipco.gov.ag',
    'ipco@gov.ag',
    '',
    '',
    '',
    'https://www.ipco.gov.ag',
    'https://www.ab.gov.ag/content/registering-business',
    'Company Registration Number',
  ),
  BS:   office(
    'Registrar General\'s Department Bahamas',
    '+1 242 322 3316',
    'Frederick Street, Nassau, Bahamas',
    'https://www.bahamas.gov.bs',
    'registrar@bahamas.gov.bs',
    '',
    '',
    '',
    'https://www.bahamas.gov.bs/wps/portal/public/gov/government-services',
    'https://www.bahamas.gov.bs/invest',
    'Company Registration Number',
  ),
  BB:   office(
    'Corporate Affairs and Intellectual Property Office (CAIPO) Barbados',
    '+1 246 535 5600',
    'Baobab Tower, Warrens, St Michael, Barbados',
    'https://www.caipo.gov.bb',
    'caipo@gov.bb',
    '',
    '',
    '',
    'https://www.caipo.gov.bb',
    'https://www.investbarbados.org/starting-a-business',
    'Company Registration Number',
  ),
  BZ:   office(
    'Companies and Corporate Affairs Registry Belize',
    '+501 822 0421',
    'Belmopan, Belize',
    'https://www.belize.gov.bz',
    'registry@belize.gov.bz',
    '',
    '',
    '',
    'https://www.belize.gov.bz',
    'https://www.belizeinvest.org.bz/starting-a-business',
    'Company Registration Number',
  ),
  DM:   office(
    'Companies and Intellectual Property Office Dominica',
    '+1 767 266 3201',
    'Kennedy Avenue, Roseau, Dominica',
    'https://www.dominica.gov.dm',
    'cipo@gov.dm',
    '',
    '',
    '',
    'https://www.dominica.gov.dm',
    'https://investdominica.dm/starting-a-business',
    'Company Registration Number',
  ),
  GD:   office(
    'Corporate Affairs and Intellectual Property Office Grenada',
    '+1 473 440 2939',
    'Frederick Street, St George\'s, Grenada',
    'https://www.gov.gd',
    'caipo@gov.gd',
    '',
    '',
    '',
    'https://www.gov.gd',
    'https://grenadagrenadines.com/invest/starting-a-business',
    'Company Registration Number',
  ),
  GY:   office(
    'Deeds and Commercial Registry Guyana',
    '+592 225 0555',
    'Avenue of the Republic, Georgetown, Guyana',
    'https://www.deeds.gov.gy',
    'deedsregistry@gov.gy',
    '',
    '',
    '',
    'https://www.deeds.gov.gy',
    'https://goinvest.gov.gy/starting-a-business',
    'Company Registration Number',
  ),
  HT:   office(
    'Ministry of Commerce and Industry Haiti (DGI Business Registration)',
    '+509 2813 1000',
    'Port-au-Prince, Haiti',
    'https://www.mci.gouv.ht',
    'info@mci.gouv.ht',
    '',
    '',
    '',
    'https://www.dgi.gouv.ht',
    'https://www.mci.gouv.ht/services',
    'Numero d\'Identification Fiscale (NIF)',
  ),
  JM:   office(
    'Companies Office of Jamaica',
    '+1 876 908 4419',
    '1 Grenada Way, Kingston, Jamaica',
    'https://www.orcjamaica.gov.jm',
    'info@orcjamaica.gov.jm',
    '',
    '',
    '',
    'https://www.orcjamaica.gov.jm',
    'https://www.jamaicatradeandinvest.org/starting-a-business',
    'Company Registration Number',
  ),
  MS:   office(
    'Companies Registry Montserrat',
    '+1 664 491 3756',
    'Brades, Montserrat',
    'https://www.gov.ms',
    'registry@gov.ms',
    '',
    '',
    '',
    'https://www.gov.ms',
    'https://www.gov.ms/government/departments/companies-registry',
    'Company Registration Number',
  ),
  KN:   office(
    'Financial Services Regulatory Commission St Kitts and Nevis',
    '+1 869 465 2539',
    'Basseterre, St Kitts and Nevis',
    'https://www.fsrc.kn',
    'info@fsrc.kn',
    '',
    '',
    '',
    'https://www.fsrc.kn',
    'https://www.investstkitts.kn/starting-a-business',
    'Company Registration Number',
  ),
  LC:   office(
    'Registry of Companies Saint Lucia',
    '+1 758 468 5500',
    'Castries, Saint Lucia',
    'https://www.govt.lc',
    'registry@govt.lc',
    '',
    '',
    '',
    'https://www.govt.lc',
    'https://www.investstlucia.com/starting-a-business',
    'Company Registration Number',
  ),
  VC:   office(
    'Commerce and Intellectual Property Office Saint Vincent and the Grenadines',
    '+1 784 457 1107',
    'Kingstown, Saint Vincent and the Grenadines',
    'https://www.gov.vc',
    'cipo@gov.vc',
    '',
    '',
    '',
    'https://www.gov.vc',
    'https://www.investsvg.com/starting-a-business',
    'Company Registration Number',
  ),
  SR:   office(
    'Chamber of Commerce and Industry Suriname',
    '+597 474 889',
    'Dr. Sophie Redmondstraat 59, Paramaribo, Suriname',
    'https://www.kkf.sr',
    'info@kkf.sr',
    '',
    '',
    '',
    'https://www.kkf.sr',
    'https://www.investsuriname.org/starting-a-business',
    'KvK Number',
  ),
  TT:   office(
    'Companies Registry Trinidad and Tobago',
    '+1 868 624 1462',
    'Corner of Richmond and Duke Streets, Port of Spain, Trinidad and Tobago',
    'https://www.legalaffairs.gov.tt',
    'registry@legalaffairs.gov.tt',
    '',
    '',
    '',
    'https://www.legalaffairs.gov.tt',
    'https://www.investt.co.tt/starting-a-business',
    'Company Registration Number',
  ),
  AI:   office(
    'Registrar of Companies Anguilla',
    '+1 264 497 2877',
    'The Valley, Anguilla',
    'https://www.gov.ai',
    'registry@gov.ai',
    '',
    '',
    '',
    'https://www.gov.ai',
    'https://www.gov.ai/service/company-registration',
    'Company Registration Number',
  ),
  BM:   office(
    'Registrar of Companies Bermuda',
    '+1 441 297 7750',
    '30 Victoria Street, Hamilton HM 12, Bermuda',
    'https://www.gov.bm',
    'roc@gov.bm',
    '',
    '',
    '',
    'https://www.gov.bm/roc',
    'https://www.gov.bm/starting-business-bermuda',
    'Company Registration Number',
  ),
  VG:   office(
    'Registry of Corporate Affairs British Virgin Islands',
    '+1 284 468 3701',
    'Road Town, Tortola, British Virgin Islands',
    'https://www.bvifsc.vg',
    'info@bvifsc.vg',
    '',
    '',
    '',
    'https://www.bvifsc.vg',
    'https://www.bvifsc.vg/corporate-services/company-incorporation',
    'Company Registration Number',
  ),
  KY:   office(
    'General Registry Cayman Islands',
    '+1 345 946 9811',
    'Elgin Avenue, George Town, Grand Cayman',
    'https://www.ciregistry.gov.ky',
    'info@ciregistry.gov.ky',
    '',
    '',
    '',
    'https://www.ciregistry.gov.ky',
    'https://www.ciregistry.gov.ky/portal/page/portal/ciregistry/home/companyincorporation',
    'Company Registration Number',
  ),
  TC:   office(
    'Financial Services Commission Turks and Caicos Islands',
    '+1 649 946 2821',
    'Providenciales, Turks and Caicos Islands',
    'https://www.fsc.tc',
    'info@fsc.tc',
    '',
    '',
    '',
    'https://www.fsc.tc',
    'https://www.fsc.tc/company-registration',
    'Company Registration Number',
  ),
}
