import type { CaricomMemberIsoCode } from './caricomMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for CARICOM full and associate
 * members in this module (informational; verify URLs, handles, forms portals, and API bases
 * before production use). Self-contained — no imports from other alliance modules.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const CARICOM_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  CaricomMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AG: roster(
    ip(
      'copyright',
      'Antigua and Barbuda Intellectual Property Office (Commerce Division) — copyright',
      'https://abip.gov.ag',
      '',
      '',
      '',
      'https://abip.gov.ag',
    ),
    ip(
      'trademarks',
      'Antigua and Barbuda Intellectual Property Office (Commerce Division)',
      'https://abip.gov.ag',
      '',
      '',
      '',
      'https://abip.gov.ag',
    ),
    ip(
      'patents',
      'Antigua and Barbuda Intellectual Property Office (Commerce Division)',
      'https://abip.gov.ag',
      '',
      '',
      '',
      'https://abip.gov.ag',
    ),
  ),
  BS: roster(
    ip(
      'copyright',
      'Bahamas Copyright Royalty Tribunal (Ministry of Finance — copyright)',
      'https://www.bahamas.gov.bs',
      '',
      '',
      '',
      'https://www.bahamas.gov.bs',
    ),
    ip(
      'trademarks',
      'Department of the Registrar General — Intellectual Property (Bahamas)',
      'https://www.bahamas.gov.bs',
      '',
      '',
      '',
      'https://www.bahamas.gov.bs',
    ),
    ip(
      'patents',
      'Department of the Registrar General — Intellectual Property (Bahamas)',
      'https://www.bahamas.gov.bs',
      '',
      '',
      '',
      'https://www.bahamas.gov.bs',
    ),
  ),
  BB: roster(
    ip(
      'copyright',
      'Corporate Affairs and Intellectual Property Office (CAIPO, Barbados) — copyright',
      'https://www.caipo.gov.bb',
      'caipo@caipo.gov.bb',
      '',
      '',
      'https://www.caipo.gov.bb',
    ),
    ip(
      'trademarks',
      'Corporate Affairs and Intellectual Property Office (CAIPO, Barbados)',
      'https://www.caipo.gov.bb',
      'caipo@caipo.gov.bb',
      '',
      '',
      'https://www.caipo.gov.bb',
    ),
    ip(
      'patents',
      'Corporate Affairs and Intellectual Property Office (CAIPO, Barbados)',
      'https://www.caipo.gov.bb',
      'caipo@caipo.gov.bb',
      '',
      '',
      'https://www.caipo.gov.bb',
    ),
  ),
  BZ: roster(
    ip(
      'copyright',
      'Belize Intellectual Property Office (BelIPO) — copyright',
      'https://www.belipo.bz',
      '',
      '',
      '',
      'https://www.belipo.bz',
    ),
    ip(
      'trademarks',
      'Belize Intellectual Property Office (BelIPO)',
      'https://www.belipo.bz',
      '',
      '',
      '',
      'https://www.belipo.bz',
    ),
    ip(
      'patents',
      'Belize Intellectual Property Office (BelIPO)',
      'https://www.belipo.bz',
      '',
      '',
      '',
      'https://www.belipo.bz',
    ),
  ),
  DM: roster(
    ip(
      'copyright',
      'Commerce and Intellectual Property Office (Dominica) — copyright',
      'https://www.dominica.gov.dm',
      '',
      '',
      '',
      'https://www.dominica.gov.dm',
    ),
    ip(
      'trademarks',
      'Commerce and Intellectual Property Office (Dominica)',
      'https://www.dominica.gov.dm',
      '',
      '',
      '',
      'https://www.dominica.gov.dm',
    ),
    ip(
      'patents',
      'Commerce and Intellectual Property Office (Dominica)',
      'https://www.dominica.gov.dm',
      '',
      '',
      '',
      'https://www.dominica.gov.dm',
    ),
  ),
  GD: roster(
    ip(
      'copyright',
      'Corporate Affairs and Intellectual Property Office (Grenada) — copyright',
      'https://www.gov.gd',
      '',
      '',
      '',
      'https://www.gov.gd',
    ),
    ip(
      'trademarks',
      'Corporate Affairs and Intellectual Property Office (Grenada)',
      'https://www.gov.gd',
      '',
      '',
      '',
      'https://www.gov.gd',
    ),
    ip(
      'patents',
      'Corporate Affairs and Intellectual Property Office (Grenada)',
      'https://www.gov.gd',
      '',
      '',
      '',
      'https://www.gov.gd',
    ),
  ),
  GY: roster(
    ip(
      'copyright',
      'Deeds and Commercial Registries Authority (Guyana) — intellectual property — copyright',
      'https://dcra.gov.gy',
      '',
      '',
      '',
      'https://dcra.gov.gy',
    ),
    ip(
      'trademarks',
      'Deeds and Commercial Registries Authority (Guyana) — intellectual property',
      'https://dcra.gov.gy',
      '',
      '',
      '',
      'https://dcra.gov.gy',
    ),
    ip(
      'patents',
      'Deeds and Commercial Registries Authority (Guyana) — intellectual property',
      'https://dcra.gov.gy',
      '',
      '',
      '',
      'https://dcra.gov.gy',
    ),
  ),
  HT: roster(
    ip(
      'copyright',
      'Bureau du Droit d\'Auteur (BDA, Haiti)',
      'https://www.bda.gouv.ht',
      '',
      '',
      '',
      'https://www.bda.gouv.ht',
    ),
    ip(
      'trademarks',
      'Bureau d\'Inspection et de Contrôle (BIC) — industrial property (Haiti)',
      'https://www.bic.gouv.ht',
      '',
      '',
      '',
      'https://www.bic.gouv.ht',
    ),
    ip(
      'patents',
      'Bureau d\'Inspection et de Contrôle (BIC) — industrial property (Haiti)',
      'https://www.bic.gouv.ht',
      '',
      '',
      '',
      'https://www.bic.gouv.ht',
    ),
  ),
  JM: roster(
    ip(
      'copyright',
      'Jamaica Intellectual Property Office (JIPO) — copyright',
      'https://www.jipo.gov.jm',
      'info@jipo.gov.jm',
      '',
      '',
      'https://www.jipo.gov.jm',
    ),
    ip(
      'trademarks',
      'Jamaica Intellectual Property Office (JIPO)',
      'https://www.jipo.gov.jm',
      'info@jipo.gov.jm',
      '',
      '',
      'https://www.jipo.gov.jm',
    ),
    ip(
      'patents',
      'Jamaica Intellectual Property Office (JIPO)',
      'https://www.jipo.gov.jm',
      'info@jipo.gov.jm',
      '',
      '',
      'https://www.jipo.gov.jm',
    ),
  ),
  MS: roster(
    ip(
      'copyright',
      'Montserrat — intellectual property (UK extension; verify locally)',
      'https://www.gov.ms',
      '',
      '',
      '',
      'https://www.gov.ms',
    ),
    ip(
      'trademarks',
      'Montserrat — intellectual property (verify locally)',
      'https://www.gov.ms',
      '',
      '',
      '',
      'https://www.gov.ms',
    ),
    ip(
      'patents',
      'Montserrat — intellectual property (verify locally)',
      'https://www.gov.ms',
      '',
      '',
      '',
      'https://www.gov.ms',
    ),
  ),
  KN: roster(
    ip(
      'copyright',
      'Ministry of Justice and Legal Affairs (Saint Kitts and Nevis) — copyright',
      'https://www.gov.kn',
      '',
      '',
      '',
      'https://www.gov.kn',
    ),
    ip(
      'trademarks',
      'Commerce and Intellectual Property Office (Saint Kitts and Nevis)',
      'https://www.gov.kn',
      '',
      '',
      '',
      'https://www.gov.kn',
    ),
    ip(
      'patents',
      'Commerce and Intellectual Property Office (Saint Kitts and Nevis)',
      'https://www.gov.kn',
      '',
      '',
      '',
      'https://www.gov.kn',
    ),
  ),
  LC: roster(
    ip(
      'copyright',
      'Ministry of Commerce — copyright (Saint Lucia)',
      'https://www.govt.lc',
      '',
      '',
      '',
      'https://www.govt.lc',
    ),
    ip(
      'trademarks',
      'Registry of Companies and Intellectual Property (Saint Lucia)',
      'https://www.govt.lc',
      '',
      '',
      '',
      'https://www.govt.lc',
    ),
    ip(
      'patents',
      'Registry of Companies and Intellectual Property (Saint Lucia)',
      'https://www.govt.lc',
      '',
      '',
      '',
      'https://www.govt.lc',
    ),
  ),
  VC: roster(
    ip(
      'copyright',
      'Ministry of Legal Affairs (Saint Vincent and the Grenadines) — copyright',
      'https://www.gov.vc',
      '',
      '',
      '',
      'https://www.gov.vc',
    ),
    ip(
      'trademarks',
      'Commerce and Intellectual Property Office (Saint Vincent and the Grenadines)',
      'https://www.gov.vc',
      '',
      '',
      '',
      'https://www.gov.vc',
    ),
    ip(
      'patents',
      'Commerce and Intellectual Property Office (Saint Vincent and the Grenadines)',
      'https://www.gov.vc',
      '',
      '',
      '',
      'https://www.gov.vc',
    ),
  ),
  SR: roster(
    ip(
      'copyright',
      'Suriname Bureau for Intellectual Property — copyright',
      'https://www.agroinformation.org',
      '',
      '',
      '',
      'https://www.agroinformation.org',
    ),
    ip(
      'trademarks',
      'Suriname Bureau for Intellectual Property',
      'https://www.agroinformation.org',
      '',
      '',
      '',
      'https://www.agroinformation.org',
    ),
    ip(
      'patents',
      'Suriname Bureau for Intellectual Property',
      'https://www.agroinformation.org',
      '',
      '',
      '',
      'https://www.agroinformation.org',
    ),
  ),
  TT: roster(
    ip(
      'copyright',
      'Intellectual Property Office (Trinidad and Tobago) — copyright',
      'https://www.ipo.gov.tt',
      '',
      '',
      '',
      'https://www.ipo.gov.tt',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (Trinidad and Tobago)',
      'https://www.ipo.gov.tt',
      '',
      '',
      '',
      'https://www.ipo.gov.tt',
    ),
    ip(
      'patents',
      'Intellectual Property Office (Trinidad and Tobago)',
      'https://www.ipo.gov.tt',
      '',
      '',
      '',
      'https://www.ipo.gov.tt',
    ),
  ),
  AI: roster(
    ip(
      'copyright',
      'Anguilla — intellectual property (UK extension; verify locally)',
      'https://www.gov.ai',
      '',
      '',
      '',
      'https://www.gov.ai',
    ),
    ip(
      'trademarks',
      'Anguilla Financial Services Commission — intellectual property',
      'https://www.fsc.org.ai',
      '',
      '',
      '',
      'https://www.fsc.org.ai',
    ),
    ip(
      'patents',
      'Anguilla Financial Services Commission — intellectual property',
      'https://www.fsc.org.ai',
      '',
      '',
      '',
      'https://www.fsc.org.ai',
    ),
  ),
  BM: roster(
    ip(
      'copyright',
      'Bermuda Copyright Tribunal (Ministry of Legal Affairs)',
      'https://www.gov.bm',
      '',
      '',
      '',
      'https://www.gov.bm',
    ),
    ip(
      'trademarks',
      'Registry General — Intellectual Property (Bermuda)',
      'https://www.gov.bm',
      '',
      '',
      '',
      'https://www.gov.bm',
    ),
    ip(
      'patents',
      'Registry General — Intellectual Property (Bermuda)',
      'https://www.gov.bm',
      '',
      '',
      '',
      'https://www.gov.bm',
    ),
  ),
  VG: roster(
    ip(
      'copyright',
      'British Virgin Islands — copyright (UK extension; verify locally)',
      'https://www.bvi.gov.vg',
      '',
      '',
      '',
      'https://www.bvi.gov.vg',
    ),
    ip(
      'trademarks',
      'BVI Financial Services Commission — intellectual property',
      'https://www.bvifsc.vg',
      '',
      '',
      '',
      'https://www.bvifsc.vg',
    ),
    ip(
      'patents',
      'BVI Financial Services Commission — intellectual property',
      'https://www.bvifsc.vg',
      '',
      '',
      '',
      'https://www.bvifsc.vg',
    ),
  ),
  KY: roster(
    ip(
      'copyright',
      'Cayman Islands — copyright (UK extension; verify locally)',
      'https://www.gov.ky',
      '',
      '',
      '',
      'https://www.gov.ky',
    ),
    ip(
      'trademarks',
      'Cayman Islands General Registry — intellectual property',
      'https://www.ciregistry.com',
      '',
      '',
      '',
      'https://www.ciregistry.com',
    ),
    ip(
      'patents',
      'Cayman Islands General Registry — intellectual property',
      'https://www.ciregistry.com',
      '',
      '',
      '',
      'https://www.ciregistry.com',
    ),
  ),
  TC: roster(
    ip(
      'copyright',
      'Turks and Caicos Islands — copyright (UK extension; verify locally)',
      'https://www.gov.tc',
      '',
      '',
      '',
      'https://www.gov.tc',
    ),
    ip(
      'trademarks',
      'Turks and Caicos Islands Financial Services Commission — intellectual property',
      'https://www.fsc.tc',
      '',
      '',
      '',
      'https://www.fsc.tc',
    ),
    ip(
      'patents',
      'Turks and Caicos Islands Financial Services Commission — intellectual property',
      'https://www.fsc.tc',
      '',
      '',
      '',
      'https://www.fsc.tc',
    ),
  ),
}
