import type { CaricomMemberIsoCode } from './caricomMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2
 * for CARICOM members and associate members (informational; verify against USGS Mineral
 * Commodity Summaries and UN Comtrade periodically). Hydrocarbon-led economies (TT, GY)
 * carry `Carbon (C)` + `Hydrogen (H)`; bauxite / alumina exporters (JM, SR, GY, HT) carry
 * `Aluminum (Al)`; service / tourism-dominated micro-states use a generic crustal-elements
 * baseline (Ca / Si / Fe / Al / Na from local cement / aggregate / salt activity).
 */
export const CARICOM_MAIN_EXPORTED_ELEMENTS: Record<CaricomMemberIsoCode, MainExportedElements> = {
  AG: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Chlorine (Cl)',
  ),
  BS: e(
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Carbon (C)',
  ),
  BB: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  BZ: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  DM: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  GD: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  GY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Manganese (Mn)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  HT: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Gold (Au)',
    'Copper (Cu)',
  ),
  JM: e(
    'Aluminum (Al)',
    'Gold (Au)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Magnesium (Mg)',
    'Sulfur (S)',
  ),
  MS: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  KN: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  LC: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  VC: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  SR: e(
    'Gold (Au)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Silver (Ag)',
    'Copper (Cu)',
  ),
  TT: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Nitrogen (N)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  AI: e(
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  BM: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  VG: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  KY: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  TC: e(
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
}
