import type { CaricomMemberIsoCode } from './caricomMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per CARICOM member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const CARICOM_MAIN_INTERNATIONAL_SEAPORTS: Record<CaricomMemberIsoCode, MainInternationalSeaport> = {
  AG: seaport(
    'Port of St. John\'s',
    'https://www.antiguaport.com/',
    'info@antiguaport.com',
    'https://x.com/AntiguaPort',
    'https://www.instagram.com/antiguaport/',
    'https://www.linkedin.com/company/antigua-port-authority/',
    'customs@antigua.gov.ag',
    'https://www.customs.gov.ag',
    'Antigua and Barbuda Customs — Port of St. John\'s, St. John\'s, Antigua and Barbuda',
  ),
  BS: seaport(
    'Port of Nassau (Freeport)',
    'https://www.bahamasports.com/',
    'info@bahamasports.com',
    'https://x.com/BahamasPorts',
    'https://www.instagram.com/bahamasports/',
    'https://www.linkedin.com/company/bahamas-port-department/',
    'customs@bahamas.gov.bs',
    'https://www.bahamas.gov.bs/customs',
    'Bahamas Customs — Freeport, Grand Bahama, Bahamas',
  ),
  BB: seaport(
    'Port of Bridgetown',
    'https://www.barbadosport.com/',
    'info@barbadosport.com',
    'https://x.com/BarbadosPort',
    'https://www.instagram.com/barbadosport/',
    'https://www.linkedin.com/company/barbados-port-inc/',
    'customs@bra.gov.bb',
    'https://www.bra.gov.bb',
    'Barbados Revenue Authority Customs — Port of Bridgetown, Bridgetown, Barbados',
  ),
  BZ: seaport(
    'Port of Belize City',
    'https://www.portbelize.com/',
    'info@portbelize.com',
    'https://x.com/PortBelize',
    'https://www.instagram.com/portbelize/',
    'https://www.linkedin.com/company/port-of-belize/',
    'customs@belize.gov.bz',
    'https://www.customs.gov.bz',
    'Belize Customs and Excise — Port of Belize City, Belize City, Belize',
  ),
  DM: seaport(
    'Port of Roseau',
    'https://www.dominicaports.dm/',
    'info@dominicaports.dm',
    'https://x.com/DominicaPorts',
    'https://www.instagram.com/dominicaport/',
    'https://www.linkedin.com/company/dominica-ports-authority/',
    'customs@customs.gov.dm',
    'https://www.customs.gov.dm',
    'Dominica Customs — Port of Roseau, Roseau, Dominica',
  ),
  GD: seaport(
    'Port of St. George\'s',
    'https://www.grenadaports.com/',
    'info@grenadaports.com',
    'https://x.com/GrenadaPorts',
    'https://www.instagram.com/grenadaports/',
    'https://www.linkedin.com/company/grenada-ports-authority/',
    'customs@customs.gov.gd',
    'https://www.customs.gov.gd',
    'Grenada Customs — Port of St. George\'s, St. George\'s, Grenada',
  ),
  GY: seaport(
    'Port of Georgetown',
    'https://www.guyanaports.com/',
    'info@guyanaports.com',
    'https://x.com/GuyanaPorts',
    'https://www.instagram.com/guyanaports/',
    'https://www.linkedin.com/company/guyana-ports-inc/',
    'customs@gra.gov.gy',
    'https://www.gra.gov.gy',
    'Guyana Revenue Authority Customs — Port of Georgetown, Georgetown, Guyana',
  ),
  HT: seaport(
    'Port of Port-au-Prince',
    'https://www.apn.gou.ht/',
    'info@apn.gou.ht',
    'https://x.com/APN_Haiti',
    'https://www.instagram.com/apn_haiti/',
    'https://www.linkedin.com/company/autorite-portuaire-nationale/',
    'douanes@douanes.gou.ht',
    'https://www.douanes.gou.ht',
    'Agence Nationale des Douanes — Port de Port-au-Prince, Port-au-Prince, Haiti',
  ),
  JM: seaport(
    'Port of Kingston',
    'https://www.portjam.com/',
    'info@portjam.com',
    'https://x.com/PortAuthorityJM',
    'https://www.instagram.com/portauthorityjm/',
    'https://www.linkedin.com/company/port-authority-of-jamaica/',
    'customs@jacustoms.gov.jm',
    'https://www.jacustoms.gov.jm',
    'Jamaica Customs Agency — Port of Kingston, Kingston, Jamaica',
  ),
  MS: seaport(
    'Port of Little Bay',
    'https://www.gov.ms/port/',
    'info@gov.ms',
    '',
    '',
    'https://www.linkedin.com/company/montserrat-ports/',
    'customs@gov.ms',
    'https://www.gov.ms/customs',
    'Montserrat Customs — Port of Little Bay, Little Bay, Montserrat',
  ),
  KN: seaport(
    'Port of Basseterre',
    'https://www.stkittsnevisports.com/',
    'info@stkittsnevisports.com',
    'https://x.com/StKittsPorts',
    'https://www.instagram.com/stkittsports/',
    'https://www.linkedin.com/company/st-kitts-nevis-ports/',
    'customs@customs.gov.kn',
    'https://www.customs.gov.kn',
    'St. Kitts and Nevis Customs — Port of Basseterre, Basseterre, Saint Kitts and Nevis',
  ),
  LC: seaport(
    'Port of Castries',
    'https://www.sluciaports.com/',
    'info@sluciaports.com',
    'https://x.com/StLuciaPorts',
    'https://www.instagram.com/stluciaports/',
    'https://www.linkedin.com/company/saint-lucia-ports-authority/',
    'customs@customs.gov.lc',
    'https://www.customs.gov.lc',
    'Saint Lucia Customs — Port of Castries, Castries, Saint Lucia',
  ),
  VC: seaport(
    'Port of Kingstown',
    'https://www.svgports.com/',
    'info@svgports.com',
    'https://x.com/SVGPorts',
    'https://www.instagram.com/svgports/',
    'https://www.linkedin.com/company/saint-vincent-ports/',
    'customs@customs.gov.vc',
    'https://www.customs.gov.vc',
    'Saint Vincent and the Grenadines Customs — Port of Kingstown, Kingstown, Saint Vincent and the Grenadines',
  ),
  SR: seaport(
    'Port of Paramaribo (Nieuwe Haven)',
    'https://www.havenbeheer.sr/',
    'info@havenbeheer.sr',
    'https://x.com/SurinamePorts',
    'https://www.instagram.com/surinameports/',
    'https://www.linkedin.com/company/suriname-ports/',
    'customs@customs.gov.sr',
    'https://www.customs.gov.sr',
    'Suriname Customs — Nieuwe Haven, Paramaribo, Suriname',
  ),
  TT: seaport(
    'Port of Port of Spain',
    'https://www.patnt.com/',
    'info@patnt.com',
    'https://x.com/PATNT',
    'https://www.instagram.com/patnt/',
    'https://www.linkedin.com/company/port-authority-of-trinidad-and-tobago/',
    'customs@customs.gov.tt',
    'https://www.customs.gov.tt',
    'Trinidad and Tobago Customs — Port of Spain, Port of Spain, Trinidad and Tobago',
  ),
  AI: seaport(
    'Port of Road Bay',
    'https://www.gov.ai/ports/',
    'info@gov.ai',
    '',
    '',
    'https://www.linkedin.com/company/anguilla-ports/',
    'customs@gov.ai',
    'https://www.gov.ai/customs',
    'Anguilla Customs — Road Bay, The Valley, Anguilla',
  ),
  BM: seaport(
    'Port of Hamilton',
    'https://www.bermudaports.com/',
    'info@bermudaports.com',
    'https://x.com/BermudaPorts',
    'https://www.instagram.com/bermudaports/',
    'https://www.linkedin.com/company/bermuda-ports/',
    'customs@customs.gov.bm',
    'https://www.customs.gov.bm',
    'Bermuda Customs — Port of Hamilton, Hamilton, Bermuda',
  ),
  VG: seaport(
    'Port Purcell (Road Town)',
    'https://www.bviports.org/',
    'info@bviports.org',
    'https://x.com/BVIPorts',
    'https://www.instagram.com/bviports/',
    'https://www.linkedin.com/company/bvi-ports-authority/',
    'customs@bvi.gov.vg',
    'https://www.bvi.gov.vg/customs',
    'British Virgin Islands Customs — Port Purcell, Road Town, Tortola',
  ),
  KY: seaport(
    'Port of Georgetown (Grand Cayman)',
    'https://www.ports.ky/',
    'info@ports.ky',
    'https://x.com/CaymanPorts',
    'https://www.instagram.com/caymanports/',
    'https://www.linkedin.com/company/cayman-islands-port-authority/',
    'customs@gov.ky',
    'https://www.customs.gov.ky',
    'Cayman Islands Customs — Port of Georgetown, Grand Cayman',
  ),
  TC: seaport(
    'Port of Grand Turk',
    'https://www.turksandcaicosports.tc/',
    'info@turksandcaicosports.tc',
    'https://x.com/TCPorts',
    'https://www.instagram.com/tcports/',
    'https://www.linkedin.com/company/turks-and-caicos-ports/',
    'customs@gov.tc',
    'https://www.gov.tc/customs',
    'Turks and Caicos Customs — Port of Grand Turk, Grand Turk',
  ),
}
