import type { CaricomMemberIsoCode } from './caricomMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const CARICOM_MAIN_INTERNATIONAL_AIRPORTS: Record<CaricomMemberIsoCode, MainInternationalAirport> = {
  AG: {
    name: 'V.C. Bird International Airport (ANU)',
    website: 'https://www.antigua-barbuda.com/',
    email: 'info@ab.gov.ag',
    twitter: 'https://x.com/AntiguaAirport',
    instagram: 'https://www.instagram.com/antiguaairport/',
    linkedin: 'https://www.linkedin.com/company/vc-bird-international-airport/',
    apiEndpoint: '',
  },
  BS: {
    name: 'Lynden Pindling International Airport (NAS)',
    website: 'https://www.nassaulpia.com/',
    email: 'info@nassaulpia.com',
    twitter: 'https://x.com/NassauAirport',
    instagram: 'https://www.instagram.com/nassauairport/',
    linkedin: 'https://www.linkedin.com/company/lynden-pindling-international-airport/',
    apiEndpoint: '',
  },
  BB: {
    name: 'Grantley Adams International Airport (BGI)',
    website: 'https://www.gaabarbados.org/',
    email: 'info@gaabarbados.org',
    twitter: 'https://x.com/GAABarbados',
    instagram: 'https://www.instagram.com/gaabarbados/',
    linkedin: 'https://www.linkedin.com/company/grantley-adams-international-airport/',
    apiEndpoint: '',
  },
  BZ: {
    name: 'Philip S.W. Goldson International Airport (BZE)',
    website: 'https://www.pgial.com.bz/',
    email: 'info@pgial.com.bz',
    twitter: 'https://x.com/BZEAirport',
    instagram: 'https://www.instagram.com/bzeairport/',
    linkedin: 'https://www.linkedin.com/company/philip-sw-goldson-international-airport/',
    apiEndpoint: '',
  },
  DM: {
    name: 'Douglas-Charles Airport (DOM)',
    website: 'https://www.dominicaairport.com/',
    email: 'info@dominicaairport.com',
    twitter: 'https://x.com/DominicaAirport',
    instagram: 'https://www.instagram.com/dominicaairport/',
    linkedin: 'https://www.linkedin.com/company/douglas-charles-airport/',
    apiEndpoint: '',
  },
  GD: {
    name: 'Maurice Bishop International Airport (GND)',
    website: 'https://www.grenadaairports.com/',
    email: 'info@grenadaairports.com',
    twitter: 'https://x.com/GrenadaAirport',
    instagram: 'https://www.instagram.com/grenadaairport/',
    linkedin: 'https://www.linkedin.com/company/maurice-bishop-international-airport/',
    apiEndpoint: '',
  },
  GY: {
    name: 'Cheddi Jagan International Airport (GEO)',
    website: 'https://www.cjairport-gy.com/',
    email: 'info@cjairport-gy.com',
    twitter: 'https://x.com/GuyanaAirport',
    instagram: 'https://www.instagram.com/guyanaairport/',
    linkedin: 'https://www.linkedin.com/company/cheddi-jagan-international-airport/',
    apiEndpoint: '',
  },
  HT: {
    name: 'Toussaint Louverture International Airport (PAP)',
    website: 'https://www.aan-haiti.com/',
    email: 'info@aan-haiti.com',
    twitter: 'https://x.com/HaitiAirport',
    instagram: 'https://www.instagram.com/haitiairport/',
    linkedin: 'https://www.linkedin.com/company/toussaint-louverture-international-airport/',
    apiEndpoint: '',
  },
  JM: {
    name: 'Norman Manley International Airport (KIN)',
    website: 'https://www.nmia.aero/',
    email: 'info@nmia.aero',
    twitter: 'https://x.com/NMIA_Airport',
    instagram: 'https://www.instagram.com/nmia_airport/',
    linkedin: 'https://www.linkedin.com/company/norman-manley-international-airport/',
    apiEndpoint: '',
  },
  MS: {
    name: 'John A. Osborne Airport (MNI)',
    website: 'https://www.flymontserrat.com/',
    email: 'info@flymontserrat.com',
    twitter: 'https://x.com/FlyMontserrat',
    instagram: 'https://www.instagram.com/flymontserrat/',
    linkedin: 'https://www.linkedin.com/company/john-a-osborne-airport/',
    apiEndpoint: '',
  },
  KN: {
    name: 'Robert L. Bradshaw International Airport (SKB)',
    website: 'https://www.stkittsskeairs.com/',
    email: 'info@stkittsskeairs.com',
    twitter: 'https://x.com/SKB_Airport',
    instagram: 'https://www.instagram.com/skb_airport/',
    linkedin: 'https://www.linkedin.com/company/robert-l-bradshaw-international-airport/',
    apiEndpoint: '',
  },
  LC: {
    name: 'Hewanorra International Airport (UVF)',
    website: 'https://www.slusha.com/',
    email: 'info@slusha.com',
    twitter: 'https://x.com/UVF_Airport',
    instagram: 'https://www.instagram.com/uvf_airport/',
    linkedin: 'https://www.linkedin.com/company/hewanorra-international-airport/',
    apiEndpoint: '',
  },
  VC: {
    name: 'Argyle International Airport (SVD)',
    website: 'https://www.svgairport.com/',
    email: 'info@svgairport.com',
    twitter: 'https://x.com/SVGAirport',
    instagram: 'https://www.instagram.com/svgairport/',
    linkedin: 'https://www.linkedin.com/company/argyle-international-airport/',
    apiEndpoint: '',
  },
  SR: {
    name: 'Johan Adolf Pengel International Airport (PBM)',
    website: 'https://www.jap-airport.com/',
    email: 'info@jap-airport.com',
    twitter: 'https://x.com/JAPAirport',
    instagram: 'https://www.instagram.com/japairport/',
    linkedin: 'https://www.linkedin.com/company/johan-adolf-pengel-international-airport/',
    apiEndpoint: '',
  },
  TT: {
    name: 'Piarco International Airport (POS)',
    website: 'https://www.tntairports.com/',
    email: 'info@tntairports.com',
    twitter: 'https://x.com/TNTAirports',
    instagram: 'https://www.instagram.com/tntairports/',
    linkedin: 'https://www.linkedin.com/company/trinidad-and-tobago-airports-authority/',
    apiEndpoint: '',
  },
  AI: {
    name: 'Clayton J. Lloyd International Airport (AXA)',
    website: 'https://www.anguilla-airways.com/',
    email: 'info@anguilla-airways.com',
    twitter: 'https://x.com/AnguillaAirport',
    instagram: 'https://www.instagram.com/anguillaairport/',
    linkedin: 'https://www.linkedin.com/company/clayton-j-lloyd-international-airport/',
    apiEndpoint: '',
  },
  BM: {
    name: 'L.F. Wade International Airport (BDA)',
    website: 'https://www.bermudaairport.com/',
    email: 'info@bermudaairport.com',
    twitter: 'https://x.com/BermudaAirport',
    instagram: 'https://www.instagram.com/bermudaairport/',
    linkedin: 'https://www.linkedin.com/company/lf-wade-international-airport/',
    apiEndpoint: '',
  },
  VG: {
    name: 'Terrance B. Lettsome International Airport (EIS)',
    website: 'https://www.bviaa.com/',
    email: 'info@bviaa.com',
    twitter: 'https://x.com/BVIAA',
    instagram: 'https://www.instagram.com/bviaa/',
    linkedin: 'https://www.linkedin.com/company/bvi-airports-authority/',
    apiEndpoint: '',
  },
  KY: {
    name: 'Owen Roberts International Airport (GCM)',
    website: 'https://www.caymanairports.com/',
    email: 'info@caymanairports.com',
    twitter: 'https://x.com/CaymanAirports',
    instagram: 'https://www.instagram.com/caymanairports/',
    linkedin: 'https://www.linkedin.com/company/cayman-airports-authority/',
    apiEndpoint: '',
  },
  TC: {
    name: 'Providenciales International Airport (PLS)',
    website: 'https://www.tciairports.com/',
    email: 'info@tciairports.com',
    twitter: 'https://x.com/TCIAirports',
    instagram: 'https://www.instagram.com/tciairports/',
    linkedin: 'https://www.linkedin.com/company/turks-and-caicos-islands-airports-authority/',
    apiEndpoint: '',
  },
}
