import type { CaricomMemberIsoCode } from './caricomMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const CARICOM_MAIN_EXPORT_COMMODITIES: Record<CaricomMemberIsoCode, MainExportCommodities> = {
  AG: m(
    'Tourism services',
    'Passenger ships',
    'Rum',
    'Fruit',
    'Fish',
    'Bed linen',
    'Electronics',
  ),
  BS: m(
    'Tourism services',
    'Refined petroleum',
    'Fish',
    'Rum',
    'Salt',
    'Aragonite',
    'Passenger ships',
  ),
  BB: m(
    'Rum',
    'Sugar',
    'Tourism services',
    'Chemicals',
    'Electronics',
    'Fish',
    'Manufactured goods',
  ),
  BZ: m(
    'Sugar',
    'Bananas',
    'Citrus fruit',
    'Crude petroleum',
    'Fish',
    'Tourism services',
    'Papayas',
  ),
  DM: m(
    'Bananas',
    'Soap',
    'Tourism services',
    'Citrus fruit',
    'Vegetables',
    'Cocoa',
    'Manufactured goods',
  ),
  GD: m(
    'Nutmeg',
    'Cocoa',
    'Fish',
    'Tourism services',
    'Mace',
    'Bananas',
    'Manufactured goods',
  ),
  GY: m(
    'Gold',
    'Rice',
    'Bauxite',
    'Sugar',
    'Shrimp',
    'Timber',
    'Aluminium ore',
  ),
  HT: m(
    'Garments',
    'Coffee',
    'Mango',
    'Essential oils',
    'Fish',
    'Cocoa',
    'Manufactured goods',
  ),
  JM: m(
    'Alumina',
    'Bauxite',
    'Rum',
    'Coffee',
    'Tourism services',
    'Yam',
    'Mining products',
  ),
  MS: m(
    'Electronic components',
    'Tourism services',
    'Rum',
    'Vegetables',
    'Fish',
    'Lime products',
    'Textiles',
  ),
  KN: m(
    'Electronics',
    'Tourism services',
    'Fish',
    'Passenger ships',
    'Rum',
    'Manufactured goods',
    'Financial services exports',
  ),
  LC: m(
    'Bananas',
    'Tourism services',
    'Beer',
    'Fish',
    'Electronics',
    'Cocoa',
    'Manufactured goods',
  ),
  VC: m(
    'Bananas',
    'Tourism services',
    'Arrowroot starch',
    'Fish',
    'Rum',
    'Manufactured goods',
    'Passenger ships',
  ),
  SR: m(
    'Gold',
    'Oil',
    'Rice',
    'Aluminium ore',
    'Shrimp',
    'Timber',
    'Bananas',
  ),
  TT: m(
    'Liquified natural gas',
    'Ammonia',
    'Methanol',
    'Iron and steel',
    'Petroleum products',
    'Chemicals',
    'Cocoa',
  ),
  AI: m(
    'Tourism services',
    'Rum',
    'Fish',
    'Lobster',
    'Salt',
    'Electronics',
    'Passenger transport',
  ),
  BM: m(
    'Tourism services',
    'Pharmaceuticals',
    'Fish',
    'Liquified natural gas re-exports',
    'Rum',
    'Financial services exports',
    'Electronics',
  ),
  VG: m(
    'Tourism services',
    'Fish',
    'Rum',
    'Sand and gravel',
    'Passenger ships',
    'Financial services exports',
    'Construction materials',
  ),
  KY: m(
    'Tourism services',
    'Fish',
    'Financial services exports',
    'Rum',
    'Re-exports',
    'Construction materials',
    'Passenger transport',
  ),
  TC: m(
    'Tourism services',
    'Fish',
    'Salt',
    'Lobster',
    'Financial services exports',
    'Construction materials',
    'Re-exports',
  ),
}
