import type { NationalBankingInstitution } from './types'
import type { CaricomMemberIsoCode } from './caricomMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per CARICOM member or associate territory.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const CARICOM_NATIONAL_BANKING_INSTITUTIONS: Record<
  CaricomMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AG: [
    bank(
      'Antigua Commercial Bank',
      '+1 268 481 8200',
      'High Street, St John\'s, Antigua and Barbuda',
      '',
      '',
      'https://www.acbonline.com',
      'customercare@acbonline.com',
      '',
      '',
      '',
      '',
      'ACBLAGAG',
      '',
    ),
    bank(
      'CUB (Caribbean Union Bank) Antigua',
      '+1 268 562 2582',
      'Friars Hill Road, St John\'s, Antigua and Barbuda',
      '',
      '',
      'https://www.caribbeanunionbank.com',
      'info@caribbeanunionbank.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Eastern Caribbean Amalgamated Bank',
      '+1 268 480 2225',
      'Old Parham Road, St John\'s, Antigua and Barbuda',
      '',
      '',
      'https://www.ecabank.com',
      'contact@ecabank.com',
      '',
      '',
      '',
      '',
      'ECAMAGAG',
      '',
    ),
  ],
  BS: [
    bank(
      'RBC Royal Bank Bahamas',
      '+1 242 356 8430',
      'East Hill Street, Nassau, Bahamas',
      '',
      '',
      'https://www.rbcroyalbank.com/caribbean/bahamas',
      'rbccaribbean@rbc.com',
      '',
      '',
      '',
      '',
      'ROYCBSNS',
      '',
    ),
    bank(
      'Bank of The Bahamas',
      '+1 242 397 8600',
      'Thompson Blvd, Nassau, Bahamas',
      '',
      '',
      'https://www.bob.bs',
      'customerservice@bob.bs',
      '',
      '',
      '',
      '',
      'BOTBBSNS',
      '',
    ),
    bank(
      'CIBC Caribbean Bahamas',
      '+1 242 502 6834',
      'Marlborough St, Nassau, Bahamas',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'bahamas@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBBSNS',
      '',
    ),
  ],
  BB: [
    bank(
      'Republic Bank Barbados',
      '+1 246 467 3000',
      'Independence Square, Bridgetown, Barbados',
      '',
      '',
      'https://www.republicbarbados.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBBBBB',
      '',
    ),
    bank(
      'RBC Royal Bank Barbados',
      '+1 246 467 8735',
      'Broad Street, Bridgetown, Barbados',
      '',
      '',
      'https://www.rbcroyalbank.com/caribbean/barbados',
      'rbccaribbean@rbc.com',
      '',
      '',
      '',
      '',
      'ROYCBBBB',
      '',
    ),
    bank(
      'CIBC Caribbean Barbados',
      '+1 246 367 2300',
      'Broad Street, Bridgetown, Barbados',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'barbados@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBBBBB',
      '',
    ),
  ],
  BZ: [
    bank(
      'Belize Bank',
      '+501 227 7092',
      'Blue Marlin Drive, Belize City, Belize',
      '',
      '',
      'https://www.belizebank.com',
      'customerservice@belizebank.com',
      '',
      '',
      '',
      '',
      'BELBBZBZ',
      '',
    ),
    bank(
      'Atlantic Bank',
      '+501 223 2948',
      '60 Euphrates Ave, Belize City, Belize',
      '',
      '',
      'https://www.atlabank.com',
      'customerservice@atlabank.com',
      '',
      '',
      '',
      '',
      'ATLCBZBZ',
      '',
    ),
    bank(
      'Heritage Bank Belize',
      '+501 223 2471',
      '1810 Coney Drive, Belize City, Belize',
      '',
      '',
      'https://www.heritage-bz.com',
      'info@heritage-bz.com',
      '',
      '',
      '',
      '',
      'HBBZBZBZ',
      '',
    ),
  ],
  DM: [
    bank(
      'National Bank of Dominica',
      '+1 767 255 2300',
      'Hillsborough St, Roseau, Dominica',
      '',
      '',
      'https://www.nbdominica.com',
      'info@nbdominica.com',
      '',
      '',
      '',
      '',
      'NATDDMDM',
      '',
    ),
    bank(
      'CIBC Caribbean Dominica',
      '+1 767 255 1000',
      'Old Street, Roseau, Dominica',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'dominica@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBDMDM',
      '',
    ),
    bank(
      'Republic Bank Dominica',
      '+1 767 255 3800',
      'Great Marlborough Street, Roseau, Dominica',
      '',
      '',
      'https://www.republicdominica.com',
      'info@republicdominica.com',
      '',
      '',
      '',
      '',
      'NISBDMDM',
      '',
    ),
  ],
  GD: [
    bank(
      'Grenada Co-operative Bank',
      '+1 473 440 1234',
      '8 Church Street, St George\'s, Grenada',
      '',
      '',
      'https://www.grenadaco-opbank.com',
      'info@grenadaco-opbank.com',
      '',
      '',
      '',
      '',
      'GCOBGDGD',
      '',
    ),
    bank(
      'Republic Bank Grenada',
      '+1 473 440 4440',
      'Grand Anse, St George\'s, Grenada',
      '',
      '',
      'https://www.republicgrenada.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBGDGD',
      '',
    ),
    bank(
      'CIBC Caribbean Grenada',
      '+1 473 440 2156',
      'Granby Street, St George\'s, Grenada',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'grenada@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBGDGD',
      '',
    ),
  ],
  GY: [
    bank(
      'Republic Bank Guyana',
      '+592 227 3278',
      'Water Street, Georgetown, Guyana',
      '',
      '',
      'https://www.republicguyana.com',
      'customer.service@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBGYGG',
      '',
    ),
    bank(
      'Guyana Bank for Trade and Industry',
      '+592 226 3256',
      '179 Water Street, Georgetown, Guyana',
      '',
      '',
      'https://www.gbti.com',
      'info@gbti.com',
      '',
      '',
      '',
      '',
      'GBTIGYGE',
      '',
    ),
    bank(
      'Demerara Bank',
      '+592 225 6718',
      '230 Camp Street, Georgetown, Guyana',
      '',
      '',
      'https://demerarabank.com',
      'info@demerarabank.com',
      '',
      '',
      '',
      '',
      'DEMBGYGG',
      '',
    ),
  ],
  HT: [
    bank(
      'Sogebank',
      '+509 2813 4000',
      'Rue Pavée 31, Port-au-Prince, Haiti',
      '',
      '',
      'https://www.sogebank.com',
      'info@sogebank.com',
      '',
      '',
      '',
      '',
      'SOGHHTPP',
      '',
    ),
    bank(
      'Unibank',
      '+509 2812 5000',
      'Angle Rue Lamarre et Rue du Centre, Port-au-Prince, Haiti',
      '',
      '',
      'https://www.unibankhaiti.com',
      'info@unibankhaiti.com',
      '',
      '',
      '',
      '',
      'UBNKHTPP',
      '',
    ),
    bank(
      'Banque Nationale de Credit (BNC)',
      '+509 2811 1111',
      'Rue des Miracles 56, Port-au-Prince, Haiti',
      '',
      '',
      'https://www.bnc.ht',
      'contact@bnc.ht',
      '',
      '',
      '',
      '',
      'BNCHHTPP',
      '',
    ),
  ],
  JM: [
    bank(
      'National Commercial Bank Jamaica',
      '+1 876 929 4622',
      '2-4 Slipe Road, Kingston, Jamaica',
      '',
      '',
      'https://www.jncb.com',
      'customercare@jncb.com',
      '',
      '',
      '',
      '',
      'JNCBJMKX',
      '',
    ),
    bank(
      'Scotiabank Jamaica',
      '+1 876 960 2675',
      '2 Oxford Road, Kingston, Jamaica',
      '',
      '',
      'https://jm.scotiabank.com',
      'customer.care@scotiabank.com',
      '',
      '',
      '',
      '',
      'NOSCJMKN',
      '',
    ),
    bank(
      'JN Bank',
      '+1 876 906 5343',
      '30 Duke Street, Kingston, Jamaica',
      '',
      '',
      'https://www.jnbank.com',
      'support@jnbank.com',
      '',
      '',
      '',
      '',
      'JNBSJMKX',
      '',
    ),
  ],
  MS: [
    bank(
      'Bank of Montserrat',
      '+1 664 491 3846',
      'Brades Main Road, Brades, Montserrat',
      '',
      '',
      'https://www.bankofmontserrat.ms',
      'info@bankofmontserrat.ms',
      '',
      '',
      '',
      '',
      'BOMSMSMS',
      '',
    ),
    bank(
      'Republic Bank Montserrat',
      '+1 664 491 4702',
      'Brades Main Road, Brades, Montserrat',
      '',
      '',
      'https://www.republictt.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBMSMS',
      '',
    ),
    bank(
      'CIBC Caribbean Montserrat',
      '+1 664 491 3788',
      'Brades Main Road, Brades, Montserrat',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'montserrat@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBMSMS',
      '',
    ),
  ],
  KN: [
    bank(
      'St Kitts-Nevis-Anguilla National Bank',
      '+1 869 465 2204',
      'Central Street, Basseterre, St Kitts and Nevis',
      '',
      '',
      'https://www.sknanb.com',
      'customerservice@sknanb.com',
      '',
      '',
      '',
      '',
      'SKNAKNBB',
      '',
    ),
    bank(
      'CIBC Caribbean St Kitts',
      '+1 869 465 2421',
      'The Circus, Basseterre, St Kitts and Nevis',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'stkitts@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBKNBB',
      '',
    ),
    bank(
      'Republic Bank St Kitts and Nevis',
      '+1 869 466 2900',
      'Fort Street, Basseterre, St Kitts and Nevis',
      '',
      '',
      'https://www.republicskn.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBKNBB',
      '',
    ),
  ],
  LC: [
    bank(
      'Bank of Saint Lucia',
      '+1 758 456 6000',
      'Bridge Street, Castries, Saint Lucia',
      '',
      '',
      'https://www.bankofsaintlucia.com',
      'customerservice@bosl.com',
      '',
      '',
      '',
      '',
      'BOSLLCLC',
      '',
    ),
    bank(
      '1st National Bank Saint Lucia',
      '+1 758 450 2100',
      'Bridge Street, Castries, Saint Lucia',
      '',
      '',
      'https://www.1stnationalbankslu.com',
      'info@1stnationalbankslu.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Republic Bank Saint Lucia',
      '+1 758 451 3000',
      'William Peter Blvd, Castries, Saint Lucia',
      '',
      '',
      'https://www.republicstlucia.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBLCLC',
      '',
    ),
  ],
  VC: [
    bank(
      'Bank of St Vincent and the Grenadines',
      '+1 784 457 1845',
      'Halifax Street, Kingstown, Saint Vincent and the Grenadines',
      '',
      '',
      'https://www.bosvg.com',
      'customerservice@bosvg.com',
      '',
      '',
      '',
      '',
      'BOSVVCVC',
      '',
    ),
    bank(
      'CIBC Caribbean St Vincent',
      '+1 784 456 1185',
      'Halifax Street, Kingstown, Saint Vincent and the Grenadines',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'stvincent@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBVCVC',
      '',
    ),
    bank(
      'Republic Bank St Vincent',
      '+1 784 452 4375',
      'Granby Street, Kingstown, Saint Vincent and the Grenadines',
      '',
      '',
      'https://www.republicsvg.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBVCVC',
      '',
    ),
  ],
  SR: [
    bank(
      'De Surinaamsche Bank',
      '+597 471100',
      'Henck Arronstraat 26-30, Paramaribo, Suriname',
      '',
      '',
      'https://www.dsb.sr',
      'info@dsb.sr',
      '',
      '',
      '',
      '',
      'SURBSRPB',
      '',
    ),
    bank(
      'Republic Bank Suriname',
      '+597 471500',
      'Dr. Sophie Redmondstraat, Paramaribo, Suriname',
      '',
      '',
      'https://www.republicbanksr.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBSRPB',
      '',
    ),
    bank(
      'Hakrinbank',
      '+597 477722',
      'Dr. J.F. Nassylaan 1, Paramaribo, Suriname',
      '',
      '',
      'https://www.hakrinbank.com',
      'info@hakrinbank.com',
      '',
      '',
      '',
      '',
      'HAKRSRPB',
      '',
    ),
  ],
  TT: [
    bank(
      'Republic Bank Trinidad and Tobago',
      '+1 868 623 1057',
      '9-17 Park Street, Port of Spain, Trinidad and Tobago',
      '',
      '',
      'https://republictt.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBTTPS',
      '',
    ),
    bank(
      'First Citizens Bank',
      '+1 868 624 3178',
      '9 Queen\'s Park East, Port of Spain, Trinidad and Tobago',
      '',
      '',
      'https://www.firstcitizenstt.com',
      'contact@firstcitizenstt.com',
      '',
      '',
      '',
      '',
      'FCBKTTPS',
      '',
    ),
    bank(
      'Scotiabank Trinidad and Tobago',
      '+1 868 627 2684',
      '56-58 Richmond Street, Port of Spain, Trinidad and Tobago',
      '',
      '',
      'https://tt.scotiabank.com',
      'customercarett@scotiabank.com',
      '',
      '',
      '',
      '',
      'NOSCTTPS',
      '',
    ),
  ],
  AI: [
    bank(
      'National Bank of Anguilla',
      '+1 264 497 2381',
      'The Valley, Anguilla',
      '',
      '',
      'https://www.nba.ai',
      'info@nba.ai',
      '',
      '',
      '',
      '',
      'NBAIAIAI',
      '',
    ),
    bank(
      'Scotiabank Anguilla',
      '+1 264 497 2355',
      'The Valley, Anguilla',
      '',
      '',
      'https://www.scotiabank.com/caribbean',
      'service@scotiabank.com',
      '',
      '',
      '',
      '',
      'NOSCAIAI',
      '',
    ),
    bank(
      'CIBC Caribbean Anguilla',
      '+1 264 497 2500',
      'The Valley, Anguilla',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'anguilla@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBAIAA',
      '',
    ),
  ],
  BM: [
    bank(
      'Butterfield Bank Bermuda',
      '+1 441 295 1111',
      '65 Front Street, Hamilton, Bermuda',
      '',
      '',
      'https://www.butterfieldgroup.com',
      'customerservice@butterfieldgroup.com',
      '',
      '',
      '',
      '',
      'BNTBBMHM',
      '',
    ),
    bank(
      'HSBC Bank Bermuda',
      '+1 441 295 4000',
      '37 Front Street, Hamilton, Bermuda',
      '',
      '',
      'https://www.hsbc.bm',
      'bermuda@hsbc.com',
      '',
      '',
      '',
      '',
      'BBDABMHM',
      '',
    ),
    bank(
      'Clarien Bank',
      '+1 441 296 6969',
      '19 Reid Street, Hamilton, Bermuda',
      '',
      '',
      'https://www.clarienbank.com',
      'info@clarienbank.com',
      '',
      '',
      '',
      '',
      'CLARBMBM',
      '',
    ),
  ],
  VG: [
    bank(
      'FirstBank Virgin Islands',
      '+1 284 494 5669',
      'Administration Drive, Road Town, Tortola, British Virgin Islands',
      '',
      '',
      'https://www.firstbankvi.com',
      'info@firstbankvi.com',
      '',
      '',
      '',
      '',
      'FBNVVGVI',
      '',
    ),
    bank(
      'Scotiabank British Virgin Islands',
      '+1 284 494 3250',
      'Wickhams Cay I, Road Town, Tortola, British Virgin Islands',
      '',
      '',
      'https://www.scotiabank.com/caribbean',
      'service@scotiabank.com',
      '',
      '',
      '',
      '',
      'NOSCVGVG',
      '',
    ),
    bank(
      'VP Bank (BVI) Limited',
      '+1 284 494 4000',
      'Wickhams Cay I, Road Town, Tortola, British Virgin Islands',
      '',
      '',
      'https://www.vpbank.com',
      'bvi@vpbank.com',
      '',
      '',
      '',
      '',
      'VPBKBVVG',
      '',
    ),
  ],
  KY: [
    bank(
      'Cayman National Bank',
      '+1 345 949 4655',
      'Elgin Avenue, George Town, Grand Cayman, Cayman Islands',
      '',
      '',
      'https://www.caymannational.com',
      'info@caymannational.com',
      '',
      '',
      '',
      '',
      'CAYNKYKY',
      '',
    ),
    bank(
      'Butterfield Bank Cayman',
      '+1 345 949 7055',
      '68 Fort Street, George Town, Grand Cayman, Cayman Islands',
      '',
      '',
      'https://www.butterfieldgroup.com',
      'customerservice@butterfieldgroup.com',
      '',
      '',
      '',
      '',
      'BNTBKYKY',
      '',
    ),
    bank(
      'Scotiabank Cayman Islands',
      '+1 345 949 7665',
      'Cardinall Avenue, George Town, Grand Cayman, Cayman Islands',
      '',
      '',
      'https://www.scotiabank.com/caribbean',
      'service@scotiabank.com',
      '',
      '',
      '',
      '',
      'NOSCKYKY',
      '',
    ),
  ],
  TC: [
    bank(
      'Turks and Caicos Banking Company',
      '+1 649 946 2801',
      'Grace Bay, Providenciales, Turks and Caicos Islands',
      '',
      '',
      'https://www.tcbc.tc',
      'info@tcbc.tc',
      '',
      '',
      '',
      '',
      'TCBCTCKY',
      '',
    ),
    bank(
      'Scotiabank Turks and Caicos',
      '+1 649 946 3661',
      'Grace Bay, Providenciales, Turks and Caicos Islands',
      '',
      '',
      'https://www.scotiabank.com/caribbean',
      'service@scotiabank.com',
      '',
      '',
      '',
      '',
      'NOSCTCKY',
      '',
    ),
    bank(
      'CIBC Caribbean Turks and Caicos',
      '+1 649 941 5021',
      'Leeward Highway, Providenciales, Turks and Caicos Islands',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'turksandcaicos@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBTCKY',
      '',
    ),
  ],
}
