import type { NationalBankingInstitution } from './types'
import type { AesMemberIsoCode } from './aesMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per AES founding member — retail and commercial
 * banks commonly used by citizens and foreign nationals. Informational; verify phone numbers,
 * branch addresses, routing codes, SWIFT/BIC, mobile apps, social handles, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const AES_NATIONAL_BANKING_INSTITUTIONS: Record<
  AesMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  BF: [
    bank(
      'Coris Bank International (CBI)',
      '+226 25 37 77 77',
      'Avenue Kwame N\'Krumah, Ouagadougou 01 BP 5487, Burkina Faso',
      '',
      'https://play.google.com/store/apps/details?id=com.coris.mobile',
      'https://www.corisbank.com/',
      'contact@corisbank.com',
      'https://x.com/CorisBank',
      'https://www.instagram.com/corisbank/',
      'https://www.linkedin.com/company/coris-bank-international/',
      '',
      '',
      '',
    ),
    bank(
      'Ecobank Burkina Faso',
      '+226 25 30 62 30',
      'Avenue Kwame N\'Krumah, Ouagadougou 01 BP 4540, Burkina Faso',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/bf',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Bank of Africa Burkina Faso (BOA-BF)',
      '+226 25 31 28 28',
      'Avenue de la Nation, Ouagadougou 01 BP 5139, Burkina Faso',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boa-bf.com/',
      'contact@boa-bf.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      '',
      '',
    ),
  ],
  ML: [
    bank(
      'Bank of Africa Mali (BOA Mali)',
      '+223 20 22 33 44',
      'Avenue du Mali, Bamako BP E 2798, Mali',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boamali.com/',
      'contact@boamali.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      '',
      '',
    ),
    bank(
      'Ecobank Mali',
      '+223 20 22 99 99',
      'Avenue du Mali, Bamako BP 224, Mali',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/ml',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Banque de Developpement du Mali (BDM)',
      '+223 20 22 12 12',
      'Avenue Modibo Keita, Bamako BP 224, Mali',
      '',
      'https://play.google.com/store/apps/details?id=com.bdm.mobile',
      'https://www.bdm.ml/',
      'contact@bdm.ml',
      '',
      '',
      'https://www.linkedin.com/company/banque-de-d%C3%A9veloppement-du-mali/',
      '',
      '',
      '',
    ),
  ],
  NE: [
    bank(
      'Ecobank Niger',
      '+227 20 73 20 20',
      'Avenue du General de Gaulle, Niamey BP 11207, Niger',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/ne',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      '',
      '',
    ),
    bank(
      'Banque Commerciale du Niger (BCN)',
      '+227 20 73 33 33',
      'Avenue du General de Gaulle, Niamey BP 11207, Niger',
      '',
      'https://play.google.com/store/apps/details?id=com.bankoafrica.mobile',
      'https://www.boa-ne.com/',
      'contact@boa-ne.com',
      'https://x.com/BankofAfrica',
      'https://www.instagram.com/bankofafrica/',
      'https://www.linkedin.com/company/bank-of-africa/',
      '',
      '',
      '',
    ),
    bank(
      'BIA-Niger (Banque Internationale pour l Afrique au Niger)',
      '+227 20 73 11 11',
      'Rue du Commerce, Niamey BP 10966, Niger',
      '',
      'https://play.google.com/store/apps/details?id=com.bianiger.mobile',
      'https://www.bianiger.com/',
      'contact@bianiger.com',
      '',
      '',
      'https://www.linkedin.com/company/bia-niger/',
      '',
      '',
      '',
    ),
  ],
}
