import type { CorporationFormationOffice } from './types'
import type { RcepMemberIsoCode } from './rcepMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per RCEP party economy.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const RCEP_CORPORATION_FORMATION_OFFICES: Record<RcepMemberIsoCode, CorporationFormationOffice> = {
  AU:   office(
    'Australian Securities and Investments Commission (ASIC)',
    '+61 1300 300 630',
    'Level 5, 100 Market Street, Sydney NSW 2000, Australia',
    'https://asic.gov.au',
    '',
    'https://twitter.com/asicmedia',
    '',
    'https://www.linkedin.com/company/australian-securities-and-investments-commission/',
    'https://asic.gov.au/for-business/registering-a-company/',
    'https://business.gov.au/planning/new-businesses/register-a-company',
    'Australian Company Number (ACN)',
  ),
  BN:   office(
    'Registry of Companies and Business Names (ROCBN)',
    '+673 2383444',
    'Ministry of Finance and Economy, Bandar Seri Begawan, Brunei Darussalam',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    '',
    '',
    '',
    '',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    'https://business.gov.bn/SitePages/Starting%20a%20Business.aspx',
    'Business Registration Number',
  ),
  KH:   office(
    'Business Registration (Ministry of Commerce Cambodia)',
    '+855 23 866 050',
    'Lot 19-61, Russian Blvd, Phnom Penh, Cambodia',
    'https://www.businessregistration.moc.gov.kh',
    '',
    '',
    '',
    '',
    'https://www.businessregistration.moc.gov.kh',
    'https://www.moc.gov.kh/en-us/service/business-registration',
    'Enterprise Registration Number',
  ),
  CN:   office(
    'State Administration for Market Regulation (Enterprise Registration)',
    '+86 10 8865 0000',
    'No. 8 Sanlihe East Road, Xicheng District, Beijing, China',
    'https://www.samr.gov.cn',
    '',
    '',
    '',
    '',
    'https://zwfw.samr.gov.cn',
    'https://www.gov.cn/fuwu/2015-12/09/content_5022390.htm',
    'Unified Social Credit Code',
  ),
  ID:   office(
    'OSS Indonesia (Ministry of Investment/BKPM)',
    '+62 21 1500 123',
    'Jl. Jenderal Gatot Subroto No. 44, Jakarta, Indonesia',
    'https://oss.go.id',
    '',
    '',
    '',
    '',
    'https://oss.go.id',
    'https://www.bkpm.go.id/en/public-service',
    'Nomor Induk Berusaha (NIB)',
  ),
  JP:   office(
    'Legal Affairs Bureau (Ministry of Justice Commercial Registration)',
    '+81 3 3580 4111',
    '1-1-1 Kasumigaseki, Chiyoda-ku, Tokyo, Japan',
    'https://www.moj.go.jp',
    '',
    '',
    '',
    '',
    'https://www.moj.go.jp/MINJI/minji06.html',
    'https://www.jetro.go.jp/en/invest/setting_up/section1/page3.html',
    'Corporate Number (Houjin Bango)',
  ),
  KR:   office(
    'Supreme Court Internet Registry Office',
    '+82 2 3480 1715',
    'Seocho-daero, Seocho-gu, Seoul, Republic of Korea',
    'https://www.iros.go.kr',
    '',
    '',
    '',
    '',
    'https://www.iros.go.kr',
    'https://www.k-startup.go.kr/common/post/detail.do?postSn=95',
    'Business Registration Number',
  ),
  LA:   office(
    'Enterprise Registration Office (Ministry of Industry and Commerce)',
    '+856 21 412 011',
    'Vientiane, Lao PDR',
    'https://erm.gov.la',
    '',
    '',
    '',
    '',
    'https://erm.gov.la',
    'https://www.laotradeportal.gov.la/kcfinder/upload/files/Forms%20for%20business%20registration.pdf',
    'Enterprise Registration Certificate Number',
  ),
  MY:   office(
    'Companies Commission of Malaysia (SSM)',
    '+60 3 7721 4000',
    'Menara SSM@Sentral, No. 7 Jalan Stesen Sentral 5, Kuala Lumpur, Malaysia',
    'https://www.ssm.com.my',
    'enquiry@ssm.com.my',
    '',
    '',
    '',
    'https://ezbiz.ssm.com.my',
    'https://www.ssm.com.my/Pages/Legal_Framework/Company/Guidelines.aspx',
    'Company Number',
  ),
  MM:   office(
    'Directorate of Investment and Company Administration (DICA)',
    '+95 1 658118',
    'Building 1, Nay Pyi Taw, Myanmar',
    'https://www.dica.gov.mm',
    '',
    '',
    '',
    '',
    'https://www.myco.dica.gov.mm',
    'https://www.dica.gov.mm/en/service',
    'Company Registration Number',
  ),
  NZ:   office(
    'New Zealand Companies Office',
    '+64 50 872 2669',
    'Wellington, New Zealand',
    'https://companies-register.companiesoffice.govt.nz',
    '',
    '',
    '',
    '',
    'https://companies-register.companiesoffice.govt.nz/help-centre/starting-a-company',
    'https://www.business.govt.nz/getting-started/advice-for-start-ups/10-step-guide-to-starting-a-business/',
    'New Zealand Business Number (NZBN)',
  ),
  PH:   office(
    'Securities and Exchange Commission Philippines (eSPARC)',
    '+63 2 8818 0921',
    '7907 Makati Avenue, Salcedo Village, Makati, Philippines',
    'https://www.sec.gov.ph',
    'imessagemo@sec.gov.ph',
    '',
    '',
    '',
    'https://esparc.sec.gov.ph',
    'https://www.sec.gov.ph/wp-content/uploads/2022/02/2022MC_no3.pdf',
    'SEC Registration Number',
  ),
  SG:   office(
    'Accounting and Corporate Regulatory Authority (ACRA)',
    '+65 6248 6028',
    '10 Anson Road, International Plaza, Singapore',
    'https://www.acra.gov.sg',
    '',
    '',
    '',
    'https://www.linkedin.com/company/accounting-and-corporate-regulatory-authority-acra-/',
    'https://www.bizfile.gov.sg',
    'https://www.acra.gov.sg/how-to-guides/before-you-start/incorporation',
    'Unique Entity Number (UEN)',
  ),
  TH:   office(
    'Department of Business Development (DBD)',
    '+66 2 547 5959',
    'Nonthaburi, Thailand',
    'https://www.dbd.go.th',
    '',
    '',
    '',
    '',
    'https://www.dbd.go.th',
    'https://www.dbd.go.th/download/article/article_20200617110202.pdf',
    'Company Registration Number',
  ),
  VN:   office(
    'Business Registration Management Agency (Ministry of Finance)',
    '+84 24 0804 3128',
    'Hanoi, Vietnam',
    'https://dangkykinhdoanh.gov.vn',
    '',
    '',
    '',
    '',
    'https://dangkykinhdoanh.gov.vn',
    'https://dangkykinhdoanh.gov.vn/vn/Pages/Trangchu.aspx',
    'Tax Identification Number (MST)',
  ),
}
