import type { RcepMemberIsoCode } from './rcepMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per RCEP party economy.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const RCEP_DOMESTIC_POST_SERVICES: Record<RcepMemberIsoCode, DomesticPostService> = {
  AU: post(
    'Australia Post',
    'https://auspost.com.au/',
    'feedback@auspost.com.au',
    'https://x.com/AusPost',
    'https://www.instagram.com/auspost/',
    'https://www.linkedin.com/company/australia-post/',
    'https://developers.auspost.com.au/',
    'NNNN',
    '^\\d{4}$',
    '2000',
    'Four-digit postcode',
  ),
  BN: post(
    'Postal Services Department (Brunei)',
    'https://www.post.gov.bn/',
    'postmaster@post.gov.bn',
    '',
    '',
    'https://www.linkedin.com/company/postal-services-department-brunei/',
    '',
    'AANNNN',
    '^[A-Z]{2}\\d{4}$',
    'BA2110',
    'Two-letter area + four digits (Brunei Darussalam)',
  ),
  KH: post(
    'Cambodia Post',
    'https://www.cambodiapost.com.kh/',
    'info@cambodiapost.com.kh',
    '',
    '',
    'https://www.linkedin.com/company/cambodia-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '12000',
    'Five-digit postcode',
  ),
  CN: post(
    'China Post',
    'https://www.ems.com.cn/',
    'service@ems.com.cn',
    'https://x.com/chinapost',
    'https://www.instagram.com/chinapost/',
    'https://www.linkedin.com/company/china-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
  ID: post(
    'Pos Indonesia',
    'https://www.posindonesia.co.id/',
    'pusatbantuan@posindonesia.co.id',
    'https://x.com/PosIndonesia',
    'https://www.instagram.com/posindonesia/',
    'https://www.linkedin.com/company/pos-indonesia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10110',
    'Five-digit postcode',
  ),
  JP: post(
    'Japan Post',
    'https://www.post.japanpost.jp/',
    'info@jp-network.japanpost.jp',
    'https://x.com/japanpost_off',
    'https://www.instagram.com/japanpost_off/',
    'https://www.linkedin.com/company/japan-post-holdings/',
    '',
    'NNN-NNNN',
    '^\\d{3}-\\d{4}$',
    '100-0001',
    'Three-digit + four-digit postcode (hyphenated)',
  ),
  KR: post(
    'Korea Post',
    'https://www.koreapost.go.kr/',
    'help@koreapost.go.kr',
    'https://x.com/koreapost',
    'https://www.instagram.com/koreapost/',
    'https://www.linkedin.com/company/korea-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '04524',
    'Five-digit postcode (reformed 2015)',
  ),
  LA: post(
    'Lao Post',
    'https://www.laopost.com.la/',
    'info@laopost.la',
    '',
    '',
    'https://www.linkedin.com/company/lao-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '01000',
    'Five-digit postcode',
  ),
  MY: post(
    'Pos Malaysia',
    'https://www.pos.com.my/',
    'customercare@pos.com.my',
    'https://x.com/posmalaysia',
    'https://www.instagram.com/posmalaysia/',
    'https://www.linkedin.com/company/pos-malaysia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '50000',
    'Five-digit postcode',
  ),
  MM: post(
    'Myanmar Post',
    'https://www.myanmarpost.com.mm/',
    'info@myanmarpost.com.mm',
    '',
    '',
    'https://www.linkedin.com/company/myanmar-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '11181',
    'Five-digit postcode (Yangon)',
  ),
  NZ: post(
    'NZ Post',
    'https://www.nzpost.co.nz/',
    'customercare@nzpost.co.nz',
    'https://x.com/NZPost',
    'https://www.instagram.com/nzpost/',
    'https://www.linkedin.com/company/nz-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '6011',
    'Four-digit postcode',
  ),
  PH: post(
    'Philippine Postal Corporation (PHLPost)',
    'https://www.phlpost.gov.ph/',
    'info@phlpost.gov.ph',
    'https://x.com/PHLPost',
    'https://www.instagram.com/phlpost/',
    'https://www.linkedin.com/company/philippine-postal-corporation/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  SG: post(
    'Singapore Post',
    'https://www.singpost.com/',
    'feedback@singpost.com',
    'https://x.com/SingPost',
    'https://www.instagram.com/singpost/',
    'https://www.linkedin.com/company/singapore-post-limited/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '018956',
    'Six-digit postcode',
  ),
  TH: post(
    'Thailand Post',
    'https://www.thailandpost.co.th/',
    'contact@thailandpost.co.th',
    'https://x.com/ThailandPost',
    'https://www.instagram.com/thailandpost/',
    'https://www.linkedin.com/company/thailand-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '10100',
    'Five-digit postcode',
  ),
  VN: post(
    'Vietnam Post (VNPost)',
    'https://www.vnpost.vn/',
    'contact@vnpost.vn',
    'https://x.com/VNPost',
    'https://www.instagram.com/vnpost/',
    'https://www.linkedin.com/company/vietnam-post/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '100000',
    'Six-digit postcode',
  ),
}
