import type { RcepMemberIsoCode } from './rcepMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for Regional Comprehensive
 * Economic Partnership (RCEP) parties in this module (informational; verify URLs, handles,
 * forms portals, and API bases before production use). Self-contained — no imports from other
 * alliance modules. `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const RCEP_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  RcepMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AU: roster(
    ip(
      'copyright',
      'Australian Government — Attorney-General\'s Department (Copyright)',
      'https://www.ag.gov.au/rights-and-protections/copyright',
      '',
      '',
      '',
      'https://www.ag.gov.au/rights-and-protections/copyright',
    ),
    ip(
      'trademarks',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
    ip(
      'patents',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
  ),
  BN: roster(
    ip(
      'copyright',
      'Brunei Darussalam Intellectual Property Office (BruIPO) — copyright',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'trademarks',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'patents',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
  ),
  KH: roster(
    ip(
      'copyright',
      'Ministry of Culture and Fine Arts — copyright (Cambodia)',
      'https://www.cambodiaip.gov.kh',
      '',
      '',
      '',
      'https://www.cambodiaip.gov.kh',
    ),
    ip(
      'trademarks',
      'Department of Intellectual Property Rights (Ministry of Commerce, Cambodia)',
      'https://www.cambodiaip.gov.kh',
      'info@cambodiaip.gov.kh',
      '',
      '',
      'https://www.cambodiaip.gov.kh',
    ),
    ip(
      'patents',
      'Department of Intellectual Property Rights (Ministry of Commerce, Cambodia)',
      'https://www.cambodiaip.gov.kh',
      'info@cambodiaip.gov.kh',
      '',
      '',
      'https://www.cambodiaip.gov.kh',
    ),
  ),
  CN: roster(
    ip(
      'copyright',
      'National Copyright Administration of the People\'s Republic of China (NCAC)',
      'https://www.ncac.gov.cn',
      '',
      '',
      '',
      'https://www.ncac.gov.cn',
    ),
    ip(
      'trademarks',
      'China National Intellectual Property Administration (CNIPA)',
      'https://www.cnipa.gov.cn',
      '',
      '',
      '',
      'https://cponline.cnipa.gov.cn',
    ),
    ip(
      'patents',
      'China National Intellectual Property Administration (CNIPA)',
      'https://www.cnipa.gov.cn',
      '',
      '',
      '',
      'https://cponline.cnipa.gov.cn',
    ),
  ),
  ID: roster(
    ip(
      'copyright',
      'Directorate General of Intellectual Property (DGIP) — copyright',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'trademarks',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
    ip(
      'patents',
      'Directorate General of Intellectual Property (DGIP)',
      'https://dgip.go.id',
      'dgip@kemenkumham.go.id',
      '',
      'https://www.linkedin.com/company/directorate-general-of-intellectual-property-indonesia/',
      'https://pdki-indonesia.dgip.go.id',
    ),
  ),
  JP: roster(
    ip(
      'copyright',
      'Agency for Cultural Affairs (Government of Japan — Copyright)',
      'https://www.bunka.go.jp/english/',
      '',
      '',
      '',
      'https://www.bunka.go.jp/english/copyright/index.html',
    ),
    ip(
      'trademarks',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
    ip(
      'patents',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
  ),
  KR: roster(
    ip(
      'copyright',
      'Korea Copyright Commission (KCC)',
      'https://www.copyright.or.kr',
      'help@copyright.or.kr',
      '',
      '',
      'https://www.copyright.or.kr',
    ),
    ip(
      'trademarks',
      'Korean Intellectual Property Office (KIPO)',
      'https://www.kipo.go.kr',
      '',
      '',
      '',
      'https://www.patent.go.kr',
    ),
    ip(
      'patents',
      'Korean Intellectual Property Office (KIPO)',
      'https://www.kipo.go.kr',
      '',
      '',
      '',
      'https://www.patent.go.kr',
    ),
  ),
  LA: roster(
    ip(
      'copyright',
      'Department of Intellectual Property (Ministry of Science and Technology, Laos)',
      'https://www.laip.gov.la',
      '',
      '',
      '',
      'https://www.laip.gov.la',
    ),
    ip(
      'trademarks',
      'Department of Intellectual Property (Ministry of Science and Technology, Laos)',
      'https://www.laip.gov.la',
      '',
      '',
      '',
      'https://www.laip.gov.la',
    ),
    ip(
      'patents',
      'Department of Intellectual Property (Ministry of Science and Technology, Laos)',
      'https://www.laip.gov.la',
      '',
      '',
      '',
      'https://www.laip.gov.la',
    ),
  ),
  MY: roster(
    ip(
      'copyright',
      'Intellectual Property Corporation of Malaysia (MyIPO) — copyright',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'trademarks',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'patents',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
  ),
  MM: roster(
    ip(
      'copyright',
      'Myanmar Copyright Office (Ministry of Religious Affairs and Culture)',
      'https://www.myanmarip.gov.mm',
      '',
      '',
      '',
      'https://www.myanmarip.gov.mm',
    ),
    ip(
      'trademarks',
      'Intellectual Property Department (Ministry of Commerce, Myanmar)',
      'https://www.myanmarip.gov.mm',
      'info@mipo.gov.mm',
      '',
      '',
      'https://www.myanmarip.gov.mm',
    ),
    ip(
      'patents',
      'Intellectual Property Department (Ministry of Commerce, Myanmar)',
      'https://www.myanmarip.gov.mm',
      'info@mipo.gov.mm',
      '',
      '',
      'https://www.myanmarip.gov.mm',
    ),
  ),
  NZ: roster(
    ip(
      'copyright',
      'Manatū Taonga — Ministry for Culture and Heritage (Copyright)',
      'https://www.mch.govt.nz',
      'info@mch.govt.nz',
      '',
      '',
      'https://www.mch.govt.nz/copyright',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
    ip(
      'patents',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
  ),
  PH: roster(
    ip(
      'copyright',
      'Intellectual Property Office of the Philippines (IPOPHL) — copyright',
      'https://www.ipophil.gov.ph',
      'info@ipophil.gov.ph',
      'https://x.com/IPOPHL',
      'https://www.linkedin.com/company/intellectual-property-office-of-the-philippines/',
      'https://epayment.ipophil.gov.ph/',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of the Philippines (IPOPHL)',
      'https://www.ipophil.gov.ph',
      'info@ipophil.gov.ph',
      'https://x.com/IPOPHL',
      'https://www.linkedin.com/company/intellectual-property-office-of-the-philippines/',
      'https://epayment.ipophil.gov.ph/',
    ),
    ip(
      'patents',
      'Intellectual Property Office of the Philippines (IPOPHL)',
      'https://www.ipophil.gov.ph',
      'info@ipophil.gov.ph',
      'https://x.com/IPOPHL',
      'https://www.linkedin.com/company/intellectual-property-office-of-the-philippines/',
      'https://epayment.ipophil.gov.ph/',
    ),
  ),
  SG: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Singapore (IPOS) — copyright',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
  ),
  TH: roster(
    ip(
      'copyright',
      'Department of Intellectual Property (DIP) — copyright',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
    ip(
      'trademarks',
      'Department of Intellectual Property (DIP)',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
    ip(
      'patents',
      'Department of Intellectual Property (DIP)',
      'https://www.ipthailand.go.th',
      'dip@ipthailand.go.th',
      '',
      '',
      'https://www.ipthailand.go.th/en/e-service.html',
    ),
  ),
  VN: roster(
    ip(
      'copyright',
      'Copyright Office of Vietnam (COV)',
      'https://cov.gov.vn',
      '',
      '',
      '',
      'https://cov.gov.vn',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Vietnam (NOIP)',
      'https://www.noip.gov.vn',
      'noip@noip.gov.vn',
      '',
      '',
      'https://www.noip.gov.vn/en-US/OnlineFiling',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Vietnam (NOIP)',
      'https://www.noip.gov.vn',
      'noip@noip.gov.vn',
      '',
      '',
      'https://www.noip.gov.vn/en-US/OnlineFiling',
    ),
  ),
}
