import type { RcepMemberIsoCode } from './rcepMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per RCEP party (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const RCEP_MAIN_INTERNATIONAL_SEAPORTS: Record<RcepMemberIsoCode, MainInternationalSeaport> = {
  AU: seaport(
    'Port of Melbourne',
    'https://www.portofmelbourne.com/',
    'info@portofmelbourne.com',
    'https://x.com/PortOfMelbourne',
    'https://www.instagram.com/portofmelbourne/',
    'https://www.linkedin.com/company/port-of-melbourne/',
    'customs@abf.gov.au',
    'https://www.abf.gov.au',
    'Australian Border Force — Port of Melbourne, Melbourne, Australia',
  ),
  BN: seaport(
    'Muara Port',
    'https://www.mtc.com.bn/',
    'info@mtc.com.bn',
    'https://x.com/MuaraPort',
    'https://www.instagram.com/muaraport/',
    'https://www.linkedin.com/company/muara-port/',
    'customs@rcs.gov.bn',
    'https://www.rcs.gov.bn',
    'Royal Customs and Excise Department — Muara Port, Muara, Brunei',
  ),
  KH: seaport(
    'Sihanoukville Autonomous Port',
    'https://www.pas.gov.kh/',
    'info@pas.gov.kh',
    'https://x.com/SihanoukvillePort',
    'https://www.instagram.com/sihanoukvilleport/',
    'https://www.linkedin.com/company/sihanoukville-autonomous-port/',
    'info@customs.gov.kh',
    'https://www.customs.gov.kh',
    'General Department of Customs and Excise — Sihanoukville Port, Sihanoukville, Cambodia',
  ),
  CN: seaport(
    'Port of Shanghai',
    'https://www.portshanghai.com.cn/',
    'info@portshanghai.com.cn',
    'https://x.com/PortShanghai',
    'https://www.instagram.com/portshanghai/',
    'https://www.linkedin.com/company/shanghai-international-port-group/',
    'customs@customs.gov.cn',
    'https://www.customs.gov.cn',
    'General Administration of Customs — Port of Shanghai, Shanghai, China',
  ),
  ID: seaport(
    'Port of Tanjung Priok (Jakarta)',
    'https://www.pelindo.co.id/',
    'info@pelindo.co.id',
    'https://x.com/Pelindo',
    'https://www.instagram.com/pelindo/',
    'https://www.linkedin.com/company/pelindo/',
    'contact.center@beacukai.go.id',
    'https://www.beacukai.go.id',
    'Direktorat Jenderal Bea dan Cukai — Pelabuhan Tanjung Priok, Jakarta, Indonesia',
  ),
  JP: seaport(
    'Port of Yokohama',
    'https://www.portof_yokohama.jp/',
    'info@portof_yokohama.jp',
    'https://x.com/PortOfYokohama',
    'https://www.instagram.com/portofyokohama/',
    'https://www.linkedin.com/company/port-and-harbor-bureau-city-of-yokohama/',
    'zeimu@customs.go.jp',
    'https://www.customs.go.jp',
    'Yokohama Customs — Port of Yokohama, Yokohama, Japan',
  ),
  KR: seaport(
    'Port of Busan',
    'https://www.busanpa.com/',
    'info@busanpa.com',
    'https://x.com/BusanPort',
    'https://www.instagram.com/busanport/',
    'https://www.linkedin.com/company/busan-port-authority/',
    'customs@customs.go.kr',
    'https://www.customs.go.kr',
    'Korea Customs Service — Port of Busan, Busan, South Korea',
  ),
  LA: seaport(
    'Port of Laem Chabang (primary maritime gateway; landlocked)',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'customs@customs.gov.la',
    'https://www.customs.gov.la',
    'Department of Customs — Vientiane, Laos',
  ),
  MY: seaport(
    'Port Klang',
    'https://www.pka.gov.my/',
    'info@pka.gov.my',
    'https://x.com/PortKlang',
    'https://www.instagram.com/portklang/',
    'https://www.linkedin.com/company/port-klang-authority/',
    'customs@customs.gov.my',
    'https://www.customs.gov.my',
    'Royal Malaysian Customs — Port Klang, Selangor, Malaysia',
  ),
  MM: seaport(
    'Thilawa Port (Yangon)',
    'https://www.mip.com.mm/',
    'info@mip.com.mm',
    'https://x.com/ThilawaPort',
    'https://www.instagram.com/thilawaport/',
    'https://www.linkedin.com/company/thilawa-port/',
    'info@customs.gov.mm',
    'https://www.customs.gov.mm',
    'Myanmar Customs Department — Thilawa Port, Yangon, Myanmar',
  ),
  NZ: seaport(
    'Port of Tauranga',
    'https://www.port-tauranga.co.nz/',
    'info@port-tauranga.co.nz',
    'https://x.com/PortofTauranga',
    'https://www.instagram.com/portoftauranga/',
    'https://www.linkedin.com/company/port-of-tauranga/',
    'customs@customs.govt.nz',
    'https://www.customs.govt.nz',
    'New Zealand Customs Service — Port of Tauranga, Tauranga, New Zealand',
  ),
  PH: seaport(
    'Port of Manila (South Harbor)',
    'https://www.ppa.com.ph/',
    'info@ppa.com.ph',
    'https://x.com/PPA_Official',
    'https://www.instagram.com/ppa_official/',
    'https://www.linkedin.com/company/philippine-ports-authority/',
    'customs@customs.gov.ph',
    'https://www.customs.gov.ph',
    'Bureau of Customs — Port of Manila, Manila, Philippines',
  ),
  SG: seaport(
    'Port of Singapore',
    'https://www.mpa.gov.sg/',
    'MPA_Enquiry@mpa.gov.sg',
    'https://x.com/Mpa_Singapore',
    'https://www.instagram.com/mpa_singapore/',
    'https://www.linkedin.com/company/maritime-and-port-authority-of-singapore/',
    'customs_support@customs.gov.sg',
    'https://www.customs.gov.sg',
    'Singapore Customs — PSA Singapore Terminals, Singapore',
  ),
  TH: seaport(
    'Port of Laem Chabang',
    'https://www.port.co.th/',
    'info@port.co.th',
    'https://x.com/PortAuthorityTH',
    'https://www.instagram.com/portauthorityth/',
    'https://www.linkedin.com/company/port-authority-of-thailand/',
    'info@customs.go.th',
    'https://www.customs.go.th',
    'Thai Customs — Laem Chabang Port, Chonburi, Thailand',
  ),
  VN: seaport(
    'Port of Ho Chi Minh City (Cát Lái)',
    'https://www.saigonnewport.com.vn/',
    'info@saigonnewport.com.vn',
    'https://x.com/SaigonNewport',
    'https://www.instagram.com/saigonnewport/',
    'https://www.linkedin.com/company/saigon-newport-corporation/',
    'contact@customs.gov.vn',
    'https://www.customs.gov.vn',
    'General Department of Vietnam Customs — Cát Lái Port, Ho Chi Minh City, Vietnam',
  ),
}
