import type { RcepMemberIsoCode } from './rcepMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const RCEP_MAIN_EXPORT_COMMODITIES: Record<RcepMemberIsoCode, MainExportCommodities> = {
  AU: m(
    'Iron ore',
    'Coal',
    'Natural gas',
    'Gold',
    'Wheat',
    'Beef',
    'Education services',
  ),
  BN: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Methanol',
    'Chemicals',
    'Garments',
    'Fish',
  ),
  KH: m(
    'Garments',
    'Footwear',
    'Knitwear',
    'Bicycles',
    'Travel goods',
    'Rice',
    'Rubber',
  ),
  CN: m(
    'Computers',
    'Telecommunications equipment',
    'Integrated circuits',
    'Office machine parts',
    'Cars',
    'Furniture',
    'Footwear',
  ),
  ID: m(
    'Coal',
    'Palm oil',
    'Iron and steel',
    'Natural gas',
    'Crude petroleum',
    'Footwear',
    'Vehicles',
  ),
  JP: m(
    'Automobiles',
    'Machinery',
    'Electrical machinery',
    'Iron and steel',
    'Plastics',
    'Optical instruments',
    'Ships',
  ),
  KR: m(
    'Semiconductors',
    'Automobiles',
    'Refined petroleum',
    'Ships',
    'Telecommunications equipment',
    'Plastics',
    'Iron and steel',
  ),
  LA: m(
    'Copper',
    'Electricity',
    'Wood products',
    'Coffee',
    'Iron and steel',
    'Garments',
    'Gold',
  ),
  MY: m(
    'Integrated circuits',
    'Refined petroleum',
    'Palm oil',
    'Petroleum gas',
    'Crude petroleum',
    'Computers',
    'Rubber',
  ),
  MM: m(
    'Natural gas',
    'Garments',
    'Rice',
    'Beans',
    'Jade',
    'Wood',
    'Fish',
  ),
  NZ: m(
    'Dairy products',
    'Meat',
    'Wood',
    'Fruit',
    'Wine',
    'Aluminium',
    'Fish',
  ),
  PH: m(
    'Integrated circuits',
    'Office machine parts',
    'Computers',
    'Insulated wire',
    'Refined petroleum',
    'Coconut oil',
    'Bananas',
  ),
  SG: m(
    'Integrated circuits',
    'Refined petroleum',
    'Gold',
    'Computers',
    'Packaged medicaments',
    'Machinery',
    'Gas turbines',
  ),
  TH: m(
    'Computers',
    'Automobiles',
    'Integrated circuits',
    'Refined petroleum',
    'Rubber',
    'Rice',
    'Gold',
  ),
  VN: m(
    'Telephones',
    'Computers',
    'Integrated circuits',
    'Garments',
    'Footwear',
    'Furniture',
    'Coffee',
  ),
}
