import type { NationalBankingInstitution } from './types'
import type { RcepMemberIsoCode } from './rcepMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per RCEP party economy.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const RCEP_NATIONAL_BANKING_INSTITUTIONS: Record<
  RcepMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AU: [
    bank(
      'Commonwealth Bank of Australia',
      '+61 13 2221',
      'Ground Floor, Tower 1, 201 Sussex Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/commbank/id310251020',
      'https://play.google.com/store/apps/details?id=com.commbank.netbank',
      'https://www.commbank.com.au',
      'customercare@cba.com.au',
      'https://twitter.com/CommBank',
      'https://www.instagram.com/commbank/',
      'https://www.linkedin.com/company/commonwealth-bank/',
      '',
      'CTBAAU2S',
      'https://api.commbank.com.au',
    ),
    bank(
      'Westpac Banking Corporation',
      '+61 13 2032',
      '275 Kent Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/westpac-mobile-banking/id284826145',
      'https://play.google.com/store/apps/details?id=org.westpac.bank',
      'https://www.westpac.com.au',
      'customercare@westpac.com.au',
      'https://twitter.com/Westpac',
      'https://www.instagram.com/westpac/',
      'https://www.linkedin.com/company/westpac/',
      '',
      'WPACAU2S',
      'https://developer.westpac.com.au',
    ),
    bank(
      'Australia and New Zealand Banking Group',
      '+61 13 13 14',
      '833 Collins Street, Docklands, VIC, Australia',
      'https://apps.apple.com/au/app/anz-australia/id385348415',
      'https://play.google.com/store/apps/details?id=com.anz.android',
      'https://www.anz.com.au',
      'contactus@anz.com',
      'https://twitter.com/ANZ_AU',
      'https://www.instagram.com/anz_au/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBAU3M',
      'https://developer.anz.com',
    ),
  ],
  BN: [
    bank(
      'Baiduri Bank',
      '+673 2449666',
      'Baiduri Community Space, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/baiduri-b-token/id1414199588',
      'https://play.google.com/store/apps/details?id=com.baiduri.mobilebanking',
      'https://www.baiduri.com.bn',
      'info@baiduri.com.bn',
      'https://twitter.com/baiduribank',
      'https://www.instagram.com/baiduribank/',
      'https://www.linkedin.com/company/baiduri-bank/',
      '',
      'BAIDBNDX',
      '',
    ),
    bank(
      'Bank Islam Brunei Darussalam',
      '+673 2238181',
      'Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/bibd-nexgen-wallet/id1541812683',
      'https://play.google.com/store/apps/details?id=com.bibd.nexgen',
      'https://www.bibd.com.bn',
      'enquiry@bibd.com.bn',
      'https://twitter.com/BIBDBrunei',
      'https://www.instagram.com/bibdbrunei/',
      'https://www.linkedin.com/company/bibd/',
      '',
      'BIBDBNBB',
      '',
    ),
    bank(
      'Standard Chartered Brunei',
      '+673 2658000',
      'Jalan Sultan, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/sg/app/sc-mobile-singapore/id445120671',
      'https://play.google.com/store/apps/details?id=com.sc.breezenxt.bn',
      'https://www.sc.com/bn',
      'clientcare.bnd@sc.com',
      'https://twitter.com/StanChart',
      'https://www.instagram.com/stanchart/',
      'https://www.linkedin.com/company/standard-chartered-bank/',
      '',
      'SCBLBNDX',
      '',
    ),
  ],
  KH: [
    bank(
      'ACLEDA Bank',
      '+855 23 994 444',
      '61 Preah Monivong Blvd, Phnom Penh, Cambodia',
      'https://apps.apple.com/kh/app/acleda-unity/id1506321092',
      'https://play.google.com/store/apps/details?id=com.acledabank.unity',
      'https://www.acledabank.com.kh',
      'acledabank@acledabank.com.kh',
      'https://twitter.com/acledabank',
      'https://www.instagram.com/acledabankplc/',
      'https://www.linkedin.com/company/acleda-bank/',
      '',
      'ACLBKHPP',
      '',
    ),
    bank(
      'Canadia Bank',
      '+855 23 868 222',
      '315 Ang Duong Street, Phnom Penh, Cambodia',
      'https://apps.apple.com/kh/app/canadia-bank-app/id1484956757',
      'https://play.google.com/store/apps/details?id=com.canadia.mobilebanking',
      'https://www.canadiabank.com.kh',
      'info@canadiabank.com.kh',
      'https://twitter.com/CanadiaBank',
      'https://www.instagram.com/canadiabank/',
      'https://www.linkedin.com/company/canadia-bank-plc/',
      '',
      'CADIKHPP',
      '',
    ),
    bank(
      'ABA Bank Cambodia',
      '+855 23 225 333',
      '141 Preah Sihanouk Blvd, Phnom Penh, Cambodia',
      'https://apps.apple.com/kh/app/aba-mobile/id968860129',
      'https://play.google.com/store/apps/details?id=com.paygo24.ibank',
      'https://www.ababank.com',
      'info@ababank.com',
      'https://twitter.com/ABA_Bank',
      'https://www.instagram.com/aba_bank/',
      'https://www.linkedin.com/company/aba-bank/',
      '',
      'ABAAKHPP',
      '',
    ),
  ],
  CN: [
    bank(
      'Industrial and Commercial Bank of China',
      '+86 10 6610 8610',
      '55 Fuxingmennei Avenue, Beijing, China',
      'https://apps.apple.com/cn/app/icbc/id363280271',
      'https://play.google.com/store/apps/details?id=com.icbc',
      'https://www.icbc.com.cn',
      'info@icbc.com.cn',
      '',
      '',
      'https://www.linkedin.com/company/icbc/',
      '',
      'ICBKCNBJ',
      '',
    ),
    bank(
      'Bank of China',
      '+86 10 6659 6688',
      '1 Fuxingmen Nei Dajie, Beijing, China',
      'https://apps.apple.com/cn/app/bank-of-china/id463862286',
      'https://play.google.com/store/apps/details?id=com.boc.bocsoft.mobilebanking',
      'https://www.boc.cn',
      'ir@bankofchina.com',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-china/',
      '',
      'BKCHCNBJ',
      '',
    ),
    bank(
      'China Construction Bank',
      '+86 10 6621 5566',
      '25 Finance Street, Xicheng District, Beijing, China',
      'https://apps.apple.com/cn/app/china-construction-bank/id391710657',
      'https://play.google.com/store/apps/details?id=com.ccb.mobile',
      'https://www.ccb.com',
      'ccbcc.zh@ccb.com',
      '',
      '',
      'https://www.linkedin.com/company/china-construction-bank/',
      '',
      'PCBCCNBJ',
      '',
    ),
  ],
  ID: [
    bank(
      'Bank Mandiri',
      '+62 21 5299 7777',
      'Plaza Mandiri, Jl. Jend. Gatot Subroto, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/livin-by-mandiri/id1555417419',
      'https://play.google.com/store/apps/details?id=id.bmri.livin',
      'https://www.bankmandiri.co.id',
      'mandiricare@bankmandiri.co.id',
      'https://twitter.com/bankmandiri',
      'https://www.instagram.com/bankmandiri/',
      'https://www.linkedin.com/company/bankmandiri/',
      '',
      'BMRIIDJA',
      '',
    ),
    bank(
      'Bank Central Asia',
      '+62 21 2358 8000',
      'Menara BCA, Grand Indonesia, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/mybca/id1465918716',
      'https://play.google.com/store/apps/details?id=com.bca.mybca.omni.android',
      'https://www.bca.co.id',
      'halobca@bca.co.id',
      'https://twitter.com/BankBCA',
      'https://www.instagram.com/goodlifebca/',
      'https://www.linkedin.com/company/pt-bank-central-asia-tbk/',
      '',
      'CENAIDJA',
      '',
    ),
    bank(
      'Bank Negara Indonesia',
      '+62 21 5728387',
      'Jl. Jend. Sudirman Kav. 1, Jakarta, Indonesia',
      'https://apps.apple.com/id/app/wondr-by-bni/id6474669196',
      'https://play.google.com/store/apps/details?id=id.co.bni.newagenbni46',
      'https://www.bni.co.id',
      'bnicall@bni.co.id',
      'https://twitter.com/BNI',
      'https://www.instagram.com/bni46/',
      'https://www.linkedin.com/company/pt-bank-negara-indonesia-persero-tbk/',
      '',
      'BNINIDJA',
      '',
    ),
  ],
  JP: [
    bank(
      'MUFG Bank',
      '+81 3 3240 1111',
      '2-7-1 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mufg/id1249041409',
      'https://play.google.com/store/apps/details?id=jp.co.bk.mufg.bkapp',
      'https://www.bk.mufg.jp',
      'info@bk.mufg.jp',
      'https://twitter.com/MUFG',
      '',
      'https://www.linkedin.com/company/mufg/',
      '',
      'BOTKJPJT',
      '',
    ),
    bank(
      'Sumitomo Mitsui Banking Corporation',
      '+81 3 3282 8111',
      '1-1-2 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/smbc/id398950681',
      'https://play.google.com/store/apps/details?id=jp.co.smbc.banking',
      'https://www.smbc.co.jp',
      'koho@smbc.co.jp',
      'https://twitter.com/SMBCGroup',
      '',
      'https://www.linkedin.com/company/smbc-group/',
      '',
      'SMBCJPJT',
      '',
    ),
    bank(
      'Mizuho Bank',
      '+81 3 3214 1111',
      '1-5-5 Otemachi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mizuho-direct/id1535103293',
      'https://play.google.com/store/apps/details?id=jp.co.mizuhobank.direct',
      'https://www.mizuhobank.co.jp',
      'info@mizuho-fg.co.jp',
      'https://twitter.com/MizuhoGroup',
      '',
      'https://www.linkedin.com/company/mizuho/',
      '',
      'MHCBJPJT',
      '',
    ),
  ],
  KR: [
    bank(
      'KB Kookmin Bank',
      '+82 2 2073 7114',
      '26 Gukjegeumyung-ro 8-gil, Yeongdeungpo-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/kb-star-banking/id373742138',
      'https://play.google.com/store/apps/details?id=com.kbstar.kbbank',
      'https://www.kbstar.com',
      'kbkookminbank@kbfg.com',
      'https://twitter.com/KBFinancialGroup',
      '',
      'https://www.linkedin.com/company/kb-financial-group/',
      '',
      'CZNBKRSE',
      '',
    ),
    bank(
      'Shinhan Bank',
      '+82 2 756 0505',
      '20 Sejong-daero 9-gil, Jung-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/shinhan-sol-global/id1363654579',
      'https://play.google.com/store/apps/details?id=com.shinhan.globalbank',
      'https://www.shinhan.com',
      'global@shinhan.com',
      'https://twitter.com/ShinhanBank',
      '',
      'https://www.linkedin.com/company/shinhan-bank/',
      '',
      'SHBKKRSE',
      '',
    ),
    bank(
      'Woori Bank',
      '+82 2 2002 3000',
      '51 Sogong-ro, Jung-gu, Seoul, South Korea',
      'https://apps.apple.com/kr/app/woori-won-banking/id1430145879',
      'https://play.google.com/store/apps/details?id=com.wooribank.smart.npib',
      'https://www.wooribank.com',
      'wbmaster@wooribank.com',
      'https://twitter.com/WooriBank',
      '',
      'https://www.linkedin.com/company/woori-bank/',
      '',
      'HVBKKRSE',
      '',
    ),
  ],
  LA: [
    bank(
      'Banque Pour Le Commerce Exterieur Lao',
      '+856 21 213200',
      'Pangkham Road, Vientiane, Laos',
      'https://apps.apple.com/la/app/bcel-one/id1224683707',
      'https://play.google.com/store/apps/details?id=com.bcel.one',
      'https://www.bcel.com.la',
      'callcenter@bcel.com.la',
      '',
      '',
      'https://www.linkedin.com/company/bcel/',
      '',
      'BCELLALA',
      '',
    ),
    bank(
      'Lao-Viet Bank',
      '+856 21 254444',
      'Lane Xang Avenue, Vientiane, Laos',
      '',
      '',
      'https://www.laovietbank.com.la',
      'info@laovietbank.com.la',
      '',
      '',
      '',
      '',
      'LVBKLALA',
      '',
    ),
    bank(
      'Banque Franco-Lao',
      '+856 21 260980',
      'Setthathirath Road, Vientiane, Laos',
      '',
      '',
      'https://www.bfl-banque.com',
      'info@bfl-banque.com',
      '',
      '',
      'https://www.linkedin.com/company/banque-franco-lao/',
      '',
      'BFLLLALA',
      '',
    ),
  ],
  MY: [
    bank(
      'Maybank',
      '+60 3 2070 8833',
      'Menara Maybank, 100 Jalan Tun Perak, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/mae-by-maybank2u/id1455827893',
      'https://play.google.com/store/apps/details?id=com.maybank2u.life',
      'https://www.maybank2u.com.my',
      'mgcc@maybank.com.my',
      'https://twitter.com/MyMaybank',
      'https://www.instagram.com/maybank/',
      'https://www.linkedin.com/company/maybank/',
      '',
      'MBBEMYKL',
      '',
    ),
    bank(
      'CIMB Bank',
      '+60 3 6204 7788',
      'Menara CIMB, Jalan Stesen Sentral 2, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/cimb-octo-my/id1533904065',
      'https://play.google.com/store/apps/details?id=com.cimbmalaysia',
      'https://www.cimb.com.my',
      'contactus@cimb.com',
      'https://twitter.com/CIMBMalaysia',
      'https://www.instagram.com/cimbmalaysia/',
      'https://www.linkedin.com/company/cimb/',
      '',
      'CIBBMYKL',
      '',
    ),
    bank(
      'Public Bank',
      '+60 3 2176 8000',
      'Menara Public Bank, Jalan Raja Chulan, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/pbe/id1181169389',
      'https://play.google.com/store/apps/details?id=com.publicbank.pbeng',
      'https://www.pbebank.com',
      'customersupport@publicbank.com.my',
      'https://twitter.com/PublicBankGroup',
      '',
      'https://www.linkedin.com/company/public-bank-berhad/',
      '',
      'PBBEMYKL',
      '',
    ),
  ],
  MM: [
    bank(
      'KBZ Bank',
      '+95 1 9510185',
      'Shwe Gon Daing Road, Yangon, Myanmar',
      'https://apps.apple.com/mm/app/kbzpay/id1343731363',
      'https://play.google.com/store/apps/details?id=com.kbzbank.kpaycustomer',
      'https://www.kbzbank.com',
      'customer.service@kbzbank.com',
      'https://twitter.com/KBZBank',
      'https://www.instagram.com/kbzbank/',
      'https://www.linkedin.com/company/kbz-bank/',
      '',
      'KBZBMMMY',
      '',
    ),
    bank(
      'CB Bank',
      '+95 1 2317770',
      'Corner of Maha Bandoola Road and 22nd Street, Yangon, Myanmar',
      'https://apps.apple.com/mm/app/cb-pay/id1456728501',
      'https://play.google.com/store/apps/details?id=com.cbbank.mobilebanking',
      'https://www.cbbank.com.mm',
      'contact@cbbank.com.mm',
      'https://twitter.com/cbbankmm',
      'https://www.instagram.com/cbbankmm/',
      'https://www.linkedin.com/company/cb-bank-pcl/',
      '',
      'CBRBMMMY',
      '',
    ),
    bank(
      'AYA Bank',
      '+95 1 2317777',
      'No. 416, Mahabandoola Road, Kyauktada Township, Yangon, Myanmar',
      'https://apps.apple.com/mm/app/aya-mobile-banking-2-0/id1439798691',
      'https://play.google.com/store/apps/details?id=com.ayabank.mbanking',
      'https://www.ayabank.com',
      'info@ayabank.com',
      'https://twitter.com/ayabank',
      'https://www.instagram.com/ayabank/',
      'https://www.linkedin.com/company/aya-bank/',
      '',
      'AYABMMMY',
      '',
    ),
  ],
  NZ: [
    bank(
      'ANZ New Zealand',
      '+64 9 252 6777',
      '23 Albert Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/anz-go-money-nz/id486726860',
      'https://play.google.com/store/apps/details?id=nz.co.anz.android.mobilebanking',
      'https://www.anz.co.nz',
      'info@anz.co.nz',
      'https://twitter.com/ANZ_NZ',
      'https://www.instagram.com/anz_nz/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBNZ22',
      '',
    ),
    bank(
      'ASB Bank',
      '+64 9 306 3000',
      '12 Jellicoe Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/asb-mobile-banking/id384056323',
      'https://play.google.com/store/apps/details?id=nz.co.asb.asbmobile',
      'https://www.asb.co.nz',
      'info@asb.co.nz',
      'https://twitter.com/ASBBank',
      'https://www.instagram.com/asbbank/',
      'https://www.linkedin.com/company/asb-bank/',
      '',
      'ASBBNZ2A',
      '',
    ),
    bank(
      'Bank of New Zealand',
      '+64 9 924 9000',
      '80 Queen Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/bnz-mobile/id413489435',
      'https://play.google.com/store/apps/details?id=nz.co.bnz.droidbanking',
      'https://www.bnz.co.nz',
      'bnz_reception@bnz.co.nz',
      'https://twitter.com/bnz',
      'https://www.instagram.com/bankofnz/',
      'https://www.linkedin.com/company/bank-of-new-zealand/',
      '',
      'BKNZNZ22',
      '',
    ),
  ],
  PH: [
    bank(
      'BDO Unibank',
      '+63 2 8631 8000',
      'BDO Corporate Center, Makati Avenue, Makati, Philippines',
      'https://apps.apple.com/ph/app/bdo-online/id1558548418',
      'https://play.google.com/store/apps/details?id=com.bdo.online',
      'https://www.bdo.com.ph',
      'customercare@bdo.com.ph',
      'https://twitter.com/BDOUnibank',
      'https://www.instagram.com/bdounibank/',
      'https://www.linkedin.com/company/bdo-unibank/',
      '',
      'BNORPHMM',
      '',
    ),
    bank(
      'Bank of the Philippine Islands',
      '+63 2 8891 0000',
      'Ayala North Exchange Tower, Makati, Philippines',
      'https://apps.apple.com/ph/app/bpi-mobile/id1131500055',
      'https://play.google.com/store/apps/details?id=ph.com.bpi.mobile',
      'https://www.bpi.com.ph',
      'help@bpi.com.ph',
      'https://twitter.com/TalktoBPI',
      'https://www.instagram.com/bpi/',
      'https://www.linkedin.com/company/bank-of-the-philippine-islands/',
      '',
      'BOPIPHMM',
      '',
    ),
    bank(
      'Metrobank',
      '+63 2 8870 0700',
      'Metrobank Plaza, Makati Avenue, Makati, Philippines',
      'https://apps.apple.com/ph/app/metrobank-online/id407362868',
      'https://play.google.com/store/apps/details?id=ph.com.metrobank.mcc',
      'https://www.metrobank.com.ph',
      'customercare@metrobank.com.ph',
      'https://twitter.com/Metrobank',
      'https://www.instagram.com/metrobank/',
      'https://www.linkedin.com/company/metrobank/',
      '',
      'MBTCPHMM',
      '',
    ),
  ],
  SG: [
    bank(
      'DBS Bank',
      '+65 6878 8888',
      '12 Marina Boulevard, Marina Bay Financial Centre, Singapore',
      'https://apps.apple.com/sg/app/dbs-digibank/id1068403820',
      'https://play.google.com/store/apps/details?id=com.dbs.sg.dbsmbanking',
      'https://www.dbs.com.sg',
      'contactus@dbs.com',
      'https://twitter.com/dbsbank',
      'https://www.instagram.com/dbsbank/',
      'https://www.linkedin.com/company/dbs-bank/',
      '',
      'DBSSSGSG',
      '',
    ),
    bank(
      'OCBC Bank',
      '+65 6363 3333',
      '65 Chulia Street, OCBC Centre, Singapore',
      'https://apps.apple.com/sg/app/ocbc-digital/id292506828',
      'https://play.google.com/store/apps/details?id=com.ocbc.mobile',
      'https://www.ocbc.com',
      'contactus@ocbc.com',
      'https://twitter.com/OCBCBank',
      'https://www.instagram.com/ocbc/',
      'https://www.linkedin.com/company/ocbc-bank/',
      '',
      'OCBCSGSG',
      '',
    ),
    bank(
      'UOB',
      '+65 6222 2121',
      '80 Raffles Place, UOB Plaza, Singapore',
      'https://apps.apple.com/sg/app/uob-tmrw/id1314626819',
      'https://play.google.com/store/apps/details?id=com.uob.might',
      'https://www.uob.com.sg',
      'uobcustomerservice@uobgroup.com',
      'https://twitter.com/UOBGroup',
      'https://www.instagram.com/uobgroup/',
      'https://www.linkedin.com/company/uob/',
      '',
      'UOVBSGSG',
      '',
    ),
  ],
  TH: [
    bank(
      'Bangkok Bank',
      '+66 2 230 1323',
      '333 Silom Road, Bang Rak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/bualuang-mbanking/id660355106',
      'https://play.google.com/store/apps/details?id=com.bbl.mobilebanking',
      'https://www.bangkokbank.com',
      'customercare@bangkokbank.com',
      'https://twitter.com/bangkokbank',
      'https://www.instagram.com/bangkokbank/',
      'https://www.linkedin.com/company/bangkok-bank/',
      '',
      'BKKBTHBK',
      '',
    ),
    bank(
      'Kasikornbank',
      '+66 2 888 8888',
      '1 Soi Rat Burana 27/1, Rat Burana, Bangkok, Thailand',
      'https://apps.apple.com/th/app/k-plus/id361170631',
      'https://play.google.com/store/apps/details?id=com.kasikorn.retail.mbanking.wap',
      'https://www.kasikornbank.com',
      'kcontactcenter@kasikornbank.com',
      'https://twitter.com/KBank_Live',
      'https://www.instagram.com/kbanklive/',
      'https://www.linkedin.com/company/kasikornbank/',
      '',
      'KASITHBK',
      '',
    ),
    bank(
      'Siam Commercial Bank',
      '+66 2 777 7777',
      '9 Ratchadaphisek Road, Chatuchak, Bangkok, Thailand',
      'https://apps.apple.com/th/app/scb-easy/id568388474',
      'https://play.google.com/store/apps/details?id=com.scb.phone',
      'https://www.scb.co.th',
      'customercare@scb.co.th',
      'https://twitter.com/scb_thailand',
      'https://www.instagram.com/scb_thailand/',
      'https://www.linkedin.com/company/the-siam-commercial-bank-public-company-limited/',
      '',
      'SICOTHBK',
      '',
    ),
  ],
  VN: [
    bank(
      'Vietcombank',
      '+84 24 3934 3137',
      '198 Tran Quang Khai, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vcb-digibank/id561433131',
      'https://play.google.com/store/apps/details?id=com.vietcombank.vcbmobile',
      'https://www.vietcombank.com.vn',
      'vcb@vietcombank.com.vn',
      'https://twitter.com/Vietcombank',
      'https://www.instagram.com/vietcombank/',
      'https://www.linkedin.com/company/vietcombank/',
      '',
      'BFTVVNVX',
      '',
    ),
    bank(
      'BIDV',
      '+84 24 2220 5544',
      '35 Hang Voi, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/bidv-smartbanking/id1283524786',
      'https://play.google.com/store/apps/details?id=com.vnpay.bidv',
      'https://www.bidv.com.vn',
      'bidv247@bidv.com.vn',
      'https://twitter.com/BIDV',
      '',
      'https://www.linkedin.com/company/bidv/',
      '',
      'BIDVVNVX',
      '',
    ),
    bank(
      'VietinBank',
      '+84 24 3941 8868',
      '108 Tran Hung Dao, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vietinbank-ipay-mobile/id542298015',
      'https://play.google.com/store/apps/details?id=com.vietinbank.ipay',
      'https://www.vietinbank.vn',
      'contact@vietinbank.vn',
      'https://twitter.com/VietinBank',
      '',
      'https://www.linkedin.com/company/vietinbank/',
      '',
      'ICBVVNVX',
      '',
    ),
  ],
}
