/**
 * Proof of Stake Index - Cryptocurrencies using Proof of Stake consensus
 * 
 * This list contains cryptocurrencies that utilize Proof of Stake (PoS) or
 * similar consensus mechanisms. These currencies are organized by their
 * staking capabilities and validator networks.
 * 
 * This index is used for staking operations, validator selection, and
 * PoS-related features throughout the application.
 * 
 * Last Updated: December 2025
 */

export type CurrencyType = 'coin' | 'token';
export type ConsensusType = 'proof-of-stake' | 'proof-of-work' | 'proof-of-authority' | 'delegated-proof-of-stake' | 'nominated-proof-of-stake' | 'liquid-proof-of-stake' | 'byzantine-fault-tolerance' | 'proof-of-transfer' | 'proof-of-coverage' | 'token' | 'hybrid' | 'optimistic-rollup';
export type CurrencyClass = 'layer-1' | 'layer-2' | 'defi' | 'dex' | 'nft' | 'gaming' | 'metaverse' | 'oracle' | 'privacy' | 'meme' | 'staking' | 'governance' | 'lending' | 'data' | 'infrastructure' | 'smart-contract-platform' | 'exchange-token' | 'ai' | 'storage' | 'payment' | 'social' | 'interoperability' | 'sports' | 'iot';

export interface ProofOfStakeItem {
  id: string;
  symbol: string;
  name: string;
  description: string;
  ucid: number;
  type: CurrencyType;
  consensusType: ConsensusType;
  class: CurrencyClass[];
  website: string | null;
  github: string | null;
  npm: string | null;
}

export const PROOF_OF_STAKE: ProofOfStakeItem[] = [
  { 
    id: 'cardano', 
    symbol: 'ADA', 
    name: 'Cardano',
    description: 'A proof-of-stake blockchain platform focused on sustainability, scalability, and transparent governance for decentralized applications.',
    ucid: 2010,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://cardano.org',
    github: 'https://github.com/input-output-hk/cardano-node',
    npm: 'https://www.npmjs.com/package/cardano-serialization-lib'
  },
  { 
    id: 'algorand', 
    symbol: 'ALGO', 
    name: 'Algorand',
    description: 'A pure proof-of-stake blockchain platform designed for speed, security, and decentralization with instant finality.',
    ucid: 4030,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://algorand.com',
    github: 'https://github.com/algorand',
    npm: 'https://www.npmjs.com/package/algosdk'
  },
  { 
    id: 'aptos', 
    symbol: 'APT', 
    name: 'Aptos',
    description: 'A layer-1 blockchain built with the Move programming language, focusing on safety, scalability, and upgradeability.',
    ucid: 21794,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://aptoslabs.com',
    github: 'https://github.com/aptos-labs',
    npm: 'https://www.npmjs.com/package/aptos'
  },
  { 
    id: 'cosmos', 
    symbol: 'ATOM', 
    name: 'Cosmos',
    description: 'An ecosystem of interconnected blockchains designed to solve scalability and interoperability issues.',
    ucid: 3794,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'interoperability'],
    website: 'https://cosmos.network',
    github: 'https://github.com/cosmos',
    npm: 'https://www.npmjs.com/package/@cosmjs/stargate'
  },
  { 
    id: 'avalanche-2', 
    symbol: 'AVAX', 
    name: 'Avalanche',
    description: 'A high-performance blockchain platform for decentralized applications and custom blockchain networks.',
    ucid: 5805,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://www.avax.network',
    github: 'https://github.com/ava-labs',
    npm: 'https://www.npmjs.com/package/avalanche'
  },
  { 
    id: 'beldex', 
    symbol: 'BDX', 
    name: 'Beldex',
    description: 'A privacy-focused blockchain providing secure transactions and decentralized applications.',
    ucid: 3896,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'privacy'],
    website: 'https://beldex.io',
    github: 'https://github.com/Beldex-Coin',
    npm: null
  },
  { 
    id: 'binancecoin', 
    symbol: 'BNB', 
    name: 'Binance',
    description: 'The native cryptocurrency of BNB Chain (formerly Binance Smart Chain), used for transaction fees and DeFi applications.',
    ucid: 1839,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'exchange-token', 'smart-contract-platform'],
    website: 'https://www.bnbchain.org',
    github: 'https://github.com/bnb-chain',
    npm: null
  },
  { 
    id: 'crypto-com-chain', 
    symbol: 'CRO', 
    name: 'Cronos',
    description: 'The native token of Cronos Chain and Crypto.com ecosystem, used for transactions and staking.',
    ucid: 3635,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'exchange-token', 'payment'],
    website: 'https://cronos.org',
    github: 'https://github.com/crypto-org-chain',
    npm: null
  },
  { 
    id: 'casper-network', 
    symbol: 'CSPR', 
    name: 'Casper Network',
    description: 'An enterprise-focused blockchain built for real-world applications with upgradeable smart contracts.',
    ucid: 7950,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://casper.network',
    github: 'https://github.com/casper-network',
    npm: 'https://www.npmjs.com/package/casper-js-sdk'
  },
  { 
    id: 'dash', 
    symbol: 'DASH', 
    name: 'Dash',
    description: 'A privacy-focused cryptocurrency featuring instant transactions and a two-tier masternode network.',
    ucid: 131,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'payment', 'privacy'],
    website: 'https://www.dash.org',
    github: 'https://github.com/dashpay',
    npm: null
  },
  { 
    id: 'decred', 
    symbol: 'DCR', 
    name: 'Decred',
    description: 'A cryptocurrency with hybrid proof-of-work/proof-of-stake consensus and on-chain governance.',
    ucid: 1168,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'governance'],
    website: 'https://decred.org',
    github: 'https://github.com/decred',
    npm: null
  },
  { 
    id: 'polkadot', 
    symbol: 'DOT', 
    name: 'Polkadot',
    description: 'A multi-chain protocol enabling diverse blockchains to transfer messages and value in a trust-free fashion.',
    ucid: 6636,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['layer-1', 'interoperability'],
    website: 'https://polkadot.network',
    github: 'https://github.com/paritytech/polkadot',
    npm: 'https://www.npmjs.com/package/@polkadot/api'
  },
  { 
    id: 'dymension', 
    symbol: 'DYM', 
    name: 'Dymension',
    description: 'A network of modular blockchains called RollApps built on the Cosmos ecosystem.',
    ucid: 28932,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'interoperability'],
    website: 'https://dymension.xyz',
    github: 'https://github.com/dymensionxyz',
    npm: null
  },
  { 
    id: 'elrond-erd-2', 
    symbol: 'EGLD', 
    name: 'MultiversX',
    description: 'A highly scalable blockchain platform (formerly Elrond) for distributed apps and enterprise use cases.',
    ucid: 6892,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://multiversx.com',
    github: 'https://github.com/multiversx',
    npm: 'https://www.npmjs.com/package/@multiversx/sdk-core'
  },
  { 
    id: 'eos', 
    symbol: 'EOS', 
    name: 'EOS',
    description: 'A blockchain platform for building decentralized applications with high transaction throughput.',
    ucid: 1765,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://eosnetwork.com',
    github: 'https://github.com/EOSIO',
    npm: 'https://www.npmjs.com/package/eosjs'
  },
  { 
    id: 'ethereum', 
    symbol: 'ETH', 
    name: 'Ethereum',
    description: 'A decentralized platform enabling smart contracts and distributed applications with its native currency Ether.',
    ucid: 1027,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ethereum.org',
    github: 'https://github.com/ethereum',
    npm: 'https://www.npmjs.com/package/ethers'
  },
  { 
    id: 'flow', 
    symbol: 'FLOW', 
    name: 'Flow',
    description: 'A blockchain built for NFTs, gaming, and digital entertainment with fast and low-cost transactions.',
    ucid: 4558,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'nft', 'gaming'],
    website: 'https://flow.com',
    github: 'https://github.com/onflow',
    npm: 'https://www.npmjs.com/package/@onflow/fcl'
  },
  { 
    id: 'fantom', 
    symbol: 'FTM', 
    name: 'Fantom',
    description: 'A fast, scalable, and secure smart contract platform using directed acyclic graph (DAG) technology.',
    ucid: 3513,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://fantom.foundation',
    github: 'https://github.com/Fantom-Foundation',
    npm: null
  },
  { 
    id: 'gnosis', 
    symbol: 'GNO', 
    name: 'Gnosis',
    description: 'A decentralized prediction market platform and Ethereum sidechain for building secure applications.',
    ucid: 1659,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'layer-2'],
    website: 'https://gnosis.io',
    github: 'https://github.com/gnosis',
    npm: 'https://www.npmjs.com/package/@gnosis.pm/safe-core-sdk'
  },
  { 
    id: 'gatechain-token', 
    symbol: 'GT', 
    name: 'Gate Token',
    description: 'The native token of Gate.io exchange and GateChain blockchain platform.',
    ucid: 4269,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['exchange-token', 'layer-1'],
    website: 'https://www.gatechain.io',
    github: 'https://github.com/gatechain',
    npm: null
  },
  { 
    id: 'provenance-blockchain', 
    symbol: 'HASH', 
    name: 'Provenance Blockchain',
    description: 'A public blockchain designed specifically for the financial services industry.',
    ucid: 9520,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://provenance.io',
    github: 'https://github.com/provenance-io',
    npm: null
  },
  { 
    id: 'hedera-hashgraph', 
    symbol: 'HBAR', 
    name: 'Hedera',
    description: 'A distributed ledger technology using hashgraph consensus for fast, fair, and secure transactions.',
    ucid: 4642,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://hedera.com',
    github: 'https://github.com/hashgraph',
    npm: 'https://www.npmjs.com/package/@hashgraph/sdk'
  },
  { 
    id: 'hyperliquid', 
    symbol: 'HYPE', 
    name: 'Hyperliquid',
    description: 'A high-performance decentralized exchange platform with deep liquidity and low latency trading.',
    ucid: 34346,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'dex'],
    website: 'https://hyperliquid.xyz',
    github: 'https://github.com/hyperliquid-dex',
    npm: null
  },
  { 
    id: 'internet-computer', 
    symbol: 'ICP', 
    name: 'Internet Computer',
    description: 'A blockchain network designed to extend the internet with decentralized computing capabilities.',
    ucid: 8916,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://internetcomputer.org',
    github: 'https://github.com/dfinity',
    npm: 'https://www.npmjs.com/package/@dfinity/agent'
  },
  { 
    id: 'immutable-x', 
    symbol: 'IMX', 
    name: 'Immutable X',
    description: 'A layer-2 scaling solution for NFTs on Ethereum with zero gas fees and instant trades.',
    ucid: 10603,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['layer-2', 'nft'],
    website: 'https://www.immutable.com',
    github: 'https://github.com/immutable',
    npm: 'https://www.npmjs.com/package/@imtbl/core-sdk'
  },
  { 
    id: 'injective-protocol', 
    symbol: 'INJ', 
    name: 'Injective',
    description: 'A decentralized exchange protocol enabling cross-chain derivatives trading with zero gas fees.',
    ucid: 7226,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'dex', 'layer-1'],
    website: 'https://injective.com',
    github: 'https://github.com/InjectiveLabs',
    npm: 'https://www.npmjs.com/package/@injectivelabs/sdk-ts'
  },
  { 
    id: 'iota', 
    symbol: 'IOTA', 
    name: 'IOTA',
    description: 'A distributed ledger for IoT devices using a directed acyclic graph (Tangle) instead of blockchain.',
    ucid: 1720,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'iot', 'infrastructure'],
    website: 'https://www.iota.org',
    github: 'https://github.com/iotaledger',
    npm: 'https://www.npmjs.com/package/@iota/sdk'
  },
  { 
    id: 'iostoken', 
    symbol: 'IOST', 
    name: 'IOST',
    description: 'A scalable blockchain platform for providing secure and scalable infrastructure for online services.',
    ucid: 2405,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://iost.io',
    github: 'https://github.com/iost-official',
    npm: 'https://www.npmjs.com/package/iost'
  },
  { 
    id: 'story', 
    symbol: 'IP', 
    name: 'Story',
    description: 'A blockchain platform focused on intellectual property management and NFT infrastructure.',
    ucid: 32370,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'nft', 'infrastructure'],
    website: 'https://storyprotocol.xyz',
    github: 'https://github.com/storyprotocol',
    npm: null
  },
  { 
    id: 'komodo', 
    symbol: 'KMD', 
    name: 'Komodo',
    description: 'A multi-chain platform providing blockchain solutions with atomic swaps and privacy features.',
    ucid: 1521,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'interoperability', 'privacy'],
    website: 'https://komodoplatform.com',
    github: 'https://github.com/KomodoPlatform',
    npm: null
  },
  { 
    id: 'kusama', 
    symbol: 'KSM', 
    name: 'Kusama',
    description: 'A scalable network of specialized blockchains built using Substrate, serving as Polkadot\'s canary network.',
    ucid: 5034,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['layer-1', 'interoperability'],
    website: 'https://kusama.network',
    github: 'https://github.com/paritytech/polkadot',
    npm: 'https://www.npmjs.com/package/@polkadot/api'
  },
  { 
    id: 'terra-luna', 
    symbol: 'LUNA', 
    name: 'Terra',
    description: 'The native token of Terra 2.0 blockchain, rebuilt after the Terra Classic collapse.',
    ucid: 20314,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://terra.money',
    github: 'https://github.com/terra-money',
    npm: 'https://www.npmjs.com/package/@terra-money/terra.js'
  },
  { 
    id: 'terra-luna-2', 
    symbol: 'LUNC', 
    name: 'Terra Classic',
    description: 'The original Terra blockchain token, now known as Terra Classic after the network split.',
    ucid: 4172,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://terra.money',
    github: 'https://github.com/classic-terra',
    npm: null
  },
  { 
    id: 'mina-protocol', 
    symbol: 'MINA', 
    name: 'Mina Protocol',
    description: 'A lightweight blockchain with a constant size of 22KB using zero-knowledge proofs.',
    ucid: 8925,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'privacy'],
    website: 'https://minaprotocol.com',
    github: 'https://github.com/MinaProtocol',
    npm: 'https://www.npmjs.com/package/mina-signer'
  },
  { 
    id: 'near', 
    symbol: 'NEAR', 
    name: 'Near',
    description: 'A sharded proof-of-stake blockchain designed for usability and scalability with simple onboarding.',
    ucid: 6535,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://near.org',
    github: 'https://github.com/near',
    npm: 'https://www.npmjs.com/package/near-api-js'
  },
  { 
    id: 'neo', 
    symbol: 'NEO', 
    name: 'NEO',
    description: 'A blockchain platform for building decentralized applications with digital assets and smart contracts.',
    ucid: 1376,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://neo.org',
    github: 'https://github.com/neo-project',
    npm: 'https://www.npmjs.com/package/@cityofzion/neon-js'
  },
  { 
    id: 'oasys', 
    symbol: 'OAS', 
    name: 'Oasys',
    description: 'A gaming-optimized blockchain providing fast transactions and low gas fees for games.',
    ucid: 21444,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'gaming'],
    website: 'https://oasys.games',
    github: 'https://github.com/oasysgames',
    npm: null
  },
  { 
    id: 'mantra-dao', 
    symbol: 'OM', 
    name: 'MANTRA',
    description: 'A security-first blockchain for Real World Asset (RWA) tokenization.',
    ucid: 6536,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'defi'],
    website: 'https://www.mantrachain.io',
    github: 'https://github.com/MANTRA-Finance',
    npm: null
  },
  { 
    id: 'ontology', 
    symbol: 'ONT', 
    name: 'Ontology',
    description: 'A high-performance blockchain focused on digital identity and data solutions.',
    ucid: 2566,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'infrastructure'],
    website: 'https://ont.io',
    github: 'https://github.com/ontio',
    npm: 'https://www.npmjs.com/package/ontology-ts-sdk'
  },
  { 
    id: 'osmosis', 
    symbol: 'OSMO', 
    name: 'Osmosis',
    description: 'A decentralized exchange and automated market maker protocol built on the Cosmos ecosystem.',
    ucid: 12220,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'dex'],
    website: 'https://osmosis.zone',
    github: 'https://github.com/osmosis-labs',
    npm: null
  },
  { 
    id: 'qtum', 
    symbol: 'QTUM', 
    name: 'Qtum',
    description: 'A blockchain platform combining Bitcoin\'s security with Ethereum\'s smart contract functionality.',
    ucid: 1684,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://qtum.org',
    github: 'https://github.com/qtumproject',
    npm: null
  },
  { 
    id: 'reddcoin', 
    symbol: 'RDD', 
    name: 'Reddcoin',
    description: 'A social cryptocurrency for tipping and microtransactions on social media platforms.',
    ucid: 118,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['social', 'payment'],
    website: 'https://reddcoin.com',
    github: 'https://github.com/reddcoin-project',
    npm: null
  },
  { 
    id: 'oasis-network', 
    symbol: 'ROSE', 
    name: 'Oasis',
    description: 'A privacy-enabled blockchain platform designed for DeFi and scalable data tokenization.',
    ucid: 7653,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'privacy', 'defi'],
    website: 'https://oasisprotocol.org',
    github: 'https://github.com/oasisprotocol',
    npm: null
  },
  { 
    id: 'thorchain', 
    symbol: 'RUNE', 
    name: 'THORChain',
    description: 'A decentralized liquidity protocol enabling cross-chain swaps of native assets.',
    ucid: 4157,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['defi', 'dex', 'interoperability'],
    website: 'https://thorchain.org',
    github: 'https://github.com/thorchain',
    npm: null
  },
  { 
    id: 'saga-2', 
    symbol: 'SAGA', 
    name: 'Saga',
    description: 'A layer-1 blockchain platform designed for launching parallel, application-specific chains.',
    ucid: 29786,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://saga.xyz',
    github: 'https://github.com/sagaxyz',
    npm: null
  },
  { 
    id: 'secret', 
    symbol: 'SCRT', 
    name: 'Secret',
    description: 'A privacy-focused blockchain enabling encrypted smart contracts with encrypted inputs, outputs, and state.',
    ucid: 5604,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'privacy', 'smart-contract-platform'],
    website: 'https://scrt.network',
    github: 'https://github.com/scrtlabs',
    npm: 'https://www.npmjs.com/package/secretjs'
  },
  { 
    id: 'sei-network', 
    symbol: 'SEI', 
    name: 'Sei',
    description: 'A layer-1 blockchain optimized for trading and DeFi applications with high throughput.',
    ucid: 23149,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'defi', 'dex'],
    website: 'https://sei.io',
    github: 'https://github.com/sei-protocol',
    npm: null
  },
  { 
    id: 'solana', 
    symbol: 'SOL', 
    name: 'Solana',
    description: 'A high-performance blockchain supporting fast transactions and low fees through proof-of-history.',
    ucid: 5426,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://solana.com',
    github: 'https://github.com/solana-labs',
    npm: 'https://www.npmjs.com/package/@solana/web3.js'
  },
  { 
    id: 'strax', 
    symbol: 'STRAX', 
    name: 'Xertra',
    description: 'A blockchain platform (formerly Stratis) for enterprise solutions and custom blockchain development.',
    ucid: 8440,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://www.stratisplatform.com',
    github: 'https://github.com/stratisproject',
    npm: null
  },
  { 
    id: 'blockstack', 
    symbol: 'STX', 
    name: 'Stacks',
    description: 'A layer-1 blockchain that brings smart contracts and dApps to Bitcoin.',
    ucid: 4847,
    type: 'coin',
    consensusType: 'proof-of-transfer',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://stacks.co',
    github: 'https://github.com/stacks-network',
    npm: 'https://www.npmjs.com/package/@stacks/transactions'
  },
  { 
    id: 'sui', 
    symbol: 'SUI', 
    name: 'Sui',
    description: 'A layer-1 blockchain built with the Move programming language for fast, scalable applications.',
    ucid: 20947,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://sui.io',
    github: 'https://github.com/MystenLabs',
    npm: 'https://www.npmjs.com/package/@mysten/sui.js'
  },
  { 
    id: 'bittensor', 
    symbol: 'TAO', 
    name: 'Bittensor',
    description: 'A decentralized machine learning network creating a peer-to-peer intelligence market.',
    ucid: 22974,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['ai', 'infrastructure'],
    website: 'https://bittensor.com',
    github: 'https://github.com/opentensor',
    npm: null
  },
  { 
    id: 'celestia', 
    symbol: 'TIA', 
    name: 'Celestia',
    description: 'A modular blockchain network that decouples consensus from execution for scalability.',
    ucid: 28299,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://celestia.org',
    github: 'https://github.com/celestiaorg',
    npm: null
  },
  { 
    id: 'the-open-network', 
    symbol: 'TON', 
    name: 'Toncoin',
    description: 'A decentralized layer-1 blockchain originally developed by Telegram, designed for mass adoption.',
    ucid: 11419,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'payment'],
    website: 'https://ton.org',
    github: 'https://github.com/ton-blockchain',
    npm: 'https://www.npmjs.com/package/ton'
  },
  { 
    id: 'tron', 
    symbol: 'TRX', 
    name: 'TRON',
    description: 'A blockchain platform focused on content sharing and entertainment with high throughput.',
    ucid: 1958,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://tron.network',
    github: 'https://github.com/tronprotocol',
    npm: 'https://www.npmjs.com/package/tronweb'
  },
  { 
    id: 'vechain', 
    symbol: 'VET', 
    name: 'Vechain',
    description: 'An enterprise-grade blockchain platform focused on supply chain management and business processes.',
    ucid: 3077,
    type: 'coin',
    consensusType: 'proof-of-authority',
    class: ['layer-1', 'infrastructure'],
    website: 'https://vechain.org',
    github: 'https://github.com/vechain',
    npm: 'https://www.npmjs.com/package/@vechain/connex'
  },
  { 
    id: 'wanchain', 
    symbol: 'WAN', 
    name: 'Wanchain',
    description: 'A blockchain platform providing cross-chain infrastructure for decentralized financial applications.',
    ucid: 2606,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'interoperability', 'defi'],
    website: 'https://wanchain.org',
    github: 'https://github.com/wanchain',
    npm: 'https://www.npmjs.com/package/wanchain-js-sdk'
  },
  { 
    id: 'waves', 
    symbol: 'WAVES', 
    name: 'Waves',
    description: 'A multi-purpose blockchain platform for custom tokens, smart contracts, and decentralized applications.',
    ucid: 1274,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://waves.tech',
    github: 'https://github.com/wavesplatform',
    npm: 'https://www.npmjs.com/package/@waves/waves-transactions'
  },
  { 
    id: 'xdce-crowd-sale', 
    symbol: 'XDC', 
    name: 'XDC Network',
    description: 'An enterprise-ready hybrid blockchain for global trade and finance with instant block finality.',
    ucid: 2634,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'infrastructure'],
    website: 'https://xdc.org',
    github: 'https://github.com/XinFinOrg',
    npm: 'https://www.npmjs.com/package/xdc3'
  },
  { 
    id: 'stellar', 
    symbol: 'XLM', 
    name: 'Stellar',
    description: 'An open network for storing and moving money, designed for fast, low-cost cross-border payments.',
    ucid: 512,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    website: 'https://stellar.org',
    github: 'https://github.com/stellar',
    npm: 'https://www.npmjs.com/package/@stellar/stellar-sdk'
  },
  { 
    id: 'ripple', 
    symbol: 'XRP', 
    name: 'XRP',
    description: 'A digital payment protocol and cryptocurrency designed for fast, low-cost international money transfers.',
    ucid: 52,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    website: 'https://ripple.com',
    github: 'https://github.com/ripple',
    npm: 'https://www.npmjs.com/package/xrpl'
  },
  { 
    id: 'tezos', 
    symbol: 'XTZ', 
    name: 'Tezos',
    description: 'A self-amending blockchain with on-chain governance and formal verification for smart contracts.',
    ucid: 2011,
    type: 'coin',
    consensusType: 'liquid-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://tezos.com',
    github: 'https://github.com/tezos',
    npm: 'https://www.npmjs.com/package/@taquito/taquito'
  },
  { 
    id: 'zano', 
    symbol: 'ZANO', 
    name: 'Zano',
    description: 'A privacy-focused cryptocurrency with hybrid proof-of-work/proof-of-stake consensus.',
    ucid: 5541,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://zano.org',
    github: 'https://github.com/hyle-team/zano',
    npm: null
  },
  { 
    id: 'zetachain', 
    symbol: 'ZETA', 
    name: 'ZetaChain',
    description: 'A foundational, public blockchain enabling omnichain smart contracts and messaging between blockchains.',
    ucid: 21259,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'interoperability'],
    website: 'https://www.zetachain.com',
    github: 'https://github.com/zeta-chain',
    npm: null
  }
];

export default PROOF_OF_STAKE;

