/**
 * SEC Securities List - Cryptocurrencies that have been subject to SEC regulatory action or scrutiny
 * 
 * This list contains digital assets that have been identified in SEC enforcement actions,
 * regulatory guidance, or other securities-related proceedings. This list is used for
 * compliance monitoring and regulatory awareness purposes.
 * 
 * Note: Inclusion in this list does not constitute legal advice or a determination
 * of securities status. Always consult with legal counsel for regulatory compliance.
 * 
 * Last Updated: December 2025
 * Source: SEC enforcement actions and regulatory guidance
 */

export type CurrencyType = 'coin' | 'token';
export type ConsensusType = 'proof-of-stake' | 'proof-of-work' | 'proof-of-authority' | 'delegated-proof-of-stake' | 'nominated-proof-of-stake' | 'byzantine-fault-tolerance' | 'token' | 'hybrid' | 'algorit hmic' | 'n/a';
export type CurrencyClass = 'layer-1' | 'layer-2' | 'defi' | 'dex' | 'nft' | 'gaming' | 'metaverse' | 'oracle' | 'privacy' | 'meme' | 'staking' | 'governance' | 'lending' | 'data' | 'infrastructure' | 'smart-contract-platform' | 'exchange-token' | 'ai' | 'storage' | 'payment' | 'social' | 'real-estate';
export type SecActionType = 'enforcement-action' | 'securities-allegation' | 'ongoing-litigation' | 'settlement' | 'alleged-fraud' | 'unregistered-securities' | 'regulatory-scrutiny';

export interface SecSecurityItem {
  id: string;
  symbol: string;
  name: string;
  description: string;
  ucid: number | null;
  type: CurrencyType;
  consensusType: ConsensusType;
  class: CurrencyClass[];
  secAction: SecActionType[];
  website: string | null;
  github: string | null;
  npm: string | null;
}

export const SEC_SECURITIES_LIST: SecSecurityItem[] = [
  {
    id: 'airtoken',
    symbol: 'AIR',
    name: 'AirToken',
    description: 'Mobile advertising rewards token that was subject to SEC enforcement action for unregistered securities offering',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['payment'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'algorand',
    symbol: 'ALGO',
    name: 'Algorand',
    description: 'Pure proof-of-stake blockchain mentioned in SEC complaints regarding exchange listings',
    ucid: 4030,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://algorand.com/',
    github: 'https://github.com/algorand',
    npm: 'algosdk'
  },
  {
    id: 'amp-token',
    symbol: 'AMP',
    name: 'Amp',
    description: 'Collateral token for the Flexa payment network, alleged as unregistered security by SEC',
    ucid: 6945,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'payment'],
    secAction: ['securities-allegation', 'unregistered-securities'],
    website: 'https://amptoken.org/',
    github: 'https://github.com/amptoken',
    npm: null
  },
  {
    id: 'axie-infinity',
    symbol: 'AXS',
    name: 'Axie Infinity',
    description: 'Governance token for blockchain-based gaming platform, subject to SEC regulatory scrutiny',
    ucid: 6783,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'nft', 'governance'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://axieinfinity.com/',
    github: 'https://github.com/axieinfinity',
    npm: null
  },
  {
    id: 'beaxy-token',
    symbol: 'BXY',
    name: 'Beaxy Token',
    description: 'Exchange token from Beaxy platform involved in SEC enforcement for unregistered securities',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['exchange-token'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'binance-usd',
    symbol: 'BUSD',
    name: 'Binance USD',
    description: 'USD-backed stablecoin discontinued after SEC action against Paxos for unregistered securities',
    ucid: 4687,
    type: 'token',
    consensusType: 'token',
    class: ['payment'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: 'https://www.binance.com/',
    github: null,
    npm: null
  },
  {
    id: 'bitconnect',
    symbol: 'BCC',
    name: 'BitConnect',
    description: 'Lending platform token shut down after SEC fraud allegations and Ponzi scheme accusations',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['lending'],
    secAction: ['enforcement-action', 'alleged-fraud', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'bittorrent',
    symbol: 'BTT',
    name: 'BitTorrent',
    description: 'Token for decentralized file sharing protocol, mentioned in SEC securities allegations',
    ucid: 3718,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'storage'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://www.bittorrent.com/',
    github: 'https://github.com/TRON-US',
    npm: null
  },
  {
    id: 'binancecoin',
    symbol: 'BNB',
    name: 'BNB',
    description: 'Binance exchange token facing ongoing SEC litigation alleging unregistered securities offering',
    ucid: 1839,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'exchange-token', 'smart-contract-platform'],
    secAction: ['ongoing-litigation', 'securities-allegation', 'unregistered-securities'],
    website: 'https://www.bnbchain.org/',
    github: 'https://github.com/bnb-chain',
    npm: null
  },
  {
    id: 'cardano',
    symbol: 'ADA',
    name: 'Cardano',
    description: 'Proof-of-stake blockchain platform mentioned in SEC complaints regarding exchange listings',
    ucid: 2010,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://cardano.org/',
    github: 'https://github.com/input-output-hk',
    npm: '@emurgo/cardano-serialization-lib-nodejs'
  },
  {
    id: 'chiliz',
    symbol: 'CHZ',
    name: 'Chiliz',
    description: 'Sports and entertainment blockchain token subject to SEC regulatory scrutiny',
    ucid: 4066,
    type: 'token',
    consensusType: 'token',
    class: ['exchange-token'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://www.chiliz.com/',
    github: 'https://github.com/chiliz-chain',
    npm: null
  },
  {
    id: 'cosmos',
    symbol: 'ATOM',
    name: 'Cosmos',
    description: 'Interoperable blockchain ecosystem mentioned in SEC securities allegations',
    ucid: 3794,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://cosmos.network/',
    github: 'https://github.com/cosmos',
    npm: '@cosmjs/stargate'
  },
  {
    id: 'coti',
    symbol: 'COTI',
    name: 'COTI',
    description: 'Enterprise payment processing platform token subject to SEC regulatory scrutiny',
    ucid: 3992,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['payment', 'infrastructure'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://coti.io/',
    github: 'https://github.com/coti-io',
    npm: null
  },
  {
    id: 'dash',
    symbol: 'DASH',
    name: 'DASH',
    description: 'Privacy-focused cryptocurrency mentioned in SEC regulatory discussions',
    ucid: 131,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    secAction: ['regulatory-scrutiny'],
    website: 'https://www.dash.org/',
    github: 'https://github.com/dashpay',
    npm: null
  },
  {
    id: 'decentraland',
    symbol: 'MANA',
    name: 'Decentraland',
    description: 'Virtual reality platform token mentioned in SEC securities allegations',
    ucid: 1966,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'gaming', 'nft'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://decentraland.org/',
    github: 'https://github.com/decentraland',
    npm: 'decentraland'
  },
  {
    id: 'derivadao',
    symbol: 'DDX',
    name: 'DerivaDAO',
    description: 'Decentralized derivatives protocol token subject to SEC enforcement action',
    ucid: 8207,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'dfx-finance',
    symbol: 'DFX',
    name: 'DFX Finance',
    description: 'Decentralized foreign exchange protocol token involved in SEC enforcement',
    ucid: 9355,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: 'https://dfx.finance/',
    github: 'https://github.com/dfx-finance',
    npm: null
  },
  {
    id: 'dragonchain',
    symbol: 'DRGN',
    name: 'DragonChain',
    description: 'Blockchain platform for business applications subject to SEC enforcement',
    ucid: 2243,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: 'https://github.com/dragonchain',
    npm: null
  },
  {
    id: 'ducat',
    symbol: 'DUCAT',
    name: 'Ducat',
    description: 'Cryptocurrency involved in SEC fraud allegations',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['payment'],
    secAction: ['enforcement-action', 'alleged-fraud'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'ethereummax',
    symbol: 'EMAX',
    name: 'EthereumMax',
    description: 'Meme token subject to SEC fraud allegations and celebrity promotion investigation',
    ucid: 14962,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    secAction: ['enforcement-action', 'alleged-fraud'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'filecoin',
    symbol: 'FIL',
    name: 'Filecoin',
    description: 'Decentralized storage network token mentioned in SEC securities allegations',
    ucid: 5704,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://filecoin.io/',
    github: 'https://github.com/filecoin-project',
    npm: '@filecoin-shipyard/js-filecoin-api-client'
  },
  {
    id: 'flow',
    symbol: 'FLOW',
    name: 'Flow',
    description: 'NFT-focused blockchain platform mentioned in SEC securities allegations',
    ucid: 4558,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'nft', 'smart-contract-platform'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://flow.com/',
    github: 'https://github.com/onflow',
    npm: '@onflow/fcl'
  },
  {
    id: 'hydro',
    symbol: 'HYDRO',
    name: 'Hydro',
    description: 'Financial services protocol token involved in SEC fraud investigation',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['defi'],
    secAction: ['enforcement-action', 'alleged-fraud'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'iht-real-estate',
    symbol: 'IHT',
    name: 'IHT Real Estate',
    description: 'Real estate tokenization platform subject to SEC enforcement action',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['real-estate'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'internet-computer',
    symbol: 'ICP',
    name: 'Internet Computer',
    description: 'Blockchain running at web speed, mentioned in SEC securities allegations',
    ucid: 8916,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://internetcomputer.org/',
    github: 'https://github.com/dfinity',
    npm: '@dfinity/agent'
  },
  {
    id: 'kromatika',
    symbol: 'KROM',
    name: 'Kromatika',
    description: 'DeFi protocol token subject to SEC enforcement action',
    ucid: 11956,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: 'https://kromatika.finance/',
    github: 'https://github.com/Kromatika-Finance',
    npm: null
  },
  {
    id: 'kin',
    symbol: 'KIN',
    name: 'Kin',
    description: 'Social media cryptocurrency that settled with SEC for unregistered securities offering',
    ucid: 1993,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['social', 'payment'],
    secAction: ['enforcement-action', 'settlement', 'unregistered-securities'],
    website: 'https://kin.org/',
    github: 'https://github.com/kinecosystem',
    npm: null
  },
  {
    id: 'lbry-credits',
    symbol: 'LBC',
    name: 'LBRY Credits',
    description: 'Content sharing platform token found to be unregistered security by SEC',
    ucid: 3297,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['social', 'infrastructure'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: 'https://github.com/lbryio',
    npm: null
  },
  {
    id: 'lcx',
    symbol: 'LCX',
    name: 'Liechtenstein Cryptoasset Exchange',
    description: 'Exchange and security token platform subject to SEC regulatory scrutiny',
    ucid: 5790,
    type: 'token',
    consensusType: 'token',
    class: ['exchange-token', 'defi'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://www.lcx.com/',
    github: 'https://github.com/LCX-AG',
    npm: null
  },
  {
    id: 'locke',
    symbol: 'LOCKE',
    name: 'Locke',
    description: 'Token involved in SEC fraud allegations',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['defi'],
    secAction: ['enforcement-action', 'alleged-fraud'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'omisego',
    symbol: 'OMG',
    name: 'OmiseGo',
    description: 'Ethereum scaling solution mentioned in SEC securities allegations',
    ucid: 1808,
    type: 'token',
    consensusType: 'token',
    class: ['layer-2', 'payment'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://omg.network/',
    github: 'https://github.com/omgnetwork',
    npm: null
  },
  {
    id: 'meta-1-coin',
    symbol: 'META1',
    name: 'Meta 1 Coin',
    description: 'Cryptocurrency subject to SEC fraud charges and emergency asset freeze',
    ucid: null,
    type: 'coin',
    consensusType: 'n/a',
    class: ['payment'],
    secAction: ['enforcement-action', 'alleged-fraud', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'mango-markets',
    symbol: 'MNGO',
    name: 'Mango',
    description: 'Decentralized trading platform token subject to SEC enforcement',
    ucid: 9538,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: 'https://mango.markets/',
    github: 'https://github.com/blockworks-foundation',
    npm: null
  },
  {
    id: 'mirror-protocol',
    symbol: 'MIR',
    name: 'Mirror Protocol',
    description: 'Synthetic assets protocol token charged by SEC for unregistered securities',
    ucid: 7857,
    type: 'token',
    consensusType: 'token',
    class: ['defi'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: 'https://github.com/Mirror-Protocol',
    npm: null
  },
  {
    id: 'tokencard',
    symbol: 'TKN',
    name: 'Monolith',
    description: 'Crypto payment card platform token mentioned in SEC allegations',
    ucid: 2458,
    type: 'token',
    consensusType: 'token',
    class: ['payment'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://monolith.xyz/',
    github: 'https://github.com/monetha',
    npm: null
  },
  {
    id: 'naga',
    symbol: 'NGC',
    name: 'Naga',
    description: 'Trading platform token subject to SEC regulatory scrutiny',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['exchange-token'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://naga.com/',
    github: null,
    npm: null
  },
  {
    id: 'near',
    symbol: 'NEAR',
    name: 'Near',
    description: 'Sharded blockchain platform mentioned in SEC securities allegations',
    ucid: 6535,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://near.org/',
    github: 'https://github.com/near',
    npm: 'near-api-js'
  },
  {
    id: 'nexo',
    symbol: 'NEXO',
    name: 'Nexo',
    description: 'Crypto lending platform token settled with SEC for unregistered securities',
    ucid: 2694,
    type: 'token',
    consensusType: 'token',
    class: ['lending', 'defi'],
    secAction: ['enforcement-action', 'settlement', 'unregistered-securities'],
    website: 'https://nexo.io/',
    github: null,
    npm: null
  },
  {
    id: 'power-ledger',
    symbol: 'POWR',
    name: 'Power Ledger',
    description: 'Energy trading platform token subject to SEC regulatory scrutiny',
    ucid: 2132,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://www.powerledger.io/',
    github: 'https://github.com/PowerLedger',
    npm: null
  },
  {
    id: 'paragon',
    symbol: 'PRG',
    name: 'Paragon',
    description: 'Cannabis industry token settled with SEC for unregistered securities',
    ucid: null,
    type: 'token',
    consensusType: 'token',
    class: ['payment'],
    secAction: ['enforcement-action', 'settlement', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'matic-network',
    symbol: 'MATIC',
    name: 'Polygon',
    description: 'Ethereum scaling solution mentioned in SEC securities allegations',
    ucid: 3890,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['layer-2'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://polygon.technology/',
    github: 'https://github.com/maticnetwork',
    npm: '@maticnetwork/maticjs'
  },
  {
    id: 'rally-2',
    symbol: 'RLY',
    name: 'Rally',
    description: 'Creator economy token platform subject to SEC regulatory scrutiny',
    ucid: 8075,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'infrastructure'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://rally.io/',
    github: 'https://github.com/rally-dfs',
    npm: null
  },
  {
    id: 'rari-governance-token',
    symbol: 'RGT',
    name: 'Rari Governance Token',
    description: 'DeFi yield aggregator governance token subject to SEC enforcement',
    ucid: 7456,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: 'https://github.com/Rari-Capital',
    npm: null
  },
  {
    id: 'salt',
    symbol: 'SALT',
    name: 'Salt Lending',
    description: 'Blockchain-backed lending platform token settled with SEC for unregistered securities',
    ucid: 1996,
    type: 'token',
    consensusType: 'token',
    class: ['lending', 'defi'],
    secAction: ['enforcement-action', 'settlement', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'solana',
    symbol: 'SOL',
    name: 'Solana',
    description: 'High-performance blockchain mentioned in SEC securities allegations',
    ucid: 5426,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://solana.com/',
    github: 'https://github.com/solana-labs',
    npm: '@solana/web3.js'
  },
  {
    id: 'the-sandbox',
    symbol: 'SAND',
    name: 'Sandbox, The',
    description: 'Metaverse gaming platform token mentioned in SEC securities allegations',
    ucid: 6210,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'gaming', 'nft'],
    secAction: ['securities-allegation', 'regulatory-scrutiny'],
    website: 'https://www.sandbox.game/',
    github: 'https://github.com/thesandboxgame',
    npm: null
  },
  {
    id: 'the-open-network',
    symbol: 'TON',
    name: 'Telegram\'s Gram',
    description: 'Telegram blockchain project halted by SEC for unregistered securities offering',
    ucid: 11419,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: 'https://ton.org/',
    github: 'https://github.com/ton-blockchain',
    npm: null
  },
  {
    id: 'terra-luna',
    symbol: 'LUNA',
    name: 'Terra (Classic)',
    description: 'Collapsed algorithmic stablecoin ecosystem under SEC fraud investigation',
    ucid: 4172,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['enforcement-action', 'alleged-fraud', 'ongoing-litigation'],
    website: 'https://terra.money/',
    github: 'https://github.com/terra-money',
    npm: null
  },
  {
    id: 'terrausd',
    symbol: 'USTC',
    name: 'Terra USD',
    description: 'Failed algorithmic stablecoin under SEC fraud investigation after collapse',
    ucid: 7129,
    type: 'token',
    consensusType: 'token',
    class: ['payment'],
    secAction: ['enforcement-action', 'alleged-fraud', 'ongoing-litigation'],
    website: 'https://terra.money/',
    github: 'https://github.com/terra-money',
    npm: null
  },
  {
    id: 'tron',
    symbol: 'TRX',
    name: 'Tron',
    description: 'Blockchain platform subject to SEC fraud charges for unregistered securities',
    ucid: 1958,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    secAction: ['enforcement-action', 'alleged-fraud', 'unregistered-securities'],
    website: 'https://tron.network/',
    github: 'https://github.com/tronprotocol',
    npm: 'tronweb'
  },
  {
    id: 'voyager-token',
    symbol: 'VGX',
    name: 'Voyager Token',
    description: 'Crypto brokerage token involved in SEC bankruptcy proceedings and securities allegations',
    ucid: 5791,
    type: 'token',
    consensusType: 'token',
    class: ['exchange-token'],
    secAction: ['enforcement-action', 'unregistered-securities'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'xyo-network',
    symbol: 'XYO',
    name: 'XYO Network',
    description: 'Location data oracle network settled with SEC for unregistered securities',
    ucid: 3902,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure'],
    secAction: ['enforcement-action', 'settlement', 'unregistered-securities'],
    website: 'https://xyo.network/',
    github: 'https://github.com/XYOracleNetwork',
    npm: null
  },
  {
    id: 'ripple',
    symbol: 'XRP',
    name: 'XRP',
    description: 'Digital payment token subject to landmark SEC lawsuit alleging unregistered securities offering',
    ucid: 52,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    secAction: ['ongoing-litigation', 'securities-allegation', 'unregistered-securities'],
    website: 'https://xrpl.org/',
    github: 'https://github.com/XRPLF',
    npm: 'xrpl'
  }
];

export default SEC_SECURITIES_LIST;

