import type { MainExportCommodities } from '../africanUnion/types'
import { commodityTuple as m } from './buildAllianceMainExportCommodities'

/**
 * Export commodities for economies not covered by AU / APEC / ASEAN / Arab League
 * or the EAC / ECCAS / ECOWAS / EU / fiveEyes / G7 / G20 / GCC alliance modules
 * (informational; verify against UN Comtrade periodically).
 */
export const MAIN_EXPORT_COMMODITIES_EXTRAS: Record<string, MainExportCommodities> = {
  AF: m('Dried fruits', 'Carpets', 'Precious stones', 'Copper ore', 'Hides and skins', 'Grapes', 'Herbs'),
  AG: m('Tourism services', 'Passenger ships', 'Rum', 'Fruit', 'Fish', 'Bed linen', 'Electronics'),
  AI: m('Tourism services', 'Rum', 'Fish', 'Lobster', 'Salt', 'Electronics', 'Passenger transport'),
  AL: m('Footwear', 'Garments', 'Chromium ore', 'Electricity', 'Oil seeds', 'Tobacco', 'Copper'),
  AM: m('Copper ore', 'Gold', 'Tobacco', 'Brandy', 'Textiles', 'Precious stones', 'Food products'),
  AZ: m('Crude petroleum', 'Natural gas', 'Refined petroleum', 'Tomatoes', 'Gold', 'Cotton', 'Plastics'),
  BA: m('Electricity', 'Aluminium', 'Furniture', 'Footwear', 'Wood products', 'Iron and steel', 'Textiles'),
  BB: m('Rum', 'Sugar', 'Tourism services', 'Chemicals', 'Electronics', 'Fish', 'Manufactured goods'),
  BD: m('Garments', 'Jute', 'Leather goods', 'Fish', 'Home textiles', 'Footwear', 'Rice'),
  BM: m('Tourism services', 'Pharmaceuticals', 'Fish', 'Liquified natural gas re-exports', 'Rum', 'Financial services exports', 'Electronics'),
  BO: m('Natural gas', 'Gold', 'Zinc ore', 'Soybeans', 'Silver', 'Tin', 'Quinoa'),
  BS: m('Tourism services', 'Refined petroleum', 'Fish', 'Rum', 'Salt', 'Aragonite', 'Passenger ships'),
  BY: m('Potassium fertilizers', 'Refined petroleum', 'Tractors', 'Dairy products', 'Machinery', 'Wood products', 'Steel'),
  BZ: m('Sugar', 'Bananas', 'Citrus fruit', 'Crude petroleum', 'Fish', 'Tourism services', 'Papayas'),
  CK: m('Fish', 'Pearls', 'Fruit', 'Copra', 'Tourism services', 'Black pearls', 'Clothing'),
  CO: m('Crude petroleum', 'Coal', 'Coffee', 'Gold', 'Bananas', 'Cut flowers', 'Refined petroleum'),
  CR: m('Medical instruments', 'Bananas', 'Pineapples', 'Coffee', 'Melons', 'Orthopedic appliances', 'Fruit juice'),
  CU: m('Raw sugar', 'Nickel', 'Tobacco', 'Zinc', 'Pharmaceuticals', 'Rum', 'Fish'),
  DM: m('Bananas', 'Soap', 'Tourism services', 'Citrus fruit', 'Vegetables', 'Cocoa', 'Manufactured goods'),
  DO: m('Gold', 'Medical instruments', 'Tobacco', 'Bananas', 'Textiles', 'Rum', 'Cocoa'),
  EC: m('Crude petroleum', 'Bananas', 'Shrimp', 'Cocoa', 'Fish', 'Cut flowers', 'Gold'),
  FJ: m('Water', 'Fish', 'Sugar', 'Gold', 'Timber', 'Garments', 'Mineral water'),
  FM: m('Fish', 'Copra', 'Tourism services', 'Black pearls', 'Kava', 'Bananas', 'Handicrafts'),
  GD: m('Nutmeg', 'Cocoa', 'Fish', 'Tourism services', 'Mace', 'Bananas', 'Manufactured goods'),
  GE: m('Copper ore', 'Wine', 'Ferroalloys', 'Gold', 'Nuts', 'Mineral water', 'Machinery'),
  GY: m('Gold', 'Rice', 'Bauxite', 'Sugar', 'Shrimp', 'Timber', 'Aluminium ore'),
  HN: m('Coffee', 'Bananas', 'Palm oil', 'Shrimp', 'Melons', 'Apparel', 'Gold'),
  HT: m('Garments', 'Coffee', 'Mango', 'Essential oils', 'Fish', 'Cocoa', 'Manufactured goods'),
  IR: m('Crude petroleum', 'Petrochemicals', 'Natural gas', 'Dates', 'Pistachios', 'Carpets', 'Steel'),
  JM: m('Alumina', 'Bauxite', 'Rum', 'Coffee', 'Tourism services', 'Yam', 'Mining products'),
  KG: m('Gold', 'Cotton', 'Precious-metal ore', 'Electricity', 'Dried fruits', 'Apparel', 'Honey'),
  KI: m('Fish', 'Copra', 'Seaweed', 'Coconut oil', 'Tourism services', 'Tuna', 'Handicrafts'),
  KN: m('Electronics', 'Tourism services', 'Fish', 'Passenger ships', 'Rum', 'Manufactured goods', 'Financial services exports'),
  KY: m('Tourism services', 'Fish', 'Financial services exports', 'Rum', 'Re-exports', 'Construction materials', 'Passenger transport'),
  KZ: m('Crude petroleum', 'Refined copper', 'Wheat', 'Uranium', 'Iron ore', 'Coal', 'Natural gas'),
  LC: m('Bananas', 'Tourism services', 'Beer', 'Fish', 'Electronics', 'Cocoa', 'Manufactured goods'),
  LK: m('Tea', 'Apparel', 'Rubber', 'Coconut products', 'Spices', 'Fish', 'Gems'),
  MD: m('Wine', 'Sunflower seeds', 'Wheat', 'Apparel', 'Fruit', 'Electricity', 'Vegetables'),
  ME: m('Aluminium', 'Electricity', 'Wine', 'Fish', 'Packaged medicaments', 'Tourism services', 'Steel'),
  MK: m('Refined copper', 'Iron and steel', 'Automobile parts', 'Textiles', 'Wine', 'Tobacco', 'Vegetables'),
  MN: m('Coal', 'Copper', 'Gold', 'Cashmere', 'Iron ore', 'Crude petroleum', 'Wool'),
  MS: m('Electronic components', 'Tourism services', 'Rum', 'Vegetables', 'Fish', 'Lime products', 'Textiles'),
  MV: m('Fish', 'Tourism services', 'Garments', 'Coconut products', 'Thresher shark meat', 'Aircraft parts', 'Re-exports'),
  NI: m('Gold', 'Coffee', 'Beef', 'Sugar', 'Beans', 'Rum', 'Textiles'),
  NP: m('Palm oil', 'Carpets', 'Tea', 'Cardamom', 'Clothing', 'Iron and steel', 'Vegetables'),
  NR: m('Phosphate', 'Fish', 'Tourism services', 'Coconut products', 'Passenger ships', 'Handicrafts', 'Re-exports'),
  NU: m('Coconut products', 'Tourism services', 'Handicrafts', 'Fish', 'Honey', 'Passenger ships', 'Food products'),
  PA: m('Bananas', 'Refined petroleum', 'Fish', 'Gold', 'Medical instruments', 'Copper ore', 'Melons'),
  PK: m('Textiles', 'Rice', 'Leather goods', 'Cotton yarn', 'Sports goods', 'Sugar', 'Cement'),
  RS: m('Electricity', 'Packaged medicaments', 'Fruit', 'Automobiles', 'Iron and steel', 'Copper ore', 'Raspberries'),
  SB: m('Timber', 'Fish', 'Palm oil', 'Copra', 'Gold', 'Tourism services', 'Cocoa'),
  SR: m('Gold', 'Oil', 'Rice', 'Aluminium ore', 'Shrimp', 'Timber', 'Bananas'),
  SV: m('Textiles', 'Coffee', 'Sugar', 'Gold', 'Electricity', 'Paper', 'Medicaments'),
  TC: m('Tourism services', 'Fish', 'Salt', 'Lobster', 'Financial services exports', 'Construction materials', 'Re-exports'),
  TJ: m('Aluminium', 'Electricity', 'Cotton', 'Precious-metal ore', 'Vegetables', 'Dried fruits', 'Textiles'),
  TM: m('Natural gas', 'Crude petroleum', 'Refined petroleum', 'Cotton', 'Wheat', 'Polypropylene', 'Electricity'),
  TO: m('Fish', 'Squash', 'Vanilla', 'Coconut products', 'Tourism services', 'Root crops', 'Handicrafts'),
  TT: m('Liquified natural gas', 'Ammonia', 'Methanol', 'Iron and steel', 'Petroleum products', 'Chemicals', 'Cocoa'),
  TV: m('Fish', 'Copra', 'Tourism services', 'Postage stamps', 'Handicrafts', 'Passenger ships', 'Re-exports'),
  UA: m('Corn', 'Wheat', 'Sunflower oil', 'Iron ore', 'Steel', 'Rapeseed', 'Poultry meat'),
  UY: m('Beef', 'Soybeans', 'Cellulose pulp', 'Rice', 'Wool', 'Dairy products', 'Wood'),
  UZ: m('Gold', 'Natural gas', 'Cotton', 'Copper', 'Textiles', 'Fruits', 'Uranium'),
  VC: m('Bananas', 'Tourism services', 'Arrowroot starch', 'Fish', 'Rum', 'Manufactured goods', 'Passenger ships'),
  VE: m('Crude petroleum', 'Refined petroleum', 'Gold', 'Iron ore', 'Aluminium', 'Soybeans', 'Corn'),
  VG: m('Tourism services', 'Fish', 'Rum', 'Sand and gravel', 'Passenger ships', 'Financial services exports', 'Construction materials'),
  VU: m('Beef', 'Copra', 'Kava', 'Tourism services', 'Fish', 'Cocoa', 'Timber'),
  WS: m('Fish', 'Coconut oil', 'Automotive parts', 'Noni juice', 'Tourism services', 'Kava', 'Beer'),
}
