import type { AuMemberIsoCode } from './auMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

// ---- Regional industrial-property venue (OAPI) shared across Francophone members ----

/**
 * OAPI — unified trademarks and patents for seventeen AU members (BJ, BF, CM, CF, TD, KM,
 * CG, CI, GQ, GA, GN, GW, ML, MR, NE, SN, TG). Copyright remains with each national office
 * per the WIPO directory. No documented public REST API — e-services portal for filings.
 */
const OAPI_TRADEMARKS = ip(
  'trademarks',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

const OAPI_PATENTS = ip(
  'patents',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

function oapiMember(copyright: IntellectualPropertyDepartment): IntellectualPropertyDepartmentsRoster {
  return roster(copyright, OAPI_TRADEMARKS, OAPI_PATENTS)
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for African Union member
 * states (informational; verify URLs, handles, forms portals, and API bases before production).
 * Pattern:
 *   - OAPI members: national copyright office (WIPO directory name) + OAPI for trademarks and patents.
 *   - ARIPO member states: national competent office per kind (WIPO / ARIPO member pages); regional
 *     ARIPO e-filing (https://eservice.aripo.org/) may supplement national routes — verify locally.
 *   - Other members: full national offices for copyright, trademarks, and patents.
 *   - EH (Sahrawi Republic): placeholder roster when no documented national IP office exists.
 * `apiEndpoint` is almost always empty — few African IP offices publish open REST APIs.
 * Verify periodically against https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const AU_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  AuMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AO: roster(
    ip(
      'copyright',
      'Instituto Angolano da Propriedade Intelectual (IAPI) — copyright',
      'https://www.iapi.gov.ao',
      'geral@iapi.gov.ao',
      '',
      '',
      'https://www.iapi.gov.ao',
    ),
    ip(
      'trademarks',
      'Instituto Angolano da Propriedade Intelectual (IAPI)',
      'https://www.iapi.gov.ao',
      'geral@iapi.gov.ao',
      '',
      '',
      'https://www.iapi.gov.ao',
    ),
    ip(
      'patents',
      'Instituto Angolano da Propriedade Intelectual (IAPI)',
      'https://www.iapi.gov.ao',
      'geral@iapi.gov.ao',
      '',
      '',
      'https://www.iapi.gov.ao',
    ),
  ),
  BF: oapiMember(
    ip(
      'copyright',
      'Office Burkinabè des Droits d\'Auteur (OBDA)',
      'https://www.obda.bf',
      'obda@obda.bf',
      '',
      '',
      'https://www.obda.bf',
    ),
  ),
  BI: roster(
    ip(
      'copyright',
      'Office Burundais des Droits d\'Auteur (OBDA)',
      'https://www.obda.bi',
      '',
      '',
      '',
      'https://www.obda.bi',
    ),
    ip(
      'trademarks',
      'Office Burundais de la Propriété Intellectuelle (OBPI)',
      'https://www.obpi.bi',
      '',
      '',
      '',
      'https://www.obpi.bi',
    ),
    ip(
      'patents',
      'Office Burundais de la Propriété Intellectuelle (OBPI)',
      'https://www.obpi.bi',
      '',
      '',
      '',
      'https://www.obpi.bi',
    ),
  ),
  BJ: oapiMember(
    ip(
      'copyright',
      'Bureau Béninois du Droit d\'Auteur et des Droits Voisins (BURIDA)',
      'https://www.burida.bj',
      'contact@burida.bj',
      '',
      '',
      'https://www.burida.bj',
    ),
  ),
  BW: roster(
    ip(
      'copyright',
      'Copyright Society of Botswana (COSBOTS)',
      'https://www.cosbots.org.bw',
      'info@cosbots.org.bw',
      '',
      'https://www.linkedin.com/company/cosbots/',
      'https://www.cosbots.org.bw',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Authority (CIPA)',
      'https://www.cipa.co.bw',
      'info@cipa.co.bw',
      'https://x.com/CIPABotswana',
      'https://www.linkedin.com/company/cipa-botswana/',
      'https://www.cipa.co.bw',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Authority (CIPA)',
      'https://www.cipa.co.bw',
      'info@cipa.co.bw',
      'https://x.com/CIPABotswana',
      'https://www.linkedin.com/company/cipa-botswana/',
      'https://www.cipa.co.bw',
    ),
  ),
  CD: roster(
    ip(
      'copyright',
      'Office Congolais des Droits d\'Auteur (OCADA)',
      'https://www.ocada.cd',
      '',
      '',
      '',
      'https://www.ocada.cd',
    ),
    ip(
      'trademarks',
      'Office Congolais de la Propriété Intellectuelle (OCPI)',
      'https://www.ocpi.cd',
      'info@ocpi.cd',
      '',
      '',
      'https://www.ocpi.cd',
    ),
    ip(
      'patents',
      'Office Congolais de la Propriété Intellectuelle (OCPI)',
      'https://www.ocpi.cd',
      'info@ocpi.cd',
      '',
      '',
      'https://www.ocpi.cd',
    ),
  ),
  CF: oapiMember(
    ip(
      'copyright',
      'Office Centrafricain du Droit d\'Auteur (OCADA)',
      'https://www.ocada-rca.cf',
      '',
      '',
      '',
      'https://www.ocada-rca.cf',
    ),
  ),
  CG: oapiMember(
    ip(
      'copyright',
      'Office Congolais du Droit d\'Auteur (OCAD)',
      'https://www.ocad.cg',
      '',
      '',
      '',
      'https://www.ocad.cg',
    ),
  ),
  CI: oapiMember(
    ip(
      'copyright',
      'Bureau Ivoirien du Droit d\'Auteur (BURIDA)',
      'https://www.burida.ci',
      'contact@burida.ci',
      '',
      '',
      'https://www.burida.ci',
    ),
  ),
  CM: oapiMember(
    ip(
      'copyright',
      'Cameroon Copyright Office (Ministry of Arts and Culture)',
      'https://www.minac.gov.cm',
      '',
      '',
      '',
      'https://www.minac.gov.cm',
    ),
  ),
  CV: roster(
    ip(
      'copyright',
      'Instituto Cabo-verdiano do Livro e do Disco (ICLD)',
      'https://www.icld.cv',
      'icld@icld.cv',
      '',
      '',
      'https://www.icld.cv',
    ),
    ip(
      'trademarks',
      'Instituto Nacional da Propriedade Intelectual (INPI Cabo Verde)',
      'https://www.inpi.cv',
      'inpi@inpi.cv',
      '',
      '',
      'https://www.inpi.cv',
    ),
    ip(
      'patents',
      'Instituto Nacional da Propriedade Intelectual (INPI Cabo Verde)',
      'https://www.inpi.cv',
      'inpi@inpi.cv',
      '',
      '',
      'https://www.inpi.cv',
    ),
  ),
  DJ: roster(
    ip(
      'copyright',
      'Ministry of Culture and Communication — copyright (Djibouti)',
      'https://www.communication.gouv.dj',
      '',
      '',
      '',
      'https://www.communication.gouv.dj',
    ),
    ip(
      'trademarks',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
    ip(
      'patents',
      'Ministry of Economy and Finance — industrial property (Djibouti)',
      'https://www.finances.gouv.dj',
      '',
      '',
      '',
      'https://www.finances.gouv.dj',
    ),
  ),
  DZ: roster(
    ip(
      'copyright',
      'Office Algérien du Droit d\'Auteur et des Droits Voisins (OADA)',
      'https://www.oada.dz',
      'contact@oada.dz',
      '',
      '',
      'https://www.oada.dz',
    ),
    ip(
      'trademarks',
      'Institut National de la Propriété Industrielle (INAPI)',
      'https://www.inapi.dz',
      'contact@inapi.dz',
      '',
      '',
      'https://www.inapi.dz',
    ),
    ip(
      'patents',
      'Institut National de la Propriété Industrielle (INAPI)',
      'https://www.inapi.dz',
      'contact@inapi.dz',
      '',
      '',
      'https://www.inapi.dz',
    ),
  ),
  EG: roster(
    ip(
      'copyright',
      'Egyptian Copyright Office (Ministry of Culture)',
      'https://www.culture.gov.eg',
      '',
      '',
      '',
      'https://www.culture.gov.eg',
    ),
    ip(
      'trademarks',
      'Egyptian Patent Office — Trademarks Department',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
    ip(
      'patents',
      'Egyptian Patent Office',
      'https://www.egyptpo.gov.eg',
      'info@egyptpo.gov.eg',
      '',
      '',
      'https://www.egyptpo.gov.eg',
    ),
  ),
  EH: roster(
    ip('copyright', 'No documented national IP office', '', '', '', '', '', ''),
    ip('trademarks', 'No documented national IP office', '', '', '', '', '', ''),
    ip('patents', 'No documented national IP office', '', '', '', '', '', ''),
  ),
  ER: roster(
    ip(
      'copyright',
      'Ministry of Information — copyright (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
    ip(
      'trademarks',
      'Ministry of Trade and Industry — industrial property (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
    ip(
      'patents',
      'Ministry of Trade and Industry — industrial property (Eritrea; verify locally)',
      '',
      '',
      '',
      '',
      '',
    ),
  ),
  ET: roster(
    ip(
      'copyright',
      'Ethiopian Intellectual Property Authority — copyright',
      'https://www.eipa.gov.et',
      'info@eipa.gov.et',
      '',
      '',
      'https://www.eipa.gov.et',
    ),
    ip(
      'trademarks',
      'Ethiopian Intellectual Property Authority (EIPA)',
      'https://www.eipa.gov.et',
      'info@eipa.gov.et',
      '',
      '',
      'https://www.eipa.gov.et',
    ),
    ip(
      'patents',
      'Ethiopian Intellectual Property Authority (EIPA)',
      'https://www.eipa.gov.et',
      'info@eipa.gov.et',
      '',
      '',
      'https://www.eipa.gov.et',
    ),
  ),
  GA: oapiMember(
    ip(
      'copyright',
      'Bureau Gabonais du Droit d\'Auteur (BGDA)',
      'https://www.bgda.ga',
      '',
      '',
      '',
      'https://www.bgda.ga',
    ),
  ),
  GH: roster(
    ip(
      'copyright',
      'Copyright Office, Registrar General\'s Department',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      '',
      'https://rgd.gov.gh',
    ),
    ip(
      'trademarks',
      'Registrar General\'s Department — Industrial Property',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      'https://www.linkedin.com/company/registrar-generals-department-ghana/',
      'https://rgd.gov.gh',
    ),
    ip(
      'patents',
      'Registrar General\'s Department — Industrial Property',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      'https://www.linkedin.com/company/registrar-generals-department-ghana/',
      'https://rgd.gov.gh',
    ),
  ),
  GM: roster(
    ip(
      'copyright',
      'National Centre for Arts and Culture (NCAC) — copyright',
      'https://www.ncac.gm',
      'info@ncac.gm',
      '',
      '',
      'https://www.ncac.gm',
    ),
    ip(
      'trademarks',
      'Registrar General\'s Department — Industrial Property (The Gambia)',
      'https://www.moj.gov.gm',
      '',
      '',
      '',
      'https://www.moj.gov.gm',
    ),
    ip(
      'patents',
      'Registrar General\'s Department — Industrial Property (The Gambia)',
      'https://www.moj.gov.gm',
      '',
      '',
      '',
      'https://www.moj.gov.gm',
    ),
  ),
  GN: oapiMember(
    ip(
      'copyright',
      'Bureau Guinéen du Droit d\'Auteur (BGDA)',
      'https://www.bgda.gn',
      '',
      '',
      '',
      'https://www.bgda.gn',
    ),
  ),
  GQ: oapiMember(
    ip(
      'copyright',
      'Office of Copyright and Related Rights (Equatorial Guinea)',
      'https://www.guineaecuatorialpress.com',
      '',
      '',
      '',
      'https://www.guineaecuatorialpress.com',
    ),
  ),
  GW: oapiMember(
    ip(
      'copyright',
      'Instituto Nacional de Direitos de Autor (INDA — Guinea-Bissau)',
      'https://www.inda.gw',
      '',
      '',
      '',
      'https://www.inda.gw',
    ),
  ),
  KE: roster(
    ip(
      'copyright',
      'Kenya Copyright Board (KECOBO)',
      'https://www.copyright.go.ke',
      'info@copyright.go.ke',
      'https://x.com/KECOBO',
      'https://www.linkedin.com/company/kenya-copyright-board/',
      'https://www.copyright.go.ke',
    ),
    ip(
      'trademarks',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
    ip(
      'patents',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
  ),
  KM: oapiMember(
    ip(
      'copyright',
      'Centre Comorien du Droit d\'Auteur et des Droits Voisins',
      'https://www.beit-salam.km',
      '',
      '',
      '',
      'https://www.beit-salam.km',
    ),
  ),
  LR: roster(
    ip(
      'copyright',
      'Liberia Copyright Office (Ministry of Commerce and Industry)',
      'https://www.moci.gov.lr',
      '',
      '',
      '',
      'https://www.moci.gov.lr',
    ),
    ip(
      'trademarks',
      'Liberia Intellectual Property Office (LIPO)',
      'https://www.lipo.gov.lr',
      'info@lipo.gov.lr',
      '',
      '',
      'https://www.lipo.gov.lr',
    ),
    ip(
      'patents',
      'Liberia Intellectual Property Office (LIPO)',
      'https://www.lipo.gov.lr',
      'info@lipo.gov.lr',
      '',
      '',
      'https://www.lipo.gov.lr',
    ),
  ),
  LS: roster(
    ip(
      'copyright',
      'Copyright Society of Lesotho (COSOLE)',
      'https://www.cosole.org.ls',
      '',
      '',
      '',
      'https://www.cosole.org.ls',
    ),
    ip(
      'trademarks',
      'Registrar General — Industrial Property (Lesotho)',
      'https://www.gov.ls',
      '',
      '',
      '',
      'https://www.gov.ls',
    ),
    ip(
      'patents',
      'Registrar General — Industrial Property (Lesotho)',
      'https://www.gov.ls',
      '',
      '',
      '',
      'https://www.gov.ls',
    ),
  ),
  LY: roster(
    ip(
      'copyright',
      'Libyan National Centre for Culture and Arts — copyright',
      'https://www.culture.gov.ly',
      '',
      '',
      '',
      'https://www.culture.gov.ly',
    ),
    ip(
      'trademarks',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
    ip(
      'patents',
      'Libyan Trademark and Patent Office (verify locally)',
      'https://www.mti.gov.ly',
      '',
      '',
      '',
      'https://www.mti.gov.ly',
    ),
  ),
  MA: roster(
    ip(
      'copyright',
      'Bureau Marocain des Droits d\'Auteur (BMDA)',
      'https://www.bmda.org',
      'contact@bmda.org',
      '',
      '',
      'https://www.bmda.org',
    ),
    ip(
      'trademarks',
      'Office Marocain de la Propriété Industrielle et Commerciale (OMPIC)',
      'https://www.ompic.ma',
      'contact@ompic.ma',
      '',
      'https://www.linkedin.com/company/ompic/',
      'https://www.ompic.ma',
    ),
    ip(
      'patents',
      'Office Marocain de la Propriété Industrielle et Commerciale (OMPIC)',
      'https://www.ompic.ma',
      'contact@ompic.ma',
      '',
      'https://www.linkedin.com/company/ompic/',
      'https://www.ompic.ma',
    ),
  ),
  MG: roster(
    ip(
      'copyright',
      'Office Malgache des Droits d\'Auteur (OMDA)',
      'https://www.omda.mg',
      '',
      '',
      '',
      'https://www.omda.mg',
    ),
    ip(
      'trademarks',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
    ip(
      'patents',
      'Office Malgache de la Propriété Industrielle (OMAPI)',
      'https://www.omapi.mg',
      'contact@omapi.mg',
      '',
      '',
      'https://www.omapi.mg',
    ),
  ),
  ML: oapiMember(
    ip(
      'copyright',
      'Bureau Malien du Droit d\'Auteur (BUMADA)',
      'https://www.bumada.ml',
      '',
      '',
      '',
      'https://www.bumada.ml',
    ),
  ),
  MR: oapiMember(
    ip(
      'copyright',
      'Bureau Mauritanien du Droit d\'Auteur (BUMDA)',
      'https://www.bumda.mr',
      '',
      '',
      '',
      'https://www.bumda.mr',
    ),
  ),
  MU: roster(
    ip(
      'copyright',
      'Mauritius Society of Authors (MASA)',
      'https://www.masa.mu',
      'info@masa.mu',
      '',
      '',
      'https://www.masa.mu',
    ),
    ip(
      'trademarks',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
    ip(
      'patents',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
  ),
  MW: roster(
    ip(
      'copyright',
      'Copyright Society of Malawi (COSOMA)',
      'https://www.cosoma.mw',
      'info@cosoma.mw',
      '',
      '',
      'https://www.cosoma.mw',
    ),
    ip(
      'trademarks',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
    ip(
      'patents',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
  ),
  MZ: roster(
    ip(
      'copyright',
      'Instituto Nacional da Propriedade Intelectual (IPI) — copyright',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'trademarks',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'patents',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
  ),
  NA: roster(
    ip(
      'copyright',
      'Namibian Society for Composers and Authors of Music (NAMCOS)',
      'https://www.namcos.org.na',
      'info@namcos.org.na',
      '',
      '',
      'https://www.namcos.org.na',
    ),
    ip(
      'trademarks',
      'Business and Intellectual Property Authority (BIPA)',
      'https://www.bipa.na',
      'info@bipa.na',
      '',
      'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
      'https://www.bipa.na',
    ),
    ip(
      'patents',
      'Business and Intellectual Property Authority (BIPA)',
      'https://www.bipa.na',
      'info@bipa.na',
      '',
      'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
      'https://www.bipa.na',
    ),
  ),
  NE: oapiMember(
    ip(
      'copyright',
      'Bureau Nigérien du Droit d\'Auteur (BUNDA)',
      'https://www.bunda.ne',
      '',
      '',
      '',
      'https://www.bunda.ne',
    ),
  ),
  NG: roster(
    ip(
      'copyright',
      'Nigerian Copyright Commission (NCC)',
      'https://www.copyright.gov.ng',
      'info@copyright.gov.ng',
      'https://x.com/NCC_NG',
      'https://www.linkedin.com/company/nigerian-copyright-commission/',
      'https://www.copyright.gov.ng',
    ),
    ip(
      'trademarks',
      'Trademarks, Patents and Designs Registry (Federal Ministry of Industry, Trade and Investment)',
      'https://www.fmiti.gov.ng',
      'info@fmiti.gov.ng',
      '',
      '',
      'https://www.fmiti.gov.ng',
    ),
    ip(
      'patents',
      'Trademarks, Patents and Designs Registry (Federal Ministry of Industry, Trade and Investment)',
      'https://www.fmiti.gov.ng',
      'info@fmiti.gov.ng',
      '',
      '',
      'https://www.fmiti.gov.ng',
    ),
  ),
  RW: roster(
    ip(
      'copyright',
      'Rwanda Society of Authors (RSAU)',
      'https://www.rsau.rw',
      'info@rsau.rw',
      '',
      '',
      'https://www.rsau.rw',
    ),
    ip(
      'trademarks',
      'Rwanda Development Board — Intellectual Property',
      'https://www.rdb.rw',
      'info@rdb.rw',
      'https://x.com/RwandaDevBoard',
      'https://www.linkedin.com/company/rwanda-development-board/',
      'https://www.rdb.rw',
    ),
    ip(
      'patents',
      'Rwanda Development Board — Intellectual Property',
      'https://www.rdb.rw',
      'info@rdb.rw',
      'https://x.com/RwandaDevBoard',
      'https://www.linkedin.com/company/rwanda-development-board/',
      'https://www.rdb.rw',
    ),
  ),
  SC: roster(
    ip(
      'copyright',
      'Seychelles Copyright Office (Ministry of Finance, National Planning and Trade)',
      'https://www.finance.gov.sc',
      '',
      '',
      '',
      'https://www.finance.gov.sc',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
    ip(
      'patents',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
  ),
  SD: roster(
    ip(
      'copyright',
      'Sudan Copyright Office (Ministry of Culture)',
      'https://www.moc.gov.sd',
      '',
      '',
      '',
      'https://www.moc.gov.sd',
    ),
    ip(
      'trademarks',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
    ip(
      'patents',
      'Registrar General of Patents, Designs and Trademarks (Sudan)',
      'https://www.mot.gov.sd',
      '',
      '',
      '',
      'https://www.mot.gov.sd',
    ),
  ),
  SL: roster(
    ip(
      'copyright',
      'Sierra Leone Copyright Office',
      'https://www.mic.gov.sl',
      '',
      '',
      '',
      'https://www.mic.gov.sl',
    ),
    ip(
      'trademarks',
      'National Intellectual Property Office of Sierra Leone (NIPOSL)',
      'https://www.niposl.gov.sl',
      'info@niposl.gov.sl',
      '',
      '',
      'https://www.niposl.gov.sl',
    ),
    ip(
      'patents',
      'National Intellectual Property Office of Sierra Leone (NIPOSL)',
      'https://www.niposl.gov.sl',
      'info@niposl.gov.sl',
      '',
      '',
      'https://www.niposl.gov.sl',
    ),
  ),
  SN: oapiMember(
    ip(
      'copyright',
      'Bureau Sénégalais du Droit d\'Auteur (BSDA)',
      'https://www.bsda.sn',
      'contact@bsda.sn',
      '',
      '',
      'https://www.bsda.sn',
    ),
  ),
  SO: roster(
    ip(
      'copyright',
      'Ministry of Information, Culture and Tourism — copyright (Somalia)',
      'https://www.mict.gov.so',
      '',
      '',
      '',
      'https://www.mict.gov.so',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
    ip(
      'patents',
      'Ministry of Commerce and Industry — industrial property (Somalia)',
      'https://www.moci.gov.so',
      '',
      '',
      '',
      'https://www.moci.gov.so',
    ),
  ),
  SS: roster(
    ip(
      'copyright',
      'Ministry of Culture, Museums and National Heritage — copyright (South Sudan)',
      'https://www.mc.gov.ss',
      '',
      '',
      '',
      'https://www.mc.gov.ss',
    ),
    ip(
      'trademarks',
      'Ministry of Justice — industrial property (South Sudan; verify locally)',
      'https://www.moj.gov.ss',
      '',
      '',
      '',
      'https://www.moj.gov.ss',
    ),
    ip(
      'patents',
      'Ministry of Justice — industrial property (South Sudan; verify locally)',
      'https://www.moj.gov.ss',
      '',
      '',
      '',
      'https://www.moj.gov.ss',
    ),
  ),
  ST: roster(
    ip(
      'copyright',
      'Instituto Nacional do Livro e do Disco (INLD — São Tomé e Príncipe)',
      'https://www.inld.st',
      '',
      '',
      '',
      'https://www.inld.st',
    ),
    ip(
      'trademarks',
      'Instituto Nacional da Propriedade Industrial (INPI STP)',
      'https://www.inpi.st',
      'inpi@inpi.st',
      '',
      '',
      'https://www.inpi.st',
    ),
    ip(
      'patents',
      'Instituto Nacional da Propriedade Industrial (INPI STP)',
      'https://www.inpi.st',
      'inpi@inpi.st',
      '',
      '',
      'https://www.inpi.st',
    ),
  ),
  SZ: roster(
    ip(
      'copyright',
      'Copyright Society of Eswatini (COSOES)',
      'https://www.cosoes.org.sz',
      '',
      '',
      '',
      'https://www.cosoes.org.sz',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
  ),
  TD: oapiMember(
    ip(
      'copyright',
      'Agence Tchadienne du Droit d\'Auteur (ATCHADA)',
      'https://www.atchada.td',
      '',
      '',
      '',
      'https://www.atchada.td',
    ),
  ),
  TG: oapiMember(
    ip(
      'copyright',
      'Office Togolais des Droits d\'Auteur et des Droits Voisins (OTDAV)',
      'https://www.otdav.tg',
      '',
      '',
      '',
      'https://www.otdav.tg',
    ),
  ),
  TN: roster(
    ip(
      'copyright',
      'Office National du Droit d\'Auteur (ONDA)',
      'https://www.onda.tn',
      'contact@onda.tn',
      '',
      '',
      'https://www.onda.tn',
    ),
    ip(
      'trademarks',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
    ip(
      'patents',
      'Institut National de la Normalisation et de la Propriété Industrielle (INNORPI)',
      'https://www.innorpi.tn',
      'contact@innorpi.tn',
      '',
      '',
      'https://www.innorpi.tn',
    ),
  ),
  TZ: roster(
    ip(
      'copyright',
      'Copyright Society of Tanzania (COSOTA)',
      'https://www.cosota.go.tz',
      'info@cosota.go.tz',
      '',
      '',
      'https://www.cosota.go.tz',
    ),
    ip(
      'trademarks',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
    ip(
      'patents',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
  ),
  UG: roster(
    ip(
      'copyright',
      'Uganda Registration Services Bureau — Copyright Registry',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
    ip(
      'trademarks',
      'Uganda Registration Services Bureau (URSB) — Industrial Property',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
    ip(
      'patents',
      'Uganda Registration Services Bureau (URSB) — Industrial Property',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
  ),
  ZA: roster(
    ip(
      'copyright',
      'Companies and Intellectual Property Commission (CIPC) — Copyright Tribunal liaison',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
  ),
  ZM: roster(
    ip(
      'copyright',
      'Copyright Society of Zambia (COSOZA)',
      'https://www.cosoza.org.zm',
      'info@cosoza.org.zm',
      '',
      '',
      'https://www.cosoza.org.zm',
    ),
    ip(
      'trademarks',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
    ip(
      'patents',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
  ),
  ZW: roster(
    ip(
      'copyright',
      'Zimbabwe Intellectual Property Office (ZIPO) — copyright',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
    ip(
      'trademarks',
      'Zimbabwe Intellectual Property Office (ZIPO)',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
    ip(
      'patents',
      'Zimbabwe Intellectual Property Office (ZIPO)',
      'https://www.zipo.co.zw',
      'info@zipo.co.zw',
      '',
      '',
      'https://www.zipo.co.zw',
    ),
  ),
}
