import type { AuMemberIsoCode } from './auMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2
 * (informational; verify against USGS Mineral Commodity Summaries and UN Comtrade periodically).
 * Petroleum / natural gas exporters are tagged with `Carbon (C)` and `Hydrogen (H)` where applicable.
 */
export const AU_MAIN_EXPORTED_ELEMENTS: Record<AuMemberIsoCode, MainExportedElements> = {
  AO: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Gold (Au)',
    'Manganese (Mn)',
    'Phosphorus (P)',
  ),
  BF: e(
    'Gold (Au)',
    'Zinc (Zn)',
    'Manganese (Mn)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Lead (Pb)',
    'Phosphorus (P)',
  ),
  BI: e(
    'Tantalum (Ta)',
    'Niobium (Nb)',
    'Gold (Au)',
    'Tungsten (W)',
    'Tin (Sn)',
    'Nickel (Ni)',
    'Vanadium (V)',
  ),
  BJ: e(
    'Iron (Fe)',
    'Gold (Au)',
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Magnesium (Mg)',
    'Aluminum (Al)',
    'Silicon (Si)',
  ),
  BW: e(
    'Carbon (C)',
    'Copper (Cu)',
    'Nickel (Ni)',
    'Gold (Au)',
    'Silver (Ag)',
    'Uranium (U)',
    'Sodium (Na)',
  ),
  CD: e(
    'Copper (Cu)',
    'Cobalt (Co)',
    'Tantalum (Ta)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Carbon (C)',
    'Gold (Au)',
  ),
  CF: e(
    'Carbon (C)',
    'Gold (Au)',
    'Uranium (U)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Manganese (Mn)',
    'Tin (Sn)',
  ),
  CG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Potassium (K)',
    'Phosphorus (P)',
    'Copper (Cu)',
    'Lead (Pb)',
  ),
  CI: e(
    'Gold (Au)',
    'Nickel (Ni)',
    'Manganese (Mn)',
    'Iron (Fe)',
    'Tantalum (Ta)',
    'Copper (Cu)',
    'Cobalt (Co)',
  ),
  CM: e(
    'Aluminum (Al)',
    'Gold (Au)',
    'Iron (Fe)',
    'Uranium (U)',
    'Carbon (C)',
    'Manganese (Mn)',
    'Nickel (Ni)',
  ),
  CV: e(
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Magnesium (Mg)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Aluminum (Al)',
  ),
  DJ: e(
    'Sodium (Na)',
    'Calcium (Ca)',
    'Magnesium (Mg)',
    'Silicon (Si)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  DZ: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Helium (He)',
    'Iron (Fe)',
    'Phosphorus (P)',
    'Zinc (Zn)',
    'Mercury (Hg)',
  ),
  EG: e(
    'Gold (Au)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Titanium (Ti)',
    'Zinc (Zn)',
    'Lead (Pb)',
  ),
  EH: e(
    'Phosphorus (P)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Uranium (U)',
    'Vanadium (V)',
    'Titanium (Ti)',
    'Manganese (Mn)',
  ),
  ER: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Silver (Ag)',
    'Potassium (K)',
    'Iron (Fe)',
    'Sulfur (S)',
  ),
  ET: e(
    'Gold (Au)',
    'Tantalum (Ta)',
    'Platinum (Pt)',
    'Potassium (K)',
    'Phosphorus (P)',
    'Niobium (Nb)',
    'Iron (Fe)',
  ),
  GA: e(
    'Manganese (Mn)',
    'Uranium (U)',
    'Iron (Fe)',
    'Gold (Au)',
    'Niobium (Nb)',
    'Titanium (Ti)',
    'Carbon (C)',
  ),
  GH: e(
    'Gold (Au)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Carbon (C)',
    'Silver (Ag)',
    'Copper (Cu)',
  ),
  GM: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Iron (Fe)',
    'Tin (Sn)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Manganese (Mn)',
  ),
  GN: e(
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Carbon (C)',
    'Uranium (U)',
    'Nickel (Ni)',
    'Copper (Cu)',
  ),
  GQ: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Gold (Au)',
    'Uranium (U)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Titanium (Ti)',
  ),
  GW: e(
    'Phosphorus (P)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Titanium (Ti)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  KE: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Sodium (Na)',
    'Fluorine (F)',
    'Gold (Au)',
    'Iron (Fe)',
    'Niobium (Nb)',
  ),
  KM: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Magnesium (Mg)',
    'Sodium (Na)',
  ),
  LR: e(
    'Iron (Fe)',
    'Gold (Au)',
    'Carbon (C)',
    'Aluminum (Al)',
    'Titanium (Ti)',
    'Manganese (Mn)',
    'Chromium (Cr)',
  ),
  LS: e(
    'Carbon (C)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  LY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Iron (Fe)',
    'Potassium (K)',
    'Phosphorus (P)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  MA: e(
    'Phosphorus (P)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Copper (Cu)',
    'Cobalt (Co)',
    'Manganese (Mn)',
    'Silver (Ag)',
  ),
  MG: e(
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Chromium (Cr)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Gold (Au)',
    'Uranium (U)',
  ),
  ML: e(
    'Gold (Au)',
    'Phosphorus (P)',
    'Lithium (Li)',
    'Uranium (U)',
    'Manganese (Mn)',
    'Iron (Fe)',
    'Copper (Cu)',
  ),
  MR: e(
    'Iron (Fe)',
    'Gold (Au)',
    'Copper (Cu)',
    'Phosphorus (P)',
    'Uranium (U)',
    'Manganese (Mn)',
    'Sodium (Na)',
  ),
  MU: e(
    'Sodium (Na)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Magnesium (Mg)',
  ),
  MW: e(
    'Uranium (U)',
    'Niobium (Nb)',
    'Tantalum (Ta)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Phosphorus (P)',
    'Calcium (Ca)',
  ),
  MZ: e(
    'Aluminum (Al)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Tantalum (Ta)',
    'Gold (Au)',
    'Carbon (C)',
    'Beryllium (Be)',
  ),
  NA: e(
    'Uranium (U)',
    'Carbon (C)',
    'Copper (Cu)',
    'Gold (Au)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Lithium (Li)',
  ),
  NE: e(
    'Uranium (U)',
    'Gold (Au)',
    'Tin (Sn)',
    'Molybdenum (Mo)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Carbon (C)',
  ),
  NG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Niobium (Nb)',
    'Tantalum (Ta)',
    'Lead (Pb)',
    'Zinc (Zn)',
  ),
  RW: e(
    'Tantalum (Ta)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Niobium (Nb)',
    'Gold (Au)',
    'Beryllium (Be)',
    'Lithium (Li)',
  ),
  SC: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Magnesium (Mg)',
    'Aluminum (Al)',
    'Sulfur (S)',
  ),
  SD: e(
    'Gold (Au)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Manganese (Mn)',
    'Zinc (Zn)',
    'Chromium (Cr)',
    'Silver (Ag)',
  ),
  SL: e(
    'Iron (Fe)',
    'Carbon (C)',
    'Gold (Au)',
    'Titanium (Ti)',
    'Aluminum (Al)',
    'Zirconium (Zr)',
    'Chromium (Cr)',
  ),
  SN: e(
    'Phosphorus (P)',
    'Gold (Au)',
    'Zirconium (Zr)',
    'Titanium (Ti)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Calcium (Ca)',
  ),
  SO: e(
    'Uranium (U)',
    'Iron (Fe)',
    'Titanium (Ti)',
    'Copper (Cu)',
    'Gold (Au)',
    'Tin (Sn)',
    'Tantalum (Ta)',
  ),
  SS: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Gold (Au)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Chromium (Cr)',
  ),
  ST: e(
    'Silicon (Si)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Magnesium (Mg)',
    'Aluminum (Al)',
    'Sodium (Na)',
  ),
  SZ: e(
    'Iron (Fe)',
    'Gold (Au)',
    'Carbon (C)',
    'Manganese (Mn)',
    'Tin (Sn)',
    'Magnesium (Mg)',
    'Calcium (Ca)',
  ),
  TD: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sodium (Na)',
    'Gold (Au)',
    'Uranium (U)',
    'Tungsten (W)',
    'Iron (Fe)',
  ),
  TG: e(
    'Phosphorus (P)',
    'Manganese (Mn)',
    'Iron (Fe)',
    'Gold (Au)',
    'Calcium (Ca)',
    'Chromium (Cr)',
    'Nickel (Ni)',
  ),
  TN: e(
    'Phosphorus (P)',
    'Iron (Fe)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Fluorine (F)',
    'Mercury (Hg)',
    'Calcium (Ca)',
  ),
  TZ: e(
    'Gold (Au)',
    'Nickel (Ni)',
    'Copper (Cu)',
    'Carbon (C)',
    'Tantalum (Ta)',
    'Tin (Sn)',
    'Helium (He)',
  ),
  UG: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Cobalt (Co)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Iron (Fe)',
    'Niobium (Nb)',
  ),
  ZA: e(
    'Platinum (Pt)',
    'Gold (Au)',
    'Carbon (C)',
    'Chromium (Cr)',
    'Manganese (Mn)',
    'Vanadium (V)',
    'Iron (Fe)',
  ),
  ZM: e(
    'Copper (Cu)',
    'Cobalt (Co)',
    'Silver (Ag)',
    'Gold (Au)',
    'Lead (Pb)',
    'Zinc (Zn)',
    'Manganese (Mn)',
  ),
  ZW: e(
    'Platinum (Pt)',
    'Gold (Au)',
    'Carbon (C)',
    'Chromium (Cr)',
    'Nickel (Ni)',
    'Lithium (Li)',
    'Copper (Cu)',
  ),
}
