import type { AuMemberIsoCode } from './auMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const AU_MAIN_EXPORT_COMMODITIES: Record<AuMemberIsoCode, MainExportCommodities> = {
  AO: m(
    'Crude petroleum',
    'Diamonds',
    'Refined petroleum',
    'Liquified natural gas',
    'Ships',
    'Iron ore',
    'Copper ore',
  ),
  BF: m(
    'Gold',
    'Cotton',
    'Oil seeds',
    'Zinc ore',
    'Sesame seeds',
    'Fruits and nuts',
    'Livestock',
  ),
  BI: m(
    'Coffee',
    'Gold',
    'Tea',
    'Niobium and tantalum ore',
    'Cobalt',
    'Hides and skins',
    'Wheat flour',
  ),
  BJ: m(
    'Cotton',
    'Gold',
    'Cashew nuts',
    'Refined petroleum',
    'Palm oil',
    'Soybeans',
    'Maize',
  ),
  BW: m(
    'Diamonds',
    'Copper ore',
    'Beef',
    'Carbonates',
    'Live cattle',
    'Machinery parts',
    'Salt',
  ),
  CD: m(
    'Copper',
    'Cobalt',
    'Gold',
    'Crude petroleum',
    'Diamonds',
    'Copper ore',
    'Refined copper',
  ),
  CF: m(
    'Gold',
    'Diamonds',
    'Timber',
    'Cotton',
    'Hides and skins',
    'Sesame seeds',
    'Coffee',
  ),
  CG: m(
    'Crude petroleum',
    'Timber',
    'Diamonds',
    'Refined petroleum',
    'Copper',
    'Gold',
    'Plywood',
  ),
  CI: m(
    'Cocoa',
    'Gold',
    'Refined petroleum',
    'Rubber',
    'Cashew nuts',
    'Cotton',
    'Palm oil',
  ),
  CM: m(
    'Crude petroleum',
    'Timber',
    'Cocoa',
    'Cotton',
    'Aluminum',
    'Coffee',
    'Bananas',
  ),
  CV: m(
    'Fish',
    'Footwear',
    'Garments',
    'Petroleum products',
    'Electronics',
    'Plastic products',
    'Beverages',
  ),
  DJ: m(
    'Live animals',
    'Coffee',
    'Hides and skins',
    'Salt',
    'Scrap metal',
    'Re-exported goods',
    'Petroleum re-exports',
  ),
  DZ: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Fertilizers',
    'Hydrocarbon derivatives',
    'Dates',
    'Wheat',
  ),
  EG: m(
    'Refined petroleum',
    'Natural gas',
    'Gold',
    'Fertilizers',
    'Textiles and garments',
    'Citrus fruit',
    'Aluminum',
  ),
  EH: m(
    'Phosphates',
    'Fish',
    'Sand and aggregates',
    'Salt',
    'Dates',
    'Agricultural products',
    'Re-exported goods',
  ),
  ER: m(
    'Copper ore',
    'Gold',
    'Livestock',
    'Textiles',
    'Food products',
    'Salt',
    'Hides and skins',
  ),
  ET: m(
    'Coffee',
    'Gold',
    'Oil seeds',
    'Cut flowers',
    'Livestock',
    'Garments',
    'Pulses',
  ),
  GA: m(
    'Crude petroleum',
    'Manganese ore',
    'Timber',
    'Refined petroleum',
    'Uranium',
    'Gold',
    'Palm oil',
  ),
  GH: m(
    'Gold',
    'Crude petroleum',
    'Cocoa',
    'Cashew nuts',
    'Manganese ore',
    'Oil seeds',
    'Refined petroleum',
  ),
  GM: m(
    'Groundnuts',
    'Fish',
    'Cotton',
    'Timber',
    'Palm kernels',
    'Petroleum products',
    'Re-exported goods',
  ),
  GN: m(
    'Gold',
    'Bauxite',
    'Aluminum',
    'Diamonds',
    'Palm oil',
    'Coffee',
    'Fruits',
  ),
  GQ: m(
    'Crude petroleum',
    'Liquified natural gas',
    'Timber',
    'Cocoa',
    'Fish',
    'Methanol',
    'Timber products',
  ),
  GW: m(
    'Cashew nuts',
    'Fish',
    'Gold',
    'Timber',
    'Palm oil',
    'Cotton',
    'Peanuts',
  ),
  KE: m(
    'Tea',
    'Cut flowers',
    'Coffee',
    'Refined petroleum',
    'Titanium ore',
    'Avocados',
    'Vegetables',
  ),
  KM: m(
    'Vanilla',
    'Cloves',
    'Ylang-ylang',
    'Fish',
    'Essential oils',
    'Copra',
    'Pepper',
  ),
  LR: m(
    'Iron ore',
    'Gold',
    'Rubber',
    'Ships',
    'Diamonds',
    'Palm oil',
    'Timber',
  ),
  LS: m(
    'Diamonds',
    'Garments',
    'Wool',
    'Water',
    'Mohair',
    'Footwear',
    'Textiles',
  ),
  LY: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Fertilizers',
    'Hydrocarbon derivatives',
    'Dates',
    'Wheat',
  ),
  MA: m(
    'Automobiles',
    'Fertilizers',
    'Phosphates',
    'Electrical components',
    'Textiles',
    'Citrus fruit',
    'Fish',
  ),
  MG: m(
    'Vanilla',
    'Nickel',
    'Apparel',
    'Cloves',
    'Gold',
    'Shrimp',
    'Graphite',
  ),
  ML: m(
    'Gold',
    'Cotton',
    'Livestock',
    'Salt',
    'Sesame seeds',
    'Fruits',
    'Shea nuts',
  ),
  MR: m(
    'Iron ore',
    'Gold',
    'Fish',
    'Copper',
    'Gypsum',
    'Crude petroleum',
    'Livestock',
  ),
  MU: m(
    'Fish',
    'Textiles',
    'Sugar',
    'Refined petroleum',
    'Jewelry',
    'Cut flowers',
    'Medical devices',
  ),
  MW: m(
    'Tobacco',
    'Tea',
    'Sugar',
    'Legumes',
    'Coffee',
    'Nuts',
    'Cotton',
  ),
  MZ: m(
    'Coal',
    'Aluminum',
    'Natural gas',
    'Electrical energy',
    'Cashew nuts',
    'Prawns',
    'Tobacco',
  ),
  NA: m(
    'Diamonds',
    'Uranium',
    'Fish',
    'Zinc',
    'Gold',
    'Beef',
    'Salt',
  ),
  NE: m(
    'Uranium',
    'Gold',
    'Livestock',
    'Onions',
    'Cowpeas',
    'Sesame seeds',
    'Crude petroleum',
  ),
  NG: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Cocoa',
    'Fertilizers',
    'Sesame seeds',
    'Gold',
  ),
  RW: m(
    'Gold',
    'Coffee',
    'Tea',
    'Tin',
    'Tantalum',
    'Tungsten',
    'Niobium',
  ),
  SC: m(
    'Fish',
    'Processed fish',
    'Petroleum re-exports',
    'Copra',
    'Cinnamon',
    'Canned tuna',
    'Tourism-linked goods',
  ),
  SD: m(
    'Gold',
    'Crude petroleum',
    'Livestock',
    'Sesame seeds',
    'Cotton',
    'Gum arabic',
    'Sheep',
  ),
  SL: m(
    'Iron ore',
    'Diamonds',
    'Rutile',
    'Cocoa',
    'Coffee',
    'Fish',
    'Timber',
  ),
  SN: m(
    'Refined petroleum',
    'Gold',
    'Fish',
    'Phosphates',
    'Groundnuts',
    'Cement',
    'Titanium ore',
  ),
  SO: m(
    'Livestock',
    'Charcoal',
    'Fish',
    'Gold',
    'Sesame seeds',
    'Bananas',
    'Hides and skins',
  ),
  SS: m(
    'Crude petroleum',
    'Gold',
    'Timber',
    'Gum arabic',
    'Sesame seeds',
    'Hides and skins',
    'Honey',
  ),
  ST: m(
    'Cocoa',
    'Coffee',
    'Palm oil',
    'Copra',
    'Fish',
    'Pepper',
    'Cinnamon',
  ),
  SZ: m(
    'Sugar',
    'Soft drink concentrates',
    'Cotton yarn',
    'Wood pulp',
    'Beef',
    'Citrus fruit',
    'Textiles',
  ),
  TD: m(
    'Crude petroleum',
    'Cotton',
    'Livestock',
    'Gum arabic',
    'Sesame seeds',
    'Gold',
    'Hides and skins',
  ),
  TG: m(
    'Crude petroleum',
    'Re-exported goods',
    'Cocoa',
    'Phosphates',
    'Cotton',
    'Coffee',
    'Refined petroleum',
  ),
  TN: m(
    'Electrical components',
    'Olive oil',
    'Textiles',
    'Phosphates',
    'Dates',
    'Fish',
    'Hydrocarbons',
  ),
  TZ: m(
    'Gold',
    'Cashew nuts',
    'Coffee',
    'Refined petroleum',
    'Cotton',
    'Tobacco',
    'Tea',
  ),
  UG: m(
    'Coffee',
    'Gold',
    'Fish',
    'Tea',
    'Cotton',
    'Maize',
    'Cut flowers',
  ),
  ZA: m(
    'Platinum',
    'Gold',
    'Coal',
    'Iron ore',
    'Manganese ore',
    'Automobiles',
    'Citrus fruit',
  ),
  ZM: m(
    'Copper',
    'Refined copper',
    'Cobalt',
    'Gold',
    'Tobacco',
    'Sugar',
    'Gemstones',
  ),
  ZW: m(
    'Platinum',
    'Gold',
    'Tobacco',
    'Nickel',
    'Diamonds',
    'Ferroalloys',
    'Cotton',
  ),
}
