import type { AuMemberIsoCode } from './auMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per AU member (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const AU_MAIN_INTERNATIONAL_SEAPORTS: Record<AuMemberIsoCode, MainInternationalSeaport> = {
  AO: seaport(
    'Port of Luanda',
    'https://www.otal.com/angola/port-of-luanda',
    'info@portosdeangola.co.ao',
    'https://x.com/PortosAngola',
    'https://www.instagram.com/portosdeangola/',
    'https://www.linkedin.com/company/portos-de-angola/',
    'aduaneira@minfin.gov.ao',
    'https://www.minfin.gov.ao',
    'Customs Post — Port of Luanda, Luanda, Angola',
  ),
  BF: seaport(
    'Port of Lomé (primary maritime gateway; landlocked)',
    'https://www.portdelome.tg/',
    'contact@portdelome.tg',
    'https://x.com/PortLome',
    'https://www.instagram.com/portdelome/',
    'https://www.linkedin.com/company/port-autonome-de-lome/',
    'douanes@finances.gov.bf',
    'https://www.douanes.gov.bf',
    'Direction Générale des Douanes, Ouagadougou, Burkina Faso',
  ),
  BI: seaport(
    'Port of Bujumbura (Lake Tanganyika)',
    'https://www.obr.bi/',
    'info@obr.bi',
    'https://x.com/OBR_Burundi',
    'https://www.instagram.com/obr_burundi/',
    'https://www.linkedin.com/company/office-burundais-des-recettes/',
    'douanes@obr.bi',
    'https://www.obr.bi',
    'Bureau des Douanes — Port de Bujumbura, Bujumbura, Burundi',
  ),
  BJ: seaport(
    'Port of Cotonou',
    'https://www.portdecotonou.com/',
    'contact@portdecotonou.com',
    'https://x.com/PortCotonou',
    'https://www.instagram.com/portcotonou/',
    'https://www.linkedin.com/company/port-autonome-de-cotonou/',
    'douanes@finances.bj',
    'https://www.douanes.bj',
    'Direction Générale des Douanes — Port de Cotonou, Cotonou, Benin',
  ),
  BW: seaport(
    'Port of Walvis Bay (primary maritime gateway; landlocked)',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'info@botswanacustoms.gov.bw',
    'https://www.botswanacustoms.gov.bw',
    'Botswana Unified Revenue Service — Customs Division, Gaborone, Botswana',
  ),
  CD: seaport(
    'Port of Matadi',
    'https://www.opdrdc.cd/',
    'contact@opdrdc.cd',
    'https://x.com/OPDRDC',
    'https://www.instagram.com/opdrdc/',
    'https://www.linkedin.com/company/office-des-ports-et-voies-fluviales-rdc/',
    'douanes@dgda.cd',
    'https://www.douanesrdc.cd',
    'Direction Générale des Douanes et Accises — Port de Matadi, Matadi, DRC',
  ),
  CF: seaport(
    'Port of Douala (primary maritime gateway; landlocked)',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.cf',
    'https://www.douanes-centrafrique.org',
    'Direction Générale des Douanes — Bangui, Central African Republic',
  ),
  CG: seaport(
    'Port of Pointe-Noire',
    'https://www.otal.com/congo/port-of-pointe-noire',
    'contact@port-noire.cg',
    'https://x.com/PortPointeNoire',
    'https://www.instagram.com/portpointenoire/',
    'https://www.linkedin.com/company/port-autonome-de-pointe-noire/',
    'douanes@finances.cg',
    'https://www.douanes.cg',
    'Direction Générale des Douanes — Port de Pointe-Noire, Pointe-Noire, Republic of the Congo',
  ),
  CI: seaport(
    'Port of Abidjan',
    'https://www.portabidjan.com/',
    'contact@portabidjan.com',
    'https://x.com/PortAbidjan',
    'https://www.instagram.com/portabidjan/',
    'https://www.linkedin.com/company/port-autonome-d-abidjan/',
    'douanes@dgi.gouv.ci',
    'https://www.douanes.ci',
    'Direction Générale des Douanes — Port d\'Abidjan, Abidjan, Côte d\'Ivoire',
  ),
  CM: seaport(
    'Port of Douala',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.cm',
    'https://www.douanes.cm',
    'Direction Générale des Douanes — Port de Douala, Douala, Cameroon',
  ),
  CV: seaport(
    'Port of Praia',
    'https://www.enapor.cv/',
    'info@enapor.cv',
    'https://x.com/ENAPOR_CV',
    'https://www.instagram.com/enapor_cv/',
    'https://www.linkedin.com/company/enapor/',
    'aduaneira@mf.gov.cv',
    'https://www.douanascv.gov.cv',
    'Serviço de Alfândegas — Porto da Praia, Praia, Cabo Verde',
  ),
  DJ: seaport(
    'Port of Djibouti',
    'https://www.portdedjibouti.com/',
    'contact@portdedjibouti.com',
    'https://x.com/PortDjibouti',
    'https://www.instagram.com/portdedjibouti/',
    'https://www.linkedin.com/company/port-de-djibouti/',
    'douanes@douanes.dj',
    'https://www.douanes.dj',
    'Direction Générale des Douanes — Port de Djibouti, Djibouti City, Djibouti',
  ),
  DZ: seaport(
    'Port of Algiers',
    'https://www.epal.dz/',
    'contact@epal.dz',
    'https://x.com/EPA_Alger',
    'https://www.instagram.com/epa_alger/',
    'https://www.linkedin.com/company/entreprise-portuaire-d-alger/',
    'douane@douane.gov.dz',
    'https://www.douane.gov.dz',
    'Direction Générale des Douanes — Port d\'Alger, Alger, Algeria',
  ),
  EG: seaport(
    'Port of Alexandria',
    'https://www.alexandria-port.com/',
    'info@alexandria-port.com',
    'https://x.com/AlexPortEgypt',
    'https://www.instagram.com/alexportegypt/',
    'https://www.linkedin.com/company/alexandria-port-authority/',
    'customs@customs.gov.eg',
    'https://www.customs.gov.eg',
    'Egyptian Customs Authority — Port of Alexandria, Alexandria, Egypt',
  ),
  EH: seaport(
    'Port of Dakhla (disputed administration)',
    'https://www.ancfcc.gov.ma/',
    'contact@portdakhla.ma',
    '',
    '',
    'https://www.linkedin.com/company/ports-maroc/',
    'douane@douane.gov.ma',
    'https://www.douane.gov.ma',
    'Administration des Douanes — Port de Dakhla, Dakhla, Western Sahara',
  ),
  ER: seaport(
    'Port of Massawa',
    'https://www.shabait.com/',
    'info@shabait.com',
    'https://x.com/shabait',
    'https://www.instagram.com/shabait/',
    'https://www.linkedin.com/company/eritrean-ports/',
    'customs@shabait.com',
    'https://www.shabait.com',
    'Eritrean Customs — Port of Massawa, Massawa, Eritrea',
  ),
  ET: seaport(
    'Port of Djibouti (primary maritime gateway; landlocked)',
    'https://www.portdedjibouti.com/',
    'contact@portdedjibouti.com',
    'https://x.com/PortDjibouti',
    'https://www.instagram.com/portdedjibouti/',
    'https://www.linkedin.com/company/port-de-djibouti/',
    'info@erca.gov.et',
    'https://www.erca.gov.et',
    'Ethiopian Customs Commission — Modjo Dry Port, Modjo, Ethiopia',
  ),
  GA: seaport(
    'Port of Owendo',
    'https://www.otal.com/gabon/port-of-owendo',
    'contact@port-gentil.ga',
    'https://x.com/PortOwendo',
    'https://www.instagram.com/portowendo/',
    'https://www.linkedin.com/company/port-d-owendo/',
    'douanes@finances.ga',
    'https://www.douanes.ga',
    'Direction Générale des Douanes — Port d\'Owendo, Owendo, Gabon',
  ),
  GH: seaport(
    'Port of Tema',
    'https://www.ghanaports.gov.gh/',
    'info@ghanaports.gov.gh',
    'https://x.com/GhanaPorts',
    'https://www.instagram.com/ghanaports/',
    'https://www.linkedin.com/company/ghana-ports-and-harbours-authority/',
    'info@gra.gov.gh',
    'https://www.gra.gov.gh',
    'Ghana Revenue Authority — Customs Division, Port of Tema, Tema, Ghana',
  ),
  GM: seaport(
    'Port of Banjul',
    'https://www.gambiaports.gm/',
    'info@gambiaports.gm',
    'https://x.com/GambiaPorts',
    'https://www.instagram.com/gambiaports/',
    'https://www.linkedin.com/company/gambia-ports-authority/',
    'info@gra.gm',
    'https://www.gra.gm',
    'Gambia Revenue Authority — Customs, Port of Banjul, Banjul, The Gambia',
  ),
  GN: seaport(
    'Port of Conakry',
    'https://www.otal.com/guinea/port-of-conakry',
    'contact@portconakry.gn',
    'https://x.com/PortConakry',
    'https://www.instagram.com/portconakry/',
    'https://www.linkedin.com/company/port-autonome-de-conakry/',
    'douanes@finances.gov.gn',
    'https://www.douanes.gov.gn',
    'Direction Générale des Douanes — Port de Conakry, Conakry, Guinea',
  ),
  GQ: seaport(
    'Port of Bata',
    'https://www.otal.com/equatorial-guinea/port-of-bata',
    'contact@portbata.gq',
    'https://x.com/PortBata',
    'https://www.instagram.com/portbata/',
    'https://www.linkedin.com/company/port-of-bata/',
    'aduana@guineaecuatorial.gq',
    'https://www.aduana.gq',
    'Aduana de Guinea Ecuatorial — Puerto de Bata, Bata, Equatorial Guinea',
  ),
  GW: seaport(
    'Port of Bissau',
    'https://www.portobissau.gw/',
    'info@portobissau.gw',
    'https://x.com/PortBissau',
    'https://www.instagram.com/portbissau/',
    'https://www.linkedin.com/company/porto-de-bissau/',
    'aduaneira@mf.gov.gw',
    'https://www.aduaneira.gov.gw',
    'Alfândega Nacional — Porto de Bissau, Bissau, Guinea-Bissau',
  ),
  KE: seaport(
    'Port of Mombasa',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@kra.go.ke',
    'https://www.kra.go.ke',
    'Kenya Revenue Authority — Customs Services, Port of Mombasa, Mombasa, Kenya',
  ),
  KM: seaport(
    'Port of Moroni',
    'https://www.portcomores.km/',
    'info@portcomores.km',
    'https://x.com/PortComores',
    'https://www.instagram.com/portcomores/',
    'https://www.linkedin.com/company/port-autonome-des-comores/',
    'douanes@finances.km',
    'https://www.douanes.km',
    'Direction des Douanes — Port de Moroni, Moroni, Comoros',
  ),
  LR: seaport(
    'Freeport of Monrovia',
    'https://www.npaliberia.com/',
    'info@npaliberia.com',
    'https://x.com/NPA_Liberia',
    'https://www.instagram.com/npa_liberia/',
    'https://www.linkedin.com/company/national-port-authority-liberia/',
    'customs@lra.gov.lr',
    'https://www.lra.gov.lr',
    'Liberia Revenue Authority — Customs, Freeport of Monrovia, Monrovia, Liberia',
  ),
  LS: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@lra.org.ls',
    'https://www.lra.org.ls',
    'Lesotho Revenue Authority — Customs Division, Maseru, Lesotho',
  ),
  LY: seaport(
    'Port of Tripoli',
    'https://www.lpc.ly/',
    'info@lpc.ly',
    'https://x.com/LibyanPorts',
    'https://www.instagram.com/libyanports/',
    'https://www.linkedin.com/company/libyan-ports-corporation/',
    'customs@customs.gov.ly',
    'https://www.customs.gov.ly',
    'Libyan Customs Authority — Port of Tripoli, Tripoli, Libya',
  ),
  MA: seaport(
    'Port of Tanger Med',
    'https://www.tangermed.ma/',
    'contact@tangermed.ma',
    'https://x.com/TangerMed',
    'https://www.instagram.com/tangermed/',
    'https://www.linkedin.com/company/tanger-med/',
    'douane@douane.gov.ma',
    'https://www.douane.gov.ma',
    'Administration des Douanes — Tanger Med, Tanger, Morocco',
  ),
  MG: seaport(
    'Port of Toamasina',
    'https://www.otal.com/madagascar/port-of-toamasina',
    'contact@port-toamasina.mg',
    'https://x.com/PortToamasina',
    'https://www.instagram.com/porttoamasina/',
    'https://www.linkedin.com/company/port-de-toamasina/',
    'douanes@douanes.gov.mg',
    'https://www.douanes.gov.mg',
    'Direction Générale des Douanes — Port de Toamasina, Toamasina, Madagascar',
  ),
  ML: seaport(
    'Port of Dakar (primary maritime gateway; landlocked)',
    'https://www.portdedakar.sn/',
    'contact@portdedakar.sn',
    'https://x.com/PortDakar',
    'https://www.instagram.com/portdedakar/',
    'https://www.linkedin.com/company/port-autonome-de-dakar/',
    'douanes@finances.ml',
    'https://www.douanes.ml',
    'Direction Générale des Douanes — Bamako, Mali',
  ),
  MR: seaport(
    'Port of Nouadhibou',
    'https://www.otal.com/mauritania/port-of-nouadhibou',
    'contact@portnouadhibou.mr',
    'https://x.com/PortNouadhibou',
    'https://www.instagram.com/portnouadhibou/',
    'https://www.linkedin.com/company/port-de-nouadhibou/',
    'douanes@finances.gov.mr',
    'https://www.douanes.gov.mr',
    'Direction Générale des Douanes — Port de Nouadhibou, Nouadhibou, Mauritania',
  ),
  MU: seaport(
    'Port Louis',
    'https://www.mpa.mu/',
    'info@mpa.mu',
    'https://x.com/MPA_Mauritius',
    'https://www.instagram.com/mpa_mauritius/',
    'https://www.linkedin.com/company/mauritius-ports-authority/',
    'customs@mra.mu',
    'https://www.mra.mu',
    'Mauritius Revenue Authority — Customs, Port Louis, Mauritius',
  ),
  MW: seaport(
    'Port of Nacala (primary maritime gateway; landlocked)',
    'https://www.otal.com/mozambique/port-of-nacala',
    'info@cdi.mw',
    'https://x.com/CDI_Malawi',
    'https://www.instagram.com/cdi_malawi/',
    'https://www.linkedin.com/company/corridor-development-initiative/',
    'customs@mra.mw',
    'https://www.mra.mw',
    'Malawi Revenue Authority — Customs Division, Blantyre, Malawi',
  ),
  MZ: seaport(
    'Port of Maputo',
    'https://www.portmaputo.com/',
    'info@portmaputo.com',
    'https://x.com/PortMaputo',
    'https://www.instagram.com/portmaputo/',
    'https://www.linkedin.com/company/porto-de-maputo/',
    'aduaneira@at.gov.mz',
    'https://www.at.gov.mz',
    'Autoridade Tributária de Moçambique — Alfândega do Porto de Maputo, Maputo, Mozambique',
  ),
  NA: seaport(
    'Port of Walvis Bay',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'customs@namra.org.na',
    'https://www.namra.org.na',
    'Namibia Revenue Agency — Customs, Port of Walvis Bay, Walvis Bay, Namibia',
  ),
  NE: seaport(
    'Port of Cotonou (primary maritime gateway; landlocked)',
    'https://www.portdecotonou.com/',
    'contact@portdecotonou.com',
    'https://x.com/PortCotonou',
    'https://www.instagram.com/portcotonou/',
    'https://www.linkedin.com/company/port-autonome-de-cotonou/',
    'douanes@finances.ne',
    'https://www.douanes.ne',
    'Direction Générale des Douanes — Niamey, Niger',
  ),
  NG: seaport(
    'Port of Lagos (Apapa)',
    'https://www.npa.gov.ng/',
    'info@npa.gov.ng',
    'https://x.com/NPA_Nigeria',
    'https://www.instagram.com/npa_nigeria/',
    'https://www.linkedin.com/company/nigerian-ports-authority/',
    'customs@customs.gov.ng',
    'https://www.customs.gov.ng',
    'Nigeria Customs Service — Apapa Port, Lagos, Nigeria',
  ),
  RW: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@rra.gov.rw',
    'https://www.rra.gov.rw',
    'Rwanda Revenue Authority — Customs Services, Kigali, Rwanda',
  ),
  SC: seaport(
    'Port Victoria',
    'https://www.spa.sc/',
    'info@spa.sc',
    'https://x.com/SPA_Seychelles',
    'https://www.instagram.com/spa_seychelles/',
    'https://www.linkedin.com/company/seychelles-ports-authority/',
    'customs@src.gov.sc',
    'https://www.src.gov.sc',
    'Seychelles Revenue Commission — Customs, Port Victoria, Mahé, Seychelles',
  ),
  SD: seaport(
    'Port Sudan',
    'https://www.spc.sd/',
    'info@spc.sd',
    'https://x.com/SPC_Sudan',
    'https://www.instagram.com/spc_sudan/',
    'https://www.linkedin.com/company/sea-ports-corporation-sudan/',
    'customs@customs.gov.sd',
    'https://www.customs.gov.sd',
    'Sudan Customs Authority — Port Sudan, Port Sudan, Sudan',
  ),
  SL: seaport(
    'Port of Freetown',
    'https://www.slpa.sl/',
    'info@slpa.sl',
    'https://x.com/SLPA_Freetown',
    'https://www.instagram.com/slpa_freetown/',
    'https://www.linkedin.com/company/sierra-leone-ports-authority/',
    'customs@nra.gov.sl',
    'https://www.nra.gov.sl',
    'National Revenue Authority — Customs, Port of Freetown, Freetown, Sierra Leone',
  ),
  SN: seaport(
    'Port of Dakar',
    'https://www.portdedakar.sn/',
    'contact@portdedakar.sn',
    'https://x.com/PortDakar',
    'https://www.instagram.com/portdedakar/',
    'https://www.linkedin.com/company/port-autonome-de-dakar/',
    'douanes@finances.sn',
    'https://www.douanes.sn',
    'Direction Générale des Douanes — Port de Dakar, Dakar, Senegal',
  ),
  SO: seaport(
    'Port of Mogadishu',
    'https://www.mpa.gov.so/',
    'info@mpa.gov.so',
    'https://x.com/MPA_Somalia',
    'https://www.instagram.com/mpa_somalia/',
    'https://www.linkedin.com/company/mogadishu-port-authority/',
    'customs@finance.gov.so',
    'https://www.customs.gov.so',
    'Somalia Customs — Port of Mogadishu, Mogadishu, Somalia',
  ),
  SS: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@nra.gov.ss',
    'https://www.nra.gov.ss',
    'National Revenue Authority — Customs, Juba, South Sudan',
  ),
  ST: seaport(
    'Port of São Tomé',
    'https://www.enaport.st/',
    'info@enaport.st',
    'https://x.com/ENAPORT_ST',
    'https://www.instagram.com/enaport_st/',
    'https://www.linkedin.com/company/enaport/',
    'aduaneira@mf.gov.st',
    'https://www.aduaneira.gov.st',
    'Alfândega Nacional — Porto de São Tomé, São Tomé, São Tomé and Príncipe',
  ),
  SZ: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@sra.org.sz',
    'https://www.sra.org.sz',
    'Eswatini Revenue Service — Customs Division, Mbabane, Eswatini',
  ),
  TD: seaport(
    'Port of Douala (primary maritime gateway; landlocked)',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.td',
    'https://www.douanes.td',
    'Direction Générale des Douanes — N\'Djamena, Chad',
  ),
  TG: seaport(
    'Port of Lomé',
    'https://www.portdelome.tg/',
    'contact@portdelome.tg',
    'https://x.com/PortLome',
    'https://www.instagram.com/portdelome/',
    'https://www.linkedin.com/company/port-autonome-de-lome/',
    'douanes@finances.tg',
    'https://www.douanes.tg',
    'Direction Générale des Douanes — Port de Lomé, Lomé, Togo',
  ),
  TN: seaport(
    'Port of Rades',
    'https://www.ommp.nat.tn/',
    'contact@ommp.nat.tn',
    'https://x.com/OMMP_Tunisia',
    'https://www.instagram.com/ommp_tunisia/',
    'https://www.linkedin.com/company/ommp-tunisia/',
    'douane@douane.gov.tn',
    'https://www.douane.gov.tn',
    'Direction Générale des Douanes — Port de Radès, Radès, Tunisia',
  ),
  TZ: seaport(
    'Port of Dar es Salaam',
    'https://www.tanzaniaports.com/',
    'info@tanzaniaports.com',
    'https://x.com/TanzaniaPorts',
    'https://www.instagram.com/tanzaniaports/',
    'https://www.linkedin.com/company/tanzania-ports-authority/',
    'customs@tra.go.tz',
    'https://www.tra.go.tz',
    'Tanzania Revenue Authority — Customs, Port of Dar es Salaam, Dar es Salaam, Tanzania',
  ),
  UG: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@ura.go.ug',
    'https://www.ura.go.ug',
    'Uganda Revenue Authority — Customs, Kampala, Uganda',
  ),
  ZA: seaport(
    'Port of Durban',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'customs@sars.gov.za',
    'https://www.sars.gov.za',
    'South African Revenue Service — Customs, Port of Durban, Durban, South Africa',
  ),
  ZM: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@zra.org.zm',
    'https://www.zra.org.zm',
    'Zambia Revenue Authority — Customs Division, Lusaka, Zambia',
  ),
  ZW: seaport(
    'Port of Beira (primary maritime gateway; landlocked)',
    'https://www.otal.com/mozambique/port-of-beira',
    'info@cdm.co.mz',
    'https://x.com/CDM_Mozambique',
    'https://www.instagram.com/cdm_mozambique/',
    'https://www.linkedin.com/company/cfm-mozambique/',
    'info@zimra.co.zw',
    'https://www.zimra.co.zw',
    'Zimbabwe Revenue Authority — Customs Division, Harare, Zimbabwe',
  ),
}
