import type { AuMemberIsoCode } from './auMemberIsoCodes'
import type { RareEarths } from './types'

/**
 * Documented rare-earth element exports (lanthanide series plus Sc and Y) by ISO 3166-1 alpha-2.
 * Entries reflect commercial or near-commercial-stage production / off-take agreements as of authoring.
 * Empty tuples indicate no documented commercial-scale REE exports (informational; verify periodically).
 */
export const AU_RARE_EARTHS: Record<AuMemberIsoCode, RareEarths> = {
  AO: [],
  BF: [],
  BI: ['Cerium (Ce)', 'Lanthanum (La)'],
  BJ: [],
  BW: [],
  CD: ['Lanthanum (La)', 'Cerium (Ce)', 'Neodymium (Nd)'],
  CF: [],
  CG: [],
  CI: [],
  CM: [],
  CV: [],
  DJ: [],
  DZ: [],
  EG: ['Neodymium (Nd)', 'Cerium (Ce)', 'Lanthanum (La)', 'Yttrium (Y)'],
  EH: [],
  ER: [],
  ET: [],
  GA: ['Neodymium (Nd)', 'Cerium (Ce)', 'Lanthanum (La)'],
  GH: [],
  GM: [],
  GN: [],
  GQ: [],
  GW: [],
  KE: ['Cerium (Ce)', 'Lanthanum (La)', 'Neodymium (Nd)'],
  KM: [],
  LR: [],
  LS: [],
  LY: [],
  MA: [],
  MG: [
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Lanthanum (La)',
    'Cerium (Ce)',
    'Yttrium (Y)',
  ],
  ML: [],
  MR: [],
  MU: [],
  MW: [
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Yttrium (Y)',
  ],
  MZ: ['Neodymium (Nd)', 'Praseodymium (Pr)', 'Cerium (Ce)', 'Lanthanum (La)'],
  NA: ['Dysprosium (Dy)', 'Terbium (Tb)', 'Yttrium (Y)'],
  NE: [],
  NG: ['Neodymium (Nd)', 'Cerium (Ce)', 'Lanthanum (La)'],
  RW: [],
  SC: [],
  SD: [],
  SL: [],
  SN: [],
  SO: [],
  SS: [],
  ST: [],
  SZ: [],
  TD: [],
  TG: [],
  TN: [],
  TZ: [
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Cerium (Ce)',
    'Lanthanum (La)',
  ],
  UG: [
    'Yttrium (Y)',
    'Dysprosium (Dy)',
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
  ],
  ZA: [
    'Neodymium (Nd)',
    'Praseodymium (Pr)',
    'Cerium (Ce)',
    'Lanthanum (La)',
    'Samarium (Sm)',
  ],
  ZM: [],
  ZW: [],
}
