import type { AuMemberIsoCode } from './auMemberIsoCodes'
import type { SecuritiesExchangeCommission } from './types'

function sec(
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): SecuritiesExchangeCommission {
  return { name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

/** UEMOA regional capital-markets regulator shared by BF BJ CI GW ML NE SN TG. */
const CREPMF = sec(
  'Conseil Régional de l\'Épargne Publique et des Marchés Financiers (CREPMF)',
  'https://www.crepmf.org',
  'crepmf@crepmf.org',
  '',
  'https://www.linkedin.com/company/crepmf/',
  'https://www.crepmf.org',
)

/** CEMAC regional capital-markets regulator shared by CF CG CM GA GQ TD. */
const COSUMAF = sec(
  'Commission de Surveillance du Marché Financier de l\'Afrique Centrale (COSUMAF)',
  'https://www.cosumaf.org',
  'cosumaf@cosumaf.org',
  '',
  '',
  'https://www.cosumaf.org',
)

/**
 * Securities and exchange / capital-markets commission by ISO 3166-1 alpha-2 for African Union
 * member states in this module (informational; verify URLs, handles, forms portals, and API
 * bases before production use). Self-contained — no imports from other alliance modules.
 * Regional bodies (CREPMF for UEMOA, COSUMAF for CEMAC) are shared constants above.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.asea.net / https://www.iosco.org/about/membership/
 */
export const AU_SECURITIES_EXCHANGE_COMMISSIONS: Record<
  AuMemberIsoCode,
  SecuritiesExchangeCommission
> = {
  AO: sec(
    'Comissão do Mercado de Capitais (CMC Angola)',
    'https://www.cmc.gv.ao',
    'cmc@cmc.gv.ao',
    '',
    'https://www.linkedin.com/company/comissão-do-mercado-de-capitais-angola/',
    'https://www.cmc.gv.ao',
  ),
  BF: CREPMF,
  BI: sec(
    'Banque de la République du Burundi — capital-markets oversight (no dedicated SEC)',
    'https://www.brb.bi',
    'info@brb.bi',
    '',
    '',
    'https://www.brb.bi',
  ),
  BJ: CREPMF,
  BW: sec(
    'Non-Bank Financial Institutions Regulatory Authority (NBFIRA)',
    'https://www.nbfira.org.bw',
    'info@nbfira.org.bw',
    'https://x.com/NBFIRA',
    'https://www.linkedin.com/company/nbfira/',
    'https://www.nbfira.org.bw',
  ),
  CD: sec(
    'Autorité des Marchés Financiers — DRC (oversight via Banque Centrale du Congo)',
    'https://www.bcc.cd',
    'info@bcc.cd',
    '',
    '',
    'https://www.bcc.cd',
  ),
  CF: COSUMAF,
  CG: COSUMAF,
  CI: sec(
    'Conseil Régional de l\'Épargne Publique et des Marchés Financiers / Autorité des Marchés Financiers de Côte d\'Ivoire',
    'https://www.amf-ci.org',
    'contact@amf-ci.org',
    '',
    '',
    'https://www.amf-ci.org',
  ),
  CM: sec(
    'Commission des Marchés Financiers du Cameroun (CMF)',
    'https://www.cmf.cm',
    'cmf@cmf.cm',
    '',
    'https://www.linkedin.com/company/commission-des-marchés-financiers-du-cameroun/',
    'https://www.cmf.cm',
  ),
  CV: sec(
    'Comissão do Mercado de Valores Mobiliários de Cabo Verde (CMVM-CV)',
    'https://www.cmvm.cv',
    'info@cmvm.cv',
    '',
    '',
    'https://www.cmvm.cv',
  ),
  DJ: sec(
    'Djibouti — capital markets oversight via Ministry of Finance (no dedicated SEC)',
    'https://www.ministere-finances.dj',
    '',
    '',
    '',
    'https://www.ministere-finances.dj',
  ),
  DZ: sec(
    'Commission d\'Organisation et de Surveillance des Opérations de Bourse (COSOB)',
    'https://www.cosob.org',
    'cosob@cosob.org',
    '',
    '',
    'https://www.cosob.org',
  ),
  EG: sec(
    'Financial Regulatory Authority (FRA Egypt)',
    'https://www.fra.gov.eg',
    'fra@fra.gov.eg',
    'https://x.com/FRAegypt',
    'https://www.linkedin.com/company/financial-regulatory-authority-egypt/',
    'https://www.fra.gov.eg',
  ),
  EH: sec(
    'Sahrawi Arab Democratic Republic — no formal capital-markets regulator documented',
    'https://www.rasd-state.ws',
    '',
    '',
    '',
    'https://www.rasd-state.ws',
  ),
  ER: sec(
    'Eritrea — no formal securities / capital-markets regulator documented',
    'https://www.eritrea.be',
    '',
    '',
    '',
    'https://www.eritrea.be',
  ),
  ET: sec(
    'Ethiopian Capital Market Authority (ECMA)',
    'https://www.ecma.gov.et',
    'info@ecma.gov.et',
    'https://x.com/ECMAEthiopia',
    'https://www.linkedin.com/company/ethiopian-capital-market-authority/',
    'https://www.ecma.gov.et',
  ),
  GA: COSUMAF,
  GH: sec(
    'Securities and Exchange Commission Ghana (SEC Ghana)',
    'https://www.sec.gov.gh',
    'sec@sec.gov.gh',
    'https://x.com/SECGhana',
    'https://www.linkedin.com/company/securities-and-exchange-commission-ghana/',
    'https://www.sec.gov.gh',
  ),
  GM: sec(
    'Gambia — capital-markets oversight via Central Bank of The Gambia (no dedicated SEC)',
    'https://www.cbg.gm',
    'info@cbg.gm',
    '',
    '',
    'https://www.cbg.gm',
  ),
  GN: sec(
    'Guinea — capital-markets oversight via Banque Centrale de la République de Guinée (no dedicated SEC)',
    'https://www.bcrg-guinee.org',
    '',
    '',
    '',
    'https://www.bcrg-guinee.org',
  ),
  GQ: COSUMAF,
  GW: CREPMF,
  KE: sec(
    'Capital Markets Authority Kenya (CMA Kenya)',
    'https://www.cma.or.ke',
    'cma@cma.or.ke',
    'https://x.com/CMA_Kenya',
    'https://www.linkedin.com/company/capital-markets-authority-kenya/',
    'https://www.cma.or.ke',
  ),
  KM: sec(
    'Comores — capital-markets oversight via Banque Centrale des Comores (no dedicated SEC)',
    'https://www.banque-comores.km',
    '',
    '',
    '',
    'https://www.banque-comores.km',
  ),
  LR: sec(
    'Liberia — capital-markets oversight via Central Bank of Liberia (no dedicated SEC)',
    'https://www.cbl.org.lr',
    'info@cbl.org.lr',
    '',
    '',
    'https://www.cbl.org.lr',
  ),
  LS: sec(
    'Lesotho — capital-markets oversight via Central Bank of Lesotho (no dedicated SEC)',
    'https://www.centralbank.org.ls',
    'info@centralbank.org.ls',
    '',
    '',
    'https://www.centralbank.org.ls',
  ),
  LY: sec(
    'Libya Financial Markets Authority (LFMA) — verify current operational status',
    'https://www.lsm.ly',
    '',
    '',
    '',
    'https://www.lsm.ly',
  ),
  MA: sec(
    'Autorité Marocaine du Marché des Capitaux (AMMC)',
    'https://www.ammc.ma',
    'ammc@ammc.ma',
    'https://x.com/AMMC_maroc',
    'https://www.linkedin.com/company/ammc/',
    'https://www.ammc.ma',
  ),
  MG: sec(
    'Commission de Surveillance du Marché de l\'Épargne et des Capitaux (CSMEC Madagascar)',
    'https://www.csmec.mg',
    'csmec@csmec.mg',
    '',
    '',
    'https://www.csmec.mg',
  ),
  ML: CREPMF,
  MR: sec(
    'Mauritania — capital-markets oversight via Banque Centrale de Mauritanie (no dedicated SEC)',
    'https://www.bcm.mr',
    '',
    '',
    '',
    'https://www.bcm.mr',
  ),
  MU: sec(
    'Financial Services Commission Mauritius (FSC)',
    'https://www.fscmauritius.org',
    'fscmauritius@fscmauritius.org',
    'https://x.com/FSCMauritius',
    'https://www.linkedin.com/company/financial-services-commission-mauritius/',
    'https://www.fscmauritius.org',
  ),
  MW: sec(
    'Reserve Bank of Malawi — Capital Markets Unit (no separate SEC; CMDA mandate)',
    'https://www.rbm.mw',
    'info@rbm.mw',
    '',
    '',
    'https://www.rbm.mw',
  ),
  MZ: sec(
    'Comissão de Valores Mobiliários de Moçambique (CVM)',
    'https://www.cvm.gov.mz',
    'geral@cvm.gov.mz',
    '',
    '',
    'https://www.cvm.gov.mz',
  ),
  NA: sec(
    'Namibia Financial Institutions Supervisory Authority (NAMFISA)',
    'https://www.namfisa.com.na',
    'enquiries@namfisa.com.na',
    'https://x.com/NAMFISA_NA',
    'https://www.linkedin.com/company/namfisa/',
    'https://www.namfisa.com.na',
  ),
  NE: CREPMF,
  NG: sec(
    'Securities and Exchange Commission Nigeria (SEC Nigeria)',
    'https://www.sec.gov.ng',
    'sec@sec.gov.ng',
    'https://x.com/SECNigeria',
    'https://www.linkedin.com/company/securities-and-exchange-commission-nigeria/',
    'https://www.sec.gov.ng',
  ),
  RW: sec(
    'Capital Markets Authority Rwanda (CMA Rwanda)',
    'https://www.cma.rw',
    'info@cma.rw',
    'https://x.com/CMA_Rwanda',
    'https://www.linkedin.com/company/capital-markets-authority-rwanda/',
    'https://www.cma.rw',
  ),
  SC: sec(
    'Financial Services Authority Seychelles (FSA)',
    'https://www.fsaseychelles.sc',
    'fsaseychelles@fsaseychelles.sc',
    '',
    'https://www.linkedin.com/company/financial-services-authority-seychelles/',
    'https://www.fsaseychelles.sc',
  ),
  SD: sec(
    'Sudan Capital Market Authority (CMA Sudan)',
    'https://www.cma.gov.sd',
    '',
    '',
    '',
    'https://www.cma.gov.sd',
  ),
  SL: sec(
    'Sierra Leone — capital-markets oversight via Bank of Sierra Leone (no dedicated SEC)',
    'https://www.bsl.gov.sl',
    'info@bsl.gov.sl',
    '',
    '',
    'https://www.bsl.gov.sl',
  ),
  SN: CREPMF,
  SO: sec(
    'Somalia — capital-markets oversight via Central Bank of Somalia (no dedicated SEC)',
    'https://www.centralbank.gov.so',
    '',
    '',
    '',
    'https://www.centralbank.gov.so',
  ),
  SS: sec(
    'South Sudan — capital-markets oversight via Bank of South Sudan (nascent SSSE; verify status)',
    'https://www.bss.gov.ss',
    '',
    '',
    '',
    'https://www.bss.gov.ss',
  ),
  ST: sec(
    'São Tomé and Príncipe — capital-markets oversight via Banco Central (no dedicated SEC)',
    'https://www.bcstp.st',
    '',
    '',
    '',
    'https://www.bcstp.st',
  ),
  SZ: sec(
    'Financial Services Regulatory Authority Eswatini (FSRA)',
    'https://www.fsra.co.sz',
    'info@fsra.co.sz',
    '',
    '',
    'https://www.fsra.co.sz',
  ),
  TD: COSUMAF,
  TG: CREPMF,
  TN: sec(
    'Conseil du Marché Financier (CMF Tunisie)',
    'https://www.cmf.gov.tn',
    'cmf@cmf.gov.tn',
    '',
    'https://www.linkedin.com/company/conseil-du-marché-financier-tunisie/',
    'https://www.cmf.gov.tn',
  ),
  TZ: sec(
    'Capital Markets and Securities Authority Tanzania (CMSA)',
    'https://www.cmsa.go.tz',
    'cmsa@cmsa.go.tz',
    'https://x.com/CMSATanzania',
    'https://www.linkedin.com/company/capital-markets-and-securities-authority-tanzania/',
    'https://www.cmsa.go.tz',
  ),
  UG: sec(
    'Capital Markets Authority Uganda (CMA Uganda)',
    'https://www.cmauganda.co.ug',
    'cma@cmauganda.co.ug',
    'https://x.com/CMAUganda',
    'https://www.linkedin.com/company/capital-markets-authority-uganda/',
    'https://www.cmauganda.co.ug',
  ),
  ZA: sec(
    'Financial Sector Conduct Authority (FSCA South Africa)',
    'https://www.fsca.co.za',
    'info@fsca.co.za',
    'https://x.com/theFSCA_ZA',
    'https://www.linkedin.com/company/financial-sector-conduct-authority/',
    'https://www.fsca.co.za',
  ),
  ZM: sec(
    'Securities and Exchange Commission Zambia (SEC Zambia)',
    'https://www.sec.gov.zm',
    'info@sec.gov.zm',
    'https://x.com/SECZambia',
    'https://www.linkedin.com/company/securities-and-exchange-commission-zambia/',
    'https://www.sec.gov.zm',
  ),
  ZW: sec(
    'Securities and Exchange Commission of Zimbabwe (SECZ)',
    'https://www.secz.org.zw',
    'secz@secz.org.zw',
    '',
    '',
    'https://www.secz.org.zw',
  ),
}
