import type { OecsMemberIsoCode } from './oecsMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per OECS member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const OECS_DOMESTIC_POST_SERVICES: Record<OecsMemberIsoCode, DomesticPostService> = {
  AG: post(
    'Antigua and Barbuda Postal Service',
    'https://www.abpost.gov.ag/',
    'info@abpost.gov.ag',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and locality addressing',
  ),
  DM: post(
    'Dominica Postal Service',
    'https://www.dominicapost.dm/',
    'info@dominicapost.dm',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  GD: post(
    'Grenada Postal Corporation',
    'https://www.grenadapost.gd/',
    'info@grenadapost.gd',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  MS: post(
    'Montserrat Post',
    'https://www.gov.ms/',
    'postoffice@gov.ms',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; UK Overseas Territory addressing',
  ),
  KN: post(
    'St Kitts and Nevis Postal Service',
    'https://www.sknpost.gov.kn/',
    'info@sknpost.gov.kn',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  LC: post(
    'Saint Lucia Postal Service',
    'https://www.stluciapost.gov.lc/',
    'info@stluciapost.gov.lc',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  VC: post(
    'SVG Post (Saint Vincent and the Grenadines)',
    'https://www.svgpost.gov.vc/',
    'info@svgpost.gov.vc',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  AI: post(
    'Anguilla Postal Service',
    'https://www.gov.ai/',
    'postoffice@gov.ai',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
}
