import type { NationalBankingInstitution } from './types'
import type { OecsMemberIsoCode } from './oecsMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per OECS member or associate territory.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const OECS_NATIONAL_BANKING_INSTITUTIONS: Record<
  OecsMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AG: [
    bank(
      'Antigua Commercial Bank',
      '+1 268 481 8200',
      'High Street, St John\'s, Antigua and Barbuda',
      '',
      '',
      'https://www.acbonline.com',
      'customercare@acbonline.com',
      '',
      '',
      '',
      '',
      'ACBLAGAG',
      '',
    ),
    bank(
      'CUB (Caribbean Union Bank) Antigua',
      '+1 268 562 2582',
      'Friars Hill Road, St John\'s, Antigua and Barbuda',
      '',
      '',
      'https://www.caribbeanunionbank.com',
      'info@caribbeanunionbank.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Eastern Caribbean Amalgamated Bank',
      '+1 268 480 2225',
      'Old Parham Road, St John\'s, Antigua and Barbuda',
      '',
      '',
      'https://www.ecabank.com',
      'contact@ecabank.com',
      '',
      '',
      '',
      '',
      'ECAMAGAG',
      '',
    ),
  ],
  DM: [
    bank(
      'National Bank of Dominica',
      '+1 767 255 2300',
      'Hillsborough St, Roseau, Dominica',
      '',
      '',
      'https://www.nbdominica.com',
      'info@nbdominica.com',
      '',
      '',
      '',
      '',
      'NATDDMDM',
      '',
    ),
    bank(
      'CIBC Caribbean Dominica',
      '+1 767 255 1000',
      'Old Street, Roseau, Dominica',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'dominica@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBDMDM',
      '',
    ),
    bank(
      'Republic Bank Dominica',
      '+1 767 255 3800',
      'Great Marlborough Street, Roseau, Dominica',
      '',
      '',
      'https://www.republicdominica.com',
      'info@republicdominica.com',
      '',
      '',
      '',
      '',
      'NISBDMDM',
      '',
    ),
  ],
  GD: [
    bank(
      'Grenada Co-operative Bank',
      '+1 473 440 1234',
      '8 Church Street, St George\'s, Grenada',
      '',
      '',
      'https://www.grenadaco-opbank.com',
      'info@grenadaco-opbank.com',
      '',
      '',
      '',
      '',
      'GCOBGDGD',
      '',
    ),
    bank(
      'Republic Bank Grenada',
      '+1 473 440 4440',
      'Grand Anse, St George\'s, Grenada',
      '',
      '',
      'https://www.republicgrenada.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBGDGD',
      '',
    ),
    bank(
      'CIBC Caribbean Grenada',
      '+1 473 440 2156',
      'Granby Street, St George\'s, Grenada',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'grenada@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBGDGD',
      '',
    ),
  ],
  MS: [
    bank(
      'Bank of Montserrat',
      '+1 664 491 3846',
      'Brades Main Road, Brades, Montserrat',
      '',
      '',
      'https://www.bankofmontserrat.ms',
      'info@bankofmontserrat.ms',
      '',
      '',
      '',
      '',
      'BOMSMSMS',
      '',
    ),
    bank(
      'Republic Bank Montserrat',
      '+1 664 491 4702',
      'Brades Main Road, Brades, Montserrat',
      '',
      '',
      'https://www.republictt.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBMSMS',
      '',
    ),
    bank(
      'CIBC Caribbean Montserrat',
      '+1 664 491 3788',
      'Brades Main Road, Brades, Montserrat',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'montserrat@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBMSMS',
      '',
    ),
  ],
  KN: [
    bank(
      'St Kitts-Nevis-Anguilla National Bank',
      '+1 869 465 2204',
      'Central Street, Basseterre, St Kitts and Nevis',
      '',
      '',
      'https://www.sknanb.com',
      'customerservice@sknanb.com',
      '',
      '',
      '',
      '',
      'SKNAKNBB',
      '',
    ),
    bank(
      'CIBC Caribbean St Kitts',
      '+1 869 465 2421',
      'The Circus, Basseterre, St Kitts and Nevis',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'stkitts@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBKNBB',
      '',
    ),
    bank(
      'Republic Bank St Kitts and Nevis',
      '+1 869 466 2900',
      'Fort Street, Basseterre, St Kitts and Nevis',
      '',
      '',
      'https://www.republicskn.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBKNBB',
      '',
    ),
  ],
  LC: [
    bank(
      'Bank of Saint Lucia',
      '+1 758 456 6000',
      'Bridge Street, Castries, Saint Lucia',
      '',
      '',
      'https://www.bankofsaintlucia.com',
      'customerservice@bosl.com',
      '',
      '',
      '',
      '',
      'BOSLLCLC',
      '',
    ),
    bank(
      '1st National Bank Saint Lucia',
      '+1 758 450 2100',
      'Bridge Street, Castries, Saint Lucia',
      '',
      '',
      'https://www.1stnationalbankslu.com',
      'info@1stnationalbankslu.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
    bank(
      'Republic Bank Saint Lucia',
      '+1 758 451 3000',
      'William Peter Blvd, Castries, Saint Lucia',
      '',
      '',
      'https://www.republicstlucia.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBLCLC',
      '',
    ),
  ],
  VC: [
    bank(
      'Bank of St Vincent and the Grenadines',
      '+1 784 457 1845',
      'Halifax Street, Kingstown, Saint Vincent and the Grenadines',
      '',
      '',
      'https://www.bosvg.com',
      'customerservice@bosvg.com',
      '',
      '',
      '',
      '',
      'BOSVVCVC',
      '',
    ),
    bank(
      'CIBC Caribbean St Vincent',
      '+1 784 456 1185',
      'Halifax Street, Kingstown, Saint Vincent and the Grenadines',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'stvincent@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBVCVC',
      '',
    ),
    bank(
      'Republic Bank St Vincent',
      '+1 784 452 4375',
      'Granby Street, Kingstown, Saint Vincent and the Grenadines',
      '',
      '',
      'https://www.republicsvg.com',
      'customerservice@rfhl.com',
      '',
      '',
      '',
      '',
      'NISBVCVC',
      '',
    ),
  ],
  AI: [
    bank(
      'National Bank of Anguilla',
      '+1 264 497 2381',
      'The Valley, Anguilla',
      '',
      '',
      'https://www.nba.ai',
      'info@nba.ai',
      '',
      '',
      '',
      '',
      'NBAIAIAI',
      '',
    ),
    bank(
      'Scotiabank Anguilla',
      '+1 264 497 2355',
      'The Valley, Anguilla',
      '',
      '',
      'https://www.scotiabank.com/caribbean',
      'service@scotiabank.com',
      '',
      '',
      '',
      '',
      'NOSCAIAI',
      '',
    ),
    bank(
      'CIBC Caribbean Anguilla',
      '+1 264 497 2500',
      'The Valley, Anguilla',
      '',
      '',
      'https://www.cibc.com/caribbean',
      'anguilla@cibcfcib.com',
      '',
      '',
      '',
      '',
      'FCIBAIAA',
      '',
    ),
  ],
}
