/**
 * Storage Currencies Index - Decentralized storage and data protocol cryptocurrencies
 * 
 * This list contains cryptocurrencies and tokens associated with decentralized storage
 * networks, data protocols, and distributed computing platforms. These assets power
 * various storage solutions, CDN networks, archival systems, and data infrastructure.
 * 
 * This index is used for storage-related integrations, protocol support, and
 * currency selection interfaces for decentralized storage features.
 * 
 * Last Updated: December 2025
 */

export type CurrencyType = 'coin' | 'token';
export type ConsensusType = 'proof-of-stake' | 'proof-of-work' | 'proof-of-authority' | 'delegated-proof-of-stake' | 'nominated-proof-of-stake' | 'liquid-proof-of-stake' | 'byzantine-fault-tolerance' | 'proof-of-transfer' | 'proof-of-coverage' | 'proof-of-space-and-time' | 'proof-of-replication' | 'token' | 'hybrid' | 'optimistic-rollup' | 'zk-rollup';
export type CurrencyClass = 'layer-1' | 'layer-2' | 'defi' | 'dex' | 'nft' | 'gaming' | 'metaverse' | 'oracle' | 'privacy' | 'meme' | 'staking' | 'governance' | 'lending' | 'data' | 'infrastructure' | 'smart-contract-platform' | 'exchange-token' | 'ai' | 'storage' | 'payment' | 'social' | 'interoperability' | 'sports' | 'iot';

export interface StorageCurrencyItem {
  id: string;
  name: string;
  tickerSymbol: string;
  description: string;
  ucid: number;
  type: CurrencyType;
  consensusType: ConsensusType;
  class: CurrencyClass[];
  network: string | string[] | null;
  website: string | null;
  github: string | null;
  npm: string | null;
}

export const STORAGE_CURRENCIES: StorageCurrencyItem[] = [
  {
    id: 'aioz-network',
    name: 'AIOZ Network',
    tickerSymbol: 'AIOZ',
    description: 'A decentralized content delivery network powered by blockchain for streaming and storage.',
    ucid: 14658,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['infrastructure', 'storage', 'data'],
    network: null,
    website: 'https://aioz.network/',
    github: 'https://github.com/AIOZNetwork',
    npm: null
  },
  {
    id: 'epik-protocol',
    name: 'EpiK Protocol',
    tickerSymbol: 'AIEPK',
    description: 'A decentralized AI knowledge graph storage and sharing platform.',
    ucid: 7455,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'ai', 'data'],
    network: 'Ethereum',
    website: 'https://epik-protocol.io/',
    github: 'https://github.com/EpiK-Protocol',
    npm: null
  },
  {
    id: 'aleph-cloud',
    name: 'Aleph Cloud',
    tickerSymbol: 'ALEPH',
    description: 'A cross-chain decentralized cloud storage and computing network.',
    ucid: 5821,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure', 'interoperability'],
    network: ['Ethereum', 'Solana', 'Polkadot/Substrate', 'Cosmos'],
    website: 'https://aleph.im/',
    github: 'https://github.com/aleph-im',
    npm: 'aleph-js'
  },
  {
    id: 'arweave',
    name: 'Arweave',
    tickerSymbol: 'AR',
    description: 'A decentralized storage network offering permanent data storage with a one-time fee payment model.',
    ucid: 5632,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://www.arweave.org/',
    github: 'https://github.com/ArweaveTeam',
    npm: 'arweave'
  },
  {
    id: 'bluzelle',
    name: 'Bluzelle',
    tickerSymbol: 'BLZ',
    description: 'A decentralized database service for DApps providing high availability and security.',
    ucid: 2505,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'data', 'infrastructure'],
    network: null,
    website: 'https://www.bluzelle.com/',
    github: 'https://github.com/bluzelle',
    npm: null
  },
  {
    id: 'bittorrent-new',
    name: 'BitTorrent (New)',
    tickerSymbol: 'BTT',
    description: 'A token incentivizing file sharing on the BitTorrent peer-to-peer protocol.',
    ucid: 3718,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Tron',
    website: 'https://www.bittorrent.com/',
    github: 'https://github.com/TRON-US',
    npm: null
  },
  {
    id: 'swarm',
    name: 'Swarm',
    tickerSymbol: 'BZZ',
    description: 'A decentralized storage and communication system for a sovereign digital society on Ethereum.',
    ucid: 9279,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://www.ethswarm.org/',
    github: 'https://github.com/ethersphere',
    npm: '@ethersphere/bee-js'
  },
  {
    id: 'cess-network',
    name: 'CESS Network',
    tickerSymbol: 'CESS',
    description: 'A decentralized cloud storage and CDN infrastructure for Web3.',
    ucid: 28882,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://cess.cloud/',
    github: 'https://github.com/CESSProject',
    npm: null
  },
  {
    id: 'coldstack',
    name: 'Coldstack',
    tickerSymbol: 'CLS',
    description: 'A decentralized cloud aggregator unifying multiple storage providers.',
    ucid: 8717,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://coldstack.io/',
    github: 'https://github.com/coldstack',
    npm: null
  },
  {
    id: 'crust-network',
    name: 'Crust Network',
    tickerSymbol: 'CRU',
    description: 'A decentralized storage network providing Web3 infrastructure built on Polkadot.',
    ucid: 8766,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://crust.network/',
    github: 'https://github.com/crustio',
    npm: null
  },
  {
    id: 'psjglobal',
    name: 'PSJGlobal',
    tickerSymbol: 'CYCON',
    description: 'A decentralized storage solution with data privacy and security features.',
    ucid: 6234,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'privacy'],
    network: 'Ethereum',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'dat-protocol',
    name: 'Dat Protocol',
    tickerSymbol: 'DAT',
    description: 'A peer-to-peer protocol for distributed data sharing and versioning.',
    ucid: 3234,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'data', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://datprotocol.org/',
    github: 'https://github.com/datproject',
    npm: 'dat-node'
  },
  {
    id: 'dmail-network',
    name: 'DMAIL Network',
    tickerSymbol: 'DMAIL',
    description: 'A decentralized email and messaging infrastructure for Web3.',
    ucid: 25475,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'infrastructure'],
    network: ['Ethereum', 'BNB Chain'],
    website: 'https://dmail.ai/',
    github: 'https://github.com/dmailofficial',
    npm: null
  },
  {
    id: 'edge',
    name: 'Edge',
    tickerSymbol: 'EDGE',
    description: 'A decentralized edge computing and storage network.',
    ucid: 3855,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://edge.com/',
    github: null,
    npm: null
  },
  {
    id: 'etho-protocol',
    name: 'Etho Protocol',
    tickerSymbol: 'ETHO',
    description: 'A community-governed blockchain focused on decentralized data storage and hosting.',
    ucid: 3751,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure', 'layer-1'],
    network: null,
    website: 'https://ethoprotocol.com/',
    github: 'https://github.com/Ether1Project',
    npm: null
  },
  {
    id: 'filecoin',
    name: 'Filecoin',
    tickerSymbol: 'FIL',
    description: 'A decentralized storage network incentivizing storage providers with cryptocurrency rewards.',
    ucid: 2280,
    type: 'coin',
    consensusType: 'proof-of-replication',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://filecoin.io/',
    github: 'https://github.com/filecoin-project',
    npm: '@filecoin-shipyard/js-filecoin-api-client'
  },
  {
    id: 'flux',
    name: 'Flux',
    tickerSymbol: 'FLUX',
    description: 'A decentralized cloud infrastructure for Web3 applications with computational resources.',
    ucid: 3029,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['infrastructure', 'storage'],
    network: null,
    website: 'https://runonflux.io/',
    github: 'https://github.com/runonflux',
    npm: null
  },
  {
    id: 'folder-protocol',
    name: 'Folder Protocol',
    tickerSymbol: 'FOL',
    description: 'A decentralized storage protocol focused on file organization and management.',
    ucid: 8932,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'functionland',
    name: 'Functionland',
    tickerSymbol: 'FULA',
    description: 'A decentralized peer-to-peer cloud storage network for personal data.',
    ucid: 21581,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://functionland.org/',
    github: 'https://github.com/functionland',
    npm: null
  },
  {
    id: 'handshake',
    name: 'Handshake',
    tickerSymbol: 'HNS',
    description: 'A decentralized naming protocol for domain name registration compatible with DNS.',
    ucid: 5817,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['infrastructure', 'data'],
    network: null,
    website: 'https://handshake.org/',
    github: 'https://github.com/handshake-org',
    npm: 'hsd'
  },
  {
    id: 'holo',
    name: 'Holo',
    tickerSymbol: 'HOT',
    description: 'A framework for building distributed peer-to-peer applications without blockchain.',
    ucid: 2682,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure'],
    network: 'Ethereum',
    website: 'https://holo.host/',
    github: 'https://github.com/holochain',
    npm: null
  },
  {
    id: 'iagon',
    name: 'IAGON',
    tickerSymbol: 'IAG',
    description: 'A decentralized cloud storage and computing platform built on Cardano.',
    ucid: 3580,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Cardano',
    website: 'https://iagon.com/',
    github: 'https://github.com/iagonnetwork',
    npm: null
  },
  {
    id: 'impossible-cloud-network',
    name: 'Impossible Cloud Network',
    tickerSymbol: 'ICNT',
    description: 'An enterprise-grade decentralized cloud storage infrastructure.',
    ucid: 29748,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://impossible.cloud/',
    github: null,
    npm: null
  },
  {
    id: 'internxt',
    name: 'Internxt',
    tickerSymbol: 'INXT',
    description: 'A private cloud storage service with end-to-end encryption built on blockchain.',
    ucid: 2498,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'privacy'],
    network: 'Ethereum',
    website: 'https://internxt.com/',
    github: 'https://github.com/internxt',
    npm: null
  },
  {
    id: 'jackal-protocol',
    name: 'Jackal Protocol',
    tickerSymbol: 'JKL',
    description: 'A decentralized storage network providing hot and cold storage solutions.',
    ucid: 22045,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://jackalprotocol.com/',
    github: 'https://github.com/JackalProtocol',
    npm: null
  },
  {
    id: 'knoxfs',
    name: 'KnoxFS',
    tickerSymbol: 'KFX',
    description: 'A decentralized cloud storage platform with enhanced security features.',
    ucid: 7812,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'privacy'],
    network: 'Ethereum',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'kyve-network',
    name: 'KYVE Network',
    tickerSymbol: 'KYVE',
    description: 'A blockchain for validating and archiving data streams from various data sources.',
    ucid: 23633,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'data', 'infrastructure'],
    network: null,
    website: 'https://kyve.network/',
    github: 'https://github.com/KYVENetwork',
    npm: null
  },
  {
    id: 'lambda',
    name: 'Lambda',
    tickerSymbol: 'LAMB',
    description: 'A decentralized data storage infrastructure providing secure and scalable storage.',
    ucid: 3657,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://lambdalabs.io/',
    github: 'https://github.com/LambdaIM',
    npm: null
  },
  {
    id: 'limewire',
    name: 'LimeWire',
    tickerSymbol: 'LMWR',
    description: 'A decentralized content platform for creators, relaunched as a Web3 music platform.',
    ucid: 21634,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'nft'],
    network: ['Ethereum', 'Polygon'],
    website: 'https://limewire.com/',
    github: 'https://github.com/limewire',
    npm: null
  },
  {
    id: 'maidsafecoin',
    name: 'MaidSafeCoin',
    tickerSymbol: 'MAID',
    description: 'The token for SAFE Network, a decentralized data storage and communications platform.',
    ucid: 291,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'privacy', 'infrastructure'],
    network: 'Omni',
    website: 'https://maidsafe.net/',
    github: 'https://github.com/maidsafe',
    npm: null
  },
  {
    id: 'meson-network',
    name: 'Meson Network',
    tickerSymbol: 'MSN',
    description: 'A decentralized bandwidth marketplace for Web3 infrastructure.',
    ucid: 17552,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'storage'],
    network: 'Ethereum',
    website: 'https://meson.network/',
    github: 'https://github.com/daqnext',
    npm: null
  },
  {
    id: 'nuco-cloud',
    name: 'Nuco.cloud',
    tickerSymbol: 'NCDT',
    description: 'A decentralized cloud storage platform with data redundancy and security.',
    ucid: 4186,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://nuco.cloud/',
    github: null,
    npm: null
  },
  {
    id: 'ocean-protocol',
    name: 'Ocean Protocol',
    tickerSymbol: 'OCEAN',
    description: 'A decentralized data exchange protocol enabling secure sharing and monetization of data.',
    ucid: 3911,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'ai', 'infrastructure'],
    network: ['Ethereum', 'Polygon'],
    website: 'https://oceanprotocol.com/',
    github: 'https://github.com/oceanprotocol',
    npm: '@oceanprotocol/lib'
  },
  {
    id: 'odin-protocol',
    name: 'Odin Protocol',
    tickerSymbol: 'ODIN',
    description: 'A decentralized oracle and data infrastructure platform.',
    ucid: 8976,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'data', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://odinprotocol.io/',
    github: 'https://github.com/odinprotocol',
    npm: null
  },
  {
    id: 'opacity',
    name: 'Opacity',
    tickerSymbol: 'OPCT',
    description: 'A decentralized cloud storage platform with anonymity and privacy features.',
    ucid: 3981,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'privacy'],
    network: 'Ethereum',
    website: 'https://opacity.io/',
    github: 'https://github.com/opacity',
    npm: null
  },
  {
    id: 'pac-protocol',
    name: 'PAC Protocol',
    tickerSymbol: 'PAC',
    description: 'A decentralized storage and data platform with masternode network.',
    ucid: 3041,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://www.pacprotocol.com/',
    github: 'https://github.com/PACProtocol',
    npm: null
  },
  {
    id: 'archivas',
    name: 'Archivas',
    tickerSymbol: 'RCHV',
    description: 'A decentralized archival storage solution for long-term data preservation.',
    ucid: 7345,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'augur',
    name: 'Augur',
    tickerSymbol: 'REP',
    description: 'A decentralized prediction market platform (included for oracle/data aspects).',
    ucid: 1104,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'data', 'governance'],
    network: 'Ethereum',
    website: 'https://www.augur.net/',
    github: 'https://github.com/AugurProject',
    npm: null
  },
  {
    id: 'iexec-rlc',
    name: 'iExec RLC',
    tickerSymbol: 'RLC',
    description: 'A decentralized marketplace for cloud computing resources.',
    ucid: 1637,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'ai'],
    network: 'Ethereum',
    website: 'https://iex.ec/',
    github: 'https://github.com/iExecBlockchainComputing',
    npm: null
  },
  {
    id: 'siacoin',
    name: 'Siacoin',
    tickerSymbol: 'SC',
    description: 'A decentralized cloud storage platform where users can rent out unused storage space.',
    ucid: 1042,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://sia.tech/',
    github: 'https://github.com/SiaFoundation',
    npm: null
  },
  {
    id: 'scprime',
    name: 'ScPrime',
    tickerSymbol: 'SCP',
    description: 'A decentralized data storage solution forked from Sia, focused on enterprise needs.',
    ucid: 5837,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://scpri.me/',
    github: 'https://github.com/ScPrime',
    npm: null
  },
  {
    id: 'shadow-token',
    name: 'Shadow Token',
    tickerSymbol: 'SHDW',
    description: 'The utility token for GenesysGo\'s Shadow Drive, a decentralized storage solution on Solana.',
    ucid: 16352,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Solana',
    website: 'https://genesysgo.com/',
    github: 'https://github.com/GenesysGo',
    npm: null
  },
  {
    id: 'shift',
    name: 'Shift',
    tickerSymbol: 'SHIFT',
    description: 'A decentralized hosting platform for websites and applications.',
    ucid: 1403,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://shiftproject.io/',
    github: 'https://github.com/shiftproject',
    npm: null
  },
  {
    id: 'sinovate',
    name: 'SINOVATE',
    tickerSymbol: 'SIN',
    description: 'A blockchain with Infinity Nodes providing decentralized cloud data storage.',
    ucid: 3725,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://sinovate.io/',
    github: 'https://github.com/SINOVATEblockchain',
    npm: null
  },
  {
    id: 'skale',
    name: 'SKALE',
    tickerSymbol: 'SKL',
    description: 'An Ethereum-compatible multi-chain network providing decentralized storage and computing.',
    ucid: 5691,
    type: 'token',
    consensusType: 'token',
    class: ['layer-2', 'infrastructure', 'storage'],
    network: 'Ethereum',
    website: 'https://skale.network/',
    github: 'https://github.com/skalenetwork',
    npm: '@skalenetwork/skale.js'
  },
  {
    id: 'skycoin',
    name: 'Skycoin',
    tickerSymbol: 'SKY',
    description: 'A blockchain platform with Skywire, a decentralized mesh network and internet.',
    ucid: 1254,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['infrastructure', 'storage'],
    network: null,
    website: 'https://www.skycoin.com/',
    github: 'https://github.com/skycoin',
    npm: null
  },
  {
    id: 'solbox',
    name: 'SolBox',
    tickerSymbol: 'SOLBOX',
    description: 'A decentralized storage solution built on Solana.',
    ucid: 18543,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Solana',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'phantasma',
    name: 'Phantasma',
    tickerSymbol: 'SOUL',
    description: 'A blockchain platform with decentralized storage for NFTs and smart contracts.',
    ucid: 2827,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'nft', 'smart-contract-platform'],
    network: null,
    website: 'https://phantasma.io/',
    github: 'https://github.com/phantasma-io',
    npm: null
  },
  {
    id: 'storx-network',
    name: 'StorX Network',
    tickerSymbol: 'SRX',
    description: 'A decentralized cloud storage network with encryption and data redundancy.',
    ucid: 7981,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://storx.io/',
    github: 'https://github.com/StorXNetwork',
    npm: null
  },
  {
    id: 'sharder',
    name: 'Sharder',
    tickerSymbol: 'SS',
    description: 'A blockchain-based data storage and sharing protocol.',
    ucid: 2386,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'data'],
    network: 'Ethereum',
    website: 'https://sharder.org/',
    github: 'https://github.com/Sharders',
    npm: null
  },
  {
    id: 'simple-software-solutions',
    name: 'Simple Software Solutions',
    tickerSymbol: 'SSS',
    description: 'A decentralized storage and computing solution.',
    ucid: 4598,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'filestar',
    name: 'FileStar',
    tickerSymbol: 'STAR',
    description: 'A decentralized data storage network based on IPFS and Filecoin.',
    ucid: 8055,
    type: 'coin',
    consensusType: 'proof-of-replication',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://filestar.com/',
    github: 'https://github.com/filestar-project',
    npm: null
  },
  {
    id: 'storj',
    name: 'Storj',
    tickerSymbol: 'STORJ',
    description: 'A decentralized cloud storage network encrypting and distributing files across a distributed network.',
    ucid: 1772,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://www.storj.io/',
    github: 'https://github.com/storj',
    npm: '@storj/storj'
  },
  {
    id: 'stratos',
    name: 'Stratos',
    tickerSymbol: 'STOS',
    description: 'A decentralized data mesh providing scalable storage, database, and computation services.',
    ucid: 11214,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure', 'data'],
    network: null,
    website: 'https://stratos.network/',
    github: 'https://github.com/stratosnet',
    npm: null
  },
  {
    id: 'tapx',
    name: 'Tapx',
    tickerSymbol: 'TAP',
    description: 'A decentralized storage and content distribution platform.',
    ucid: 5923,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'threefold',
    name: 'ThreeFold',
    tickerSymbol: 'TFT',
    description: 'A peer-to-peer internet infrastructure providing decentralized compute, storage, and network capacity.',
    ucid: 5264,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['infrastructure', 'storage'],
    network: null,
    website: 'https://threefold.io/',
    github: 'https://github.com/threefoldtech',
    npm: null
  },
  {
    id: 'verida',
    name: 'Verida',
    tickerSymbol: 'VDA',
    description: 'A decentralized personal data storage and identity protocol.',
    ucid: 20856,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'privacy', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://www.verida.io/',
    github: 'https://github.com/verida',
    npm: null
  },
  {
    id: 'walrus',
    name: 'Walrus',
    tickerSymbol: 'WAL',
    description: 'A decentralized storage solution.',
    ucid: 35482,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'storagechain',
    name: 'StorageChain',
    tickerSymbol: 'WSTOR',
    description: 'A decentralized cloud storage blockchain platform.',
    ucid: 9234,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    network: 'Ethereum',
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'wesendit',
    name: 'WeSendit',
    tickerSymbol: 'WSI',
    description: 'A decentralized file sharing and storage platform.',
    ucid: 7234,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'social'],
    network: 'Ethereum',
    website: 'https://wesendit.io/',
    github: null,
    npm: null
  },
  {
    id: 'sirius-chain',
    name: 'Sirius Chain',
    tickerSymbol: 'XPX',
    description: 'A decentralized storage and streaming solution with ProximaX protocol.',
    ucid: 2893,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['storage', 'infrastructure'],
    network: null,
    website: 'https://siriuschain.io/',
    github: 'https://github.com/proximax-storage',
    npm: null
  },
  {
    id: 'zus',
    name: 'Zus',
    tickerSymbol: 'ZCN',
    description: 'A high-performance decentralized storage network with data privacy and security.',
    ucid: 3758,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'privacy', 'infrastructure'],
    network: 'Ethereum',
    website: 'https://www.zus.network/',
    github: 'https://github.com/0chain',
    npm: null
  }
];

export default STORAGE_CURRENCIES;
