/**
 * NY Exchange Offerings - Coinbase Index - Cryptocurrencies available on Coinbase NY Exchange
 * 
 * This list contains cryptocurrencies that are available for trading on Coinbase's
 * New York State cryptocurrency exchange. These offerings represent a curated selection
 * of digital assets that have been approved for trading in New York State through
 * Coinbase's platform under BitLicense and NYDFS regulatory framework.
 * 
 * This index excludes assets that are specifically restricted for NY residents,
 * such as DOGE (Dogecoin), SHIB (Shiba Inu), XMR (Monero), ZEC (Zcash), and other
 * privacy coins or assets not yet approved by NYDFS.
 * 
 * This index is used for NY exchange-specific displays, Coinbase integration features,
 * and regulatory-compliant currency selection interfaces.
 * 
 * Last Updated: December 2025
 * Source: Coinbase Digital Asset Disclosures, NYDFS Greenlist, and Coinbase regulatory filings
 */

export interface NYExchangeOfferingsCoinbaseItem {
  id: string;
  symbol: string;
  name: string;
}

export const NY_EXCHANGE_OFFERINGS_COINBASE: NYExchangeOfferingsCoinbaseItem[] = [
  { id: '0x', symbol: 'ZRX', name: '0x' },
  { id: '1inch-network', symbol: '1INCH', name: '1inch Network' },
  { id: 'aave', symbol: 'AAVE', name: 'Aave' },
  { id: 'adventure-gold', symbol: 'AGLD', name: 'Adventure Gold' },
  { id: 'aergo', symbol: 'AERGO', name: 'Aergo' },
  { id: 'aerodrome-finance', symbol: 'AERO', name: 'Aerodrome Finance' },
  { id: 'aioz-network', symbol: 'AIOZ', name: 'AIOZ Network' },
  { id: 'akash-network', symbol: 'AKT', name: 'Akash Network' },
  { id: 'alchemix', symbol: 'ALCX', name: 'Alchemix' },
  { id: 'alchemy-pay', symbol: 'ACH', name: 'Alchemy Pay' },
  { id: 'aleph-im', symbol: 'ALEPH', name: 'Aleph.im' }, //Aleph Cloud
  { id: 'algorand', symbol: 'ALGO', name: 'Algorand' },
  { id: 'my-neighbor-alice', symbol: 'ALICE', name: 'My Neighbor Alice' },
  { id: 'amp', symbol: 'AMP', name: 'Amp' },
  { id: 'ankr', symbol: 'ANKR', name: 'Ankr' },
  { id: 'apecoin', symbol: 'APE', name: 'ApeCoin' },
  { id: 'api3', symbol: 'API3', name: 'API3' },
  { id: 'aptos', symbol: 'APT', name: 'Aptos' },
  { id: 'arbitrum', symbol: 'ARB', name: 'Arbitrum' },
  { id: 'arpa', symbol: 'ARPA', name: 'ARPA' },
  { id: 'assemble', symbol: 'ASM', name: 'Assemble' },
  { id: 'atom', symbol: 'ATOM', name: 'Cosmos' },
  { id: 'bounce-token', symbol: 'AUCTION', name: 'Bounce Token' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche' },
  { id: 'aventus', symbol: 'AVT', name: 'Aventus' },
  { id: 'axie-infinity-shards', symbol: 'AXS', name: 'Axie Infinity Shards' },
  { id: 'badger', symbol: 'BADGER', name: 'BADGER' },
  { id: 'balancer', symbol: 'BAL', name: 'Balancer' },
  { id: 'bancor-network-token', symbol: 'BNT', name: 'Bancor Network Token' },
  { id: 'band-token', symbol: 'BAND', name: 'Band Token' },
  { id: 'basic-attention-token', symbol: 'BAT', name: 'Basic Attention Token' },
  { id: 'bitcoin-cash', symbol: 'BCH', name: 'Bitcoin Cash' },
  { id: 'biconomy', symbol: 'BICO', name: 'Biconomy' },
  { id: 'bluzelle', symbol: 'BLZ', name: 'Bluzelle' },
  { id: 'bonk', symbol: 'BONK', name: 'Bonk' },
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin' },
  { id: 'braintrust', symbol: 'BTRST', name: 'Braintrust' },
  { id: 'coin98', symbol: 'C98', name: 'Coin98' },
  { id: 'coinbase-wrapped-staked-eth', symbol: 'cbETH', name: 'Coinbase Wrapped Staked ETH' },
  { id: 'celo', symbol: 'CGLD', name: 'Celo' },
  { id: 'compound-governance-token', symbol: 'COMP', name: 'Compound' },
  { id: 'core', symbol: 'CORE', name: 'Core' }, //Corechain
  { id: 'crypto-com-coin', symbol: 'CRO', name: 'Crypto.com Coin' }, //Cronos
  { id: 'curve-dao-token', symbol: 'CRV', name: 'Curve' },
  { id: 'cartesi', symbol: 'CTSI', name: 'Cartesi' },
  { id: 'cryptex-finance', symbol: 'CTX', name: 'Cryptex Finance' },
  { id: 'civic', symbol: 'CVC', name: 'Civic' },
  { id: 'convex-finance', symbol: 'CVX', name: 'Convex Finance' },
  { id: 'dai', symbol: 'DAI', name: 'DAI Stablecoin' },
  { id: 'degen', symbol: 'DEGEN', name: 'Degen' },
  { id: 'dia', symbol: 'DIA', name: 'DIA' },
  { id: 'dogwifhat', symbol: 'WIF', name: 'dogwifhat' },
  { id: 'dogecoin', symbol: 'DOGE', name: 'Doge' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot' },
  { id: 'multiversx', symbol: 'EGLD', name: 'MultiversX' },
  { id: 'ethereum-name-service', symbol: 'ENS', name: 'Ethereum Name Service' },
  { id: 'ethereum-classic', symbol: 'ETC', name: 'Ethereum Classic' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum' },
  { id: 'freysa', symbol: 'FAI', name: 'Freysa' },
  { id: 'harvest-finance', symbol: 'FARM', name: 'Harvest Finance' },
  { id: 'fetch-ai', symbol: 'FET', name: 'Fetch' }, //Fetch AI Artificial Superintelligence
  { id: 'filecoin', symbol: 'FIL', name: 'Filecoin' },
  { id: 'flare', symbol: 'FLR', name: 'Flare' },
  { id: 'flow', symbol: 'FLOW', name: 'Flow' },
  { id: 'forta', symbol: 'FORT', name: 'Forta' },
  { id: 'fox-token', symbol: 'FOX', name: 'FOX Token' },
  { id: 'gravity', symbol: 'G', name: 'Gravity' },
  { id: 'goldfinch', symbol: 'GFI', name: 'Goldfinch' },
  { id: 'golem', symbol: 'GLM', name: 'Golem' },
  { id: 'gmt', symbol: 'GMT', name: 'GMT' },
  { id: 'gnosis', symbol: 'GNO', name: 'Gnosis' },
  { id: 'gods-unchained', symbol: 'GODS', name: 'Gods Unchained' },
  { id: 'the-graph', symbol: 'GRT', name: 'The Graph' },
  { id: 'gitcoin', symbol: 'GTC', name: 'Gitcoin' },
  { id: 'hedera', symbol: 'HBAR', name: 'Hedera' },
  { id: 'helium', symbol: 'HNT', name: 'Helium' },
  { id: 'dfinity', symbol: 'ICP', name: 'Dfinity' }, //Internet Computer
  { id: 'idex', symbol: 'IDEX', name: 'IDEX' },
  { id: 'illuvium', symbol: 'ILV', name: 'Illuvium' },
  { id: 'immutable-x', symbol: 'IMX', name: 'ImmutableX' },
  { id: 'index-cooperative', symbol: 'INDEX', name: 'Index Cooperative' },
  { id: 'injective', symbol: 'INJ', name: 'Injective' },
  { id: 'inverse-finance', symbol: 'INV', name: 'Inverse Finance' },
  { id: 'iotex', symbol: 'IOTX', name: 'IoTeX' },
  { id: 'jasmy', symbol: 'JASMY', name: 'Jasmy' },
  { id: 'kryll', symbol: 'KRL', name: 'kryll' },
  { id: 'kusama', symbol: 'KSM', name: 'Kusama' },
  { id: 'kyber-network', symbol: 'KNC', name: 'Kyber Network' },
  { id: 'lcx-token', symbol: 'LCX', name: 'LCX Token' },
  { id: 'lido-dao', symbol: 'LDO', name: 'Lido DAO' },
  { id: 'chainlink', symbol: 'LINK', name: 'ChainLink' },
  { id: 'livepeer', symbol: 'LPT', name: 'Livepeer' },
  { id: 'liquity', symbol: 'LQTY', name: 'Liquity' },
  { id: 'loopring', symbol: 'LRC', name: 'LoopringCoin' },
  { id: 'litecoin', symbol: 'LTC', name: 'Litecoin' },
  { id: 'decentraland', symbol: 'MANA', name: 'Decentraland' },
  { id: 'mask-network', symbol: 'MASK', name: 'Mask Network' },
  { id: 'measurable-data-token', symbol: 'MDT', name: 'Measurable Data Token' },
  { id: 'metis', symbol: 'METIS', name: 'Metis' },
  { id: 'melon', symbol: 'MLN', name: 'Melon' }, //Enzyme
  { id: 'marinade', symbol: 'MNDE', name: 'Marinade (MNDE)' },
  { id: 'mina', symbol: 'MINA', name: 'Mina' },
  { id: 'maker', symbol: 'MKR', name: 'Maker' },
  { id: 'moonwell', symbol: 'WELL', name: 'Moonwell' },
  { id: 'metaplex', symbol: 'MPLX', name: 'Metaplex' },
  { id: 'near-protocol', symbol: 'NEAR', name: 'NEAR Protocol' },
  { id: 'nkn', symbol: 'NKN', name: 'NKN' },
  { id: 'nomina', symbol: 'NOM', name: 'Nomina' },
  { id: 'numeraire', symbol: 'NMR', name: 'Numeraire' },
  { id: 'optimism', symbol: 'OP', name: 'Optimism' },
  { id: 'orca', symbol: 'ORCA', name: 'Orca' },
  { id: 'orchid-token', symbol: 'OXT', name: 'Orchid Token' },
  { id: 'origin-token', symbol: 'OGN', name: 'Origin Token' },
  { id: 'origin-trails', symbol: 'TRAC', name: 'Origin Trails' }, //Origin Trail
  { id: 'osmosis', symbol: 'OSMO', name: 'Osmosis' },
  { id: 'paxos-standard', symbol: 'PAX', name: 'Paxos Standard' },
  { id: 'paxos-gold', symbol: 'PAXG', name: 'Paxos Gold' },
  { id: 'paypal-usd', symbol: 'PYUSD', name: 'PayPal USD' },
  { id: 'pendle', symbol: 'PENDLE', name: 'Pendle' },
  { id: 'pepe', symbol: 'PEPE', name: 'Pepe' },
  { id: 'perpetual-protocol', symbol: 'PERP', name: 'Perpetual Protocol' },
  { id: 'pluton', symbol: 'PLU', name: 'Pluton' },
  { id: 'polkastarter', symbol: 'POLS', name: 'Polkastarter' },
  { id: 'polygon-ecosystem-token', symbol: 'POL', name: 'Polygon Ecosystem Token' },
  { id: 'powerledger', symbol: 'POWR', name: 'Powerledger' },
  { id: 'propy', symbol: 'PRO', name: 'Propy' },
  { id: 'pyth-network', symbol: 'PYTH', name: 'Pyth Network' },
  { id: 'quant', symbol: 'QNT', name: 'Quant' },
  { id: 'rarible', symbol: 'RARI', name: 'Rarible' },
  { id: 'render', symbol: 'RENDER', name: 'Render' },
  { id: 'request-network', symbol: 'REQ', name: 'Request Network' },
  { id: 'iexec-rlc', symbol: 'RLC', name: 'iExec RLC' },
  { id: 'ronin', symbol: 'RONIN', name: 'Ronin' },
  { id: 'oasis', symbol: 'ROSE', name: 'Oasis' },
  { id: 'safe', symbol: 'SAFE', name: 'Safe' },
  { id: 'the-sandbox', symbol: 'SAND', name: 'The Sandbox' },
  { id: 'stader', symbol: 'SD', name: 'Stader' },
  { id: 'sei-network', symbol: 'SEI', name: 'Sei' },
  { id: 'shiba-inu', symbol: 'SHIB', name: 'Shiba Inu' },
  { id: 'shping', symbol: 'SHPING', name: 'Shping' },
  { id: 'skale-labs', symbol: 'SKL', name: 'Skale Labs' },
  { id: 'sky', symbol: 'SKY', name: 'Sky' },
  { id: 'solana', symbol: 'SOL', name: 'Solana' },
  { id: 'spell', symbol: 'SPELL', name: 'Spell' },
  { id: 'subsquid', symbol: 'SQD', name: 'Subsquid' },
  { id: 'storj', symbol: 'STORJ', name: 'Storj' },
  { id: 'stacks', symbol: 'STX', name: 'Stacks' },
  { id: 'suku', symbol: 'SUKU', name: 'Suku' },
  { id: 'sui', symbol: 'SUI', name: 'Sui' },
  { id: 'super', symbol: 'SUPER', name: 'Super' }, //SuperVerse
  { id: 'maple-finance', symbol: 'SYRUP', name: 'Maple Finance' },
  { id: 'bittensor', symbol: 'TAO', name: 'Bittensor' },
  { id: 'tellor', symbol: 'TRB', name: 'Tellor' },
  { id: 'tru', symbol: 'TRU', name: 'TRU' },
  { id: 'uma', symbol: 'UMA', name: 'UMA Voting Token' },
  { id: 'uniswap', symbol: 'UNI', name: 'Uniswap' },
  { id: 'usd-coin', symbol: 'USDC', name: 'USD Coin' },
  { id: 'velodrome-finance', symbol: 'VELO', name: 'Velodrome Finance' },
  { id: 'vechain', symbol: 'VET', name: 'VeChain' },
  { id: 'vethor-token', symbol: 'VTHO', name: 'VeThor Token' },
  { id: 'stellar', symbol: 'XLM', name: 'Stellar' },
  { id: 'ripple', symbol: 'XRP', name: 'XRP' },
  { id: 'tezos', symbol: 'XTZ', name: 'Tezos' },
  { id: 'xyo-network', symbol: 'XYO', name: 'XYO Network' },
  { id: 'yearn-finance', symbol: 'YFI', name: 'yearn.finance' },
  { id: 'zcash', symbol: 'ZEC', name: 'Zcash' }
];

export default NY_EXCHANGE_OFFERINGS_COINBASE;
