/**
 * NY Exchange Offerings - Coinbase Index - Cryptocurrencies available on Coinbase NY Exchange
 * 
 * This list contains cryptocurrencies that are available for trading on Coinbase's
 * New York State cryptocurrency exchange. These offerings represent a curated selection
 * of digital assets that have been approved for trading in New York State through
 * Coinbase's platform under BitLicense and NYDFS regulatory framework.
 * 
 * This index excludes assets that are specifically restricted for NY residents,
 * such as DOGE (Dogecoin), SHIB (Shiba Inu), XMR (Monero), ZEC (Zcash), and other
 * privacy coins or assets not yet approved by NYDFS.
 * 
 * This index is used for NY exchange-specific displays, Coinbase integration features,
 * and regulatory-compliant currency selection interfaces.
 * 
 * Last Updated: December 2025
 * Source: Coinbase Digital Asset Disclosures, NYDFS Greenlist, and Coinbase regulatory filings
 */

export type CurrencyType = 'coin' | 'token';
export type ConsensusType = 'proof-of-stake' | 'proof-of-work' | 'proof-of-authority' | 'delegated-proof-of-stake' | 'nominated-proof-of-stake' | 'liquid-proof-of-stake' | 'byzantine-fault-tolerance' | 'proof-of-transfer' | 'proof-of-coverage' | 'proof-of-space-and-time' | 'proof-of-replication' | 'token' | 'hybrid' | 'optimistic-rollup' | 'zk-rollup';
export type CurrencyClass = 'layer-1' | 'layer-2' | 'defi' | 'dex' | 'nft' | 'gaming' | 'metaverse' | 'oracle' | 'privacy' | 'meme' | 'staking' | 'governance' | 'lending' | 'data' | 'infrastructure' | 'smart-contract-platform' | 'exchange-token' | 'ai' | 'storage' | 'payment' | 'social' | 'interoperability' | 'sports' | 'iot' | 'yield-farming' | 'derivatives' | 'stablecoin';

export interface NYExchangeOfferingsCoinbaseItem {
  id: string;
  symbol: string;
  name: string;
  description: string;
  ucid: number;
  type: CurrencyType;
  consensusType: ConsensusType;
  class: CurrencyClass[];
  website: string | null;
  github: string | null;
  npm: string | null;
}

export const NY_EXCHANGE_OFFERINGS_COINBASE: NYExchangeOfferingsCoinbaseItem[] = [
  {
    id: '0x',
    symbol: 'ZRX',
    name: '0x',
    description: 'An open protocol enabling peer-to-peer exchange of ERC-20 tokens on Ethereum.',
    ucid: 1896,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'infrastructure'],
    website: 'https://0x.org',
    github: 'https://github.com/0xProject',
    npm: 'https://www.npmjs.com/package/0x.js'
  },
  {
    id: '1inch-network',
    symbol: '1INCH',
    name: '1inch Network',
    description: 'A DEX aggregator that finds the best prices across multiple decentralized exchanges.',
    ucid: 8104,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://1inch.io',
    github: 'https://github.com/1inch',
    npm: 'https://www.npmjs.com/package/@1inch/limit-order-protocol'
  },
  {
    id: 'aave',
    symbol: 'AAVE',
    name: 'Aave',
    description: 'A decentralized lending protocol that allows users to lend and borrow cryptocurrencies without intermediaries.',
    ucid: 7278,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://aave.com',
    github: 'https://github.com/aave',
    npm: 'https://www.npmjs.com/package/@aave/protocol-js'
  },
  {
    id: 'adventure-gold',
    symbol: 'AGLD',
    name: 'Adventure Gold',
    description: 'An ERC-20 token for metaverse gaming and NFT projects related to the Loot ecosystem.',
    ucid: 11568,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'nft', 'metaverse'],
    website: 'https://www.lootproject.com',
    github: null,
    npm: null
  },
  {
    id: 'aergo',
    symbol: 'AERGO',
    name: 'Aergo',
    description: 'An enterprise-ready blockchain platform with SQL smart contracts and hybrid architecture.',
    ucid: 3637,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform', 'infrastructure'],
    website: 'https://www.aergo.io',
    github: 'https://github.com/aergoio',
    npm: 'https://www.npmjs.com/package/@herajs/client'
  },
  {
    id: 'aerodrome-finance',
    symbol: 'AERO',
    name: 'Aerodrome Finance',
    description: 'A next-generation AMM designed to be the central liquidity hub on Base.',
    ucid: 29270,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'layer-2'],
    website: 'https://aerodrome.finance',
    github: null,
    npm: null
  },
  {
    id: 'aioz-network',
    symbol: 'AIOZ',
    name: 'AIOZ Network',
    description: 'A decentralized content delivery network powered by blockchain for streaming and storage.',
    ucid: 9104,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['infrastructure', 'storage', 'data'],
    website: 'https://aioz.network',
    github: 'https://github.com/AIOZNetwork',
    npm: null
  },
  {
    id: 'akash-network',
    symbol: 'AKT',
    name: 'Akash Network',
    description: 'A decentralized cloud computing marketplace for deploying applications.',
    ucid: 7431,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['infrastructure', 'data'],
    website: 'https://akash.network',
    github: 'https://github.com/akash-network',
    npm: null
  },
  {
    id: 'alchemix',
    symbol: 'ALCX',
    name: 'Alchemix',
    description: 'A future-yield-backed synthetic asset platform enabling self-repaying loans.',
    ucid: 8613,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://alchemix.fi',
    github: 'https://github.com/alchemix-finance',
    npm: null
  },
  {
    id: 'alchemy-pay',
    symbol: 'ACH',
    name: 'Alchemy Pay',
    description: 'A payment solution bridging fiat and crypto for seamless transactions.',
    ucid: 6958,
    type: 'token',
    consensusType: 'token',
    class: ['payment', 'infrastructure'],
    website: 'https://alchemypay.org',
    github: 'https://github.com/alchemyplatform',
    npm: null
  },
  {
    id: 'aleph-im',
    symbol: 'ALEPH',
    name: 'Aleph.im',
    description: 'A cross-blockchain decentralized cloud storage and computing network.',
    ucid: 5567,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure', 'data'],
    website: 'https://aleph.im',
    github: 'https://github.com/aleph-im',
    npm: 'https://www.npmjs.com/package/aleph-js'
  },
  {
    id: 'algorand',
    symbol: 'ALGO',
    name: 'Algorand',
    description: 'A pure proof-of-stake blockchain focused on scalability, security, and decentralization.',
    ucid: 4030,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://algorand.com',
    github: 'https://github.com/algorand',
    npm: 'https://www.npmjs.com/package/algosdk'
  },
  {
    id: 'my-neighbor-alice',
    symbol: 'ALICE',
    name: 'My Neighbor Alice',
    description: 'A multiplayer builder game where players build virtual lands and interact in a social metaverse.',
    ucid: 8766,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'metaverse', 'nft'],
    website: 'https://www.myneighboralice.com',
    github: null,
    npm: null
  },
  {
    id: 'amp',
    symbol: 'AMP',
    name: 'Amp',
    description: 'A digital collateral token designed to facilitate instant, verifiable assurances for value transfer.',
    ucid: 6945,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'payment'],
    website: 'https://amptoken.org',
    github: 'https://github.com/amptoken',
    npm: null
  },
  {
    id: 'ankr',
    symbol: 'ANKR',
    name: 'Ankr',
    description: 'A decentralized web3 infrastructure provider offering node services and staking solutions.',
    ucid: 3783,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'staking'],
    website: 'https://www.ankr.com',
    github: 'https://github.com/Ankr-network',
    npm: 'https://www.npmjs.com/package/@ankr.com/ankr.js'
  },
  {
    id: 'apecoin',
    symbol: 'APE',
    name: 'ApeCoin',
    description: 'The governance and utility token for the APE ecosystem and Bored Ape Yacht Club.',
    ucid: 18876,
    type: 'token',
    consensusType: 'token',
    class: ['governance', 'nft', 'metaverse'],
    website: 'https://apecoin.com',
    github: null,
    npm: null
  },
  {
    id: 'api3',
    symbol: 'API3',
    name: 'API3',
    description: 'A decentralized API network enabling smart contracts to access off-chain data through first-party oracles.',
    ucid: 7737,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure', 'data'],
    website: 'https://api3.org',
    github: 'https://github.com/api3dao',
    npm: 'https://www.npmjs.com/package/@api3/airnode-node'
  },
  {
    id: 'aptos',
    symbol: 'APT',
    name: 'Aptos',
    description: 'A layer-1 blockchain using the Move programming language with focus on safety and scalability.',
    ucid: 21794,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://aptoslabs.com',
    github: 'https://github.com/aptos-labs',
    npm: 'https://www.npmjs.com/package/aptos'
  },
  {
    id: 'arbitrum',
    symbol: 'ARB',
    name: 'Arbitrum',
    description: 'An Ethereum layer-2 scaling solution using optimistic rollups for faster and cheaper transactions.',
    ucid: 11841,
    type: 'token',
    consensusType: 'optimistic-rollup',
    class: ['layer-2', 'infrastructure', 'governance'],
    website: 'https://arbitrum.io',
    github: 'https://github.com/OffchainLabs',
    npm: 'https://www.npmjs.com/package/@arbitrum/sdk'
  },
  {
    id: 'arpa',
    symbol: 'ARPA',
    name: 'ARPA',
    description: 'A privacy-preserving computation network for blockchains using secure multi-party computation.',
    ucid: 4039,
    type: 'token',
    consensusType: 'token',
    class: ['privacy', 'infrastructure'],
    website: 'https://arpachain.io',
    github: 'https://github.com/ARPA-Network',
    npm: null
  },
  {
    id: 'assemble',
    symbol: 'ASM',
    name: 'Assemble',
    description: 'A global point integration platform that aggregates and utilizes points from various services.',
    ucid: 7295,
    type: 'token',
    consensusType: 'token',
    class: ['payment', 'data'],
    website: 'https://assembleprotocol.io',
    github: null,
    npm: null
  },
  {
    id: 'atom',
    symbol: 'ATOM',
    name: 'Cosmos',
    description: 'A decentralized network of independent blockchains enabling interoperability through IBC protocol.',
    ucid: 3794,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'interoperability', 'smart-contract-platform'],
    website: 'https://cosmos.network',
    github: 'https://github.com/cosmos',
    npm: 'https://www.npmjs.com/package/@cosmjs/stargate'
  },
  {
    id: 'bounce-token',
    symbol: 'AUCTION',
    name: 'Bounce Token',
    description: 'A decentralized auction protocol for token sales and NFT auctions.',
    ucid: 7004,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'nft'],
    website: 'https://bounce.finance',
    github: 'https://github.com/bouncefinance',
    npm: null
  },
  {
    id: 'avalanche-2',
    symbol: 'AVAX',
    name: 'Avalanche',
    description: 'A high-performance smart contract platform with sub-second finality and low fees.',
    ucid: 5805,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://avax.network',
    github: 'https://github.com/ava-labs',
    npm: 'https://www.npmjs.com/package/avalanche'
  },
  {
    id: 'aventus',
    symbol: 'AVT',
    name: 'Aventus',
    description: 'A blockchain-based ticketing solution preventing fraud and scalping in event ticketing.',
    ucid: 1856,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'nft'],
    website: 'https://aventus.io',
    github: 'https://github.com/AventusProtocolFoundation',
    npm: null
  },
  {
    id: 'axie-infinity-shards',
    symbol: 'AXS',
    name: 'Axie Infinity Shards',
    description: 'The governance token for Axie Infinity, a play-to-earn blockchain game.',
    ucid: 6783,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'nft', 'governance', 'metaverse'],
    website: 'https://axieinfinity.com',
    github: 'https://github.com/axieinfinity',
    npm: null
  },
  {
    id: 'badger',
    symbol: 'BADGER',
    name: 'BADGER',
    description: 'A DeFi platform focused on bringing Bitcoin to DeFi through tokenized BTC products.',
    ucid: 7859,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    website: 'https://badger.com',
    github: 'https://github.com/Badger-Finance',
    npm: null
  },
  {
    id: 'balancer',
    symbol: 'BAL',
    name: 'Balancer',
    description: 'An automated portfolio manager and liquidity provider with flexible pool ratios.',
    ucid: 5728,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://balancer.fi',
    github: 'https://github.com/balancer',
    npm: 'https://www.npmjs.com/package/@balancer-labs/sdk'
  },
  {
    id: 'bancor-network-token',
    symbol: 'BNT',
    name: 'Bancor Network Token',
    description: 'A decentralized trading protocol with automated market-making and single-sided liquidity provision.',
    ucid: 1727,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex'],
    website: 'https://bancor.network',
    github: 'https://github.com/bancorprotocol',
    npm: 'https://www.npmjs.com/package/@bancor/sdk'
  },
  {
    id: 'band-token',
    symbol: 'BAND',
    name: 'Band Token',
    description: 'A cross-chain data oracle platform aggregating and connecting real-world data to smart contracts.',
    ucid: 4679,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure', 'data'],
    website: 'https://bandprotocol.com',
    github: 'https://github.com/bandprotocol',
    npm: 'https://www.npmjs.com/package/@bandprotocol/bandchain.js'
  },
  {
    id: 'basic-attention-token',
    symbol: 'BAT',
    name: 'Basic Attention Token',
    description: 'A utility token powering the Brave browser ecosystem for digital advertising.',
    ucid: 1697,
    type: 'token',
    consensusType: 'token',
    class: ['payment', 'social'],
    website: 'https://basicattentiontoken.org',
    github: 'https://github.com/brave-intl',
    npm: null
  },
  {
    id: 'bitcoin-cash',
    symbol: 'BCH',
    name: 'Bitcoin Cash',
    description: 'A peer-to-peer electronic cash system forked from Bitcoin with larger block sizes.',
    ucid: 1831,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoincash.org',
    github: 'https://github.com/bitcoincashorg',
    npm: 'https://www.npmjs.com/package/@psf/bitcoincashjs-lib'
  },
  {
    id: 'biconomy',
    symbol: 'BICO',
    name: 'Biconomy',
    description: 'A multichain relayer infrastructure enabling gasless transactions and simplified UX.',
    ucid: 9543,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'interoperability'],
    website: 'https://biconomy.io',
    github: 'https://github.com/bcnmy',
    npm: 'https://www.npmjs.com/package/@biconomy/mexa'
  },
  {
    id: 'bluzelle',
    symbol: 'BLZ',
    name: 'Bluzelle',
    description: 'A decentralized storage network for the creator economy with NFT storage solutions.',
    ucid: 2505,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'nft', 'infrastructure'],
    website: 'https://bluzelle.com',
    github: 'https://github.com/bluzelle',
    npm: 'https://www.npmjs.com/package/@bluzelle/sdk-js'
  },
  {
    id: 'bonk',
    symbol: 'BONK',
    name: 'Bonk',
    description: 'A community-driven meme coin on Solana ecosystem.',
    ucid: 23095,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://bonkcoin.com',
    github: null,
    npm: null
  },
  {
    id: 'bitcoin',
    symbol: 'BTC',
    name: 'Bitcoin',
    description: 'The first decentralized cryptocurrency, serving as digital gold and a peer-to-peer electronic cash system.',
    ucid: 1,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoin.org',
    github: 'https://github.com/bitcoin',
    npm: 'https://www.npmjs.com/package/bitcoinjs-lib'
  },
  {
    id: 'braintrust',
    symbol: 'BTRST',
    name: 'Braintrust',
    description: 'A decentralized talent network connecting skilled professionals with organizations.',
    ucid: 11394,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'governance'],
    website: 'https://www.usebraintrust.com',
    github: null,
    npm: null
  },
  {
    id: 'coin98',
    symbol: 'C98',
    name: 'Coin98',
    description: 'A DeFi platform and multi-chain wallet enabling cross-chain swaps and yield farming.',
    ucid: 10903,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'interoperability'],
    website: 'https://coin98.com',
    github: 'https://github.com/coin98',
    npm: null
  },
  {
    id: 'coinbase-wrapped-staked-eth',
    symbol: 'cbETH',
    name: 'Coinbase Wrapped Staked ETH',
    description: 'A liquid staking token representing staked ETH on Coinbase with accruing rewards.',
    ucid: 21535,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking'],
    website: 'https://www.coinbase.com/cbeth',
    github: null,
    npm: null
  },
  {
    id: 'celo',
    symbol: 'CGLD',
    name: 'Celo',
    description: 'A mobile-first blockchain platform focused on financial inclusion with stablecoin infrastructure.',
    ucid: 5567,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform', 'payment'],
    website: 'https://celo.org',
    github: 'https://github.com/celo-org',
    npm: 'https://www.npmjs.com/package/@celo/contractkit'
  },
  {
    id: 'compound-governance-token',
    symbol: 'COMP',
    name: 'Compound',
    description: 'The governance token for Compound, an algorithmic money market protocol.',
    ucid: 5692,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://compound.finance',
    github: 'https://github.com/compound-finance',
    npm: 'https://www.npmjs.com/package/@compound-finance/compound-js'
  },
  {
    id: 'core',
    symbol: 'CORE',
    name: 'Core',
    description: 'A layer-1 blockchain combining Bitcoin mining security with EVM compatibility.',
    ucid: 23254,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://coredao.org',
    github: 'https://github.com/coredao-org',
    npm: null
  },
  {
    id: 'crypto-com-coin',
    symbol: 'CRO',
    name: 'Crypto.com Coin',
    description: 'The native cryptocurrency of Cronos Chain, an EVM-compatible blockchain.',
    ucid: 3635,
    type: 'coin',
    consensusType: 'proof-of-authority',
    class: ['layer-1', 'payment', 'exchange-token'],
    website: 'https://cronos.org',
    github: 'https://github.com/crypto-org-chain',
    npm: null
  },
  {
    id: 'curve-dao-token',
    symbol: 'CRV',
    name: 'Curve',
    description: 'A DEX optimized for stablecoin swaps with low slippage and efficient liquidity.',
    ucid: 6538,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://curve.fi',
    github: 'https://github.com/curvefi',
    npm: 'https://www.npmjs.com/package/@curvefi/api'
  },
  {
    id: 'cartesi',
    symbol: 'CTSI',
    name: 'Cartesi',
    description: 'A layer-2 platform enabling complex computations using Linux infrastructure in smart contracts.',
    ucid: 5444,
    type: 'token',
    consensusType: 'token',
    class: ['layer-2', 'infrastructure'],
    website: 'https://cartesi.io',
    github: 'https://github.com/cartesi',
    npm: 'https://www.npmjs.com/package/@cartesi/sdk'
  },
  {
    id: 'cryptex-finance',
    symbol: 'CTX',
    name: 'Cryptex Finance',
    description: 'A protocol for creating and trading index tokens tracking crypto market sectors.',
    ucid: 9025,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    website: 'https://cryptex.finance',
    github: 'https://github.com/cryptexfinance',
    npm: null
  },
  {
    id: 'civic',
    symbol: 'CVC',
    name: 'Civic',
    description: 'A decentralized identity verification protocol enabling secure and private identity management.',
    ucid: 1816,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://www.civic.com',
    github: 'https://github.com/civicteam',
    npm: 'https://www.npmjs.com/package/@civic/ethereum-gateway-react'
  },
  {
    id: 'convex-finance',
    symbol: 'CVX',
    name: 'Convex Finance',
    description: 'A platform for boosting Curve Finance yields through tokenized veCRV positions.',
    ucid: 9903,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'yield-farming'],
    website: 'https://www.convexfinance.com',
    github: 'https://github.com/convex-eth',
    npm: null
  },
  {
    id: 'dai',
    symbol: 'DAI',
    name: 'DAI Stablecoin',
    description: 'A decentralized stablecoin pegged to USD and backed by crypto collateral.',
    ucid: 2308,
    type: 'token',
    consensusType: 'token',
    class: ['stablecoin', 'defi'],
    website: 'https://makerdao.com',
    github: 'https://github.com/makerdao',
    npm: 'https://www.npmjs.com/package/@makerdao/dai'
  },
  {
    id: 'degen',
    symbol: 'DEGEN',
    name: 'Degen',
    description: 'A community token for the Farcaster social network ecosystem.',
    ucid: 30950,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'meme'],
    website: 'https://www.degen.tips',
    github: null,
    npm: null
  },
  {
    id: 'dia',
    symbol: 'DIA',
    name: 'DIA',
    description: 'A cross-chain oracle platform providing transparent and customizable data feeds.',
    ucid: 6138,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'data', 'infrastructure'],
    website: 'https://diadata.org',
    github: 'https://github.com/diadata-org',
    npm: null
  },
  {
    id: 'dogwifhat',
    symbol: 'WIF',
    name: 'dogwifhat',
    description: 'A meme coin on Solana featuring a dog with a hat.',
    ucid: 28752,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://dogwifhat.com',
    github: null,
    npm: null
  },
  {
    id: 'dogecoin',
    symbol: 'DOGE',
    name: 'Doge',
    description: 'The original meme cryptocurrency featuring the Shiba Inu dog from the Doge meme.',
    ucid: 74,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'meme', 'payment'],
    website: 'https://dogecoin.com',
    github: 'https://github.com/dogecoin',
    npm: null
  },
  {
    id: 'polkadot',
    symbol: 'DOT',
    name: 'Polkadot',
    description: 'A multi-chain protocol enabling cross-blockchain transfers and scalability through parachains.',
    ucid: 6636,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['layer-1', 'interoperability', 'smart-contract-platform'],
    website: 'https://polkadot.network',
    github: 'https://github.com/paritytech/polkadot',
    npm: 'https://www.npmjs.com/package/@polkadot/api'
  },
  {
    id: 'multiversx',
    symbol: 'EGLD',
    name: 'MultiversX',
    description: 'A highly scalable blockchain platform using adaptive state sharding for performance.',
    ucid: 6892,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://multiversx.com',
    github: 'https://github.com/multiversx',
    npm: 'https://www.npmjs.com/package/@multiversx/sdk-core'
  },
  {
    id: 'ethereum-name-service',
    symbol: 'ENS',
    name: 'Ethereum Name Service',
    description: 'A decentralized naming system for Ethereum addresses and decentralized websites.',
    ucid: 13855,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'governance'],
    website: 'https://ens.domains',
    github: 'https://github.com/ensdomains',
    npm: 'https://www.npmjs.com/package/@ensdomains/ensjs'
  },
  {
    id: 'ethereum-classic',
    symbol: 'ETC',
    name: 'Ethereum Classic',
    description: 'The original Ethereum blockchain maintaining code immutability after the DAO hack.',
    ucid: 1321,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ethereumclassic.org',
    github: 'https://github.com/ethereumclassic',
    npm: null
  },
  {
    id: 'ethereum',
    symbol: 'ETH',
    name: 'Ethereum',
    description: 'The leading smart contract platform enabling decentralized applications and DeFi.',
    ucid: 1027,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ethereum.org',
    github: 'https://github.com/ethereum',
    npm: 'https://www.npmjs.com/package/ethers'
  },
  {
    id: 'freysa',
    symbol: 'FAI',
    name: 'Freysa',
    description: 'An AI-focused cryptocurrency project with limited public information.',
    ucid: 32000,
    type: 'token',
    consensusType: 'token',
    class: ['ai'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'harvest-finance',
    symbol: 'FARM',
    name: 'Harvest Finance',
    description: 'An automated yield farming protocol that optimizes returns across DeFi platforms.',
    ucid: 6859,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'yield-farming'],
    website: 'https://harvest.finance',
    github: 'https://github.com/harvest-finance',
    npm: null
  },
  {
    id: 'fetch-ai',
    symbol: 'FET',
    name: 'Fetch',
    description: 'An AI-focused blockchain platform for autonomous economic agents and machine learning.',
    ucid: 3773,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'ai', 'data'],
    website: 'https://fetch.ai',
    github: 'https://github.com/fetchai',
    npm: 'https://www.npmjs.com/package/fetchai'
  },
  {
    id: 'filecoin',
    symbol: 'FIL',
    name: 'Filecoin',
    description: 'A decentralized storage network incentivizing storage providers with cryptocurrency rewards.',
    ucid: 2280,
    type: 'coin',
    consensusType: 'proof-of-replication',
    class: ['storage', 'infrastructure'],
    website: 'https://filecoin.io',
    github: 'https://github.com/filecoin-project',
    npm: '@filecoin-shipyard/js-filecoin-api-client'
  },
  {
    id: 'flare',
    symbol: 'FLR',
    name: 'Flare',
    description: 'A layer-1 blockchain bringing smart contract functionality to XRP Ledger and other networks.',
    ucid: 7950,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform', 'interoperability'],
    website: 'https://flare.network',
    github: 'https://github.com/flare-foundation',
    npm: null
  },
  {
    id: 'flow',
    symbol: 'FLOW',
    name: 'Flow',
    description: 'A fast and developer-friendly blockchain built for NFTs, games, and consumer applications.',
    ucid: 4558,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'nft', 'gaming', 'smart-contract-platform'],
    website: 'https://flow.com',
    github: 'https://github.com/onflow',
    npm: 'https://www.npmjs.com/package/@onflow/fcl'
  },
  {
    id: 'forta',
    symbol: 'FORT',
    name: 'Forta',
    description: 'A decentralized monitoring network for detecting threats and anomalies on blockchain.',
    ucid: 18877,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://forta.org',
    github: 'https://github.com/forta-network',
    npm: 'https://www.npmjs.com/package/forta-agent'
  },
  {
    id: 'fox-token',
    symbol: 'FOX',
    name: 'FOX Token',
    description: 'The governance token for ShapeShift DAO, a decentralized crypto trading platform.',
    ucid: 8204,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance', 'dex'],
    website: 'https://shapeshift.com',
    github: 'https://github.com/shapeshift',
    npm: null
  },
  {
    id: 'gravity',
    symbol: 'G',
    name: 'Gravity',
    description: 'A cross-chain communication and data oracle network connecting blockchains.',
    ucid: 4305,
    type: 'token',
    consensusType: 'token',
    class: ['interoperability', 'oracle', 'infrastructure'],
    website: 'https://gravity.tech',
    github: 'https://github.com/Gravity-Tech',
    npm: null
  },
  {
    id: 'goldfinch',
    symbol: 'GFI',
    name: 'Goldfinch',
    description: 'A decentralized credit protocol providing crypto loans without collateral.',
    ucid: 11825,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://goldfinch.finance',
    github: 'https://github.com/goldfinch-eng',
    npm: null
  },
  {
    id: 'golem',
    symbol: 'GLM',
    name: 'Golem',
    description: 'A decentralized marketplace for computing power enabling users to rent out their machines.',
    ucid: 1455,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://www.golem.network',
    github: 'https://github.com/golemfactory',
    npm: 'https://www.npmjs.com/package/@golem-sdk/golem-js'
  },
  {
    id: 'gmt',
    symbol: 'GMT',
    name: 'GMT',
    description: 'The governance token for STEPN, a move-to-earn fitness and lifestyle app.',
    ucid: 18069,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'social', 'governance'],
    website: 'https://stepn.com',
    github: null,
    npm: null
  },
  {
    id: 'gnosis',
    symbol: 'GNO',
    name: 'Gnosis',
    description: 'A platform for prediction markets and decentralized infrastructure services.',
    ucid: 1659,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance', 'infrastructure'],
    website: 'https://gnosis.io',
    github: 'https://github.com/gnosis',
    npm: 'https://www.npmjs.com/package/@gnosis.pm/safe-core-sdk'
  },
  {
    id: 'gods-unchained',
    symbol: 'GODS',
    name: 'Gods Unchained',
    description: 'A play-to-earn trading card game built on blockchain with NFT cards.',
    ucid: 9674,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'nft'],
    website: 'https://godsunchained.com',
    github: 'https://github.com/immutable',
    npm: null
  },
  {
    id: 'the-graph',
    symbol: 'GRT',
    name: 'The Graph',
    description: 'A decentralized protocol for indexing and querying blockchain data.',
    ucid: 6719,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data', 'oracle'],
    website: 'https://thegraph.com',
    github: 'https://github.com/graphprotocol',
    npm: 'https://www.npmjs.com/package/@graphprotocol/graph-cli'
  },
  {
    id: 'gitcoin',
    symbol: 'GTC',
    name: 'Gitcoin',
    description: 'A platform for funding and building open-source software with community governance.',
    ucid: 11713,
    type: 'token',
    consensusType: 'token',
    class: ['governance', 'social'],
    website: 'https://gitcoin.co',
    github: 'https://github.com/gitcoinco',
    npm: null
  },
  {
    id: 'hedera',
    symbol: 'HBAR',
    name: 'Hedera',
    description: 'A fast and secure public network using hashgraph consensus for enterprise applications.',
    ucid: 4642,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://hedera.com',
    github: 'https://github.com/hashgraph',
    npm: 'https://www.npmjs.com/package/@hashgraph/sdk'
  },
  {
    id: 'helium',
    symbol: 'HNT',
    name: 'Helium',
    description: 'A decentralized wireless network for IoT devices using proof-of-coverage consensus.',
    ucid: 5665,
    type: 'coin',
    consensusType: 'proof-of-coverage',
    class: ['layer-1', 'iot', 'infrastructure'],
    website: 'https://www.helium.com',
    github: 'https://github.com/helium',
    npm: 'https://www.npmjs.com/package/@helium/http'
  },
  {
    id: 'dfinity',
    symbol: 'ICP',
    name: 'Dfinity',
    description: 'A blockchain-based decentralized cloud computing platform running at web speed.',
    ucid: 8916,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform', 'infrastructure'],
    website: 'https://dfinity.org',
    github: 'https://github.com/dfinity',
    npm: 'https://www.npmjs.com/package/@dfinity/agent'
  },
  {
    id: 'idex',
    symbol: 'IDEX',
    name: 'IDEX',
    description: 'A hybrid decentralized exchange combining the speed of centralized exchanges with blockchain settlement.',
    ucid: 3928,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://idex.io',
    github: 'https://github.com/idexio',
    npm: 'https://www.npmjs.com/package/@idexio/idex-sdk'
  },
  {
    id: 'illuvium',
    symbol: 'ILV',
    name: 'Illuvium',
    description: 'An open-world RPG game built on Ethereum with NFT creatures and play-to-earn mechanics.',
    ucid: 8719,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'nft', 'metaverse'],
    website: 'https://illuvium.io',
    github: 'https://github.com/IlluviumGame',
    npm: null
  },
  {
    id: 'immutable-x',
    symbol: 'IMX',
    name: 'ImmutableX',
    description: 'A layer-2 scaling solution for NFTs on Ethereum with zero gas fees.',
    ucid: 10603,
    type: 'token',
    consensusType: 'zk-rollup',
    class: ['layer-2', 'nft', 'infrastructure'],
    website: 'https://www.immutable.com',
    github: 'https://github.com/immutable',
    npm: 'https://www.npmjs.com/package/@imtbl/core-sdk'
  },
  {
    id: 'index-cooperative',
    symbol: 'INDEX',
    name: 'Index Cooperative',
    description: 'A decentralized protocol for creating and managing crypto index products.',
    ucid: 7402,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    website: 'https://indexcoop.com',
    github: 'https://github.com/IndexCoop',
    npm: null
  },
  {
    id: 'injective',
    symbol: 'INJ',
    name: 'Injective',
    description: 'A layer-1 blockchain built for finance with decentralized orderbook exchange.',
    ucid: 7226,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'dex', 'defi'],
    website: 'https://injective.com',
    github: 'https://github.com/InjectiveLabs',
    npm: 'https://www.npmjs.com/package/@injectivelabs/sdk-ts'
  },
  {
    id: 'inverse-finance',
    symbol: 'INV',
    name: 'Inverse Finance',
    description: 'A decentralized autonomous organization for DeFi banking and synthetic assets.',
    ucid: 8482,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://inverse.finance',
    github: 'https://github.com/InverseFinance',
    npm: null
  },
  {
    id: 'iotex',
    symbol: 'IOTX',
    name: 'IoTeX',
    description: 'A blockchain platform connecting IoT devices with decentralized applications.',
    ucid: 2777,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'iot', 'infrastructure'],
    website: 'https://iotex.io',
    github: 'https://github.com/iotexproject',
    npm: 'https://www.npmjs.com/package/iotex-antenna'
  },
  {
    id: 'jasmy',
    symbol: 'JASMY',
    name: 'Jasmy',
    description: 'A Japanese IoT platform democratizing data ownership through blockchain.',
    ucid: 8425,
    type: 'token',
    consensusType: 'token',
    class: ['iot', 'data', 'infrastructure'],
    website: 'https://www.jasmy.co.jp',
    github: null,
    npm: null
  },
  {
    id: 'kryll',
    symbol: 'KRL',
    name: 'kryll',
    description: 'An automated crypto trading platform with strategy building and backtesting tools.',
    ucid: 2949,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'data'],
    website: 'https://kryll.io',
    github: 'https://github.com/Kryll-io',
    npm: null
  },
  {
    id: 'kusama',
    symbol: 'KSM',
    name: 'Kusama',
    description: 'A canary network for Polkadot enabling experimental blockchain development.',
    ucid: 5034,
    type: 'coin',
    consensusType: 'nominated-proof-of-stake',
    class: ['layer-1', 'interoperability', 'smart-contract-platform'],
    website: 'https://kusama.network',
    github: 'https://github.com/paritytech/polkadot',
    npm: 'https://www.npmjs.com/package/@polkadot/api'
  },
  {
    id: 'kyber-network',
    symbol: 'KNC',
    name: 'Kyber Network',
    description: 'A hub for liquidity protocols that aggregates liquidity from various sources.',
    ucid: 1982,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://kyber.network',
    github: 'https://github.com/KyberNetwork',
    npm: 'https://www.npmjs.com/package/@kybernetwork/ks-sdk-core'
  },
  {
    id: 'lcx-token',
    symbol: 'LCX',
    name: 'LCX Token',
    description: 'A regulated security token exchange platform based in Liechtenstein.',
    ucid: 3766,
    type: 'token',
    consensusType: 'token',
    class: ['exchange-token', 'defi'],
    website: 'https://www.lcx.com',
    github: null,
    npm: null
  },
  {
    id: 'lido-dao',
    symbol: 'LDO',
    name: 'Lido DAO',
    description: 'The governance token for Lido, a liquid staking protocol for Ethereum and other chains.',
    ucid: 8000,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking', 'governance'],
    website: 'https://lido.fi',
    github: 'https://github.com/lidofinance',
    npm: 'https://www.npmjs.com/package/@lido-sdk/contracts'
  },
  {
    id: 'chainlink',
    symbol: 'LINK',
    name: 'ChainLink',
    description: 'A decentralized oracle network providing real-world data to smart contracts.',
    ucid: 1975,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure', 'data'],
    website: 'https://chain.link',
    github: 'https://github.com/smartcontractkit',
    npm: 'https://www.npmjs.com/package/@chainlink/contracts'
  },
  {
    id: 'livepeer',
    symbol: 'LPT',
    name: 'Livepeer',
    description: 'A decentralized video streaming network for cost-effective video transcoding.',
    ucid: 3640,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://livepeer.org',
    github: 'https://github.com/livepeer',
    npm: 'https://www.npmjs.com/package/@livepeer/sdk'
  },
  {
    id: 'liquity',
    symbol: 'LQTY',
    name: 'Liquity',
    description: 'A decentralized borrowing protocol offering interest-free loans against ETH collateral.',
    ucid: 8967,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://www.liquity.org',
    github: 'https://github.com/liquity',
    npm: 'https://www.npmjs.com/package/@liquity/lib-base'
  },
  {
    id: 'loopring',
    symbol: 'LRC',
    name: 'LoopringCoin',
    description: 'A zkRollup Layer 2 protocol for building high-performance decentralized exchanges.',
    ucid: 1934,
    type: 'token',
    consensusType: 'zk-rollup',
    class: ['layer-2', 'dex', 'infrastructure'],
    website: 'https://loopring.org',
    github: 'https://github.com/Loopring',
    npm: 'https://www.npmjs.com/package/@loopring-web/loopring-sdk'
  },
  {
    id: 'litecoin',
    symbol: 'LTC',
    name: 'Litecoin',
    description: 'A peer-to-peer cryptocurrency designed for fast, low-cost payments.',
    ucid: 2,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://litecoin.org',
    github: 'https://github.com/litecoin-project',
    npm: null
  },
  {
    id: 'decentraland',
    symbol: 'MANA',
    name: 'Decentraland',
    description: 'A virtual reality platform powered by Ethereum where users own and create content.',
    ucid: 1966,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'nft', 'gaming'],
    website: 'https://decentraland.org',
    github: 'https://github.com/decentraland',
    npm: 'https://www.npmjs.com/package/decentraland'
  },
  {
    id: 'mask-network',
    symbol: 'MASK',
    name: 'Mask Network',
    description: 'A bridge connecting Web 2.0 social media with Web 3.0 decentralized applications.',
    ucid: 8536,
    type: 'token',
    consensusType: 'token',
    class: ['social', 'infrastructure'],
    website: 'https://mask.io',
    github: 'https://github.com/DimensionDev',
    npm: null
  },
  {
    id: 'measurable-data-token',
    symbol: 'MDT',
    name: 'Measurable Data Token',
    description: 'A decentralized data exchange platform rewarding users for sharing anonymous data.',
    ucid: 2348,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'social'],
    website: 'https://measurable.ai',
    github: null,
    npm: null
  },
  {
    id: 'metis',
    symbol: 'METIS',
    name: 'Metis',
    description: 'An Ethereum layer-2 rollup platform for building decentralized organizations.',
    ucid: 9640,
    type: 'token',
    consensusType: 'optimistic-rollup',
    class: ['layer-2', 'infrastructure'],
    website: 'https://www.metis.io',
    github: 'https://github.com/MetisProtocol',
    npm: null
  },
  {
    id: 'melon',
    symbol: 'MLN',
    name: 'Melon',
    description: 'A protocol for decentralized asset management on Ethereum (now Enzyme).',
    ucid: 1552,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance'],
    website: 'https://enzyme.finance',
    github: 'https://github.com/enzymefinance',
    npm: null
  },
  {
    id: 'marinade',
    symbol: 'MNDE',
    name: 'Marinade (MNDE)',
    description: 'The governance token for Marinade Finance, a liquid staking protocol on Solana.',
    ucid: 11461,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking', 'governance'],
    website: 'https://marinade.finance',
    github: 'https://github.com/marinade-finance',
    npm: null
  },
  {
    id: 'mina',
    symbol: 'MINA',
    name: 'Mina',
    description: 'The lightest blockchain using zk-SNARKs to maintain a constant 22KB size.',
    ucid: 8646,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform', 'privacy'],
    website: 'https://minaprotocol.com',
    github: 'https://github.com/MinaProtocol',
    npm: 'https://www.npmjs.com/package/mina-signer'
  },
  {
    id: 'maker',
    symbol: 'MKR',
    name: 'Maker',
    description: 'The governance token for MakerDAO, managing the DAI stablecoin system.',
    ucid: 1518,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance', 'stablecoin'],
    website: 'https://makerdao.com',
    github: 'https://github.com/makerdao',
    npm: 'https://www.npmjs.com/package/@makerdao/dai'
  },
  {
    id: 'moonwell',
    symbol: 'WELL',
    name: 'Moonwell',
    description: 'An open lending and borrowing DeFi protocol on Moonbeam and Base.',
    ucid: 9285,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://moonwell.fi',
    github: 'https://github.com/moonwell-fi',
    npm: null
  },
  {
    id: 'metaplex',
    symbol: 'MPLX',
    name: 'Metaplex',
    description: 'The NFT standard and infrastructure for creating and managing NFTs on Solana.',
    ucid: 22487,
    type: 'token',
    consensusType: 'token',
    class: ['nft', 'infrastructure'],
    website: 'https://www.metaplex.com',
    github: 'https://github.com/metaplex-foundation',
    npm: 'https://www.npmjs.com/package/@metaplex-foundation/js'
  },
  {
    id: 'near-protocol',
    symbol: 'NEAR',
    name: 'NEAR Protocol',
    description: 'A sharded proof-of-stake blockchain designed for usability and scalability.',
    ucid: 6535,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://near.org',
    github: 'https://github.com/near',
    npm: 'https://www.npmjs.com/package/near-api-js'
  },
  {
    id: 'nkn',
    symbol: 'NKN',
    name: 'NKN',
    description: 'A decentralized data transmission network utilizing blockchain for peer-to-peer connectivity.',
    ucid: 2780,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['infrastructure', 'data'],
    website: 'https://nkn.org',
    github: 'https://github.com/nknorg',
    npm: 'https://www.npmjs.com/package/nkn-sdk-js'
  },
  {
    id: 'nomina',
    symbol: 'NOM',
    name: 'Nomina',
    description: 'A cryptocurrency token with limited public information.',
    ucid: 32100,
    type: 'token',
    consensusType: 'token',
    class: ['defi'],
    website: null,
    github: null,
    npm: null
  },
  {
    id: 'numeraire',
    symbol: 'NMR',
    name: 'Numeraire',
    description: 'A token for the Numerai hedge fund platform where data scientists stake predictions.',
    ucid: 1732,
    type: 'token',
    consensusType: 'token',
    class: ['ai', 'data'],
    website: 'https://numer.ai',
    github: 'https://github.com/numerai',
    npm: null
  },
  {
    id: 'optimism',
    symbol: 'OP',
    name: 'Optimism',
    description: 'An Ethereum layer-2 scaling solution using optimistic rollups for lower fees.',
    ucid: 11840,
    type: 'token',
    consensusType: 'optimistic-rollup',
    class: ['layer-2', 'infrastructure', 'governance'],
    website: 'https://optimism.io',
    github: 'https://github.com/ethereum-optimism',
    npm: 'https://www.npmjs.com/package/@eth-optimism/sdk'
  },
  {
    id: 'orca',
    symbol: 'ORCA',
    name: 'Orca',
    description: 'The most user-friendly DEX on Solana with concentrated liquidity pools.',
    ucid: 11191,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex'],
    website: 'https://www.orca.so',
    github: 'https://github.com/orca-so',
    npm: 'https://www.npmjs.com/package/@orca-so/sdk'
  },
  {
    id: 'orchid-token',
    symbol: 'OXT',
    name: 'Orchid Token',
    description: 'A decentralized VPN marketplace providing private internet access.',
    ucid: 5026,
    type: 'token',
    consensusType: 'token',
    class: ['privacy', 'infrastructure'],
    website: 'https://www.orchid.com',
    github: 'https://github.com/OrchidTechnologies',
    npm: null
  },
  {
    id: 'origin-token',
    symbol: 'OGN',
    name: 'Origin Token',
    description: 'A platform for building decentralized marketplaces and NFT applications.',
    ucid: 5117,
    type: 'token',
    consensusType: 'token',
    class: ['nft', 'defi', 'governance'],
    website: 'https://www.originprotocol.com',
    github: 'https://github.com/OriginProtocol',
    npm: 'https://www.npmjs.com/package/@origin/graphql'
  },
  {
    id: 'origin-trails',
    symbol: 'TRAC',
    name: 'Origin Trails',
    description: 'A blockchain-based protocol for supply chain data sharing and verification.',
    ucid: 2467,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'infrastructure'],
    website: 'https://origintrail.io',
    github: 'https://github.com/OriginTrail',
    npm: null
  },
  {
    id: 'osmosis',
    symbol: 'OSMO',
    name: 'Osmosis',
    description: 'An advanced AMM protocol built on Cosmos with interchain liquidity.',
    ucid: 12220,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'dex', 'interoperability'],
    website: 'https://osmosis.zone',
    github: 'https://github.com/osmosis-labs',
    npm: 'https://www.npmjs.com/package/osmojs'
  },
  {
    id: 'paxos-standard',
    symbol: 'PAX',
    name: 'Paxos Standard',
    description: 'A regulated stablecoin pegged 1:1 to USD issued by Paxos Trust Company.',
    ucid: 3330,
    type: 'token',
    consensusType: 'token',
    class: ['stablecoin', 'payment'],
    website: 'https://paxos.com',
    github: null,
    npm: null
  },
  {
    id: 'paxos-gold',
    symbol: 'PAXG',
    name: 'Paxos Gold',
    description: 'A token backed by physical gold, each representing one troy ounce of London Good Delivery gold.',
    ucid: 4705,
    type: 'token',
    consensusType: 'token',
    class: ['stablecoin'],
    website: 'https://paxos.com/paxgold',
    github: null,
    npm: null
  },
  {
    id: 'paypal-usd',
    symbol: 'PYUSD',
    name: 'PayPal USD',
    description: 'A stablecoin issued by PayPal pegged 1:1 to the US Dollar.',
    ucid: 28321,
    type: 'token',
    consensusType: 'token',
    class: ['stablecoin', 'payment'],
    website: 'https://www.paypal.com/pyusd',
    github: null,
    npm: null
  },
  {
    id: 'pendle',
    symbol: 'PENDLE',
    name: 'Pendle',
    description: 'A permissionless yield-trading protocol enabling tokenization and trading of future yield.',
    ucid: 9481,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'yield-farming'],
    website: 'https://www.pendle.finance',
    github: 'https://github.com/pendle-finance',
    npm: 'https://www.npmjs.com/package/@pendle/sdk-v2'
  },
  {
    id: 'pepe',
    symbol: 'PEPE',
    name: 'Pepe',
    description: 'A meme coin inspired by the Pepe the Frog internet meme.',
    ucid: 24478,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://www.pepe.vip',
    github: null,
    npm: null
  },
  {
    id: 'perpetual-protocol',
    symbol: 'PERP',
    name: 'Perpetual Protocol',
    description: 'A decentralized perpetual contract protocol for trading with up to 10x leverage.',
    ucid: 6950,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'derivatives'],
    website: 'https://perp.com',
    github: 'https://github.com/perpetual-protocol',
    npm: null
  },
  {
    id: 'pluton',
    symbol: 'PLU',
    name: 'Pluton',
    description: 'The rewards token of Plutus, a crypto rewards platform.',
    ucid: 1080,
    type: 'token',
    consensusType: 'token',
    class: ['payment', 'defi'],
    website: 'https://plutus.it',
    github: null,
    npm: null
  },
  {
    id: 'polkastarter',
    symbol: 'POLS',
    name: 'Polkastarter',
    description: 'A cross-chain launchpad protocol for decentralized token sales.',
    ucid: 7129,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'infrastructure'],
    website: 'https://polkastarter.com',
    github: 'https://github.com/polkastarter',
    npm: null
  },
  {
    id: 'polygon-ecosystem-token',
    symbol: 'POL',
    name: 'Polygon Ecosystem Token',
    description: 'The native token of Polygon, a scaling solution for Ethereum with sidechains.',
    ucid: 3890,
    type: 'token',
    consensusType: 'proof-of-stake',
    class: ['layer-2', 'infrastructure'],
    website: 'https://polygon.technology',
    github: 'https://github.com/maticnetwork',
    npm: 'https://www.npmjs.com/package/@maticnetwork/maticjs'
  },
  {
    id: 'powerledger',
    symbol: 'POWR',
    name: 'Powerledger',
    description: 'A blockchain-based platform for trading renewable energy and environmental commodities.',
    ucid: 2132,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://powerledger.io',
    github: 'https://github.com/Power-Ledger',
    npm: null
  },
  {
    id: 'propy',
    symbol: 'PRO',
    name: 'Propy',
    description: 'A blockchain-based real estate transaction platform enabling global property transfers.',
    ucid: 1974,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'nft'],
    website: 'https://propy.com',
    github: 'https://github.com/Propy',
    npm: null
  },
  {
    id: 'pyth-network',
    symbol: 'PYTH',
    name: 'Pyth Network',
    description: 'A high-fidelity oracle network delivering real-time market data to smart contracts.',
    ucid: 28177,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'data', 'infrastructure'],
    website: 'https://pyth.network',
    github: 'https://github.com/pyth-network',
    npm: 'https://www.npmjs.com/package/@pythnetwork/client'
  },
  {
    id: 'quant',
    symbol: 'QNT',
    name: 'Quant',
    description: 'A blockchain interoperability protocol connecting multiple blockchains and networks.',
    ucid: 3155,
    type: 'token',
    consensusType: 'token',
    class: ['interoperability', 'infrastructure'],
    website: 'https://www.quant.network',
    github: null,
    npm: null
  },
  {
    id: 'rarible',
    symbol: 'RARI',
    name: 'Rarible',
    description: 'A multi-chain NFT marketplace and platform with community governance.',
    ucid: 6910,
    type: 'token',
    consensusType: 'token',
    class: ['nft', 'governance'],
    website: 'https://rarible.com',
    github: 'https://github.com/rarible',
    npm: 'https://www.npmjs.com/package/@rarible/sdk'
  },
  {
    id: 'render',
    symbol: 'RENDER',
    name: 'Render',
    description: 'A decentralized GPU rendering network for creators and artists.',
    ucid: 5690,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://rendernetwork.com',
    github: 'https://github.com/rndr-network',
    npm: null
  },
  {
    id: 'request-network',
    symbol: 'REQ',
    name: 'Request Network',
    description: 'A decentralized payment protocol for requesting, detecting, and making payments.',
    ucid: 2071,
    type: 'token',
    consensusType: 'token',
    class: ['payment', 'infrastructure'],
    website: 'https://request.network',
    github: 'https://github.com/RequestNetwork',
    npm: 'https://www.npmjs.com/package/@requestnetwork/request-client.js'
  },
  {
    id: 'iexec-rlc',
    symbol: 'RLC',
    name: 'iExec RLC',
    description: 'A decentralized marketplace for cloud computing resources.',
    ucid: 1637,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'data'],
    website: 'https://iex.ec',
    github: 'https://github.com/iExecBlockchainComputing',
    npm: 'https://www.npmjs.com/package/iexec'
  },
  {
    id: 'ronin',
    symbol: 'RONIN',
    name: 'Ronin',
    description: 'An Ethereum sidechain built for gaming, powering Axie Infinity.',
    ucid: 14101,
    type: 'coin',
    consensusType: 'proof-of-authority',
    class: ['layer-1', 'gaming', 'nft'],
    website: 'https://roninchain.com',
    github: 'https://github.com/axieinfinity',
    npm: null
  },
  {
    id: 'oasis',
    symbol: 'ROSE',
    name: 'Oasis',
    description: 'A privacy-enabled blockchain platform for DeFi and responsible data economy.',
    ucid: 7653,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'privacy', 'smart-contract-platform'],
    website: 'https://oasisprotocol.org',
    github: 'https://github.com/oasisprotocol',
    npm: 'https://www.npmjs.com/package/@oasisprotocol/client'
  },
  {
    id: 'safe',
    symbol: 'SAFE',
    name: 'Safe',
    description: 'The governance token for Safe (formerly Gnosis Safe), a multi-signature wallet platform.',
    ucid: 28206,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'governance'],
    website: 'https://safe.global',
    github: 'https://github.com/safe-global',
    npm: 'https://www.npmjs.com/package/@safe-global/safe-core-sdk'
  },
  {
    id: 'the-sandbox',
    symbol: 'SAND',
    name: 'The Sandbox',
    description: 'A virtual metaverse where players can build, own, and monetize gaming experiences.',
    ucid: 6210,
    type: 'token',
    consensusType: 'token',
    class: ['metaverse', 'gaming', 'nft'],
    website: 'https://www.sandbox.game',
    github: 'https://github.com/thesandboxgame',
    npm: null
  },
  {
    id: 'stader',
    symbol: 'SD',
    name: 'Stader',
    description: 'A multi-chain liquid staking platform simplifying staking across blockchains.',
    ucid: 11367,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'staking'],
    website: 'https://www.staderlabs.com',
    github: 'https://github.com/stader-labs',
    npm: null
  },
  {
    id: 'sei-network',
    symbol: 'SEI',
    name: 'Sei',
    description: 'A layer-1 blockchain optimized for trading with built-in orderbook infrastructure.',
    ucid: 23149,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'dex', 'smart-contract-platform'],
    website: 'https://sei.io',
    github: 'https://github.com/sei-protocol',
    npm: null
  },
  {
    id: 'shiba-inu',
    symbol: 'SHIB',
    name: 'Shiba Inu',
    description: 'A decentralized meme token featuring the Shiba Inu dog breed.',
    ucid: 5994,
    type: 'token',
    consensusType: 'token',
    class: ['meme'],
    website: 'https://shibatoken.com',
    github: null,
    npm: null
  },
  {
    id: 'shping',
    symbol: 'SHPING',
    name: 'Shping',
    description: 'A blockchain-based product verification and shopper marketing platform.',
    ucid: 2588,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'infrastructure'],
    website: 'https://shping.com',
    github: null,
    npm: null
  },
  {
    id: 'skale-labs',
    symbol: 'SKL',
    name: 'Skale Labs',
    description: 'An elastic blockchain network providing high-throughput sidechains for Ethereum.',
    ucid: 5691,
    type: 'token',
    consensusType: 'token',
    class: ['layer-2', 'infrastructure'],
    website: 'https://skale.space',
    github: 'https://github.com/skalenetwork',
    npm: 'https://www.npmjs.com/package/@skalenetwork/skale-contracts-ethers-v5'
  },
  {
    id: 'sky',
    symbol: 'SKY',
    name: 'Sky',
    description: 'The rebranded MakerDAO ecosystem token (formerly MKR) governing the Sky protocol.',
    ucid: 1518,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance', 'stablecoin'],
    website: 'https://sky.money',
    github: 'https://github.com/makerdao',
    npm: 'https://www.npmjs.com/package/@makerdao/dai'
  },
  {
    id: 'solana',
    symbol: 'SOL',
    name: 'Solana',
    description: 'A high-performance blockchain using proof-of-history for fast, low-cost transactions.',
    ucid: 5426,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://solana.com',
    github: 'https://github.com/solana-labs',
    npm: 'https://www.npmjs.com/package/@solana/web3.js'
  },
  {
    id: 'spell',
    symbol: 'SPELL',
    name: 'Spell',
    description: 'The governance token for Abracadabra.money, a lending platform using interest-bearing tokens as collateral.',
    ucid: 8896,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://abracadabra.money',
    github: 'https://github.com/Abracadabra-money',
    npm: null
  },
  {
    id: 'subsquid',
    symbol: 'SQD',
    name: 'Subsquid',
    description: 'A decentralized data indexing framework for blockchain data querying and analytics.',
    ucid: 28688,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'infrastructure'],
    website: 'https://subsquid.io',
    github: 'https://github.com/subsquid',
    npm: 'https://www.npmjs.com/package/@subsquid/substrate-processor'
  },
  {
    id: 'storj',
    symbol: 'STORJ',
    name: 'Storj',
    description: 'A decentralized cloud storage network with end-to-end encryption.',
    ucid: 1772,
    type: 'token',
    consensusType: 'token',
    class: ['storage', 'infrastructure'],
    website: 'https://www.storj.io',
    github: 'https://github.com/storj',
    npm: 'https://www.npmjs.com/package/@storj/uplink'
  },
  {
    id: 'stacks',
    symbol: 'STX',
    name: 'Stacks',
    description: 'A layer-1 blockchain bringing smart contracts to Bitcoin through proof-of-transfer.',
    ucid: 4847,
    type: 'coin',
    consensusType: 'proof-of-transfer',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://www.stacks.co',
    github: 'https://github.com/stacks-network',
    npm: 'https://www.npmjs.com/package/@stacks/transactions'
  },
  {
    id: 'suku',
    symbol: 'SUKU',
    name: 'Suku',
    description: 'A blockchain-based supply chain platform enabling transparent product tracking.',
    ucid: 5752,
    type: 'token',
    consensusType: 'token',
    class: ['data', 'infrastructure'],
    website: 'https://www.suku.world',
    github: null,
    npm: null
  },
  {
    id: 'sui',
    symbol: 'SUI',
    name: 'Sui',
    description: 'A layer-1 blockchain using the Move language with parallel transaction execution.',
    ucid: 20947,
    type: 'coin',
    consensusType: 'delegated-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://sui.io',
    github: 'https://github.com/MystenLabs',
    npm: 'https://www.npmjs.com/package/@mysten/sui.js'
  },
  {
    id: 'super',
    symbol: 'SUPER',
    name: 'Super',
    description: 'A gaming and metaverse ecosystem token enabling NFT marketplaces and game creation.',
    ucid: 6777,
    type: 'token',
    consensusType: 'token',
    class: ['gaming', 'metaverse', 'nft'],
    website: 'https://superverse.co',
    github: null,
    npm: null
  },
  {
    id: 'maple-finance',
    symbol: 'SYRUP',
    name: 'Maple Finance',
    description: 'A decentralized corporate credit market providing undercollateralized loans.',
    ucid: 8301,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending'],
    website: 'https://maple.finance',
    github: 'https://github.com/maple-labs',
    npm: null
  },
  {
    id: 'bittensor',
    symbol: 'TAO',
    name: 'Bittensor',
    description: 'A decentralized machine learning network incentivizing AI model development.',
    ucid: 22974,
    type: 'coin',
    consensusType: 'proof-of-stake',
    class: ['ai', 'data', 'infrastructure'],
    website: 'https://bittensor.com',
    github: 'https://github.com/opentensor',
    npm: null
  },
  {
    id: 'tellor',
    symbol: 'TRB',
    name: 'Tellor',
    description: 'A decentralized oracle network providing high-value off-chain data to smart contracts.',
    ucid: 4944,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'infrastructure', 'data'],
    website: 'https://tellor.io',
    github: 'https://github.com/tellor-io',
    npm: 'https://www.npmjs.com/package/usingtellor'
  },
  {
    id: 'tru',
    symbol: 'TRU',
    name: 'TRU',
    description: 'The governance token for TrueFi, a DeFi protocol for uncollateralized lending.',
    ucid: 6719,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'lending', 'governance'],
    website: 'https://truefi.io',
    github: 'https://github.com/trusttoken',
    npm: null
  },
  {
    id: 'uma',
    symbol: 'UMA',
    name: 'UMA Voting Token',
    description: 'A protocol for creating synthetic assets and decentralized financial contracts.',
    ucid: 5617,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'governance', 'oracle'],
    website: 'https://umaproject.org',
    github: 'https://github.com/UMAprotocol',
    npm: 'https://www.npmjs.com/package/@uma/sdk'
  },
  {
    id: 'uniswap',
    symbol: 'UNI',
    name: 'Uniswap',
    description: 'The most popular decentralized trading protocol with automated liquidity provision on Ethereum.',
    ucid: 7083,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'governance'],
    website: 'https://uniswap.org',
    github: 'https://github.com/Uniswap',
    npm: 'https://www.npmjs.com/package/@uniswap/sdk'
  },
  {
    id: 'usd-coin',
    symbol: 'USDC',
    name: 'USD Coin',
    description: 'A fully-backed stablecoin pegged 1:1 to the US Dollar issued by Circle.',
    ucid: 3408,
    type: 'token',
    consensusType: 'token',
    class: ['stablecoin', 'payment'],
    website: 'https://www.circle.com/usdc',
    github: 'https://github.com/circlefin',
    npm: null
  },
  {
    id: 'velodrome-finance',
    symbol: 'VELO',
    name: 'Velodrome Finance',
    description: 'A next-generation AMM on Optimism inspired by Solidly with ve(3,3) mechanics.',
    ucid: 19721,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'dex', 'layer-2'],
    website: 'https://velodrome.finance',
    github: 'https://github.com/velodrome-finance',
    npm: null
  },
  {
    id: 'vechain',
    symbol: 'VET',
    name: 'VeChain',
    description: 'An enterprise blockchain platform for supply chain management and IoT.',
    ucid: 3077,
    type: 'coin',
    consensusType: 'proof-of-authority',
    class: ['layer-1', 'infrastructure', 'iot'],
    website: 'https://www.vechain.org',
    github: 'https://github.com/vechain',
    npm: 'https://www.npmjs.com/package/@vechain/connex'
  },
  {
    id: 'vethor-token',
    symbol: 'VTHO',
    name: 'VeThor Token',
    description: 'The energy token used to power transactions on the VeChain blockchain.',
    ucid: 3012,
    type: 'token',
    consensusType: 'token',
    class: ['infrastructure', 'payment'],
    website: 'https://www.vechain.org',
    github: 'https://github.com/vechain',
    npm: 'https://www.npmjs.com/package/@vechain/connex'
  },
  {
    id: 'stellar',
    symbol: 'XLM',
    name: 'Stellar',
    description: 'An open network for storing and moving money with fast, low-cost cross-border payments.',
    ucid: 512,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    website: 'https://stellar.org',
    github: 'https://github.com/stellar',
    npm: 'https://www.npmjs.com/package/@stellar/stellar-sdk'
  },
  {
    id: 'ripple',
    symbol: 'XRP',
    name: 'XRP',
    description: 'A digital payment protocol and cryptocurrency enabling fast, low-cost international money transfers.',
    ucid: 52,
    type: 'coin',
    consensusType: 'byzantine-fault-tolerance',
    class: ['layer-1', 'payment'],
    website: 'https://ripple.com',
    github: 'https://github.com/ripple',
    npm: 'https://www.npmjs.com/package/xrpl'
  },
  {
    id: 'tezos',
    symbol: 'XTZ',
    name: 'Tezos',
    description: 'A self-amending blockchain with on-chain governance and formal verification.',
    ucid: 2011,
    type: 'coin',
    consensusType: 'liquid-proof-of-stake',
    class: ['layer-1', 'smart-contract-platform', 'governance'],
    website: 'https://tezos.com',
    github: 'https://gitlab.com/tezos/tezos',
    npm: 'https://www.npmjs.com/package/@taquito/taquito'
  },
  {
    id: 'xyo-network',
    symbol: 'XYO',
    name: 'XYO Network',
    description: 'A decentralized network of devices providing verifiable location data to smart contracts.',
    ucid: 2765,
    type: 'token',
    consensusType: 'token',
    class: ['oracle', 'data', 'iot'],
    website: 'https://xyo.network',
    github: 'https://github.com/XYOracleNetwork',
    npm: 'https://www.npmjs.com/package/@xyo-network/sdk-xyo-js'
  },
  {
    id: 'yearn-finance',
    symbol: 'YFI',
    name: 'yearn.finance',
    description: 'A yield aggregator and optimization protocol automating DeFi strategies.',
    ucid: 5864,
    type: 'token',
    consensusType: 'token',
    class: ['defi', 'yield-farming', 'governance'],
    website: 'https://yearn.finance',
    github: 'https://github.com/yearn',
    npm: 'https://www.npmjs.com/package/@yfi/sdk'
  },
  {
    id: 'zcash',
    symbol: 'ZEC',
    name: 'Zcash',
    description: 'A privacy-focused cryptocurrency using zero-knowledge proofs for shielded transactions.',
    ucid: 1437,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://z.cash',
    github: 'https://github.com/zcash',
    npm: null
  }
];

export default NY_EXCHANGE_OFFERINGS_COINBASE;
