/**
 * Proof of Work Index - Curated list of Proof of Work cryptocurrencies
 * 
 * This list contains cryptocurrencies that use Proof of Work (PoW) consensus mechanisms.
 * Proof of Work is a consensus algorithm that requires miners to solve complex
 * cryptographic puzzles to validate transactions and create new blocks.
 * 
 * This index is used for PoW-specific displays, mining-related features, and
 * consensus mechanism categorization interfaces.
 * 
 * Last Updated: December 2025
 */

export type CurrencyType = 'coin' | 'token';
export type ConsensusType = 'proof-of-stake' | 'proof-of-work' | 'proof-of-authority' | 'delegated-proof-of-stake' | 'nominated-proof-of-stake' | 'liquid-proof-of-stake' | 'byzantine-fault-tolerance' | 'proof-of-transfer' | 'proof-of-coverage' | 'token' | 'hybrid' | 'optimistic-rollup';
export type CurrencyClass = 'layer-1' | 'layer-2' | 'defi' | 'dex' | 'nft' | 'gaming' | 'metaverse' | 'oracle' | 'privacy' | 'meme' | 'staking' | 'governance' | 'lending' | 'data' | 'infrastructure' | 'smart-contract-platform' | 'exchange-token' | 'ai' | 'storage' | 'payment' | 'social' | 'interoperability' | 'sports' | 'iot';

export interface ProofOfWorkItem {
  id: string;
  symbol: string;
  name: string;
  description: string;
  ucid: number;
  type: CurrencyType;
  consensusType: ConsensusType;
  class: CurrencyClass[];
  website: string | null;
  github: string | null;
  npm: string | null;
}

export const PROOF_OF_WORK: ProofOfWorkItem[] = [
  { 
    id: 'bitcoin-cash', 
    symbol: 'BCH', 
    name: 'Bitcoin Cash',
    description: 'A peer-to-peer electronic cash system forked from Bitcoin, focusing on fast transactions and low fees.',
    ucid: 1831,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoincash.org',
    github: 'https://github.com/bitcoincashorg',
    npm: null
  },
  { 
    id: 'bytecoin', 
    symbol: 'BCN', 
    name: 'Bytecoin',
    description: 'A privacy-focused cryptocurrency using CryptoNote technology and ring signatures.',
    ucid: 372,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://bytecoin.org',
    github: 'https://github.com/bcndev',
    npm: null
  },
  { 
    id: 'bitcoin-diamond', 
    symbol: 'BCD', 
    name: 'Bitcoin Diamond',
    description: 'A Bitcoin fork aiming to improve transaction speed and reduce mining centralization.',
    ucid: 2222,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'http://www.btcd.io',
    github: 'https://github.com/eveybcd',
    npm: null
  },
  { 
    id: 'beldex', 
    symbol: 'BDX', 
    name: 'Beldex',
    description: 'A privacy-focused blockchain providing secure transactions and decentralized applications.',
    ucid: 3896,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy'],
    website: 'https://beldex.io',
    github: 'https://github.com/Beldex-Coin',
    npm: null
  },
  { 
    id: 'beam', 
    symbol: 'BEAM', 
    name: 'Beam',
    description: 'A privacy-focused cryptocurrency using the Mimblewimble protocol for confidential transactions.',
    ucid: 3702,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://beam.mw',
    github: 'https://github.com/BeamMW',
    npm: null
  },
  { 
    id: 'bismuth', 
    symbol: 'BIS', 
    name: 'Bismuth',
    description: 'A Python-based blockchain platform supporting custom tokens and decentralized applications.',
    ucid: 2009,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://bismuth.cz',
    github: 'https://github.com/bismuthfoundation',
    npm: null
  },
  { 
    id: 'bitcoin-cash-sv', 
    symbol: 'BSV', 
    name: 'Bitcoin SV',
    description: 'Bitcoin Satoshi Vision - a Bitcoin Cash fork claiming to restore Satoshi\'s original Bitcoin protocol.',
    ucid: 3602,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoinsv.io',
    github: 'https://github.com/bitcoin-sv',
    npm: null
  },
  { 
    id: 'bitcoin', 
    symbol: 'BTC', 
    name: 'Bitcoin',
    description: 'The first decentralized cryptocurrency, serving as digital gold and a peer-to-peer electronic cash system.',
    ucid: 1,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoin.org',
    github: 'https://github.com/bitcoin',
    npm: 'https://www.npmjs.com/package/bitcoinjs-lib'
  },
  { 
    id: 'bitcoin-gold', 
    symbol: 'BTG', 
    name: 'Bitcoin Gold',
    description: 'A Bitcoin fork designed to democratize mining by using GPU-friendly algorithms.',
    ucid: 2083,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://bitcoingold.org',
    github: 'https://github.com/BTCGPU',
    npm: null
  },
  { 
    id: 'bytom', 
    symbol: 'BTM', 
    name: 'Bytom',
    description: 'A blockchain protocol for asset registration and exchange in the digital and physical world.',
    ucid: 1866,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://bytom.io',
    github: 'https://github.com/Bytom',
    npm: null
  },
  { 
    id: 'carboncoin', 
    symbol: 'CARBON', 
    name: 'Carboncoin',
    description: 'An early cryptocurrency focused on carbon credit trading and environmental initiatives.',
    ucid: 321,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'californium', 
    symbol: 'CF', 
    name: 'Californium',
    description: 'A proof-of-work cryptocurrency with fast block times.',
    ucid: 989,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'conflux-token', 
    symbol: 'CFX', 
    name: 'Conflux Network',
    description: 'A high-throughput blockchain using a tree-graph consensus algorithm for scalability.',
    ucid: 7334,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://confluxnetwork.org',
    github: 'https://github.com/Conflux-Chain',
    npm: 'https://www.npmjs.com/package/js-conflux-sdk'
  },
  { 
    id: 'nervos-network', 
    symbol: 'CKB', 
    name: 'Nervos Network',
    description: 'A layered blockchain network designed for universal interoperability and scalability.',
    ucid: 4948,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'interoperability'],
    website: 'https://nervos.org',
    github: 'https://github.com/nervosnetwork',
    npm: 'https://www.npmjs.com/package/@nervosnetwork/ckb-sdk-core'
  },
  { 
    id: 'clams', 
    symbol: 'CLAM', 
    name: 'Clams',
    description: 'A cryptocurrency originally distributed to Bitcoin, Litecoin, and Dogecoin holders.',
    ucid: 40,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'payment'],
    website: 'https://clamcoin.org',
    github: 'https://github.com/nochowderforyou/clams',
    npm: null
  },
  { 
    id: 'callisto', 
    symbol: 'CLO', 
    name: 'Callisto Network',
    description: 'A blockchain platform forked from Ethereum Classic, focusing on smart contract security.',
    ucid: 2757,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://callisto.network',
    github: 'https://github.com/EthereumCommonwealth',
    npm: null
  },
  { 
    id: 'clore-ai', 
    symbol: 'CLORE', 
    name: 'Clore.ai',
    description: 'A decentralized marketplace for renting GPU computing power for AI and rendering tasks.',
    ucid: 28724,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['ai', 'infrastructure'],
    website: 'https://clore.ai',
    github: 'https://github.com/cloreai',
    npm: null
  },
  { 
    id: 'comet', 
    symbol: 'CMT', 
    name: 'Comet',
    description: 'A proof-of-work cryptocurrency with community-driven development.',
    ucid: 2246,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'dash', 
    symbol: 'DASH', 
    name: 'Dash',
    description: 'A privacy-focused cryptocurrency featuring instant transactions and a two-tier masternode network.',
    ucid: 131,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'payment', 'privacy'],
    website: 'https://www.dash.org',
    github: 'https://github.com/dashpay',
    npm: null
  },
  { 
    id: 'decred', 
    symbol: 'DCR', 
    name: 'Decred',
    description: 'A cryptocurrency with hybrid proof-of-work/proof-of-stake consensus and on-chain governance.',
    ucid: 1168,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'governance'],
    website: 'https://decred.org',
    github: 'https://github.com/decred',
    npm: null
  },
  { 
    id: 'deutsche-emark', 
    symbol: 'DEM', 
    name: 'Deutsche eMark',
    description: 'A German cryptocurrency designed for fast and secure peer-to-peer transactions.',
    ucid: 1657,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://deutsche-emark.org',
    github: 'https://github.com/emarkproject',
    npm: null
  },
  { 
    id: 'digibyte', 
    symbol: 'DGB', 
    name: 'Digibyte',
    description: 'A fast and secure blockchain using five mining algorithms for decentralization.',
    ucid: 109,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://digibyte.org',
    github: 'https://github.com/digibyte',
    npm: null
  },
  { 
    id: 'digitalcoin', 
    symbol: 'DGC', 
    name: 'Digitalcoin',
    description: 'An early alternative cryptocurrency with multi-algorithm mining support.',
    ucid: 31,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'dimecoin', 
    symbol: 'DIME', 
    name: 'Dimecoin',
    description: 'A micro-transaction focused cryptocurrency with very low transaction fees.',
    ucid: 927,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://dimecoinnetwork.com',
    github: 'https://github.com/dime-coin',
    npm: null
  },
  { 
    id: 'dollarcoin', 
    symbol: 'DLC', 
    name: 'Dollarcoin',
    description: 'A cryptocurrency designed for everyday transactions.',
    ucid: 658,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'dogecoin', 
    symbol: 'DOGE', 
    name: 'Dogecoin',
    description: 'A meme-inspired cryptocurrency originally created as a joke, now widely used for tipping and payments.',
    ucid: 74,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'meme', 'payment'],
    website: 'https://dogecoin.com',
    github: 'https://github.com/dogecoin',
    npm: null
  },
  { 
    id: 'e-gulden', 
    symbol: 'EFL', 
    name: 'e-Gulden',
    description: 'A Dutch cryptocurrency designed for local merchants and everyday transactions.',
    ucid: 464,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://e-gulden.org',
    github: 'https://github.com/Electronic-Gulden-Foundation',
    npm: null
  },
  { 
    id: 'edge-matrix-computing', 
    symbol: 'EMC', 
    name: 'Edge Matrix Computing',
    description: 'A blockchain platform for AI and edge computing applications.',
    ucid: 3723,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['ai', 'infrastructure'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'epic-cash', 
    symbol: 'EPIC', 
    name: 'Epic Cash',
    description: 'A privacy-focused cryptocurrency using the Mimblewimble protocol.',
    ucid: 5594,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://epic.tech',
    github: 'https://github.com/EpicCash',
    npm: null
  },
  { 
    id: 'ergo', 
    symbol: 'ERG', 
    name: 'Ergo',
    description: 'A smart contract platform using the eUTXO model with advanced cryptographic features.',
    ucid: 1762,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ergoplatform.org',
    github: 'https://github.com/ergoplatform',
    npm: 'https://www.npmjs.com/package/@fleet-sdk/core'
  },
  { 
    id: 'ethereum-classic', 
    symbol: 'ETC', 
    name: 'Ethereum Classic',
    description: 'The original Ethereum blockchain that maintained the immutability principle after The DAO hack.',
    ucid: 1321,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ethereumclassic.org',
    github: 'https://github.com/ethereumclassic',
    npm: null
  },
  { 
    id: 'ethereum-pow', 
    symbol: 'ETHW', 
    name: 'EthereumPOW',
    description: 'A fork of Ethereum maintaining proof-of-work consensus after Ethereum\'s merge to proof-of-stake.',
    ucid: 21296,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://ethereumpow.org',
    github: 'https://github.com/ethereumpow',
    npm: null
  },
  { 
    id: 'firo', 
    symbol: 'FIRO', 
    name: 'Firo',
    description: 'A privacy-focused cryptocurrency (formerly Zcoin) using Lelantus protocol for anonymity.',
    ucid: 1414,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://firo.org',
    github: 'https://github.com/firoorg',
    npm: null
  },
  { 
    id: 'zelcash', 
    symbol: 'FLUX', 
    name: 'Flux',
    description: 'A decentralized cloud infrastructure for Web3 applications with computational resources.',
    ucid: 3029,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['infrastructure', 'storage'],
    website: 'https://runonflux.io',
    github: 'https://github.com/RunOnFlux',
    npm: null
  },
  { 
    id: 'freicoin', 
    symbol: 'FRC', 
    name: 'Freicoin',
    description: 'A cryptocurrency implementing demurrage (negative interest) to encourage spending.',
    ucid: 66,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'http://freico.in',
    github: 'https://github.com/freicoin',
    npm: null
  },
  { 
    id: 'francs', 
    symbol: 'FRN', 
    name: 'Francs',
    description: 'A cryptocurrency focused on stability and everyday transactions.',
    ucid: 758,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'feathercoin', 
    symbol: 'FTC', 
    name: 'Feathercoin',
    description: 'An early Litecoin-based cryptocurrency with community-driven development.',
    ucid: 8,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://feathercoin.com',
    github: 'https://github.com/FeatherCoin',
    npm: null
  },
  { 
    id: 'gamecredits', 
    symbol: 'GAME', 
    name: 'GameCredits',
    description: 'A cryptocurrency designed for the gaming industry and in-game purchases.',
    ucid: 826,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['gaming', 'payment'],
    website: 'https://gamecredits.org',
    github: 'https://github.com/gamecredits-project',
    npm: null
  },
  { 
    id: 'goldcoin', 
    symbol: 'GLC', 
    name: 'Goldcoin',
    description: 'A peer-to-peer cryptocurrency focused on stability and security.',
    ucid: 276,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://goldcoin.org',
    github: 'https://github.com/GoldCoin-GLCoin',
    npm: null
  },
  { 
    id: 'grin', 
    symbol: 'GRIN', 
    name: 'Grin',
    description: 'A privacy-focused cryptocurrency implementing the Mimblewimble protocol for scalability and anonymity.',
    ucid: 3704,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://grin.mw',
    github: 'https://github.com/mimblewimble/grin',
    npm: null
  },
  { 
    id: 'groestlcoin', 
    symbol: 'GRS', 
    name: 'Groestlcoin',
    description: 'A cryptocurrency designed to be ASIC-resistant with fast and secure transactions.',
    ucid: 258,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://groestlcoin.org',
    github: 'https://github.com/Groestlcoin',
    npm: null
  },
  { 
    id: 'handshake', 
    symbol: 'HNS', 
    name: 'Handshake',
    description: 'A decentralized naming protocol for domain name registration compatible with DNS.',
    ucid: 5817,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['infrastructure', 'data'],
    website: 'https://handshake.org',
    github: 'https://github.com/handshake-org',
    npm: 'https://www.npmjs.com/package/hsd'
  },
  { 
    id: 'hathor', 
    symbol: 'HTR', 
    name: 'Hathor',
    description: 'A scalable blockchain using DAG technology for custom tokens without fees.',
    ucid: 5065,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://hathor.network',
    github: 'https://github.com/HathorNetwork',
    npm: 'https://www.npmjs.com/package/@hathor/wallet-lib'
  },
  { 
    id: 'hush', 
    symbol: 'HUSH', 
    name: 'Hush',
    description: 'A privacy-focused cryptocurrency forked from Zcash with enhanced anonymity features.',
    ucid: 1909,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy'],
    website: 'https://hush.is',
    github: 'https://github.com/MyHush',
    npm: null
  },
  { 
    id: 'ilcoin', 
    symbol: 'ILC', 
    name: 'ILCoin',
    description: 'A cryptocurrency focusing on on-chain data storage and hybrid blockchain technology.',
    ucid: 2901,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'storage'],
    website: 'https://ilcoincrypto.com',
    github: 'https://github.com/ilcoin-project',
    npm: null
  },
  { 
    id: 'ixcoin', 
    symbol: 'IXC', 
    name: 'Ixcoin',
    description: 'One of the earliest Bitcoin forks, launched in 2011.',
    ucid: 313,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'kaspa', 
    symbol: 'KAS', 
    name: 'Kaspa',
    description: 'A proof-of-work cryptocurrency using blockDAG architecture for high transaction throughput.',
    ucid: 20396,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://kaspa.org',
    github: 'https://github.com/kaspanet',
    npm: null
  },
  { 
    id: 'kadena', 
    symbol: 'KDA', 
    name: 'Kadena',
    description: 'A scalable proof-of-work blockchain with a braided multi-chain architecture and Pact smart contracts.',
    ucid: 5647,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://kadena.io',
    github: 'https://github.com/kadena-io',
    npm: 'https://www.npmjs.com/package/@kadena/client'
  },
  { 
    id: 'komodo', 
    symbol: 'KMD', 
    name: 'Komodo',
    description: 'A multi-chain platform providing blockchain solutions with atomic swaps and privacy features.',
    ucid: 1521,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'interoperability', 'privacy'],
    website: 'https://komodoplatform.com',
    github: 'https://github.com/KomodoPlatform',
    npm: null
  },
  { 
    id: 'lbry-credits', 
    symbol: 'LBC', 
    name: 'LBRY Credits',
    description: 'The native token of LBRY, a decentralized content sharing and publishing platform.',
    ucid: 1298,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['social', 'data'],
    website: 'https://lbry.com',
    github: 'https://github.com/lbryio',
    npm: null
  },
  { id: 'kaspa', symbol: 'KAS', name: 'Kaspa' },
  { id: 'komodo', symbol: 'KMD', name: 'Komodo' },
  { id: 'lbry-credits', symbol: 'LBC', name: 'LBRY Credits' },
  { 
    id: 'litecoin-cash', 
    symbol: 'LCC', 
    name: 'Litecoin Cash',
    description: 'A fork of Litecoin with larger block sizes and different mining algorithm.',
    ucid: 2599,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://litecoinca.sh',
    github: 'https://github.com/litecoincash-project',
    npm: null
  },
  { 
    id: 'luckycoin', 
    symbol: 'LKY', 
    name: 'Luckycoin',
    description: 'An early cryptocurrency with random block rewards, inspired by Litecoin.',
    ucid: 41,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'litecoin', 
    symbol: 'LTC', 
    name: 'Litecoin',
    description: 'A peer-to-peer cryptocurrency based on Bitcoin with faster block generation times.',
    ucid: 2,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://litecoin.org',
    github: 'https://github.com/litecoin-project',
    npm: null
  },
  { 
    id: 'matrix-ai-network', 
    symbol: 'MAN', 
    name: 'Matrix AI Network',
    description: 'A blockchain platform integrating AI with distributed computing.',
    ucid: 2474,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['ai', 'infrastructure'],
    website: 'https://www.matrix.io',
    github: 'https://github.com/MatrixAINetwork',
    npm: null
  },
  { 
    id: 'marscoin', 
    symbol: 'MARS', 
    name: 'Marscoin',
    description: 'A cryptocurrency designed for potential use in Mars colonization efforts.',
    ucid: 349,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://marscoin.org',
    github: 'https://github.com/marscoin',
    npm: null
  },
  { 
    id: 'monacoin', 
    symbol: 'MONA', 
    name: 'MonaCoin',
    description: 'A Japanese cryptocurrency based on Litecoin with a strong domestic community.',
    ucid: 213,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://monacoin.org',
    github: 'https://github.com/monacoinproject',
    npm: null
  },
  { 
    id: 'mimblewimblecoin', 
    symbol: 'MWC', 
    name: 'MimbleWimbleCoin',
    description: 'A privacy-focused cryptocurrency implementing the Mimblewimble protocol.',
    ucid: 5031,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://mwc.mw',
    github: 'https://github.com/mwcproject',
    npm: null
  },
  { 
    id: 'nexa', 
    symbol: 'NEXA', 
    name: 'Nexa',
    description: 'A scalable proof-of-work blockchain designed for high transaction throughput.',
    ucid: 20056,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://nexa.org',
    github: 'https://gitlab.com/nexa',
    npm: null
  },
  { 
    id: 'nimiq', 
    symbol: 'NIM', 
    name: 'Nimiq',
    description: 'A browser-based blockchain designed for ease of use and accessibility.',
    ucid: 2916,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://nimiq.com',
    github: 'https://github.com/nimiq',
    npm: 'https://www.npmjs.com/package/@nimiq/core-web'
  },
  { 
    id: 'namecoin', 
    symbol: 'NMC', 
    name: 'Namecoin',
    description: 'A decentralized DNS and identity system based on Bitcoin technology.',
    ucid: 3,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['infrastructure', 'data'],
    website: 'https://namecoin.org',
    github: 'https://github.com/namecoin',
    npm: null
  },
  { 
    id: 'energi', 
    symbol: 'NRG', 
    name: 'Energi',
    description: 'A cryptocurrency combining proof-of-work with governance and self-funding treasury.',
    ucid: 3218,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'governance'],
    website: 'https://energi.world',
    github: 'https://github.com/energicryptocurrency',
    npm: null
  },
  { 
    id: 'newyorkcoin', 
    symbol: 'NYC', 
    name: 'NewYorkCoin',
    description: 'A cryptocurrency designed for fast transactions with New York City branding.',
    ucid: 98,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://newyorkcoin.net',
    github: 'https://github.com/NewYorkCoin-NYC',
    npm: null
  },
  { 
    id: 'omni', 
    symbol: 'OMNI', 
    name: 'Omni',
    description: 'A platform for creating and trading custom digital assets on the Bitcoin blockchain.',
    ucid: 83,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-2', 'infrastructure'],
    website: 'https://omniexplorer.info',
    github: 'https://github.com/OmniLayer',
    npm: null
  },
  { 
    id: 'pascal', 
    symbol: 'PASC', 
    name: 'Pascal',
    description: 'A cryptocurrency with infinite scaling through SafeBox technology.',
    ucid: 1524,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://pascalcoin.org',
    github: 'https://github.com/PascalCoin',
    npm: null
  },
  { 
    id: 'polis', 
    symbol: 'POLIS', 
    name: 'Polis',
    description: 'A community-driven cryptocurrency with masternode network.',
    ucid: 2359,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'governance'],
    website: 'https://polispay.org',
    github: 'https://github.com/polispay',
    npm: null
  },
  { 
    id: 'potcoin', 
    symbol: 'POT', 
    name: 'PotCoin',
    description: 'A cryptocurrency designed for the cannabis industry and related transactions.',
    ucid: 122,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://potcoin.com',
    github: 'https://github.com/potcoin',
    npm: null
  },
  { 
    id: 'peercoin', 
    symbol: 'PPC', 
    name: 'Peercoin',
    description: 'The first cryptocurrency to implement proof-of-stake alongside proof-of-work.',
    ucid: 5,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'payment'],
    website: 'https://peercoin.net',
    github: 'https://github.com/peercoin',
    npm: null
  },
  { 
    id: 'quantum-resistant-ledger', 
    symbol: 'QRL', 
    name: 'Quantum Resistant Ledger',
    description: 'A blockchain designed to be secure against quantum computing attacks using XMSS signatures.',
    ucid: 1430,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://theqrl.org',
    github: 'https://github.com/theQRL',
    npm: 'https://www.npmjs.com/package/@theqrl/wallet-helpers'
  },
  { 
    id: 'quark', 
    symbol: 'QRK', 
    name: 'QuarkCoin',
    description: 'An early cryptocurrency with nine rounds of hashing for security.',
    ucid: 91,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'qubitcoin', 
    symbol: 'QTC', 
    name: 'Qubitcoin',
    description: 'A cryptocurrency using the Qubit hashing algorithm.',
    ucid: 155,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'qubic', 
    symbol: 'QUBIC', 
    name: 'Qubic',
    description: 'A decentralized computation platform with useful proof-of-work.',
    ucid: 29169,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['infrastructure', 'ai'],
    website: 'https://qubic.org',
    github: 'https://github.com/qubic',
    npm: null
  },
  { 
    id: 'ravencoin', 
    symbol: 'RVN', 
    name: 'Ravencoin',
    description: 'A blockchain platform designed for efficient creation and transfer of digital assets.',
    ucid: 2577,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://ravencoin.org',
    github: 'https://github.com/RavenProject',
    npm: null
  },
  { 
    id: 'radiant', 
    symbol: 'RXD', 
    name: 'Radiant',
    description: 'A peer-to-peer digital asset system with unspent transaction output (UTXO) based smart contracts.',
    ucid: 21111,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'smart-contract-platform'],
    website: 'https://radiantblockchain.org',
    github: 'https://github.com/RadiantBlockchain',
    npm: null
  },
  { 
    id: 'siacoin', 
    symbol: 'SC', 
    name: 'Siacoin',
    description: 'A decentralized cloud storage platform where users can rent out unused storage space.',
    ucid: 1042,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    website: 'https://sia.tech',
    github: 'https://github.com/SiaFoundation',
    npm: null
  },
  { 
    id: 'scprime', 
    symbol: 'SCP', 
    name: 'ScPrime',
    description: 'A decentralized data storage solution forked from Sia, focused on enterprise needs.',
    ucid: 5837,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['storage', 'infrastructure'],
    website: 'https://scpri.me',
    github: 'https://github.com/scprimecoin',
    npm: null
  },
  { id: 'radiant', symbol: 'RXD', name: 'Radiant' },
  { id: 'ravencoin', symbol: 'RVN', name: 'Ravencoin' },
  { id: 'scprime', symbol: 'SCP', name: 'ScPrime' },
  { id: 'siacoin', symbol: 'SC', name: 'Siacoin' },
  { 
    id: 'stronghands', 
    symbol: 'SHND', 
    name: 'StrongHands',
    description: 'A cryptocurrency with large supply designed for community-driven growth.',
    ucid: 2633,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://www.stronghands.info',
    github: 'https://github.com/valiant1x',
    npm: null
  },
  { 
    id: 'stratis', 
    symbol: 'STRAX', 
    name: 'Stratis [New]',
    description: 'A blockchain platform (formerly Stratis) for enterprise solutions and custom blockchain development.',
    ucid: 8440,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://www.stratisplatform.com',
    github: 'https://github.com/stratisproject',
    npm: null
  },
  { 
    id: 'syscoin', 
    symbol: 'SYS', 
    name: 'Syscoin',
    description: 'A blockchain platform providing scalability through merged mining with Bitcoin.',
    ucid: 541,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'infrastructure'],
    website: 'https://syscoin.org',
    github: 'https://github.com/syscoin',
    npm: null
  },
  { 
    id: 'terracoin', 
    symbol: 'TRC', 
    name: 'Terracoin',
    description: 'One of the earliest Bitcoin alternatives, launched in 2012.',
    ucid: 65,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://terracoin.io',
    github: 'https://github.com/terracoin',
    npm: null
  },
  { 
    id: 'unobtanium', 
    symbol: 'UNO', 
    name: 'Unobtanium',
    description: 'A rare cryptocurrency with limited supply and merge-mining capability.',
    ucid: 38,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://unobtanium.uno',
    github: 'https://github.com/unobtanium-official',
    npm: null
  },
  { 
    id: 'viacoin', 
    symbol: 'VIA', 
    name: 'Viacoin',
    description: 'A Bitcoin derivative blockchain focused on fast transactions and protocol innovations.',
    ucid: 109,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://viacoin.org',
    github: 'https://github.com/viacoin',
    npm: null
  },
  { 
    id: 'vertcoin', 
    symbol: 'VTC', 
    name: 'Vertcoin',
    description: 'A cryptocurrency designed to be ASIC-resistant to maintain decentralized mining.',
    ucid: 99,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://vertcoin.org',
    github: 'https://github.com/vertcoin-project',
    npm: null
  },
  { 
    id: 'digitalnote', 
    symbol: 'XDN', 
    name: 'DigitalNote',
    description: 'A privacy-focused cryptocurrency with encrypted messaging features.',
    ucid: 1361,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://digitalnote.org',
    github: 'https://github.com/xdn-project',
    npm: null
  },
  { 
    id: 'counterparty', 
    symbol: 'XCP', 
    name: 'Counterparty',
    description: 'A platform for creating decentralized financial tools on the Bitcoin blockchain.',
    ucid: 87,
    type: 'token',
    consensusType: 'proof-of-work',
    class: ['layer-2', 'defi'],
    website: 'https://counterparty.io',
    github: 'https://github.com/CounterpartyXCP',
    npm: null
  },
  { 
    id: 'monero', 
    symbol: 'XMR', 
    name: 'Monero',
    description: 'A privacy-focused cryptocurrency using ring signatures, stealth addresses, and confidential transactions.',
    ucid: 328,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://getmonero.org',
    github: 'https://github.com/monero-project',
    npm: null
  },
  { 
    id: 'myriad', 
    symbol: 'XMY', 
    name: 'MyriadCoin',
    description: 'A cryptocurrency with five mining algorithms for enhanced decentralization.',
    ucid: 182,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://myriadcoin.org',
    github: 'https://github.com/myriadteam',
    npm: null
  },
  { 
    id: 'primecoin', 
    symbol: 'XPM', 
    name: 'Primecoin',
    description: 'A cryptocurrency using prime number chains for proof-of-work, contributing to mathematical research.',
    ucid: 72,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://primecoin.io',
    github: 'https://github.com/primecoin',
    npm: null
  },
  { 
    id: 'verge', 
    symbol: 'XVG', 
    name: 'Verge',
    description: 'A privacy-focused cryptocurrency using multiple anonymity-centric networks.',
    ucid: 693,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://vergecurrency.com',
    github: 'https://github.com/vergecurrency',
    npm: null
  },
  { 
    id: 'phoenixcoin', 
    symbol: 'PXC', 
    name: 'Phoenixcoin',
    description: 'An early cryptocurrency based on Bitcoin technology.',
    ucid: 90,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: null,
    github: null,
    npm: null
  },
  { 
    id: 'zano', 
    symbol: 'ZANO', 
    name: 'Zano',
    description: 'A privacy-focused cryptocurrency with hybrid proof-of-work/proof-of-stake consensus.',
    ucid: 5541,
    type: 'coin',
    consensusType: 'hybrid',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://zano.org',
    github: 'https://github.com/hyle-team/zano',
    npm: null
  },
  { 
    id: 'zcash', 
    symbol: 'ZEC', 
    name: 'ZCash',
    description: 'A privacy-focused cryptocurrency using zero-knowledge proofs (zk-SNARKs) for shielded transactions.',
    ucid: 1437,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://z.cash',
    github: 'https://github.com/zcash',
    npm: null
  },
  { 
    id: 'zclassic', 
    symbol: 'ZCL', 
    name: 'ZClassic',
    description: 'A fork of Zcash removing the founder\'s reward.',
    ucid: 1447,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: null,
    github: 'https://github.com/z-classic',
    npm: null
  },
  { 
    id: 'zencash', 
    symbol: 'ZEN', 
    name: 'Horizen',
    description: 'A privacy-focused blockchain platform with sidechain capabilities and a large node network.',
    ucid: 1698,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'infrastructure'],
    website: 'https://horizen.io',
    github: 'https://github.com/HorizenOfficial',
    npm: null
  },
  { 
    id: 'zero', 
    symbol: 'ZER', 
    name: 'Zero',
    description: 'A privacy-focused cryptocurrency using zero-knowledge proofs.',
    ucid: 1984,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'privacy', 'payment'],
    website: 'https://zerocurrency.com',
    github: 'https://github.com/zerocurrency',
    npm: null
  },
  { 
    id: 'zetacoin', 
    symbol: 'ZET', 
    name: 'Zetacoin',
    description: 'A SHA-256 cryptocurrency designed for fast and secure transactions.',
    ucid: 97,
    type: 'coin',
    consensusType: 'proof-of-work',
    class: ['layer-1', 'payment'],
    website: 'https://zetacoin.org',
    github: 'https://github.com/zetacoin',
    npm: null
  }
];

export default PROOF_OF_WORK;

