import type { CorporationFormationOffice } from './types'
import type { CptppMemberIsoCode } from './cptppMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per CPTPP party economy.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const CPTPP_CORPORATION_FORMATION_OFFICES: Record<CptppMemberIsoCode, CorporationFormationOffice> = {
  AU:   office(
    'Australian Securities and Investments Commission (ASIC)',
    '+61 1300 300 630',
    'Level 5, 100 Market Street, Sydney NSW 2000, Australia',
    'https://asic.gov.au',
    '',
    'https://twitter.com/asicmedia',
    '',
    'https://www.linkedin.com/company/australian-securities-and-investments-commission/',
    'https://asic.gov.au/for-business/registering-a-company/',
    'https://business.gov.au/planning/new-businesses/register-a-company',
    'Australian Company Number (ACN)',
  ),
  BN:   office(
    'Registry of Companies and Business Names (ROCBN)',
    '+673 2383444',
    'Ministry of Finance and Economy, Bandar Seri Begawan, Brunei Darussalam',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    '',
    '',
    '',
    '',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    'https://business.gov.bn/SitePages/Starting%20a%20Business.aspx',
    'Business Registration Number',
  ),
  CA:   office(
    'Corporations Canada (Innovation, Science and Economic Development)',
    '+1 866 333 5556',
    '235 Queen Street, Ottawa, ON K1A 0H5, Canada',
    'https://ised-isde.canada.ca/site/corporations-canada/en',
    '',
    '',
    '',
    '',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/incorporate-business-corporation',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/steps-incorporating',
    'Corporation Number',
  ),
  CL:   office(
    'Registro de Empresas y Sociedades (Tu Empresa en un Dia)',
    '+56 2 2440 6000',
    'Santiago, Chile',
    'https://www.registrodeempresasysociedades.cl',
    '',
    '',
    '',
    '',
    'https://www.registrodeempresasysociedades.cl',
    'https://www.chileatiende.gob.cl/fichas/31239-constituir-una-sociedad-en-el-registro-de-empresas-y-sociedades-res',
    'Rol Unico Tributario (RUT)',
  ),
  JP:   office(
    'Legal Affairs Bureau (Ministry of Justice Commercial Registration)',
    '+81 3 3580 4111',
    '1-1-1 Kasumigaseki, Chiyoda-ku, Tokyo, Japan',
    'https://www.moj.go.jp',
    '',
    '',
    '',
    '',
    'https://www.moj.go.jp/MINJI/minji06.html',
    'https://www.jetro.go.jp/en/invest/setting_up/section1/page3.html',
    'Corporate Number (Houjin Bango)',
  ),
  MY:   office(
    'Companies Commission of Malaysia (SSM)',
    '+60 3 7721 4000',
    'Menara SSM@Sentral, No. 7 Jalan Stesen Sentral 5, Kuala Lumpur, Malaysia',
    'https://www.ssm.com.my',
    'enquiry@ssm.com.my',
    '',
    '',
    '',
    'https://ezbiz.ssm.com.my',
    'https://www.ssm.com.my/Pages/Legal_Framework/Company/Guidelines.aspx',
    'Company Number',
  ),
  MX:   office(
    'Secretaria de Economia - Tu Empresa',
    '+52 55 5729 9100',
    'Av. Insurgentes Sur 1940, Mexico City, Mexico',
    'https://www.gob.mx/se',
    '',
    '',
    '',
    '',
    'https://www.gob.mx/tuempresa',
    'https://www.gob.mx/tramites/ficha/constitucion-de-sociedades/SRE2566',
    'Registro Federal de Contribuyentes (RFC)',
  ),
  NZ:   office(
    'New Zealand Companies Office',
    '+64 50 872 2669',
    'Wellington, New Zealand',
    'https://companies-register.companiesoffice.govt.nz',
    '',
    '',
    '',
    '',
    'https://companies-register.companiesoffice.govt.nz/help-centre/starting-a-company',
    'https://www.business.govt.nz/getting-started/advice-for-start-ups/10-step-guide-to-starting-a-business/',
    'New Zealand Business Number (NZBN)',
  ),
  PE:   office(
    'SUNARP - SID Sunarp',
    '+51 1 208 3100',
    'Av. Primavera 1878, Santiago de Surco, Lima, Peru',
    'https://www.sunarp.gob.pe',
    '',
    '',
    '',
    '',
    'https://sid.sunarp.gob.pe',
    'https://www.gob.pe/709-inscribir-una-empresa-en-el-registro-de-personas-juridicas',
    'Registro Unico de Contribuyentes (RUC)',
  ),
  SG:   office(
    'Accounting and Corporate Regulatory Authority (ACRA)',
    '+65 6248 6028',
    '10 Anson Road, International Plaza, Singapore',
    'https://www.acra.gov.sg',
    '',
    '',
    '',
    'https://www.linkedin.com/company/accounting-and-corporate-regulatory-authority-acra-/',
    'https://www.bizfile.gov.sg',
    'https://www.acra.gov.sg/how-to-guides/before-you-start/incorporation',
    'Unique Entity Number (UEN)',
  ),
  GB:   office(
    'Companies House United Kingdom',
    '+44 303 1234 500',
    'Crown Way, Cardiff CF14 3UZ, United Kingdom',
    'https://www.gov.uk/government/organisations/companies-house',
    'enquiries@companieshouse.gov.uk',
    'https://twitter.com/CompaniesHouse',
    '',
    'https://www.linkedin.com/company/companies-house/',
    'https://www.gov.uk/limited-company-formation',
    'https://www.gov.uk/set-up-limited-company',
    'Company Registration Number (CRN)',
  ),
  VN:   office(
    'Business Registration Management Agency (Ministry of Finance)',
    '+84 24 0804 3128',
    'Hanoi, Vietnam',
    'https://dangkykinhdoanh.gov.vn',
    '',
    '',
    '',
    '',
    'https://dangkykinhdoanh.gov.vn',
    'https://dangkykinhdoanh.gov.vn/vn/Pages/Trangchu.aspx',
    'Tax Identification Number (MST)',
  ),
}
