import type { CptppMemberIsoCode } from './cptppMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for CPTPP parties
 * (informational; verify URLs, handles, forms portals, and API bases before production
 * use). Self-contained — no imports from other alliance modules. `apiEndpoint` is almost
 * always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const CPTPP_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  CptppMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AU: roster(
    ip(
      'copyright',
      'Australian Government — Attorney-General\'s Department (Copyright)',
      'https://www.ag.gov.au/rights-and-protections/copyright',
      '',
      '',
      '',
      'https://www.ag.gov.au/rights-and-protections/copyright',
    ),
    ip(
      'trademarks',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
    ip(
      'patents',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
  ),
  BN: roster(
    ip(
      'copyright',
      'Brunei Darussalam Intellectual Property Office (BruIPO) — copyright',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'trademarks',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'patents',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
  ),
  CA: roster(
    ip(
      'copyright',
      'Canadian Intellectual Property Office (CIPO) — copyright',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'trademarks',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'patents',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
  ),
  CL: roster(
    ip(
      'copyright',
      'Ministerio de las Culturas, las Artes y el Patrimonio — Dirección de Derecho de Autor',
      'https://www.cultura.gob.cl',
      '',
      'https://x.com/mincultura',
      '',
      'https://www.cultura.gob.cl',
    ),
    ip(
      'trademarks',
      'Instituto Nacional de Propiedad Industrial (INAPI Chile)',
      'https://www.inapi.cl',
      'contacto@inapi.cl',
      'https://x.com/INAPIChile',
      'https://www.linkedin.com/company/inapi-chile/',
      'https://tramites.inapi.cl',
    ),
    ip(
      'patents',
      'Instituto Nacional de Propiedad Industrial (INAPI Chile)',
      'https://www.inapi.cl',
      'contacto@inapi.cl',
      'https://x.com/INAPIChile',
      'https://www.linkedin.com/company/inapi-chile/',
      'https://tramites.inapi.cl',
    ),
  ),
  JP: roster(
    ip(
      'copyright',
      'Agency for Cultural Affairs (Government of Japan — Copyright)',
      'https://www.bunka.go.jp/english/',
      '',
      '',
      '',
      'https://www.bunka.go.jp/english/copyright/index.html',
    ),
    ip(
      'trademarks',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
    ip(
      'patents',
      'Japan Patent Office (JPO)',
      'https://www.jpo.go.jp',
      '',
      '',
      '',
      'https://www.j-platpat.inpit.go.jp/',
    ),
  ),
  MY: roster(
    ip(
      'copyright',
      'Intellectual Property Corporation of Malaysia (MyIPO) — copyright',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'trademarks',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'patents',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
  ),
  MX: roster(
    ip(
      'copyright',
      'Instituto Nacional del Derecho de Autor (INDAUTOR)',
      'https://www.indautor.gob.mx',
      'indautor@indautor.gob.mx',
      'https://x.com/INDAUTORMX',
      '',
      'https://www.indautor.gob.mx/servicios/',
    ),
    ip(
      'trademarks',
      'Mexican Institute of Industrial Property (IMPI)',
      'https://www.gob.mx/impi',
      'impi@impi.gob.mx',
      'https://x.com/IMPI_MX',
      'https://www.linkedin.com/company/impi/',
      'https://www.gob.mx/impi/acciones-y-programas/servicios-en-linea',
    ),
    ip(
      'patents',
      'Mexican Institute of Industrial Property (IMPI)',
      'https://www.gob.mx/impi',
      'impi@impi.gob.mx',
      'https://x.com/IMPI_MX',
      'https://www.linkedin.com/company/impi/',
      'https://www.gob.mx/impi/acciones-y-programas/servicios-en-linea',
    ),
  ),
  NZ: roster(
    ip(
      'copyright',
      'Manatū Taonga — Ministry for Culture and Heritage (Copyright)',
      'https://www.mch.govt.nz',
      'info@mch.govt.nz',
      '',
      '',
      'https://www.mch.govt.nz/copyright',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
    ip(
      'patents',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
  ),
  PE: roster(
    ip(
      'copyright',
      'National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI) — copyright',
      'https://www.indecopi.gob.pe',
      'consultas@indecopi.gob.pe',
      'https://x.com/INDECOPI',
      'https://www.linkedin.com/company/indecopi/',
      'https://www.indecopi.gob.pe/servicios-en-linea',
    ),
    ip(
      'trademarks',
      'National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI)',
      'https://www.indecopi.gob.pe',
      'consultas@indecopi.gob.pe',
      'https://x.com/INDECOPI',
      'https://www.linkedin.com/company/indecopi/',
      'https://www.indecopi.gob.pe/servicios-en-linea',
    ),
    ip(
      'patents',
      'National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI)',
      'https://www.indecopi.gob.pe',
      'consultas@indecopi.gob.pe',
      'https://x.com/INDECOPI',
      'https://www.linkedin.com/company/indecopi/',
      'https://www.indecopi.gob.pe/servicios-en-linea',
    ),
  ),
  SG: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Singapore (IPOS) — copyright',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
  ),
  GB: roster(
    ip(
      'copyright',
      'Intellectual Property Office (UK) — copyright guidance',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'patents',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
  ),
  VN: roster(
    ip(
      'copyright',
      'Copyright Office of Vietnam (COV)',
      'https://cov.gov.vn',
      '',
      '',
      '',
      'https://cov.gov.vn',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Vietnam (NOIP)',
      'https://www.noip.gov.vn',
      'noip@noip.gov.vn',
      '',
      '',
      'https://www.noip.gov.vn/en-US/OnlineFiling',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Vietnam (NOIP)',
      'https://www.noip.gov.vn',
      'noip@noip.gov.vn',
      '',
      '',
      'https://www.noip.gov.vn/en-US/OnlineFiling',
    ),
  ),
}
