import type { CptppMemberIsoCode } from './cptppMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const CPTPP_MAIN_INTERNATIONAL_AIRPORTS: Record<CptppMemberIsoCode, MainInternationalAirport> = {
  AU: {
    name: 'Sydney Kingsford Smith Airport (SYD)',
    website: 'https://www.sydneyairport.com.au/',
    email: 'info@sydneyairport.com.au',
    twitter: 'https://x.com/SydneyAirport',
    instagram: 'https://www.instagram.com/sydneyairport/',
    linkedin: 'https://www.linkedin.com/company/sydney-airport/',
    apiEndpoint: '',
  },
  BN: {
    name: 'Brunei International Airport (BWN)',
    website: 'https://www.bruneiair.com/',
    email: 'info@bruneiair.com',
    twitter: 'https://x.com/BruneiAirport',
    instagram: 'https://www.instagram.com/bruneiairport/',
    linkedin: 'https://www.linkedin.com/company/brunei-international-airport/',
    apiEndpoint: '',
  },
  CA: {
    name: 'Toronto Pearson International Airport (YYZ)',
    website: 'https://www.torontopearson.com/',
    email: 'info@torontopearson.com',
    twitter: 'https://x.com/TorontoPearson',
    instagram: 'https://www.instagram.com/torontopearson/',
    linkedin: 'https://www.linkedin.com/company/toronto-pearson-international-airport/',
    apiEndpoint: '',
  },
  CL: {
    name: 'Arturo Merino Benítez International Airport (SCL)',
    website: 'https://www.nuestroaeropuerto.cl/',
    email: 'contacto@nuestroaeropuerto.cl',
    twitter: 'https://x.com/AeropuertoSCL',
    instagram: 'https://www.instagram.com/aeropuertoscl/',
    linkedin: 'https://www.linkedin.com/company/nuevo-aeropuerto-internacional-arturo-merino-benitez/',
    apiEndpoint: '',
  },
  JP: {
    name: 'Tokyo Haneda Airport (HND)',
    website: 'https://www.haneda-airport.jp/',
    email: 'info@haneda-airport.jp',
    twitter: 'https://x.com/TokyoHaneda',
    instagram: 'https://www.instagram.com/tokyohaneda/',
    linkedin: 'https://www.linkedin.com/company/tokyo-international-airport/',
    apiEndpoint: '',
  },
  MY: {
    name: 'Kuala Lumpur International Airport (KUL)',
    website: 'https://www.klia.com.my/',
    email: 'info@klia.com.my',
    twitter: 'https://x.com/KLIA_Malaysia',
    instagram: 'https://www.instagram.com/klia_malaysia/',
    linkedin: 'https://www.linkedin.com/company/malaysia-airports/',
    apiEndpoint: '',
  },
  MX: {
    name: 'Mexico City International Airport (MEX)',
    website: 'https://www.aicm.com.mx/',
    email: 'contacto@aicm.com.mx',
    twitter: 'https://x.com/AICM_mx',
    instagram: 'https://www.instagram.com/aicm_mx/',
    linkedin: 'https://www.linkedin.com/company/aeropuerto-internacional-de-la-ciudad-de-mexico/',
    apiEndpoint: '',
  },
  NZ: {
    name: 'Auckland Airport (AKL)',
    website: 'https://www.aucklandairport.co.nz/',
    email: 'info@aucklandairport.co.nz',
    twitter: 'https://x.com/AucklandAirport',
    instagram: 'https://www.instagram.com/aucklandairport/',
    linkedin: 'https://www.linkedin.com/company/auckland-airport/',
    apiEndpoint: '',
  },
  PE: {
    name: 'Jorge Chávez International Airport (LIM)',
    website: 'https://www.lima-airport.com/',
    email: 'info@lima-airport.com',
    twitter: 'https://x.com/LimaAirport',
    instagram: 'https://www.instagram.com/limaairport/',
    linkedin: 'https://www.linkedin.com/company/lima-airport-partners/',
    apiEndpoint: '',
  },
  SG: {
    name: 'Singapore Changi Airport (SIN)',
    website: 'https://www.changiairport.com/',
    email: 'feedback@changiairport.com',
    twitter: 'https://x.com/ChangiAirport',
    instagram: 'https://www.instagram.com/changiairport/',
    linkedin: 'https://www.linkedin.com/company/changi-airport-group/',
    apiEndpoint: '',
  },
  GB: {
    name: 'Heathrow Airport (LHR)',
    website: 'https://www.heathrow.com/',
    email: 'customer.service@heathrow.com',
    twitter: 'https://x.com/HeathrowAirport',
    instagram: 'https://www.instagram.com/heathrowairport/',
    linkedin: 'https://www.linkedin.com/company/heathrow-airport/',
    apiEndpoint: '',
  },
  VN: {
    name: 'Noi Bai International Airport (HAN)',
    website: 'https://www.noibaiairport.vn/',
    email: 'info@noibaiairport.vn',
    twitter: 'https://x.com/NoiBaiAirport',
    instagram: 'https://www.instagram.com/noibaiairport/',
    linkedin: 'https://www.linkedin.com/company/noi-bai-international-airport/',
    apiEndpoint: '',
  },
}
