import type { NationalBankingInstitution } from './types'
import type { CptppMemberIsoCode } from './cptppMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per CPTPP party economy.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const CPTPP_NATIONAL_BANKING_INSTITUTIONS: Record<
  CptppMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  AU: [
    bank(
      'Commonwealth Bank of Australia',
      '+61 13 2221',
      'Ground Floor, Tower 1, 201 Sussex Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/commbank/id310251020',
      'https://play.google.com/store/apps/details?id=com.commbank.netbank',
      'https://www.commbank.com.au',
      'customercare@cba.com.au',
      'https://twitter.com/CommBank',
      'https://www.instagram.com/commbank/',
      'https://www.linkedin.com/company/commonwealth-bank/',
      '',
      'CTBAAU2S',
      'https://api.commbank.com.au',
    ),
    bank(
      'Westpac Banking Corporation',
      '+61 13 2032',
      '275 Kent Street, Sydney, NSW, Australia',
      'https://apps.apple.com/au/app/westpac-mobile-banking/id284826145',
      'https://play.google.com/store/apps/details?id=org.westpac.bank',
      'https://www.westpac.com.au',
      'customercare@westpac.com.au',
      'https://twitter.com/Westpac',
      'https://www.instagram.com/westpac/',
      'https://www.linkedin.com/company/westpac/',
      '',
      'WPACAU2S',
      'https://developer.westpac.com.au',
    ),
    bank(
      'Australia and New Zealand Banking Group',
      '+61 13 13 14',
      '833 Collins Street, Docklands, VIC, Australia',
      'https://apps.apple.com/au/app/anz-australia/id385348415',
      'https://play.google.com/store/apps/details?id=com.anz.android',
      'https://www.anz.com.au',
      'contactus@anz.com',
      'https://twitter.com/ANZ_AU',
      'https://www.instagram.com/anz_au/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBAU3M',
      'https://developer.anz.com',
    ),
  ],
  BN: [
    bank(
      'Baiduri Bank',
      '+673 2449666',
      'Baiduri Community Space, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/baiduri-b-token/id1414199588',
      'https://play.google.com/store/apps/details?id=com.baiduri.mobilebanking',
      'https://www.baiduri.com.bn',
      'info@baiduri.com.bn',
      'https://twitter.com/baiduribank',
      'https://www.instagram.com/baiduribank/',
      'https://www.linkedin.com/company/baiduri-bank/',
      '',
      'BAIDBNDX',
      '',
    ),
    bank(
      'Bank Islam Brunei Darussalam',
      '+673 2238181',
      'Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/bn/app/bibd-nexgen-wallet/id1541812683',
      'https://play.google.com/store/apps/details?id=com.bibd.nexgen',
      'https://www.bibd.com.bn',
      'enquiry@bibd.com.bn',
      'https://twitter.com/BIBDBrunei',
      'https://www.instagram.com/bibdbrunei/',
      'https://www.linkedin.com/company/bibd/',
      '',
      'BIBDBNBB',
      '',
    ),
    bank(
      'Standard Chartered Brunei',
      '+673 2658000',
      'Jalan Sultan, Bandar Seri Begawan, Brunei',
      'https://apps.apple.com/sg/app/sc-mobile-singapore/id445120671',
      'https://play.google.com/store/apps/details?id=com.sc.breezenxt.bn',
      'https://www.sc.com/bn',
      'clientcare.bnd@sc.com',
      'https://twitter.com/StanChart',
      'https://www.instagram.com/stanchart/',
      'https://www.linkedin.com/company/standard-chartered-bank/',
      '',
      'SCBLBNDX',
      '',
    ),
  ],
  CA: [
    bank(
      'Royal Bank of Canada',
      '+1 416 974 5151',
      '200 Bay Street, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/rbc-mobile/id407597290',
      'https://play.google.com/store/apps/details?id=com.rbc.mobile.android',
      'https://www.rbc.com',
      'info@rbc.com',
      'https://twitter.com/RBC',
      'https://www.instagram.com/rbc/',
      'https://www.linkedin.com/company/rbc/',
      '',
      'ROYCCAT2',
      '',
    ),
    bank(
      'Toronto-Dominion Bank',
      '+1 416 308 9030',
      '66 Wellington Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/td-canada/id358071948',
      'https://play.google.com/store/apps/details?id=com.td',
      'https://www.td.com',
      'customer.service@td.com',
      'https://twitter.com/TD_Canada',
      'https://www.instagram.com/td_canada/',
      'https://www.linkedin.com/company/td/',
      '',
      'TDOMCATTTOR',
      '',
    ),
    bank(
      'Scotiabank',
      '+1 416 933 8000',
      '44 King Street West, Toronto, ON, Canada',
      'https://apps.apple.com/ca/app/scotiabank/id341351824',
      'https://play.google.com/store/apps/details?id=ca.scotiabank.banking',
      'https://www.scotiabank.com',
      'customer.service@scotiabank.com',
      'https://twitter.com/Scotiabank',
      'https://www.instagram.com/scotiabank/',
      'https://www.linkedin.com/company/scotiabank/',
      '',
      'NOSCCATT',
      '',
    ),
  ],
  CL: [
    bank(
      'Banco de Chile',
      '+56 2 2637 1111',
      'Ahumada 251, Santiago, Chile',
      'https://apps.apple.com/cl/app/banco-de-chile/id404124896',
      'https://play.google.com/store/apps/details?id=cl.bancochile.mi_banco',
      'https://www.bancochile.cl',
      'informaciones@bancochile.cl',
      'https://twitter.com/bancodechile',
      'https://www.instagram.com/bancodechile/',
      'https://www.linkedin.com/company/banco-de-chile/',
      '',
      'BCHICLRM',
      '',
    ),
    bank(
      'Banco Santander Chile',
      '+56 2 2320 2000',
      'Bandera 140, Santiago, Chile',
      'https://apps.apple.com/cl/app/banco-santander-chile/id498462567',
      'https://play.google.com/store/apps/details?id=cl.santander.santander',
      'https://www.santander.cl',
      'contacto@santander.cl',
      'https://twitter.com/SantanderChile',
      'https://www.instagram.com/santanderchile/',
      'https://www.linkedin.com/company/banco-santander-chile/',
      '',
      'BSCHCLRM',
      '',
    ),
    bank(
      'BancoEstado',
      '+56 2 2670 7000',
      'Morande 25, Santiago, Chile',
      'https://apps.apple.com/cl/app/bancoestado/id450526199',
      'https://play.google.com/store/apps/details?id=cl.bancoestado.bemovil',
      'https://www.bancoestado.cl',
      'contacto@bancoestado.cl',
      'https://twitter.com/BancoEstado',
      'https://www.instagram.com/bancoestado/',
      'https://www.linkedin.com/company/bancoestado/',
      '',
      'BECHCLRM',
      '',
    ),
  ],
  JP: [
    bank(
      'MUFG Bank',
      '+81 3 3240 1111',
      '2-7-1 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mufg/id1249041409',
      'https://play.google.com/store/apps/details?id=jp.co.bk.mufg.bkapp',
      'https://www.bk.mufg.jp',
      'info@bk.mufg.jp',
      'https://twitter.com/MUFG',
      '',
      'https://www.linkedin.com/company/mufg/',
      '',
      'BOTKJPJT',
      '',
    ),
    bank(
      'Sumitomo Mitsui Banking Corporation',
      '+81 3 3282 8111',
      '1-1-2 Marunouchi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/smbc/id398950681',
      'https://play.google.com/store/apps/details?id=jp.co.smbc.banking',
      'https://www.smbc.co.jp',
      'koho@smbc.co.jp',
      'https://twitter.com/SMBCGroup',
      '',
      'https://www.linkedin.com/company/smbc-group/',
      '',
      'SMBCJPJT',
      '',
    ),
    bank(
      'Mizuho Bank',
      '+81 3 3214 1111',
      '1-5-5 Otemachi, Chiyoda-ku, Tokyo, Japan',
      'https://apps.apple.com/jp/app/mizuho-direct/id1535103293',
      'https://play.google.com/store/apps/details?id=jp.co.mizuhobank.direct',
      'https://www.mizuhobank.co.jp',
      'info@mizuho-fg.co.jp',
      'https://twitter.com/MizuhoGroup',
      '',
      'https://www.linkedin.com/company/mizuho/',
      '',
      'MHCBJPJT',
      '',
    ),
  ],
  MY: [
    bank(
      'Maybank',
      '+60 3 2070 8833',
      'Menara Maybank, 100 Jalan Tun Perak, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/mae-by-maybank2u/id1455827893',
      'https://play.google.com/store/apps/details?id=com.maybank2u.life',
      'https://www.maybank2u.com.my',
      'mgcc@maybank.com.my',
      'https://twitter.com/MyMaybank',
      'https://www.instagram.com/maybank/',
      'https://www.linkedin.com/company/maybank/',
      '',
      'MBBEMYKL',
      '',
    ),
    bank(
      'CIMB Bank',
      '+60 3 6204 7788',
      'Menara CIMB, Jalan Stesen Sentral 2, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/cimb-octo-my/id1533904065',
      'https://play.google.com/store/apps/details?id=com.cimbmalaysia',
      'https://www.cimb.com.my',
      'contactus@cimb.com',
      'https://twitter.com/CIMBMalaysia',
      'https://www.instagram.com/cimbmalaysia/',
      'https://www.linkedin.com/company/cimb/',
      '',
      'CIBBMYKL',
      '',
    ),
    bank(
      'Public Bank',
      '+60 3 2176 8000',
      'Menara Public Bank, Jalan Raja Chulan, Kuala Lumpur, Malaysia',
      'https://apps.apple.com/my/app/pbe/id1181169389',
      'https://play.google.com/store/apps/details?id=com.publicbank.pbeng',
      'https://www.pbebank.com',
      'customersupport@publicbank.com.my',
      'https://twitter.com/PublicBankGroup',
      '',
      'https://www.linkedin.com/company/public-bank-berhad/',
      '',
      'PBBEMYKL',
      '',
    ),
  ],
  MX: [
    bank(
      'BBVA Mexico',
      '+52 55 5621 3434',
      'Paseo de la Reforma 510, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/bbva-mexico/id375408965',
      'https://play.google.com/store/apps/details?id=com.bancomer.mbanking',
      'https://www.bbva.mx',
      'une.mx@bbva.com',
      'https://twitter.com/BBVA_Mex',
      'https://www.instagram.com/bbva_mex/',
      'https://www.linkedin.com/company/bbva-mexico/',
      '',
      'BCMRMXMM',
      '',
    ),
    bank(
      'Banorte',
      '+52 81 8156 9600',
      'Av. Revolucion 3000 Sur, Monterrey, Mexico',
      'https://apps.apple.com/mx/app/banorte-movil/id445541658',
      'https://play.google.com/store/apps/details?id=com.banorte.movil',
      'https://www.banorte.com',
      'une@banorte.com',
      'https://twitter.com/Banorte_mx',
      'https://www.instagram.com/banorte_mx/',
      'https://www.linkedin.com/company/grupo-financiero-banorte/',
      '',
      'MENOMXMT',
      '',
    ),
    bank(
      'Citibanamex',
      '+52 55 1226 2639',
      'Isabel la Catolica 44, Mexico City, Mexico',
      'https://apps.apple.com/mx/app/citibanamex-movil/id394943449',
      'https://play.google.com/store/apps/details?id=com.citibanamex.banamexmobile',
      'https://www.banamex.com',
      'atencionaclientes@citibanamex.com',
      'https://twitter.com/Citibanamex',
      'https://www.instagram.com/citibanamex/',
      'https://www.linkedin.com/company/citibanamex/',
      '',
      'BNMXMXMM',
      '',
    ),
  ],
  NZ: [
    bank(
      'ANZ New Zealand',
      '+64 9 252 6777',
      '23 Albert Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/anz-go-money-nz/id486726860',
      'https://play.google.com/store/apps/details?id=nz.co.anz.android.mobilebanking',
      'https://www.anz.co.nz',
      'info@anz.co.nz',
      'https://twitter.com/ANZ_NZ',
      'https://www.instagram.com/anz_nz/',
      'https://www.linkedin.com/company/anz/',
      '',
      'ANZBNZ22',
      '',
    ),
    bank(
      'ASB Bank',
      '+64 9 306 3000',
      '12 Jellicoe Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/asb-mobile-banking/id384056323',
      'https://play.google.com/store/apps/details?id=nz.co.asb.asbmobile',
      'https://www.asb.co.nz',
      'info@asb.co.nz',
      'https://twitter.com/ASBBank',
      'https://www.instagram.com/asbbank/',
      'https://www.linkedin.com/company/asb-bank/',
      '',
      'ASBBNZ2A',
      '',
    ),
    bank(
      'Bank of New Zealand',
      '+64 9 924 9000',
      '80 Queen Street, Auckland, New Zealand',
      'https://apps.apple.com/nz/app/bnz-mobile/id413489435',
      'https://play.google.com/store/apps/details?id=nz.co.bnz.droidbanking',
      'https://www.bnz.co.nz',
      'bnz_reception@bnz.co.nz',
      'https://twitter.com/bnz',
      'https://www.instagram.com/bankofnz/',
      'https://www.linkedin.com/company/bank-of-new-zealand/',
      '',
      'BKNZNZ22',
      '',
    ),
  ],
  PE: [
    bank(
      'Banco de Credito del Peru',
      '+51 1 311 9898',
      'Calle Centenario 156, La Molina, Lima, Peru',
      'https://apps.apple.com/pe/app/bcp/id511971097',
      'https://play.google.com/store/apps/details?id=pe.com.bcp.inbanking',
      'https://www.viabcp.com',
      'contacto@bcp.com.pe',
      'https://twitter.com/BCPComunica',
      'https://www.instagram.com/viabcp/',
      'https://www.linkedin.com/company/bcp/',
      '',
      'BCPLPEPL',
      '',
    ),
    bank(
      'Interbank Peru',
      '+51 1 219 2000',
      'Carlos Villaran 140, La Victoria, Lima, Peru',
      'https://apps.apple.com/pe/app/interbank-app/id455429155',
      'https://play.google.com/store/apps/details?id=pe.interbank.mobilebanking',
      'https://www.interbank.pe',
      'servicioalcliente@intercorp.com.pe',
      'https://twitter.com/Interbank',
      'https://www.instagram.com/interbank/',
      'https://www.linkedin.com/company/interbank/',
      '',
      'BINPPEPL',
      '',
    ),
    bank(
      'BBVA Peru',
      '+51 1 595 0000',
      'Av. Republica de Panama 3055, San Isidro, Lima, Peru',
      'https://apps.apple.com/pe/app/bbva-peru/id375267788',
      'https://play.google.com/store/apps/details?id=com.bbva.netcash.peru',
      'https://www.bbva.pe',
      'contacto.pe@bbva.com',
      'https://twitter.com/BBVA_Peru',
      'https://www.instagram.com/bbva_peru/',
      'https://www.linkedin.com/company/bbva-en-peru/',
      '',
      'BCONPEPL',
      '',
    ),
  ],
  SG: [
    bank(
      'DBS Bank',
      '+65 6878 8888',
      '12 Marina Boulevard, Marina Bay Financial Centre, Singapore',
      'https://apps.apple.com/sg/app/dbs-digibank/id1068403820',
      'https://play.google.com/store/apps/details?id=com.dbs.sg.dbsmbanking',
      'https://www.dbs.com.sg',
      'contactus@dbs.com',
      'https://twitter.com/dbsbank',
      'https://www.instagram.com/dbsbank/',
      'https://www.linkedin.com/company/dbs-bank/',
      '',
      'DBSSSGSG',
      '',
    ),
    bank(
      'OCBC Bank',
      '+65 6363 3333',
      '65 Chulia Street, OCBC Centre, Singapore',
      'https://apps.apple.com/sg/app/ocbc-digital/id292506828',
      'https://play.google.com/store/apps/details?id=com.ocbc.mobile',
      'https://www.ocbc.com',
      'contactus@ocbc.com',
      'https://twitter.com/OCBCBank',
      'https://www.instagram.com/ocbc/',
      'https://www.linkedin.com/company/ocbc-bank/',
      '',
      'OCBCSGSG',
      '',
    ),
    bank(
      'UOB',
      '+65 6222 2121',
      '80 Raffles Place, UOB Plaza, Singapore',
      'https://apps.apple.com/sg/app/uob-tmrw/id1314626819',
      'https://play.google.com/store/apps/details?id=com.uob.might',
      'https://www.uob.com.sg',
      'uobcustomerservice@uobgroup.com',
      'https://twitter.com/UOBGroup',
      'https://www.instagram.com/uobgroup/',
      'https://www.linkedin.com/company/uob/',
      '',
      'UOVBSGSG',
      '',
    ),
  ],
  GB: [
    bank(
      'HSBC UK Bank',
      '+44 345 740 4404',
      '8 Canada Square, London, United Kingdom',
      '',
      '',
      'https://www.hsbc.co.uk',
      'ukcustomer.services@hsbc.com',
      '',
      '',
      '',
      '',
      'HBUKGB4B',
      '',
    ),
    bank(
      'Barclays Bank UK',
      '+44 20 7116 1000',
      '1 Churchill Place, London, United Kingdom',
      '',
      '',
      'https://www.barclays.co.uk',
      'customer.services@barclays.co.uk',
      '',
      '',
      '',
      '',
      'BARCGB22',
      '',
    ),
    bank(
      'Lloyds Bank',
      '+44 20 7626 1500',
      '25 Gresham Street, London, United Kingdom',
      '',
      '',
      'https://www.lloydsbank.com',
      'onlinecomplaints@lloydsbank.co.uk',
      '',
      '',
      '',
      '',
      'LOYDGB2L',
      '',
    ),
  ],
  VN: [
    bank(
      'Vietcombank',
      '+84 24 3934 3137',
      '198 Tran Quang Khai, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vcb-digibank/id561433131',
      'https://play.google.com/store/apps/details?id=com.vietcombank.vcbmobile',
      'https://www.vietcombank.com.vn',
      'vcb@vietcombank.com.vn',
      'https://twitter.com/Vietcombank',
      'https://www.instagram.com/vietcombank/',
      'https://www.linkedin.com/company/vietcombank/',
      '',
      'BFTVVNVX',
      '',
    ),
    bank(
      'BIDV',
      '+84 24 2220 5544',
      '35 Hang Voi, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/bidv-smartbanking/id1283524786',
      'https://play.google.com/store/apps/details?id=com.vnpay.bidv',
      'https://www.bidv.com.vn',
      'bidv247@bidv.com.vn',
      'https://twitter.com/BIDV',
      '',
      'https://www.linkedin.com/company/bidv/',
      '',
      'BIDVVNVX',
      '',
    ),
    bank(
      'VietinBank',
      '+84 24 3941 8868',
      '108 Tran Hung Dao, Hoan Kiem, Hanoi, Vietnam',
      'https://apps.apple.com/vn/app/vietinbank-ipay-mobile/id542298015',
      'https://play.google.com/store/apps/details?id=com.vietinbank.ipay',
      'https://www.vietinbank.vn',
      'contact@vietinbank.vn',
      'https://twitter.com/VietinBank',
      '',
      'https://www.linkedin.com/company/vietinbank/',
      '',
      'ICBVVNVX',
      '',
    ),
  ],
}
