import type { CorporationFormationOffice } from './types'
import type { EacMemberIsoCode } from './eacMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per EAC partner state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const EAC_CORPORATION_FORMATION_OFFICES: Record<EacMemberIsoCode, CorporationFormationOffice> = {
  BI:   office(
    'Agence de Developpement du Burundi (ADB) - Guichet Unique',
    '+257 22 27 90 00',
    'Avenue du Large, Immeuble Old East, Bujumbura, Burundi',
    'https://investburundi.bi',
    'info@investburundi.bi',
    '',
    '',
    '',
    'https://investburundi.bi/guichet-unique',
    'https://investburundi.bi/procedures-de-creation',
    'Numero RCCM',
  ),
  CD:   office(
    'Guichet Unique de Creation d\'Entreprise (GUCE DRC)',
    '+243 81 555 7000',
    'Immeuble Fickin, Boulevard du 30 Juin, Gombe, Kinshasa, DR Congo',
    'https://guichetunique.cd',
    'contact@guichetunique.cd',
    '',
    '',
    '',
    'https://guichetunique.cd/creation-dentreprise',
    'https://guichetunique.cd/pieces-a-fournir',
    'Numero RCCM',
  ),
  KE:   office(
    'Business Registration Service (BRS Kenya)',
    '+254 20 222 7461',
    'Sheria House, Harambee Avenue, Nairobi, Kenya',
    'https://brs.go.ke',
    'info@brs.go.ke',
    'https://x.com/BRS_Kenya',
    '',
    'https://www.linkedin.com/company/business-registration-service-kenya/',
    'https://brs.go.ke/service/company-registration',
    'https://www.ecitizen.go.ke',
    'Certificate of Incorporation Number',
  ),
  RW:   office(
    'Rwanda Development Board (RDB) - Business Registration',
    '+250 252 587 441',
    'KG 9 Avenue, Nyarutarama, Kigali, Rwanda',
    'https://rdb.rw',
    'info@rdb.rw',
    'https://x.com/RDBrwanda',
    'https://www.instagram.com/visitrwanda_now/',
    'https://www.linkedin.com/company/rwanda-development-board/',
    'https://org.rdb.rw',
    'https://rdb.rw/business/business-registration/',
    'Company Registration Number',
  ),
  SO:   office(
    'Ministry of Commerce and Industry Somalia - Company Registrar',
    '+252 61 553 3333',
    'Maka Al-Mukarama Road, Mogadishu, Somalia',
    'https://moci.gov.so',
    'info@moci.gov.so',
    '',
    '',
    '',
    'https://moci.gov.so/services/business-registration',
    '',
    'Business Registration Number',
  ),
  SS:   office(
    'Ministry of Justice and Constitutional Affairs South Sudan - Business Registry',
    '+211 92 348 8800',
    'Ministries Road, Juba, South Sudan',
    'https://www.mojca.gov.ss',
    'info@mojca.gov.ss',
    '',
    '',
    '',
    'https://www.mojca.gov.ss/services/business-registration',
    '',
    'Certificate of Incorporation Number',
  ),
  TZ:   office(
    'Business Registrations and Licensing Agency (BRELA Tanzania)',
    '+255 22 221 0113',
    'BRELA House, Shaaban Robert Street, Dar es Salaam, Tanzania',
    'https://www.brela.go.tz',
    'info@brela.go.tz',
    'https://x.com/BrelaTanzania',
    '',
    'https://www.linkedin.com/company/brela/',
    'https://ors.brela.go.tz',
    'https://www.brela.go.tz/index.php/business-registration',
    'Company Registration Number',
  ),
  UG:   office(
    'Uganda Registration Services Bureau (URSB)',
    '+256 414 233 219',
    'Plot 5 George Street, Georgian House, Kampala, Uganda',
    'https://www.ursb.go.ug',
    'registration@ursb.go.ug',
    'https://x.com/URSBHQ',
    '',
    'https://www.linkedin.com/company/uganda-registration-services-bureau/',
    'https://ursb.go.ug/business-registration/',
    'https://ursb.go.ug/forms-and-fees/',
    'Registration Number',
  ),
}
