import type { EacMemberIsoCode } from './eacMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per EAC partner state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const EAC_DOMESTIC_POST_SERVICES: Record<EacMemberIsoCode, DomesticPostService> = {
  BI: post(
    'Régie nationale des Postes du Burundi',
    'http://www.poste.bi/',
    'info@burundipost.bi',
    '',
    '',
    'https://www.linkedin.com/company/poste-burundi/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune-based addressing',
  ),
  CD: post(
    'SCPT RDC (Services postaux)',
    'https://scpt.cd/',
    'info@postesrdc.cd',
    '',
    '',
    'https://www.linkedin.com/company/scpt-rdc/',
    '',
    'none',
    '',
    '',
    'No universal national postcode; commune and P.O. Box',
  ),
  KE: post(
    'Postal Corporation of Kenya',
    'http://posta.co.ke/',
    'customercare@posta.co.ke',
    'https://x.com/postakenya',
    'https://www.instagram.com/postakenya/',
    'https://www.linkedin.com/company/postal-corporation-of-kenya/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00100',
    'Five-digit postcode; P.O. Box culture remains common',
  ),
  RW: post(
    'Rwanda Post (Iposita)',
    'https://i-posita.rw/',
    'info@ipostarltd.rw',
    'https://x.com/ipositaryw',
    'https://www.instagram.com/ipositaryw/',
    'https://www.linkedin.com/company/iposta-rwanda/',
    '',
    'none',
    '',
    '',
    'No legacy numeric postcode; Kigali addressing reforms — verify locally',
  ),
  SO: post(
    'Somali Postal Service',
    'https://www.upu.int/en/Somalia',
    'minister@mpt.gov.so',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district and landmark addressing',
  ),
  SS: post(
    'South Sudan Post',
    'http://ssscc.org/',
    'sssccngo@gmail.com',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system; Juba district addressing',
  ),
  TZ: post(
    'Tanzania Posts Corporation',
    'https://posta.co.tz/',
    'info@tpoc.co.tz',
    '',
    '',
    'https://www.linkedin.com/company/tanzania-posts-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '11101',
    'Five-digit postcode',
  ),
  UG: post(
    'Uganda Post Limited',
    'https://www.eposta.ug/',
    'info@posta.co.ug',
    'https://x.com/ugposts',
    'https://www.instagram.com/ugposts/',
    'https://www.linkedin.com/company/uganda-post-limited/',
    '',
    'none',
    '',
    '',
    'P.O. Box dominant; no universal street postcode',
  ),
}
