import type { NationalBankingInstitution } from './types'
import type { EacMemberIsoCode } from './eacMemberIsoCodes'

function bank(
  name: string,
  phone: string,
  address: string,
  mobileAppIos: string,
  mobileAppAndroid: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  generalRoutingNumber: string,
  swiftCode: string,
  apiEndpoint: string,
): NationalBankingInstitution {
  return {
    name,
    phone,
    address,
    mobileAppIos,
    mobileAppAndroid,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    generalRoutingNumber,
    swiftCode,
    apiEndpoint,
  }
}

/**
 * Three main national banking institutions per EAC partner state.
 * Informational; verify phone numbers, branch addresses, routing codes, SWIFT/BIC, mobile apps,
 * social handles, and API bases before production. Self-contained — no imports from other alliance modules.
 */
export const EAC_NATIONAL_BANKING_INSTITUTIONS: Record<
  EacMemberIsoCode,
  readonly [NationalBankingInstitution, NationalBankingInstitution, NationalBankingInstitution]
> = {
  BI: [
    bank(
      'Banque de Credit de Bujumbura (BCB)',
      '+257 22 22 10 88',
      'Boulevard de la Liberte, Bujumbura, Burundi',
      '',
      '',
      'https://www.bcb.bi/',
      'contact@bcb.bi',
      '',
      '',
      'https://www.linkedin.com/company/banque-de-cr%C3%A9dit-de-bujumbura/',
      '',
      'BCBIBIBI',
      '',
    ),
    bank(
      'Interbank Burundi',
      '+257 22 22 08 50',
      'Avenue de l Industrie, Bujumbura, Burundi',
      '',
      '',
      'https://www.interbankburundi.com/',
      'info@interbankburundi.com',
      '',
      '',
      'https://www.linkedin.com/company/interbank-burundi/',
      '',
      'INBKBIBI',
      '',
    ),
    bank(
      'BANCOBU',
      '+257 22 20 80 00',
      'Avenue du Large 26, Bujumbura, Burundi',
      '',
      '',
      'https://www.bancobu.bi/',
      'contact@bancobu.bi',
      '',
      '',
      'https://www.linkedin.com/company/bancobu/',
      '',
      'BCBUBIBI',
      '',
    ),
  ],
  CD: [
    bank(
      'Rawbank',
      '+243 99 601 1300',
      '3487 Boulevard du 30 Juin, Kinshasa, DR Congo',
      '',
      '',
      'https://www.rawbank.com/',
      'info@rawbank.com',
      'https://x.com/Rawbank',
      '',
      'https://www.linkedin.com/company/rawbank/',
      '',
      'RAWBCDKI',
      '',
    ),
    bank(
      'Equity BCDC',
      '+243 99 601 1301',
      '5 Avenue des Aviateurs, Kinshasa, DR Congo',
      '',
      '',
      'https://equitygroupholdings.com/cd/',
      'contact@equitygroupholdings.com',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-congo/',
      '',
      'BCDCCDKI',
      '',
    ),
    bank(
      'Ecobank DRC',
      '+243 81 555 7700',
      'Immeuble Ecobank, Gombe, Kinshasa, DR Congo',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/cd',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCCDKI',
      '',
    ),
  ],
  KE: [
    bank(
      'KCB Bank Kenya',
      '+254 20 3270000',
      'Kencom House, Moi Avenue, Nairobi, Kenya',
      '',
      '',
      'https://ke.kcbgroup.com/',
      'contactcentre@kcbgroup.com',
      '',
      '',
      'https://www.linkedin.com/company/kcb-bank-kenya-limited/',
      '',
      'KCBLKENX',
      '',
    ),
    bank(
      'Equity Bank Kenya',
      '+254 763 000 000',
      'Equity Centre, Hospital Road, Nairobi, Kenya',
      '',
      '',
      'https://equitygroupholdings.com/ke/',
      'info@equitybank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-limited/',
      '',
      'EQBLKENA',
      '',
    ),
    bank(
      'Co-operative Bank of Kenya',
      '+254 20 2776000',
      'Co-op House, Haile Selassie Avenue, Nairobi, Kenya',
      '',
      '',
      'https://www.co-opbank.co.ke/',
      'customerservice@co-opbank.co.ke',
      '',
      '',
      'https://www.linkedin.com/company/co-operative-bank-of-kenya/',
      '',
      'KCOOKENA',
      '',
    ),
  ],
  RW: [
    bank(
      'Bank of Kigali',
      '+250 788 143 000',
      'KN3 Ave, Kigali, Rwanda',
      '',
      '',
      'https://www.bk.rw/',
      'customerservice@bk.rw',
      '',
      '',
      'https://www.linkedin.com/company/bank-of-kigali/',
      '',
      'BKIGRWRW',
      '',
    ),
    bank(
      'I&M Bank Rwanda',
      '+250 252 575 000',
      'KN3 Ave, Kigali, Rwanda',
      '',
      '',
      'https://www.imbankrw.com/',
      'customercare@imbank.co.rw',
      '',
      '',
      'https://www.linkedin.com/company/i-m-bank-rwanda/',
      '',
      'IMRWRWRW',
      '',
    ),
    bank(
      'Ecobank Rwanda',
      '+250 252 550 678',
      'Avenue de la Paix, Kigali, Rwanda',
      'https://apps.apple.com/app/ecobank-mobile/id514891772',
      'https://play.google.com/store/apps/details?id=com.ecobank.mobileapp',
      'https://www.ecobank.com/rw',
      'contactcentre@ecobank.com',
      'https://x.com/EcobankGroup',
      'https://www.instagram.com/ecobankgroup/',
      'https://www.linkedin.com/company/ecobank-transnational-incorporated/',
      '',
      'ECOCRWRW',
      '',
    ),
  ],
  SO: [
    bank(
      'Salaam Somali Bank',
      '+252 61 700 0000',
      'KM4, Mogadishu, Somalia',
      '',
      '',
      'https://www.salaambank.so/',
      'info@salaambank.so',
      '',
      '',
      'https://www.linkedin.com/company/salaam-somali-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Premier Bank Somalia',
      '+252 61 222 1111',
      'Airport Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.premierbank.so/',
      'info@premierbank.so',
      '',
      '',
      'https://www.linkedin.com/company/premier-bank-somalia/',
      '',
      '',
      '',
    ),
    bank(
      'Dahabshiil Bank International',
      '+252 63 333 3000',
      'Maka Al Mukarama Road, Mogadishu, Somalia',
      '',
      '',
      'https://www.dahabshiilbank.com/',
      'info@dahabshiilbank.com',
      '',
      '',
      'https://www.linkedin.com/company/dahabshiil-bank-international/',
      '',
      '',
      '',
    ),
  ],
  SS: [
    bank(
      'Ivory Bank',
      '+211 92 210 0000',
      'Airport Road, Juba, South Sudan',
      '',
      '',
      'https://www.ivorybankss.com/',
      'info@ivorybankss.com',
      '',
      '',
      'https://www.linkedin.com/company/ivory-bank/',
      '',
      '',
      '',
    ),
    bank(
      'Equity Bank South Sudan',
      '+211 92 535 5555',
      'Customs Market, Juba, South Sudan',
      '',
      '',
      'https://equitygroupholdings.com/ss/',
      'info@equitybankss.com',
      '',
      '',
      'https://www.linkedin.com/company/equity-bank-limited/',
      '',
      '',
      '',
    ),
    bank(
      'Cooperative Bank of South Sudan',
      '+211 92 911 1111',
      'Nimule Street, Juba, South Sudan',
      '',
      '',
      'https://www.co-opbankss.com/',
      'info@co-opbankss.com',
      '',
      '',
      '',
      '',
      '',
      '',
    ),
  ],
  TZ: [
    bank(
      'NMB Bank Tanzania',
      '+255 22 232 2000',
      'NMB House, Ohio Street, Dar es Salaam, Tanzania',
      '',
      '',
      'https://www.nmbbank.co.tz/',
      'customercare@nmbbank.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/nmb-bank-plc/',
      '',
      'NMIBTZTZ',
      '',
    ),
    bank(
      'CRDB Bank',
      '+255 22 219 7700',
      'Azikiwe Street, Dar es Salaam, Tanzania',
      '',
      '',
      'https://www.crdbbank.co.tz/',
      'servicequality@crdbbank.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/crdb-bank-plc/',
      '',
      'CORUTZTZ',
      '',
    ),
    bank(
      'NBC Bank Tanzania',
      '+255 22 219 7000',
      'Sokoine Drive, Dar es Salaam, Tanzania',
      '',
      '',
      'https://nbc.co.tz/',
      'customercare@nbc.co.tz',
      '',
      '',
      'https://www.linkedin.com/company/nbc-bank-tanzania/',
      '',
      'NICATZTZ',
      '',
    ),
  ],
  UG: [
    bank(
      'Stanbic Bank Uganda',
      '+256 312 224 600',
      'Plot 17 Hannington Road, Kampala, Uganda',
      '',
      '',
      'https://www.stanbicbank.co.ug/',
      'customercare@stanbic.com',
      '',
      '',
      'https://www.linkedin.com/company/stanbic-bank-uganda/',
      '',
      'SBICUGKX',
      '',
    ),
    bank(
      'Centenary Bank',
      '+256 417 126 000',
      'Mapeera House, Kampala Road, Kampala, Uganda',
      '',
      '',
      'https://www.centenarybank.co.ug/',
      'customerservice@centenarybank.co.ug',
      '',
      '',
      'https://www.linkedin.com/company/centenary-bank-uganda/',
      '',
      'CERBUGKA',
      '',
    ),
    bank(
      'dfcu Bank',
      '+256 312 300 000',
      'Plot 26 Kyadondo Road, Kampala, Uganda',
      '',
      '',
      'https://www.dfcugroup.com/',
      'customercare@dfcugroup.com',
      '',
      '',
      'https://www.linkedin.com/company/dfcu-bank/',
      '',
      'DFCUUGKA',
      '',
    ),
  ],
}
