// RedStone Oracle for Bitcoin (BTC)
// Emerging Modular Oracle Network

export const redstoneOracle = {
  name: "RedStone Oracle",
  blockchain: "Bitcoin (BTC) via Layer 2",
  type: "Modular Oracle Network",
  description: "RedStone is an emerging oracle project that aggregates BTC price data and delivers it on Ethereum L2s, Solana, and other supported chains. Features a modular architecture allowing flexible data delivery methods. Provides low-latency, high-frequency price updates.",
  url: "https://redstone.finance/",
  docs: "https://docs.redstone.finance/",
  api: {
    jsClient: "https://github.com/redstone-finance/redstone-js",
    restApi: "https://api.redstone.finance/",
    npmPackage: "@redstone-finance/api",
    documentation: "https://docs.redstone.finance/docs/introduction",
    priceFeeds: "https://app.redstone.finance/#/app/tokens",
  },
  features: [
    "BTC price data aggregation",
    "Modular data delivery (push, pull, X-layer)",
    "Support for Ethereum L2s",
    "Sub-second price updates",
    "Low gas costs",
    "Multiple data sources",
    "TypeScript/JavaScript SDK",
    "REST API access",
    "Custom price feeds",
    "High-frequency data",
  ],
  useCases: [
    "DeFi protocols on EVM chains",
    "Bitcoin-backed derivatives",
    "Lending and borrowing platforms",
    "Cross-chain bridges",
    "Perpetual swaps",
    "Options trading",
    "Algorithmic trading",
    "Portfolio management",
  ],
  integrationMethod: "TypeScript SDK (@redstone-finance/api) / Smart Contract / REST API",
  dataFrequency: "Sub-second to seconds, configurable",
  pricing: "Free tier available for testing",
  coverage: "1000+ tokens including BTC and BTC pairs",
  deliveryModels: {
    push: "Traditional oracle model - data pushed on-chain",
    pull: "On-demand data fetching (gas-efficient)",
    xLayer: "Cross-layer data delivery for L2s",
  },
  layer2Support: {
    arbitrum: "Native support",
    optimism: "Native support",
    polygon: "Native support",
    avalanche: "Native support",
    stacks: "Planned future support",
  },
  socialMedia: {
    twitter: "https://twitter.com/redstone_defi",
    discord: "https://discord.gg/redstone",
    github: "https://github.com/redstone-finance",
    telegram: "https://t.me/redstonefinance",
    linkedin: "https://www.linkedin.com/company/redstone-finance/",
  },
  integrationNotes: "Use @redstone-finance/api for TypeScript integration: `const price = await getPrice('BTC');`. For smart contracts, use RedStone price feeds on supported EVM chains. Modular architecture allows choosing optimal data delivery method.",
  npmPackages: [
    "@redstone-finance/api",
    "@redstone-finance/evm-connector",
    "@redstone-finance/protocol",
  ],
  sampleCode: "const { getPrice } = require('@redstone-finance/api'); const btcPrice = await getPrice('BTC');",
  advantages: [
    "Modular and flexible",
    "Low latency",
    "Gas-efficient",
    "Multiple data sources",
    "Easy TypeScript integration",
    "Supports EVM L2s",
  ],
  comparison2025: {
    vsChainlink: "RedStone offers modular data delivery and potentially lower costs, but Chainlink has longer track record and broader adoption",
    vsPyth: "Both offer low-latency data; RedStone is more focused on EVM, Pyth has broader multi-chain support",
  },
};

