import type { CorporationFormationOffice } from './types'
import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per Commonwealth member state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const COMMONWEALTH_CORPORATION_FORMATION_OFFICES: Record<CommonwealthMemberIsoCode, CorporationFormationOffice> = {
  AG:   office(
    'Intellectual Property and Commerce Office (IPCO) Antigua and Barbuda',
    '+1 268 462 0007',
    'High Street, St John\'s, Antigua and Barbuda',
    'https://www.ipco.gov.ag',
    'ipco@gov.ag',
    '',
    '',
    '',
    'https://www.ipco.gov.ag',
    'https://www.ab.gov.ag/content/registering-business',
    'Company Registration Number',
  ),
  AU:   office(
    'Australian Securities and Investments Commission (ASIC)',
    '+61 1300 300 630',
    'Level 5, 100 Market Street, Sydney NSW 2000, Australia',
    'https://asic.gov.au',
    '',
    'https://twitter.com/asicmedia',
    '',
    'https://www.linkedin.com/company/australian-securities-and-investments-commission/',
    'https://asic.gov.au/for-business/registering-a-company/',
    'https://business.gov.au/planning/new-businesses/register-a-company',
    'Australian Company Number (ACN)',
  ),
  BS:   office(
    'Registrar General\'s Department Bahamas',
    '+1 242 322 3316',
    'Frederick Street, Nassau, Bahamas',
    'https://www.bahamas.gov.bs',
    'registrar@bahamas.gov.bs',
    '',
    '',
    '',
    'https://www.bahamas.gov.bs/wps/portal/public/gov/government-services',
    'https://www.bahamas.gov.bs/invest',
    'Company Registration Number',
  ),
  BD:   office(
    'Registrar of Joint Stock Companies and Firms (RJSC)',
    '+880 2 951 2778',
    'E-6/B, Agargaon Administrative Area, Dhaka, Bangladesh',
    'https://www.roc.gov.bd',
    'info@roc.gov.bd',
    '',
    '',
    '',
    'https://www.roc.gov.bd',
    'https://www.bida.gov.bd/invest-in-bangladesh/starting-business',
    'Company Registration Number',
  ),
  BB:   office(
    'Corporate Affairs and Intellectual Property Office (CAIPO) Barbados',
    '+1 246 535 5600',
    'Baobab Tower, Warrens, St Michael, Barbados',
    'https://www.caipo.gov.bb',
    'caipo@gov.bb',
    '',
    '',
    '',
    'https://www.caipo.gov.bb',
    'https://www.investbarbados.org/starting-a-business',
    'Company Registration Number',
  ),
  BZ:   office(
    'Companies and Corporate Affairs Registry Belize',
    '+501 822 0421',
    'Belmopan, Belize',
    'https://www.belize.gov.bz',
    'registry@belize.gov.bz',
    '',
    '',
    '',
    'https://www.belize.gov.bz',
    'https://www.belizeinvest.org.bz/starting-a-business',
    'Company Registration Number',
  ),
  BW:   office(
    'Companies and Intellectual Property Authority (CIPA)',
    '+267 367 3700',
    'Plot 50676, Fairgrounds Office Park, Gaborone, Botswana',
    'https://www.cipa.co.bw',
    'info@cipa.co.bw',
    'https://x.com/CIPA_Botswana',
    '',
    'https://www.linkedin.com/company/cipa-botswana/',
    'https://www.cipa.co.bw/register-a-company',
    'https://www.cipa.co.bw/company-registration-checklist',
    'Company Registration Number',
  ),
  BN:   office(
    'Registry of Companies and Business Names (ROCBN)',
    '+673 2383444',
    'Ministry of Finance and Economy, Bandar Seri Begawan, Brunei Darussalam',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    '',
    '',
    '',
    '',
    'https://www.ocp.mofe.gov.bn/SitePages/ROCBN%20Home.aspx',
    'https://business.gov.bn/SitePages/Starting%20a%20Business.aspx',
    'Business Registration Number',
  ),
  CM:   office(
    'Centre de Formalites de Creation d\'Entreprise (CFCE Cameroun)',
    '+237 233 42 59 59',
    'Immeuble MAGZI, Yaounde, Cameroon',
    'https://www.apme.cm',
    'cfce@apme.cm',
    '',
    '',
    'https://www.linkedin.com/company/apme-cameroun/',
    'https://www.apme.cm/cfce',
    'https://www.apme.cm/cfce/check-list',
    'Numero RCCM',
  ),
  CA:   office(
    'Corporations Canada (Innovation, Science and Economic Development)',
    '+1 866 333 5556',
    '235 Queen Street, Ottawa, ON K1A 0H5, Canada',
    'https://ised-isde.canada.ca/site/corporations-canada/en',
    '',
    '',
    '',
    '',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/incorporate-business-corporation',
    'https://ised-isde.canada.ca/site/corporations-canada/en/business-corporations/steps-incorporating',
    'Corporation Number',
  ),
  CY:   office(
    'Department of Registrar of Companies and Intellectual Property Cyprus',
    '+357 22 403 150',
    'Makarios III Avenue, Nicosia, Cyprus',
    'https://www.companies.gov.cy',
    'companies@companies.gov.cy',
    '',
    '',
    '',
    'https://www.companies.gov.cy',
    'https://www.companies.gov.cy/en/company-registration',
    'Registration Number (HE)',
  ),
  DM:   office(
    'Companies and Intellectual Property Office Dominica',
    '+1 767 266 3201',
    'Kennedy Avenue, Roseau, Dominica',
    'https://www.dominica.gov.dm',
    'cipo@gov.dm',
    '',
    '',
    '',
    'https://www.dominica.gov.dm',
    'https://investdominica.dm/starting-a-business',
    'Company Registration Number',
  ),
  SZ:   office(
    'Eswatini Companies Office (Ministry of Commerce, Industry and Trade)',
    '+268 2404 3200',
    'Lilunga House, Somhlolo Road, Mbabane, Eswatini',
    'https://www.gov.sz/index.php/business/companies-office',
    'companiesoffice@gov.sz',
    '',
    '',
    '',
    'https://www.gov.sz/index.php/business/companies-office',
    'https://www.gov.sz/index.php/business/forms',
    'Company Registration Number',
  ),
  FJ:   office(
    'Registrar of Companies Fiji',
    '+679 330 6166',
    'Level 5, FNPF Place, Suva, Fiji',
    'https://www.companies.gov.fj',
    'companies@companies.gov.fj',
    '',
    '',
    '',
    'https://www.companies.gov.fj',
    'https://www.investmentfiji.org.fj/starting-a-business',
    'Company Registration Number',
  ),
  GA:   office(
    'Agence Nationale de Promotion des Investissements du Gabon (ANPI-Gabon)',
    '+241 01 79 20 00',
    'Immeuble Arambo, Libreville, Gabon',
    'https://www.investingabon.ga',
    'contact@investingabon.ga',
    '',
    '',
    'https://www.linkedin.com/company/anpi-gabon/',
    'https://www.investingabon.ga/creer-mon-entreprise',
    'https://www.investingabon.ga/guide-createur',
    'Numero RCCM',
  ),
  GM:   office(
    'Ministry of Justice The Gambia - Registrar of Companies',
    '+220 422 5308',
    'Marina Parade, Banjul, The Gambia',
    'https://www.moj.gov.gm',
    'info@moj.gov.gm',
    '',
    '',
    '',
    'https://www.moj.gov.gm/registrar-general',
    '',
    'Company Registration Number',
  ),
  GH:   office(
    'Registrar-General\'s Department (RGD Ghana)',
    '+233 30 266 1081',
    'Ministries, Accra, Ghana',
    'https://rgd.gov.gh',
    'info@rgd.gov.gh',
    'https://x.com/ORC_ghana',
    '',
    'https://www.linkedin.com/company/office-of-the-registrar-of-companies-ghana/',
    'https://egovonline.gegov.gov.gh/RGDPortalWeb/portal/RGDHome',
    'https://rgd.gov.gh/services/business-registration/',
    'Company Registration Number',
  ),
  GD:   office(
    'Corporate Affairs and Intellectual Property Office Grenada',
    '+1 473 440 2939',
    'Frederick Street, St George\'s, Grenada',
    'https://www.gov.gd',
    'caipo@gov.gd',
    '',
    '',
    '',
    'https://www.gov.gd',
    'https://grenadagrenadines.com/invest/starting-a-business',
    'Company Registration Number',
  ),
  GY:   office(
    'Deeds and Commercial Registry Guyana',
    '+592 225 0555',
    'Avenue of the Republic, Georgetown, Guyana',
    'https://www.deeds.gov.gy',
    'deedsregistry@gov.gy',
    '',
    '',
    '',
    'https://www.deeds.gov.gy',
    'https://goinvest.gov.gy/starting-a-business',
    'Company Registration Number',
  ),
  IN:   office(
    'Ministry of Corporate Affairs India (MCA21)',
    '+91 11 2306 3386',
    '5th Floor, A Wing, Shastri Bhawan, New Delhi, India',
    'https://www.mca.gov.in',
    'helpdesk@mca.gov.in',
    '',
    '',
    '',
    'https://www.mca.gov.in/content/mca/global/en/mca/e-filing-services.html',
    'https://www.mca.gov.in/content/mca/global/en/acts-rules/ebooks/company-incorporation.html',
    'Corporate Identification Number (CIN)',
  ),
  JM:   office(
    'Companies Office of Jamaica',
    '+1 876 908 4419',
    '1 Grenada Way, Kingston, Jamaica',
    'https://www.orcjamaica.gov.jm',
    'info@orcjamaica.gov.jm',
    '',
    '',
    '',
    'https://www.orcjamaica.gov.jm',
    'https://www.jamaicatradeandinvest.org/starting-a-business',
    'Company Registration Number',
  ),
  KE:   office(
    'Business Registration Service (BRS Kenya)',
    '+254 20 222 7461',
    'Sheria House, Harambee Avenue, Nairobi, Kenya',
    'https://brs.go.ke',
    'info@brs.go.ke',
    'https://x.com/BRS_Kenya',
    '',
    'https://www.linkedin.com/company/business-registration-service-kenya/',
    'https://brs.go.ke/service/company-registration',
    'https://www.ecitizen.go.ke',
    'Certificate of Incorporation Number',
  ),
  KI:   office(
    'Ministry of Commerce, Industry and Cooperatives Kiribati',
    '+686 750 26000',
    'Betio, Tarawa, Kiribati',
    'https://www.mfep.gov.ki',
    'commerce@mfep.gov.ki',
    '',
    '',
    '',
    'https://www.mfep.gov.ki',
    'https://www.mfep.gov.ki/commerce',
    'Business License Number',
  ),
  LS:   office(
    'One Stop Business Facilitation Centre (OBFC Lesotho)',
    '+266 22 312 100',
    'Bedco House, Kingsway Road, Maseru, Lesotho',
    'https://www.obfc.org.ls',
    'info@obfc.org.ls',
    '',
    '',
    '',
    'https://www.obfc.org.ls/company-registration',
    'https://www.obfc.org.ls/checklists',
    'Company Registration Number',
  ),
  MW:   office(
    'Registrar General Department Malawi',
    '+265 1 770 155',
    'Glyn Jones Road, Ginnery Corner, Blantyre, Malawi',
    'https://www.registrargeneral.gov.mw',
    'registrargeneral@justice.gov.mw',
    '',
    '',
    '',
    'https://www.registrargeneral.gov.mw/company-registration',
    'https://www.registrargeneral.gov.mw/forms-and-fees',
    'Certificate of Incorporation Number',
  ),
  MY:   office(
    'Companies Commission of Malaysia (SSM)',
    '+60 3 7721 4000',
    'Menara SSM@Sentral, No. 7 Jalan Stesen Sentral 5, Kuala Lumpur, Malaysia',
    'https://www.ssm.com.my',
    'enquiry@ssm.com.my',
    '',
    '',
    '',
    'https://ezbiz.ssm.com.my',
    'https://www.ssm.com.my/Pages/Legal_Framework/Company/Guidelines.aspx',
    'Company Number',
  ),
  MV:   office(
    'Ministry of Economic Development and Trade Maldives (Business Center)',
    '+960 334 3101',
    'Male, Maldives',
    'https://www.trade.gov.mv',
    'info@trade.gov.mv',
    '',
    '',
    '',
    'https://www.trade.gov.mv',
    'https://www.investmaldives.org/starting-a-business',
    'Business Registration Number',
  ),
  MT:   office(
    'Malta Business Registry',
    '+356 2342 0000',
    'Notabile Road, Attard, Malta',
    'https://mbr.mt',
    'mbr@mbr.mt',
    '',
    '',
    '',
    'https://mbr.mt',
    'https://mbr.mt/registration-of-companies',
    'Company Registration Number',
  ),
  MU:   office(
    'Corporate and Business Registration Department (CBRD Mauritius)',
    '+230 202 0600',
    '7th Floor, SICOM Tower, Wall Street, Ebene, Mauritius',
    'https://companies.govmu.org',
    'companies.registry@govmu.org',
    '',
    '',
    '',
    'https://companies.govmu.org/Pages/Corporate%20and%20Business/Company-Registration.aspx',
    'https://companies.govmu.org/Pages/Guidelines.aspx',
    'Business Registration Number (BRN)',
  ),
  MZ:   office(
    'Conservatoria do Registo das Entidades Legais (CREL Mozambique)',
    '+258 21 327 800',
    'Av. Vladimir Lenine 265, Maputo, Mozambique',
    'https://www.mjcr.gov.mz',
    'atendimento@mjcr.gov.mz',
    '',
    '',
    '',
    'https://www.mjcr.gov.mz/servicos/registo-comercial',
    'https://www.mjcr.gov.mz/servicos/requisitos',
    'Numero de Registo Comercial (NUEL)',
  ),
  NA:   office(
    'Business and Intellectual Property Authority (BIPA Namibia)',
    '+264 61 299 4400',
    '55 Robert Mugabe Avenue, Windhoek, Namibia',
    'https://www.bipa.na',
    'info@bipa.na',
    'https://x.com/BIPA_NA',
    '',
    'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
    'https://www.bipa.na/company-registration',
    'https://www.bipa.na/checklists-and-forms',
    'Company Registration Number',
  ),
  NR:   office(
    'Department of Justice and Border Control Nauru',
    '+674 557 3133',
    'Yaren, Nauru',
    'https://www.nauru.gov.nr',
    'registry@nauru.gov.nr',
    '',
    '',
    '',
    'https://www.nauru.gov.nr',
    'https://www.nauru.gov.nr/government/departments',
    'Business Registration Number',
  ),
  NZ:   office(
    'New Zealand Companies Office',
    '+64 50 872 2669',
    'Wellington, New Zealand',
    'https://companies-register.companiesoffice.govt.nz',
    '',
    '',
    '',
    '',
    'https://companies-register.companiesoffice.govt.nz/help-centre/starting-a-company',
    'https://www.business.govt.nz/getting-started/advice-for-start-ups/10-step-guide-to-starting-a-business/',
    'New Zealand Business Number (NZBN)',
  ),
  NG:   office(
    'Corporate Affairs Commission (CAC Nigeria)',
    '+234 700 022 2255',
    'Plot 420, Tigris Crescent, Maitama, Abuja, Nigeria',
    'https://www.cac.gov.ng',
    'enquiries@cac.gov.ng',
    'https://x.com/cacnigeria1',
    'https://www.instagram.com/cacnigeria/',
    'https://www.linkedin.com/company/corporate-affairs-commission-nigeria/',
    'https://pre.cac.gov.ng/register',
    'https://www.cac.gov.ng/resources',
    'Registration Number (RC Number)',
  ),
  PK:   office(
    'Securities and Exchange Commission of Pakistan (SECP)',
    '+92 51 920 7091',
    'NIC Building, 63 Jinnah Avenue, Islamabad, Pakistan',
    'https://www.secp.gov.pk',
    'helpdesk@secp.gov.pk',
    '',
    '',
    '',
    'https://eservices.secp.gov.pk',
    'https://www.secp.gov.pk/company-formation',
    'National Tax Number (NTN)',
  ),
  PG:   office(
    'Investment Promotion Authority (IPA) Papua New Guinea',
    '+675 321 7311',
    'Malaoro Street, Port Moresby, Papua New Guinea',
    'https://www.ipa.gov.pg',
    '',
    '',
    '',
    '',
    'https://www.ipa.gov.pg/online-services',
    'https://www.ipa.gov.pg/business-registration',
    'Company Number',
  ),
  RW:   office(
    'Rwanda Development Board (RDB) - Business Registration',
    '+250 252 587 441',
    'KG 9 Avenue, Nyarutarama, Kigali, Rwanda',
    'https://rdb.rw',
    'info@rdb.rw',
    'https://x.com/RDBrwanda',
    'https://www.instagram.com/visitrwanda_now/',
    'https://www.linkedin.com/company/rwanda-development-board/',
    'https://org.rdb.rw',
    'https://rdb.rw/business/business-registration/',
    'Company Registration Number',
  ),
  KN:   office(
    'Financial Services Regulatory Commission St Kitts and Nevis',
    '+1 869 465 2539',
    'Basseterre, St Kitts and Nevis',
    'https://www.fsrc.kn',
    'info@fsrc.kn',
    '',
    '',
    '',
    'https://www.fsrc.kn',
    'https://www.investstkitts.kn/starting-a-business',
    'Company Registration Number',
  ),
  LC:   office(
    'Registry of Companies Saint Lucia',
    '+1 758 468 5500',
    'Castries, Saint Lucia',
    'https://www.govt.lc',
    'registry@govt.lc',
    '',
    '',
    '',
    'https://www.govt.lc',
    'https://www.investstlucia.com/starting-a-business',
    'Company Registration Number',
  ),
  VC:   office(
    'Commerce and Intellectual Property Office Saint Vincent and the Grenadines',
    '+1 784 457 1107',
    'Kingstown, Saint Vincent and the Grenadines',
    'https://www.gov.vc',
    'cipo@gov.vc',
    '',
    '',
    '',
    'https://www.gov.vc',
    'https://www.investsvg.com/starting-a-business',
    'Company Registration Number',
  ),
  WS:   office(
    'Ministry of Commerce, Industry and Labour Samoa',
    '+685 20471',
    'Apia, Samoa',
    'https://www.mcil.gov.ws',
    'registry@mcil.gov.ws',
    '',
    '',
    '',
    'https://www.mcil.gov.ws',
    'https://www.mcil.gov.ws/business-registration',
    'Company Registration Number',
  ),
  SC:   office(
    'Seychelles Revenue Commission - Registrar General Division',
    '+248 4 282 800',
    'Maison Collet, Francis Rachel Street, Victoria, Seychelles',
    'https://www.src.gov.sc',
    'registrargeneral@src.gov.sc',
    '',
    '',
    '',
    'https://www.src.gov.sc/services/business-registration',
    'https://www.src.gov.sc/checklists-and-forms',
    'Company Registration Number',
  ),
  SL:   office(
    'Office of the Administrator and Registrar General (OARG Sierra Leone)',
    '+232 79 990 739',
    'Roxy Building, Walpole Street, Freetown, Sierra Leone',
    'https://oarg.gov.sl',
    'info@oarg.gov.sl',
    'https://x.com/OargSierraLeone',
    '',
    'https://www.linkedin.com/company/oarg-sl/',
    'https://oarg.gov.sl/business-registration',
    'https://oarg.gov.sl/requirements',
    'Company Registration Number',
  ),
  SG:   office(
    'Accounting and Corporate Regulatory Authority (ACRA)',
    '+65 6248 6028',
    '10 Anson Road, International Plaza, Singapore',
    'https://www.acra.gov.sg',
    '',
    '',
    '',
    'https://www.linkedin.com/company/accounting-and-corporate-regulatory-authority-acra-/',
    'https://www.bizfile.gov.sg',
    'https://www.acra.gov.sg/how-to-guides/before-you-start/incorporation',
    'Unique Entity Number (UEN)',
  ),
  SB:   office(
    'Business Registry Unit Solomon Islands',
    '+677 22556',
    'Honiara, Solomon Islands',
    'https://www.commerce.gov.sb',
    'registry@commerce.gov.sb',
    '',
    '',
    '',
    'https://www.commerce.gov.sb',
    'https://www.commerce.gov.sb/business-registration',
    'Company Registration Number',
  ),
  ZA:   office(
    'Companies and Intellectual Property Commission (CIPC South Africa)',
    '+27 86 100 2472',
    'the dti Campus, 77 Meintjies Street, Sunnyside, Pretoria, South Africa',
    'https://www.cipc.co.za',
    'info@cipc.co.za',
    'https://x.com/theCIPC',
    '',
    'https://www.linkedin.com/company/cipc/',
    'https://www.cipc.co.za/?page_id=3781',
    'https://www.cipc.co.za/?page_id=3791',
    'Enterprise Number',
  ),
  LK:   office(
    'Registrar of Companies Sri Lanka',
    '+94 11 268 9210',
    'Level 12, West Tower, World Trade Center, Colombo, Sri Lanka',
    'https://www.drc.gov.lk',
    'info@drc.gov.lk',
    '',
    '',
    '',
    'https://www.drc.gov.lk',
    'https://www.drc.gov.lk/registration-of-companies',
    'Company Registration Number',
  ),
  TZ:   office(
    'Business Registrations and Licensing Agency (BRELA Tanzania)',
    '+255 22 221 0113',
    'BRELA House, Shaaban Robert Street, Dar es Salaam, Tanzania',
    'https://www.brela.go.tz',
    'info@brela.go.tz',
    'https://x.com/BrelaTanzania',
    '',
    'https://www.linkedin.com/company/brela/',
    'https://ors.brela.go.tz',
    'https://www.brela.go.tz/index.php/business-registration',
    'Company Registration Number',
  ),
  TG:   office(
    'Centre de Formalites des Entreprises (CFE Togo)',
    '+228 22 53 47 47',
    'Chaine du Port, Lome, Togo',
    'https://cfe.tg',
    'info@cfe.tg',
    '',
    '',
    'https://www.linkedin.com/company/cfetogo/',
    'https://cfe.tg/creation-dentreprise',
    'https://cfe.tg/pieces-a-fournir',
    'Numero RCCM',
  ),
  TO:   office(
    'Ministry of Commerce and Consumer Affairs Tonga',
    '+676 23 611',
    'Nuku\'alofa, Tonga',
    'https://www.commerce.gov.to',
    'commerce@commerce.gov.to',
    '',
    '',
    '',
    'https://www.commerce.gov.to',
    'https://www.commerce.gov.to/business-registration',
    'Business Registration Number',
  ),
  TT:   office(
    'Companies Registry Trinidad and Tobago',
    '+1 868 624 1462',
    'Corner of Richmond and Duke Streets, Port of Spain, Trinidad and Tobago',
    'https://www.legalaffairs.gov.tt',
    'registry@legalaffairs.gov.tt',
    '',
    '',
    '',
    'https://www.legalaffairs.gov.tt',
    'https://www.investt.co.tt/starting-a-business',
    'Company Registration Number',
  ),
  TV:   office(
    'Ministry of Finance Tuvalu (Business Registry)',
    '+688 20801',
    'Funafuti, Tuvalu',
    'https://www.tuvalu.tv',
    'finance@gov.tv',
    '',
    '',
    '',
    'https://www.tuvalu.tv',
    'https://www.tuvalu.tv/government',
    'Business Registration Number',
  ),
  UG:   office(
    'Uganda Registration Services Bureau (URSB)',
    '+256 414 233 219',
    'Plot 5 George Street, Georgian House, Kampala, Uganda',
    'https://www.ursb.go.ug',
    'registration@ursb.go.ug',
    'https://x.com/URSBHQ',
    '',
    'https://www.linkedin.com/company/uganda-registration-services-bureau/',
    'https://ursb.go.ug/business-registration/',
    'https://ursb.go.ug/forms-and-fees/',
    'Registration Number',
  ),
  GB:   office(
    'Companies House United Kingdom',
    '+44 303 1234 500',
    'Crown Way, Cardiff CF14 3UZ, United Kingdom',
    'https://www.gov.uk/government/organisations/companies-house',
    'enquiries@companieshouse.gov.uk',
    'https://twitter.com/CompaniesHouse',
    '',
    'https://www.linkedin.com/company/companies-house/',
    'https://www.gov.uk/limited-company-formation',
    'https://www.gov.uk/set-up-limited-company',
    'Company Registration Number (CRN)',
  ),
  VU:   office(
    'Vanuatu Financial Services Commission',
    '+678 22666',
    'Port Vila, Vanuatu',
    'https://www.vfsc.vu',
    'info@vfsc.vu',
    '',
    '',
    '',
    'https://www.vfsc.vu',
    'https://www.vfsc.vu/company-registration',
    'Company Registration Number',
  ),
  ZM:   office(
    'Patents and Companies Registration Agency (PACRA Zambia)',
    '+260 211 255 127',
    'PACRA Building, Haile Selassie Avenue, Lusaka, Zambia',
    'https://www.pacra.org.zm',
    'info@pacra.org.zm',
    'https://x.com/PacraZm',
    '',
    'https://www.linkedin.com/company/pacra-zambia/',
    'https://portal.pacra.org.zm',
    'https://www.pacra.org.zm/checklists',
    'Company Registration Number',
  ),
}
