import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per Commonwealth member state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const COMMONWEALTH_DOMESTIC_POST_SERVICES: Record<CommonwealthMemberIsoCode, DomesticPostService> = {
  AG: post(
    'Antigua and Barbuda Postal Service',
    'https://www.abpost.gov.ag/',
    'info@abpost.gov.ag',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island and locality addressing',
  ),
  AU: post(
    'Australia Post',
    'https://auspost.com.au/',
    'feedback@auspost.com.au',
    'https://x.com/AusPost',
    'https://www.instagram.com/auspost/',
    'https://www.linkedin.com/company/australia-post/',
    'https://developers.auspost.com.au/',
    'NNNN',
    '^\\d{4}$',
    '2000',
    'Four-digit postcode',
  ),
  BS: post(
    'Bahamas Postal Service',
    'https://www.bahamas.gov.bs/bps',
    'info@bps.gov.bs',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  BD: post(
    'Bangladesh Post Office',
    'https://bdpost.gov.bd/',
    'info@bdpost.gov.bd',
    'https://x.com/BangladeshPost',
    '',
    'https://www.linkedin.com/company/bangladesh-post-office/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1000',
    'Four-digit postcode',
  ),
  BB: post(
    'Barbados Postal Service',
    'https://www.bps.gov.bb/',
    'info@bps.gov.bb',
    '',
    '',
    '',
    '',
    'BBNNNNN',
    '^BB\\d{5}$',
    'BB11000',
    'BB + five digits (Barbados)',
  ),
  BZ: post(
    'Belize Postal Service',
    'https://www.belizepost.bz/',
    'info@belizepost.bz',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing',
  ),
  BW: post(
    'BotswanaPost',
    'https://www.botspost.co.bw/',
    'customercare@botspost.co.bw',
    'https://x.com/BotswanaPost',
    'https://www.instagram.com/botswanapost/',
    'https://www.linkedin.com/company/botswanapost/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00000',
    'Five-digit national postcode (verify district mapping locally)',
  ),
  BN: post(
    'Postal Services Department (Brunei)',
    'https://www.post.gov.bn/',
    'postmaster@post.gov.bn',
    '',
    '',
    'https://www.linkedin.com/company/postal-services-department-brunei/',
    '',
    'AANNNN',
    '^[A-Z]{2}\\d{4}$',
    'BA2110',
    'Two-letter area + four digits (Brunei Darussalam)',
  ),
  CM: post(
    'CAMPOST',
    'http://campost.cm/',
    'info@campost.cm',
    '',
    '',
    'https://www.linkedin.com/company/campost/',
    '',
    'none',
    '',
    '',
    'No national postcode; regional and P.O. Box routing',
  ),
  CA: post(
    'Canada Post',
    'https://www.canadapost-postescanada.ca/',
    'customercare@canadapost-postescanada.ca',
    'https://x.com/canadapostcorp',
    'https://www.instagram.com/canadapost/',
    'https://www.linkedin.com/company/canada-post/',
    'https://www.canadapost-postescanada.ca/cpc/en/tools/find-a-postal-code.page',
    'ANA NAN',
    '^[A-Z]\\d[A-Z] \\d[A-Z]\\d$',
    'K1A 0B1',
    'Canadian postal code (letter-digit-letter space digit-letter-digit)',
  ),
  CY: post(
    'Cyprus Post',
    'https://www.cypruspost.post/',
    'info@cypruspost.post',
    'https://x.com/CyprusPost',
    '',
    'https://www.linkedin.com/company/cyprus-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '1010',
    'Four-digit postcode',
  ),
  DM: post(
    'Dominica Postal Service',
    'https://www.dominicapost.dm/',
    'info@dominicapost.dm',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  SZ: post(
    'Eswatini Posts & Telecommunications Corporation',
    'https://www.eswatinipost.co.sz/',
    'info@post.co.sz',
    '',
    '',
    'https://www.linkedin.com/company/eswatini-posts-telecommunications/',
    '',
    'ANNN',
    '^[A-Z]\\\\d{3}$',
    'H100',
    'Letter + three digits (H = Hhohho region prefix)',
  ),
  FJ: post(
    'Fiji Post',
    'https://www.fijipost.com.fj/',
    'info@fijipost.com.fj',
    'https://x.com/FijiPost',
    '',
    'https://www.linkedin.com/company/fiji-post/',
    '',
    'none',
    '',
    '',
    'No national postcode; town and island addressing',
  ),
  GA: post(
    'Gabon Poste EMS',
    'https://www.gabonpost.ga/',
    'infos@gpost.ga',
    '',
    '',
    'https://www.linkedin.com/company/gabon-poste/',
    '',
    'none',
    '',
    '',
    'No national postcode; Libreville/Port-Gentil district addressing',
  ),
  GM: post(
    'GamPost',
    'https://gampost.gm/',
    'info@gampost.gm',
    '',
    '',
    'https://www.linkedin.com/company/gampost/',
    '',
    'none',
    '',
    '',
    'No national postcode; settlement and P.O. Box',
  ),
  GH: post(
    'Ghana Post',
    'http://ghanapost.com.gh/',
    'info@ghanapost.com.gh',
    'https://x.com/ghanapostgh',
    'https://www.instagram.com/ghanapostgh/',
    'https://www.linkedin.com/company/ghana-post/',
    '',
    'none',
    '',
    '',
    'GhanaPostGPS digital address parallel to legacy P.O. Box; no legacy numeric postcode',
  ),
  GD: post(
    'Grenada Postal Corporation',
    'https://www.grenadapost.gd/',
    'info@grenadapost.gd',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  GY: post(
    'Guyana Post Office Corporation',
    'https://www.guyanapost.gy/',
    'info@guyanapost.gy',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; locality addressing',
  ),
  IN: post(
    'India Post',
    'https://www.indiapost.gov.in/',
    'helpdesk@indiapost.gov.in',
    'https://x.com/IndiaPostOffice',
    'https://www.instagram.com/indiapostoffice/',
    'https://www.linkedin.com/company/india-post/',
    'https://www.indiapost.gov.in/',
    'NNNNNN',
    '^\\d{6}$',
    '110001',
    'Six-digit PIN code',
  ),
  JM: post(
    'Jamaica Post',
    'https://www.jamaicapost.gov.jm/',
    'info@jamaicapost.gov.jm',
    'https://x.com/JamaicaPost',
    '',
    'https://www.linkedin.com/company/jamaica-post/',
    '',
    'none',
    '',
    '',
    'No national postcode; parish and locality addressing',
  ),
  KE: post(
    'Postal Corporation of Kenya',
    'http://posta.co.ke/',
    'customercare@posta.co.ke',
    'https://x.com/postakenya',
    'https://www.instagram.com/postakenya/',
    'https://www.linkedin.com/company/postal-corporation-of-kenya/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '00100',
    'Five-digit postcode; P.O. Box culture remains common',
  ),
  KI: post(
    'Kiribati Post',
    'https://www.kiribatipost.ki/',
    'info@kiribatipost.ki',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  LS: post(
    'Lesotho Postal Services',
    'https://lesothopost.org.ls/',
    'info@post.org.ls',
    '',
    '',
    'https://www.linkedin.com/company/lesotho-postal-services/',
    '',
    'NNN',
    '^\\\\d{3}$',
    '100',
    'Three-digit postcode',
  ),
  MW: post(
    'Malawi Posts Corporation',
    'https://malawipost.gov.mw/',
    'info@malawipost.gov.mw',
    '',
    '',
    'https://www.linkedin.com/company/malawi-posts-corporation/',
    '',
    'none',
    '',
    '',
    'No national postcode; district and P.O. Box',
  ),
  MY: post(
    'Pos Malaysia',
    'https://www.pos.com.my/',
    'customercare@pos.com.my',
    'https://x.com/posmalaysia',
    'https://www.instagram.com/posmalaysia/',
    'https://www.linkedin.com/company/pos-malaysia/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '50000',
    'Five-digit postcode',
  ),
  MV: post(
    'Maldives Post',
    'https://www.maldivespost.com/',
    'info@maldivespost.com',
    'https://x.com/MaldivesPost',
    '',
    'https://www.linkedin.com/company/maldives-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '20026',
    'Five-digit postcode',
  ),
  MT: post(
    'MaltaPost',
    'https://www.maltapost.com/',
    'info@maltapost.com',
    'https://x.com/MaltaPost',
    'https://www.instagram.com/maltapost/',
    'https://www.linkedin.com/company/maltapost/',
    '',
    'AAA NNNN',
    '^[A-Z]{3} \\d{4}$',
    'VLT 1117',
    'Three letters + space + four digits',
  ),
  MU: post(
    'Mauritius Post Ltd',
    'https://www.mauritiuspost.mu/',
    'info@mpl.mu',
    '',
    '',
    'https://www.linkedin.com/company/mauritius-post-ltd/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '42602',
    'Five-digit postcode (optional letter suffix in some datasets)',
  ),
  MZ: post(
    'Correios de Moçambique',
    'http://correios.co.mz/',
    'cac@correios.co.mz',
    '',
    '',
    'https://www.linkedin.com/company/correios-de-mocambique/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '1100',
    'Four-digit postcode',
  ),
  NA: post(
    'NamPost',
    'https://nampost.na/',
    'customerservice@namibiapost.na',
    '',
    '',
    'https://www.linkedin.com/company/nampost/',
    '',
    'none',
    '',
    '',
    'Private bag / P.O. Box numbering; no universal street postcode',
  ),
  NR: post(
    'Nauru Post',
    'https://www.naurupost.nr/',
    'info@naurupost.nr',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; district addressing',
  ),
  NZ: post(
    'NZ Post',
    'https://www.nzpost.co.nz/',
    'customercare@nzpost.co.nz',
    'https://x.com/NZPost',
    'https://www.instagram.com/nzpost/',
    'https://www.linkedin.com/company/nz-post/',
    '',
    'NNNN',
    '^\\d{4}$',
    '6011',
    'Four-digit postcode',
  ),
  NG: post(
    'Nigeria Postal Service (NIPOST)',
    'http://nipost.gov.ng/',
    'info@nipost.gov.ng',
    'https://x.com/e_nipost',
    'https://www.instagram.com/e_nipost/',
    'https://www.linkedin.com/company/nipost/',
    '',
    'NNNNNN',
    '^\\\\d{6}$',
    '100001',
    'Six-digit postcode (state + LGA + delivery)',
  ),
  PK: post(
    'Pakistan Post',
    'https://www.pakpost.gov.pk/',
    'info@pakpost.gov.pk',
    'https://x.com/PakistanPost',
    '',
    'https://www.linkedin.com/company/pakistan-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '44000',
    'Five-digit postcode',
  ),
  PG: post(
    'Post PNG',
    'https://www.postpng.com.pg/',
    'info@postpng.com.pg',
    '',
    '',
    'https://www.linkedin.com/company/post-png/',
    '',
    'NNN',
    '^\\d{3}$',
    '111',
    'Three-digit postcode',
  ),
  RW: post(
    'Rwanda Post (Iposita)',
    'https://i-posita.rw/',
    'info@ipostarltd.rw',
    'https://x.com/ipositaryw',
    'https://www.instagram.com/ipositaryw/',
    'https://www.linkedin.com/company/iposta-rwanda/',
    '',
    'none',
    '',
    '',
    'No legacy numeric postcode; Kigali addressing reforms — verify locally',
  ),
  KN: post(
    'St Kitts and Nevis Postal Service',
    'https://www.sknpost.gov.kn/',
    'info@sknpost.gov.kn',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  LC: post(
    'Saint Lucia Postal Service',
    'https://www.stluciapost.gov.lc/',
    'info@stluciapost.gov.lc',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  VC: post(
    'SVG Post (Saint Vincent and the Grenadines)',
    'https://www.svgpost.gov.vc/',
    'info@svgpost.gov.vc',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; parish addressing',
  ),
  WS: post(
    'Samoa Post',
    'https://www.samoapost.ws/',
    'info@samoapost.ws',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; village addressing',
  ),
  SC: post(
    'Seychelles Postal Services',
    'https://www.seychelles-post.com/',
    'info@sib.gov.sc',
    '',
    '',
    'https://www.linkedin.com/company/seychelles-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; island and district addressing',
  ),
  SL: post(
    'Salone Post EMS',
    'https://www.slpost.gov.sl/',
    'info@slipa.gov.sl',
    '',
    '',
    'https://www.linkedin.com/company/sierra-leone-postal-services/',
    '',
    'none',
    '',
    '',
    'No national postcode; Freetown district addressing',
  ),
  SG: post(
    'Singapore Post',
    'https://www.singpost.com/',
    'feedback@singpost.com',
    'https://x.com/SingPost',
    'https://www.instagram.com/singpost/',
    'https://www.linkedin.com/company/singapore-post-limited/',
    '',
    'NNNNNN',
    '^\\d{6}$',
    '018956',
    'Six-digit postcode',
  ),
  SB: post(
    'Solomon Post',
    'https://www.solomonpost.com.sb/',
    'info@solomonpost.com.sb',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  ZA: post(
    'South African Post Office',
    'http://www.postoffice.co.za/',
    'custserv@postoffice.co.za',
    'https://x.com/PostofficeSa',
    'https://www.instagram.com/sapostoffice/',
    'https://www.linkedin.com/company/south-african-post-office/',
    '',
    'NNNN',
    '^\\\\d{4}$',
    '2000',
    'Four-digit postcode (street delivery and P.O. Box)',
  ),
  LK: post(
    'Sri Lanka Post',
    'https://www.slpost.gov.lk/',
    'info@slpost.gov.lk',
    'https://x.com/SLPost',
    '',
    'https://www.linkedin.com/company/sri-lanka-post/',
    '',
    'NNNNN',
    '^\\d{5}$',
    '00100',
    'Five-digit postcode',
  ),
  TZ: post(
    'Tanzania Posts Corporation',
    'https://posta.co.tz/',
    'info@tpoc.co.tz',
    '',
    '',
    'https://www.linkedin.com/company/tanzania-posts-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '11101',
    'Five-digit postcode',
  ),
  TG: post(
    'La Poste du Togo',
    'https://www.laposte.tg/',
    'contact@laposte.tg',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-du-togo/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune addressing',
  ),
  TO: post(
    'Tonga Post',
    'https://www.tongapost.to/',
    'info@tongapost.to',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  TT: post(
    'TTPost (Trinidad and Tobago Postal Corporation)',
    'https://www.ttpost.net/',
    'info@ttpost.net',
    'https://x.com/TTPost',
    '',
    'https://www.linkedin.com/company/ttpost/',
    '',
    'none',
    '',
    '',
    'No national postcode; locality addressing',
  ),
  TV: post(
    'Tuvalu Post',
    'https://www.tuvalupost.tv/',
    'info@tuvalupost.tv',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  UG: post(
    'Uganda Post Limited',
    'https://www.eposta.ug/',
    'info@posta.co.ug',
    'https://x.com/ugposts',
    'https://www.instagram.com/ugposts/',
    'https://www.linkedin.com/company/uganda-post-limited/',
    '',
    'none',
    '',
    '',
    'P.O. Box dominant; no universal street postcode',
  ),
  GB: post(
    'Royal Mail',
    'https://www.royalmail.com/',
    'customerservice@royalmail.com',
    'https://x.com/RoyalMail',
    'https://www.instagram.com/royalmailofficial/',
    'https://www.linkedin.com/company/royal-mail/',
    'https://developer.royalmail.net/',
    'AAN NAA',
    '^[A-Z]{1,2}\\d[A-Z\\d]? \\d[A-Z]{2}$',
    'SW1A 1AA',
    'UK postcode (outward + inward codes)',
  ),
  VU: post(
    'Vanuatu Post',
    'https://www.vanuatupost.vu/',
    'info@vanuatupost.vu',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; island addressing',
  ),
  ZM: post(
    'Zambia Postal Services Corporation',
    'http://www.zampost.gov.zm/',
    'info.zampost@gmail.com',
    '',
    '',
    'https://www.linkedin.com/company/zambia-postal-services-corporation/',
    '',
    'NNNNN',
    '^\\\\d{5}$',
    '10101',
    'Five-digit postcode',
  ),
}
