import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'
import type {
  IntellectualPropertyDepartment,
  IntellectualPropertyDepartmentKind,
  IntellectualPropertyDepartmentsRoster,
} from './types'

function ip(
  kind: IntellectualPropertyDepartmentKind,
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): IntellectualPropertyDepartment {
  return { kind, name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

function roster(
  copyright: IntellectualPropertyDepartment,
  trademarks: IntellectualPropertyDepartment,
  patents: IntellectualPropertyDepartment,
): IntellectualPropertyDepartmentsRoster {
  return { copyright, trademarks, patents }
}

const OAPI_TRADEMARKS = ip(
  'trademarks',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

const OAPI_PATENTS = ip(
  'patents',
  'African Intellectual Property Organization (OAPI)',
  'https://www.oapi.int/en/',
  'oapi@oapi.int',
  '',
  'https://www.linkedin.com/company/oapi/',
  'https://www.oapi.int/en/e-services/',
)

function oapiMember(copyright: IntellectualPropertyDepartment): IntellectualPropertyDepartmentsRoster {
  return roster(copyright, OAPI_TRADEMARKS, OAPI_PATENTS)
}

/**
 * Intellectual property competent offices by ISO 3166-1 alpha-2 for Commonwealth of Nations
 * members in this module (informational; verify URLs, handles, forms portals, and API bases
 * before production use). Self-contained in this package — no imports from other alliance
 * modules. `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.wipo.int/en/web/country-profiles/directory-ip-offices
 */
export const COMMONWEALTH_INTELLECTUAL_PROPERTY_DEPARTMENTS: Record<
  CommonwealthMemberIsoCode,
  IntellectualPropertyDepartmentsRoster
> = {
  AG: roster(
    ip(
      'copyright',
      'Antigua and Barbuda Intellectual Property Office (Commerce Division) — copyright',
      'https://abip.gov.ag',
      '',
      '',
      '',
      'https://abip.gov.ag',
    ),
    ip(
      'trademarks',
      'Antigua and Barbuda Intellectual Property Office (Commerce Division)',
      'https://abip.gov.ag',
      '',
      '',
      '',
      'https://abip.gov.ag',
    ),
    ip(
      'patents',
      'Antigua and Barbuda Intellectual Property Office (Commerce Division)',
      'https://abip.gov.ag',
      '',
      '',
      '',
      'https://abip.gov.ag',
    ),
  ),
  AU: roster(
    ip(
      'copyright',
      'Australian Government — Attorney-General\'s Department (Copyright)',
      'https://www.ag.gov.au/rights-and-protections/copyright',
      '',
      '',
      '',
      'https://www.ag.gov.au/rights-and-protections/copyright',
    ),
    ip(
      'trademarks',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
    ip(
      'patents',
      'IP Australia',
      'https://www.ipaustralia.gov.au',
      'ipaustralia@ipaustralia.gov.au',
      'https://x.com/IPAustralia',
      'https://www.linkedin.com/company/ip-australia/',
      'https://www.ipaustralia.gov.au/apply-online',
    ),
  ),
  BS: roster(
    ip(
      'copyright',
      'Bahamas Copyright Royalty Tribunal (Ministry of Finance — copyright)',
      'https://www.bahamas.gov.bs',
      '',
      '',
      '',
      'https://www.bahamas.gov.bs',
    ),
    ip(
      'trademarks',
      'Department of the Registrar General — Intellectual Property (Bahamas)',
      'https://www.bahamas.gov.bs',
      '',
      '',
      '',
      'https://www.bahamas.gov.bs',
    ),
    ip(
      'patents',
      'Department of the Registrar General — Intellectual Property (Bahamas)',
      'https://www.bahamas.gov.bs',
      '',
      '',
      '',
      'https://www.bahamas.gov.bs',
    ),
  ),
  BD: roster(
    ip(
      'copyright',
      'Department of Patents, Designs and Trademarks (DPDT, Bangladesh) — copyright',
      'https://dpdt.gov.bd',
      'dpdt@dpdt.gov.bd',
      '',
      '',
      'https://dpdt.gov.bd',
    ),
    ip(
      'trademarks',
      'Department of Patents, Designs and Trademarks (DPDT, Bangladesh)',
      'https://dpdt.gov.bd',
      'dpdt@dpdt.gov.bd',
      '',
      '',
      'https://dpdt.gov.bd',
    ),
    ip(
      'patents',
      'Department of Patents, Designs and Trademarks (DPDT, Bangladesh)',
      'https://dpdt.gov.bd',
      'dpdt@dpdt.gov.bd',
      '',
      '',
      'https://dpdt.gov.bd',
    ),
  ),
  BB: roster(
    ip(
      'copyright',
      'Corporate Affairs and Intellectual Property Office (CAIPO, Barbados) — copyright',
      'https://www.caipo.gov.bb',
      'caipo@caipo.gov.bb',
      '',
      '',
      'https://www.caipo.gov.bb',
    ),
    ip(
      'trademarks',
      'Corporate Affairs and Intellectual Property Office (CAIPO, Barbados)',
      'https://www.caipo.gov.bb',
      'caipo@caipo.gov.bb',
      '',
      '',
      'https://www.caipo.gov.bb',
    ),
    ip(
      'patents',
      'Corporate Affairs and Intellectual Property Office (CAIPO, Barbados)',
      'https://www.caipo.gov.bb',
      'caipo@caipo.gov.bb',
      '',
      '',
      'https://www.caipo.gov.bb',
    ),
  ),
  BZ: roster(
    ip(
      'copyright',
      'Belize Intellectual Property Office (BelIPO) — copyright',
      'https://www.belipo.bz',
      '',
      '',
      '',
      'https://www.belipo.bz',
    ),
    ip(
      'trademarks',
      'Belize Intellectual Property Office (BelIPO)',
      'https://www.belipo.bz',
      '',
      '',
      '',
      'https://www.belipo.bz',
    ),
    ip(
      'patents',
      'Belize Intellectual Property Office (BelIPO)',
      'https://www.belipo.bz',
      '',
      '',
      '',
      'https://www.belipo.bz',
    ),
  ),
  BW: roster(
    ip(
      'copyright',
      'Copyright Society of Botswana (COSBOTS)',
      'https://www.cosbots.org.bw',
      'info@cosbots.org.bw',
      '',
      'https://www.linkedin.com/company/cosbots/',
      'https://www.cosbots.org.bw',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Authority (CIPA)',
      'https://www.cipa.co.bw',
      'info@cipa.co.bw',
      'https://x.com/CIPABotswana',
      'https://www.linkedin.com/company/cipa-botswana/',
      'https://www.cipa.co.bw',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Authority (CIPA)',
      'https://www.cipa.co.bw',
      'info@cipa.co.bw',
      'https://x.com/CIPABotswana',
      'https://www.linkedin.com/company/cipa-botswana/',
      'https://www.cipa.co.bw',
    ),
  ),
  BN: roster(
    ip(
      'copyright',
      'Brunei Darussalam Intellectual Property Office (BruIPO) — copyright',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'trademarks',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
    ip(
      'patents',
      'Brunei Darussalam Intellectual Property Office (BruIPO)',
      'https://www.bruipo.gov.bn',
      'bruipo@bruipo.gov.bn',
      '',
      '',
      'https://www.bruipo.gov.bn',
    ),
  ),
  CM: oapiMember(
    ip(
      'copyright',
      'Cameroon Copyright Office (Ministry of Arts and Culture)',
      'https://www.minac.gov.cm',
      '',
      '',
      '',
      'https://www.minac.gov.cm',
    ),
  ),
  CA: roster(
    ip(
      'copyright',
      'Canadian Intellectual Property Office (CIPO) — copyright',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'trademarks',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
    ip(
      'patents',
      'Canadian Intellectual Property Office (CIPO)',
      'https://ised-isde.canada.ca/cipo',
      'cipo-opic@canada.ca',
      'https://x.com/CIPOCanada',
      'https://www.linkedin.com/company/canadian-intellectual-property-office/',
      'https://ised-isde.canada.ca/cipo/en/learn-how-to/forms-and-fees.html',
    ),
  ),
  CY: roster(
    ip(
      'copyright',
      'Department of Registrar of Companies and Intellectual Property (Cyprus) — copyright',
      'https://www.intellectualproperty.gov.cy',
      'ipd@ipd.gov.cy',
      '',
      '',
      'https://www.intellectualproperty.gov.cy',
    ),
    ip(
      'trademarks',
      'Department of Registrar of Companies and Intellectual Property (Cyprus)',
      'https://www.intellectualproperty.gov.cy',
      'ipd@ipd.gov.cy',
      '',
      '',
      'https://www.intellectualproperty.gov.cy',
    ),
    ip(
      'patents',
      'Department of Registrar of Companies and Intellectual Property (Cyprus)',
      'https://www.intellectualproperty.gov.cy',
      'ipd@ipd.gov.cy',
      '',
      '',
      'https://www.intellectualproperty.gov.cy',
    ),
  ),
  DM: roster(
    ip(
      'copyright',
      'Commerce and Intellectual Property Office (Dominica) — copyright',
      'https://www.dominica.gov.dm',
      '',
      '',
      '',
      'https://www.dominica.gov.dm',
    ),
    ip(
      'trademarks',
      'Commerce and Intellectual Property Office (Dominica)',
      'https://www.dominica.gov.dm',
      '',
      '',
      '',
      'https://www.dominica.gov.dm',
    ),
    ip(
      'patents',
      'Commerce and Intellectual Property Office (Dominica)',
      'https://www.dominica.gov.dm',
      '',
      '',
      '',
      'https://www.dominica.gov.dm',
    ),
  ),
  SZ: roster(
    ip(
      'copyright',
      'Copyright Society of Eswatini (COSOES)',
      'https://www.cosoes.org.sz',
      '',
      '',
      '',
      'https://www.cosoes.org.sz',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Trade — Industrial Property',
      'https://www.gov.sz',
      '',
      '',
      '',
      'https://www.gov.sz',
    ),
  ),
  FJ: roster(
    ip(
      'copyright',
      'Office of the Registrar of Trademarks and Patents (Fiji) — copyright',
      'https://www.ipr.gov.fj',
      '',
      '',
      '',
      'https://www.ipr.gov.fj',
    ),
    ip(
      'trademarks',
      'Office of the Registrar of Trademarks and Patents (Fiji)',
      'https://www.ipr.gov.fj',
      '',
      '',
      '',
      'https://www.ipr.gov.fj',
    ),
    ip(
      'patents',
      'Office of the Registrar of Trademarks and Patents (Fiji)',
      'https://www.ipr.gov.fj',
      '',
      '',
      '',
      'https://www.ipr.gov.fj',
    ),
  ),
  GA: oapiMember(
    ip(
      'copyright',
      'Bureau Gabonais du Droit d\'Auteur (BGDA)',
      'https://www.bgda.ga',
      '',
      '',
      '',
      'https://www.bgda.ga',
    ),
  ),
  GM: roster(
    ip(
      'copyright',
      'National Centre for Arts and Culture (NCAC) — copyright',
      'https://www.ncac.gm',
      'info@ncac.gm',
      '',
      '',
      'https://www.ncac.gm',
    ),
    ip(
      'trademarks',
      'Registrar General\'s Department — Industrial Property (The Gambia)',
      'https://www.moj.gov.gm',
      '',
      '',
      '',
      'https://www.moj.gov.gm',
    ),
    ip(
      'patents',
      'Registrar General\'s Department — Industrial Property (The Gambia)',
      'https://www.moj.gov.gm',
      '',
      '',
      '',
      'https://www.moj.gov.gm',
    ),
  ),
  GH: roster(
    ip(
      'copyright',
      'Copyright Office, Registrar General\'s Department',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      '',
      'https://rgd.gov.gh',
    ),
    ip(
      'trademarks',
      'Registrar General\'s Department — Industrial Property',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      'https://www.linkedin.com/company/registrar-generals-department-ghana/',
      'https://rgd.gov.gh',
    ),
    ip(
      'patents',
      'Registrar General\'s Department — Industrial Property',
      'https://rgd.gov.gh',
      'info@rgd.gov.gh',
      '',
      'https://www.linkedin.com/company/registrar-generals-department-ghana/',
      'https://rgd.gov.gh',
    ),
  ),
  GD: roster(
    ip(
      'copyright',
      'Corporate Affairs and Intellectual Property Office (Grenada) — copyright',
      'https://www.gov.gd',
      '',
      '',
      '',
      'https://www.gov.gd',
    ),
    ip(
      'trademarks',
      'Corporate Affairs and Intellectual Property Office (Grenada)',
      'https://www.gov.gd',
      '',
      '',
      '',
      'https://www.gov.gd',
    ),
    ip(
      'patents',
      'Corporate Affairs and Intellectual Property Office (Grenada)',
      'https://www.gov.gd',
      '',
      '',
      '',
      'https://www.gov.gd',
    ),
  ),
  GY: roster(
    ip(
      'copyright',
      'Deeds and Commercial Registries Authority (Guyana) — intellectual property — copyright',
      'https://dcra.gov.gy',
      '',
      '',
      '',
      'https://dcra.gov.gy',
    ),
    ip(
      'trademarks',
      'Deeds and Commercial Registries Authority (Guyana) — intellectual property',
      'https://dcra.gov.gy',
      '',
      '',
      '',
      'https://dcra.gov.gy',
    ),
    ip(
      'patents',
      'Deeds and Commercial Registries Authority (Guyana) — intellectual property',
      'https://dcra.gov.gy',
      '',
      '',
      '',
      'https://dcra.gov.gy',
    ),
  ),
  IN: roster(
    ip(
      'copyright',
      'Copyright Office of India',
      'https://copyright.gov.in',
      '',
      '',
      '',
      'https://copyright.gov.in',
    ),
    ip(
      'trademarks',
      'Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)',
      'https://ipindia.gov.in',
      'cgoffice@nic.in',
      '',
      'https://www.linkedin.com/company/office-of-the-controller-general-of-patents-designs-and-trade-marks/',
      'https://ipindiaonline.gov.in',
    ),
    ip(
      'patents',
      'Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)',
      'https://ipindia.gov.in',
      'cgoffice@nic.in',
      '',
      'https://www.linkedin.com/company/office-of-the-controller-general-of-patents-designs-and-trade-marks/',
      'https://ipindiaonline.gov.in',
    ),
  ),
  JM: roster(
    ip(
      'copyright',
      'Jamaica Intellectual Property Office (JIPO) — copyright',
      'https://www.jipo.gov.jm',
      'info@jipo.gov.jm',
      '',
      '',
      'https://www.jipo.gov.jm',
    ),
    ip(
      'trademarks',
      'Jamaica Intellectual Property Office (JIPO)',
      'https://www.jipo.gov.jm',
      'info@jipo.gov.jm',
      '',
      '',
      'https://www.jipo.gov.jm',
    ),
    ip(
      'patents',
      'Jamaica Intellectual Property Office (JIPO)',
      'https://www.jipo.gov.jm',
      'info@jipo.gov.jm',
      '',
      '',
      'https://www.jipo.gov.jm',
    ),
  ),
  KE: roster(
    ip(
      'copyright',
      'Kenya Copyright Board (KECOBO)',
      'https://www.copyright.go.ke',
      'info@copyright.go.ke',
      'https://x.com/KECOBO',
      'https://www.linkedin.com/company/kenya-copyright-board/',
      'https://www.copyright.go.ke',
    ),
    ip(
      'trademarks',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
    ip(
      'patents',
      'Kenya Industrial Property Institute (KIPI)',
      'https://www.kipi.go.ke',
      'info@kipi.go.ke',
      'https://x.com/KIPI_Kenya',
      'https://www.linkedin.com/company/kenya-industrial-property-institute/',
      'https://www.kipi.go.ke',
    ),
  ),
  KI: roster(
    ip(
      'copyright',
      'Ministry of Commerce, Industry and Cooperatives (Kiribati) — intellectual property — copyright',
      'https://www.mcic.gov.ki',
      '',
      '',
      '',
      'https://www.mcic.gov.ki',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Cooperatives (Kiribati) — intellectual property',
      'https://www.mcic.gov.ki',
      '',
      '',
      '',
      'https://www.mcic.gov.ki',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Cooperatives (Kiribati) — intellectual property',
      'https://www.mcic.gov.ki',
      '',
      '',
      '',
      'https://www.mcic.gov.ki',
    ),
  ),
  LS: roster(
    ip(
      'copyright',
      'Copyright Society of Lesotho (COSOLE)',
      'https://www.cosole.org.ls',
      '',
      '',
      '',
      'https://www.cosole.org.ls',
    ),
    ip(
      'trademarks',
      'Registrar General — Industrial Property (Lesotho)',
      'https://www.gov.ls',
      '',
      '',
      '',
      'https://www.gov.ls',
    ),
    ip(
      'patents',
      'Registrar General — Industrial Property (Lesotho)',
      'https://www.gov.ls',
      '',
      '',
      '',
      'https://www.gov.ls',
    ),
  ),
  MW: roster(
    ip(
      'copyright',
      'Copyright Society of Malawi (COSOMA)',
      'https://www.cosoma.mw',
      'info@cosoma.mw',
      '',
      '',
      'https://www.cosoma.mw',
    ),
    ip(
      'trademarks',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
    ip(
      'patents',
      'Department of the Registrar General — Industrial Property',
      'https://www.registrargeneral.gov.mw',
      'info@registrargeneral.gov.mw',
      '',
      '',
      'https://www.registrargeneral.gov.mw',
    ),
  ),
  MY: roster(
    ip(
      'copyright',
      'Intellectual Property Corporation of Malaysia (MyIPO) — copyright',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'trademarks',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
    ip(
      'patents',
      'Intellectual Property Corporation of Malaysia (MyIPO)',
      'https://www.myipo.gov.my',
      'myipo@myipo.gov.my',
      '',
      'https://www.linkedin.com/company/myipo/',
      'https://www.myipo.gov.my/en/apply-for-ip',
    ),
  ),
  MV: roster(
    ip(
      'copyright',
      'Maldives Intellectual Property Office — copyright',
      'https://www.ipmaldives.gov.mv',
      '',
      '',
      '',
      'https://www.ipmaldives.gov.mv',
    ),
    ip(
      'trademarks',
      'Maldives Intellectual Property Office',
      'https://www.ipmaldives.gov.mv',
      '',
      '',
      '',
      'https://www.ipmaldives.gov.mv',
    ),
    ip(
      'patents',
      'Maldives Intellectual Property Office',
      'https://www.ipmaldives.gov.mv',
      '',
      '',
      '',
      'https://www.ipmaldives.gov.mv',
    ),
  ),
  MT: roster(
    ip(
      'copyright',
      'Commerce Department — Intellectual Property (Malta) — copyright',
      'https://commerce.gov.mt',
      '',
      '',
      '',
      'https://commerce.gov.mt',
    ),
    ip(
      'trademarks',
      'Commerce Department — Intellectual Property (Malta)',
      'https://commerce.gov.mt',
      '',
      '',
      '',
      'https://commerce.gov.mt',
    ),
    ip(
      'patents',
      'Commerce Department — Intellectual Property (Malta)',
      'https://commerce.gov.mt',
      '',
      '',
      '',
      'https://commerce.gov.mt',
    ),
  ),
  MU: roster(
    ip(
      'copyright',
      'Mauritius Society of Authors (MASA)',
      'https://www.masa.mu',
      'info@masa.mu',
      '',
      '',
      'https://www.masa.mu',
    ),
    ip(
      'trademarks',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
    ip(
      'patents',
      'Industrial Property Office (IPO Mauritius)',
      'https://www.gov.mu',
      'ipo@gov.mu',
      '',
      '',
      'https://www.gov.mu',
    ),
  ),
  MZ: roster(
    ip(
      'copyright',
      'Instituto Nacional da Propriedade Intelectual (IPI) — copyright',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'trademarks',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
    ip(
      'patents',
      'Instituto Nacional da Propriedade Intelectual (IPI)',
      'https://www.ipi.gov.mz',
      'ipi@ipi.gov.mz',
      '',
      '',
      'https://www.ipi.gov.mz',
    ),
  ),
  NA: roster(
    ip(
      'copyright',
      'Namibian Society for Composers and Authors of Music (NAMCOS)',
      'https://www.namcos.org.na',
      'info@namcos.org.na',
      '',
      '',
      'https://www.namcos.org.na',
    ),
    ip(
      'trademarks',
      'Business and Intellectual Property Authority (BIPA)',
      'https://www.bipa.na',
      'info@bipa.na',
      '',
      'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
      'https://www.bipa.na',
    ),
    ip(
      'patents',
      'Business and Intellectual Property Authority (BIPA)',
      'https://www.bipa.na',
      'info@bipa.na',
      '',
      'https://www.linkedin.com/company/business-and-intellectual-property-authority/',
      'https://www.bipa.na',
    ),
  ),
  NR: roster(
    ip(
      'copyright',
      'Nauru — intellectual property (verify locally; no dedicated portal documented)',
      'https://www.nauru.gov.nr',
      '',
      '',
      '',
      'https://www.nauru.gov.nr',
    ),
    ip(
      'trademarks',
      'Nauru — intellectual property (verify locally)',
      'https://www.nauru.gov.nr',
      '',
      '',
      '',
      'https://www.nauru.gov.nr',
    ),
    ip(
      'patents',
      'Nauru — intellectual property (verify locally)',
      'https://www.nauru.gov.nr',
      '',
      '',
      '',
      'https://www.nauru.gov.nr',
    ),
  ),
  NZ: roster(
    ip(
      'copyright',
      'Manatū Taonga — Ministry for Culture and Heritage (Copyright)',
      'https://www.mch.govt.nz',
      'info@mch.govt.nz',
      '',
      '',
      'https://www.mch.govt.nz/copyright',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
    ip(
      'patents',
      'Intellectual Property Office of New Zealand (IPONZ)',
      'https://www.iponz.govt.nz',
      'iponz@mbie.govt.nz',
      '',
      'https://www.linkedin.com/company/intellectual-property-office-of-new-zealand/',
      'https://www.iponz.govt.nz/about-iponz/online-services',
    ),
  ),
  NG: roster(
    ip(
      'copyright',
      'Nigerian Copyright Commission (NCC)',
      'https://www.copyright.gov.ng',
      'info@copyright.gov.ng',
      'https://x.com/NCC_NG',
      'https://www.linkedin.com/company/nigerian-copyright-commission/',
      'https://www.copyright.gov.ng',
    ),
    ip(
      'trademarks',
      'Trademarks, Patents and Designs Registry (Federal Ministry of Industry, Trade and Investment)',
      'https://www.fmiti.gov.ng',
      'info@fmiti.gov.ng',
      '',
      '',
      'https://www.fmiti.gov.ng',
    ),
    ip(
      'patents',
      'Trademarks, Patents and Designs Registry (Federal Ministry of Industry, Trade and Investment)',
      'https://www.fmiti.gov.ng',
      'info@fmiti.gov.ng',
      '',
      '',
      'https://www.fmiti.gov.ng',
    ),
  ),
  PK: roster(
    ip(
      'copyright',
      'Intellectual Property Organization of Pakistan (IPO-Pakistan) — copyright',
      'https://ipo.gov.pk',
      'info@ipo.gov.pk',
      '',
      '',
      'https://ipo.gov.pk',
    ),
    ip(
      'trademarks',
      'Intellectual Property Organization of Pakistan (IPO-Pakistan)',
      'https://ipo.gov.pk',
      'info@ipo.gov.pk',
      '',
      '',
      'https://ipo.gov.pk',
    ),
    ip(
      'patents',
      'Intellectual Property Organization of Pakistan (IPO-Pakistan)',
      'https://ipo.gov.pk',
      'info@ipo.gov.pk',
      '',
      '',
      'https://ipo.gov.pk',
    ),
  ),
  PG: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Papua New Guinea (IPOPNG) — copyright',
      'https://www.ipopng.gov.pg',
      'info@ipopng.gov.pg',
      '',
      '',
      'https://www.ipopng.gov.pg',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Papua New Guinea (IPOPNG)',
      'https://www.ipopng.gov.pg',
      'info@ipopng.gov.pg',
      '',
      '',
      'https://www.ipopng.gov.pg',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Papua New Guinea (IPOPNG)',
      'https://www.ipopng.gov.pg',
      'info@ipopng.gov.pg',
      '',
      '',
      'https://www.ipopng.gov.pg',
    ),
  ),
  RW: roster(
    ip(
      'copyright',
      'Rwanda Society of Authors (RSAU)',
      'https://www.rsau.rw',
      'info@rsau.rw',
      '',
      '',
      'https://www.rsau.rw',
    ),
    ip(
      'trademarks',
      'Rwanda Development Board — Intellectual Property',
      'https://www.rdb.rw',
      'info@rdb.rw',
      'https://x.com/RwandaDevBoard',
      'https://www.linkedin.com/company/rwanda-development-board/',
      'https://www.rdb.rw',
    ),
    ip(
      'patents',
      'Rwanda Development Board — Intellectual Property',
      'https://www.rdb.rw',
      'info@rdb.rw',
      'https://x.com/RwandaDevBoard',
      'https://www.linkedin.com/company/rwanda-development-board/',
      'https://www.rdb.rw',
    ),
  ),
  KN: roster(
    ip(
      'copyright',
      'Ministry of Justice and Legal Affairs (Saint Kitts and Nevis) — copyright',
      'https://www.gov.kn',
      '',
      '',
      '',
      'https://www.gov.kn',
    ),
    ip(
      'trademarks',
      'Commerce and Intellectual Property Office (Saint Kitts and Nevis)',
      'https://www.gov.kn',
      '',
      '',
      '',
      'https://www.gov.kn',
    ),
    ip(
      'patents',
      'Commerce and Intellectual Property Office (Saint Kitts and Nevis)',
      'https://www.gov.kn',
      '',
      '',
      '',
      'https://www.gov.kn',
    ),
  ),
  LC: roster(
    ip(
      'copyright',
      'Ministry of Commerce — copyright (Saint Lucia)',
      'https://www.govt.lc',
      '',
      '',
      '',
      'https://www.govt.lc',
    ),
    ip(
      'trademarks',
      'Registry of Companies and Intellectual Property (Saint Lucia)',
      'https://www.govt.lc',
      '',
      '',
      '',
      'https://www.govt.lc',
    ),
    ip(
      'patents',
      'Registry of Companies and Intellectual Property (Saint Lucia)',
      'https://www.govt.lc',
      '',
      '',
      '',
      'https://www.govt.lc',
    ),
  ),
  VC: roster(
    ip(
      'copyright',
      'Ministry of Legal Affairs (Saint Vincent and the Grenadines) — copyright',
      'https://www.gov.vc',
      '',
      '',
      '',
      'https://www.gov.vc',
    ),
    ip(
      'trademarks',
      'Commerce and Intellectual Property Office (Saint Vincent and the Grenadines)',
      'https://www.gov.vc',
      '',
      '',
      '',
      'https://www.gov.vc',
    ),
    ip(
      'patents',
      'Commerce and Intellectual Property Office (Saint Vincent and the Grenadines)',
      'https://www.gov.vc',
      '',
      '',
      '',
      'https://www.gov.vc',
    ),
  ),
  WS: roster(
    ip(
      'copyright',
      'Ministry of Commerce, Industry and Labour (Samoa) — intellectual property — copyright',
      'https://www.mcil.gov.ws',
      '',
      '',
      '',
      'https://www.mcil.gov.ws',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce, Industry and Labour (Samoa) — intellectual property',
      'https://www.mcil.gov.ws',
      '',
      '',
      '',
      'https://www.mcil.gov.ws',
    ),
    ip(
      'patents',
      'Ministry of Commerce, Industry and Labour (Samoa) — intellectual property',
      'https://www.mcil.gov.ws',
      '',
      '',
      '',
      'https://www.mcil.gov.ws',
    ),
  ),
  SC: roster(
    ip(
      'copyright',
      'Seychelles Copyright Office (Ministry of Finance, National Planning and Trade)',
      'https://www.finance.gov.sc',
      '',
      '',
      '',
      'https://www.finance.gov.sc',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
    ip(
      'patents',
      'Intellectual Property Office (Seychelles)',
      'https://www.ipo.gov.sc',
      'info@ipo.gov.sc',
      '',
      '',
      'https://www.ipo.gov.sc',
    ),
  ),
  SL: roster(
    ip(
      'copyright',
      'Sierra Leone Copyright Office',
      'https://www.mic.gov.sl',
      '',
      '',
      '',
      'https://www.mic.gov.sl',
    ),
    ip(
      'trademarks',
      'National Intellectual Property Office of Sierra Leone (NIPOSL)',
      'https://www.niposl.gov.sl',
      'info@niposl.gov.sl',
      '',
      '',
      'https://www.niposl.gov.sl',
    ),
    ip(
      'patents',
      'National Intellectual Property Office of Sierra Leone (NIPOSL)',
      'https://www.niposl.gov.sl',
      'info@niposl.gov.sl',
      '',
      '',
      'https://www.niposl.gov.sl',
    ),
  ),
  SG: roster(
    ip(
      'copyright',
      'Intellectual Property Office of Singapore (IPOS) — copyright',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
    ip(
      'patents',
      'Intellectual Property Office of Singapore (IPOS)',
      'https://www.ipos.gov.sg',
      'ipos@ipos.gov.sg',
      'https://x.com/IPOSG',
      'https://www.linkedin.com/company/intellectual-property-office-of-singapore/',
      'https://www.ipos.gov.sg/eservices',
    ),
  ),
  SB: roster(
    ip(
      'copyright',
      'Solomon Islands Ministry of Commerce — intellectual property — copyright',
      'https://www.commerce.gov.sb',
      '',
      '',
      '',
      'https://www.commerce.gov.sb',
    ),
    ip(
      'trademarks',
      'Solomon Islands Ministry of Commerce — intellectual property',
      'https://www.commerce.gov.sb',
      '',
      '',
      '',
      'https://www.commerce.gov.sb',
    ),
    ip(
      'patents',
      'Solomon Islands Ministry of Commerce — intellectual property',
      'https://www.commerce.gov.sb',
      '',
      '',
      '',
      'https://www.commerce.gov.sb',
    ),
  ),
  ZA: roster(
    ip(
      'copyright',
      'Companies and Intellectual Property Commission (CIPC) — Copyright Tribunal liaison',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'trademarks',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
    ip(
      'patents',
      'Companies and Intellectual Property Commission (CIPC)',
      'https://www.cipc.co.za',
      'info@cipc.co.za',
      'https://x.com/the_cipc',
      'https://www.linkedin.com/company/cipc/',
      'https://www.cipc.co.za',
    ),
  ),
  LK: roster(
    ip(
      'copyright',
      'National Intellectual Property Office of Sri Lanka (NIPO) — copyright',
      'https://www.nipo.gov.lk',
      'info@nipo.gov.lk',
      '',
      '',
      'https://www.nipo.gov.lk',
    ),
    ip(
      'trademarks',
      'National Intellectual Property Office of Sri Lanka (NIPO)',
      'https://www.nipo.gov.lk',
      'info@nipo.gov.lk',
      '',
      '',
      'https://www.nipo.gov.lk',
    ),
    ip(
      'patents',
      'National Intellectual Property Office of Sri Lanka (NIPO)',
      'https://www.nipo.gov.lk',
      'info@nipo.gov.lk',
      '',
      '',
      'https://www.nipo.gov.lk',
    ),
  ),
  TZ: roster(
    ip(
      'copyright',
      'Copyright Society of Tanzania (COSOTA)',
      'https://www.cosota.go.tz',
      'info@cosota.go.tz',
      '',
      '',
      'https://www.cosota.go.tz',
    ),
    ip(
      'trademarks',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
    ip(
      'patents',
      'Business Registrations and Licensing Agency (BRELA)',
      'https://www.brela.go.tz',
      'info@brela.go.tz',
      '',
      'https://www.linkedin.com/company/brela/',
      'https://www.brela.go.tz',
    ),
  ),
  TG: oapiMember(
    ip(
      'copyright',
      'Office Togolais des Droits d\'Auteur et des Droits Voisins (OTDAV)',
      'https://www.otdav.tg',
      '',
      '',
      '',
      'https://www.otdav.tg',
    ),
  ),
  TO: roster(
    ip(
      'copyright',
      'Ministry of Commerce and Consumer Affairs (Tonga) — intellectual property — copyright',
      'https://www.commerce.gov.to',
      '',
      '',
      '',
      'https://www.commerce.gov.to',
    ),
    ip(
      'trademarks',
      'Ministry of Commerce and Consumer Affairs (Tonga) — intellectual property',
      'https://www.commerce.gov.to',
      '',
      '',
      '',
      'https://www.commerce.gov.to',
    ),
    ip(
      'patents',
      'Ministry of Commerce and Consumer Affairs (Tonga) — intellectual property',
      'https://www.commerce.gov.to',
      '',
      '',
      '',
      'https://www.commerce.gov.to',
    ),
  ),
  TT: roster(
    ip(
      'copyright',
      'Intellectual Property Office (Trinidad and Tobago) — copyright',
      'https://www.ipo.gov.tt',
      '',
      '',
      '',
      'https://www.ipo.gov.tt',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (Trinidad and Tobago)',
      'https://www.ipo.gov.tt',
      '',
      '',
      '',
      'https://www.ipo.gov.tt',
    ),
    ip(
      'patents',
      'Intellectual Property Office (Trinidad and Tobago)',
      'https://www.ipo.gov.tt',
      '',
      '',
      '',
      'https://www.ipo.gov.tt',
    ),
  ),
  TV: roster(
    ip(
      'copyright',
      'Tuvalu — intellectual property (verify locally; no dedicated portal documented)',
      'https://www.gov.tv',
      '',
      '',
      '',
      'https://www.gov.tv',
    ),
    ip(
      'trademarks',
      'Tuvalu — intellectual property (verify locally)',
      'https://www.gov.tv',
      '',
      '',
      '',
      'https://www.gov.tv',
    ),
    ip(
      'patents',
      'Tuvalu — intellectual property (verify locally)',
      'https://www.gov.tv',
      '',
      '',
      '',
      'https://www.gov.tv',
    ),
  ),
  UG: roster(
    ip(
      'copyright',
      'Uganda Registration Services Bureau — Copyright Registry',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
    ip(
      'trademarks',
      'Uganda Registration Services Bureau (URSB) — Industrial Property',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
    ip(
      'patents',
      'Uganda Registration Services Bureau (URSB) — Industrial Property',
      'https://www.ursb.go.ug',
      'info@ursb.go.ug',
      '',
      'https://www.linkedin.com/company/uganda-registration-services-bureau/',
      'https://www.ursb.go.ug',
    ),
  ),
  GB: roster(
    ip(
      'copyright',
      'Intellectual Property Office (UK) — copyright guidance',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'trademarks',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
    ip(
      'patents',
      'Intellectual Property Office (UK)',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
      'enquiries@ipo.gov.uk',
      'https://x.com/The_IPO',
      'https://www.linkedin.com/company/intellectual-property-office/',
      'https://www.gov.uk/government/organisations/intellectual-property-office',
    ),
  ),
  VU: roster(
    ip(
      'copyright',
      'Vanuatu Financial Services Commission — intellectual property — copyright',
      'https://www.vfsc.vu',
      '',
      '',
      '',
      'https://www.vfsc.vu',
    ),
    ip(
      'trademarks',
      'Vanuatu Financial Services Commission — intellectual property',
      'https://www.vfsc.vu',
      '',
      '',
      '',
      'https://www.vfsc.vu',
    ),
    ip(
      'patents',
      'Vanuatu Financial Services Commission — intellectual property',
      'https://www.vfsc.vu',
      '',
      '',
      '',
      'https://www.vfsc.vu',
    ),
  ),
  ZM: roster(
    ip(
      'copyright',
      'Copyright Society of Zambia (COSOZA)',
      'https://www.cosoza.org.zm',
      'info@cosoza.org.zm',
      '',
      '',
      'https://www.cosoza.org.zm',
    ),
    ip(
      'trademarks',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
    ip(
      'patents',
      'Patents and Companies Registration Agency (PACRA)',
      'https://www.pacra.org.zm',
      'info@pacra.org.zm',
      '',
      'https://www.linkedin.com/company/pacra/',
      'https://www.pacra.org.zm',
    ),
  ),
}
