import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'
import type { MainInternationalSeaport } from './types'

function seaport(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  customsEmail: string,
  customsWebsite: string,
  customsAddress: string,
  apiEndpoint = '',
): MainInternationalSeaport {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    customsOffice: {
      email: customsEmail,
      website: customsWebsite,
      address: customsAddress,
    },
  }
}

/**
 * Main international seaport per Commonwealth member state (coastal gateway or principal maritime access point).
 * Informational; verify URLs, handles, customs contacts, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const COMMONWEALTH_MAIN_INTERNATIONAL_SEAPORTS: Record<CommonwealthMemberIsoCode, MainInternationalSeaport> = {
  AG: seaport(
    'Port of St. John\'s',
    'https://www.antiguaport.com/',
    'info@antiguaport.com',
    'https://x.com/AntiguaPort',
    'https://www.instagram.com/antiguaport/',
    'https://www.linkedin.com/company/antigua-port-authority/',
    'customs@antigua.gov.ag',
    'https://www.customs.gov.ag',
    'Antigua and Barbuda Customs — Port of St. John\'s, St. John\'s, Antigua and Barbuda',
  ),
  AU: seaport(
    'Port of Melbourne',
    'https://www.portofmelbourne.com/',
    'info@portofmelbourne.com',
    'https://x.com/PortOfMelbourne',
    'https://www.instagram.com/portofmelbourne/',
    'https://www.linkedin.com/company/port-of-melbourne/',
    'customs@abf.gov.au',
    'https://www.abf.gov.au',
    'Australian Border Force — Port of Melbourne, Melbourne, Australia',
  ),
  BS: seaport(
    'Port of Nassau (Freeport)',
    'https://www.bahamasports.com/',
    'info@bahamasports.com',
    'https://x.com/BahamasPorts',
    'https://www.instagram.com/bahamasports/',
    'https://www.linkedin.com/company/bahamas-port-department/',
    'customs@bahamas.gov.bs',
    'https://www.bahamas.gov.bs/customs',
    'Bahamas Customs — Freeport, Grand Bahama, Bahamas',
  ),
  BD: seaport(
    'Port of Chittagong (Chattogram)',
    'https://www.cpa.gov.bd/',
    'info@cpa.gov.bd',
    'https://x.com/CPA_Bangladesh',
    'https://www.instagram.com/cpa_bangladesh/',
    'https://www.linkedin.com/company/chittagong-port-authority/',
    'customs@customs.gov.bd',
    'https://www.customs.gov.bd',
    'National Board of Revenue Customs — Chattogram Port, Chattogram, Bangladesh',
  ),
  BB: seaport(
    'Port of Bridgetown',
    'https://www.barbadosport.com/',
    'info@barbadosport.com',
    'https://x.com/BarbadosPort',
    'https://www.instagram.com/barbadosport/',
    'https://www.linkedin.com/company/barbados-port-inc/',
    'customs@bra.gov.bb',
    'https://www.bra.gov.bb',
    'Barbados Revenue Authority Customs — Port of Bridgetown, Bridgetown, Barbados',
  ),
  BZ: seaport(
    'Port of Belize City',
    'https://www.portbelize.com/',
    'info@portbelize.com',
    'https://x.com/PortBelize',
    'https://www.instagram.com/portbelize/',
    'https://www.linkedin.com/company/port-of-belize/',
    'customs@belize.gov.bz',
    'https://www.customs.gov.bz',
    'Belize Customs and Excise — Port of Belize City, Belize City, Belize',
  ),
  BW: seaport(
    'Port of Walvis Bay (primary maritime gateway; landlocked)',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'info@botswanacustoms.gov.bw',
    'https://www.botswanacustoms.gov.bw',
    'Botswana Unified Revenue Service — Gaborone, Botswana',
  ),
  BN: seaport(
    'Muara Port',
    'https://www.mtc.com.bn/',
    'info@mtc.com.bn',
    'https://x.com/MuaraPort',
    'https://www.instagram.com/muaraport/',
    'https://www.linkedin.com/company/muara-port/',
    'customs@rcs.gov.bn',
    'https://www.rcs.gov.bn',
    'Royal Customs and Excise Department — Muara Port, Muara, Brunei',
  ),
  CM: seaport(
    'Port of Douala',
    'https://www.otal.com/cameroon/port-of-douala',
    'contact@pad.cm',
    'https://x.com/PortDouala',
    'https://www.instagram.com/portdouala/',
    'https://www.linkedin.com/company/port-autonome-de-douala/',
    'douanes@finances.cm',
    'https://www.douanes.cm',
    'Direction Générale des Douanes — Port de Douala, Douala, Cameroon',
  ),
  CA: seaport(
    'Port of Vancouver',
    'https://www.portvancouver.com/',
    'info@portvancouver.com',
    'https://x.com/portvancouver',
    'https://www.instagram.com/portvancouver/',
    'https://www.linkedin.com/company/port-of-vancouver/',
    'cbcsa-client-services@cbsa-asfc.gc.ca',
    'https://www.cbsa-asfc.gc.ca',
    'Canada Border Services Agency — Port of Vancouver, Vancouver, Canada',
  ),
  CY: seaport(
    'Port of Limassol',
    'https://www.cyprusports.gov.cy/',
    'info@cyprusports.gov.cy',
    'https://x.com/CyprusPorts',
    'https://www.instagram.com/cyprusports/',
    'https://www.linkedin.com/company/cyprus-ports-authority/',
    'customs@mof.gov.cy',
    'https://www.mof.gov.cy/customs',
    'Cyprus Customs — Port of Limassol, Limassol, Cyprus',
  ),
  DM: seaport(
    'Port of Roseau',
    'https://www.dominicaports.dm/',
    'info@dominicaports.dm',
    'https://x.com/DominicaPorts',
    'https://www.instagram.com/dominicaport/',
    'https://www.linkedin.com/company/dominica-ports-authority/',
    'customs@customs.gov.dm',
    'https://www.customs.gov.dm',
    'Dominica Customs — Port of Roseau, Roseau, Dominica',
  ),
  SZ: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@sra.org.sz',
    'https://www.sra.org.sz',
    'Eswatini Revenue Service — Mbabane, Eswatini',
  ),
  FJ: seaport(
    'Port of Suva',
    'https://www.fijiports.com.fj/',
    'info@fijiports.com.fj',
    'https://x.com/FijiPorts',
    'https://www.instagram.com/fijiports/',
    'https://www.linkedin.com/company/fiji-ports-corporation/',
    'customs@fiji.gov.fj',
    'https://www.frcs.org.fj',
    'FRCS Customs — Port of Suva, Suva, Fiji',
  ),
  GA: seaport(
    'Port of Owendo',
    'https://www.otal.com/gabon/port-of-owendo',
    'contact@port-gentil.ga',
    'https://x.com/PortOwendo',
    'https://www.instagram.com/portowendo/',
    'https://www.linkedin.com/company/port-d-owendo/',
    'douanes@finances.ga',
    'https://www.douanes.ga',
    'Direction Générale des Douanes — Port d\'Owendo, Owendo, Gabon',
  ),
  GM: seaport(
    'Port of Banjul',
    'https://www.gambiaports.gm/',
    'info@gambiaports.gm',
    'https://x.com/GambiaPorts',
    'https://www.instagram.com/gambiaports/',
    'https://www.linkedin.com/company/gambia-ports-authority/',
    'info@gra.gm',
    'https://www.gra.gm',
    'Gambia Revenue Authority — Customs, Port of Banjul, Banjul, The Gambia',
  ),
  GH: seaport(
    'Port of Tema',
    'https://www.ghanaports.gov.gh/',
    'info@ghanaports.gov.gh',
    'https://x.com/GhanaPorts',
    'https://www.instagram.com/ghanaports/',
    'https://www.linkedin.com/company/ghana-ports-and-harbours-authority/',
    'info@gra.gov.gh',
    'https://www.gra.gov.gh',
    'Ghana Revenue Authority — Customs Division, Port of Tema, Tema, Ghana',
  ),
  GD: seaport(
    'Port of St. George\'s',
    'https://www.grenadaports.com/',
    'info@grenadaports.com',
    'https://x.com/GrenadaPorts',
    'https://www.instagram.com/grenadaports/',
    'https://www.linkedin.com/company/grenada-ports-authority/',
    'customs@customs.gov.gd',
    'https://www.customs.gov.gd',
    'Grenada Customs — Port of St. George\'s, St. George\'s, Grenada',
  ),
  GY: seaport(
    'Port of Georgetown',
    'https://www.guyanaports.com/',
    'info@guyanaports.com',
    'https://x.com/GuyanaPorts',
    'https://www.instagram.com/guyanaports/',
    'https://www.linkedin.com/company/guyana-ports-inc/',
    'customs@gra.gov.gy',
    'https://www.gra.gov.gy',
    'Guyana Revenue Authority Customs — Port of Georgetown, Georgetown, Guyana',
  ),
  IN: seaport(
    'Jawaharlal Nehru Port (Nhava Sheva)',
    'https://www.jnport.gov.in/',
    'info@jnport.gov.in',
    'https://x.com/JNPort',
    'https://www.instagram.com/jnport/',
    'https://www.linkedin.com/company/jawaharlal-nehru-port-trust/',
    'customs@cbic.gov.in',
    'https://www.cbic.gov.in',
    'Indian Customs — Jawaharlal Nehru Port, Navi Mumbai, India',
  ),
  JM: seaport(
    'Port of Kingston',
    'https://www.portjam.com/',
    'info@portjam.com',
    'https://x.com/PortAuthorityJM',
    'https://www.instagram.com/portauthorityjm/',
    'https://www.linkedin.com/company/port-authority-of-jamaica/',
    'customs@jacustoms.gov.jm',
    'https://www.jacustoms.gov.jm',
    'Jamaica Customs Agency — Port of Kingston, Kingston, Jamaica',
  ),
  KE: seaport(
    'Port of Mombasa',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@kra.go.ke',
    'https://www.kra.go.ke',
    'Kenya Revenue Authority — Customs Services, Port of Mombasa, Mombasa, Kenya',
  ),
  KI: seaport(
    'Port of Betio (Tarawa)',
    'https://www.mic.gov.ki/',
    'info@mic.gov.ki',
    'https://x.com/KiribatiPorts',
    'https://www.instagram.com/kiribatiports/',
    'https://www.linkedin.com/company/kiribati-ports/',
    'customs@mfed.gov.ki',
    'https://www.mfed.gov.ki',
    'Kiribati Customs — Port of Betio, Tarawa, Kiribati',
  ),
  LS: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@lra.org.ls',
    'https://www.lra.org.ls',
    'Lesotho Revenue Authority — Customs Division, Maseru, Lesotho',
  ),
  MW: seaport(
    'Port of Nacala (primary maritime gateway; landlocked)',
    'https://www.otal.com/mozambique/port-of-nacala',
    'info@cdi.mw',
    'https://x.com/CDI_Malawi',
    'https://www.instagram.com/cdi_malawi/',
    'https://www.linkedin.com/company/corridor-development-initiative/',
    'customs@mra.mw',
    'https://www.mra.mw',
    'Malawi Revenue Authority — Customs Division, Blantyre, Malawi',
  ),
  MY: seaport(
    'Port Klang',
    'https://www.pka.gov.my/',
    'info@pka.gov.my',
    'https://x.com/PortKlang',
    'https://www.instagram.com/portklang/',
    'https://www.linkedin.com/company/port-klang-authority/',
    'customs@customs.gov.my',
    'https://www.customs.gov.my',
    'Royal Malaysian Customs — Port Klang, Selangor, Malaysia',
  ),
  MV: seaport(
    'Port of Malé',
    'https://www.mpa.gov.mv/',
    'info@mpa.gov.mv',
    'https://x.com/MPA_Maldives',
    'https://www.instagram.com/mpa_maldives/',
    'https://www.linkedin.com/company/maldives-ports-limited/',
    'customs@customs.gov.mv',
    'https://www.customs.gov.mv',
    'Maldives Customs Service — Port of Malé, Malé, Maldives',
  ),
  MT: seaport(
    'Port of Marsaxlokk (Malta Freeport)',
    'https://www.maltafreeport.com/',
    'info@maltafreeport.com',
    'https://x.com/MaltaFreeport',
    'https://www.instagram.com/maltafreeport/',
    'https://www.linkedin.com/company/malta-freeport/',
    'customs@gov.mt',
    'https://cfr.gov.mt',
    'Malta Customs — Malta Freeport, Marsaxlokk, Malta',
  ),
  MU: seaport(
    'Port Louis',
    'https://www.mpa.mu/',
    'info@mpa.mu',
    'https://x.com/MPA_Mauritius',
    'https://www.instagram.com/mpa_mauritius/',
    'https://www.linkedin.com/company/mauritius-ports-authority/',
    'customs@mra.mu',
    'https://www.mra.mu',
    'Mauritius Revenue Authority — Customs, Port Louis, Mauritius',
  ),
  MZ: seaport(
    'Port of Maputo',
    'https://www.portmaputo.com/',
    'info@portmaputo.com',
    'https://x.com/PortMaputo',
    'https://www.instagram.com/portmaputo/',
    'https://www.linkedin.com/company/porto-de-maputo/',
    'aduaneira@at.gov.mz',
    'https://www.at.gov.mz',
    'Autoridade Tributária de Moçambique — Alfândega do Porto de Maputo, Maputo, Mozambique',
  ),
  NA: seaport(
    'Port of Walvis Bay',
    'https://www.namport.com.na/',
    'info@namport.com.na',
    'https://x.com/NamportNamibia',
    'https://www.instagram.com/namport_namibia/',
    'https://www.linkedin.com/company/namport/',
    'customs@namra.org.na',
    'https://www.namra.org.na',
    'Namibia Revenue Agency — Customs, Port of Walvis Bay, Walvis Bay, Namibia',
  ),
  NR: seaport(
    'Port of Nauru (Aiwo)',
    'https://www.nauruports.nr/',
    'info@nauruports.nr',
    '',
    '',
    'https://www.linkedin.com/company/nauru-ports/',
    'customs@customs.gov.nr',
    'https://www.customs.gov.nr',
    'Nauru Customs — Aiwo District, Nauru',
  ),
  NZ: seaport(
    'Port of Tauranga',
    'https://www.port-tauranga.co.nz/',
    'info@port-tauranga.co.nz',
    'https://x.com/PortofTauranga',
    'https://www.instagram.com/portoftauranga/',
    'https://www.linkedin.com/company/port-of-tauranga/',
    'customs@customs.govt.nz',
    'https://www.customs.govt.nz',
    'New Zealand Customs Service — Port of Tauranga, Tauranga, New Zealand',
  ),
  NG: seaport(
    'Port of Lagos (Apapa)',
    'https://www.npa.gov.ng/',
    'info@npa.gov.ng',
    'https://x.com/NPA_Nigeria',
    'https://www.instagram.com/npa_nigeria/',
    'https://www.linkedin.com/company/nigerian-ports-authority/',
    'customs@customs.gov.ng',
    'https://www.customs.gov.ng',
    'Nigeria Customs Service — Apapa Port, Lagos, Nigeria',
  ),
  PK: seaport(
    'Port of Karachi',
    'https://www.kpt.gov.pk/',
    'info@kpt.gov.pk',
    'https://x.com/KarachiPort',
    'https://www.instagram.com/karachiport/',
    'https://www.linkedin.com/company/karachi-port-trust/',
    'customs@customs.gov.pk',
    'https://www.fbr.gov.pk',
    'Pakistan Customs — Port of Karachi, Karachi, Pakistan',
  ),
  PG: seaport(
    'Port of Lae',
    'https://www.pngports.com.pg/',
    'info@pngports.com.pg',
    'https://x.com/PNGPorts',
    'https://www.instagram.com/pngports/',
    'https://www.linkedin.com/company/png-ports-corporation/',
    'customs@irc.gov.pg',
    'https://www.irc.gov.pg',
    'PNG Customs — Port of Lae, Lae, Papua New Guinea',
  ),
  RW: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@rra.gov.rw',
    'https://www.rra.gov.rw',
    'Rwanda Revenue Authority — Customs Services, Kigali, Rwanda',
  ),
  KN: seaport(
    'Port of Basseterre',
    'https://www.stkittsnevisports.com/',
    'info@stkittsnevisports.com',
    'https://x.com/StKittsPorts',
    'https://www.instagram.com/stkittsports/',
    'https://www.linkedin.com/company/st-kitts-nevis-ports/',
    'customs@customs.gov.kn',
    'https://www.customs.gov.kn',
    'St. Kitts and Nevis Customs — Port of Basseterre, Basseterre, Saint Kitts and Nevis',
  ),
  LC: seaport(
    'Port of Castries',
    'https://www.sluciaports.com/',
    'info@sluciaports.com',
    'https://x.com/StLuciaPorts',
    'https://www.instagram.com/stluciaports/',
    'https://www.linkedin.com/company/saint-lucia-ports-authority/',
    'customs@customs.gov.lc',
    'https://www.customs.gov.lc',
    'Saint Lucia Customs — Port of Castries, Castries, Saint Lucia',
  ),
  VC: seaport(
    'Port of Kingstown',
    'https://www.svgports.com/',
    'info@svgports.com',
    'https://x.com/SVGPorts',
    'https://www.instagram.com/svgports/',
    'https://www.linkedin.com/company/saint-vincent-ports/',
    'customs@customs.gov.vc',
    'https://www.customs.gov.vc',
    'Saint Vincent and the Grenadines Customs — Port of Kingstown, Kingstown, Saint Vincent and the Grenadines',
  ),
  WS: seaport(
    'Port of Apia',
    'https://www.samoaports.ws/',
    'info@samoaports.ws',
    'https://x.com/SamoaPorts',
    'https://www.instagram.com/samoaports/',
    'https://www.linkedin.com/company/samoa-ports-authority/',
    'customs@revenue.gov.ws',
    'https://www.revenue.gov.ws',
    'Samoa Revenue Authority Customs — Port of Apia, Apia, Samoa',
  ),
  SC: seaport(
    'Port Victoria',
    'https://www.spa.sc/',
    'info@spa.sc',
    'https://x.com/SPA_Seychelles',
    'https://www.instagram.com/spa_seychelles/',
    'https://www.linkedin.com/company/seychelles-ports-authority/',
    'customs@src.gov.sc',
    'https://www.src.gov.sc',
    'Seychelles Revenue Commission — Customs, Port Victoria, Mahé, Seychelles',
  ),
  SL: seaport(
    'Port of Freetown',
    'https://www.slpa.sl/',
    'info@slpa.sl',
    'https://x.com/SLPA_Freetown',
    'https://www.instagram.com/slpa_freetown/',
    'https://www.linkedin.com/company/sierra-leone-ports-authority/',
    'customs@nra.gov.sl',
    'https://www.nra.gov.sl',
    'National Revenue Authority — Customs, Port of Freetown, Freetown, Sierra Leone',
  ),
  SG: seaport(
    'Port of Singapore',
    'https://www.mpa.gov.sg/',
    'MPA_Enquiry@mpa.gov.sg',
    'https://x.com/Mpa_Singapore',
    'https://www.instagram.com/mpa_singapore/',
    'https://www.linkedin.com/company/maritime-and-port-authority-of-singapore/',
    'customs_support@customs.gov.sg',
    'https://www.customs.gov.sg',
    'Singapore Customs — PSA Singapore Terminals, Singapore',
  ),
  SB: seaport(
    'Port of Honiara',
    'https://www.sipa.com.sb/',
    'info@sipa.com.sb',
    'https://x.com/SolomonPorts',
    'https://www.instagram.com/solomonports/',
    'https://www.linkedin.com/company/solomon-ports/',
    'customs@customs.gov.sb',
    'https://www.customs.gov.sb',
    'Solomon Islands Customs — Port of Honiara, Honiara, Solomon Islands',
  ),
  ZA: seaport(
    'Port of Durban',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'customs@sars.gov.za',
    'https://www.sars.gov.za',
    'South African Revenue Service — Customs, Port of Durban, Durban, South Africa',
  ),
  LK: seaport(
    'Port of Colombo',
    'https://www.slpa.lk/',
    'info@slpa.lk',
    'https://x.com/SLPA_LK',
    'https://www.instagram.com/slpa_lk/',
    'https://www.linkedin.com/company/sri-lanka-ports-authority/',
    'customs@gov.lk',
    'https://www.customs.gov.lk',
    'Sri Lanka Customs — Port of Colombo, Colombo, Sri Lanka',
  ),
  TZ: seaport(
    'Port of Dar es Salaam',
    'https://www.tanzaniaports.com/',
    'info@tanzaniaports.com',
    'https://x.com/TanzaniaPorts',
    'https://www.instagram.com/tanzaniaports/',
    'https://www.linkedin.com/company/tanzania-ports-authority/',
    'customs@tra.go.tz',
    'https://www.tra.go.tz',
    'Tanzania Revenue Authority — Customs, Port of Dar es Salaam, Dar es Salaam, Tanzania',
  ),
  TG: seaport(
    'Port of Lomé',
    'https://www.portdelome.tg/',
    'contact@portdelome.tg',
    'https://x.com/PortLome',
    'https://www.instagram.com/portdelome/',
    'https://www.linkedin.com/company/port-autonome-de-lome/',
    'douanes@finances.tg',
    'https://www.douanes.tg',
    'Direction Générale des Douanes — Port de Lomé, Lomé, Togo',
  ),
  TO: seaport(
    'Port of Nuku\'alofa',
    'https://www.tongaports.to/',
    'info@tongaports.to',
    'https://x.com/TongaPorts',
    'https://www.instagram.com/tongaports/',
    'https://www.linkedin.com/company/tonga-ports-authority/',
    'customs@customs.gov.to',
    'https://www.customs.gov.to',
    'Tonga Customs — Port of Nuku\'alofa, Nuku\'alofa, Tonga',
  ),
  TT: seaport(
    'Port of Port of Spain',
    'https://www.patnt.com/',
    'info@patnt.com',
    'https://x.com/PATNT',
    'https://www.instagram.com/patnt/',
    'https://www.linkedin.com/company/port-authority-of-trinidad-and-tobago/',
    'customs@customs.gov.tt',
    'https://www.customs.gov.tt',
    'Trinidad and Tobago Customs — Port of Spain, Port of Spain, Trinidad and Tobago',
  ),
  TV: seaport(
    'Port of Funafuti',
    'https://www.tuvaluports.tv/',
    'info@tuvaluports.tv',
    '',
    '',
    'https://www.linkedin.com/company/tuvalu-ports/',
    'customs@customs.gov.tv',
    'https://www.customs.gov.tv',
    'Tuvalu Customs — Port of Funafuti, Funafuti, Tuvalu',
  ),
  UG: seaport(
    'Port of Mombasa (primary maritime gateway; landlocked)',
    'https://www.kpa.co.ke/',
    'info@kpa.co.ke',
    'https://x.com/Kenya_Ports',
    'https://www.instagram.com/kenya_ports/',
    'https://www.linkedin.com/company/kenya-ports-authority/',
    'info@ura.go.ug',
    'https://www.ura.go.ug',
    'Uganda Revenue Authority — Customs, Kampala, Uganda',
  ),
  GB: seaport(
    'Port of Felixstowe',
    'https://www.portoffelixstowe.co.uk/',
    'info@portoffelixstowe.co.uk',
    'https://x.com/PortofFelixstowe',
    'https://www.instagram.com/portoffelixstowe/',
    'https://www.linkedin.com/company/port-of-felixstowe/',
    'national.advice@hmrc.gov.uk',
    'https://www.gov.uk/government/organisations/hm-revenue-customs',
    'HMRC Border Force — Port of Felixstowe, Felixstowe, United Kingdom',
  ),
  VU: seaport(
    'Port Vila',
    'https://www.vanuatuports.vu/',
    'info@vanuatuports.vu',
    'https://x.com/VanuatuPorts',
    'https://www.instagram.com/vanuatuports/',
    'https://www.linkedin.com/company/vanuatu-ports/',
    'customs@customs.gov.vu',
    'https://www.customs.gov.vu',
    'Vanuatu Customs — Port Vila, Port Vila, Vanuatu',
  ),
  ZM: seaport(
    'Port of Durban (primary maritime gateway; landlocked)',
    'https://www.transnetnationalportsauthority.net/',
    'info@tnpa.co.za',
    'https://x.com/TNPA_Official',
    'https://www.instagram.com/tnpa_official/',
    'https://www.linkedin.com/company/transnet-national-ports-authority/',
    'info@zra.org.zm',
    'https://www.zra.org.zm',
    'Zambia Revenue Authority — Customs Division, Lusaka, Zambia',
  ),
}
