import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'
import type { MainExportCommodities } from './types'

function m(
  a: string,
  b: string,
  c: string,
  d: string,
  e: string,
  f: string,
  g: string,
): MainExportCommodities {
  return [a, b, c, d, e, f, g]
}

/**
 * Principal export commodities by ISO 3166-1 alpha-2 (informational; verify against
 * UN Comtrade / national statistics periodically).
 */
export const COMMONWEALTH_MAIN_EXPORT_COMMODITIES: Record<
  CommonwealthMemberIsoCode,
  MainExportCommodities
> = {
  AG: m(
    'Tourism services',
    'Passenger ships',
    'Rum',
    'Fruit',
    'Fish',
    'Bed linen',
    'Electronics',
  ),
  AU: m(
    'Iron ore',
    'Coal',
    'Natural gas',
    'Gold',
    'Beef',
    'Wheat',
    'Aluminium',
  ),
  BS: m(
    'Tourism services',
    'Refined petroleum',
    'Fish',
    'Rum',
    'Salt',
    'Aragonite',
    'Passenger ships',
  ),
  BD: m(
    'Garments',
    'Jute',
    'Leather goods',
    'Fish',
    'Home textiles',
    'Footwear',
    'Rice',
  ),
  BB: m(
    'Rum',
    'Sugar',
    'Tourism services',
    'Chemicals',
    'Electronics',
    'Fish',
    'Manufactured goods',
  ),
  BZ: m(
    'Sugar',
    'Bananas',
    'Citrus fruit',
    'Crude petroleum',
    'Fish',
    'Tourism services',
    'Papayas',
  ),
  BW: m(
    'Diamonds',
    'Copper ore',
    'Beef',
    'Carbonates',
    'Live cattle',
    'Machinery parts',
    'Salt',
  ),
  BN: m(
    'Crude petroleum',
    'Liquified natural gas',
    'Refined petroleum',
    'Chemicals',
    'Fish',
    'Garments',
    'Plastics',
  ),
  CM: m(
    'Crude petroleum',
    'Timber',
    'Cocoa',
    'Cotton',
    'Aluminum',
    'Coffee',
    'Bananas',
  ),
  CA: m(
    'Crude petroleum',
    'Automobiles',
    'Gold',
    'Wheat',
    'Lumber',
    'Aluminium',
    'Natural gas',
  ),
  CY: m(
    'Refined petroleum',
    'Cheese',
    'Packaged medicaments',
    'Fish',
    'Halloumi',
    'Potatoes',
    'Tourism services',
  ),
  DM: m(
    'Bananas',
    'Soap',
    'Tourism services',
    'Citrus fruit',
    'Vegetables',
    'Cocoa',
    'Manufactured goods',
  ),
  SZ: m(
    'Sugar',
    'Soft drink concentrates',
    'Cotton yarn',
    'Wood pulp',
    'Beef',
    'Citrus fruit',
    'Textiles',
  ),
  FJ: m(
    'Water',
    'Fish',
    'Sugar',
    'Gold',
    'Timber',
    'Garments',
    'Mineral water',
  ),
  GA: m(
    'Crude petroleum',
    'Manganese ore',
    'Timber',
    'Refined petroleum',
    'Uranium',
    'Gold',
    'Palm oil',
  ),
  GM: m(
    'Groundnuts',
    'Fish',
    'Cotton',
    'Timber',
    'Palm kernels',
    'Petroleum products',
    'Re-exported goods',
  ),
  GH: m(
    'Gold',
    'Crude petroleum',
    'Cocoa',
    'Cashew nuts',
    'Manganese ore',
    'Oil seeds',
    'Refined petroleum',
  ),
  GD: m(
    'Nutmeg',
    'Cocoa',
    'Fish',
    'Tourism services',
    'Mace',
    'Bananas',
    'Manufactured goods',
  ),
  GY: m(
    'Gold',
    'Rice',
    'Bauxite',
    'Sugar',
    'Shrimp',
    'Timber',
    'Aluminium ore',
  ),
  IN: m(
    'Refined petroleum',
    'Diamonds',
    'Pharmaceuticals',
    'Rice',
    'Machinery',
    'Iron and steel',
    'Cotton yarn',
  ),
  JM: m(
    'Alumina',
    'Bauxite',
    'Rum',
    'Coffee',
    'Tourism services',
    'Yam',
    'Mining products',
  ),
  KE: m(
    'Tea',
    'Cut flowers',
    'Coffee',
    'Refined petroleum',
    'Titanium ore',
    'Avocados',
    'Vegetables',
  ),
  KI: m(
    'Fish',
    'Copra',
    'Seaweed',
    'Coconut oil',
    'Tourism services',
    'Tuna',
    'Handicrafts',
  ),
  LS: m(
    'Diamonds',
    'Garments',
    'Wool',
    'Water',
    'Mohair',
    'Footwear',
    'Textiles',
  ),
  MW: m(
    'Tobacco',
    'Tea',
    'Sugar',
    'Legumes',
    'Coffee',
    'Nuts',
    'Cotton',
  ),
  MY: m(
    'Integrated circuits',
    'Palm oil',
    'Refined petroleum',
    'Liquified natural gas',
    'Rubber',
    'Natural gas',
    'Electrical machinery',
  ),
  MV: m(
    'Fish',
    'Tourism services',
    'Garments',
    'Coconut products',
    'Thresher shark meat',
    'Aircraft parts',
    'Re-exports',
  ),
  MT: m(
    'Refined petroleum',
    'Packaged medicaments',
    'Fish',
    'Integrated circuits',
    'Pharmaceuticals',
    'Electronics',
    'Tourism services',
  ),
  MU: m(
    'Fish',
    'Textiles',
    'Sugar',
    'Refined petroleum',
    'Jewelry',
    'Cut flowers',
    'Medical devices',
  ),
  MZ: m(
    'Coal',
    'Aluminum',
    'Natural gas',
    'Electrical energy',
    'Cashew nuts',
    'Prawns',
    'Tobacco',
  ),
  NA: m(
    'Diamonds',
    'Uranium',
    'Fish',
    'Zinc',
    'Gold',
    'Beef',
    'Salt',
  ),
  NR: m(
    'Phosphate',
    'Fish',
    'Tourism services',
    'Coconut products',
    'Passenger ships',
    'Handicrafts',
    'Re-exports',
  ),
  NZ: m(
    'Milk powder',
    'Meat',
    'Wood products',
    'Wine',
    'Honey',
    'Butter',
    'Fruit',
  ),
  NG: m(
    'Crude petroleum',
    'Natural gas',
    'Refined petroleum',
    'Cocoa',
    'Fertilizers',
    'Sesame seeds',
    'Gold',
  ),
  PK: m(
    'Textiles',
    'Rice',
    'Leather goods',
    'Cotton yarn',
    'Sports goods',
    'Sugar',
    'Cement',
  ),
  PG: m(
    'Liquified natural gas',
    'Gold',
    'Copper ore',
    'Petroleum',
    'Palm oil',
    'Logs',
    'Coffee',
  ),
  RW: m(
    'Gold',
    'Coffee',
    'Tea',
    'Tin',
    'Tantalum',
    'Tungsten',
    'Niobium',
  ),
  KN: m(
    'Electronics',
    'Tourism services',
    'Fish',
    'Passenger ships',
    'Rum',
    'Manufactured goods',
    'Financial services exports',
  ),
  LC: m(
    'Bananas',
    'Tourism services',
    'Beer',
    'Fish',
    'Electronics',
    'Cocoa',
    'Manufactured goods',
  ),
  VC: m(
    'Bananas',
    'Tourism services',
    'Arrowroot starch',
    'Fish',
    'Rum',
    'Manufactured goods',
    'Passenger ships',
  ),
  WS: m(
    'Fish',
    'Coconut oil',
    'Automotive parts',
    'Noni juice',
    'Tourism services',
    'Kava',
    'Beer',
  ),
  SC: m(
    'Fish',
    'Processed fish',
    'Petroleum re-exports',
    'Copra',
    'Cinnamon',
    'Canned tuna',
    'Tourism-linked goods',
  ),
  SL: m(
    'Iron ore',
    'Diamonds',
    'Rutile',
    'Cocoa',
    'Coffee',
    'Fish',
    'Timber',
  ),
  SG: m(
    'Integrated circuits',
    'Refined petroleum',
    'Machinery',
    'Pharmaceuticals',
    'Optical media',
    'Gold',
    'Gas turbines',
  ),
  SB: m(
    'Timber',
    'Fish',
    'Palm oil',
    'Copra',
    'Gold',
    'Tourism services',
    'Cocoa',
  ),
  ZA: m(
    'Platinum',
    'Gold',
    'Coal',
    'Iron ore',
    'Manganese ore',
    'Automobiles',
    'Citrus fruit',
  ),
  LK: m(
    'Tea',
    'Apparel',
    'Rubber',
    'Coconut products',
    'Spices',
    'Fish',
    'Gems',
  ),
  TZ: m(
    'Gold',
    'Cashew nuts',
    'Coffee',
    'Refined petroleum',
    'Cotton',
    'Tobacco',
    'Tea',
  ),
  TG: m(
    'Crude petroleum',
    'Re-exported goods',
    'Cocoa',
    'Phosphates',
    'Cotton',
    'Coffee',
    'Refined petroleum',
  ),
  TO: m(
    'Fish',
    'Squash',
    'Vanilla',
    'Coconut products',
    'Tourism services',
    'Root crops',
    'Handicrafts',
  ),
  TT: m(
    'Liquified natural gas',
    'Ammonia',
    'Methanol',
    'Iron and steel',
    'Petroleum products',
    'Chemicals',
    'Cocoa',
  ),
  TV: m(
    'Fish',
    'Copra',
    'Tourism services',
    'Postage stamps',
    'Handicrafts',
    'Passenger ships',
    'Re-exports',
  ),
  UG: m(
    'Coffee',
    'Gold',
    'Fish',
    'Tea',
    'Cotton',
    'Maize',
    'Cut flowers',
  ),
  GB: m(
    'Gold',
    'Cars',
    'Packaged medicaments',
    'Crude petroleum',
    'Gas turbines',
    'Scotch whisky',
    'Aircraft parts',
  ),
  VU: m(
    'Beef',
    'Copra',
    'Kava',
    'Tourism services',
    'Fish',
    'Cocoa',
    'Timber',
  ),
  ZM: m(
    'Copper',
    'Refined copper',
    'Cobalt',
    'Gold',
    'Tobacco',
    'Sugar',
    'Gemstones',
  ),
}
