import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'
import type { MainInternationalAirport } from './types'

/**
 * Main international airport per member (capital or primary commercial gateway).
 * Informational; verify URLs, handles, and API bases before production.
 */
export const COMMONWEALTH_MAIN_INTERNATIONAL_AIRPORTS: Record<CommonwealthMemberIsoCode, MainInternationalAirport> = {
  AG: {
    name: 'V.C. Bird International Airport (ANU)',
    website: 'https://www.antigua-barbuda.com/',
    email: 'info@ab.gov.ag',
    twitter: 'https://x.com/AntiguaAirport',
    instagram: 'https://www.instagram.com/antiguaairport/',
    linkedin: 'https://www.linkedin.com/company/vc-bird-international-airport/',
    apiEndpoint: '',
  },
  AU: {
    name: 'Sydney Kingsford Smith Airport (SYD)',
    website: 'https://www.sydneyairport.com.au/',
    email: 'info@sydneyairport.com.au',
    twitter: 'https://x.com/SydneyAirport',
    instagram: 'https://www.instagram.com/sydneyairport/',
    linkedin: 'https://www.linkedin.com/company/sydney-airport/',
    apiEndpoint: '',
  },
  BS: {
    name: 'Lynden Pindling International Airport (NAS)',
    website: 'https://www.nassaulpia.com/',
    email: 'info@nassaulpia.com',
    twitter: 'https://x.com/NassauAirport',
    instagram: 'https://www.instagram.com/nassauairport/',
    linkedin: 'https://www.linkedin.com/company/lynden-pindling-international-airport/',
    apiEndpoint: '',
  },
  BD: {
    name: 'Hazrat Shahjalal International Airport (DAC)',
    website: 'https://www.caab.gov.bd/',
    email: 'info@caab.gov.bd',
    twitter: 'https://x.com/CAAB_Official',
    instagram: 'https://www.instagram.com/caab_official/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-bangladesh/',
    apiEndpoint: '',
  },
  BB: {
    name: 'Grantley Adams International Airport (BGI)',
    website: 'https://www.gaabarbados.org/',
    email: 'info@gaabarbados.org',
    twitter: 'https://x.com/GAABarbados',
    instagram: 'https://www.instagram.com/gaabarbados/',
    linkedin: 'https://www.linkedin.com/company/grantley-adams-international-airport/',
    apiEndpoint: '',
  },
  BZ: {
    name: 'Philip S.W. Goldson International Airport (BZE)',
    website: 'https://www.pgial.com.bz/',
    email: 'info@pgial.com.bz',
    twitter: 'https://x.com/BZEAirport',
    instagram: 'https://www.instagram.com/bzeairport/',
    linkedin: 'https://www.linkedin.com/company/philip-sw-goldson-international-airport/',
    apiEndpoint: '',
  },
  BW: {
    name: 'Sir Seretse Khama International Airport (GBE)',
    website: 'https://www.caab.co.bw/',
    email: 'info@caab.co.bw',
    twitter: 'https://x.com/CAAB_Botswana',
    instagram: 'https://www.instagram.com/caab_botswana/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-of-botswana/',
    apiEndpoint: '',
  },
  BN: {
    name: 'Brunei International Airport (BWN)',
    website: 'https://www.bruneiair.com/',
    email: 'info@bruneiair.com',
    twitter: 'https://x.com/BruneiAirport',
    instagram: 'https://www.instagram.com/bruneiairport/',
    linkedin: 'https://www.linkedin.com/company/brunei-international-airport/',
    apiEndpoint: '',
  },
  CM: {
    name: 'Yaoundé Nsimalen International Airport (NSI)',
    website: 'https://www.aeroport-yaounde.cm/',
    email: 'info@aeroport-yaounde.cm',
    twitter: 'https://x.com/AeroportNSI',
    instagram: 'https://www.instagram.com/aeroportnsimalen/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-nsimalen/',
    apiEndpoint: '',
  },
  CA: {
    name: 'Toronto Pearson International Airport (YYZ)',
    website: 'https://www.torontopearson.com/',
    email: 'info@torontopearson.com',
    twitter: 'https://x.com/TorontoPearson',
    instagram: 'https://www.instagram.com/torontopearson/',
    linkedin: 'https://www.linkedin.com/company/toronto-pearson-international-airport/',
    apiEndpoint: '',
  },
  CY: {
    name: 'Larnaca International Airport (LCA)',
    website: 'https://www.hermesairports.com/',
    email: 'info@hermesairports.com',
    twitter: 'https://x.com/HermesAirports',
    instagram: 'https://www.instagram.com/hermesairports/',
    linkedin: 'https://www.linkedin.com/company/hermes-airports/',
    apiEndpoint: '',
  },
  DM: {
    name: 'Douglas-Charles Airport (DOM)',
    website: 'https://www.dominicaairport.com/',
    email: 'info@dominicaairport.com',
    twitter: 'https://x.com/DominicaAirport',
    instagram: 'https://www.instagram.com/dominicaairport/',
    linkedin: 'https://www.linkedin.com/company/douglas-charles-airport/',
    apiEndpoint: '',
  },
  SZ: {
    name: 'King Mswati III International Airport (SHO)',
    website: 'https://www.eswacaa.co.sz/',
    email: 'info@eswacaa.co.sz',
    twitter: 'https://x.com/Eswacaa',
    instagram: 'https://www.instagram.com/eswacaa/',
    linkedin: 'https://www.linkedin.com/company/eswacaa/',
    apiEndpoint: '',
  },
  FJ: {
    name: 'Nadi International Airport (NAN)',
    website: 'https://www.nadi-airport.com/',
    email: 'info@nadi-airport.com',
    twitter: 'https://x.com/NadiAirport',
    instagram: 'https://www.instagram.com/nadiairport/',
    linkedin: 'https://www.linkedin.com/company/nadi-international-airport/',
    apiEndpoint: '',
  },
  GA: {
    name: 'Libreville Leon M\'ba International Airport (LBV)',
    website: 'https://www.aeroport-libreville.ga/',
    email: 'contact@aeroport-libreville.ga',
    twitter: 'https://x.com/AeroportLBV',
    instagram: 'https://www.instagram.com/aeroportlibreville/',
    linkedin: 'https://www.linkedin.com/company/aeroport-leon-mba/',
    apiEndpoint: '',
  },
  GM: {
    name: 'Banjul International Airport (BJL)',
    website: 'https://www.gcaa.gm/',
    email: 'info@gcaa.gm',
    twitter: 'https://x.com/GCAA_Gambia',
    instagram: 'https://www.instagram.com/gcaa_gambia/',
    linkedin: 'https://www.linkedin.com/company/gambia-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GH: {
    name: 'Kotoka International Airport (ACC)',
    website: 'https://www.gcaa.com.gh/',
    email: 'info@gcaa.com.gh',
    twitter: 'https://x.com/GCAA_Ghana',
    instagram: 'https://www.instagram.com/gcaa_ghana/',
    linkedin: 'https://www.linkedin.com/company/ghana-civil-aviation-authority/',
    apiEndpoint: '',
  },
  GD: {
    name: 'Maurice Bishop International Airport (GND)',
    website: 'https://www.grenadaairports.com/',
    email: 'info@grenadaairports.com',
    twitter: 'https://x.com/GrenadaAirport',
    instagram: 'https://www.instagram.com/grenadaairport/',
    linkedin: 'https://www.linkedin.com/company/maurice-bishop-international-airport/',
    apiEndpoint: '',
  },
  GY: {
    name: 'Cheddi Jagan International Airport (GEO)',
    website: 'https://www.cjairport-gy.com/',
    email: 'info@cjairport-gy.com',
    twitter: 'https://x.com/GuyanaAirport',
    instagram: 'https://www.instagram.com/guyanaairport/',
    linkedin: 'https://www.linkedin.com/company/cheddi-jagan-international-airport/',
    apiEndpoint: '',
  },
  IN: {
    name: 'Indira Gandhi International Airport (DEL)',
    website: 'https://www.newdelhiairport.in/',
    email: 'feedback@delhiairport.com',
    twitter: 'https://x.com/DelhiAirport',
    instagram: 'https://www.instagram.com/delhiairport/',
    linkedin: 'https://www.linkedin.com/company/delhi-international-airport-limited/',
    apiEndpoint: '',
  },
  JM: {
    name: 'Norman Manley International Airport (KIN)',
    website: 'https://www.nmia.aero/',
    email: 'info@nmia.aero',
    twitter: 'https://x.com/NMIA_Airport',
    instagram: 'https://www.instagram.com/nmia_airport/',
    linkedin: 'https://www.linkedin.com/company/norman-manley-international-airport/',
    apiEndpoint: '',
  },
  KE: {
    name: 'Jomo Kenyatta International Airport (NBO)',
    website: 'https://www.kaa.go.ke/',
    email: 'info@kaa.go.ke',
    twitter: 'https://x.com/KenyaAirports',
    instagram: 'https://www.instagram.com/kenyaairports/',
    linkedin: 'https://www.linkedin.com/company/kenya-airports-authority/',
    apiEndpoint: '',
  },
  KI: {
    name: 'Bonriki International Airport (TRW)',
    website: 'https://www.aviation.gov.ki/',
    email: 'info@aviation.gov.ki',
    twitter: 'https://x.com/KiribatiAir',
    instagram: 'https://www.instagram.com/kiribatiair/',
    linkedin: 'https://www.linkedin.com/company/kiribati-aviation/',
    apiEndpoint: '',
  },
  LS: {
    name: 'Moshoeshoe I International Airport (MSU)',
    website: 'https://www.lac.org.ls/',
    email: 'info@lac.org.ls',
    twitter: 'https://x.com/LAC_Lesotho',
    instagram: 'https://www.instagram.com/lac_lesotho/',
    linkedin: 'https://www.linkedin.com/company/lesotho-airports-authority/',
    apiEndpoint: '',
  },
  MW: {
    name: 'Kamuzu International Airport (LLW)',
    website: 'https://www.dca.gov.mw/',
    email: 'info@dca.gov.mw',
    twitter: 'https://x.com/DCA_Malawi',
    instagram: 'https://www.instagram.com/dca_malawi/',
    linkedin: 'https://www.linkedin.com/company/department-of-civil-aviation-malawi/',
    apiEndpoint: '',
  },
  MY: {
    name: 'Kuala Lumpur International Airport (KUL)',
    website: 'https://www.klia.com.my/',
    email: 'info@klia.com.my',
    twitter: 'https://x.com/KLIA_Malaysia',
    instagram: 'https://www.instagram.com/klia_malaysia/',
    linkedin: 'https://www.linkedin.com/company/malaysia-airports/',
    apiEndpoint: '',
  },
  MV: {
    name: 'Velana International Airport (MLE)',
    website: 'https://www.maclonline.com/',
    email: 'info@macl.aero',
    twitter: 'https://x.com/MACL_Official',
    instagram: 'https://www.instagram.com/macl_official/',
    linkedin: 'https://www.linkedin.com/company/maldives-airports-company-limited/',
    apiEndpoint: '',
  },
  MT: {
    name: 'Malta International Airport (MLA)',
    website: 'https://www.maltairport.com/',
    email: 'info@maltairport.com',
    twitter: 'https://x.com/MaltaAirport',
    instagram: 'https://www.instagram.com/maltairport/',
    linkedin: 'https://www.linkedin.com/company/malta-international-airport/',
    apiEndpoint: '',
  },
  MU: {
    name: 'Sir Seewoosagur Ramgoolam International Airport (MRU)',
    website: 'https://www.airports.mu/',
    email: 'info@airports.mu',
    twitter: 'https://x.com/AirportsMauritius',
    instagram: 'https://www.instagram.com/airportsmauritius/',
    linkedin: 'https://www.linkedin.com/company/airports-of-mauritius-co-ltd/',
    apiEndpoint: '',
  },
  MZ: {
    name: 'Maputo International Airport (MPM)',
    website: 'https://www.aeroportos.co.mz/',
    email: 'info@aeroportos.co.mz',
    twitter: 'https://x.com/AeroportosMZ',
    instagram: 'https://www.instagram.com/aeroportosmz/',
    linkedin: 'https://www.linkedin.com/company/aeroportos-de-mocambique/',
    apiEndpoint: '',
  },
  NA: {
    name: 'Hosea Kutako International Airport (WDH)',
    website: 'https://www.airports.com.na/',
    email: 'info@airports.com.na',
    twitter: 'https://x.com/AirportsNamibia',
    instagram: 'https://www.instagram.com/airportsnamibia/',
    linkedin: 'https://www.linkedin.com/company/namibia-airports-company/',
    apiEndpoint: '',
  },
  NR: {
    name: 'Nauru International Airport (INU)',
    website: 'https://www.nauru.gov.nr/',
    email: 'info@nauru.gov.nr',
    twitter: 'https://x.com/NauruGov',
    instagram: 'https://www.instagram.com/naurugov/',
    linkedin: 'https://www.linkedin.com/company/republic-of-nauru/',
    apiEndpoint: '',
  },
  NZ: {
    name: 'Auckland Airport (AKL)',
    website: 'https://www.aucklandairport.co.nz/',
    email: 'info@aucklandairport.co.nz',
    twitter: 'https://x.com/AucklandAirport',
    instagram: 'https://www.instagram.com/aucklandairport/',
    linkedin: 'https://www.linkedin.com/company/auckland-airport/',
    apiEndpoint: '',
  },
  NG: {
    name: 'Murtala Muhammed International Airport (LOS)',
    website: 'https://www.faan.gov.ng/',
    email: 'info@faan.gov.ng',
    twitter: 'https://x.com/FAAN_Official',
    instagram: 'https://www.instagram.com/faan_official/',
    linkedin: 'https://www.linkedin.com/company/federal-airports-authority-of-nigeria/',
    apiEndpoint: '',
  },
  PK: {
    name: 'Jinnah International Airport (KHI)',
    website: 'https://www.karachiairport.com.pk/',
    email: 'info@karachiairport.com.pk',
    twitter: 'https://x.com/KarachiAirport',
    instagram: 'https://www.instagram.com/karachi_airport/',
    linkedin: 'https://www.linkedin.com/company/jinnah-international-airport/',
    apiEndpoint: '',
  },
  PG: {
    name: 'Jacksons International Airport (POM)',
    website: 'https://www.nac.com.pg/',
    email: 'info@nac.com.pg',
    twitter: 'https://x.com/NAC_PNG',
    instagram: 'https://www.instagram.com/nac_png/',
    linkedin: 'https://www.linkedin.com/company/national-airports-corporation-png/',
    apiEndpoint: '',
  },
  RW: {
    name: 'Kigali International Airport (KGL)',
    website: 'https://www.rcaa.gov.rw/',
    email: 'info@rcaa.gov.rw',
    twitter: 'https://x.com/RCAA_Rwanda',
    instagram: 'https://www.instagram.com/rcaa_rwanda/',
    linkedin: 'https://www.linkedin.com/company/rwanda-civil-aviation-authority/',
    apiEndpoint: '',
  },
  KN: {
    name: 'Robert L. Bradshaw International Airport (SKB)',
    website: 'https://www.stkittsskeairs.com/',
    email: 'info@stkittsskeairs.com',
    twitter: 'https://x.com/SKB_Airport',
    instagram: 'https://www.instagram.com/skb_airport/',
    linkedin: 'https://www.linkedin.com/company/robert-l-bradshaw-international-airport/',
    apiEndpoint: '',
  },
  LC: {
    name: 'Hewanorra International Airport (UVF)',
    website: 'https://www.slusha.com/',
    email: 'info@slusha.com',
    twitter: 'https://x.com/UVF_Airport',
    instagram: 'https://www.instagram.com/uvf_airport/',
    linkedin: 'https://www.linkedin.com/company/hewanorra-international-airport/',
    apiEndpoint: '',
  },
  VC: {
    name: 'Argyle International Airport (SVD)',
    website: 'https://www.svgairport.com/',
    email: 'info@svgairport.com',
    twitter: 'https://x.com/SVGAirport',
    instagram: 'https://www.instagram.com/svgairport/',
    linkedin: 'https://www.linkedin.com/company/argyle-international-airport/',
    apiEndpoint: '',
  },
  WS: {
    name: 'Faleolo International Airport (APW)',
    website: 'https://www.samoaairports.ws/',
    email: 'info@samoaairports.ws',
    twitter: 'https://x.com/SamoaAirports',
    instagram: 'https://www.instagram.com/samoaairports/',
    linkedin: 'https://www.linkedin.com/company/samoa-airports-authority/',
    apiEndpoint: '',
  },
  SC: {
    name: 'Seychelles International Airport (SEZ)',
    website: 'https://www.scaa.sc/',
    email: 'info@scaa.sc',
    twitter: 'https://x.com/SCAA_Seychelles',
    instagram: 'https://www.instagram.com/scaa_seychelles/',
    linkedin: 'https://www.linkedin.com/company/seychelles-civil-aviation-authority/',
    apiEndpoint: '',
  },
  SL: {
    name: 'Freetown Lungi International Airport (FNA)',
    website: 'https://www.slac.gov.sl/',
    email: 'info@slac.gov.sl',
    twitter: 'https://x.com/SLAC_SierraLeone',
    instagram: 'https://www.instagram.com/slac_sierraleone/',
    linkedin: 'https://www.linkedin.com/company/sierra-leone-airports-authority/',
    apiEndpoint: '',
  },
  SG: {
    name: 'Singapore Changi Airport (SIN)',
    website: 'https://www.changiairport.com/',
    email: 'feedback@changiairport.com',
    twitter: 'https://x.com/ChangiAirport',
    instagram: 'https://www.instagram.com/changiairport/',
    linkedin: 'https://www.linkedin.com/company/changi-airport-group/',
    apiEndpoint: '',
  },
  SB: {
    name: 'Honiara International Airport (HIR)',
    website: 'https://www.siac.com.sb/',
    email: 'info@siac.com.sb',
    twitter: 'https://x.com/SIAC_Solomon',
    instagram: 'https://www.instagram.com/siac_solomon/',
    linkedin: 'https://www.linkedin.com/company/solomon-islands-airports-corporation/',
    apiEndpoint: '',
  },
  ZA: {
    name: 'O.R. Tambo International Airport (JNB)',
    website: 'https://www.airports.co.za/',
    email: 'info@airports.co.za',
    twitter: 'https://x.com/Airports_ZA',
    instagram: 'https://www.instagram.com/airports_co_za/',
    linkedin: 'https://www.linkedin.com/company/airports-company-south-africa/',
    apiEndpoint: '',
  },
  LK: {
    name: 'Bandaranaike International Airport (CMB)',
    website: 'https://www.airport.lk/',
    email: 'info@airport.lk',
    twitter: 'https://x.com/BandaranaikeAP',
    instagram: 'https://www.instagram.com/bandaranaikeap/',
    linkedin: 'https://www.linkedin.com/company/bandaranaike-international-airport/',
    apiEndpoint: '',
  },
  TZ: {
    name: 'Julius Nyerere International Airport (DAR)',
    website: 'https://www.taa.go.tz/',
    email: 'info@taa.go.tz',
    twitter: 'https://x.com/TAA_Tanzania',
    instagram: 'https://www.instagram.com/taa_tanzania/',
    linkedin: 'https://www.linkedin.com/company/tanzania-airports-authority/',
    apiEndpoint: '',
  },
  TG: {
    name: 'Lomé-Tokoin International Airport (LFW)',
    website: 'https://www.aeroport-lome.tg/',
    email: 'contact@aeroport-lome.tg',
    twitter: 'https://x.com/AeroportLFW',
    instagram: 'https://www.instagram.com/aeroportlfw/',
    linkedin: 'https://www.linkedin.com/company/aeroport-international-lome/',
    apiEndpoint: '',
  },
  TO: {
    name: 'Fua\'amotu International Airport (TBU)',
    website: 'https://www.tongaairports.com/',
    email: 'info@tongaairports.com',
    twitter: 'https://x.com/TongaAirports',
    instagram: 'https://www.instagram.com/tongaairports/',
    linkedin: 'https://www.linkedin.com/company/tonga-airports-limited/',
    apiEndpoint: '',
  },
  TT: {
    name: 'Piarco International Airport (POS)',
    website: 'https://www.tntairports.com/',
    email: 'info@tntairports.com',
    twitter: 'https://x.com/TNTAirports',
    instagram: 'https://www.instagram.com/tntairports/',
    linkedin: 'https://www.linkedin.com/company/trinidad-and-tobago-airports-authority/',
    apiEndpoint: '',
  },
  TV: {
    name: 'Funafuti International Airport (FUN)',
    website: 'https://www.tuvalu.tv/',
    email: 'info@tuvalu.tv',
    twitter: 'https://x.com/TuvaluGov',
    instagram: 'https://www.instagram.com/tuvalugov/',
    linkedin: 'https://www.linkedin.com/company/government-of-tuvalu/',
    apiEndpoint: '',
  },
  UG: {
    name: 'Entebbe International Airport (EBB)',
    website: 'https://www.caa.co.ug/',
    email: 'info@caa.co.ug',
    twitter: 'https://x.com/CAA_Uganda',
    instagram: 'https://www.instagram.com/caa_uganda/',
    linkedin: 'https://www.linkedin.com/company/civil-aviation-authority-uganda/',
    apiEndpoint: '',
  },
  GB: {
    name: 'Heathrow Airport (LHR)',
    website: 'https://www.heathrow.com/',
    email: 'customer.service@heathrow.com',
    twitter: 'https://x.com/HeathrowAirport',
    instagram: 'https://www.instagram.com/heathrowairport/',
    linkedin: 'https://www.linkedin.com/company/heathrow-airport/',
    apiEndpoint: '',
  },
  VU: {
    name: 'Bauerfield International Airport (VLI)',
    website: 'https://www.airports.vu/',
    email: 'info@airports.vu',
    twitter: 'https://x.com/VanuatuAirports',
    instagram: 'https://www.instagram.com/vanuatuairports/',
    linkedin: 'https://www.linkedin.com/company/airports-vanuatu/',
    apiEndpoint: '',
  },
  ZM: {
    name: 'Kenneth Kaunda International Airport (LUN)',
    website: 'https://www.zacl.co.zm/',
    email: 'info@zacl.co.zm',
    twitter: 'https://x.com/ZACL_Airports',
    instagram: 'https://www.instagram.com/zacl_airports/',
    linkedin: 'https://www.linkedin.com/company/zambia-airports-corporation-limited/',
    apiEndpoint: '',
  },
}
