import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'
import type { MainExportedElements } from './types'

function e(
  a: string,
  b: string,
  c: string,
  d: string,
  f: string,
  g: string,
  h: string,
): MainExportedElements {
  return [a, b, c, d, f, g, h]
}

/**
 * Seven principal exported chemical elements (mined or refined) by ISO 3166-1 alpha-2
 * for Commonwealth of Nations members (informational; verify against USGS Mineral Commodity
 * Summaries, BGS World Mineral Production, and UN Comtrade periodically).
 * Hydrocarbon-led economies carry `Carbon (C)` + `Hydrogen (H)`; semiconductor / wafer hubs
 * carry `Silicon (Si)`; smelter economies carry `Aluminum (Al)`.
 */
export const COMMONWEALTH_MAIN_EXPORTED_ELEMENTS: Record<CommonwealthMemberIsoCode, MainExportedElements> = {
  AG: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Chlorine (Cl)',
  ),
  AU: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Lithium (Li)',
    'Gold (Au)',
    'Copper (Cu)',
    'Nickel (Ni)',
  ),
  BS: e(
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Carbon (C)',
  ),
  BD: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Aluminum (Al)',
  ),
  BB: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sodium (Na)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
  ),
  BZ: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  BW: e(
    'Carbon (C)',
    'Copper (Cu)',
    'Nickel (Ni)',
    'Gold (Au)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Sulfur (S)',
  ),
  BN: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  CM: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Cobalt (Co)',
    'Manganese (Mn)',
    'Gold (Au)',
  ),
  CA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Potassium (K)',
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Gold (Au)',
    'Uranium (U)',
  ),
  CY: e(
    'Copper (Cu)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Silicon (Si)',
    'Aluminum (Al)',
    'Sodium (Na)',
  ),
  DM: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  SZ: e(
    'Carbon (C)',
    'Iron (Fe)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Sulfur (S)',
  ),
  FJ: e(
    'Gold (Au)',
    'Silver (Ag)',
    'Copper (Cu)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
    'Silicon (Si)',
  ),
  GA: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Manganese (Mn)',
    'Gold (Au)',
    'Iron (Fe)',
    'Niobium (Nb)',
    'Uranium (U)',
  ),
  GM: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Calcium (Ca)',
  ),
  GH: e(
    'Gold (Au)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Lithium (Li)',
    'Iron (Fe)',
  ),
  GD: e(
    'Silicon (Si)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  GY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Gold (Au)',
    'Aluminum (Al)',
    'Manganese (Mn)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  IN: e(
    'Iron (Fe)',
    'Aluminum (Al)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Copper (Cu)',
    'Manganese (Mn)',
    'Titanium (Ti)',
  ),
  JM: e(
    'Aluminum (Al)',
    'Gold (Au)',
    'Iron (Fe)',
    'Calcium (Ca)',
    'Silicon (Si)',
    'Magnesium (Mg)',
    'Sulfur (S)',
  ),
  KE: e(
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Sodium (Na)',
    'Fluorine (F)',
    'Gold (Au)',
    'Niobium (Nb)',
    'Calcium (Ca)',
  ),
  KI: e(
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Aluminum (Al)',
  ),
  LS: e(
    'Carbon (C)',
    'Silicon (Si)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
  ),
  MW: e(
    'Uranium (U)',
    'Niobium (Nb)',
    'Tantalum (Ta)',
    'Titanium (Ti)',
    'Iron (Fe)',
    'Gold (Au)',
    'Calcium (Ca)',
  ),
  MY: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Gold (Au)',
    'Silicon (Si)',
  ),
  MV: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  MT: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Carbon (C)',
    'Sulfur (S)',
  ),
  MU: e(
    'Calcium (Ca)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sodium (Na)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  MZ: e(
    'Aluminum (Al)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Gold (Au)',
    'Iron (Fe)',
  ),
  NA: e(
    'Uranium (U)',
    'Carbon (C)',
    'Copper (Cu)',
    'Zinc (Zn)',
    'Gold (Au)',
    'Lithium (Li)',
    'Lead (Pb)',
  ),
  NR: e(
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Sulfur (S)',
    'Aluminum (Al)',
  ),
  NZ: e(
    'Gold (Au)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Carbon (C)',
    'Silver (Ag)',
    'Hydrogen (H)',
    'Titanium (Ti)',
  ),
  NG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Tin (Sn)',
    'Tantalum (Ta)',
    'Niobium (Nb)',
    'Lead (Pb)',
    'Gold (Au)',
  ),
  PK: e(
    'Copper (Cu)',
    'Gold (Au)',
    'Chromium (Cr)',
    'Carbon (C)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  PG: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Nickel (Ni)',
    'Cobalt (Co)',
    'Carbon (C)',
    'Hydrogen (H)',
  ),
  RW: e(
    'Tantalum (Ta)',
    'Tin (Sn)',
    'Tungsten (W)',
    'Gold (Au)',
    'Niobium (Nb)',
    'Beryllium (Be)',
    'Iron (Fe)',
  ),
  KN: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  LC: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  VC: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  WS: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  SC: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  SL: e(
    'Iron (Fe)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Carbon (C)',
    'Aluminum (Al)',
    'Gold (Au)',
    'Manganese (Mn)',
  ),
  SG: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Silicon (Si)',
    'Sulfur (S)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Gold (Au)',
  ),
  SB: e(
    'Gold (Au)',
    'Aluminum (Al)',
    'Nickel (Ni)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Silicon (Si)',
    'Calcium (Ca)',
  ),
  ZA: e(
    'Platinum (Pt)',
    'Palladium (Pd)',
    'Gold (Au)',
    'Chromium (Cr)',
    'Manganese (Mn)',
    'Carbon (C)',
    'Iron (Fe)',
  ),
  LK: e(
    'Carbon (C)',
    'Aluminum (Al)',
    'Titanium (Ti)',
    'Zirconium (Zr)',
    'Phosphorus (P)',
    'Iron (Fe)',
    'Manganese (Mn)',
  ),
  TZ: e(
    'Gold (Au)',
    'Carbon (C)',
    'Nickel (Ni)',
    'Copper (Cu)',
    'Silver (Ag)',
    'Titanium (Ti)',
    'Niobium (Nb)',
  ),
  TG: e(
    'Phosphorus (P)',
    'Calcium (Ca)',
    'Iron (Fe)',
    'Manganese (Mn)',
    'Aluminum (Al)',
    'Silicon (Si)',
    'Carbon (C)',
  ),
  TO: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  TT: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Sulfur (S)',
    'Nitrogen (N)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Calcium (Ca)',
  ),
  TV: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  UG: e(
    'Gold (Au)',
    'Copper (Cu)',
    'Carbon (C)',
    'Hydrogen (H)',
    'Cobalt (Co)',
    'Iron (Fe)',
    'Phosphorus (P)',
  ),
  GB: e(
    'Carbon (C)',
    'Hydrogen (H)',
    'Lithium (Li)',
    'Aluminum (Al)',
    'Iron (Fe)',
    'Copper (Cu)',
    'Tin (Sn)',
  ),
  VU: e(
    'Calcium (Ca)',
    'Sodium (Na)',
    'Silicon (Si)',
    'Iron (Fe)',
    'Aluminum (Al)',
    'Sulfur (S)',
    'Magnesium (Mg)',
  ),
  ZM: e(
    'Copper (Cu)',
    'Cobalt (Co)',
    'Gold (Au)',
    'Manganese (Mn)',
    'Nickel (Ni)',
    'Beryllium (Be)',
    'Iron (Fe)',
  ),
}
