import type { CommonwealthMemberIsoCode } from './commonwealthMemberIsoCodes'
import type { SecuritiesExchangeCommission } from './types'

function sec(
  name: string,
  website: string,
  email: string,
  twitter: string,
  linkedin: string,
  formsUrl: string,
  apiEndpoint = '',
): SecuritiesExchangeCommission {
  return { name, website, email, twitter, linkedin, formsUrl, apiEndpoint }
}

/** Eastern Caribbean Securities Regulatory Commission — shared by AG, DM, GD, KN, LC, VC. */
const ECSRC = sec(
  'Eastern Caribbean Securities Regulatory Commission (ECSRC)',
  'https://www.ecsrc.com',
  'ecsrc@ecsrc.com',
  '',
  '',
  'https://www.ecsrc.com',
)

/**
 * Securities and exchange / capital-markets commission by ISO 3166-1 alpha-2 for Commonwealth of
 * Nations members in this module (informational; verify URLs, handles, forms portals, and API
 * bases before production use). Self-contained — no imports from other alliance modules.
 * `apiEndpoint` is almost always empty. Verify periodically:
 * https://www.iosco.org/about/membership/
 */
export const COMMONWEALTH_SECURITIES_EXCHANGE_COMMISSIONS: Record<
  CommonwealthMemberIsoCode,
  SecuritiesExchangeCommission
> = {
  AG: ECSRC,
  AU: sec(
    'Australian Securities and Investments Commission (ASIC)',
    'https://asic.gov.au',
    'enquiries@asic.gov.au',
    'https://x.com/ASICConnect',
    'https://www.linkedin.com/company/asic/',
    'https://asic.gov.au/online-services/',
  ),
  BS: sec(
    'Securities Commission of the Bahamas (SCB)',
    'https://www.scb.gov.bs',
    'info@scb.gov.bs',
    '',
    'https://www.linkedin.com/company/securities-commission-of-the-bahamas/',
    'https://www.scb.gov.bs',
  ),
  BD: sec(
    'Bangladesh Securities and Exchange Commission (BSEC)',
    'https://www.sec.gov.bd',
    'secsec@sec.gov.bd',
    '',
    'https://www.linkedin.com/company/bangladesh-securities-and-exchange-commission/',
    'https://www.sec.gov.bd',
  ),
  BB: sec(
    'Financial Services Commission Barbados (FSC)',
    'https://www.fsc.gov.bb',
    'info@fsc.gov.bb',
    '',
    '',
    'https://www.fsc.gov.bb',
  ),
  BZ: sec(
    'International Financial Services Commission Belize (IFSC)',
    'https://www.ifsc.gov.bz',
    'info@ifsc.gov.bz',
    '',
    '',
    'https://www.ifsc.gov.bz',
  ),
  BW: sec(
    'Non-Bank Financial Institutions Regulatory Authority (NBFIRA)',
    'https://www.nbfira.org.bw',
    'info@nbfira.org.bw',
    'https://x.com/NBFIRA',
    'https://www.linkedin.com/company/nbfira/',
    'https://www.nbfira.org.bw',
  ),
  BN: sec(
    'Autoriti Monetari Brunei Darussalam (AMBD) — capital-markets supervision',
    'https://www.ambd.gov.bn',
    'ambd@ambd.gov.bn',
    '',
    'https://www.linkedin.com/company/autoriti-monetari-brunei-darussalam/',
    'https://www.ambd.gov.bn',
  ),
  CM: sec(
    'Commission des Marchés Financiers du Cameroun (CMF)',
    'https://www.cmf.cm',
    'cmf@cmf.cm',
    '',
    'https://www.linkedin.com/company/commission-des-marchés-financiers-du-cameroun/',
    'https://www.cmf.cm',
  ),
  CA: sec(
    'Canadian Securities Administrators (CSA)',
    'https://www.securities-administrators.ca',
    'info@csa-acvm.ca',
    'https://x.com/CSA_News',
    'https://www.linkedin.com/company/canadian-securities-administrators/',
    'https://www.securities-administrators.ca',
  ),
  CY: sec(
    'Cyprus Securities and Exchange Commission (CySEC)',
    'https://www.cysec.gov.cy',
    'cysec@cysec.gov.cy',
    'https://x.com/CySEC_official',
    'https://www.linkedin.com/company/cysec/',
    'https://www.cysec.gov.cy',
  ),
  DM: ECSRC,
  SZ: sec(
    'Financial Services Regulatory Authority Eswatini (FSRA)',
    'https://www.fsra.co.sz',
    'info@fsra.co.sz',
    '',
    '',
    'https://www.fsra.co.sz',
  ),
  FJ: sec(
    'Reserve Bank of Fiji (RBF) — capital-markets oversight (no dedicated SEC)',
    'https://www.rbf.gov.fj',
    'rbf@rbf.gov.fj',
    '',
    '',
    'https://www.rbf.gov.fj',
  ),
  GA: sec(
    'Commission de Surveillance du Marché Financier de l\'Afrique Centrale (COSUMAF)',
    'https://www.cosumaf.org',
    'cosumaf@cosumaf.org',
    '',
    '',
    'https://www.cosumaf.org',
  ),
  GM: sec(
    'Gambia — capital-markets oversight via Central Bank of The Gambia (no dedicated SEC)',
    'https://www.cbg.gm',
    'info@cbg.gm',
    '',
    '',
    'https://www.cbg.gm',
  ),
  GH: sec(
    'Securities and Exchange Commission Ghana (SEC Ghana)',
    'https://www.sec.gov.gh',
    'sec@sec.gov.gh',
    'https://x.com/SECGhana',
    'https://www.linkedin.com/company/securities-and-exchange-commission-ghana/',
    'https://www.sec.gov.gh',
  ),
  GD: ECSRC,
  GY: sec(
    'Guyana Securities Council (GSC)',
    'https://www.gsc.gov.gy',
    '',
    '',
    '',
    'https://www.gsc.gov.gy',
  ),
  IN: sec(
    'Securities and Exchange Board of India (SEBI)',
    'https://www.sebi.gov.in',
    'sebi@sebi.gov.in',
    'https://x.com/SEBI_India',
    'https://www.linkedin.com/company/securities-and-exchange-board-of-india/',
    'https://www.sebi.gov.in',
  ),
  JM: sec(
    'Financial Services Commission Jamaica (FSC Jamaica)',
    'https://www.fscjamaica.org',
    'info@fscjamaica.org',
    'https://x.com/FSCJamaica',
    'https://www.linkedin.com/company/financial-services-commission-jamaica/',
    'https://www.fscjamaica.org',
  ),
  KE: sec(
    'Capital Markets Authority Kenya (CMA Kenya)',
    'https://www.cma.or.ke',
    'cma@cma.or.ke',
    'https://x.com/CMA_Kenya',
    'https://www.linkedin.com/company/capital-markets-authority-kenya/',
    'https://www.cma.or.ke',
  ),
  KI: sec(
    'Kiribati — capital-markets oversight via Ministry of Finance (no dedicated SEC)',
    'https://www.mfed.gov.ki',
    '',
    '',
    '',
    'https://www.mfed.gov.ki',
  ),
  LS: sec(
    'Lesotho — capital-markets oversight via Central Bank of Lesotho (no dedicated SEC)',
    'https://www.centralbank.org.ls',
    'info@centralbank.org.ls',
    '',
    '',
    'https://www.centralbank.org.ls',
  ),
  MW: sec(
    'Reserve Bank of Malawi — Capital Markets Unit (no separate SEC)',
    'https://www.rbm.mw',
    'info@rbm.mw',
    '',
    '',
    'https://www.rbm.mw',
  ),
  MY: sec(
    'Securities Commission Malaysia (SC)',
    'https://www.sc.com.my',
    'sc@sc.com.my',
    'https://x.com/SC_Malaysia',
    'https://www.linkedin.com/company/securities-commission-malaysia/',
    'https://www.sc.com.my',
  ),
  MV: sec(
    'Maldives Capital Market Development Authority (CMDA)',
    'https://www.cmda.gov.mv',
    'info@cmda.gov.mv',
    '',
    '',
    'https://www.cmda.gov.mv',
  ),
  MT: sec(
    'Malta Financial Services Authority (MFSA)',
    'https://www.mfsa.mt',
    'communications@mfsa.mt',
    'https://x.com/MFSAMalta',
    'https://www.linkedin.com/company/malta-financial-services-authority/',
    'https://www.mfsa.mt',
  ),
  MU: sec(
    'Financial Services Commission Mauritius (FSC)',
    'https://www.fscmauritius.org',
    'fscmauritius@fscmauritius.org',
    'https://x.com/FSCMauritius',
    'https://www.linkedin.com/company/financial-services-commission-mauritius/',
    'https://www.fscmauritius.org',
  ),
  MZ: sec(
    'Comissão de Valores Mobiliários de Moçambique (CVM)',
    'https://www.cvm.gov.mz',
    'geral@cvm.gov.mz',
    '',
    '',
    'https://www.cvm.gov.mz',
  ),
  NA: sec(
    'Namibia Financial Institutions Supervisory Authority (NAMFISA)',
    'https://www.namfisa.com.na',
    'enquiries@namfisa.com.na',
    'https://x.com/NAMFISA_NA',
    'https://www.linkedin.com/company/namfisa/',
    'https://www.namfisa.com.na',
  ),
  NR: sec(
    'Nauru — capital-markets oversight via Republic of Nauru Finance Corporation (no dedicated SEC)',
    'https://www.naurugov.nr',
    '',
    '',
    '',
    'https://www.naurugov.nr',
  ),
  NZ: sec(
    'Financial Markets Authority (FMA New Zealand)',
    'https://www.fma.govt.nz',
    'info@fma.govt.nz',
    'https://x.com/FMANZgov',
    'https://www.linkedin.com/company/financial-markets-authority/',
    'https://www.fma.govt.nz',
  ),
  NG: sec(
    'Securities and Exchange Commission Nigeria (SEC Nigeria)',
    'https://www.sec.gov.ng',
    'sec@sec.gov.ng',
    'https://x.com/SECNigeria',
    'https://www.linkedin.com/company/securities-and-exchange-commission-nigeria/',
    'https://www.sec.gov.ng',
  ),
  PK: sec(
    'Securities and Exchange Commission of Pakistan (SECP)',
    'https://www.secp.gov.pk',
    'info@secp.gov.pk',
    'https://x.com/SECP_Pakistan',
    'https://www.linkedin.com/company/secp/',
    'https://www.secp.gov.pk',
  ),
  PG: sec(
    'Securities Commission of Papua New Guinea (SCPNG)',
    'https://www.scpng.gov.pg',
    'info@scpng.gov.pg',
    '',
    '',
    'https://www.scpng.gov.pg',
  ),
  RW: sec(
    'Capital Markets Authority Rwanda (CMA Rwanda)',
    'https://www.cma.rw',
    'info@cma.rw',
    'https://x.com/CMA_Rwanda',
    'https://www.linkedin.com/company/capital-markets-authority-rwanda/',
    'https://www.cma.rw',
  ),
  KN: ECSRC,
  LC: ECSRC,
  VC: ECSRC,
  WS: sec(
    'Central Bank of Samoa — capital-markets oversight (no dedicated SEC)',
    'https://www.centralbank.gov.ws',
    'cbs@centralbank.gov.ws',
    '',
    '',
    'https://www.centralbank.gov.ws',
  ),
  SC: sec(
    'Financial Services Authority Seychelles (FSA)',
    'https://www.fsaseychelles.sc',
    'fsaseychelles@fsaseychelles.sc',
    '',
    'https://www.linkedin.com/company/financial-services-authority-seychelles/',
    'https://www.fsaseychelles.sc',
  ),
  SL: sec(
    'Sierra Leone — capital-markets oversight via Bank of Sierra Leone (no dedicated SEC)',
    'https://www.bsl.gov.sl',
    'info@bsl.gov.sl',
    '',
    '',
    'https://www.bsl.gov.sl',
  ),
  SG: sec(
    'Monetary Authority of Singapore (MAS)',
    'https://www.mas.gov.sg',
    'contact_MAS@mas.gov.sg',
    'https://x.com/mas_sg',
    'https://www.linkedin.com/company/monetary-authority-of-singapore/',
    'https://www.mas.gov.sg',
  ),
  SB: sec(
    'Central Bank of Solomon Islands — capital-markets oversight (no dedicated SEC)',
    'https://www.cbsi.com.sb',
    'info@cbsi.com.sb',
    '',
    '',
    'https://www.cbsi.com.sb',
  ),
  ZA: sec(
    'Financial Sector Conduct Authority (FSCA South Africa)',
    'https://www.fsca.co.za',
    'info@fsca.co.za',
    'https://x.com/theFSCA_ZA',
    'https://www.linkedin.com/company/financial-sector-conduct-authority/',
    'https://www.fsca.co.za',
  ),
  LK: sec(
    'Securities and Exchange Commission of Sri Lanka (SEC Sri Lanka)',
    'https://www.sec.gov.lk',
    'info@sec.gov.lk',
    'https://x.com/SECSriLanka',
    'https://www.linkedin.com/company/securities-and-exchange-commission-of-sri-lanka/',
    'https://www.sec.gov.lk',
  ),
  TZ: sec(
    'Capital Markets and Securities Authority Tanzania (CMSA)',
    'https://www.cmsa.go.tz',
    'cmsa@cmsa.go.tz',
    'https://x.com/CMSATanzania',
    'https://www.linkedin.com/company/capital-markets-and-securities-authority-tanzania/',
    'https://www.cmsa.go.tz',
  ),
  TG: sec(
    'Conseil Régional de l\'Épargne Publique et des Marchés Financiers (CREPMF)',
    'https://www.crepmf.org',
    'crepmf@crepmf.org',
    '',
    'https://www.linkedin.com/company/crepmf/',
    'https://www.crepmf.org',
  ),
  TO: sec(
    'National Reserve Bank of Tonga — capital-markets oversight (no dedicated SEC)',
    'https://www.reservebank.to',
    'nrbt@reservebank.to',
    '',
    '',
    'https://www.reservebank.to',
  ),
  TT: sec(
    'Trinidad and Tobago Securities and Exchange Commission (TTSEC)',
    'https://www.ttsec.org.tt',
    'info@ttsec.org.tt',
    'https://x.com/TTSECtt',
    'https://www.linkedin.com/company/ttsec/',
    'https://www.ttsec.org.tt',
  ),
  TV: sec(
    'Tuvalu — capital-markets oversight via National Bank of Tuvalu (no dedicated SEC)',
    'https://www.tuvalu.tv',
    '',
    '',
    '',
    'https://www.tuvalu.tv',
  ),
  UG: sec(
    'Capital Markets Authority Uganda (CMA Uganda)',
    'https://www.cmauganda.co.ug',
    'cma@cmauganda.co.ug',
    'https://x.com/CMAUganda',
    'https://www.linkedin.com/company/capital-markets-authority-uganda/',
    'https://www.cmauganda.co.ug',
  ),
  GB: sec(
    'Financial Conduct Authority (FCA United Kingdom)',
    'https://www.fca.org.uk',
    'consumer.queries@fca.org.uk',
    'https://x.com/TheFCA',
    'https://www.linkedin.com/company/financial-conduct-authority/',
    'https://www.fca.org.uk',
  ),
  VU: sec(
    'Vanuatu Financial Services Commission (VFSC)',
    'https://www.vfsc.vu',
    'info@vfsc.vu',
    '',
    '',
    'https://www.vfsc.vu',
  ),
  ZM: sec(
    'Securities and Exchange Commission Zambia (SEC Zambia)',
    'https://www.sec.gov.zm',
    'info@sec.gov.zm',
    'https://x.com/SECZambia',
    'https://www.linkedin.com/company/securities-and-exchange-commission-zambia/',
    'https://www.sec.gov.zm',
  ),
}
