import type { CorporationFormationOffice } from './types'
import type { EccasMemberIsoCode } from './eccasMemberIsoCodes'

function office(
  name: string,
  phone: string,
  address: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  formsUrl: string,
  checklistsUrl: string,
  registrationNumberLabel: string,
): CorporationFormationOffice {
  return {
    name,
    phone,
    address,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    formsUrl,
    checklistsUrl,
    registrationNumberLabel,
  }
}

/**
 * National corporation / company formation office per ECCAS partner state.
 * Informational; verify phone numbers, addresses, filing portals, checklists, social handles,
 * and registration-number taxonomy before production. Self-contained — no imports from other alliance modules.
 */
export const ECCAS_CORPORATION_FORMATION_OFFICES: Record<EccasMemberIsoCode, CorporationFormationOffice> = {
  AO:   office(
    'Guiche Unico da Empresa (GUE) Angola',
    '+244 222 331 251',
    'Largo da Maianga, Edificio One Metropolis, Luanda, Angola',
    'https://gue.gov.ao',
    'geral@gue.gov.ao',
    '',
    '',
    '',
    'https://gue.gov.ao/ao/servicos/criacao-de-empresas',
    'https://gue.gov.ao/ao/servicos/requisitos',
    'Numero de Identificacao de Pessoa Coletiva (NIF)',
  ),
  BI:   office(
    'Agence de Developpement du Burundi (ADB) - Guichet Unique',
    '+257 22 27 90 00',
    'Avenue du Large, Immeuble Old East, Bujumbura, Burundi',
    'https://investburundi.bi',
    'info@investburundi.bi',
    '',
    '',
    '',
    'https://investburundi.bi/guichet-unique',
    'https://investburundi.bi/procedures-de-creation',
    'Numero RCCM',
  ),
  CM:   office(
    'Centre de Formalites de Creation d\'Entreprise (CFCE Cameroun)',
    '+237 233 42 59 59',
    'Immeuble MAGZI, Yaounde, Cameroon',
    'https://www.apme.cm',
    'cfce@apme.cm',
    '',
    '',
    'https://www.linkedin.com/company/apme-cameroun/',
    'https://www.apme.cm/cfce',
    'https://www.apme.cm/cfce/check-list',
    'Numero RCCM',
  ),
  CF:   office(
    'Guichet Unique de Formalites des Entreprises (RCA)',
    '+236 75 05 05 05',
    'Avenue de l\'Independance, Bangui, Central African Republic',
    'https://www.apica.cf',
    'contact@apica.cf',
    '',
    '',
    '',
    'https://www.apica.cf/creation-entreprise',
    'https://www.apica.cf/check-list',
    'Numero RCCM',
  ),
  TD:   office(
    'Agence Nationale des Investissements et des Exportations (ANIE Chad) - Guichet Unique',
    '+235 22 52 42 42',
    'Quartier Sabangali, N\'Djamena, Chad',
    'https://www.anie.td',
    'contact@anie.td',
    '',
    '',
    '',
    'https://www.anie.td/guichet-unique',
    'https://www.anie.td/guide-createur',
    'Numero RCCM',
  ),
  CD:   office(
    'Guichet Unique de Creation d\'Entreprise (GUCE DRC)',
    '+243 81 555 7000',
    'Immeuble Fickin, Boulevard du 30 Juin, Gombe, Kinshasa, DR Congo',
    'https://guichetunique.cd',
    'contact@guichetunique.cd',
    '',
    '',
    '',
    'https://guichetunique.cd/creation-dentreprise',
    'https://guichetunique.cd/pieces-a-fournir',
    'Numero RCCM',
  ),
  GQ:   office(
    'Ventanilla Unica Empresarial - Ministerio de Comercio (Equatorial Guinea)',
    '+240 333 09 50 00',
    'Avenida de la Independencia, Malabo, Equatorial Guinea',
    'https://www.guineaecuatorialpress.com',
    'comercio@guineaecuatorial-gob.com',
    '',
    '',
    '',
    'https://www.guineaecuatorialpress.com/noticias/ventanilla_unica_empresarial',
    '',
    'Numero de Registro Mercantil',
  ),
  GA:   office(
    'Agence Nationale de Promotion des Investissements du Gabon (ANPI-Gabon)',
    '+241 01 79 20 00',
    'Immeuble Arambo, Libreville, Gabon',
    'https://www.investingabon.ga',
    'contact@investingabon.ga',
    '',
    '',
    'https://www.linkedin.com/company/anpi-gabon/',
    'https://www.investingabon.ga/creer-mon-entreprise',
    'https://www.investingabon.ga/guide-createur',
    'Numero RCCM',
  ),
  CG:   office(
    'Centre de Formalites Administratives des Entreprises (CFE Congo)',
    '+242 06 665 77 77',
    'Avenue Amilcar Cabral, Brazzaville, Republic of the Congo',
    'https://cfe.cg',
    'contact@cfe.cg',
    '',
    '',
    '',
    'https://cfe.cg/creer-entreprise',
    'https://cfe.cg/guide-des-formalites',
    'Numero RCCM',
  ),
  ST:   office(
    'Guiche Unico de Empresas (Sao Tome and Principe)',
    '+239 222 1515',
    'Avenida Marginal 12 de Julho, Sao Tome, Sao Tome and Principe',
    'https://www.guicheunico.st',
    'contacto@guicheunico.st',
    '',
    '',
    '',
    'https://www.guicheunico.st/abrir-empresa',
    'https://www.guicheunico.st/requisitos',
    'Numero de Matricula Comercial',
  ),
}
