import type { EccasMemberIsoCode } from './eccasMemberIsoCodes'
import type { DomesticPostService } from './types'

function post(
  name: string,
  website: string,
  email: string,
  twitter: string,
  instagram: string,
  linkedin: string,
  apiEndpoint: string,
  format: string,
  pattern: string,
  example: string,
  notes: string,
): DomesticPostService {
  return {
    name,
    website,
    email,
    twitter,
    instagram,
    linkedin,
    apiEndpoint,
    postalCodeSchema: { format, pattern, example, notes },
  }
}

/**
 * National designated postal operator and postal code schema per ECCAS partner state.
 * Informational; verify URLs, handles, schemas, and API bases before production.
 * Self-contained — no imports from other alliance modules.
 */
export const ECCAS_DOMESTIC_POST_SERVICES: Record<EccasMemberIsoCode, DomesticPostService> = {
  AO: post(
    'CTT Angola (Empresa Nacional de Correios)',
    'https://www.ctt.ao/',
    'geral@ctt.ao',
    'https://x.com/cttangola',
    'https://www.instagram.com/correiosdeangola/',
    'https://www.linkedin.com/company/correios-de-angola/',
    '',
    'none',
    '',
    '',
    'No national structured postcode; descriptive street addressing and P.O. Box common',
  ),
  BI: post(
    'Régie nationale des Postes du Burundi',
    'http://www.poste.bi/',
    'info@burundipost.bi',
    '',
    '',
    'https://www.linkedin.com/company/poste-burundi/',
    '',
    'none',
    '',
    '',
    'No national postcode; commune-based addressing',
  ),
  CM: post(
    'CAMPOST',
    'http://campost.cm/',
    'info@campost.cm',
    '',
    '',
    'https://www.linkedin.com/company/campost/',
    '',
    'none',
    '',
    '',
    'No national postcode; regional and P.O. Box routing',
  ),
  CF: post(
    'Office national des Postes RCA',
    'https://onet-rca.cf/',
    'contact@onet-rca.cf',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  TD: post(
    'La Poste Tchadienne',
    'https://www.laposte.td/',
    'contact@laposte.td',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-tchadienne/',
    '',
    'none',
    '',
    '',
    'No national postcode system',
  ),
  CD: post(
    'SCPT RDC (Services postaux)',
    'https://scpt.cd/',
    'info@postesrdc.cd',
    '',
    '',
    'https://www.linkedin.com/company/scpt-rdc/',
    '',
    'none',
    '',
    '',
    'No universal national postcode; commune and P.O. Box',
  ),
  GQ: post(
    'Correos de Guinea Ecuatorial',
    'https://www.correosgq.com/',
    'info@correosgq.com',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode; Malabo/Bata addressing',
  ),
  GA: post(
    'Gabon Poste EMS',
    'https://www.gabonpost.ga/',
    'infos@gpost.ga',
    '',
    '',
    'https://www.linkedin.com/company/gabon-poste/',
    '',
    'none',
    '',
    '',
    'No national postcode; Libreville/Port-Gentil district addressing',
  ),
  CG: post(
    'La Poste du Congo EMS',
    'http://laposte.cg/',
    'contact@lacongolaise.cg',
    '',
    '',
    'https://www.linkedin.com/company/la-poste-congo/',
    '',
    'none',
    '',
    '',
    'No national postcode; Brazzaville/Pointe-Noire district addressing',
  ),
  ST: post(
    'Correios de São Tomé e Príncipe',
    'https://www.correios.st/',
    'cac@correios.st',
    '',
    '',
    '',
    '',
    'none',
    '',
    '',
    'No national postcode',
  ),
}
